ProcessObject Class Reference
Main Modules Class List Namespace List Online
ProcessObject Class Reference
#include <T3D/gameBase/processList.h>
Classes
struct Link
Public Member Functions
ProcessObject ()
virtual ~ProcessObject ()
virtual void advanceTime (F32 dt)
Advances simulation time for animations.
virtual void clearProcessAfter ()
Clears the effects of a call to processAfter()
virtual ProcessObject * getAfterObject () const
Returns the object that this processes after.
virtual GameConnection * getControllingClient ()
This is really implemented in GameBase and is only here to avoid casts within ProcessList.
virtual U32 getPacketDataChecksum (GameConnection *conn)
This is really implemented in GameBase and is only here to avoid casts within ProcessList.
virtual void interpolateTick (F32 delta)
Interpolates between tick events.
bool isTicking () const
Returns true if this object processes ticks.
void plJoin (ProcessObject *)
void plLinkAfter (ProcessObject *)
void plLinkBefore (ProcessObject *)
void plUnlink ()
virtual void preprocessMove (Move *move)
Allow object to modify the Move before it is ticked or sent to the server.
virtual void processAfter (ProcessObject *obj)
Force this object to process after some other object.
virtual void processTick (const Move *move)
Processes a move event and updates object state once every 32 milliseconds.
void removeFromProcessList ()
Removes this object from the tick-processing list.
virtual void setProcessTick (bool t)
Set the status of tick processing.
Public Attributes
bool mIsGameBase
U32 mOrderGUID
Link mProcessLink
U32 mProcessTag
bool mProcessTick
Constructor & Destructor Documentation
ProcessObject::ProcessObject ()
virtual ProcessObject::~ProcessObject () inline virtual
References removeFromProcessList().
Member Function Documentation
virtual void ProcessObject::advanceTime (F32 dt) inline virtual
Advances simulation time for animations.
This is called every frame.
Parameters
dt Time since last advance call
Reimplemented in ShapeBase, Player, AITurretShape, Vehicle, PhysicsShape, RigidShape, WheeledVehicle, ParticleEmitter, Lightning, HoverVehicle, Projectile, FlyingVehicle, TurretShape, Splash, Explosion, Item, SpawnSphere, TSStatic, OpenVRTrackedObject, PhysicsDebris, Debris, Sun, LightBase, ProximityMine, Ribbon, ParticleEmitterNode, RibbonNode, and Entity.
Referenced by ProcessList::postTickSignal().
virtual void ProcessObject::clearProcessAfter () inline virtual
Clears the effects of a call to processAfter()
Reimplemented in SceneObject.
virtual ProcessObject* ProcessObject::getAfterObject () const inline virtual
Returns the object that this processes after.
See also
processAfter
Reimplemented in SceneObject.
virtual GameConnection* ProcessObject::getControllingClient () inline virtual
This is really implemented in GameBase and is only here to avoid casts within ProcessList.
Reimplemented in GameBase.
virtual U32 ProcessObject::getPacketDataChecksum (GameConnection * conn) inline virtual
This is really implemented in GameBase and is only here to avoid casts within ProcessList.
Reimplemented in GameBase.
virtual void ProcessObject::interpolateTick (F32 delta) inline virtual
Interpolates between tick events.
This takes place on the CLIENT ONLY.
Parameters
delta Time since last call to interpolate
Reimplemented in Player, Vehicle, PhysicsShape, RigidShape, Camera, Precipitation, Lightning, Projectile, Item, TurretShape, TSStatic, OpenVRTrackedObject, PhysicsDebris, LightBase, PathCamera, Ribbon, and Entity.
bool ProcessObject::isTicking () const inline
Returns true if this object processes ticks.
References mProcessTick.
void ProcessObject::plJoin (ProcessObject *)
void ProcessObject::plLinkAfter (ProcessObject *)
void ProcessObject::plLinkBefore (ProcessObject *)
void ProcessObject::plUnlink ()
Referenced by removeFromProcessList().
virtual void ProcessObject::preprocessMove (Move * move) inline virtual
Allow object to modify the Move before it is ticked or sent to the server.
This is only called for the control object on the client-side.
virtual void ProcessObject::processAfter (ProcessObject * obj) inline virtual
Force this object to process after some other object.
For example, a player mounted to a vehicle would want to process after the vehicle to prevent a visible 'lagging' from occurring when the vehicle moves. So the player would be set to processAfter(theVehicle).
Parameters
obj Object to process after
Reimplemented in SceneObject.
virtual void ProcessObject::processTick (const Move * move) inline virtual
Processes a move event and updates object state once every 32 milliseconds.
This takes place both on the client and server, every 32 milliseconds (1 tick).
See also
ProcessList
Parameters
move Move event corresponding to this tick, or NULL.
Reimplemented in ShapeBase, Player, GameBase, AITurretShape, Vehicle, PhysicsShape, RigidShape, Camera, ParticleEmitter, Precipitation, NavMesh, VolumetricFog, Lightning, Projectile, Item, TurretShape, Splash, Explosion, SpawnSphere, TSStatic, OpenVRTrackedObject, PhysicsDebris, Debris, NavPath, ProximityMine, PathCamera, Ribbon, Trigger, ParticleEmitterNode, TimeOfDay, RibbonNode, CollisionTrigger, StaticShape, Entity, and PhysicsForce.
void ProcessObject::removeFromProcessList () inline
Removes this object from the tick-processing list.
References plUnlink().
Referenced by ~ProcessObject().
virtual void ProcessObject::setProcessTick (bool t) inline virtual
Set the status of tick processing.
Set true to receive processTick, advanceTime, and interpolateTick calls.
See also
processTick
Parameters
t If true, tick processing is enabled.
Reimplemented in SceneObject.
References mProcessTick.
Member Data Documentation
bool ProcessObject::mIsGameBase
U32 ProcessObject::mOrderGUID
Link ProcessObject::mProcessLink
U32 ProcessObject::mProcessTag
bool ProcessObject::mProcessTick
Referenced by isTicking(), and setProcessTick().
Copyright © GarageGames, LLC. All Rights Reserved.