OrientedBox3F Class Reference
Main Modules Class List Namespace List Online
OrientedBox3F Class Reference
An oriented bounding box (OBB) described by a center point, three normalizes axis vectors, and half-extents along each of the axes.
#include <math/mOrientedBox.h>
Public Types
enum Axis {
RightVector,
ForwardVector,
UpVector
}
Public Types inherited from BoxBase
enum Edges {
NearLeftEdge,
NearBottomEdge,
NearRightEdge,
NearTopEdge,
FarLeftEdge,
FarTopEdge,
FarRightEdge,
FarBottomEdge,
LeftTopEdge,
LeftBottomEdge,
RightTopEdge,
RightBottomEdge,
NUM_EDGES,
InvalidEdge
}
Indices for the edges of the box.
enum PlaneMasks : U32 {
PlaneMaskLeft = (1 << LeftPlane),
PlaneMaskRight = (1 << RightPlane),
PlaneMaskTop = (1 << TopPlane),
PlaneMaskBottom = (1 << BottomPlane),
PlaneMaskNear = (1 << NearPlane),
PlaneMaskFar = (1 << FarPlane),
PlaneMaskAll = 0xFFFFFFFF
}
enum Planes {
LeftPlane,
RightPlane,
NearPlane,
FarPlane,
TopPlane,
BottomPlane,
NUM_PLANES
}
Indices for the side planes of the box.
enum Points {
NearBottomRight,
NearTopRight,
NearTopLeft,
NearBottomLeft,
FarBottomRight,
FarTopRight,
FarTopLeft,
FarBottomLeft,
NUM_POINTS,
InvalidPoint = NUM_POINTS
}
Indices of the corner points.
Public Member Functions
OrientedBox3F ()
OrientedBox3F (const MatrixF &transform, const Point3F &extents)
OrientedBox3F (const MatrixF &transform, const Box3F &aabb)
const Point3F & getAxis (U32 i) const
Return the normalized axis vector for the given world-space axis.
const Point3F & getCenter () const
Return the center point of the bounding box.
const Point3F & getHalfExtents () const
Return the half-extents along each axis.
const Point3F * getPoints () const
Return the corner points of the box.
bool isContained (const Point3F &point) const
Return true if the given point is contained in the OBB.
operator const Point3F * () const
Return the array of corner points for the box.
void set (const MatrixF &transform, const Point3F &extents)
Compute the OBB values from the given transform and extents.
void set (const MatrixF &transform, const Box3F &aabb)
Compute the OBB from an AABB in the given transform space.
Protected Member Functions
void _initPoints ()
Protected Attributes
Point3F mAxes [3]
Normalized axis vectors.
Point3F mCenter
Center point.
Point3F mHalfExtents
Box half-extents along each axis.
Point3F mPoints [NUM_POINTS]
Corner points.
Additional Inherited Members
Static Public Member Functions inherited from BoxBase
static void getEdgePointIndices (Edges edge, Points &outP1, Points &outP2)
Get the start and end point of the given edge.
static Points getOppositePoint (Points p)
Return the point index for the opposite corner of p.
static Points getPlanePointIndex (Planes plane, U32 i)
static Points getPointIndexFromOctant (const Point3F &p)
Return the point index for the corner point that corresponds to the octant that p points to.
Detailed Description
An oriented bounding box (OBB) described by a center point, three normalizes axis vectors, and half-extents along each of the axes.
Member Enumeration Documentation
enum OrientedBox3F::Axis
Enumerator
RightVector
ForwardVector
UpVector
Constructor & Destructor Documentation
OrientedBox3F::OrientedBox3F () inline
OrientedBox3F::OrientedBox3F (const MatrixF & transform, const Point3F & extents) inline
OrientedBox3F::OrientedBox3F (const MatrixF & transform, const Box3F & aabb) inline
Member Function Documentation
void OrientedBox3F::_initPoints () protected
const Point3F& OrientedBox3F::getAxis (U32 i) const inline
Return the normalized axis vector for the given world-space axis.
Referenced by PlaneF::whichSide().
const Point3F& OrientedBox3F::getCenter () const inline
Return the center point of the bounding box.
References mCenter.
Referenced by PlaneF::whichSide().
const Point3F& OrientedBox3F::getHalfExtents () const inline
Return the half-extents along each axis.
Since the OBBs are symmetrical across each axis, we store half-extents instead of full extents as usually half-extents are needed in the computations.
References isContained(), and mHalfExtents.
Referenced by PlaneF::whichSide().
const Point3F* OrientedBox3F::getPoints () const inline
Return the corner points of the box.
References mPoints.
Referenced by operator const Point3F *().
bool OrientedBox3F::isContained (const Point3F & point) const
Return true if the given point is contained in the OBB.
Referenced by getHalfExtents().
OrientedBox3F::operator const Point3F * () const inline
Return the array of corner points for the box.
References getPoints().
void OrientedBox3F::set (const MatrixF & transform, const Point3F & extents)
Compute the OBB values from the given transform and extents.
Parameters
transform World->object space transform.
extents Box extent on each axis.
Referenced by SceneSimpleZone::_updateOrientedWorldBox().
void OrientedBox3F::set (const MatrixF & transform, const Box3F & aabb)
Compute the OBB from an AABB in the given transform space.
Parameters
transform Transform space for the AABB.
aabb An axis-aligned bounding box in the given transform space.
Member Data Documentation
Point3F OrientedBox3F::mAxes[3] protected
Normalized axis vectors.
Point3F OrientedBox3F::mCenter protected
Center point.
Referenced by getCenter().
Point3F OrientedBox3F::mHalfExtents protected
Box half-extents along each axis.
Referenced by getHalfExtents().
Point3F OrientedBox3F::mPoints[NUM_POINTS] protected
Corner points.
Referenced by getPoints().
Copyright © GarageGames, LLC. All Rights Reserved.