StrongObjectRef Class Reference
Main Modules Class List Namespace List Online
StrongObjectRef Class Reference
Base class for StrongRefBase strong reference pointers.
#include <core/util/refBase.h>
Public Member Functions
StrongObjectRef (StrongRefBase *object=NULL)
Constructor, assigns from the object and increments its reference count if it's not NULL.
~StrongObjectRef ()
Destructor, dereferences the object, if there is one.
void set (StrongRefBase *object)
Assigns this reference object from an existing StrongRefBase instance.
Protected Member Functions
void decRef ()
decrements the reference count on the referenced object
void incRef ()
increments the reference count on the referenced object
Protected Attributes
StrongRefBase * mObject
the object this RefObjectRef references
Detailed Description
Base class for StrongRefBase strong reference pointers.
Constructor & Destructor Documentation
StrongObjectRef::StrongObjectRef (StrongRefBase * object = NULL) inline
Constructor, assigns from the object and increments its reference count if it's not NULL.
StrongObjectRef::~StrongObjectRef () inline
Destructor, dereferences the object, if there is one.
Member Function Documentation
void StrongObjectRef::decRef () inline protected
decrements the reference count on the referenced object
References StrongRefBase::decRefCount().
void StrongObjectRef::incRef () inline protected
increments the reference count on the referenced object
References StrongRefBase::incRefCount().
void StrongObjectRef::set (StrongRefBase * object) inline
Assigns this reference object from an existing StrongRefBase instance.
Referenced by GFXTexHandle::free(), GFXCubemapHandle::free(), GFXCubemapHandle::GFXCubemapHandle(), GFXTexHandle::operator=(), GFXPrimitiveBufferHandle::operator=(), GFXVertexBufferHandle< GFXWaterVertex >::operator=(), and GFXVertexBufferDataHandle::operator=().
Member Data Documentation
StrongRefBase* StrongObjectRef::mObject protected
the object this RefObjectRef references
Referenced by StrongRefPtr< GFXD3D9ShaderConstBuffer >::operator=().
Copyright © GarageGames, LLC. All Rights Reserved.