IdGenerator Class Reference
Main Modules Class List Namespace List Online
IdGenerator Class Reference
#include <core/idGenerator.h>
Public Member Functions
IdGenerator (U32 base, U32 numIds)
U32 alloc ()
void free (U32 id)
U32 numIdsUsed ()
void reset ()
Constructor & Destructor Documentation
IdGenerator::IdGenerator (U32 base, U32 numIds) inline
Member Function Documentation
U32 IdGenerator::alloc () inline
References Vector< T >::empty(), Vector< T >::last(), and Vector< T >::pop_back().
void IdGenerator::free (U32 id) inline
References Vector< T >::push_back().
U32 IdGenerator::numIdsUsed () inline
References Vector< T >::size().
void IdGenerator::reset (void) inline
References Vector< T >::clear().
Copyright © GarageGames, LLC. All Rights Reserved.