SceneRenderState Class Reference
Main Modules Class List Namespace List Online
SceneRenderState Class Reference
The SceneRenderState describes the state of the scene being rendered.
#include <scene/sceneRenderState.h>
Public Types
typedef Delegate< BaseMatInstance *(BaseMatInstance *) > MatDelegate
The delegate used for material overrides.
Public Member Functions
SceneRenderState (SceneManager *sceneManager, ScenePassType passType, const SceneCameraState &view=SceneCameraState::fromGFX(), RenderPassManager *renderPass=NULL, bool usePostEffects=true)
Construct a new SceneRenderState.
~SceneRenderState ()
SceneManager * getSceneManager () const
Return the SceneManager that is being rendered in this SceneRenderState.
bool usePostEffects () const
If true then bin based post effects are disabled during rendering with this scene state.
void usePostEffects (bool value)
Culling
const SceneCullingState & getCullingState () const
Return the culling state for the scene.
SceneCullingState & getCullingState ()
const Frustum & getCullingFrustum () const
Returns the root culling frustum.
const Frustum & getCameraFrustum () const
Returns the root camera frustum.
Rendering
const Box3F & getRenderArea () const
Get the AABB around the scene portion that we render.
void setRenderArea (const Box3F &area)
Set the AABB of the space that should be rendered.
void renderObjects (SceneObject **objects, U32 numObjects)
Batch the given objects to the render pass manager and then render the batched instances.
Lighting
ColorF getAmbientLightColor () const
Return the ambient light color to use for rendering the scene.
void setAmbientLightColor (const ColorF &color)
Set the global ambient light color to render with.
bool disableAdvancedLightingBins () const
If true then Advanced Lighting bin draws are disabled during rendering with this scene state.
void disableAdvancedLightingBins (bool enabled)
bool renderLightmappedMeshes () const
void renderLightmappedMeshes (bool enabled)
bool renderNonLightmappedMeshes () const
void renderNonLightmappedMeshes (bool enabled)
Passes
RenderPassManager * getRenderPass () const
Return the RenderPassManager that manages rendering objects batched for this SceneRenderState.
ScenePassType getScenePassType () const
Returns the type of scene rendering pass that we're doing.
bool isDiffusePass () const
Returns true if this is a diffuse scene rendering pass.
bool isReflectPass () const
Returns true if this is a reflection scene rendering pass.
bool isShadowPass () const
Returns true if this is a shadow scene rendering pass.
bool isOtherPass () const
Returns true if this is not one of the other rendering passes.
Render Style
SceneRenderStyle getSceneRenderStyle () const
Get the rendering style used for the scene.
void setSceneRenderStyle (SceneRenderStyle style)
Set the rendering style used for the scene.
Transforms, projections, and viewports.
const RectI & getViewport () const
Return the screen-space viewport rectangle.
const MatrixF & getWorldViewMatrix () const
Return the world->view transform matrix.
const MatrixF & getProjectionMatrix () const
Return the project transform matrix.
const Point3F & getCameraPosition () const
Returns the actual camera position.
const MatrixF & getCameraTransform () const
Returns the camera transform (view->world) this SceneRenderState is using.
F32 getNearPlane () const
Returns the minimum distance something must be from the camera to not be culled.
F32 getFarPlane () const
Returns the maximum distance something can be from the camera to not be culled.
const Point3F & getVectorEye () const
Returns the camera vector normalized to 1 / far distance.
const Point2F & getWorldToScreenScale () const
Returns the possibly overloaded world to screen scale.
void setWorldToScreenScale (const Point2F &scale)
Set a new world to screen scale to overload future screen metrics operations.
F32 projectRadius (F32 dist, F32 radius) const
Returns the pixel size of the radius projected to the screen at a desired distance.
Point3F getDiffuseCameraPosition () const
Returns the camera position used during the diffuse rendering pass which may be different from the actual camera position.
const MatrixF & getDiffuseCameraTransform () const
void setDiffuseCameraTransform (const MatrixF &mat)
Set a new diffuse camera transform.
Material Overrides
BaseMatInstance * getOverrideMaterial (BaseMatInstance *matInst) const
When performing a special render pass like shadows this returns a specialized override material.
MatDelegate & getMaterialDelegate ()
Returns the optional material override delegate which is used during some special render passes.
const MatDelegate & getMaterialDelegate () const
Protected Attributes
ColorF mAmbientLightColor
Global ambient light color.
SceneCullingState mCullingState
Culling state of the scene.
MatrixF mDiffuseCameraTransform
bool mDisableAdvancedLightingBins
Disables AdvancedLighting bin draws during rendering with this scene state.
MatDelegate mMatDelegate
The optional material override delegate.
Box3F mRenderArea
The AABB that encloses the space in the scene that we render.
bool mRenderLightmappedMeshes
If true (default) lightmapped meshes should be rendered.
bool mRenderNonLightmappedMeshes
If true (default) non-lightmapped meshes should be rendered.
RenderPassManager * mRenderPass
The render pass which we are setting up with this scene state.
SceneManager * mSceneManager
SceneManager being rendered in this state.
ScenePassType mScenePassType
The type of scene render pass we're doing.
SceneRenderStyle mSceneRenderStyle
The render style being performed.
bool mUsePostEffects
Forces bin based post effects to be disabled during rendering with this scene state.
Point3F mVectorEye
The camera vector normalized to 1 / far dist.
Point2F mWorldToScreenScale
The world to screen space scalar used for LOD calculations.
Detailed Description
The SceneRenderState describes the state of the scene being rendered.
It keeps track of the information that objects need to render properly with regard to the camera position, any fog information, viewing frustum, the global environment map for reflections, viewable distance, etc.
It also owns the current culling state.
Member Typedef Documentation
typedef Delegate< BaseMatInstance*(BaseMatInstance*) > SceneRenderState::MatDelegate
The delegate used for material overrides.
See also
getOverrideMaterial
Constructor & Destructor Documentation
SceneRenderState::SceneRenderState (SceneManager * sceneManager, ScenePassType passType, const SceneCameraState & view = SceneCameraState::fromGFX(), RenderPassManager * renderPass = NULL, bool usePostEffects = true)
Construct a new SceneRenderState.
Parameters
sceneManager SceneManager rendered in this SceneRenderState.
passType Type of rendering pass that the SceneRenderState is for.
view The view that is being rendered
renderPass The render pass which is being set up by this SceneRenderState. If NULL, then Scene::getDefaultRenderPass() is used.
usePostEffect Whether PostFX are enabled in the rendering pass.
SceneRenderState::~SceneRenderState ()
Member Function Documentation
bool SceneRenderState::disableAdvancedLightingBins () const inline
If true then Advanced Lighting bin draws are disabled during rendering with this scene state.
References mDisableAdvancedLightingBins.
void SceneRenderState::disableAdvancedLightingBins (bool enabled) inline
ColorF SceneRenderState::getAmbientLightColor () const inline
Return the ambient light color to use for rendering the scene.
At the moment, we only support a single global ambient color with which all objects in the scene are rendered. This is because when using Advanced Lighting, we are not resolving light contribution on a per-surface or per-object basis but rather do it globally by gathering light contribution to the whole scene and since the ambient factor is decided by the sun/vector light, it simply becomes a base light level onto which shadowing/lighting is blended based on the shadow maps of the sun/vector light.
Returns
The ambient light color for rendering.
References mAmbientLightColor.
Referenced by SceneData::init().
const Frustum& SceneRenderState::getCameraFrustum () const inline
Returns the root camera frustum.
References SceneCullingState::getCameraFrustum(), and getCullingState().
const Point3F& SceneRenderState::getCameraPosition () const inline
Returns the actual camera position.
See also
getDiffuseCameraPosition
References SceneCullingState::getCameraState(), getCullingState(), and SceneCameraState::getViewPosition().
const MatrixF& SceneRenderState::getCameraTransform () const inline
Returns the camera transform (view->world) this SceneRenderState is using.
References SceneCullingState::getCameraState(), getCullingState(), and SceneCameraState::getViewWorldMatrix().
const Frustum& SceneRenderState::getCullingFrustum () const inline
Returns the root culling frustum.
References SceneCullingState::getCullingFrustum(), and getCullingState().
Referenced by getFarPlane(), and getNearPlane().
const SceneCullingState& SceneRenderState::getCullingState () const inline
Return the culling state for the scene.
References mCullingState.
Referenced by getCameraFrustum(), getCameraPosition(), getCameraTransform(), getCullingFrustum(), and getViewport().
SceneCullingState& SceneRenderState::getCullingState () inline
References mCullingState.
Point3F SceneRenderState::getDiffuseCameraPosition () const inline
Returns the camera position used during the diffuse rendering pass which may be different from the actual camera position.
This is useful when doing level of detail calculations that need to be relative to the diffuse pass.
See also
getCameraPosition
References MatrixF::getPosition().
const MatrixF& SceneRenderState::getDiffuseCameraTransform () const inline
References mDiffuseCameraTransform.
F32 SceneRenderState::getFarPlane () const inline
Returns the maximum distance something can be from the camera to not be culled.
References getCullingFrustum(), and Frustum::getFarDist().
MatDelegate& SceneRenderState::getMaterialDelegate () inline
Returns the optional material override delegate which is used during some special render passes.
See also
getOverrideMaterial
References mMatDelegate.
const MatDelegate& SceneRenderState::getMaterialDelegate () const inline
References mMatDelegate.
F32 SceneRenderState::getNearPlane () const inline
Returns the minimum distance something must be from the camera to not be culled.
References getCullingFrustum(), and Frustum::getNearDist().
BaseMatInstance* SceneRenderState::getOverrideMaterial (BaseMatInstance * matInst) const inline
When performing a special render pass like shadows this returns a specialized override material.
It can return NULL if the override wants to disable rendering. If there is no override in place then the input material is returned unaltered.
References mMatDelegate.
const MatrixF& SceneRenderState::getProjectionMatrix () const
Return the project transform matrix.
Referenced by getViewport().
const Box3F& SceneRenderState::getRenderArea () const inline
Get the AABB around the scene portion that we render.
References mRenderArea.
RenderPassManager* SceneRenderState::getRenderPass () const inline
Return the RenderPassManager that manages rendering objects batched for this SceneRenderState.
References mRenderPass.
SceneManager* SceneRenderState::getSceneManager () const inline
Return the SceneManager that is being rendered in this SceneRenderState.
References mSceneManager.
Referenced by SceneData::init().
ScenePassType SceneRenderState::getScenePassType () const inline
Returns the type of scene rendering pass that we're doing.
References mScenePassType.
SceneRenderStyle SceneRenderState::getSceneRenderStyle () const inline
Get the rendering style used for the scene.
References mSceneRenderStyle.
const Point3F& SceneRenderState::getVectorEye () const inline
Returns the camera vector normalized to 1 / far distance.
References mVectorEye.
const RectI& SceneRenderState::getViewport () const inline
Return the screen-space viewport rectangle.
References SceneCullingState::getCameraState(), getCullingState(), getProjectionMatrix(), SceneCameraState::getViewport(), and getWorldViewMatrix().
const Point2F& SceneRenderState::getWorldToScreenScale () const inline
Returns the possibly overloaded world to screen scale.
See also
projectRadius
References mWorldToScreenScale.
const MatrixF& SceneRenderState::getWorldViewMatrix () const
Return the world->view transform matrix.
Referenced by getViewport().
bool SceneRenderState::isDiffusePass () const inline
Returns true if this is a diffuse scene rendering pass.
Referenced by ScenePolyhedralObject< Base, P >::_renderObject().
bool SceneRenderState::isOtherPass () const inline
Returns true if this is not one of the other rendering passes.
bool SceneRenderState::isReflectPass () const inline
Returns true if this is a reflection scene rendering pass.
bool SceneRenderState::isShadowPass () const inline
Returns true if this is a shadow scene rendering pass.
F32 SceneRenderState::projectRadius (F32 dist, F32 radius) const inline
Returns the pixel size of the radius projected to the screen at a desired distance.
Internally this uses the stored world to screen scale and viewport extents. This allows the projection to be overloaded in special cases like when rendering shadows or reflections.
See also
getWorldToScreenScale
getViewportExtent
References Point2F::y.
bool SceneRenderState::renderLightmappedMeshes () const inline
References mRenderLightmappedMeshes.
void SceneRenderState::renderLightmappedMeshes (bool enabled) inline
bool SceneRenderState::renderNonLightmappedMeshes () const inline
References mRenderNonLightmappedMeshes.
void SceneRenderState::renderNonLightmappedMeshes (bool enabled) inline
void SceneRenderState::renderObjects (SceneObject ** objects, U32 numObjects)
Batch the given objects to the render pass manager and then render the batched instances.
Parameters
objects List of objects.
numObjects Number of objects in objects.
Referenced by setRenderArea().
void SceneRenderState::setAmbientLightColor (const ColorF & color) inline
Set the global ambient light color to render with.
void SceneRenderState::setDiffuseCameraTransform (const MatrixF & mat) inline
Set a new diffuse camera transform.
See also
getDiffuseCameraTransform
void SceneRenderState::setRenderArea (const Box3F & area) inline
Set the AABB of the space that should be rendered.
References renderObjects().
void SceneRenderState::setSceneRenderStyle (SceneRenderStyle style) inline
Set the rendering style used for the scene.
void SceneRenderState::setWorldToScreenScale (const Point2F & scale) inline
Set a new world to screen scale to overload future screen metrics operations.
bool SceneRenderState::usePostEffects () const inline
If true then bin based post effects are disabled during rendering with this scene state.
References mUsePostEffects.
void SceneRenderState::usePostEffects (bool value) inline
Member Data Documentation
ColorF SceneRenderState::mAmbientLightColor protected
Global ambient light color.
Referenced by getAmbientLightColor().
SceneCullingState SceneRenderState::mCullingState protected
Culling state of the scene.
Referenced by getCullingState().
MatrixF SceneRenderState::mDiffuseCameraTransform protected
Referenced by getDiffuseCameraTransform().
bool SceneRenderState::mDisableAdvancedLightingBins protected
Disables AdvancedLighting bin draws during rendering with this scene state.
Referenced by disableAdvancedLightingBins().
MatDelegate SceneRenderState::mMatDelegate protected
The optional material override delegate.
Referenced by getMaterialDelegate(), and getOverrideMaterial().
Box3F SceneRenderState::mRenderArea protected
The AABB that encloses the space in the scene that we render.
Referenced by getRenderArea().
bool SceneRenderState::mRenderLightmappedMeshes protected
If true (default) lightmapped meshes should be rendered.
Referenced by renderLightmappedMeshes().
bool SceneRenderState::mRenderNonLightmappedMeshes protected
If true (default) non-lightmapped meshes should be rendered.
Referenced by renderNonLightmappedMeshes().
RenderPassManager* SceneRenderState::mRenderPass protected
The render pass which we are setting up with this scene state.
Referenced by getRenderPass().
SceneManager* SceneRenderState::mSceneManager protected
SceneManager being rendered in this state.
Referenced by getSceneManager().
ScenePassType SceneRenderState::mScenePassType protected
The type of scene render pass we're doing.
Referenced by getScenePassType().
SceneRenderStyle SceneRenderState::mSceneRenderStyle protected
The render style being performed.
Referenced by getSceneRenderStyle().
bool SceneRenderState::mUsePostEffects protected
Forces bin based post effects to be disabled during rendering with this scene state.
Referenced by usePostEffects().
Point3F SceneRenderState::mVectorEye protected
The camera vector normalized to 1 / far dist.
Referenced by getVectorEye().
Point2F SceneRenderState::mWorldToScreenScale protected
The world to screen space scalar used for LOD calculations.
Referenced by getWorldToScreenScale().
Copyright © GarageGames, LLC. All Rights Reserved.