Torque::Path Class Reference
Main Modules Class List Namespace List Online
Torque::Path Class Reference
FileSystem filename representation.
#include <core/util/path.h>
Public Types
enum Separator { OsSeparator = '/' }
Public Member Functions
Path ()
Path (const char *file)
Path (const String &file)
bool appendPath (const Path &path)
Appends the argument's path component to the object's path component.
String getDirectory (U32) const
U32 getDirectoryCount () const
const String & getExtension () const
const String & getFileName () const
const String & getFullFileName () const
const String & getFullPath () const
String getFullPathWithoutRoot () const
Returns the full file path without the volume root.
const String & getPath () const
const String & getRoot () const
String getRootAndPath () const
Returns the root and path.
bool isAbsolute () const
bool isDirectory () const
bool isEmpty () const
bool isRelative () const
operator String () const
bool operator!= (const Path &path) const
Path & operator= (const String &file)
bool operator== (const Path &path) const
const String & setExtension (const String &s)
const String & setFileName (const String &s)
const String & setPath (const String &s)
const String & setRoot (const String &s)
Static Public Member Functions
static String CleanSeparators (String path)
Replace all '\' with '/'.
static String CompressPath (String path)
Remove "." and ".." relative paths.
static String Join (const String &, String::ValueType, const String &)
Join two path or file name components together.
static Path MakeRelativePath (const Path &makeRelative, const Path &relativeTo, U32 mode=String::NoCase)
Take two paths and return the relative path between them.
Detailed Description
FileSystem filename representation.
Filenames has the following form: "root:path/file.ext"
Member Enumeration Documentation
enum Torque::Path::Separator
Enumerator
OsSeparator
Constructor & Destructor Documentation
Torque::Path::Path () inline
Torque::Path::Path (const char * file) inline
Torque::Path::Path (const String & file) inline
Member Function Documentation
bool Torque::Path::appendPath (const Path & path)
Appends the argument's path component to the object's path component.
The object's root, filename and extension are unaffected.
Referenced by getExtension().
static String Torque::Path::CleanSeparators (String path) static
Replace all '\' with '/'.
Referenced by isEmpty().
static String Torque::Path::CompressPath (String path) static
Remove "." and ".." relative paths.
Referenced by isEmpty().
String Torque::Path::getDirectory (U32) const
Referenced by getExtension().
U32 Torque::Path::getDirectoryCount () const
Referenced by getExtension().
const String& Torque::Path::getExtension () const inline
References appendPath(), getDirectory(), getDirectoryCount(), getFullFileName(), getFullPath(), getFullPathWithoutRoot(), getRootAndPath(), isAbsolute(), isDirectory(), isRelative(), Torque::PathToOS(), Torque::PathToPlatform(), setExtension(), setFileName(), setPath(), and setRoot().
const String& Torque::Path::getFileName () const inline
const String& Torque::Path::getFullFileName () const
Referenced by getExtension().
const String& Torque::Path::getFullPath () const
Referenced by getExtension(), GFXShader::getPixelShaderFile(), GFXShader::getVertexShaderFile(), isEmpty(), operator String(), and operator==().
String Torque::Path::getFullPathWithoutRoot () const
Returns the full file path without the volume root.
Referenced by getExtension().
const String& Torque::Path::getPath (void) const inline
const String& Torque::Path::getRoot () const inline
String Torque::Path::getRootAndPath () const
Returns the root and path.
Referenced by getExtension().
bool Torque::Path::isAbsolute () const
Referenced by getExtension().
bool Torque::Path::isDirectory () const
Referenced by getExtension().
bool Torque::Path::isEmpty () const inline
References CleanSeparators(), CompressPath(), getFullPath(), String::isEmpty(), Join(), MakeRelativePath(), and String::NoCase.
bool Torque::Path::isRelative () const
Referenced by getExtension().
static String Torque::Path::Join (const String & , String::ValueType , const String &) static
Join two path or file name components together.
Referenced by isEmpty().
static Path Torque::Path::MakeRelativePath (const Path & makeRelative, const Path & relativeTo, U32 mode = String::NoCase) static
Take two paths and return the relative path between them.
Referenced by isEmpty().
Torque::Path::operator String () const inline
References getFullPath().
bool Torque::Path::operator!= (const Path & path) const inline
Path& Torque::Path::operator= (const String & file) inline
bool Torque::Path::operator== (const Path & path) const inline
References String::equal(), and getFullPath().
const String& Torque::Path::setExtension (const String & s)
Referenced by getExtension().
const String& Torque::Path::setFileName (const String & s)
Referenced by getExtension().
const String& Torque::Path::setPath (const String & s)
Referenced by getExtension().
const String& Torque::Path::setRoot (const String & s)
Referenced by getExtension().
Copyright © GarageGames, LLC. All Rights Reserved.