x86UNIXFont Class Reference
Main Modules Class List Namespace List Online
x86UNIXFont Class Reference
#include <platformX86UNIX/x86UNIXFont.h>
Public Member Functions
x86UNIXFont ()
virtual ~x86UNIXFont ()
virtual bool create (const char *name, dsize_t size, U32 charset=TGE_ANSI_CHARSET)
This is just for createPlatformFont to call.
virtual PlatformFont::CharInfo & getCharInfo (const UTF16 ch) const
virtual PlatformFont::CharInfo & getCharInfo (const UTF8 *str) const
U32 getFontBaseLine () const
U32 getFontHeight () const
virtual bool isValidChar (const UTF16 ch) const
Is the specified character valid for rendering?
virtual bool isValidChar (const UTF8 *str) const
Public Member Functions inherited from PlatformFont
virtual ~PlatformFont ()
Additional Inherited Members
Static Public Member Functions inherited from PlatformFont
static void enumeratePlatformFonts (Vector< StringTableEntry > &fonts, UTF16 *fontFamily=NULL)
Constructor & Destructor Documentation
x86UNIXFont::x86UNIXFont ()
virtual x86UNIXFont::~x86UNIXFont () virtual
Member Function Documentation
virtual bool x86UNIXFont::create (const char * name, dsize_t size, U32 charset = TGE_ANSI_CHARSET) virtual
This is just for createPlatformFont to call.
Implements PlatformFont.
Referenced by getFontBaseLine().
virtual PlatformFont::CharInfo& x86UNIXFont::getCharInfo (const UTF16 ch) const virtual
Implements PlatformFont.
Referenced by getFontBaseLine().
virtual PlatformFont::CharInfo& x86UNIXFont::getCharInfo (const UTF8 * str) const virtual
Implements PlatformFont.
U32 x86UNIXFont::getFontBaseLine () const inline virtual
Implements PlatformFont.
References create(), and getCharInfo().
U32 x86UNIXFont::getFontHeight () const inline virtual
Implements PlatformFont.
virtual bool x86UNIXFont::isValidChar (const UTF16 ch) const virtual
Is the specified character valid for rendering?
Implements PlatformFont.
virtual bool x86UNIXFont::isValidChar (const UTF8 * str) const virtual
Implements PlatformFont.
Copyright © GarageGames, LLC. All Rights Reserved.