ConsoleBaseType Class Reference
Main Modules Class List Namespace List Online
ConsoleBaseType Class Reference abstract
Information about a console type.
#include <console/dynamicTypes.h>
Public Member Functions
const char * getDocString () const
Return the documentation string for this type.
const EngineEnumTable * getEnumTable () const
Return the EnumTable for this type (only for enumeration types).
const char * getInspectorFieldType ()
Return the name of the GuiInspectorField subclass that fields of this type should use for editing.
S32 getTypeID () const
Return the unique numeric ID of this type.
const EngineTypeInfo * getTypeInfo () const
Return the type info for the engine type corresponding to this console type or NULL if there is no mapping for the console type.
StringTableEntry getTypeName () const
Return the console type name (TypeXXX).
S32 getTypeSize () const
Return the size of a single value in bytes.
void setInspectorFieldType (const char *type)
Set the name of the GuiInspectorField subclass that fields of this type should use for editing.
Value Handling Interface
virtual void setData (void *dptr, S32 argc, const char **argv, const EnumTable *tbl, BitSet32 flag)=0
virtual const char * getData (void *dptr, const EnumTable *tbl, BitSet32 flag)=0
virtual const char * getTypeClassName ()=0
virtual void * getNativeVariable ()=0
Allocate a single value.
virtual void deleteNativeVariable (void *var)=0
Delete a single value allocated with getNativeVariable().
virtual const bool isDatablock ()
Return true if this is datablock object type.
virtual const char * prepData (const char *data, char *buffer, U32 bufferLen)
virtual StringTableEntry getTypePrefix (void) const
Static Public Member Functions
static ConsoleBaseType * getType (const S32 typeID)
Call me to get a pointer to a type's info.
static ConsoleBaseType * getTypeByClassName (const char *typeName)
static ConsoleBaseType * getTypeByName (const char *typeName)
Call to get a pointer to a type's info.
static void initialize ()
Called once to initialize the console type system.
Protected Member Functions
ConsoleBaseType (const S32 size, S32 *idPtr, const char *aTypeName)
The constructor is responsible for linking an element into the master list, registering the type ID, etc.
~ConsoleBaseType ()
Destructor is private to avoid people mucking up the list.
Protected Attributes
const char * mInspectorFieldType
Name of GuiInspectorField subclass to instantiate for field edit controls in inspectors.
ConsoleBaseType * mListNext
Next item in the list of all console types.
S32 mTypeID
Unique numeric type ID.
const EngineTypeInfo * mTypeInfo
Type info object for the engine type corresponding to this console type.
StringTableEntry mTypeName
Name of this console type (TypeXXX).
dsize_t mTypeSize
Size of a single data value point.
Static Protected Attributes
static S32 smConsoleTypeCount
Total number of defined console types. This is used to generate unique IDs for each type.
static ConsoleBaseType * smListHead
We maintain a linked list of all console types; this is its head.
cbt_list List Interface
Interface for accessing/traversing the list of types.
static ConsoleBaseType * getListHead ()
Get the head of the list.
ConsoleBaseType * getListNext () const
Get the item that follows this item in the list.
Detailed Description
Information about a console type.
Constructor & Destructor Documentation
ConsoleBaseType::ConsoleBaseType (const S32 size, S32 * idPtr, const char * aTypeName) protected
The constructor is responsible for linking an element into the master list, registering the type ID, etc.
ConsoleBaseType::~ConsoleBaseType () inline protected
Destructor is private to avoid people mucking up the list.
References getListHead().
Member Function Documentation
virtual void ConsoleBaseType::deleteNativeVariable (void * var) pure virtual
Delete a single value allocated with getNativeVariable().
Implemented in AbstractClassRep, and SimObjectRefConsoleBaseType< T >.
Referenced by setInspectorFieldType().
virtual const char* ConsoleBaseType::getData (void * dptr, const EnumTable * tbl, BitSet32 flag) pure virtual
Implemented in ConcreteAbstractClassRep< T >, BitfieldConsoleBaseType, EnumConsoleBaseType, RuntimeClassRep< T >, and SimObjectRefConsoleBaseType< T >.
Referenced by setInspectorFieldType().
const char* ConsoleBaseType::getDocString () const inline
Return the documentation string for this type.
References EngineExport::getDocString(), and getTypeInfo().
const EngineEnumTable* ConsoleBaseType::getEnumTable () const inline
Return the EnumTable for this type (only for enumeration types).
References EngineTypeInfo::getEnumTable(), and getTypeInfo().
Referenced by EnumConsoleBaseType::getData(), and EnumConsoleBaseType::setData().
const char* ConsoleBaseType::getInspectorFieldType () inline
Return the name of the GuiInspectorField subclass that fields of this type should use for editing.
References mInspectorFieldType.
static ConsoleBaseType* ConsoleBaseType::getListHead () static
Get the head of the list.
Referenced by ~ConsoleBaseType().
ConsoleBaseType* ConsoleBaseType::getListNext () const inline
Get the item that follows this item in the list.
References getType(), getTypeByClassName(), getTypeByName(), initialize(), and mListNext.
virtual void* ConsoleBaseType::getNativeVariable () pure virtual
Allocate a single value.
Implemented in AbstractClassRep, and SimObjectRefConsoleBaseType< T >.
Referenced by setInspectorFieldType().
static ConsoleBaseType* ConsoleBaseType::getType (const S32 typeID) static
Call me to get a pointer to a type's info.
Referenced by getListNext().
static ConsoleBaseType* ConsoleBaseType::getTypeByClassName (const char * typeName) static
Referenced by getListNext().
static ConsoleBaseType* ConsoleBaseType::getTypeByName (const char * typeName) static
Call to get a pointer to a type's info.
Referenced by getListNext().
virtual const char* ConsoleBaseType::getTypeClassName () pure virtual
Implemented in ConcreteAbstractClassRep< T >, RuntimeClassRep< T >, and SimObjectRefConsoleBaseType< T >.
Referenced by setInspectorFieldType().
S32 ConsoleBaseType::getTypeID () const inline
Return the unique numeric ID of this type.
References mTypeID.
const EngineTypeInfo* ConsoleBaseType::getTypeInfo () const inline
Return the type info for the engine type corresponding to this console type or NULL if there is no mapping for the console type.
References mTypeInfo.
Referenced by getDocString(), and getEnumTable().
StringTableEntry ConsoleBaseType::getTypeName () const inline
Return the console type name (TypeXXX).
References mTypeName.
virtual StringTableEntry ConsoleBaseType::getTypePrefix (void) const inline virtual
S32 ConsoleBaseType::getTypeSize () const inline
Return the size of a single value in bytes.
References mTypeSize.
static void ConsoleBaseType::initialize () static
Called once to initialize the console type system.
Referenced by getListNext().
virtual const bool ConsoleBaseType::isDatablock () inline virtual
Return true if this is datablock object type.
Reimplemented in ConcreteAbstractClassRep< T >, RuntimeClassRep< T >, and SimObjectRefConsoleBaseType< T >.
virtual const char* ConsoleBaseType::prepData (const char * data, char * buffer, U32 bufferLen) inline virtual
virtual void ConsoleBaseType::setData (void * dptr, S32 argc, const char ** argv, const EnumTable * tbl, BitSet32 flag) pure virtual
Implemented in ConcreteAbstractClassRep< T >, BitfieldConsoleBaseType, EnumConsoleBaseType, RuntimeClassRep< T >, and SimObjectRefConsoleBaseType< T >.
Referenced by setInspectorFieldType().
void ConsoleBaseType::setInspectorFieldType (const char * type) inline
Set the name of the GuiInspectorField subclass that fields of this type should use for editing.
References deleteNativeVariable(), getData(), getNativeVariable(), getTypeClassName(), and setData().
Member Data Documentation
const char* ConsoleBaseType::mInspectorFieldType protected
Name of GuiInspectorField subclass to instantiate for field edit controls in inspectors.
Referenced by getInspectorFieldType().
ConsoleBaseType* ConsoleBaseType::mListNext protected
Next item in the list of all console types.
Referenced by getListNext().
S32 ConsoleBaseType::mTypeID protected
Unique numeric type ID.
Referenced by getTypeID().
const EngineTypeInfo* ConsoleBaseType::mTypeInfo protected
Type info object for the engine type corresponding to this console type.
Since several console types may be mapped to a single native type, this type info instance may be shared by multiple ConsoleBaseType instances. NULL if the console type is not mapped to an engine API type.
Referenced by ConcreteAbstractClassRep< T >::ConcreteAbstractClassRep(), getTypeInfo(), and RuntimeClassRep< T >::RuntimeClassRep().
StringTableEntry ConsoleBaseType::mTypeName protected
Name of this console type (TypeXXX).
Referenced by getTypeName().
dsize_t ConsoleBaseType::mTypeSize protected
Size of a single data value point.
Referenced by getTypeSize().
S32 ConsoleBaseType::smConsoleTypeCount static protected
Total number of defined console types. This is used to generate unique IDs for each type.
ConsoleBaseType* ConsoleBaseType::smListHead static protected
We maintain a linked list of all console types; this is its head.
Copyright © GarageGames, LLC. All Rights Reserved.