ConsoleObject Class Reference
Main Modules Class List Namespace List Online
ConsoleObject Class Reference
Interface class to the console.
#include <console/consoleObject.h>
Public Member Functions
ConsoleObject ()
virtual AbstractClassRep * getClassRep () const
Gets the ClassRep.
Public Member Functions inherited from EngineObject
EngineObject ()
virtual ~EngineObject ()
DECLARE_ABSTRACT_CLASS (EngineObject, void)
DECLARE_INSCOPE (_GLOBALSCOPE)
virtual String describeSelf () const
Return a string that describes this instance. Meant primarily for debugging.
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
IEngineObjectPool * getEngineObjectPool () const
Return the pool of EngineObjects to which this object belongs.
void operator delete (void *ptr)
Release the given object's memory in the pool it has been allocated from.
void * operator new (size_t size)
void * operator new (size_t size, IEngineObjectPool *pool)
void * operator new (size_t size TORQUE_TMM_ARGS_DECL)
Allocate a new object in the default object pool.
void * operator new (size_t size, IEngineObjectPool *pool TORQUE_TMM_ARGS_DECL)
Allocate a new object in the given object pool.
void * operator new (size_t size, void *ptr)
Placement new.
Public Member Functions inherited from StrongRefBase
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Static Public Member Functions
static const char * __category ()
static const char * __description ()
static void consoleInit ()
Register global constant variables and do other one-time initialization tasks in a subclass of ConsoleObject.
static void initPersistFields ()
Register dynamic fields in a subclass of ConsoleObject.
static const char * lookupClassName (const U32 in_classTag)
Get the classname from a class tag.
Static Public Member Functions inherited from EngineObject
static void debugDumpInstances ()
Dump describeSelf()s of all live ConsoleObjects to the console.
static void debugEnumInstances (const std::type_info &type, DebugEnumInstancesCallback callback)
Call the given callback for all instances of the given type.
static void debugEnumInstances (const char *className, DebugEnumInstancesCallback callback)
Same as above but uses an export class name and also includes inheritance (i.e.
Static Public Attributes
static const bool __smIsDatablock = false
Subclasses of ConsoleObjects that are datablocks should redefine this static member variable and set it to true.
Protected Member Functions
ConsoleObject (const ConsoleObject &)
Protected Member Functions inherited from EngineObject
virtual void _destroySelf ()
Subclasses should overload this method instead of the public destroySelf().
object incRefCount ()
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
const AbstractClassRep::Field * findField (StringTableEntry fieldName) const
Get a reference to a field by name.
bool setField (const char *fieldName, const char *value)
Set the value of a field.
Object Creation
static ConsoleObject * create (const char *in_pClassName)
static ConsoleObject * create (const U32 groupId, const U32 typeId, const U32 in_classId)
Fields
static void addGroup (const char *in_pGroupname, const char *in_pGroupDocs=NULL)
Mark the beginning of a group of fields.
static void endGroup (const char *in_pGroupname)
Mark the end of a group of fields.
static void addArray (const char *arrayName, S32 count)
Marks the start of a fixed size array of fields.
static void endArray (const char *arrayName)
Marks the end of an array of fields.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a complex field.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::WriteDataNotify in_writeDataFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, const char *in_pFieldDocs, U32 flags=0)
Register a simple field.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::WriteDataNotify in_writeDataFn, const char *in_pFieldDocs, U32 flags=0)
static void addFieldV (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, TypeValidator *v, const char *in_pFieldDocs=NULL)
Register a validated field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, AbstractClassRep::WriteDataNotify in_writeDataFn=&defaultProtectedWriteFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a complex protected field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, AbstractClassRep::WriteDataNotify in_writeDataFn=&defaultProtectedWriteFn, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a simple protected field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addDeprecatedField (const char *fieldName)
Add a deprecated field.
static bool removeField (const char *in_pFieldname)
Remove a field.
Logging
These functions will try to print out a message along the lines of "ObjectClass - ObjectName(ObjectId) - formatted message"
virtual String _getLogMessage (const char *fmt, va_list args) const
Overload this in subclasses to change the message formatting.
void logMessage (const char *fmt,...) const
Logs with Con::printf.
void logWarning (const char *fmt,...) const
Logs with Con::warnf.
void logError (const char *fmt,...) const
Logs with Con::errorf.
Field List
const AbstractClassRep::FieldList & getFieldList () const
Get a list of all the fields. This information cannot be modified.
AbstractClassRep::FieldList & getModifiableFieldList ()
Get a list of all the fields, set up so we can modify them.
bool & getDynamicGroupExpand ()
Get a handle to a boolean telling us if we expanded the dynamic group.
ConsoleObject Implementation
These functions are implemented in every subclass of ConsoleObject by an IMPLEMENT_CONOBJECT or IMPLEMENT_CO_* macro.
S32 getClassId (U32 netClassGroup) const
Get our network-layer class id.
StringTableEntry getClassName () const
Get our compiler and platform independent class name.
static AbstractClassRep * getStaticClassRep ()
Get the abstract class information for this class.
static AbstractClassRep * getParentStaticClassRep ()
Get the abstract class information for this class's superclass.
Object IDs and lookup.
For a subclass hierarchy based on ConsoleObject to become functional for use as a console object type, the hierarchy must implement a naming scheme and indexing function for looking up objects by name.
static ConsoleObject * __findObject (const char *)
static const char * __getObjectId (ConsoleObject *)
Additional Inherited Members
Public Types inherited from EngineObject
typedef void(* DebugEnumInstancesCallback) (EngineObject *)
Type of callback function for iterating over EngineObject instances.
Public Attributes inherited from EngineObject
DECLARE_INSTANTIABLE
Protected Types inherited from EngineObject
typedef ::FalseType __IsDisposableType
typedef ::FalseType __IsSingletonType
Static Protected Member Functions inherited from EngineObject
static void * _allocateObject (size_t size, IEngineObjectPool *pool TORQUE_TMM_ARGS_DECL)
Protected Attributes inherited from EngineObject
DEFINE_CREATE_METHOD
return object
Protected Attributes inherited from StrongRefBase
U32 mRefCount
reference counter for StrongRefPtr objects
Detailed Description
Interface class to the console.
The Basics
Any object which you want to work with the console system should derive from this, and access functionality through the static interface.
This class is always used with the DECLARE_CONOBJECT and IMPLEMENT_* macros.
// A very basic example object. It will do nothing!
class TorqueObject : public ConsoleObject {
     // Must provide a Parent typedef so the console system knows what we inherit from.
     typedef ConsoleObject Parent;
     // This does a lot of menial declaration for you.
     DECLARE_CONOBJECT(TorqueObject);
     // This is for us to register our fields in.
     static void initPersistFields();
     // A sample field.
     S8 mSample;
}
// And the accordant implementation...
IMPLEMENT_CONOBJECT(TorqueObject);
void TorqueObject::initPersistFields()
{
  // If you want to inherit any fields from the parent (you do), do this:
  Parent::initPersistFields();
  // Pass the field, the type, the offset,                  and a usage string.
  addField("sample", TypeS8, Offset(mSample, TorqueObject), "A test field.");
}
That's all you need to do to get a class registered with the console system. At this point, you can instantiate it via script, tie methods to it using ConsoleMethod, register fields, and so forth. You can also register any global variables related to the class by creating a consoleInit() method.
You will need to use different IMPLEMENT_ macros in different cases; for instance, if you are making a NetObject (for ghosting), a DataBlock, or a NetEvent.
See also
AbstractClassRep for gory implementation details.
Constructor & Destructor Documentation
ConsoleObject::ConsoleObject (const ConsoleObject &) protected
ConsoleObject::ConsoleObject () inline
References AbstractClassRep::create(), and AbstractClassRep::findField().
Member Function Documentation
static const char* ConsoleObject::__category () inline static
static const char* ConsoleObject::__description () inline static
static ConsoleObject* ConsoleObject::__findObject (const char *) inline static
static const char* ConsoleObject::__getObjectId (ConsoleObject *) inline static
virtual String ConsoleObject::_getLogMessage (const char * fmt, va_list args) const virtual
Overload this in subclasses to change the message formatting.
Parameters
fmt A printf style format string.
args A va_list containing the args passed ot a log function.
Note
It is suggested that you use String::VToString.
Reimplemented in SimObject.
static void ConsoleObject::addArray (const char * arrayName, S32 count) static
Marks the start of a fixed size array of fields.
See also
console_autodoc
static void ConsoleObject::addDeprecatedField (const char * fieldName) static
Add a deprecated field.
A deprecated field will always be undefined, even if you assign a value to it. This is useful when you need to make sure that a field is not being used anymore.
static void ConsoleObject::addField (const char * in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, const U32 in_elementCount = 1, const char * in_pFieldDocs = NULL, U32 flags = 0) static
Register a complex field.
Parameters
in_pFieldname Name of the field.
in_fieldType Type of the field.
See also
ConsoleDynamicTypes
Parameters
in_fieldOffset Offset to the field from the start of the class; calculated using the Offset() macro.
in_elementCount Number of elements in this field. Arrays of elements are assumed to be contiguous in memory.
in_pFieldDocs Usage string for this field.
See also
console_autodoc
static void ConsoleObject::addField (const char * in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::WriteDataNotify in_writeDataFn, const U32 in_elementCount = 1, const char * in_pFieldDocs = NULL, U32 flags = 0) static
static void ConsoleObject::addField (const char * in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, const char * in_pFieldDocs, U32 flags = 0) static
Register a simple field.
Parameters
in_pFieldname Name of the field.
in_fieldType Type of the field.
See also
ConsoleDynamicTypes
Parameters
in_fieldOffset Offset to the field from the start of the class; calculated using the Offset() macro.
in_pFieldDocs Usage string for this field.
See also
console_autodoc
static void ConsoleObject::addField (const char * in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::WriteDataNotify in_writeDataFn, const char * in_pFieldDocs, U32 flags = 0) static
static void ConsoleObject::addFieldV (const char * in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, TypeValidator * v, const char * in_pFieldDocs = NULL) static
Register a validated field.
A validated field is just like a normal field except that you can't have it be an array, and that you give it a pointer to a TypeValidator subclass, which is then used to validate any value placed in it. Invalid values are ignored and an error is printed to the console.
See also
addField
typeValidators.h
static void ConsoleObject::addGroup (const char * in_pGroupname, const char * in_pGroupDocs = NULL) static
Mark the beginning of a group of fields.
This is used in the consoleDoc system.
See also
console_autodoc
static void ConsoleObject::addProtectedField (const char * in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn = &defaultProtectedGetFn, AbstractClassRep::WriteDataNotify in_writeDataFn = &defaultProtectedWriteFn, const U32 in_elementCount = 1, const char * in_pFieldDocs = NULL, U32 flags = 0) static
Register a complex protected field.
Parameters
in_pFieldname Name of the field.
in_fieldType Type of the field.
See also
ConsoleDynamicTypes
Parameters
in_fieldOffset Offset to the field from the start of the class; calculated using the Offset() macro.
in_setDataFn When this field gets set, it will call the callback provided.
See also
console_protected
Parameters
in_getDataFn When this field is accessed for it's data, it will return the value of this function
in_elementCount Number of elements in this field. Arrays of elements are assumed to be contiguous in memory.
in_pFieldDocs Usage string for this field.
See also
console_autodoc
static void ConsoleObject::addProtectedField (const char * in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn = &defaultProtectedGetFn, const U32 in_elementCount = 1, const char * in_pFieldDocs = NULL, U32 flags = 0) static
static void ConsoleObject::addProtectedField (const char * in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn = &defaultProtectedGetFn, AbstractClassRep::WriteDataNotify in_writeDataFn = &defaultProtectedWriteFn, const char * in_pFieldDocs = NULL, U32 flags = 0) static
Register a simple protected field.
Parameters
in_pFieldname Name of the field.
in_fieldType Type of the field.
See also
ConsoleDynamicTypes
Parameters
in_fieldOffset Offset to the field from the start of the class; calculated using the Offset() macro.
in_setDataFn When this field gets set, it will call the callback provided.
See also
console_protected
Parameters
in_getDataFn When this field is accessed for it's data, it will return the value of this function
in_pFieldDocs Usage string for this field.
See also
console_autodoc
static void ConsoleObject::addProtectedField (const char * in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn = &defaultProtectedGetFn, const char * in_pFieldDocs = NULL, U32 flags = 0) static
static void ConsoleObject::consoleInit () static
Register global constant variables and do other one-time initialization tasks in a subclass of ConsoleObject.
See also
console
Referenced by Player::enableHeadZCalc(), PhysicsShape::getDataBlock(), and Camera::getValidEditOrbitPoint().
ConsoleObject * ConsoleObject::create (const char * in_pClassName) inline static
References AbstractClassRep::create().
ConsoleObject * ConsoleObject::create (const U32 groupId, const U32 typeId, const U32 in_classId) inline static
References AbstractClassRep::create().
static void ConsoleObject::endArray (const char * arrayName) static
Marks the end of an array of fields.
See also
console_autodoc
static void ConsoleObject::endGroup (const char * in_pGroupname) static
Mark the end of a group of fields.
This is used in the consoleDoc system.
See also
console_autodoc
const AbstractClassRep::Field * ConsoleObject::findField (StringTableEntry fieldName) const inline
Get a reference to a field by name.
S32 ConsoleObject::getClassId (U32 netClassGroup) const inline
Get our network-layer class id.
Parameters
netClassGroup The net class for which we want our ID.
See also
StringTableEntry ConsoleObject::getClassName () const inline
Get our compiler and platform independent class name.
Note
This name can be used to instantiate another instance using create()
Referenced by TamlCustomNode::addNode(), and SimObject::getComponentName().
virtual AbstractClassRep* ConsoleObject::getClassRep () const virtual
Gets the ClassRep.
bool & ConsoleObject::getDynamicGroupExpand () inline
Get a handle to a boolean telling us if we expanded the dynamic group.
See also
GuiInspector::Inspect()
const AbstractClassRep::FieldList & ConsoleObject::getFieldList () const inline
Get a list of all the fields. This information cannot be modified.
AbstractClassRep::FieldList & ConsoleObject::getModifiableFieldList () inline
Get a list of all the fields, set up so we can modify them.
Note
This is a bad trick to pull if you aren't very careful, since you can blast field data!
static AbstractClassRep* ConsoleObject::getParentStaticClassRep () inline static
Get the abstract class information for this class's superclass.
References AbstractClassRep::getClassId(), and AbstractClassRep::getClassName().
static AbstractClassRep* ConsoleObject::getStaticClassRep () inline static
Get the abstract class information for this class.
static void ConsoleObject::initPersistFields () static
Register dynamic fields in a subclass of ConsoleObject.
See also
addField(), addFieldV(), addDeprecatedField(), addGroup(), endGroup()
void ConsoleObject::logError (const char * fmt, ...) const
Logs with Con::errorf.
void ConsoleObject::logMessage (const char * fmt, ...) const
Logs with Con::printf.
void ConsoleObject::logWarning (const char * fmt, ...) const
Logs with Con::warnf.
static const char* ConsoleObject::lookupClassName (const U32 in_classTag) static
Get the classname from a class tag.
static bool ConsoleObject::removeField (const char * in_pFieldname) static
Remove a field.
Sometimes, you just have to remove a field!
Returns
True on success.
bool ConsoleObject::setField (const char * fieldName, const char * value) inline
Set the value of a field.
References AbstractClassRep::Field::flag, AbstractClassRep::Field::offset, Con::setData(), AbstractClassRep::Field::table, and AbstractClassRep::Field::type.
Member Data Documentation
const bool ConsoleObject::__smIsDatablock = false static
Subclasses of ConsoleObjects that are datablocks should redefine this static member variable and set it to true.
Copyright © GarageGames, LLC. All Rights Reserved.