SimPersistID Class Reference
Main Modules Class List Namespace List Online
SimPersistID Class Reference
A globally unique persistent ID for a SimObject.
#include <console/simPersistID.h>
Public Types
typedef void Parent
Public Member Functions
SimObject * getObject () const
Return the object that is bound to this PID.
const Torque::UUID & getUUID () const
Return the UUID bound to this PID.
Public Member Functions inherited from StrongRefBase
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Static Public Member Functions
static SimPersistID * find (const Torque::UUID &uuid)
Look up a persistent ID by its UUID. Return NULL if no PID is bound to the given UUID.
static SimObject * findObjectByUUID (const Torque::UUID &uuid)
Find a SimObject by the UUID assigned to its PID.
static SimPersistID * findOrCreate (const Torque::UUID &uuid)
Look up a persistent ID by its UUID.
static void init ()
Initialize the persistent ID system.
static void shutdown ()
Uninitialize the persistent ID system.
Protected Types
typedef HashTable< Torque::UUID, SimPersistID * > LookupTableType
Protected Member Functions
SimPersistID (SimObject *object)
Construct a new persistent ID for "object" by generating a fresh unique identifier.
SimPersistID (const Torque::UUID &uuid)
Construct a persistent ID stub for the given unique identifier.
~SimPersistID ()
void resolve (SimObject *object)
Bind this unresolved PID to the given object.
void unresolve ()
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Static Protected Member Functions
static SimPersistID * create (SimObject *object)
Create a persistent ID for the given object.
Protected Attributes
SimObject * mObject
Reference to the SimObject.
Torque::UUID mUUID
The UUID assigned to the object. Never changes.
Protected Attributes inherited from StrongRefBase
U32 mRefCount
reference counter for StrongRefPtr objects
Static Protected Attributes
static LookupTableType * smLookupTable
Table of persistent object IDs.
Detailed Description
A globally unique persistent ID for a SimObject.
Member Typedef Documentation
typedef HashTable< Torque::UUID, SimPersistID* > SimPersistID::LookupTableType protected
typedef void SimPersistID::Parent
Constructor & Destructor Documentation
SimPersistID::SimPersistID (SimObject * object) protected
Construct a new persistent ID for "object" by generating a fresh unique identifier.
SimPersistID::SimPersistID (const Torque::UUID & uuid) protected
Construct a persistent ID stub for the given unique identifier.
The stub remains not bound to any object until it is resolved.
SimPersistID::~SimPersistID () protected
Member Function Documentation
static SimPersistID* SimPersistID::create (SimObject * object) static protected
Create a persistent ID for the given object.
Referenced by unresolve().
static SimPersistID* SimPersistID::find (const Torque::UUID & uuid) static
Look up a persistent ID by its UUID. Return NULL if no PID is bound to the given UUID.
Referenced by unresolve().
static SimObject* SimPersistID::findObjectByUUID (const Torque::UUID & uuid) static
Find a SimObject by the UUID assigned to its PID.
Return NULL if either no PID is bound to the given UUID or if the PID bound to it is not yet resolved.
Referenced by unresolve().
static SimPersistID* SimPersistID::findOrCreate (const Torque::UUID & uuid) static
Look up a persistent ID by its UUID.
If no PID is bound to the given UUID yet, create a new PID and bind it to the UUID.
Referenced by unresolve().
SimObject* SimPersistID::getObject () const inline
Return the object that is bound to this PID.
If the PID has not yet been resolved, return NULL.
References mObject.
const Torque::UUID& SimPersistID::getUUID () const inline
Return the UUID bound to this PID.
References mUUID.
static void SimPersistID::init () static
Initialize the persistent ID system.
Referenced by unresolve().
void SimPersistID::resolve (SimObject * object) protected
Bind this unresolved PID to the given object.
static void SimPersistID::shutdown () static
Uninitialize the persistent ID system.
Referenced by unresolve().
void SimPersistID::unresolve () inline protected
References create(), find(), findObjectByUUID(), findOrCreate(), init(), and shutdown().
Member Data Documentation
SimObject* SimPersistID::mObject protected
Reference to the SimObject.
Will be NULL for as long as the persistent ID is not resolved.
Referenced by getObject().
Torque::UUID SimPersistID::mUUID protected
The UUID assigned to the object. Never changes.
Referenced by getUUID().
LookupTableType* SimPersistID::smLookupTable static protected
Table of persistent object IDs.
Copyright © GarageGames, LLC. All Rights Reserved.