DataChunker Class Reference
Main Modules Class List Namespace List Online
DataChunker Class Reference
Implements a chunked data allocator.
#include <core/dataChunker.h>
Classes
struct DataBlock
Block of allocated memory.
Public Types
enum {
PaddDBSize = (sizeof(DataBlock) + 3) & ~3,
ChunkSize = 16384 - PaddDBSize
}
Public Member Functions
DataChunker (S32 size=ChunkSize)
Initialize using blocks of a given size.
~DataChunker ()
void * alloc (S32 size)
Return a pointer to a chunk of memory from a pre-allocated block.
U32 countUsedBlocks ()
void freeBlocks (bool keepOne=false)
Free all allocated memory blocks.
void setChunkSize (U32 size)
void swap (DataChunker &d)
Swaps the memory allocated in one data chunker for another.
Public Attributes
S32 mChunkSize
The size allocated for each page in the DataChunker.
DataBlock * mCurBlock
current page we're allocating data from.
Detailed Description
Implements a chunked data allocator.
Calling new/malloc all the time is a time consuming operation. Therefore, we provide the DataChunker, which allocates memory in blocks of chunkSize (by default 16k, see ChunkSize, though it can be set in the constructor), then doles it out as requested, in chunks of up to chunkSize in size.
It will assert if you try to get more than ChunkSize bytes at a time, and it deals with the logic of allocating new blocks and giving out word-aligned chunks.
Note that new/free/realloc WILL NOT WORK on memory gotten from the DataChunker. This also only grows (you can call freeBlocks to deallocate and reset things).
Member Enumeration Documentation
anonymous enum
Enumerator
PaddDBSize
Padded size of DataBlock.
ChunkSize
Default size of each DataBlock page in the DataChunker.
Constructor & Destructor Documentation
DataChunker::DataChunker (S32 size = ChunkSize)
Initialize using blocks of a given size.
One new block is allocated at constructor-time.
Parameters
size Size in bytes of the space to allocate for each block.
Referenced by FreeListChunker< NetEventNote >::FreeListChunker(), and FreeListChunkerUntyped::FreeListChunkerUntyped().
DataChunker::~DataChunker ()
Member Function Documentation
void* DataChunker::alloc (S32 size)
Return a pointer to a chunk of memory from a pre-allocated block.
This memory goes away when you call freeBlocks.
This memory is word-aligned.
Parameters
size Size of chunk to return. This must be less than chunkSize or else an assertion will occur.
Referenced by Chunker< ShadowVolumeBSP::SVPoly >::alloc(), MultiTypedChunker::alloc(), ClassChunker< SceneZoneSpace::ZoneSpaceRef >::alloc(), and SceneCullingState::allocateData().
U32 DataChunker::countUsedBlocks () inline
References mCurBlock.
void DataChunker::freeBlocks (bool keepOne = false)
Free all allocated memory blocks.
This invalidates all pointers returned from alloc().
Referenced by Chunker< ShadowVolumeBSP::SVPoly >::clear(), MultiTypedChunker::clear(), and ClassChunker< SceneZoneSpace::ZoneSpaceRef >::freeBlocks().
void DataChunker::setChunkSize (U32 size) inline
References mChunkSize, and mCurBlock.
Referenced by HashTable< Key, Value >::resize().
void DataChunker::swap (DataChunker & d) inline
Swaps the memory allocated in one data chunker for another.
This can be used to implement packing of memory stored in a DataChunker.
References mCurBlock.
Member Data Documentation
S32 DataChunker::mChunkSize
The size allocated for each page in the DataChunker.
Referenced by setChunkSize().
DataBlock* DataChunker::mCurBlock
current page we're allocating data from.
If the data size request is greater than the memory space currently available in the current page, a new page will be allocated.
Referenced by countUsedBlocks(), setChunkSize(), and swap().
Copyright © GarageGames, LLC. All Rights Reserved.