ColladaAppMaterial Class Reference
Main Modules Class List Namespace List Online
ColladaAppMaterial Class Reference
#include <ts/collada/colladaAppMaterial.h>
Public Member Functions
ColladaAppMaterial (const char *matName)
ColladaAppMaterial (const domMaterial *pMat)
~ColladaAppMaterial ()
Material * createMaterial (const Torque::Path &path) const
String getName () const
void resolveColor (const domCommon_color_or_texture_type *value, ColorF *dst)
void resolveFloat (const domCommon_float_or_param_type *value, F32 *dst)
template<class T >
void resolveTransparency (const T shader, F32 *dst)
Public Member Functions inherited from AppMaterial
AppMaterial ()
virtual ~AppMaterial ()
virtual U32 getFlags ()
virtual F32 getReflectance ()
Public Attributes
ColorF diffuseColor
String diffuseMap
bool doubleSided
domEffect * effect
Collada <effect> element.
ColladaExtension_effect * effectExt
effect extension
const domMaterial * mat
Collada <material> element.
String name
Name of this material (cleaned)
String normalMap
ColorF specularColor
String specularMap
F32 specularPower
Public Attributes inherited from AppMaterial
U32 flags
F32 reflectance
Constructor & Destructor Documentation
ColladaAppMaterial::ColladaAppMaterial (const char * matName)
ColladaAppMaterial::ColladaAppMaterial (const domMaterial * pMat)
ColladaAppMaterial::~ColladaAppMaterial () inline
References effectExt.
Member Function Documentation
Material* ColladaAppMaterial::createMaterial (const Torque::Path & path) const
Referenced by resolveTransparency().
String ColladaAppMaterial::getName () const inline virtual
Reimplemented from AppMaterial.
References name, resolveColor(), and resolveFloat().
void ColladaAppMaterial::resolveColor (const domCommon_color_or_texture_type * value, ColorF * dst)
Referenced by getName().
void ColladaAppMaterial::resolveFloat (const domCommon_float_or_param_type * value, F32 * dst)
Referenced by getName(), and resolveTransparency().
template<class T > void ColladaAppMaterial::resolveTransparency (const T shader, F32 * dst) inline
References createMaterial(), and resolveFloat().
Member Data Documentation
ColorF ColladaAppMaterial::diffuseColor
String ColladaAppMaterial::diffuseMap
bool ColladaAppMaterial::doubleSided
domEffect* ColladaAppMaterial::effect
Collada <effect> element.
ColladaExtension_effect* ColladaAppMaterial::effectExt
effect extension
Referenced by ~ColladaAppMaterial().
const domMaterial* ColladaAppMaterial::mat
Collada <material> element.
String ColladaAppMaterial::name
Name of this material (cleaned)
Referenced by getName().
String ColladaAppMaterial::normalMap
ColorF ColladaAppMaterial::specularColor
String ColladaAppMaterial::specularMap
F32 ColladaAppMaterial::specularPower
Copyright © GarageGames, LLC. All Rights Reserved.