Torque::List< Type > Class Template Reference
Main Modules Class List Namespace List Online
Torque::List< Type > Class Template Reference
A list template class.
#include <core/util/tList.h>
Classes
class _Iterator
Public Types
typedef _Iterator< const Type, const Link > ConstIterator
typedef const Type & ConstReference
typedef S32 DifferenceType
typedef _Iterator< Type, Link > Iterator
typedef PrivatePersist * PersistentIter
A PersistentIter is used for the special cases where you need to store an iterator for efficiency reasons.
typedef Type & Reference
typedef U32 SizeType
typedef Type ValueType
Public Member Functions
List ()
List (const List &p)
~List ()
Iterator begin ()
_Iterator to first element
ConstIterator begin () const
_Iterator to first element
void clear ()
Empty the List.
Iterator end ()
_Iterator to last element + 1
ConstIterator end () const
_Iterator to last element + 1
void erase (U32)
Preserves element order.
void erase (Iterator)
Preserves element order.
Type & first ()
First element.
const Type & first () const
First element.
U32 getSize () const
Return the number of elements.
Iterator insert (U32 index, const Type &=Type())
Insert new element at the given index.
Iterator insert (Iterator, const Type &=Type())
Insert at the given iter.
bool isEmpty () const
Node count == 0?
Type & last ()
Last element.
const Type & last () const
Last element.
void operator= (const List &p)
Type & operator[] (U32)
const Type & operator[] (U32) const
void popBack ()
Remove the last element.
void popFront ()
Remove the first element.
Iterator pushBack (const Type &=Type())
Insert after the last element.
Iterator pushFront (const Type &=Type())
Insert at first element.
Iterator rbegin ()
_Iterator to first element - 1
ConstIterator rbegin () const
_Iterator to first element - 1
Iterator rend ()
_Iterator to last element
ConstIterator rend () const
_Iterator to last element
void resize (U32)
Set the list size.
Detailed Description
template<typename Type>
class Torque::List< Type >
A list template class.
A classic list class similar to the STL list class. The list class supports fast insert and erase operations, but slow dynamic access. The list is circular and the iterator supports iterating past the end() or rend() in order to loop around.
Member Typedef Documentation
template<typename Type> typedef _Iterator<const Type,const Link> Torque::List< Type >::ConstIterator
template<typename Type> typedef const Type& Torque::List< Type >::ConstReference
template<typename Type> typedef S32 Torque::List< Type >::DifferenceType
template<typename Type> typedef _Iterator<Type,Link> Torque::List< Type >::Iterator
template<typename Type> typedef PrivatePersist* Torque::List< Type >::PersistentIter
A PersistentIter is used for the special cases where you need to store an iterator for efficiency reasons.
The _Iterator class handles the conversion to/from PersistentIter.
Note
The data in the node this points to could go away, so only use these in cases where you control the allocation/deallocation of the nodes in the list.
template<typename Type> typedef Type& Torque::List< Type >::Reference
template<typename Type> typedef U32 Torque::List< Type >::SizeType
template<typename Type> typedef Type Torque::List< Type >::ValueType
Constructor & Destructor Documentation
template<class Type > Torque::List< Type >::List ()
template<class Type > Torque::List< Type >::~List ()
References Torque::List< Type >::begin(), and Torque::List< Type >::end().
template<class Type > Torque::List< Type >::List (const List< Type > & p)
Member Function Documentation
template<class Type > List< Type >::Iterator Torque::List< Type >::begin () inline
_Iterator to first element
Referenced by Torque::List< Type >::operator=(), and Torque::List< Type >::~List().
template<class Type > List< Type >::ConstIterator Torque::List< Type >::begin () const inline
_Iterator to first element
template<class Type > void Torque::List< Type >::clear (void)
Empty the List.
template<class Type > List< Type >::Iterator Torque::List< Type >::end () inline
_Iterator to last element + 1
Referenced by Torque::List< Type >::operator=(), and Torque::List< Type >::~List().
template<class Type > List< Type >::ConstIterator Torque::List< Type >::end () const inline
_Iterator to last element + 1
template<class Type > void Torque::List< Type >::erase (U32 index) inline
Preserves element order.
Referenced by Torque::List< Type >::popBack(), and Torque::List< Type >::popFront().
template<class Type > void Torque::List< Type >::erase (Iterator itr)
Preserves element order.
template<class Type > Type & Torque::List< Type >::first () inline
First element.
template<class Type > const Type & Torque::List< Type >::first () const inline
First element.
template<class Type > U32 Torque::List< Type >::getSize () const inline
Return the number of elements.
template<class Type> List< Type >::Iterator Torque::List< Type >::insert (U32 index, const Type & x = Type()) inline
Insert new element at the given index.
Referenced by Torque::List< Type >::pushBack(), and Torque::List< Type >::pushFront().
template<class Type> List< Type >::Iterator Torque::List< Type >::insert (Iterator itr, const Type & x = Type())
Insert at the given iter.
template<class Type > bool Torque::List< Type >::isEmpty () const inline
Node count == 0?
template<class Type > Type & Torque::List< Type >::last () inline
Last element.
template<class Type > const Type & Torque::List< Type >::last () const inline
Last element.
template<class Type > void Torque::List< Type >::operator= (const List< Type > & p)
References Torque::List< Type >::begin(), Torque::List< Type >::end(), Torque::List< Type >::popBack(), and Torque::List< Type >::pushBack().
template<class Type > Type & Torque::List< Type >::operator[] (U32 index) inline
template<class Type > const Type & Torque::List< Type >::operator[] (U32 index) const inline
template<class Type > void Torque::List< Type >::popBack () inline
Remove the last element.
References Torque::List< Type >::erase().
Referenced by Torque::List< Type >::operator=(), and Torque::List< Type >::resize().
template<class Type > void Torque::List< Type >::popFront () inline
Remove the first element.
References Torque::List< Type >::erase().
template<class Type> List< Type >::Iterator Torque::List< Type >::pushBack (const Type & x = Type()) inline
Insert after the last element.
References Torque::List< Type >::insert().
Referenced by Torque::List< Type >::operator=(), and Torque::List< Type >::resize().
template<class Type> List< Type >::Iterator Torque::List< Type >::pushFront (const Type & x = Type()) inline
Insert at first element.
References Torque::List< Type >::insert().
template<class Type > List< Type >::Iterator Torque::List< Type >::rbegin () inline
_Iterator to first element - 1
template<class Type > List< Type >::ConstIterator Torque::List< Type >::rbegin () const inline
_Iterator to first element - 1
template<class Type > List< Type >::Iterator Torque::List< Type >::rend () inline
_Iterator to last element
template<class Type > List< Type >::ConstIterator Torque::List< Type >::rend () const inline
_Iterator to last element
template<class Type > void Torque::List< Type >::resize (U32 size)
Set the list size.
References Torque::List< Type >::popBack(), and Torque::List< Type >::pushBack().
Copyright © GarageGames, LLC. All Rights Reserved.