SparseArray< T > Class Template Reference
Main Modules Class List Namespace List Online
SparseArray< T > Class Template Reference
#include <core/tSparseArray.h>
Classes
struct Node
Public Member Functions
SparseArray (const U32 modulusSize=64)
~SparseArray ()
void clearTables ()
void insert (T *pObject, U32 key)
T * remove (U32 key)
T * retreive (U32 key)
Protected Attributes
U32 mModulus
Node * mSentryTables
Constructor & Destructor Documentation
template<class T > SparseArray< T >::SparseArray (const U32 modulusSize = 64) inline
References SparseArray< T >::mModulus, SparseArray< T >::mSentryTables, and SparseArray< T >::Node::next.
template<class T > SparseArray< T >::~SparseArray () inline
References SparseArray< T >::clearTables().
Member Function Documentation
template<class T > void SparseArray< T >::clearTables () inline
References SparseArray< T >::mModulus, SparseArray< T >::mSentryTables, SparseArray< T >::Node::next, and SparseArray< T >::Node::pObject.
Referenced by SparseArray< T >::~SparseArray().
template<class T> void SparseArray< T >::insert (T * pObject, U32 key) inline
References SparseArray< T >::Node::key, SparseArray< T >::mModulus, SparseArray< T >::mSentryTables, SparseArray< T >::Node::next, and SparseArray< T >::Node::pObject.
Referenced by SimpleHashTable< T >::insert().
template<class T > T * SparseArray< T >::remove (U32 key) inline
References SparseArray< T >::Node::key, SparseArray< T >::mModulus, SparseArray< T >::mSentryTables, SparseArray< T >::Node::next, and T.
Referenced by SimpleHashTable< T >::remove().
template<class T > T * SparseArray< T >::retreive (U32 key) inline
References SparseArray< T >::Node::key, SparseArray< T >::mModulus, SparseArray< T >::mSentryTables, SparseArray< T >::Node::next, and SparseArray< T >::Node::pObject.
Referenced by SimpleHashTable< T >::retreive().
Member Data Documentation
template<class T> U32 SparseArray< T >::mModulus protected
Referenced by SparseArray< T >::clearTables(), SparseArray< T >::insert(), SparseArray< T >::remove(), SparseArray< T >::retreive(), and SparseArray< T >::SparseArray().
template<class T> Node* SparseArray< T >::mSentryTables protected
Referenced by SparseArray< T >::clearTables(), SparseArray< T >::insert(), SparseArray< T >::remove(), SparseArray< T >::retreive(), and SparseArray< T >::SparseArray().
Copyright © GarageGames, LLC. All Rights Reserved.