FixedSizeDeque< T > Class Template Reference
Main Modules Class List Namespace List Online
FixedSizeDeque< T > Class Template Reference
A double-ended queue with a fixed number of entries set at construction time.
#include <core/util/tFixedSizeDeque.h>
Public Types
typedef T ValueType
Type for elements stored in the deque.
Public Member Functions
FixedSizeDeque (U32 bufferSize)
~FixedSizeDeque ()
ValueType back () const
Return the rightmost value in the queue.
U32 capacity () const
void clear ()
ValueType front () const
Return the leftmost value in the queue.
bool isEmpty () const
ValueType popBack ()
Remove and return the rightmost value in the queue.
ValueType popFront ()
Remove and return the leftmost value in the queue.
void pushBack (const ValueType &value)
Append "value" to the right end of the queue.
void pushFront (const ValueType &value)
Prepend "value" to the left end of the queue.
U32 size () const
Protected Attributes
ValueType * mBuffer
U32 mBufferSize
U32 mEnd
U32 mSize
U32 mStart
Index.
Detailed Description
template<typename T>
class FixedSizeDeque< T >
A double-ended queue with a fixed number of entries set at construction time.
Implemented as an array.
Parameters
T Element type of the queue.
Member Typedef Documentation
template<typename T> typedef T FixedSizeDeque< T >::ValueType
Type for elements stored in the deque.
Constructor & Destructor Documentation
template<typename T> FixedSizeDeque< T >::FixedSizeDeque (U32 bufferSize) inline
template<typename T> FixedSizeDeque< T >::~FixedSizeDeque () inline
Member Function Documentation
template<typename T> ValueType FixedSizeDeque< T >::back () const inline
Return the rightmost value in the queue.
template<typename T> U32 FixedSizeDeque< T >::capacity () const inline
Referenced by AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::needPacket(), FixedSizeDeque< QueuedPacket >::pushBack(), FixedSizeDeque< QueuedPacket >::pushFront(), and AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::submitPacket().
template<typename T> void FixedSizeDeque< T >::clear (void) inline
template<typename T> ValueType FixedSizeDeque< T >::front () const inline
Return the leftmost value in the queue.
Referenced by AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::needPacket().
template<typename T> bool FixedSizeDeque< T >::isEmpty () const inline
Referenced by FixedSizeDeque< QueuedPacket >::back(), FixedSizeDeque< QueuedPacket >::front(), AsyncPacketQueue< SFXStreamPacket *, SFXVoiceTimeSource, SFXBuffer * >::isEmpty(), FixedSizeDeque< QueuedPacket >::popBack(), and FixedSizeDeque< QueuedPacket >::popFront().
template<typename T> ValueType FixedSizeDeque< T >::popBack () inline
Remove and return the rightmost value in the queue.
template<typename T> ValueType FixedSizeDeque< T >::popFront () inline
Remove and return the leftmost value in the queue.
Referenced by FixedSizeDeque< QueuedPacket >::clear(), and AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::needPacket().
template<typename T> void FixedSizeDeque< T >::pushBack (const ValueType & value) inline
Append "value" to the right end of the queue.
Referenced by AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::submitPacket().
template<typename T> void FixedSizeDeque< T >::pushFront (const ValueType & value) inline
Prepend "value" to the left end of the queue.
template<typename T> U32 FixedSizeDeque< T >::size () const inline
Referenced by FixedSizeDeque< QueuedPacket >::capacity(), FixedSizeDeque< QueuedPacket >::clear(), FixedSizeDeque< QueuedPacket >::isEmpty(), AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::needPacket(), and AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::submitPacket().
Member Data Documentation
template<typename T> ValueType* FixedSizeDeque< T >::mBuffer protected
template<typename T> U32 FixedSizeDeque< T >::mBufferSize protected
template<typename T> U32 FixedSizeDeque< T >::mEnd protected
Referenced by FixedSizeDeque< QueuedPacket >::pushBack().
template<typename T> U32 FixedSizeDeque< T >::mSize protected
Referenced by FixedSizeDeque< QueuedPacket >::size().
template<typename T> U32 FixedSizeDeque< T >::mStart protected
Index.
Referenced by FixedSizeDeque< QueuedPacket >::front(), FixedSizeDeque< QueuedPacket >::popFront(), and FixedSizeDeque< QueuedPacket >::pushFront().
Copyright © GarageGames, LLC. All Rights Reserved.