ResourceManager Class Reference
Main Modules Class List Namespace List Online
ResourceManager Class Reference
#include <core/resourceManager.h>
Public Types
typedef Signal< void(const Torque::Path &path)> ChangedSignal
Public Member Functions
~ResourceManager ()
void dumpToConsole ()
ResourceBase find (const Torque::Path &path)
ChangedSignal & getChangedSignal ()
Registering with this signal will give an opportunity to handle a change to the resource on disk.
ResourceBase load (const Torque::Path &path)
ResourceBase nextResource ()
void reloadResource (const Torque::Path &path, bool showMessage=false)
ResourceBase startResourceList (ResourceBase::Signature inSignature=U32_MAX)
Static Public Member Functions
static ResourceManager & get ()
Protected Types
typedef HashTable< String, ResourceBase::Header * > ResourceHeaderMap
Protected Member Functions
ResourceManager ()
void notifiedFileChanged (const Torque::Path &path)
bool remove (ResourceBase::Header *header)
Protected Attributes
ChangedSignal mChangeSignal
ResourceHeaderMap::Iterator mIter
U32 mIterSigFilter
ResourceHeaderMap mPrevResourceHeaderMap
The map of old resources which have been replaced by new resources from a file change notification.
ResourceHeaderMap mResourceHeaderMap
The map of resources.
Member Typedef Documentation
typedef Signal<void(const Torque::Path &path)> ResourceManager::ChangedSignal
typedef HashTable<String,ResourceBase::Header*> ResourceManager::ResourceHeaderMap protected
Constructor & Destructor Documentation
ResourceManager::~ResourceManager ()
Referenced by getChangedSignal().
ResourceManager::ResourceManager () protected
Member Function Documentation
void ResourceManager::dumpToConsole ()
Referenced by getChangedSignal().
ResourceBase ResourceManager::find (const Torque::Path & path)
static ResourceManager& ResourceManager::get () static
ChangedSignal& ResourceManager::getChangedSignal () inline
Registering with this signal will give an opportunity to handle a change to the resource on disk.
For example, if a PNG file is edited by the artist and saved the ResourceManager will signal that the file has changed so the TextureManager may act appropriately - which probably means to re-init the materials using that PNG. The signal passes the Resource's signature so the callee may filter these.
References dumpToConsole(), mChangeSignal, and ~ResourceManager().
ResourceBase ResourceManager::load (const Torque::Path & path)
ResourceBase ResourceManager::nextResource ()
void ResourceManager::notifiedFileChanged (const Torque::Path & path) protected
void ResourceManager::reloadResource (const Torque::Path & path, bool showMessage = false)
bool ResourceManager::remove (ResourceBase::Header * header) protected
ResourceBase ResourceManager::startResourceList (ResourceBase::Signature inSignature = U32_MAX)
Member Data Documentation
ChangedSignal ResourceManager::mChangeSignal protected
Referenced by getChangedSignal().
ResourceHeaderMap::Iterator ResourceManager::mIter protected
U32 ResourceManager::mIterSigFilter protected
ResourceHeaderMap ResourceManager::mPrevResourceHeaderMap protected
The map of old resources which have been replaced by new resources from a file change notification.
ResourceHeaderMap ResourceManager::mResourceHeaderMap protected
The map of resources.
Copyright © GarageGames, LLC. All Rights Reserved.