AsyncWriteItem< T, Stream > Class Template Reference
Main Modules Class List Namespace List Online
AsyncWriteItem< T, Stream > Class Template Reference
Work item for writing to an output stream.
#include <platform/threads/threadPoolAsyncIO.h>
Public Types
typedef Parent::BufferType BufferType
typedef Parent::OffsetType OffsetType
typedef AsyncIOItem< T, Stream > Parent
typedef Parent::StreamType StreamType
typedef Parent::ValueType ValueType
Public Types inherited from AsyncIOItem< T, Stream >
typedef RawDataT< ValueType > BufferType
typedef U32 OffsetType
typedef WorkItem Parent
typedef Stream StreamType
typedef T ValueType
Public Types inherited from ThreadPool::WorkItem
typedef ThreadSafeRefCount< WorkItem > Parent
Public Types inherited from ThreadSafeRefCount< WorkItem >
typedef void Parent
Public Member Functions
AsyncWriteItem (StreamType *stream, U32 numElements, OffsetType offsetInStream, BufferType &buffer, bool takeOwnershipOfBuffer=true, U32 offsetInBuffer=0, ThreadContext *context=0)
Public Member Functions inherited from AsyncIOItem< T, Stream >
AsyncIOItem (StreamType *stream, U32 numElements, OffsetType offsetInStream, ThreadContext *context=0)
If the stream uses implicit positioning, then the supplied "offsetInStream" is meaningless and ignored.
AsyncIOItem (StreamType *stream, BufferType &buffer, U32 offsetInBuffer, U32 numElements, OffsetType offsetInStream, bool takeOwnershipOfBuffer=true, ThreadContext *context=0)
Construct a read item on "stream" that stores data into the given "buffer".
BufferType & getBuffer ()
Return the data buffer being written to/read from.
U32 getNumElements ()
Return the number of elements involved in the transfer.
U32 getOffsetInBuffer ()
Return the position in the data buffer at which to start the transfer.
OffsetType getOffsetInStream ()
Return the position in the stream at which to start the transfer.
StreamType * getStream ()
Return the stream being written to/read from.
Public Member Functions inherited from ThreadPool::WorkItem
WorkItem (Context *context=0)
Construct a new work item.
virtual ~WorkItem ()
Context * getContext () const
Return the work context associated with the work item.
virtual F32 getPriority ()
Return the item's base priority value.
bool hasExecuted () const
Has this work item been executed already?
virtual bool isCancellationRequested ()
Return true if the work item should be cancelled.
void process ()
Process the work item.
Public Member Functions inherited from ThreadSafeRefCount< WorkItem >
ThreadSafeRefCount ()
ThreadSafeRefCount (bool noSet)
void addRef ()
Increase the reference count on the object.
void clearLowestBit ()
U32 getRefCount () const
Get the current reference count.
bool isShared () const
void release ()
Decrease the object's reference count and delete the object, if the count drops to zero and claiming the object by the current thread succeeds.
Protected Member Functions
void _prep (StreamType *stream)
void _write (IOutputStream< T > *stream)
void _write (IOffsetOutputStream< T > *stream)
void _write (IAsyncOutputStream< T > *stream)
virtual void execute ()
Execute the actions associated with this work item.
Protected Member Functions inherited from AsyncIOItem< T, Stream >
ValueType * getBufferPtr ()
Protected Member Functions inherited from ThreadPool::WorkItem
bool cancellationPoint ()
Mark a point in a work item's execution where the item can be safely cancelled.
virtual void onCancelled ()
Called when the item has been cancelled.
Protected Attributes
void * mAsyncHandle
Handle of asynchronous write operation, if the stream implements IAsyncOutputStream.
Protected Attributes inherited from AsyncIOItem< T, Stream >
BufferType mBuffer
Buffer keeping/receiving the data elements.
U32 mNumElements
Number of elements to read from/write to the stream.
U32 mOffsetInBuffer
Offset in "mBuffer" from where to read/where to start writing to.
OffsetType mOffsetInStream
Offset in stream from where to read/where to write to.
StreamType * mStream
The stream to read from/write to.
Protected Attributes inherited from ThreadPool::WorkItem
Context * mContext
The work context of this item.
bool mExecuted
This flag is set after the execute() method has completed.
Protected Attributes inherited from ThreadSafeRefCount< WorkItem >
U32 mRefCount
Reference count and claim bit. Note that this increments in steps of two.
Additional Inherited Members
Static Public Member Functions inherited from ThreadSafeRefCount< WorkItem >
static WorkItem * safeRead (WorkItem *const volatile &refPtr)
Dereference a reference-counted pointer in a multi-thread safe way.
Static Protected Member Functions inherited from ThreadSafeRefCount< WorkItem >
static U32 decrementAndTestAndSet (U32 &refCount)
Decrement the given reference count.
Detailed Description
template<typename T, class Stream = IOffsetOutputStream< T >>
class AsyncWriteItem< T, Stream >
Work item for writing to an output stream.
The stream being written to may implement any of the given output stream interfaces. Preference is given to IAsyncOutputStream, then to IOffsetOutputStream, and only if none of these is implemented IOutputStream is used.
A useful feature is to yield ownership of the data buffer to the write item. This way, this can be pretty much used in a fire-and-forget manner where after submission, no further synchronization happens between the client and the work item.
Note
Be aware that if writing to an output stream that has an implicit position property, multiple concurrent writes will interfere with each other.
Member Typedef Documentation
template<typename T , class Stream = IOffsetOutputStream< T >> typedef Parent::BufferType AsyncWriteItem< T, Stream >::BufferType
template<typename T , class Stream = IOffsetOutputStream< T >> typedef Parent::OffsetType AsyncWriteItem< T, Stream >::OffsetType
template<typename T , class Stream = IOffsetOutputStream< T >> typedef AsyncIOItem< T, Stream > AsyncWriteItem< T, Stream >::Parent
template<typename T , class Stream = IOffsetOutputStream< T >> typedef Parent::StreamType AsyncWriteItem< T, Stream >::StreamType
template<typename T , class Stream = IOffsetOutputStream< T >> typedef Parent::ValueType AsyncWriteItem< T, Stream >::ValueType
Constructor & Destructor Documentation
template<typename T , class Stream = IOffsetOutputStream< T >> AsyncWriteItem< T, Stream >::AsyncWriteItem (StreamType * stream, U32 numElements, OffsetType offsetInStream, BufferType & buffer, bool takeOwnershipOfBuffer = true, U32 offsetInBuffer = 0, ThreadContext * context = 0) inline
Member Function Documentation
template<typename T , class Stream = IOffsetOutputStream< T >> void AsyncWriteItem< T, Stream >::_prep (StreamType * stream) inline protected
References AsyncIOItem< T, Stream >::getBufferPtr(), AsyncIOItem< T, Stream >::getNumElements(), and IAsyncOutputStream< T, Offset >::issueWriteAt().
template<typename T , class Stream = IOffsetOutputStream< T >> void AsyncWriteItem< T, Stream >::_write (IOutputStream< T > * stream) inline protected
References AsyncIOItem< T, Stream >::getBufferPtr(), AsyncIOItem< T, Stream >::getNumElements(), and IOutputStream< T >::write().
template<typename T , class Stream = IOffsetOutputStream< T >> void AsyncWriteItem< T, Stream >::_write (IOffsetOutputStream< T > * stream) inline protected
References AsyncIOItem< T, Stream >::getBufferPtr(), AsyncIOItem< T, Stream >::getNumElements(), AsyncIOItem< T, Stream >::getOffsetInStream(), and IOffsetOutputStream< T, Offset >::writeAt().
template<typename T , class Stream = IOffsetOutputStream< T >> void AsyncWriteItem< T, Stream >::_write (IAsyncOutputStream< T > * stream) inline protected
References IAsyncOutputStream< T, Offset >::tryCompleteWriteAt().
template<typename T , class Stream > void AsyncWriteItem< T, Stream >::execute () protected virtual
Execute the actions associated with this work item.
This is the primary function to implement by subclasses.
Implements ThreadPool::WorkItem.
References ThreadPool::WorkItem::cancellationPoint(), and AsyncIOItem< T, Stream >::getStream().
Member Data Documentation
template<typename T , class Stream = IOffsetOutputStream< T >> void* AsyncWriteItem< T, Stream >::mAsyncHandle protected
Handle of asynchronous write operation, if the stream implements IAsyncOutputStream.
Copyright © GarageGames, LLC. All Rights Reserved.