ForestItem Class Reference
Main Modules Class List Namespace List Online
ForestItem Class Reference
#include <forest/forestItem.h>
Public Member Functions
ForestItem ()
If we're currently being effected by one or more wind emitters then we hold the results in this class.
~ForestItem ()
bool canBillboard (const SceneRenderState *state, F32 distToCamera) const
Point3F getCenterPoint () const
ForestItemData * getData () const
const ForestItemKey & getKey () const
const Box3F & getObjBox () const
Point3F getPosition () const
F32 getRadius () const
F32 getScale () const
Point3F getSize () const
F32 getSqDistanceToPoint (const Point2F &point) const
const MatrixF & getTransform () const
const Box3F & getWorldBox () const
bool isValid () const
Returns true if this is a valid item.
void makeInvalid ()
Invalidates the item.
bool operator!= (const ForestItem &) const
bool operator== (const ForestItem &) const
void setData (ForestItemData *data)
void setKey (const ForestItemKey &key)
void setTransform (const MatrixF &xfm, F32 scale)
bool castRay (const Point3F &start, const Point3F &end, RayInfo *outInfo, bool rendered) const
Collision.
bool buildPolyList (AbstractPolyList *polyList, const Box3F &box, const SphereF &sphere) const
Static Public Attributes
static const ForestItem Invalid
Protected Attributes
ForestItemData * mDataBlock
ForestItemKey mKey
F32 mRadius
F32 mScale
MatrixF mTransform
Box3F mWorldBox
Constructor & Destructor Documentation
ForestItem::ForestItem ()
If we're currently being effected by one or more wind emitters then we hold the results in this class.
ForestItem::~ForestItem ()
Member Function Documentation
bool ForestItem::buildPolyList (AbstractPolyList * polyList, const Box3F & box, const SphereF & sphere) const
bool ForestItem::canBillboard (const SceneRenderState * state, F32 distToCamera) const inline
References ForestItemData::canBillboard().
bool ForestItem::castRay (const Point3F & start, const Point3F & end, RayInfo * outInfo, bool rendered) const
Collision.
Point3F ForestItem::getCenterPoint () const inline
References Box3F::getCenter().
ForestItemData* ForestItem::getData () const inline
const ForestItemKey& ForestItem::getKey () const inline
const Box3F& ForestItem::getObjBox () const inline
References ForestItemData::getObjBox().
Point3F ForestItem::getPosition () const inline
References MatrixF::getPosition().
F32 ForestItem::getRadius () const inline
References ForestItemData::mRadius.
F32 ForestItem::getScale () const inline
Point3F ForestItem::getSize () const inline
References Box3F::getExtents(), ForestItemData::getObjBox(), Point3F::One, and Box3F::scale().
F32 ForestItem::getSqDistanceToPoint (const Point2F & point) const inline
const MatrixF& ForestItem::getTransform () const inline
const Box3F& ForestItem::getWorldBox () const inline
bool ForestItem::isValid () const inline
Returns true if this is a valid item.
void ForestItem::makeInvalid () inline
Invalidates the item.
bool ForestItem::operator!= (const ForestItem & _test) const inline
References mKey.
bool ForestItem::operator== (const ForestItem & _test) const inline
References mKey.
void ForestItem::setData (ForestItemData * data)
void ForestItem::setKey (const ForestItemKey & key) inline
void ForestItem::setTransform (const MatrixF & xfm, F32 scale)
Member Data Documentation
const ForestItem ForestItem::Invalid static
ForestItemData* ForestItem::mDataBlock protected
ForestItemKey ForestItem::mKey protected
Referenced by operator!=(), and operator==().
F32 ForestItem::mRadius protected
F32 ForestItem::mScale protected
MatrixF ForestItem::mTransform protected
Box3F ForestItem::mWorldBox protected
Copyright © GarageGames, LLC. All Rights Reserved.