BtWorld Class Reference
Main Modules Class List Namespace List Online
BtWorld Class Reference
#include <T3D/physics/bullet/btWorld.h>
Public Member Functions
BtWorld ()
virtual ~BtWorld ()
virtual bool castRay (const Point3F &startPnt, const Point3F &endPnt, RayInfo *ri, const Point3F &impulse)
An abstract way to raycast into any type of PhysicsWorld, in a way that mirrors a Torque-style raycast.
virtual PhysicsBody * castRay (const Point3F &start, const Point3F &end, U32 bodyTypes)
virtual void destroyWorld ()
Tears down the physics world destroying any existing bodies, joints, and controllers.
virtual void explosion (const Point3F &pos, F32 radius, F32 forceMagnitude)
btDynamicsWorld * getDynamicsWorld () const
const F32 getEditorTimeScale () const
bool getEnabled () const
void getPhysicsResults ()
virtual bool initWorld (bool isServer, ProcessList *processList)
Prepare the physics world for use.
virtual bool isEnabled () const
Returns true if the physics world is active and simulating.
bool isWritable () const
virtual void onDebugDraw (const SceneRenderState *state)
Overloaded to do debug drawing.
virtual void reset ()
void setEditorTimeScale (F32 timeScale)
void setEnabled (bool enabled)
void tickPhysics (U32 elapsedMs)
Public Member Functions inherited from PhysicsWorld
PhysicsWorld ()
The constructor.
virtual ~PhysicsWorld ()
The destructor.
const Point3F & getGravity () const
Returns the active gravity force.
Signal< void()> & getStaticChangedSignal ()
Signal< void()> & getUpdateSignal ()
Protected Member Functions
void _destroy ()
Protected Attributes
btBroadphaseInterface * mBroadphase
btDefaultCollisionConfiguration * mCollisionConfiguration
BtDebugDraw mDebugDraw
btCollisionDispatcher * mDispatcher
btDynamicsWorld * mDynamicsWorld
F32 mEditorTimeScale
bool mErrorReport
bool mIsEnabled
bool mIsSimulating
ProcessList * mProcessList
btConstraintSolver * mSolver
U32 mTickCount
Protected Attributes inherited from PhysicsWorld
Point3F mGravity
The current gravity force.
Signal< void()> mStaticChangedSignal
Signal< void()> mUpdateSignal
Additional Inherited Members
Public Types inherited from PhysicsWorld
enum BodyType {
BT_Static = BIT(0),
BT_Dynamic = BIT(1),
BT_Player = BIT(2),
BT_All = BT_Static | BT_Dynamic | BT_Player
}
Static Public Attributes inherited from PhysicsWorld
static U32 smPhysicsMaxSubSteps
static F32 smPhysicsStepTime
Physics timing.
Constructor & Destructor Documentation
BtWorld::BtWorld ()
virtual BtWorld::~BtWorld () virtual
Member Function Documentation
void BtWorld::_destroy () protected
virtual bool BtWorld::castRay (const Point3F & startPnt, const Point3F & endPnt, RayInfo * ri, const Point3F & impulse) virtual
An abstract way to raycast into any type of PhysicsWorld, in a way that mirrors a Torque-style raycast.
This method is not fully developed or very sophisticated. For example, there is no system of collision groups or raycast masks, which could be very complex to write in a PhysicsPlugin-Abstract way...
Implements PhysicsWorld.
virtual PhysicsBody* BtWorld::castRay (const Point3F & start, const Point3F & end, U32 bodyTypes) virtual
Implements PhysicsWorld.
virtual void BtWorld::destroyWorld () virtual
Tears down the physics world destroying any existing bodies, joints, and controllers.
Implements PhysicsWorld.
virtual void BtWorld::explosion (const Point3F & pos, F32 radius, F32 forceMagnitude) virtual
Implements PhysicsWorld.
btDynamicsWorld* BtWorld::getDynamicsWorld () const inline
References getPhysicsResults(), mDynamicsWorld, and tickPhysics().
const F32 BtWorld::getEditorTimeScale () const inline
References mEditorTimeScale.
bool BtWorld::getEnabled (void) const inline
References mIsEnabled.
void BtWorld::getPhysicsResults ()
Referenced by getDynamicsWorld().
virtual bool BtWorld::initWorld (bool isServer, ProcessList * processList) virtual
Prepare the physics world for use.
Implements PhysicsWorld.
virtual bool BtWorld::isEnabled () const inline virtual
Returns true if the physics world is active and simulating.
Implements PhysicsWorld.
References mIsEnabled.
bool BtWorld::isWritable () const inline
References mIsSimulating, and setEnabled().
virtual void BtWorld::onDebugDraw (const SceneRenderState * state) virtual
Overloaded to do debug drawing.
It is assumed the GFX state is setup prior to this call for rendering in world space.
Implements PhysicsWorld.
virtual void BtWorld::reset () virtual
Implements PhysicsWorld.
void BtWorld::setEditorTimeScale (F32 timeScale) inline
void BtWorld::setEnabled (bool enabled)
Referenced by isWritable().
void BtWorld::tickPhysics (U32 elapsedMs)
Referenced by getDynamicsWorld().
Member Data Documentation
btBroadphaseInterface* BtWorld::mBroadphase protected
btDefaultCollisionConfiguration* BtWorld::mCollisionConfiguration protected
BtDebugDraw BtWorld::mDebugDraw protected
btCollisionDispatcher* BtWorld::mDispatcher protected
btDynamicsWorld* BtWorld::mDynamicsWorld protected
Referenced by getDynamicsWorld().
F32 BtWorld::mEditorTimeScale protected
Referenced by getEditorTimeScale().
bool BtWorld::mErrorReport protected
bool BtWorld::mIsEnabled protected
Referenced by getEnabled(), and isEnabled().
bool BtWorld::mIsSimulating protected
Referenced by isWritable().
ProcessList* BtWorld::mProcessList protected
btConstraintSolver* BtWorld::mSolver protected
U32 BtWorld::mTickCount protected
Copyright © GarageGames, LLC. All Rights Reserved.