AssetPtrBase Class Reference
Main Modules Class List Namespace List Online
AssetPtrBase Class Reference abstract
#include <assets/assetPtr.h>
Public Member Functions
AssetPtrBase ()
virtual ~AssetPtrBase ()
virtual void clear (void)=0
Referencing.
virtual StringTableEntry getAssetId (void) const =0
virtual StringTableEntry getAssetType (void) const =0
virtual bool isAssetId (const char *pAssetId) const =0
virtual bool isNull (void) const =0
Validity.
virtual bool notNull (void) const =0
void registerRefreshNotify (AssetPtrCallback *pCallback)
Notification.
virtual void setAssetId (const char *pAssetId)=0
void unregisterRefreshNotify (void)
Constructor & Destructor Documentation
AssetPtrBase::AssetPtrBase () inline
virtual AssetPtrBase::~AssetPtrBase () inline virtual
Member Function Documentation
virtual void AssetPtrBase::clear (void) pure virtual
Referencing.
Implemented in AssetPtr< T >, and AssetPtr< ShapeAsset >.
virtual StringTableEntry AssetPtrBase::getAssetId (void) const pure virtual
Implemented in AssetPtr< T >, and AssetPtr< ShapeAsset >.
virtual StringTableEntry AssetPtrBase::getAssetType (void) const pure virtual
Implemented in AssetPtr< T >, and AssetPtr< ShapeAsset >.
virtual bool AssetPtrBase::isAssetId (const char * pAssetId) const pure virtual
Implemented in AssetPtr< T >, and AssetPtr< ShapeAsset >.
virtual bool AssetPtrBase::isNull (void) const pure virtual
Validity.
Implemented in AssetPtr< T >, and AssetPtr< ShapeAsset >.
virtual bool AssetPtrBase::notNull (void) const pure virtual
Implemented in AssetPtr< T >, and AssetPtr< ShapeAsset >.
void AssetPtrBase::registerRefreshNotify (AssetPtrCallback * pCallback) inline
Notification.
References SimObject::isProperlyAdded(), and AssetManager::registerAssetPtrRefreshNotify().
virtual void AssetPtrBase::setAssetId (const char * pAssetId) pure virtual
Implemented in AssetPtr< T >, and AssetPtr< ShapeAsset >.
void AssetPtrBase::unregisterRefreshNotify (void) inline
References SimObject::isProperlyAdded(), and AssetManager::unregisterAssetPtrRefreshNotify().
Copyright © GarageGames, LLC. All Rights Reserved.