BtBody Class Reference
Main Modules Class List Namespace List Online
BtBody Class Reference
#include <T3D/physics/bullet/btBody.h>
Public Member Functions
BtBody ()
virtual ~BtBody ()
virtual void applyCorrection (const MatrixF &xfm)
virtual void applyForce (const Point3F &force)
virtual void applyImpulse (const Point3F &origin, const Point3F &force)
virtual void applyTorque (const Point3F &torque)
virtual void findContact (SceneObject **contactObject, VectorF *contactNormal, Vector< SceneObject * > *outOverlapObjects) const
virtual Point3F getAngVelocity () const
virtual Point3F getCMassPosition () const
virtual PhysicsCollision * getColShape ()
Returns the collision shape used to create the body.
virtual Point3F getLinVelocity () const
virtual F32 getMass () const
virtual void getState (PhysicsState *outState)
virtual MatrixF & getTransform (MatrixF *outMatrix)
Returns the transform of the physics body at the last processed simulation tick.
virtual PhysicsWorld * getWorld ()
Returns the physics world this object is a member of.
virtual Box3F getWorldBounds ()
Returns the world aligned bounding box containing the PhysicsObject.
virtual bool init (PhysicsCollision *shape, F32 mass, U32 bodyFlags, SceneObject *obj, PhysicsWorld *world)
Initialize the body with a collision shape and basic physics properties.
virtual bool isDynamic () const
Returns true if the object is a dynamic rigid body animated by the physics simulation.
virtual bool isSimulationEnabled ()
virtual void moveKinematicTo (const MatrixF &xfm)
virtual void setAngVelocity (const Point3F &vel)
virtual void setDamping (F32 linear, F32 angular)
virtual void setLinVelocity (const Point3F &vel)
virtual void setMaterial (F32 restitution, F32 friction, F32 staticFriction)
virtual void setSimulationEnabled (bool enabled)
Set false to skip simulation of this object or temporarily remove it from the physics simulation.
virtual void setSleeping (bool sleeping)
virtual void setSleepThreshold (F32 linear, F32 angular)
virtual void setTransform (const MatrixF &xfm)
Sets the transform on the physics object.
Public Member Functions inherited from PhysicsBody
virtual ~PhysicsBody ()
Public Member Functions inherited from PhysicsObject
virtual ~PhysicsObject ()
const PhysicsUserData & getUserData () const
PhysicsUserData & getUserData ()
void queueCallback (U32 ms, Delegate< void()> callback)
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Protected Member Functions
void _releaseActor ()
Protected Member Functions inherited from PhysicsObject
PhysicsObject ()
You shouldn't be creating this object directly.
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Protected Attributes
btRigidBody * mActor
The physics actor.
MatrixF * mCenterOfMass
The center of mass offset used if the graphical transform is not at the mass center.
StrongRefPtr< BtCollision > mColShape
The collision representation.
btCompoundShape * mCompound
Our local compound if we had to adjust the mass center on a dynamic.
MatrixF * mInvCenterOfMass
The inverse center of mass offset.
bool mIsDynamic
bool mIsEnabled
Is the body participating in the physics simulation.
F32 mMass
BtWorld * mWorld
The physics world we are in.
Protected Attributes inherited from PhysicsObject
U32 mQueuedEvent
The last queued callback event.
PhysicsUserData mUserData
The user data object assigned to this object.
Additional Inherited Members
Public Types inherited from PhysicsBody
enum {
BF_TRIGGER = BIT(0),
BF_KINEMATIC = BIT(1),
BF_DEBRIS = BIT(2)
}
Constructor & Destructor Documentation
BtBody::BtBody ()
virtual BtBody::~BtBody () virtual
Member Function Documentation
void BtBody::_releaseActor () protected
virtual void BtBody::applyCorrection (const MatrixF & xfm) virtual
Implements PhysicsBody.
Referenced by getMass().
virtual void BtBody::applyForce (const Point3F & force) virtual
Implements PhysicsBody.
Referenced by getMass().
virtual void BtBody::applyImpulse (const Point3F & origin, const Point3F & force) virtual
Implements PhysicsBody.
Referenced by getMass().
virtual void BtBody::applyTorque (const Point3F & torque) virtual
Implements PhysicsBody.
Referenced by getMass().
virtual void BtBody::findContact (SceneObject ** contactObject, VectorF * contactNormal, Vector< SceneObject * > * outOverlapObjects) const virtual
Implements PhysicsBody.
Referenced by getMass().
virtual Point3F BtBody::getAngVelocity () const virtual
Implements PhysicsBody.
Referenced by getMass().
virtual Point3F BtBody::getCMassPosition () const virtual
Implements PhysicsBody.
Referenced by getMass().
virtual PhysicsCollision* BtBody::getColShape () virtual
Returns the collision shape used to create the body.
Implements PhysicsBody.
Referenced by isDynamic().
virtual Point3F BtBody::getLinVelocity () const virtual
Implements PhysicsBody.
Referenced by getMass().
virtual F32 BtBody::getMass () const inline virtual
Implements PhysicsBody.
References applyCorrection(), applyForce(), applyImpulse(), applyTorque(), findContact(), getAngVelocity(), getCMassPosition(), getLinVelocity(), mMass, moveKinematicTo(), setAngVelocity(), setLinVelocity(), setMaterial(), and setSleeping().
virtual void BtBody::getState (PhysicsState * outState) virtual
Implements PhysicsBody.
Referenced by isDynamic().
virtual MatrixF& BtBody::getTransform (MatrixF * outMatrix) virtual
Returns the transform of the physics body at the last processed simulation tick.
Implements PhysicsObject.
virtual PhysicsWorld* BtBody::getWorld () virtual
Returns the physics world this object is a member of.
Implements PhysicsObject.
virtual Box3F BtBody::getWorldBounds () virtual
Returns the world aligned bounding box containing the PhysicsObject.
Implements PhysicsObject.
virtual bool BtBody::init (PhysicsCollision * shape, F32 mass, U32 bodyFlags, SceneObject * obj, PhysicsWorld * world) virtual
Initialize the body with a collision shape and basic physics properties.
Implements PhysicsBody.
Referenced by isSimulationEnabled().
virtual bool BtBody::isDynamic () const inline virtual
Returns true if the object is a dynamic rigid body animated by the physics simulation.
Kinematics are not considered to be dynamic.
Implements PhysicsBody.
References getColShape(), getState(), mIsDynamic, setDamping(), and setSleepThreshold().
virtual bool BtBody::isSimulationEnabled () inline virtual
Implements PhysicsObject.
References init(), and mIsEnabled.
virtual void BtBody::moveKinematicTo (const MatrixF & xfm) virtual
Implements PhysicsBody.
Referenced by getMass().
virtual void BtBody::setAngVelocity (const Point3F & vel) virtual
Implements PhysicsBody.
Referenced by getMass().
virtual void BtBody::setDamping (F32 linear, F32 angular) virtual
Implements PhysicsBody.
Referenced by isDynamic().
virtual void BtBody::setLinVelocity (const Point3F & vel) virtual
Implements PhysicsBody.
Referenced by getMass().
virtual void BtBody::setMaterial (F32 restitution, F32 friction, F32 staticFriction) virtual
Implements PhysicsBody.
Referenced by getMass().
virtual void BtBody::setSimulationEnabled (bool enabled) virtual
Set false to skip simulation of this object or temporarily remove it from the physics simulation.
Implementation is PhysicsPlugin specific.
Implements PhysicsObject.
virtual void BtBody::setSleeping (bool sleeping) virtual
Implements PhysicsBody.
Referenced by getMass().
virtual void BtBody::setSleepThreshold (F32 linear, F32 angular) virtual
Implements PhysicsBody.
Referenced by isDynamic().
virtual void BtBody::setTransform (const MatrixF & transform) virtual
Sets the transform on the physics object.
For static objects this is only intended to be used for for infrequent changes when editing the mission.
Implements PhysicsObject.
Member Data Documentation
btRigidBody* BtBody::mActor protected
The physics actor.
MatrixF* BtBody::mCenterOfMass protected
The center of mass offset used if the graphical transform is not at the mass center.
StrongRefPtr<BtCollision> BtBody::mColShape protected
The collision representation.
btCompoundShape* BtBody::mCompound protected
Our local compound if we had to adjust the mass center on a dynamic.
MatrixF* BtBody::mInvCenterOfMass protected
The inverse center of mass offset.
bool BtBody::mIsDynamic protected
Referenced by isDynamic().
bool BtBody::mIsEnabled protected
Is the body participating in the physics simulation.
Referenced by isSimulationEnabled().
F32 BtBody::mMass protected
Referenced by getMass().
BtWorld* BtBody::mWorld protected
The physics world we are in.
Copyright © GarageGames, LLC. All Rights Reserved.