ConsoleStackFrameSaver Class Reference
Main Modules Class List Namespace List Online
ConsoleStackFrameSaver Class Reference
Console System
Utility class to save and restore the current console stack frame.
#include <console/console.h>
Public Member Functions
ConsoleStackFrameSaver ()
~ConsoleStackFrameSaver ()
void restore ()
void save ()
Public Attributes
bool mSaved
Detailed Description
Utility class to save and restore the current console stack frame.
Constructor & Destructor Documentation
ConsoleStackFrameSaver::ConsoleStackFrameSaver () inline
ConsoleStackFrameSaver::~ConsoleStackFrameSaver () inline
Member Function Documentation
void ConsoleStackFrameSaver::restore ()
void ConsoleStackFrameSaver::save ()
Referenced by _EngineConsoleCallbackHelper::call(), _EngineConsoleExecCallbackHelper< P1 >::call(), and _EngineConsoleExecCallbackHelper< const char * >::call().
Member Data Documentation
bool ConsoleStackFrameSaver::mSaved
Copyright © GarageGames, LLC. All Rights Reserved.