PlatformCursorController Class Reference
Main Modules Class List Namespace List Online
PlatformCursorController Class Reference abstract
#include <windowManager/platformCursorController.h>
Classes
struct Cursor_Shape
Public Types
enum {
curArrow = 0,
curWait,
curPlus,
curResizeVert,
curResizeHorz,
curResizeAll,
curIBeam,
curResizeNESW,
curResizeNWSE,
curHand
}
Public Member Functions
PlatformCursorController (PlatformWindow *owner)
virtual ~PlatformCursorController ()
virtual void getCursorPosition (Point2I &point)=0
virtual S32 getDoubleClickHeight ()=0
virtual U32 getDoubleClickTime ()=0
virtual S32 getDoubleClickWidth ()=0
virtual bool isCursorVisible ()=0
virtual void popCursor ()
virtual void pushCursor (S32 cursorID)
virtual void pushCursor (const UTF8 *fileName)
virtual void refreshCursor ()
virtual void setCursorPosition (S32 x, S32 y)=0
virtual void setCursorShape (const Cursor_Shape &shape, bool reload)
virtual void setCursorShape (U32 cursorID)=0
virtual void setCursorShape (const UTF8 *filename, bool reload)=0
virtual void setCursorVisible (bool visible)=0
Protected Attributes
Vector< Cursor_Shape > mCursors
PlatformWindow * mOwner
The PlatformWindow that owns this Cursor Controller.
Member Enumeration Documentation
anonymous enum
Enumerator
curArrow
curWait
curPlus
curResizeVert
curResizeHorz
curResizeAll
curIBeam
curResizeNESW
curResizeNWSE
curHand
Constructor & Destructor Documentation
PlatformCursorController::PlatformCursorController (PlatformWindow * owner) inline
virtual PlatformCursorController::~PlatformCursorController () inline virtual
Member Function Documentation
virtual void PlatformCursorController::getCursorPosition (Point2I & point) pure virtual
Implemented in Win32CursorController, MacCursorController, and PlatformCursorControllerSDL.
Referenced by PlatformWindow::getCursorPosition().
virtual S32 PlatformCursorController::getDoubleClickHeight () pure virtual
Implemented in Win32CursorController, MacCursorController, and PlatformCursorControllerSDL.
virtual U32 PlatformCursorController::getDoubleClickTime () pure virtual
Implemented in Win32CursorController, MacCursorController, and PlatformCursorControllerSDL.
virtual S32 PlatformCursorController::getDoubleClickWidth () pure virtual
Implemented in Win32CursorController, MacCursorController, and PlatformCursorControllerSDL.
virtual bool PlatformCursorController::isCursorVisible () pure virtual
Implemented in Win32CursorController, MacCursorController, and PlatformCursorControllerSDL.
Referenced by PlatformWindow::isCursorVisible().
virtual void PlatformCursorController::popCursor () virtual
virtual void PlatformCursorController::pushCursor (S32 cursorID) virtual
Referenced by MacCursorController::MacCursorController(), PlatformCursorControllerSDL::PlatformCursorControllerSDL(), and Win32CursorController::Win32CursorController().
virtual void PlatformCursorController::pushCursor (const UTF8 * fileName) virtual
virtual void PlatformCursorController::refreshCursor () virtual
virtual void PlatformCursorController::setCursorPosition (S32 x, S32 y) pure virtual
Implemented in Win32CursorController, MacCursorController, and PlatformCursorControllerSDL.
Referenced by PlatformWindow::setCursorPosition().
virtual void PlatformCursorController::setCursorShape (const Cursor_Shape & shape, bool reload) virtual
virtual void PlatformCursorController::setCursorShape (U32 cursorID) pure virtual
Implemented in Win32CursorController, MacCursorController, and PlatformCursorControllerSDL.
virtual void PlatformCursorController::setCursorShape (const UTF8 * filename, bool reload) pure virtual
Implemented in Win32CursorController, MacCursorController, and PlatformCursorControllerSDL.
virtual void PlatformCursorController::setCursorVisible (bool visible) pure virtual
Implemented in Win32CursorController, MacCursorController, and PlatformCursorControllerSDL.
Referenced by PlatformWindow::setCursorVisible().
Member Data Documentation
Vector<Cursor_Shape> PlatformCursorController::mCursors protected
PlatformWindow* PlatformCursorController::mOwner protected
The PlatformWindow that owns this Cursor Controller.
Copyright © GarageGames, LLC. All Rights Reserved.