GBufferConditionerGLSL Class Reference
Main Modules Class List Namespace List Online
GBufferConditionerGLSL Class Reference
#include <lighting/advanced/glsl/gBufferConditionerGLSL.h>
Public Types
enum NormalSpace {
WorldSpace,
ViewSpace
}
enum NormalStorage {
CartesianXYZ,
CartesianXY,
Spherical,
LambertAzimuthal
}
Public Types inherited from ConditionerFeature
enum MethodType {
ConditionMethod = 0,
UnconditionMethod,
NumMethodTypes
}
Public Types inherited from ShaderFeature
enum OutputTarget {
DefaultTarget = 1 << 0,
RenderTarget1 = 1 << 1,
RenderTarget2 = 1 << 2,
RenderTarget3 = 1 << 3
}
Public Member Functions
GBufferConditionerGLSL (const GFXFormat bufferFormat, const NormalSpace nrmSpace)
virtual ~GBufferConditionerGLSL ()
virtual String getName ()
Returns the name of this feature.
virtual Resources getResources (const MaterialFeatureData &fd)
Returns the resource requirements of this feature based on what other features are present.
virtual void processPix (Vector< ShaderComponent * > &componentList, const MaterialFeatureData &fd)
virtual void processVert (Vector< ShaderComponent * > &componentList, const MaterialFeatureData &fd)
Public Member Functions inherited from ConditionerFeature
ConditionerFeature (const GFXFormat bufferFormat)
virtual ~ConditionerFeature ()
virtual LangElement * assignColor (LangElement *elem, Material::BlendOp blend, LangElement *lerpElem=NULL, ShaderFeature::OutputTarget outputTarget=ShaderFeature::DefaultTarget)
Helper function for applying the color to shader output.
virtual LangElement * assignOutput (Var *unconditionedOutput, ShaderFeature::OutputTarget outputTarget=ShaderFeature::DefaultTarget)
virtual LangElement * expandNormalMap (LangElement *sampleNormalOp, LangElement *normalDecl, LangElement *normalVar, const MaterialFeatureData &fd)
Expand and assign a normal map. This takes care of compressed normal maps as well.
virtual Material::BlendOp getBlendOp ()
Identifies what type of blending a feature uses.
virtual GFXFormat getBufferFormat () const
virtual ConditionerMethodDependency * getConditionerMethodDependency (MethodType methodType)
virtual const String & getShaderMethodName (MethodType methodType)
virtual Var * getVertTexCoord (const String &name)
Get the incoming base texture coords - useful for bumpmap and detail maps.
virtual bool setBufferFormat (const GFXFormat bufferFormat)
virtual LangElement * setupTexSpaceMat (Vector< ShaderComponent * > &componentList, Var **texSpaceMat)
Set up a texture space matrix - to pass into pixel shader.
Public Member Functions inherited from ShaderFeature
ShaderFeature ()
virtual ~ShaderFeature ()
virtual void addDependency (const ShaderDependency *depends)
Adds a dependency to this shader feature.
virtual ShaderFeatureConstHandles * createConstHandles (GFXShader *shader, SimObject *userObject)
virtual void determineFeature (Material *material, const GFXVertexFormat *vertexFormat, U32 stageNum, const FeatureType &type, const FeatureSet &features, MaterialFeatureData *outFeatureData)
virtual const Vector< const ShaderDependency * > & getDependencies () const
Gets the dependency list for this shader feature.
LangElement * getOutput () const
returns output from a processed vertex or pixel shader
virtual U32 getOutputTargets (const MaterialFeatureData &fd) const
Gets the render target this shader feature is assigning data to.
const char * getOutputTargetVarName (OutputTarget target=DefaultTarget) const
Returns the name of output targer var.
virtual const char * getOutputVarName () const
Returns the output variable name for this feature if it applies.
S32 getProcessIndex () const
virtual void processPixMacros (Vector< GFXShaderMacro > &macros, const MaterialFeatureData &fd)
Allows the feature to add macros to pixel shader compiles.
virtual void processVertMacros (Vector< GFXShaderMacro > &macros, const MaterialFeatureData &fd)
Allows the feature to add macros to vertex shader compiles.
virtual void reset ()
Called after processing the vertex and processing the pixel to cleanup any temporary structures stored in the feature.
void setInstancingFormat (GFXVertexFormat *format)
void setProcessIndex (S32 index)
virtual void setTexData (Material::StageData &stageDat, const MaterialFeatureData &fd, RenderPassData &passData, U32 &texIndex)
Fills texture related info in RenderPassData for this feature.
Protected Member Functions
virtual Var * _conditionOutput (Var *unconditionedOutput, MultiLine *meta)
virtual GenOp * _posnegDecode (GenOp *val)
virtual GenOp * _posnegEncode (GenOp *val)
virtual Var * _unconditionInput (Var *conditionedInput, MultiLine *meta)
virtual Var * printMethodHeader (MethodType methodType, const String &methodName, Stream &stream, MultiLine *meta)
Protected Member Functions inherited from ConditionerFeature
void _print (Stream *stream)
virtual void _printMethod (MethodType methodType, const String &methodName, Stream &stream)
virtual void printFooterComment (MethodType methodType, const String &methodName, Stream &stream, MultiLine *meta)
virtual void printHeaderComment (MethodType methodType, const String &methodName, Stream &stream, MultiLine *meta)
virtual void printMethodFooter (MethodType methodType, Var *retVar, Stream &stream, MultiLine *meta)
Protected Attributes
U32 mBitsPerChannel
bool mCanWriteNegativeValues
NormalStorage mNormalStorageType
Protected Attributes inherited from ConditionerFeature
GFXFormat mBufferFormat
String mConditionMethodName
ConditionerMethodDependency * mMethodDependency [NumMethodTypes]
String mShaderIncludePath
String mUnconditionMethodName
Protected Attributes inherited from ShaderFeature
Vector< const ShaderDependency * > mDependencies
The list of unique shader dependencies.
S32 mProcessIndex
LangElement * output
Additional Inherited Members
Static Public Member Functions inherited from ConditionerFeature
static void updateConditioners ()
Static Public Member Functions inherited from ShaderFeature
static Var * findOrCreateLocal (const char *name, const char *type, MultiLine *multi)
A simpler helper function which either finds the existing local var or creates one.
Public Attributes inherited from ShaderFeature
GFXVertexFormat * mInstancingFormat
const GFXVertexFormat * mVertexFormat
Static Public Attributes inherited from ConditionerFeature
static const String ConditionerIncludeFileName
Static Protected Member Functions inherited from ConditionerFeature
static void _updateConditioners ()
Static Protected Attributes inherited from ConditionerFeature
static Vector< ConditionerFeature * > smConditioners
static bool smDirtyConditioners
Member Enumeration Documentation
enum GBufferConditionerGLSL::NormalSpace
Enumerator
WorldSpace
ViewSpace
enum GBufferConditionerGLSL::NormalStorage
Enumerator
CartesianXYZ
CartesianXY
Spherical
LambertAzimuthal
Constructor & Destructor Documentation
GBufferConditionerGLSL::GBufferConditionerGLSL (const GFXFormat bufferFormat, const NormalSpace nrmSpace)
virtual GBufferConditionerGLSL::~GBufferConditionerGLSL () virtual
Member Function Documentation
virtual Var* GBufferConditionerGLSL::_conditionOutput (Var * unconditionedOutput, MultiLine * meta) protected virtual
Reimplemented from ConditionerFeature.
Referenced by getName().
virtual GenOp* GBufferConditionerGLSL::_posnegDecode (GenOp * val) protected virtual
Referenced by getName().
virtual GenOp* GBufferConditionerGLSL::_posnegEncode (GenOp * val) protected virtual
Referenced by getName().
virtual Var* GBufferConditionerGLSL::_unconditionInput (Var * conditionedInput, MultiLine * meta) protected virtual
Reimplemented from ConditionerFeature.
Referenced by getName().
virtual String GBufferConditionerGLSL::getName () inline virtual
Returns the name of this feature.
Implements ShaderFeature.
References _conditionOutput(), _posnegDecode(), _posnegEncode(), _unconditionInput(), and printMethodHeader().
virtual Resources GBufferConditionerGLSL::getResources (const MaterialFeatureData & fd) virtual
Returns the resource requirements of this feature based on what other features are present.
The "resources" are things such as texture units, and texture registers of which there can be very limited numbers. The resources can vary depending on hardware and what other features are present.
Reimplemented from ShaderFeature.
virtual Var* GBufferConditionerGLSL::printMethodHeader (MethodType methodType, const String & methodName, Stream & stream, MultiLine * meta) protected virtual
Reimplemented from ConditionerFeature.
Referenced by getName().
virtual void GBufferConditionerGLSL::processPix (Vector< ShaderComponent * > & componentList, const MaterialFeatureData & fd) virtual
Process pixel shader - This function is used by each feature to generate a list of LangElements that can be traversed and "printed" to generate the actual shader code. The 'output' member is the head of that list.
The componentList is used mostly for access to the "Connector" structure which is used to pass data from the vertex to the pixel shader.
The MaterialFeatureData parameter is used to determine what other features are present for the shader being generated.
Reimplemented from ShaderFeature.
virtual void GBufferConditionerGLSL::processVert (Vector< ShaderComponent * > & componentList, const MaterialFeatureData & fd) virtual
Process vertex shader - This function is used by each feature to generate a list of LangElements that can be traversed and "printed" to generate the actual shader code. The 'output' member is the head of that list.
The componentList is used mostly for access to the "Connector" structure which is used to pass data from the vertex to the pixel shader.
The MaterialFeatureData parameter is used to determine what other features are present for the shader being generated.
Reimplemented from ShaderFeature.
Member Data Documentation
U32 GBufferConditionerGLSL::mBitsPerChannel protected
bool GBufferConditionerGLSL::mCanWriteNegativeValues protected
NormalStorage GBufferConditionerGLSL::mNormalStorageType protected
Copyright © GarageGames, LLC. All Rights Reserved.