TamlVisitor Class Reference
Main Modules Class List Namespace List Online
TamlVisitor Class Reference abstract
#include <persistence/taml/tamlVisitor.h>
Classes
struct PropertyState
Visitor property state.
Public Member Functions
TamlVisitor ()
virtual ~TamlVisitor ()
virtual bool visit (const TamlParser &parser, PropertyState &propertyState)=0
The state of the visited property.
virtual bool wantsPropertyChanges (void)=0
Whether the visitor wants to perform property changes.
virtual bool wantsRootOnly (void)=0
Whether the visitor wants to visit the root node only.
Detailed Description
See also
tamlGroup
Constructor & Destructor Documentation
TamlVisitor::TamlVisitor () inline
virtual TamlVisitor::~TamlVisitor () inline virtual
References visit(), wantsPropertyChanges(), and wantsRootOnly().
Member Function Documentation
virtual bool TamlVisitor::visit (const TamlParser & parser, PropertyState & propertyState) pure virtual
The state of the visited property.
Implemented in TamlAssetDeclaredUpdateVisitor, TamlAssetReferencedUpdateVisitor, TamlAssetDeclaredVisitor, TamlAssetReferencedVisitor, and TamlModuleIdUpdateVisitor.
Referenced by ~TamlVisitor().
virtual bool TamlVisitor::wantsPropertyChanges (void) pure virtual
Whether the visitor wants to perform property changes.
This allows a check against the parser which may not allow changes.
Implemented in TamlAssetDeclaredUpdateVisitor, TamlAssetReferencedUpdateVisitor, TamlAssetDeclaredVisitor, TamlAssetReferencedVisitor, and TamlModuleIdUpdateVisitor.
Referenced by ~TamlVisitor().
virtual bool TamlVisitor::wantsRootOnly (void) pure virtual
Whether the visitor wants to visit the root node only.
Implemented in TamlAssetDeclaredUpdateVisitor, TamlAssetReferencedUpdateVisitor, TamlAssetDeclaredVisitor, TamlAssetReferencedVisitor, and TamlModuleIdUpdateVisitor.
Referenced by ~TamlVisitor().
Copyright © GarageGames, LLC. All Rights Reserved.