SFXObject< NUM_DIMENSIONS > Class Template Reference
Main Modules Class List Namespace List Online
SFXObject< NUM_DIMENSIONS > Class Template Reference
Information about an object in the SFX world.
#include <sfx/sfxWorld.h>
Public Types
typedef ScopeTrackerObject< NUM_DIMENSIONS > Parent
Public Types inherited from ScopeTrackerObject< NUM_DIMENSIONS >
enum { AllInScope = (0x01010101 >> ((4 - NUM_DIMENSIONS) * 8)) }
typedef void Parent
Public Member Functions
SFXObject ()
void clearFlags (U32 bits)
bool isEmitter () const
bool isListener () const
Return true if this object is currently being used as the listener.
bool isOccluder () const
Return true if this object is occluding sound.
bool isOccluderOnly () const
Return true if this object is only a sound occluder without any more ambient sound properties.
bool isPortal () const
Return true if this object connects two ambient spaces.
bool isZone () const
void setFlags (U32 bits)
Implementor Interface
The following methods must be implemented by the client.
They are defined here just for reference. If you don't override them, you'll get link errors.
void getReferenceCenter (F32 pos[NUM_DIMENSIONS]) const
Return the world-space position of the ears on this object.
void getBounds (F32 minBounds[NUM_DIMENSIONS], F32 maxBounds[NUM_DIMENSIONS]) const
Return the object's bounding box in world-space including its surround zone.
void getRealBounds (F32 minBounds[NUM_DIMENSIONS], F32 maxBounds[NUM_DIMENSIONS]) const
Return the object's bounding box in world-space excluding its surround zone.
bool containsPoint (const F32 point[NUM_DIMENSIONS]) const
Return true if the given point is contained in the object's volume.
SFXAmbience * getAmbience () const
Return the ambient space active within this object.
String describeSelf () const
Public Member Functions inherited from ScopeTrackerObject< NUM_DIMENSIONS >
ScopeTrackerObject (U32 flags=0)
void clearScopeMask ()
TrackingNode * getMaxTrackingNode (U32 dimension)
const TrackingNode * getMaxTrackingNode (U32 dimension) const
TrackingNode * getMinTrackingNode (U32 dimension)
const TrackingNode * getMinTrackingNode (U32 dimension) const
bool isInScope () const
Return true if the reference center lies within the object bound's on all axes.
bool isInScope (U32 dimension) const
bool isRegistered () const
Return true if the object is currently being tracked.
void setInScope (U32 dimension, bool state)
void getPosition (F32 pos[NUM_DIMENSIONS]) const
Return the position of the object in world-space.
void getReferenceCenter (F32 pos[NUM_DIMENSIONS]) const
If this object is the reference object, this method should return the world-space pivot point in the object that will be the world reference center.
void getBounds (F32 minBounds[NUM_DIMENSIONS], F32 maxBounds[NUM_DIMENSIONS]) const
Return the object's bounding box in world-space.
String describeSelf () const
Protected Attributes
BitSet32 mFlags
Protected Attributes inherited from ScopeTrackerObject< NUM_DIMENSIONS >
union {
U8 mBytes [4]
U32 mDWord
} mScopeMask
TrackingNode mTrackingNodes [NUM_DIMENSIONS][2]
Detailed Description
template<S32 NUM_DIMENSIONS>
class SFXObject< NUM_DIMENSIONS >
Information about an object in the SFX world.
SFXObjects are:
Occluders: blocking sound
Zones: ambient sound spaces
Portals: connectors between zones
Listeners: receiving sound
Note that emitters are not managed by the SFX world. Instead, the set of 3D voices active on the device at any one point is defined as the set of current sound sources.
Member Typedef Documentation
template<S32 NUM_DIMENSIONS> typedef ScopeTrackerObject< NUM_DIMENSIONS > SFXObject< NUM_DIMENSIONS >::Parent
Constructor & Destructor Documentation
template<S32 NUM_DIMENSIONS> SFXObject< NUM_DIMENSIONS >::SFXObject () inline
Member Function Documentation
template<S32 NUM_DIMENSIONS> void SFXObject< NUM_DIMENSIONS >::clearFlags (U32 bits) inline
template<S32 NUM_DIMENSIONS> bool SFXObject< NUM_DIMENSIONS >::containsPoint (const F32 point[NUM_DIMENSIONS]) const
Return true if the given point is contained in the object's volume.
Referenced by SFXObject< 3 >::clearFlags().
template<S32 NUM_DIMENSIONS> String SFXObject< NUM_DIMENSIONS >::describeSelf () const
Referenced by SFXObject< 3 >::clearFlags().
template<S32 NUM_DIMENSIONS> SFXAmbience* SFXObject< NUM_DIMENSIONS >::getAmbience () const
Return the ambient space active within this object.
Note
Portals cannot have their own ambient spaces.
Referenced by SFXObject< 3 >::clearFlags().
template<S32 NUM_DIMENSIONS> void SFXObject< NUM_DIMENSIONS >::getBounds (F32 minBounds[NUM_DIMENSIONS], F32 maxBounds[NUM_DIMENSIONS]) const
Return the object's bounding box in world-space including its surround zone.
Referenced by SFXObject< 3 >::clearFlags().
template<S32 NUM_DIMENSIONS> void SFXObject< NUM_DIMENSIONS >::getRealBounds (F32 minBounds[NUM_DIMENSIONS], F32 maxBounds[NUM_DIMENSIONS]) const
Return the object's bounding box in world-space excluding its surround zone.
Referenced by SFXObject< 3 >::clearFlags().
template<S32 NUM_DIMENSIONS> void SFXObject< NUM_DIMENSIONS >::getReferenceCenter (F32 pos[NUM_DIMENSIONS]) const
Return the world-space position of the ears on this object.
This will only be called on objects that are made listeners.
Referenced by SFXObject< 3 >::clearFlags().
template<S32 NUM_DIMENSIONS> bool SFXObject< NUM_DIMENSIONS >::isEmitter () const inline
template<S32 NUM_DIMENSIONS> bool SFXObject< NUM_DIMENSIONS >::isListener () const inline
Return true if this object is currently being used as the listener.
Note
All other sound-related properties (occlusion, ambience, etc.) will be ignored on the listener object.
template<S32 NUM_DIMENSIONS> bool SFXObject< NUM_DIMENSIONS >::isOccluder () const inline
Return true if this object is occluding sound.
Referenced by SFXObject< 3 >::isOccluderOnly().
template<S32 NUM_DIMENSIONS> bool SFXObject< NUM_DIMENSIONS >::isOccluderOnly () const inline
Return true if this object is only a sound occluder without any more ambient sound properties.
These kind of objects are not put into the tracking system.
template<S32 NUM_DIMENSIONS> bool SFXObject< NUM_DIMENSIONS >::isPortal () const inline
Return true if this object connects two ambient spaces.
template<S32 NUM_DIMENSIONS> bool SFXObject< NUM_DIMENSIONS >::isZone () const inline
Referenced by SFXObject< 3 >::isOccluderOnly().
template<S32 NUM_DIMENSIONS> void SFXObject< NUM_DIMENSIONS >::setFlags (U32 bits) inline
Member Data Documentation
template<S32 NUM_DIMENSIONS> BitSet32 SFXObject< NUM_DIMENSIONS >::mFlags protected
Copyright © GarageGames, LLC. All Rights Reserved.