Zip::ZipStatFilter Class Reference
Main Modules Class List Namespace List Online
Zip::ZipStatFilter Class Reference
Zip CodeZip Code » | Zip Code Internals
Helper class for tracking CRC and uncompressed size.
#include <core/util/zip/zipStatFilter.h>
Public Member Functions
ZipStatFilter ()
ZipStatFilter (CentralDir *cd)
virtual ~ZipStatFilter ()
virtual bool attachStream (Stream *stream)
virtual void detachStream ()
CentralDir * getCentralDir ()
virtual Stream * getStream ()
void setCentralDir (CentralDir *cd)
Public Member Functions inherited from FilterStream
virtual ~FilterStream ()
U32 getPosition () const
Gets the position in the stream.
U32 getStreamSize ()
Gets the size of the stream.
bool hasCapability (const Capability) const
Checks to see if this stream has the capability of a given function.
bool setPosition (const U32 in_newPosition)
Sets the position of the stream. Returns if the new position is valid or not.
Public Member Functions inherited from Stream
Stream ()
virtual ~Stream ()
virtual Stream * clone () const
Create an exact replica of this stream.
bool copyFrom (Stream *other)
Copy the contents of another stream into this one.
Stream::StreamStatus getStatus () const
Gets the status of the stream.
bool Put (char character)
void read (String *str)
bool read (ColorI *)
Read an integral color from the stream.
bool read (ColorF *)
Read a floating point color from the stream.
bool read (NetAddress *)
Read a network address from the stream.
bool read (NetSocket *)
Read a network socket from the stream.
bool read (RawData *)
Read some raw data from the stream.
bool read (Torque::ByteBuffer *)
Read some raw data from the stream.
bool read (const U32 in_numBytes, void *out_pBuffer)
bool read (bool *out_pRead)
void readLine (U8 *buffer, U32 bufferSize)
Reads a line from the stream.
void readLongString (U32 maxStringLen, char *stringBuf)
Reads a string that could potentially be more than 255 characters long.
virtual void readString (char stringBuf[256])
Reads a string of maximum 255 characters long.
const char * readSTString (bool casesens=false)
Reads a string and inserts it into the StringTable.
void write (const String &str)
bool write (const ColorI &)
Write an integral color to the stream.
bool write (const ColorF &)
Write a floating point color to the stream.
bool write (const NetAddress &)
Write a network address to the stream.
bool write (const NetSocket &)
Write a network socket to the stream.
bool write (const RawData &)
Write some raw data onto the stream.
bool write (const Torque::ByteBuffer &)
Write some raw data onto the stream.
bool write (const U32 in_numBytes, const void *in_pBuffer)
bool write (const bool &in_rWrite)
bool writeFormattedBuffer (const char *format,...)
Writes a formatted buffer to the stream.
void writeLine (const U8 *buffer)
writes a line to the stream
void writeLongString (U32 maxStringLen, const char *string)
Writes a string to the stream.
virtual void writeString (const char *stringBuf, S32 maxLen=255)
Writes a string to the stream.
bool writeStringBuffer (const char *buffer)
Writes a NULL terminated string buffer.
void writeTabs (U32 count)
Write a number of tabs to this stream.
void writeText (const char *text)
Write raw text to the stream.
Protected Member Functions
virtual bool _read (const U32 numBytes, void *buffer)
virtual bool _write (const U32 numBytes, const void *buffer)
Protected Member Functions inherited from Stream
virtual void _read (String *str)
virtual void _write (const String &str)
void setStatus (const StreamStatus in_newStatus)
Protected Attributes
CentralDir * mCD
Stream * mStream
Additional Inherited Members
Public Types inherited from Stream
enum Capability {
StreamWrite = BIT(0),
StreamRead = BIT(1),
StreamPosition = BIT(2)
}
enum StreamStatus {
Ok = 0,
IOError,
EOS,
IllegalCall,
Closed,
UnknownError
}
Status constants for the stream.
Static Public Member Functions inherited from Stream
static const char * getStatusString (const StreamStatus in_status)
Gets a printable string form of the status.
Detailed Description
Helper class for tracking CRC and uncompressed size.
ZipStatFilter allows us to track CRC and uncompressed size on the fly. This is necessary when dealing with compressed files as the CRC must be of the uncompressed data.
ZipStatFilter is mostly intended for internal use by the zip code. However, it can be useful when reading zips sequentially using the stream interface to provide CRC checking.
Example
// It's assumed that you would use proper error checking and that
// zip is a valid pointer to a ZipArchive and otherStream is a pointer
// to a valid stream.
Zip::ZipArchive *zip;
Stream *otherStream;
// We need the real central directory to compare the CRC32
Zip::CentralDir *realCD = zip->findFileInfo("file.txt");
Stream *stream = zip->openFile("file.txt", ZipArchive::Read);
Zip::CentralDir fakeCD;
Zip::ZipStatFilter zsf(&fakeCD);
zsf.attachStream(stream);
// ... read <i>entire</i> file sequentially using zsf instead of stream
otherStream->copyFrom(&zsf);
zsf.detachStream();
// fakeCD.mCRC32 now contains the CRC32 of the stream
if(fakeCD.mCRC32 != realCD->mCRC32)
{
   // ... handle CRC failure ...
}
zip->closeFile(stream);
A more complete example of this may be found in the code for the ZipArchive::extractFile() method in zipArchive.cc
Constructor & Destructor Documentation
Zip::ZipStatFilter::ZipStatFilter () inline
Zip::ZipStatFilter::ZipStatFilter (CentralDir * cd) inline
virtual Zip::ZipStatFilter::~ZipStatFilter () inline virtual
References detachStream().
Member Function Documentation
virtual bool Zip::ZipStatFilter::_read (const U32 numBytes, void * buffer) inline protected virtual
Reimplemented from FilterStream.
References CRC::calculateCRC(), Zip::FileHeader::mCRC32, Zip::FileHeader::mUncompressedSize, and Stream::read().
virtual bool Zip::ZipStatFilter::_write (const U32 numBytes, const void * buffer) inline protected virtual
Reimplemented from FilterStream.
References CRC::calculateCRC(), Zip::FileHeader::mCRC32, Zip::FileHeader::mUncompressedSize, and Stream::write().
virtual bool Zip::ZipStatFilter::attachStream (Stream * stream) inline virtual
Implements FilterStream.
References CRC::INITIAL_CRC_VALUE, Zip::FileHeader::mCRC32, and Zip::FileHeader::mUncompressedSize.
virtual void Zip::ZipStatFilter::detachStream () inline virtual
Implements FilterStream.
References CRC::CRC_POSTCOND_VALUE, and Zip::FileHeader::mCRC32.
Referenced by ~ZipStatFilter().
CentralDir* Zip::ZipStatFilter::getCentralDir () inline
References mCD.
virtual Stream* Zip::ZipStatFilter::getStream () inline virtual
Implements FilterStream.
References mStream.
void Zip::ZipStatFilter::setCentralDir (CentralDir * cd) inline
Member Data Documentation
CentralDir* Zip::ZipStatFilter::mCD protected
Referenced by getCentralDir().
Stream* Zip::ZipStatFilter::mStream protected
Referenced by getStream().
Copyright © GarageGames, LLC. All Rights Reserved.