TSPartInstance Class Reference
Main Modules Class List Namespace List Online
TSPartInstance Class Reference
#include <ts/tsPartInstance.h>
Public Member Functions
TSPartInstance (TSShapeInstance *source)
TSPartInstance (TSShapeInstance *source, S32 objectIndex)
~TSPartInstance ()
Box3F & getBounds ()
Point3F & getCenter ()
F32 & getRadius ()
const TSShape * getShape ()
TSShapeInstance * getSourceShapeInstance ()
void render (const TSRenderState &rdata)
void render (S32 dl, const TSRenderState &rdata)
void setDetailData (F32 *sizeCutoffs, S32 numDetails)
choose detail method – pass in NULL for first parameter to just use shapes data
Detail Information Accessors
F32 getDetailSize (S32 dl) const
S32 getPolyCount (S32 dl)
S32 getNumDetails () const
S32 getCurrentObjectDetail () const
void setCurrentObjectDetail (S32 od)
F32 getCurrentIntraDetail () const
void setCurrentIntraDetail (F32 intra)
Static Public Member Functions
static void breakShape (TSShapeInstance *, S32 subShape, Vector< TSPartInstance * > &partList, F32 *probShatter, F32 *probBreak, S32 probDepth)
Public Attributes
void * mData
for use by app
Constructor & Destructor Documentation
TSPartInstance::TSPartInstance (TSShapeInstance * source)
TSPartInstance::TSPartInstance (TSShapeInstance * source, S32 objectIndex)
TSPartInstance::~TSPartInstance ()
Member Function Documentation
static void TSPartInstance::breakShape (TSShapeInstance * , S32 subShape, Vector< TSPartInstance * > & partList, F32 * probShatter, F32 * probBreak, S32 probDepth) static
Box3F& TSPartInstance::getBounds () inline
Point3F& TSPartInstance::getCenter () inline
F32 TSPartInstance::getCurrentIntraDetail () const inline
S32 TSPartInstance::getCurrentObjectDetail () const inline
F32 TSPartInstance::getDetailSize (S32 dl) const
Referenced by render().
S32 TSPartInstance::getNumDetails () const inline
References TSShapeInstance::getShape(), and TSShape::mSmallestVisibleDL.
S32 TSPartInstance::getPolyCount (S32 dl)
Referenced by render().
F32& TSPartInstance::getRadius () inline
const TSShape* TSPartInstance::getShape (void) inline
References TSShapeInstance::getShape().
TSShapeInstance* TSPartInstance::getSourceShapeInstance () inline
void TSPartInstance::render (const TSRenderState & rdata) inline
References getDetailSize(), getPolyCount(), render(), and setDetailData().
Referenced by render().
void TSPartInstance::render (S32 dl, const TSRenderState & rdata)
void TSPartInstance::setCurrentIntraDetail (F32 intra) inline
void TSPartInstance::setCurrentObjectDetail (S32 od) inline
void TSPartInstance::setDetailData (F32 * sizeCutoffs, S32 numDetails)
choose detail method – pass in NULL for first parameter to just use shapes data
Referenced by render().
Member Data Documentation
void* TSPartInstance::mData
for use by app
Copyright © GarageGames, LLC. All Rights Reserved.