MRandomDeck< T > Class Template Reference
Main Modules Class List Namespace List Online
MRandomDeck< T > Class Template Reference
#include <math/mRandomDeck.h>
Public Member Functions
MRandomDeck (MRandomLCG *randGen=&gRandGen)
void addToPile (const T &item)
void addToPile (const Vector< T > &items)
S32 draw (T *item, bool reshuffle=true)
void removeAll (Vector< T > *outItems)
void shuffle ()
Protected Attributes
Vector< T > mDeck
Vector< T > mPile
MRandomLCG * mRandGen
Constructor & Destructor Documentation
template<class T > MRandomDeck< T >::MRandomDeck (MRandomLCG * randGen = &gRandGen) inline
Member Function Documentation
template<class T > void MRandomDeck< T >::addToPile (const T & item) inline
References MRandomDeck< T >::mPile.
template<class T > void MRandomDeck< T >::addToPile (const Vector< T > & items) inline
References MRandomDeck< T >::mPile.
template<class T > S32 MRandomDeck< T >::draw (T * item, bool reshuffle = true) inline
References MRandomDeck< T >::mDeck, MRandomDeck< T >::mPile, and MRandomDeck< T >::shuffle().
template<class T > void MRandomDeck< T >::removeAll (Vector< T > * outItems) inline
References MRandomDeck< T >::mDeck, Vector< T >::merge(), and MRandomDeck< T >::mPile.
template<class T > void MRandomDeck< T >::shuffle () inline
References MRandomDeck< T >::mDeck, MRandomDeck< T >::mPile, MRandomDeck< T >::mRandGen, MRandomLCG::randI(), and T.
Referenced by MRandomDeck< T >::draw().
Member Data Documentation
template<class T > Vector<T> MRandomDeck< T >::mDeck protected
Referenced by MRandomDeck< T >::draw(), MRandomDeck< T >::removeAll(), and MRandomDeck< T >::shuffle().
template<class T > Vector<T> MRandomDeck< T >::mPile protected
Referenced by MRandomDeck< T >::addToPile(), MRandomDeck< T >::draw(), MRandomDeck< T >::removeAll(), and MRandomDeck< T >::shuffle().
template<class T > MRandomLCG* MRandomDeck< T >::mRandGen protected
Referenced by MRandomDeck< T >::shuffle().
Copyright © GarageGames, LLC. All Rights Reserved.