GFXDevice Class Reference
Main Modules Class List Namespace List Online
GFXDevice Class Reference abstract
GFXDevice is the TSE graphics interface layer.
#include <gfx/gfxDevice.h>
Public Types
typedef Signal< bool(GFXDeviceEventType)> DeviceEventSignal
enum GenericShaderType {
GSColor = 0,
GSTexture,
GSModColorTexture,
GSAddColorTexture,
GSTargetRestore,
GS_COUNT
}
enum GFXDeviceEventType {
deCreate,
deInit,
deDestroy,
deStartOfFrame,
deEndOfFrame,
dePostFrame,
deStartOfField,
deLeftStereoFrameRendered,
deRightStereoFrameRendered,
deEndOfField
}
enum GFXDeviceLimits { NumStereoPorts = 2 }
enum GFXDeviceRenderStyles {
RS_Standard = 0,
RS_StereoSideBySide = (1<<0),
RS_StereoSeparate = (1<<1)
}
Public Member Functions
GFXDevice ()
virtual ~GFXDevice ()
void activateStereoTarget (S32 eyeId)
Activates a stereo render target, setting the correct viewport to render eye contents.
bool allowRender () const
void beginReset ()
bool canCurrentlyRender () const
Returns true if the scene has begun and its safe to make rendering calls.
virtual GFXFence * createFence ()=0
Allocate a fence.
virtual GFXOcclusionQuery * createOcclusionQuery ()
Returns a hardware occlusion query object or NULL if this device does not support them.
virtual void doParanoidStateCheck ()
void dumpStates (const char *fileName) const
This is a method designed for debugging.
void finalizeReset ()
virtual const GFXAdapter & getAdapter ()
Returns the Adapter that was used to create this device.
virtual GFXAdapterType getAdapterType ()=0
Returns active graphics adapter type.
GFXCardProfiler * getCardProfiler () const
U32 getCurrentRenderStyle () const
Retrieve the current rendering style based on GFXDeviceRenderStyles.
S32 getCurrentStereoTarget () const
Retrieve the current stereo target being rendered to.
const Swizzle< U8, 3 > * getDeviceSwizzle24 () const
Swizzle to convert 24bpp bitmaps from RGB to the native device format.
const Swizzle< U8, 4 > * getDeviceSwizzle32 () const
Swizzle to convert 32bpp bitmaps from RGBA to the native device format.
GFXDrawUtil * getDrawUtil ()
Get access to this device's drawing utility class.
virtual F32 getFillConventionOffset () const =0
Get the fill convention for this device.
const MatrixF * getInverseStereoEyeTransforms ()
virtual U32 getMaxDynamicIndices ()=0
virtual U32 getMaxDynamicVerts ()=0
const Point3F * getStereoEyeOffsets ()
Get the current eye offset used during stereo rendering.
const MatrixF * getStereoEyeTransforms ()
const FovPort * getStereoFovPort ()
Get the current eye offset used during stereo rendering.
const MatrixF & getStereoHeadTransform ()
RectI * getStereoViewports ()
Point2F getWorldToScreenScale () const
Returns the scale for converting world space units to screen space units...
virtual void init (const GFXVideoMode &mode, PlatformWindow *window=NULL)=0
Initialize this GFXDevice, optionally specifying a platform window to bind to.
bool recentlyReset ()
void setAllowRender (bool render)
void setCurrentRenderStyle (U32 style)
Set the current rendering style, based on GFXDeviceRenderStyles.
void setCurrentStereoTarget (const F32 targetId)
Set the current stereo target being rendered to (in case we're doing anything with postfx)
void setStereoEyeOffsets (Point3F *offsets)
Set the current eye offset used during stereo rendering.
void setStereoEyeTransforms (MatrixF *transforms)
void setStereoFovPort (const FovPort *ports)
Set the current eye offset used during stereo rendering. Assumes NumStereoPorts are available.
void setStereoHeadTransform (const MatrixF &mat)
Sets the head matrix for stereo rendering.
void setStereoTargets (GFXTextureTarget **targets)
Sets stereo render targets.
void setSteroViewports (const RectI *ports)
Sets stereo viewports.
virtual void setupGenericShaders (GenericShaderType type=GSColor)
This is a helper function to set a default shader for rendering GUI elements on systems which do not support fixed-function operations as well as for things which need just generic position/texture/color shaders.
Debug Methods
virtual void enterDebugEvent (ColorI color, const char *name)=0
virtual void leaveDebugEvent ()=0
virtual void setDebugMarker (ColorI color, const char *name)=0
Video Mode Functions
Enumerates the supported video modes of the device
virtual void enumerateVideoModes ()=0
const Vector< GFXVideoMode > *const getVideoModeList () const
Returns the video mode list.
virtual GFXFormat selectSupportedFormat (GFXTextureProfile *profile, const Vector< GFXFormat > &formats, bool texture, bool mustblend, bool mustfilter)=0
Returns the first format from the list which meets all the criteria of the texture profile and query options.
Render Target functions
virtual GFXTextureTarget * allocRenderToTextureTarget ()=0
Allocate a target for doing render to texture operations, with no depth/stencil buffer.
virtual GFXWindowTarget * allocWindowTarget (PlatformWindow *window)=0
Allocate a target for a given window.
void pushActiveRenderTarget ()
Store the current render target to restore later.
void popActiveRenderTarget ()
Restore the previous render target.
void setActiveRenderTarget (GFXTarget *target, bool updateViewport=true)
Assign a new active render target.
GFXTarget * getActiveRenderTarget ()
Returns the current active render target.
Shader functions
virtual F32 getPixelShaderVersion () const =0
virtual void setPixelShaderVersion (F32 version)=0
virtual U32 getNumSamplers () const =0
Returns the number of texture samplers that can be used in a shader rendering pass.
virtual U32 getNumRenderTargets () const =0
Returns the number of simultaneous render targets supported by the device.
virtual void setShader (GFXShader *shader, bool force=false)
virtual void disableShaders (bool force=false)
void setShaderConstBuffer (GFXShaderConstBuffer *buffer)
Set the buffer! (Actual set happens on the next draw call, just like textures, state blocks, etc)
virtual GFXShader * createShader ()=0
Creates a new empty shader which must be initialized and deleted by the caller.
Light Settings
NONE of these should be overridden by API implementations because of the state caching stuff.
void setLight (U32 stage, GFXLightInfo *light)
void setLightMaterial (const GFXLightMaterial &mat)
void setGlobalAmbientColor (const ColorF &color)
Texture State Settings
NONE of these should be overridden by API implementations because of the state caching stuff.
void setTexture (U32 stage, GFXTextureObject *texture)
void setCubeTexture (U32 stage, GFXCubemap *cubemap)
GFXTextureObject * getCurrentTexture (U32 stage)
State Block Interface
virtual GFXStateBlockRef createStateBlock (const GFXStateBlockDesc &desc)
Creates a state block object based on the desc passed in.
virtual void setStateBlock (GFXStateBlock *block)
Sets the current stateblock (actually activated in ::updateStates)
GFXStateBlock * getStateBlock ()
virtual void setStateBlockByDesc (const GFXStateBlockDesc &desc)
This sets a stateblock directly from the description structure.
Matrix interface
void setWorldMatrix (const MatrixF &newWorld)
Sets the top of the world matrix stack.
const MatrixF & getWorldMatrix () const
Gets the matrix on the top of the world matrix stack.
void pushWorldMatrix ()
Pushes the world matrix stack and copies the current top matrix to the new top of the stack.
void popWorldMatrix ()
Pops the world matrix stack.
void setProjectionMatrix (const MatrixF &newProj)
Sets the projection matrix.
const MatrixF & getProjectionMatrix () const
Gets the projection matrix.
void setViewMatrix (const MatrixF &newView)
Sets the view matrix.
const MatrixF & getViewMatrix () const
Gets the view matrix.
void multWorld (const MatrixF &mat)
Multiplies the matrix at the top of the world matrix stack by a matrix and replaces the top of the matrix stack with the result.
void setTextureMatrix (const U32 stage, const MatrixF &texMat)
Set texture matrix for a sampler.
void setViewport (const RectI &rect)
Set an area of the target to render to.
const RectI & getViewport () const
Get the current area of the target we will render to.
virtual void setClipRect (const RectI &rect)=0
virtual const RectI & getClipRect () const =0
virtual void setFrustum (F32 left, F32 right, F32 bottom, F32 top, F32 nearPlane, F32 farPlane, bool bRotate=true)
Set the projection frustum.
virtual void setFrustum (const Frustum &frust, bool bRotate=true)
void getFrustum (F32 *left, F32 *right, F32 *bottom, F32 *top, F32 *nearPlane, F32 *farPlane, bool *isOrtho) const
Get the projection frustum.
const Frustum & getFrustum () const
Get the projection frustum.
void setOrtho (F32 left, F32 right, F32 bottom, F32 top, F32 nearPlane, F32 farPlane, bool doRotate=false)
This will construct and apply an orthographic projection matrix with the provided parameters.
bool isFrustumOrtho () const
Return true if the current frustum uses orthographic projection rather than perspective projection.
Static Public Member Functions
static bool destroy ()
static bool devicePresent ()
static GFXDevice * get ()
static DeviceEventSignal & getDeviceEventSignal ()
static void initConsole ()
Protected Member Functions
virtual void _updateRenderTargets ()=0
Updates the render targets and viewport in a device specific manner when they are dirty.
virtual bool beginSceneInternal ()=0
virtual void deviceInited ()
Notify GFXDevice that we are initialized.
virtual void endSceneInternal ()=0
virtual void preDestroy ()
This is called before this, or any other device, is deleted in the global destroy() method.
virtual void setAdapter (const GFXAdapter &adapter)
Set the adapter that this device is using. For use by GFXInit::createDevice only.
virtual void setGlobalAmbientInternal (ColorF color)=0
virtual void setLightInternal (U32 lightStage, const GFXLightInfo light, bool lightEnable)=0
virtual void setLightMaterialInternal (const GFXLightMaterial mat)=0
virtual void setMatrix (GFXMatrixType mtype, const MatrixF &mat)=0
This function must be implemented differently per API and it should set ONLY the current matrix.
virtual void setShaderConstBufferInternal (GFXShaderConstBuffer *buffer)=0
Called by base GFXDevice to actually set a const buffer.
virtual void setTextureInternal (U32 textureUnit, const GFXTextureObject *texture)=0
Stateblock functions
virtual GFXStateBlockRef createStateBlockInternal (const GFXStateBlockDesc &desc)=0
Called by GFXDevice to create a device specific stateblock.
virtual void setStateBlockInternal (GFXStateBlock *block, bool force)=0
Called by GFXDevice to actually set a stateblock.
State Initialization.
virtual void initStates ()=0
State initialization.
Protected Attributes
bool mAllowRender
Set if we're in a mode where we want rendering to occur.
bool mCanCurrentlyRender
Set once the device is active.
GFXCardProfiler * mCardProfiler
The CardProfiler for this device.
U32 mCurrentFrontBufferIdx
U32 mCurrentRenderStyle
The style of rendering that is to be performed, based on GFXDeviceRenderStyles.
GFXTargetRef mCurrentRT
The current render target which may or may not not be yet activated.
S32 mCurrentStereoTarget
Current stereo target being rendered to.
Swizzle< U8, 3 > * mDeviceSwizzle24
Swizzle< U8, 4 > * mDeviceSwizzle32
GFXDrawUtil * mDrawer
FovPort mFovPorts [NumStereoPorts]
Fov port settings.
GFXTexHandle mFrontBuffer [2]
bool mInitialized
This will allow querying to see if a device is initialized and ready to have operations performed on it.
MatrixF mInverseStereoEyeTransforms [NumStereoPorts]
Inverse of mStereoEyeTransforms.
bool mReset
GFXResource * mResourceListHead
Head of the resource list.
GFXTargetRef mRTDeactivate
This tracks a previously activated render target which need to be deactivated.
bool mRTDirty
This is set when the current and/or deactivate render targets have changed and the device need to update its state on the next draw/clear.
Vector< GFXTargetRef > mRTStack
A stack of previously active render targets.
Point3F mStereoEyeOffset [NumStereoPorts]
Eye offset used when using a stereo rendering style.
MatrixF mStereoEyeTransforms [NumStereoPorts]
Left and right matrix for eyes.
MatrixF mStereoHeadTransform
Center matrix for head.
GFXTextureTarget * mStereoTargets [NumStereoPorts]
Destination targets for stereo rendering.
RectI mStereoViewports [NumStereoPorts]
Destination viewports for stereo rendering.
Vector< GFXVideoMode > mVideoModes
List of valid video modes for this device.
RectI mViewport
The current viewport rect.
bool mViewportDirty
If true the viewport has been changed and it must be updated on the next draw/clear.
Light Tracking
GFXLightInfo mCurrentLight [LIGHT_STAGE_COUNT]
bool mCurrentLightEnable [LIGHT_STAGE_COUNT]
bool mLightDirty [LIGHT_STAGE_COUNT]
bool mLightsDirty
ColorF mGlobalAmbientColor
bool mGlobalAmbientColorDirty
Fixed function material tracking
GFXLightMaterial mCurrentLightMaterial
bool mLightMaterialDirty
Matrix managing variables
MatrixF mWorldMatrix [WORLD_STACK_MAX]
bool mWorldMatrixDirty
S32 mWorldStackSize
MatrixF mProjectionMatrix
bool mProjectionMatrixDirty
MatrixF mViewMatrix
bool mViewMatrixDirty
MatrixF mTextureMatrix [TEXTURE_STAGE_COUNT]
bool mTextureMatrixDirty [TEXTURE_STAGE_COUNT]
bool mTextureMatrixCheckDirty
Current frustum planes
Frustum mFrustum
Resource debug methods
GFXDeviceStatistics mDeviceStatistics
virtual void fillResourceVectors (const char *resNames, bool unflaggedOnly, Vector< GFXResource * > &textureObjects, Vector< GFXResource * > &textureTargets, Vector< GFXResource * > &windowTargets, Vector< GFXResource * > &vertexBuffers, Vector< GFXResource * > &primitiveBuffers, Vector< GFXResource * > &fences, Vector< GFXResource * > &cubemaps, Vector< GFXResource * > &shaders, Vector< GFXResource * > &stateblocks)
This is a helper method for describeResourcesToFile.
virtual void listResources (bool unflaggedOnly)
Lists how many of each GFX resource (e.g.
virtual void flagCurrentResources ()
Flags all resources GFX is currently aware of.
virtual void clearResourceFlags ()
Clears the flag on all resources GFX is currently aware of.
virtual void describeResources (const char *resName, const char *file, bool unflaggedOnly)
Dumps a description of the specified resource types to the console.
GFXDeviceStatistics * getDeviceStatistics ()
Returns the current GFXDeviceStatistics, stats are cleared every ::beginScene call.
State tracking variables
enum TexDirtyType {
GFXTDT_Normal,
GFXTDT_Cube
}
typedef Map< U32, GFXStateBlockRef > StateBlockMap
bool mStateDirty
Set if ANY state is dirty, including matrices or primitive buffers.
GFXTexHandle mCurrentTexture [TEXTURE_STAGE_COUNT]
GFXTexHandle mNewTexture [TEXTURE_STAGE_COUNT]
GFXCubemapHandle mCurrentCubemap [TEXTURE_STAGE_COUNT]
GFXCubemapHandle mNewCubemap [TEXTURE_STAGE_COUNT]
TexDirtyType mTexType [TEXTURE_STAGE_COUNT]
bool mTextureDirty [TEXTURE_STAGE_COUNT]
bool mTexturesDirty
StateBlockMap mCurrentStateBlocks
bool mStateBlockDirty
GFXStateBlockRef mCurrentStateBlock
GFXStateBlockRef mNewStateBlock
GFXShaderConstBuffer * mCurrentShaderConstBuffer
static bool smWireframe
A global forced wireframe mode.
static bool smDisableVSync
The global vsync state.
static F32 smForcedPixVersion
The forced shader model version if non-zero.
static bool smDisableOcclusionQuery
Disable all hardware occlusion queries causing them to return only the visibile state.
Buffer Allocation
These methods are implemented per-device and are called by the GFX layer when a user calls an alloc
Note
Primitive Buffers are NOT implemented per device, they wrap index buffers
StrongRefPtr< GFXVertexBuffer > mCurrentVertexBuffer [VERTEX_STREAM_COUNT]
bool mVertexBufferDirty [VERTEX_STREAM_COUNT]
U32 mVertexBufferFrequency [VERTEX_STREAM_COUNT]
bool mVertexBufferFrequencyDirty [VERTEX_STREAM_COUNT]
const GFXVertexDecl * mCurrVertexDecl
bool mVertexDeclDirty
StrongRefPtr< GFXPrimitiveBuffer > mCurrentPrimitiveBuffer
bool mPrimitiveBufferDirty
static const U32 VERTEX_STREAM_COUNT = 4
The maximum number of supported vertex streams which may be more than the device supports.
virtual GFXVertexBuffer * allocVertexBuffer (U32 numVerts, const GFXVertexFormat *vertexFormat, U32 vertSize, GFXBufferType bufferType, void *data=NULL)=0
This allocates a vertex buffer and returns a pointer to the allocated buffer.
virtual GFXVertexDecl * allocVertexDecl (const GFXVertexFormat *vertexFormat)=0
Called from GFXVertexFormat to allocate the hardware specific vertex declaration for rendering.
virtual void setVertexDecl (const GFXVertexDecl *decl)=0
Sets the current vertex declaration on the device.
virtual void setVertexStream (U32 stream, GFXVertexBuffer *buffer)=0
Sets the vertex buffer on the device.
virtual void setVertexStreamFrequency (U32 stream, U32 frequency)=0
Set the vertex stream frequency on the device.
virtual GFXPrimitiveBuffer * allocPrimitiveBuffer (U32 numIndices, U32 numPrimitives, GFXBufferType bufferType, void *data=NULL)=0
This allocates a primitive buffer and returns a pointer to the allocated buffer.
Texture functions
GFXTextureManager * mTextureManager
virtual GFXCubemap * createCubemap ()=0
GFXTextureManager * getTextureManager ()
Rendering methods
PlatformTimer * mFrameTime
virtual void clear (U32 flags, ColorI color, F32 z, U32 stencil)=0
virtual bool beginScene ()
virtual void endScene ()
virtual void beginField ()
virtual void endField ()
virtual GFXTexHandle & getFrontBuffer ()
void setPrimitiveBuffer (GFXPrimitiveBuffer *buffer)
void setVertexBuffer (GFXVertexBuffer *buffer, U32 stream=0, U32 frequency=0)
Sets the vertex buffer.
void setVertexFormat (const GFXVertexFormat *vertexFormat)
Sets the current vertex format.
virtual void drawPrimitive (GFXPrimitiveType primType, U32 vertexStart, U32 primitiveCount)=0
virtual void drawIndexedPrimitive (GFXPrimitiveType primType, U32 startVertex, U32 minIndex, U32 numVerts, U32 startIndex, U32 primitiveCount)=0
The parameters to drawIndexedPrimitive are somewhat complicated.
void drawPrimitive (const GFXPrimitive &prim)
void drawPrimitive (U32 primitiveIndex)
void drawPrimitives ()
void drawPrimitiveBuffer (GFXPrimitiveBuffer *buffer)
General state interface
Sets the dirty Render/Texture/Sampler states from the caching system
static bool getWireframe ()
Returns the forced global wireframe state.
static bool getDisableOcclusionQuery ()
Returns true if the occlusion query is disabled.
void updateStates (bool forceSetAll=false)
Detailed Description
GFXDevice is the TSE graphics interface layer.
This allows the TSE to do many things, such as use multiple render devices for multi-head systems, and allow a game to render in DirectX 9, OpenGL or any other API which has a GFX implementation seamlessly. There are many concepts in GFX device which may not be familiar to you, especially if you have not used DirectX.
Buffers There are three types of buffers in GFX: vertex, index and primitive. Please note that index buffers are not accessable outside the GFX layer, they are wrapped by primitive buffers. Primitive buffers will be explained in detail later. Buffers are allocated and deallocated using their associated allocXBuffer and freeXBuffer methods on the device. When a buffer is allocated you pass in a pointer to, depending on the buffer, a vertex type pointer or a U16 pointer. During allocation, this pointer is set to the address of where you should copy in the information for this buffer. You must the tell the GFXDevice that the information is in, and it should prepare the buffer for use by calling the prepare method on it. Dynamic vertex buffer example:
GFXVertexP *verts;        // Making a buffer containing verticies with only position
// Allocate a dynamic vertex buffer to hold 3 vertices and use *verts as the location to copy information into
GFXVertexBufferHandle vb = GFX->allocVertexBuffer(3, &verts, true);
// Now set the information, we're making a triangle
verts[0].point = Point3F(200.f, 200.f, 0.f);
verts[1].point = Point3F(200.f, 400.f, 0.f);
verts[2].point = Point3F(400.f, 200.f, 0.f);
// Tell GFX that the information is in and it should be made ready for use
// Note that nothing is done with verts, this should not and MUST NOT be deleted
// stored, or otherwise used after prepare is called.
GFX->prepare(vb);
// Because this is a dynamic vertex buffer, it is only assured to be valid until someone
// else allocates a dynamic vertex buffer, so we will render it now
GFX->setVertexBuffer(vb);
GFX->drawPrimitive(GFXTriangleStrip, 0, 1);
// Now because this is a dynamic vertex buffer it MUST NOT BE FREED you are only
// given a handle to a vertex buffer which belongs to the device
To use a static vertex buffer, it is very similar, this is an example using a static primitive buffer:
This takes place inside a constructor for a class which has a member variable called mPB which is the primitive buffer for the class instance.
U16 *idx;                          // This is going to be where to write indices
GFXPrimitiveInfo *primitiveInfo;   // This will be where to write primitive information
// Allocate a primitive buffer with 4 indices, and 1 primitive described for use
mPB = GFX->allocPrimitiveBuffer(4, &idx, 1, &primitiveInfo);
// Write the index information, this is going to be for the outline of a triangle using
// a line strip
idx[0] = 0;
idx[1] = 1;
idx[2] = 2;
idx[3] = 0;
// Write the information for the primitive
primitiveInfo->indexStart = 0;            // Starting with index 0
primitiveInfo->minVertex = 0;             // The minimum vertex index is 0
primitiveInfo->maxVertex = 3;             // The maximum vertex index is 3
primitiveInfo->primitiveCount = 3;        // There are 3 lines we are drawing
primitiveInfo->type = GFXLineStrip;       // This primitive info describes a line strip
The following code takes place in the destructor for the same class
// Because this is a static buffer it's our responsibility to free it when we are done
GFX->freePrimitiveBuffer(mPB);
This last bit takes place in the rendering function for the class
// You need to set a vertex buffer as well, primitive buffers contain indexing
// information, not vertex information. This is so you could have, say, a static
// vertex buffer, and a dynamic primitive buffer.
// This sets the primitive buffer to the static buffer we allocated in the constructor
GFX->setPrimitiveBuffer(mPB);
// Draw the first primitive contained in the set primitive buffer, our primitive buffer
// has only one primitive, so we could also technically call GFX->drawPrimitives(); and
// get the same result.
GFX->drawPrimitive(0);
If you need any more examples on how to use these buffers please see the rest of the engine.
Primitive Buffers
Primitive buffers wrap and extend the concept of index buffers. The purpose of a primitive buffer is to let objects store all information they have to render their primitives in a central place. Say that a shape is made up of triangle strips and triangle fans, it would still have only one primitive buffer which contained primitive information for each strip and fan. It could then draw itself with one call.
TO BE FINISHED LATER
Member Typedef Documentation
typedef Signal<bool (GFXDeviceEventType)> GFXDevice::DeviceEventSignal
typedef Map<U32, GFXStateBlockRef> GFXDevice::StateBlockMap protected
Member Enumeration Documentation
enum GFXDevice::GenericShaderType
Enumerator
GSColor
GSTexture
GSModColorTexture
GSAddColorTexture
GSTargetRestore
GS_COUNT
enum GFXDevice::GFXDeviceEventType
Enumerator
deCreate
The device has been created, but not initialized.
deInit
The device has been initialized.
deDestroy
The device is about to be destroyed.
deStartOfFrame
The device has started rendering a frame.
deEndOfFrame
The device is about to finish rendering a frame.
dePostFrame
The device has rendered a frame and ended the scene.
deStartOfField
The device has started rendering a frame's field (such as for side-by-side rendering)
deLeftStereoFrameRendered
left stereo frame has been rendered
deRightStereoFrameRendered
right stereo frame has been rendered
deEndOfField
The device is about to finish rendering a frame's field.
enum GFXDevice::GFXDeviceLimits
Enumerator
NumStereoPorts
enum GFXDevice::GFXDeviceRenderStyles
Enumerator
RS_Standard
RS_StereoSideBySide
RS_StereoSeparate
enum GFXDevice::TexDirtyType protected
Enumerator
GFXTDT_Normal
GFXTDT_Cube
Constructor & Destructor Documentation
GFXDevice::GFXDevice ()
Referenced by setAdapter().
virtual GFXDevice::~GFXDevice () virtual
Referenced by setAdapter().
Member Function Documentation
virtual void GFXDevice::_updateRenderTargets () protected pure virtual
Updates the render targets and viewport in a device specific manner when they are dirty.
Implemented in GFXD3D9Device, GFXD3D11Device, GFXNullDevice, and GFXGLDevice.
void GFXDevice::activateStereoTarget (S32 eyeId) inline
Activates a stereo render target, setting the correct viewport to render eye contents.
If eyeId is -1, set a viewport encompassing the entire size of the render targets.
References setActiveRenderTarget(), and setViewport().
virtual GFXPrimitiveBuffer* GFXDevice::allocPrimitiveBuffer (U32 numIndices, U32 numPrimitives, GFXBufferType bufferType, void * data = NULL) protected pure virtual
This allocates a primitive buffer and returns a pointer to the allocated buffer.
A primitive buffer's type argument refers to the index data - the primitive data will always be preserved from call to call.
Note
All index buffers use unsigned 16-bit indices.
Implemented in GFXD3D9Device, GFXD3D11Device, GFXGLDevice, and GFXNullDevice.
virtual GFXTextureTarget* GFXDevice::allocRenderToTextureTarget () pure virtual
Allocate a target for doing render to texture operations, with no depth/stencil buffer.
Implemented in GFXNullDevice, GFXGLDevice, and GFXPCD3D9Device.
Referenced by getDeviceSwizzle24().
virtual GFXVertexBuffer* GFXDevice::allocVertexBuffer (U32 numVerts, const GFXVertexFormat * vertexFormat, U32 vertSize, GFXBufferType bufferType, void * data = NULL) protected pure virtual
This allocates a vertex buffer and returns a pointer to the allocated buffer.
This function should not be called directly - rather it should be used by the GFXVertexBufferHandle class.
Implemented in GFXD3D9Device, GFXD3D11Device, GFXGLDevice, and GFXNullDevice.
virtual GFXVertexDecl* GFXDevice::allocVertexDecl (const GFXVertexFormat * vertexFormat) protected pure virtual
Called from GFXVertexFormat to allocate the hardware specific vertex declaration for rendering.
Implemented in GFXD3D9Device, GFXD3D11Device, GFXGLDevice, and GFXNullDevice.
virtual GFXWindowTarget* GFXDevice::allocWindowTarget (PlatformWindow * window) pure virtual
Allocate a target for a given window.
Implemented in GFXNullDevice, GFXGLDevice, and GFXPCD3D9Device.
Referenced by getDeviceSwizzle24().
bool GFXDevice::allowRender () const inline
References mAllowRender.
virtual void GFXDevice::beginField () virtual
Referenced by disableShaders().
void GFXDevice::beginReset () inline
virtual bool GFXDevice::beginScene () virtual
Referenced by disableShaders().
virtual bool GFXDevice::beginSceneInternal () protected pure virtual
Implemented in GFXD3D9Device, GFXD3D11Device, GFXNullDevice, GFXGLDevice, and GFXPCD3D9Device.
bool GFXDevice::canCurrentlyRender () const inline
Returns true if the scene has begun and its safe to make rendering calls.
See also
beginScene
endScene
References mCanCurrentlyRender.
virtual void GFXDevice::clear (U32 flags, ColorI color, F32 z, U32 stencil) pure virtual
Implemented in GFXD3D9Device, GFXD3D11Device, GFXNullDevice, and GFXGLDevice.
Referenced by disableShaders().
virtual void GFXDevice::clearResourceFlags () virtual
Clears the flag on all resources GFX is currently aware of.
Referenced by getAdapter().
virtual GFXCubemap* GFXDevice::createCubemap () pure virtual
Implemented in GFXD3D9Device, GFXD3D11Device, GFXNullDevice, and GFXGLDevice.
virtual GFXFence* GFXDevice::createFence () pure virtual
Allocate a fence.
The API specific implementation of GFXDevice is responsible to make sure that the proper type is used. GFXGeneralFence should work in all cases.
Implemented in GFXD3D9Device, GFXD3D11Device, GFXNullDevice, and GFXGLDevice.
Referenced by getFrontBuffer().
virtual GFXOcclusionQuery* GFXDevice::createOcclusionQuery () inline virtual
Returns a hardware occlusion query object or NULL if this device does not support them.
Reimplemented in GFXD3D9Device, GFXD3D11Device, GFXNullDevice, and GFXGLDevice.
References setCubeTexture(), setGlobalAmbientColor(), setLight(), setLightMaterial(), and setTexture().
virtual GFXShader* GFXDevice::createShader () pure virtual
Creates a new empty shader which must be initialized and deleted by the caller.
See also
GFXShader::init
Implemented in GFXD3D9Device, GFXD3D11Device, GFXNullDevice, and GFXGLDevice.
Referenced by disableShaders().
virtual GFXStateBlockRef GFXDevice::createStateBlock (const GFXStateBlockDesc & desc) virtual
Creates a state block object based on the desc passed in.
This object represents an immutable state.
Referenced by getCurrentTexture().
virtual GFXStateBlockRef GFXDevice::createStateBlockInternal (const GFXStateBlockDesc & desc) protected pure virtual
Called by GFXDevice to create a device specific stateblock.
Implemented in GFXD3D9Device, GFXD3D11Device, GFXGLDevice, and GFXNullDevice.
virtual void GFXDevice::describeResources (const char * resName, const char * file, bool unflaggedOnly) virtual
Dumps a description of the specified resource types to the console.
Parameters
resNames A string of space separated class names (e.g. "GFXTextureObject GFXTextureTarget GFXShader") to describe to the console
file A path to the file to write the descriptions to. If it is NULL or "", descriptions are written to the console.
unflaggedOnly If true, this method only counts unflagged resources
Note
resNames is case sensitive because there is no dStristr function.
Referenced by getAdapter().
static bool GFXDevice::destroy () static
Referenced by get().
virtual void GFXDevice::deviceInited () protected virtual
Notify GFXDevice that we are initialized.
Referenced by setAdapter().
static bool GFXDevice::devicePresent () inline static
References getAdapterType().
virtual void GFXDevice::disableShaders (bool force = false) inline virtual
Reimplemented in GFXD3D9Device.
References beginField(), beginScene(), clear(), createShader(), endField(), endScene(), and setShaderConstBuffer().
virtual void GFXDevice::doParanoidStateCheck () inline virtual
Reimplemented in GFXD3D9Device, and GFXD3D11Device.
References dumpStates(), and getDrawUtil().
virtual void GFXDevice::drawIndexedPrimitive (GFXPrimitiveType primType, U32 startVertex, U32 minIndex, U32 numVerts, U32 startIndex, U32 primitiveCount) pure virtual
The parameters to drawIndexedPrimitive are somewhat complicated.
From a raw-data stand point they evaluate to something like the following:
U16 indicies[] = { 0, 1, 2, 1, 0, 0, 2 };
Point3F verts[] = { Point3F(0.0f, 0.0f, 0.0f), Point3F(0.0f, 1.0f, 0.0f), Point3F(0.0f, 0.0f, 1.0f) };
GFX->drawIndexedPrimitive(GFXLineList, // Drawing a list of lines, each line is two verts
                           0, // vertex 0 will be referenced so minIndex = 0
                           3, // 3 verticies will be used for this draw call
                           1, // We want index 1 to be the first index used, so indicies 1-6 will be used
                           3  // Drawing 3 LineList primitives, meaning 6 verts will be drawn
                            );
U16 *idxPtr = &indicies[1];  // 1 = startIndex, so the pointer is offset such that:
                             //    idxPtr[0] is the same as indicies[1]
U32 numVertsToDrawFromBuffer = primitiveCount * 2; // 2 verts define a line in the GFXLineList primitive type (6)
Parameters
primType Type of primitive to draw
startVertex This defines index zero. Its the offset from the start of the vertex buffer to the first vertex.
minIndex The smallest index into the vertex stream which will be used for this draw call. This is a zero based index relative to startVertex. It is strictly a performance hint for implementations. No vertex below minIndex will be referenced by this draw call. For device implementors, this should not be used to offset the vertex buffer, or index buffer.
numVerts The number of verticies which will be referenced in this draw call. This is not the number of verticies which will be drawn. That is a function of 'primType' and 'primitiveCount'.
startIndex An offset from the start of the index buffer to specify where to start. If 'idxBuffer' is a pointer to an array of integers, this could be written as int *offsetIdx = idxBuffer + startIndex;
primitiveCount The number of primitives of type 'primType' to draw.
Implemented in GFXD3D9Device, GFXD3D11Device, GFXNullDevice, and GFXGLDevice.
Referenced by getFrontBuffer().
virtual void GFXDevice::drawPrimitive (GFXPrimitiveType primType, U32 vertexStart, U32 primitiveCount) pure virtual
Implemented in GFXD3D9Device, GFXD3D11Device, GFXNullDevice, and GFXGLDevice.
Referenced by getFrontBuffer().
void GFXDevice::drawPrimitive (const GFXPrimitive & prim)
void GFXDevice::drawPrimitive (U32 primitiveIndex)
void GFXDevice::drawPrimitiveBuffer (GFXPrimitiveBuffer * buffer)
Referenced by getFrontBuffer().
void GFXDevice::drawPrimitives ()
Referenced by getFrontBuffer().
void GFXDevice::dumpStates (const char * fileName) const
This is a method designed for debugging.
It will allow you to dump the states in the render manager out to a file so that it can be diffed and examined.
Referenced by doParanoidStateCheck().
virtual void GFXDevice::endField () virtual
Referenced by disableShaders().
virtual void GFXDevice::endScene () virtual
Referenced by disableShaders().
virtual void GFXDevice::endSceneInternal () protected pure virtual
Implemented in GFXD3D9Device, GFXD3D11Device, GFXNullDevice, and GFXGLDevice.
virtual void GFXDevice::enterDebugEvent (ColorI color, const char * name) pure virtual
Implemented in GFXNullDevice, GFXGLDevice, and GFXPCD3D9Device.
Referenced by getAdapter().
virtual void GFXDevice::enumerateVideoModes () pure virtual
Implemented in GFXNullDevice, GFXGLDevice, and GFXPCD3D9Device.
virtual void GFXDevice::fillResourceVectors (const char * resNames, bool unflaggedOnly, Vector< GFXResource * > & textureObjects, Vector< GFXResource * > & textureTargets, Vector< GFXResource * > & windowTargets, Vector< GFXResource * > & vertexBuffers, Vector< GFXResource * > & primitiveBuffers, Vector< GFXResource * > & fences, Vector< GFXResource * > & cubemaps, Vector< GFXResource * > & shaders, Vector< GFXResource * > & stateblocks) protected virtual
This is a helper method for describeResourcesToFile.
It walks through the GFXResource list and sorts it by item type, putting the resources into the proper vector.
See also
describeResources
void GFXDevice::finalizeReset () inline
virtual void GFXDevice::flagCurrentResources () virtual
Flags all resources GFX is currently aware of.
Referenced by getAdapter().
static GFXDevice* GFXDevice::get () inline static
References destroy(), and initConsole().
GFXTarget* GFXDevice::getActiveRenderTarget () inline
Returns the current active render target.
References getNumRenderTargets(), getNumSamplers(), getPixelShaderVersion(), mCurrentRT, and setPixelShaderVersion().
virtual const GFXAdapter& GFXDevice::getAdapter () inline virtual
Returns the Adapter that was used to create this device.
References clearResourceFlags(), describeResources(), enterDebugEvent(), flagCurrentResources(), leaveDebugEvent(), listResources(), and setDebugMarker().
virtual GFXAdapterType GFXDevice::getAdapterType () pure virtual
Returns active graphics adapter type.
Implemented in GFXD3D9Device, GFXD3D11Device, GFXNullDevice, and GFXGLDevice.
Referenced by devicePresent(), and getCardProfiler().
GFXCardProfiler* GFXDevice::getCardProfiler () const inline
References getAdapterType(), and mCardProfiler.
virtual const RectI& GFXDevice::getClipRect () const pure virtual
Implemented in GFXD3D9Device, GFXD3D11Device, GFXNullDevice, and GFXGLDevice.
Referenced by getViewport().
U32 GFXDevice::getCurrentRenderStyle () const inline
Retrieve the current rendering style based on GFXDeviceRenderStyles.
References mCurrentRenderStyle.
S32 GFXDevice::getCurrentStereoTarget () const inline
Retrieve the current stereo target being rendered to.
References mCurrentStereoTarget.
GFXTextureObject* GFXDevice::getCurrentTexture (U32 stage) inline
References createStateBlock(), and setStateBlock().
static DeviceEventSignal& GFXDevice::getDeviceEventSignal () static
GFXDeviceStatistics* GFXDevice::getDeviceStatistics () inline
Returns the current GFXDeviceStatistics, stats are cleared every ::beginScene call.
References mDeviceStatistics.
const Swizzle<U8, 3>* GFXDevice::getDeviceSwizzle24 () const inline
Swizzle to convert 24bpp bitmaps from RGB to the native device format.
References allocRenderToTextureTarget(), allocWindowTarget(), mDeviceSwizzle24, popActiveRenderTarget(), pushActiveRenderTarget(), and setActiveRenderTarget().
const Swizzle<U8, 4>* GFXDevice::getDeviceSwizzle32 () const inline
Swizzle to convert 32bpp bitmaps from RGBA to the native device format.
References mDeviceSwizzle32.
static bool GFXDevice::getDisableOcclusionQuery () inline static
Returns true if the occlusion query is disabled.
References setWorldMatrix(), and smDisableOcclusionQuery.
GFXDrawUtil* GFXDevice::getDrawUtil ()
Get access to this device's drawing utility class.
Referenced by doParanoidStateCheck().
virtual F32 GFXDevice::getFillConventionOffset () const pure virtual
Get the fill convention for this device.
Implemented in GFXD3D9Device, GFXD3D11Device, GFXNullDevice, and GFXGLDevice.
Referenced by setupGenericShaders().
virtual GFXTexHandle& GFXDevice::getFrontBuffer () inline virtual
References createFence(), drawIndexedPrimitive(), drawPrimitive(), drawPrimitiveBuffer(), drawPrimitives(), mCurrentFrontBufferIdx, setPrimitiveBuffer(), setVertexBuffer(), and setVertexFormat().
void GFXDevice::getFrustum (F32 * left, F32 * right, F32 * bottom, F32 * top, F32 * nearPlane, F32 * farPlane, bool * isOrtho) const
Get the projection frustum.
const Frustum& GFXDevice::getFrustum () const inline
Get the projection frustum.
References mFrustum, and setOrtho().
Referenced by getViewport().
const MatrixF* GFXDevice::getInverseStereoEyeTransforms () inline
References mInverseStereoEyeTransforms.
virtual U32 GFXDevice::getMaxDynamicIndices () pure virtual
Implemented in GFXD3D9Device, GFXD3D11Device, GFXNullDevice, and GFXGLDevice.
Referenced by setupGenericShaders().
virtual U32 GFXDevice::getMaxDynamicVerts () pure virtual
Implemented in GFXD3D9Device, GFXD3D11Device, GFXNullDevice, and GFXGLDevice.
Referenced by setupGenericShaders().
virtual U32 GFXDevice::getNumRenderTargets () const pure virtual
Returns the number of simultaneous render targets supported by the device.
Implemented in GFXD3D9Device, GFXD3D11Device, GFXNullDevice, and GFXGLDevice.
Referenced by getActiveRenderTarget().
virtual U32 GFXDevice::getNumSamplers () const pure virtual
Returns the number of texture samplers that can be used in a shader rendering pass.
Implemented in GFXD3D9Device, GFXD3D11Device, GFXNullDevice, and GFXGLDevice.
Referenced by getActiveRenderTarget().
virtual F32 GFXDevice::getPixelShaderVersion () const pure virtual
Implemented in GFXD3D9Device, GFXD3D11Device, GFXNullDevice, and GFXGLDevice.
Referenced by getActiveRenderTarget().
const MatrixF& GFXDevice::getProjectionMatrix () const inline
Gets the projection matrix.
References mProjectionMatrix, and setViewMatrix().
GFXStateBlock* GFXDevice::getStateBlock () inline
References mNewStateBlock, setStateBlockByDesc(), and updateStates().
const Point3F* GFXDevice::getStereoEyeOffsets () inline
Get the current eye offset used during stereo rendering.
References mStereoEyeOffset.
const MatrixF* GFXDevice::getStereoEyeTransforms () inline
References mStereoEyeTransforms.
const FovPort* GFXDevice::getStereoFovPort () inline
Get the current eye offset used during stereo rendering.
References mFovPorts.
const MatrixF& GFXDevice::getStereoHeadTransform () inline
References mStereoHeadTransform.
RectI* GFXDevice::getStereoViewports () inline
References mStereoViewports.
GFXTextureManager* GFXDevice::getTextureManager () inline
References mTextureManager.
const Vector<GFXVideoMode>* const GFXDevice::getVideoModeList () const inline
Returns the video mode list.
See also
GFXVideoMode
References mVideoModes, and selectSupportedFormat().
const MatrixF& GFXDevice::getViewMatrix () const inline
Gets the view matrix.
References multWorld(), mViewMatrix, setTextureMatrix(), and setViewport().
const RectI& GFXDevice::getViewport () const inline
Get the current area of the target we will render to.
References getClipRect(), getFrustum(), mViewport, setClipRect(), and setFrustum().
static bool GFXDevice::getWireframe () inline static
Returns the forced global wireframe state.
References smWireframe.
Referenced by SceneData::init().
const MatrixF& GFXDevice::getWorldMatrix () const inline
Gets the matrix on the top of the world matrix stack.
References mWorldStackSize, popWorldMatrix(), pushWorldMatrix(), and setProjectionMatrix().
Point2F GFXDevice::getWorldToScreenScale () const
Returns the scale for converting world space units to screen space units...
aka pixels.
This is the true scale which is best used for GUI drawing. For doing lod calculations you should be using the functions in SceneState which is adjusted for special cases like shadows and reflections.
See also
SceneState::getWorldToScreenScale()
SceneState::projectRadius()
Referenced by isFrustumOrtho().
virtual void GFXDevice::init (const GFXVideoMode & mode, PlatformWindow * window = NULL) pure virtual
Initialize this GFXDevice, optionally specifying a platform window to bind to.
Implemented in GFXD3D9Device, GFXD3D11Device, GFXNullDevice, GFXGLDevice, and GFXPCD3D9Device.
Referenced by setAdapter().
static void GFXDevice::initConsole () static
Referenced by get().
virtual void GFXDevice::initStates () protected pure virtual
State initialization.
This MUST BE CALLED in setVideoMode after the device is created.
Implemented in GFXD3D9Device, GFXGLDevice, GFXNullDevice, GFXD3D11Device, and GFXPCD3D9Device.
bool GFXDevice::isFrustumOrtho () const inline
Return true if the current frustum uses orthographic projection rather than perspective projection.
References getWorldToScreenScale(), and Frustum::isOrtho().
virtual void GFXDevice::leaveDebugEvent () pure virtual
Implemented in GFXNullDevice, GFXGLDevice, and GFXPCD3D9Device.
Referenced by getAdapter().
virtual void GFXDevice::listResources (bool unflaggedOnly) virtual
Lists how many of each GFX resource (e.g.
textures, texture targets, shaders, etc.) GFX is aware of
Parameters
unflaggedOnly If true, this method only counts unflagged resources
Referenced by getAdapter().
void GFXDevice::multWorld (const MatrixF & mat) inline
Multiplies the matrix at the top of the world matrix stack by a matrix and replaces the top of the matrix stack with the result.
Parameters
mat Matrix to multiply
References mStateDirty, MatrixF::mul(), mWorldMatrix, mWorldMatrixDirty, and mWorldStackSize.
Referenced by getViewMatrix().
void GFXDevice::popActiveRenderTarget ()
Restore the previous render target.
Referenced by getDeviceSwizzle24().
void GFXDevice::popWorldMatrix () inline
Pops the world matrix stack.
References mStateDirty, mWorldMatrixDirty, and mWorldStackSize.
Referenced by getWorldMatrix().
virtual void GFXDevice::preDestroy () protected virtual
This is called before this, or any other device, is deleted in the global destroy() method.
It allows the device to clean up anything while everything is still valid.
Reimplemented in GFXD3D9Device, GFXD3D11Device, GFXNullDevice, and GFXGLDevice.
Referenced by GFXGLDevice::preDestroy(), and GFXD3D11Device::preDestroy().
void GFXDevice::pushActiveRenderTarget ()
Store the current render target to restore later.
Referenced by getDeviceSwizzle24().
void GFXDevice::pushWorldMatrix () inline
Pushes the world matrix stack and copies the current top matrix to the new top of the stack.
References mStateDirty, mWorldMatrix, mWorldMatrixDirty, and mWorldStackSize.
Referenced by getWorldMatrix().
bool GFXDevice::recentlyReset () inline
References mReset.
virtual GFXFormat GFXDevice::selectSupportedFormat (GFXTextureProfile * profile, const Vector< GFXFormat > & formats, bool texture, bool mustblend, bool mustfilter) pure virtual
Returns the first format from the list which meets all the criteria of the texture profile and query options.
Implemented in GFXNullDevice, GFXGLDevice, and GFXPCD3D9Device.
Referenced by getVideoModeList().
void GFXDevice::setActiveRenderTarget (GFXTarget * target, bool updateViewport = true)
Assign a new active render target.
Referenced by activateStereoTarget(), and getDeviceSwizzle24().
virtual void GFXDevice::setAdapter (const GFXAdapter & adapter) inline protected virtual
Set the adapter that this device is using. For use by GFXInit::createDevice only.
References deviceInited(), GFXDevice(), init(), and ~GFXDevice().
void GFXDevice::setAllowRender (bool render) inline
virtual void GFXDevice::setClipRect (const RectI & rect) pure virtual
Implemented in GFXD3D9Device, GFXD3D11Device, GFXNullDevice, and GFXGLDevice.
Referenced by getViewport().
void GFXDevice::setCubeTexture (U32 stage, GFXCubemap * cubemap)
Referenced by createOcclusionQuery().
void GFXDevice::setCurrentRenderStyle (U32 style) inline
Set the current rendering style, based on GFXDeviceRenderStyles.
void GFXDevice::setCurrentStereoTarget (const F32 targetId) inline
Set the current stereo target being rendered to (in case we're doing anything with postfx)
virtual void GFXDevice::setDebugMarker (ColorI color, const char * name) pure virtual
Implemented in GFXNullDevice, GFXGLDevice, and GFXPCD3D9Device.
Referenced by getAdapter().
virtual void GFXDevice::setFrustum (F32 left, F32 right, F32 bottom, F32 top, F32 nearPlane, F32 farPlane, bool bRotate = true) virtual
Set the projection frustum.
See also
MathUtils::makeFrustum()
Referenced by getViewport().
virtual void GFXDevice::setFrustum (const Frustum & frust, bool bRotate = true) virtual
void GFXDevice::setGlobalAmbientColor (const ColorF & color)
Referenced by createOcclusionQuery().
virtual void GFXDevice::setGlobalAmbientInternal (ColorF color) protected pure virtual
Implemented in GFXD3D9Device, GFXD3D11Device, GFXGLDevice, and GFXNullDevice.
void GFXDevice::setLight (U32 stage, GFXLightInfo * light)
Referenced by createOcclusionQuery().
virtual void GFXDevice::setLightInternal (U32 lightStage, const GFXLightInfo light, bool lightEnable) protected pure virtual
Implemented in GFXD3D9Device, GFXD3D11Device, GFXGLDevice, and GFXNullDevice.
void GFXDevice::setLightMaterial (const GFXLightMaterial & mat)
Referenced by createOcclusionQuery().
virtual void GFXDevice::setLightMaterialInternal (const GFXLightMaterial mat) protected pure virtual
Implemented in GFXD3D9Device, GFXD3D11Device, GFXGLDevice, and GFXNullDevice.
virtual void GFXDevice::setMatrix (GFXMatrixType mtype, const MatrixF & mat) protected pure virtual
This function must be implemented differently per API and it should set ONLY the current matrix.
For example, in OpenGL, there should be NO matrix stack activity, all the stack stuff is managed in the GFX layer.
OpenGL does not have separate world and view matrices. It has ModelView which is world * view. You must take this into consideration.
Parameters
mtype Which matrix to set, world/view/projection
mat Matrix to assign
Implemented in GFXGLDevice, GFXD3D11Device, GFXNullDevice, and GFXPCD3D9Device.
void GFXDevice::setOrtho (F32 left, F32 right, F32 bottom, F32 top, F32 nearPlane, F32 farPlane, bool doRotate = false)
This will construct and apply an orthographic projection matrix with the provided parameters.
Parameters
doRotate If set to true, the resulting matrix will be rotated PI/2 around the X axis
Referenced by getFrustum().
virtual void GFXDevice::setPixelShaderVersion (F32 version) pure virtual
Implemented in GFXD3D9Device, GFXD3D11Device, GFXNullDevice, and GFXGLDevice.
Referenced by getActiveRenderTarget().
void GFXDevice::setPrimitiveBuffer (GFXPrimitiveBuffer * buffer)
Referenced by getFrontBuffer().
void GFXDevice::setProjectionMatrix (const MatrixF & newProj) inline
Sets the projection matrix.
Parameters
newProj New projection matrix to set
References mProjectionMatrix, mProjectionMatrixDirty, and mStateDirty.
Referenced by getWorldMatrix().
virtual void GFXDevice::setShader (GFXShader * shader, bool force = false) inline virtual
Reimplemented in GFXD3D9Device, GFXD3D11Device, and GFXGLDevice.
void GFXDevice::setShaderConstBuffer (GFXShaderConstBuffer * buffer)
Set the buffer! (Actual set happens on the next draw call, just like textures, state blocks, etc)
Referenced by disableShaders().
virtual void GFXDevice::setShaderConstBufferInternal (GFXShaderConstBuffer * buffer) protected pure virtual
Called by base GFXDevice to actually set a const buffer.
Implemented in GFXD3D9Device, GFXD3D11Device, GFXGLDevice, and GFXNullDevice.
virtual void GFXDevice::setStateBlock (GFXStateBlock * block) virtual
Sets the current stateblock (actually activated in ::updateStates)
Referenced by getCurrentTexture().
virtual void GFXDevice::setStateBlockByDesc (const GFXStateBlockDesc & desc) virtual
This sets a stateblock directly from the description structure.
Its acceptable to use this for debug rendering and other low frequency rendering tasks.
Referenced by getStateBlock().
virtual void GFXDevice::setStateBlockInternal (GFXStateBlock * block, bool force) protected pure virtual
Called by GFXDevice to actually set a stateblock.
Parameters
force If true, set all states
Implemented in GFXD3D9Device, GFXD3D11Device, GFXGLDevice, and GFXNullDevice.
void GFXDevice::setStereoEyeOffsets (Point3F * offsets) inline
Set the current eye offset used during stereo rendering.
References dMemcpy(), and NumStereoPorts.
void GFXDevice::setStereoEyeTransforms (MatrixF * transforms) inline
References dMemcpy(), and MatrixF::inverse().
void GFXDevice::setStereoFovPort (const FovPort * ports) inline
Set the current eye offset used during stereo rendering. Assumes NumStereoPorts are available.
References dMemcpy().
void GFXDevice::setStereoHeadTransform (const MatrixF & mat) inline
Sets the head matrix for stereo rendering.
void GFXDevice::setStereoTargets (GFXTextureTarget ** targets) inline
Sets stereo render targets.
void GFXDevice::setSteroViewports (const RectI * ports) inline
Sets stereo viewports.
References dMemcpy(), and NumStereoPorts.
void GFXDevice::setTexture (U32 stage, GFXTextureObject * texture)
Referenced by createOcclusionQuery().
virtual void GFXDevice::setTextureInternal (U32 textureUnit, const GFXTextureObject * texture) protected pure virtual
Implemented in GFXD3D9Device, GFXGLDevice, GFXD3D11Device, and GFXNullDevice.
void GFXDevice::setTextureMatrix (const U32 stage, const MatrixF & texMat) inline
Set texture matrix for a sampler.
References mStateDirty, mTextureMatrix, mTextureMatrixCheckDirty, and mTextureMatrixDirty.
Referenced by getViewMatrix().
virtual void GFXDevice::setupGenericShaders (GenericShaderType type = GSColor) inline virtual
This is a helper function to set a default shader for rendering GUI elements on systems which do not support fixed-function operations as well as for things which need just generic position/texture/color shaders.
Parameters
type Type of generic shader, add your own if you need
Reimplemented in GFXD3D9Device, GFXD3D11Device, and GFXGLDevice.
References getFillConventionOffset(), getMaxDynamicIndices(), and getMaxDynamicVerts().
void GFXDevice::setVertexBuffer (GFXVertexBuffer * buffer, U32 stream = 0, U32 frequency = 0) inline
Sets the vertex buffer.
When setting the stream 0 vertex buffer it will automatically set its associated vertex format as the active format.
Parameters
buffer The vertex buffer or NULL to clear the buffer.
stream The stream index of the vertex source stream to place the buffer.
frequency The stream frequency of the vertex buffer.
References mCurrentVertexBuffer, mStateDirty, mVertexBufferDirty, mVertexBufferFrequency, mVertexBufferFrequencyDirty, GFXVertexBuffer::mVertexFormat, setVertexFormat(), and VERTEX_STREAM_COUNT.
Referenced by getFrontBuffer().
virtual void GFXDevice::setVertexDecl (const GFXVertexDecl * decl) protected pure virtual
Sets the current vertex declaration on the device.
Implemented in GFXD3D9Device, GFXD3D11Device, GFXGLDevice, and GFXNullDevice.
void GFXDevice::setVertexFormat (const GFXVertexFormat * vertexFormat) inline
Sets the current vertex format.
This should only be used if the vertex format of the stream 0 vertex buffer is different from the one associated to it. Typically this is used when rendering from multiple vertex streams.
References GFXVertexFormat::getDecl(), mCurrVertexDecl, mStateDirty, and mVertexDeclDirty.
Referenced by getFrontBuffer(), and setVertexBuffer().
virtual void GFXDevice::setVertexStream (U32 stream, GFXVertexBuffer * buffer) protected pure virtual
Sets the vertex buffer on the device.
Implemented in GFXD3D9Device, GFXD3D11Device, GFXGLDevice, and GFXNullDevice.
virtual void GFXDevice::setVertexStreamFrequency (U32 stream, U32 frequency) protected pure virtual
Set the vertex stream frequency on the device.
Implemented in GFXD3D9Device, GFXD3D11Device, GFXGLDevice, and GFXNullDevice.
void GFXDevice::setViewMatrix (const MatrixF & newView) inline
Sets the view matrix.
Parameters
newView New view matrix to set
References mStateDirty, mViewMatrix, and mViewMatrixDirty.
Referenced by getProjectionMatrix().
void GFXDevice::setViewport (const RectI & rect)
Set an area of the target to render to.
Referenced by activateStereoTarget(), and getViewMatrix().
void GFXDevice::setWorldMatrix (const MatrixF & newWorld) inline
Sets the top of the world matrix stack.
Parameters
newWorld New world matrix to set
References mStateDirty, mWorldMatrix, mWorldMatrixDirty, and mWorldStackSize.
Referenced by getDisableOcclusionQuery().
void GFXDevice::updateStates (bool forceSetAll = false)
Referenced by getStateBlock().
Member Data Documentation
bool GFXDevice::mAllowRender protected
Set if we're in a mode where we want rendering to occur.
Referenced by allowRender().
bool GFXDevice::mCanCurrentlyRender protected
Set once the device is active.
Referenced by canCurrentlyRender().
GFXCardProfiler* GFXDevice::mCardProfiler protected
The CardProfiler for this device.
Referenced by getCardProfiler().
GFXCubemapHandle GFXDevice::mCurrentCubemap[TEXTURE_STAGE_COUNT] protected
U32 GFXDevice::mCurrentFrontBufferIdx protected
Referenced by getFrontBuffer().
GFXLightInfo GFXDevice::mCurrentLight[LIGHT_STAGE_COUNT] protected
bool GFXDevice::mCurrentLightEnable[LIGHT_STAGE_COUNT] protected
GFXLightMaterial GFXDevice::mCurrentLightMaterial protected
StrongRefPtr<GFXPrimitiveBuffer> GFXDevice::mCurrentPrimitiveBuffer protected
U32 GFXDevice::mCurrentRenderStyle protected
The style of rendering that is to be performed, based on GFXDeviceRenderStyles.
Referenced by getCurrentRenderStyle().
GFXTargetRef GFXDevice::mCurrentRT protected
The current render target which may or may not not be yet activated.
See also
mRTDirty
Referenced by getActiveRenderTarget().
GFXShaderConstBuffer* GFXDevice::mCurrentShaderConstBuffer protected
GFXStateBlockRef GFXDevice::mCurrentStateBlock protected
StateBlockMap GFXDevice::mCurrentStateBlocks protected
S32 GFXDevice::mCurrentStereoTarget protected
Current stereo target being rendered to.
Referenced by getCurrentStereoTarget().
GFXTexHandle GFXDevice::mCurrentTexture[TEXTURE_STAGE_COUNT] protected
StrongRefPtr<GFXVertexBuffer> GFXDevice::mCurrentVertexBuffer[VERTEX_STREAM_COUNT] protected
Referenced by setVertexBuffer().
const GFXVertexDecl* GFXDevice::mCurrVertexDecl protected
Referenced by setVertexFormat().
GFXDeviceStatistics GFXDevice::mDeviceStatistics protected
Referenced by getDeviceStatistics().
Swizzle<U8, 3>* GFXDevice::mDeviceSwizzle24 protected
See also
getDeviceSwizzle24
Referenced by getDeviceSwizzle24().
Swizzle<U8, 4>* GFXDevice::mDeviceSwizzle32 protected
See also
getDeviceSwizzle32
Referenced by getDeviceSwizzle32().
GFXDrawUtil* GFXDevice::mDrawer protected
FovPort GFXDevice::mFovPorts[NumStereoPorts] protected
Fov port settings.
Referenced by getStereoFovPort().
PlatformTimer* GFXDevice::mFrameTime
GFXTexHandle GFXDevice::mFrontBuffer[2] protected
Frustum GFXDevice::mFrustum protected
Referenced by getFrustum().
ColorF GFXDevice::mGlobalAmbientColor protected
bool GFXDevice::mGlobalAmbientColorDirty protected
bool GFXDevice::mInitialized protected
This will allow querying to see if a device is initialized and ready to have operations performed on it.
MatrixF GFXDevice::mInverseStereoEyeTransforms[NumStereoPorts] protected
Inverse of mStereoEyeTransforms.
Referenced by getInverseStereoEyeTransforms().
bool GFXDevice::mLightDirty[LIGHT_STAGE_COUNT] protected
bool GFXDevice::mLightMaterialDirty protected
bool GFXDevice::mLightsDirty protected
GFXCubemapHandle GFXDevice::mNewCubemap[TEXTURE_STAGE_COUNT] protected
GFXStateBlockRef GFXDevice::mNewStateBlock protected
Referenced by getStateBlock().
GFXTexHandle GFXDevice::mNewTexture[TEXTURE_STAGE_COUNT] protected
bool GFXDevice::mPrimitiveBufferDirty protected
MatrixF GFXDevice::mProjectionMatrix protected
Referenced by getProjectionMatrix(), and setProjectionMatrix().
bool GFXDevice::mProjectionMatrixDirty protected
Referenced by setProjectionMatrix().
bool GFXDevice::mReset protected
Referenced by recentlyReset().
GFXResource* GFXDevice::mResourceListHead protected
Head of the resource list.
See also
GFXResource
GFXTargetRef GFXDevice::mRTDeactivate protected
This tracks a previously activated render target which need to be deactivated.
bool GFXDevice::mRTDirty protected
This is set when the current and/or deactivate render targets have changed and the device need to update its state on the next draw/clear.
Vector<GFXTargetRef> GFXDevice::mRTStack protected
A stack of previously active render targets.
bool GFXDevice::mStateBlockDirty protected
bool GFXDevice::mStateDirty protected
Set if ANY state is dirty, including matrices or primitive buffers.
Referenced by multWorld(), popWorldMatrix(), pushWorldMatrix(), setProjectionMatrix(), setTextureMatrix(), setVertexBuffer(), setVertexFormat(), setViewMatrix(), and setWorldMatrix().
Point3F GFXDevice::mStereoEyeOffset[NumStereoPorts] protected
Eye offset used when using a stereo rendering style.
Referenced by getStereoEyeOffsets().
MatrixF GFXDevice::mStereoEyeTransforms[NumStereoPorts] protected
Left and right matrix for eyes.
Referenced by getStereoEyeTransforms().
MatrixF GFXDevice::mStereoHeadTransform protected
Center matrix for head.
Referenced by getStereoHeadTransform().
GFXTextureTarget* GFXDevice::mStereoTargets[NumStereoPorts] protected
Destination targets for stereo rendering.
RectI GFXDevice::mStereoViewports[NumStereoPorts] protected
Destination viewports for stereo rendering.
Referenced by getStereoViewports().
bool GFXDevice::mTextureDirty[TEXTURE_STAGE_COUNT] protected
GFXTextureManager* GFXDevice::mTextureManager protected
Referenced by getTextureManager(), and GFXD3D11Device::preDestroy().
MatrixF GFXDevice::mTextureMatrix[TEXTURE_STAGE_COUNT] protected
Referenced by setTextureMatrix().
bool GFXDevice::mTextureMatrixCheckDirty protected
Referenced by setTextureMatrix().
bool GFXDevice::mTextureMatrixDirty[TEXTURE_STAGE_COUNT] protected
Referenced by setTextureMatrix().
bool GFXDevice::mTexturesDirty protected
TexDirtyType GFXDevice::mTexType[TEXTURE_STAGE_COUNT] protected
bool GFXDevice::mVertexBufferDirty[VERTEX_STREAM_COUNT] protected
Referenced by setVertexBuffer().
U32 GFXDevice::mVertexBufferFrequency[VERTEX_STREAM_COUNT] protected
Referenced by setVertexBuffer().
bool GFXDevice::mVertexBufferFrequencyDirty[VERTEX_STREAM_COUNT] protected
Referenced by setVertexBuffer().
bool GFXDevice::mVertexDeclDirty protected
Referenced by setVertexFormat().
Vector<GFXVideoMode> GFXDevice::mVideoModes protected
List of valid video modes for this device.
Referenced by getVideoModeList().
MatrixF GFXDevice::mViewMatrix protected
Referenced by getViewMatrix(), and setViewMatrix().
bool GFXDevice::mViewMatrixDirty protected
Referenced by setViewMatrix().
RectI GFXDevice::mViewport protected
The current viewport rect.
Referenced by getViewport().
bool GFXDevice::mViewportDirty protected
If true the viewport has been changed and it must be updated on the next draw/clear.
MatrixF GFXDevice::mWorldMatrix[WORLD_STACK_MAX] protected
Referenced by multWorld(), pushWorldMatrix(), and setWorldMatrix().
bool GFXDevice::mWorldMatrixDirty protected
Referenced by multWorld(), popWorldMatrix(), pushWorldMatrix(), and setWorldMatrix().
S32 GFXDevice::mWorldStackSize protected
Referenced by getWorldMatrix(), multWorld(), popWorldMatrix(), pushWorldMatrix(), and setWorldMatrix().
bool GFXDevice::smDisableOcclusionQuery static protected
Disable all hardware occlusion queries causing them to return only the visibile state.
Referenced by getDisableOcclusionQuery().
bool GFXDevice::smDisableVSync static protected
The global vsync state.
F32 GFXDevice::smForcedPixVersion static protected
The forced shader model version if non-zero.
bool GFXDevice::smWireframe static protected
A global forced wireframe mode.
Referenced by getWireframe().
const U32 GFXDevice::VERTEX_STREAM_COUNT = 4 static protected
The maximum number of supported vertex streams which may be more than the device supports.
Referenced by setVertexBuffer().
Copyright © GarageGames, LLC. All Rights Reserved.