TerrainFile Class Reference
Main Modules Class List Namespace List Online
TerrainFile Class Reference
#include <terrain/terrFile.h>
Public Types
enum Constants { FILE_VERSION = 7 }
Public Member Functions
TerrainFile ()
virtual ~TerrainFile ()
TerrainSquare * findSquare (U32 level, U32 x, U32 y) const
U16 getHeight (U32 x, U32 y) const
const U16 * getHeightAddress (U32 x, U32 y) const
const Vector< U16 > & getHeightMap () const
Returns the constant heightmap vector.
U8 getLayerIndex (U32 x, U32 y) const
BaseMatInstance * getMaterialMapping (U32 index) const
StringTableEntry getMaterialName (U32 x, U32 y) const
U16 getMaxHeight () const
void import (const GBitmap &heightMap, F32 heightScale, const Vector< U8 > &layerMap, const Vector< String > &materials, bool flipYAxis=true)
bool isEmptyAt (U32 x, U32 y) const
bool isPointInTerrain (U32 x, U32 y) const
Check if the given point is valid within the (non-tiled) terrain file.
bool save (const char *filename)
void setHeight (U32 x, U32 y, U16 height)
void setHeightMap (const Vector< U16 > &heightmap, bool updateCollision)
Sets a new heightmap state.
void setLayerIndex (U32 x, U32 y, U8 index)
void setSize (U32 newResolution, bool clear)
void smooth (F32 factor, U32 steps, bool updateCollision)
Performs multiple smoothing steps on the heightmap.
void updateGrid (const Point2I &minPt, const Point2I &maxPt)
Updates the terrain grid for the specified area.
Static Public Member Functions
static void create (String *inOutFilename, U32 newSize, const Vector< String > &materials)
static TerrainFile * load (const Torque::Path &path)
Protected Member Functions
void _buildGridMap ()
void _initMaterialInstMapping ()
void _load (FileStream &stream)
The internal loading function.
void _loadLegacy (FileStream &stream)
The legacy file loading code.
void _resolveMaterials (const Vector< String > &materials)
Used to populate the materail vector by finding the TerrainMaterial objects by name.
Protected Attributes
Torque::Path mFilePath
The full path and name of the TerrainFile.
U32 mFileVersion
The file version.
U32 mGridLevels
Vector< TerrainSquare * > mGridMap
The grid map layers used to accelerate collision queries for the height map data.
Vector< TerrainSquare > mGridMapPool
The memory pool used by the grid map layers.
Vector< U16 > mHeightMap
The fixed point height map.
Vector< U8 > mLayerMap
The layer index at each height map sample.
MaterialList mMaterialInstMapping
MaterialList used to map terrain materials to material instances for the sake of collision (physics, etc.).
Vector< TerrainMaterial * > mMaterials
The materials used to render the terrain.
bool mNeedsResaving
The dirty flag.
U32 mSize
The dimensions of the layer and height maps.
Member Enumeration Documentation
enum TerrainFile::Constants
Enumerator
FILE_VERSION
Constructor & Destructor Documentation
TerrainFile::TerrainFile ()
virtual TerrainFile::~TerrainFile () virtual
Member Function Documentation
void TerrainFile::_buildGridMap () protected
void TerrainFile::_initMaterialInstMapping () protected
void TerrainFile::_load (FileStream & stream) protected
The internal loading function.
void TerrainFile::_loadLegacy (FileStream & stream) protected
The legacy file loading code.
void TerrainFile::_resolveMaterials (const Vector< String > & materials) protected
Used to populate the materail vector by finding the TerrainMaterial objects by name.
static void TerrainFile::create (String * inOutFilename, U32 newSize, const Vector< String > & materials) static
TerrainSquare * TerrainFile::findSquare (U32 level, U32 x, U32 y) const inline
U16 TerrainFile::getHeight (U32 x, U32 y) const inline
const U16 * TerrainFile::getHeightAddress (U32 x, U32 y) const inline
const Vector<U16>& TerrainFile::getHeightMap () const inline
Returns the constant heightmap vector.
U8 TerrainFile::getLayerIndex (U32 x, U32 y) const inline
BaseMatInstance * TerrainFile::getMaterialMapping (U32 index) const inline
StringTableEntry TerrainFile::getMaterialName (U32 x, U32 y) const inline
References SimObject::getInternalName().
U16 TerrainFile::getMaxHeight () const inline
void TerrainFile::import (const GBitmap & heightMap, F32 heightScale, const Vector< U8 > & layerMap, const Vector< String > & materials, bool flipYAxis = true)
bool TerrainFile::isEmptyAt (U32 x, U32 y) const inline
References TerrainBlock::getHeight(), and TerrainBlock::setHeight().
bool TerrainFile::isPointInTerrain (U32 x, U32 y) const inline
Check if the given point is valid within the (non-tiled) terrain file.
static TerrainFile* TerrainFile::load (const Torque::Path & path) static
bool TerrainFile::save (const char * filename)
void TerrainFile::setHeight (U32 x, U32 y, U16 height) inline
void TerrainFile::setHeightMap (const Vector< U16 > & heightmap, bool updateCollision)
Sets a new heightmap state.
void TerrainFile::setLayerIndex (U32 x, U32 y, U8 index) inline
void TerrainFile::setSize (U32 newResolution, bool clear)
void TerrainFile::smooth (F32 factor, U32 steps, bool updateCollision)
Performs multiple smoothing steps on the heightmap.
void TerrainFile::updateGrid (const Point2I & minPt, const Point2I & maxPt)
Updates the terrain grid for the specified area.
Member Data Documentation
Torque::Path TerrainFile::mFilePath protected
The full path and name of the TerrainFile.
U32 TerrainFile::mFileVersion protected
The file version.
U32 TerrainFile::mGridLevels protected
Vector<TerrainSquare*> TerrainFile::mGridMap protected
The grid map layers used to accelerate collision queries for the height map data.
Vector<TerrainSquare> TerrainFile::mGridMapPool protected
The memory pool used by the grid map layers.
Vector<U16> TerrainFile::mHeightMap protected
The fixed point height map.
See also
fixedToFloat
Vector<U8> TerrainFile::mLayerMap protected
The layer index at each height map sample.
Referenced by TerrainBlock::getLayerMap(), and TerrainBlock::setLayerMap().
MaterialList TerrainFile::mMaterialInstMapping protected
MaterialList used to map terrain materials to material instances for the sake of collision (physics, etc.).
Vector<TerrainMaterial*> TerrainFile::mMaterials protected
The materials used to render the terrain.
Referenced by TerrainBlock::getMaterials(), and TerrainBlock::setMaterials().
bool TerrainFile::mNeedsResaving protected
The dirty flag.
U32 TerrainFile::mSize protected
The dimensions of the layer and height maps.
Referenced by TerrainBlock::getBlockSize(), and TerrainBlock::getWorldBlockSize().
Copyright © GarageGames, LLC. All Rights Reserved.