WeakRefBase::WeakReference Class Reference
Main Modules Class List Namespace List Online
WeakRefBase::WeakReference Class Reference
Weak reference to WeakRefBase.
#include <core/util/refBase.h>
Public Member Functions
void decRefCount ()
WeakRefBase * get ()
U32 getRefCount ()
void incRefCount ()
Detailed Description
Weak reference to WeakRefBase.
Member Function Documentation
void WeakRefBase::WeakReference::decRefCount () inline
Referenced by StrongWeakRefPtr< SFXVoice >::operator=().
WeakRefBase* WeakRefBase::WeakReference::get () inline
Referenced by StrongWeakRefPtr< SFXVoice >::operator=().
U32 WeakRefBase::WeakReference::getRefCount () inline
void WeakRefBase::WeakReference::incRefCount () inline
Referenced by StrongWeakRefPtr< SFXVoice >::operator=().
Copyright © GarageGames, LLC. All Rights Reserved.