ProcessedFFMaterial Class Reference
Main Modules Class List Namespace List Online
ProcessedFFMaterial Class Reference
Fixed function rendering.
#include <materials/processedFFMaterial.h>
Classes
struct FixedFuncFeatureData
Public Member Functions
ProcessedFFMaterial ()
ProcessedFFMaterial (Material &mat, const bool isLightingMaterial=false)
~ProcessedFFMaterial ()
virtual U32 getNumStages ()
Returns the number of stages we're using (not to be confused with the number of passes)
virtual bool init (const FeatureSet &features, const GFXVertexFormat *vertexFormat, const MatFeaturesDelegate &featuresDelegate)
Initializes us (eg. loads textures, creates passes, generates shaders)
virtual bool setupPass (SceneRenderState *, const SceneData &sgData, U32 pass)
Sets up the given pass.
Render state setting
virtual void setTextureStages (SceneRenderState *, const SceneData &sgData, U32 pass)
Sets necessary textures and texture ops for rendering.
virtual MaterialParameters * allocMaterialParameters ()
virtual MaterialParameterHandle * getMaterialParameterHandle (const String &name)
virtual MaterialParameters * getDefaultMaterialParameters ()
virtual void setTransforms (const MatrixSet &matrixSet, SceneRenderState *state, const U32 pass)
Sets the transformation matrix, i.e. Model * View * Projection.
virtual void setNodeTransforms (const MatrixF *address, const U32 numTransforms, const U32 pass)
Sets the node transforms for HW Skinning.
virtual void setSceneInfo (SceneRenderState *, const SceneData &sgData, U32 pass)
Sets the scene info like lights for the given pass.
Public Member Functions inherited from ProcessedMaterial
ProcessedMaterial ()
virtual ~ProcessedMaterial ()
virtual void dumpMaterialInfo ()
Dump shader info, or FF texture info?
const FeatureSet & getFeatures () const
Returns the active features in use by this material.
Material * getMaterial () const
Returns the source material.
virtual MaterialParameters * getMaterialParameters ()
U32 getNumPasses () const
Returns the number of passes we are rendering (not to be confused with the number of stages).
RenderPassData * getPass (U32 pass)
Returns the pass data for the given pass.
const RenderPassData * getPass (U32 pass) const
Returns the pass data for the given pass.
U32 getStageFromPass (U32 pass) const
Gets the stage number for a pass.
GFXTexHandle getStageTexture (U32 stage, const FeatureType &type)
Returns the texture used by a stage.
virtual const MatStateHint & getStateHint () const
Returns the state hint which can be used for sorting and fast comparisions of the equality of a material instance.
bool hasAccumulation () const
Returns true if any pass accumulates.
bool hasGlow () const
Returns true if any pass glows.
virtual void setMaterialParameters (MaterialParameters *param, S32 pass)
virtual void addStateBlockDesc (const GFXStateBlockDesc &sb)
virtual void updateStateBlocks ()
virtual void setShaderMacros (const Vector< GFXShaderMacro > &macros)
Set the user defined shader macros.
virtual void setBuffers (GFXVertexBufferHandleBase *vertBuffer, GFXPrimitiveBufferHandle *primBuffer)
Sets the given vertex and primitive buffers so we can render geometry.
virtual void setUserObject (SimObject *userObject)
virtual bool stepInstance ()
Protected Member Functions
void _construct ()
Internal functions
virtual void _addPass (U32 stageNum, FixedFuncFeatureData &featData)
Adds a pass for the given stage.
virtual void _setPassBlendOp ()
Chooses a blend op for the pass during pass creation.
void _createPasses (U32 stageNum, const FeatureSet &features)
Creates all necessary passes for the given stage.
void _determineFeatures (U32 stageNum, FixedFuncFeatureData &featData, const FeatureSet &features)
Determine what features we need.
virtual void _setPrimaryLightInfo (const MatrixF &objTrans, LightInfo *light, U32 pass)
Sets light info for the first light.
virtual void _setSecondaryLightInfo (const MatrixF &objTrans, LightInfo *light)
Sets light info for the second light.
virtual void _initPassStateBlock (RenderPassData *rpd, GFXStateBlockDesc &result)
Does the base render state block setting, normally per pass.
Protected Member Functions inherited from ProcessedMaterial
GFXTexHandle _createTexture (const char *filename, GFXTextureProfile *profile)
Loads the texture located at _getTexturePath(filename) and gives it the specified profile.
String _getTexturePath (const String &filename)
Returns the path the material will attempt to load for a given texture filename.
void _setBlendState (Material::BlendOp blendOp, GFXStateBlockDesc &desc)
Sets the blend state for rendering.
virtual void _setStageData ()
Loads all the textures for all of the stages in the Material.
virtual void _initStateBlockTemplates (GFXStateBlockDesc &stateTranslucent, GFXStateBlockDesc &stateGlow, GFXStateBlockDesc &stateReflect)
Creates the default state block templates, used by initStateBlocks.
virtual void _initRenderStateStateBlocks (RenderPassData *rpd)
Creates the default state blocks for a list of render states.
virtual void _initRenderPassDataStateBlocks ()
Creates the default state blocks for each RenderPassData item.
virtual U32 _getRenderStateIndex (const SceneRenderState *state, const SceneData &sgData)
This returns the index into the renderState array based on the sgData passed in.
virtual void _setRenderState (const SceneRenderState *state, const SceneData &sgData, U32 pass)
Activates the correct mPasses[currPass].renderState based on scene graph info.
Protected Attributes
MaterialParameterHandle * mDefaultHandle
MaterialParameters * mDefaultParameters
bool mIsLightingMaterial
Vector< GFXShaderConstDesc > mParamDesc
Protected Attributes inherited from ProcessedMaterial
MaterialParameters * mCurrentParams
FeatureSet mFeatures
The active features in use by this material.
bool mHasAccumulation
If we have accumulation.
bool mHasGlow
If we glow.
bool mHasSetStageData
If we've already loaded the stage data.
Material * mMaterial
The material which we are processing.
U32 mMaxStages
Number of stages (not to be confused with number of passes)
Vector< RenderPassData * > mPasses
Our passes.
Material::StageData mStages [Material::MAX_STAGES]
Material::StageData is used here because the shader generator throws a fit if it's passed anything else.
MatStateHint mStateHint
The state hint used for material sorting and quick equality comparision.
GFXStateBlockDesc mUserDefined
Set by addStateBlockDesc, should be considered when initPassStateBlock is called.
Vector< GFXShaderMacro > mUserMacros
The user defined macros to pass to the shader initialization.
SimObject * mUserObject
The user defined object to pass to ShaderFeature::createConstHandles.
const GFXVertexFormat * mVertexFormat
The vertex format on which this material will render.
Detailed Description
Fixed function rendering.
Does not load or use shaders. Does not rely on GFXMaterialFeatureData. Tries very hard to not rely on anything possibly related to shaders.
Note
Does not always succeed.
Constructor & Destructor Documentation
ProcessedFFMaterial::ProcessedFFMaterial ()
ProcessedFFMaterial::ProcessedFFMaterial (Material & mat, const bool isLightingMaterial = false)
ProcessedFFMaterial::~ProcessedFFMaterial ()
Member Function Documentation
virtual void ProcessedFFMaterial::_addPass (U32 stageNum, FixedFuncFeatureData & featData) protected virtual
Adds a pass for the given stage.
void ProcessedFFMaterial::_construct () protected
void ProcessedFFMaterial::_createPasses (U32 stageNum, const FeatureSet & features) protected
Creates all necessary passes for the given stage.
void ProcessedFFMaterial::_determineFeatures (U32 stageNum, FixedFuncFeatureData & featData, const FeatureSet & features) protected
Determine what features we need.
virtual void ProcessedFFMaterial::_initPassStateBlock (RenderPassData * rpd, GFXStateBlockDesc & result) protected virtual
Does the base render state block setting, normally per pass.
Reimplemented from ProcessedMaterial.
virtual void ProcessedFFMaterial::_setPassBlendOp () protected virtual
Chooses a blend op for the pass during pass creation.
virtual void ProcessedFFMaterial::_setPrimaryLightInfo (const MatrixF & objTrans, LightInfo * light, U32 pass) protected virtual
Sets light info for the first light.
virtual void ProcessedFFMaterial::_setSecondaryLightInfo (const MatrixF & objTrans, LightInfo * light) protected virtual
Sets light info for the second light.
virtual MaterialParameters* ProcessedFFMaterial::allocMaterialParameters () virtual
Implements ProcessedMaterial.
virtual MaterialParameters* ProcessedFFMaterial::getDefaultMaterialParameters () virtual
Implements ProcessedMaterial.
virtual MaterialParameterHandle* ProcessedFFMaterial::getMaterialParameterHandle (const String & name) virtual
Implements ProcessedMaterial.
virtual U32 ProcessedFFMaterial::getNumStages () virtual
Returns the number of stages we're using (not to be confused with the number of passes)
Implements ProcessedMaterial.
Referenced by setNodeTransforms().
virtual bool ProcessedFFMaterial::init (const FeatureSet & features, const GFXVertexFormat * vertexFormat, const MatFeaturesDelegate & featuresDelegate) virtual
Initializes us (eg. loads textures, creates passes, generates shaders)
Implements ProcessedMaterial.
Referenced by setNodeTransforms().
virtual void ProcessedFFMaterial::setNodeTransforms (const MatrixF * address, const U32 numTransforms, const U32 pass) inline virtual
Sets the node transforms for HW Skinning.
Implements ProcessedMaterial.
References getNumStages(), init(), setSceneInfo(), and setupPass().
virtual void ProcessedFFMaterial::setSceneInfo (SceneRenderState * , const SceneData & sgData, U32 pass) virtual
Sets the scene info like lights for the given pass.
Implements ProcessedMaterial.
Referenced by setNodeTransforms().
virtual void ProcessedFFMaterial::setTextureStages (SceneRenderState * , const SceneData & sgData, U32 pass) virtual
Sets necessary textures and texture ops for rendering.
Implements ProcessedMaterial.
virtual void ProcessedFFMaterial::setTransforms (const MatrixSet & matrixSet, SceneRenderState * state, const U32 pass) virtual
Sets the transformation matrix, i.e. Model * View * Projection.
Implements ProcessedMaterial.
virtual bool ProcessedFFMaterial::setupPass (SceneRenderState * , const SceneData & sgData, U32 pass) virtual
Sets up the given pass.
Returns
false if the pass could not be set up
Implements ProcessedMaterial.
Referenced by setNodeTransforms().
Member Data Documentation
MaterialParameterHandle* ProcessedFFMaterial::mDefaultHandle protected
MaterialParameters* ProcessedFFMaterial::mDefaultParameters protected
bool ProcessedFFMaterial::mIsLightingMaterial protected
Vector<GFXShaderConstDesc> ProcessedFFMaterial::mParamDesc protected
Copyright © GarageGames, LLC. All Rights Reserved.