SFXWorld< NUM_DIMENSIONS, Object > Class Template Reference
Main Modules Class List Namespace List Online
SFXWorld< NUM_DIMENSIONS, Object > Class Template Reference
SFXWorld tracks an N-dimensional world of SFXObjects.
#include <sfx/sfxWorld.h>
Classes
struct Scope
Record for objects that are currently in scope.
Public Types
typedef ScopeTracker< NUM_DIMENSIONS, Object > Parent
Public Types inherited from ScopeTracker< NUM_DIMENSIONS, Object >
typedef ObjectType::TrackingNode NodeType
typedef TypeTraits< Object >::BaseType ObjectType
typedef void Parent
Public Member Functions
SFXWorld ()
void notifyChanged (Object object)
void update ()
Update the state of the SFX world.
Public Member Functions inherited from ScopeTracker< NUM_DIMENSIONS, Object >
ScopeTracker ()
void debugDump ()
Object getReferenceObject () const
void registerObject (Object object)
Add a volume object to the world.
void setReferenceObject (Object object)
void unregisterObject (Object object)
Remove a volume object from the world.
void updateObject (Object object)
Update the position of the object in the world.
Protected Member Functions
S32 _findScope (Object object)
Return the index on the scope stack that is tied to the given object or -1 if the object is not on the stack.
F32 _getSortValue (Object object)
virtual void _onScopeIn (Object object)
virtual void _onScopeOut (Object object)
void _sortScopes ()
Protected Member Functions inherited from ScopeTracker< NUM_DIMENSIONS, Object >
void _setScope (Object object)
Set the scoping state of the given object.
void _insertTrackingNode (U32 dimension, NodeType *node)
void _removeTrackingNode (U32 dimension, NodeType *node)
void _moveTrackingNode (U32 dimension, NodeType *node, F32 newPos)
void _initTracking ()
void _uninitTracking ()
Protected Attributes
Vector< Scope > mScopeStack
A top-down ordering of all objects that are currently in scope.
Protected Attributes inherited from ScopeTracker< NUM_DIMENSIONS, Object >
NodeType mBoundaryNodes [NUM_DIMENSIONS][2]
Vector< Object > mPotentialScopeInObjects
Object mReferenceObject
The reference object.
NodeType * mTrackingList [NUM_DIMENSIONS][2]
Additional Inherited Members
Protected Types inherited from ScopeTracker< NUM_DIMENSIONS, Object >
enum {
MIN = 0,
MAX = 1
}
Detailed Description
template<S32 NUM_DIMENSIONS, typename Object>
class SFXWorld< NUM_DIMENSIONS, Object >
SFXWorld tracks an N-dimensional world of SFXObjects.
This class uses two systems as back-ends: occlusion handling is passed on to the occlusion manager installed on the system and tracking the listener traveling through the ambient spaces is
Member Typedef Documentation
template<S32 NUM_DIMENSIONS, typename Object> typedef ScopeTracker< NUM_DIMENSIONS, Object > SFXWorld< NUM_DIMENSIONS, Object >::Parent
Constructor & Destructor Documentation
template<S32 NUM_DIMENSIONS, class Object > SFXWorld< NUM_DIMENSIONS, Object >::SFXWorld ()
Member Function Documentation
template<S32 NUM_DIMENSIONS, class Object> S32 SFXWorld< NUM_DIMENSIONS, Object >::_findScope (Object object) protected
Return the index on the scope stack that is tied to the given object or -1 if the object is not on the stack.
template<S32 NUM_DIMENSIONS, class Object> F32 SFXWorld< NUM_DIMENSIONS, Object >::_getSortValue (Object object) protected
template<int NUM_DIMENSIONS, class Object> void SFXWorld< NUM_DIMENSIONS, Object >::_onScopeIn (Object object) protected virtual
Reimplemented from ScopeTracker< NUM_DIMENSIONS, Object >.
References Platform::outputDebugString().
template<S32 NUM_DIMENSIONS, class Object> void SFXWorld< NUM_DIMENSIONS, Object >::_onScopeOut (Object object) protected virtual
Reimplemented from ScopeTracker< NUM_DIMENSIONS, Object >.
References SFXWorld< NUM_DIMENSIONS, Object >::Scope::mSoundscape, and Platform::outputDebugString().
template<S32 NUM_DIMENSIONS, typename Object> void SFXWorld< NUM_DIMENSIONS, Object >::_sortScopes () protected
template<S32 NUM_DIMENSIONS, class Object> void SFXWorld< NUM_DIMENSIONS, Object >::notifyChanged (Object object)
References SFXWorld< NUM_DIMENSIONS, Object >::Scope::mObject, SFXWorld< NUM_DIMENSIONS, Object >::Scope::mSoundscape, and SFXSoundscape::setAmbience().
template<S32 NUM_DIMENSIONS, class Object > void SFXWorld< NUM_DIMENSIONS, Object >::update ()
Update the state of the SFX world.
Note
This method may potentially be costly; don't update every frame.
References SFXSoundscapeManager::insertSoundscape(), SFXWorld< NUM_DIMENSIONS, Object >::Scope::mObject, SFXWorld< NUM_DIMENSIONS, Object >::Scope::mSoundscape, and SFXSoundscapeManager::removeSoundscape().
Member Data Documentation
template<S32 NUM_DIMENSIONS, typename Object> Vector< Scope > SFXWorld< NUM_DIMENSIONS, Object >::mScopeStack protected
A top-down ordering of all objects that are currently in scope.
Copyright © GarageGames, LLC. All Rights Reserved.