GLOrderedFenceRangeManager Class Reference
Main Modules Class List Namespace List Online
GLOrderedFenceRangeManager Class Reference
#include <gfx/gl/gfxGLCircularVolatileBuffer.h>
Public Member Functions
~GLOrderedFenceRangeManager ()
void protectOrderedRange (U32 start, U32 end)
void waitAllRanges ()
void waitFirstRange (U32 start, U32 end)
void waitOverlapRanges (U32 start, U32 end)
Protected Attributes
Vector< GLFenceRange > mFenceRanges
Constructor & Destructor Documentation
GLOrderedFenceRangeManager::~GLOrderedFenceRangeManager () inline
Member Function Documentation
void GLOrderedFenceRangeManager::protectOrderedRange (U32 start, U32 end) inline
References GLFenceRange::init().
void GLOrderedFenceRangeManager::waitAllRanges () inline
References GLFenceRange::wait().
void GLOrderedFenceRangeManager::waitFirstRange (U32 start, U32 end) inline
void GLOrderedFenceRangeManager::waitOverlapRanges (U32 start, U32 end) inline
References GLFenceRange::checkOverlap().
Member Data Documentation
Vector<GLFenceRange> GLOrderedFenceRangeManager::mFenceRanges protected
Copyright © GarageGames, LLC. All Rights Reserved.