AsyncPacketQueue< Packet, TimeSource, Consumer, Tick > Class Template Reference
Main Modules Class List Namespace List Online
AsyncPacketQueue< Packet, TimeSource, Consumer, Tick > Class Template Reference
Time-based packet stream queue.
#include <platform/async/asyncPacketQueue.h>
Classes
struct QueuedPacket
Information about the time slice covered by an individual packet currently on the queue.
Public Types
typedef TypeTraits< Consumer >::BaseType ConsumerType
The type of consumer that receives the packets from this queue.
typedef TypeTraits< Packet >::BaseType PacketType
The type of data packets being streamed through this queue.
typedef void Parent
typedef Tick TickType
Type for counting ticks.
typedef TypeTraits< TimeSource >::BaseType TimeSourceType
Public Member Functions
AsyncPacketQueue (U32 maxQueuedPackets, TimeSource timeSource, Consumer consumer, TickType totalTicks=0, bool dropPackets=false)
Construct an AsyncPacketQueue of the given length.
TickType getCurrentTick () const
Return the current playback position according to the time source.
U32 getTotalQueuedPackets () const
Return the total number of packets that have been queued so far.
TickType getTotalQueuedTicks () const
Return the total number of ticks that have been queued so far.
bool isAtEnd () const
Return true if all packets have been streamed.
bool isEmpty () const
Return true if there are currently.
bool needPacket ()
Return true if the queue needs one or more new packets to be submitted.
bool submitPacket (Packet packet, TickType packetTicks, bool isLast=false, TickType packetPos=TypeTraits< TickType >::MAX)
Submit a data packet to the queue.
Protected Types
typedef FixedSizeDeque< QueuedPacket > PacketQueue
Protected Attributes
Consumer mConsumer
The output stream that this queue feeds into.
bool mDropPackets
If true, packets that have missed their proper queuing timeframe will be dropped.
PacketQueue mPacketQueue
Queue that holds records for each packet currently in the queue.
TimeSource mTimeSource
The time source to which we are sync'ing.
U32 mTotalQueuedPackets
Total number of packets queued so far.
TickType mTotalQueuedTicks
Total number of ticks submitted to the queue so far.
TickType mTotalTicks
Total number of ticks spanned by the total queue playback time.
Detailed Description
template<typename Packet, typename TimeSource = IPositionable< U32 >*, typename Consumer = IOutputStream< Packet >*, typename Tick = U32>
class AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >
Time-based packet stream queue.
AsyncPacketQueue writes data packets to a consumer stream in sync to a tick time source. Outdated packets may optionally be dropped automatically by the queue. A fixed maximum number of packets can reside in the queue concurrently at any one time.
Be aware that using single item queues for synchronizing to a timer will usually result in bad timing behavior when packet uploading takes any non-trivial amount of time.
Note
While the queue associates a variable tick count with each individual packet, the queue fill status is measured in number of packets rather than in total tick time.
Parameters
Packet Value type of packets passed through this queue.
TimeSource Value type for time tick source to which the queue is synchronized.
Consumer Value type of stream to which the packets are written.
Member Typedef Documentation
template<typename Packet, typename TimeSource = IPositionable< U32 >*, typename Consumer = IOutputStream< Packet >*, typename Tick = U32> typedef TypeTraits< Consumer >::BaseType AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::ConsumerType
The type of consumer that receives the packets from this queue.
template<typename Packet, typename TimeSource = IPositionable< U32 >*, typename Consumer = IOutputStream< Packet >*, typename Tick = U32> typedef FixedSizeDeque< QueuedPacket > AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::PacketQueue protected
template<typename Packet, typename TimeSource = IPositionable< U32 >*, typename Consumer = IOutputStream< Packet >*, typename Tick = U32> typedef TypeTraits< Packet >::BaseType AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::PacketType
The type of data packets being streamed through this queue.
template<typename Packet, typename TimeSource = IPositionable< U32 >*, typename Consumer = IOutputStream< Packet >*, typename Tick = U32> typedef void AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::Parent
template<typename Packet, typename TimeSource = IPositionable< U32 >*, typename Consumer = IOutputStream< Packet >*, typename Tick = U32> typedef Tick AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::TickType
Type for counting ticks.
template<typename Packet, typename TimeSource = IPositionable< U32 >*, typename Consumer = IOutputStream< Packet >*, typename Tick = U32> typedef TypeTraits< TimeSource >::BaseType AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::TimeSourceType
Constructor & Destructor Documentation
template<typename Packet, typename TimeSource = IPositionable< U32 >*, typename Consumer = IOutputStream< Packet >*, typename Tick = U32> AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::AsyncPacketQueue (U32 maxQueuedPackets, TimeSource timeSource, Consumer consumer, TickType totalTicks = 0, bool dropPackets = false) inline
Construct an AsyncPacketQueue of the given length.
Parameters
maxQueuedPackets The length of the queue in packets. Only a maximum of 'maxQueuedPackets' packets can be concurrently in the queue at any one time.
timeSource The tick time source to which the queue synchronizes.
consumer The output stream that receives the packets in sync to timeSource.
totalTicks The total number of ticks that will be played back through the queue; if 0, the length is considered indefinite.
dropPackets Whether the queue should drop outdated packets; if dropped, a packet will not reach the consumer.
Member Function Documentation
template<typename Packet, typename TimeSource = IPositionable< U32 >*, typename Consumer = IOutputStream< Packet >*, typename Tick = U32> TickType AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::getCurrentTick () const inline
Return the current playback position according to the time source.
Referenced by AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::isAtEnd(), AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::needPacket(), and AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::submitPacket().
template<typename Packet, typename TimeSource = IPositionable< U32 >*, typename Consumer = IOutputStream< Packet >*, typename Tick = U32> U32 AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::getTotalQueuedPackets () const inline
Return the total number of packets that have been queued so far.
template<typename Packet, typename TimeSource = IPositionable< U32 >*, typename Consumer = IOutputStream< Packet >*, typename Tick = U32> TickType AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::getTotalQueuedTicks () const inline
Return the total number of ticks that have been queued so far.
template<typename Packet , typename TimeSource , typename Consumer , typename Tick > bool AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::isAtEnd () const inline
Return true if all packets have been streamed.
References AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::getCurrentTick(), AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::mDropPackets, AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::mTotalQueuedTicks, and AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::mTotalTicks.
Referenced by AsyncPacketQueue< SFXStreamPacket *, SFXVoiceTimeSource, SFXBuffer * >::isEmpty(), and AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::needPacket().
template<typename Packet, typename TimeSource = IPositionable< U32 >*, typename Consumer = IOutputStream< Packet >*, typename Tick = U32> bool AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::isEmpty (void) const inline
Return true if there are currently.
template<typename Packet , typename TimeSource , typename Consumer , typename Tick > bool AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::needPacket ()
Return true if the queue needs one or more new packets to be submitted.
References FixedSizeDeque< T >::capacity(), FixedSizeDeque< T >::front(), AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::getCurrentTick(), AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::isAtEnd(), AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::mPacketQueue, AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::mTotalQueuedPackets, Platform::outputDebugString(), FixedSizeDeque< T >::popFront(), and FixedSizeDeque< T >::size().
Referenced by AsyncPacketQueue< SFXStreamPacket *, SFXVoiceTimeSource, SFXBuffer * >::isEmpty().
template<typename Packet, typename TimeSource , typename Consumer , typename Tick > bool AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::submitPacket (Packet packet, TickType packetTicks, bool isLast = false, TickType packetPos = TypeTraits< TickType >::MAX)
Submit a data packet to the queue.
Parameters
packet The data packet.
packetTicks The duration of the packet in ticks.
isLast If true, the packet is the last one in the stream.
packetPos The absolute position of the packet in the stream; if this is not supplied the packet is assumed to immediately follow the preceding packet.
Returns
true if the packet has been queued or false if it has been dropped.
References FixedSizeDeque< T >::capacity(), AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::getCurrentTick(), AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::mConsumer, AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::mDropPackets, AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::mPacketQueue, AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::mTotalQueuedPackets, AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::mTotalQueuedTicks, AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::mTotalTicks, Platform::outputDebugString(), FixedSizeDeque< T >::pushBack(), AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::QueuedPacket::QueuedPacket(), and FixedSizeDeque< T >::size().
Referenced by AsyncPacketQueue< SFXStreamPacket *, SFXVoiceTimeSource, SFXBuffer * >::isEmpty().
Member Data Documentation
template<typename Packet, typename TimeSource = IPositionable< U32 >*, typename Consumer = IOutputStream< Packet >*, typename Tick = U32> Consumer AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::mConsumer protected
The output stream that this queue feeds into.
Referenced by AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::submitPacket().
template<typename Packet, typename TimeSource = IPositionable< U32 >*, typename Consumer = IOutputStream< Packet >*, typename Tick = U32> bool AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::mDropPackets protected
If true, packets that have missed their proper queuing timeframe will be dropped.
If false, they will be queued nonetheless.
Referenced by AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::isAtEnd(), and AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::submitPacket().
template<typename Packet, typename TimeSource = IPositionable< U32 >*, typename Consumer = IOutputStream< Packet >*, typename Tick = U32> PacketQueue AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::mPacketQueue protected
Queue that holds records for each packet currently in the queue.
New packets are added to back.
Referenced by AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::needPacket(), and AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::submitPacket().
template<typename Packet, typename TimeSource = IPositionable< U32 >*, typename Consumer = IOutputStream< Packet >*, typename Tick = U32> TimeSource AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::mTimeSource protected
The time source to which we are sync'ing.
template<typename Packet, typename TimeSource = IPositionable< U32 >*, typename Consumer = IOutputStream< Packet >*, typename Tick = U32> U32 AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::mTotalQueuedPackets protected
Total number of packets queued so far.
Referenced by AsyncPacketQueue< SFXStreamPacket *, SFXVoiceTimeSource, SFXBuffer * >::getTotalQueuedPackets(), AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::needPacket(), and AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::submitPacket().
template<typename Packet, typename TimeSource = IPositionable< U32 >*, typename Consumer = IOutputStream< Packet >*, typename Tick = U32> TickType AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::mTotalQueuedTicks protected
Total number of ticks submitted to the queue so far.
Referenced by AsyncPacketQueue< SFXStreamPacket *, SFXVoiceTimeSource, SFXBuffer * >::getTotalQueuedTicks(), AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::isAtEnd(), and AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::submitPacket().
template<typename Packet, typename TimeSource = IPositionable< U32 >*, typename Consumer = IOutputStream< Packet >*, typename Tick = U32> TickType AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::mTotalTicks protected
Total number of ticks spanned by the total queue playback time.
If this is zero, the total queue time is considered to be infinite.
Referenced by AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::isAtEnd(), and AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::submitPacket().
Copyright © GarageGames, LLC. All Rights Reserved.