ShadowMapManager Class Reference
Main Modules Class List Namespace List Online
ShadowMapManager Class Reference
#include <lighting/shadowMap/shadowMapManager.h>
Public Member Functions
ShadowMapManager ()
virtual ~ShadowMapManager ()
virtual void activate ()
virtual void deactivate ()
LightShadowMap * getCurrentDynamicShadowMap () const
LightShadowMap * getCurrentShadowMap () const
Return the current shadow map.
ShadowMapPass * getShadowMapPass () const
GFXTextureObject * getTapRotationTex ()
void setLightDynamicShadowMap (LightShadowMap *lm)
void setLightShadowMap (LightShadowMap *lm)
Sets the current shadowmap (used in setLightInfo/setTextureStage calls)
void setLightShadowMapForLight (LightInfo *light)
Looks up the shadow map for the light then sets it.
Public Member Functions inherited from ShadowManager
ShadowManager ()
virtual ~ShadowManager ()
virtual bool canActivate ()
const String & getManagerTypeName () const
virtual SceneManager * getSceneManager ()
Static Public Member Functions
static const char * getSingletonName ()
static void updateShadowDisable ()
Static Public Attributes
static Signal< void(void)> smShadowDeactivateSignal
The shadow map deactivation signal.
Static Public Attributes inherited from ShadowManager
static const String ManagerTypeName
Protected Member Functions
void _onPreRender (SceneManager *sg, const SceneRenderState *state)
void _onTextureEvent (GFXTexCallbackCode code)
Protected Attributes
LightShadowMap * mCurrentDynamicShadowMap
LightShadowMap * mCurrentShadowMap
bool mIsActive
ShadowMapPass * mShadowMapPass
GFXTexHandle mTapRotationTex
Constructor & Destructor Documentation
ShadowMapManager::ShadowMapManager ()
virtual ShadowMapManager::~ShadowMapManager () virtual
Member Function Documentation
void ShadowMapManager::_onPreRender (SceneManager * sg, const SceneRenderState * state) protected
void ShadowMapManager::_onTextureEvent (GFXTexCallbackCode code) protected
virtual void ShadowMapManager::activate () virtual
Reimplemented from ShadowManager.
Referenced by getShadowMapPass().
virtual void ShadowMapManager::deactivate () virtual
Reimplemented from ShadowManager.
Referenced by getShadowMapPass().
LightShadowMap* ShadowMapManager::getCurrentDynamicShadowMap () const inline
References mCurrentDynamicShadowMap.
LightShadowMap* ShadowMapManager::getCurrentShadowMap () const inline
Return the current shadow map.
References mCurrentShadowMap.
ShadowMapPass* ShadowMapManager::getShadowMapPass () const inline
References activate(), deactivate(), getTapRotationTex(), and mShadowMapPass.
static const char* ShadowMapManager::getSingletonName () inline static
GFXTextureObject* ShadowMapManager::getTapRotationTex ()
Referenced by getShadowMapPass().
void ShadowMapManager::setLightDynamicShadowMap (LightShadowMap * lm) inline
References mCurrentDynamicShadowMap, and setLightShadowMapForLight().
void ShadowMapManager::setLightShadowMap (LightShadowMap * lm) inline
Sets the current shadowmap (used in setLightInfo/setTextureStage calls)
References mCurrentShadowMap.
void ShadowMapManager::setLightShadowMapForLight (LightInfo * light)
Looks up the shadow map for the light then sets it.
Referenced by setLightDynamicShadowMap().
static void ShadowMapManager::updateShadowDisable () static
Member Data Documentation
LightShadowMap* ShadowMapManager::mCurrentDynamicShadowMap protected
Referenced by getCurrentDynamicShadowMap(), and setLightDynamicShadowMap().
LightShadowMap* ShadowMapManager::mCurrentShadowMap protected
Referenced by getCurrentShadowMap(), and setLightShadowMap().
bool ShadowMapManager::mIsActive protected
ShadowMapPass* ShadowMapManager::mShadowMapPass protected
Referenced by getShadowMapPass().
GFXTexHandle ShadowMapManager::mTapRotationTex protected
Signal<void(void)> ShadowMapManager::smShadowDeactivateSignal static
The shadow map deactivation signal.
Copyright © GarageGames, LLC. All Rights Reserved.