GBitmap Class Reference
Main Modules Class List Namespace List Online
GBitmap Class Reference
#include <gfx/bitmap/gBitmap.h>
Classes
struct Registration
Public Types
enum Constants { c_maxMipLevels = 13 }
Public Member Functions
GBitmap ()
GBitmap (const GBitmap &)
GBitmap (const U32 in_width, const U32 in_height, const bool in_extrudeMipLevels=false, const GFXFormat in_format=GFXFormatR8G8B8)
GBitmap (const U32 in_width, const U32 in_height, const U8 *data)
virtual ~GBitmap ()
void allocateBitmap (const U32 in_width, const U32 in_height, const bool in_extrudeMipLevels=false, const GFXFormat in_format=GFXFormatR8G8B8)
bool checkForTransparency ()
In general you will want to use this function if there is not a good spot in the bitmap loader(s) to check the alpha value of the pixels.
bool combine (const GBitmap *bitmapA, const GBitmap *bitmapB, const GFXTextureOp combineOp)
This method will combine bitmapA and bitmapB using the operation specified by combineOp.
void copyChannel (U32 index, GBitmap *outBitmap) const
Copies a color channel by index into the first channel of the output bitmap.
void copyRect (const GBitmap *in, const RectI &srcRect, const Point2I &dstPoint, const U32 srcMipLevel=0, const U32 dstMipLevel=0)
GBitmap * createPaddedBitmap () const
GBitmap * createPow2Bitmap () const
void deleteImage ()
void extrudeMipLevels (bool clearBorders=false)
void extrudeMipLevelsDetail ()
void fill (const ColorI &rColor)
Fills the first mip level of the bitmap with the specified color.
void fillWhite ()
An optimized version of fill().
U8 * getAddress (const S32 in_x, const S32 in_y, const U32 mipLevel=0)
const U8 * getAddress (const S32 in_x, const S32 in_y, const U32 mipLevel=0) const
const U8 * getBits (const U32 in_mipLevel=0) const
U32 getByteSize () const
U32 getBytesPerPixel () const
bool getColor (const U32 x, const U32 y, ColorI &rColor) const
U32 getDepth (const U32 in_mipLevel=0) const
GFXFormat getFormat () const
bool getHasTransparency () const
Use these functions to set and get the mHasTransparency value This is used to indicate that this bitmap has pixels that have an alpha value less than 255 (used by the auto-Material mapper)
U32 getHeight (const U32 in_mipLevel=0) const
U32 getNumMipLevels () const
U32 getWidth (const U32 in_mipLevel=0) const
U8 * getWritableBits (const U32 in_mipLevel=0)
bool read (Stream &io_rStream)
bool readBitmap (const String &bmType, Stream &ioStream)
Read a bitmap from a stream.
bool readMNG (Stream &io_rStream)
ColorF sampleTexel (F32 u, F32 v) const
bool setColor (const U32 x, const U32 y, const ColorI &rColor)
bool setFormat (GFXFormat fmt)
void setHasTransparency (bool hasTransparency)
template<class T , dsize_t mapLength>
void swizzle (const Swizzle< T, mapLength > *s)
bool write (Stream &io_rStream) const
bool writeBitmap (const String &bmType, Stream &ioStream, U32 compressionLevel=U32_MAX)
Write a bitmap to a stream.
bool writeMNG (Stream &io_rStream) const
Static Public Member Functions
static Resource< GBitmap > load (const Torque::Path &path)
Load the given bitmap file.
static bool sFindFile (const Torque::Path &path, Torque::Path *outPath)
Find the first file matching the registered extensions skipping the original.
static bool sFindFiles (const Torque::Path &path, Vector< Torque::Path > *outFoundPaths)
Given a path to a file, try all known extensions.
static const Registration * sFindRegInfo (const String &extension)
static String sGetExtensionList ()
Returns a space separated string of all registered extensions.
static void sRegisterFormat (const Registration &reg)
Static Public Attributes
static Vector< Registration > sRegistrations
Static Protected Member Functions
static Resource< GBitmap > _load (const Torque::Path &path)
static Resource< GBitmap > _search (const Torque::Path &path)
Member Enumeration Documentation
enum GBitmap::Constants
Enumerator
c_maxMipLevels
The maximum mipmap levels we support.
The current value lets us support up to 4096 x 4096 images.
Constructor & Destructor Documentation
GBitmap::GBitmap ()
Referenced by GBitmap::Registration::Registration().
GBitmap::GBitmap (const GBitmap &)
GBitmap::GBitmap (const U32 in_width, const U32 in_height, const bool in_extrudeMipLevels = false, const GFXFormat in_format = GFXFormatR8G8B8)
GBitmap::GBitmap (const U32 in_width, const U32 in_height, const U8 * data)
virtual GBitmap::~GBitmap () virtual
Referenced by GBitmap::Registration::Registration().
Member Function Documentation
static Resource<GBitmap> GBitmap::_load (const Torque::Path & path) static protected
Referenced by GBitmap::Registration::Registration().
static Resource<GBitmap> GBitmap::_search (const Torque::Path & path) static protected
Referenced by GBitmap::Registration::Registration().
void GBitmap::allocateBitmap (const U32 in_width, const U32 in_height, const bool in_extrudeMipLevels = false, const GFXFormat in_format = GFXFormatR8G8B8)
Referenced by GBitmap::Registration::Registration().
bool GBitmap::checkForTransparency ()
In general you will want to use this function if there is not a good spot in the bitmap loader(s) to check the alpha value of the pixels.
This function uses the texture format to loop over the bitmap bits and to check for alpha values less than 255
Referenced by setHasTransparency().
bool GBitmap::combine (const GBitmap * bitmapA, const GBitmap * bitmapB, const GFXTextureOp combineOp)
This method will combine bitmapA and bitmapB using the operation specified by combineOp.
The result will be stored in the bitmap that this method is called on. The size of the resulting bitmap will be the larger of A and B. The format of the resulting bitmap will be the format of A or B, whichever has a larger byte size.
Note
There are some restrictions on ops and formats that will probably change based on how we use this function.
Referenced by setHasTransparency().
void GBitmap::copyChannel (U32 index, GBitmap * outBitmap) const
Copies a color channel by index into the first channel of the output bitmap.
The output bitmap must be the same dimensions as the source.
Referenced by getNumMipLevels().
void GBitmap::copyRect (const GBitmap * in, const RectI & srcRect, const Point2I & dstPoint, const U32 srcMipLevel = 0, const U32 dstMipLevel = 0)
Referenced by getNumMipLevels().
GBitmap* GBitmap::createPaddedBitmap () const
Referenced by getNumMipLevels().
GBitmap* GBitmap::createPow2Bitmap () const
Referenced by getNumMipLevels().
void GBitmap::deleteImage ()
Referenced by setHasTransparency().
void GBitmap::extrudeMipLevels (bool clearBorders = false)
Referenced by GBitmap::Registration::Registration().
void GBitmap::extrudeMipLevelsDetail ()
Referenced by GBitmap::Registration::Registration().
void GBitmap::fill (const ColorI & rColor)
Fills the first mip level of the bitmap with the specified color.
Referenced by setHasTransparency().
void GBitmap::fillWhite ()
An optimized version of fill().
Referenced by setHasTransparency().
U8 * GBitmap::getAddress (const S32 in_x, const S32 in_y, const U32 mipLevel = 0) inline
References getWidth(), and getWritableBits().
Referenced by getFormat().
const U8 * GBitmap::getAddress (const S32 in_x, const S32 in_y, const U32 mipLevel = 0) const inline
References getBits(), and getWidth().
const U8 * GBitmap::getBits (const U32 in_mipLevel = 0) const inline
Referenced by getAddress(), and getFormat().
U32 GBitmap::getByteSize () const inline
U32 GBitmap::getBytesPerPixel () const inline
bool GBitmap::getColor (const U32 x, const U32 y, ColorI & rColor) const
Referenced by setHasTransparency().
U32 GBitmap::getDepth (const U32 in_mipLevel = 0) const
Referenced by getFormat().
GFXFormat GBitmap::getFormat () const inline
References getAddress(), getBits(), getDepth(), getHeight(), getWidth(), getWritableBits(), and setFormat().
bool GBitmap::getHasTransparency () const inline
Use these functions to set and get the mHasTransparency value This is used to indicate that this bitmap has pixels that have an alpha value less than 255 (used by the auto-Material mapper)
U32 GBitmap::getHeight (const U32 in_mipLevel = 0) const inline
Referenced by getFormat(), and swizzle().
U32 GBitmap::getNumMipLevels () const inline
References copyChannel(), copyRect(), createPaddedBitmap(), and createPow2Bitmap().
U32 GBitmap::getWidth (const U32 in_mipLevel = 0) const inline
Referenced by getAddress(), getFormat(), and swizzle().
U8 * GBitmap::getWritableBits (const U32 in_mipLevel = 0) inline
Referenced by getAddress(), getFormat(), and swizzle().
static Resource<GBitmap> GBitmap::load (const Torque::Path & path) static
Load the given bitmap file.
It will try known file extensions if one is not specified. If all else fails it will look up the folder hierarchy for a match.
Important: Don't do something like this...
GBitmap* bitmap; // WRONG TYPE!
bitmap = GBitmap::load(filename);
Resources are reference-counted and the smart pointer conversion will release the bitmap and thus render the resulting bitmap pointer invalid! The right way is like this:
Resource<GBitmap> bitmap; // Correct!
bitmap = GBitmap::load(filename);
Referenced by GBitmap::Registration::Registration().
bool GBitmap::read (Stream & io_rStream)
Referenced by setHasTransparency().
bool GBitmap::readBitmap (const String & bmType, Stream & ioStream)
Read a bitmap from a stream.
Parameters
bmType This is a file extension to describe the type of the data [i.e. "png" for PNG file, etc]
ioStream The stream to read from
Referenced by setHasTransparency().
bool GBitmap::readMNG (Stream & io_rStream)
Referenced by setHasTransparency().
ColorF GBitmap::sampleTexel (F32 u, F32 v) const
Referenced by setHasTransparency().
bool GBitmap::setColor (const U32 x, const U32 y, const ColorI & rColor)
Referenced by setHasTransparency().
bool GBitmap::setFormat (GFXFormat fmt)
Referenced by getFormat().
void GBitmap::setHasTransparency (bool hasTransparency) inline
References checkForTransparency(), combine(), deleteImage(), fill(), fillWhite(), getColor(), read(), readBitmap(), readMNG(), sampleTexel(), setColor(), swizzle(), write(), writeBitmap(), and writeMNG().
static bool GBitmap::sFindFile (const Torque::Path & path, Torque::Path * outPath) static
Find the first file matching the registered extensions skipping the original.
Referenced by GBitmap::Registration::Registration().
static bool GBitmap::sFindFiles (const Torque::Path & path, Vector< Torque::Path > * outFoundPaths) static
Given a path to a file, try all known extensions.
If the file exists on disk, fill in path with the correct extension and return true. Otherwise, return false.
Referenced by GBitmap::Registration::Registration().
static const Registration* GBitmap::sFindRegInfo (const String & extension) static
Referenced by GBitmap::Registration::Registration().
static String GBitmap::sGetExtensionList () static
Returns a space separated string of all registered extensions.
Referenced by GBitmap::Registration::Registration().
static void GBitmap::sRegisterFormat (const Registration & reg) static
Referenced by GBitmap::Registration::Registration().
template<class T , dsize_t mapLength> void GBitmap::swizzle (const Swizzle< T, mapLength > * s)
References dFree(), dMalloc, dMemcpy(), getHeight(), getWidth(), getWritableBits(), and Swizzle< T, mapLength >::ToBuffer().
Referenced by setHasTransparency().
bool GBitmap::write (Stream & io_rStream) const
Referenced by setHasTransparency().
bool GBitmap::writeBitmap (const String & bmType, Stream & ioStream, U32 compressionLevel = U32_MAX)
Write a bitmap to a stream.
Parameters
bmType This is a file extension to describe the type of the data [i.e. "png" for PNG file, etc]
ioStream The stream to read from
compressionLevel Image format-specific compression level. If set to U32_MAX, we use the default compression defined when the format was registered.
Referenced by setHasTransparency().
bool GBitmap::writeMNG (Stream & io_rStream) const
Referenced by setHasTransparency().
Member Data Documentation
Vector<Registration> GBitmap::sRegistrations static
Copyright © GarageGames, LLC. All Rights Reserved.