ColladaExtension_animation_clip Class Reference
Main Modules Class List Namespace List Online
ColladaExtension_animation_clip Class Reference
#include <ts/collada/colladaExtensions.h>
Classes
struct Trigger
Public Member Functions
ColladaExtension_animation_clip (const domAnimation_clip *clip)
Public Member Functions inherited from ColladaExtension
ColladaExtension ()
virtual ~ColladaExtension ()
Public Attributes
bool blend
F32 blendReferenceTime
bool cyclic
S32 num_triggers
F32 priority
Vector< Trigger > triggers
Additional Inherited Members
Protected Member Functions inherited from ColladaExtension
template<class T >
const domTechnique * findExtraTechnique (const T *element, const char *name) const
Find the technique with the named profile.
const domTechnique * findExtraTechnique (const domCommon_color_or_texture_type_complexType::domTexture *element, const char *name) const
The <texture> element does not define an extra_array, so need a specialized version of the template.
const domAny * findParam (const char *name)
Find the parameter with the given name.
template<typename T >
void get (const char *name, T &value, T defaultVal)
Get the value of the named parameter (use defaultVal if parameter not found)
template<typename T >
void get (const char *name, AnimatedElement< T > &value, T defaultVal)
Get the value of the named animated parameter (use defaultVal if parameter not found)
Protected Attributes inherited from ColladaExtension
const domTechnique * pTechnique
Constructor & Destructor Documentation
ColladaExtension_animation_clip::ColladaExtension_animation_clip (const domAnimation_clip * clip) inline
References ColladaExtension::findExtraTechnique(), Vector< T >::increment(), Vector< T >::last(), and ColladaExtension::pTechnique.
Member Data Documentation
bool ColladaExtension_animation_clip::blend
F32 ColladaExtension_animation_clip::blendReferenceTime
bool ColladaExtension_animation_clip::cyclic
S32 ColladaExtension_animation_clip::num_triggers
F32 ColladaExtension_animation_clip::priority
Vector<Trigger> ColladaExtension_animation_clip::triggers
Copyright © GarageGames, LLC. All Rights Reserved.