SceneObjectLightingPlugin Class Reference
Main Modules Class List Namespace List Online
SceneObjectLightingPlugin Class Reference abstract
#include <scene/sceneObjectLightingPlugin.h>
Public Member Functions
virtual ~SceneObjectLightingPlugin ()
virtual U32 packUpdate (SceneObject *obj, U32 checkMask, NetConnection *conn, U32 mask, BitStream *stream)=0
virtual void reset ()
Reset light plugin to clean state.
virtual void unpackUpdate (SceneObject *obj, NetConnection *conn, BitStream *stream)=0
Constructor & Destructor Documentation
virtual SceneObjectLightingPlugin::~SceneObjectLightingPlugin () inline virtual
Member Function Documentation
virtual U32 SceneObjectLightingPlugin::packUpdate (SceneObject * obj, U32 checkMask, NetConnection * conn, U32 mask, BitStream * stream) pure virtual
Implemented in BasicSceneObjectLightingPlugin.
Referenced by reset().
virtual void SceneObjectLightingPlugin::reset (void) inline virtual
Reset light plugin to clean state.
Reimplemented in BasicSceneObjectLightingPlugin.
References packUpdate(), and unpackUpdate().
virtual void SceneObjectLightingPlugin::unpackUpdate (SceneObject * obj, NetConnection * conn, BitStream * stream) pure virtual
Implemented in BasicSceneObjectLightingPlugin.
Referenced by reset().
Copyright © GarageGames, LLC. All Rights Reserved.