Console System
Main Modules Class List Namespace List Online
Console System
The Console system is the basis for logging, SimObject, and TorqueScript itself.
Modules
Reflection
Exports console information to XML representation.
Script Auto-Documentation
Scripting Engine Callbacks
The scripting engine makes heavy use of callbacks to represent function exposed to the scripting language.
Scripting Engine Type Functions
Namespaces
Compiler
Con
This namespace contains the core of the console functionality.
Classes
struct _EngineConsoleExecCallbackHelper< P1 >
class ConsoleConstructor
This is the backend for the ConsoleMethod()/ConsoleFunction() macros.
struct ConsoleDocFragment
An arbitrary fragment of auto-doc text for the script reference.
struct ConsoleFunctionHeader
Extended information about a console function.
struct ConsoleLogEntry
Represents an entry in the log.
class ConsoleStackFrameSaver
Utility class to save and restore the current console stack frame.
class ConsoleValue
class ConsoleValueRef
class StringStackConsoleWrapper
class StringStackWrapper
Typedefs
typedef const char * StringTableEntry
Enumerations
enum StringTableConstants { StringTagPrefixByte = 0x01 }
Functions
bool collapseEscape (char *buf)
bool dAtob (ConsoleValue &ref)
F32 dAtof (ConsoleValueRef &ref)
S32 dAtoi (ConsoleValueRef &ref)
void expandEscape (char *dest, const char *src)
U32 HashPointer (StringTableEntry ptr)
Variables
bool gWarnUndefinedScriptVariables
Indicates that warnings about undefined script variables should be displayed.
char * typeValueEmpty
Global Console Definition Macros
Note
If TORQUE_DEBUG is defined, then we gather documentation information, and do some extra sanity checks.
See also
ConsoleConstructor console_autodoc
#define DECLARE_CALLBACK(returnType, name, args) virtual returnType name ## _callback args
Define a C++ method that calls back to script on an object.
#define conmethod_return_const return (const
#define conmethod_return_S32 return (S32
#define conmethod_return_F32 return (F32
#define conmethod_nullify(val)
#define conmethod_return_void conmethod_nullify(void
#define conmethod_return_bool return (bool
#define ConsoleFunctionGroupBegin(groupName, usage) static ConsoleConstructor cfg_ConsoleFunctionGroup_##groupName##_GroupBegin(NULL,#groupName,usage)
#define ConsoleFunction(name, returnType, minArgs, maxArgs, usage1)
#define ConsoleToolFunction(name, returnType, minArgs, maxArgs, usage1)
#define ConsoleFunctionGroupEnd(groupName) static ConsoleConstructor cfg_##groupName##_GroupEnd(NULL,#groupName,NULL)
#define ConsoleNamespace(className, usage) ConsoleConstructor cc_##className##_Namespace(#className, usage)
#define ConsoleMethodGroupBegin(className, groupName, usage) static ConsoleConstructor cc_##className##_##groupName##_GroupBegin(#className,#groupName,usage)
#define ConsoleMethod(className, name, returnType, minArgs, maxArgs, usage1)
#define ConsoleStaticMethod(className, name, returnType, minArgs, maxArgs, usage1)
#define ConsoleMethodGroupEnd(className, groupName) static ConsoleConstructor cc_##className##_##groupName##_GroupEnd(#className,#groupName,NULL)
#define ConsoleDoc(text)
Add a fragment of auto-doc text to the console API reference.
typedef ConsoleLogEntry::Level LogLevel
DefineEnumType (LogLevel)
DefineConsoleType (TypeBool, bool) DefineConsoleType(TypeBoolVector
Vector< bool > DefineConsoleType (TypeS8, S8) DefineConsoleType(TypeS32
Vector< bool > S32 DefineConsoleType (TypeS32Vector, Vector< S32 >) DefineConsoleType(TypeF32
Vector< bool > S32 F32 DefineConsoleType (TypeF32Vector, Vector< F32 >) DefineUnmappedConsoleType(TypeString
Vector< bool > S32 F32 const char * DefineConsoleType (TypeCaseString, const char *) DefineConsoleType(TypeRealString
Vector< bool > S32 F32 const char String DefineConsoleType (TypeCommand, String) DefineConsoleType(TypeFilename
Vector< bool > S32 F32 const char String const char * DefineConsoleType (TypeStringFilename, String) DefineConsoleType(TypeRotationF
Vector< bool > S32 F32 const char String const char RotationF DefineConsoleType (TypeUUID, Torque::UUID) DefineUnmappedConsoleType(TypePID
A universally unique identifier.
Vector< bool > S32 F32 const char String const char RotationF SimPersistID * DefineConsoleType (TypeImageFilename, String) DefineConsoleType(TypePrefabFilename
TypeImageFilename is equivalent to TypeStringFilename in its usage, it exists for the benefit of GuiInspector, which will provide a custom InspectorField for this type that can display a texture preview.
Vector< bool > S32 F32 const char String const char RotationF SimPersistID String DefineConsoleType (TypeShapeFilename, String) DefineConsoleType(TypeMaterialName
TypeShapeFilename is equivalent to TypeStringFilename in its usage, it exists for the benefit of GuiInspector, which will provide a custom InspectorField for this type.
Vector< bool > S32 F32 const char String const char RotationF SimPersistID String String DefineConsoleType (TypeTerrainMaterialIndex, S32) DefineConsoleType(TypeTerrainMaterialName
TypeTerrainMaterialIndex is equivalent to TypeS32 in its usage, it exists for the benefit of GuiInspector, which will provide a custom InspectorField for this type.
Vector< bool > S32 F32 const char String const char RotationF SimPersistID String String const char * DefineConsoleType (TypeCubemapName, String) DefineConsoleType(TypeParticleParameterString
TypeCubemapName is equivalent to TypeRealString in its usage, but the Inspector will provide a drop-down list of CubemapData objects.
Vector< bool > S32 F32 const char String const char RotationF SimPersistID String String const char const char * DefineConsoleType (TypeFlag, S32) DefineConsoleType(TypeColorI
Vector< bool > S32 F32 const char String const char RotationF SimPersistID String String const char const char ColorI DefineConsoleType (TypeColorF, ColorF) DefineConsoleType(TypeSimObjectName
Vector< bool > S32 F32 const char String const char RotationF SimPersistID String String const char const char ColorI SimObject * DefineConsoleType (TypeShader, GFXShader *) DefineConsoleType(TypeSimObjectPtr
Vector< bool > S32 F32 const char String const char RotationF SimPersistID String String const char const char ColorI SimObject SimObject * DefineConsoleType (TypeSimPersistId, SimPersistID *) DefineConsoleType(TypeName
A persistent reference to an object.
#define Offset(x, cls) offsetof(cls, x)
Detailed Description
The Console system is the basis for logging, SimObject, and TorqueScript itself.
Macro Definition Documentation
#define conmethod_nullify (val)
#define conmethod_return_bool return (bool
#define conmethod_return_const return (const
#define conmethod_return_F32 return (F32
#define conmethod_return_S32 return (S32
#define conmethod_return_void conmethod_nullify(void
#define ConsoleDoc (text)
Value:
namespace {                                           \
         ConsoleDocFragment _sDocFragment( text );           \
      }
Add a fragment of auto-doc text to the console API reference.
Note
There can only be one ConsoleDoc per source file.
#define ConsoleFunction (name, returnType, minArgs, maxArgs, usage1)
Value:
returnType cf_##name(SimObject *, S32, ConsoleValueRef *argv); \
   ConsoleConstructor cc_##name##_obj(NULL,#name,cf_##name,usage1,minArgs,maxArgs); \
      returnType cf_##name(SimObject *, S32 argc, ConsoleValueRef *argv)
#define ConsoleFunctionGroupBegin (groupName, usage) static ConsoleConstructor cfg_ConsoleFunctionGroup_##groupName##_GroupBegin(NULL,#groupName,usage)
#define ConsoleFunctionGroupEnd (groupName) static ConsoleConstructor cfg_##groupName##_GroupEnd(NULL,#groupName,NULL)
#define ConsoleMethod (className, name, returnType, minArgs, maxArgs, usage1)
Value:
inline returnType cm_##className##_##name(className *, S32, ConsoleValueRef *argv); \
   returnType cm_##className##_##name##_caster(SimObject *object, S32 argc, ConsoleValueRef *argv) { \
         AssertFatal( dynamic_cast<className*>( object ), "Object passed to " #name " is not a " #className "!" ); \
         conmethod_return_##returnType ) cm_##className##_##name(static_cast<className*>(object),argc,argv); \
      };                                                                                              \
      ConsoleConstructor cc_##className##_##name##_obj(#className,#name,cm_##className##_##name##_caster,usage1,minArgs,maxArgs); \
      inline returnType cm_##className##_##name(className *object, S32 argc, ConsoleValueRef *argv)
#define ConsoleMethodGroupBegin (className, groupName, usage) static ConsoleConstructor cc_##className##_##groupName##_GroupBegin(#className,#groupName,usage)
#define ConsoleMethodGroupEnd (className, groupName) static ConsoleConstructor cc_##className##_##groupName##_GroupEnd(#className,#groupName,NULL)
#define ConsoleNamespace (className, usage) ConsoleConstructor cc_##className##_Namespace(#className, usage)
#define ConsoleStaticMethod (className, name, returnType, minArgs, maxArgs, usage1)
Value:
inline returnType cm_##className##_##name(S32, ConsoleValueRef *); \
   returnType cm_##className##_##name##_caster(SimObject *object, S32 argc, ConsoleValueRef *argv) { \
   conmethod_return_##returnType ) cm_##className##_##name(argc,argv); \
   }; \
   ConsoleConstructor \
   cc_##className##_##name##_obj(#className,#name,cm_##className##_##name##_caster,usage1,minArgs,maxArgs); \
   inline returnType cm_##className##_##name(S32 argc, ConsoleValueRef *argv)
#define ConsoleToolFunction (name, returnType, minArgs, maxArgs, usage1)
Value:
returnType ctf_##name(SimObject *, S32, ConsoleValueRef *argv); \
   ConsoleConstructor cc_##name##_obj(NULL,#name,ctf_##name,usage1,minArgs,maxArgs, true); \
   returnType ctf_##name(SimObject *, S32 argc, ConsoleValueRef *argv)
#define DECLARE_CALLBACK (returnType, name, args) virtual returnType name ## _callback args
Define a C++ method that calls back to script on an object.
See also
consoleCallback.h
Referenced by ShapeBase::getMass().
#define Offset (x, cls) offsetof(cls, x)
Referenced by SceneAmbientSoundObject< Base >::initPersistFields().
Typedef Documentation
typedef ConsoleLogEntry::Level LogLevel
typedef const char* StringTableEntry
Enumeration Type Documentation
enum StringTableConstants
Enumerator
StringTagPrefixByte
Magic value prefixed to tagged strings.
Function Documentation
bool collapseEscape (char * buf)
Referenced by Con::executef().
bool dAtob (ConsoleValue & ref) inline
References ConsoleValue::getBoolValue().
Referenced by GuiControl::_setActive(), GuiControl::_setVisible(), TamlCustomField::getFieldValue(), ColladaPrimitive< T >::getTriangleData(), StateMachine::readFieldValue(), AssetBase::setAssetAutoUnload(), AssetBase::setAssetInternal(), ModuleDefinition::setDeprecated(), ModuleDefinition::setEnabled(), GuiRolloutCtrl::setExpanded(), WorldEditor::setObjectsUseBoxCenter(), ModuleDefinition::setSynchronized(), and TamlAssetDeclaredVisitor::visit().
F32 dAtof (ConsoleValueRef & ref) inline
References ConsoleValueRef::getFloatValue().
Referenced by GuiSliderCtrl::_setValue(), TamlCustomField::getFieldValue(), StringStack::getFloatValue(), ColladaPrimitive< T >::getTriangleData(), EngineUnmarshallData< U32 >::operator()(), StateMachine::readFieldValue(), and GuiSliderCtrl::setScriptValue().
S32 dAtoi (ConsoleValueRef & ref) inline
References ConsoleValueRef::getSignedIntValue().
Referenced by TamlCustomField::getFieldValue(), StringStack::getIntValue(), ColladaPrimitive< T >::getTriangleData(), EngineUnmarshallData< S32 >::operator()(), ModuleDefinition::setBuildId(), ModuleDefinition::setDependencies(), and ModuleDefinition::setVersionId().
DefineConsoleType (TypeBool , bool)
Referenced by RectSpacingI::expandRect(), ShapeAsset::getShapeResource(), ExampleAsset::onAssetRefresh(), GameObjectAsset::onAssetRefresh(), and ComponentAsset::onAssetRefresh().
Vector<bool> DefineConsoleType (TypeS8 , S8)
Vector<bool> S32 DefineConsoleType (TypeS32Vector , Vector< S32 >)
Vector<bool> S32 F32 DefineConsoleType (TypeF32Vector , Vector< F32 >)
Vector<bool> S32 F32 const char* DefineConsoleType (TypeCaseString , const char *)
Vector<bool> S32 F32 const char String DefineConsoleType (TypeCommand , String)
Vector<bool> S32 F32 const char String const char* DefineConsoleType (TypeStringFilename , String)
Vector<bool> S32 F32 const char String const char RotationF DefineConsoleType (TypeUUID , Torque::UUID)
A universally unique identifier.
A persistent ID that is associated with an object. This type cannot be used to reference PIDs of other objects.
Vector<bool> S32 F32 const char String const char RotationF SimPersistID* DefineConsoleType (TypeImageFilename , String)
TypeImageFilename is equivalent to TypeStringFilename in its usage, it exists for the benefit of GuiInspector, which will provide a custom InspectorField for this type that can display a texture preview.
TypePrefabFilename is equivalent to TypeStringFilename in its usage, it exists for the benefit of GuiInspector, which will provide a custom InspectorField for this type.
Vector<bool> S32 F32 const char String const char RotationF SimPersistID String DefineConsoleType (TypeShapeFilename , String)
TypeShapeFilename is equivalent to TypeStringFilename in its usage, it exists for the benefit of GuiInspector, which will provide a custom InspectorField for this type.
TypeMaterialName is equivalent to TypeRealString in its usage, it exists for the benefit of GuiInspector, which will provide a custom InspectorField for this type.
Vector<bool> S32 F32 const char String const char RotationF SimPersistID String String DefineConsoleType (TypeTerrainMaterialIndex , S32)
TypeTerrainMaterialIndex is equivalent to TypeS32 in its usage, it exists for the benefit of GuiInspector, which will provide a custom InspectorField for this type.
TypeTerrainMaterialName is equivalent to TypeString in its usage, it exists for the benefit of GuiInspector, which will provide a custom InspectorField for this type.
Vector<bool> S32 F32 const char String const char RotationF SimPersistID String String const char* DefineConsoleType (TypeCubemapName , String)
TypeCubemapName is equivalent to TypeRealString in its usage, but the Inspector will provide a drop-down list of CubemapData objects.
Vector<bool> S32 F32 const char String const char RotationF SimPersistID String String const char const char* DefineConsoleType (TypeFlag , S32)
Vector<bool> S32 F32 const char String const char RotationF SimPersistID String String const char const char ColorI DefineConsoleType (TypeColorF , ColorF)
Vector<bool> S32 F32 const char String const char RotationF SimPersistID String String const char const char ColorI SimObject* DefineConsoleType (TypeShader , GFXShader *)
Vector<bool> S32 F32 const char String const char RotationF SimPersistID String String const char const char ColorI SimObject SimObject* DefineConsoleType (TypeSimPersistId , SimPersistID *)
A persistent reference to an object.
This reference indirectly goes through the referenced object's persistent ID. Special field type for SimObject::objectName
DefineEnumType (LogLevel)
Referenced by GuiAutoScrollCtrl::_getScrollAmount(), GuiControlProfile::decUseCount(), CollisionComponent::getBestCollisionAngle(), Item::getCollisionObject(), GuiStackControl::getCount(), GuiScrollCtrl::getCurHitRegion(), GuiGradientCtrl::getDisplayMode(), TSStatic::getLOSDetails(), NavMesh::getNavMesh(), LeapMotionFrame::getPointablesCount(), GuiTabBookCtrl::getSelectedPageNum(), GuiColorPickerCtrl::getSelectorPos(), TSShapeConstructor::getShapePath(), SFXPlayList::getSlots(), GuiBitmapButtonCtrl::getState(), Camera::getValidEditOrbitPoint(), GuiGraphCtrl::setMax(), CoverPoint::setPeek(), GuiButtonBaseCtrl::setUseMouseEvents(), GuiTSCtrl::shouldRenderChildControls(), GuiFrameSetCtrl::updateSizes(), and GuiParticleGraphCtrl::~GuiParticleGraphCtrl().
void expandEscape (char * dest, const char * src)
Referenced by Con::executef().
U32 HashPointer (StringTableEntry ptr)
Referenced by Con::executef().
Variable Documentation
bool gWarnUndefinedScriptVariables
Indicates that warnings about undefined script variables should be displayed.
Note
This is set and controlled by script.
char* typeValueEmpty
Referenced by ConsoleValue::cleanup(), and ConsoleValue::init().
Copyright © GarageGames, LLC. All Rights Reserved.