Compiler Namespace Reference
Main Modules Class List Namespace List Online
Compiler Namespace Reference
Console System
Classes
struct CompilerFloatTable
struct CompilerIdentTable
struct CompilerStringTable
struct ConsoleParser
List of parsers for the compiler.
Typedefs
typedef const char *(* fnGetCurrentFile) ()
Function for GetCurrentFile from the lexer.
typedef S32(* fnGetCurrentLine) ()
Function for GetCurrentLine from the lexer.
typedef S32(* fnParse) ()
Function for Parse from the lexer.
typedef void(* fnRestart) (FILE *input_file)
Function for Restart from the lexer.
typedef void(* fnSetScanBuffer) (const char *sb, const char *fn)
Function for SetScanBuffer from the lexer.
Enumerations
enum CompiledInstructions {
OP_FUNC_DECL,
OP_CREATE_OBJECT,
OP_ADD_OBJECT,
OP_END_OBJECT,
OP_FINISH_OBJECT,
OP_JMPIFFNOT,
OP_JMPIFNOT,
OP_JMPIFF,
OP_JMPIF,
OP_JMPIFNOT_NP,
OP_JMPIF_NP,
OP_JMP,
OP_RETURN,
OP_RETURN_VOID,
OP_RETURN_FLT,
OP_RETURN_UINT,
OP_CMPEQ,
OP_CMPGR,
OP_CMPGE,
OP_CMPLT,
OP_CMPLE,
OP_CMPNE,
OP_XOR,
OP_MOD,
OP_BITAND,
OP_BITOR,
OP_NOT,
OP_NOTF,
OP_ONESCOMPLEMENT,
OP_SHR,
OP_SHL,
OP_AND,
OP_OR,
OP_ADD,
OP_SUB,
OP_MUL,
OP_DIV,
OP_NEG,
OP_SETCURVAR,
OP_SETCURVAR_CREATE,
OP_SETCURVAR_ARRAY,
OP_SETCURVAR_ARRAY_CREATE,
OP_LOADVAR_UINT,
OP_LOADVAR_FLT,
OP_LOADVAR_STR,
OP_LOADVAR_VAR,
OP_SAVEVAR_UINT,
OP_SAVEVAR_FLT,
OP_SAVEVAR_STR,
OP_SAVEVAR_VAR,
OP_SETCUROBJECT,
OP_SETCUROBJECT_NEW,
OP_SETCUROBJECT_INTERNAL,
OP_SETCURFIELD,
OP_SETCURFIELD_ARRAY,
OP_SETCURFIELD_TYPE,
OP_LOADFIELD_UINT,
OP_LOADFIELD_FLT,
OP_LOADFIELD_STR,
OP_SAVEFIELD_UINT,
OP_SAVEFIELD_FLT,
OP_SAVEFIELD_STR,
OP_STR_TO_UINT,
OP_STR_TO_FLT,
OP_STR_TO_NONE,
OP_FLT_TO_UINT,
OP_FLT_TO_STR,
OP_FLT_TO_NONE,
OP_UINT_TO_FLT,
OP_UINT_TO_STR,
OP_UINT_TO_NONE,
OP_COPYVAR_TO_NONE,
OP_LOADIMMED_UINT,
OP_LOADIMMED_FLT,
OP_TAG_TO_STR,
OP_LOADIMMED_STR,
OP_DOCBLOCK_STR,
OP_LOADIMMED_IDENT,
OP_CALLFUNC_RESOLVE,
OP_CALLFUNC,
OP_ADVANCE_STR,
OP_ADVANCE_STR_APPENDCHAR,
OP_ADVANCE_STR_COMMA,
OP_ADVANCE_STR_NUL,
OP_REWIND_STR,
OP_TERMINATE_REWIND_STR,
OP_COMPARE_STR,
OP_PUSH,
OP_PUSH_UINT,
OP_PUSH_FLT,
OP_PUSH_VAR,
OP_PUSH_FRAME,
OP_ASSERT,
OP_BREAK,
OP_ITER_BEGIN,
OP_ITER_BEGIN_STR,
OP_ITER,
OP_ITER_END,
OP_INVALID
}
The opcodes for the TorqueScript VM.
Functions
bool addConsoleParser (char *ext, fnGetCurrentFile gcf, fnGetCurrentLine gcl, fnParse p, fnRestart r, fnSetScanBuffer ssb, bool def=false)
Add a console parser to the list.
StringTableEntry CodeToSTE (U32 *code, U32 ip)
U32 compileBlock (StmtNode *block, CodeStream &codeStream, U32 ip)
void compileSTEtoCode (StringTableEntry ste, U32 ip, U32 *ptr)
void * consoleAlloc (U32 size)
void consoleAllocReset ()
F64 consoleStringToNumber (const char *str, StringTableEntry file=0, U32 line=0)
void evalSTEtoCode (StringTableEntry ste, U32 ip, U32 *ptr)
void freeConsoleParserList (void)
Free the console parser list.
CompilerFloatTable * getCurrentFloatTable ()
CompilerStringTable * getCurrentStringTable ()
CompilerFloatTable & getFunctionFloatTable ()
CompilerStringTable & getFunctionStringTable ()
CompilerFloatTable & getGlobalFloatTable ()
CompilerStringTable & getGlobalStringTable ()
CompilerIdentTable & getIdentTable ()
ConsoleParser * getParserForFile (const char *filename)
Get the parser for a particular file based on its extension.
void precompileIdent (StringTableEntry ident)
void resetTables ()
Helper function to reset the float, string, and ident tables to a base starting state.
void setCurrentFloatTable (CompilerFloatTable *cst)
void setCurrentStringTable (CompilerStringTable *cst)
Variables
bool gSyntaxError
void(* STEtoCode)(StringTableEntry ste, U32 ip, U32 *ptr)
Typedef Documentation
typedef const char*(* Compiler::fnGetCurrentFile) ()
Function for GetCurrentFile from the lexer.
typedef S32(* Compiler::fnGetCurrentLine) ()
Function for GetCurrentLine from the lexer.
typedef S32(* Compiler::fnParse) ()
Function for Parse from the lexer.
typedef void(* Compiler::fnRestart) (FILE *input_file)
Function for Restart from the lexer.
typedef void(* Compiler::fnSetScanBuffer) (const char *sb, const char *fn)
Function for SetScanBuffer from the lexer.
Enumeration Type Documentation
enum Compiler::CompiledInstructions
The opcodes for the TorqueScript VM.
Enumerator
OP_FUNC_DECL
OP_CREATE_OBJECT
OP_ADD_OBJECT
OP_END_OBJECT
OP_FINISH_OBJECT
OP_JMPIFFNOT
OP_JMPIFNOT
OP_JMPIFF
OP_JMPIF
OP_JMPIFNOT_NP
OP_JMPIF_NP
OP_JMP
OP_RETURN
OP_RETURN_VOID
OP_RETURN_FLT
OP_RETURN_UINT
OP_CMPEQ
OP_CMPGR
OP_CMPGE
OP_CMPLT
OP_CMPLE
OP_CMPNE
OP_XOR
OP_MOD
OP_BITAND
OP_BITOR
OP_NOT
OP_NOTF
OP_ONESCOMPLEMENT
OP_SHR
OP_SHL
OP_AND
OP_OR
OP_ADD
OP_SUB
OP_MUL
OP_DIV
OP_NEG
OP_SETCURVAR
OP_SETCURVAR_CREATE
OP_SETCURVAR_ARRAY
OP_SETCURVAR_ARRAY_CREATE
OP_LOADVAR_UINT
OP_LOADVAR_FLT
OP_LOADVAR_STR
OP_LOADVAR_VAR
OP_SAVEVAR_UINT
OP_SAVEVAR_FLT
OP_SAVEVAR_STR
OP_SAVEVAR_VAR
OP_SETCUROBJECT
OP_SETCUROBJECT_NEW
OP_SETCUROBJECT_INTERNAL
OP_SETCURFIELD
OP_SETCURFIELD_ARRAY
OP_SETCURFIELD_TYPE
OP_LOADFIELD_UINT
OP_LOADFIELD_FLT
OP_LOADFIELD_STR
OP_SAVEFIELD_UINT
OP_SAVEFIELD_FLT
OP_SAVEFIELD_STR
OP_STR_TO_UINT
OP_STR_TO_FLT
OP_STR_TO_NONE
OP_FLT_TO_UINT
OP_FLT_TO_STR
OP_FLT_TO_NONE
OP_UINT_TO_FLT
OP_UINT_TO_STR
OP_UINT_TO_NONE
OP_COPYVAR_TO_NONE
OP_LOADIMMED_UINT
OP_LOADIMMED_FLT
OP_TAG_TO_STR
OP_LOADIMMED_STR
OP_DOCBLOCK_STR
OP_LOADIMMED_IDENT
OP_CALLFUNC_RESOLVE
OP_CALLFUNC
OP_ADVANCE_STR
OP_ADVANCE_STR_APPENDCHAR
OP_ADVANCE_STR_COMMA
OP_ADVANCE_STR_NUL
OP_REWIND_STR
OP_TERMINATE_REWIND_STR
OP_COMPARE_STR
OP_PUSH
OP_PUSH_UINT
OP_PUSH_FLT
OP_PUSH_VAR
OP_PUSH_FRAME
OP_ASSERT
OP_BREAK
OP_ITER_BEGIN
Prepare foreach iterator.
OP_ITER_BEGIN_STR
Prepare foreach$ iterator.
OP_ITER
Enter foreach loop.
OP_ITER_END
End foreach loop.
OP_INVALID
Function Documentation
bool Compiler::addConsoleParser (char * ext, fnGetCurrentFile gcf, fnGetCurrentLine gcl, fnParse p, fnRestart r, fnSetScanBuffer ssb, bool def = false)
Add a console parser to the list.
Parameters
ext Filename extension
gcf GetCurrentFile function
gcl GetCurrentLine function
p Parse function
r Restart function
ssb SetScanBuffer function
def true if this is the default parser (Note: set this only on the .cs parser!)
Returns
true for success, false for failure (out of memory)
See also
FreeConsoleParserList(), ConsoleParser
StringTableEntry Compiler::CodeToSTE (U32 * code, U32 ip) inline
References compileSTEtoCode(), consoleAlloc(), consoleAllocReset(), evalSTEtoCode(), getCurrentFloatTable(), getCurrentStringTable(), getFunctionFloatTable(), getFunctionStringTable(), getGlobalFloatTable(), getGlobalStringTable(), getIdentTable(), gSyntaxError, Compiler::CompilerIdentTable::Entry::ip, precompileIdent(), resetTables(), setCurrentFloatTable(), setCurrentStringTable(), and STEtoCode.
U32 Compiler::compileBlock (StmtNode * block, CodeStream & codeStream, U32 ip)
void Compiler::compileSTEtoCode (StringTableEntry ste, U32 ip, U32 * ptr)
Referenced by CodeToSTE().
void* Compiler::consoleAlloc (U32 size)
Referenced by CodeToSTE().
void Compiler::consoleAllocReset ()
Referenced by CodeToSTE().
F64 Compiler::consoleStringToNumber (const char * str, StringTableEntry file = 0, U32 line = 0)
void Compiler::evalSTEtoCode (StringTableEntry ste, U32 ip, U32 * ptr)
Referenced by CodeToSTE().
void Compiler::freeConsoleParserList (void)
Free the console parser list.
See also
AddConsoleParser()
CompilerFloatTable* Compiler::getCurrentFloatTable ()
Referenced by CodeToSTE().
CompilerStringTable* Compiler::getCurrentStringTable ()
Referenced by CodeToSTE().
CompilerFloatTable& Compiler::getFunctionFloatTable ()
Referenced by CodeToSTE().
CompilerStringTable& Compiler::getFunctionStringTable ()
Referenced by CodeToSTE().
CompilerFloatTable& Compiler::getGlobalFloatTable ()
Referenced by CodeToSTE().
CompilerStringTable& Compiler::getGlobalStringTable ()
Referenced by CodeToSTE().
CompilerIdentTable& Compiler::getIdentTable ()
Referenced by CodeToSTE().
ConsoleParser* Compiler::getParserForFile (const char * filename)
Get the parser for a particular file based on its extension.
Parameters
filename Filename of file to obtain parser for
See also
ConsoleParser
void Compiler::precompileIdent (StringTableEntry ident)
Referenced by CodeToSTE().
void Compiler::resetTables ()
Helper function to reset the float, string, and ident tables to a base starting state.
Referenced by CodeToSTE().
void Compiler::setCurrentFloatTable (CompilerFloatTable * cst)
Referenced by CodeToSTE().
void Compiler::setCurrentStringTable (CompilerStringTable * cst)
Referenced by CodeToSTE().
Variable Documentation
bool Compiler::gSyntaxError
Referenced by CodeToSTE().
void(* Compiler::STEtoCode) (StringTableEntry ste, U32 ip, U32 *ptr)
Referenced by CodeToSTE(), and CodeStream::emitSTE().
Copyright © GarageGames, LLC. All Rights Reserved.