DictHash Namespace Reference
Main Modules Class List Namespace List Online
DictHash Namespace Reference
Functions
U32 hash (const GFXSamplerStateDesc &data)
U32 hash (U32 data)
U32 hash (const StringCase &data)
U32 hash (const StringNoCase &data)
U32 hash (const String &data)
U32 hash (const Torque::UUID &uuid)
U32 hash (const char *data)
U32 hash (const void *data)
template<class A , class B >
U32 hash (const CompoundKey< A, B > &compound)
template<class A , class B , class C >
U32 hash (const CompoundKey3< A, B, C > &compound)
U32 hash (const Point2I &key)
Generates a 32bit hash from a Point2I.
U32 nextPrime (U32)
Function Documentation
U32 DictHash::hash (const GFXSamplerStateDesc & data)
U32 DictHash::hash (U32 data) inline
Referenced by HashTable< Key, Value >::~HashTable().
U32 DictHash::hash (const StringCase & data) inline
References String::getHashCaseSensitive().
U32 DictHash::hash (const StringNoCase & data) inline
References String::getHashCaseInsensitive().
U32 DictHash::hash (const String & data) inline
References String::getHashCaseInsensitive().
U32 DictHash::hash (const Torque::UUID & uuid) inline
References Torque::UUID::getHash().
U32 DictHash::hash (const char * data) inline
References Torque::hash().
U32 DictHash::hash (const void * data) inline
template<class A , class B > U32 DictHash::hash (const CompoundKey< A, B > & compound) inline
References CompoundKey< A, B >::key1, and CompoundKey< A, B >::key2.
template<class A , class B , class C > U32 DictHash::hash (const CompoundKey3< A, B, C > & compound) inline
References CompoundKey3< A, B, C >::key1, CompoundKey3< A, B, C >::key2, CompoundKey3< A, B, C >::key3, and nextPrime().
U32 DictHash::hash (const Point2I & key) inline
Generates a 32bit hash from a Point2I.
See also
DictHash
References Point2I::x, and Point2I::y.
U32 DictHash::nextPrime (U32)
Referenced by hash(), and HashTable< Key, Value >::~HashTable().
Copyright © GarageGames, LLC. All Rights Reserved.