TSShapeConstructor::ChangeSet Struct Reference
Main Modules Class List Namespace List Online
TSShapeConstructor::ChangeSet Struct Reference
#include <ts/tsShapeConstruct.h>
Classes
struct Command
Public Types
enum eCommandType {
CmdAddNode,
CmdRemoveNode,
CmdRenameNode,
CmdSetNodeTransform,
CmdSetNodeParent,
CmdAddMesh,
CmdAddPrimitive,
CmdRemoveMesh,
CmdSetMeshSize,
CmdSetMeshType,
CmdSetMeshMaterial,
CmdRemoveObject,
CmdRenameObject,
CmdSetObjectNode,
CmdSetBounds,
CmdRenameDetailLevel,
CmdRemoveDetailLevel,
CmdSetDetailLevelSize,
CmdAddImposter,
CmdRemoveImposter,
CmdAddCollisionDetail,
CmdAddSequence,
CmdRemoveSequence,
CmdRenameSequence,
CmdSetSequenceCyclic,
CmdSetSequenceBlend,
CmdSetSequencePriority,
CmdSetSequenceGroundSpeed,
CmdAddTrigger,
CmdRemoveTrigger,
CmdInvalid
}
Public Member Functions
void add (Command &cmd)
bool addCmd_addImposter (const Command &newCmd)
bool addCmd_addSequence (Command &newCmd)
bool addCmd_addTrigger (const Command &newCmd)
bool addCmd_removeDetailLevel (const Command &newCmd)
bool addCmd_removeImposter (const Command &newCmd)
bool addCmd_removeMesh (const Command &newCmd)
bool addCmd_removeNode (const Command &newCmd)
bool addCmd_removeObject (const Command &newCmd)
bool addCmd_removeSequence (const Command &newCmd)
bool addCmd_removeTrigger (const Command &newCmd)
bool addCmd_renameDetailLevel (const Command &newCmd)
bool addCmd_renameNode (const Command &newCmd)
bool addCmd_renameObject (const Command &newCmd)
bool addCmd_renameSequence (const Command &newCmd)
bool addCmd_setBounds (const Command &newCmd)
bool addCmd_setDetailSize (const Command &newCmd)
bool addCmd_setMeshMaterial (const Command &newCmd)
bool addCmd_setMeshSize (const Command &newCmd)
bool addCmd_setMeshType (const Command &newCmd)
bool addCmd_setNodeParent (const Command &newCmd)
bool addCmd_setNodeTransform (const Command &newCmd)
bool addCmd_setObjectNode (const Command &newCmd)
bool addCmd_setSequenceBlend (const Command &newCmd)
bool addCmd_setSequenceCyclic (const Command &newCmd)
bool addCmd_setSequenceGroundSpeed (const Command &newCmd)
bool addCmd_setSequencePriority (const Command &newCmd)
void clear ()
bool empty ()
eCommandType getCmdType (const char *name)
void write (TSShape *shape, Stream &stream, const String &savePath)
Public Attributes
Vector< Command > mCommands
Member Enumeration Documentation
enum TSShapeConstructor::ChangeSet::eCommandType
Enumerator
CmdAddNode
CmdRemoveNode
CmdRenameNode
CmdSetNodeTransform
CmdSetNodeParent
CmdAddMesh
CmdAddPrimitive
CmdRemoveMesh
CmdSetMeshSize
CmdSetMeshType
CmdSetMeshMaterial
CmdRemoveObject
CmdRenameObject
CmdSetObjectNode
CmdSetBounds
CmdRenameDetailLevel
CmdRemoveDetailLevel
CmdSetDetailLevelSize
CmdAddImposter
CmdRemoveImposter
CmdAddCollisionDetail
CmdAddSequence
CmdRemoveSequence
CmdRenameSequence
CmdSetSequenceCyclic
CmdSetSequenceBlend
CmdSetSequencePriority
CmdSetSequenceGroundSpeed
CmdAddTrigger
CmdRemoveTrigger
CmdInvalid
Member Function Documentation
void TSShapeConstructor::ChangeSet::add (Command & cmd)
Referenced by empty().
bool TSShapeConstructor::ChangeSet::addCmd_addImposter (const Command & newCmd)
Referenced by empty().
bool TSShapeConstructor::ChangeSet::addCmd_addSequence (Command & newCmd)
Referenced by empty().
bool TSShapeConstructor::ChangeSet::addCmd_addTrigger (const Command & newCmd)
Referenced by empty().
bool TSShapeConstructor::ChangeSet::addCmd_removeDetailLevel (const Command & newCmd)
Referenced by empty().
bool TSShapeConstructor::ChangeSet::addCmd_removeImposter (const Command & newCmd)
Referenced by empty().
bool TSShapeConstructor::ChangeSet::addCmd_removeMesh (const Command & newCmd)
Referenced by empty().
bool TSShapeConstructor::ChangeSet::addCmd_removeNode (const Command & newCmd)
Referenced by empty().
bool TSShapeConstructor::ChangeSet::addCmd_removeObject (const Command & newCmd)
Referenced by empty().
bool TSShapeConstructor::ChangeSet::addCmd_removeSequence (const Command & newCmd)
Referenced by empty().
bool TSShapeConstructor::ChangeSet::addCmd_removeTrigger (const Command & newCmd)
Referenced by empty().
bool TSShapeConstructor::ChangeSet::addCmd_renameDetailLevel (const Command & newCmd)
Referenced by empty().
bool TSShapeConstructor::ChangeSet::addCmd_renameNode (const Command & newCmd)
Referenced by empty().
bool TSShapeConstructor::ChangeSet::addCmd_renameObject (const Command & newCmd)
Referenced by empty().
bool TSShapeConstructor::ChangeSet::addCmd_renameSequence (const Command & newCmd)
Referenced by empty().
bool TSShapeConstructor::ChangeSet::addCmd_setBounds (const Command & newCmd)
Referenced by empty().
bool TSShapeConstructor::ChangeSet::addCmd_setDetailSize (const Command & newCmd)
Referenced by empty().
bool TSShapeConstructor::ChangeSet::addCmd_setMeshMaterial (const Command & newCmd)
Referenced by empty().
bool TSShapeConstructor::ChangeSet::addCmd_setMeshSize (const Command & newCmd)
Referenced by empty().
bool TSShapeConstructor::ChangeSet::addCmd_setMeshType (const Command & newCmd)
Referenced by empty().
bool TSShapeConstructor::ChangeSet::addCmd_setNodeParent (const Command & newCmd)
Referenced by empty().
bool TSShapeConstructor::ChangeSet::addCmd_setNodeTransform (const Command & newCmd)
Referenced by empty().
bool TSShapeConstructor::ChangeSet::addCmd_setObjectNode (const Command & newCmd)
Referenced by empty().
bool TSShapeConstructor::ChangeSet::addCmd_setSequenceBlend (const Command & newCmd)
Referenced by empty().
bool TSShapeConstructor::ChangeSet::addCmd_setSequenceCyclic (const Command & newCmd)
Referenced by empty().
bool TSShapeConstructor::ChangeSet::addCmd_setSequenceGroundSpeed (const Command & newCmd)
Referenced by empty().
bool TSShapeConstructor::ChangeSet::addCmd_setSequencePriority (const Command & newCmd)
Referenced by empty().
void TSShapeConstructor::ChangeSet::clear (void) inline
References Vector< T >::clear().
bool TSShapeConstructor::ChangeSet::empty () inline
References add(), addCmd_addImposter(), addCmd_addSequence(), addCmd_addTrigger(), addCmd_removeDetailLevel(), addCmd_removeImposter(), addCmd_removeMesh(), addCmd_removeNode(), addCmd_removeObject(), addCmd_removeSequence(), addCmd_removeTrigger(), addCmd_renameDetailLevel(), addCmd_renameNode(), addCmd_renameObject(), addCmd_renameSequence(), addCmd_setBounds(), addCmd_setDetailSize(), addCmd_setMeshMaterial(), addCmd_setMeshSize(), addCmd_setMeshType(), addCmd_setNodeParent(), addCmd_setNodeTransform(), addCmd_setObjectNode(), addCmd_setSequenceBlend(), addCmd_setSequenceCyclic(), addCmd_setSequenceGroundSpeed(), addCmd_setSequencePriority(), Vector< T >::empty(), and write().
eCommandType TSShapeConstructor::ChangeSet::getCmdType (const char * name)
void TSShapeConstructor::ChangeSet::write (TSShape * shape, Stream & stream, const String & savePath)
Referenced by empty().
Member Data Documentation
Vector<Command> TSShapeConstructor::ChangeSet::mCommands
Copyright © GarageGames, LLC. All Rights Reserved.