GBitmap::Registration Struct Reference
Main Modules Class List Namespace List Online
GBitmap::Registration Struct Reference
#include <gfx/bitmap/gBitmap.h>
Public Types
typedef bool(* ReadFunc) (Stream &stream, GBitmap *bitmap)
The read function prototype.
typedef bool(* WriteFunc) (GBitmap *bitmap, Stream &stream, U32 compressionLevel)
The write function prototype. Compression levels are image-specific - see their registration declaration for details.
Public Member Functions
Registration ()
Public Attributes
U32 defaultCompression
the default compression level [levels are image-specific - see their registration declaration for details]
Vector< String > extensions
the list of file extensions for this bitmap type [these should be lower case]
U32 priority
Used to sort the registrations so that lookups occur in a fixed order.
ReadFunc readFunc
the read function to call for this bitmap type
WriteFunc writeFunc
the write function to call for this bitmap type
Member Typedef Documentation
typedef bool(* GBitmap::Registration::ReadFunc) (Stream &stream, GBitmap *bitmap)
The read function prototype.
typedef bool(* GBitmap::Registration::WriteFunc) (GBitmap *bitmap, Stream &stream, U32 compressionLevel)
The write function prototype. Compression levels are image-specific - see their registration declaration for details.
Constructor & Destructor Documentation
GBitmap::Registration::Registration () inline
References GBitmap::_load(), GBitmap::_search(), GBitmap::allocateBitmap(), GBitmap::extrudeMipLevels(), GBitmap::extrudeMipLevelsDetail(), GBitmap::GBitmap(), GBitmap::load(), GBitmap::sFindFile(), GBitmap::sFindFiles(), GBitmap::sFindRegInfo(), GBitmap::sGetExtensionList(), GBitmap::sRegisterFormat(), and GBitmap::~GBitmap().
Member Data Documentation
U32 GBitmap::Registration::defaultCompression
the default compression level [levels are image-specific - see their registration declaration for details]
Vector<String> GBitmap::Registration::extensions
the list of file extensions for this bitmap type [these should be lower case]
U32 GBitmap::Registration::priority
Used to sort the registrations so that lookups occur in a fixed order.
ReadFunc GBitmap::Registration::readFunc
the read function to call for this bitmap type
WriteFunc GBitmap::Registration::writeFunc
the write function to call for this bitmap type
Copyright © GarageGames, LLC. All Rights Reserved.