GuiGameListOptionsCtrl::Row Struct Reference
Main Modules Class List Namespace List Online
GuiGameListOptionsCtrl::Row Struct Reference
An extension to the parent's row, adding the ability to keep a collection of options and track status related to them.
#include <gui/controls/guiGameListOptionsCtrl.h>
Public Member Functions
Row ()
Public Attributes
Vector< StringTableEntry > mOptions
Collection of options available to display.
S32 mSelectedOption
Index into mOptions pointing at the selected option.
bool mWrapOptions
Determines if options should "wrap around" at the ends.
Detailed Description
An extension to the parent's row, adding the ability to keep a collection of options and track status related to them.
Constructor & Destructor Documentation
GuiGameListOptionsCtrl::Row::Row () inline
References GuiGameListOptionsCtrl::addRow(), GuiGameListOptionsCtrl::getCurrentOption(), GuiGameListOptionsCtrl::onKeyDown(), GuiGameListOptionsCtrl::onMouseUp(), GuiGameListOptionsCtrl::onRender(), GuiGameListOptionsCtrl::selectOption(), and GuiGameListOptionsCtrl::setOptions().
Member Data Documentation
Vector<StringTableEntry> GuiGameListOptionsCtrl::Row::mOptions
Collection of options available to display.
S32 GuiGameListOptionsCtrl::Row::mSelectedOption
Index into mOptions pointing at the selected option.
bool GuiGameListOptionsCtrl::Row::mWrapOptions
Determines if options should "wrap around" at the ends.
Copyright © GarageGames, LLC. All Rights Reserved.