PolyhedronUnmanagedVectorData Struct Reference
Main Modules Class List Namespace List Online
PolyhedronUnmanagedVectorData Struct Reference
Polyhedron data stored as raw points with memory being managed externally.
#include <math/mPolyhedron.h>
Public Types
typedef UnmanagedVector< Edge > EdgeListType
typedef UnmanagedVector< PlaneF > PlaneListType
typedef UnmanagedVector< Point3F > PointListType
Public Types inherited from PolyhedronData
typedef Edge EdgeType
typedef PlaneF PlaneType
typedef Point3F PointType
Public Member Functions
Accessors
U32 getNumPlanes () const
Return the number of planes that make up this polyhedron.
const PlaneF * getPlanes () const
Return the planes that make up the polyhedron.
PlaneF * getPlanes ()
U32 getNumPoints () const
Return the number of points that this polyhedron has.
const Point3F * getPoints () const
Point3F * getPoints ()
U32 getNumEdges () const
Return the number of edges that this polyhedron has.
const Edge * getEdges () const
Edge * getEdges ()
Protected Attributes
EdgeListType edgeList
List of edges.
PlaneListType planeList
List of planes. Note that by default, the normals facing inwards.
PointListType pointList
List of vertices.
Additional Inherited Members
Static Public Member Functions inherited from PolyhedronData
template<typename Polyhedron >
static void buildBoxData (Polyhedron &poly, const MatrixF &mat, const Box3F &box, bool invertNormals=false)
Detailed Description
Polyhedron data stored as raw points with memory being managed externally.
Member Typedef Documentation
typedef UnmanagedVector< Edge > PolyhedronUnmanagedVectorData::EdgeListType
typedef UnmanagedVector< PlaneF > PolyhedronUnmanagedVectorData::PlaneListType
typedef UnmanagedVector< Point3F > PolyhedronUnmanagedVectorData::PointListType
Member Function Documentation
const Edge* PolyhedronUnmanagedVectorData::getEdges () const inline
References UnmanagedVector< T >::address().
Edge* PolyhedronUnmanagedVectorData::getEdges () inline
References UnmanagedVector< T >::address().
U32 PolyhedronUnmanagedVectorData::getNumEdges () const inline
Return the number of edges that this polyhedron has.
References UnmanagedVector< T >::size().
U32 PolyhedronUnmanagedVectorData::getNumPlanes () const inline
Return the number of planes that make up this polyhedron.
References UnmanagedVector< T >::size().
U32 PolyhedronUnmanagedVectorData::getNumPoints () const inline
Return the number of points that this polyhedron has.
References UnmanagedVector< T >::size().
const PlaneF* PolyhedronUnmanagedVectorData::getPlanes () const inline
Return the planes that make up the polyhedron.
Note
The normals of these planes are facing inwards.
References UnmanagedVector< T >::address().
PlaneF* PolyhedronUnmanagedVectorData::getPlanes () inline
References UnmanagedVector< T >::address().
const Point3F* PolyhedronUnmanagedVectorData::getPoints () const inline
References UnmanagedVector< T >::address().
Point3F* PolyhedronUnmanagedVectorData::getPoints () inline
References UnmanagedVector< T >::address().
Member Data Documentation
EdgeListType PolyhedronUnmanagedVectorData::edgeList protected
List of edges.
PlaneListType PolyhedronUnmanagedVectorData::planeList protected
List of planes. Note that by default, the normals facing inwards.
PointListType PolyhedronUnmanagedVectorData::pointList protected
List of vertices.
Copyright © GarageGames, LLC. All Rights Reserved.