Player::Death Struct Reference
Main Modules Class List Namespace List Online
Player::Death Struct Reference
#include <T3D/player.h>
Public Member Functions
Death ()
void clear ()
MatrixF * fallToGround (F32 adjust, const Point3F &pos, F32 zrot, F32 boxRad)
VectorF getPosAdd ()
bool haveVelocity ()
void initFall ()
Public Attributes
VectorF curNormal
F32 curSink
F32 lastPos
Point3F posAdd
VectorF rotate
Constructor & Destructor Documentation
Player::Death::Death () inline
Member Function Documentation
void Player::Death::clear (void) inline
References dMemset().
MatrixF* Player::Death::fallToGround (F32 adjust, const Point3F & pos, F32 zrot, F32 boxRad)
VectorF Player::Death::getPosAdd () inline
References Point3F::set().
bool Player::Death::haveVelocity () inline
References Point3F::x, and Point3F::y.
void Player::Death::initFall () inline
References Point3F::set().
Member Data Documentation
VectorF Player::Death::curNormal
F32 Player::Death::curSink
F32 Player::Death::lastPos
Point3F Player::Death::posAdd
VectorF Player::Death::rotate
Copyright © GarageGames, LLC. All Rights Reserved.