SceneCameraState Class Reference
Main Modules Class List Namespace List Online
SceneCameraState Class Reference
An object that combines all the state that is relevant to looking into the scene from a particular point of view.
#include <scene/sceneCameraState.h>
Public Member Functions
SceneCameraState (const RectI &viewport, const Frustum &frustum, const MatrixF &worldView, const MatrixF &projection)
Freeze the given viewing state.
const Frustum & getFrustum () const
Return the camera frustum.
const MatrixF & getHeadWorldViewMatrix () const
Returns the world->view transform for the head (used to calculate various display metrics)
const MatrixF & getProjectionMatrix () const
Return the projection transform.
const Point3F & getViewDirection () const
Return the world-space view vector.
const RectI & getViewport () const
Return the screen-space viewport rectangle.
const Point3F & getViewPosition () const
Return the view position. This is a shortcut for getFrustum().getPosition().
const MatrixF & getViewWorldMatrix () const
Return the view->world transform. This is a shortcut for getFrustum().getTransform().
const MatrixF & getWorldViewMatrix () const
Return the world->view transform.
Static Public Member Functions
static SceneCameraState fromGFX ()
Capture the view state from the current GFX state.
static SceneCameraState fromGFXWithViewport (const RectI &viewport)
Protected Member Functions
SceneCameraState ()
Internal constructor.
Protected Attributes
Frustum mFrustum
The viewing frustum.
MatrixF mHeadWorldViewMatrix
Actual head position (will be - eye pos)
MatrixF mProjectionMatrix
The projection matrix.
Point3F mViewDirection
World-space vector representing the view direction.
RectI mViewport
The screen-space viewport rectangle.
MatrixF mWorldViewMatrix
The inverse of the frustum's transform stored here for caching.
Detailed Description
An object that combines all the state that is relevant to looking into the scene from a particular point of view.
Constructor & Destructor Documentation
SceneCameraState::SceneCameraState () inline protected
Internal constructor.
References fromGFX(), and fromGFXWithViewport().
SceneCameraState::SceneCameraState (const RectI & viewport, const Frustum & frustum, const MatrixF & worldView, const MatrixF & projection)
Freeze the given viewing state.
Parameters
viewport Screen-space viewport rectangle.
frustum Camera frustum.
worldView World->view matrix.
projection Projection matrix.
Member Function Documentation
static SceneCameraState SceneCameraState::fromGFX () static
Capture the view state from the current GFX state.
Referenced by SceneCameraState().
static SceneCameraState SceneCameraState::fromGFXWithViewport (const RectI & viewport) static
Referenced by SceneCameraState().
const Frustum& SceneCameraState::getFrustum () const inline
Return the camera frustum.
References mFrustum.
Referenced by SceneCullingState::getCameraFrustum().
const MatrixF& SceneCameraState::getHeadWorldViewMatrix () const inline
Returns the world->view transform for the head (used to calculate various display metrics)
References mHeadWorldViewMatrix.
const MatrixF& SceneCameraState::getProjectionMatrix () const inline
Return the projection transform.
References mProjectionMatrix.
const Point3F& SceneCameraState::getViewDirection () const inline
Return the world-space view vector.
References mViewDirection.
const RectI& SceneCameraState::getViewport () const inline
Return the screen-space viewport rectangle.
References mViewport.
Referenced by SceneRenderState::getViewport().
const Point3F& SceneCameraState::getViewPosition () const inline
Return the view position. This is a shortcut for getFrustum().getPosition().
References Frustum::getPosition().
Referenced by SceneRenderState::getCameraPosition().
const MatrixF& SceneCameraState::getViewWorldMatrix () const inline
Return the view->world transform. This is a shortcut for getFrustum().getTransform().
References Frustum::getTransform().
Referenced by SceneRenderState::getCameraTransform().
const MatrixF& SceneCameraState::getWorldViewMatrix () const inline
Return the world->view transform.
References mWorldViewMatrix.
Member Data Documentation
Frustum SceneCameraState::mFrustum protected
The viewing frustum.
Referenced by getFrustum().
MatrixF SceneCameraState::mHeadWorldViewMatrix protected
Actual head position (will be - eye pos)
Referenced by getHeadWorldViewMatrix().
MatrixF SceneCameraState::mProjectionMatrix protected
The projection matrix.
Referenced by getProjectionMatrix().
Point3F SceneCameraState::mViewDirection protected
World-space vector representing the view direction.
Referenced by getViewDirection().
RectI SceneCameraState::mViewport protected
The screen-space viewport rectangle.
Referenced by getViewport().
MatrixF SceneCameraState::mWorldViewMatrix protected
The inverse of the frustum's transform stored here for caching.
Referenced by getWorldViewMatrix().
Copyright © GarageGames, LLC. All Rights Reserved.