ScenePolyhedralObject< Base, P > Class Template Reference
Main Modules Class List Namespace List Online
ScenePolyhedralObject< Base, P > Class Template Reference
Helper template for mixing a polyhedral volume definition into the superclass hierarchy of a SceneSpace-derived class.
#include <scene/mixin/scenePolyhedralObject.h>
Public Types
enum {
MAX_PLANES = 256,
MAX_POINTS = 256,
MAX_EDGES = 256
}
typedef Base Parent
typedef P PolyhedronType
Public Member Functions
ScenePolyhedralObject ()
ScenePolyhedralObject (const PolyhedronType &polyhedron)
virtual bool containsPoint (const Point3F &point)
const PolyhedronType & getPolyhedron () const
Return the polyhedron that describes the space.
virtual bool onAdd ()
virtual U32 packUpdate (NetConnection *connection, U32 mask, BitStream *stream)
virtual AnyPolyhedron ToAnyPolyhedron () const
Convert the polyhedral object to a raw polyhedron.
virtual void unpackUpdate (NetConnection *connection, BitStream *stream)
virtual bool writeField (StringTableEntry name, const char *value)
virtual void writeFields (Stream &stream, U32 tabStop)
Static Public Member Functions
static void initPersistFields ()
Protected Types
enum {
PolyMask = Parent::NextFreeMask << 0,
NextFreeMask = Parent::NextFreeMask << 1
}
Protected Member Functions
virtual void _renderObject (ObjectRenderInst *ri, SceneRenderState *state, BaseMatInstance *overrideMat)
Protected Attributes
bool mIsBox
Whether the polyhedron corresponds to the object box.
PolyhedronType mPolyhedron
The polyhedron that defines the volume of the object.
Detailed Description
template<typename Base, typename P = Polyhedron>
class ScenePolyhedralObject< Base, P >
Helper template for mixing a polyhedral volume definition into the superclass hierarchy of a SceneSpace-derived class.
Member Typedef Documentation
template<typename Base, typename P = Polyhedron> typedef Base ScenePolyhedralObject< Base, P >::Parent
template<typename Base, typename P = Polyhedron> typedef P ScenePolyhedralObject< Base, P >::PolyhedronType
Member Enumeration Documentation
template<typename Base, typename P = Polyhedron> anonymous enum
Enumerator
MAX_PLANES
MAX_POINTS
MAX_EDGES
template<typename Base, typename P = Polyhedron> anonymous enum protected
Enumerator
PolyMask
NextFreeMask
Constructor & Destructor Documentation
template<typename Base, typename P = Polyhedron> ScenePolyhedralObject< Base, P >::ScenePolyhedralObject () inline
template<typename Base, typename P = Polyhedron> ScenePolyhedralObject< Base, P >::ScenePolyhedralObject (const PolyhedronType & polyhedron) inline
Member Function Documentation
template<typename Base , typename P > void ScenePolyhedralObject< Base, P >::_renderObject (ObjectRenderInst * ri, SceneRenderState * state, BaseMatInstance * overrideMat) protected virtual
Reimplemented in Portal, AccumulationVolume, and OcclusionVolume.
References DebugDrawer::drawPolyhedronDebugInfo(), DebugDrawer::get(), SceneRenderState::isDiffusePass(), MatrixF::scale(), GFXStateBlockDesc::setBlend(), GFXStateBlockDesc::setCullMode(), GFXStateBlockDesc::setFillModeWireframe(), and GFXStateBlockDesc::setZReadWrite().
template<typename Base , typename P > bool ScenePolyhedralObject< Base, P >::containsPoint (const Point3F & point) virtual
References Point3F::convolveInverse().
template<typename Base, typename P = Polyhedron> const PolyhedronType& ScenePolyhedralObject< Base, P >::getPolyhedron () const inline
Return the polyhedron that describes the space.
template<typename Base , typename P > void ScenePolyhedralObject< Base, P >::initPersistFields (void) static
References AbstractClassRep::FIELD_HideInInspectors.
template<typename Base , typename P > bool ScenePolyhedralObject< Base, P >::onAdd (void) virtual
Reimplemented in AccumulationVolume, ScenePolyhedralZone, and OcclusionVolume.
References MatrixF::Identity.
template<typename Base , typename P > U32 ScenePolyhedralObject< Base, P >::packUpdate (NetConnection * connection, U32 mask, BitStream * stream) virtual
Reimplemented in Portal, AccumulationVolume, SceneAmbientSoundObject< ScenePolyhedralObject< SceneSpace > >, and SceneAmbientSoundObject< ScenePolyhedralZone >.
References BitStream::writeFlag(), and BitStream::writeInt().
template<typename Base, typename P = Polyhedron> virtual AnyPolyhedron ScenePolyhedralObject< Base, P >::ToAnyPolyhedron () const inline virtual
Convert the polyhedral object to a raw polyhedron.
Implements IScenePolyhedralObject.
template<typename Base , typename P > void ScenePolyhedralObject< Base, P >::unpackUpdate (NetConnection * connection, BitStream * stream) virtual
Reimplemented in Portal, AccumulationVolume, SceneAmbientSoundObject< ScenePolyhedralObject< SceneSpace > >, and SceneAmbientSoundObject< ScenePolyhedralZone >.
References BitStream::readFlag(), and BitStream::readInt().
template<typename Base , typename P > bool ScenePolyhedralObject< Base, P >::writeField (StringTableEntry name, const char * value) virtual
Reimplemented in Portal.
template<typename Base , typename P > void ScenePolyhedralObject< Base, P >::writeFields (Stream & stream, U32 tabStop) virtual
References PlaneF::d, PolyhedronData::Edge::face, ScenePolyhedralObject< Base, P >::mIsBox, ScenePolyhedralObject< Base, P >::mPolyhedron, PolyhedronData::Edge::vertex, Stream::write(), Stream::writeLine(), Stream::writeTabs(), Point3F::x, Point3F::y, and Point3F::z.
Member Data Documentation
template<typename Base, typename P = Polyhedron> bool ScenePolyhedralObject< Base, P >::mIsBox protected
Whether the polyhedron corresponds to the object box.
If so, several things can be fast-tracked. For example, serializing the polyhedron is pointless as it can be easily reconstructed from the object box on load time. Also, certain operations like containment tests have significantly faster formulations for AABBs (given that the input data is transformed into object space) than for general polyhedrons.
Referenced by ScenePolyhedralObject< Base, P >::writeFields().
template<typename Base, typename P = Polyhedron> PolyhedronType ScenePolyhedralObject< Base, P >::mPolyhedron protected
The polyhedron that defines the volume of the object.
Note
Defined in object space by default.
Referenced by ScenePolyhedralObject< Base, P >::writeFields().
Copyright © GarageGames, LLC. All Rights Reserved.