Zip::ExtraField Class Reference
Main Modules Class List Namespace List Online
Zip::ExtraField Class Reference abstract
Zip Code » Zip Code Internals
#include <core/util/zip/extraField.h>
Public Member Functions
ExtraField ()
ExtraField (U16 id, ExtraFieldCreateFn fnCreate)
virtual ~ExtraField ()
U16 getID ()
virtual bool read (Stream *stream)=0
Static Public Member Functions
static ExtraField * create (U16 id)
Protected Attributes
ExtraFieldCreateFn mCreateFn
U16 mID
Constructor & Destructor Documentation
Zip::ExtraField::ExtraField () inline
Zip::ExtraField::ExtraField (U16 id, ExtraFieldCreateFn fnCreate)
virtual Zip::ExtraField::~ExtraField () inline virtual
Member Function Documentation
static ExtraField* Zip::ExtraField::create (U16 id) static
Referenced by getID().
U16 Zip::ExtraField::getID () inline
References create(), mID, and read().
virtual bool Zip::ExtraField::read (Stream * stream) pure virtual
Referenced by getID().
Member Data Documentation
ExtraFieldCreateFn Zip::ExtraField::mCreateFn protected
U16 Zip::ExtraField::mID protected
Referenced by getID().
Copyright © GarageGames, LLC. All Rights Reserved.