SimObjectList Class Reference
Main Modules Class List Namespace List Online
SimObjectList Class Reference
A vector of SimObjects.
#include <console/simObjectList.h>
Public Member Functions
SimObject * at (S32 index) const
bool pushBack (SimObject *)
Add the SimObject* to the end of the list, unless it's already in the list.
bool pushBackForce (SimObject *)
Add the SimObject* to the end of the list, moving it there if it's already present in the list.
bool pushFront (SimObject *)
Add the SimObject* to the start of the list.
bool remove (SimObject *)
Remove the SimObject* from the list; may disrupt order of the list.
bool removeStable (SimObject *pObject)
Remove the SimObject* from the list; guaranteed to preserve list order.
void scriptSort (const String &scriptCallback)
Performs a sort of the objects in the set using a script callback function to do the comparision.
void sortId ()
Performs a simple sort by SimObjectId.
Public Member Functions inherited from VectorPtr< SimObject * >
VectorPtr ()
VectorPtr (const char *fileName, const U32 lineNum)
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
void insert (iterator, const SimObject * &)
void insert (S32 idx)
void erase (iterator)
SimObject * & front ()
const SimObject * & front () const
SimObject * & back ()
const SimObject * & back () const
void push_front (const SimObject * &)
void push_back (const SimObject * &)
SimObject * & operator[] (U32)
const SimObject * & operator[] (U32) const
SimObject * & first ()
const SimObject * & first () const
SimObject * & last ()
const SimObject * & last () const
void erase_fast (U32)
void erase_fast (iterator)
Additional Inherited Members
Public Types inherited from VectorPtr< SimObject * >
typedef SimObject * value_type
typedef SimObject * & reference
typedef const SimObject * & const_reference
typedef SimObject * * iterator
typedef const SimObject * * const_iterator
typedef U32 difference_type
typedef U32 size_type
typedef Vector< void * > Parent
Detailed Description
A vector of SimObjects.
As this inherits from VectorPtr, it has the full range of vector methods.
Member Function Documentation
SimObject* SimObjectList::at (S32 index) const inline
References removeStable(), scriptSort(), Vector< void * >::size(), and sortId().
Referenced by SimSet::at().
bool SimObjectList::pushBack (SimObject *)
Add the SimObject* to the end of the list, unless it's already in the list.
bool SimObjectList::pushBackForce (SimObject *)
Add the SimObject* to the end of the list, moving it there if it's already present in the list.
bool SimObjectList::pushFront (SimObject *)
Add the SimObject* to the start of the list.
bool SimObjectList::remove (SimObject *)
Remove the SimObject* from the list; may disrupt order of the list.
bool SimObjectList::removeStable (SimObject * pObject)
Remove the SimObject* from the list; guaranteed to preserve list order.
Referenced by at().
void SimObjectList::scriptSort (const String & scriptCallback)
Performs a sort of the objects in the set using a script callback function to do the comparision.
See also
SimSet::scriptSort
Referenced by at().
void SimObjectList::sortId ()
Performs a simple sort by SimObjectId.
Referenced by at().
Copyright © GarageGames, LLC. All Rights Reserved.