MRandomLCG Class Reference
Main Modules Class List Namespace List Online
MRandomLCG Class Reference
Linear Congruential Method, the "minimal standard generator".
#include <math/mRandom.h>
Public Member Functions
MRandomLCG ()
MRandomLCG (S32 s)
virtual ~MRandomLCG ()
S32 randI (S32 i, S32 n)
i..n integer generator
U32 randI (void)
0..2^31 random number generator
void setSeed (S32 s)
Public Member Functions inherited from MRandomGenerator
virtual ~MRandomGenerator ()
S32 getSeed ()
virtual F32 randF (void)
0.0 .. 1.0 F32 random number generator
F32 randF (F32 i, F32 n)
i..n F32 random number generator
S32 randI (S32 i, S32 n)
i..n integer random number generator
void setSeed ()
Static Public Member Functions
static void setGlobalRandSeed (U32 seed)
Static Protected Attributes
static const S32 msQuotient
static const S32 msRemainder
Additional Inherited Members
Protected Member Functions inherited from MRandomGenerator
MRandomGenerator ()
Protected Attributes inherited from MRandomGenerator
S32 mSeed
Detailed Description
Linear Congruential Method, the "minimal standard generator".
Fast, farly good random numbers (better than using rand)
Author
Park & Miller, 1988, Comm of the ACM, 31(10), pp. 1192-1201
Constructor & Destructor Documentation
MRandomLCG::MRandomLCG ()
MRandomLCG::MRandomLCG (S32 s)
virtual MRandomLCG::~MRandomLCG () inline virtual
References MRandomGenerator::randI(), and MRandomGenerator::setSeed().
Member Function Documentation
S32 MRandomLCG::randI (S32 i, S32 n) inline
i..n integer generator
References MRandomGenerator::randI().
Referenced by MRandomDeck< T >::shuffle().
U32 MRandomLCG::randI (void) virtual
0..2^31 random number generator
Implements MRandomGenerator.
static void MRandomLCG::setGlobalRandSeed (U32 seed) static
void MRandomLCG::setSeed (S32 s) virtual
Implements MRandomGenerator.
Member Data Documentation
const S32 MRandomLCG::msQuotient static protected
const S32 MRandomLCG::msRemainder static protected
Copyright © GarageGames, LLC. All Rights Reserved.