MatrixF Class Reference
Main Modules Class List Namespace List Online
MatrixF Class Reference
4x4 Matrix Class
#include <math/mMatrix.h>
Public Member Functions
MatrixF (bool identity=false)
Create an uninitialized matrix.
MatrixF (const EulerF &e)
Create a matrix to rotate about origin by e.
MatrixF (const EulerF &e, const Point3F &p)
Create a matrix to rotate about p by e.
MatrixF & add (const MatrixF &m)
MatrixF & affineInverse ()
Take inverse of matrix assuming it is affine (rotation, scale, sheer, translation only).
void displace (const Point3F &delta)
Add the passed delta to the matrix position.
void dumpMatrix (const char *caption=NULL) const
bool fullInverse ()
Compute the inverse of the matrix.
void getColumn (S32 col, Point4F *cptr) const
Copy the requested column into a Point4F.
void getColumn (S32 col, Point3F *cptr) const
Copy the requested column into a Point3F.
Point3F getColumn3F (S32 col) const
Point4F getColumn4F (S32 col) const
VectorF getForwardVector () const
Get the y axis of the matrix.
Point3F getPosition () const
Get the position of the matrix.
VectorF getRightVector () const
Get the x axis of the matrix.
void getRow (S32 row, Point4F *cptr) const
Copy the specified row into a Point4F.
void getRow (S32 row, Point3F *cptr) const
Copy the specified row into a Point3F.
Point3F getRow3F (S32 row) const
Point4F getRow4F (S32 row) const
Point3F getScale () const
Return scale assuming scale was applied via mat.scale(s).
VectorF getUpVector () const
Get the z axis of the matrix.
MatrixF & identity ()
Make this an identity matrix.
MatrixF & inverse ()
Invert m.
void invertTo (MatrixF *out)
Copy the inversion of this into out matrix.
bool isAffine () const
Check to see if this is an affine matrix.
bool isIdentity () const
Checks for identity matrix.
MatrixF & mul (const MatrixF &a)
M * a -> M.
MatrixF & mul (const MatrixF &a, const MatrixF &b)
a * b -> M
MatrixF & mul (const F32 a)
M * a -> M.
MatrixF & mul (const MatrixF &a, const F32 b)
a * b -> M
void mul (Point4F &p) const
M * p -> p (full [4x4] * [1x4])
void mul (Box3F &b) const
Axial box -> Axial Box.
MatrixF & mulL (const MatrixF &a)
a * M -> M
void mulP (Point3F &p) const
M * p -> p (assume w = 1.0f)
void mulP (const Point3F &p, Point3F *d) const
M * p -> d (assume w = 1.0f)
void mulV (VectorF &p) const
M * v -> v (assume w = 0.0f)
void mulV (const VectorF &p, Point3F *d) const
M * v -> d (assume w = 0.0f)
void normalize ()
Normalize the matrix.
F32 & operator() (S32 row, S32 col)
Convenience function to allow people to treat this like an array.
F32 operator() (S32 row, S32 col) const
MatrixF & operator*= (const MatrixF &m)
MatrixF & scale (const Point3F &s)
M * Matrix(p) -> M.
MatrixF & scale (F32 s)
MatrixF & set (const EulerF &e)
Initialize matrix to rotate about origin by e.
MatrixF & set (const EulerF &e, const Point3F &p)
Initialize matrix to rotate about p by e.
void setColumn (S32 col, const Point4F &cptr)
Set the specified column from a Point4F.
void setColumn (S32 col, const Point3F &cptr)
Set the specified column from a Point3F.
MatrixF & setCrossProduct (const Point3F &p)
Initialize matrix with a cross product of p.
void setPosition (const Point3F &pos)
Set the position of the matrix.
void setRow (S32 row, const Point4F &cptr)
Set the specified row from a Point4F.
void setRow (S32 row, const Point3F &cptr)
Set the specified row from a Point3F.
MatrixF & setTensorProduct (const Point3F &p, const Point3F &q)
Initialize matrix with a tensor product of p.
EulerF toEuler () const
MatrixF & transpose ()
Swap rows and columns.
void transposeTo (F32 *matrix) const
Swaps rows and columns into matrix.
Static Public Member Functions
static U32 idx (U32 i, U32 j)
Get the index in m to element in column i, row j.
Static Public Attributes
static const MatrixF Identity
Friends
MatrixF operator* (const MatrixF &m1, const MatrixF &m2)
Detailed Description
4x4 Matrix Class
This runs at F32 precision.
Constructor & Destructor Documentation
MatrixF::MatrixF (bool identity = false) inline explicit
Create an uninitialized matrix.
Parameters
identity If true, initialize to the identity matrix.
References identity().
MatrixF::MatrixF (const EulerF & e) inline explicit
Create a matrix to rotate about origin by e.
See also
set
MatrixF::MatrixF (const EulerF & e, const Point3F & p) inline
Create a matrix to rotate about p by e.
See also
set
Member Function Documentation
MatrixF & MatrixF::add (const MatrixF & m) inline
Referenced by setPosition().
MatrixF & MatrixF::affineInverse () inline
Take inverse of matrix assuming it is affine (rotation, scale, sheer, translation only).
Referenced by idx().
void MatrixF::displace (const Point3F & delta) inline
Add the passed delta to the matrix position.
References Point3F::x, Point3F::y, and Point3F::z.
Referenced by setPosition().
void MatrixF::dumpMatrix (const char * caption = NULL) const
Referenced by operator()().
bool MatrixF::fullInverse ()
Compute the inverse of the matrix.
Computes inverse of full 4x4 matrix. Returns false and performs no inverse if the determinant is 0.
Note: In most cases you want to use the normal inverse function. This method should be used if the matrix has something other than (0,0,0,1) in the bottom row.
Referenced by scale().
void MatrixF::getColumn (S32 col, Point4F * cptr) const inline
Copy the requested column into a Point4F.
References Point4F::w, Point4F::x, Point4F::y, and Point4F::z.
Referenced by getColumn3F(), getColumn4F(), getForwardVector(), getRightVector(), getUpVector(), FModFNTable::Thunk< FN >::operator()(), and scale().
void MatrixF::getColumn (S32 col, Point3F * cptr) const inline
Copy the requested column into a Point3F.
This drops the bottom-most row.
References Point3F::x, Point3F::y, and Point3F::z.
Point3F MatrixF::getColumn3F (S32 col) const inline
References getColumn(), getRow(), and setColumn().
Point4F MatrixF::getColumn4F (S32 col) const inline
References getColumn().
VectorF MatrixF::getForwardVector () const inline
Get the y axis of the matrix.
This is the 2nd column of the matrix and is normally considered the forward vector.
References getColumn().
Referenced by PolyhedronData::buildBoxData(), LightInfo::getDirection(), and setPosition().
Point3F MatrixF::getPosition () const inline
Get the position of the matrix.
This is the 4th column of the matrix.
Referenced by SilhouetteExtractorBasePerspective< PolyhedronType >::begin(), SceneRenderState::getDiffuseCameraPosition(), LightInfo::getPosition(), ForestItem::getPosition(), and getRow3F().
VectorF MatrixF::getRightVector () const inline
Get the x axis of the matrix.
This is the 1st column of the matrix and is normally considered the right vector.
References getColumn().
Referenced by PolyhedronData::buildBoxData(), and setPosition().
void MatrixF::getRow (S32 row, Point4F * cptr) const inline
Copy the specified row into a Point4F.
References Point4F::w, Point4F::x, Point4F::y, and Point4F::z.
Referenced by getColumn3F(), getRow3F(), and getRow4F().
void MatrixF::getRow (S32 row, Point3F * cptr) const inline
Copy the specified row into a Point3F.
Right-most item is dropped.
References Point3F::x, Point3F::y, and Point3F::z.
Point3F MatrixF::getRow3F (S32 row) const inline
References getPosition(), getRow(), and setRow().
Point4F MatrixF::getRow4F (S32 row) const inline
References getRow().
Point3F MatrixF::getScale () const inline
Return scale assuming scale was applied via mat.scale(s).
References scale(), Point3F::x, Point3F::y, and Point3F::z.
Referenced by scale().
VectorF MatrixF::getUpVector () const inline
Get the z axis of the matrix.
This is the 3rd column of the matrix and is normally considered the up vector.
References getColumn().
Referenced by PolyhedronData::buildBoxData(), and setPosition().
MatrixF & MatrixF::identity () inline
Make this an identity matrix.
Referenced by Frustum::clearProjectionOffset(), AbstractPolyList::doConstruct(), ForestConvex::ForestConvex(), idx(), MatrixF(), and OrthoBoxConvex::OrthoBoxConvex().
static U32 MatrixF::idx (U32 i, U32 j) inline static
Get the index in m to element in column i, row j.
This is necessary as we have m as a one dimensional array.
Parameters
i Column desired.
j Row desired.
References affineInverse(), identity(), inverse(), invertTo(), isAffine(), isIdentity(), scale(), setCrossProduct(), setTensorProduct(), and transpose().
Referenced by operator()().
MatrixF & MatrixF::inverse () inline
Invert m.
Referenced by idx(), RotationF::operator-(), RotationF::operator-=(), and GFXDevice::setStereoEyeTransforms().
void MatrixF::invertTo (MatrixF * out) inline
Copy the inversion of this into out matrix.
Referenced by idx().
bool MatrixF::isAffine () const
Check to see if this is an affine matrix.
Referenced by idx().
bool MatrixF::isIdentity () const inline
Checks for identity matrix.
Referenced by idx().
MatrixF & MatrixF::mul (const MatrixF & a) inline
M * a -> M.
Referenced by OpenVRRenderModel::getWorldBox(), mul(), GFXDevice::multWorld(), RotationF::operator+(), RotationF::operator+=(), RotationF::operator-(), RotationF::operator-=(), setPosition(), and AbstractPolyList::setTransform().
MatrixF & MatrixF::mul (const MatrixF & a, const MatrixF & b) inline
a * b -> M
MatrixF & MatrixF::mul (const F32 a) inline
M * a -> M.
MatrixF & MatrixF::mul (const MatrixF & a, const F32 b) inline
a * b -> M
References mul().
void MatrixF::mul (Point4F & p) const inline
M * p -> p (full [4x4] * [1x4])
References Point4F::x.
void MatrixF::mul (Box3F & b) const inline
Axial box -> Axial Box.
References Box3F::maxExtents, Box3F::minExtents, and Point3F::x.
MatrixF & MatrixF::mulL (const MatrixF & a) inline
a * M -> M
Referenced by setPosition().
void MatrixF::mulP (Point3F & p) const inline
M * p -> p (assume w = 1.0f)
References Point3F::x.
Referenced by PolyhedronBoxIntersector< Polyhedron >::_preprocess(), PolyhedronData::buildBoxData(), setPosition(), and PolyhedronImpl< Base >::transform().
void MatrixF::mulP (const Point3F & p, Point3F * d) const inline
M * p -> d (assume w = 1.0f)
References Point3F::x.
void MatrixF::mulV (VectorF & p) const inline
M * v -> v (assume w = 0.0f)
References Point3F::x.
Referenced by setPosition().
void MatrixF::mulV (const VectorF & p, Point3F * d) const inline
M * v -> d (assume w = 0.0f)
References Point3F::x.
void MatrixF::normalize () inline
Normalize the matrix.
Referenced by scale().
F32& MatrixF::operator() (S32 row, S32 col) inline
Convenience function to allow people to treat this like an array.
References idx().
F32 MatrixF::operator() (S32 row, S32 col) const inline
References dumpMatrix(), idx(), operator*, and operator*=().
MatrixF & MatrixF::operator*= (const MatrixF & m) inline
References scale(), and Point3F::x.
Referenced by operator()().
MatrixF & MatrixF::scale (const Point3F & s) inline
M * Matrix(p) -> M.
Referenced by ScenePolyhedralObject< Base, P >::_renderObject(), getScale(), idx(), operator*=(), and ColladaUtils::ImportOptions::reset().
MatrixF& MatrixF::scale (F32 s) inline
References fullInverse(), getColumn(), getScale(), normalize(), scale(), toEuler(), and transposeTo().
Referenced by scale().
MatrixF & MatrixF::set (const EulerF & e) inline
Initialize matrix to rotate about origin by e.
MatrixF & MatrixF::set (const EulerF & e, const Point3F & p) inline
Initialize matrix to rotate about p by e.
void MatrixF::setColumn (S32 col, const Point4F & cptr) inline
Set the specified column from a Point4F.
References Point4F::w, Point4F::x, Point4F::y, and Point4F::z.
Referenced by getColumn3F(), ColladaUtils::ImportOptions::reset(), TSTransform::setMatrix(), and setPosition().
void MatrixF::setColumn (S32 col, const Point3F & cptr) inline
Set the specified column from a Point3F.
The bottom-most row is not set.
References Point3F::x, Point3F::y, and Point3F::z.
MatrixF & MatrixF::setCrossProduct (const Point3F & p) inline
Initialize matrix with a cross product of p.
References Point3F::x, Point3F::y, and Point3F::z.
Referenced by idx().
void MatrixF::setPosition (const Point3F & pos) inline
Set the position of the matrix.
This is the 4th column of the matrix.
References add(), displace(), getForwardVector(), getRightVector(), getUpVector(), mul(), mulL(), mulP(), mulV(), and setColumn().
Referenced by TransformF::getMatrix(), PhysicsState::getTransform(), ColladaUtils::ImportOptions::reset(), and LightInfo::setPosition().
void MatrixF::setRow (S32 row, const Point4F & cptr) inline
Set the specified row from a Point4F.
References Point4F::w, Point4F::x, Point4F::y, and Point4F::z.
Referenced by getRow3F().
void MatrixF::setRow (S32 row, const Point3F & cptr) inline
Set the specified row from a Point3F.
The right-most item is not set.
References Point3F::x, Point3F::y, and Point3F::z.
MatrixF & MatrixF::setTensorProduct (const Point3F & p, const Point3F & q) inline
Initialize matrix with a tensor product of p.
References Point3F::x, Point3F::y, and Point3F::z.
Referenced by idx().
EulerF MatrixF::toEuler () const
Referenced by scale().
MatrixF & MatrixF::transpose () inline
Swap rows and columns.
Referenced by idx().
void MatrixF::transposeTo (F32 * matrix) const
Swaps rows and columns into matrix.
Referenced by scale().
Friends And Related Function Documentation
MatrixF operator* (const MatrixF & m1, const MatrixF & m2) friend
Referenced by operator()().
Member Data Documentation
const MatrixF MatrixF::Identity static
Referenced by SceneObject::applyRadialImpulse(), TurretShape::doRespawn(), GameBase::getCameraTransform(), GameBase::getEyeCameraTransform(), LeapMotionFrame::getHandRot(), LeapMotionFrame::getPointableRot(), RazerHydraFrame::getRot(), Entity::getRotation(), TSShapeInstance::ObjectInstance::getTransform(), SceneData::init(), ScenePolyhedralObject< Base, P >::onAdd(), and SceneData::SceneData().
Copyright © GarageGames, LLC. All Rights Reserved.