ForestCell Class Reference
Main Modules Class List Namespace List Online
ForestCell Class Reference
#include <forest/forestCell.h>
Public Member Functions
ForestCell (const RectF &rect)
virtual ~ForestCell ()
void buildBatches ()
void buildPhysicsRep (Forest *forest)
bool castRay (const Point3F &start, const Point3F &end, RayInfo *outInfo, bool rendered) const
void clearPhysicsRep (Forest *forest)
bool findIndexByKey (ForestItemKey key, U32 *outIndex) const
The find function does a binary search thru the sorted item list.
void freeBatches ()
const Box3F & getBounds () const
The bounds of the cell generated by combining the bounds of all the contained items or child cells.
ForestCell * getChildAt (const Point3F &pos) const
Returns the child cell at the position.
void getChildren (Vector< ForestCell * > *outCells) const
Returns the child cells.
void getChildren (Vector< const ForestCell * > *outCells) const
const Vector< ForestItem > & getItems () const
Returns the items from this one cell.
void getItems (Vector< ForestItem > *outItems) const
Returns the items from this cell and all its sub-cells.
const ForestItem & getLargestItem () const
const RectF & getRect () const
Returns the 2D rectangle of quad tree bounds for this cell.
const BitVector & getZoneOverlap () const
Returns a bit vector of what zones overlap this cell.
bool hasBatches () const
const ForestItem & insertItem (ForestItemKey key, ForestItemData *data, const MatrixF &xfm, F32 scale)
void invalidateBounds ()
Set flag so this cells bounds will be recalculated the next call to getBounds.
bool isBranch () const
Returns true if this cell has child cells.
bool isEmpty () const
Returns true if this cell has no items and no child cells.
bool isLeaf () const
Returns true if this cell does not have child cells.
bool removeItem (ForestItemKey key, const Point3F &keyPos, bool deleteIfEmpty=false)
S32 render (TSRenderState *rdata, const Frustum *culler)
S32 renderBatches (SceneRenderState *state, Frustum *culler)
Static Public Attributes
static const U32 MaxItems = 200
The maximum amount of objects allowed in a cell before we repartition it.
Protected Member Functions
U32 _getSubCell (F32 x, F32 y) const
RectF _makeChildRect (U32 index) const
void _updateBounds ()
void _updateZoning (const SceneZoneSpaceManager *zoneManager)
Protected Attributes
Vector< ForestCellBatch * > mBatches
A vector of the current batches associated with this cell.
Box3F mBounds
The combined bounding box of all the items in or children of this cell.
bool mIsDirty
If items have been added or removed the dirty flag is set so that the bounds can be rebuilt on the next request.
bool mIsInteriorOnly
Whether this cell is fully contained inside interior zones.
Vector< ForestItem > mItems
All the items in this cell.
ForestItem mLargestItem
The largest item in this cell.
PhysicsBody * mPhysicsRep [2]
PhysicsBody for client and server for all trees in this ForestCell, if it is a leaf cell.
RectF mRect
The area which this cell represents in the world.
ForestCell * mSubCells [4]
The quad tree cells below this one which may contain sub elements.
BitVector mZoneOverlap
The zone overlap for this cell.
Constructor & Destructor Documentation
ForestCell::ForestCell (const RectF & rect)
virtual ForestCell::~ForestCell () virtual
Member Function Documentation
U32 ForestCell::_getSubCell (F32 x, F32 y) const inline protected
References RectF::extent, RectF::point, Point2F::x, and Point2F::y.
Referenced by getChildAt().
RectF ForestCell::_makeChildRect (U32 index) const inline protected
References _updateBounds(), _updateZoning(), RectF::extent, RectF::point, Point2F::x, and Point2F::y.
void ForestCell::_updateBounds () protected
Referenced by _makeChildRect(), and getBounds().
void ForestCell::_updateZoning (const SceneZoneSpaceManager * zoneManager) protected
Referenced by _makeChildRect().
void ForestCell::buildBatches ()
Referenced by hasBatches().
void ForestCell::buildPhysicsRep (Forest * forest)
Referenced by getItems().
bool ForestCell::castRay (const Point3F & start, const Point3F & end, RayInfo * outInfo, bool rendered) const
Referenced by getZoneOverlap().
void ForestCell::clearPhysicsRep (Forest * forest)
Referenced by getItems().
bool ForestCell::findIndexByKey (ForestItemKey key, U32 * outIndex) const
The find function does a binary search thru the sorted item list.
If the key is found then the index is the position of the item. If the key is not found the index is the correct insertion position for adding the new item.
Parameters
key The item key to search for.
outIndex The item index or insertion index if the item was not found.
Returns
Returns true if the item index is found.
Referenced by hasBatches().
void ForestCell::freeBatches ()
Referenced by hasBatches().
const Box3F & ForestCell::getBounds () const inline
The bounds of the cell generated by combining the bounds of all the contained items or child cells.
References _updateBounds(), mBounds, and mIsDirty.
Referenced by getRect().
ForestCell * ForestCell::getChildAt (const Point3F & pos) const inline
Returns the child cell at the position.
The position is assumed to be within this cell.
References _getSubCell(), mSubCells, Point3F::x, and Point3F::y.
Referenced by getLargestItem().
void ForestCell::getChildren (Vector< ForestCell * > * outCells) const inline
Returns the child cells.
References Vector< T >::merge().
void ForestCell::getChildren (Vector< const ForestCell * > * outCells) const inline
References Vector< T >::merge().
const Vector<ForestItem>& ForestCell::getItems () const inline
Returns the items from this one cell.
References buildPhysicsRep(), clearPhysicsRep(), and mItems.
void ForestCell::getItems (Vector< ForestItem > * outItems) const
Returns the items from this cell and all its sub-cells.
const ForestItem& ForestCell::getLargestItem () const inline
References getChildAt(), insertItem(), mLargestItem, and removeItem().
const RectF& ForestCell::getRect () const inline
Returns the 2D rectangle of quad tree bounds for this cell.
It is fixed and does not change during runtime.
References getBounds(), and mRect.
const BitVector& ForestCell::getZoneOverlap () const inline
Returns a bit vector of what zones overlap this cell.
References castRay(), SimSet::end(), and mZoneOverlap.
bool ForestCell::hasBatches () const inline
References buildBatches(), Vector< T >::empty(), findIndexByKey(), freeBatches(), render(), and renderBatches().
const ForestItem& ForestCell::insertItem (ForestItemKey key, ForestItemData * data, const MatrixF & xfm, F32 scale)
Referenced by getLargestItem().
void ForestCell::invalidateBounds () inline
Set flag so this cells bounds will be recalculated the next call to getBounds.
bool ForestCell::isBranch () const inline
Returns true if this cell has child cells.
This is the same as !isLeaf() but exists for clarity.
bool ForestCell::isEmpty () const inline
Returns true if this cell has no items and no child cells.
References Vector< T >::empty(), and isLeaf().
bool ForestCell::isLeaf () const inline
Returns true if this cell does not have child cells.
It should directly contain items.
Referenced by isEmpty().
bool ForestCell::removeItem (ForestItemKey key, const Point3F & keyPos, bool deleteIfEmpty = false)
Referenced by getLargestItem().
S32 ForestCell::render (TSRenderState * rdata, const Frustum * culler)
Referenced by hasBatches().
S32 ForestCell::renderBatches (SceneRenderState * state, Frustum * culler)
Referenced by hasBatches().
Member Data Documentation
const U32 ForestCell::MaxItems = 200 static
The maximum amount of objects allowed in a cell before we repartition it.
Vector<ForestCellBatch*> ForestCell::mBatches protected
A vector of the current batches associated with this cell.
Box3F ForestCell::mBounds protected
The combined bounding box of all the items in or children of this cell.
Referenced by getBounds().
bool ForestCell::mIsDirty protected
If items have been added or removed the dirty flag is set so that the bounds can be rebuilt on the next request.
Referenced by getBounds().
bool ForestCell::mIsInteriorOnly protected
Whether this cell is fully contained inside interior zones.
Vector<ForestItem> ForestCell::mItems protected
All the items in this cell.
Referenced by getItems().
ForestItem ForestCell::mLargestItem protected
The largest item in this cell.
Referenced by getLargestItem().
PhysicsBody* ForestCell::mPhysicsRep[2] protected
PhysicsBody for client and server for all trees in this ForestCell, if it is a leaf cell.
RectF ForestCell::mRect protected
The area which this cell represents in the world.
Referenced by getRect().
ForestCell* ForestCell::mSubCells[4] protected
The quad tree cells below this one which may contain sub elements.
Referenced by getChildAt().
BitVector ForestCell::mZoneOverlap protected
The zone overlap for this cell.
Note
The bit for the outdoor zone is never set.
Referenced by getZoneOverlap().
Copyright © GarageGames, LLC. All Rights Reserved.