NetStringTable Class Reference
Main Modules Class List Namespace List Online
NetStringTable Class Reference
#include <sim/netStringTable.h>
Public Member Functions
void dumpToConsole ()
void incStringRefScript (U32 id)
const char * lookupString (U32 id)
void removeString (U32 id, bool script=false)
Static Public Member Functions
static void create ()
static void destroy ()
static void expandString (NetStringHandle &string, char *buf, U32 bufSize, U32 argc, const char **argv)
Friends
U32 GameAddTaggedString (const char *string)
Member Function Documentation
static void NetStringTable::create () static
static void NetStringTable::destroy () static
void NetStringTable::dumpToConsole ()
static void NetStringTable::expandString (NetStringHandle & string, char * buf, U32 bufSize, U32 argc, const char ** argv) static
void NetStringTable::incStringRefScript (U32 id)
const char* NetStringTable::lookupString (U32 id)
Referenced by NetStringHandle::getString().
void NetStringTable::removeString (U32 id, bool script = false)
Referenced by NetStringHandle::operator=(), NetStringHandle::setFromIndex(), and NetStringHandle::~NetStringHandle().
Friends And Related Function Documentation
U32 GameAddTaggedString (const char * string) friend
Copyright © GarageGames, LLC. All Rights Reserved.