RazerHydraDevice Class Reference
Main Modules Class List Namespace List Online
RazerHydraDevice Class Reference
#include <platform/input/razerHydra/razerHydraDevice.h>
Public Member Functions
RazerHydraDevice ()
~RazerHydraDevice ()
void disable ()
bool enable ()
const Point3F & getControllerPosition (U32 controller)
const QuatF & getControllerRotation (U32 controller)
bool isActive ()
bool isControllerDocked (U32 controller)
bool process ()
Public Member Functions inherited from IInputDevice
const char * getDeviceName () const
U32 getDeviceType () const
bool isEnabled ()
Static Public Member Functions
static const char * getSingletonName ()
static void staticInit ()
Static Public Attributes
static U32 RH_1 [RazerHydraConstants::MaxControllers]
static U32 RH_2 [RazerHydraConstants::MaxControllers]
static U32 RH_3 [RazerHydraConstants::MaxControllers]
static U32 RH_4 [RazerHydraConstants::MaxControllers]
static U32 RH_DOCKED [RazerHydraConstants::MaxControllers]
static U32 RH_FRAME
static U32 RH_POS [RazerHydraConstants::MaxControllers]
static U32 RH_POSX [RazerHydraConstants::MaxControllers]
static U32 RH_POSY [RazerHydraConstants::MaxControllers]
static U32 RH_POSZ [RazerHydraConstants::MaxControllers]
static U32 RH_ROT [RazerHydraConstants::MaxControllers]
static U32 RH_ROTAXISX [RazerHydraConstants::MaxControllers]
static U32 RH_ROTAXISY [RazerHydraConstants::MaxControllers]
static U32 RH_SHOULDER [RazerHydraConstants::MaxControllers]
static U32 RH_START [RazerHydraConstants::MaxControllers]
static U32 RH_THUMB [RazerHydraConstants::MaxControllers]
static U32 RH_THUMBX [RazerHydraConstants::MaxControllers]
static U32 RH_THUMBY [RazerHydraConstants::MaxControllers]
static U32 RH_TRIGGER [RazerHydraConstants::MaxControllers]
static bool smCombinedPositionEvents
static bool smEnableDevice
static bool smGenerateWholeFrameEvents
static F32 smMaximumAxisAngle
static bool smProcessWhenDocked
static bool smRotationAsAxisEvents
static bool smSeparatePositionEvents
Protected Member Functions
void buildCodeTable ()
Build out the codes used for controller actions with the Input Event Manager.
bool checkControllers ()
Checks if there are active controllers.
Protected Attributes
bool mActive
Is the Razer Hydra active (enabled means the library is loaded)
RazerHyrdaControllerData * mDataBuffer [RazerHydraConstants::MaxControllers][2]
Buffers to store data for the controllers.
FN_SixenseAutoEnableHemisphereTracking mfnSixenseAutoEnableHemisphereTracking
FN_SixenseExit mfnSixenseExit
FN_SixenseGetAllData mfnSixenseGetAllData
FN_SixenseGetAllNewestData mfnSixenseGetAllNewestData
FN_SixenseGetBaseColor mfnSixenseGetBaseColor
FN_SixenseGetData mfnSixenseGetData
FN_SixenseGetFilterEnabled mfnSixenseGetFilterEnabled
FN_SixenseGetFilterParams mfnSixenseGetFilterParams
FN_SixenseGetHemisphereTrackingMode mfnSixenseGetHemisphereTrackingMode
FN_SixenseGetHighPriorityBindingEnabled mfnSixenseGetHighPriorityBindingEnabled
FN_SixenseGetHistorySize mfnSixenseGetHistorySize
FN_SixenseGetMaxBases mfnSixenseGetMaxBases
FN_SixenseGetMaxControllers mfnSixenseGetMaxControllers
FN_SixenseGetNewestData mfnSixenseGetNewestData
FN_SixenseGetNumActiveControllers mfnSixenseGetNumActiveControllers
FN_SixenseInit mfnSixenseInit
FN_SixenseIsBaseConnected mfnSixenseIsBaseConnected
FN_SixenseIsControllerEnabled mfnSixenseIsControllerEnabled
FN_SixenseSetActiveBase mfnSixenseSetActiveBase
FN_SixenseSetBaseColor mfnSixenseSetBaseColor
FN_SixenseSetFilterEnabled mfnSixenseSetFilterEnabled
FN_SixenseSetFilterParams mfnSixenseSetFilterParams
FN_SixenseSetHemisphereTrackingMode mfnSixenseSetHemisphereTrackingMode
FN_SixenseSetHighPriorityBindingEnabled mfnSixenseSetHighPriorityBindingEnabled
FN_SixenseTriggerVibration mfnSixenseTriggerVibration
S32 mLastActiveCheck
When was the last check for an active Hydra.
S32 mMaximumBases
S32 mMaximumControllers
S32 mNumberActiveControllers
RazerHyrdaControllerData * mPrevData [RazerHydraConstants::MaxControllers]
Points to the buffers that holds the previously collected data for each controller.
DLibraryRef mRazerHydraLib
Protected Attributes inherited from IInputDevice
U32 mDeviceType
Device type.
bool mEnabled
Is the device enabled.
char mName [30]
Device name.
Constructor & Destructor Documentation
RazerHydraDevice::RazerHydraDevice ()
RazerHydraDevice::~RazerHydraDevice ()
Member Function Documentation
void RazerHydraDevice::buildCodeTable () protected
Build out the codes used for controller actions with the Input Event Manager.
bool RazerHydraDevice::checkControllers () protected
Checks if there are active controllers.
void RazerHydraDevice::disable ()
bool RazerHydraDevice::enable ()
const Point3F& RazerHydraDevice::getControllerPosition (U32 controller)
Referenced by isActive().
const QuatF& RazerHydraDevice::getControllerRotation (U32 controller)
Referenced by isActive().
static const char* RazerHydraDevice::getSingletonName () inline static
bool RazerHydraDevice::isActive () inline
References getControllerPosition(), getControllerRotation(), isControllerDocked(), and mActive.
bool RazerHydraDevice::isControllerDocked (U32 controller)
Referenced by isActive().
bool RazerHydraDevice::process () virtual
Implements IInputDevice.
static void RazerHydraDevice::staticInit () static
Member Data Documentation
bool RazerHydraDevice::mActive protected
Is the Razer Hydra active (enabled means the library is loaded)
Referenced by isActive().
RazerHyrdaControllerData* RazerHydraDevice::mDataBuffer[RazerHydraConstants::MaxControllers][2] protected
Buffers to store data for the controllers.
FN_SixenseAutoEnableHemisphereTracking RazerHydraDevice::mfnSixenseAutoEnableHemisphereTracking protected
FN_SixenseExit RazerHydraDevice::mfnSixenseExit protected
FN_SixenseGetAllData RazerHydraDevice::mfnSixenseGetAllData protected
FN_SixenseGetAllNewestData RazerHydraDevice::mfnSixenseGetAllNewestData protected
FN_SixenseGetBaseColor RazerHydraDevice::mfnSixenseGetBaseColor protected
FN_SixenseGetData RazerHydraDevice::mfnSixenseGetData protected
FN_SixenseGetFilterEnabled RazerHydraDevice::mfnSixenseGetFilterEnabled protected
FN_SixenseGetFilterParams RazerHydraDevice::mfnSixenseGetFilterParams protected
FN_SixenseGetHemisphereTrackingMode RazerHydraDevice::mfnSixenseGetHemisphereTrackingMode protected
FN_SixenseGetHighPriorityBindingEnabled RazerHydraDevice::mfnSixenseGetHighPriorityBindingEnabled protected
FN_SixenseGetHistorySize RazerHydraDevice::mfnSixenseGetHistorySize protected
FN_SixenseGetMaxBases RazerHydraDevice::mfnSixenseGetMaxBases protected
FN_SixenseGetMaxControllers RazerHydraDevice::mfnSixenseGetMaxControllers protected
FN_SixenseGetNewestData RazerHydraDevice::mfnSixenseGetNewestData protected
FN_SixenseGetNumActiveControllers RazerHydraDevice::mfnSixenseGetNumActiveControllers protected
FN_SixenseInit RazerHydraDevice::mfnSixenseInit protected
FN_SixenseIsBaseConnected RazerHydraDevice::mfnSixenseIsBaseConnected protected
FN_SixenseIsControllerEnabled RazerHydraDevice::mfnSixenseIsControllerEnabled protected
FN_SixenseSetActiveBase RazerHydraDevice::mfnSixenseSetActiveBase protected
FN_SixenseSetBaseColor RazerHydraDevice::mfnSixenseSetBaseColor protected
FN_SixenseSetFilterEnabled RazerHydraDevice::mfnSixenseSetFilterEnabled protected
FN_SixenseSetFilterParams RazerHydraDevice::mfnSixenseSetFilterParams protected
FN_SixenseSetHemisphereTrackingMode RazerHydraDevice::mfnSixenseSetHemisphereTrackingMode protected
FN_SixenseSetHighPriorityBindingEnabled RazerHydraDevice::mfnSixenseSetHighPriorityBindingEnabled protected
FN_SixenseTriggerVibration RazerHydraDevice::mfnSixenseTriggerVibration protected
S32 RazerHydraDevice::mLastActiveCheck protected
When was the last check for an active Hydra.
S32 RazerHydraDevice::mMaximumBases protected
S32 RazerHydraDevice::mMaximumControllers protected
S32 RazerHydraDevice::mNumberActiveControllers protected
RazerHyrdaControllerData* RazerHydraDevice::mPrevData[RazerHydraConstants::MaxControllers] protected
Points to the buffers that holds the previously collected data for each controller.
DLibraryRef RazerHydraDevice::mRazerHydraLib protected
U32 RazerHydraDevice::RH_1[RazerHydraConstants::MaxControllers] static
U32 RazerHydraDevice::RH_2[RazerHydraConstants::MaxControllers] static
U32 RazerHydraDevice::RH_3[RazerHydraConstants::MaxControllers] static
U32 RazerHydraDevice::RH_4[RazerHydraConstants::MaxControllers] static
U32 RazerHydraDevice::RH_DOCKED[RazerHydraConstants::MaxControllers] static
U32 RazerHydraDevice::RH_FRAME static
U32 RazerHydraDevice::RH_POS[RazerHydraConstants::MaxControllers] static
U32 RazerHydraDevice::RH_POSX[RazerHydraConstants::MaxControllers] static
U32 RazerHydraDevice::RH_POSY[RazerHydraConstants::MaxControllers] static
U32 RazerHydraDevice::RH_POSZ[RazerHydraConstants::MaxControllers] static
U32 RazerHydraDevice::RH_ROT[RazerHydraConstants::MaxControllers] static
U32 RazerHydraDevice::RH_ROTAXISX[RazerHydraConstants::MaxControllers] static
U32 RazerHydraDevice::RH_ROTAXISY[RazerHydraConstants::MaxControllers] static
U32 RazerHydraDevice::RH_SHOULDER[RazerHydraConstants::MaxControllers] static
U32 RazerHydraDevice::RH_START[RazerHydraConstants::MaxControllers] static
U32 RazerHydraDevice::RH_THUMB[RazerHydraConstants::MaxControllers] static
U32 RazerHydraDevice::RH_THUMBX[RazerHydraConstants::MaxControllers] static
U32 RazerHydraDevice::RH_THUMBY[RazerHydraConstants::MaxControllers] static
U32 RazerHydraDevice::RH_TRIGGER[RazerHydraConstants::MaxControllers] static
bool RazerHydraDevice::smCombinedPositionEvents static
bool RazerHydraDevice::smEnableDevice static
bool RazerHydraDevice::smGenerateWholeFrameEvents static
F32 RazerHydraDevice::smMaximumAxisAngle static
bool RazerHydraDevice::smProcessWhenDocked static
bool RazerHydraDevice::smRotationAsAxisEvents static
bool RazerHydraDevice::smSeparatePositionEvents static
Copyright © GarageGames, LLC. All Rights Reserved.