AsyncUpdateList Class Reference
Main Modules Class List Namespace List Online
AsyncUpdateList Class Reference
This structure keeps track of the objects that need updating.
#include <platform/async/asyncUpdate.h>
Public Member Functions
virtual ~AsyncUpdateList ()
virtual void add (IPolled *ptr)
Add the structure to the update list.
virtual void process (S32 timeOut=-1)
Update the structures currently on the processing list.
Public Member Functions inherited from ThreadSafeRefCount< AsyncUpdateList >
ThreadSafeRefCount ()
ThreadSafeRefCount (bool noSet)
void addRef ()
Increase the reference count on the object.
void clearLowestBit ()
U32 getRefCount () const
Get the current reference count.
bool isShared () const
void release ()
Decrease the object's reference count and delete the object, if the count drops to zero and claiming the object by the current thread succeeds.
Protected Types
typedef ThreadSafeDeque< IPolled * > UpdateList
Protected Attributes
UpdateList mUpdateList
List of structures currently in the update loop.
Protected Attributes inherited from ThreadSafeRefCount< AsyncUpdateList >
U32 mRefCount
Reference count and claim bit. Note that this increments in steps of two.
Additional Inherited Members
Public Types inherited from ThreadSafeRefCount< AsyncUpdateList >
typedef void Parent
Static Public Member Functions inherited from ThreadSafeRefCount< AsyncUpdateList >
static AsyncUpdateList * safeRead (AsyncUpdateList *const volatile &refPtr)
Dereference a reference-counted pointer in a multi-thread safe way.
Static Protected Member Functions inherited from ThreadSafeRefCount< AsyncUpdateList >
static U32 decrementAndTestAndSet (U32 &refCount)
Decrement the given reference count.
Detailed Description
This structure keeps track of the objects that need updating.
Member Typedef Documentation
typedef ThreadSafeDeque< IPolled* > AsyncUpdateList::UpdateList protected
Constructor & Destructor Documentation
virtual AsyncUpdateList::~AsyncUpdateList () inline virtual
References process().
Member Function Documentation
virtual void AsyncUpdateList::add (IPolled * ptr) inline virtual
Add the structure to the update list.
It will stay on this list, until its update() method returns false.
Note
This can be called on different threads.
References ThreadSafeDeque< T >::pushBack().
virtual void AsyncUpdateList::process (S32 timeOut = -1) virtual
Update the structures currently on the processing list.
Parameters
timeOut Soft limit in milliseconds on the time spent on flushing the list. Default of -1 means no limit and function will only return, if update list has been fully flushed.
Referenced by ~AsyncUpdateList().
Member Data Documentation
UpdateList AsyncUpdateList::mUpdateList protected
List of structures currently in the update loop.
Copyright © GarageGames, LLC. All Rights Reserved.