fsTiXmlDeclaration Class Reference
Main Modules Class List Namespace List Online
fsTiXmlDeclaration Class Reference
#include <persistence/taml/fsTinyXml.h>
Public Member Functions
fsTiXmlDeclaration ()
fsTiXmlDeclaration (const char *_version, const char *_encoding, const char *_standalone)
virtual TiXmlNode * Clone () const
virtual void Print (FileStream &stream, int depth, TIXML_STRING *str) const
virtual void Print (FileStream &stream, int depth) const
Constructor & Destructor Documentation
fsTiXmlDeclaration::fsTiXmlDeclaration () inline
fsTiXmlDeclaration::fsTiXmlDeclaration (const char * _version, const char * _encoding, const char * _standalone) inline
References fsTiXmlNode::Print().
Member Function Documentation
virtual TiXmlNode* fsTiXmlDeclaration::Clone () const inline virtual
virtual void fsTiXmlDeclaration::Print (FileStream & stream, int depth, TIXML_STRING * str) const virtual
Referenced by fsTiXmlUnknown::Clone().
virtual void fsTiXmlDeclaration::Print (FileStream & stream, int depth) const inline virtual
Implements fsTiXmlNode.
References fsTiXmlNode::Print().
Copyright © GarageGames, LLC. All Rights Reserved.