VideoFrameGrabber Class Reference
Main Modules Class List Namespace List Online
VideoFrameGrabber Class Reference abstract
Abstract frame grabber class implementation and initalization depends on video device.
#include <gfx/video/videoCapture.h>
Public Member Functions
VideoFrameGrabber ()
virtual ~VideoFrameGrabber ()
Protected Member Functions
void _onTextureEvent (GFXTexCallbackCode code)
Texture event callback.
virtual void captureBackBuffer ()=0
Captures the current backbuffer. If the last capture wasn't made into a bitmap, it will be overriden.
GBitmap * fetchBitmap ()
Returns one captured bitmap. Returns NULL if there are no more bitmaps.
virtual void makeBitmap ()=0
Starts converting the last backbuffer capture to a bitmap Depending on the VideoFrameGrabber implementation, this may not produce a bitmap right away.
void pushNewBitmap (GBitmap *bitmap)
Pushes a fresh bitmap into our list.
virtual void releaseTextures ()
Releases internal textures.
void setOutResolution (const Point2I &res)
Sets the output frame resolution.
Protected Attributes
Vector< GBitmap * > mBitmapList
Point2I mResolution
Detailed Description
Abstract frame grabber class implementation and initalization depends on video device.
Constructor & Destructor Documentation
VideoFrameGrabber::VideoFrameGrabber ()
Referenced by releaseTextures().
virtual VideoFrameGrabber::~VideoFrameGrabber () virtual
Referenced by releaseTextures().
Member Function Documentation
void VideoFrameGrabber::_onTextureEvent (GFXTexCallbackCode code) protected
Texture event callback.
Referenced by pushNewBitmap().
virtual void VideoFrameGrabber::captureBackBuffer () protected pure virtual
Captures the current backbuffer. If the last capture wasn't made into a bitmap, it will be overriden.
Implemented in VideoFrameGrabberD3D9.
Referenced by pushNewBitmap().
GBitmap* VideoFrameGrabber::fetchBitmap () protected
Returns one captured bitmap. Returns NULL if there are no more bitmaps.
Referenced by pushNewBitmap().
virtual void VideoFrameGrabber::makeBitmap () protected pure virtual
Starts converting the last backbuffer capture to a bitmap Depending on the VideoFrameGrabber implementation, this may not produce a bitmap right away.
Implemented in VideoFrameGrabberD3D9.
Referenced by pushNewBitmap().
void VideoFrameGrabber::pushNewBitmap (GBitmap * bitmap) inline protected
Pushes a fresh bitmap into our list.
References _onTextureEvent(), captureBackBuffer(), fetchBitmap(), makeBitmap(), and Vector< T >::push_back().
virtual void VideoFrameGrabber::releaseTextures () inline protected virtual
Releases internal textures.
Reimplemented in VideoFrameGrabberD3D9.
References VideoFrameGrabber(), and ~VideoFrameGrabber().
void VideoFrameGrabber::setOutResolution (const Point2I & res) inline protected
Sets the output frame resolution.
Member Data Documentation
Vector<GBitmap*> VideoFrameGrabber::mBitmapList protected
Point2I VideoFrameGrabber::mResolution protected
Copyright © GarageGames, LLC. All Rights Reserved.