SFXALBuffer Class Reference
Main Modules Class List Namespace List Online
SFXALBuffer Class Reference
#include <sfx/openal/sfxALBuffer.h>
Public Types
typedef SFXBuffer Parent
Public Types inherited from SFXBuffer
typedef void Parent
enum Status {
STATUS_Null,
STATUS_Loading,
STATUS_Ready,
STATUS_Blocked,
STATUS_AtEnd
}
Status indicators for sound buffers.
Public Types inherited from IPolled
typedef void Parent
Public Types inherited from IOutputStream< SFXInternal::SFXStreamPacket * >
typedef SFXInternal::SFXStreamPacket * ElementType
The element type of this input stream.
typedef void Parent
Public Member Functions
virtual ~SFXALBuffer ()
Public Member Functions inherited from SFXBuffer
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
U32 getDuration () const
const SFXFormat & getFormat () const
virtual U32 getMemoryUsed () const
U32 getNumSamples () const
Status getStatus () const
bool isAtEnd () const
bool isBlocked () const
bool isDead () const
bool isLoading () const
bool isReady () const
bool isStreaming () const
bool isUnique () const
void load ()
Start the async request chain for the buffer.
virtual bool update ()
Update the object state.
Public Member Functions inherited from StrongRefBase
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Public Member Functions inherited from IOutputStream< SFXInternal::SFXStreamPacket * >
virtual void write (const ElementType *buffer, U32 num)=0
Write "num" elements from "buffer" to the stream at its current position.
Static Public Member Functions
static SFXALBuffer * create (const OPENALFNTABLE &oalft, const ThreadSafeRef< SFXStream > &stream, SFXDescription *description, bool useHardware)
Protected Member Functions
SFXALBuffer (const OPENALFNTABLE &oalft, const ThreadSafeRef< SFXStream > &stream, SFXDescription *description, bool useHardware)
void _flush ()
Flush all queue state for this buffer on the device.
ALenum _getALFormat () const
SFXALVoice * _getUniqueVoice () const
virtual void write (SFXInternal::SFXStreamPacket *const *packets, U32 num)
Protected Member Functions inherited from SFXBuffer
SFXBuffer (const ThreadSafeRef< SFXStream > &stream, SFXDescription *description, bool createAsyncState=true)
Create a new buffer from stream using the parameters in description.
SFXBuffer (SFXDescription *description)
Create a buffer with just a description.
virtual ~SFXBuffer ()
void _setStatus (Status status)
Set the buffer status and trigger mOnStatusChange if the status changes.
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Static Protected Member Functions
static ALenum _sfxFormatToALFormat (const SFXFormat &format)
Protected Attributes
ALuint mALBuffer
AL buffer in case this is a static, non-streaming buffer.
Vector< ALuint > mFreeBuffers
Free buffers for use in queuing in case this is a streaming buffer.
bool mIs3d
const OPENALFNTABLE & mOpenAL
bool mUseHardware
Protected Attributes inherited from SFXBuffer
AsyncStatePtr mAsyncState
Pointer to structure keeping the asynchronous I/O state of the buffer.
U32 mDuration
Total playback time of the associated sound stream in milliseconds.
SFXFormat mFormat
The sound sample format used by the buffer.
bool mIsDead
If true, the buffer is dead and will be deleted.
bool mIsLooping
For streaming buffers, tells whether the source stream loops.
bool mIsStreaming
If true, this is a continuously streaming buffer.
bool mIsUnique
If true, this buffer can only have a single SFXVoice attached.
Status mStatus
The buffer readiness status.
StrongWeakRefPtr< SFXVoice > mUniqueVoice
If this is a unique buffer (i.e.
Protected Attributes inherited from StrongRefBase
U32 mRefCount
reference counter for StrongRefPtr objects
Additional Inherited Members
Public Attributes inherited from SFXBuffer
Signal< void(SFXBuffer *buffer, Status newStatus) > mOnStatusChange
Signal that is triggered when the buffer status changes.
Static Public Attributes inherited from SFXBuffer
static Signal< void(SFXBuffer *) > smBufferDestroyedSignal
This signal is triggered from SFXBuffer's destructor so the sound system can keep track of buffers being released on the device.
Protected Types inherited from SFXBuffer
typedef ThreadSafeRef< AsyncState > AsyncStatePtr
typedef SFXInternal::SFXAsyncQueue * SFXAsyncQueuePtr
typedef ThreadSafeRef< SFXInternal::SFXAsyncStream > SFXAsyncStreamPtr
Member Typedef Documentation
typedef SFXBuffer SFXALBuffer::Parent
Constructor & Destructor Documentation
SFXALBuffer::SFXALBuffer (const OPENALFNTABLE & oalft, const ThreadSafeRef< SFXStream > & stream, SFXDescription * description, bool useHardware) protected
virtual SFXALBuffer::~SFXALBuffer () virtual
Referenced by _getUniqueVoice().
Member Function Documentation
void SFXALBuffer::_flush () protected virtual
Flush all queue state for this buffer on the device.
Note
Called on the SFX update thread.
Implements SFXBuffer.
Referenced by _getUniqueVoice().
ALenum SFXALBuffer::_getALFormat () const inline protected
References _sfxFormatToALFormat(), and SFXBuffer::getFormat().
SFXALVoice* SFXALBuffer::_getUniqueVoice () const inline protected
References _flush(), create(), StrongWeakRefPtr< T >::getPointer(), SFXBuffer::mUniqueVoice, write(), and ~SFXALBuffer().
static ALenum SFXALBuffer::_sfxFormatToALFormat (const SFXFormat & format) inline static protected
References SFXFormat::getBitsPerSample(), and SFXFormat::getChannels().
Referenced by _getALFormat().
static SFXALBuffer* SFXALBuffer::create (const OPENALFNTABLE & oalft, const ThreadSafeRef< SFXStream > & stream, SFXDescription * description, bool useHardware) static
Referenced by _getUniqueVoice().
virtual void SFXALBuffer::write (SFXInternal::SFXStreamPacket *const * packets, U32 num) protected virtual
Referenced by _getUniqueVoice().
Member Data Documentation
ALuint SFXALBuffer::mALBuffer protected
AL buffer in case this is a static, non-streaming buffer.
Vector< ALuint > SFXALBuffer::mFreeBuffers protected
Free buffers for use in queuing in case this is a streaming buffer.
bool SFXALBuffer::mIs3d protected
const OPENALFNTABLE& SFXALBuffer::mOpenAL protected
bool SFXALBuffer::mUseHardware protected
Copyright © GarageGames, LLC. All Rights Reserved.