ShadowVolumeBSP Class Reference
Main Modules Class List Namespace List Online
ShadowVolumeBSP Class Reference
Used to calculate shadows.
#include <lighting/common/shadowVolumeBSP.h>
Classes
struct SurfaceInfo
struct SVNode
struct SVPoly
Public Member Functions
ShadowVolumeBSP ()
~ShadowVolumeBSP ()
void addToPolyList (SVPoly **, SVPoly *) const
void addUniqueVolume (SurfaceInfo *, U32)
void clipPoly (SVNode *, SVPoly **, SVPoly *)
void clipToSelf (SVNode *, SVPoly **, SVPoly *)
SVNode * createNode ()
SVPoly * createPoly ()
F32 getClippedSurfaceArea (SVNode *, SVPoly *)
F32 getLitSurfaceArea (SVPoly *, SurfaceInfo *)
const PlaneF & getPlane (U32) const
F32 getPolySurfaceArea (SVPoly *) const
SVNode * getShadowVolume (U32)
U32 insertPlane (const PlaneF &)
void insertPoly (SVNode **, SVPoly *)
void insertPolyBack (SVNode **, SVPoly *)
void insertPolyFront (SVNode **, SVPoly *)
void insertShadowVolume (SVNode **, U32)
void movePolyList (SVPoly **, SVPoly *) const
void recycleNode (SVNode *)
void recyclePoly (SVPoly *)
void removeLastInterior ()
void splitPoly (SVPoly *, const PlaneF &, SVPoly **, SVPoly **)
bool testPoint (SVNode *, const Point3F &)
bool testPoly (SVNode *, SVPoly *)
SVNode::Side whichSide (SVPoly *, const PlaneF &) const
Access functions
void insertPoly (SVPoly *poly)
bool testPoint (Point3F &pnt)
bool testPoly (SVPoly *poly)
F32 getClippedSurfaceArea (SVPoly *poly)
Helpers
void buildPolyVolume (SVPoly *, LightInfo *)
SVPoly * copyPoly (SVPoly *)
Public Attributes
SVNode * mFirstInteriorNode
Chunker< SVNode > mNodeChunker
SVNode * mNodeStore
Vector< SVNode * > mParentNodes
Vector< PlaneF > mPlanes
Chunker< SVPoly > mPolyChunker
SVPoly * mPolyStore
Vector< SVNode * > mShadowVolumes
Vector< SurfaceInfo * > mSurfaces
SVNode * mSVRoot
Detailed Description
Used to calculate shadows.
Constructor & Destructor Documentation
ShadowVolumeBSP::ShadowVolumeBSP ()
ShadowVolumeBSP::~ShadowVolumeBSP ()
Member Function Documentation
void ShadowVolumeBSP::addToPolyList (SVPoly ** , SVPoly *) const
void ShadowVolumeBSP::addUniqueVolume (SurfaceInfo * , U32)
void ShadowVolumeBSP::buildPolyVolume (SVPoly * , LightInfo *)
Referenced by getClippedSurfaceArea().
void ShadowVolumeBSP::clipPoly (SVNode * , SVPoly ** , SVPoly *)
void ShadowVolumeBSP::clipToSelf (SVNode * , SVPoly ** , SVPoly *)
SVPoly* ShadowVolumeBSP::copyPoly (SVPoly *)
Referenced by getClippedSurfaceArea().
SVNode* ShadowVolumeBSP::createNode ()
SVPoly* ShadowVolumeBSP::createPoly ()
F32 ShadowVolumeBSP::getClippedSurfaceArea (SVNode * , SVPoly *)
F32 ShadowVolumeBSP::getClippedSurfaceArea (SVPoly * poly) inline
References buildPolyVolume(), copyPoly(), and getClippedSurfaceArea().
Referenced by getClippedSurfaceArea().
F32 ShadowVolumeBSP::getLitSurfaceArea (SVPoly * , SurfaceInfo *)
const PlaneF& ShadowVolumeBSP::getPlane (U32) const
F32 ShadowVolumeBSP::getPolySurfaceArea (SVPoly *) const
SVNode* ShadowVolumeBSP::getShadowVolume (U32)
U32 ShadowVolumeBSP::insertPlane (const PlaneF &)
void ShadowVolumeBSP::insertPoly (SVNode ** , SVPoly *)
void ShadowVolumeBSP::insertPoly (SVPoly * poly) inline
References insertPoly().
Referenced by insertPoly().
void ShadowVolumeBSP::insertPolyBack (SVNode ** , SVPoly *)
void ShadowVolumeBSP::insertPolyFront (SVNode ** , SVPoly *)
void ShadowVolumeBSP::insertShadowVolume (SVNode ** , U32)
void ShadowVolumeBSP::movePolyList (SVPoly ** , SVPoly *) const
void ShadowVolumeBSP::recycleNode (SVNode *)
void ShadowVolumeBSP::recyclePoly (SVPoly *)
void ShadowVolumeBSP::removeLastInterior ()
void ShadowVolumeBSP::splitPoly (SVPoly * , const PlaneF & , SVPoly ** , SVPoly **)
bool ShadowVolumeBSP::testPoint (SVNode * , const Point3F &)
bool ShadowVolumeBSP::testPoint (Point3F & pnt) inline
References testPoint().
Referenced by testPoint().
bool ShadowVolumeBSP::testPoly (SVNode * , SVPoly *)
bool ShadowVolumeBSP::testPoly (SVPoly * poly) inline
References testPoly().
Referenced by testPoly().
SVNode::Side ShadowVolumeBSP::whichSide (SVPoly * , const PlaneF &) const
Member Data Documentation
SVNode* ShadowVolumeBSP::mFirstInteriorNode
Chunker<SVNode> ShadowVolumeBSP::mNodeChunker
SVNode* ShadowVolumeBSP::mNodeStore
Vector<SVNode*> ShadowVolumeBSP::mParentNodes
Vector<PlaneF> ShadowVolumeBSP::mPlanes
Chunker<SVPoly> ShadowVolumeBSP::mPolyChunker
SVPoly* ShadowVolumeBSP::mPolyStore
Vector<SVNode*> ShadowVolumeBSP::mShadowVolumes
Vector<SurfaceInfo *> ShadowVolumeBSP::mSurfaces
SVNode* ShadowVolumeBSP::mSVRoot
Copyright © GarageGames, LLC. All Rights Reserved.