PlatformFont Class Reference
Main Modules Class List Namespace List Online
PlatformFont Class Reference abstract
#include <platform/platformFont.h>
Classes
struct CharInfo
Public Member Functions
virtual ~PlatformFont ()
virtual bool create (const char *name, dsize_t size, U32 charset=TGE_ANSI_CHARSET)=0
This is just for createPlatformFont to call.
virtual PlatformFont::CharInfo & getCharInfo (const UTF16 ch) const =0
virtual PlatformFont::CharInfo & getCharInfo (const UTF8 *str) const =0
virtual U32 getFontBaseLine () const =0
virtual U32 getFontHeight () const =0
virtual bool isValidChar (const UTF16 ch) const =0
Is the specified character valid for rendering?
virtual bool isValidChar (const UTF8 *str) const =0
Static Public Member Functions
static void enumeratePlatformFonts (Vector< StringTableEntry > &fonts, UTF16 *fontFamily=NULL)
Constructor & Destructor Documentation
virtual PlatformFont::~PlatformFont () inline virtual
References create(), enumeratePlatformFonts(), getCharInfo(), getFontBaseLine(), getFontHeight(), and isValidChar().
Member Function Documentation
virtual bool PlatformFont::create (const char * name, dsize_t size, U32 charset = TGE_ANSI_CHARSET) pure virtual
This is just for createPlatformFont to call.
Implemented in x86UNIXFont, WinFont, and OSXFont.
Referenced by ~PlatformFont().
static void PlatformFont::enumeratePlatformFonts (Vector< StringTableEntry > & fonts, UTF16 * fontFamily = NULL) static
Referenced by ~PlatformFont().
virtual PlatformFont::CharInfo& PlatformFont::getCharInfo (const UTF16 ch) const pure virtual
Implemented in OSXFont, x86UNIXFont, and WinFont.
Referenced by ~PlatformFont().
virtual PlatformFont::CharInfo& PlatformFont::getCharInfo (const UTF8 * str) const pure virtual
Implemented in OSXFont, x86UNIXFont, and WinFont.
virtual U32 PlatformFont::getFontBaseLine () const pure virtual
Implemented in OSXFont, x86UNIXFont, and WinFont.
Referenced by ~PlatformFont().
virtual U32 PlatformFont::getFontHeight () const pure virtual
Implemented in OSXFont, x86UNIXFont, and WinFont.
Referenced by ~PlatformFont().
virtual bool PlatformFont::isValidChar (const UTF16 ch) const pure virtual
Is the specified character valid for rendering?
Implemented in OSXFont, x86UNIXFont, and WinFont.
Referenced by GFont::isValidChar(), and ~PlatformFont().
virtual bool PlatformFont::isValidChar (const UTF8 * str) const pure virtual
Implemented in OSXFont, x86UNIXFont, and WinFont.
Copyright © GarageGames, LLC. All Rights Reserved.