AssetTagsManifest::AssetTag Class Reference
Main Modules Class List Namespace List Online
AssetTagsManifest::AssetTag Class Reference
Asset location.
#include <assets/assetTagsManifest.h>
Public Member Functions
AssetTag (StringTableEntry tagName)
bool containsAsset (typeAssetId assetId)
void removeAsset (typeAssetId assetId)
Public Attributes
Vector< typeAssetId > mAssets
typeAssetTagName mTagName
Detailed Description
Asset location.
Constructor & Destructor Documentation
AssetTagsManifest::AssetTag::AssetTag (StringTableEntry tagName) inline
References mTagName.
Member Function Documentation
bool AssetTagsManifest::AssetTag::containsAsset (typeAssetId assetId) inline
References Vector< T >::begin(), Vector< T >::end(), and mAssets.
void AssetTagsManifest::AssetTag::removeAsset (typeAssetId assetId) inline
References Vector< T >::begin(), Vector< T >::end(), Vector< T >::erase(), and mAssets.
Member Data Documentation
Vector<typeAssetId> AssetTagsManifest::AssetTag::mAssets
Referenced by containsAsset(), and removeAsset().
typeAssetTagName AssetTagsManifest::AssetTag::mTagName
Referenced by AssetTag().
Copyright © GarageGames, LLC. All Rights Reserved.