SFXXAudioVoice Class Reference
Main Modules Class List Namespace List Online
SFXXAudioVoice Class Reference
#include <sfx/xaudio/sfxXAudioVoice.h>
Public Types
typedef SFXVoice Parent
Public Types inherited from SFXVoice
typedef void Parent
Public Types inherited from IPositionable< U32 >
typedef void Parent
typedef U32 PositionType
The type used to indicate positions.
Public Member Functions
virtual ~SFXXAudioVoice ()
const X3DAUDIO_EMITTER & getEmitter () const
bool is3D () const
Is this a 3D positional voice.
void play (bool looping)
Starts playback from the current position.
void setCone (F32 innerAngle, F32 outerAngle, F32 outerVolume)
Set sound cone of a 3D sound.
void setMinMaxDistance (F32 min, F32 max)
Sets the minimum and maximum distances for 3d falloff.
void setPitch (F32 pitch)
Sets the pitch scale.
void setTransform (const MatrixF &transform)
Sets the position and orientation for a 3d voice.
void setVelocity (const VectorF &velocity)
Sets the velocity for a 3d voice.
void setVolume (F32 volume)
Sets the volume.
Public Member Functions inherited from SFXVoice
virtual ~SFXVoice ()
The destructor.
const SFXFormat & getFormat () const
virtual U32 getPosition () const
Return the current playback position (in number of samples).
virtual SFXStatus getStatus () const
virtual bool isVirtual () const
Returns true if the voice is virtualized on the device.
virtual void pause ()
Pauses playback.
virtual void setPosition (U32 sample)
Sets the playback position to the given sample count.
virtual void setPriority (F32 priority)
Set the priority of this voice.
virtual void setReverb (const SFXSoundReverbProperties &reverb)
Set the reverb properties for playback of this sound.
virtual void setRolloffFactor (F32 factor)
Set the distance attenuation rolloff factor. Support by device optional.
virtual void stop ()
Stops playback and moves the position to the start.
Public Member Functions inherited from StrongRefBase
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Static Public Member Functions
static SFXXAudioVoice * create (IXAudio2 *xaudio, bool is3D, SFXXAudioBuffer *buffer, SFXXAudioVoice *inVoice=NULL)
Protected Member Functions
SFXXAudioVoice (SFXXAudioBuffer *buffer)
This constructor does not create a valid voice.
void _flush ()
SFXXAudioBuffer * _getBuffer () const
void _loadNonStreamed ()
virtual void _pause ()
Pause playback on the device.
virtual void _play ()
Start playback on the device.
virtual void _seek (U32 sample)
Set the playback cursor on the device.
virtual SFXStatus _status () const
Return the current playback status (playing, paused, or stopped).
virtual void _stop ()
Stop playback on the device.
virtual U32 _tell () const
Get the playback cursor on the device.
void STDMETHODCALLTYPE OnBufferEnd (void *bufferContext)
void STDMETHODCALLTYPE OnBufferStart (void *bufferContext)
void STDMETHODCALLTYPE OnLoopEnd (void *bufferContext)
void STDMETHODCALLTYPE OnStreamEnd ()
void STDMETHODCALLTYPE OnVoiceError (void *bufferContext, HRESULT error)
void STDMETHODCALLTYPE OnVoiceProcessingPassEnd ()
void STDMETHODCALLTYPE OnVoiceProcessingPassStart (UINT32 BytesRequired)
void STDMETHODCALLTYPE OnVoiceProcessingPassStart ()
Protected Member Functions inherited from SFXVoice
SFXVoice (SFXBuffer *buffer)
void _attachToBuffer ()
virtual void _onBufferStatusChange (SFXBuffer *buffer, SFXBuffer::Status newStatus)
Hooked up to SFXBuffer::mOnStatusChange of mBuffer.
void _resetStream (U32 sampleStartPos, bool triggerUpdate=true)
Reset streaming of the voice by cloning the current streaming source and letting the resulting stream start from sampleStartPos.
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Protected Attributes
X3DAUDIO_EMITTER mEmitter
The cached X3DAudio emitter data.
bool mHasStarted
Whether we have started playback.
bool mHasStopped
Whether the voice has stopped playing.
bool mIs3D
Used to know what sounds need positional updates.
bool mIsLooping
Whether playback is looping.
bool mIsPlaying
Whether playback is currently running.
CRITICAL_SECTION mLock
F32 mPitch
Since 3D sounds are pitch shifted for doppler effect we need to track the users base pitch.
S32 mSamplesPlayedOffset
XAudio does not reset the SamplesPlayed count as is stated in the docs.
SFXXAudioDevice * mXAudioDevice
The device that created us.
IXAudio2SourceVoice * mXAudioVoice
The XAudio voice.
Data for Non-Streaming Voices
bool mNonStreamBufferLoaded
Whether we have loaded our non-streaming data.
XAUDIO2_BUFFER mNonStreamBuffer
Audio buffer for non-streaming voice.
U32 mNonStreamSampleStartPos
Sample to start playing at when seting up mNonStreamBuffer.
Protected Attributes inherited from SFXVoice
WeakRefPtr< SFXBuffer > mBuffer
Sound data played back by the voice.
U32 mOffset
For streaming voices, this keeps track of play start offset after seeking.
volatile SFXStatus mStatus
Current playback status.
Protected Attributes inherited from StrongRefBase
U32 mRefCount
reference counter for StrongRefPtr objects
Additional Inherited Members
Static Public Attributes inherited from SFXVoice
static Signal< void(SFXVoice *) > smVoiceCreatedSignal
static Signal< void(SFXVoice *) > smVoiceDestroyedSignal
Member Typedef Documentation
typedef SFXVoice SFXXAudioVoice::Parent
Constructor & Destructor Documentation
SFXXAudioVoice::SFXXAudioVoice (SFXXAudioBuffer * buffer) protected
This constructor does not create a valid voice.
See also
SFXXAudioVoice::create
virtual SFXXAudioVoice::~SFXXAudioVoice () virtual
Referenced by _getBuffer().
Member Function Documentation
void SFXXAudioVoice::_flush () protected
Referenced by OnVoiceProcessingPassStart().
SFXXAudioBuffer* SFXXAudioVoice::_getBuffer () const inline protected
References create(), WeakRefPtr< T >::getPointer(), is3D(), SFXVoice::mBuffer, play(), setCone(), setMinMaxDistance(), setPitch(), setTransform(), setVelocity(), setVolume(), and ~SFXXAudioVoice().
void SFXXAudioVoice::_loadNonStreamed () protected
Referenced by OnVoiceProcessingPassStart().
virtual void SFXXAudioVoice::_pause () protected virtual
Pause playback on the device.
Note
Called from both the SFX update thread and the main thread.
Implements SFXVoice.
Referenced by OnVoiceProcessingPassStart().
virtual void SFXXAudioVoice::_play () protected virtual
Start playback on the device.
Note
Called from both the SFX update thread and the main thread.
Implements SFXVoice.
Referenced by OnVoiceProcessingPassStart().
virtual void SFXXAudioVoice::_seek (U32 sample) protected virtual
Set the playback cursor on the device.
Note
Only used for non-streaming voices.
Implements SFXVoice.
Referenced by OnVoiceProcessingPassStart().
virtual SFXStatus SFXXAudioVoice::_status () const protected virtual
Return the current playback status (playing, paused, or stopped).
Default status is stopped.
Implements SFXVoice.
Referenced by OnVoiceProcessingPassStart().
virtual void SFXXAudioVoice::_stop () protected virtual
Stop playback on the device.
Note
Called from both the SFX update thread and the main thread.
Implements SFXVoice.
Referenced by OnVoiceProcessingPassStart().
virtual U32 SFXXAudioVoice::_tell () const protected virtual
Get the playback cursor on the device.
When the voice is playing or paused, this method must return a valid sample position. When the voice is stopped, the result of this method is undefined.
For streaming voices that are looping, the sample position must be a total count of the number of samples played so far which thus includes the count of all cycles before the current one. For non-looping voices, this behavior is optional.
Note
This is called for both streaming and non-streaming voices.
Implements SFXVoice.
Referenced by OnVoiceProcessingPassStart().
static SFXXAudioVoice* SFXXAudioVoice::create (IXAudio2 * xaudio, bool is3D, SFXXAudioBuffer * buffer, SFXXAudioVoice * inVoice = NULL) static
Referenced by _getBuffer().
const X3DAUDIO_EMITTER& SFXXAudioVoice::getEmitter () const inline
References mEmitter.
bool SFXXAudioVoice::is3D () const inline
Is this a 3D positional voice.
References mIs3D.
Referenced by _getBuffer().
void STDMETHODCALLTYPE SFXXAudioVoice::OnBufferEnd (void * bufferContext) protected
Referenced by OnVoiceProcessingPassEnd().
void STDMETHODCALLTYPE SFXXAudioVoice::OnBufferStart (void * bufferContext) inline protected
void STDMETHODCALLTYPE SFXXAudioVoice::OnLoopEnd (void * bufferContext) inline protected
void STDMETHODCALLTYPE SFXXAudioVoice::OnStreamEnd () protected
void STDMETHODCALLTYPE SFXXAudioVoice::OnVoiceError (void * bufferContext, HRESULT error) inline protected
void STDMETHODCALLTYPE SFXXAudioVoice::OnVoiceProcessingPassEnd () inline protected
References OnBufferEnd().
void STDMETHODCALLTYPE SFXXAudioVoice::OnVoiceProcessingPassStart (UINT32 BytesRequired) inline protected
void STDMETHODCALLTYPE SFXXAudioVoice::OnVoiceProcessingPassStart () inline protected
References _flush(), _loadNonStreamed(), _pause(), _play(), _seek(), _status(), _stop(), and _tell().
void SFXXAudioVoice::play (bool looping) virtual
Starts playback from the current position.
Reimplemented from SFXVoice.
Referenced by _getBuffer().
void SFXXAudioVoice::setCone (F32 innerAngle, F32 outerAngle, F32 outerVolume) virtual
Set sound cone of a 3D sound.
Parameters
innerAngle Inner cone angle in degrees.
outerAngle Outer cone angle in degrees.
outerVolume Outer volume factor.
Implements SFXVoice.
Referenced by _getBuffer().
void SFXXAudioVoice::setMinMaxDistance (F32 min, F32 max) virtual
Sets the minimum and maximum distances for 3d falloff.
Implements SFXVoice.
Referenced by _getBuffer().
void SFXXAudioVoice::setPitch (F32 pitch) virtual
Sets the pitch scale.
Implements SFXVoice.
Referenced by _getBuffer().
void SFXXAudioVoice::setTransform (const MatrixF & transform) virtual
Sets the position and orientation for a 3d voice.
Implements SFXVoice.
Referenced by _getBuffer().
void SFXXAudioVoice::setVelocity (const VectorF & velocity) virtual
Sets the velocity for a 3d voice.
Implements SFXVoice.
Referenced by _getBuffer().
void SFXXAudioVoice::setVolume (F32 volume) virtual
Sets the volume.
Implements SFXVoice.
Referenced by _getBuffer().
Member Data Documentation
X3DAUDIO_EMITTER SFXXAudioVoice::mEmitter protected
The cached X3DAudio emitter data.
Referenced by getEmitter().
bool SFXXAudioVoice::mHasStarted protected
Whether we have started playback.
bool SFXXAudioVoice::mHasStopped mutable protected
Whether the voice has stopped playing.
bool SFXXAudioVoice::mIs3D protected
Used to know what sounds need positional updates.
Referenced by is3D().
bool SFXXAudioVoice::mIsLooping protected
Whether playback is looping.
bool SFXXAudioVoice::mIsPlaying protected
Whether playback is currently running.
CRITICAL_SECTION SFXXAudioVoice::mLock protected
XAUDIO2_BUFFER SFXXAudioVoice::mNonStreamBuffer protected
Audio buffer for non-streaming voice.
bool SFXXAudioVoice::mNonStreamBufferLoaded protected
Whether we have loaded our non-streaming data.
We use an explicit flag here as we really can't rely on XAUDIO2_VOICE_STATE.
U32 SFXXAudioVoice::mNonStreamSampleStartPos protected
Sample to start playing at when seting up mNonStreamBuffer.
F32 SFXXAudioVoice::mPitch protected
Since 3D sounds are pitch shifted for doppler effect we need to track the users base pitch.
S32 SFXXAudioVoice::mSamplesPlayedOffset protected
XAudio does not reset the SamplesPlayed count as is stated in the docs.
To work around that, we offset the values reported by XAudio through this field.
SFXXAudioDevice* SFXXAudioVoice::mXAudioDevice protected
The device that created us.
IXAudio2SourceVoice* SFXXAudioVoice::mXAudioVoice protected
The XAudio voice.
Copyright © GarageGames, LLC. All Rights Reserved.