Vector< T > Class Template Reference
Main Modules Class List Namespace List Online
Vector< T > Class Template Reference
A dynamic array template class.
#include <platform/platform.h>
Inherited by FastVector< T >, Selection< T >, TSMesh::FreeableVector< T >, and VectorSet< T >.
Public Member Functions
Vector (const U32 initialSize=0)
Vector (const U32 initialSize, const char *fileName, const U32 lineNum)
Vector (const char *fileName, const U32 lineNum)
Vector (const Vector &)
~Vector ()
Protected Member Functions
void construct (U32 start, U32 end)
Constructs elements from start to end-1
void construct (U32 start, U32 end, const T *array)
void destroy (U32 start, U32 end)
Destructs elements from start to end-1
bool resize (U32)
Protected Attributes
T * mArray
Pointer to the Vector elements.
U32 mArraySize
Number of elements allocated for the Vector.
U32 mElementCount
Number of elements currently in the Vector.
STL interface
typedef T value_type
typedef T & reference
typedef const T & const_reference
typedef T * iterator
typedef const T * const_iterator
typedef S32 difference_type
typedef U32 size_type
typedef difference_type(QSORT_CALLBACK * compare_func) (const T *a, const T *b)
Vector< T > & operator= (const Vector< T > &p)
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
S32 size () const
bool empty () const
bool contains (const T &) const
void insert (iterator, const T &)
void erase (iterator)
T & front ()
const T & front () const
T & back ()
const T & back () const
void push_front (const T &)
void push_back (const T &)
U32 push_front_unique (const T &)
U32 push_back_unique (const T &)
S32 find_next (const T &, U32 start=0) const
void pop_front ()
void pop_back ()
T & operator[] (U32)
const T & operator[] (U32) const
T & operator[] (S32 i)
const T & operator[] (S32 i) const
void reserve (U32)
U32 capacity () const
Extended interface
U32 memSize () const
T * address () const
U32 setSize (U32)
void increment ()
void decrement ()
void increment (U32)
void decrement (U32)
void insert (U32)
void insert (U32, const T &)
void erase (U32)
void erase_fast (U32)
void erase (U32 index, U32 count)
void erase_fast (iterator)
void clear ()
void compact ()
void sort (compare_func f)
void fill (const T &value)
bool remove (const T &)
Finds the first matching element and erases it.
T & first ()
T & last ()
const T & first () const
const T & last () const
void set (void *addr, U32 sz)
void merge (const Vector &p)
Appends the content of the vector to this one.
void merge (const T *addr, U32 count)
Appends the content of the array to the vector.
void reverse ()
Detailed Description
template<class T>
class Vector< T >
A dynamic array template class.
The vector grows as you insert or append elements. Insertion is fastest at the end of the array. Resizing of the array can be avoided by pre-allocating space using the reserve() method.
Member Typedef Documentation
template<class T> typedef difference_type(QSORT_CALLBACK * Vector< T >::compare_func) (const T *a, const T *b)
template<class T> typedef const T* Vector< T >::const_iterator
template<class T> typedef const T& Vector< T >::const_reference
template<class T> typedef S32 Vector< T >::difference_type
template<class T> typedef T* Vector< T >::iterator
template<class T> typedef T& Vector< T >::reference
template<class T> typedef U32 Vector< T >::size_type
template<class T> typedef T Vector< T >::value_type
Constructor & Destructor Documentation
template<class T > Vector< T >::Vector (const U32 initialSize = 0) inline
References Vector< T >::mArray, Vector< T >::mArraySize, Vector< T >::mElementCount, and Vector< T >::reserve().
template<class T > Vector< T >::Vector (const U32 initialSize, const char * fileName, const U32 lineNum) inline
References Vector< T >::mArray, Vector< T >::mArraySize, Vector< T >::mElementCount, and Vector< T >::reserve().
template<class T > Vector< T >::Vector (const char * fileName, const U32 lineNum) inline
References Vector< T >::mArray, Vector< T >::mArraySize, and Vector< T >::mElementCount.
template<class T > Vector< T >::Vector (const Vector< T > & p) inline
References Vector< T >::construct(), Vector< T >::mArray, Vector< T >::mElementCount, and Vector< T >::resize().
template<class T > Vector< T >::~Vector () inline
References Vector< T >::clear(), dFree(), and Vector< T >::mArray.
Member Function Documentation
template<class T > T * Vector< T >::address () const inline
References Vector< T >::mArray.
Referenced by PolyhedronVectorData::getEdges(), PolyhedronVectorData::getPlanes(), PolyhedronVectorData::getPoints(), Vector< LightInfo * >::operator[](), Vector< T >::set(), and Vector< T >::sort().
template<class T > T & Vector< T >::back () inline
References Vector< T >::end(), and Vector< T >::mElementCount.
Referenced by VectorPtr< GuiFrameSetCtrl::FrameDetail * >::insert().
template<class T > const T & Vector< T >::back () const inline
References Vector< T >::end(), and Vector< T >::mElementCount.
template<class T > Vector< T >::iterator Vector< T >::begin () inline
References Vector< T >::mArray.
Referenced by Vector< T >::contains(), AssetQuery::containsAsset(), AssetTagsManifest::AssetTag::containsAsset(), TamlCustomNode::findNode(), TamlCustomNodes::findNode(), Vector< T >::front(), ConstantTable::GetConstantByName(), ModuleDefinition::getDependencies(), EventManager::getEventManager(), TamlCustomNode::getIgnoreEmpty(), Selection< T >::offset(), EventManager::printEventManagers(), Vector< T >::remove(), AssetTagsManifest::AssetTag::removeAsset(), EventManager::removeEventManager(), Selection< T >::rotate(), and TamlAssetDeclaredVisitor::visit().
template<class T > Vector< T >::const_iterator Vector< T >::begin () const inline
References Vector< T >::mArray.
template<class T > U32 Vector< T >::capacity () const inline
References Vector< T >::mArraySize.
Referenced by Vector< T >::memSize(), and Vector< LightInfo * >::operator[]().
template<class T > void Vector< T >::clear (void) inline
References Vector< T >::destroy(), and Vector< T >::mElementCount.
Referenced by FindMatch::clear(), TamlAssetDeclaredVisitor::clear(), TSShapeConstructor::ChangeSet::clear(), CollisionInterface::clearCollisionNotifyList(), GuiTextListCtrl::clearColumnOffsets(), GuiEditCtrl::clearGuides(), Ribbon::clearSegments(), RuntimeClassRep< T >::consoleRegister(), _SourceReader::initFromSource(), Vector< LightInfo * >::operator[](), IdGenerator::reset(), AssetDefinition::reset(), _SourceReader::reset(), ModuleDefinition::setDependencies(), DDSFile::~DDSFile(), GFXAdapter::~GFXAdapter(), and Vector< T >::~Vector().
template<class T > void Vector< T >::compact () inline
References Vector< T >::mElementCount, and Vector< T >::resize().
Referenced by Vector< LightInfo * >::operator[]().
template<class T > void Vector< T >::construct (U32 start, U32 end) inline protected
Constructs elements from start to end-1
References constructInPlace(), Vector< T >::mArray, and Vector< T >::mElementCount.
Referenced by Vector< T >::increment(), Vector< T >::operator=(), Vector< T >::setSize(), and Vector< T >::Vector().
template<class T> void Vector< T >::construct (U32 start, U32 end, const T * array) inline protected
References constructInPlace(), Vector< T >::mArray, and Vector< T >::mElementCount.
template<class T> bool Vector< T >::contains (const T & x) const inline
References Vector< T >::begin(), and Vector< T >::end().
Referenced by SceneTraversalState::haveVisitedZone(), and GuiTreeViewCtrl::isSelected().
template<class T > void Vector< T >::decrement () inline
References destructInPlace(), Vector< T >::mArray, and Vector< T >::mElementCount.
Referenced by Vector< LightInfo * >::operator[](), Vector< T >::pop_back(), and ScopeTracker< NUM_DIMENSIONS, Object >::updateObject().
template<class T > void Vector< T >::decrement (U32 delta) inline
References Vector< T >::destroy(), and Vector< T >::mElementCount.
template<class T > void Vector< T >::destroy (U32 start, U32 end) inline protected
Destructs elements from start to end-1
References destructInPlace(), Vector< T >::mArray, and Vector< T >::mElementCount.
Referenced by Vector< T >::clear(), Vector< T >::decrement(), Vector< T >::erase(), Vector< T >::operator=(), and Vector< T >::setSize().
template<class T > bool Vector< T >::empty () const inline
References Vector< T >::mElementCount.
Referenced by IdGenerator::alloc(), MaterialList::empty(), TSShapeConstructor::ChangeSet::empty(), FeatureSet::getDescription(), ForestCell::hasBatches(), PersistenceManager::hasDirty(), TSShapeInstance::inTransition(), VertexPolyList::isEmpty(), FeatureSet::isEmpty(), ForestCell::isEmpty(), FeatureSet::isNotEmpty(), SimSetIterator::operator*(), and ScopeTracker< NUM_DIMENSIONS, Object >::updateObject().
template<class T > Vector< T >::iterator Vector< T >::end () inline
References Vector< T >::mArray, and Vector< T >::mElementCount.
Referenced by Vector< T >::back(), Vector< T >::contains(), AssetQuery::containsAsset(), AssetTagsManifest::AssetTag::containsAsset(), ConstantTable::GetConstantByName(), ModuleDefinition::getDependencies(), EventManager::getEventManager(), Selection< T >::offset(), EventManager::printEventManagers(), Vector< T >::remove(), AssetTagsManifest::AssetTag::removeAsset(), EventManager::removeEventManager(), Selection< T >::rotate(), and TamlAssetDeclaredVisitor::visit().
template<class T > Vector< T >::const_iterator Vector< T >::end () const inline
References Vector< T >::mArray, and Vector< T >::mElementCount.
template<class T > void Vector< T >::erase (iterator q) inline
References Vector< T >::mArray.
Referenced by VectorPtr< GuiFrameSetCtrl::FrameDetail * >::insert(), Vector< LightInfo * >::operator[](), Vector< T >::pop_front(), Vector< T >::remove(), WindowInputGenerator::removeAcceleratorKey(), WindowInputGenerator::removeAcceleratorKeys(), AssetTagsManifest::AssetTag::removeAsset(), ThreadManager::removeThread(), and Interface< RenderComponentInterface >::~Interface().
template<class T > void Vector< T >::erase (U32 index) inline
References destructInPlace(), dMemmove(), Vector< T >::mArray, and Vector< T >::mElementCount.
template<class T > void Vector< T >::erase (U32 index, U32 count) inline
References Vector< T >::destroy(), dMemmove(), Vector< T >::mArray, and Vector< T >::mElementCount.
template<class T > void Vector< T >::erase_fast (U32 index) inline
References destructInPlace(), dMemmove(), Vector< T >::mArray, and Vector< T >::mElementCount.
Referenced by Vector< T >::erase_fast(), Vector< LightInfo * >::operator[](), and EventManager::removeEventManager().
template<class T > void Vector< T >::erase_fast (iterator q) inline
References Vector< T >::erase_fast(), and Vector< T >::mArray.
template<class T> void Vector< T >::fill (const T & value) inline
References Vector< T >::mArray, and Vector< T >::size().
Referenced by Vector< LightInfo * >::operator[]().
template<class T> S32 Vector< T >::find_next (const T & x, U32 start = 0) const inline
References Vector< T >::mArray, and Vector< T >::mElementCount.
Referenced by Vector< T >::push_back_unique(), and Vector< T >::push_front_unique().
template<class T > T & Vector< T >::first () inline
References Vector< T >::mArray, and Vector< T >::mElementCount.
Referenced by Vector< LightInfo * >::operator[]().
template<class T > const T & Vector< T >::first () const inline
References Vector< T >::mArray, and Vector< T >::mElementCount.
template<class T > T & Vector< T >::front () inline
References Vector< T >::begin().
Referenced by VectorPtr< GuiFrameSetCtrl::FrameDetail * >::insert().
template<class T > const T & Vector< T >::front () const inline
References Vector< T >::begin().
template<class T > void Vector< T >::increment () inline
References constructInPlace(), Vector< T >::mArray, Vector< T >::mArraySize, Vector< T >::mElementCount, and Vector< T >::resize().
Referenced by _TorqueThreadStaticReg::_TorqueThreadStaticReg(), ColladaExtension_animation_clip::ColladaExtension_animation_clip(), Vector< LightInfo * >::operator[](), Vector< T >::push_back(), and Vector< T >::push_back_unique().
template<class T > void Vector< T >::increment (U32 delta) inline
References Vector< T >::construct(), Vector< T >::mArraySize, Vector< T >::mElementCount, and Vector< T >::resize().
template<class T> void Vector< T >::insert (iterator p, const T & x) inline
References Vector< T >::mArray.
Referenced by Vector< T >::insert(), Vector< LightInfo * >::operator[](), Vector< T >::push_front(), and Vector< T >::push_front_unique().
template<class T> void Vector< T >::insert (U32 index) inline
References constructInPlace(), dMemmove(), Vector< T >::mArray, Vector< T >::mArraySize, Vector< T >::mElementCount, and Vector< T >::resize().
template<class T> void Vector< T >::insert (U32 index, const T & x) inline
References Vector< T >::insert(), and Vector< T >::mArray.
template<class T > T & Vector< T >::last () inline
References Vector< T >::mArray, and Vector< T >::mElementCount.
Referenced by IdGenerator::alloc(), ColladaExtension_animation_clip::ColladaExtension_animation_clip(), SceneTraversalState::getCurrentCullingVolume(), _SourceReader::initFromSource(), SimSetIterator::operator*(), Vector< LightInfo * >::operator[](), and ScopeTracker< NUM_DIMENSIONS, Object >::updateObject().
template<class T > const T & Vector< T >::last () const inline
References Vector< T >::mArray, and Vector< T >::mElementCount.
template<class T > U32 Vector< T >::memSize () const inline
References Vector< T >::capacity(), and T.
Referenced by Vector< LightInfo * >::operator[]().
template<class T > void Vector< T >::merge (const Vector< T > & p) inline
Appends the content of the vector to this one.
References constructInPlace(), Vector< T >::mArray, Vector< T >::mArraySize, Vector< T >::mElementCount, Vector< T >::resize(), Vector< T >::size(), and T.
Referenced by ForestCell::getChildren(), Vector< LightInfo * >::operator[](), MRandomDeck< T >::removeAll(), and ModuleDefinition::setDependencies().
template<class T> void Vector< T >::merge (const T * addr, U32 count) inline
Appends the content of the array to the vector.
Parameters
addr A pointer to the first item of the array to merge.
count The number of elements in the array to merge.
References constructInPlace(), Vector< T >::mArray, Vector< T >::mArraySize, Vector< T >::mElementCount, Vector< T >::resize(), and T.
template<class T> Vector< T > & Vector< T >::operator= (const Vector< T > & p) inline
References Vector< T >::construct(), Vector< T >::destroy(), Vector< T >::mArray, Vector< T >::mElementCount, and Vector< T >::resize().
Referenced by TSMesh::FreeableVector< Point4F >::operator=().
template<class T > T & Vector< T >::operator[] (U32 index) inline
References Vector< T >::mArray, and Vector< T >::mElementCount.
Referenced by VectorPtr< GuiFrameSetCtrl::FrameDetail * >::insert().
template<class T > const T & Vector< T >::operator[] (U32 index) const inline
References Vector< T >::mArray, and Vector< T >::mElementCount.
template<class T> T& Vector< T >::operator[] (S32 i) inline
Referenced by Vector< LightInfo * >::operator[]().
template<class T> const T& Vector< T >::operator[] (S32 i) const inline
Referenced by Vector< LightInfo * >::operator[]().
template<class T > void Vector< T >::pop_back () inline
References Vector< T >::decrement(), and Vector< T >::mElementCount.
Referenced by IdGenerator::alloc(), CodeStream::popFixScope(), and SceneTraversalState::popZone().
template<class T > void Vector< T >::pop_front () inline
References Vector< T >::erase(), and Vector< T >::mElementCount.
template<class T> void Vector< T >::push_back (const T & x) inline
References Vector< T >::increment(), Vector< T >::mArray, and Vector< T >::mElementCount.
Referenced by ScopeTracker< NUM_DIMENSIONS, Object >::_moveTrackingNode(), _TorqueThreadStaticReg::_TorqueThreadStaticReg(), WindowInputGenerator::addAcceleratorKey(), CodeStream::addBreakLine(), GuiTextListCtrl::addColumnOffset(), OggInputStream::addDecoder(), EventManager::addEventManager(), GuiEditCtrl::addGuide(), ThreadManager::addThread(), TSSkinMesh::addWeightForVert(), CodeStream::emitFix(), SimSet::findObjectByCallback(), SimSet::findObjectByType(), IdGenerator::free(), Entity::getComponents(), _SourceReader::initFromSource(), VectorPtr< GuiFrameSetCtrl::FrameDetail * >::insert(), SimpleQueryList::insertObject(), Interface< RenderComponentInterface >::Interface(), CodeStream::patch(), CodeStream::pushFixScope(), VideoFrameGrabber::pushNewBitmap(), SceneTraversalState::pushZone(), ModuleDefinition::setDependencies(), and TamlAssetDeclaredVisitor::visit().
template<class T> U32 Vector< T >::push_back_unique (const T & x) inline
References Vector< T >::find_next(), Vector< T >::increment(), Vector< T >::mArray, and Vector< T >::mElementCount.
template<class T> void Vector< T >::push_front (const T & x) inline
References Vector< T >::insert(), and Vector< T >::mArray.
Referenced by VectorPtr< GuiFrameSetCtrl::FrameDetail * >::insert().
template<class T> U32 Vector< T >::push_front_unique (const T & x) inline
References Vector< T >::find_next(), Vector< T >::insert(), and Vector< T >::mArray.
template<class T> bool Vector< T >::remove (const T & x) inline
Finds the first matching element and erases it.
Returns
Returns true if a match is found.
References Vector< T >::begin(), Vector< T >::end(), and Vector< T >::erase().
template<class T > void Vector< T >::reserve (U32 size) inline
References Vector< T >::mArraySize, Vector< T >::mElementCount, and Vector< T >::resize().
Referenced by Vector< LightInfo * >::operator[](), and Vector< T >::Vector().
template<class T > bool Vector< T >::resize (U32 ecount) inline protected
References Vector< T >::mArray, Vector< T >::mArraySize, Vector< T >::mElementCount, and T.
Referenced by Vector< T >::compact(), TSMesh::FreeableVector< Point4F >::free_memory(), Vector< T >::increment(), Vector< T >::insert(), Vector< T >::merge(), Vector< T >::operator=(), Vector< T >::reserve(), Vector< T >::setSize(), and Vector< T >::Vector().
template<class T > void Vector< T >::reverse () inline
References Vector< T >::mArray, and Vector< T >::size().
Referenced by Vector< LightInfo * >::operator[]().
template<class T > void Vector< T >::set (void * addr, U32 sz) inline
References Vector< T >::address(), dMemcpy(), Vector< T >::setSize(), and T.
template<class T > U32 Vector< T >::setSize (U32 size) inline
References Vector< T >::construct(), Vector< T >::destroy(), Vector< T >::mArraySize, Vector< T >::mElementCount, Vector< T >::resize(), and Vector< T >::size().
Referenced by PolyhedronVectorData::buildBox(), RuntimeClassRep< T >::consoleRegister(), Vector< LightInfo * >::operator[](), and Vector< T >::set().
template<class T > S32 Vector< T >::size () const inline
References Vector< T >::mElementCount.
Referenced by TerrCell::_isVertIndexEmpty(), _TorqueThreadStaticReg::_TorqueThreadStaticReg(), GuiEditCtrl::addGuide(), GuiFrameSetCtrl::columns(), RuntimeClassRep< T >::consoleRegister(), GuiImageList::Count(), ArrayObject::count(), Polytope::didIntersect(), Vector< T >::fill(), SFXDevice::getBufferCount(), Entity::getComponentCount(), Component::getComponentField(), Component::getComponentFieldCount(), UndoManager::getCompoundStackDepth(), AssetQuery::getCount(), FeatureSet::getCount(), ModuleDefinition::getDependencies(), ModuleDefinition::getDependencyCount(), FeatureMgr::getFeatureCount(), StateMachine::getField(), StateMachine::getFieldsCount(), OculusVRDevice::getHMDCount(), ForestCellBatch::getItemCount(), LangTable::getLangName(), MaterialList::getMaterialInst(), CompoundUndoAction::getNumChildren(), CollisionTrigger::getNumCollisionTriggeringObjects(), PolyhedronVectorData::getNumEdges(), GuiPopUpMenuCtrl::getNumEntries(), GuiPopUpMenuCtrlEx::getNumEntries(), GuiInspectorGroup::getNumFields(), GuiInspector::getNumInspectObjects(), LangTable::getNumLang(), CodeStream::getNumLineBreaks(), SFXSystem::getNumListeners(), SFXSource::getNumParameters(), PolyhedronVectorData::getNumPlanes(), SplCtrlPts::getNumPoints(), PolyhedronVectorData::getNumPoints(), GuiEditCtrl::getNumSelected(), LangFile::getNumStrings(), SFXSoundscapeManager::getNumTotalSoundscapes(), Trigger::getNumTriggeringObjects(), SceneZoneSpaceManager::getNumZoneSpaces(), GenericConstBufferLayout::getParameterCount(), GuiTreeViewCtrl::getSelectedItemsCount(), ForestSelectionTool::getSelectionCount(), GuiEditCtrl::getSelectionSize(), OculusVRDevice::getSensorCount(), StateMachine::getStateCount(), ThreadManager::getThreadById(), GuiShapeEdPreview::getThreadCount(), SceneTraversalState::getTraversalDepth(), AnimatedElementList< T >::getValue(), SFXDevice::getVoiceCount(), SceneTraversalState::getZoneIdFromStack(), SceneCullingState::getZoneState(), _SourceReader::initFromSource(), FindMatch::isFull(), LangFile::isLoaded(), StringBuffer::length(), Vector< T >::merge(), Zip::ZipArchive::numEntries(), IdGenerator::numIdsUsed(), FindMatch::numMatches(), HifiMoveList::onAdvanceObjects(), CodeStream::popFixScope(), CodeStream::pushFixScope(), WindowInputGenerator::removeAcceleratorKey(), WindowInputGenerator::removeAcceleratorKeys(), ThreadManager::removeThread(), Vector< T >::reverse(), GuiFrameSetCtrl::rows(), Selection< T >::scale(), Vector< T >::setSize(), MaterialList::size(), Vector< T >::sort(), ModuleDefinition::writeDependencies(), DDSFile::~DDSFile(), Interface< RenderComponentInterface >::~Interface(), and TSShapeLoader::Subshape::~Subshape().
template<class T > void Vector< T >::sort (compare_func f) inline
References Vector< T >::address(), Vector< T >::size(), and T.
Referenced by Vector< LightInfo * >::operator[]().
Member Data Documentation
template<class T> T* Vector< T >::mArray protected
Pointer to the Vector elements.
Referenced by Vector< T >::address(), Vector< T >::begin(), Vector< T >::construct(), Vector< T >::decrement(), Vector< T >::destroy(), Vector< T >::end(), Vector< T >::erase(), Vector< T >::erase_fast(), Vector< T >::fill(), Vector< T >::find_next(), Vector< T >::first(), Vector< T >::increment(), Vector< T >::insert(), Vector< T >::last(), Vector< T >::merge(), Vector< T >::operator=(), Vector< T >::operator[](), Vector< T >::push_back(), Vector< T >::push_back_unique(), Vector< T >::push_front(), Vector< T >::push_front_unique(), Vector< T >::resize(), Vector< T >::reverse(), Selection< T >::scale(), Vector< T >::Vector(), and Vector< T >::~Vector().
template<class T> U32 Vector< T >::mArraySize protected
Number of elements allocated for the Vector.
Referenced by Vector< T >::capacity(), Vector< T >::increment(), Vector< T >::insert(), Vector< T >::merge(), Vector< T >::reserve(), Vector< T >::resize(), Vector< T >::setSize(), and Vector< T >::Vector().
template<class T> U32 Vector< T >::mElementCount protected
Number of elements currently in the Vector.
Referenced by Vector< T >::back(), Vector< T >::clear(), Vector< T >::compact(), Vector< T >::construct(), Vector< T >::decrement(), Vector< T >::destroy(), Vector< T >::empty(), Vector< T >::end(), Vector< T >::erase(), Vector< T >::erase_fast(), Vector< T >::find_next(), Vector< T >::first(), Vector< T >::increment(), Vector< T >::insert(), Vector< T >::last(), Vector< T >::merge(), Vector< T >::operator=(), Vector< T >::operator[](), Vector< T >::pop_back(), Vector< T >::pop_front(), Vector< T >::push_back(), Vector< T >::push_back_unique(), Vector< T >::reserve(), Vector< T >::resize(), Vector< T >::setSize(), Vector< T >::size(), and Vector< T >::Vector().
Copyright © GarageGames, LLC. All Rights Reserved.