SFXVoice Class Reference
Main Modules Class List Namespace List Online
SFXVoice Class Reference abstract
The voice interface provides for playback of sound buffers and positioning of 3D sounds.
#include <sfx/sfxVoice.h>
Public Types
typedef void Parent
Public Types inherited from IPositionable< U32 >
typedef void Parent
typedef U32 PositionType
The type used to indicate positions.
Public Member Functions
virtual ~SFXVoice ()
The destructor.
const SFXFormat & getFormat () const
virtual U32 getPosition () const
Return the current playback position (in number of samples).
virtual SFXStatus getStatus () const
virtual bool isVirtual () const
Returns true if the voice is virtualized on the device.
virtual void pause ()
Pauses playback.
virtual void play (bool looping)
Starts playback from the current position.
virtual void setCone (F32 innerAngle, F32 outerAngle, F32 outerVolume)=0
Set sound cone of a 3D sound.
virtual void setMinMaxDistance (F32 min, F32 max)=0
Sets the minimum and maximum distances for 3d falloff.
virtual void setPitch (F32 pitch)=0
Sets the pitch scale.
virtual void setPosition (U32 sample)
Sets the playback position to the given sample count.
virtual void setPriority (F32 priority)
Set the priority of this voice.
virtual void setReverb (const SFXSoundReverbProperties &reverb)
Set the reverb properties for playback of this sound.
virtual void setRolloffFactor (F32 factor)
Set the distance attenuation rolloff factor. Support by device optional.
virtual void setTransform (const MatrixF &transform)=0
Sets the position and orientation for a 3d voice.
virtual void setVelocity (const VectorF &velocity)=0
Sets the velocity for a 3d voice.
virtual void setVolume (F32 volume)=0
Sets the volume.
virtual void stop ()
Stops playback and moves the position to the start.
Public Member Functions inherited from StrongRefBase
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Static Public Attributes
static Signal< void(SFXVoice *) > smVoiceCreatedSignal
static Signal< void(SFXVoice *) > smVoiceDestroyedSignal
Protected Member Functions
SFXVoice (SFXBuffer *buffer)
void _attachToBuffer ()
virtual void _onBufferStatusChange (SFXBuffer *buffer, SFXBuffer::Status newStatus)
Hooked up to SFXBuffer::mOnStatusChange of mBuffer.
Device Control Methods
virtual SFXStatus _status () const =0
Return the current playback status (playing, paused, or stopped).
virtual void _stop ()=0
Stop playback on the device.
virtual void _play ()=0
Start playback on the device.
virtual void _pause ()=0
Pause playback on the device.
virtual void _seek (U32 sample)=0
Set the playback cursor on the device.
virtual U32 _tell () const =0
Get the playback cursor on the device.
Streaming
The following methods are for streaming voices only.
void _resetStream (U32 sampleStartPos, bool triggerUpdate=true)
Reset streaming of the voice by cloning the current streaming source and letting the resulting stream start from sampleStartPos.
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Protected Attributes
WeakRefPtr< SFXBuffer > mBuffer
Sound data played back by the voice.
U32 mOffset
For streaming voices, this keeps track of play start offset after seeking.
volatile SFXStatus mStatus
Current playback status.
Protected Attributes inherited from StrongRefBase
U32 mRefCount
reference counter for StrongRefPtr objects
Detailed Description
The voice interface provides for playback of sound buffers and positioning of 3D sounds.
This abstract class is derived from in the different device layers to implement device-specific playback control.
The primary responsibility of this class is to mediate between the user requests (play(), stop(), pause(), setPosition()), the buffer (which may change state asynchronously), and the underlying device playback control (_play(), _stop(), _pause(), _seek()).
Member Typedef Documentation
typedef void SFXVoice::Parent
Constructor & Destructor Documentation
SFXVoice::SFXVoice (SFXBuffer * buffer) explicit protected
virtual SFXVoice::~SFXVoice () virtual
The destructor.
Member Function Documentation
void SFXVoice::_attachToBuffer () protected
virtual void SFXVoice::_onBufferStatusChange (SFXBuffer * buffer, SFXBuffer::Status newStatus) protected virtual
Hooked up to SFXBuffer::mOnStatusChange of mBuffer.
Note
Called on the SFX update thread.
virtual void SFXVoice::_pause () protected pure virtual
Pause playback on the device.
Note
Called from both the SFX update thread and the main thread.
Implemented in SFXXAudioVoice, SFXFMODVoice, SFXALVoice, SFXDSVoice, and SFXNullVoice.
virtual void SFXVoice::_play () protected pure virtual
Start playback on the device.
Note
Called from both the SFX update thread and the main thread.
Implemented in SFXXAudioVoice, SFXFMODVoice, SFXALVoice, SFXDSVoice, and SFXNullVoice.
void SFXVoice::_resetStream (U32 sampleStartPos, bool triggerUpdate = true) protected
Reset streaming of the voice by cloning the current streaming source and letting the resulting stream start from sampleStartPos.
virtual void SFXVoice::_seek (U32 sample) protected pure virtual
Set the playback cursor on the device.
Note
Only used for non-streaming voices.
Implemented in SFXXAudioVoice, SFXFMODVoice, SFXALVoice, SFXDSVoice, and SFXNullVoice.
virtual SFXStatus SFXVoice::_status () const protected pure virtual
Return the current playback status (playing, paused, or stopped).
Default status is stopped.
Implemented in SFXXAudioVoice, SFXFMODVoice, SFXALVoice, SFXDSVoice, and SFXNullVoice.
virtual void SFXVoice::_stop () protected pure virtual
Stop playback on the device.
Note
Called from both the SFX update thread and the main thread.
Implemented in SFXXAudioVoice, SFXFMODVoice, SFXALVoice, SFXDSVoice, and SFXNullVoice.
virtual U32 SFXVoice::_tell () const protected pure virtual
Get the playback cursor on the device.
When the voice is playing or paused, this method must return a valid sample position. When the voice is stopped, the result of this method is undefined.
For streaming voices that are looping, the sample position must be a total count of the number of samples played so far which thus includes the count of all cycles before the current one. For non-looping voices, this behavior is optional.
Note
This is called for both streaming and non-streaming voices.
Implemented in SFXXAudioVoice, SFXFMODVoice, SFXALVoice, SFXDSVoice, and SFXNullVoice.
Referenced by SFXInternal::SFXVoiceTimeSource::getPosition().
const SFXFormat& SFXVoice::getFormat () const inline
References SFXBuffer::getFormat().
virtual U32 SFXVoice::getPosition () const virtual
Return the current playback position (in number of samples).
Note
For looping sounds, this will return the position in the current cycle and not the total number of samples played so far.
Implements IPositionable< U32 >.
virtual SFXStatus SFXVoice::getStatus () const virtual
Returns
the current playback status.
Note
For streaming voices, the reaction to for the voice to update its status to SFXStatusStopped after the voice has stopped playing depends on the synchronization of the underlying device. If, for example, the underlying device uses periodic updates and doesn't have notifications, then a delay up to the total length of the period time may occur before the status changes. Note that in-between the actual playback stopping and the voice updating its status, the result of getPosition() is undefined.
Reimplemented in SFXNullVoice.
Referenced by SFXSound::isBlocked().
virtual bool SFXVoice::isVirtual () const inline virtual
Returns true if the voice is virtualized on the device.
Note
Always false on devices that do not support voice management.
Reimplemented in SFXFMODVoice.
virtual void SFXVoice::pause () virtual
Pauses playback.
virtual void SFXVoice::play (bool looping) virtual
Starts playback from the current position.
Reimplemented in SFXXAudioVoice, SFXFMODVoice, SFXALVoice, SFXDSVoice, and SFXNullVoice.
virtual void SFXVoice::setCone (F32 innerAngle, F32 outerAngle, F32 outerVolume) pure virtual
Set sound cone of a 3D sound.
Parameters
innerAngle Inner cone angle in degrees.
outerAngle Outer cone angle in degrees.
outerVolume Outer volume factor.
Implemented in SFXXAudioVoice, SFXFMODVoice, SFXALVoice, SFXDSVoice, and SFXNullVoice.
virtual void SFXVoice::setMinMaxDistance (F32 min, F32 max) pure virtual
Sets the minimum and maximum distances for 3d falloff.
Implemented in SFXXAudioVoice, SFXFMODVoice, SFXALVoice, SFXDSVoice, and SFXNullVoice.
virtual void SFXVoice::setPitch (F32 pitch) pure virtual
Sets the pitch scale.
Implemented in SFXXAudioVoice, SFXFMODVoice, SFXALVoice, SFXDSVoice, and SFXNullVoice.
virtual void SFXVoice::setPosition (U32 sample) virtual
Sets the playback position to the given sample count.
Parameters
sample Offset in number of samples. This is allowed to use an offset accumulated from multiple cycles. Each cycle will wrap around back to the beginning of the buffer.
Implements IPositionable< U32 >.
Reimplemented in SFXNullVoice.
virtual void SFXVoice::setPriority (F32 priority) inline virtual
Set the priority of this voice.
Default 1.0.
Note
Has no effect on devices that do not support voice management.
Reimplemented in SFXFMODVoice.
virtual void SFXVoice::setReverb (const SFXSoundReverbProperties & reverb) inline virtual
Set the reverb properties for playback of this sound.
Note
Has no effect on devices that do not support reverb.
Reimplemented in SFXFMODVoice.
virtual void SFXVoice::setRolloffFactor (F32 factor) inline virtual
Set the distance attenuation rolloff factor. Support by device optional.
Reimplemented in SFXALVoice.
virtual void SFXVoice::setTransform (const MatrixF & transform) pure virtual
Sets the position and orientation for a 3d voice.
Implemented in SFXXAudioVoice, SFXFMODVoice, SFXALVoice, SFXDSVoice, and SFXNullVoice.
virtual void SFXVoice::setVelocity (const VectorF & velocity) pure virtual
Sets the velocity for a 3d voice.
Implemented in SFXXAudioVoice, SFXFMODVoice, SFXALVoice, SFXDSVoice, and SFXNullVoice.
virtual void SFXVoice::setVolume (F32 volume) pure virtual
Sets the volume.
Implemented in SFXXAudioVoice, SFXFMODVoice, SFXALVoice, SFXDSVoice, and SFXNullVoice.
virtual void SFXVoice::stop () virtual
Stops playback and moves the position to the start.
Member Data Documentation
WeakRefPtr< SFXBuffer > SFXVoice::mBuffer protected
Sound data played back by the voice.
Referenced by SFXDSVoice::_getBuffer(), SFXALVoice::_getBuffer(), SFXFMODVoice::_getBuffer(), SFXXAudioVoice::_getBuffer(), and SFXInternal::SFXVoiceTimeSource::getPosition().
U32 SFXVoice::mOffset protected
For streaming voices, this keeps track of play start offset after seeking.
Expressed in number of samples.
volatile SFXStatus SFXVoice::mStatus mutable protected
Current playback status.
Note
This is maintained on both the sound update thread as well as the main thread.
Signal< void(SFXVoice*) > SFXVoice::smVoiceCreatedSignal static
Signal< void(SFXVoice*) > SFXVoice::smVoiceDestroyedSignal static
Copyright © GarageGames, LLC. All Rights Reserved.