GFXD3D9TextureObject Class Reference
Main Modules Class List Namespace List Online
GFXD3D9TextureObject Class Reference
#include <gfx/D3D9/gfxD3D9TextureObject.h>
Public Member Functions
GFXD3D9TextureObject (GFXDevice *d, GFXTextureProfile *profile)
~GFXD3D9TextureObject ()
virtual bool copyToBmp (GBitmap *bmp)
IDirect3DTexture9 * get2DTex ()
IDirect3DTexture9 ** get2DTexPtr ()
IDirect3DVolumeTexture9 * get3DTex ()
IDirect3DVolumeTexture9 ** get3DTexPtr ()
IDirect3DSurface9 * getSurface ()
IDirect3DSurface9 ** getSurfacePtr ()
IDirect3DBaseTexture9 * getTex ()
virtual GFXLockedRect * lock (U32 mipLevel=0, RectI *inRect=NULL)
Acquire a lock on part of the texture.
virtual void pureVirtualCrash ()
void release ()
void resurrect ()
When called the resource should restore all device sensitive information destroyed by zombify()
virtual void unlock (U32 mipLevel=0)
Releases a lock previously acquired.
void zombify ()
When called the resource should destroy all device sensitive information (e.g. D3D resources in D3DPOOL_DEFAULT.
Public Member Functions inherited from GFXTextureObject
GFXTextureObject (GFXDevice *aDevice, GFXTextureProfile *profile)
virtual ~GFXTextureObject ()
virtual const String describeSelf () const
The resource should put a description of itself (number of vertices, size/width of texture, etc.) in buffer.
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
bool dumpToDisk (const String &bmType, const String &path)
Debug helper function for writing the texture to disk.
GBitmap * getBitmap ()
U32 getBitmapDepth () const
U32 getBitmapHeight () const
U32 getBitmapWidth () const
DDSFile * getDDS ()
U32 getDepth () const
U32 getEstimatedSizeInBytes () const
Returns the estimated video memory usage in bytes including mipmaps.
GFXFormat getFormat () const
U32 getFormatByteSize () const
U32 getHeight () const
virtual F32 getMaxUCoord () const
virtual F32 getMaxVCoord () const
U32 getMipLevels () const
const String & getPath () const
Returns the file path to the texture if it was loaded from disk.
const Point3I & getSize () const
U32 getWidth () const
bool isRenderTarget () const
Returns true if this texture is a render target.
virtual void kill ()
Public Member Functions inherited from StrongRefBase
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Public Member Functions inherited from GFXResource
GFXResource ()
virtual ~GFXResource ()
void clearFlag ()
GFXResource * getNextResource () const
GFXDevice * getOwningDevice () const
GFXResource * getPrevResource () const
bool isFlagged ()
void registerResourceWithDevice (GFXDevice *device)
Registers this resource with the given device.
void setFlag ()
Public Attributes
bool isManaged
Public Attributes inherited from GFXTextureObject
S32 mAntialiasLevel
GBitmap * mBitmap
GBitmap we are backed by.
Point3I mBitmapSize
DDSFile * mDDS
DDSFile we're backed by.
bool mDead
String mDebugCreationPath
String mDebugDescription
GFXTextureObject * mDebugNext
GFXTextureObject * mDebugPrev
U32 mDeleteTime
The time at which all references to this texture were removed.
GFXDevice * mDevice
The device this texture belongs to.
GFXFormat mFormat
GFXTextureObject * mHashNext
The siblings in the cache hash table.
bool mHasTransparency
U32 mMipLevels
GFXTextureObject * mNext
The next texture in the linked list.
String mPath
The path to the texture file if the content was loaded from a resource.
GFXTextureObject * mPrev
The previous texture in the linked list.
GFXTextureProfile * mProfile
String mTextureLookupName
This is the file name or other unique string used to hash this texture object.
Point3I mTextureSize
Protected Attributes
IDirect3DSurface9 * mD3DSurface
IDirect3DBaseTexture9 * mD3DTexture
bool mLocked
D3DLOCKED_RECT mLockRect
GFXTexHandle mLockTex
Protected Attributes inherited from StrongRefBase
U32 mRefCount
reference counter for StrongRefPtr objects
Static Protected Attributes
static U32 mTexCount
Additional Inherited Members
Static Public Member Functions inherited from GFXTextureObject
static U32 dumpActiveTOs ()
Static Public Attributes inherited from GFXTextureObject
static U32 smActiveTOCount
static GFXTextureObject * smHead
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Constructor & Destructor Documentation
GFXD3D9TextureObject::GFXD3D9TextureObject (GFXDevice * d, GFXTextureProfile * profile)
GFXD3D9TextureObject::~GFXD3D9TextureObject ()
Member Function Documentation
virtual bool GFXD3D9TextureObject::copyToBmp (GBitmap * bmp) virtual
Implements GFXTextureObject.
IDirect3DTexture9* GFXD3D9TextureObject::get2DTex () inline
References mD3DTexture.
IDirect3DTexture9** GFXD3D9TextureObject::get2DTexPtr () inline
References mD3DTexture.
IDirect3DVolumeTexture9* GFXD3D9TextureObject::get3DTex () inline
References mD3DTexture.
IDirect3DVolumeTexture9** GFXD3D9TextureObject::get3DTexPtr () inline
References mD3DTexture, and release().
IDirect3DSurface9* GFXD3D9TextureObject::getSurface () inline
References mD3DSurface.
IDirect3DSurface9** GFXD3D9TextureObject::getSurfacePtr () inline
References mD3DSurface, resurrect(), and zombify().
IDirect3DBaseTexture9* GFXD3D9TextureObject::getTex () inline
References mD3DTexture.
virtual GFXLockedRect* GFXD3D9TextureObject::lock (U32 mipLevel = 0, RectI * inRect = NULL) virtual
Acquire a lock on part of the texture.
The GFXLockedRect returned is managed by the GFXTextureObject and does not need to be freed.
Implements GFXTextureObject.
virtual void GFXD3D9TextureObject::pureVirtualCrash () inline virtual
Implements GFXTextureObject.
void GFXD3D9TextureObject::release ()
Referenced by get3DTexPtr().
void GFXD3D9TextureObject::resurrect () virtual
When called the resource should restore all device sensitive information destroyed by zombify()
Implements GFXResource.
Referenced by getSurfacePtr().
virtual void GFXD3D9TextureObject::unlock (U32 mipLevel = 0) virtual
Releases a lock previously acquired.
Note that the mipLevel parameter must match the corresponding lock!
Implements GFXTextureObject.
void GFXD3D9TextureObject::zombify () virtual
When called the resource should destroy all device sensitive information (e.g. D3D resources in D3DPOOL_DEFAULT.
Implements GFXResource.
Referenced by getSurfacePtr().
Member Data Documentation
bool GFXD3D9TextureObject::isManaged
IDirect3DSurface9* GFXD3D9TextureObject::mD3DSurface protected
Referenced by getSurface(), and getSurfacePtr().
IDirect3DBaseTexture9* GFXD3D9TextureObject::mD3DTexture protected
Referenced by get2DTex(), get2DTexPtr(), get3DTex(), get3DTexPtr(), and getTex().
bool GFXD3D9TextureObject::mLocked protected
D3DLOCKED_RECT GFXD3D9TextureObject::mLockRect protected
GFXTexHandle GFXD3D9TextureObject::mLockTex protected
U32 GFXD3D9TextureObject::mTexCount static protected
Copyright © GarageGames, LLC. All Rights Reserved.