MatStateHint Class Reference
Main Modules Class List Namespace List Online
MatStateHint Class Reference
A simple object for generating and comparing string based hints used for sorting and identifying materials uniquely by its shaders and states.
#include <materials/matStateHint.h>
Public Member Functions
MatStateHint ()
Constructor.
MatStateHint (const String &state)
Constructor for building special hints.
void clear ()
Clears the hint.
void init (const ProcessedMaterial *mat)
Initialize the state hint from a ProcessMaterial.
operator U32 () const
Returns a 32bit hash key used for sorting by material state.
bool operator!= (const MatStateHint &hint) const
Fast comparision of state for inequality.
bool operator== (const MatStateHint &hint) const
Fast comparision of state for equality.
Static Public Attributes
static const MatStateHint Default
A default state hint.
Protected Attributes
String mState
An interned string of the combined material shader and state info for evert pass of the processed material.
Detailed Description
A simple object for generating and comparing string based hints used for sorting and identifying materials uniquely by its shaders and states.
Constructor & Destructor Documentation
MatStateHint::MatStateHint () inline
Constructor.
MatStateHint::MatStateHint (const String & state) inline
Constructor for building special hints.
References init().
Member Function Documentation
void MatStateHint::clear (void) inline
Clears the hint.
References String::clear(), and mState.
void MatStateHint::init (const ProcessedMaterial * mat)
Initialize the state hint from a ProcessMaterial.
This assumes that the ProcessedMaterial has properly initialized its passes to describe the material uniquely.
Referenced by MatStateHint().
MatStateHint::operator U32 () const inline
Returns a 32bit hash key used for sorting by material state.
References String::getHashCaseSensitive(), and mState.
bool MatStateHint::operator!= (const MatStateHint & hint) const inline
Fast comparision of state for inequality.
References mState.
bool MatStateHint::operator== (const MatStateHint & hint) const inline
Fast comparision of state for equality.
References mState.
Member Data Documentation
const MatStateHint MatStateHint::Default static
A default state hint.
String MatStateHint::mState protected
An interned string of the combined material shader and state info for evert pass of the processed material.
Referenced by clear(), operator U32(), operator!=(), and operator==().
Copyright © GarageGames, LLC. All Rights Reserved.