MatrixSet Class Reference
Main Modules Class List Namespace List Online
MatrixSet Class Reference
#include <math/util/matrixSet.h>
Public Member Functions
MatrixSet ()
const MatrixF & getCameraToObject () const
const MatrixF & getCameraToScreen () const
const MatrixF & getCameraToWorld () const
const MatrixF & getObjectToCamera () const
const MatrixF & getObjectToWorld () const
const MatrixF & getWorldToCamera () const
const MatrixF & getWorldToObject () const
const MatrixF & getWorldToScreen () const
const MatrixF & getWorldViewProjection () const
void restoreSceneViewProjection ()
void setProjection (const MatrixF &projection)
void setSceneProjection (const MatrixF &projection)
void setSceneView (const MatrixF &view)
void setView (const MatrixF &view)
void setWorld (const MatrixF &world)
Constructor & Destructor Documentation
MatrixSet::MatrixSet ()
Member Function Documentation
const MatrixF& MatrixSet::getCameraToObject () const inline
const MatrixF& MatrixSet::getCameraToScreen () const inline
const MatrixF& MatrixSet::getCameraToWorld () const inline
const MatrixF& MatrixSet::getObjectToCamera () const inline
const MatrixF& MatrixSet::getObjectToWorld () const inline
const MatrixF& MatrixSet::getWorldToCamera () const inline
const MatrixF& MatrixSet::getWorldToObject () const inline
const MatrixF& MatrixSet::getWorldToScreen () const inline
const MatrixF& MatrixSet::getWorldViewProjection () const inline
void MatrixSet::restoreSceneViewProjection () inline
References dALIGN_END, setProjection(), and setView().
void MatrixSet::setProjection (const MatrixF & projection) inline
Referenced by restoreSceneViewProjection(), and setSceneProjection().
void MatrixSet::setSceneProjection (const MatrixF & projection) inline
References setProjection().
void MatrixSet::setSceneView (const MatrixF & view) inline
References setView().
void MatrixSet::setView (const MatrixF & view) inline
Referenced by restoreSceneViewProjection(), and setSceneView().
void MatrixSet::setWorld (const MatrixF & world) inline
Copyright © GarageGames, LLC. All Rights Reserved.