PhysicsWorld Class Reference
Main Modules Class List Namespace List Online
PhysicsWorld Class Reference abstract
#include <T3D/physics/physicsWorld.h>
Public Types
enum BodyType {
BT_Static = BIT(0),
BT_Dynamic = BIT(1),
BT_Player = BIT(2),
BT_All = BT_Static | BT_Dynamic | BT_Player
}
Public Member Functions
PhysicsWorld ()
The constructor.
virtual ~PhysicsWorld ()
The destructor.
virtual bool castRay (const Point3F &startPnt, const Point3F &endPnt, RayInfo *ri, const Point3F &impulse)=0
An abstract way to raycast into any type of PhysicsWorld, in a way that mirrors a Torque-style raycast.
virtual PhysicsBody * castRay (const Point3F &start, const Point3F &end, U32 bodyTypes=BT_All)=0
virtual void destroyWorld ()=0
Tears down the physics world destroying any existing bodies, joints, and controllers.
virtual void explosion (const Point3F &pos, F32 radius, F32 forceMagnitude)=0
const Point3F & getGravity () const
Returns the active gravity force.
Signal< void()> & getStaticChangedSignal ()
Signal< void()> & getUpdateSignal ()
virtual bool initWorld (bool isServer, ProcessList *processList)=0
Prepare the physics world for use.
virtual bool isEnabled () const =0
Returns true if the physics world is active and simulating.
virtual void onDebugDraw (const SceneRenderState *state)=0
Overloaded to do debug drawing.
virtual void reset ()=0
Static Public Attributes
static U32 smPhysicsMaxSubSteps
static F32 smPhysicsStepTime
Physics timing.
Protected Attributes
Point3F mGravity
The current gravity force.
Signal< void()> mStaticChangedSignal
Signal< void()> mUpdateSignal
Member Enumeration Documentation
enum PhysicsWorld::BodyType
Enumerator
BT_Static
BT_Dynamic
BT_Player
BT_All
Constructor & Destructor Documentation
PhysicsWorld::PhysicsWorld ()
The constructor.
virtual PhysicsWorld::~PhysicsWorld () inline virtual
The destructor.
Member Function Documentation
virtual bool PhysicsWorld::castRay (const Point3F & startPnt, const Point3F & endPnt, RayInfo * ri, const Point3F & impulse) pure virtual
An abstract way to raycast into any type of PhysicsWorld, in a way that mirrors a Torque-style raycast.
This method is not fully developed or very sophisticated. For example, there is no system of collision groups or raycast masks, which could be very complex to write in a PhysicsPlugin-Abstract way...
Implemented in Px3World, and BtWorld.
Referenced by getGravity().
virtual PhysicsBody* PhysicsWorld::castRay (const Point3F & start, const Point3F & end, U32 bodyTypes = BT_All) pure virtual
Implemented in Px3World, and BtWorld.
virtual void PhysicsWorld::destroyWorld () pure virtual
Tears down the physics world destroying any existing bodies, joints, and controllers.
Implemented in Px3World, and BtWorld.
Referenced by getStaticChangedSignal().
virtual void PhysicsWorld::explosion (const Point3F & pos, F32 radius, F32 forceMagnitude) pure virtual
Implemented in Px3World, and BtWorld.
const Point3F& PhysicsWorld::getGravity () const inline
Returns the active gravity force.
References castRay(), and mGravity.
Signal<void()>& PhysicsWorld::getStaticChangedSignal () inline
References destroyWorld(), initWorld(), isEnabled(), mStaticChangedSignal, onDebugDraw(), and reset().
Signal<void()>& PhysicsWorld::getUpdateSignal () inline
References mUpdateSignal.
virtual bool PhysicsWorld::initWorld (bool isServer, ProcessList * processList) pure virtual
Prepare the physics world for use.
Implemented in Px3World, and BtWorld.
Referenced by getStaticChangedSignal().
virtual bool PhysicsWorld::isEnabled () const pure virtual
Returns true if the physics world is active and simulating.
Implemented in Px3World, and BtWorld.
Referenced by getStaticChangedSignal().
virtual void PhysicsWorld::onDebugDraw (const SceneRenderState * state) pure virtual
Overloaded to do debug drawing.
It is assumed the GFX state is setup prior to this call for rendering in world space.
Implemented in Px3World, and BtWorld.
Referenced by getStaticChangedSignal().
virtual void PhysicsWorld::reset () pure virtual
Implemented in Px3World, and BtWorld.
Referenced by getStaticChangedSignal().
Member Data Documentation
Point3F PhysicsWorld::mGravity protected
The current gravity force.
Referenced by getGravity().
Signal<void()> PhysicsWorld::mStaticChangedSignal protected
Referenced by getStaticChangedSignal().
Signal<void()> PhysicsWorld::mUpdateSignal protected
Referenced by getUpdateSignal().
U32 PhysicsWorld::smPhysicsMaxSubSteps static
F32 PhysicsWorld::smPhysicsStepTime static
Physics timing.
Copyright © GarageGames, LLC. All Rights Reserved.