Px3World Class Reference
Main Modules Class List Namespace List Online
Px3World Class Reference
#include <T3D/physics/physx3/px3World.h>
Public Member Functions
Px3World ()
virtual ~Px3World ()
virtual bool castRay (const Point3F &startPnt, const Point3F &endPnt, RayInfo *ri, const Point3F &impulse)
An abstract way to raycast into any type of PhysicsWorld, in a way that mirrors a Torque-style raycast.
virtual PhysicsBody * castRay (const Point3F &start, const Point3F &end, U32 bodyTypes=BT_All)
physx::PxController * createController (physx::PxControllerDesc &desc)
virtual void destroyWorld ()
Tears down the physics world destroying any existing bodies, joints, and controllers.
virtual void explosion (const Point3F &pos, F32 radius, F32 forceMagnitude)
const F32 getEditorTimeScale () const
void getPhysicsResults ()
physx::PxScene * getScene ()
U32 getTick ()
virtual bool initWorld (bool isServer, ProcessList *processList)
Prepare the physics world for use.
virtual bool isEnabled () const
Returns true if the physics world is active and simulating.
bool isServer ()
void lockScene ()
virtual void onDebugDraw (const SceneRenderState *state)
Overloaded to do debug drawing.
void releaseWriteLock ()
virtual void reset ()
void setEditorTimeScale (F32 timeScale)
void setEnabled (bool enabled)
void tickPhysics (U32 elapsedMs)
void unlockScene ()
Public Member Functions inherited from PhysicsWorld
PhysicsWorld ()
The constructor.
virtual ~PhysicsWorld ()
The destructor.
const Point3F & getGravity () const
Returns the active gravity force.
Signal< void()> & getStaticChangedSignal ()
Signal< void()> & getUpdateSignal ()
Static Public Member Functions
static physx::PxCooking * getCooking ()
static void lockScenes ()
static void releaseWriteLocks ()
static bool restartSDK (bool destroyOnly=false, Px3World *clientWorld=NULL, Px3World *serverWorld=NULL)
static void unlockScenes ()
Protected Member Functions
bool _simulate (const F32 dt)
Protected Attributes
F32 mAccumulator
physx::PxControllerManager * mControllerManager
F32 mEditorTimeScale
bool mErrorReport
bool mIsEnabled
bool mIsSceneLocked
bool mIsServer
bool mIsSimulating
ProcessList * mProcessList
physx::PxRenderBuffer * mRenderBuffer
physx::PxScene * mScene
U32 mTickCount
Protected Attributes inherited from PhysicsWorld
Point3F mGravity
The current gravity force.
Signal< void()> mStaticChangedSignal
Signal< void()> mUpdateSignal
Static Protected Attributes
static physx::PxCooking * smCooking
static physx::PxDefaultCpuDispatcher * smCpuDispatcher
static Px3ConsoleStream * smErrorCallback
static physx::PxFoundation * smFoundation
static physx::PxDefaultAllocator smMemoryAlloc
static physx::PxProfileZoneManager * smProfileZoneManager
static physx::PxVisualDebuggerConnection * smPvdConnection
Additional Inherited Members
Public Types inherited from PhysicsWorld
enum BodyType {
BT_Static = BIT(0),
BT_Dynamic = BIT(1),
BT_Player = BIT(2),
BT_All = BT_Static | BT_Dynamic | BT_Player
}
Static Public Attributes inherited from PhysicsWorld
static U32 smPhysicsMaxSubSteps
static F32 smPhysicsStepTime
Physics timing.
Constructor & Destructor Documentation
Px3World::Px3World ()
virtual Px3World::~Px3World () virtual
Member Function Documentation
bool Px3World::_simulate (const F32 dt) protected
virtual bool Px3World::castRay (const Point3F & startPnt, const Point3F & endPnt, RayInfo * ri, const Point3F & impulse) virtual
An abstract way to raycast into any type of PhysicsWorld, in a way that mirrors a Torque-style raycast.
This method is not fully developed or very sophisticated. For example, there is no system of collision groups or raycast masks, which could be very complex to write in a PhysicsPlugin-Abstract way...
Implements PhysicsWorld.
Referenced by reset().
virtual PhysicsBody* Px3World::castRay (const Point3F & start, const Point3F & end, U32 bodyTypes = BT_All) virtual
Implements PhysicsWorld.
physx::PxController* Px3World::createController (physx::PxControllerDesc & desc)
Referenced by isServer().
virtual void Px3World::destroyWorld () virtual
Tears down the physics world destroying any existing bodies, joints, and controllers.
Implements PhysicsWorld.
virtual void Px3World::explosion (const Point3F & pos, F32 radius, F32 forceMagnitude) virtual
Implements PhysicsWorld.
Referenced by reset().
static physx::PxCooking* Px3World::getCooking () static
Referenced by isServer().
const F32 Px3World::getEditorTimeScale () const inline
References mEditorTimeScale, and releaseWriteLock().
void Px3World::getPhysicsResults ()
Referenced by getTick().
physx::PxScene* Px3World::getScene () inline
References mScene, and setEnabled().
U32 Px3World::getTick () inline
References getPhysicsResults(), mTickCount, and tickPhysics().
virtual bool Px3World::initWorld (bool isServer, ProcessList * processList) virtual
Prepare the physics world for use.
Implements PhysicsWorld.
virtual bool Px3World::isEnabled () const inline virtual
Returns true if the physics world is active and simulating.
Implements PhysicsWorld.
References mIsEnabled.
bool Px3World::isServer () inline
References createController(), getCooking(), lockScene(), lockScenes(), mIsServer, releaseWriteLocks(), restartSDK(), unlockScene(), and unlockScenes().
void Px3World::lockScene ()
Referenced by isServer().
static void Px3World::lockScenes () static
Referenced by isServer().
virtual void Px3World::onDebugDraw (const SceneRenderState * state) virtual
Overloaded to do debug drawing.
It is assumed the GFX state is setup prior to this call for rendering in world space.
Implements PhysicsWorld.
void Px3World::releaseWriteLock ()
Referenced by getEditorTimeScale().
static void Px3World::releaseWriteLocks () static
Referenced by isServer().
virtual void Px3World::reset (void) inline virtual
Implements PhysicsWorld.
References PhysicsWorld::BT_All, castRay(), and explosion().
static bool Px3World::restartSDK (bool destroyOnly = false, Px3World * clientWorld = NULL, Px3World * serverWorld = NULL) static
Referenced by isServer().
void Px3World::setEditorTimeScale (F32 timeScale) inline
void Px3World::setEnabled (bool enabled)
Referenced by getScene().
void Px3World::tickPhysics (U32 elapsedMs)
Referenced by getTick().
void Px3World::unlockScene ()
Referenced by isServer().
static void Px3World::unlockScenes () static
Referenced by isServer().
Member Data Documentation
F32 Px3World::mAccumulator protected
physx::PxControllerManager* Px3World::mControllerManager protected
F32 Px3World::mEditorTimeScale protected
Referenced by getEditorTimeScale().
bool Px3World::mErrorReport protected
bool Px3World::mIsEnabled protected
Referenced by isEnabled().
bool Px3World::mIsSceneLocked protected
bool Px3World::mIsServer protected
Referenced by isServer().
bool Px3World::mIsSimulating protected
ProcessList* Px3World::mProcessList protected
physx::PxRenderBuffer* Px3World::mRenderBuffer protected
physx::PxScene* Px3World::mScene protected
Referenced by getScene().
U32 Px3World::mTickCount protected
Referenced by getTick().
physx::PxCooking* Px3World::smCooking static protected
physx::PxDefaultCpuDispatcher* Px3World::smCpuDispatcher static protected
Px3ConsoleStream* Px3World::smErrorCallback static protected
physx::PxFoundation* Px3World::smFoundation static protected
physx::PxDefaultAllocator Px3World::smMemoryAlloc static protected
physx::PxProfileZoneManager* Px3World::smProfileZoneManager static protected
physx::PxVisualDebuggerConnection* Px3World::smPvdConnection static protected
Copyright © GarageGames, LLC. All Rights Reserved.