SFXDSVoice Class Reference
Main Modules Class List Namespace List Online
SFXDSVoice Class Reference
#include <sfx/dsound/sfxDSVoice.h>
Public Member Functions
virtual ~SFXDSVoice ()
void play (bool looping)
Starts playback from the current position.
void setCone (F32 innerAngle, F32 outerAngle, F32 outerVolume)
Set sound cone of a 3D sound.
void setMinMaxDistance (F32 min, F32 max)
Sets the minimum and maximum distances for 3d falloff.
void setPitch (F32 pitch)
Sets the pitch scale.
void setTransform (const MatrixF &transform)
Sets the position and orientation for a 3d voice.
void setVelocity (const VectorF &velocity)
Sets the velocity for a 3d voice.
void setVolume (F32 volume)
Sets the volume.
Public Member Functions inherited from SFXVoice
virtual ~SFXVoice ()
The destructor.
const SFXFormat & getFormat () const
virtual U32 getPosition () const
Return the current playback position (in number of samples).
virtual SFXStatus getStatus () const
virtual bool isVirtual () const
Returns true if the voice is virtualized on the device.
virtual void pause ()
Pauses playback.
virtual void setPosition (U32 sample)
Sets the playback position to the given sample count.
virtual void setPriority (F32 priority)
Set the priority of this voice.
virtual void setReverb (const SFXSoundReverbProperties &reverb)
Set the reverb properties for playback of this sound.
virtual void setRolloffFactor (F32 factor)
Set the distance attenuation rolloff factor. Support by device optional.
virtual void stop ()
Stops playback and moves the position to the start.
Public Member Functions inherited from StrongRefBase
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Static Public Member Functions
static SFXDSVoice * create (SFXDSDevice *device, SFXDSBuffer *buffer)
Protected Member Functions
SFXDSVoice (SFXDSDevice *device, SFXDSBuffer *buffer, IDirectSoundBuffer8 *dsBuffer, IDirectSound3DBuffer8 *dsBuffer3d)
SFXDSBuffer * _getBuffer () const
virtual void _pause ()
Pause playback on the device.
virtual void _play ()
Start playback on the device.
virtual void _seek (U32 sample)
Set the playback cursor on the device.
virtual SFXStatus _status () const
Return the current playback status (playing, paused, or stopped).
virtual void _stop ()
Stop playback on the device.
virtual U32 _tell () const
Get the playback cursor on the device.
Protected Member Functions inherited from SFXVoice
SFXVoice (SFXBuffer *buffer)
void _attachToBuffer ()
virtual void _onBufferStatusChange (SFXBuffer *buffer, SFXBuffer::Status newStatus)
Hooked up to SFXBuffer::mOnStatusChange of mBuffer.
void _resetStream (U32 sampleStartPos, bool triggerUpdate=true)
Reset streaming of the voice by cloning the current streaming source and letting the resulting stream start from sampleStartPos.
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Static Protected Member Functions
static LONG _linearToLogVolume (F32 linVolume)
Helper for converting floating point linear volume to a logrithmic integer volume for dsound.
Protected Attributes
SFXDSDevice * mDevice
The device used to commit deferred settings.
IDirectSoundBuffer8 * mDSBuffer
IDirectSound3DBuffer8 * mDSBuffer3D
bool mIsLooping
Protected Attributes inherited from SFXVoice
WeakRefPtr< SFXBuffer > mBuffer
Sound data played back by the voice.
U32 mOffset
For streaming voices, this keeps track of play start offset after seeking.
volatile SFXStatus mStatus
Current playback status.
Protected Attributes inherited from StrongRefBase
U32 mRefCount
reference counter for StrongRefPtr objects
Additional Inherited Members
Public Types inherited from SFXVoice
typedef void Parent
Public Types inherited from IPositionable< U32 >
typedef void Parent
typedef U32 PositionType
The type used to indicate positions.
Static Public Attributes inherited from SFXVoice
static Signal< void(SFXVoice *) > smVoiceCreatedSignal
static Signal< void(SFXVoice *) > smVoiceDestroyedSignal
Constructor & Destructor Documentation
SFXDSVoice::SFXDSVoice (SFXDSDevice * device, SFXDSBuffer * buffer, IDirectSoundBuffer8 * dsBuffer, IDirectSound3DBuffer8 * dsBuffer3d) protected
virtual SFXDSVoice::~SFXDSVoice () virtual
Referenced by _getBuffer().
Member Function Documentation
SFXDSBuffer* SFXDSVoice::_getBuffer () const inline protected
References _linearToLogVolume(), _pause(), _play(), _seek(), _status(), _stop(), _tell(), create(), WeakRefPtr< T >::getPointer(), SFXVoice::mBuffer, play(), setCone(), setMinMaxDistance(), setPitch(), setTransform(), setVelocity(), setVolume(), and ~SFXDSVoice().
static LONG SFXDSVoice::_linearToLogVolume (F32 linVolume) static protected
Helper for converting floating point linear volume to a logrithmic integer volume for dsound.
Referenced by _getBuffer().
virtual void SFXDSVoice::_pause () protected virtual
Pause playback on the device.
Note
Called from both the SFX update thread and the main thread.
Implements SFXVoice.
Referenced by _getBuffer().
virtual void SFXDSVoice::_play () protected virtual
Start playback on the device.
Note
Called from both the SFX update thread and the main thread.
Implements SFXVoice.
Referenced by _getBuffer().
virtual void SFXDSVoice::_seek (U32 sample) protected virtual
Set the playback cursor on the device.
Note
Only used for non-streaming voices.
Implements SFXVoice.
Referenced by _getBuffer().
virtual SFXStatus SFXDSVoice::_status () const protected virtual
Return the current playback status (playing, paused, or stopped).
Default status is stopped.
Implements SFXVoice.
Referenced by _getBuffer().
virtual void SFXDSVoice::_stop () protected virtual
Stop playback on the device.
Note
Called from both the SFX update thread and the main thread.
Implements SFXVoice.
Referenced by _getBuffer().
virtual U32 SFXDSVoice::_tell () const protected virtual
Get the playback cursor on the device.
When the voice is playing or paused, this method must return a valid sample position. When the voice is stopped, the result of this method is undefined.
For streaming voices that are looping, the sample position must be a total count of the number of samples played so far which thus includes the count of all cycles before the current one. For non-looping voices, this behavior is optional.
Note
This is called for both streaming and non-streaming voices.
Implements SFXVoice.
Referenced by _getBuffer().
static SFXDSVoice* SFXDSVoice::create (SFXDSDevice * device, SFXDSBuffer * buffer) static
Referenced by _getBuffer().
void SFXDSVoice::play (bool looping) virtual
Starts playback from the current position.
Reimplemented from SFXVoice.
Referenced by _getBuffer().
void SFXDSVoice::setCone (F32 innerAngle, F32 outerAngle, F32 outerVolume) virtual
Set sound cone of a 3D sound.
Parameters
innerAngle Inner cone angle in degrees.
outerAngle Outer cone angle in degrees.
outerVolume Outer volume factor.
Implements SFXVoice.
Referenced by _getBuffer().
void SFXDSVoice::setMinMaxDistance (F32 min, F32 max) virtual
Sets the minimum and maximum distances for 3d falloff.
Implements SFXVoice.
Referenced by _getBuffer().
void SFXDSVoice::setPitch (F32 pitch) virtual
Sets the pitch scale.
Implements SFXVoice.
Referenced by _getBuffer().
void SFXDSVoice::setTransform (const MatrixF & transform) virtual
Sets the position and orientation for a 3d voice.
Implements SFXVoice.
Referenced by _getBuffer().
void SFXDSVoice::setVelocity (const VectorF & velocity) virtual
Sets the velocity for a 3d voice.
Implements SFXVoice.
Referenced by _getBuffer().
void SFXDSVoice::setVolume (F32 volume) virtual
Sets the volume.
Implements SFXVoice.
Referenced by _getBuffer().
Member Data Documentation
SFXDSDevice* SFXDSVoice::mDevice protected
The device used to commit deferred settings.
IDirectSoundBuffer8* SFXDSVoice::mDSBuffer protected
IDirectSound3DBuffer8* SFXDSVoice::mDSBuffer3D protected
bool SFXDSVoice::mIsLooping protected
Copyright © GarageGames, LLC. All Rights Reserved.