CameraFX Class Reference
Main Modules Class List Namespace List Online
CameraFX Class Reference
#include <T3D/fx/cameraFXMgr.h>
Public Member Functions
CameraFX ()
virtual ~CameraFX ()
MatrixF & getTrans ()
virtual bool isExpired ()
void setDuration (F32 duration)
virtual void update (F32 dt)
Protected Attributes
MatrixF mCamFXTrans
F32 mDuration
F32 mElapsedTime
Constructor & Destructor Documentation
CameraFX::CameraFX ()
virtual CameraFX::~CameraFX () inline virtual
Member Function Documentation
MatrixF& CameraFX::getTrans () inline
References mCamFXTrans.
virtual bool CameraFX::isExpired () inline virtual
Reimplemented in CameraShake.
References mDuration.
Referenced by CameraShake::setAmplitude().
void CameraFX::setDuration (F32 duration) inline
References update().
virtual void CameraFX::update (F32 dt) virtual
Reimplemented in CameraShake.
Referenced by CameraFXManager::getTrans(), CameraShake::setAmplitude(), and setDuration().
Member Data Documentation
MatrixF CameraFX::mCamFXTrans protected
Referenced by getTrans(), and CameraFXManager::getTrans().
F32 CameraFX::mDuration protected
Referenced by isExpired().
F32 CameraFX::mElapsedTime protected
Copyright © GarageGames, LLC. All Rights Reserved.