QuatF Class Reference
Main Modules Class List Namespace List Online
QuatF Class Reference
#include <math/mQuat.h>
Public Member Functions
QuatF ()
QuatF (F32 _x, F32 _y, F32 _z, F32 w)
QuatF (const Point3F &axis, F32 angle)
QuatF (const MatrixF &m)
QuatF (const AngAxisF &a)
QuatF (const EulerF &e)
F32 angleBetween (const QuatF &q)
F32 dot (const QuatF &q) const
QuatF & extrapolate (const QuatF &q1, const QuatF &q2, F32 t)
QuatF & identity ()
QuatF & interpolate (const QuatF &q1, const QuatF &q2, F32 t)
QuatF & inverse ()
S32 isIdentity () const
QuatF & mul (const QuatF &a, const QuatF &b)
Point3F & mulP (const Point3F &a, Point3F *r) const
QuatF & neg ()
QuatF & normalize ()
S32 operator!= (const QuatF &c) const
QuatF operator* (F32 a) const
QuatF & operator*= (const QuatF &c)
QuatF & operator*= (F32 a)
QuatF & operator+= (const QuatF &c)
QuatF operator- (const QuatF &c) const
QuatF & operator-= (const QuatF &c)
QuatF & operator/= (const QuatF &c)
QuatF & operator/= (F32 a)
S32 operator== (const QuatF &c) const
QuatF & set (F32 _x, F32 _y, F32 _z, F32 _w)
QuatF & set (const Point3F &axis, F32 angle)
QuatF & set (const MatrixF &m)
QuatF & set (const AngAxisF &a)
QuatF & set (const EulerF &e)
MatrixF * setMatrix (MatrixF *mat) const
QuatF & shortestArc (const VectorF &normalizedA, const VectorF &normalizedB)
QuatF & slerp (const QuatF &q, F32 t)
QuatF & square ()
Public Attributes
F32 w
F32 x
F32 y
F32 z
Static Public Attributes
static const QuatF Identity
Constructor & Destructor Documentation
QuatF::QuatF () inline
References angleBetween(), dot(), extrapolate(), identity(), interpolate(), inverse(), isIdentity(), mul(), mulP(), neg(), normalize(), operator!=(), operator*(), operator*=(), operator+=(), operator-(), operator-=(), operator/=(), operator==(), setMatrix(), shortestArc(), slerp(), and square().
Referenced by operator*(), and operator-().
QuatF::QuatF (F32 _x, F32 _y, F32 _z, F32 w) inline
QuatF::QuatF (const Point3F & axis, F32 angle) inline
QuatF::QuatF (const MatrixF & m) inline
QuatF::QuatF (const AngAxisF & a) inline
QuatF::QuatF (const EulerF & e) inline
Member Function Documentation
F32 QuatF::angleBetween (const QuatF & q) inline
References dot().
Referenced by QuatF().
F32 QuatF::dot (const QuatF & q) const inline
References w, x, y, and z.
Referenced by angleBetween(), and QuatF().
QuatF& QuatF::extrapolate (const QuatF & q1, const QuatF & q2, F32 t)
Referenced by QuatF().
QuatF & QuatF::identity () inline
References w, x, y, and z.
Referenced by TSScale::identity(), and QuatF().
QuatF& QuatF::interpolate (const QuatF & q1, const QuatF & q2, F32 t)
Referenced by PhysicsState::interpolate(), and QuatF().
QuatF& QuatF::inverse ()
Referenced by operator==(), and QuatF().
int QuatF::isIdentity () const inline
References x, y, and z.
Referenced by operator==(), and QuatF().
QuatF& QuatF::mul (const QuatF & a, const QuatF & b)
Referenced by QuatF().
Point3F& QuatF::mulP (const Point3F & a, Point3F * r) const
Referenced by QuatF().
QuatF & QuatF::neg () inline
References w, x, y, and z.
Referenced by QuatF().
QuatF& QuatF::normalize ()
Referenced by operator==(), and QuatF().
int QuatF::operator!= (const QuatF & c) const inline
References operator==().
Referenced by QuatF().
QuatF QuatF::operator* (F32 a) const inline
References QuatF(), w, x, y, and z.
Referenced by QuatF().
QuatF& QuatF::operator*= (const QuatF & c)
Referenced by QuatF().
QuatF & QuatF::operator*= (F32 a) inline
References w, x, y, and z.
QuatF & QuatF::operator+= (const QuatF & c) inline
References w, x, y, and z.
Referenced by QuatF().
QuatF QuatF::operator- (const QuatF & c) const inline
References QuatF(), w, x, y, and z.
Referenced by QuatF().
QuatF & QuatF::operator-= (const QuatF & c) inline
References w, x, y, and z.
Referenced by QuatF().
QuatF& QuatF::operator/= (const QuatF & c)
Referenced by QuatF().
QuatF & QuatF::operator/= (F32 a) inline
References w, x, y, and z.
int QuatF::operator== (const QuatF & c) const inline
References inverse(), isIdentity(), and normalize().
Referenced by operator!=(), and QuatF().
QuatF & QuatF::set (F32 _x, F32 _y, F32 _z, F32 _w) inline
References w, x, y, and z.
QuatF& QuatF::set (const Point3F & axis, F32 angle)
QuatF& QuatF::set (const MatrixF & m)
QuatF& QuatF::set (const AngAxisF & a)
QuatF& QuatF::set (const EulerF & e)
MatrixF* QuatF::setMatrix (MatrixF * mat) const
Referenced by PhysicsState::getTransform(), QuatF(), and TSTransform::setMatrix().
QuatF& QuatF::shortestArc (const VectorF & normalizedA, const VectorF & normalizedB)
Referenced by QuatF().
QuatF& QuatF::slerp (const QuatF & q, F32 t)
Referenced by QuatF().
QuatF& QuatF::square ()
Referenced by QuatF().
Member Data Documentation
const QuatF QuatF::Identity static
Referenced by LeapMotionFrame::getHandRotQuat(), LeapMotionFrame::getPointableRotQuat(), and RazerHydraFrame::getRotQuat().
F32 QuatF::w
Referenced by dot(), TamlCustomField::getFieldValue(), identity(), neg(), operator*(), operator*=(), operator+=(), operator-(), operator-=(), operator/=(), set(), and TamlCustomField::setFieldValue().
F32 QuatF::x
Referenced by dot(), TamlCustomField::getFieldValue(), identity(), isIdentity(), neg(), operator*(), operator*=(), operator+=(), operator-(), operator-=(), operator/=(), set(), and TamlCustomField::setFieldValue().
F32 QuatF::y
Referenced by dot(), TamlCustomField::getFieldValue(), identity(), isIdentity(), neg(), operator*(), operator*=(), operator+=(), operator-(), operator-=(), operator/=(), set(), and TamlCustomField::setFieldValue().
F32 QuatF::z
Referenced by dot(), TamlCustomField::getFieldValue(), identity(), isIdentity(), neg(), operator*(), operator*=(), operator+=(), operator-(), operator-=(), operator/=(), set(), and TamlCustomField::setFieldValue().
Copyright © GarageGames, LLC. All Rights Reserved.