Frustum Class Reference
Main Modules Class List Namespace List Online
Frustum Class Reference
This class implements a view frustum for use in culling scene objects and rendering the scene.
#include <math/util/frustum.h>
Public Types
typedef PolyhedronImpl< FrustumData > Parent
Public Types inherited from PolyhedronImpl< FrustumData >
typedef FrustumData::Edge Edge
typedef FrustumData::EdgeListType EdgeListType
typedef FrustumData::PlaneListType PlaneListType
typedef FrustumData::PointListType PointListType
Public Types inherited from FrustumData
enum { EdgeCount = 12 }
enum {
PlaneLeft,
PlaneRight,
PlaneNear,
PlaneFar,
PlaneTop,
PlaneBottom,
PlaneCount
}
Indices for the planes in a frustum.
enum : U32 {
PlaneMaskLeft = (1 << PlaneLeft),
PlaneMaskRight = (1 << PlaneRight),
PlaneMaskTop = (1 << PlaneTop),
PlaneMaskBottom = (1 << PlaneBottom),
PlaneMaskNear = (1 << PlaneNear),
PlaneMaskFar = (1 << PlaneFar),
PlaneMaskAll = 0xFFFFFFFF
}
Used to mask out planes for testing.
enum CornerPoints {
NearTopLeft,
NearTopRight,
NearBottomLeft,
NearBottomRight,
FarTopLeft,
FarTopRight,
FarBottomLeft,
FarBottomRight,
CornerPointCount
}
Indices for the corner points of the frustum.
typedef FixedSizeVector< Edge, EdgeCount > EdgeListType
enum PlaneCenters {
PlaneLeftCenter,
PlaneRightCenter,
PlaneTopCenter,
PlaneBottomCenter,
PlaneNearCenter,
PlaneFarCenter
}
Indices for the center points of the frustum planes.
typedef FixedSizeVector< PlaneF, PlaneCount > PlaneListType
typedef FixedSizeVector< Point3F, CornerPointCount > PointListType
Public Types inherited from PolyhedronData
typedef Edge EdgeType
typedef PlaneF PlaneType
typedef Point3F PointType
Public Member Functions
Constructors
Frustum (bool orthographic=false, F32 nearLeft=-1.0f, F32 nearRight=1.0f, F32 nearTop=1.0f, F32 nearBottom=-1.0f, F32 nearDist=0.1f, F32 farDist=1.0f, const MatrixF &transform=MatrixF(true))
Construct a non-inverted frustum.
Operators
bool operator== (const Frustum &frustum) const
bool operator!= (const Frustum &frustum) const
Initialization
Functions used to initialize the frustum.
void set (bool isOrtho, F32 fovYInRadians, F32 aspectRatio, F32 nearDist, F32 farDist, const MatrixF &mat=MatrixF(true))
Sets the frustum from the field of view, screen aspect ratio, and the near and far distances.
void set (bool isOrtho, F32 nearLeft, F32 nearRight, F32 nearTop, F32 nearBottom, F32 nearDist, F32 farDist, const MatrixF &transform=MatrixF(true))
Sets the frustum from the near plane dimensions and near and far distances.
void setNearDist (F32 nearDist)
Sets the frustum by extracting the planes from a projection, view-projection, or world-view-projection matrix.
void setFarDist (F32 farDist)
Changes the far distance of the frustum.
void setNearFarDist (F32 nearDist, F32 farDist)
Changes the near and far distance of the frustum.
void cropNearFar (F32 newNearDist, F32 newFarDist)
F32 getFarDist () const
Returns the far clip distance used to create the frustum planes.
F32 getNearDist () const
Returns the far clip distance used to create the frustum planes.
F32 getNearLeft () const
Return the camera-space minimum X coordinate on the near plane.
F32 getNearRight () const
Return the camera-space maximum X coordinate on the near plane.
F32 getNearTop () const
Return the camera-space maximum Z coordinate on the near plane.
F32 getNearBottom () const
Return the camera-space minimum Z coordinate on the near plane.
F32 getWidth () const
Return the camera-space width of the frustum.
F32 getHeight () const
Return the camera-space height of the frustum.
F32 getFov () const
F32 getAspectRatio () const
Transformation
These functions for transforming the frustum from one space to another.
void setTransform (const MatrixF &transform)
Sets a new transform for the frustum.
const MatrixF & getTransform () const
Returns the current transform matrix for the frustum.
void scaleFromCenter (F32 scale)
Scales up the frustum from its center point.
void mul (const MatrixF &mat)
Transforms the frustum by F = F * mat.
void mulL (const MatrixF &mat)
Transforms the frustum by F = mat * F.
void invert ()
Flip the plane normals which has the result of reversing the culling results.
bool isInverted () const
Returns true if the frustum planes point outwards.
const Point3F & getPosition () const
Returns the origin point of the frustum.
const Box3F & getBounds () const
Returns the axis aligned bounding box of the frustum points typically used for early rejection.
bool hasProjectionOffset () const
const Point2F & getProjectionOffset () const
Get the offset used when calculating the projection matrix.
const MatrixF & getProjectionOffsetMatrix () const
Get the offset matrix used when calculating the projection matrix.
void setProjectionOffset (const Point2F &offsetMat)
Set the offset used when calculating the projection matrix.
void clearProjectionOffset ()
Clear any offset used when calculating the projection matrix.
bool bakeProjectionOffset ()
Enlarges the frustum to contain the planes generated by a project offset, if any.
void getProjectionMatrix (MatrixF *proj, bool gfxRotate=true) const
Generates a projection matrix from the frustum.
void update ()
Will update the frustum if it is dirty.
Culling
bool isCulled (const Box3F &aabb) const
Return true if the contents of the given AABB can be culled.
bool isCulled (const OrientedBox3F &obb) const
Return true if the contents of the given OBB can be culled.
bool isCulled (const SphereF &sphere) const
Return true if the contents of the given sphere can be culled.
Projection Type
bool isOrtho () const
Public Member Functions inherited from PolyhedronImpl< FrustumData >
PolyhedronImpl ()
Construct an empty polyhedron.
PolyhedronImpl (PlaneListType planes, PointListType points, EdgeListType edges)
Construct a polyhedron described by the given planes and edges.
Box3F getBounds () const
Return the AABB around the polyhedron.
Point3F getCenterPoint () const
Return the median point of all points defined on the polyhedron.
void transform (const MatrixF &matrix, const Point3F &scale=Point3F::One)
Transform the polyhedron using the given transform matrix and scale.
bool isContained (const Point3F &point, F32 epsilon=0.f) const
bool isContained (const Point3F *points, U32 numPoints) const
bool isContained (const Box3F &aabb) const
bool isContained (const SphereF &sphere) const
bool isContained (const OrientedBox3F &obb) const
OverlapTestResult testPotentialIntersection (const Box3F &aabb) const
OverlapTestResult testPotentialIntersection (const SphereF &sphere) const
OverlapTestResult testPotentialIntersection (const OrientedBox3F &obb) const
U32 testPlanes (const Box3F &bounds, U32 planeMask=0xFFFFFFFF, F32 expand=0.0f) const
bool clipSegment (Point3F &pnt0, Point3F &pnt1) const
U32 clipPolygon (const Point3F *inVertices, U32 inNumVertices, Point3F *outVertices, U32 maxOutVertices) const
U32 constructIntersection (const PlaneF &plane, Point3F *outPoints, U32 maxOutPoints) const
Build the intersection of this polyhedron with the given plane.
U32 extractFace (U32 plane, IndexType *outIndices, U32 maxOutIndices) const
Extract the polygon for the given plane.
Public Member Functions inherited from FrustumData
operator AnyPolyhedron () const
const PlaneF * getPlanes () const
Return the planes that make up the polyhedron.
const Point3F * getPoints () const
Protected Attributes
Point2F mProjectionOffset
Offset used for projection matrix calculations.
MatrixF mProjectionOffsetMatrix
The calculated projection offset matrix.
Tiling
U32 mNumTiles
Number of subdivisions.
Point2I mCurrTile
Current rendering tile.
Point2F mTileOverlap
Tile overlap percentage.
Protected Attributes inherited from FrustumData
F32 mFarDist
bool mIsInverted
Whether the frustum is inverted, i.e.
bool mIsOrtho
Determines whether this Frustum is orthographic or perspective.
F32 mNearBottom
F32 mNearDist
F32 mNearLeft
The size of the near plane used to generate the frustum points and planes.
F32 mNearRight
F32 mNearTop
Point3F mPosition
Camera position extracted from tarnsform.
MatrixF mTransform
Used to transform the frustum points from camera space into the desired clipping space.
bool mDirty
When true, points, planes and bounds must be re-calculated before use.
PlaneListType mPlanes
PointListType mPoints
Point3F mPlaneCenters [PlaneCount]
The center points of the individual faces of the frustum.
Box3F mBounds
The clipping-space axis-aligned bounding box which contains the extents of the frustum.
Tile settings
U32 getNumTiles () const
const Point2I & getCurTile () const
void tileFrustum (U32 numTiles, const Point2I &curTile, Point2F overlap)
static void tile (F32 *left, F32 *right, F32 *top, F32 *bottom, U32 numTiles, const Point2I &curTile, Point2F overlap)
Additional Inherited Members
Static Public Member Functions inherited from FrustumData
static U32 getNumPlanes ()
Return the number of planes that a frustum has.
static U32 getNumPoints ()
Return the number of corner points that a frustum has.
static U32 getNumEdges ()
Return the number of edges that a frustum has.
static const Edge * getEdges ()
Return the edge definitions for a frustum.
Static Public Member Functions inherited from PolyhedronData
template<typename Polyhedron >
static void buildBoxData (Polyhedron &poly, const MatrixF &mat, const Box3F &box, bool invertNormals=false)
Protected Member Functions inherited from PolyhedronImpl< FrustumData >
OverlapTestResult _testOverlap (const P &bounds) const
Protected Member Functions inherited from FrustumData
FrustumData ()
void _update () const
Update the point and plane data from the current frustum settings.
Static Protected Attributes inherited from FrustumData
static EdgeListType smEdges
Static edge list.
Detailed Description
This class implements a view frustum for use in culling scene objects and rendering the scene.
Frustums are always non-inverted by default which means that even if the frustum transform applies a negative scale, the frustum will still be non-inverted.
Member Typedef Documentation
typedef PolyhedronImpl< FrustumData > Frustum::Parent
Constructor & Destructor Documentation
Frustum::Frustum (bool orthographic = false, F32 nearLeft = -1.0f, F32 nearRight = 1.0f, F32 nearTop = 1.0f, F32 nearBottom = -1.0f, F32 nearDist = 0.1f, F32 farDist = 1.0f, const MatrixF & transform = MatrixF(true))
Construct a non-inverted frustum.
Note
If the given transform has a negative scale, the plane normals will automatically be inverted so that the frustum will still be non-inverted. Use invert() to actually cause the frustum to be inverted.
Member Function Documentation
bool Frustum::bakeProjectionOffset ()
Enlarges the frustum to contain the planes generated by a project offset, if any.
Used by scene culling to ensure that all object are contained within the asymetrical frustum.
void Frustum::clearProjectionOffset () inline
Clear any offset used when calculating the projection matrix.
References MatrixF::identity(), and Point2F::zero().
void Frustum::cropNearFar (F32 newNearDist, F32 newFarDist)
F32 Frustum::getAspectRatio () const inline
const Box3F& Frustum::getBounds () const inline
Returns the axis aligned bounding box of the frustum points typically used for early rejection.
const Point2I& Frustum::getCurTile () const inline
F32 Frustum::getFarDist () const inline
Returns the far clip distance used to create the frustum planes.
Referenced by SceneRenderState::getFarPlane().
F32 Frustum::getFov () const inline
F32 Frustum::getHeight () const inline
Return the camera-space height of the frustum.
F32 Frustum::getNearBottom () const inline
Return the camera-space minimum Z coordinate on the near plane.
F32 Frustum::getNearDist () const inline
Returns the far clip distance used to create the frustum planes.
Referenced by SceneRenderState::getNearPlane().
F32 Frustum::getNearLeft () const inline
Return the camera-space minimum X coordinate on the near plane.
F32 Frustum::getNearRight () const inline
Return the camera-space maximum X coordinate on the near plane.
F32 Frustum::getNearTop () const inline
Return the camera-space maximum Z coordinate on the near plane.
U32 Frustum::getNumTiles () const inline
const Point3F& Frustum::getPosition () const inline
Returns the origin point of the frustum.
Referenced by SceneCameraState::getViewPosition().
void Frustum::getProjectionMatrix (MatrixF * proj, bool gfxRotate = true) const
Generates a projection matrix from the frustum.
const Point2F& Frustum::getProjectionOffset () const inline
Get the offset used when calculating the projection matrix.
const MatrixF& Frustum::getProjectionOffsetMatrix () const inline
Get the offset matrix used when calculating the projection matrix.
const MatrixF& Frustum::getTransform () const inline
Returns the current transform matrix for the frustum.
Referenced by SceneCameraState::getViewWorldMatrix().
F32 Frustum::getWidth () const inline
Return the camera-space width of the frustum.
bool Frustum::hasProjectionOffset () const inline
References Point2F::isZero().
void Frustum::invert ()
Flip the plane normals which has the result of reversing the culling results.
bool Frustum::isCulled (const Box3F & aabb) const inline
Return true if the contents of the given AABB can be culled.
bool Frustum::isCulled (const OrientedBox3F & obb) const inline
Return true if the contents of the given OBB can be culled.
bool Frustum::isCulled (const SphereF & sphere) const inline
Return true if the contents of the given sphere can be culled.
bool Frustum::isInverted () const inline
Returns true if the frustum planes point outwards.
bool Frustum::isOrtho () const inline
Referenced by GFXDevice::isFrustumOrtho().
void Frustum::mul (const MatrixF & mat)
Transforms the frustum by F = F * mat.
void Frustum::mulL (const MatrixF & mat)
Transforms the frustum by F = mat * F.
bool Frustum::operator!= (const Frustum & frustum) const inline
bool Frustum::operator== (const Frustum & frustum) const inline
References FrustumData::mFarDist, FrustumData::mNearBottom, FrustumData::mNearDist, FrustumData::mNearLeft, FrustumData::mNearTop, mProjectionOffset, Point2F::x, and Point2F::y.
void Frustum::scaleFromCenter (F32 scale)
Scales up the frustum from its center point.
void Frustum::set (bool isOrtho, F32 fovYInRadians, F32 aspectRatio, F32 nearDist, F32 farDist, const MatrixF & mat = MatrixF(true))
Sets the frustum from the field of view, screen aspect ratio, and the near and far distances.
You can pass an matrix to transform the frustum.
void Frustum::set (bool isOrtho, F32 nearLeft, F32 nearRight, F32 nearTop, F32 nearBottom, F32 nearDist, F32 farDist, const MatrixF & transform = MatrixF(true))
Sets the frustum from the near plane dimensions and near and far distances.
void Frustum::setFarDist (F32 farDist)
Changes the far distance of the frustum.
void Frustum::setNearDist (F32 nearDist)
Sets the frustum by extracting the planes from a projection, view-projection, or world-view-projection matrix.
Changes the near distance of the frustum.
void Frustum::setNearFarDist (F32 nearDist, F32 farDist)
Changes the near and far distance of the frustum.
void Frustum::setProjectionOffset (const Point2F & offsetMat)
Set the offset used when calculating the projection matrix.
void Frustum::setTransform (const MatrixF & transform)
Sets a new transform for the frustum.
static void Frustum::tile (F32 * left, F32 * right, F32 * top, F32 * bottom, U32 numTiles, const Point2I & curTile, Point2F overlap) static
void Frustum::tileFrustum (U32 numTiles, const Point2I & curTile, Point2F overlap)
void Frustum::update () inline
Will update the frustum if it is dirty.
Member Data Documentation
Point2I Frustum::mCurrTile protected
Current rendering tile.
U32 Frustum::mNumTiles protected
Number of subdivisions.
Point2F Frustum::mProjectionOffset protected
Offset used for projection matrix calculations.
Referenced by operator==().
MatrixF Frustum::mProjectionOffsetMatrix protected
The calculated projection offset matrix.
Point2F Frustum::mTileOverlap protected
Tile overlap percentage.
Copyright © GarageGames, LLC. All Rights Reserved.