GFont Class Reference
Main Modules Class List Namespace List Online
GFont Class Reference
#include <gfx/gFont.h>
Public Types
enum Constants {
TabWidthInSpaces = 3,
TextureSheetSize = 256
}
Public Member Functions
GFont ()
virtual ~GFont ()
void dumpInfo () const
Dump information about this font to the console.
void exportStrip (const char *fileName, U32 padding, U32 kerning)
Export to an image strip for image processing.
const U32 getAscent () const
const U32 getBaseline () const
U32 getBreakPos (const UTF16 *string, U32 strlen, U32 width, bool breakOnWhitespace)
U32 getCharHeight (const UTF16 in_charIndex)
const PlatformFont::CharInfo & getCharInfo (const UTF16 in_charIndex)
U32 getCharWidth (const UTF16 in_charIndex)
U32 getCharXIncrement (const UTF16 in_charIndex)
const U32 getDescent () const
U32 getFontCharSet () const
String getFontFaceName () const
Get the face name of the font.
U32 getFontSize () const
const U32 getHeight () const
U32 getStrNWidth (const UTF16 *, U32 n)
These are the preferred width functions.
U32 getStrNWidth (const UTF8 *, U32 n)
U32 getStrNWidthPrecise (const UTF16 *, U32 n)
U32 getStrNWidthPrecise (const UTF8 *, U32 n)
U32 getStrWidth (const UTF8 *)
These UTF8 versions of the width functions will be deprecated, please avoid them.
U32 getStrWidthPrecise (const UTF8 *)
GFXTexHandle getTextureHandle (S32 index) const
const bool hasPlatformFont () const
Query as to presence of platform font.
void importStrip (const char *fileName, U32 padding, U32 kerning)
Import an image strip generated with exportStrip, make sure parameters match!
bool isAlphaOnly () const
Query to determine if we should use add or modulate (as A8 textures are treated as having 0 for RGB).
bool isValidChar (const UTF16 in_charIndex) const
bool read (Stream &io_rStream)
void setPlatformFont (PlatformFont *inPlatformFont)
void wrapString (const UTF8 *string, U32 width, Vector< U32 > &startLineOffset, Vector< U32 > &lineLen)
bool write (Stream &io_rStream)
Static Public Member Functions
static Resource< GFont > create (const String &faceName, U32 size, const char *cacheDirectory=0, U32 charset=TGE_ANSI_CHARSET)
static const PlatformFont::CharInfo & getDefaultCharInfo ()
static String getFontCacheFilename (const String &faceName, U32 faceSize)
Get the filename for a cached font.
static GFont * load (const Torque::Path &path)
Protected Member Functions
void addBitmap (PlatformFont::CharInfo &charInfo)
void addSheet (void)
void assignSheet (S32 sheetNum, GBitmap *bmp)
bool loadCharInfo (const UTF16 ch)
Protected Attributes
void * mMutex
Member Enumeration Documentation
enum GFont::Constants
Enumerator
TabWidthInSpaces
TextureSheetSize
Constructor & Destructor Documentation
GFont::GFont ()
virtual GFont::~GFont () virtual
Member Function Documentation
void GFont::addBitmap (PlatformFont::CharInfo & charInfo) protected
Referenced by getFontCharSet().
void GFont::addSheet (void) protected
Referenced by getFontCharSet().
void GFont::assignSheet (S32 sheetNum, GBitmap * bmp) protected
Referenced by getFontCharSet().
static Resource<GFont> GFont::create (const String & faceName, U32 size, const char * cacheDirectory = 0, U32 charset = TGE_ANSI_CHARSET) static
void GFont::dumpInfo () const
Dump information about this font to the console.
Referenced by getDescent().
void GFont::exportStrip (const char * fileName, U32 padding, U32 kerning)
Export to an image strip for image processing.
Referenced by getDescent().
const U32 GFont::getAscent () const inline
const U32 GFont::getBaseline () const inline
U32 GFont::getBreakPos (const UTF16 * string, U32 strlen, U32 width, bool breakOnWhitespace)
Referenced by getDescent().
U32 GFont::getCharHeight (const UTF16 in_charIndex) inline
References getCharInfo(), and PlatformFont::CharInfo::height.
Referenced by getTextureHandle().
const PlatformFont::CharInfo& GFont::getCharInfo (const UTF16 in_charIndex)
Referenced by getCharHeight(), getCharWidth(), getCharXIncrement(), and getTextureHandle().
U32 GFont::getCharWidth (const UTF16 in_charIndex) inline
References getCharInfo(), and PlatformFont::CharInfo::width.
Referenced by getTextureHandle().
U32 GFont::getCharXIncrement (const UTF16 in_charIndex) inline
References getCharInfo(), and PlatformFont::CharInfo::xIncrement.
Referenced by getTextureHandle().
static const PlatformFont::CharInfo& GFont::getDefaultCharInfo () static
Referenced by getTextureHandle().
const U32 GFont::getDescent () const inline
References dumpInfo(), exportStrip(), getBreakPos(), getStrNWidth(), getStrNWidthPrecise(), getStrWidth(), getStrWidthPrecise(), importStrip(), setPlatformFont(), and wrapString().
static String GFont::getFontCacheFilename (const String & faceName, U32 faceSize) static
Get the filename for a cached font.
Referenced by isAlphaOnly().
U32 GFont::getFontCharSet () const inline
References addBitmap(), addSheet(), assignSheet(), load(), loadCharInfo(), read(), and write().
String GFont::getFontFaceName () const inline
Get the face name of the font.
U32 GFont::getFontSize () const inline
const U32 GFont::getHeight () const inline
U32 GFont::getStrNWidth (const UTF16 * , U32 n)
These are the preferred width functions.
Referenced by getDescent().
U32 GFont::getStrNWidth (const UTF8 * , U32 n)
U32 GFont::getStrNWidthPrecise (const UTF16 * , U32 n)
Referenced by getDescent().
U32 GFont::getStrNWidthPrecise (const UTF8 * , U32 n)
U32 GFont::getStrWidth (const UTF8 *)
These UTF8 versions of the width functions will be deprecated, please avoid them.
Referenced by getDescent().
U32 GFont::getStrWidthPrecise (const UTF8 *)
Referenced by getDescent().
GFXTexHandle GFont::getTextureHandle (S32 index) const inline
References getCharHeight(), getCharInfo(), getCharWidth(), getCharXIncrement(), getDefaultCharInfo(), and isValidChar().
const bool GFont::hasPlatformFont () const inline
Query as to presence of platform font.
If absent, we cannot generate more chars!
void GFont::importStrip (const char * fileName, U32 padding, U32 kerning)
Import an image strip generated with exportStrip, make sure parameters match!
Referenced by getDescent().
bool GFont::isAlphaOnly () const inline
Query to determine if we should use add or modulate (as A8 textures are treated as having 0 for RGB).
References getFontCacheFilename().
bool GFont::isValidChar (const UTF16 in_charIndex) const inline
References PlatformFont::isValidChar().
Referenced by getTextureHandle().
static GFont* GFont::load (const Torque::Path & path) static
Referenced by getFontCharSet().
bool GFont::loadCharInfo (const UTF16 ch) protected
Referenced by getFontCharSet().
bool GFont::read (Stream & io_rStream)
Referenced by getFontCharSet().
void GFont::setPlatformFont (PlatformFont * inPlatformFont)
Referenced by getDescent().
void GFont::wrapString (const UTF8 * string, U32 width, Vector< U32 > & startLineOffset, Vector< U32 > & lineLen)
Referenced by getDescent().
bool GFont::write (Stream & io_rStream)
Referenced by getFontCharSet().
Member Data Documentation
void* GFont::mMutex protected
Copyright © GarageGames, LLC. All Rights Reserved.