CollisionList Class Reference
Main Modules Class List Namespace List Online
CollisionList Class Reference
#include <collision/collision.h>
Public Types
enum { MaxCollisions = 64 }
Public Member Functions
CollisionList ()
void clear ()
S32 getCount () const
F32 getMaxHeight () const
F32 getTime () const
Collision & increment ()
const Collision & operator[] (const dsize_t idx) const
Collision & operator[] (const dsize_t idx)
void setMaxHeight (const F32 height)
void setTime (const F32 t)
Protected Attributes
Collision mCollision [MaxCollisions]
dsize_t mCount
F32 mMaxHeight
F32 mT
Member Enumeration Documentation
anonymous enum
Enumerator
MaxCollisions
Constructor & Destructor Documentation
CollisionList::CollisionList () inline
Member Function Documentation
void CollisionList::clear (void) inline
Referenced by CollisionInterface::clearCollisionList().
S32 CollisionList::getCount () const inline
Referenced by CollisionComponent::getBestCollision(), CollisionComponent::getCollisionAngle(), CollisionComponent::getCollisionCount(), and CollisionComponent::getCollisionNormal().
F32 CollisionList::getMaxHeight () const inline
F32 CollisionList::getTime () const inline
Collision& CollisionList::increment () inline
const Collision& CollisionList::operator[] (const dsize_t idx) const inline
Collision& CollisionList::operator[] (const dsize_t idx) inline
void CollisionList::setMaxHeight (const F32 height) inline
void CollisionList::setTime (const F32 t) inline
Member Data Documentation
Collision CollisionList::mCollision[MaxCollisions] protected
dsize_t CollisionList::mCount protected
F32 CollisionList::mMaxHeight protected
F32 CollisionList::mT protected
Copyright © GarageGames, LLC. All Rights Reserved.