GFXGLDevice Class Reference
Main Modules Class List Namespace List Online
GFXGLDevice Class Reference
#include <gfx/gl/gfxGLDevice.h>
Classes
struct GLCapabilities
Public Member Functions
GFXGLDevice (U32 adapterIndex)
virtual ~GFXGLDevice ()
virtual void activate ()
virtual GFXCubemap * createCubemap ()
virtual void deactivate ()
virtual void enterDebugEvent (ColorI color, const char *name)
virtual void enumerateVideoModes ()
virtual GFXAdapterType getAdapterType ()
Returns active graphics adapter type.
virtual F32 getFillConventionOffset () const
Get the fill convention for this device.
virtual U32 getTotalVideoMemory ()
virtual U32 getTotalVideoMemory_GL_EXT ()
virtual void init (const GFXVideoMode &mode, PlatformWindow *window=NULL)
Initialize this GFXDevice, optionally specifying a platform window to bind to.
virtual void leaveDebugEvent ()
void resurrect ()
virtual void setDebugMarker (ColorI color, const char *name)
void zombify ()
Render Target functions
virtual GFXTextureTarget * allocRenderToTextureTarget ()
Allocate a target for doing render to texture operations, with no depth/stencil buffer.
virtual GFXWindowTarget * allocWindowTarget (PlatformWindow *window)
Allocate a target for a given window.
virtual void _updateRenderTargets ()
Updates the render targets and viewport in a device specific manner when they are dirty.
Public Member Functions inherited from GFXDevice
GFXDevice ()
virtual ~GFXDevice ()
void activateStereoTarget (S32 eyeId)
Activates a stereo render target, setting the correct viewport to render eye contents.
bool allowRender () const
void beginReset ()
bool canCurrentlyRender () const
Returns true if the scene has begun and its safe to make rendering calls.
virtual void doParanoidStateCheck ()
void dumpStates (const char *fileName) const
This is a method designed for debugging.
void finalizeReset ()
virtual const GFXAdapter & getAdapter ()
Returns the Adapter that was used to create this device.
GFXCardProfiler * getCardProfiler () const
U32 getCurrentRenderStyle () const
Retrieve the current rendering style based on GFXDeviceRenderStyles.
S32 getCurrentStereoTarget () const
Retrieve the current stereo target being rendered to.
const Swizzle< U8, 3 > * getDeviceSwizzle24 () const
Swizzle to convert 24bpp bitmaps from RGB to the native device format.
const Swizzle< U8, 4 > * getDeviceSwizzle32 () const
Swizzle to convert 32bpp bitmaps from RGBA to the native device format.
GFXDrawUtil * getDrawUtil ()
Get access to this device's drawing utility class.
const MatrixF * getInverseStereoEyeTransforms ()
const Point3F * getStereoEyeOffsets ()
Get the current eye offset used during stereo rendering.
const MatrixF * getStereoEyeTransforms ()
const FovPort * getStereoFovPort ()
Get the current eye offset used during stereo rendering.
const MatrixF & getStereoHeadTransform ()
RectI * getStereoViewports ()
Point2F getWorldToScreenScale () const
Returns the scale for converting world space units to screen space units...
bool recentlyReset ()
void setAllowRender (bool render)
void setCurrentRenderStyle (U32 style)
Set the current rendering style, based on GFXDeviceRenderStyles.
void setCurrentStereoTarget (const F32 targetId)
Set the current stereo target being rendered to (in case we're doing anything with postfx)
void setStereoEyeOffsets (Point3F *offsets)
Set the current eye offset used during stereo rendering.
void setStereoEyeTransforms (MatrixF *transforms)
void setStereoFovPort (const FovPort *ports)
Set the current eye offset used during stereo rendering. Assumes NumStereoPorts are available.
void setStereoHeadTransform (const MatrixF &mat)
Sets the head matrix for stereo rendering.
void setStereoTargets (GFXTextureTarget **targets)
Sets stereo render targets.
void setSteroViewports (const RectI *ports)
Sets stereo viewports.
const Vector< GFXVideoMode > *const getVideoModeList () const
Returns the video mode list.
void pushActiveRenderTarget ()
Store the current render target to restore later.
void popActiveRenderTarget ()
Restore the previous render target.
void setActiveRenderTarget (GFXTarget *target, bool updateViewport=true)
Assign a new active render target.
GFXTarget * getActiveRenderTarget ()
Returns the current active render target.
virtual void disableShaders (bool force=false)
void setShaderConstBuffer (GFXShaderConstBuffer *buffer)
Set the buffer! (Actual set happens on the next draw call, just like textures, state blocks, etc)
void setLight (U32 stage, GFXLightInfo *light)
void setLightMaterial (const GFXLightMaterial &mat)
void setGlobalAmbientColor (const ColorF &color)
void setTexture (U32 stage, GFXTextureObject *texture)
void setCubeTexture (U32 stage, GFXCubemap *cubemap)
GFXTextureObject * getCurrentTexture (U32 stage)
virtual GFXStateBlockRef createStateBlock (const GFXStateBlockDesc &desc)
Creates a state block object based on the desc passed in.
virtual void setStateBlock (GFXStateBlock *block)
Sets the current stateblock (actually activated in ::updateStates)
GFXStateBlock * getStateBlock ()
virtual void setStateBlockByDesc (const GFXStateBlockDesc &desc)
This sets a stateblock directly from the description structure.
void setWorldMatrix (const MatrixF &newWorld)
Sets the top of the world matrix stack.
const MatrixF & getWorldMatrix () const
Gets the matrix on the top of the world matrix stack.
void pushWorldMatrix ()
Pushes the world matrix stack and copies the current top matrix to the new top of the stack.
void popWorldMatrix ()
Pops the world matrix stack.
void setProjectionMatrix (const MatrixF &newProj)
Sets the projection matrix.
const MatrixF & getProjectionMatrix () const
Gets the projection matrix.
void setViewMatrix (const MatrixF &newView)
Sets the view matrix.
const MatrixF & getViewMatrix () const
Gets the view matrix.
void multWorld (const MatrixF &mat)
Multiplies the matrix at the top of the world matrix stack by a matrix and replaces the top of the matrix stack with the result.
void setTextureMatrix (const U32 stage, const MatrixF &texMat)
Set texture matrix for a sampler.
void setViewport (const RectI &rect)
Set an area of the target to render to.
const RectI & getViewport () const
Get the current area of the target we will render to.
virtual void setFrustum (F32 left, F32 right, F32 bottom, F32 top, F32 nearPlane, F32 farPlane, bool bRotate=true)
Set the projection frustum.
virtual void setFrustum (const Frustum &frust, bool bRotate=true)
void getFrustum (F32 *left, F32 *right, F32 *bottom, F32 *top, F32 *nearPlane, F32 *farPlane, bool *isOrtho) const
Get the projection frustum.
const Frustum & getFrustum () const
Get the projection frustum.
void setOrtho (F32 left, F32 right, F32 bottom, F32 top, F32 nearPlane, F32 farPlane, bool doRotate=false)
This will construct and apply an orthographic projection matrix with the provided parameters.
bool isFrustumOrtho () const
Return true if the current frustum uses orthographic projection rather than perspective projection.
virtual void listResources (bool unflaggedOnly)
Lists how many of each GFX resource (e.g.
virtual void flagCurrentResources ()
Flags all resources GFX is currently aware of.
virtual void clearResourceFlags ()
Clears the flag on all resources GFX is currently aware of.
virtual void describeResources (const char *resName, const char *file, bool unflaggedOnly)
Dumps a description of the specified resource types to the console.
GFXDeviceStatistics * getDeviceStatistics ()
Returns the current GFXDeviceStatistics, stats are cleared every ::beginScene call.
GFXTextureManager * getTextureManager ()
virtual bool beginScene ()
virtual void endScene ()
virtual void beginField ()
virtual void endField ()
virtual GFXTexHandle & getFrontBuffer ()
void setPrimitiveBuffer (GFXPrimitiveBuffer *buffer)
void setVertexBuffer (GFXVertexBuffer *buffer, U32 stream=0, U32 frequency=0)
Sets the vertex buffer.
void setVertexFormat (const GFXVertexFormat *vertexFormat)
Sets the current vertex format.
void drawPrimitive (const GFXPrimitive &prim)
void drawPrimitive (U32 primitiveIndex)
void drawPrimitives ()
void drawPrimitiveBuffer (GFXPrimitiveBuffer *buffer)
void updateStates (bool forceSetAll=false)
Static Public Member Functions
static GFXDevice * createInstance (U32 adapterIndex)
static void enumerateAdapters (Vector< GFXAdapter * > &adapterList)
Static Public Member Functions inherited from GFXDevice
static bool destroy ()
static bool devicePresent ()
static GFXDevice * get ()
static DeviceEventSignal & getDeviceEventSignal ()
static void initConsole ()
static bool getWireframe ()
Returns the forced global wireframe state.
static bool getDisableOcclusionQuery ()
Returns true if the occlusion query is disabled.
Public Attributes
GLCapabilities mCapabilities
Public Attributes inherited from GFXDevice
PlatformTimer * mFrameTime
Shader functions
virtual F32 getPixelShaderVersion () const
virtual void setPixelShaderVersion (F32 version)
virtual void setShader (GFXShader *shader, bool force=false)
virtual GFXFormat selectSupportedFormat (GFXTextureProfile *profile, const Vector< GFXFormat > &formats, bool texture, bool mustblend, bool mustfilter)
virtual U32 getNumSamplers () const
Returns the number of texture samplers that can be used in a shader rendering pass.
virtual U32 getNumRenderTargets () const
Returns the number of simultaneous render targets supported by the device.
virtual GFXShader * createShader ()
Creates a new empty shader which must be initialized and deleted by the caller.
virtual void clear (U32 flags, ColorI color, F32 z, U32 stencil)
virtual bool beginSceneInternal ()
virtual void endSceneInternal ()
virtual void drawPrimitive (GFXPrimitiveType primType, U32 vertexStart, U32 primitiveCount)
virtual void drawIndexedPrimitive (GFXPrimitiveType primType, U32 startVertex, U32 minIndex, U32 numVerts, U32 startIndex, U32 primitiveCount)
The parameters to drawIndexedPrimitive are somewhat complicated.
virtual void setClipRect (const RectI &rect)
virtual const RectI & getClipRect () const
virtual void preDestroy ()
This is called before this, or any other device, is deleted in the global destroy() method.
virtual U32 getMaxDynamicVerts ()
virtual U32 getMaxDynamicIndices ()
GFXFence * createFence ()
Allocate a fence.
GFXOcclusionQuery * createOcclusionQuery ()
Returns a hardware occlusion query object or NULL if this device does not support them.
GFXGLStateBlockRef getCurrentStateBlock ()
virtual void setupGenericShaders (GenericShaderType type=GSColor)
This is a helper function to set a default shader for rendering GUI elements on systems which do not support fixed-function operations as well as for things which need just generic position/texture/color shaders.
bool supportsAnisotropic () const
GFXGLStateCache * getOpenglCache ()
GFXTextureObject * getDefaultDepthTex () const
const U32 getNumVertexStreams () const
Returns the number of vertex streams supported by the device.
bool glUseMap () const
virtual GFXStateBlockRef createStateBlockInternal (const GFXStateBlockDesc &desc)
Called by GFXDevice to create a device specific stateblock.
virtual void setStateBlockInternal (GFXStateBlock *block, bool force)
Called by GFXDevice to actually set a stateblock.
virtual void setShaderConstBufferInternal (GFXShaderConstBuffer *buffer)
Called by base GFXDevice to actually set a const buffer.
virtual void setTextureInternal (U32 textureUnit, const GFXTextureObject *texture)
virtual void setCubemapInternal (U32 cubemap, const GFXGLCubemap *texture)
virtual void setLightInternal (U32 lightStage, const GFXLightInfo light, bool lightEnable)
virtual void setLightMaterialInternal (const GFXLightMaterial mat)
virtual void setGlobalAmbientInternal (ColorF color)
State Initalization.
virtual void initStates ()
State initalization.
virtual void setMatrix (GFXMatrixType mtype, const MatrixF &mat)
This function must be implemented differently per API and it should set ONLY the current matrix.
virtual GFXVertexBuffer * allocVertexBuffer (U32 numVerts, const GFXVertexFormat *vertexFormat, U32 vertSize, GFXBufferType bufferType, void *data=NULL)
This allocates a vertex buffer and returns a pointer to the allocated buffer.
virtual GFXPrimitiveBuffer * allocPrimitiveBuffer (U32 numIndices, U32 numPrimitives, GFXBufferType bufferType, void *data=NULL)
This allocates a primitive buffer and returns a pointer to the allocated buffer.
virtual GFXVertexDecl * allocVertexDecl (const GFXVertexFormat *vertexFormat)
Called from GFXVertexFormat to allocate the hardware specific vertex declaration for rendering.
virtual void setVertexDecl (const GFXVertexDecl *decl)
Sets the current vertex declaration on the device.
virtual void setVertexStream (U32 stream, GFXVertexBuffer *buffer)
Sets the vertex buffer on the device.
virtual void setVertexStreamFrequency (U32 stream, U32 frequency)
Set the vertex stream frequency on the device.
Additional Inherited Members
Public Types inherited from GFXDevice
typedef Signal< bool(GFXDeviceEventType)> DeviceEventSignal
enum GenericShaderType {
GSColor = 0,
GSTexture,
GSModColorTexture,
GSAddColorTexture,
GSTargetRestore,
GS_COUNT
}
enum GFXDeviceEventType {
deCreate,
deInit,
deDestroy,
deStartOfFrame,
deEndOfFrame,
dePostFrame,
deStartOfField,
deLeftStereoFrameRendered,
deRightStereoFrameRendered,
deEndOfField
}
enum GFXDeviceLimits { NumStereoPorts = 2 }
enum GFXDeviceRenderStyles {
RS_Standard = 0,
RS_StereoSideBySide = (1<<0),
RS_StereoSeparate = (1<<1)
}
Protected Types inherited from GFXDevice
enum TexDirtyType {
GFXTDT_Normal,
GFXTDT_Cube
}
typedef Map< U32, GFXStateBlockRef > StateBlockMap
Protected Member Functions inherited from GFXDevice
virtual void deviceInited ()
Notify GFXDevice that we are initialized.
virtual void setAdapter (const GFXAdapter &adapter)
Set the adapter that this device is using. For use by GFXInit::createDevice only.
virtual void fillResourceVectors (const char *resNames, bool unflaggedOnly, Vector< GFXResource * > &textureObjects, Vector< GFXResource * > &textureTargets, Vector< GFXResource * > &windowTargets, Vector< GFXResource * > &vertexBuffers, Vector< GFXResource * > &primitiveBuffers, Vector< GFXResource * > &fences, Vector< GFXResource * > &cubemaps, Vector< GFXResource * > &shaders, Vector< GFXResource * > &stateblocks)
This is a helper method for describeResourcesToFile.
Protected Attributes inherited from GFXDevice
bool mAllowRender
Set if we're in a mode where we want rendering to occur.
bool mCanCurrentlyRender
Set once the device is active.
GFXCardProfiler * mCardProfiler
The CardProfiler for this device.
U32 mCurrentFrontBufferIdx
U32 mCurrentRenderStyle
The style of rendering that is to be performed, based on GFXDeviceRenderStyles.
GFXTargetRef mCurrentRT
The current render target which may or may not not be yet activated.
S32 mCurrentStereoTarget
Current stereo target being rendered to.
Swizzle< U8, 3 > * mDeviceSwizzle24
Swizzle< U8, 4 > * mDeviceSwizzle32
GFXDrawUtil * mDrawer
FovPort mFovPorts [NumStereoPorts]
Fov port settings.
GFXTexHandle mFrontBuffer [2]
bool mInitialized
This will allow querying to see if a device is initialized and ready to have operations performed on it.
MatrixF mInverseStereoEyeTransforms [NumStereoPorts]
Inverse of mStereoEyeTransforms.
bool mReset
GFXResource * mResourceListHead
Head of the resource list.
GFXTargetRef mRTDeactivate
This tracks a previously activated render target which need to be deactivated.
bool mRTDirty
This is set when the current and/or deactivate render targets have changed and the device need to update its state on the next draw/clear.
Vector< GFXTargetRef > mRTStack
A stack of previously active render targets.
Point3F mStereoEyeOffset [NumStereoPorts]
Eye offset used when using a stereo rendering style.
MatrixF mStereoEyeTransforms [NumStereoPorts]
Left and right matrix for eyes.
MatrixF mStereoHeadTransform
Center matrix for head.
GFXTextureTarget * mStereoTargets [NumStereoPorts]
Destination targets for stereo rendering.
RectI mStereoViewports [NumStereoPorts]
Destination viewports for stereo rendering.
Vector< GFXVideoMode > mVideoModes
List of valid video modes for this device.
RectI mViewport
The current viewport rect.
bool mViewportDirty
If true the viewport has been changed and it must be updated on the next draw/clear.
GFXLightInfo mCurrentLight [LIGHT_STAGE_COUNT]
bool mCurrentLightEnable [LIGHT_STAGE_COUNT]
bool mLightDirty [LIGHT_STAGE_COUNT]
bool mLightsDirty
ColorF mGlobalAmbientColor
bool mGlobalAmbientColorDirty
GFXLightMaterial mCurrentLightMaterial
bool mLightMaterialDirty
MatrixF mWorldMatrix [WORLD_STACK_MAX]
bool mWorldMatrixDirty
S32 mWorldStackSize
MatrixF mProjectionMatrix
bool mProjectionMatrixDirty
MatrixF mViewMatrix
bool mViewMatrixDirty
MatrixF mTextureMatrix [TEXTURE_STAGE_COUNT]
bool mTextureMatrixDirty [TEXTURE_STAGE_COUNT]
bool mTextureMatrixCheckDirty
Frustum mFrustum
GFXDeviceStatistics mDeviceStatistics
bool mStateDirty
Set if ANY state is dirty, including matrices or primitive buffers.
GFXTexHandle mCurrentTexture [TEXTURE_STAGE_COUNT]
GFXTexHandle mNewTexture [TEXTURE_STAGE_COUNT]
GFXCubemapHandle mCurrentCubemap [TEXTURE_STAGE_COUNT]
GFXCubemapHandle mNewCubemap [TEXTURE_STAGE_COUNT]
TexDirtyType mTexType [TEXTURE_STAGE_COUNT]
bool mTextureDirty [TEXTURE_STAGE_COUNT]
bool mTexturesDirty
StateBlockMap mCurrentStateBlocks
bool mStateBlockDirty
GFXStateBlockRef mCurrentStateBlock
GFXStateBlockRef mNewStateBlock
GFXShaderConstBuffer * mCurrentShaderConstBuffer
StrongRefPtr< GFXVertexBuffer > mCurrentVertexBuffer [VERTEX_STREAM_COUNT]
bool mVertexBufferDirty [VERTEX_STREAM_COUNT]
U32 mVertexBufferFrequency [VERTEX_STREAM_COUNT]
bool mVertexBufferFrequencyDirty [VERTEX_STREAM_COUNT]
const GFXVertexDecl * mCurrVertexDecl
bool mVertexDeclDirty
StrongRefPtr< GFXPrimitiveBuffer > mCurrentPrimitiveBuffer
bool mPrimitiveBufferDirty
GFXTextureManager * mTextureManager
Static Protected Attributes inherited from GFXDevice
static bool smWireframe
A global forced wireframe mode.
static bool smDisableVSync
The global vsync state.
static F32 smForcedPixVersion
The forced shader model version if non-zero.
static bool smDisableOcclusionQuery
Disable all hardware occlusion queries causing them to return only the visibile state.
static const U32 VERTEX_STREAM_COUNT = 4
The maximum number of supported vertex streams which may be more than the device supports.
Constructor & Destructor Documentation
GFXGLDevice::GFXGLDevice (U32 adapterIndex)
virtual GFXGLDevice::~GFXGLDevice () virtual
Member Function Documentation
virtual void GFXGLDevice::_updateRenderTargets () virtual
Updates the render targets and viewport in a device specific manner when they are dirty.
Implements GFXDevice.
Referenced by getFillConventionOffset().
virtual void GFXGLDevice::activate () inline virtual
virtual GFXPrimitiveBuffer* GFXGLDevice::allocPrimitiveBuffer (U32 numIndices, U32 numPrimitives, GFXBufferType bufferType, void * data = NULL) protected virtual
This allocates a primitive buffer and returns a pointer to the allocated buffer.
A primitive buffer's type argument refers to the index data - the primitive data will always be preserved from call to call.
Note
All index buffers use unsigned 16-bit indices.
Implements GFXDevice.
Referenced by initStates().
virtual GFXTextureTarget* GFXGLDevice::allocRenderToTextureTarget () virtual
Allocate a target for doing render to texture operations, with no depth/stencil buffer.
Implements GFXDevice.
Referenced by getFillConventionOffset().
virtual GFXVertexBuffer* GFXGLDevice::allocVertexBuffer (U32 numVerts, const GFXVertexFormat * vertexFormat, U32 vertSize, GFXBufferType bufferType, void * data = NULL) protected virtual
This allocates a vertex buffer and returns a pointer to the allocated buffer.
This function should not be called directly - rather it should be used by the GFXVertexBufferHandle class.
Implements GFXDevice.
Referenced by initStates().
virtual GFXVertexDecl* GFXGLDevice::allocVertexDecl (const GFXVertexFormat * vertexFormat) protected virtual
Called from GFXVertexFormat to allocate the hardware specific vertex declaration for rendering.
Implements GFXDevice.
Referenced by initStates().
virtual GFXWindowTarget* GFXGLDevice::allocWindowTarget (PlatformWindow * window) virtual
Allocate a target for a given window.
Implements GFXDevice.
Referenced by getFillConventionOffset().
virtual bool GFXGLDevice::beginSceneInternal () virtual
Implements GFXDevice.
Referenced by setPixelShaderVersion().
virtual void GFXGLDevice::clear (U32 flags, ColorI color, F32 z, U32 stencil) virtual
Implements GFXDevice.
Referenced by setPixelShaderVersion().
virtual GFXCubemap* GFXGLDevice::createCubemap () virtual
Implements GFXDevice.
Referenced by getAdapterType().
GFXFence* GFXGLDevice::createFence () virtual
Allocate a fence.
The API specific implementation of GFXDevice is responsible to make sure that the proper type is used. GFXGeneralFence should work in all cases.
Implements GFXDevice.
Referenced by getMaxDynamicIndices().
static GFXDevice* GFXGLDevice::createInstance (U32 adapterIndex) static
GFXOcclusionQuery* GFXGLDevice::createOcclusionQuery () virtual
Returns a hardware occlusion query object or NULL if this device does not support them.
Reimplemented from GFXDevice.
Referenced by getMaxDynamicIndices().
virtual GFXShader* GFXGLDevice::createShader () virtual
Creates a new empty shader which must be initialized and deleted by the caller.
See also
GFXShader::init
Implements GFXDevice.
Referenced by setPixelShaderVersion().
virtual GFXStateBlockRef GFXGLDevice::createStateBlockInternal (const GFXStateBlockDesc & desc) protected virtual
Called by GFXDevice to create a device specific stateblock.
Implements GFXDevice.
Referenced by glUseMap().
virtual void GFXGLDevice::deactivate () inline virtual
virtual void GFXGLDevice::drawIndexedPrimitive (GFXPrimitiveType primType, U32 startVertex, U32 minIndex, U32 numVerts, U32 startIndex, U32 primitiveCount) virtual
The parameters to drawIndexedPrimitive are somewhat complicated.
From a raw-data stand point they evaluate to something like the following:
U16 indicies[] = { 0, 1, 2, 1, 0, 0, 2 };
Point3F verts[] = { Point3F(0.0f, 0.0f, 0.0f), Point3F(0.0f, 1.0f, 0.0f), Point3F(0.0f, 0.0f, 1.0f) };
GFX->drawIndexedPrimitive(GFXLineList, // Drawing a list of lines, each line is two verts
                           0, // vertex 0 will be referenced so minIndex = 0
                           3, // 3 verticies will be used for this draw call
                           1, // We want index 1 to be the first index used, so indicies 1-6 will be used
                           3  // Drawing 3 LineList primitives, meaning 6 verts will be drawn
                            );
U16 *idxPtr = &indicies[1];  // 1 = startIndex, so the pointer is offset such that:
                             //    idxPtr[0] is the same as indicies[1]
U32 numVertsToDrawFromBuffer = primitiveCount * 2; // 2 verts define a line in the GFXLineList primitive type (6)
Parameters
primType Type of primitive to draw
startVertex This defines index zero. Its the offset from the start of the vertex buffer to the first vertex.
minIndex The smallest index into the vertex stream which will be used for this draw call. This is a zero based index relative to startVertex. It is strictly a performance hint for implementations. No vertex below minIndex will be referenced by this draw call. For device implementors, this should not be used to offset the vertex buffer, or index buffer.
numVerts The number of verticies which will be referenced in this draw call. This is not the number of verticies which will be drawn. That is a function of 'primType' and 'primitiveCount'.
startIndex An offset from the start of the index buffer to specify where to start. If 'idxBuffer' is a pointer to an array of integers, this could be written as int *offsetIdx = idxBuffer + startIndex;
primitiveCount The number of primitives of type 'primType' to draw.
Implements GFXDevice.
Referenced by setPixelShaderVersion().
virtual void GFXGLDevice::drawPrimitive (GFXPrimitiveType primType, U32 vertexStart, U32 primitiveCount) virtual
Implements GFXDevice.
Referenced by setPixelShaderVersion().
virtual void GFXGLDevice::endSceneInternal () virtual
Implements GFXDevice.
Referenced by setPixelShaderVersion().
virtual void GFXGLDevice::enterDebugEvent (ColorI color, const char * name) virtual
Implements GFXDevice.
Referenced by getAdapterType().
static void GFXGLDevice::enumerateAdapters (Vector< GFXAdapter * > & adapterList) static
virtual void GFXGLDevice::enumerateVideoModes () virtual
Implements GFXDevice.
Referenced by getAdapterType().
virtual GFXAdapterType GFXGLDevice::getAdapterType () inline virtual
Returns active graphics adapter type.
Implements GFXDevice.
References createCubemap(), enterDebugEvent(), enumerateVideoModes(), getTotalVideoMemory(), getTotalVideoMemory_GL_EXT(), leaveDebugEvent(), and setDebugMarker().
virtual const RectI& GFXGLDevice::getClipRect () const inline virtual
Implements GFXDevice.
GFXGLStateBlockRef GFXGLDevice::getCurrentStateBlock () inline
References GFXDevice::GSColor, and setupGenericShaders().
GFXTextureObject* GFXGLDevice::getDefaultDepthTex () const
Referenced by getOpenglCache().
virtual F32 GFXGLDevice::getFillConventionOffset () const inline virtual
Get the fill convention for this device.
Implements GFXDevice.
References _updateRenderTargets(), allocRenderToTextureTarget(), and allocWindowTarget().
virtual U32 GFXGLDevice::getMaxDynamicIndices () inline virtual
Implements GFXDevice.
References createFence(), and createOcclusionQuery().
virtual U32 GFXGLDevice::getMaxDynamicVerts () inline virtual
Implements GFXDevice.
virtual U32 GFXGLDevice::getNumRenderTargets () const virtual
Returns the number of simultaneous render targets supported by the device.
Implements GFXDevice.
Referenced by setPixelShaderVersion().
virtual U32 GFXGLDevice::getNumSamplers () const virtual
Returns the number of texture samplers that can be used in a shader rendering pass.
Implements GFXDevice.
Referenced by setPixelShaderVersion().
const U32 GFXGLDevice::getNumVertexStreams () const inline
Returns the number of vertex streams supported by the device.
GFXGLStateCache* GFXGLDevice::getOpenglCache () inline
References getDefaultDepthTex().
Referenced by GFXGLPreserveTexture::GFXGLPreserveTexture().
virtual F32 GFXGLDevice::getPixelShaderVersion () const inline virtual
Implements GFXDevice.
virtual U32 GFXGLDevice::getTotalVideoMemory () virtual
Referenced by getAdapterType().
virtual U32 GFXGLDevice::getTotalVideoMemory_GL_EXT () virtual
Referenced by getAdapterType().
bool GFXGLDevice::glUseMap () const inline
References createStateBlockInternal(), setCubemapInternal(), setGlobalAmbientInternal(), setLightInternal(), setLightMaterialInternal(), setShaderConstBufferInternal(), setStateBlockInternal(), and setTextureInternal().
virtual void GFXGLDevice::init (const GFXVideoMode & mode, PlatformWindow * window = NULL) virtual
Initialize this GFXDevice, optionally specifying a platform window to bind to.
Implements GFXDevice.
virtual void GFXGLDevice::initStates () inline protected virtual
State initalization.
This MUST BE CALLED in setVideoMode after the device is created.
Implements GFXDevice.
References allocPrimitiveBuffer(), allocVertexBuffer(), allocVertexDecl(), setMatrix(), setVertexDecl(), setVertexStream(), and setVertexStreamFrequency().
virtual void GFXGLDevice::leaveDebugEvent () virtual
Implements GFXDevice.
Referenced by getAdapterType().
virtual void GFXGLDevice::preDestroy () inline virtual
This is called before this, or any other device, is deleted in the global destroy() method.
It allows the device to clean up anything while everything is still valid.
Reimplemented from GFXDevice.
References GFXDevice::preDestroy().
void GFXGLDevice::resurrect ()
virtual GFXFormat GFXGLDevice::selectSupportedFormat (GFXTextureProfile * profile, const Vector< GFXFormat > & formats, bool texture, bool mustblend, bool mustfilter) virtual
Attention
GL cannot check if the given format supports blending or filtering!
Implements GFXDevice.
Referenced by setPixelShaderVersion().
virtual void GFXGLDevice::setClipRect (const RectI & rect) virtual
Implements GFXDevice.
Referenced by setPixelShaderVersion().
virtual void GFXGLDevice::setCubemapInternal (U32 cubemap, const GFXGLCubemap * texture) protected virtual
Referenced by glUseMap().
virtual void GFXGLDevice::setDebugMarker (ColorI color, const char * name) virtual
Implements GFXDevice.
Referenced by getAdapterType().
virtual void GFXGLDevice::setGlobalAmbientInternal (ColorF color) protected virtual
Implements GFXDevice.
Referenced by glUseMap().
virtual void GFXGLDevice::setLightInternal (U32 lightStage, const GFXLightInfo light, bool lightEnable) protected virtual
Implements GFXDevice.
Referenced by glUseMap().
virtual void GFXGLDevice::setLightMaterialInternal (const GFXLightMaterial mat) protected virtual
Implements GFXDevice.
Referenced by glUseMap().
virtual void GFXGLDevice::setMatrix (GFXMatrixType mtype, const MatrixF & mat) protected virtual
This function must be implemented differently per API and it should set ONLY the current matrix.
For example, in OpenGL, there should be NO matrix stack activity, all the stack stuff is managed in the GFX layer.
OpenGL does not have separate world and view matrices. It has ModelView which is world * view. You must take this into consideration.
Parameters
mtype Which matrix to set, world/view/projection
mat Matrix to assign
Implements GFXDevice.
Referenced by initStates().
virtual void GFXGLDevice::setPixelShaderVersion (F32 version) inline virtual
Implements GFXDevice.
References beginSceneInternal(), clear(), createShader(), drawIndexedPrimitive(), drawPrimitive(), endSceneInternal(), getNumRenderTargets(), getNumSamplers(), selectSupportedFormat(), setClipRect(), and setShader().
virtual void GFXGLDevice::setShader (GFXShader * shader, bool force = false) virtual
Reimplemented from GFXDevice.
Referenced by setPixelShaderVersion().
virtual void GFXGLDevice::setShaderConstBufferInternal (GFXShaderConstBuffer * buffer) protected virtual
Called by base GFXDevice to actually set a const buffer.
Implements GFXDevice.
Referenced by glUseMap().
virtual void GFXGLDevice::setStateBlockInternal (GFXStateBlock * block, bool force) protected virtual
Called by GFXDevice to actually set a stateblock.
Implements GFXDevice.
Referenced by glUseMap().
virtual void GFXGLDevice::setTextureInternal (U32 textureUnit, const GFXTextureObject * texture) protected virtual
Implements GFXDevice.
Referenced by glUseMap().
virtual void GFXGLDevice::setupGenericShaders (GenericShaderType type = GSColor) virtual
This is a helper function to set a default shader for rendering GUI elements on systems which do not support fixed-function operations as well as for things which need just generic position/texture/color shaders.
Parameters
type Type of generic shader, add your own if you need
Reimplemented from GFXDevice.
Referenced by getCurrentStateBlock().
virtual void GFXGLDevice::setVertexDecl (const GFXVertexDecl * decl) protected virtual
Sets the current vertex declaration on the device.
Implements GFXDevice.
Referenced by initStates().
virtual void GFXGLDevice::setVertexStream (U32 stream, GFXVertexBuffer * buffer) protected virtual
Sets the vertex buffer on the device.
Implements GFXDevice.
Referenced by initStates().
virtual void GFXGLDevice::setVertexStreamFrequency (U32 stream, U32 frequency) protected virtual
Set the vertex stream frequency on the device.
Implements GFXDevice.
Referenced by initStates().
bool GFXGLDevice::supportsAnisotropic () const inline
void GFXGLDevice::zombify ()
Member Data Documentation
GLCapabilities GFXGLDevice::mCapabilities
Copyright © GarageGames, LLC. All Rights Reserved.