String Class Reference
Main Modules Class List Namespace List Online
String Class Reference
The String class represents a 0-terminated array of characters.
#include <core/util/str.h>
Classes
class StrFormat
An internal support class for ToString().
Public Types
enum Mode {
Case = 0,
NoCase = 1,
Left = 0,
Right = 2
}
Default mode is case sensitive starting from the left.
typedef U32 SizeType
typedef StringChar ValueType
Public Member Functions
String ()
String (const String &str)
String (const StringChar *str)
String (const StringChar *str, SizeType size)
Copy from raw data.
String (const UTF16 *str)
~String ()
const UTF8 * c_str () const
Return the string as a native type.
void clear ()
Erases all characters in a string.
String collapseEscapes () const
Replace all escape sequences in with their respective character codes.
S32 compare (const StringChar *str, SizeType len=0, U32 mode=Case|Left) const
Compare this string with another.
S32 compare (const String &str, SizeType len=0, U32 mode=Case|Left) const
bool endsWith (const char *text) const
Return true if the string ends with the given text.
bool equal (const String &str, U32 mode=Case) const
Compare two strings for equality.
String & erase (SizeType pos, SizeType len)
String expandEscapes () const
Replace all characters that need to be escaped for the string to be a valid string literal with their respective escape sequences.
SizeType find (StringChar c, SizeType pos=0, U32 mode=Case|Left) const
SizeType find (const StringChar *str, SizeType pos=0, U32 mode=Case|Left) const
SizeType find (const String &str, SizeType pos=0, U32 mode=Case|Left) const
U32 getHashCaseInsensitive () const
Get the case-insensitive hash of the string [only calculates the hash as necessary].
U32 getHashCaseSensitive () const
Get the case-sensitive hash of the string [only calculates the hash as necessary].
String & insert (SizeType pos, const StringChar c)
String & insert (SizeType pos, const StringChar *str)
String & insert (SizeType pos, const String &str)
String & insert (SizeType pos, const StringChar *str, SizeType len)
bool isEmpty () const
Is this an empty string [""]?
bool isNotEmpty () const
Is this not an empty string [""]?
bool isSame (const String &str) const
Return true if both strings refer to the same shared data.
bool isShared () const
Is this string's reference count greater than 1?
SizeType length () const
Returns the length of the string in bytes.
SizeType numChars () const
Returns the length of the string in characters.
operator const StringChar * () const
bool operator!= (const String &str) const
bool operator!= (StringChar c) const
String & operator+= (StringChar)
String & operator+= (const StringChar *)
String & operator+= (const String &)
bool operator< (const String &str) const
bool operator<= (const String &str) const
String & operator= (StringChar)
String & operator= (const StringChar *)
String & operator= (const String &)
bool operator== (const String &str) const
bool operator== (StringChar c) const
bool operator> (const String &str) const
bool operator>= (const String &str) const
StringChar operator[] (U32 i) const
StringChar operator[] (S32 i) const
String & replace (SizeType pos, SizeType len, const StringChar *str)
String & replace (SizeType pos, SizeType len, const String &str)
String & replace (StringChar c1, StringChar c2)
Replace all occurrences of character 'c1' with 'c2'.
String & replace (const String &s1, const String &s2)
Replace all occurrences of StringData 's1' with StringData 's2'.
SizeType size () const
Returns the length of the string in bytes including the NULL terminator.
void split (const char *delimiter, Vector< String > &outElements) const
Split the string into its components separated by the given delimiter.
bool startsWith (const char *text) const
Return true if the string starts with the given text.
String substr (SizeType pos, SizeType len=-1) const
String trim () const
Remove leading and trailing whitespace.
const UTF16 * utf16 () const
const UTF8 * utf8 () const
Interning
Interning maps identical strings to unique instances so that equality amounts to simple pointer comparisons.
Note that using interned strings within global destructors is not safe as table destruction runs within this phase as well. Uses o interned strings in global destructors is thus dependent on object file ordering.
Also, interned strings are not reference-counted. Once interned, a string will persist until shutdown. This is to avoid costly concurrent reference counting that would otherwise be necessary.
String intern () const
Return the interned version of the string.
bool isInterned () const
Return true if this string is interned.
Static Public Member Functions
static bool isEmpty (const char *)
String Utility routines
static String ToString (const char *format,...)
static String VToString (const char *format, va_list args)
static String ToString (bool v)
static String ToString (U32 v)
static String ToString (S32 v)
static String ToString (F32 v)
static String ToString (F64 v)
static String SpanToString (const char *start, const char *end)
static String ToLower (const String &string)
static String ToUpper (const String &string)
static String GetTrailingNumber (const char *str, S32 &number)
static String GetFirstNumber (const char *str, U32 &startPos, U32 &endPos)
Static Public Attributes
static const String EmptyString
A predefined empty string.
static const SizeType NPos
Indicates 'not found' when using find() functions.
Friends
String operator+ (const String &a, StringChar c)
String operator+ (StringChar c, const String &a)
String operator+ (const String &a, const StringChar *b)
String operator+ (const String &a, const String &b)
String operator+ (const StringChar *a, const String &b)
Detailed Description
The String class represents a 0-terminated array of characters.
Member Typedef Documentation
typedef U32 String::SizeType
typedef StringChar String::ValueType
Member Enumeration Documentation
enum String::Mode
Default mode is case sensitive starting from the left.
Enumerator
Case
Case sensitive.
NoCase
Case insensitive.
Left
Start at left end of string.
Right
Start at right end of string.
Constructor & Destructor Documentation
String::String ()
Referenced by String::StrFormat::getString().
String::String (const String & str)
String::String (const StringChar * str)
String::String (const StringChar * str, SizeType size)
Copy from raw data.
String::String (const UTF16 * str)
String::~String ()
Member Function Documentation
const UTF8* String::c_str () const
Return the string as a native type.
Referenced by StringBuilder::append(), ScopeTracker< NUM_DIMENSIONS, Object >::debugDump(), OculusVRHMDDevice::getDisplayDeviceType(), LightManager::getId(), OculusVRHMDDevice::getManufacturer(), OculusVRSensorDevice::getManufacturer(), LightManager::getName(), OculusVRHMDDevice::getProductName(), OculusVRSensorDevice::getProductName(), GuiConsoleTextCtrl::getText(), GFXVertexFormat::isEqual(), operator const StringChar *(), FModFNTable::Thunk< FN >::operator()(), operator[](), SceneAmbientSoundObject< Base >::unpackUpdate(), and utf8().
void String::clear (void) inline
Erases all characters in a string.
References Case, compare(), EmptyString, equal(), find(), getHashCaseInsensitive(), getHashCaseSensitive(), isSame(), isShared(), Left, operator+=(), and operator=().
Referenced by MatStateHint::clear().
String String::collapseEscapes () const
Replace all escape sequences in with their respective character codes.
Referenced by insert().
S32 String::compare (const StringChar * str, SizeType len = 0, U32 mode = Case|Left) const
Compare this string with another.
Parameters
str The string to compare against.
len If len is non-zero, then at most len characters are compared.
mode Comparison mode.
Returns
Difference between the first two characters that don't match.
Referenced by clear().
S32 String::compare (const String & str, SizeType len = 0, U32 mode = Case|Left) const
See also
compare(const StringChar *, SizeType, U32) const
bool String::endsWith (const char * text) const
Return true if the string ends with the given text.
Referenced by insert().
bool String::equal (const String & str, U32 mode = Case) const
Compare two strings for equality.
It will use the string hashes to determine inequality.
Parameters
str The string to compare against.
mode Comparison mode - case sensitive or not.
Referenced by clear(), ArrayObject::isEqual(), and Torque::Path::operator==().
String& String::erase (SizeType pos, SizeType len)
Referenced by insert().
String String::expandEscapes () const
Replace all characters that need to be escaped for the string to be a valid string literal with their respective escape sequences.
Referenced by insert().
SizeType String::find (StringChar c, SizeType pos = 0, U32 mode = Case|Left) const
Referenced by clear().
SizeType String::find (const StringChar * str, SizeType pos = 0, U32 mode = Case|Left) const
SizeType String::find (const String & str, SizeType pos = 0, U32 mode = Case|Left) const
static String String::GetFirstNumber (const char * str, U32 & startPos, U32 & endPos) static
Referenced by ToString().
U32 String::getHashCaseInsensitive () const
Get the case-insensitive hash of the string [only calculates the hash as necessary].
Referenced by clear(), DictHash::hash(), and RenderInstType::operator RenderInstTypeHash().
U32 String::getHashCaseSensitive () const
Get the case-sensitive hash of the string [only calculates the hash as necessary].
Referenced by clear(), DictHash::hash(), and MatStateHint::operator U32().
static String String::GetTrailingNumber (const char * str, S32 & number) static
Referenced by ToString().
String& String::insert (SizeType pos, const StringChar c) inline
References collapseEscapes(), endsWith(), erase(), expandEscapes(), insert(), replace(), split(), startsWith(), substr(), and trim().
Referenced by insert().
String& String::insert (SizeType pos, const StringChar * str)
String& String::insert (SizeType pos, const String & str)
String& String::insert (SizeType pos, const StringChar * str, SizeType len)
String String::intern () const
Return the interned version of the string.
Note
Interning is case-sensitive.
Referenced by ToString().
bool String::isEmpty () const
Is this an empty string [""]?
Referenced by FeatureSet::getDescription(), Torque::Path::isEmpty(), isNotEmpty(), and utf8().
static bool String::isEmpty (const char *) static
bool String::isInterned () const
Return true if this string is interned.
Referenced by ToString().
bool String::isNotEmpty () const inline
Is this not an empty string [""]?
References isEmpty().
Referenced by GFXD3D9Shader::getDisassembly(), and GFXD3D11Shader::getDisassembly().
bool String::isSame (const String & str) const
Return true if both strings refer to the same shared data.
Referenced by clear().
bool String::isShared () const
Is this string's reference count greater than 1?
Referenced by clear().
SizeType String::length () const
Returns the length of the string in bytes.
Referenced by StringBuilder::append(), ColorI::convertFromHex(), and utf8().
SizeType String::numChars () const
Returns the length of the string in characters.
Referenced by utf8().
String::operator const StringChar * () const inline
References c_str().
bool String::operator!= (const String & str) const inline
References operator==().
bool String::operator!= (StringChar c) const inline
References operator+, operator<(), operator<=(), operator>(), operator>=(), ToString(), and VToString().
String& String::operator+= (StringChar)
Referenced by clear().
String& String::operator+= (const StringChar *)
String& String::operator+= (const String &)
bool String::operator< (const String & str) const
Referenced by operator!=().
bool String::operator<= (const String & str) const
Referenced by operator!=().
String& String::operator= (StringChar)
Referenced by clear(), and FileName::operator=().
String& String::operator= (const StringChar *)
String& String::operator= (const String &)
bool String::operator== (const String & str) const
Referenced by operator!=(), and operator[]().
bool String::operator== (StringChar c) const
bool String::operator> (const String & str) const
Referenced by operator!=().
bool String::operator>= (const String & str) const
Referenced by operator!=().
StringChar String::operator[] (U32 i) const inline
References c_str().
StringChar String::operator[] (S32 i) const inline
References c_str(), and operator==().
String& String::replace (SizeType pos, SizeType len, const StringChar * str)
Referenced by insert(), and FModFNTable::Thunk< FN >::operator()().
String& String::replace (SizeType pos, SizeType len, const String & str)
String& String::replace (StringChar c1, StringChar c2)
Replace all occurrences of character 'c1' with 'c2'.
String& String::replace (const String & s1, const String & s2)
Replace all occurrences of StringData 's1' with StringData 's2'.
SizeType String::size () const
Returns the length of the string in bytes including the NULL terminator.
Referenced by utf8().
static String String::SpanToString (const char * start, const char * end) static
Referenced by ToString().
void String::split (const char * delimiter, Vector< String > & outElements) const
Split the string into its components separated by the given delimiter.
Referenced by insert().
bool String::startsWith (const char * text) const
Return true if the string starts with the given text.
Referenced by insert().
String String::substr (SizeType pos, SizeType len = -1) const
Referenced by insert(), and ColorI::set().
static String String::ToLower (const String & string) static
Referenced by ToString().
static String String::ToString (const char * format, ...) static
Referenced by ManagedSingleton< BasicSceneObjectPluginFactory >::createSingleton(), ManagedSingleton< BasicSceneObjectPluginFactory >::deleteSingleton(), ManagedSingleton< BasicSceneObjectPluginFactory >::instance(), operator!=(), and FModFNTable::Thunk< FN >::operator()().
static String String::ToString (bool v) static
static String String::ToString (U32 v) inline static
References ToString().
Referenced by ToString().
static String String::ToString (S32 v) inline static
References ToString().
Referenced by ToString().
static String String::ToString (F32 v) inline static
References ToString().
Referenced by ToString().
static String String::ToString (F64 v) inline static
References GetFirstNumber(), GetTrailingNumber(), intern(), isInterned(), SpanToString(), ToLower(), ToString(), and ToUpper().
Referenced by ToString().
static String String::ToUpper (const String & string) static
Referenced by ToString().
String String::trim () const
Remove leading and trailing whitespace.
Referenced by insert().
const UTF16* String::utf16 () const
Referenced by EngineTypeTraits< String >::ReturnValue().
const UTF8* String::utf8 () const inline
References c_str(), isEmpty(), length(), numChars(), and size().
static String String::VToString (const char * format, va_list args) static
Referenced by operator!=().
Friends And Related Function Documentation
String operator+ (const String & a, StringChar c) friend
Referenced by operator!=(), and FileName::operator=().
String operator+ (StringChar c, const String & a) friend
String operator+ (const String & a, const StringChar * b) friend
String operator+ (const String & a, const String & b) friend
String operator+ (const StringChar * a, const String & b) friend
Member Data Documentation
const String String::EmptyString static
A predefined empty string.
Referenced by GenericConstBufferLayout::ParamDesc::clear(), clear(), GuiTreeViewCtrl::clearFilterText(), Sim::findObject(), PostEffect::getPriority(), TSShapeInstance::getTargetName(), GFXPrimitiveBufferHandle::GFXPrimitiveBufferHandle(), and ColladaUtils::ImportOptions::reset().
const SizeType String::NPos static
Indicates 'not found' when using find() functions.
Copyright © GarageGames, LLC. All Rights Reserved.