InterpolatedChangeProperty< T, TimeSource > Class Template Reference
Main Modules Class List Namespace List Online
InterpolatedChangeProperty< T, TimeSource > Class Template Reference
A property that smoothly transitions to new values instead of assuming them right away.
#include <util/interpolatedChangeProperty.h>
Public Types
enum { DEFAULT_TRANSITION_TIME = 2000 }
typedef TimeSource TimeSourceType
typedef TimeSource::TickType TimeType
Public Member Functions
InterpolatedChangeProperty (const T &initialValue=T())
const T & getCurrentValue () const
Get the current value.
const TimeSourceType & geTimeSource () const
Return the time source to which interpolation synchronizes.
TimeSourceType & getTimeSource ()
void setTargetValue (const T &value)
Set the desired value.
void setTransitionCurve (const EaseF &ease)
Set the interpolation to use for going from one ambient color to a different one.
void setTransitionTime (TimeType time)
Set the amount of time it takes to go from one ambient color to a different one.
Protected Member Functions
void _update () const
Update mCurrentValue.
Protected Attributes
T mCurrentValue
The current value.
Transitioning
Transitioning allows to smoothly go from one value to a different one over a period of time.
TimeSourceType mTimeSource
TimeType mBlendPhaseTime
Number of milliseconds it takes to go from one value to a different one.
EaseF mTransitionCurve
Interpolation to use for going from source to target.
TimeType mTransitionStartTime
The time the transition started. If 0, no transition is in progress.
T mSourceValue
The value we are transitioning from.
T mTargetValue
The value we are transitioning to.
Detailed Description
template<typename T, class TimeSource = GenericTimeSource< SimMSTimer >>
class InterpolatedChangeProperty< T, TimeSource >
A property that smoothly transitions to new values instead of assuming them right away.
Parameters
T Value type. Must have "interpolate(from, to, factor)" method.
TimeSource Time source to which interpolation is synchronized.
Member Typedef Documentation
template<typename T, class TimeSource = GenericTimeSource< SimMSTimer >> typedef TimeSource InterpolatedChangeProperty< T, TimeSource >::TimeSourceType
template<typename T, class TimeSource = GenericTimeSource< SimMSTimer >> typedef TimeSource::TickType InterpolatedChangeProperty< T, TimeSource >::TimeType
Member Enumeration Documentation
template<typename T, class TimeSource = GenericTimeSource< SimMSTimer >> anonymous enum
Enumerator
DEFAULT_TRANSITION_TIME
Default time (in milliseconds) to go from one value to a new one.
Constructor & Destructor Documentation
template<typename T, class TimeSource = GenericTimeSource< SimMSTimer >> InterpolatedChangeProperty< T, TimeSource >::InterpolatedChangeProperty (const T & initialValue = T()) inline
Member Function Documentation
template<typename T , typename TimeSource > void InterpolatedChangeProperty< T, TimeSource >::_update () const protected
Update mCurrentValue.
References GenericTimeSource< Timer, Tick >::getPosition(), EaseF::getUnitValue(), InterpolatedChangeProperty< T, TimeSource >::mTargetValue, and InterpolatedChangeProperty< T, TimeSource >::mTransitionStartTime.
Referenced by InterpolatedChangeProperty< ColorF >::getCurrentValue().
template<typename T, class TimeSource = GenericTimeSource< SimMSTimer >> const T& InterpolatedChangeProperty< T, TimeSource >::getCurrentValue () const inline
Get the current value.
If a transition is in progress, this will be an interpolation of the last value and the new one.
Referenced by SceneManager::getAmbientLightColor(), and InterpolatedChangeProperty< T, TimeSource >::setTargetValue().
template<typename T, class TimeSource = GenericTimeSource< SimMSTimer >> const TimeSourceType& InterpolatedChangeProperty< T, TimeSource >::geTimeSource () const inline
Return the time source to which interpolation synchronizes.
template<typename T, class TimeSource = GenericTimeSource< SimMSTimer >> TimeSourceType& InterpolatedChangeProperty< T, TimeSource >::getTimeSource () inline
template<typename T, typename TimeSource > void InterpolatedChangeProperty< T, TimeSource >::setTargetValue (const T & value)
Set the desired value.
If this differs from the current value, a smooth blend to the given color will be initiated.
Parameters
value Desired value.
References InterpolatedChangeProperty< T, TimeSource >::getCurrentValue(), and GenericTimeSource< Timer, Tick >::getPosition().
Referenced by InterpolatedChangeProperty< ColorF >::setTransitionTime().
template<typename T, class TimeSource = GenericTimeSource< SimMSTimer >> void InterpolatedChangeProperty< T, TimeSource >::setTransitionCurve (const EaseF & ease) inline
Set the interpolation to use for going from one ambient color to a different one.
Referenced by SceneManager::setAmbientLightTransitionCurve().
template<typename T, class TimeSource = GenericTimeSource< SimMSTimer >> void InterpolatedChangeProperty< T, TimeSource >::setTransitionTime (TimeType time) inline
Set the amount of time it takes to go from one ambient color to a different one.
Referenced by SceneManager::setAmbientLightTransitionTime().
Member Data Documentation
template<typename T, class TimeSource = GenericTimeSource< SimMSTimer >> TimeType InterpolatedChangeProperty< T, TimeSource >::mBlendPhaseTime protected
Number of milliseconds it takes to go from one value to a different one.
template<typename T, class TimeSource = GenericTimeSource< SimMSTimer >> T InterpolatedChangeProperty< T, TimeSource >::mCurrentValue mutable protected
The current value.
Referenced by InterpolatedChangeProperty< ColorF >::getCurrentValue().
template<typename T, class TimeSource = GenericTimeSource< SimMSTimer >> T InterpolatedChangeProperty< T, TimeSource >::mSourceValue protected
The value we are transitioning from.
template<typename T, class TimeSource = GenericTimeSource< SimMSTimer >> T InterpolatedChangeProperty< T, TimeSource >::mTargetValue protected
The value we are transitioning to.
Referenced by InterpolatedChangeProperty< T, TimeSource >::_update().
template<typename T, class TimeSource = GenericTimeSource< SimMSTimer >> TimeSourceType InterpolatedChangeProperty< T, TimeSource >::mTimeSource protected
Referenced by InterpolatedChangeProperty< ColorF >::geTimeSource(), and InterpolatedChangeProperty< ColorF >::getTimeSource().
template<typename T, class TimeSource = GenericTimeSource< SimMSTimer >> EaseF InterpolatedChangeProperty< T, TimeSource >::mTransitionCurve protected
Interpolation to use for going from source to target.
template<typename T, class TimeSource = GenericTimeSource< SimMSTimer >> TimeType InterpolatedChangeProperty< T, TimeSource >::mTransitionStartTime mutable protected
The time the transition started. If 0, no transition is in progress.
Referenced by InterpolatedChangeProperty< T, TimeSource >::_update().
Copyright © GarageGames, LLC. All Rights Reserved.