WeakRefPtr< T > Class Template Reference
Main Modules Class List Namespace List Online
WeakRefPtr< T > Class Template Reference
Weak reference pointer class.
#include <core/util/refBase.h>
Inherited by SimObjectPtr< T >, SimObjectPtr< AccumulationVolume >, SimObjectPtr< AdvancedLightBinManager >, SimObjectPtr< AIPlayer >, SimObjectPtr< AssetTagsManifest >, SimObjectPtr< ConvexShape >, SimObjectPtr< DecalRoad >, SimObjectPtr< DynamicShadowRenderPassManager >, SimObjectPtr< Entity >, SimObjectPtr< EventManager >, SimObjectPtr< Forest >, SimObjectPtr< ForestTool >, SimObjectPtr< GameBase >, SimObjectPtr< Gizmo >, SimObjectPtr< GuiButtonCtrl >, SimObjectPtr< GuiCanvas >, SimObjectPtr< GuiControl >, SimObjectPtr< GuiControlProfile >, SimObjectPtr< GuiCursor >, SimObjectPtr< GuiInspector >, SimObjectPtr< GuiInspectorField >, SimObjectPtr< GuiOffscreenCanvas >, SimObjectPtr< GuiTextEditCtrl >, SimObjectPtr< Material >, SimObjectPtr< MeshRoad >, SimObjectPtr< MissionArea >, SimObjectPtr< ModuleDefinition >, SimObjectPtr< NavMesh >, SimObjectPtr< NetConnection >, SimObjectPtr< NetObject >, SimObjectPtr< ParticleEmitter >, SimObjectPtr< PhysicsShape >, SimObjectPtr< PostEffect >, SimObjectPtr< RenderPassManager >, SimObjectPtr< RenderPassStateToken >, SimObjectPtr< RenderPrePassMgr >, SimObjectPtr< Ribbon >, SimObjectPtr< River >, SimObjectPtr< SceneObject >, SimObjectPtr< SFXDescription >, SimObjectPtr< SFXSource >, SimObjectPtr< SFXTrack >, SimObjectPtr< ShadowRenderPassManager >, SimObjectPtr< ShapeAsset >, SimObjectPtr< ShapeBase >, SimObjectPtr< SimGroup >, SimObjectPtr< SimObject >, SimObjectPtr< SimSet >, SimObjectPtr< SimXMLDocument >, SimObjectPtr< TerrainBlock >, and SimObjectPtr< WorldEditorSelection >.
Public Member Functions
WeakRefPtr ()
WeakRefPtr (T *ptr)
WeakRefPtr (const WeakRefPtr< T > &ref)
~WeakRefPtr ()
T * getPointer () const
Returns the pointer.
bool isNull () const
Returns true if the pointer is not set.
bool isValid () const
Returns true if the pointer is set.
operator T * () const
T & operator* () const
T * operator-> () const
WeakRefPtr< T > & operator= (const WeakRefPtr< T > &ref)
WeakRefPtr< T > & operator= (T *ptr)
Protected Member Functions
void set (WeakRefBase::WeakReference *ref)
void set (T *obj)
Detailed Description
template<class T>
class WeakRefPtr< T >
Weak reference pointer class.
Instances of this template class can be used as pointers to instances of WeakRefBase and its subclasses. When the object referenced by a WeakRefPtr instance is deleted, the pointer to the object is set to NULL in the WeakRefPtr instance.
Constructor & Destructor Documentation
template<class T> WeakRefPtr< T >::WeakRefPtr () inline
template<class T> WeakRefPtr< T >::WeakRefPtr (T * ptr) inline
template<class T> WeakRefPtr< T >::WeakRefPtr (const WeakRefPtr< T > & ref) inline
template<class T> WeakRefPtr< T >::~WeakRefPtr () inline
Member Function Documentation
template<class T> T* WeakRefPtr< T >::getPointer () const inline
Returns the pointer.
Referenced by SFXDSVoice::_getBuffer(), SFXALVoice::_getBuffer(), SFXFMODVoice::_getBuffer(), SFXXAudioVoice::_getBuffer(), and SFXFMODEventSource::getEvent().
template<class T> bool WeakRefPtr< T >::isNull (void) const inline
Returns true if the pointer is not set.
Referenced by NetConnection::isLocalConnection(), AssetPtr< ShapeAsset >::isNull(), and AssetPtr< ShapeAsset >::notNull().
template<class T> bool WeakRefPtr< T >::isValid () const inline
Returns true if the pointer is set.
Referenced by RenderPassStateBin::_getStateToken(), and SFXSource::isLooping().
template<class T> WeakRefPtr< T >::operator T * () const inline
template<class T> T& WeakRefPtr< T >::operator* (void) const inline
template<class T> T* WeakRefPtr< T >::operator-> (void) const inline
template<class T> WeakRefPtr<T>& WeakRefPtr< T >::operator= (const WeakRefPtr< T > & ref) inline
template<class T> WeakRefPtr<T>& WeakRefPtr< T >::operator= (T * ptr) inline
template<class T> void WeakRefPtr< T >::set (WeakRefBase::WeakReference * ref) inline protected
template<class T> void WeakRefPtr< T >::set (T * obj) inline protected
Copyright © GarageGames, LLC. All Rights Reserved.