ThreadManager Class Reference
Main Modules Class List Namespace List Online
ThreadManager Class Reference
#include <platform/threads/thread.h>
Public Member Functions
ThreadManager ()
Static Public Member Functions
static void addThread (Thread *thread)
Each thread should add itself to the thread pool the first time it runs.
static bool compare (U32 threadId_1, U32 threadId_2)
Returns true if the 2 thread ids represent the same thread.
static Thread * getCurrentThread ()
static U32 getCurrentThreadId ()
Returns the platform specific thread id of the calling thread.
static U32 getMainThreadId ()
Returns the platform specific thread id ot the main thread.
static const char * getSingletonName ()
static Thread * getThreadById (U32 threadid)
Searches the pool of known threads for a thread whose id is equivalent to the given threadid.
static bool isCurrentThread (U32 threadId)
Returns true if threadId is the same as the calling thread's id.
static bool isMainThread ()
Return true if the caller is running on the main thread.
static void removeThread (Thread *thread)
Constructor & Destructor Documentation
ThreadManager::ThreadManager () inline
Member Function Documentation
static void ThreadManager::addThread (Thread * thread) inline static
Each thread should add itself to the thread pool the first time it runs.
References Thread::getId(), ManagedSingleton< T >::instance(), Mutex::lock(), Vector< T >::push_back(), and Mutex::unlock().
static bool ThreadManager::compare (U32 threadId_1, U32 threadId_2) static
Returns true if the 2 thread ids represent the same thread.
Some thread APIs return an opaque object as a thread id, so the == operator cannot reliably compare thread ids.
Referenced by SFXInternal::isSFXThread().
static Thread* ThreadManager::getCurrentThread () inline static
References getCurrentThreadId().
static U32 ThreadManager::getCurrentThreadId () static
Returns the platform specific thread id of the calling thread.
Some platforms do not guarantee that this ID stays the same over the life of the thread, so use ThreadManager::compare() to compare thread ids.
Referenced by getCurrentThread(), isMainThread(), and SFXInternal::isSFXThread().
static U32 ThreadManager::getMainThreadId () inline static
Returns the platform specific thread id ot the main thread.
Referenced by SFXInternal::isSFXThread().
static const char* ThreadManager::getSingletonName () inline static
static Thread* ThreadManager::getThreadById (U32 threadid) inline static
Searches the pool of known threads for a thread whose id is equivalent to the given threadid.
Compares thread ids with ThreadManager::compare().
References Thread::getId(), ManagedSingleton< T >::instance(), Mutex::lock(), Vector< T >::size(), and Mutex::unlock().
bool ThreadManager::isCurrentThread (U32 threadId) inline static
Returns true if threadId is the same as the calling thread's id.
bool ThreadManager::isMainThread () inline static
Return true if the caller is running on the main thread.
References getCurrentThreadId().
static void ThreadManager::removeThread (Thread * thread) inline static
References Vector< T >::erase(), Thread::getId(), ManagedSingleton< T >::instance(), Mutex::lock(), Vector< T >::size(), and Mutex::unlock().
Copyright © GarageGames, LLC. All Rights Reserved.