CollisionComponent Class Reference
Main Modules Class List Namespace List Online
CollisionComponent Class Reference
#include <T3D/components/collision/collisionComponent.h>
Public Types
enum MeshType {
None = 0,
Bounds = 1,
CollisionMesh = 2,
VisibleMesh = 3
}
Public Types inherited from Component
enum NetMaskBits {
InitialUpdateMask = BIT(0),
OwnerMask = BIT(1),
UpdateMask = BIT(2),
EnableMask = BIT(3),
NextFreeMask = BIT(4)
}
usage functions are used by the various engine-based behaviors to integrate with the component classes
Public Types inherited from SimGroup
typedef SimSet Parent
Public Types inherited from SimSet
typedef SimObject Parent
enum SetModification {
SetCleared,
SetObjectAdded,
SetObjectRemoved
}
typedef Signal< void(SetModification modification, SimSet *set, SimObject *object) > SetModificationSignal
Signal for letting observers know when objects are added to or removed from the set.
typedef SimObjectList::iterator iterator
typedef SimObjectList::value_type value
Public Types inherited from SimObject
typedef ConsoleObject Parent
enum WriteFlags {
SelectedOnly = BIT(0),
NoName = BIT(1),
IgnoreCanSave = BIT(2)
}
Flags passed to SimObject::write.
Public Types inherited from EngineObject
typedef void(* DebugEnumInstancesCallback) (EngineObject *)
Type of callback function for iterating over EngineObject instances.
Public Types inherited from CollisionInterface
enum PublicConstants { CollisionTimeoutValue = 250 }
Public Member Functions
CollisionComponent ()
virtual ~CollisionComponent ()
PhysicsCollision * buildColShapes ()
virtual bool buildPolyList (PolyListContext context, AbstractPolyList *polyList, const Box3F &box, const SphereF &sphere)
virtual bool castRay (const Point3F &start, const Point3F &end, RayInfo *info)
virtual void checkDependencies ()
virtual void componentAddedToOwner (Component *comp)
virtual void componentRemovedFromOwner (Component *comp)
DECLARE_CONOBJECT (CollisionComponent)
S32 getBestCollision (Point3F upVector)
F32 getBestCollisionAngle (VectorF upVector)
F32 getCollisionAngle (S32 collisionIndex, Point3F upVector)
S32 getCollisionCount ()
virtual PhysicsCollision * getCollisionData ()
Point3F getCollisionNormal (S32 collisionIndex)
Point3F getContactNormal ()
bool hasContact ()
void inspectPostApply ()
Called after any property of the object is changed in the world editor.
virtual void onComponentAdd ()
virtual void onComponentRemove ()
virtual void ownerTransformSet (MatrixF *mat)
virtual U32 packUpdate (NetConnection *con, U32 mask, BitStream *stream)
Instructs this object to pack its state for transfer over the network.
void prepCollision ()
virtual void processTick ()
void targetShapeChanged (RenderComponentInterface *instanceInterface)
virtual void unpackUpdate (NetConnection *con, BitStream *stream)
Instructs this object to read state data previously packed with packUpdate.
void updatePhysics ()
Public Member Functions inherited from Component
Component ()
virtual ~Component ()
virtual void advanceTime (F32 dt)
void checkComponentFieldModified (const char *slotName, const char *newValue)
This is what we actually use to check if the modified field is one of our behavior fields. If it is, we update and make the correct callbacks.
DECLARE_CONOBJECT (Component)
Entity * getOwner ()
virtual void interpolateTick (F32 dt)
bool isActive ()
bool isEnabled ()
virtual bool onAdd ()
Called when the object is added to the sim.
virtual void onDynamicModified (const char *slotName, const char *newValue=NULL)
Called when a dynamic field is modified.
virtual void onRemove ()
Called when the object is removed from the sim.
virtual void onStaticModified (const char *slotName, const char *newValue)
Called when a static field is modified.
virtual void packToStream (Stream &stream, U32 tabStop, S32 behaviorID, U32 flags=0)
virtual void setDataField (StringTableEntry slotName, const char *array, const char *value)
void setEnabled (bool toggle)
void setOwner (Entity *pOwner)
void addComponentField (const char *fieldName, const char *desc, const char *type, const char *defaultValue=NULL, const char *userData=NULL, bool hidden=false)
Adds a named field to a Component that can specify a description, data type, default value and userData.
S32 getComponentFieldCount ()
Returns the number of ComponentField's on this template.
ComponentField * getComponentField (S32 idx)
Gets a ComponentField by its index in the mFields vector.
ComponentField * getComponentField (const char *fieldName)
const char * getComponentType ()
const char * getDescriptionText (const char *desc)
const char * getName ()
const char * getFriendlyName ()
bool isNetworked ()
void beginFieldGroup (const char *groupName)
void endFieldGroup ()
void addDependency (StringTableEntry name)
Public Member Functions inherited from NetObject
NetObject ()
~NetObject ()
virtual void clearMaskBits (U32 orMask)
Clear the specified bits from the dirty mask.
void clearScopeAlways ()
Stop scoping the object to all connections.
virtual String describeSelf () const
Return a textual description of the object.
virtual U32 filterMaskBits (U32 mask, NetConnection *connection)
U32 getNetIndex ()
Get the ghost index of this object.
virtual F32 getUpdatePriority (CameraScopeQuery *focusObject, U32 updateMask, S32 updateSkips)
This returns a value which is used to prioritize which objects need to be updated.
bool isClientObject () const
Is this a client object?
bool isGhost () const
Is this is a ghost?
bool isGhostable () const
Is this object ghostable?
bool isGhostAlways () const
Should this object always be ghosted?
bool isScopeable () const
Is this object subject to scoping?
bool isScopeLocal () const
Should this object only be visible to the client which created it?
bool isServerObject () const
Is this a server object?
virtual void onCameraScopeQuery (NetConnection *cr, CameraScopeQuery *camInfo)
Queries the object about information used to determine scope.
virtual void setMaskBits (U32 orMask)
Used to mark a bit as dirty; ie, that its corresponding set of fields need to be transmitted next update.
void setScopeAlways ()
Scope the object to all connections.
DECLARE_CONOBJECT (NetObject)
NetObject * getServerObject () const
Returns a pointer to the server object when on a local connection.
NetObject * getClientObject () const
Returns a pointer to the client object when on a local connection.
Public Member Functions inherited from SimGroup
~SimGroup ()
void addObject (SimObject *object, SimObjectId id)
void addObject (SimObject *object, const char *name)
virtual void addObject (SimObject *object)
Add the given object to the set.
virtual void clear ()
Remove all objects from this set.
virtual SimGroup * clone ()
Return a shallow copy of this object.
DECLARE_CONOBJECT (SimGroup)
virtual SimGroup * deepClone ()
Return a deep copy of this object.
virtual SimObject * findObject (const char *name)
Find a named sub-object of this object.
virtual void popObject ()
Remove an object from the end of the list.
virtual bool processArguments (S32 argc, ConsoleValueRef *argv)
Process constructor options. (ie, new SimObject(1,2,3))
virtual void pushObject (SimObject *object)
Add the given object to the end of the object list of this set.
virtual void removeObject (SimObject *object)
Remove the given object from the set.
Public Member Functions inherited from SimSet
SimSet ()
~SimSet ()
virtual void addTamlChild (SimObject *pSimObject)
Called when Taml attempts to populate an objects children during a read.
void callOnChildren (const String &method, S32 argc, ConsoleValueRef argv[], bool executeOnChildGroups=true)
DECLARE_CONOBJECT (SimSet)
SimObject * findObject (SimObject *object)
Find the given object in this set.
template<class T >
void findObjectByCallback (bool(*fn)(T *), Vector< T * > &foundObjects)
Add all child objects (including children of children) to the foundObjects Vector which are of type T and for which DecideAddObjectCallback return true;.
virtual SimObject * findObjectByInternalName (StringTableEntry internalName, bool searchChildren=false)
SimObject * findObjectByLineNumber (const char *fileName, S32 declarationLine, bool searchChildren=false)
template<class T >
void findObjectByType (Vector< T * > &foundObjects)
Add all child objects (including children of children) to the foundObjects Vector which are of type T.
SimObject * getRandom ()
const SetModificationSignal & getSetModificationSignal () const
Return the signal that is triggered when an object is added to or removed from the set.
SetModificationSignal & getSetModificationSignal ()
virtual SimObject * getTamlChild (const U32 childIndex) const
Called when Taml attempts to compile a list of children.
virtual U32 getTamlChildCount (void) const
Called when Taml attempts to compile a list of children.
void lock ()
virtual void onDeleteNotify (SimObject *object)
Called when a SimObject is deleted.
virtual bool readObject (Stream *stream)
U32 sizeRecursive ()
Return the number of objects in this set as well as all sets that are contained in this set and its children.
void unlock ()
virtual void write (Stream &stream, U32 tabStop, U32 flags=0)
Output the TorqueScript to recreate this object.
virtual bool writeObject (Stream *stream)
virtual bool acceptsAsChild (SimObject *object) const
Return true if this set accepts the given object as a child.
void deleteAllObjects ()
Deletes all the objects in the set.
void bringObjectToFront (SimObject *obj)
void pushObjectToBack (SimObject *obj)
void scriptSort (const String &scriptCallbackFn)
Performs a sort of the objects in the set using a script callback function to do the comparison.
SimObject * front ()
SimObject * first ()
SimObject * last ()
bool empty () const
S32 size () const
iterator begin ()
iterator end ()
value operator[] (S32 index)
iterator find (iterator first, iterator last, SimObject *obj)
iterator find (SimObject *obj)
virtual bool reOrder (SimObject *obj, SimObject *target=0)
Reorder the position of "obj" to either be the last object in the list or, if "target" is given, to come before "target" in the list of children.
SimObject * at (S32 index) const
Return the object at the given index.
Public Member Functions inherited from SimObject
virtual void copyTo (SimObject *object)
Copy SimObject to another SimObject (Originally designed for T2D).
DECLARE_CONOBJECT (SimObject)
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
virtual void getConsoleMethodData (const char *fname, S32 routingId, S32 *type, S32 *minArgs, S32 *maxArgs, void **callback, const char **usage)
Namespace * getNamespace ()
Return the object's namespace.
StringTableEntry getProgenitorFile (void) const
virtual bool handlesConsoleMethod (const char *fname, S32 *routingId)
void setProgenitorFile (const char *pFile)
const char * tabComplete (const char *prevText, S32 baseLen, bool)
Get next matching item in namespace.
virtual bool writeField (StringTableEntry fieldname, const char *value)
Determine whether or not a field should be written.
virtual void writeFields (Stream &stream, U32 tabStop)
Write the fields of this object in TorqueScript.
void setCanSaveDynamicFields (bool bCanSave)
Set whether fields created at runtime should be saved. Default is true.
bool getCanSaveDynamicFields ()
Get whether fields created at runtime should be saved. Default is true.
SimObject * getCopySource () const
Return the object that this object is copying fields from.
void setCopySource (SimObject *object)
Set the object that this object should be copying fields from.
void assignFieldsFrom (SimObject *obj)
Copy fields from another object onto this one.
void assignDynamicFieldsFrom (SimObject *obj)
Copy dynamic fields from another object onto this one.
Notify * removeNotify (void *ptr, Notify::Type)
Remove a notification from the list.
void deleteNotify (SimObject *obj)
Notify an object when we are deleted.
void clearNotify (SimObject *obj)
Notify an object when we are cleared.
void clearAllNotifications ()
Remove all notifications for this object.
void processDeleteNotifies ()
Send out deletion notifications.
void registerReference (SimObject **obj)
Register a reference to this object.
void unregisterReference (SimObject **obj)
Unregister a reference to this object.
SimPersistID * getPersistentId () const
Return the persistent ID assigned to this object or NULL.
SimPersistID * getOrCreatePersistentId ()
Return the persistent ID assigned to this object or assign one to it if it has none.
StringTableEntry getClassNamespace () const
Return name of class namespace set on this object.
StringTableEntry getSuperClassNamespace () const
Return name of superclass namespace set on this object.
void setClassNamespace (const char *classNamespace)
void setSuperClassNamespace (const char *superClassNamespace)
const char * getDataField (StringTableEntry slotName, const char *array)
Get the value of a field on the object.
void setDataField (StringTableEntry slotName, const char *array, const char *value)
Set the value of a field on the object.
const char * getPrefixedDataField (StringTableEntry fieldName, const char *array)
void setPrefixedDataField (StringTableEntry fieldName, const char *array, const char *value)
const char * getPrefixedDynamicDataField (StringTableEntry fieldName, const char *array, const S32 fieldType=-1)
void setPrefixedDynamicDataField (StringTableEntry fieldName, const char *array, const char *value, const S32 fieldType=-1)
StringTableEntry getDataFieldPrefix (StringTableEntry fieldName)
U32 getDataFieldType (StringTableEntry slotName, const char *array)
Get the type of a field on the object.
void setDataFieldType (const U32 fieldTypeId, StringTableEntry slotName, const char *array)
Set the type of a dynamic field on the object.
void setDataFieldType (const char *typeName, StringTableEntry slotName, const char *array)
SimFieldDictionary * getFieldDictionary ()
Get reference to the dictionary containing dynamic fields.
virtual StringTableEntry getComponentName ()
void setInternalName (const char *newname)
These functions support internal naming that is not namespace bound for locating child controls in a generic way.
StringTableEntry getInternalName () const
Get the internal name of this control.
void setOriginalName (const char *originalName)
Set the original name of this control.
StringTableEntry getOriginalName () const
Get the original name of this control.
void setFilename (const char *file)
These functions allow you to set and access the filename where this object was created.
StringTableEntry getFilename () const
Get the filename.
void setDeclarationLine (U32 lineNumber)
These functions are used to track the line number (1-based) on which the object was created if it was loaded from script.
S32 getDeclarationLine () const
Get the declaration line number.
virtual bool save (const char *pcFilePath, bool bOnlySelected=false, const char *preappend=NULL)
Save object as a TorqueScript File.
virtual bool isMethod (const char *methodName)
Check if a method exists in the objects current namespace.
virtual bool isField (const char *fieldName, bool includeStatic=true, bool includeDynamic=true)
Return true if the field is defined on the object.
SimObjectId getId () const
Return the unique numeric object ID.
const char * getIdString () const
Return the object ID as a string.
StringTableEntry getName () const
Return the name of this object.
SimGroup * getGroup () const
Return the SimGroup that this object is contained in.
void assignName (const char *name)
Assign the given name to this object.
void setId (SimObjectId id)
bool isChildOfGroup (SimGroup *pGroup)
bool isProperlyAdded () const
bool isDeleted () const
bool isRemoved () const
virtual bool isLocked () const
virtual void setLocked (bool b)
virtual bool isHidden () const
virtual void setHidden (bool b)
bool isSelected () const
bool isExpanded () const
bool isEditorOnly () const
bool isNameChangeAllowed () const
bool isAutoDeleted () const
void setSelected (bool sel)
void setExpanded (bool exp)
void setModDynamicFields (bool dyn)
void setModStaticFields (bool sta)
bool canModDynamicFields ()
bool canModStaticFields ()
void setAutoDelete (bool val)
void setEditorOnly (bool val)
void setNameChangeAllowed (bool val)
bool getCanSave () const
Returns boolean specifying if the object can be serialized.
virtual void setCanSave (bool val)
Set serialization flag.
bool isSelectedRecursive () const
Returns true if this object is selected or any group it is a member of is.
SimObject ()
virtual ~SimObject ()
virtual void onGroupAdd ()
Called when the object is added to a SimGroup.
virtual void onGroupRemove ()
Called when the object is removed from a SimGroup.
virtual void onNameChange (const char *name)
Called when the object's name is changed.
virtual void onPostAdd ()
Called when the adding of the object to the sim is complete, all sub-objects have been processed as well.
virtual void inspectPreApply ()
Called before any property of the object is changed in the world editor.
virtual void onEditorEnable ()
Called when the editor is activated.
virtual void onEditorDisable ()
Called when the editor is deactivated.
bool registerObject ()
Register an object with the object system.
bool registerObject (U32 id)
Register the object, forcing the id.
bool registerObject (const char *name)
Register the object, assigning the name.
bool registerObject (const char *name, U32 id)
Register the object, assigning a name and ID.
void unregisterObject ()
Unregister the object from Sim.
void deleteObject ()
Unregister, mark as deleted, and free the object.
void safeDeleteObject ()
Performs a safe delayed delete of the object using a sim event.
bool addToSet (SimObjectId)
bool addToSet (const char *)
bool removeFromSet (SimObjectId)
bool removeFromSet (const char *)
void dumpToConsole (bool includeFunctions=true)
Dump the contents of this object to the console.
virtual void dumpClassHierarchy ()
added this so that you can print the entire class hierarchy, including script objects,
virtual void dumpGroupHierarchy ()
Print the SimGroup hierarchy of this object to the console.
Public Member Functions inherited from ConsoleObject
ConsoleObject ()
virtual AbstractClassRep * getClassRep () const
Gets the ClassRep.
const AbstractClassRep::Field * findField (StringTableEntry fieldName) const
Get a reference to a field by name.
bool setField (const char *fieldName, const char *value)
Set the value of a field.
void logMessage (const char *fmt,...) const
Logs with Con::printf.
void logWarning (const char *fmt,...) const
Logs with Con::warnf.
void logError (const char *fmt,...) const
Logs with Con::errorf.
const AbstractClassRep::FieldList & getFieldList () const
Get a list of all the fields. This information cannot be modified.
AbstractClassRep::FieldList & getModifiableFieldList ()
Get a list of all the fields, set up so we can modify them.
bool & getDynamicGroupExpand ()
Get a handle to a boolean telling us if we expanded the dynamic group.
S32 getClassId (U32 netClassGroup) const
Get our network-layer class id.
StringTableEntry getClassName () const
Get our compiler and platform independent class name.
Public Member Functions inherited from EngineObject
EngineObject ()
virtual ~EngineObject ()
DECLARE_ABSTRACT_CLASS (EngineObject, void)
DECLARE_INSCOPE (_GLOBALSCOPE)
IEngineObjectPool * getEngineObjectPool () const
Return the pool of EngineObjects to which this object belongs.
void operator delete (void *ptr)
Release the given object's memory in the pool it has been allocated from.
void * operator new (size_t size)
void * operator new (size_t size, IEngineObjectPool *pool)
void * operator new (size_t size TORQUE_TMM_ARGS_DECL)
Allocate a new object in the default object pool.
void * operator new (size_t size, IEngineObjectPool *pool TORQUE_TMM_ARGS_DECL)
Allocate a new object in the given object pool.
void * operator new (size_t size, void *ptr)
Placement new.
Public Member Functions inherited from StrongRefBase
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Public Member Functions inherited from Interface< UpdateInterface >
Interface ()
virtual ~Interface ()
Public Member Functions inherited from CollisionInterface
void clearCollisionList ()
void clearCollisionNotifyList ()
bool doesBlockColliding ()
Collision * getCollision (S32 col)
CollisionList * getCollisionList ()
checkCollisions
ContactInfo * getContactInfo ()
Convex * getConvexList ()
void handleCollision (Collision &col, VectorF velocity)
handleCollision This will take a collision and queue the collision info for the object so that in knows about the collision.
void handleCollisionList (CollisionList &collisionList, VectorF velocity)
handleCollisionList This basically takes in a CollisionList and calls handleCollision for each.
Static Public Member Functions
static void initPersistFields ()
Static Public Member Functions inherited from Component
static bool _setEnabled (void *object, const char *index, const char *data)
static void initPersistFields ()
static bool setOwner (void *object, const char *index, const char *data)
static bool setDescription (void *object, const char *index, const char *data)
static const char * getDescription (void *obj, const char *data)
Static Public Member Functions inherited from NetObject
static void collapseDirtyList ()
static void initPersistFields ()
template<class T >
static T * getServerObject (T *netObj)
Template form for the callers convenience.
template<class T >
static T * getClientObject (T *netObj)
Template form for the callers convenience.
Static Public Member Functions inherited from SimObject
static SimObject * __findObject (const char *id)
static const char * __getObjectId (ConsoleObject *object)
static void initPersistFields ()
static void setForcedId (SimObjectId id)
Force an Id on the next registered object.
Static Public Member Functions inherited from ConsoleObject
static const char * __category ()
static const char * __description ()
static void consoleInit ()
Register global constant variables and do other one-time initialization tasks in a subclass of ConsoleObject.
static void initPersistFields ()
Register dynamic fields in a subclass of ConsoleObject.
static const char * lookupClassName (const U32 in_classTag)
Get the classname from a class tag.
static AbstractClassRep * getStaticClassRep ()
Get the abstract class information for this class.
static AbstractClassRep * getParentStaticClassRep ()
Get the abstract class information for this class's superclass.
static ConsoleObject * create (const char *in_pClassName)
static ConsoleObject * create (const U32 groupId, const U32 typeId, const U32 in_classId)
static void addGroup (const char *in_pGroupname, const char *in_pGroupDocs=NULL)
Mark the beginning of a group of fields.
static void endGroup (const char *in_pGroupname)
Mark the end of a group of fields.
static void addArray (const char *arrayName, S32 count)
Marks the start of a fixed size array of fields.
static void endArray (const char *arrayName)
Marks the end of an array of fields.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a complex field.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::WriteDataNotify in_writeDataFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, const char *in_pFieldDocs, U32 flags=0)
Register a simple field.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::WriteDataNotify in_writeDataFn, const char *in_pFieldDocs, U32 flags=0)
static void addFieldV (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, TypeValidator *v, const char *in_pFieldDocs=NULL)
Register a validated field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, AbstractClassRep::WriteDataNotify in_writeDataFn=&defaultProtectedWriteFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a complex protected field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, AbstractClassRep::WriteDataNotify in_writeDataFn=&defaultProtectedWriteFn, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a simple protected field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addDeprecatedField (const char *fieldName)
Add a deprecated field.
static bool removeField (const char *in_pFieldname)
Remove a field.
static ConsoleObject * __findObject (const char *)
static const char * __getObjectId (ConsoleObject *)
Static Public Member Functions inherited from EngineObject
static void debugDumpInstances ()
Dump describeSelf()s of all live ConsoleObjects to the console.
static void debugEnumInstances (const std::type_info &type, DebugEnumInstancesCallback callback)
Call the given callback for all instances of the given type.
static void debugEnumInstances (const char *className, DebugEnumInstancesCallback callback)
Same as above but uses an export class name and also includes inheritance (i.e.
Public Attributes
PhysicsBody * mPhysicsRep
PhysicsWorld * mPhysicsWorld
Public Attributes inherited from Component
Signal< void(SimObject *, String, String) > onDataSet
Public Attributes inherited from EngineObject
DECLARE_INSTANTIABLE
Public Attributes inherited from CollisionInterface
Signal< void(PhysicsCollision *collision) > onCollisionChanged
Signal< void(SceneObject *) > onCollisionSignal
Signal< void(SceneObject *) > onContactSignal
Protected Types
enum { ColliderMask = Parent::NextFreeMask }
Protected Types inherited from NetObject
enum NetFlags {
IsGhost = BIT(1),
ScopeAlways = BIT(6),
ScopeLocal = BIT(7),
Ghostable = BIT(8),
MaxNetFlagBit = 15
}
Protected Types inherited from EngineObject
typedef ::FalseType __IsDisposableType
typedef ::FalseType __IsSingletonType
Protected Attributes
StringTableEntry colisionMeshPrefix
bool mAnimated
Vector< S32 > mCollisionDetails
MeshType mCollisionType
MeshType mDecalType
Vector< S32 > mLOSDetails
MeshType mLOSType
PhysicsComponentInterface * mOwnerPhysicsInterface
RenderComponentInterface * mOwnerRenderInterface
Protected Attributes inherited from Component
U32 componentIdx
StringTableEntry mComponentGroup
StringTableEntry mComponentType
Vector< StringTableEntry > mDependencies
StringTableEntry mDescription
bool mEnabled
Vector< ComponentField > mFields
StringTableEntry mFriendlyName
StringTableEntry mFromResource
bool mHidden
bool mNetworked
StringTableEntry mNetworkType
Entity * mOwner
StringTableEntry mTemplateName
Protected Attributes inherited from NetObject
SimObjectPtr< NetObject > mClientObject
Pointer to the client object on a local connection.
GhostInfo * mFirstObjectRef
Head of a linked list storing GhostInfos referencing this NetObject.
BitSet32 mNetFlags
Flag values from NetFlags.
U32 mNetIndex
The index of this ghost in the GhostManager on the server.
SimObjectPtr< NetObject > mServerObject
Pointer to the server object on a local connection.
Protected Attributes inherited from SimSet
void * mMutex
SetModificationSignal mSetModificationSignal
Signal that is triggered when objects are added or removed from the set.
SimObjectList objectList
Protected Attributes inherited from SimObject
DEFINE_CREATE_METHOD
SimObjectId mId
Id number for this object.
StringTableEntry mInternalName
Internal name assigned to the object. Not set by default.
return object
bool mCanSaveFieldDictionary
Whether dynamic fields should be saved out in serialization. Defaults to true.
SimPersistID * mPersistentId
Persistent ID assigned to this object.
Namespace * mNameSpace
The namespace in which method lookup for this object begins.
StringTableEntry mClassName
Name of namespace to use as class namespace.
StringTableEntry mSuperClassName
Name of namespace to use as class super namespace.
Protected Attributes inherited from EngineObject
DEFINE_CREATE_METHOD
return object
Protected Attributes inherited from StrongRefBase
U32 mRefCount
reference counter for StrongRefPtr objects
Protected Attributes inherited from CollisionInterface
U32 CollisionMoveMask
bool mBlockColliding
CollisionList mCollisionList
Vector< CollisionInterface * > mCollisionNotifyList
ContactInfo mContactInfo
Convex * mConvexList
CollisionTimeout * mTimeoutList
Box3F mWorkingQueryBox
Additional Inherited Members
Static Public Attributes inherited from ConsoleObject
static const bool __smIsDatablock = false
Subclasses of ConsoleObjects that are datablocks should redefine this static member variable and set it to true.
Static Public Attributes inherited from Interface< UpdateInterface >
static Vector< UpdateInterface * > all
Protected Member Functions inherited from SimSet
DECLARE_CALLBACK (void, onObjectAdded,(SimObject *object))
DECLARE_CALLBACK (void, onObjectRemoved,(SimObject *object))
Protected Member Functions inherited from SimObject
virtual void _destroySelf ()
Subclasses should overload this method instead of the public destroySelf().
virtual String _getLogMessage (const char *fmt, va_list args) const
We can provide more detail, like object name and id.
virtual void _onSelected ()
Called when the object is selected in the editor.
virtual void _onUnselected ()
Called when the object is unselected in the editor.
object incRefCount ()
virtual void onTamlAddParent (SimObject *pParentObject)
Called after Taml has finished reading the object and has added the object to any parent.
virtual void onTamlCustomRead (const TamlCustomNodes &customNodes)
Called during the reading of the object to allow custom properties to be read.
virtual void onTamlCustomWrite (TamlCustomNodes &customNodes)
Called during the writing of the object to allow custom properties to be written.
virtual void onTamlPostRead (const TamlCustomNodes &customNodes)
Called after Taml has finished reading the object.
virtual void onTamlPostWrite (void)
Called after Taml has finished writing the object.
virtual void onTamlPreRead (void)
Called prior to Taml reading the object.
virtual void onTamlPreWrite (void)
Taml callbacks.
object registerObject ()
void linkNamespaces ()
Perform namespace linking on this object.
void unlinkNamespaces ()
Undo namespace linking on this object.
Protected Member Functions inherited from ConsoleObject
ConsoleObject (const ConsoleObject &)
Protected Member Functions inherited from EngineObject
object incRefCount ()
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Protected Member Functions inherited from CollisionInterface
bool checkEarlyOut (Point3F start, VectorF velocity, F32 time, Box3F objectBox, Point3F objectScale, Box3F collisionBox, U32 collisionMask, CollisionWorkingList &colWorkingList)
checkEarlyOut This function lets you trying and early out of any expensive collision checks by using simple extruded poly boxes representing our objects If it returns true, we know we won't hit with the given parameters and can successfully early out.
void handleCollisionNotifyList ()
void queueCollision (SceneObject *obj, const VectorF &vec)
Static Protected Member Functions inherited from SimObject
static bool _setPersistentID (void *object, const char *index, const char *data)
Static Protected Member Functions inherited from EngineObject
static void * _allocateObject (size_t size, IEngineObjectPool *pool TORQUE_TMM_ARGS_DECL)
Static Protected Attributes inherited from SimObject
static SimObjectId smForcedId
The Id to force upon the object. Poor object.
static bool smForceId
Force a registered object to use the given Id. Cleared upon use.
Static Protected Attributes inherited from CollisionInterface
static CollisionTimeout * sFreeTimeoutList
Member Enumeration Documentation
anonymous enum protected
Enumerator
ColliderMask
enum CollisionComponent::MeshType
Enumerator
None
No mesh.
Bounds
Bounding box of the shape.
CollisionMesh
Specifically designated collision meshes.
VisibleMesh
Rendered mesh polygons.
Constructor & Destructor Documentation
CollisionComponent::CollisionComponent ()
virtual CollisionComponent::~CollisionComponent () virtual
Member Function Documentation
PhysicsCollision* CollisionComponent::buildColShapes ()
virtual bool CollisionComponent::buildPolyList (PolyListContext context, AbstractPolyList * polyList, const Box3F & box, const SphereF & sphere) inline virtual
Implements CollisionInterface.
References getCollisionData().
virtual bool CollisionComponent::castRay (const Point3F & start, const Point3F & end, RayInfo * info) virtual
Implements CastRayInterface.
virtual void CollisionComponent::checkDependencies () virtual
Reimplemented from Component.
virtual void CollisionComponent::componentAddedToOwner (Component * comp) virtual
Reimplemented from Component.
virtual void CollisionComponent::componentRemovedFromOwner (Component * comp) virtual
Reimplemented from Component.
CollisionComponent::DECLARE_CONOBJECT (CollisionComponent)
S32 CollisionComponent::getBestCollision (Point3F upVector) inline
References CollisionList::getCount(), and CollisionInterface::mCollisionList.
Referenced by getBestCollisionAngle().
F32 CollisionComponent::getBestCollisionAngle (VectorF upVector) inline
References DefineEnumType(), getBestCollision(), and getCollisionAngle().
F32 CollisionComponent::getCollisionAngle (S32 collisionIndex, Point3F upVector) inline
References CollisionList::getCount(), and CollisionInterface::mCollisionList.
Referenced by getBestCollisionAngle().
S32 CollisionComponent::getCollisionCount () inline
References CollisionList::getCount(), and CollisionInterface::mCollisionList.
virtual PhysicsCollision* CollisionComponent::getCollisionData () virtual
Implements CollisionInterface.
Referenced by buildPolyList().
Point3F CollisionComponent::getCollisionNormal (S32 collisionIndex) inline
References CollisionList::getCount(), CollisionInterface::mCollisionList, and Point3F::Zero.
Point3F CollisionComponent::getContactNormal () inline
References ContactInfo::contactNormal, and CollisionInterface::mContactInfo.
bool CollisionComponent::hasContact () inline
References ContactInfo::contactObject, and CollisionInterface::mContactInfo.
static void CollisionComponent::initPersistFields () static
void CollisionComponent::inspectPostApply () virtual
Called after any property of the object is changed in the world editor.
See also
inspectPreApply
Reimplemented from SimObject.
virtual void CollisionComponent::onComponentAdd () virtual
Reimplemented from Component.
virtual void CollisionComponent::onComponentRemove () virtual
Reimplemented from Component.
virtual void CollisionComponent::ownerTransformSet (MatrixF * mat) virtual
Reimplemented from Component.
virtual U32 CollisionComponent::packUpdate (NetConnection * conn, U32 mask, BitStream * stream) virtual
Instructs this object to pack its state for transfer over the network.
Parameters
conn Net connection being used
mask Mask indicating fields to transmit.
stream Bitstream to pack data to
Returns
Any bits which were not dealt with. The value is stored by the networking system. Don't set bits you weren't passed.
Reimplemented from Component.
void CollisionComponent::prepCollision ()
virtual void CollisionComponent::processTick () virtual
Reimplemented from Component.
void CollisionComponent::targetShapeChanged (RenderComponentInterface * instanceInterface)
virtual void CollisionComponent::unpackUpdate (NetConnection * conn, BitStream * stream) virtual
Instructs this object to read state data previously packed with packUpdate.
Parameters
conn Net connection being used
stream stream to read from
Reimplemented from Component.
void CollisionComponent::updatePhysics ()
Member Data Documentation
StringTableEntry CollisionComponent::colisionMeshPrefix protected
bool CollisionComponent::mAnimated protected
Vector<S32> CollisionComponent::mCollisionDetails protected
MeshType CollisionComponent::mCollisionType protected
MeshType CollisionComponent::mDecalType protected
Vector<S32> CollisionComponent::mLOSDetails protected
MeshType CollisionComponent::mLOSType protected
PhysicsComponentInterface* CollisionComponent::mOwnerPhysicsInterface protected
RenderComponentInterface* CollisionComponent::mOwnerRenderInterface protected
PhysicsBody* CollisionComponent::mPhysicsRep
PhysicsWorld* CollisionComponent::mPhysicsWorld
Copyright © GarageGames, LLC. All Rights Reserved.