Point3I Class Reference
Main Modules Class List Namespace List Online
Point3I Class Reference
3D integer point
#include <math/mPoint3.h>
Public Member Functions
Point3I ()
Create an uninitialized point.
Point3I (const Point3I &)
Copy constructor.
Point3I (S32 xyz)
Initializes all elements to the same value.
Point3I (S32 in_x, S32 in_y, S32 in_z)
Create a point from co-ordinates.
void convolve (const Point3I &)
Convolve by parameter.
bool isZero () const
Check for point at origin. (No epsilon.)
F32 len () const
Get length.
void neg ()
Invert co-ordinate's signs.
operator const S32 * () const
operator S32 * ()
bool operator!= (const Point3I &) const
Point3I operator* (S32) const
Point3I & operator*= (S32)
Point3I operator+ (const Point3I &) const
Point3I & operator+= (const Point3I &)
Point3I operator- (const Point3I &) const
Point3I operator- () const
Point3I & operator-= (const Point3I &)
Point3I operator/ (S32) const
Point3I & operator/= (S32)
bool operator== (const Point3I &) const
void set (S32 xyz)
Initializes all elements to the same value.
void set (S32 in_x, S32 in_y, S32 in_z)
Set co-ordinates.
void setMax (const Point3I &)
Store greater co-ordinates in this point.
void setMin (const Point3I &)
Store lesser co-ordinates in this point.
void zero ()
Zero all values.
Public Attributes
S32 x
X co-ordinate.
S32 y
Y co-ordinate.
S32 z
Z co-ordinate.
Static Public Attributes
static const Point3I One
static const Point3I Zero
Detailed Description
3D integer point
Uses S32 internally.
Constructor & Destructor Documentation
Point3I::Point3I () inline
Create an uninitialized point.
Referenced by operator*(), operator+(), operator-(), and operator/().
Point3I::Point3I (const Point3I & _copy) inline
Copy constructor.
Point3I::Point3I (S32 xyz) inline explicit
Initializes all elements to the same value.
Point3I::Point3I (S32 in_x, S32 in_y, S32 in_z) inline
Create a point from co-ordinates.
Member Function Documentation
void Point3I::convolve (const Point3I & c) inline
Convolve by parameter.
References x, y, and z.
Referenced by Point3F::asPoint2F(), and Point3D::operator const F64 *().
bool Point3I::isZero () const inline
Check for point at origin. (No epsilon.)
References x, y, and z.
Referenced by Point3F::asPoint2F(), and Point3D::operator const F64 *().
F32 Point3I::len () const inline
Get length.
References x, y, and z.
Referenced by Point3F::asPoint2F(), and Point3D::operator const F64 *().
void Point3I::neg () inline
Invert co-ordinate's signs.
References x, y, and z.
Referenced by Point3F::asPoint2F(), and Point3D::operator const F64 *().
Point3I::operator const S32 * () const inline
References operator!=(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator==(), and x.
Point3I::operator S32 * () inline
References x.
bool Point3I::operator!= (const Point3I & _test) const inline
Referenced by Point3F::asPoint2F(), Point3D::operator const F64 *(), and operator const S32 *().
Point3I Point3I::operator* (S32 mul) const inline
References Point3I(), x, y, and z.
Referenced by Point3F::asPoint2F(), Point3D::operator const F64 *(), and operator const S32 *().
Point3I & Point3I::operator*= (S32 mul) inline
References x, y, and z.
Referenced by Point3F::asPoint2F(), Point3D::operator const F64 *(), and operator const S32 *().
Point3I Point3I::operator+ (const Point3I & _add) const inline
References Point3I(), x, y, and z.
Referenced by Point3F::asPoint2F(), Point3D::operator const F64 *(), and operator const S32 *().
Point3I & Point3I::operator+= (const Point3I & _add) inline
References x, y, and z.
Referenced by Point3F::asPoint2F(), Point3D::operator const F64 *(), and operator const S32 *().
Point3I Point3I::operator- (const Point3I & _rSub) const inline
References Point3I(), x, y, and z.
Point3I Point3I::operator- () const inline
References Point3I(), x, y, and z.
Referenced by Point3F::asPoint2F(), Point3D::operator const F64 *(), and operator const S32 *().
Point3I & Point3I::operator-= (const Point3I & _rSub) inline
References x, y, and z.
Referenced by Point3F::asPoint2F(), Point3D::operator const F64 *(), and operator const S32 *().
Point3I Point3I::operator/ (S32 div) const inline
References Point3I(), x, y, and z.
Referenced by Point3F::asPoint2F(), Point3D::operator const F64 *(), and operator const S32 *().
Point3I & Point3I::operator/= (S32 div) inline
References x, y, and z.
Referenced by Point3F::asPoint2F(), Point3D::operator const F64 *(), and operator const S32 *().
bool Point3I::operator== (const Point3I & _test) const inline
References x, y, and z.
Referenced by Point3F::asPoint2F(), Point3D::operator const F64 *(), and operator const S32 *().
void Point3I::set (S32 xyz) inline
Initializes all elements to the same value.
References x, y, and z.
void Point3I::set (S32 in_x, S32 in_y, S32 in_z) inline
Set co-ordinates.
References x, y, and z.
void Point3I::setMax (const Point3I & _test) inline
Store greater co-ordinates in this point.
References x, y, and z.
Referenced by Box3I::Box3I(), and Box3I::intersect().
void Point3I::setMin (const Point3I & _test) inline
Store lesser co-ordinates in this point.
References x, y, and z.
Referenced by Box3I::Box3I(), and Box3I::intersect().
void Point3I::zero () inline
Zero all values.
References x, y, and z.
Member Data Documentation
const Point3I Point3I::One static
S32 Point3I::x
X co-ordinate.
Referenced by convolve(), GFXTextureObject::getBitmapWidth(), Box3I::getCenter(), TamlCustomField::getFieldValue(), GFXTextureObject::getWidth(), Box3I::isContained(), Box3I::isOverlapped(), Box3I::isValidBox(), isZero(), len(), Box3I::len_x(), neg(), Point3D::operator const F64 *(), operator const S32 *(), operator S32 *(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator==(), Point3F::Point3F(), set(), TamlCustomField::setFieldValue(), setMax(), setMin(), and zero().
S32 Point3I::y
Y co-ordinate.
Referenced by convolve(), GFXTextureObject::getBitmapHeight(), Box3I::getCenter(), TamlCustomField::getFieldValue(), GFXTextureObject::getHeight(), Box3I::isContained(), Box3I::isOverlapped(), Box3I::isValidBox(), isZero(), len(), Box3I::len_y(), neg(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator==(), Point3F::Point3F(), set(), TamlCustomField::setFieldValue(), setMax(), setMin(), and zero().
S32 Point3I::z
Z co-ordinate.
Referenced by convolve(), GFXTextureObject::getBitmapDepth(), Box3I::getCenter(), GFXTextureObject::getDepth(), TamlCustomField::getFieldValue(), Box3I::isContained(), Box3I::isOverlapped(), Box3I::isValidBox(), isZero(), len(), Box3I::len_z(), neg(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator==(), Point3F::Point3F(), set(), TamlCustomField::setFieldValue(), setMax(), setMin(), and zero().
const Point3I Point3I::Zero static
Referenced by LeapMotionFrame::getHandPos(), LeapMotionFrame::getPointablePos(), and RazerHydraFrame::getPos().
Copyright © GarageGames, LLC. All Rights Reserved.