SFXSystem Class Reference
Main Modules Class List Namespace List Online
SFXSystem Class Reference
This class provides access to the sound system.
#include <sfx/sfxSystem.h>
Public Types
typedef Signal< void(SFXSystemEventType event) > EventSignalType
typedef Vector< SFXSound * > SFXSoundVector
typedef Vector< SFXSource * > SFXSourceVector
Public Member Functions
void _update ()
This is only public so that it can be called by the game update loop.
void addPlugin (SFXSystemPlugin *plugin)
Register the given plugin with the system.
void dumpSources (StringBuilder *toString=NULL, bool excludeGroups=true)
Dump information about all current SFXSources to the console or to the given StringBuilder.
EventSignalType & getEventSignal ()
Return the SFX system event signal.
SFXSoundscapeManager * getSoundscapeManager () const
void notifyDescriptionChanged (SFXDescription *description)
Notify the SFX system that the given description has changed.
void notifyTrackChanged (SFXTrack *track)
void removePlugin (SFXSystemPlugin *plugin)
Unregister the given plugin with the system.
Device Management
bool createDevice (const String &providerName, const String &deviceName, bool useHardware, S32 maxBuffers, bool changeDevice=false)
This initializes a new device.
String getDeviceInfoString ()
Returns the current device information or NULL if no device is present.
void deleteDevice ()
This destroys the current device.
bool hasDevice () const
Returns true if a device is allocated.
Source Creation
SFXSource * createSource (SFXTrack *track, const MatrixF *transform=NULL, const VectorF *velocity=NULL)
Used to create new sound sources from a sound profile.
SFXSound * createSourceFromStream (const ThreadSafeRef< SFXStream > &stream, SFXDescription *description)
Used to create a streaming sound source from a user supplied stream object.
SFXSource * playOnce (SFXTrack *track, const MatrixF *transform=NULL, const VectorF *velocity=NULL, F32 fadeInTime=-1.f)
Creates a source which when it finishes playing will auto delete itself.
SFXSource * playOnce (SFXProfile *profile, const MatrixF *transform=NULL, const VectorF *velocity=NULL, F32 fadeInTime=-1.f)
void stopAndDeleteSource (SFXSource *source)
Stop the source and delete it.
void deleteWhenStopped (SFXSource *source)
Mark source for deletion when it is moving into stopped state.
Listeners
U32 getNumListeners () const
Return the number of listeners currently configured.
void setNumListeners (U32 num)
Set the number of concurrent listeners.
const SFXListenerProperties & getListener (U32 index=0) const
Set the property of the given listener.
void setListener (U32 index, const MatrixF &transform, const Point3F &velocity)
Set the 3D attributes of the given listener.
void setListener (U32 index, const SFXListenerProperties &properties)
3D Sound Configuration
{
SFXDistanceModel getDistanceModel () const
Return the curve model currently used distance attenuation of positional sounds.
void setDistanceModel (SFXDistanceModel model)
F32 getDopplerFactor () const
void setDopplerFactor (F32 factor)
F32 getRolloffFactor () const
void setRolloffFactor (F32 factor)
const SFXReverbProperties & getReverb () const
void setReverb (const SFXReverbProperties &reverb)
Static Public Member Functions
static void destroy ()
This is called after Sim::shutdown() in shutdownLibraries() to free the sound system singlton.
static SFXSystem * getSingleton ()
Returns the one an only instance of the SFXSystem unless it hasn't been initialized or its been disabled in your build.
static void init ()
This is called from initialization to prepare the sound system singleton.
Protected Member Functions
SFXSystem ()
The protected constructor.
~SFXSystem ()
The non-virtual destructor.
void _assignVoice (SFXSound *sound)
void _assignVoices ()
This called to reprioritize and reassign voices to sources.
SFXBuffer * _createBuffer (const ThreadSafeRef< SFXStream > &stream, SFXDescription *description)
Called from SFXProfile to create a device specific sound buffer used in conjunction with a voice in playback.
SFXBuffer * _createBuffer (const String &filename, SFXDescription *description)
Load file directly through SFXDevice.
SFXDevice * _getDevice () const
void _onAddSource (SFXSource *source)
Called from SFXSource::onAdd to register the source.
void _onRemoveSource (SFXSource *source)
Called from SFXSource::onRemove to unregister the source.
void _sortSounds (const SFXListenerProperties &listener)
void _updateSources ()
Called to reprioritize and reassign buffers as sources change state, volumes are adjusted, and the listener moves around.
Protected Attributes
SFXDevice * mDevice
The current output sound device initialized and ready to play back.
SFXDistanceModel mDistanceModel
The distance model used for rolloff curve computation on 3D sounds.
F32 mDopplerFactor
The current doppler scale factor.
EventSignalType mEventSignal
SFX system event signal.
U32 mLastAmbientUpdateTime
U32 mLastParameterUpdateTime
U32 mLastSourceUpdateTime
The last time the sources got an update.
Vector< SFXListenerProperties > mListeners
The current position and orientation of all listeners.
SFXSourceVector mPlayOnceSources
This is used to keep track of play once sources that must be released when they stop playing.
Vector< SFXSystemPlugin * > mPlugins
List of plugins currently linked to the SFX system.
SFXReverbProperties mReverb
Current global reverb properties.
F32 mRolloffFactor
The current curve rolloff factor.
SFXSoundVector mSounds
SFXSoundscapeManager * mSoundscapeMgr
Ambient soundscape manager.
Stats
Stats reported back to the console for tracking performance.
S32 mStatNumSources
S32 mStatNumSounds
S32 mStatNumPlaying
S32 mStatNumCulled
S32 mStatNumVoices
S32 mStatSourceUpdateTime
S32 mStatParameterUpdateTime
S32 mStatAmbientUpdateTime
Static Protected Attributes
static SFXSystem * smSingleton
The one and only instance of the SFXSystem.
Detailed Description
This class provides access to the sound system.
There are a few script preferences that are used by the sound providers.
$pref::SFX::frequency - This is the playback frequency for the primary sound buffer used for mixing. Although most providers will reformat on the fly, for best quality and performance match your sound files to this setting.
$pref::SFX::bitrate - This is the playback bitrate for the primary sound buffer used for mixing. Although most providers will reformat on the fly, for best quality and performance match your sound files to this setting.
Member Typedef Documentation
typedef Signal< void(SFXSystemEventType event) > SFXSystem::EventSignalType
typedef Vector< SFXSound* > SFXSystem::SFXSoundVector
typedef Vector< SFXSource* > SFXSystem::SFXSourceVector
Constructor & Destructor Documentation
SFXSystem::SFXSystem () protected
The protected constructor.
See also
SFXSystem::init()
SFXSystem::~SFXSystem () protected
The non-virtual destructor.
You shouldn't ever need to overload this class.
Member Function Documentation
void SFXSystem::_assignVoice (SFXSound * sound) protected
void SFXSystem::_assignVoices () protected
This called to reprioritize and reassign voices to sources.
SFXBuffer* SFXSystem::_createBuffer (const ThreadSafeRef< SFXStream > & stream, SFXDescription * description) protected
Called from SFXProfile to create a device specific sound buffer used in conjunction with a voice in playback.
SFXBuffer* SFXSystem::_createBuffer (const String & filename, SFXDescription * description) protected
Load file directly through SFXDevice.
Depends on availability with selected SFXDevice.
Returns
Return new buffer or NULL.
SFXDevice* SFXSystem::_getDevice () const inline protected
void SFXSystem::_onAddSource (SFXSource * source) protected
Called from SFXSource::onAdd to register the source.
void SFXSystem::_onRemoveSource (SFXSource * source) protected
Called from SFXSource::onRemove to unregister the source.
void SFXSystem::_sortSounds (const SFXListenerProperties & listener) protected
void SFXSystem::_update ()
This is only public so that it can be called by the game update loop.
It updates the current device and all sources.
void SFXSystem::_updateSources () protected
Called to reprioritize and reassign buffers as sources change state, volumes are adjusted, and the listener moves around.
See also
SFXSource::_update()
void SFXSystem::addPlugin (SFXSystemPlugin * plugin)
Register the given plugin with the system.
bool SFXSystem::createDevice (const String & providerName, const String & deviceName, bool useHardware, S32 maxBuffers, bool changeDevice = false)
This initializes a new device.
Parameters
providerName The name of the provider.
deviceName The name of the provider device.
useHardware Toggles the use of hardware processing when available.
maxBuffers The maximum buffers for this device to use or -1 for the device to pick its own reasonable default.
changeDevice Allows this to change the current device to a new one
Returns
Returns true if the device was created.
SFXSource* SFXSystem::createSource (SFXTrack * track, const MatrixF * transform = NULL, const VectorF * velocity = NULL)
Used to create new sound sources from a sound profile.
The returned source is in a stopped state and ready for playback. Use the SFX_DELETE macro to free the source when your done.
Note
The track must have at least the same lifetime as the source. If the description disappears while the source is still there, the source will go with it.
Parameters
profile The sound profile for the created source.
transform The optional transform if creating a 3D source.
velocity The optional doppler velocity if creating a 3D source.
Returns
The sound source or NULL if an error occured.
SFXSound* SFXSystem::createSourceFromStream (const ThreadSafeRef< SFXStream > & stream, SFXDescription * description)
Used to create a streaming sound source from a user supplied stream object.
It is only intended for memory based streams. For sound file streaming use createSource() with a streaming SFXProfile.
Use the SFX_DELETE macro to free the source when your done.
Note
The description must have at least the same lifetime as the sound. If the description disappears while the source is still there, the sound will go with it.
Parameters
stream The stream used to create the sound buffer. It must exist for the lifetime of the source and will have its reference count decremented when the source is destroyed.
description The sound description to apply to the source.
Returns
The sound source or NULL if an error occured.
void SFXSystem::deleteDevice ()
This destroys the current device.
All sources loose their playback buffers, but otherwise continue to function.
void SFXSystem::deleteWhenStopped (SFXSource * source)
Mark source for deletion when it is moving into stopped state.
This method is useful to basically make a source a play-once source after the fact.
static void SFXSystem::destroy () static
This is called after Sim::shutdown() in shutdownLibraries() to free the sound system singlton.
After this the SFX singleton is null and any call to it will crash.
void SFXSystem::dumpSources (StringBuilder * toString = NULL, bool excludeGroups = true)
Dump information about all current SFXSources to the console or to the given StringBuilder.
String SFXSystem::getDeviceInfoString ()
Returns the current device information or NULL if no device is present.
The information string is in the following format:
Provider Name Name Hardware Buffers
SFXDistanceModel SFXSystem::getDistanceModel () const inline
Return the curve model currently used distance attenuation of positional sounds.
F32 SFXSystem::getDopplerFactor () const inline
EventSignalType& SFXSystem::getEventSignal () inline
Return the SFX system event signal.
const SFXListenerProperties& SFXSystem::getListener (U32 index = 0) const inline
Set the property of the given listener.
U32 SFXSystem::getNumListeners () const inline
Return the number of listeners currently configured.
References Vector< T >::size().
const SFXReverbProperties& SFXSystem::getReverb () const inline
F32 SFXSystem::getRolloffFactor () const inline
static SFXSystem* SFXSystem::getSingleton () inline static
Returns the one an only instance of the SFXSystem unless it hasn't been initialized or its been disabled in your build.
For convienence you can use the SFX-> macro as well.
See also
SFXSystem::init()
SFX
SFXSoundscapeManager* SFXSystem::getSoundscapeManager () const inline
bool SFXSystem::hasDevice () const inline
Returns true if a device is allocated.
References SFXSystemPlugin::createSource().
static void SFXSystem::init () static
This is called from initialization to prepare the sound system singleton.
This also includes registering common resource types and initializing available sound providers.
void SFXSystem::notifyDescriptionChanged (SFXDescription * description)
Notify the SFX system that the given description has changed.
All sources currently using the description will be updated.
void SFXSystem::notifyTrackChanged (SFXTrack * track)
SFXSource* SFXSystem::playOnce (SFXTrack * track, const MatrixF * transform = NULL, const VectorF * velocity = NULL, F32 fadeInTime = -1.f)
Creates a source which when it finishes playing will auto delete itself.
Be aware that the returned SFXSource pointer should only be used for error checking or immediate setting changes. It may be deleted as soon as the next system tick.
Parameters
profile The sound profile for the created source.
transform The optional transform if creating a 3D source.
velocity The optional doppler velocity if creating a 3D source.
Returns
The sound source or NULL if an error occured.
SFXSource* SFXSystem::playOnce (SFXProfile * profile, const MatrixF * transform = NULL, const VectorF * velocity = NULL, F32 fadeInTime = -1.f) inline
void SFXSystem::removePlugin (SFXSystemPlugin * plugin)
Unregister the given plugin with the system.
void SFXSystem::setDistanceModel (SFXDistanceModel model)
void SFXSystem::setDopplerFactor (F32 factor)
void SFXSystem::setListener (U32 index, const MatrixF & transform, const Point3F & velocity)
Set the 3D attributes of the given listener.
void SFXSystem::setListener (U32 index, const SFXListenerProperties & properties) inline
References SFXListenerProperties::getTransform(), and SFXListenerProperties::getVelocity().
void SFXSystem::setNumListeners (U32 num)
Set the number of concurrent listeners.
Note
It depends on the selected device if more than one listener is actually supported.
void SFXSystem::setReverb (const SFXReverbProperties & reverb)
void SFXSystem::setRolloffFactor (F32 factor)
void SFXSystem::stopAndDeleteSource (SFXSource * source)
Stop the source and delete it.
This method will take care of the fade-out time that the source may need before it will actually stop and may be deleted.
Member Data Documentation
SFXDevice* SFXSystem::mDevice protected
The current output sound device initialized and ready to play back.
SFXDistanceModel SFXSystem::mDistanceModel protected
The distance model used for rolloff curve computation on 3D sounds.
F32 SFXSystem::mDopplerFactor protected
The current doppler scale factor.
EventSignalType SFXSystem::mEventSignal protected
SFX system event signal.
U32 SFXSystem::mLastAmbientUpdateTime protected
U32 SFXSystem::mLastParameterUpdateTime protected
U32 SFXSystem::mLastSourceUpdateTime protected
The last time the sources got an update.
Vector< SFXListenerProperties > SFXSystem::mListeners protected
The current position and orientation of all listeners.
SFXSourceVector SFXSystem::mPlayOnceSources protected
This is used to keep track of play once sources that must be released when they stop playing.
Vector< SFXSystemPlugin* > SFXSystem::mPlugins protected
List of plugins currently linked to the SFX system.
SFXReverbProperties SFXSystem::mReverb protected
Current global reverb properties.
F32 SFXSystem::mRolloffFactor protected
The current curve rolloff factor.
SFXSoundVector SFXSystem::mSounds protected
SFXSoundscapeManager* SFXSystem::mSoundscapeMgr protected
Ambient soundscape manager.
S32 SFXSystem::mStatAmbientUpdateTime protected
S32 SFXSystem::mStatNumCulled protected
S32 SFXSystem::mStatNumPlaying protected
S32 SFXSystem::mStatNumSounds protected
S32 SFXSystem::mStatNumSources protected
S32 SFXSystem::mStatNumVoices protected
S32 SFXSystem::mStatParameterUpdateTime protected
S32 SFXSystem::mStatSourceUpdateTime protected
SFXSystem* SFXSystem::smSingleton static protected
The one and only instance of the SFXSystem.
Copyright © GarageGames, LLC. All Rights Reserved.