PhysicsObject Class Reference
Main Modules Class List Namespace List Online
PhysicsObject Class Reference abstract
#include <T3D/physics/physicsObject.h>
Public Member Functions
virtual ~PhysicsObject ()
virtual MatrixF & getTransform (MatrixF *outMatrix)=0
Returns the transform of the physics body at the last processed simulation tick.
const PhysicsUserData & getUserData () const
PhysicsUserData & getUserData ()
virtual PhysicsWorld * getWorld ()=0
Returns the physics world this object is a member of.
virtual Box3F getWorldBounds ()=0
Returns the world aligned bounding box containing the PhysicsObject.
virtual bool isSimulationEnabled ()=0
void queueCallback (U32 ms, Delegate< void()> callback)
virtual void setSimulationEnabled (bool enabled)=0
Set false to skip simulation of this object or temporarily remove it from the physics simulation.
virtual void setTransform (const MatrixF &transform)=0
Sets the transform on the physics object.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Protected Member Functions
PhysicsObject ()
You shouldn't be creating this object directly.
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Protected Attributes
U32 mQueuedEvent
The last queued callback event.
PhysicsUserData mUserData
The user data object assigned to this object.
Constructor & Destructor Documentation
virtual PhysicsObject::~PhysicsObject () virtual
PhysicsObject::PhysicsObject () protected
You shouldn't be creating this object directly.
Referenced by getUserData().
Member Function Documentation
virtual MatrixF& PhysicsObject::getTransform (MatrixF * outMatrix) pure virtual
Returns the transform of the physics body at the last processed simulation tick.
Implemented in Px3Body, BtBody, BtPlayer, and Px3Player.
const PhysicsUserData& PhysicsObject::getUserData () const inline
References mUserData.
PhysicsUserData& PhysicsObject::getUserData () inline
References isSimulationEnabled(), mUserData, PhysicsObject(), and setSimulationEnabled().
virtual PhysicsWorld* PhysicsObject::getWorld () pure virtual
Returns the physics world this object is a member of.
Implemented in Px3Body, BtBody, BtPlayer, and Px3Player.
virtual Box3F PhysicsObject::getWorldBounds () pure virtual
Returns the world aligned bounding box containing the PhysicsObject.
Implemented in Px3Body, BtPlayer, BtBody, and Px3Player.
virtual bool PhysicsObject::isSimulationEnabled () pure virtual
Implemented in Px3Body, BtPlayer, BtBody, and Px3Player.
Referenced by getUserData().
void PhysicsObject::queueCallback (U32 ms, Delegate< void()> callback)
virtual void PhysicsObject::setSimulationEnabled (bool enabled) pure virtual
Set false to skip simulation of this object or temporarily remove it from the physics simulation.
Implementation is PhysicsPlugin specific.
Implemented in Px3Body, BtPlayer, BtBody, and Px3Player.
Referenced by getUserData().
virtual void PhysicsObject::setTransform (const MatrixF & transform) pure virtual
Sets the transform on the physics object.
For static objects this is only intended to be used for for infrequent changes when editing the mission.
Implemented in Px3Body, BtBody, BtPlayer, and Px3Player.
Member Data Documentation
U32 PhysicsObject::mQueuedEvent protected
The last queued callback event.
See also
queueCallback
PhysicsUserData PhysicsObject::mUserData protected
The user data object assigned to this object.
Referenced by getUserData().
Copyright © GarageGames, LLC. All Rights Reserved.