ConsoleValueStack Class Reference
Main Modules Class List Namespace List Online
ConsoleValueStack Class Reference
#include <console/stringStack.h>
Public Member Functions
ConsoleValueStack ()
~ConsoleValueStack ()
void clearFrames ()
void getArgcArgv (StringTableEntry name, U32 *argc, ConsoleValueRef **in_argv, bool popStackFrame=false)
ConsoleValue * pop ()
void popFrame ()
ConsoleValue * pushFLT (float value)
void pushFrame ()
ConsoleValue * pushStackString (const char *value)
ConsoleValue * pushString (const char *value)
ConsoleValue * pushStringStackPtr (StringStackPtr ptr)
ConsoleValue * pushUINT (U32 value)
void pushValue (ConsoleValue &value)
void pushVar (ConsoleValue *variable)
ConsoleValue * reserveValues (U32 numValues)
bool reserveValues (U32 numValues, ConsoleValueRef *values)
void resetFrame ()
Public Attributes
ConsoleValueRef mArgv [MaxArgs]
U32 mFrame
ConsoleValue mStack [MaxStackDepth]
U32 mStackFrames [MaxStackDepth]
U32 mStackPos
Constructor & Destructor Documentation
ConsoleValueStack::ConsoleValueStack ()
ConsoleValueStack::~ConsoleValueStack ()
Member Function Documentation
void ConsoleValueStack::clearFrames ()
void ConsoleValueStack::getArgcArgv (StringTableEntry name, U32 * argc, ConsoleValueRef ** in_argv, bool popStackFrame = false)
ConsoleValue* ConsoleValueStack::pop ()
void ConsoleValueStack::popFrame ()
ConsoleValue* ConsoleValueStack::pushFLT (float value)
void ConsoleValueStack::pushFrame ()
ConsoleValue* ConsoleValueStack::pushStackString (const char * value)
ConsoleValue* ConsoleValueStack::pushString (const char * value)
ConsoleValue* ConsoleValueStack::pushStringStackPtr (StringStackPtr ptr)
ConsoleValue* ConsoleValueStack::pushUINT (U32 value)
void ConsoleValueStack::pushValue (ConsoleValue & value)
void ConsoleValueStack::pushVar (ConsoleValue * variable)
ConsoleValue* ConsoleValueStack::reserveValues (U32 numValues)
Referenced by _EngineConsoleCallbackHelper::call(), _EngineConsoleExecCallbackHelper< P1 >::call(), and _EngineConsoleExecCallbackHelper< const char * >::call().
bool ConsoleValueStack::reserveValues (U32 numValues, ConsoleValueRef * values)
void ConsoleValueStack::resetFrame ()
Member Data Documentation
ConsoleValueRef ConsoleValueStack::mArgv[MaxArgs]
U32 ConsoleValueStack::mFrame
ConsoleValue ConsoleValueStack::mStack[MaxStackDepth]
U32 ConsoleValueStack::mStackFrames[MaxStackDepth]
U32 ConsoleValueStack::mStackPos
Copyright © GarageGames, LLC. All Rights Reserved.