Namespace Class Reference
Main Modules Class List Namespace List Online
Namespace Class Reference
A dictionary of function entries.
#include <console/consoleInternal.h>
Classes
struct Entry
A function entry in the namespace.
Public Member Functions
Namespace ()
~Namespace ()
void addCommand (StringTableEntry name, StringCallback, const char *usage, S32 minArgs, S32 maxArgs, bool toolOnly=false, ConsoleFunctionHeader *header=NULL)
void addCommand (StringTableEntry name, IntCallback, const char *usage, S32 minArgs, S32 maxArgs, bool toolOnly=false, ConsoleFunctionHeader *header=NULL)
void addCommand (StringTableEntry name, FloatCallback, const char *usage, S32 minArgs, S32 maxArgs, bool toolOnly=false, ConsoleFunctionHeader *header=NULL)
void addCommand (StringTableEntry name, VoidCallback, const char *usage, S32 minArgs, S32 maxArgs, bool toolOnly=false, ConsoleFunctionHeader *header=NULL)
void addCommand (StringTableEntry name, BoolCallback, const char *usage, S32 minArgs, S32 maxArgs, bool toolOnly=false, ConsoleFunctionHeader *header=NULL)
void addFunction (StringTableEntry name, CodeBlock *cb, U32 functionOffset, const char *usage=NULL, U32 lineNumber=0)
void addScriptCallback (const char *funcName, const char *usage, ConsoleFunctionHeader *header=NULL)
void buildHashTable ()
bool classLinkTo (Namespace *parent)
void clearEntries ()
Entry * createLocalEntry (StringTableEntry name)
void decRefCountToParent ()
Decrease the count on the reference that this namespace holds to its parent.
void getEntryList (VectorPtr< Entry * > *)
StringTableEntry getName () const
Return the name of this namespace.
StringTableEntry getPackage () const
Return the package in which this namespace is defined.
Namespace * getPackageRoot ()
Return the topmost package in the parent hierarchy of this namespace that still refers to the same namespace.
Namespace * getParent () const
Return the superordinate namespace to this namespace.
void getUniqueEntryLists (Namespace *other, VectorPtr< Entry * > *outThisList, VectorPtr< Entry * > *outOtherList)
void incRefCountToParent ()
Increase the count on the reference that this namespace holds to its parent.
bool isClass () const
Returns true if this namespace represents an engine defined class and is not just a script defined class namespace.
Entry * lookup (StringTableEntry name)
Entry * lookupRecursive (StringTableEntry name)
void markGroup (const char *name, const char *usage)
const char * tabComplete (const char *prevText, S32 baseLen, bool fForward)
bool unlinkClass (Namespace *parent)
Static Public Member Functions
static void activatePackage (StringTableEntry name)
static void deactivatePackage (StringTableEntry name)
static void deactivatePackageStack (StringTableEntry name)
static void dumpClasses (bool dumpScript=true, bool dumpEngine=true)
static void dumpFunctions (bool dumpScript=true, bool dumpEngine=true)
static Namespace * find (StringTableEntry name, StringTableEntry package=NULL)
static StringTableEntry getActivePackage (U32 index)
static U32 getActivePackagesCount ()
static Namespace * global ()
static void init ()
static bool isPackage (StringTableEntry name)
static void printNamespaceEntries (Namespace *g, bool dumpScript=true, bool dumpEngine=true)
static void relinkPackages ()
static void shutdown ()
static void trashCache ()
static void unlinkPackages ()
Public Attributes
char * lastUsage
AbstractClassRep * mClassRep
bool mCleanUpUsage
Script defined usage strings need to be cleaned up.
Entry * mEntryList
U32 mHashSequence
U32 mHashSize
Entry ** mHashTable
StringTableEntry mName
Namespace * mNext
StringTableEntry mPackage
Namespace * mParent
U32 mRefCountToParent
const char * mUsage
Static Public Attributes
static DataChunker mAllocator
static DataChunker mCacheAllocator
static U32 mCacheSequence
static Namespace * mGlobalNamespace
static Namespace * mNamespaceList
Detailed Description
A dictionary of function entries.
Namespaces are used for dispatching calls in the console system.
Constructor & Destructor Documentation
Namespace::Namespace ()
Namespace::~Namespace ()
Member Function Documentation
static void Namespace::activatePackage (StringTableEntry name) static
void Namespace::addCommand (StringTableEntry name, StringCallback , const char * usage, S32 minArgs, S32 maxArgs, bool toolOnly = false, ConsoleFunctionHeader * header = NULL)
void Namespace::addCommand (StringTableEntry name, IntCallback , const char * usage, S32 minArgs, S32 maxArgs, bool toolOnly = false, ConsoleFunctionHeader * header = NULL)
void Namespace::addCommand (StringTableEntry name, FloatCallback , const char * usage, S32 minArgs, S32 maxArgs, bool toolOnly = false, ConsoleFunctionHeader * header = NULL)
void Namespace::addCommand (StringTableEntry name, VoidCallback , const char * usage, S32 minArgs, S32 maxArgs, bool toolOnly = false, ConsoleFunctionHeader * header = NULL)
void Namespace::addCommand (StringTableEntry name, BoolCallback , const char * usage, S32 minArgs, S32 maxArgs, bool toolOnly = false, ConsoleFunctionHeader * header = NULL)
void Namespace::addFunction (StringTableEntry name, CodeBlock * cb, U32 functionOffset, const char * usage = NULL, U32 lineNumber = 0)
void Namespace::addScriptCallback (const char * funcName, const char * usage, ConsoleFunctionHeader * header = NULL)
void Namespace::buildHashTable ()
Referenced by decRefCountToParent().
bool Namespace::classLinkTo (Namespace * parent)
Referenced by decRefCountToParent().
void Namespace::clearEntries ()
Referenced by decRefCountToParent().
Entry* Namespace::createLocalEntry (StringTableEntry name)
Referenced by decRefCountToParent().
static void Namespace::deactivatePackage (StringTableEntry name) static
static void Namespace::deactivatePackageStack (StringTableEntry name) static
void Namespace::decRefCountToParent () inline
Decrease the count on the reference that this namespace holds to its parent.
Note
Must not be called on namespaces coming from packages.
References buildHashTable(), classLinkTo(), clearEntries(), createLocalEntry(), getUniqueEntryLists(), lookup(), lookupRecursive(), tabComplete(), and unlinkClass().
static void Namespace::dumpClasses (bool dumpScript = true, bool dumpEngine = true) static
static void Namespace::dumpFunctions (bool dumpScript = true, bool dumpEngine = true) static
static Namespace* Namespace::find (StringTableEntry name, StringTableEntry package = NULL) static
static StringTableEntry Namespace::getActivePackage (U32 index) static
static U32 Namespace::getActivePackagesCount () static
void Namespace::getEntryList (VectorPtr< Entry * > *)
Referenced by isClass().
StringTableEntry Namespace::getName () const inline
Return the name of this namespace.
References mName.
StringTableEntry Namespace::getPackage () const inline
Return the package in which this namespace is defined.
References Namespace::Entry::mPackage.
Namespace* Namespace::getPackageRoot () inline
Return the topmost package in the parent hierarchy of this namespace that still refers to the same namespace.
If packages are active and adding to this namespace, then they will be linked in-between the namespace they are adding to and its real parent namespace.
References mName, and mParent.
Namespace* Namespace::getParent () const inline
Return the superordinate namespace to this namespace.
Symbols are inherited from this namespace.
References mParent.
void Namespace::getUniqueEntryLists (Namespace * other, VectorPtr< Entry * > * outThisList, VectorPtr< Entry * > * outOtherList)
Referenced by decRefCountToParent().
static Namespace* Namespace::global () static
void Namespace::incRefCountToParent () inline
Increase the count on the reference that this namespace holds to its parent.
Note
Must not be called on namespaces coming from packages.
static void Namespace::init () static
bool Namespace::isClass () const inline
Returns true if this namespace represents an engine defined class and is not just a script defined class namespace.
References getEntryList(), and AbstractClassRep::getNameSpace().
static bool Namespace::isPackage (StringTableEntry name) static
Entry* Namespace::lookup (StringTableEntry name)
Referenced by decRefCountToParent().
Entry* Namespace::lookupRecursive (StringTableEntry name)
Referenced by decRefCountToParent().
void Namespace::markGroup (const char * name, const char * usage)
static void Namespace::printNamespaceEntries (Namespace * g, bool dumpScript = true, bool dumpEngine = true) static
static void Namespace::relinkPackages () static
static void Namespace::shutdown () static
const char* Namespace::tabComplete (const char * prevText, S32 baseLen, bool fForward)
Referenced by decRefCountToParent(), and Dictionary::isOwner().
static void Namespace::trashCache () static
bool Namespace::unlinkClass (Namespace * parent)
Referenced by decRefCountToParent().
static void Namespace::unlinkPackages () static
Member Data Documentation
char* Namespace::lastUsage
DataChunker Namespace::mAllocator static
DataChunker Namespace::mCacheAllocator static
U32 Namespace::mCacheSequence static
AbstractClassRep* Namespace::mClassRep
Referenced by RuntimeClassRep< T >::consoleRegister().
bool Namespace::mCleanUpUsage
Script defined usage strings need to be cleaned up.
This field indicates whether or not the usage was set from script.
Entry* Namespace::mEntryList
Namespace* Namespace::mGlobalNamespace static
U32 Namespace::mHashSequence
Note
The hash sequence is used by the autodoc console facility as a means of testing reference state.
U32 Namespace::mHashSize
Entry** Namespace::mHashTable
StringTableEntry Namespace::mName
Referenced by getName(), and getPackageRoot().
Namespace* Namespace::mNamespaceList static
Namespace* Namespace::mNext
StringTableEntry Namespace::mPackage
Namespace* Namespace::mParent
Referenced by getPackageRoot(), and getParent().
U32 Namespace::mRefCountToParent
const char* Namespace::mUsage
Copyright © GarageGames, LLC. All Rights Reserved.