CubeLightShadowMap Class Reference
Main Modules Class List Namespace List Online
CubeLightShadowMap Class Reference
#include <lighting/shadowMap/cubeLightShadowMap.h>
Public Member Functions
CubeLightShadowMap (LightInfo *light)
virtual void _render (RenderPassManager *renderPass, const SceneRenderState *diffuseState)
virtual ShadowType getShadowType () const
virtual bool hasShadowTex () const
virtual void releaseTextures ()
virtual void setShaderParameters (GFXShaderConstBuffer *params, LightingShaderConstants *lsc)
virtual bool setTextureStage (U32 currTexFlag, LightingShaderConstants *lsc)
Public Member Functions inherited from LightShadowMap
LightShadowMap (LightInfo *light)
virtual ~LightShadowMap ()
U32 getBestTexSize (U32 scale=1) const
Returns the best texture size based on the user texture size, the last light screen size, and global shadow tweak parameters.
F32 getLastPriority () const
F32 getLastScreenSize () const
U32 getLastUpdate () const
LightInfo * getLightInfo ()
BaseMatInstance * getShadowMaterial (BaseMatInstance *inMat) const
Returns the correct shadow material this type of light or NULL if no shadow material is possible.
U32 getTexSize () const
GFXTextureObject * getTexture () const
const MatrixF & getWorldToLightProj () const
bool isDynamic ()
bool isViewDependent () const
void render (RenderPassManager *renderPass, const SceneRenderState *diffuseState, bool _dynamic, bool _forceUpdate)
void setDebugTarget (const String &name)
void setDynamic (bool value)
void updatePriority (const SceneRenderState *state, U32 currTimeMs)
Protected Attributes
GFXCubemapHandle mCubemap
The shadow cubemap.
Protected Attributes inherited from LightShadowMap
GFXShaderConstHandle * mBlurBoundaries
NamedTexTarget mDebugTarget
Helper for rendering shadow map for debugging.
PlatformTimer * mDynamicRefreshTimer
bool mIsDynamic
bool mIsViewDependent
If true the shadow is view dependent and cannot be skipped if visible and within active range.
U32 mLastCull
The time this shadow was last culled and prioritized.
F32 mLastPriority
F32 mLastScreenSize
GFXShader * mLastShader
U32 mLastUpdate
The time this shadow was last updated.
LightInfo * mLight
GFXTexHandle mShadowMapDepth
GFXTexHandle mShadowMapTex
PlatformTimer * mStaticRefreshTimer
GFXTextureTargetRef mTarget
U32 mTexSize
MatrixF mWorldToLightProj
Additional Inherited Members
Static Public Member Functions inherited from LightShadowMap
static GFXTextureObject * _getDepthTarget (U32 width, U32 height)
static S32 QSORT_CALLBACK cmpPriority (LightShadowMap *const *lsm1, LightShadowMap *const *lsm2)
static void releaseAllTextures ()
static U32 releaseUnusedTextures ()
Releases any shadow maps that have not been culled in a while and returns the count of the remaing shadow maps in use.
Static Public Attributes inherited from LightShadowMap
static const GFXFormat ShadowMapFormat
static bool smDebugRenderFrustums
Whether to render shadow frustums for lights that have debug rendering enabled.
static F32 smShadowTexScalar
Used to scale the shadow texture size for performance tweaking.
Protected Member Functions inherited from LightShadowMap
void _debugRender (SceneRenderState *shadowRenderState)
If there is a LightDebugInfo attached to the light that owns this map, then update its information from the given render state.
void _onTextureEvent (GFXTexCallbackCode code)
The callback used to get texture events.
void calcLightMatrices (MatrixF &outLightMatrix, const Frustum &viewFrustum)
Static Protected Attributes inherited from LightShadowMap
static Vector< LightShadowMap * > smShadowMaps
All the shadow maps in the system.
static Vector< LightShadowMap * > smUsedShadowMaps
All the shadow maps that have been recently rendered to.
Constructor & Destructor Documentation
CubeLightShadowMap::CubeLightShadowMap (LightInfo * light)
Member Function Documentation
virtual void CubeLightShadowMap::_render (RenderPassManager * renderPass, const SceneRenderState * diffuseState) virtual
Implements LightShadowMap.
Referenced by getShadowType().
virtual ShadowType CubeLightShadowMap::getShadowType () const inline virtual
Implements LightShadowMap.
References _render(), releaseTextures(), setShaderParameters(), and setTextureStage().
virtual bool CubeLightShadowMap::hasShadowTex () const inline virtual
Reimplemented from LightShadowMap.
References StrongRefPtr< T >::isValid(), and mCubemap.
virtual void CubeLightShadowMap::releaseTextures () virtual
Reimplemented from LightShadowMap.
Referenced by getShadowType().
virtual void CubeLightShadowMap::setShaderParameters (GFXShaderConstBuffer * params, LightingShaderConstants * lsc) virtual
Implements LightShadowMap.
Referenced by getShadowType().
virtual bool CubeLightShadowMap::setTextureStage (U32 currTexFlag, LightingShaderConstants * lsc) virtual
Reimplemented from LightShadowMap.
Referenced by getShadowType().
Member Data Documentation
GFXCubemapHandle CubeLightShadowMap::mCubemap protected
The shadow cubemap.
Referenced by hasShadowTex().
Copyright © GarageGames, LLC. All Rights Reserved.