StrongRefPtr< T > Class Template Reference
Main Modules Class List Namespace List Online
StrongRefPtr< T > Class Template Reference
Reference counted object template pointer class Instances of this template class can be used as pointers to instances of StrongRefBase and its subclasses.
#include <core/util/refBase.h>
Public Member Functions
StrongRefPtr ()
StrongRefPtr (T *ptr)
StrongRefPtr (const StrongRefPtr< T > &ref)
~StrongRefPtr ()
T * getPointer () const
bool isNull () const
bool isValid () const
operator T * () const
T & operator* () const
T * operator-> () const
StrongRefPtr< T > & operator= (const StrongRefPtr< T > &ref)
StrongRefPtr< T > & operator= (T *ptr)
Additional Inherited Members
Protected Member Functions inherited from StrongObjectRef
void decRef ()
decrements the reference count on the referenced object
void incRef ()
increments the reference count on the referenced object
StrongObjectRef (StrongRefBase *object=NULL)
Constructor, assigns from the object and increments its reference count if it's not NULL.
~StrongObjectRef ()
Destructor, dereferences the object, if there is one.
void set (StrongRefBase *object)
Assigns this reference object from an existing StrongRefBase instance.
Protected Attributes inherited from StrongObjectRef
StrongRefBase * mObject
the object this RefObjectRef references
Detailed Description
template<class T>
class StrongRefPtr< T >
Reference counted object template pointer class Instances of this template class can be used as pointers to instances of StrongRefBase and its subclasses.
The object will not be deleted until all of the StrongRefPtr instances pointing to it have been destructed.
Constructor & Destructor Documentation
template<class T> StrongRefPtr< T >::StrongRefPtr () inline
template<class T> StrongRefPtr< T >::StrongRefPtr (T * ptr) inline
template<class T> StrongRefPtr< T >::StrongRefPtr (const StrongRefPtr< T > & ref) inline
template<class T> StrongRefPtr< T >::~StrongRefPtr () inline
Member Function Documentation
template<class T> T* StrongRefPtr< T >::getPointer () const inline
Referenced by GFXTexHandle::operator!=(), GFXTexHandle::operator=(), GFXTexHandle::operator==(), and GFXPrimitiveBufferHandle::operator==().
template<class T> bool StrongRefPtr< T >::isNull (void) const inline
template<class T> bool StrongRefPtr< T >::isValid () const inline
Referenced by CubeLightShadowMap::hasShadowTex().
template<class T> StrongRefPtr< T >::operator T * () const inline
template<class T> T& StrongRefPtr< T >::operator* (void) const inline
template<class T> T* StrongRefPtr< T >::operator-> (void) const inline
template<class T> StrongRefPtr<T>& StrongRefPtr< T >::operator= (const StrongRefPtr< T > & ref) inline
template<class T> StrongRefPtr<T>& StrongRefPtr< T >::operator= (T * ptr) inline
Copyright © GarageGames, LLC. All Rights Reserved.