SFXFileStream Class Reference
Main Modules Class List Namespace List Online
SFXFileStream Class Reference abstract
An SFXStream that streams from a file.
#include <sfx/sfxFileStream.h>
Public Member Functions
virtual ~SFXFileStream ()
Destructor.
void close ()
Closes the stream.
U32 getDataLength () const
The data size in bytes of the decompressed PCM data.
U32 getDuration () const
The length of the sound in milliseconds.
const SFXFormat & getFormat () const
The format of the data in the stream.
U32 getSampleCount () const
The number of samples in the data stream.
bool isEOS () const
Returns true if we've reached the end of the stream.
bool open (Stream *stream, bool ownStream=false)
Opens and optionally takes ownership of the stream.
Public Member Functions inherited from SFXStream
virtual ~SFXStream ()
Destructor.
virtual SFXStream * clone () const
Make a copy of this stream with its own private state, so new independent read() operations can be issued on the same data stream.
virtual U32 read (U8 *buffer, U32 length)=0
Reads data from the stream and decompresses it into PCM samples.
virtual void reset ()=0
Resets the stream to restart reading data from the begining.
Public Member Functions inherited from ThreadSafeRefCount< SFXStream >
ThreadSafeRefCount ()
ThreadSafeRefCount (bool noSet)
void addRef ()
Increase the reference count on the object.
void clearLowestBit ()
U32 getRefCount () const
Get the current reference count.
bool isShared () const
void release ()
Decrease the object's reference count and delete the object, if the count drops to zero and claiming the object by the current thread succeeds.
Static Public Member Functions
static SFXFileStream * create (String filename)
This is a helper function used to create an appropriate SFXStream for the requested sound file.
static bool exists (String filename)
static void registerExtension (String ext, SFXFILESTREAM_CREATE_FN create_fn)
static void unregisterExtension (String ext)
Static Public Member Functions inherited from ThreadSafeRefCount< SFXStream >
static SFXStream * safeRead (SFXStream *const volatile &refPtr)
Dereference a reference-counted pointer in a multi-thread safe way.
Protected Types
typedef Vector< SFXFILESTREAM_CREATE_FN > CreateFnsVector
typedef Vector< String > ExtensionsVector
Protected Member Functions
SFXFileStream ()
Constructs the stream in an uninitilized state.
SFXFileStream (const SFXFileStream &cloneFrom)
virtual void _close ()=0
Overloaded for cleanup of file format specific structures.
virtual bool _readHeader ()=0
Overloaded in the derived classes to read the file header.
Protected Attributes
SFXFormat mFormat
The format of the data in the stream.
bool mOwnStream
If true then we're responsible for closing the stream.
U32 mSamples
The number of samples in the data stream.
Stream * mStream
The file stream we're reading from.
Protected Attributes inherited from ThreadSafeRefCount< SFXStream >
U32 mRefCount
Reference count and claim bit. Note that this increments in steps of two.
Static Protected Attributes
static CreateFnsVector smCreateFns
static ExtensionsVector smExtensions
Additional Inherited Members
Public Types inherited from SFXStream
typedef void Parent
Public Types inherited from ThreadSafeRefCount< SFXStream >
typedef void Parent
Public Types inherited from IResettable
typedef void Parent
Static Protected Member Functions inherited from ThreadSafeRefCount< SFXStream >
static U32 decrementAndTestAndSet (U32 &refCount)
Decrement the given reference count.
Detailed Description
An SFXStream that streams from a file.
Member Typedef Documentation
typedef Vector< SFXFILESTREAM_CREATE_FN > SFXFileStream::CreateFnsVector protected
typedef Vector< String > SFXFileStream::ExtensionsVector protected
Constructor & Destructor Documentation
SFXFileStream::SFXFileStream () protected
Constructs the stream in an uninitilized state.
SFXFileStream::SFXFileStream (const SFXFileStream & cloneFrom) protected
virtual SFXFileStream::~SFXFileStream () virtual
Destructor.
Member Function Documentation
virtual void SFXFileStream::_close () protected pure virtual
Overloaded for cleanup of file format specific structures.
Implemented in SFXWavStream.
virtual bool SFXFileStream::_readHeader () protected pure virtual
Overloaded in the derived classes to read the file header.
It should initialize mFormat and mSamples.
Implemented in SFXWavStream.
void SFXFileStream::close ()
Closes the stream.
static SFXFileStream* SFXFileStream::create (String filename) static
This is a helper function used to create an appropriate SFXStream for the requested sound file.
Parameters
filename The sound file path with or without extension.
static bool SFXFileStream::exists (String filename) static
U32 SFXFileStream::getDataLength () const inline virtual
The data size in bytes of the decompressed PCM data.
Implements SFXStream.
References SFXFormat::getBytesPerSample().
U32 SFXFileStream::getDuration () const inline virtual
The length of the sound in milliseconds.
Implements SFXStream.
References SFXFormat::getDuration(), and isEOS().
const SFXFormat& SFXFileStream::getFormat () const inline virtual
The format of the data in the stream.
Implements SFXStream.
References mFormat.
U32 SFXFileStream::getSampleCount () const inline virtual
The number of samples in the data stream.
Implements SFXStream.
References mSamples.
bool SFXFileStream::isEOS () const virtual
Returns true if we've reached the end of the stream.
Implements SFXStream.
Referenced by getDuration().
bool SFXFileStream::open (Stream * stream, bool ownStream = false)
Opens and optionally takes ownership of the stream.
static void SFXFileStream::registerExtension (String ext, SFXFILESTREAM_CREATE_FN create_fn) static
static void SFXFileStream::unregisterExtension (String ext) static
Member Data Documentation
SFXFormat SFXFileStream::mFormat protected
The format of the data in the stream.
Referenced by getFormat().
bool SFXFileStream::mOwnStream protected
If true then we're responsible for closing the stream.
U32 SFXFileStream::mSamples protected
The number of samples in the data stream.
Referenced by getSampleCount().
Stream* SFXFileStream::mStream protected
The file stream we're reading from.
Referenced by SFXWavStream::clone().
CreateFnsVector SFXFileStream::smCreateFns static protected
ExtensionsVector SFXFileStream::smExtensions static protected
Copyright © GarageGames, LLC. All Rights Reserved.