FeatureSet Class Reference
Main Modules Class List Namespace List Online
FeatureSet Class Reference
#include <shaderGen/featureSet.h>
Classes
struct FeatureInfo
Public Member Functions
FeatureSet ()
FeatureSet (const FeatureSet &h)
void addFeature (const FeatureType &type, S32 index=-1)
void clear ()
Clears all features.
void exclude (const FeatureSet &features)
Removes features that are in the input set.
void filter (const FeatureSet &features)
Removes features that are not in the input set.
const FeatureType & getAt (U32 index, S32 *outIndex=NULL) const
Returns the feature at the index and optionally the feature index when it was added.
U32 getCount () const
Returns the feature count.
const String & getDescription () const
Return the description string which uniquely identifies this feature set.
S32 getNextFeatureIndex (const FeatureType &type, S32 index) const
bool hasFeature (const FeatureType &type, S32 index=-1) const
Returns true if this handle has this feature.
bool isEmpty () const
Returns true if the feature set is empty.
bool isNotEmpty () const
Returns true if the feature set is not empty.
void merge (const FeatureSet &features)
bool operator!= (const FeatureSet &h) const
Equality operators.
FeatureSet & operator= (const FeatureSet &h)
bool operator== (const FeatureSet &h) const
bool operator[] (const FeatureType &type) const
void removeFeature (const FeatureType &type)
void setFeature (const FeatureType &type, bool set, S32 index=-1)
Static Public Attributes
static const FeatureSet EmptySet
Default empty feature set.
Protected Member Functions
void _rebuildDesc ()
Static Protected Member Functions
static S32 _typeCmp (const FeatureInfo *a, const FeatureInfo *b)
Protected Attributes
String mDescription
A string representation of all the features used for comparisons.
Vector< FeatureInfo > mFeatures
The list of featurs.
Constructor & Destructor Documentation
FeatureSet::FeatureSet () inline
FeatureSet::FeatureSet (const FeatureSet & h) inline
References operator=().
Member Function Documentation
void FeatureSet::_rebuildDesc () protected
static S32 FeatureSet::_typeCmp (const FeatureInfo * a, const FeatureInfo * b) static protected
void FeatureSet::addFeature (const FeatureType & type, S32 index = -1)
Referenced by getCount().
void FeatureSet::clear ()
Clears all features.
Referenced by getCount().
void FeatureSet::exclude (const FeatureSet & features)
Removes features that are in the input set.
Referenced by getCount().
void FeatureSet::filter (const FeatureSet & features)
Removes features that are not in the input set.
Referenced by getCount().
const FeatureType& FeatureSet::getAt (U32 index, S32 * outIndex = NULL) const
Returns the feature at the index and optionally the feature index when it was added.
Referenced by getCount().
U32 FeatureSet::getCount (void) const inline
Returns the feature count.
References addFeature(), clear(), exclude(), filter(), getAt(), getNextFeatureIndex(), hasFeature(), FeatureSet::FeatureInfo::index, merge(), removeFeature(), setFeature(), Vector< T >::size(), and FeatureSet::FeatureInfo::type.
const String & FeatureSet::getDescription (void) const inline
Return the description string which uniquely identifies this feature set.
References Vector< T >::empty(), String::isEmpty(), mDescription, and mFeatures.
Referenced by isNotEmpty(), operator!=(), and operator==().
S32 FeatureSet::getNextFeatureIndex (const FeatureType & type, S32 index) const
Referenced by getCount().
bool FeatureSet::hasFeature (const FeatureType & type, S32 index = -1) const
Returns true if this handle has this feature.
Referenced by getCount(), and operator[]().
bool FeatureSet::isEmpty (void) const inline
Returns true if the feature set is empty.
References Vector< T >::empty().
bool FeatureSet::isNotEmpty () const inline
Returns true if the feature set is not empty.
References Vector< T >::empty(), and getDescription().
void FeatureSet::merge (const FeatureSet & features)
Referenced by getCount().
bool FeatureSet::operator!= (const FeatureSet & h) const inline
Equality operators.
References getDescription().
FeatureSet& FeatureSet::operator= (const FeatureSet & h)
Referenced by FeatureSet().
bool FeatureSet::operator== (const FeatureSet & h) const inline
References getDescription().
bool FeatureSet::operator[] (const FeatureType & type) const inline
References hasFeature().
void FeatureSet::removeFeature (const FeatureType & type)
Referenced by getCount().
void FeatureSet::setFeature (const FeatureType & type, bool set, S32 index = -1)
Referenced by getCount().
Member Data Documentation
const FeatureSet FeatureSet::EmptySet static
Default empty feature set.
String FeatureSet::mDescription protected
A string representation of all the features used for comparisons.
Referenced by getDescription().
Vector<FeatureInfo> FeatureSet::mFeatures protected
The list of featurs.
Referenced by getDescription().
Copyright © GarageGames, LLC. All Rights Reserved.