PropertyInfo Namespace Reference
Main Modules Class List Namespace List Online
PropertyInfo Namespace Reference
Functions
bool default_print (String &result, const String &data)
bool default_print (String &result, const bool &data)
bool default_print (String &result, const F32 &data)
bool default_print (String &result, const U32 &data)
bool default_print (String &result, const S32 &data)
bool default_print (String &result, const Vector< F32 > &data)
bool default_print (String &result, const Vector< U32 > &data)
bool default_print (String &result, const Vector< S32 > &data)
bool default_print (String &result, const Point2F &data)
bool default_print (String &result, const Point2I &data)
bool default_print (String &result, const Point3F &data)
bool default_print (String &result, const Point3I &data)
bool default_print (String &result, const Point4F &data)
bool default_print (String &result, const Point4I &data)
bool default_print (String &result, const RectI &data)
bool default_print (String &result, const RectF &data)
bool default_print (String &result, const Box3I &data)
bool default_print (String &result, const Box3F &data)
bool default_print (String &result, const AngAxisF &data)
bool default_print (String &result, const QuatF &data)
bool default_print (String &result, const MatrixF &data)
bool default_print (String &result, const ColorF &data)
bool default_print (String &result, const ColorI &data)
bool default_print (String &result, const FileName &data)
bool default_print (String &result, SimObjectType const &data)
bool default_print (String &result, SimObject *const &data)
bool default_print (String &result, SimObjectType *const &data)
bool default_scan (const String &data, String &result)
bool default_scan (const String &data, bool &result)
bool default_scan (const String &data, F32 &result)
bool default_scan (const String &data, U32 &result)
bool default_scan (const String &data, S32 &result)
bool default_scan (const String &data, Vector< F32 > &result)
bool default_scan (const String &data, Vector< U32 > &result)
bool default_scan (const String &data, Vector< S32 > &result)
bool default_scan (const String &data, Point2F &result)
bool default_scan (const String &data, Point2I &result)
bool default_scan (const String &data, Point3F &result)
bool default_scan (const String &data, Point3I &result)
bool default_scan (const String &data, Point4F &result)
bool default_scan (const String &data, Point4I &result)
bool default_scan (const String &data, RectI &result)
bool default_scan (const String &data, RectF &result)
bool default_scan (const String &data, Box3I &result)
bool default_scan (const String &data, Box3F &result)
bool default_scan (const String &data, AngAxisF &result)
bool default_scan (const String &data, QuatF &result)
bool default_scan (const String &data, MatrixF &result)
bool default_scan (const String &data, ColorF &result)
bool default_scan (const String &data, ColorI &result)
bool default_scan (const String &data, FileName &result)
bool default_scan (const String &data, SimObjectType &result)
bool default_scan (const String &data, SimObject *&result)
bool hex_print (String &string, const U32 &hex)
bool hex_print (String &string, const S32 &hex)
bool hex_print (String &string, const U16 &hex)
bool hex_print (String &string, const S16 &hex)
bool hex_print (String &string, const U8 &hex)
bool hex_print (String &string, const S8 &hex)
bool hex_scan (const String &string, U32 &hex)
bool hex_scan (const String &string, S32 &hex)
bool hex_scan (const String &string, U16 &hex)
bool hex_scan (const String &string, S16 &hex)
bool hex_scan (const String &string, U8 &hex)
bool hex_scan (const String &string, S8 &hex)
template<class T >
bool typed_simobject_print (String &result, T *const &data)
template<class T >
bool typed_simobject_scan (const String &data, T *&result)
Function Documentation
bool PropertyInfo::default_print (String & result, const String & data)
Referenced by typed_simobject_print().
bool PropertyInfo::default_print (String & result, const bool & data)
bool PropertyInfo::default_print (String & result, const F32 & data)
bool PropertyInfo::default_print (String & result, const U32 & data)
bool PropertyInfo::default_print (String & result, const S32 & data)
bool PropertyInfo::default_print (String & result, const Vector< F32 > & data)
bool PropertyInfo::default_print (String & result, const Vector< U32 > & data)
bool PropertyInfo::default_print (String & result, const Vector< S32 > & data)
bool PropertyInfo::default_print (String & result, const Point2F & data)
bool PropertyInfo::default_print (String & result, const Point2I & data)
bool PropertyInfo::default_print (String & result, const Point3F & data)
bool PropertyInfo::default_print (String & result, const Point3I & data)
bool PropertyInfo::default_print (String & result, const Point4F & data)
bool PropertyInfo::default_print (String & result, const Point4I & data)
bool PropertyInfo::default_print (String & result, const RectI & data)
bool PropertyInfo::default_print (String & result, const RectF & data)
bool PropertyInfo::default_print (String & result, const Box3I & data)
bool PropertyInfo::default_print (String & result, const Box3F & data)
bool PropertyInfo::default_print (String & result, const AngAxisF & data)
bool PropertyInfo::default_print (String & result, const QuatF & data)
bool PropertyInfo::default_print (String & result, const MatrixF & data)
bool PropertyInfo::default_print (String & result, const ColorF & data)
bool PropertyInfo::default_print (String & result, const ColorI & data)
bool PropertyInfo::default_print (String & result, const FileName & data)
bool PropertyInfo::default_print (String & result, SimObjectType const & data)
bool PropertyInfo::default_print (String & result, SimObject *const & data)
bool PropertyInfo::default_print (String & result, SimObjectType *const & data)
bool PropertyInfo::default_scan (const String & data, String & result)
Referenced by typed_simobject_scan().
bool PropertyInfo::default_scan (const String & data, bool & result)
bool PropertyInfo::default_scan (const String & data, F32 & result)
bool PropertyInfo::default_scan (const String & data, U32 & result)
bool PropertyInfo::default_scan (const String & data, S32 & result)
bool PropertyInfo::default_scan (const String & data, Vector< F32 > & result)
bool PropertyInfo::default_scan (const String & data, Vector< U32 > & result)
bool PropertyInfo::default_scan (const String & data, Vector< S32 > & result)
bool PropertyInfo::default_scan (const String & data, Point2F & result)
bool PropertyInfo::default_scan (const String & data, Point2I & result)
bool PropertyInfo::default_scan (const String & data, Point3F & result)
bool PropertyInfo::default_scan (const String & data, Point3I & result)
bool PropertyInfo::default_scan (const String & data, Point4F & result)
bool PropertyInfo::default_scan (const String & data, Point4I & result)
bool PropertyInfo::default_scan (const String & data, RectI & result)
bool PropertyInfo::default_scan (const String & data, RectF & result)
bool PropertyInfo::default_scan (const String & data, Box3I & result)
bool PropertyInfo::default_scan (const String & data, Box3F & result)
bool PropertyInfo::default_scan (const String & data, AngAxisF & result)
bool PropertyInfo::default_scan (const String & data, QuatF & result)
bool PropertyInfo::default_scan (const String & data, MatrixF & result)
bool PropertyInfo::default_scan (const String & data, ColorF & result)
bool PropertyInfo::default_scan (const String & data, ColorI & result)
bool PropertyInfo::default_scan (const String & data, FileName & result)
bool PropertyInfo::default_scan (const String & data, SimObjectType & result)
bool PropertyInfo::default_scan (const String & data, SimObject *& result)
bool PropertyInfo::hex_print (String & string, const U32 & hex)
Referenced by typed_simobject_print().
bool PropertyInfo::hex_print (String & string, const S32 & hex)
bool PropertyInfo::hex_print (String & string, const U16 & hex)
bool PropertyInfo::hex_print (String & string, const S16 & hex)
bool PropertyInfo::hex_print (String & string, const U8 & hex)
bool PropertyInfo::hex_print (String & string, const S8 & hex)
bool PropertyInfo::hex_scan (const String & string, U32 & hex)
Referenced by typed_simobject_print().
bool PropertyInfo::hex_scan (const String & string, S32 & hex)
bool PropertyInfo::hex_scan (const String & string, U16 & hex)
bool PropertyInfo::hex_scan (const String & string, S16 & hex)
bool PropertyInfo::hex_scan (const String & string, U8 & hex)
bool PropertyInfo::hex_scan (const String & string, S8 & hex)
template<class T > bool PropertyInfo::typed_simobject_print (String & result, T *const & data) inline
References default_print(), hex_print(), and hex_scan().
template<class T > bool PropertyInfo::typed_simobject_scan (const String & data, T *& result) inline
References default_scan(), and T.
Copyright © GarageGames, LLC. All Rights Reserved.