Con Namespace Reference
Main Modules Class List Namespace List Online
Con Namespace Reference
Console SystemConsole System » | Reflection
This namespace contains the core of the console functionality.
Classes
class XMLExport
Enumerations
enum Constants {
DSOVersion = 48,
MaxLineLength = 512,
MaxDataTypes = 256
}
Various configuration constants.
Functions
bool isMainThread ()
Returns true when called from the main thread, false otherwise.
bool isScriptPathExpando (const char *expando)
void removeScriptPathExpando (const char *expando)
void setScriptPathExpando (const char *expando, const char *path, bool toolsOnly=false)
Control Functions
The console must be initialized and shutdown appropriately during the lifetime of the app.
These functions are used to manage this behavior.
Note
Torque deals with this aspect of console management, so you don't need to call these functions in normal usage of the engine.
void init ()
Initializes the console.
void shutdown ()
Shuts down the console.
bool isActive ()
Is the console active at this time?
Miscellaneous
void stripColorChars (char *line)
Remove color marking information from a string.
bool expandScriptFilename (char *filename, U32 size, const char *src)
Convert from a relative script path to an absolute script path.
bool expandGameScriptFilename (char *filename, U32 size, const char *src)
bool expandToolScriptFilename (char *filename, U32 size, const char *src)
bool collapseScriptFilename (char *filename, U32 size, const char *src)
bool expandPath (char *pDstPath, U32 size, const char *pSrcPath, const char *pWorkingDirectoryHint=NULL, const bool ensureTrailingSlash=false)
void collapsePath (char *pDstPath, U32 size, const char *pSrcPath, const char *pWorkingDirectoryHint=NULL)
bool isBasePath (const char *SrcPath, const char *pBasePath)
void ensureTrailingSlash (char *pDstPath, const char *pSrcPath)
bool stripRepeatSlashes (char *pDstPath, const char *pSrcPath, S32 dstSize)
StringTableEntry getDSOPath (const char *scriptPath)
void addPathExpando (const char *pExpandoName, const char *pPath)
void removePathExpando (const char *pExpandoName)
bool isPathExpando (const char *pExpandoName)
StringTableEntry getPathExpando (const char *pExpandoName)
U32 getPathExpandoCount (void)
StringTableEntry getPathExpandoKey (U32 expandoIndex)
StringTableEntry getPathExpandoValue (U32 expandoIndex)
bool isCurrentScriptToolScript ()
StringTableEntry getModNameFromPath (const char *path)
bool isFunction (const char *fn)
Returns true if fn is a global scripting function.
U32 tabComplete (char *inputBuffer, U32 cursorPos, U32 maxResultLength, bool forwardTab)
This is the basis for tab completion in the console.
Global Variable Accessors
Assign a string value to a global console variable
Parameters
name Global console variable name to set
value String value to assign to this variable.
void setVariable (const char *name, const char *value)
const char * getVariable (const char *name)
Retrieve the string value of a global console variable.
const char * getObjectField (const char *name)
Retrieve the string value of an object field.
void setBoolVariable (const char *name, bool var)
Same as setVariable(), but for bools.
bool getBoolVariable (const char *name, bool def=false)
Same as getVariable(), but for bools.
void setIntVariable (const char *name, S32 var)
Same as setVariable(), but for ints.
S32 getIntVariable (const char *name, S32 def=0)
Same as getVariable(), but for ints.
void setFloatVariable (const char *name, F32 var)
Same as setVariable(), but for floats.
F32 getFloatVariable (const char *name, F32 def=.0f)
Same as getVariable(), but for floats.
Global Function Registration
void addCommand (const char *name, StringCallback cb, const char *usage, S32 minArgs, S32 maxArgs, bool toolOnly=false, ConsoleFunctionHeader *header=NULL)
Register a C++ function with the console making it a global function callable from the scripting engine.
void addCommand (const char *name, IntCallback cb, const char *usage, S32 minArgs, S32 maxArgs, bool toolOnly=false, ConsoleFunctionHeader *header=NULL)
Register a C++ function with the console making it a global function callable from the scripting engine.
void addCommand (const char *name, FloatCallback cb, const char *usage, S32 minArgs, S32 maxArgs, bool toolOnly=false, ConsoleFunctionHeader *header=NULL)
Register a C++ function with the console making it a global function callable from the scripting engine.
void addCommand (const char *name, VoidCallback cb, const char *usage, S32 minArgs, S32 maxArgs, bool toolOnly=false, ConsoleFunctionHeader *header=NULL)
Register a C++ function with the console making it a global function callable from the scripting engine.
void addCommand (const char *name, BoolCallback cb, const char *usage, S32 minArgs, S32 maxArgs, bool toolOnly=false, ConsoleFunctionHeader *header=NULL)
Register a C++ function with the console making it a global function callable from the scripting engine.
Namespace Function Registration
void addCommand (const char *nameSpace, const char *name, StringCallback cb, const char *usage, S32 minArgs, S32 maxArgs, bool toolOnly=false, ConsoleFunctionHeader *header=NULL)
Register a C++ function with the console making it callable as a method of the given namespace from the scripting engine.
void addCommand (const char *nameSpace, const char *name, IntCallback cb, const char *usage, S32 minArgs, S32 maxArgs, bool toolOnly=false, ConsoleFunctionHeader *header=NULL)
Register a C++ function with the console making it callable as a method of the given namespace from the scripting engine.
void addCommand (const char *nameSpace, const char *name, FloatCallback cb, const char *usage, S32 minArgs, S32 maxArgs, bool toolOnly=false, ConsoleFunctionHeader *header=NULL)
Register a C++ function with the console making it callable as a method of the given namespace from the scripting engine.
void addCommand (const char *nameSpace, const char *name, VoidCallback cb, const char *usage, S32 minArgs, S32 maxArgs, bool toolOnly=false, ConsoleFunctionHeader *header=NULL)
Register a C++ function with the console making it callable as a method of the given namespace from the scripting engine.
void addCommand (const char *nameSpace, const char *name, BoolCallback cb, const char *usage, S32 minArgs, S32 maxArgs, bool toolOnly=false, ConsoleFunctionHeader *header=NULL)
Register a C++ function with the console making it callable as a method of the given namespace from the scripting engine.
Special Purpose Registration
These are special-purpose functions that exist to allow commands to be grouped, so that when we generate console docs, they can be more meaningfully presented.
Click here for more information about console docs and grouping.
void markCommandGroup (const char *nsName, const char *name, const char *usage=NULL)
void beginCommandGroup (const char *nsName, const char *name, const char *usage)
void endCommandGroup (const char *nsName, const char *name)
void noteScriptCallback (const char *className, const char *funcName, const char *usage, ConsoleFunctionHeader *header=NULL)
Console Output
These functions process the formatted string and pass it to all the ConsumerCallbacks that are currently registered.
The console log file and the console window callbacks are installed by default.
See also
addConsumer()
removeConsumer()
void printf (const char *_format,...)
void warnf (const char *_format,...)
void errorf (const char *_format,...)
void warnf (ConsoleLogEntry::Type type, const char *_format,...)
void errorf (ConsoleLogEntry::Type type, const char *_format,...)
void printSeparator (void)
Prints a separator to the console.
void printBlankLine (void)
Prints a separator to the console.
Console Execution
These are functions relating to the execution of script code.
ConsoleValueRef execute (S32 argc, const char *argv[])
Call a script function from C/C++ code.
ConsoleValueRef execute (S32 argc, ConsoleValueRef argv[])
ConsoleValueRef execute (SimObject *object, S32 argc, const char *argv[], bool thisCallOnly=false)
Call a Torque Script member function of a SimObject from C/C++ code.
ConsoleValueRef execute (SimObject *object, S32 argc, ConsoleValueRef argv[], bool thisCallOnly=false)
bool executeFile (const char *fileName, bool noCalls, bool journalScript)
Executes a script file and compiles it for use in script.
ConsoleValueRef evaluate (const char *string, bool echo=false, const char *fileName=NULL)
Evaluate an arbitrary chunk of code.
ConsoleValueRef evaluatef (const char *string,...)
Evaluate an arbitrary line of script.
Console Function Implementation Helpers
The functions Con::getIntArg, Con::getFloatArg and Con::getArgBuffer(size) are used to allocate on the console stack string variables that will be passed into the next console
char * getReturnBuffer (U32 bufferSize)
getReturnBuffer lets you allocate stack space to return data in.
char * getReturnBuffer (const char *stringToCopy)
char * getReturnBuffer (const String &str)
char * getReturnBuffer (const StringBuilder &str)
char * getArgBuffer (U32 bufferSize)
char * getFloatArg (F64 arg)
char * getIntArg (S32 arg)
char * getBoolArg (bool arg)
char * getStringArg (const char *arg)
char * getStringArg (const String &arg)
Namespaces
Namespace * lookupNamespace (const char *nsName)
bool linkNamespaces (const char *parentName, const char *childName)
bool unlinkNamespaces (const char *parentName, const char *childName)
bool classLinkNamespaces (Namespace *parent, Namespace *child)
const char * getNamespaceList (Namespace *ns)
Logging
void getLockLog (ConsoleLogEntry *&log, U32 &size)
void unlockLog (void)
void setLogMode (S32 mode)
Instant Group
void pushInstantGroup (String name=String())
void popInstantGroup ()
Dynamic Type System
void setData (S32 type, void *dptr, S32 index, S32 argc, const char **argv, const EnumTable *tbl=NULL, BitSet32 flag=0)
const char * getData (S32 type, void *dptr, S32 index, const EnumTable *tbl=NULL, BitSet32 flag=0)
const char * getFormattedData (S32 type, const char *data, const EnumTable *tbl=NULL, BitSet32 flag=0)
Console Execution - executef
{
Implements a script function thunk which automatically converts parameters to relevant console types. Can be used as follows:
Con::executef("functionName", ...);
Con::executef(mySimObject, "functionName", ...);
NOTE: if you get a rather cryptic template error coming through here, most likely you are trying to convert a parameter which EngineMarshallType does not have a specialization for. Another problem can occur if you do not include "console/simBase.h" and "console/engineAPI.h" since _EngineConsoleExecCallbackHelper and SimConsoleThreadExecCallback are required.
See also
_EngineConsoleExecCallbackHelper
template<typename R , typename... ArgTs>
ConsoleValueRef executef (R r, ArgTs...argTs)
Variables
String gInstantGroup
The current $instantGroup setting.
Console Consumers
The console distributes its output through Torque by using consumers.
Every time a new line is printed to the console, all the ConsumerCallbacks registered using addConsumer are called, in order.
Note
The GuiConsole control, which provides the on-screen in-game console, uses a different technique to render the console. It calls getLockLog() to lock the Vector of on-screen console entries, then it renders them as needed. While the Vector is locked, the console will not change the Vector. When the GuiConsole control is done with the console entries, it calls unlockLog() to tell the console that it is again safe to modify the Vector.
See also
TelnetConsole
TelnetDebugger
WinConsole
MacCarbConsole
StdConsole
ConsoleLogger
typedef JournaledSignal< void(RawData)> ConsoleInputEvent
ConsoleInputEvent smConsoleInput
Called from the native consoles to provide lines of console input to process.
void addConsumer (ConsumerCallback cb)
void removeConsumer (ConsumerCallback cb)
Variable Management
typedef Delegate< void()> NotifyDelegate
The delegate signature for the variable assignment notifications.
void addVariable (const char *name, S32 type, void *pointer, const char *usage=NULL)
Add a console variable that references the value of a variable in C++ code.
void addConstant (const char *name, S32 type, const void *pointer, const char *usage=NULL)
Add a console constant that references the value of a constant in C++ code.
bool removeVariable (const char *name)
Remove a console variable.
void addVariableNotify (const char *name, const NotifyDelegate &callback)
Add a callback for notification when a variable is assigned a new value.
void removeVariableNotify (const char *name, const NotifyDelegate &callback)
Remove an existing variable assignment notification callback.
void setLocalVariable (const char *name, const char *value)
Assign a string value to a locally scoped console variable.
const char * getLocalVariable (const char *name)
Retrieve the string value to a locally scoped console variable.
Detailed Description
This namespace contains the core of the console functionality.
Introduction
The console is a key part of Torque's architecture. It allows direct run-time control of many aspects of the engine.
Typedef Documentation
typedef JournaledSignal<void(RawData)> Con::ConsoleInputEvent
typedef Delegate<void()> Con::NotifyDelegate
The delegate signature for the variable assignment notifications.
See also
addVariableNotify, removeVariableNotify
Enumeration Type Documentation
enum Con::Constants
Various configuration constants.
Enumerator
DSOVersion
This is the version number associated with DSO files.
If you make any changes to the way the scripting language works (such as DSO format changes, adding/removing op-codes) that would break compatibility, then you should increment this.
If you make a really major change, increment it to the next multiple of ten.
12/29/04 - BJG - 33->34 Removed some opcodes, part of namespace upgrade. 12/30/04 - BJG - 34->35 Reordered some things, further general shuffling. 11/03/05 - BJG - 35->36 Integrated new debugger code. 07/31/07 - THB - 42->43 Patch from Andreas Kirsch: Added opcode to support nested new declarations. 09/12/07 - CAF - 43->44 remove newmsg operator 09/27/07 - RDB - 44->45 Patch from Andreas Kirsch: Added opcode to support correct void return 01/13/09 - TMS - 45->46 Added script assert 09/07/14 - jamesu - 46->47 64bit support 10/14/14 - jamesu - 47->48 Added opcodes to reduce reliance on strings in function calls
MaxLineLength
Maximum length of a line of console input.
MaxDataTypes
Maximum number of registered data types.
Function Documentation
void Con::addCommand (const char * name, StringCallback cb, const char * usage, S32 minArgs, S32 maxArgs, bool toolOnly = false, ConsoleFunctionHeader * header = NULL)
Register a C++ function with the console making it a global function callable from the scripting engine.
Parameters
name Name of the new function.
cb Pointer to the function implementing the scripting call; a console callback function returning a specific type value.
usage Documentation for this function. console_autodoc
minArgs Minimum number of arguments this function accepts
maxArgs Maximum number of arguments this function accepts
toolOnly Wether this is a TORQUE_TOOLS only function.
header The extended function header.
void Con::addCommand (const char * name, IntCallback cb, const char * usage, S32 minArgs, S32 maxArgs, bool toolOnly = false, ConsoleFunctionHeader * header = NULL)
Register a C++ function with the console making it a global function callable from the scripting engine.
Parameters
name Name of the new function.
cb Pointer to the function implementing the scripting call; a console callback function returning a specific type value.
usage Documentation for this function. console_autodoc
minArgs Minimum number of arguments this function accepts
maxArgs Maximum number of arguments this function accepts
toolOnly Wether this is a TORQUE_TOOLS only function.
header The extended function header.
void Con::addCommand (const char * name, FloatCallback cb, const char * usage, S32 minArgs, S32 maxArgs, bool toolOnly = false, ConsoleFunctionHeader * header = NULL)
Register a C++ function with the console making it a global function callable from the scripting engine.
Parameters
name Name of the new function.
cb Pointer to the function implementing the scripting call; a console callback function returning a specific type value.
usage Documentation for this function. console_autodoc
minArgs Minimum number of arguments this function accepts
maxArgs Maximum number of arguments this function accepts
toolOnly Wether this is a TORQUE_TOOLS only function.
header The extended function header.
void Con::addCommand (const char * name, VoidCallback cb, const char * usage, S32 minArgs, S32 maxArgs, bool toolOnly = false, ConsoleFunctionHeader * header = NULL)
Register a C++ function with the console making it a global function callable from the scripting engine.
Parameters
name Name of the new function.
cb Pointer to the function implementing the scripting call; a console callback function returning a specific type value.
usage Documentation for this function. console_autodoc
minArgs Minimum number of arguments this function accepts
maxArgs Maximum number of arguments this function accepts
toolOnly Wether this is a TORQUE_TOOLS only function.
header The extended function header.
void Con::addCommand (const char * name, BoolCallback cb, const char * usage, S32 minArgs, S32 maxArgs, bool toolOnly = false, ConsoleFunctionHeader * header = NULL)
Register a C++ function with the console making it a global function callable from the scripting engine.
Parameters
name Name of the new function.
cb Pointer to the function implementing the scripting call; a console callback function returning a specific type value.
usage Documentation for this function. console_autodoc
minArgs Minimum number of arguments this function accepts
maxArgs Maximum number of arguments this function accepts
toolOnly Wether this is a TORQUE_TOOLS only function.
header The extended function header.
void Con::addCommand (const char * nameSpace, const char * name, StringCallback cb, const char * usage, S32 minArgs, S32 maxArgs, bool toolOnly = false, ConsoleFunctionHeader * header = NULL)
Register a C++ function with the console making it callable as a method of the given namespace from the scripting engine.
Parameters
nameSpace Name of the namespace to associate the new function with; this is usually the name of a class.
name Name of the new function.
cb Pointer to the function implementing the scripting call; a console callback function returning a specific type value.
usage Documentation for this function. console_autodoc
minArgs Minimum number of arguments this function accepts
maxArgs Maximum number of arguments this function accepts
toolOnly Wether this is a TORQUE_TOOLS only function.
header The extended function header.
void Con::addCommand (const char * nameSpace, const char * name, IntCallback cb, const char * usage, S32 minArgs, S32 maxArgs, bool toolOnly = false, ConsoleFunctionHeader * header = NULL)
Register a C++ function with the console making it callable as a method of the given namespace from the scripting engine.
Parameters
nameSpace Name of the namespace to associate the new function with; this is usually the name of a class.
name Name of the new function.
cb Pointer to the function implementing the scripting call; a console callback function returning a specific type value.
usage Documentation for this function. console_autodoc
minArgs Minimum number of arguments this function accepts
maxArgs Maximum number of arguments this function accepts
toolOnly Wether this is a TORQUE_TOOLS only function.
header The extended function header.
void Con::addCommand (const char * nameSpace, const char * name, FloatCallback cb, const char * usage, S32 minArgs, S32 maxArgs, bool toolOnly = false, ConsoleFunctionHeader * header = NULL)
Register a C++ function with the console making it callable as a method of the given namespace from the scripting engine.
Parameters
nameSpace Name of the namespace to associate the new function with; this is usually the name of a class.
name Name of the new function.
cb Pointer to the function implementing the scripting call; a console callback function returning a specific type value.
usage Documentation for this function. console_autodoc
minArgs Minimum number of arguments this function accepts
maxArgs Maximum number of arguments this function accepts
toolOnly Wether this is a TORQUE_TOOLS only function.
header The extended function header.
void Con::addCommand (const char * nameSpace, const char * name, VoidCallback cb, const char * usage, S32 minArgs, S32 maxArgs, bool toolOnly = false, ConsoleFunctionHeader * header = NULL)
Register a C++ function with the console making it callable as a method of the given namespace from the scripting engine.
Parameters
nameSpace Name of the namespace to associate the new function with; this is usually the name of a class.
name Name of the new function.
cb Pointer to the function implementing the scripting call; a console callback function returning a specific type value.
usage Documentation for this function. console_autodoc
minArgs Minimum number of arguments this function accepts
maxArgs Maximum number of arguments this function accepts
toolOnly Wether this is a TORQUE_TOOLS only function.
header The extended function header.
void Con::addCommand (const char * nameSpace, const char * name, BoolCallback cb, const char * usage, S32 minArgs, S32 maxArgs, bool toolOnly = false, ConsoleFunctionHeader * header = NULL)
Register a C++ function with the console making it callable as a method of the given namespace from the scripting engine.
Parameters
nameSpace Name of the namespace to associate the new function with; this is usually the name of a class.
name Name of the new function.
cb Pointer to the function implementing the scripting call; a console callback function returning a specific type value.
usage Documentation for this function. console_autodoc
minArgs Minimum number of arguments this function accepts
maxArgs Maximum number of arguments this function accepts
toolOnly Wether this is a TORQUE_TOOLS only function.
header The extended function header.
void Con::addConstant (const char * name, S32 type, const void * pointer, const char * usage = NULL)
Add a console constant that references the value of a constant in C++ code.
Parameters
name Global console constant name to create.
type The type of the C++ constant; see the ConsoleDynamicTypes enum for a complete list.
pointer Pointer to the constant.
usage Documentation string.
See also
ConsoleDynamicTypes
void Con::addConsumer (ConsumerCallback cb)
void Con::addPathExpando (const char * pExpandoName, const char * pPath)
void Con::addVariable (const char * name, S32 type, void * pointer, const char * usage = NULL)
Add a console variable that references the value of a variable in C++ code.
If a value is assigned to the console variable the C++ variable is updated, and vice-versa.
Parameters
name Global console variable name to create.
type The type of the C++ variable; see the ConsoleDynamicTypes enum for a complete list.
pointer Pointer to the variable.
usage Documentation string.
See also
ConsoleDynamicTypes
void Con::addVariableNotify (const char * name, const NotifyDelegate & callback)
Add a callback for notification when a variable is assigned a new value.
Parameters
name An existing global console variable name.
callback The notification delegate function.
void Con::beginCommandGroup (const char * nsName, const char * name, const char * usage)
bool Con::classLinkNamespaces (Namespace * parent, Namespace * child)
Note
This should only be called from consoleObject.h
Referenced by RuntimeClassRep< T >::init(), ConcreteAbstractClassRep< T >::init(), and printBlankLine().
void Con::collapsePath (char * pDstPath, U32 size, const char * pSrcPath, const char * pWorkingDirectoryHint = NULL)
bool Con::collapseScriptFilename (char * filename, U32 size, const char * src)
void Con::endCommandGroup (const char * nsName, const char * name)
void Con::ensureTrailingSlash (char * pDstPath, const char * pSrcPath)
void Con::errorf (const char * _format, ...)
Note
The console window colors warning text as RED.
Parameters
_format A stdlib printf style formatted out put string
... Variables to be written
Referenced by ColorI::convertFromHex(), RuntimeClassRep< T >::setData(), ConcreteAbstractClassRep< T >::setData(), Dictionary::Entry::setFloatValue(), Dictionary::Entry::setIntValue(), Dictionary::Entry::setStringStackPtrValue(), Dictionary::Entry::setStringValue(), and SceneAmbientSoundObject< Base >::unpackUpdate().
void Con::errorf (ConsoleLogEntry::Type type, const char * _format, ...)
Note
The console window colors warning text as RED.
Parameters
type Allows you to associate the warning message with an internal module.
_format A stdlib printf style formatted out put string
... Variables to be written
See also
Con::errorf()
ConsoleValueRef Con::evaluate (const char * string, bool echo = false, const char * fileName = NULL)
Evaluate an arbitrary chunk of code.
Parameters
string Buffer containing code to execute.
echo Should we echo the string to the console?
fileName Indicate what file this code is coming from; used in error reporting and such. NOTE: This function restores the console stack on return.
Referenced by printBlankLine().
ConsoleValueRef Con::evaluatef (const char * string, ...)
Evaluate an arbitrary line of script.
This wraps dVsprintf(), so you can substitute parameters into the code being executed. NOTE: This function restores the console stack on return.
Referenced by printBlankLine().
ConsoleValueRef Con::execute (S32 argc, const char * argv[])
Call a script function from C/C++ code.
Parameters
argc Number of elements in the argv parameter
argv A character string array containing the name of the function to call followed by the arguments to that function.
// Call a Torque script function called mAbs, having one parameter.
char* argv[] = {"abs", "-9"};
char* result = execute(2, argv);
NOTE: this function restores the console stack on return.
Referenced by printBlankLine().
ConsoleValueRef Con::execute (S32 argc, ConsoleValueRef argv[])
ConsoleValueRef Con::execute (SimObject * object, S32 argc, const char * argv[], bool thisCallOnly = false)
Call a Torque Script member function of a SimObject from C/C++ code.
Parameters
object Object on which to execute the method call.
argc Number of elements in the argv parameter (must be >2, see argv)
argv A character string array containing the name of the member function to call followed by an empty parameter (gets filled with object ID) followed by arguments to that function.
// Call the method setMode() on an object, passing it one parameter.
char* argv[] = {"setMode", "", "2"};
char* result = execute(mysimobject, 3, argv);
NOTE: this function restores the console stack on return.
ConsoleValueRef Con::execute (SimObject * object, S32 argc, ConsoleValueRef argv[], bool thisCallOnly = false)
template<typename R , typename... ArgTs> ConsoleValueRef Con::executef (R r, ArgTs... argTs)
References collapseEscape(), executef(), expandEscape(), and HashPointer().
Referenced by executef(), UndoScriptAction::onAdd(), UndoScriptAction::onRemove(), UndoScriptAction::redo(), and UndoScriptAction::undo().
bool Con::executeFile (const char * fileName, bool noCalls, bool journalScript)
Executes a script file and compiles it for use in script.
Parameters
string File name that is the script to be executed and compiled.
fileName Path to the file to execute
noCalls Deprecated
journalScript Deprecated
Returns
True if the script was successfully executed, false if not.
Referenced by printBlankLine().
bool Con::expandGameScriptFilename (char * filename, U32 size, const char * src)
bool Con::expandPath (char * pDstPath, U32 size, const char * pSrcPath, const char * pWorkingDirectoryHint = NULL, const bool ensureTrailingSlash = false)
Referenced by TamlAssetDeclaredVisitor::visit().
bool Con::expandScriptFilename (char * filename, U32 size, const char * src)
Convert from a relative script path to an absolute script path.
This is used in (among other places) the exec() script function, which takes a parameter indicating a script file and executes it. Script paths can be one of:
Absolute: fps/foo/bar.cs Paths of this sort are passed through.
Mod-relative: ~/foo/bar.cs Paths of this sort have their replaced with the name of the current mod.
File-relative: ./baz/blip.cs Paths of this sort are calculated relative to the path of the current scripting file.
Note
This function determines paths relative to the currently executing CodeBlock. Calling it outside of script execution will result in it directly copying src to filename, since it won't know to what the path is relative!
Parameters
filename Pointer to string buffer to fill with absolute path.
size Size of buffer pointed to by filename.
src Original, possibly relative script path.
bool Con::expandToolScriptFilename (char * filename, U32 size, const char * src)
char* Con::getArgBuffer (U32 bufferSize)
Referenced by printBlankLine().
char* Con::getBoolArg (bool arg)
Referenced by AssetBase::getAssetAutoUnload(), AssetBase::getAssetInternal(), AssetBase::getAssetPrivate(), and printBlankLine().
bool Con::getBoolVariable (const char * name, bool def = false)
Same as getVariable(), but for bools.
Parameters
name Name of the variable.
def Default value to supply if no matching variable is found.
const char* Con::getData (S32 type, void * dptr, S32 index, const EnumTable * tbl = NULL, BitSet32 flag = 0)
Referenced by printBlankLine(), and TamlCustomField::setFieldValue().
StringTableEntry Con::getDSOPath (const char * scriptPath)
char* Con::getFloatArg (F64 arg)
Referenced by printBlankLine().
F32 Con::getFloatVariable (const char * name, F32 def = .0f)
Same as getVariable(), but for floats.
Parameters
name Name of the variable.
def Default value to supply if no matching variable is found.
const char* Con::getFormattedData (S32 type, const char * data, const EnumTable * tbl = NULL, BitSet32 flag = 0)
Referenced by printBlankLine().
char* Con::getIntArg (S32 arg)
Referenced by AssetQuery::getCount(), ModuleDefinition::getScopeSet(), and printBlankLine().
S32 Con::getIntVariable (const char * name, S32 def = 0)
Same as getVariable(), but for ints.
Parameters
name Name of the variable.
def Default value to supply if no matching variable is found.
const char* Con::getLocalVariable (const char * name)
Retrieve the string value to a locally scoped console variable.
Note
The context of the variable is determined by gEvalState; that is, by the currently executing code.
Parameters
name Local console variable name to get
void Con::getLockLog (ConsoleLogEntry *& log, U32 & size)
Referenced by printBlankLine().
StringTableEntry Con::getModNameFromPath (const char * path)
const char* Con::getNamespaceList (Namespace * ns)
Referenced by printBlankLine().
const char* Con::getObjectField (const char * name)
Retrieve the string value of an object field.
Parameters
name "object.field" string to query
Returns
The string value of the variable or NULL if no object is specified
StringTableEntry Con::getPathExpando (const char * pExpandoName)
U32 Con::getPathExpandoCount (void)
StringTableEntry Con::getPathExpandoKey (U32 expandoIndex)
StringTableEntry Con::getPathExpandoValue (U32 expandoIndex)
char* Con::getReturnBuffer (U32 bufferSize)
getReturnBuffer lets you allocate stack space to return data in.
Referenced by RuntimeClassRep< T >::getData(), BitfieldConsoleBaseType::getData(), ConcreteAbstractClassRep< T >::getData(), ModuleDefinition::getDependencies(), _EngineMethodTrampoline< Frame, R(ArgTs...) >::jmp(), and printBlankLine().
char* Con::getReturnBuffer (const char * stringToCopy)
char* Con::getReturnBuffer (const String & str)
char* Con::getReturnBuffer (const StringBuilder & str)
char* Con::getStringArg (const char * arg)
Referenced by printBlankLine().
char* Con::getStringArg (const String & arg)
const char* Con::getVariable (const char * name)
Retrieve the string value of a global console variable.
Parameters
name Global Console variable name to query
Returns
The string value of the variable or "" if the variable does not exist.
void Con::init ()
Initializes the console.
This performs the following steps:
Calls Namespace::init() to initialize the scripting namespace hierarchy.
Calls ConsoleConstructor::setup() to initialize globally defined console methods and functions.
Registers some basic global script variables.
Calls AbstractClassRep::init() to initialize Torque's class database.
Registers some basic global script functions that couldn't usefully be defined anywhere else.
bool Con::isActive ()
Is the console active at this time?
bool Con::isBasePath (const char * SrcPath, const char * pBasePath)
bool Con::isCurrentScriptToolScript ()
bool Con::isFunction (const char * fn)
Returns true if fn is a global scripting function.
This looks in the global namespace. It also checks to see if fn is in the StringTable; if not, it returns false.
bool Con::isMainThread ()
Returns true when called from the main thread, false otherwise.
Referenced by _EngineConsoleCallbackHelper::call(), _EngineConsoleExecCallbackHelper< P1 >::call(), _EngineConsoleExecCallbackHelper< const char * >::call(), StringStack::getArgBuffer(), StringStack::getReturnBuffer(), and printBlankLine().
bool Con::isPathExpando (const char * pExpandoName)
bool Con::isScriptPathExpando (const char * expando)
bool Con::linkNamespaces (const char * parentName, const char * childName)
Referenced by printBlankLine().
Namespace* Con::lookupNamespace (const char * nsName)
Referenced by RuntimeClassRep< T >::consoleRegister(), and printBlankLine().
void Con::markCommandGroup (const char * nsName, const char * name, const char * usage = NULL)
void Con::noteScriptCallback (const char * className, const char * funcName, const char * usage, ConsoleFunctionHeader * header = NULL)
void Con::popInstantGroup ()
Referenced by printBlankLine().
void Con::printBlankLine (void) inline
Prints a separator to the console.
References classLinkNamespaces(), evaluate(), evaluatef(), execute(), executeFile(), getArgBuffer(), getBoolArg(), getData(), getFloatArg(), getFormattedData(), getIntArg(), getLockLog(), getNamespaceList(), getReturnBuffer(), getStringArg(), isMainThread(), linkNamespaces(), lookupNamespace(), popInstantGroup(), printBlankLine(), printf(), pushInstantGroup(), setData(), setLogMode(), unlinkNamespaces(), and unlockLog().
Referenced by printBlankLine().
void Con::printf (const char * _format, ...)
Parameters
_format A stdlib printf style formatted out put string
... Variables to be written
Referenced by AssetManager::acquireAsset(), ScopeTracker< NUM_DIMENSIONS, Object >::debugDump(), printBlankLine(), printSeparator(), SceneLighting::ObjectProxy::processStartObjectLightingEvent(), and SceneLighting::ObjectProxy::processTGELightProcessEvent().
void Con::printSeparator (void) inline
Prints a separator to the console.
References printf(), and printSeparator().
Referenced by AssetManager::acquireAsset(), and printSeparator().
void Con::pushInstantGroup (String name = String())
Referenced by printBlankLine().
void Con::removeConsumer (ConsumerCallback cb)
void Con::removePathExpando (const char * pExpandoName)
void Con::removeScriptPathExpando (const char * expando)
bool Con::removeVariable (const char * name)
Remove a console variable.
Parameters
name Global console variable name to remove
Returns
true if variable existed before removal.
void Con::removeVariableNotify (const char * name, const NotifyDelegate & callback)
Remove an existing variable assignment notification callback.
Parameters
name An existing global console variable name.
callback The notification delegate function.
void Con::setBoolVariable (const char * name, bool var)
Same as setVariable(), but for bools.
void Con::setData (S32 type, void * dptr, S32 index, S32 argc, const char ** argv, const EnumTable * tbl = NULL, BitSet32 flag = 0)
Referenced by TamlCustomField::getFieldValue(), printBlankLine(), and ConsoleObject::setField().
void Con::setFloatVariable (const char * name, F32 var)
Same as setVariable(), but for floats.
void Con::setIntVariable (const char * name, S32 var)
Same as setVariable(), but for ints.
void Con::setLocalVariable (const char * name, const char * value)
Assign a string value to a locally scoped console variable.
Note
The context of the variable is determined by gEvalState; that is, by the currently executing code.
Parameters
name Local console variable name to set
value String value to assign to name
void Con::setLogMode (S32 mode)
Referenced by printBlankLine().
void Con::setScriptPathExpando (const char * expando, const char * path, bool toolsOnly = false)
void Con::setVariable (const char * name, const char * value)
void Con::shutdown ()
Shuts down the console.
This performs the following steps:
Closes the console log file.
Calls Namespace::shutdown() to shut down the scripting namespace hierarchy.
void Con::stripColorChars (char * line)
Remove color marking information from a string.
Note
It does this in-place, so be careful! It may potentially blast data if you're not careful. When in doubt, make a copy of the string first.
bool Con::stripRepeatSlashes (char * pDstPath, const char * pSrcPath, S32 dstSize)
U32 Con::tabComplete (char * inputBuffer, U32 cursorPos, U32 maxResultLength, bool forwardTab)
This is the basis for tab completion in the console.
Note
This is an internally used function. You probably don't care much about how this works.
This function does some basic parsing to try to ascertain the namespace in which we are attempting to do tab completion, then bumps control off to the appropriate tabComplete function, either in SimObject or Namespace.
Parameters
inputBuffer Pointer to buffer containing starting data, or last result.
cursorPos Location of cursor in this buffer. This is used to indicate what part of the string should be kept and what part should be advanced to the next match if any.
maxResultLength Maximum amount of result data to put into inputBuffer. This is capped by MaxCompletionBufferSize.
forwardTab Should we go forward to next match or backwards to previous match? True indicates forward.
bool Con::unlinkNamespaces (const char * parentName, const char * childName)
Referenced by printBlankLine().
void Con::unlockLog (void)
Referenced by printBlankLine().
void Con::warnf (const char * _format, ...)
Note
The console window colors warning text as LIGHT GRAY.
Parameters
_format A stdlib printf style formatted out put string
... Variables to be written
Referenced by AssetManager::acquireAsset(), TamlCustomNodes::addNode(), ResponseCurve< T >::addPoint(), TamlCustomField::getFieldValue(), TamlCustomNode::getIgnoreEmpty(), ColladaPrimitive< T >::getTriangleData(), TamlAssetDeclaredUpdateVisitor::setAssetIdFrom(), TamlAssetDeclaredUpdateVisitor::setAssetIdTo(), TamlCustomField::setFieldValue(), ResponseCurve< T >::setPoint(), and TamlAssetDeclaredUpdateVisitor::visit().
void Con::warnf (ConsoleLogEntry::Type type, const char * _format, ...)
Note
The console window colors warning text as LIGHT GRAY.
Parameters
type Allows you to associate the warning message with an internal module.
_format A stdlib printf style formatted out put string
... Variables to be written
See also
Con::warnf()
Variable Documentation
String Con::gInstantGroup
The current $instantGroup setting.
ConsoleInputEvent Con::smConsoleInput
Called from the native consoles to provide lines of console input to process.
This will schedule it for execution ASAP.
Copyright © GarageGames, LLC. All Rights Reserved.