rapidjson Namespace Reference
Main Modules Class List Namespace List Online
rapidjson Namespace Reference
Namespaces
internal
Classes
class Allocator
Concept for allocating, resizing and freeing memory block.
struct AutoUTF
Dynamically select encoding according to stream's runtime-specified UTF encoding type.
class AutoUTFInputStream
Input stream wrapper with dynamically bound encoding and automatic encoding detection.
class AutoUTFOutputStream
Output stream wrapper with dynamically bound encoding and automatic encoding detection.
struct BaseReaderHandler
Default implementation of Handler.
class CrtAllocator
C-runtime library allocator.
class EncodedInputStream
Input byte stream wrapper with a statically bound encoding.
class EncodedOutputStream
Output byte stream wrapper with statically bound encoding.
class Encoding
Concept for encoding of Unicode characters.
class FileReadStream
File byte stream for input using fread().
class FileStream
(Depreciated) Wrapper of C file stream for input or output.
class FileWriteStream
Wrapper of C file stream for input using fread().
class GenericDocument
A document for parsing JSON text as DOM.
struct GenericInsituStringStream
A read-write string stream.
class GenericReader
SAX-style JSON parser. Use Reader for UTF8 encoding and default allocator.
struct GenericStringBuffer
Represents an in-memory output stream.
struct GenericStringStream
Read-only string stream.
class GenericValue
Represents a JSON value. Use Value for UTF8 encoding and default allocator.
class Handler
Concept for receiving events from GenericReader upon parsing.
class MemoryPoolAllocator
Default memory allocator used by the parser and DOM.
class PrettyWriter
Writer with indentation and spacing.
struct STATIC_ASSERTION_FAILURE
struct STATIC_ASSERTION_FAILURE< true >
struct StaticAssertTest
class Stream
Concept for reading and writing characters.
struct Transcoder
Encoding conversion.
struct Transcoder< Encoding, Encoding >
Specialization of Transcoder with same source and target encoding.
struct UTF16
UTF-16 encoding.
struct UTF16BE
UTF-16 big endian encoding.
struct UTF16LE
UTF-16 little endian encoding.
struct UTF32
UTF-32 encoding.
struct UTF32BE
UTF-32 big endian encoding.
struct UTF32LE
UTF-32 little endian enocoding.
struct UTF8
UTF-8 encoding.
class Writer
JSON writer.
Typedefs
typedef GenericDocument< UTF8<> > Document
typedef GenericInsituStringStream< UTF8<> > InsituStringStream
typedef GenericReader< UTF8<>, UTF8<> > Reader
Reader with UTF8 encoding and default allocator.
typedef unsigned SizeType
Use 32-bit array/string indices even for 64-bit platform, instead of using size_t.
typedef GenericStringBuffer< UTF8<> > StringBuffer
typedef GenericStringStream< UTF8<> > StringStream
typedef GenericValue< UTF8<> > Value
Value with UTF8 encoding.
Enumerations
enum ParseFlag {
kParseDefaultFlags = 0,
kParseInsituFlag = 1,
kParseValidateEncodingFlag = 2
}
Combination of parseFlags.
enum Type {
kNullType = 0,
kFalseType = 1,
kTrueType = 2,
kObjectType = 3,
kArrayType = 4,
kStringType = 5,
kNumberType = 6
}
Type of JSON value.
enum UTFType {
kUTF8 = 0,
kUTF16LE = 1,
kUTF16BE = 2,
kUTF32LE = 3,
kUTF32BE = 4
}
Runtime-specified UTF encoding type of a stream.
Functions
template<>
void PutN (GenericStringBuffer< UTF8<> > &stream, char c, size_t n)
Implement specialized version of PutN() with memset() for better performance.
template<>
void PutN (FileWriteStream &stream, char c, size_t n)
Implement specialized version of PutN() with memset() for better performance.
template<typename Stream , typename Ch >
void PutN (Stream &stream, Ch c, size_t n)
Put N copies of a character to a stream.
template<typename InputStream >
void SkipWhitespace (InputStream &is)
Skip the JSON white spaces in a stream.
Typedef Documentation
typedef GenericDocument<UTF8<> > rapidjson::Document
typedef GenericInsituStringStream<UTF8<> > rapidjson::InsituStringStream
typedef GenericReader<UTF8<>, UTF8<> > rapidjson::Reader
Reader with UTF8 encoding and default allocator.
typedef unsigned rapidjson::SizeType
Use 32-bit array/string indices even for 64-bit platform, instead of using size_t.
User may override the SizeType by defining RAPIDJSON_NO_SIZETYPEDEFINE.
typedef GenericStringBuffer<UTF8<> > rapidjson::StringBuffer
typedef GenericStringStream<UTF8<> > rapidjson::StringStream
typedef GenericValue<UTF8<> > rapidjson::Value
Value with UTF8 encoding.
Enumeration Type Documentation
enum rapidjson::ParseFlag
Combination of parseFlags.
Enumerator
kParseDefaultFlags
Default parse flags. Non-destructive parsing. Text strings are decoded into allocated buffer.
kParseInsituFlag
In-situ(destructive) parsing.
kParseValidateEncodingFlag
Validate encoding of JSON strings.
enum rapidjson::Type
Type of JSON value.
Enumerator
kNullType
null
kFalseType
false
kTrueType
true
kObjectType
object
kArrayType
array
kStringType
string
kNumberType
number
enum rapidjson::UTFType
Runtime-specified UTF encoding type of a stream.
Enumerator
kUTF8
UTF-8.
kUTF16LE
UTF-16 little endian.
kUTF16BE
UTF-16 big endian.
kUTF32LE
UTF-32 little endian.
kUTF32BE
UTF-32 big endian.
Function Documentation
template<> void rapidjson::PutN (GenericStringBuffer< UTF8<> > & stream, char c, size_t n) inline
Implement specialized version of PutN() with memset() for better performance.
template<> void rapidjson::PutN (FileWriteStream & stream, char c, size_t n) inline
Implement specialized version of PutN() with memset() for better performance.
References rapidjson::FileWriteStream::PutN().
Referenced by rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteIndent().
template<typename Stream , typename Ch > void rapidjson::PutN (Stream & stream, Ch c, size_t n) inline
Put N copies of a character to a stream.
template<typename InputStream > void rapidjson::SkipWhitespace (InputStream & is)
Skip the JSON white spaces in a stream.
Parameters
stream A input stream for skipping white spaces.
Note
This function has SSE2/SSE4.2 specialization.
References rapidjson::GenericStringStream< Encoding >::src_, and rapidjson::GenericInsituStringStream< Encoding >::src_.
Referenced by rapidjson::GenericReader< SourceEncoding, TargetEncoding, Allocator >::GetErrorOffset(), and rapidjson::GenericReader< SourceEncoding, TargetEncoding, Allocator >::Parse().
Copyright © GarageGames, LLC. All Rights Reserved.