StringUnit Namespace Reference
Main Modules Class List Namespace List Online
StringUnit Namespace Reference
These functions are used for chunking up strings by delimiter.
Functions
const char * getUnit (const char *string, U32 index, const char *set, char *buffer=0, U32 bufferSize=0)
U32 getUnitCount (const char *string, const char *set)
const char * getUnits (const char *string, S32 startIndex, S32 endIndex, const char *set)
const char * removeUnit (const char *string, U32 index, const char *set)
const char * setUnit (const char *string, U32 index, const char *replace, const char *set)
Detailed Description
These functions are used for chunking up strings by delimiter.
Especially useful for handling TorqueScript space-delimited fields
Function Documentation
const char* StringUnit::getUnit (const char * string, U32 index, const char * set, char * buffer = 0, U32 bufferSize = 0)
Referenced by TamlAssetDeclaredUpdateVisitor::setAssetIdFrom(), TamlAssetDeclaredUpdateVisitor::setAssetIdTo(), ModuleDefinition::setDependencies(), TamlAssetReferencedVisitor::visit(), TamlAssetDeclaredVisitor::visit(), and TamlAssetReferencedUpdateVisitor::visit().
U32 StringUnit::getUnitCount (const char * string, const char * set)
Referenced by TamlAssetDeclaredUpdateVisitor::setAssetIdFrom(), TamlAssetDeclaredUpdateVisitor::setAssetIdTo(), ModuleDefinition::setDependencies(), TamlAssetReferencedVisitor::visit(), TamlAssetDeclaredVisitor::visit(), and TamlAssetReferencedUpdateVisitor::visit().
const char* StringUnit::getUnits (const char * string, S32 startIndex, S32 endIndex, const char * set)
const char* StringUnit::removeUnit (const char * string, U32 index, const char * set)
const char* StringUnit::setUnit (const char * string, U32 index, const char * replace, const char * set)
Copyright © GarageGames, LLC. All Rights Reserved.