ColladaUtils Namespace Reference
Main Modules Class List Namespace List Online
ColladaUtils Namespace Reference
Classes
struct ImportOptions
Functions
void applyConditioners (domCOLLADA *root)
void collapsePath (std::string &path)
void convertTransform (MatrixF &m)
void exportColladaHeader (TiXmlElement *rootNode)
void exportColladaMaterials (TiXmlElement *rootNode, const OptimizedPolyList &mesh, Vector< String > &matNames, const Torque::Path &colladaFile)
void exportColladaMesh (TiXmlElement *rootNode, const OptimizedPolyList &mesh, const String &meshName, const Vector< String > &matNames)
void exportColladaScene (TiXmlElement *rootNode, const String &meshName, const Vector< String > &matNames)
void exportColladaTriangles (TiXmlElement *meshNode, const OptimizedPolyList &mesh, const String &meshName, const Vector< String > &matNames)
void exportToCollada (const Torque::Path &colladaFile, const OptimizedPolyList &mesh, const String &meshName=String::EmptyString)
const domProfile_COMMON * findEffectCommonProfile (const domEffect *effect)
const domCommon_color_or_texture_type_complexType * findEffectDiffuse (const domEffect *effect)
const domCommon_color_or_texture_type_complexType * findEffectSpecular (const domEffect *effect)
Torque::Path findTexture (const Torque::Path &diffuseMap)
ImportOptions & getOptions ()
String getSamplerImagePath (const domEffect *effect, const domFx_sampler2D_common_complexType *sampler2D)
const domFx_sampler2D_common_complexType * getTextureSampler (const domEffect *effect, const domCommon_color_or_texture_type_complexType *texture)
String resolveImagePath (const domImage *image)
Function Documentation
void ColladaUtils::applyConditioners (domCOLLADA * root)
Referenced by ColladaUtils::ImportOptions::reset().
void ColladaUtils::collapsePath (std::string & path)
Referenced by ColladaUtils::ImportOptions::reset().
void ColladaUtils::convertTransform (MatrixF & m)
Referenced by ColladaUtils::ImportOptions::reset().
void ColladaUtils::exportColladaHeader (TiXmlElement * rootNode)
Referenced by ColladaUtils::ImportOptions::reset().
void ColladaUtils::exportColladaMaterials (TiXmlElement * rootNode, const OptimizedPolyList & mesh, Vector< String > & matNames, const Torque::Path & colladaFile)
Referenced by ColladaUtils::ImportOptions::reset().
void ColladaUtils::exportColladaMesh (TiXmlElement * rootNode, const OptimizedPolyList & mesh, const String & meshName, const Vector< String > & matNames)
Referenced by ColladaUtils::ImportOptions::reset().
void ColladaUtils::exportColladaScene (TiXmlElement * rootNode, const String & meshName, const Vector< String > & matNames)
Referenced by ColladaUtils::ImportOptions::reset().
void ColladaUtils::exportColladaTriangles (TiXmlElement * meshNode, const OptimizedPolyList & mesh, const String & meshName, const Vector< String > & matNames)
Referenced by ColladaUtils::ImportOptions::reset().
void ColladaUtils::exportToCollada (const Torque::Path & colladaFile, const OptimizedPolyList & mesh, const String & meshName = String::EmptyString)
Referenced by ColladaUtils::ImportOptions::reset().
const domProfile_COMMON* ColladaUtils::findEffectCommonProfile (const domEffect * effect)
Referenced by ColladaExtension_effect::ColladaExtension_effect(), and ColladaUtils::ImportOptions::reset().
const domCommon_color_or_texture_type_complexType* ColladaUtils::findEffectDiffuse (const domEffect * effect)
Referenced by ColladaExtension_effect::ColladaExtension_effect(), and ColladaUtils::ImportOptions::reset().
const domCommon_color_or_texture_type_complexType* ColladaUtils::findEffectSpecular (const domEffect * effect)
Referenced by ColladaUtils::ImportOptions::reset().
Torque::Path ColladaUtils::findTexture (const Torque::Path & diffuseMap)
Referenced by ColladaUtils::ImportOptions::reset().
ImportOptions& ColladaUtils::getOptions ()
Referenced by ColladaUtils::ImportOptions::reset().
String ColladaUtils::getSamplerImagePath (const domEffect * effect, const domFx_sampler2D_common_complexType * sampler2D)
Referenced by ColladaUtils::ImportOptions::reset().
const domFx_sampler2D_common_complexType* ColladaUtils::getTextureSampler (const domEffect * effect, const domCommon_color_or_texture_type_complexType * texture)
Referenced by ColladaExtension_effect::ColladaExtension_effect(), and ColladaUtils::ImportOptions::reset().
String ColladaUtils::resolveImagePath (const domImage * image)
Referenced by ColladaUtils::ImportOptions::reset().
Copyright © GarageGames, LLC. All Rights Reserved.