rapidjson::UTF8< CharType > Struct Template Reference
Main Modules Class List Namespace List Online
rapidjson::UTF8< CharType > Struct Template Reference
UTF-8 encoding.
#include <persistence/rapidjson/encodings.h>
Public Types
typedef CharType Ch
Static Public Member Functions
template<typename InputStream >
static bool Decode (InputStream &is, unsigned *codepoint)
template<typename OutputStream >
static void Encode (OutputStream &os, unsigned codepoint)
static unsigned char GetRange (unsigned char c)
template<typename OutputByteStream >
static void Put (OutputByteStream &os, Ch c)
template<typename OutputByteStream >
static void PutBOM (OutputByteStream &os)
template<typename InputByteStream >
static Ch Take (InputByteStream &is)
template<typename InputByteStream >
static CharType TakeBOM (InputByteStream &is)
template<typename InputStream , typename OutputStream >
static bool Validate (InputStream &is, OutputStream &os)
Detailed Description
template<typename CharType = char>
struct rapidjson::UTF8< CharType >
UTF-8 encoding.
http://en.wikipedia.org/wiki/UTF-8 http://tools.ietf.org/html/rfc3629
Template Parameters
CharType Code unit for storing 8-bit UTF-8 data. Default is char.
Member Typedef Documentation
template<typename CharType = char> typedef CharType rapidjson::UTF8< CharType >::Ch
Member Function Documentation
template<typename CharType = char> template<typename InputStream > static bool rapidjson::UTF8< CharType >::Decode (InputStream & is, unsigned * codepoint) inline static
References rapidjson::UTF8< CharType >::GetRange().
Referenced by rapidjson::AutoUTF< CharType >::Decode().
template<typename CharType = char> template<typename OutputStream > static void rapidjson::UTF8< CharType >::Encode (OutputStream & os, unsigned codepoint) inline static
Referenced by rapidjson::AutoUTF< CharType >::Encode().
template<typename CharType = char> static unsigned char rapidjson::UTF8< CharType >::GetRange (unsigned char c) inline static
Referenced by rapidjson::UTF8< CharType >::Decode(), and rapidjson::UTF8< CharType >::Validate().
template<typename CharType = char> template<typename OutputByteStream > static void rapidjson::UTF8< CharType >::Put (OutputByteStream & os, Ch c) inline static
template<typename CharType = char> template<typename OutputByteStream > static void rapidjson::UTF8< CharType >::PutBOM (OutputByteStream & os) inline static
template<typename CharType = char> template<typename InputByteStream > static Ch rapidjson::UTF8< CharType >::Take (InputByteStream & is) inline static
Referenced by rapidjson::UTF8< CharType >::TakeBOM(), rapidjson::UTF16LE< CharType >::TakeBOM(), rapidjson::UTF16BE< CharType >::TakeBOM(), rapidjson::UTF32LE< CharType >::TakeBOM(), and rapidjson::UTF32BE< CharType >::TakeBOM().
template<typename CharType = char> template<typename InputByteStream > static CharType rapidjson::UTF8< CharType >::TakeBOM (InputByteStream & is) inline static
References rapidjson::UTF8< CharType >::Take().
template<typename CharType = char> template<typename InputStream , typename OutputStream > static bool rapidjson::UTF8< CharType >::Validate (InputStream & is, OutputStream & os) inline static
References rapidjson::UTF8< CharType >::GetRange().
Referenced by rapidjson::AutoUTF< CharType >::Validate().
Copyright © GarageGames, LLC. All Rights Reserved.