PolyhedronFixedVectorData< NUM_PLANES, NUM_POINTS, NUM_EDGES > Struct Template Reference
Main Modules Class List Namespace List Online
PolyhedronFixedVectorData< NUM_PLANES, NUM_POINTS, NUM_EDGES > Struct Template Reference
Polyhedron data stored in fixed size arrays.
#include <math/mPolyhedron.h>
Public Types
typedef FixedSizeVector< Edge, NUM_EDGES > EdgeListType
typedef FixedSizeVector< PlaneF, NUM_PLANES > PlaneListType
typedef FixedSizeVector< Point3F, NUM_POINTS > PointListType
Public Types inherited from PolyhedronData
typedef Edge EdgeType
typedef PlaneF PlaneType
typedef Point3F PointType
Public Member Functions
operator AnyPolyhedron () const
Conversion to the common polyhedron type.
Accessors
U32 getNumPlanes () const
Return the number of planes that make up this polyhedron.
PlaneF * getPlanes () const
Return the planes that make up the polyhedron.
U32 getNumPoints () const
Return the number of points that this polyhedron has.
Point3F * getPoints () const
U32 getNumEdges () const
Return the number of edges that this polyhedron has.
Edge * getEdges () const
Protected Attributes
EdgeListType edgeList
List of edges.
PlaneListType planeList
List of planes. Note that by default, the normals facing inwards.
PointListType pointList
List of vertices.
Additional Inherited Members
Static Public Member Functions inherited from PolyhedronData
template<typename Polyhedron >
static void buildBoxData (Polyhedron &poly, const MatrixF &mat, const Box3F &box, bool invertNormals=false)
Detailed Description
template<S32 NUM_PLANES, S32 NUM_POINTS, S32 NUM_EDGES>
struct PolyhedronFixedVectorData< NUM_PLANES, NUM_POINTS, NUM_EDGES >
Polyhedron data stored in fixed size arrays.
Member Typedef Documentation
template<S32 NUM_PLANES, S32 NUM_POINTS, S32 NUM_EDGES> typedef FixedSizeVector< Edge, NUM_EDGES > PolyhedronFixedVectorData< NUM_PLANES, NUM_POINTS, NUM_EDGES >::EdgeListType
template<S32 NUM_PLANES, S32 NUM_POINTS, S32 NUM_EDGES> typedef FixedSizeVector< PlaneF, NUM_PLANES > PolyhedronFixedVectorData< NUM_PLANES, NUM_POINTS, NUM_EDGES >::PlaneListType
template<S32 NUM_PLANES, S32 NUM_POINTS, S32 NUM_EDGES> typedef FixedSizeVector< Point3F, NUM_POINTS > PolyhedronFixedVectorData< NUM_PLANES, NUM_POINTS, NUM_EDGES >::PointListType
Member Function Documentation
template<S32 NUM_PLANES, S32 NUM_POINTS, S32 NUM_EDGES> Edge* PolyhedronFixedVectorData< NUM_PLANES, NUM_POINTS, NUM_EDGES >::getEdges () const inline
References FixedSizeVector< T, SIZE >::address().
template<S32 NUM_PLANES, S32 NUM_POINTS, S32 NUM_EDGES> U32 PolyhedronFixedVectorData< NUM_PLANES, NUM_POINTS, NUM_EDGES >::getNumEdges () const inline
Return the number of edges that this polyhedron has.
References FixedSizeVector< T, SIZE >::size().
template<S32 NUM_PLANES, S32 NUM_POINTS, S32 NUM_EDGES> U32 PolyhedronFixedVectorData< NUM_PLANES, NUM_POINTS, NUM_EDGES >::getNumPlanes () const inline
Return the number of planes that make up this polyhedron.
References FixedSizeVector< T, SIZE >::size().
template<S32 NUM_PLANES, S32 NUM_POINTS, S32 NUM_EDGES> U32 PolyhedronFixedVectorData< NUM_PLANES, NUM_POINTS, NUM_EDGES >::getNumPoints () const inline
Return the number of points that this polyhedron has.
References FixedSizeVector< T, SIZE >::size().
template<S32 NUM_PLANES, S32 NUM_POINTS, S32 NUM_EDGES> PlaneF* PolyhedronFixedVectorData< NUM_PLANES, NUM_POINTS, NUM_EDGES >::getPlanes () const inline
Return the planes that make up the polyhedron.
Note
The normals of these planes are facing inwards.
References FixedSizeVector< T, SIZE >::address().
template<S32 NUM_PLANES, S32 NUM_POINTS, S32 NUM_EDGES> Point3F* PolyhedronFixedVectorData< NUM_PLANES, NUM_POINTS, NUM_EDGES >::getPoints () const inline
References FixedSizeVector< T, SIZE >::address().
template<S32 NUM_PLANES, S32 NUM_POINTS, S32 NUM_EDGES> PolyhedronFixedVectorData< NUM_PLANES, NUM_POINTS, NUM_EDGES >::operator AnyPolyhedron () const inline
Conversion to the common polyhedron type.
Member Data Documentation
template<S32 NUM_PLANES, S32 NUM_POINTS, S32 NUM_EDGES> EdgeListType PolyhedronFixedVectorData< NUM_PLANES, NUM_POINTS, NUM_EDGES >::edgeList protected
List of edges.
template<S32 NUM_PLANES, S32 NUM_POINTS, S32 NUM_EDGES> PlaneListType PolyhedronFixedVectorData< NUM_PLANES, NUM_POINTS, NUM_EDGES >::planeList protected
List of planes. Note that by default, the normals facing inwards.
template<S32 NUM_PLANES, S32 NUM_POINTS, S32 NUM_EDGES> PointListType PolyhedronFixedVectorData< NUM_PLANES, NUM_POINTS, NUM_EDGES >::pointList protected
List of vertices.
Copyright © GarageGames, LLC. All Rights Reserved.