ContactInfo Struct Reference
Main Modules Class List Namespace List Online
ContactInfo Struct Reference
#include <T3D/components/collision/collisionInterfaces.h>
Public Member Functions
ContactInfo ()
void clear ()
Public Attributes
bool contacted
BaseMatInstance * contactMaterial
VectorF contactNormal
SceneObject * contactObject
Point3F contactPoint
F32 contactTime
S32 contactTimer
VectorF idealContactNormal
bool move
Constructor & Destructor Documentation
ContactInfo::ContactInfo () inline
References clear().
Member Function Documentation
void ContactInfo::clear (void) inline
References Point3F::set().
Referenced by ContactInfo().
Member Data Documentation
bool ContactInfo::contacted
BaseMatInstance* ContactInfo::contactMaterial
VectorF ContactInfo::contactNormal
Referenced by CollisionComponent::getContactNormal().
SceneObject* ContactInfo::contactObject
Referenced by CollisionComponent::hasContact().
Point3F ContactInfo::contactPoint
F32 ContactInfo::contactTime
S32 ContactInfo::contactTimer
VectorF ContactInfo::idealContactNormal
bool ContactInfo::move
Copyright © GarageGames, LLC. All Rights Reserved.