SilhouetteExtractorOrtho< Polyhedron > Struct Template Reference
Main Modules Class List Namespace List Online
SilhouetteExtractorOrtho< Polyhedron > Struct Template Reference
Silhouette edge extraction for orthographic projections.
#include <math/mSilhouetteExtractor.h>
Public Member Functions
SilhouetteExtractorOrtho (const Polyhedron &polyhedron)
U32 extractSilhouette (const Point3F &viewDirOS, U32 *outIndices, U32 maxOutIndices) const
Generate a silhouette polygon for the polyhedron based on the given view direction.
Protected Types
typedef SilhouetteExtractorImpl< SilhouetteExtractorBaseOrtho< Polyhedron > > ExtractorType
Protected Attributes
ExtractorType mExtractor
The actual extractor implementation.
Detailed Description
template<typename Polyhedron>
struct SilhouetteExtractorOrtho< Polyhedron >
Silhouette edge extraction for orthographic projections.
Member Typedef Documentation
template<typename Polyhedron > typedef SilhouetteExtractorImpl< SilhouetteExtractorBaseOrtho< Polyhedron > > SilhouetteExtractorOrtho< Polyhedron >::ExtractorType protected
Constructor & Destructor Documentation
template<typename Polyhedron > SilhouetteExtractorOrtho< Polyhedron >::SilhouetteExtractorOrtho (const Polyhedron & polyhedron) inline
Member Function Documentation
template<typename Polyhedron > U32 SilhouetteExtractorOrtho< Polyhedron >::extractSilhouette (const Point3F & viewDirOS, U32 * outIndices, U32 maxOutIndices) const inline
Generate a silhouette polygon for the polyhedron based on the given view direction.
Parameters
viewDirOS Object-space normalized view vector.
outIndices Array where the resulting vertex indices will be stored. Must have enough room. If you don't know the exact size that you need, just allocate one index for any point in the mesh.
maxOutIndices The number of indices that can be stored in outIndices. If insufficient, the return value will be 0.
Returns
Number of indices written to outIndices or 0 if the silhouette extraction failed.
Note
Be aware that silhouette polygons are in most cases non-planar!
The direction of the ordering of the resulting indices is undefined meaning that different silhouettes extracted from the same polyhedron may have different CCW/CW ordering. The only guarantee is that the resulting indices are consecutive.
References SilhouetteExtractorBaseOrtho< Polyhedron >::begin(), SilhouetteExtractorBaseOrtho< Polyhedron >::end(), and SilhouetteExtractorImpl< Base >::extractSilhouette().
Member Data Documentation
template<typename Polyhedron > ExtractorType SilhouetteExtractorOrtho< Polyhedron >::mExtractor protected
The actual extractor implementation.
Copyright © GarageGames, LLC. All Rights Reserved.