PolyhedronData Struct Reference
Main Modules Class List Namespace List Online
PolyhedronData Struct Reference
Base class for helping to abstract over how a polyhedron stores and updates its data.
#include <math/mPolyhedron.h>
Classes
struct Edge
Winged edge.
Public Types
typedef Edge EdgeType
typedef PlaneF PlaneType
typedef Point3F PointType
Static Public Member Functions
template<typename Polyhedron >
static void buildBoxData (Polyhedron &poly, const MatrixF &mat, const Box3F &box, bool invertNormals=false)
Detailed Description
Base class for helping to abstract over how a polyhedron stores and updates its data.
The PolyhedronData class hierarchy is designed to give users of PolyhedronImpl maximum freedom in modifying those behaviors. This leads to some duplicating in the various PolyhedronData classes but it ultimately provides greater control.
All accesses to the data go through accessors on the base classes. This gives the base class the freedom to implement lazy updates, for example.
A given base implementation is also free to store additional data or derive extended classes from the base classes expected for points (Point3F), edges (Edge), and planes (PlaneF). If a class does that, it loses the ability to trivially convert to AnyPolyhedron, though.
Member Typedef Documentation
typedef Edge PolyhedronData::EdgeType
typedef PlaneF PolyhedronData::PlaneType
typedef Point3F PolyhedronData::PointType
Member Function Documentation
template<typename Polyhedron > void PolyhedronData::buildBoxData (Polyhedron & poly, const MatrixF & mat, const Box3F & box, bool invertNormals = false) static
References MatrixF::getForwardVector(), MatrixF::getRightVector(), MatrixF::getUpVector(), Box3F::len_x(), Box3F::len_y(), Box3F::len_z(), Box3F::minExtents, and MatrixF::mulP().
Referenced by PolyhedronVectorData::buildBox().
Copyright © GarageGames, LLC. All Rights Reserved.