TamlVisitor::PropertyState Struct Reference
Main Modules Class List Namespace List Online
TamlVisitor::PropertyState Struct Reference
Visitor property state.
#include <persistence/taml/tamlVisitor.h>
Public Member Functions
PropertyState ()
StringTableEntry getObjectName (void) const
StringTableEntry getPropertyName (void) const
const char * getPropertyValue (void) const
bool getPropertyValueDirty (void) const
bool isRootObject (void) const
void resetPropertyValueDirty (void)
void setObjectName (const char *pObjectName, const bool rootObject)
void setProperty (const char *pPropertyName, const char *pPropertyValue)
void updatePropertyValue (const char *pPropertyValue)
Detailed Description
Visitor property state.
Constructor & Destructor Documentation
TamlVisitor::PropertyState::PropertyState () inline
Member Function Documentation
StringTableEntry TamlVisitor::PropertyState::getObjectName (void) const inline
Referenced by TamlAssetDeclaredVisitor::visit().
StringTableEntry TamlVisitor::PropertyState::getPropertyName (void) const inline
Referenced by TamlAssetDeclaredVisitor::visit(), and TamlAssetDeclaredUpdateVisitor::visit().
const char* TamlVisitor::PropertyState::getPropertyValue (void) const inline
Referenced by TamlModuleIdUpdateVisitor::visit(), TamlAssetReferencedVisitor::visit(), TamlAssetDeclaredVisitor::visit(), TamlAssetReferencedUpdateVisitor::visit(), and TamlAssetDeclaredUpdateVisitor::visit().
bool TamlVisitor::PropertyState::getPropertyValueDirty (void) const inline
bool TamlVisitor::PropertyState::isRootObject (void) const inline
Referenced by TamlAssetDeclaredVisitor::visit().
void TamlVisitor::PropertyState::resetPropertyValueDirty (void) inline
void TamlVisitor::PropertyState::setObjectName (const char * pObjectName, const bool rootObject) inline
void TamlVisitor::PropertyState::setProperty (const char * pPropertyName, const char * pPropertyValue) inline
void TamlVisitor::PropertyState::updatePropertyValue (const char * pPropertyValue) inline
Referenced by TamlModuleIdUpdateVisitor::visit(), TamlAssetReferencedUpdateVisitor::visit(), and TamlAssetDeclaredUpdateVisitor::visit().
Copyright © GarageGames, LLC. All Rights Reserved.