RectF Class Reference
Main Modules Class List Namespace List Online
RectF Class Reference
#include <math/mRect.h>
Public Member Functions
RectF ()
RectF (const Point2F &in_rMin, const Point2F &in_rExtent)
RectF (const F32 in_left, const F32 in_top, const F32 in_width, const F32 in_height)
bool contains (const Point2F &p) const
bool contains (const RectF &R) const
F32 getDistanceToPoint (const Point2F &refPt) const
Return distance of the reference point to the rectangle.
F32 getSqDistanceToPoint (const Point2F &refPt) const
Return the squared distance of the reference point to the rectangle.
void inset (F32 x, F32 y)
bool intersect (const RectF &clipRect)
bool intersectTriangle (const Point2F &a, const Point2F &b, const Point2F &c)
bool isValidRect () const
F32 len_x () const
F32 len_y () const
bool overlaps (const RectF &) const
bool pointInRect (const Point2F &pt) const
void set (const Point2F &in_rMin, const Point2F &in_rExtent)
void set (const F32 in_left, const F32 in_top, const F32 in_width, const F32 in_height)
void unionRects (const RectF &rect)
Public Attributes
Point2F extent
Point2F point
Constructor & Destructor Documentation
RectF::RectF () inline
References RectI::inset(), RectI::intersect(), RectI::overlaps(), and RectI::pointInRect().
RectF::RectF (const Point2F & in_rMin, const Point2F & in_rExtent) inline
RectF::RectF (const F32 in_left, const F32 in_top, const F32 in_width, const F32 in_height) inline
Member Function Documentation
bool RectF::contains (const Point2F & p) const inline
References RectI::contains(), RectI::len_x(), RectI::len_y(), RectI::point, RectI::unionRects(), Point2F::x, and Point2F::y.
Referenced by intersectTriangle().
bool RectF::contains (const RectF & R) const inline
References extent, point, Point2F::x, and Point2F::y.
F32 RectF::getDistanceToPoint (const Point2F & refPt) const inline
Return distance of the reference point to the rectangle.
References getSqDistanceToPoint().
F32 RectF::getSqDistanceToPoint (const Point2F & refPt) const inline
Return the squared distance of the reference point to the rectangle.
References extent, and point.
Referenced by getDistanceToPoint().
void RectF::inset (F32 x, F32 y) inline
References RectI::extent, RectI::point, Point2I::x, and Point2I::y.
bool RectF::intersect (const RectF & clipRect) inline
References extent, isValidRect(), point, Point2F::x, and Point2F::y.
Referenced by overlaps().
bool RectF::intersectTriangle (const Point2F & a, const Point2F & b, const Point2F & c) inline
References contains(), extent, point, Point2F::x, and Point2F::y.
bool RectF::isValidRect () const inline
References Point2F::x, and Point2F::y.
Referenced by intersect().
F32 RectF::len_x () const inline
References extent, and Point2F::x.
F32 RectF::len_y () const inline
References extent, and Point2F::y.
bool RectF::overlaps (const RectF & clipRect) const inline
References intersect(), Point2F::x, and Point2F::y.
bool RectF::pointInRect (const Point2F & pt) const inline
References extent, point, Point2F::x, and Point2F::y.
void RectF::set (const Point2F & in_rMin, const Point2F & in_rExtent) inline
References extent, and point.
void RectF::set (const F32 in_left, const F32 in_top, const F32 in_width, const F32 in_height) inline
References extent, point, and Point2F::set().
void RectF::unionRects (const RectF & rect) inline
References extent, point, Point2F::x, and Point2F::y.
Member Data Documentation
Point2F RectF::extent
Referenced by ForestCell::_getSubCell(), ForestCell::_makeChildRect(), contains(), TamlCustomField::getFieldValue(), getSqDistanceToPoint(), intersect(), intersectTriangle(), len_x(), len_y(), pointInRect(), set(), TamlCustomField::setFieldValue(), and unionRects().
Point2F RectF::point
Referenced by ForestCell::_getSubCell(), ForestCell::_makeChildRect(), contains(), TamlCustomField::getFieldValue(), getSqDistanceToPoint(), intersect(), intersectTriangle(), pointInRect(), set(), TamlCustomField::setFieldValue(), and unionRects().
Copyright © GarageGames, LLC. All Rights Reserved.