GFXFence Class Reference
Main Modules Class List Namespace List Online
GFXFence Class Reference abstract
#include <gfx/gfxFence.h>
Public Types
enum FenceStatus {
Unset,
Pending,
Processed,
Unsupported
}
The states returned by getStatus()
Public Member Functions
GFXFence (GFXDevice *device)
virtual ~GFXFence ()
virtual void block ()=0
This method will not return until the fence has been processed by the GPU.
virtual FenceStatus getStatus () const =0
This is a non-blocking call to get the status of the fence.
virtual void issue ()=0
This method inserts the fence into the command buffer.
Public Member Functions inherited from GFXResource
GFXResource ()
virtual ~GFXResource ()
void clearFlag ()
virtual const String describeSelf () const =0
The resource should put a description of itself (number of vertices, size/width of texture, etc.) in buffer.
GFXResource * getNextResource () const
GFXDevice * getOwningDevice () const
GFXResource * getPrevResource () const
bool isFlagged ()
void registerResourceWithDevice (GFXDevice *device)
Registers this resource with the given device.
virtual void resurrect ()=0
When called the resource should restore all device sensitive information destroyed by zombify()
void setFlag ()
virtual void zombify ()=0
When called the resource should destroy all device sensitive information (e.g. D3D resources in D3DPOOL_DEFAULT.
Protected Attributes
GFXDevice * mDevice
Member Enumeration Documentation
enum GFXFence::FenceStatus
The states returned by getStatus()
Enumerator
Unset
The fence has not been set.
Pending
The fence has been set and has not been hit.
Processed
The fence has been processed.
Unsupported
A non-blocking query of fence status is not supported by the implementation.
Constructor & Destructor Documentation
GFXFence::GFXFence (GFXDevice * device) inline
virtual GFXFence::~GFXFence () inline virtual
References block(), getStatus(), and issue().
Member Function Documentation
virtual void GFXFence::block () pure virtual
This method will not return until the fence has been processed by the GPU.
Implemented in GFXGeneralFence, GFXD3D11QueryFence, and GFXGLAppleFence.
Referenced by GFXGeneralFence::getStatus(), and ~GFXFence().
virtual FenceStatus GFXFence::getStatus () const pure virtual
This is a non-blocking call to get the status of the fence.
See also
GFXFence::FenceStatus
Implemented in GFXGeneralFence, GFXD3D11QueryFence, and GFXGLAppleFence.
Referenced by ~GFXFence().
virtual void GFXFence::issue () pure virtual
This method inserts the fence into the command buffer.
Implemented in GFXGeneralFence, GFXD3D11QueryFence, and GFXGLAppleFence.
Referenced by GFXGeneralFence::GFXGeneralFence(), and ~GFXFence().
Member Data Documentation
GFXDevice* GFXFence::mDevice protected
Copyright © GarageGames, LLC. All Rights Reserved.