Selection< T > Class Template Reference
Main Modules Class List Namespace List Online
Selection< T > Class Template Reference
#include <gui/worldEditor/tSelection.h>
Public Member Functions
Selection ()
virtual ~Selection ()
bool add (const GridInfo &info)
add unique grid info into the selection - test uniqueness by grid position
F32 getAvgHeight ()
bool getInfo (Point2I pos, GridInfo &info)
F32 getMaxHeight ()
F32 getMinHeight ()
StringTableEntry getName ()
MatrixF getOrientation ()
Point3F getOrigin ()
Point3F getScale ()
void offset (const Point3F &delta)
bool remove (const GridInfo &info)
void reset ()
void rotate (const EulerF &delta)
void scale (const Point3F &delta)
bool setInfo (GridInfo &info)
void setName (StringTableEntry name)
Public Member Functions inherited from Vector< T >
Vector (const U32 initialSize=0)
Vector (const U32 initialSize, const char *fileName, const U32 lineNum)
Vector (const char *fileName, const U32 lineNum)
Vector (const Vector &)
~Vector ()
Vector< T > & operator= (const Vector< T > &p)
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
S32 size () const
bool empty () const
bool contains (const T &) const
void insert (iterator, const T &)
void erase (iterator)
T & front ()
const T & front () const
T & back ()
const T & back () const
void push_front (const T &)
void push_back (const T &)
U32 push_front_unique (const T &)
U32 push_back_unique (const T &)
S32 find_next (const T &, U32 start=0) const
void pop_front ()
void pop_back ()
T & operator[] (U32)
const T & operator[] (U32) const
T & operator[] (S32 i)
const T & operator[] (S32 i) const
void reserve (U32)
U32 capacity () const
U32 memSize () const
T * address () const
U32 setSize (U32)
void increment ()
void decrement ()
void increment (U32)
void decrement (U32)
void insert (U32)
void insert (U32, const T &)
void erase (U32)
void erase_fast (U32)
void erase (U32 index, U32 count)
void erase_fast (iterator)
void clear ()
void compact ()
void sort (compare_func f)
void fill (const T &value)
bool remove (const T &)
Finds the first matching element and erases it.
T & first ()
T & last ()
const T & first () const
const T & last () const
void set (void *addr, U32 sz)
void merge (const Vector &p)
Appends the content of the vector to this one.
void merge (const T *addr, U32 count)
Appends the content of the array to the vector.
void reverse ()
Public Member Functions inherited from Vector< GridInfo >
Vector (const U32 initialSize=0)
Vector (const U32 initialSize, const char *fileName, const U32 lineNum)
Vector (const char *fileName, const U32 lineNum)
Vector (const Vector &)
~Vector ()
void insert (U32)
void insert (U32, const GridInfo &)
void erase (U32)
void erase (U32 index, U32 count)
U32 memSize () const
GridInfo * address () const
U32 setSize (U32)
void increment ()
void increment (U32)
void decrement ()
void decrement (U32)
void erase_fast (U32)
void erase_fast (iterator)
void clear ()
void compact ()
void sort (compare_func f)
void fill (const GridInfo &value)
bool remove (const GridInfo &)
Finds the first matching element and erases it.
GridInfo & first ()
const GridInfo & first () const
GridInfo & last ()
const GridInfo & last () const
void set (void *addr, U32 sz)
void merge (const Vector &p)
Appends the content of the vector to this one.
void merge (const GridInfo *addr, U32 count)
Appends the content of the array to the vector.
void reverse ()
Vector< GridInfo > & operator= (const Vector< GridInfo > &p)
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
S32 size () const
bool empty () const
bool contains (const GridInfo &) const
void insert (iterator, const GridInfo &)
void erase (iterator)
GridInfo & front ()
const GridInfo & front () const
GridInfo & back ()
const GridInfo & back () const
void push_front (const GridInfo &)
void push_back (const GridInfo &)
U32 push_front_unique (const GridInfo &)
U32 push_back_unique (const GridInfo &)
S32 find_next (const GridInfo &, U32 start=0) const
void pop_front ()
void pop_back ()
GridInfo & operator[] (U32)
const GridInfo & operator[] (U32) const
GridInfo & operator[] (S32 i)
const GridInfo & operator[] (S32 i) const
void reserve (U32)
U32 capacity () const
Protected Member Functions
virtual void offsetObject (T &object, const Point3F &delta)
virtual void rotateObject (T &object, const EulerF &delta, const Point3F &origin)
virtual void scaleObject (T &object, const Point3F &delta)
Protected Member Functions inherited from Vector< T >
void construct (U32 start, U32 end)
Constructs elements from start to end-1
void construct (U32 start, U32 end, const T *array)
void destroy (U32 start, U32 end)
Destructs elements from start to end-1
bool resize (U32)
Protected Member Functions inherited from Vector< GridInfo >
void construct (U32 start, U32 end)
Constructs elements from start to end-1
void construct (U32 start, U32 end, const GridInfo *array)
void destroy (U32 start, U32 end)
Destructs elements from start to end-1
bool resize (U32)
Additional Inherited Members
Public Types inherited from Vector< T >
typedef T value_type
typedef T & reference
typedef const T & const_reference
typedef T * iterator
typedef const T * const_iterator
typedef S32 difference_type
typedef U32 size_type
typedef difference_type(QSORT_CALLBACK * compare_func) (const T *a, const T *b)
Public Types inherited from Vector< GridInfo >
typedef GridInfo value_type
typedef GridInfo & reference
typedef const GridInfo & const_reference
typedef GridInfo * iterator
typedef const GridInfo * const_iterator
typedef S32 difference_type
typedef U32 size_type
typedef difference_type(QSORT_CALLBACK * compare_func) (const GridInfo *a, const GridInfo *b)
Protected Attributes inherited from Vector< T >
T * mArray
Pointer to the Vector elements.
U32 mArraySize
Number of elements allocated for the Vector.
U32 mElementCount
Number of elements currently in the Vector.
Protected Attributes inherited from Vector< GridInfo >
GridInfo * mArray
Pointer to the Vector elements.
U32 mArraySize
Number of elements allocated for the Vector.
U32 mElementCount
Number of elements currently in the Vector.
Constructor & Destructor Documentation
template<class T> Selection< T >::Selection ()
template<class T> virtual Selection< T >::~Selection () virtual
Member Function Documentation
template<class T> bool Selection< T >::add (const GridInfo & info)
add unique grid info into the selection - test uniqueness by grid position
template<class T> F32 Selection< T >::getAvgHeight ()
template<class T> bool Selection< T >::getInfo (Point2I pos, GridInfo & info)
template<class T> F32 Selection< T >::getMaxHeight ()
template<class T> F32 Selection< T >::getMinHeight ()
template<class T> StringTableEntry Selection< T >::getName () inline
template<class T> MatrixF Selection< T >::getOrientation () inline
template<class T> Point3F Selection< T >::getOrigin () inline
Referenced by Selection< T >::rotate().
template<class T> Point3F Selection< T >::getScale () inline
template<class T > void Selection< T >::offset (const Point3F & delta) inline
References Vector< T >::begin(), Vector< T >::end(), and Selection< T >::offsetObject().
Referenced by Selection< ForestItem >::getScale().
template<class T> virtual void Selection< T >::offsetObject (T & object, const Point3F & delta) inline protected virtual
Reimplemented in ForestItemSelection.
Referenced by Selection< T >::offset().
template<class T> bool Selection< T >::remove (const GridInfo & info)
template<class T> void Selection< T >::reset ()
Referenced by ClearAction::useMouseBrush().
template<class T > void Selection< T >::rotate (const EulerF & delta) inline
References Vector< T >::begin(), Vector< T >::end(), Selection< T >::getOrigin(), and Selection< T >::rotateObject().
Referenced by Selection< ForestItem >::getScale().
template<class T> virtual void Selection< T >::rotateObject (T & object, const EulerF & delta, const Point3F & origin) inline protected virtual
Reimplemented in ForestItemSelection.
Referenced by Selection< T >::rotate().
template<class T > void Selection< T >::scale (const Point3F & delta) inline
References Vector< T >::mArray, Selection< T >::scaleObject(), and Vector< T >::size().
Referenced by Selection< ForestItem >::getScale().
template<class T> virtual void Selection< T >::scaleObject (T & object, const Point3F & delta) inline protected virtual
Reimplemented in ForestItemSelection.
Referenced by Selection< T >::scale().
template<class T> bool Selection< T >::setInfo (GridInfo & info)
template<class T> void Selection< T >::setName (StringTableEntry name)
Copyright © GarageGames, LLC. All Rights Reserved.