GFXPrimitiveBuffer Class Reference
Main Modules Class List Namespace List Online
GFXPrimitiveBuffer Class Reference abstract
#include <gfx/gfxPrimitiveBuffer.h>
Public Member Functions
GFXPrimitiveBuffer (GFXDevice *device, U32 indexCount, U32 primitiveCount, GFXBufferType bufferType)
virtual ~GFXPrimitiveBuffer ()
virtual const String describeSelf () const
The resource should put a description of itself (number of vertices, size/width of texture, etc.) in buffer.
virtual void lock (U32 indexStart, U32 indexEnd, void **indexPtr)=0
locks this primitive buffer for writing into
virtual void prepare ()=0
prepares this primitive buffer for use on the device it was allocated on
virtual void unlock ()=0
unlocks this primitive buffer.
Public Member Functions inherited from StrongRefBase
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Public Member Functions inherited from GFXResource
GFXResource ()
virtual ~GFXResource ()
void clearFlag ()
GFXResource * getNextResource () const
GFXDevice * getOwningDevice () const
GFXResource * getPrevResource () const
bool isFlagged ()
void registerResourceWithDevice (GFXDevice *device)
Registers this resource with the given device.
virtual void resurrect ()=0
When called the resource should restore all device sensitive information destroyed by zombify()
void setFlag ()
virtual void zombify ()=0
When called the resource should destroy all device sensitive information (e.g. D3D resources in D3DPOOL_DEFAULT.
Static Public Member Functions
static void dumpActivePBs ()
Public Attributes
GFXBufferType mBufferType
String mDebugCreationPath
GFXPrimitiveBuffer * mDebugNext
GFXPrimitiveBuffer * mDebugPrev
GFXDevice * mDevice
U32 mIndexCount
GFXPrimitive * mPrimitiveArray
U32 mPrimitiveCount
U32 mVolatileStart
Static Public Attributes
static U32 smActivePBCount
static GFXPrimitiveBuffer * smHead
Additional Inherited Members
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Protected Attributes inherited from StrongRefBase
U32 mRefCount
reference counter for StrongRefPtr objects
Constructor & Destructor Documentation
GFXPrimitiveBuffer::GFXPrimitiveBuffer (GFXDevice * device, U32 indexCount, U32 primitiveCount, GFXBufferType bufferType) inline
References dMemset(), mDebugPrev, and smHead.
virtual GFXPrimitiveBuffer::~GFXPrimitiveBuffer () inline virtual
References describeSelf(), lock(), mDebugNext, mDebugPrev, mPrimitiveArray, prepare(), and unlock().
Member Function Documentation
virtual const String GFXPrimitiveBuffer::describeSelf () const virtual
The resource should put a description of itself (number of vertices, size/width of texture, etc.) in buffer.
Implements GFXResource.
Referenced by ~GFXPrimitiveBuffer().
static void GFXPrimitiveBuffer::dumpActivePBs () static
virtual void GFXPrimitiveBuffer::lock (U32 indexStart, U32 indexEnd, void ** indexPtr) pure virtual
locks this primitive buffer for writing into
Implemented in GFXD3D11PrimitiveBuffer, and GFXGLPrimitiveBuffer.
Referenced by ~GFXPrimitiveBuffer().
virtual void GFXPrimitiveBuffer::prepare () pure virtual
prepares this primitive buffer for use on the device it was allocated on
Implemented in GFXD3D11PrimitiveBuffer, and GFXGLPrimitiveBuffer.
Referenced by ~GFXPrimitiveBuffer().
virtual void GFXPrimitiveBuffer::unlock () pure virtual
unlocks this primitive buffer.
Implemented in GFXD3D11PrimitiveBuffer, and GFXGLPrimitiveBuffer.
Referenced by ~GFXPrimitiveBuffer().
Member Data Documentation
GFXBufferType GFXPrimitiveBuffer::mBufferType
String GFXPrimitiveBuffer::mDebugCreationPath
GFXPrimitiveBuffer* GFXPrimitiveBuffer::mDebugNext
Referenced by ~GFXPrimitiveBuffer().
GFXPrimitiveBuffer* GFXPrimitiveBuffer::mDebugPrev
Referenced by GFXPrimitiveBuffer(), and ~GFXPrimitiveBuffer().
GFXDevice* GFXPrimitiveBuffer::mDevice
U32 GFXPrimitiveBuffer::mIndexCount
Referenced by GFXPrimitiveBufferHandle::lock().
GFXPrimitive* GFXPrimitiveBuffer::mPrimitiveArray
Referenced by ~GFXPrimitiveBuffer().
U32 GFXPrimitiveBuffer::mPrimitiveCount
U32 GFXPrimitiveBuffer::mVolatileStart
U32 GFXPrimitiveBuffer::smActivePBCount static
GFXPrimitiveBuffer* GFXPrimitiveBuffer::smHead static
Referenced by GFXPrimitiveBuffer().
Copyright © GarageGames, LLC. All Rights Reserved.