GFXTexHandle Class Reference
Main Modules Class List Namespace List Online
GFXTexHandle Class Reference
A reference counted handle to a texture resource.
#include <gfx/gfxTextureHandle.h>
Public Member Functions
GFXTexHandle ()
GFXTexHandle (GFXTextureObject *obj)
GFXTexHandle (const GFXTexHandle &handle, const String &desc)
GFXTexHandle (const String &texName, GFXTextureProfile *profile, const String &desc)
GFXTexHandle (GBitmap *bmp, GFXTextureProfile *profile, bool deleteBmp, const String &desc)
GFXTexHandle (DDSFile *bmp, GFXTextureProfile *profile, bool deleteDDS, const String &desc)
GFXTexHandle (U32 width, U32 height, GFXFormat format, GFXTextureProfile *profile, const String &desc, U32 numMipLevels=1, S32 antialiasLevel=0)
bool copyToBmp (GBitmap *bmp)
void free ()
Releases the texture handle.
GBitmap * getBitmap ()
Returns the backing bitmap for this texture.
const GBitmap * getBitmap () const
U32 getDepth () const
GFXFormat getFormat () const
U32 getHeight () const
U32 getWidth () const
Point2I getWidthHeight () const
Returns the width and height as a point.
GFXLockedRect * lock (U32 mipLevel=0, RectI *inRect=NULL)
operator GFXTextureObject * () const
Returns the texture object.
bool operator!= (const GFXTexHandle &t) const
GFXTexHandle & operator= (const GFXTexHandle &t)
GFXTexHandle & operator= (GFXTextureObject *to)
bool operator== (const GFXTexHandle &t) const
void refresh ()
Reloads the texture.
bool set (const String &texName, GFXTextureProfile *profile, const String &desc)
bool set (GBitmap *bmp, GFXTextureProfile *profile, bool deleteBmp, const String &desc)
bool set (DDSFile *bmp, GFXTextureProfile *profile, bool deleteDDS, const String &desc)
bool set (U32 width, U32 height, GFXFormat format, GFXTextureProfile *profile, const String &desc, U32 numMipLevels=1, S32 antialiasLevel=0)
bool set (U32 width, U32 height, U32 depth, void *pixels, GFXFormat format, GFXTextureProfile *profile, const String &desc, U32 numMipLevels=1)
void unlock (U32 mipLevel=0)
Public Member Functions inherited from StrongRefPtr< GFXTextureObject >
StrongRefPtr ()
StrongRefPtr (GFXTextureObject *ptr)
StrongRefPtr (const StrongRefPtr< GFXTextureObject > &ref)
~StrongRefPtr ()
GFXTextureObject * getPointer () const
bool isNull () const
bool isValid () const
operator GFXTextureObject * () const
GFXTextureObject & operator* () const
GFXTextureObject * operator-> () const
StrongRefPtr< GFXTextureObject > & operator= (const StrongRefPtr< GFXTextureObject > &ref)
StrongRefPtr< GFXTextureObject > & operator= (GFXTextureObject *ptr)
Static Public Attributes
static GFXTexHandle ONE
Helper 2x2 R8G8B8A8 texture filled with 255.
static GFXTexHandle ZERO
Helper 2x2 R8G8B8A8 texture filled with 0.
static GFXTexHandle ZUP
Helper 2x2 R8G8B8A8 normal map texture filled with 128, 128, 255.
Additional Inherited Members
Protected Member Functions inherited from StrongObjectRef
void decRef ()
decrements the reference count on the referenced object
void incRef ()
increments the reference count on the referenced object
StrongObjectRef (StrongRefBase *object=NULL)
Constructor, assigns from the object and increments its reference count if it's not NULL.
~StrongObjectRef ()
Destructor, dereferences the object, if there is one.
void set (StrongRefBase *object)
Assigns this reference object from an existing StrongRefBase instance.
Protected Attributes inherited from StrongObjectRef
StrongRefBase * mObject
the object this RefObjectRef references
Detailed Description
A reference counted handle to a texture resource.
Constructor & Destructor Documentation
GFXTexHandle::GFXTexHandle () inline
GFXTexHandle::GFXTexHandle (GFXTextureObject * obj)
GFXTexHandle::GFXTexHandle (const GFXTexHandle & handle, const String & desc)
GFXTexHandle::GFXTexHandle (const String & texName, GFXTextureProfile * profile, const String & desc)
GFXTexHandle::GFXTexHandle (GBitmap * bmp, GFXTextureProfile * profile, bool deleteBmp, const String & desc)
GFXTexHandle::GFXTexHandle (DDSFile * bmp, GFXTextureProfile * profile, bool deleteDDS, const String & desc)
GFXTexHandle::GFXTexHandle (U32 width, U32 height, GFXFormat format, GFXTextureProfile * profile, const String & desc, U32 numMipLevels = 1, S32 antialiasLevel = 0)
Member Function Documentation
bool GFXTexHandle::copyToBmp (GBitmap * bmp) inline
References GFXTextureObject::copyToBmp(), and StrongRefPtr< GFXTextureObject >::getPointer().
void GFXTexHandle::free () inline
Releases the texture handle.
References StrongObjectRef::set().
GBitmap* GFXTexHandle::getBitmap () inline
Returns the backing bitmap for this texture.
References GFXTextureObject::getBitmap(), and StrongRefPtr< GFXTextureObject >::getPointer().
const GBitmap* GFXTexHandle::getBitmap () const inline
References GFXTextureObject::getBitmap(), and StrongRefPtr< GFXTextureObject >::getPointer().
U32 GFXTexHandle::getDepth () const inline
References GFXTextureObject::getDepth(), and StrongRefPtr< GFXTextureObject >::getPointer().
GFXFormat GFXTexHandle::getFormat () const inline
References GFXTextureObject::getFormat(), StrongRefPtr< GFXTextureObject >::getPointer(), and refresh().
U32 GFXTexHandle::getHeight () const inline
References GFXTextureObject::getHeight(), and StrongRefPtr< GFXTextureObject >::getPointer().
Referenced by getWidthHeight().
U32 GFXTexHandle::getWidth () const inline
References StrongRefPtr< GFXTextureObject >::getPointer(), and GFXTextureObject::getWidth().
Referenced by getWidthHeight().
Point2I GFXTexHandle::getWidthHeight () const inline
Returns the width and height as a point.
References getHeight(), StrongRefPtr< GFXTextureObject >::getPointer(), getWidth(), and Point2I::Zero.
GFXLockedRect* GFXTexHandle::lock (U32 mipLevel = 0, RectI * inRect = NULL) inline
References StrongRefPtr< GFXTextureObject >::getPointer(), and GFXTextureObject::lock().
GFXTexHandle::operator GFXTextureObject * () const inline
Returns the texture object.
References StrongRefPtr< GFXTextureObject >::getPointer().
bool GFXTexHandle::operator!= (const GFXTexHandle & t) const inline
References StrongRefPtr< T >::getPointer(), and StrongRefPtr< GFXTextureObject >::getPointer().
GFXTexHandle& GFXTexHandle::operator= (const GFXTexHandle & t) inline
References StrongRefPtr< T >::getPointer(), and StrongObjectRef::set().
GFXTexHandle& GFXTexHandle::operator= (GFXTextureObject * to) inline
References StrongObjectRef::set().
bool GFXTexHandle::operator== (const GFXTexHandle & t) const inline
References StrongRefPtr< T >::getPointer(), and StrongRefPtr< GFXTextureObject >::getPointer().
void GFXTexHandle::refresh ()
Reloads the texture.
See also
GFXTextureManager::reloadTexture
Referenced by getFormat().
bool GFXTexHandle::set (const String & texName, GFXTextureProfile * profile, const String & desc)
Referenced by VRTextureSet< 4 >::init().
bool GFXTexHandle::set (GBitmap * bmp, GFXTextureProfile * profile, bool deleteBmp, const String & desc)
bool GFXTexHandle::set (DDSFile * bmp, GFXTextureProfile * profile, bool deleteDDS, const String & desc)
bool GFXTexHandle::set (U32 width, U32 height, GFXFormat format, GFXTextureProfile * profile, const String & desc, U32 numMipLevels = 1, S32 antialiasLevel = 0)
bool GFXTexHandle::set (U32 width, U32 height, U32 depth, void * pixels, GFXFormat format, GFXTextureProfile * profile, const String & desc, U32 numMipLevels = 1)
void GFXTexHandle::unlock (U32 mipLevel = 0) inline
References StrongRefPtr< GFXTextureObject >::getPointer(), and GFXTextureObject::unlock().
Member Data Documentation
GFXTexHandle GFXTexHandle::ONE static
Helper 2x2 R8G8B8A8 texture filled with 255.
GFXTexHandle GFXTexHandle::ZERO static
Helper 2x2 R8G8B8A8 texture filled with 0.
GFXTexHandle GFXTexHandle::ZUP static
Helper 2x2 R8G8B8A8 normal map texture filled with 128, 128, 255.
Copyright © GarageGames, LLC. All Rights Reserved.