SceneLighting::ObjectProxy Class Reference
Main Modules Class List Namespace List Online
SceneLighting::ObjectProxy Class Reference abstract
Create a proxy for each object to store data.
#include <lighting/common/sceneLighting.h>
Public Member Functions
ObjectProxy (SceneObject *obj)
virtual ~ObjectProxy ()
virtual void addToShadowVolume (ShadowVolumeBSP *shadowVolume, LightInfo *light, S32 level)
virtual void getClipPlanes (Vector< PlaneF > &planes)
SceneObject * getObject ()
SceneObject * operator-> ()
virtual bool supportsShadowVolume ()
Lighting Interface
virtual bool loadResources ()
virtual void init ()
virtual bool tgePreLight (LightInfo *light)
virtual bool preLight (LightInfo *)
virtual void light (LightInfo *)
virtual void postLight (bool lastLight)
Lighting events
virtual void processLightingStart ()
virtual void processTGELightProcessEvent (U32 curr, U32 max, LightInfo *)
virtual bool processStartObjectLightingEvent (U32 current, U32 max)
virtual void processSGObjectProcessEvent (LightInfo *currLight)
Persistence
We cache lighting information to cut down on load times.
There are flags such as ForceAlways and LoadOnly which allow you to control this behaviour.
bool calcValidation ()
bool isValidChunk (PersistInfo::PersistChunk *)
virtual U32 getResourceCRC ()=0
virtual bool setPersistInfo (PersistInfo::PersistChunk *)
virtual bool getPersistInfo (PersistInfo::PersistChunk *)
Public Attributes
U32 mChunkCRC
SimObjectPtr< SceneObject > mObj
Detailed Description
Create a proxy for each object to store data.
Constructor & Destructor Documentation
SceneLighting::ObjectProxy::ObjectProxy (SceneObject * obj) inline
virtual SceneLighting::ObjectProxy::~ObjectProxy () inline virtual
Member Function Documentation
virtual void SceneLighting::ObjectProxy::addToShadowVolume (ShadowVolumeBSP * shadowVolume, LightInfo * light, S32 level) inline virtual
bool SceneLighting::ObjectProxy::calcValidation ()
Referenced by processSGObjectProcessEvent().
virtual void SceneLighting::ObjectProxy::getClipPlanes (Vector< PlaneF > & planes) inline virtual
SceneObject* SceneLighting::ObjectProxy::getObject () inline
virtual bool SceneLighting::ObjectProxy::getPersistInfo (PersistInfo::PersistChunk *) virtual
Referenced by processSGObjectProcessEvent().
virtual U32 SceneLighting::ObjectProxy::getResourceCRC () pure virtual
Referenced by processSGObjectProcessEvent().
virtual void SceneLighting::ObjectProxy::init () inline virtual
bool SceneLighting::ObjectProxy::isValidChunk (PersistInfo::PersistChunk *)
Referenced by processSGObjectProcessEvent().
virtual void SceneLighting::ObjectProxy::light (LightInfo *) inline virtual
Referenced by processSGObjectProcessEvent().
virtual bool SceneLighting::ObjectProxy::loadResources () inline virtual
SceneObject* SceneLighting::ObjectProxy::operator-> (void) inline
virtual void SceneLighting::ObjectProxy::postLight (bool lastLight) inline virtual
virtual bool SceneLighting::ObjectProxy::preLight (LightInfo *) inline virtual
Referenced by tgePreLight().
virtual void SceneLighting::ObjectProxy::processLightingStart () inline virtual
virtual void SceneLighting::ObjectProxy::processSGObjectProcessEvent (LightInfo * currLight) inline virtual
References calcValidation(), getPersistInfo(), getResourceCRC(), isValidChunk(), light(), and setPersistInfo().
virtual bool SceneLighting::ObjectProxy::processStartObjectLightingEvent (U32 current, U32 max) inline virtual
References Con::printf().
virtual void SceneLighting::ObjectProxy::processTGELightProcessEvent (U32 curr, U32 max, LightInfo *) inline virtual
References Con::printf().
virtual bool SceneLighting::ObjectProxy::setPersistInfo (PersistInfo::PersistChunk *) virtual
Referenced by processSGObjectProcessEvent().
virtual bool SceneLighting::ObjectProxy::supportsShadowVolume () inline virtual
virtual bool SceneLighting::ObjectProxy::tgePreLight (LightInfo * light) inline virtual
References preLight().
Member Data Documentation
U32 SceneLighting::ObjectProxy::mChunkCRC
SimObjectPtr<SceneObject> SceneLighting::ObjectProxy::mObj
Copyright © GarageGames, LLC. All Rights Reserved.