TamlAssetDeclaredUpdateVisitor Class Reference
Main Modules Class List Namespace List Online
TamlAssetDeclaredUpdateVisitor Class Reference
#include <assets/tamlAssetDeclaredUpdateVisitor.h>
Public Member Functions
TamlAssetDeclaredUpdateVisitor ()
virtual ~TamlAssetDeclaredUpdateVisitor ()
StringTableEntry getAssetIdFrom (void) const
const char * getAssetIdTo (void) const
void setAssetIdFrom (const char *pAssetIdFrom)
void setAssetIdTo (const char *pAssetIdTo)
virtual bool visit (const TamlParser &parser, TamlVisitor::PropertyState &propertyState)
The state of the visited property.
virtual bool wantsPropertyChanges (void)
Whether the visitor wants to perform property changes.
virtual bool wantsRootOnly (void)
Whether the visitor wants to visit the root node only.
Public Member Functions inherited from TamlVisitor
TamlVisitor ()
virtual ~TamlVisitor ()
Constructor & Destructor Documentation
TamlAssetDeclaredUpdateVisitor::TamlAssetDeclaredUpdateVisitor () inline
virtual TamlAssetDeclaredUpdateVisitor::~TamlAssetDeclaredUpdateVisitor () inline virtual
Member Function Documentation
StringTableEntry TamlAssetDeclaredUpdateVisitor::getAssetIdFrom (void) const inline
const char* TamlAssetDeclaredUpdateVisitor::getAssetIdTo (void) const inline
void TamlAssetDeclaredUpdateVisitor::setAssetIdFrom (const char * pAssetIdFrom) inline
References StringUnit::getUnit(), StringUnit::getUnitCount(), and Con::warnf().
void TamlAssetDeclaredUpdateVisitor::setAssetIdTo (const char * pAssetIdTo) inline
References StringUnit::getUnit(), StringUnit::getUnitCount(), and Con::warnf().
virtual bool TamlAssetDeclaredUpdateVisitor::visit (const TamlParser & parser, TamlVisitor::PropertyState & propertyState) inline virtual
The state of the visited property.
Implements TamlVisitor.
References TamlVisitor::PropertyState::getPropertyName(), TamlVisitor::PropertyState::getPropertyValue(), TamlVisitor::PropertyState::updatePropertyValue(), and Con::warnf().
virtual bool TamlAssetDeclaredUpdateVisitor::wantsPropertyChanges (void) inline virtual
Whether the visitor wants to perform property changes.
This allows a check against the parser which may not allow changes.
Implements TamlVisitor.
virtual bool TamlAssetDeclaredUpdateVisitor::wantsRootOnly (void) inline virtual
Whether the visitor wants to visit the root node only.
Implements TamlVisitor.
Copyright © GarageGames, LLC. All Rights Reserved.