SFXWavStream Class Reference
Main Modules Class List Namespace List Online
SFXWavStream Class Reference
An SFXFileStream that loads sample data from a WAV file.
#include <sfx/media/sfxWavStream.h>
Public Types
typedef SFXFileStream Parent
Public Types inherited from SFXStream
typedef void Parent
Public Types inherited from ThreadSafeRefCount< SFXStream >
typedef void Parent
Public Types inherited from IResettable
typedef void Parent
Public Types inherited from IPositionable< U32 >
typedef void Parent
typedef U32 PositionType
The type used to indicate positions.
Public Member Functions
SFXWavStream ()
SFXWavStream (const SFXWavStream &cloneFrom)
virtual ~SFXWavStream ()
Destructor.
virtual SFXStream * clone () const
Make a copy of this stream with its own private state, so new independent read() operations can be issued on the same data stream.
virtual U32 getPosition () const
virtual U32 read (U8 *buffer, U32 length)
Reads data from the stream and decompresses it into PCM samples.
virtual void reset ()
Resets the stream to restart reading data from the begining.
virtual void setPosition (U32 offset)
Set the current position to be "pos".
Public Member Functions inherited from SFXFileStream
virtual ~SFXFileStream ()
Destructor.
void close ()
Closes the stream.
U32 getDataLength () const
The data size in bytes of the decompressed PCM data.
U32 getDuration () const
The length of the sound in milliseconds.
const SFXFormat & getFormat () const
The format of the data in the stream.
U32 getSampleCount () const
The number of samples in the data stream.
bool isEOS () const
Returns true if we've reached the end of the stream.
bool open (Stream *stream, bool ownStream=false)
Opens and optionally takes ownership of the stream.
Public Member Functions inherited from SFXStream
virtual ~SFXStream ()
Destructor.
Public Member Functions inherited from ThreadSafeRefCount< SFXStream >
ThreadSafeRefCount ()
ThreadSafeRefCount (bool noSet)
void addRef ()
Increase the reference count on the object.
void clearLowestBit ()
U32 getRefCount () const
Get the current reference count.
bool isShared () const
void release ()
Decrease the object's reference count and delete the object, if the count drops to zero and claiming the object by the current thread succeeds.
Static Public Member Functions
static SFXWavStream * create (Stream *stream)
Static Public Member Functions inherited from SFXFileStream
static SFXFileStream * create (String filename)
This is a helper function used to create an appropriate SFXStream for the requested sound file.
static bool exists (String filename)
static void registerExtension (String ext, SFXFILESTREAM_CREATE_FN create_fn)
static void unregisterExtension (String ext)
Static Public Member Functions inherited from ThreadSafeRefCount< SFXStream >
static SFXStream * safeRead (SFXStream *const volatile &refPtr)
Dereference a reference-counted pointer in a multi-thread safe way.
Protected Member Functions
virtual void _close ()
Overloaded for cleanup of file format specific structures.
virtual bool _readHeader ()
Overloaded in the derived classes to read the file header.
Protected Member Functions inherited from SFXFileStream
SFXFileStream ()
Constructs the stream in an uninitilized state.
SFXFileStream (const SFXFileStream &cloneFrom)
Protected Attributes
U32 mDataStart
The file position of the start of the PCM data for fast reset().
Protected Attributes inherited from SFXFileStream
SFXFormat mFormat
The format of the data in the stream.
bool mOwnStream
If true then we're responsible for closing the stream.
U32 mSamples
The number of samples in the data stream.
Stream * mStream
The file stream we're reading from.
Protected Attributes inherited from ThreadSafeRefCount< SFXStream >
U32 mRefCount
Reference count and claim bit. Note that this increments in steps of two.
Additional Inherited Members
Protected Types inherited from SFXFileStream
typedef Vector< SFXFILESTREAM_CREATE_FN > CreateFnsVector
typedef Vector< String > ExtensionsVector
Static Protected Member Functions inherited from ThreadSafeRefCount< SFXStream >
static U32 decrementAndTestAndSet (U32 &refCount)
Decrement the given reference count.
Static Protected Attributes inherited from SFXFileStream
static CreateFnsVector smCreateFns
static ExtensionsVector smExtensions
Detailed Description
An SFXFileStream that loads sample data from a WAV file.
Member Typedef Documentation
typedef SFXFileStream SFXWavStream::Parent
Constructor & Destructor Documentation
SFXWavStream::SFXWavStream ()
Referenced by clone().
SFXWavStream::SFXWavStream (const SFXWavStream & cloneFrom)
virtual SFXWavStream::~SFXWavStream () virtual
Destructor.
Member Function Documentation
virtual void SFXWavStream::_close () protected virtual
Overloaded for cleanup of file format specific structures.
Implements SFXFileStream.
virtual bool SFXWavStream::_readHeader () protected virtual
Overloaded in the derived classes to read the file header.
It should initialize mFormat and mSamples.
Implements SFXFileStream.
virtual SFXStream* SFXWavStream::clone () const inline virtual
Make a copy of this stream with its own private state, so new independent read() operations can be issued on the same data stream.
Returns
Returns a copy of the stream or NULL.
Reimplemented from SFXStream.
References getPosition(), SFXFileStream::mStream, SAFE_DELETE, setPosition(), and SFXWavStream().
static SFXWavStream* SFXWavStream::create (Stream * stream) static
virtual U32 SFXWavStream::getPosition () const virtual
Returns
the current position.
Implements IPositionable< U32 >.
Referenced by clone().
virtual U32 SFXWavStream::read (U8 * buffer, U32 length) virtual
Reads data from the stream and decompresses it into PCM samples.
Parameters
length Number of bytes to read.
Implements SFXStream.
virtual void SFXWavStream::reset () virtual
Resets the stream to restart reading data from the begining.
Implements SFXStream.
virtual void SFXWavStream::setPosition (U32 pos) virtual
Set the current position to be "pos".
Parameters
pos The new position.
Implements IPositionable< U32 >.
Referenced by clone().
Member Data Documentation
U32 SFXWavStream::mDataStart protected
The file position of the start of the PCM data for fast reset().
Copyright © GarageGames, LLC. All Rights Reserved.