TamlWriteNode Class Reference
Main Modules Class List Namespace List Online
TamlWriteNode Class Reference
#include <persistence/taml/tamlWriteNode.h>
Classes
class FieldValuePair
Public Member Functions
TamlWriteNode ()
void resetNode (void)
void set (SimObject *pSimObject)
Public Attributes
Vector< TamlWriteNode * > * mChildren
TamlCustomNodes mCustomNodes
Vector< TamlWriteNode::FieldValuePair * > mFields
const char * mpObjectName
SimObject * mpSimObject
TamlCallbacks * mpTamlCallbacks
U32 mRefId
TamlWriteNode * mRefToNode
Constructor & Destructor Documentation
TamlWriteNode::TamlWriteNode () inline
References mChildren, mpObjectName, mpSimObject, mpTamlCallbacks, mRefToNode, and resetNode().
Member Function Documentation
void TamlWriteNode::resetNode (void)
Referenced by set(), and TamlWriteNode().
void TamlWriteNode::set (SimObject * pSimObject) inline
References SimObject::getName(), mpObjectName, mpSimObject, mpTamlCallbacks, and resetNode().
Member Data Documentation
Vector<TamlWriteNode*>* TamlWriteNode::mChildren
Referenced by TamlWriteNode().
TamlCustomNodes TamlWriteNode::mCustomNodes
Vector<TamlWriteNode::FieldValuePair*> TamlWriteNode::mFields
const char* TamlWriteNode::mpObjectName
Referenced by set(), and TamlWriteNode().
SimObject* TamlWriteNode::mpSimObject
Referenced by set(), and TamlWriteNode().
TamlCallbacks* TamlWriteNode::mpTamlCallbacks
Referenced by set(), and TamlWriteNode().
U32 TamlWriteNode::mRefId
TamlWriteNode* TamlWriteNode::mRefToNode
Referenced by TamlWriteNode().
Copyright © GarageGames, LLC. All Rights Reserved.