GFXTextureObject Class Reference
Main Modules Class List Namespace List Online
GFXTextureObject Class Reference abstract
#include <gfx/gfxTextureObject.h>
Public Member Functions
GFXTextureObject (GFXDevice *aDevice, GFXTextureProfile *profile)
virtual ~GFXTextureObject ()
virtual bool copyToBmp (GBitmap *bmp)=0
virtual const String describeSelf () const
The resource should put a description of itself (number of vertices, size/width of texture, etc.) in buffer.
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
bool dumpToDisk (const String &bmType, const String &path)
Debug helper function for writing the texture to disk.
GBitmap * getBitmap ()
U32 getBitmapDepth () const
U32 getBitmapHeight () const
U32 getBitmapWidth () const
DDSFile * getDDS ()
U32 getDepth () const
U32 getEstimatedSizeInBytes () const
Returns the estimated video memory usage in bytes including mipmaps.
GFXFormat getFormat () const
U32 getFormatByteSize () const
U32 getHeight () const
virtual F32 getMaxUCoord () const
virtual F32 getMaxVCoord () const
U32 getMipLevels () const
const String & getPath () const
Returns the file path to the texture if it was loaded from disk.
const Point3I & getSize () const
U32 getWidth () const
bool isRenderTarget () const
Returns true if this texture is a render target.
virtual void kill ()
virtual GFXLockedRect * lock (U32 mipLevel=0, RectI *inRect=NULL)=0
Acquire a lock on part of the texture.
virtual void pureVirtualCrash ()=0
virtual void unlock (U32 mipLevel=0)=0
Releases a lock previously acquired.
Public Member Functions inherited from StrongRefBase
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Public Member Functions inherited from GFXResource
GFXResource ()
virtual ~GFXResource ()
void clearFlag ()
GFXResource * getNextResource () const
GFXDevice * getOwningDevice () const
GFXResource * getPrevResource () const
bool isFlagged ()
void registerResourceWithDevice (GFXDevice *device)
Registers this resource with the given device.
virtual void resurrect ()=0
When called the resource should restore all device sensitive information destroyed by zombify()
void setFlag ()
virtual void zombify ()=0
When called the resource should destroy all device sensitive information (e.g. D3D resources in D3DPOOL_DEFAULT.
Static Public Member Functions
static U32 dumpActiveTOs ()
Public Attributes
S32 mAntialiasLevel
GBitmap * mBitmap
GBitmap we are backed by.
Point3I mBitmapSize
DDSFile * mDDS
DDSFile we're backed by.
bool mDead
String mDebugCreationPath
String mDebugDescription
GFXTextureObject * mDebugNext
GFXTextureObject * mDebugPrev
U32 mDeleteTime
The time at which all references to this texture were removed.
GFXDevice * mDevice
The device this texture belongs to.
GFXFormat mFormat
GFXTextureObject * mHashNext
The siblings in the cache hash table.
bool mHasTransparency
U32 mMipLevels
GFXTextureObject * mNext
The next texture in the linked list.
String mPath
The path to the texture file if the content was loaded from a resource.
GFXTextureObject * mPrev
The previous texture in the linked list.
GFXTextureProfile * mProfile
String mTextureLookupName
This is the file name or other unique string used to hash this texture object.
Point3I mTextureSize
Static Public Attributes
static U32 smActiveTOCount
static GFXTextureObject * smHead
Additional Inherited Members
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Protected Attributes inherited from StrongRefBase
U32 mRefCount
reference counter for StrongRefPtr objects
Constructor & Destructor Documentation
GFXTextureObject::GFXTextureObject (GFXDevice * aDevice, GFXTextureProfile * profile)
virtual GFXTextureObject::~GFXTextureObject () virtual
Member Function Documentation
virtual bool GFXTextureObject::copyToBmp (GBitmap * bmp) pure virtual
Implemented in GFXD3D11TextureObject, and GFXGLTextureObject.
Referenced by GFXTexHandle::copyToBmp().
virtual const String GFXTextureObject::describeSelf () const virtual
The resource should put a description of itself (number of vertices, size/width of texture, etc.) in buffer.
Implements GFXResource.
Reimplemented in GFXGLTextureObject.
virtual void GFXTextureObject::destroySelf () virtual
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
Reimplemented from StrongRefBase.
static U32 GFXTextureObject::dumpActiveTOs () static
bool GFXTextureObject::dumpToDisk (const String & bmType, const String & path)
Debug helper function for writing the texture to disk.
GBitmap * GFXTextureObject::getBitmap () inline
Referenced by GFXTexHandle::getBitmap().
U32 GFXTextureObject::getBitmapDepth () const inline
References Point3I::z.
U32 GFXTextureObject::getBitmapHeight () const inline
References Point3I::y.
U32 GFXTextureObject::getBitmapWidth () const inline
References Point3I::x.
DDSFile * GFXTextureObject::getDDS () inline
U32 GFXTextureObject::getDepth () const inline
References Point3I::z.
Referenced by GFXTexHandle::getDepth().
U32 GFXTextureObject::getEstimatedSizeInBytes () const
Returns the estimated video memory usage in bytes including mipmaps.
GFXFormat GFXTextureObject::getFormat () const inline
Referenced by GFXTexHandle::getFormat().
U32 GFXTextureObject::getFormatByteSize () const inline
U32 GFXTextureObject::getHeight () const inline
References Point3I::y.
Referenced by GFXTexHandle::getHeight().
virtual F32 GFXTextureObject::getMaxUCoord () const virtual
Reimplemented in GFXGLTextureObject.
virtual F32 GFXTextureObject::getMaxVCoord () const virtual
Reimplemented in GFXGLTextureObject.
U32 GFXTextureObject::getMipLevels () const inline
const String& GFXTextureObject::getPath (void) const inline
Returns the file path to the texture if it was loaded from disk.
const Point3I& GFXTextureObject::getSize () const inline
U32 GFXTextureObject::getWidth () const inline
References Point3I::x.
Referenced by GFXTexHandle::getWidth().
bool GFXTextureObject::isRenderTarget () const inline
Returns true if this texture is a render target.
References GFXTextureProfile::isRenderTarget().
virtual void GFXTextureObject::kill () virtual
virtual GFXLockedRect* GFXTextureObject::lock (U32 mipLevel = 0, RectI * inRect = NULL) pure virtual
Acquire a lock on part of the texture.
The GFXLockedRect returned is managed by the GFXTextureObject and does not need to be freed.
Implemented in GFXD3D11TextureObject, and GFXGLTextureObject.
Referenced by GFXTexHandle::lock().
virtual void GFXTextureObject::pureVirtualCrash () pure virtual
Implemented in GFXD3D11TextureObject, and GFXGLTextureObject.
virtual void GFXTextureObject::unlock (U32 mipLevel = 0) pure virtual
Releases a lock previously acquired.
Note that the mipLevel parameter must match the corresponding lock!
Implemented in GFXD3D11TextureObject, and GFXGLTextureObject.
Referenced by GFXTexHandle::unlock().
Member Data Documentation
S32 GFXTextureObject::mAntialiasLevel
GBitmap* GFXTextureObject::mBitmap
GBitmap we are backed by.
Point3I GFXTextureObject::mBitmapSize
DDSFile* GFXTextureObject::mDDS
DDSFile we're backed by.
bool GFXTextureObject::mDead
String GFXTextureObject::mDebugCreationPath
String GFXTextureObject::mDebugDescription
GFXTextureObject* GFXTextureObject::mDebugNext
GFXTextureObject* GFXTextureObject::mDebugPrev
U32 GFXTextureObject::mDeleteTime
The time at which all references to this texture were removed.
GFXDevice* GFXTextureObject::mDevice
The device this texture belongs to.
GFXFormat GFXTextureObject::mFormat
GFXTextureObject* GFXTextureObject::mHashNext
The siblings in the cache hash table.
See also
GFXTextureManager::mHashTable
bool GFXTextureObject::mHasTransparency
U32 GFXTextureObject::mMipLevels
GFXTextureObject* GFXTextureObject::mNext
The next texture in the linked list.
See also
GFXTextureManager::mListHead
String GFXTextureObject::mPath
The path to the texture file if the content was loaded from a resource.
GFXTextureObject* GFXTextureObject::mPrev
The previous texture in the linked list.
See also
GFXTextureManager::mListHead
GFXTextureProfile* GFXTextureObject::mProfile
String GFXTextureObject::mTextureLookupName
This is the file name or other unique string used to hash this texture object.
Point3I GFXTextureObject::mTextureSize
U32 GFXTextureObject::smActiveTOCount static
GFXTextureObject* GFXTextureObject::smHead static
Copyright © GarageGames, LLC. All Rights Reserved.