GenericConstBufferLayout Class Reference
Main Modules Class List Namespace List Online
GenericConstBufferLayout Class Reference
This class defines the memory layout for a GenericConstBuffer.
#include <gfx/genericConstBuffer.h>
Classes
struct ParamDesc
Describes the parameters we contain.
Public Member Functions
GenericConstBufferLayout ()
virtual ~GenericConstBufferLayout ()
virtual void addParameter (const String &name, const GFXShaderConstType constType, const U32 offset, const U32 size, const U32 arraySize, const U32 alignValue)
Add a parameter to the buffer.
void clear ()
Restore to initial state.
U32 getBufferSize () const
Get the size of the buffer.
bool getDesc (const String &name, ParamDesc &param) const
Returns the ParamDesc of a parameter.
bool getDesc (const U32 index, ParamDesc &param) const
Returns the ParamDesc of a parameter.
U32 getParameterCount () const
Get the number of parameters.
bool read (Stream *s)
Load this layout from a stream.
virtual bool set (const ParamDesc &pd, const GFXShaderConstType constType, const U32 size, const void *data, U8 *basePointer)
Set a parameter, given a base pointer.
bool write (Stream *s)
Save this layout to a stream.
Protected Types
typedef Vector< ParamDesc > Params
Vector of parameter descriptions.
Protected Member Functions
virtual bool setMatrix (const ParamDesc &pd, const GFXShaderConstType constType, const U32 size, const void *data, U8 *basePointer)
Set a matrix, given a base pointer.
Protected Attributes
U32 mBufferSize
U32 mCurrentIndex
Params mParams
Vector of parameter descriptions.
U32 mTimesCleared
Detailed Description
This class defines the memory layout for a GenericConstBuffer.
Member Typedef Documentation
typedef Vector<ParamDesc> GenericConstBufferLayout::Params protected
Vector of parameter descriptions.
Constructor & Destructor Documentation
GenericConstBufferLayout::GenericConstBufferLayout ()
virtual GenericConstBufferLayout::~GenericConstBufferLayout () inline virtual
References addParameter(), GenericConstBufferLayout::ParamDesc::alignValue, GenericConstBufferLayout::ParamDesc::arraySize, GenericConstBufferLayout::ParamDesc::constType, GenericConstBufferLayout::ParamDesc::name, GenericConstBufferLayout::ParamDesc::offset, and GenericConstBufferLayout::ParamDesc::size.
Member Function Documentation
virtual void GenericConstBufferLayout::addParameter (const String & name, const GFXShaderConstType constType, const U32 offset, const U32 size, const U32 arraySize, const U32 alignValue) virtual
Add a parameter to the buffer.
Referenced by ~GenericConstBufferLayout().
void GenericConstBufferLayout::clear ()
Restore to initial state.
U32 GenericConstBufferLayout::getBufferSize () const inline
Get the size of the buffer.
References mBufferSize.
Referenced by GenericConstBuffer::isEqual().
bool GenericConstBufferLayout::getDesc (const String & name, ParamDesc & param) const
Returns the ParamDesc of a parameter.
Referenced by getParameterCount().
bool GenericConstBufferLayout::getDesc (const U32 index, ParamDesc & param) const
Returns the ParamDesc of a parameter.
U32 GenericConstBufferLayout::getParameterCount () const inline
Get the number of parameters.
References GenericConstBufferLayout::ParamDesc::clear(), GenericConstBufferLayout::ParamDesc::constType, getDesc(), GenericConstBufferLayout::ParamDesc::index, mParams, read(), setMatrix(), GenericConstBufferLayout::ParamDesc::size, Vector< T >::size(), and write().
bool GenericConstBufferLayout::read (Stream * s)
Load this layout from a stream.
Referenced by getParameterCount().
virtual bool GenericConstBufferLayout::set (const ParamDesc & pd, const GFXShaderConstType constType, const U32 size, const void * data, U8 * basePointer) virtual
Set a parameter, given a base pointer.
Reimplemented in GFXD3D11ConstBufferLayout.
virtual bool GenericConstBufferLayout::setMatrix (const ParamDesc & pd, const GFXShaderConstType constType, const U32 size, const void * data, U8 * basePointer) protected virtual
Set a matrix, given a base pointer.
Reimplemented in GFXD3D11ConstBufferLayout.
Referenced by getParameterCount().
bool GenericConstBufferLayout::write (Stream * s)
Save this layout to a stream.
Referenced by getParameterCount().
Member Data Documentation
U32 GenericConstBufferLayout::mBufferSize protected
Referenced by getBufferSize().
U32 GenericConstBufferLayout::mCurrentIndex protected
Params GenericConstBufferLayout::mParams protected
Vector of parameter descriptions.
Referenced by getParameterCount().
U32 GenericConstBufferLayout::mTimesCleared protected
Copyright © GarageGames, LLC. All Rights Reserved.