Material::StageData Class Reference
Main Modules Class List Namespace List Online
Material::StageData Class Reference
#include <materials/materialDefinition.h>
Public Member Functions
StageData ()
GFXCubemap * getCubemap () const
Returns the stage cubemap.
void getFeatureSet (FeatureSet *outFeatures) const
Returns the active texture features.
GFXTextureObject * getTex (const FeatureType &type) const
Returns the texture object or NULL if there is no texture entry for that feature type in the table.
bool hasValidTex () const
Returns true if we have a valid texture assigned to any feature in the texture table.
void setCubemap (GFXCubemap *cubemap)
Set the stage cubemap.
void setTex (const FeatureType &type, GFXTextureObject *tex)
Assigns a texture object by feature type.
Protected Types
typedef HashTable< const FeatureType *, GFXTexHandle > TextureTable
Protected Attributes
GFXCubemap * mCubemap
The cubemap for this stage.
TextureTable mTextures
The sparse table of textures by feature index.
Member Typedef Documentation
typedef HashTable<const FeatureType*,GFXTexHandle> Material::StageData::TextureTable protected
Constructor & Destructor Documentation
Material::StageData::StageData () inline
Member Function Documentation
GFXCubemap* Material::StageData::getCubemap () const inline
Returns the stage cubemap.
References mCubemap.
void Material::StageData::getFeatureSet (FeatureSet * outFeatures) const
Returns the active texture features.
Referenced by hasValidTex().
GFXTextureObject* Material::StageData::getTex (const FeatureType & type) const inline
Returns the texture object or NULL if there is no texture entry for that feature type in the table.
References HashTable< Key, Value >::end(), and HashTable< Key, Value >::find().
bool Material::StageData::hasValidTex () const inline
Returns true if we have a valid texture assigned to any feature in the texture table.
References HashTable< Key, Value >::begin(), HashTable< Key, Value >::end(), and getFeatureSet().
void Material::StageData::setCubemap (GFXCubemap * cubemap) inline
Set the stage cubemap.
void Material::StageData::setTex (const FeatureType & type, GFXTextureObject * tex) inline
Assigns a texture object by feature type.
References HashTable< Key, Value >::end(), HashTable< Key, Value >::erase(), HashTable< Key, Value >::find(), and HashTable< Key, Value >::findOrInsert().
Member Data Documentation
GFXCubemap* Material::StageData::mCubemap protected
The cubemap for this stage.
Referenced by getCubemap().
TextureTable Material::StageData::mTextures protected
The sparse table of textures by feature index.
See also
getTex
setTex
Copyright © GarageGames, LLC. All Rights Reserved.