SimObject Class Reference
Main Modules Class List Namespace List Online
SimObject Class Reference
Base class for objects involved in the simulation.
#include <console/simObject.h>
Inherits ConsoleObject, and TamlCallbacks.
Inherited by ActionMap, ArrayObject, AssetBase, AssetManager, AssetQuery, AssetTagsManifest, BaseMaterialDefinition, ConsoleLogger, CubemapData, DebugDrawer, DeclaredAssets, EventManager, FieldBrushObject, FileDialog, FileObject, ForestBrushElement, ForestTool, GFXSamplerStateData, GFXStateBlockData, Gizmo, GizmoProfile, GuiControlProfile, GuiCursor, GuiImageList, InputDevice, LangTable, LeapMotionFrame, Message, MessageVector, ModuleManager, ModuleMergeDefinition, PersistenceManager, PopupMenu, RazerHydraFrame, ReferencedAssets, RenderBinManager, RenderPassManager, RenderPassStateToken, SceneLighting, ScriptMsgListener, ScriptObject, Settings, SFXParameter, ShaderData, SimDataBlock, SimResponseCurve, SimSet, SimXMLDocument, StreamObject, Taml, TCPObject, TerrainMaterial, TSShapeConstructor, UndoAction, UndoManager, and ZipObject.
Classes
struct Notify
Public Types
typedef ConsoleObject Parent
enum WriteFlags {
SelectedOnly = BIT(0),
NoName = BIT(1),
IgnoreCanSave = BIT(2)
}
Flags passed to SimObject::write.
Public Types inherited from EngineObject
typedef void(* DebugEnumInstancesCallback) (EngineObject *)
Type of callback function for iterating over EngineObject instances.
Public Member Functions
virtual void copyTo (SimObject *object)
Copy SimObject to another SimObject (Originally designed for T2D).
DECLARE_CONOBJECT (SimObject)
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
virtual SimObject * findObject (const char *name)
Find a named sub-object of this object.
virtual void getConsoleMethodData (const char *fname, S32 routingId, S32 *type, S32 *minArgs, S32 *maxArgs, void **callback, const char **usage)
Namespace * getNamespace ()
Return the object's namespace.
StringTableEntry getProgenitorFile (void) const
virtual bool handlesConsoleMethod (const char *fname, S32 *routingId)
void setProgenitorFile (const char *pFile)
const char * tabComplete (const char *prevText, S32 baseLen, bool)
Get next matching item in namespace.
Public Member Functions inherited from ConsoleObject
ConsoleObject ()
virtual AbstractClassRep * getClassRep () const
Gets the ClassRep.
const AbstractClassRep::Field * findField (StringTableEntry fieldName) const
Get a reference to a field by name.
bool setField (const char *fieldName, const char *value)
Set the value of a field.
void logMessage (const char *fmt,...) const
Logs with Con::printf.
void logWarning (const char *fmt,...) const
Logs with Con::warnf.
void logError (const char *fmt,...) const
Logs with Con::errorf.
const AbstractClassRep::FieldList & getFieldList () const
Get a list of all the fields. This information cannot be modified.
AbstractClassRep::FieldList & getModifiableFieldList ()
Get a list of all the fields, set up so we can modify them.
bool & getDynamicGroupExpand ()
Get a handle to a boolean telling us if we expanded the dynamic group.
S32 getClassId (U32 netClassGroup) const
Get our network-layer class id.
StringTableEntry getClassName () const
Get our compiler and platform independent class name.
Public Member Functions inherited from EngineObject
EngineObject ()
virtual ~EngineObject ()
DECLARE_ABSTRACT_CLASS (EngineObject, void)
DECLARE_INSCOPE (_GLOBALSCOPE)
IEngineObjectPool * getEngineObjectPool () const
Return the pool of EngineObjects to which this object belongs.
void operator delete (void *ptr)
Release the given object's memory in the pool it has been allocated from.
void * operator new (size_t size)
void * operator new (size_t size, IEngineObjectPool *pool)
void * operator new (size_t size TORQUE_TMM_ARGS_DECL)
Allocate a new object in the default object pool.
void * operator new (size_t size, IEngineObjectPool *pool TORQUE_TMM_ARGS_DECL)
Allocate a new object in the given object pool.
void * operator new (size_t size, void *ptr)
Placement new.
Public Member Functions inherited from StrongRefBase
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Static Public Member Functions
static SimObject * __findObject (const char *id)
static const char * __getObjectId (ConsoleObject *object)
static void initPersistFields ()
Static Public Member Functions inherited from ConsoleObject
static const char * __category ()
static const char * __description ()
static void consoleInit ()
Register global constant variables and do other one-time initialization tasks in a subclass of ConsoleObject.
static void initPersistFields ()
Register dynamic fields in a subclass of ConsoleObject.
static const char * lookupClassName (const U32 in_classTag)
Get the classname from a class tag.
static ConsoleObject * create (const char *in_pClassName)
static ConsoleObject * create (const U32 groupId, const U32 typeId, const U32 in_classId)
static void addGroup (const char *in_pGroupname, const char *in_pGroupDocs=NULL)
Mark the beginning of a group of fields.
static void endGroup (const char *in_pGroupname)
Mark the end of a group of fields.
static void addArray (const char *arrayName, S32 count)
Marks the start of a fixed size array of fields.
static void endArray (const char *arrayName)
Marks the end of an array of fields.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a complex field.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::WriteDataNotify in_writeDataFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, const char *in_pFieldDocs, U32 flags=0)
Register a simple field.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::WriteDataNotify in_writeDataFn, const char *in_pFieldDocs, U32 flags=0)
static void addFieldV (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, TypeValidator *v, const char *in_pFieldDocs=NULL)
Register a validated field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, AbstractClassRep::WriteDataNotify in_writeDataFn=&defaultProtectedWriteFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a complex protected field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, AbstractClassRep::WriteDataNotify in_writeDataFn=&defaultProtectedWriteFn, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a simple protected field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addDeprecatedField (const char *fieldName)
Add a deprecated field.
static bool removeField (const char *in_pFieldname)
Remove a field.
static AbstractClassRep * getStaticClassRep ()
Get the abstract class information for this class.
static AbstractClassRep * getParentStaticClassRep ()
Get the abstract class information for this class's superclass.
static ConsoleObject * __findObject (const char *)
static const char * __getObjectId (ConsoleObject *)
Static Public Member Functions inherited from EngineObject
static void debugDumpInstances ()
Dump describeSelf()s of all live ConsoleObjects to the console.
static void debugEnumInstances (const std::type_info &type, DebugEnumInstancesCallback callback)
Call the given callback for all instances of the given type.
static void debugEnumInstances (const char *className, DebugEnumInstancesCallback callback)
Same as above but uses an export class name and also includes inheritance (i.e.
Protected Member Functions
virtual void _destroySelf ()
Subclasses should overload this method instead of the public destroySelf().
virtual String _getLogMessage (const char *fmt, va_list args) const
We can provide more detail, like object name and id.
virtual void _onSelected ()
Called when the object is selected in the editor.
virtual void _onUnselected ()
Called when the object is unselected in the editor.
object incRefCount ()
virtual void onTamlAddParent (SimObject *pParentObject)
Called after Taml has finished reading the object and has added the object to any parent.
virtual void onTamlCustomRead (const TamlCustomNodes &customNodes)
Called during the reading of the object to allow custom properties to be read.
virtual void onTamlCustomWrite (TamlCustomNodes &customNodes)
Called during the writing of the object to allow custom properties to be written.
virtual void onTamlPostRead (const TamlCustomNodes &customNodes)
Called after Taml has finished reading the object.
virtual void onTamlPostWrite (void)
Called after Taml has finished writing the object.
virtual void onTamlPreRead (void)
Called prior to Taml reading the object.
virtual void onTamlPreWrite (void)
Taml callbacks.
object registerObject ()
Protected Member Functions inherited from ConsoleObject
ConsoleObject (const ConsoleObject &)
Protected Member Functions inherited from EngineObject
object incRefCount ()
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Protected Attributes
DEFINE_CREATE_METHOD
SimObjectId mId
Id number for this object.
StringTableEntry mInternalName
Internal name assigned to the object. Not set by default.
return object
Protected Attributes inherited from EngineObject
DEFINE_CREATE_METHOD
return object
Protected Attributes inherited from StrongRefBase
U32 mRefCount
reference counter for StrongRefPtr objects
Static Protected Attributes
static SimObjectId smForcedId
The Id to force upon the object. Poor object.
static bool smForceId
Force a registered object to use the given Id. Cleared upon use.
Notification
Notify * removeNotify (void *ptr, Notify::Type)
Remove a notification from the list.
void deleteNotify (SimObject *obj)
Notify an object when we are deleted.
void clearNotify (SimObject *obj)
Notify an object when we are cleared.
void clearAllNotifications ()
Remove all notifications for this object.
void processDeleteNotifies ()
Send out deletion notifications.
void registerReference (SimObject **obj)
Register a reference to this object.
void unregisterReference (SimObject **obj)
Unregister a reference to this object.
Serialization
bool mCanSaveFieldDictionary
Whether dynamic fields should be saved out in serialization. Defaults to true.
virtual bool writeField (StringTableEntry fieldname, const char *value)
Determine whether or not a field should be written.
virtual void write (Stream &stream, U32 tabStop, U32 flags=0)
Output the TorqueScript to recreate this object.
virtual void writeFields (Stream &stream, U32 tabStop)
Write the fields of this object in TorqueScript.
virtual bool writeObject (Stream *stream)
virtual bool readObject (Stream *stream)
void setCanSaveDynamicFields (bool bCanSave)
Set whether fields created at runtime should be saved. Default is true.
bool getCanSaveDynamicFields ()
Get whether fields created at runtime should be saved. Default is true.
SimObject * getCopySource () const
Return the object that this object is copying fields from.
void setCopySource (SimObject *object)
Set the object that this object should be copying fields from.
void assignFieldsFrom (SimObject *obj)
Copy fields from another object onto this one.
void assignDynamicFieldsFrom (SimObject *obj)
Copy dynamic fields from another object onto this one.
Persistent IDs
SimPersistID * mPersistentId
Persistent ID assigned to this object.
SimPersistID * getPersistentId () const
Return the persistent ID assigned to this object or NULL.
SimPersistID * getOrCreatePersistentId ()
Return the persistent ID assigned to this object or assign one to it if it has none.
static bool _setPersistentID (void *object, const char *index, const char *data)
Namespace management
Namespace * mNameSpace
The namespace in which method lookup for this object begins.
StringTableEntry mClassName
Name of namespace to use as class namespace.
StringTableEntry mSuperClassName
Name of namespace to use as class super namespace.
StringTableEntry getClassNamespace () const
Return name of class namespace set on this object.
StringTableEntry getSuperClassNamespace () const
Return name of superclass namespace set on this object.
void setClassNamespace (const char *classNamespace)
void setSuperClassNamespace (const char *superClassNamespace)
void linkNamespaces ()
Perform namespace linking on this object.
void unlinkNamespaces ()
Undo namespace linking on this object.
Cloning
virtual SimObject * clone ()
Return a shallow copy of this object.
virtual SimObject * deepClone ()
Return a deep copy of this object.
Accessors
const char * getDataField (StringTableEntry slotName, const char *array)
Get the value of a field on the object.
void setDataField (StringTableEntry slotName, const char *array, const char *value)
Set the value of a field on the object.
const char * getPrefixedDataField (StringTableEntry fieldName, const char *array)
void setPrefixedDataField (StringTableEntry fieldName, const char *array, const char *value)
const char * getPrefixedDynamicDataField (StringTableEntry fieldName, const char *array, const S32 fieldType=-1)
void setPrefixedDynamicDataField (StringTableEntry fieldName, const char *array, const char *value, const S32 fieldType=-1)
StringTableEntry getDataFieldPrefix (StringTableEntry fieldName)
U32 getDataFieldType (StringTableEntry slotName, const char *array)
Get the type of a field on the object.
void setDataFieldType (const U32 fieldTypeId, StringTableEntry slotName, const char *array)
Set the type of a dynamic field on the object.
void setDataFieldType (const char *typeName, StringTableEntry slotName, const char *array)
SimFieldDictionary * getFieldDictionary ()
Get reference to the dictionary containing dynamic fields.
virtual StringTableEntry getComponentName ()
void setInternalName (const char *newname)
These functions support internal naming that is not namespace bound for locating child controls in a generic way.
StringTableEntry getInternalName () const
Get the internal name of this control.
void setOriginalName (const char *originalName)
Set the original name of this control.
StringTableEntry getOriginalName () const
Get the original name of this control.
void setFilename (const char *file)
These functions allow you to set and access the filename where this object was created.
StringTableEntry getFilename () const
Get the filename.
void setDeclarationLine (U32 lineNumber)
These functions are used to track the line number (1-based) on which the object was created if it was loaded from script.
S32 getDeclarationLine () const
Get the declaration line number.
virtual bool save (const char *pcFilePath, bool bOnlySelected=false, const char *preappend=NULL)
Save object as a TorqueScript File.
virtual bool isMethod (const char *methodName)
Check if a method exists in the objects current namespace.
virtual bool isField (const char *fieldName, bool includeStatic=true, bool includeDynamic=true)
Return true if the field is defined on the object.
SimObjectId getId () const
Return the unique numeric object ID.
const char * getIdString () const
Return the object ID as a string.
StringTableEntry getName () const
Return the name of this object.
SimGroup * getGroup () const
Return the SimGroup that this object is contained in.
void assignName (const char *name)
Assign the given name to this object.
void setId (SimObjectId id)
bool isChildOfGroup (SimGroup *pGroup)
bool isProperlyAdded () const
bool isDeleted () const
bool isRemoved () const
virtual bool isLocked () const
virtual void setLocked (bool b)
virtual bool isHidden () const
virtual void setHidden (bool b)
bool isSelected () const
bool isExpanded () const
bool isEditorOnly () const
bool isNameChangeAllowed () const
bool isAutoDeleted () const
void setSelected (bool sel)
void setExpanded (bool exp)
void setModDynamicFields (bool dyn)
void setModStaticFields (bool sta)
bool canModDynamicFields ()
bool canModStaticFields ()
void setAutoDelete (bool val)
void setEditorOnly (bool val)
void setNameChangeAllowed (bool val)
bool getCanSave () const
Returns boolean specifying if the object can be serialized.
virtual void setCanSave (bool val)
Set serialization flag.
bool isSelectedRecursive () const
Returns true if this object is selected or any group it is a member of is.
static void setForcedId (SimObjectId id)
Force an Id on the next registered object.
Initialization
SimObject ()
virtual ~SimObject ()
virtual bool processArguments (S32 argc, ConsoleValueRef *argv)
Process constructor options. (ie, new SimObject(1,2,3))
Events
virtual bool onAdd ()
Called when the object is added to the sim.
virtual void onRemove ()
Called when the object is removed from the sim.
virtual void onGroupAdd ()
Called when the object is added to a SimGroup.
virtual void onGroupRemove ()
Called when the object is removed from a SimGroup.
virtual void onNameChange (const char *name)
Called when the object's name is changed.
virtual void onPostAdd ()
Called when the adding of the object to the sim is complete, all sub-objects have been processed as well.
virtual void onStaticModified (const char *slotName, const char *newValue=NULL)
Specifically, these are called by setDataField when a static or dynamic field is modified, see the console details.
virtual void onDynamicModified (const char *slotName, const char *newValue=NULL)
Called when a dynamic field is modified.
virtual void inspectPreApply ()
Called before any property of the object is changed in the world editor.
virtual void inspectPostApply ()
Called after any property of the object is changed in the world editor.
virtual void onDeleteNotify (SimObject *object)
Called when a SimObject is deleted.
virtual void onEditorEnable ()
Called when the editor is activated.
virtual void onEditorDisable ()
Called when the editor is deactivated.
Registration
SimObjects must be registered with the object system.
bool registerObject ()
Register an object with the object system.
bool registerObject (U32 id)
Register the object, forcing the id.
bool registerObject (const char *name)
Register the object, assigning the name.
bool registerObject (const char *name, U32 id)
Register the object, assigning a name and ID.
void unregisterObject ()
Unregister the object from Sim.
void deleteObject ()
Unregister, mark as deleted, and free the object.
void safeDeleteObject ()
Performs a safe delayed delete of the object using a sim event.
Sets
The object must be properly registered before you can add/remove it to/from a set.
All these functions accept either a name or ID to identify the set you wish to operate on. Then they call addObject or removeObject on the set, which sets up appropriate notifications.
An object may be in multiple sets at a time.
bool addToSet (SimObjectId)
bool addToSet (const char *)
bool removeFromSet (SimObjectId)
bool removeFromSet (const char *)
Debugging
virtual String describeSelf () const
Return a textual description of the object.
void dumpToConsole (bool includeFunctions=true)
Dump the contents of this object to the console.
virtual void dumpClassHierarchy ()
added this so that you can print the entire class hierarchy, including script objects,
virtual void dumpGroupHierarchy ()
Print the SimGroup hierarchy of this object to the console.
Additional Inherited Members
Public Attributes inherited from EngineObject
DECLARE_INSTANTIABLE
Static Public Attributes inherited from ConsoleObject
static const bool __smIsDatablock = false
Subclasses of ConsoleObjects that are datablocks should redefine this static member variable and set it to true.
Protected Types inherited from EngineObject
typedef ::FalseType __IsDisposableType
typedef ::FalseType __IsSingletonType
Static Protected Member Functions inherited from EngineObject
static void * _allocateObject (size_t size, IEngineObjectPool *pool TORQUE_TMM_ARGS_DECL)
Detailed Description
Base class for objects involved in the simulation.
Introduction
SimObject is a base class for most of the classes you'll encounter working in Torque. It provides fundamental services allowing "smart" object referencing, creation, destruction, organization, and location. Along with SimEvent, it gives you a flexible event-scheduling system, as well as laying the foundation for the in-game editors, GUI system, and other vital subsystems.
Subclassing
You will spend a lot of your time in Torque subclassing, or working with subclasses of, SimObject. SimObject is designed to be easy to subclass.
You should not need to override anything in a subclass except:
The constructor/destructor.
processArguments()
onAdd()/onRemove()
onGroupAdd()/onGroupRemove()
onNameChange()
onStaticModified()
onDeleteNotify()
onEditorEnable()/onEditorDisable()
inspectPreApply()/inspectPostApply()
things from ConsoleObject (see ConsoleObject docs for specifics)
Of course, if you know what you're doing, go nuts! But in most cases, you shouldn't need to touch things not on that list.
When you subclass, you should define a typedef in the class, called Parent, that references the class you're inheriting from.
class mySubClass : public SimObject {
    typedef SimObject Parent;
    ...
Then, when you override a method, put in:
bool mySubClass::onAdd()
{
    if(!Parent::onAdd())
        return false;
    // ... do other things ...
}
Of course, you want to replace onAdd with the appropriate method call.
A SimObject's Life Cycle
SimObjects do not live apart. One of the primary benefits of using a SimObject is that you can uniquely identify it and easily find it (using its ID). Torque does this by keeping a global hierarchy of SimGroups - a tree - containing every registered SimObject. You can then query for a given object using Sim::findObject() (or SimSet::findObject() if you want to search only a specific set).
// Three examples of registering an object.
// Method 1:
AIClient *aiPlayer = new AIClient();
aiPlayer->registerObject();
// Method 2:
ActionMap* globalMap = new ActionMap;
globalMap->registerObject("GlobalActionMap");
// Method 3:
bool reg = mObj->registerObject(id);
Registering a SimObject performs these tasks:
Marks the object as not cleared and not removed.
Assigns the object a unique SimObjectID if it does not have one already.
Adds the object to the global name and ID dictionaries so it can be found again.
Calls the object's onAdd() method. Note: SimObject::onAdd() performs some important initialization steps. See here for details" on how to properly subclass SimObject.
If onAdd() fails (returns false), it calls unregisterObject().
Checks to make sure that the SimObject was properly initialized (and asserts if not).
Calling registerObject() and passing an ID or a name will cause the object to be assigned that name and/or ID before it is registered.
Congratulations, you have now registered your object! What now?
Well, hopefully, the SimObject will have a long, useful life. But eventually, it must die.
There are a two ways a SimObject can die.
First, the game can be shut down. This causes the root SimGroup to be unregistered and deleted. When a SimGroup is unregistered, it unregisters all of its member SimObjects; this results in everything that has been registered with Sim being unregistered, as everything registered with Sim is in the root group.
Second, you can manually kill it off, either by calling unregisterObject() or by calling deleteObject().
When you unregister a SimObject, the following tasks are performed:
The object is flagged as removed.
Notifications are cleaned up.
If the object is in a group, then it removes itself from the group.
Delete notifications are sent out.
Finally, the object removes itself from the Sim globals, and tells Sim to get rid of any pending events for it.
If you call deleteObject(), all of the above tasks are performed, in addition to some sanity checking to make sure the object was previously added properly, and isn't in the process of being deleted. After the object is unregistered, it deallocates itself.
Torque Editors
SimObjects are one of the building blocks for the in-game editors. They provide a basic interface for the editor to be able to list the fields of the object, update them safely and reliably, and inform the object things have changed.
This interface is implemented in the following areas:
onNameChange() is called when the object is renamed.
onStaticModified() is called whenever a static field is modified.
inspectPreApply() is called before the object's fields are updated, when changes are being applied.
inspectPostApply() is called after the object's fields are updated.
onEditorEnable() is called whenever an editor is enabled (for instance, when you hit F11 to bring up the world editor).
onEditorDisable() is called whenever the editor is disabled (for instance, when you hit F11 again to close the world editor).
(Note: you can check the variable gEditingMission to see if the mission editor is running; if so, you may want to render special indicators. For instance, the fxFoliageReplicator renders inner and outer radii when the mission editor is runnning.)
The Console
SimObject extends ConsoleObject by allowing you to to set arbitrary dynamic fields on the object, as well as statically defined fields. This is done through two methods, setDataField and getDataField, which deal with the complexities of allowing access to two different types of object fields.
Static fields take priority over dynamic fields. This is to be expected, as the role of dynamic fields is to allow data to be stored in addition to the predefined fields.
The fields in a SimObject are like properties (or fields) in a class.
Some fields may be arrays, which is what the array parameter is for; if it's non-null, then it is parsed with dAtoI and used as an index into the array. If you access something as an array which isn't, then you get an empty string.
You don't need to read any further than this. Right now, set/getDataField are called a total of 6 times through the entire Torque codebase. Therefore, you probably don't need to be familiar with the details of accessing them. You may want to look at Con::setData instead. Most of the time you will probably be accessing fields directly, or using the scripting language, which in either case means you don't need to do anything special.
The functions to get/set these fields are very straightforward:
setDataField(StringTable->insert("locked", false), NULL, b ? "true" : "false");
curObject->setDataField(curField, curFieldArray, STR.getStringValue());
setDataField(slotName, array, value);
For advanced users: There are two flags which control the behavior of these functions. The first is ModStaticFields, which controls whether or not the DataField functions look through the static fields (defined with addField; see ConsoleObject for details) of the class. The second is ModDynamicFields, which controls dynamically defined fields. They are set automatically by the console constructor code.
Member Typedef Documentation
typedef ConsoleObject SimObject::Parent
Member Enumeration Documentation
enum SimObject::WriteFlags
Flags passed to SimObject::write.
Enumerator
SelectedOnly
Indicates that only objects marked as selected should be outputted. Used in SimSet.
NoName
Indicates that the object name should not be saved.
IgnoreCanSave
Write out even if CannotSave=true.
Constructor & Destructor Documentation
SimObject::SimObject ()
Referenced by getDeclarationLine().
virtual SimObject::~SimObject () virtual
Referenced by getDeclarationLine().
Member Function Documentation
static SimObject* SimObject::__findObject (const char * id) inline static
References Sim::findObject().
static const char* SimObject::__getObjectId (ConsoleObject * object) inline static
References destroySelf(), getIdString(), getName(), and object.
virtual void SimObject::_destroySelf () protected virtual
Subclasses should overload this method instead of the public destroySelf().
Reimplemented from EngineObject.
virtual String SimObject::_getLogMessage (const char * fmt, va_list args) const protected virtual
We can provide more detail, like object name and id.
Reimplemented from ConsoleObject.
Referenced by _onUnselected().
virtual void SimObject::_onSelected () inline protected virtual
Called when the object is selected in the editor.
Reimplemented in ScatterSky, Sun, and LightBase.
virtual void SimObject::_onUnselected () inline protected virtual
Called when the object is unselected in the editor.
Reimplemented in ScatterSky, Sun, and LightBase.
References _getLogMessage(), and DEFINE_CREATE_METHOD.
static bool SimObject::_setPersistentID (void * object, const char * index, const char * data) static protected
bool SimObject::addToSet (SimObjectId)
Referenced by isHidden().
bool SimObject::addToSet (const char *)
void SimObject::assignDynamicFieldsFrom (SimObject * obj)
Copy dynamic fields from another object onto this one.
Everything from obj will overwrite what's in this object.
Parameters
obj Object to copy from.
Referenced by getCopySource().
void SimObject::assignFieldsFrom (SimObject * obj)
Copy fields from another object onto this one.
Objects must be of same type. Everything from obj will overwrite what's in this object; extra fields in this object will remain. This includes dynamic fields.
Parameters
obj Object to copy from.
Referenced by getCopySource().
void SimObject::assignName (const char * name)
Assign the given name to this object.
Referenced by SimGroup::addObject(), and getGroup().
bool SimObject::canModDynamicFields () inline
References BitSet32::test().
bool SimObject::canModStaticFields () inline
References BitSet32::test().
void SimObject::clearAllNotifications ()
Remove all notifications for this object.
Referenced by onEditorDisable().
void SimObject::clearNotify (SimObject * obj)
Notify an object when we are cleared.
Referenced by onEditorDisable().
virtual SimObject* SimObject::clone () virtual
Return a shallow copy of this object.
Reimplemented in SimGroup, and SimSet.
virtual void SimObject::copyTo (SimObject * object) virtual
Copy SimObject to another SimObject (Originally designed for T2D).
Reimplemented in AssetBase, ShapeAsset, ComponentAsset, GameObjectAsset, and ExampleAsset.
Referenced by getPersistentId().
SimObject::DECLARE_CONOBJECT (SimObject)
Referenced by getConsoleMethodData().
virtual SimObject* SimObject::deepClone () virtual
Return a deep copy of this object.
Reimplemented in SimGroup.
void SimObject::deleteNotify (SimObject * obj)
Notify an object when we are deleted.
Referenced by onEditorDisable().
void SimObject::deleteObject ()
Unregister, mark as deleted, and free the object.
Referenced by onEditorDisable(), and Taml::read().
virtual String SimObject::describeSelf () const virtual
Return a textual description of the object.
Reimplemented from EngineObject.
Reimplemented in NetObject, Portal, SceneSimpleZone, and SceneRootZone.
Referenced by getPersistentId().
virtual void SimObject::destroySelf () virtual
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
Reimplemented from EngineObject.
Referenced by __getObjectId().
virtual void SimObject::dumpClassHierarchy () virtual
added this so that you can print the entire class hierarchy, including script objects,
Print the AbstractClassRep hierarchy of this object to the console.
Referenced by getPersistentId().
virtual void SimObject::dumpGroupHierarchy () virtual
Print the SimGroup hierarchy of this object to the console.
Referenced by getPersistentId().
void SimObject::dumpToConsole (bool includeFunctions = true)
Dump the contents of this object to the console.
Use the Torque Script dump() and dumpF() functions to call this.
Referenced by getPersistentId().
virtual SimObject* SimObject::findObject (const char * name) virtual
Find a named sub-object of this object.
This is subclassed in the SimGroup and SimSet classes.
For a single object, it just returns NULL, as normal objects cannot have children.
Reimplemented in SimGroup, and SimSet.
Referenced by onEditorDisable().
bool SimObject::getCanSave () const inline
Returns boolean specifying if the object can be serialized.
References BitSet32::test().
bool SimObject::getCanSaveDynamicFields () inline
Get whether fields created at runtime should be saved. Default is true.
References mCanSaveFieldDictionary.
StringTableEntry SimObject::getClassNamespace () const inline
Return name of class namespace set on this object.
References mClassName.
virtual StringTableEntry SimObject::getComponentName () inline virtual
Reimplemented in ComponentAsset.
References ConsoleObject::getClassName(), and setInternalName().
virtual void SimObject::getConsoleMethodData (const char * fname, S32 routingId, S32 * type, S32 * minArgs, S32 * maxArgs, void ** callback, const char ** usage) inline virtual
References DECLARE_CONOBJECT().
SimObject* SimObject::getCopySource () const inline
Return the object that this object is copying fields from.
References assignDynamicFieldsFrom(), assignFieldsFrom(), and setCopySource().
const char* SimObject::getDataField (StringTableEntry slotName, const char * array)
Get the value of a field on the object.
See here for a detailed discussion of what this function does.
Parameters
slotName Field to access.
array String containing index into array (if field is an array); if NULL, it is ignored.
StringTableEntry SimObject::getDataFieldPrefix (StringTableEntry fieldName)
U32 SimObject::getDataFieldType (StringTableEntry slotName, const char * array)
Get the type of a field on the object.
Parameters
slotName Field to access.
array String containing index into array (if field is an array); if NULL, it is ignored.
S32 SimObject::getDeclarationLine () const inline
Get the declaration line number.
References isField(), isMethod(), onAdd(), onGroupAdd(), onGroupRemove(), onNameChange(), onRemove(), processArguments(), save(), SimObject(), and ~SimObject().
SimFieldDictionary* SimObject::getFieldDictionary () inline
Get reference to the dictionary containing dynamic fields.
See here for a detailed discussion of what this function does.
This dictionary can be iterated over using a SimFieldDictionaryIterator.
StringTableEntry SimObject::getFilename () const inline
Get the filename.
References setDeclarationLine().
SimGroup* SimObject::getGroup () const inline
Return the SimGroup that this object is contained in.
Never NULL except for RootGroup and unregistered objects.
References assignName(), and setId().
Referenced by SettingSaveNode::~SettingSaveNode().
SimObjectId SimObject::getId () const inline
Return the unique numeric object ID.
References mId.
Referenced by AssetManager::acquireAsset(), and SimDataBlock::isClientOnly().
const char* SimObject::getIdString () const inline
Return the object ID as a string.
Referenced by __getObjectId().
StringTableEntry SimObject::getInternalName () const inline
Get the internal name of this control.
References mInternalName, and setOriginalName().
Referenced by TerrainFile::getMaterialName().
StringTableEntry SimObject::getName () const inline
Return the name of this object.
Referenced by __getObjectId(), and TamlWriteNode::set().
Namespace* SimObject::getNamespace () inline
Return the object's namespace.
References mNameSpace, and tabComplete().
SimPersistID* SimObject::getOrCreatePersistentId ()
Return the persistent ID assigned to this object or assign one to it if it has none.
Referenced by getPersistentId().
StringTableEntry SimObject::getOriginalName () const inline
Get the original name of this control.
References setFilename().
SimPersistID* SimObject::getPersistentId () const inline
Return the persistent ID assigned to this object or NULL.
References copyTo(), describeSelf(), dumpClassHierarchy(), dumpGroupHierarchy(), dumpToConsole(), getOrCreatePersistentId(), initPersistFields(), and mPersistentId.
const char* SimObject::getPrefixedDataField (StringTableEntry fieldName, const char * array)
const char* SimObject::getPrefixedDynamicDataField (StringTableEntry fieldName, const char * array, const S32 fieldType = -1)
StringTableEntry SimObject::getProgenitorFile (void) const inline
StringTableEntry SimObject::getSuperClassNamespace () const inline
Return name of superclass namespace set on this object.
References mSuperClassName, setClassNamespace(), and setSuperClassNamespace().
virtual bool SimObject::handlesConsoleMethod (const char * fname, S32 * routingId) inline virtual
object SimObject::incRefCount () protected
Referenced by Message::addReference().
static void SimObject::initPersistFields () static
Referenced by getPersistentId().
virtual void SimObject::inspectPostApply () virtual
Called after any property of the object is changed in the world editor.
See also
inspectPreApply
Reimplemented in GuiControl, SceneObject, ShapeBaseImageData, TerrainBlock, MeshRoad, River, Material, SFXPlayList, GuiMLTextCtrl, Precipitation, GameBase, NavMesh, fxFoliageReplicator, PhysicsShape, SFXEmitter, TSStatic, VolumetricFog, CameraBookmark, ForestWindEmitter, SFXDescription, DecalRoad, GuiBitmapButtonCtrl, Forest, ConvexShape, WaterObject, GuiAutoScrollCtrl, GuiGradientCtrl, Marker, SpawnSphere, GroundCover, Trigger, CollisionComponent, MeshComponent, WaterBlock, LevelInfo, DecalData, WaterPlane, Sun, WayPoint, OpenVRTrackedObject, SFXAmbience, fxShapeReplicator, GuiIconButtonCtrl, NavPath, CollisionTrigger, LightBase, LightAnimData, RenderMeshExample, GameBaseData, CoverPoint, SFXTrack, RenderShapeExample, LightFlareData, ScatterSky, LightDescription, SkyBox, ParticleEmitterNode, AccumulationVolume, MissionMarker, TSForestItemData, TimeOfDay, GuiTextCtrl, CloudLayer, PhysicalZone, GroundPlane, GuiMessageVectorCtrl, RibbonNode, BasicClouds, Prefab, GuiBitmapCtrl, SFXEnvironment, MissionArea, GuiToolboxButtonCtrl, GuiControlArrayControl, GuiMaterialCtrl, GuiDynamicCtrlArrayControl, and GuiTabPageCtrl.
Referenced by onPostAdd().
virtual void SimObject::inspectPreApply () virtual
Called before any property of the object is changed in the world editor.
The calling order here is:
inspectPreApply()
...
calls to setDataField()
...
inspectPostApply()
Reimplemented in GuiControl, and GuiGradientCtrl.
Referenced by onPostAdd().
bool SimObject::isAutoDeleted () const inline
References setSelected(), and BitSet32::test().
bool SimObject::isChildOfGroup (SimGroup * pGroup)
Referenced by setForcedId().
bool SimObject::isDeleted () const inline
References BitSet32::test().
bool SimObject::isEditorOnly () const inline
References BitSet32::test().
bool SimObject::isExpanded () const inline
References BitSet32::test().
virtual bool SimObject::isField (const char * fieldName, bool includeStatic = true, bool includeDynamic = true) virtual
Return true if the field is defined on the object.
Referenced by getDeclarationLine().
virtual bool SimObject::isHidden () const inline virtual
Reimplemented in GuiControl.
References addToSet(), readObject(), removeFromSet(), setHidden(), BitSet32::test(), write(), writeField(), writeFields(), and writeObject().
virtual bool SimObject::isLocked () const inline virtual
References setLocked(), and BitSet32::test().
virtual bool SimObject::isMethod (const char * methodName) virtual
Check if a method exists in the objects current namespace.
Referenced by getDeclarationLine(), UndoScriptAction::onAdd(), and UndoScriptAction::onRemove().
bool SimObject::isNameChangeAllowed () const inline
References BitSet32::test().
bool SimObject::isProperlyAdded () const inline
References BitSet32::test().
Referenced by AssetPtrBase::registerRefreshNotify(), and AssetPtrBase::unregisterRefreshNotify().
bool SimObject::isRemoved () const inline
References BitSet32::test().
bool SimObject::isSelected () const inline
References BitSet32::test().
Referenced by GuiTreeViewCtrl::isSelected().
bool SimObject::isSelectedRecursive () const
Returns true if this object is selected or any group it is a member of is.
Referenced by setCanSave().
void SimObject::linkNamespaces () protected
Perform namespace linking on this object.
virtual bool SimObject::onAdd () virtual
Called when the object is added to the sim.
Reimplemented in ShapeBase, Player, SceneObject, SFXSource, GuiTreeViewCtrl, GuiControl, GuiControlProfile, ShapeBaseImageData, GuiInspectorTypeBitMask32, TerrainEditor, MeshRoad, WorldEditor, River, Material, GuiCursor, GuiEditCtrl, GuiGameListMenuProfile, GuiMLTextCtrl, NetObject, PostEffect, PersistenceManager, TerrainBlock, Vehicle, AITurretShape, GameBase, RigidShape, fxFoliageReplicator, Precipitation, GameConnection, PhysicsShape, Camera, WheeledVehicle, SFXEmitter, UndoScriptAction, ParticleEmitter, SimResponseCurve, TSShapeConstructor, GuiCanvas, ForestWindEmitter, NavMesh, CameraBookmark, VolumetricFog, Gizmo, FlyingVehicle, SFXDescription, GuiInspectorField, Projectile, GuiRolloutCtrl, TurretShape, PlayerControllerComponent, Item, Splash, DecalRoad, SFXParameter, ConvexShape, Explosion, Lightning, Forest, WaterObject, AIPlayer, ModuleManager, SFXFMODProject, GuiGradientCtrl, RigidBodyComponent, SFXFMODEventGroup, SFXProfile, Debris, SpawnSphere, AITurretShapeData, HoverVehicle, SimDataBlock, Taml, GuiPopUpMenuCtrlEx, GuiPopUpMenuCtrl, PhysicsDebris, ShaderData, GroundCover, TSStatic, EditTSCtrl, SplashData, Marker, Trigger, MeshComponent, ExplosionData, LevelInfo, SFXFMODEvent, GuiGameListMenuCtrl, GuiGameListOptionsCtrl, AssetManager, GuiMissionAreaCtrl, OpenVRTrackedObject, WayPoint, ForestItemData, WaterBlock, ForestBrush, UInputManager, Message, GuiFrameSetCtrl, Sun, GuiTextEditCtrl, ProximityMine, DecalData, SFXState, SFXAmbience, fxShapeReplicator, Ribbon, WaterPlane, PathCamera, CollisionTrigger, RenderMeshExample, NavPath, LightBase, DInputManager, RenderObjectExample, TCPObject, GameBaseData, MessageVector, ParticleData, ScenePolyhedralObject< SceneSimpleZone >, ScenePolyhedralObject< SceneSpace >, DebrisData, PhysicsDebrisData, ScriptGroup, CoverPoint, LeapMotionFrame, RenderShapeExample, AnimationComponent, RazerHydraFrame, Component, RenderFormatToken, SFXTrack, LightDescription, GizmoProfile, TimeOfDay, CameraComponent, TerrainMaterial, SkyBox, ParticleEmitterNode, RenderTexTargetBinManager, AccumulationVolume, TSForestItemData, ScatterSky, LightningData, Entity, MissionMarker, StaticShape, OpenVROverlay, ScenePolyhedralZone, PhysicalZone, CloudLayer, GuiRiverEditorCtrl, GuiSplitContainer, GuiTerrPreviewCtrl, PopupMenu, RibbonNode, OcclusionVolume, ScriptMsgListener, BasicClouds, ScriptTickObject, GuiInspectorGroup, SceneSpace, GuiMessageVectorCtrl, ForestBrushTool, GameTSCtrl, GroundPlane, PhysicsShapeData, GuiMeshRoadEditorCtrl, GuiNavEditorCtrl, Prefab, ProjectileData, GuiInspectorNodeListField, SimPath::Path, GuiRoadEditorCtrl, GuiTextCtrl, SFXEnvironment, ParticleEmitterData, SimXMLDocument, ForestEditorCtrl, CustomMaterial, GuiConvexEditorCtrl, CameraOrbiterComponent, guiAnimBitmapCtrl, SceneRootZone, MissionArea, StreamObject, CubemapData, GuiDecalEditorCtrl, PhysicsForce, ActionMap, StateMachineComponent, GuiInspectorEntityGroup, EditManager, GuiInspectorCustomField, GuiInspectorComponentGroup, GuiInspectorVariableField, FileStreamObject, GuiInspectorDynamicField, GuiMissionAreaEditorCtrl, RibbonData, GFXStateBlockData, RigidShapeData, ScriptObject, TriggerComponent, OpenVRTrackedObjectData, ParticleEmitterNodeData, VehicleBlocker, HoverVehicleData, and GuiOffscreenCanvas.
Referenced by getDeclarationLine(), and UndoScriptAction::onAdd().
virtual void SimObject::onDeleteNotify (SimObject * object) virtual
Called when a SimObject is deleted.
When you are on the notification list for another object and it is deleted, this method is called.
Reimplemented in ShapeBase, SceneObject, SFXSource, GuiControl, GuiControlProfile, TerrainEditor, SimSet, ForestWindEmitter, Camera, SFXSound, ModuleManager, Trigger, UInputManager, NavPath, CollisionTrigger, DInputManager, CompoundUndoAction, and GuiInspector.
Referenced by onPostAdd(), and Camera::setOffset().
virtual void SimObject::onDynamicModified (const char * slotName, const char * newValue = NULL) virtual
Called when a dynamic field is modified.
Reimplemented in Component, MeshComponent, and StateMachineComponent.
Referenced by onPostAdd().
virtual void SimObject::onEditorDisable () inline virtual
Called when the editor is deactivated.
Reimplemented in MeshRoad, TerrainBlock, Camera, ForestWindEmitter, NavMesh, DecalRoad, Marker, NavPath, PathCamera, CoverPoint, SceneSpace, MissionMarker, Prefab, and GuiDecalEditorCtrl.
References clearAllNotifications(), clearNotify(), deleteNotify(), deleteObject(), findObject(), processDeleteNotifies(), SimObject::Notify::ptr, registerObject(), registerReference(), removeNotify(), safeDeleteObject(), unregisterObject(), and unregisterReference().
Referenced by Camera::getValidEditOrbitPoint().
virtual void SimObject::onEditorEnable () inline virtual
Called when the editor is activated.
Reimplemented in MeshRoad, WorldEditor, TerrainBlock, Camera, ForestWindEmitter, NavMesh, DecalRoad, Marker, NavPath, PathCamera, CoverPoint, SceneSpace, MissionMarker, and Prefab.
Referenced by Camera::getValidEditOrbitPoint().
virtual void SimObject::onGroupAdd () virtual
Called when the object is added to a SimGroup.
Reimplemented in SFXSource, CameraBookmark, and Marker.
Referenced by getDeclarationLine().
virtual void SimObject::onGroupRemove () virtual
Called when the object is removed from a SimGroup.
Reimplemented in GuiControl, and CameraBookmark.
Referenced by getDeclarationLine().
virtual void SimObject::onNameChange (const char * name) virtual
Called when the object's name is changed.
Reimplemented in ForestItemData.
Referenced by getDeclarationLine().
virtual void SimObject::onPostAdd () inline virtual
Called when the adding of the object to the sim is complete, all sub-objects have been processed as well.
Reimplemented in Entity.
References inspectPostApply(), inspectPreApply(), onDeleteNotify(), onDynamicModified(), and onStaticModified().
virtual void SimObject::onRemove () virtual
Called when the object is removed from the sim.
Reimplemented in ShapeBase, Player, SceneObject, SFXSource, NetConnection, GuiControl, SimGroup, MeshRoad, River, Material, GuiCursor, GuiEditCtrl, NetObject, PostEffect, PersistenceManager, TerrainBlock, SimSet, Vehicle, AITurretShape, GameBase, RigidShape, fxFoliageReplicator, Precipitation, GameConnection, PhysicsShape, UndoScriptAction, Camera, WheeledVehicle, SFXEmitter, ParticleEmitter, SimResponseCurve, GuiCanvas, ForestWindEmitter, NavMesh, CameraBookmark, VolumetricFog, Gizmo, FlyingVehicle, Projectile, TurretShape, PlayerControllerComponent, Item, Splash, DecalRoad, SFXSound, SFXParameter, ConvexShape, Explosion, Lightning, Forest, WaterObject, AIPlayer, ModuleManager, SFXFMODProject, RigidBodyComponent, SFXFMODEventGroup, SFXProfile, Debris, HoverVehicle, Taml, PhysicsDebris, ShaderData, GroundCover, Ribbon, TSStatic, EditTSCtrl, Marker, Trigger, MeshComponent, LevelInfo, SFXFMODEvent, AssetManager, OpenVRTrackedObject, WaterBlock, UInputManager, Message, Sun, ProximityMine, GuiTextListCtrl, DecalData, fxShapeReplicator, WaterPlane, PathCamera, CollisionTrigger, RenderMeshExample, NavPath, LightBase, DInputManager, RenderObjectExample, MessageVector, ScriptGroup, CoverPoint, LeapMotionFrame, RenderShapeExample, AnimationComponent, RazerHydraFrame, Component, RenderFormatToken, TimeOfDay, CameraComponent, SkyBox, ParticleEmitterNode, AccumulationVolume, ScatterSky, TSForestItemData, Entity, MissionMarker, FieldBrushObject, StaticShape, OpenVROverlay, PhysicalZone, CloudLayer, PopupMenu, RibbonNode, ScriptMsgListener, BasicClouds, ScriptTickObject, SceneSpace, GuiMessageVectorCtrl, VolumetricFogRTManager, ForestBrushTool, GroundPlane, PhysicsShapeData, Prefab, SimPath::Path, SimXMLDocument, CustomMaterial, RenderBinManager, GuiConvexEditorCtrl, CameraOrbiterComponent, SceneRootZone, MissionArea, PhysicsForce, GuiInspector, StateMachineComponent, ScriptObject, TriggerComponent, VehicleBlocker, and GuiOffscreenCanvas.
Referenced by getDeclarationLine(), Player::getMaxForwardVelocity(), Camera::getValidEditOrbitPoint(), and UndoScriptAction::onRemove().
virtual void SimObject::onStaticModified (const char * slotName, const char * newValue = NULL) virtual
Specifically, these are called by setDataField when a static or dynamic field is modified, see the console details.
Called when a static field is modified.
Reimplemented in GuiControlProfile, MeshRoad, River, SFXEmitter, Entity, Component, DecalRoad, GuiTextEditCtrl, SimDataBlock, WaterBlock, WaterPlane, GuiIconButtonCtrl, DecalData, SkyBox, and StateMachineComponent.
Referenced by onPostAdd().
virtual void SimObject::onTamlAddParent (SimObject * pParentObject) inline protected virtual
Called after Taml has finished reading the object and has added the object to any parent.
Implements TamlCallbacks.
virtual void SimObject::onTamlCustomRead (const TamlCustomNodes & customNodes) protected virtual
Called during the reading of the object to allow custom properties to be read.
Implements TamlCallbacks.
Reimplemented in AssetTagsManifest, and AssetQuery.
Referenced by onTamlCustomWrite().
virtual void SimObject::onTamlCustomWrite (TamlCustomNodes & customNodes) inline protected virtual
Called during the writing of the object to allow custom properties to be written.
Implements TamlCallbacks.
Reimplemented in AssetTagsManifest, and AssetQuery.
References onTamlCustomRead().
virtual void SimObject::onTamlPostRead (const TamlCustomNodes & customNodes) inline protected virtual
Called after Taml has finished reading the object.
The custom properties is additionally passed here for object who want to process it at the end of reading.
Implements TamlCallbacks.
virtual void SimObject::onTamlPostWrite (void) inline protected virtual
Called after Taml has finished writing the object.
Implements TamlCallbacks.
virtual void SimObject::onTamlPreRead (void) inline protected virtual
Called prior to Taml reading the object.
Implements TamlCallbacks.
virtual void SimObject::onTamlPreWrite (void) inline protected virtual
Taml callbacks.
Implements TamlCallbacks.
virtual bool SimObject::processArguments (S32 argc, ConsoleValueRef * argv) virtual
Process constructor options. (ie, new SimObject(1,2,3))
Reimplemented in SimGroup, SFXSource, GuiControl, WaterObject, TCPObject, ConsoleLogger, SimPersistSet, SimXMLDocument, and SFXTrack.
Referenced by getDeclarationLine().
void SimObject::processDeleteNotifies ()
Send out deletion notifications.
Referenced by onEditorDisable().
virtual bool SimObject::readObject (Stream * stream) virtual
Reimplemented in SimSet.
Referenced by isHidden().
object SimObject::registerObject () protected
Referenced by DecalData::getSet(), and onEditorDisable().
bool SimObject::registerObject ()
Register an object with the object system.
This must be called if you want to keep the object around. In the rare case that you will delete the object immediately, or don't want to be able to use Sim::findObject to locate it, then you don't need to register it.
registerObject adds the object to the global ID and name dictionaries, after first assigning it a new ID number. It calls onAdd(). If onAdd fails, it unregisters the object and returns false.
If a subclass's onAdd doesn't eventually call SimObject::onAdd(), it will cause an assertion.
bool SimObject::registerObject (U32 id)
Register the object, forcing the id.
See also
registerObject()
Parameters
id ID to assign to the object.
bool SimObject::registerObject (const char * name)
Register the object, assigning the name.
See also
registerObject()
Parameters
name Name to assign to the object.
bool SimObject::registerObject (const char * name, U32 id)
Register the object, assigning a name and ID.
See also
registerObject()
Parameters
name Name to assign to the object.
id ID to assign to the object.
void SimObject::registerReference (SimObject ** obj)
Register a reference to this object.
You pass a pointer to your reference to this object.
When the object is deleted, it will null your pointer, ensuring you don't access old memory.
Parameters
obj Pointer to your reference to the object.
Referenced by onEditorDisable().
bool SimObject::removeFromSet (SimObjectId)
Referenced by isHidden().
bool SimObject::removeFromSet (const char *)
Notify* SimObject::removeNotify (void * ptr, Notify::Type)
Remove a notification from the list.
Referenced by onEditorDisable().
void SimObject::safeDeleteObject ()
Performs a safe delayed delete of the object using a sim event.
Referenced by onEditorDisable().
virtual bool SimObject::save (const char * pcFilePath, bool bOnlySelected = false, const char * preappend = NULL) virtual
Save object as a TorqueScript File.
Referenced by getDeclarationLine().
void SimObject::setAutoDelete (bool val) inline
References BitSet32::clear(), and BitSet32::set().
virtual void SimObject::setCanSave (bool val) inline virtual
Set serialization flag.
Reimplemented in WorldEditorSelection.
References BitSet32::clear(), isSelectedRecursive(), and BitSet32::set().
void SimObject::setCanSaveDynamicFields (bool bCanSave) inline
Set whether fields created at runtime should be saved. Default is true.
void SimObject::setClassNamespace (const char * classNamespace)
Referenced by getSuperClassNamespace().
void SimObject::setCopySource (SimObject * object)
Set the object that this object should be copying fields from.
Referenced by getCopySource().
void SimObject::setDataField (StringTableEntry slotName, const char * array, const char * value)
Set the value of a field on the object.
See here for a detailed discussion of what this function does.
Parameters
slotName Field to access.
array String containing index into array; if NULL, it is ignored.
value Value to store.
void SimObject::setDataFieldType (const U32 fieldTypeId, StringTableEntry slotName, const char * array)
Set the type of a dynamic field on the object.
Parameters
typeName/Id Console base type name/id to assign to a dynamic field.
slotName Field to access.
array String containing index into array (if field is an array); if NULL, it is ignored.
void SimObject::setDataFieldType (const char * typeName, StringTableEntry slotName, const char * array)
void SimObject::setDeclarationLine (U32 lineNumber)
These functions are used to track the line number (1-based) on which the object was created if it was loaded from script.
Set the declaration line number
Referenced by getFilename().
void SimObject::setEditorOnly (bool val) inline
References BitSet32::clear(), and BitSet32::set().
void SimObject::setExpanded (bool exp) inline
References BitSet32::clear(), and BitSet32::set().
void SimObject::setFilename (const char * file)
These functions allow you to set and access the filename where this object was created.
Set the filename
Referenced by getOriginalName().
static void SimObject::setForcedId (SimObjectId id) inline static
Force an Id on the next registered object.
References isChildOfGroup().
virtual void SimObject::setHidden (bool b) virtual
Reimplemented in ShapeBase, SceneObject, GuiControl, and WayPoint.
Referenced by isHidden().
void SimObject::setId (SimObjectId id)
Referenced by getGroup().
void SimObject::setInternalName (const char * newname)
These functions support internal naming that is not namespace bound for locating child controls in a generic way.
Set the internal name of this control (Not linked to a namespace)
Referenced by getComponentName().
virtual void SimObject::setLocked (bool b) virtual
Reimplemented in ModuleDefinition.
Referenced by isLocked().
void SimObject::setModDynamicFields (bool dyn) inline
References BitSet32::clear(), and BitSet32::set().
void SimObject::setModStaticFields (bool sta) inline
References BitSet32::clear(), and BitSet32::set().
void SimObject::setNameChangeAllowed (bool val) inline
References BitSet32::clear(), and BitSet32::set().
void SimObject::setOriginalName (const char * originalName)
Set the original name of this control.
Referenced by getInternalName().
void SimObject::setPrefixedDataField (StringTableEntry fieldName, const char * array, const char * value)
void SimObject::setPrefixedDynamicDataField (StringTableEntry fieldName, const char * array, const char * value, const S32 fieldType = -1)
void SimObject::setProgenitorFile (const char * pFile) inline
void SimObject::setSelected (bool sel)
Referenced by isAutoDeleted().
void SimObject::setSuperClassNamespace (const char * superClassNamespace)
Referenced by getSuperClassNamespace().
const char* SimObject::tabComplete (const char * prevText, S32 baseLen, bool)
Get next matching item in namespace.
This wraps a call to Namespace::tabComplete; it gets the next thing in the namespace, given a starting value and a base length of the string. See Namespace::tabComplete for details.
Referenced by getNamespace().
void SimObject::unlinkNamespaces () protected
Undo namespace linking on this object.
void SimObject::unregisterObject ()
Unregister the object from Sim.
This performs several operations:
Sets the removed flag.
Call onRemove()
Clear out notifications.
Remove the object from...
its group, if any. (via getGroup)
Sim::gNameDictionary
Sim::gIDDictionary
Finally, cancel any pending events for this object (as it can't receive them now).
Referenced by onEditorDisable().
void SimObject::unregisterReference (SimObject ** obj)
Unregister a reference to this object.
Remove a reference from the list, so that it won't get nulled inappropriately.
Call this when you're done with your reference to the object, especially if you're going to free the memory. Otherwise, you may erroneously get something overwritten.
See also
registerReference
Referenced by onEditorDisable().
virtual void SimObject::write (Stream & stream, U32 tabStop, U32 flags = 0) virtual
Output the TorqueScript to recreate this object.
This calls writeFields internally.
Parameters
stream Stream to output to.
tabStop Indentation level for this object.
flags If SelectedOnly is passed here, then only objects marked as selected (using setSelected) will output themselves.
Reimplemented in GuiControl, SimSet, Entity, NavMesh, SimDataBlock, and SimPersistSet.
Referenced by isHidden().
virtual bool SimObject::writeField (StringTableEntry fieldname, const char * value) virtual
Determine whether or not a field should be written.
Parameters
fiedname The name of the field being written.
value The value of the field.
Reimplemented in SceneObject, MeshRoad, River, Material, SceneZoneSpace, TSShapeConstructor, Portal, DecalRoad, ConvexShape, ScenePolyhedralObject< SceneSimpleZone >, and ScenePolyhedralObject< SceneSpace >.
Referenced by isHidden().
virtual void SimObject::writeFields (Stream & stream, U32 tabStop) virtual
Write the fields of this object in TorqueScript.
Parameters
stream Stream for output.
tabStop Indentation level for the fields.
Reimplemented in MeshRoad, River, DecalRoad, ConvexShape, ScenePolyhedralObject< SceneSimpleZone >, and ScenePolyhedralObject< SceneSpace >.
Referenced by isHidden().
virtual bool SimObject::writeObject (Stream * stream) virtual
Reimplemented in SimSet.
Referenced by isHidden().
Member Data Documentation
SimObject::DEFINE_CREATE_METHOD protected
Initial value:
{
         T* object = new T
Referenced by _onUnselected().
bool SimObject::mCanSaveFieldDictionary protected
Whether dynamic fields should be saved out in serialization. Defaults to true.
Referenced by getCanSaveDynamicFields().
StringTableEntry SimObject::mClassName protected
Name of namespace to use as class namespace.
Referenced by getClassNamespace().
SimObjectId SimObject::mId protected
Id number for this object.
Referenced by SimGroup::addObject(), and getId().
StringTableEntry SimObject::mInternalName protected
Internal name assigned to the object. Not set by default.
Referenced by getInternalName().
Namespace* SimObject::mNameSpace protected
The namespace in which method lookup for this object begins.
Referenced by getNamespace().
SimPersistID* SimObject::mPersistentId protected
Persistent ID assigned to this object.
Allows to unambiguously refer to this object in serializations regardless of stream object ordering.
Referenced by getPersistentId().
StringTableEntry SimObject::mSuperClassName protected
Name of namespace to use as class super namespace.
Referenced by getSuperClassNamespace().
return SimObject::object protected
Referenced by __getObjectId(), RenderPassStateBin::_getStateToken(), GuiControl::_setActive(), GuiProgressBitmapCtrl::_setBitmap(), RenderPassStateBin::_setStateToken(), GuiSliderCtrl::_setValue(), GuiControl::_setVisible(), sgSceneLightingProcessEvent::process(), FieldBrushObject::setDescription(), GuiContainer::setDockingField(), GuiRolloutCtrl::setExpanded(), WorldEditor::setObjectsUseBoxCenter(), FieldBrushObject::setSortName(), and GuiTextCtrl::setText().
SimObjectId SimObject::smForcedId static protected
The Id to force upon the object. Poor object.
bool SimObject::smForceId static protected
Force a registered object to use the given Id. Cleared upon use.
Copyright © GarageGames, LLC. All Rights Reserved.