GFXCubemap Class Reference
Main Modules Class List Namespace List Online
GFXCubemap Class Reference abstract
#include <gfx/gfxCubemap.h>
Public Member Functions
virtual ~GFXCubemap ()
virtual const String describeSelf () const
The resource should put a description of itself (number of vertices, size/width of texture, etc.) in buffer.
virtual GFXFormat getFormat () const =0
Returns the face texture format.
const String & getPath () const
Returns the cubemap file path set at creation.
virtual U32 getSize () const =0
Returns the size of the faces.
virtual void initDynamic (U32 texSize, GFXFormat faceFormat=GFXFormatR8G8B8A8)=0
void initNormalize (U32 size)
virtual void initStatic (GFXTexHandle *faces)=0
Create a static cubemap from a list of 6 face textures.
virtual void initStatic (DDSFile *dds)=0
Create a static cubemap from a DDS cubemap file.
Public Member Functions inherited from StrongRefBase
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Public Member Functions inherited from GFXResource
GFXResource ()
virtual ~GFXResource ()
void clearFlag ()
GFXResource * getNextResource () const
GFXDevice * getOwningDevice () const
GFXResource * getPrevResource () const
bool isFlagged ()
void registerResourceWithDevice (GFXDevice *device)
Registers this resource with the given device.
virtual void resurrect ()=0
When called the resource should restore all device sensitive information destroyed by zombify()
void setFlag ()
virtual void zombify ()=0
When called the resource should destroy all device sensitive information (e.g. D3D resources in D3DPOOL_DEFAULT.
Protected Member Functions
void _setPath (const String &path)
Sets the cubemap file path.
virtual void setToTexUnit (U32 tuNum)=0
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Protected Attributes
String mPath
The path to the cubemap file.
Protected Attributes inherited from StrongRefBase
U32 mRefCount
reference counter for StrongRefPtr objects
Constructor & Destructor Documentation
virtual GFXCubemap::~GFXCubemap () virtual
Referenced by _setPath().
Member Function Documentation
void GFXCubemap::_setPath (const String & path) inline protected
Sets the cubemap file path.
References getFormat(), getSize(), initDynamic(), initNormalize(), initStatic(), and ~GFXCubemap().
virtual const String GFXCubemap::describeSelf () const virtual
The resource should put a description of itself (number of vertices, size/width of texture, etc.) in buffer.
Implements GFXResource.
Referenced by getPath().
virtual GFXFormat GFXCubemap::getFormat () const pure virtual
Returns the face texture format.
Implemented in GFXGLCubemap, and GFXD3D11Cubemap.
Referenced by _setPath().
const String& GFXCubemap::getPath (void) const inline
Returns the cubemap file path set at creation.
References describeSelf(), and mPath.
virtual U32 GFXCubemap::getSize () const pure virtual
Returns the size of the faces.
Implemented in GFXGLCubemap, and GFXD3D11Cubemap.
Referenced by _setPath().
virtual void GFXCubemap::initDynamic (U32 texSize, GFXFormat faceFormat = GFXFormatR8G8B8A8) pure virtual
Implemented in GFXGLCubemap, and GFXD3D11Cubemap.
Referenced by _setPath().
void GFXCubemap::initNormalize (U32 size)
Referenced by _setPath().
virtual void GFXCubemap::initStatic (GFXTexHandle * faces) pure virtual
Create a static cubemap from a list of 6 face textures.
Implemented in GFXGLCubemap, and GFXD3D11Cubemap.
Referenced by _setPath().
virtual void GFXCubemap::initStatic (DDSFile * dds) pure virtual
Create a static cubemap from a DDS cubemap file.
Implemented in GFXGLCubemap, and GFXD3D11Cubemap.
virtual void GFXCubemap::setToTexUnit (U32 tuNum) protected pure virtual
Implemented in GFXGLCubemap, and GFXD3D11Cubemap.
Member Data Documentation
String GFXCubemap::mPath protected
The path to the cubemap file.
Referenced by getPath().
Copyright © GarageGames, LLC. All Rights Reserved.