HashTable< Key, Value > Class Template Reference
Main Modules Class List Namespace List Online
HashTable< Key, Value > Class Template Reference
A HashTable template class.
#include <core/util/tDictionary.h>
Classes
class _Iterator
struct Pair
Public Types
typedef _Iterator< const Pair, const Node, const HashTable > ConstIterator
typedef const Pair & ConstReference
typedef S32 DifferenceType
typedef _Iterator< Pair, Node, HashTable > Iterator
typedef Pair & Reference
typedef U32 SizeType
typedef Pair ValueType
Public Member Functions
HashTable ()
HashTable (const HashTable &p)
~HashTable ()
Iterator begin ()
Iterator to first element.
ConstIterator begin () const
Iterator to first element.
void clear ()
Empty the HashTable.
F32 collisions () const
Returns the average number of nodes per bucket.
S32 count (const Key &) const
Count the number of matching keys in the table.
Iterator end ()
Iterator to last element + 1.
ConstIterator end () const
Iterator to last element + 1.
void erase (Iterator)
Erase the given entry.
void erase (const Key &key)
Erase all matching keys from the table.
void erase (const Key &key, const Value &value)
Erase entry for this key-value pair.
Iterator find (const Key &)
Find the first entry for the given key.
ConstIterator find (const Key &) const
Find the first entry for the given key.
bool find (const Key &key, Value &value)
Find the first entry for the given key.
Iterator findOrInsert (const Key &key)
Find the key, or insert a one if it doesn't exist.
Iterator insertEqual (const Key &key, const Value &)
Insert the key value pair and allow duplicates.
Iterator insertUnique (const Key &key, const Value &)
Insert the key value pair but don't insert duplicates.
bool isEmpty () const
Returns true if the table is empty.
void operator= (const HashTable &p)
void resize (U32 size)
Resize the bucket table for an estimated number of elements.
U32 size () const
Return the number of elements.
U32 tableSize () const
Return the size of the hash bucket table.
Detailed Description
template<typename Key, typename Value>
class HashTable< Key, Value >
A HashTable template class.
The hash table class maps between a key and an associated value. Access using the key is performed using a hash table. The class provides methods for both unique and equal keys. The global ::hash(Type) function is used for hashing, see util/hash.h
Member Typedef Documentation
template<typename Key, typename Value> typedef _Iterator<const Pair,const Node,const HashTable> HashTable< Key, Value >::ConstIterator
template<typename Key, typename Value> typedef const Pair& HashTable< Key, Value >::ConstReference
template<typename Key, typename Value> typedef S32 HashTable< Key, Value >::DifferenceType
template<typename Key, typename Value> typedef _Iterator<Pair,Node,HashTable> HashTable< Key, Value >::Iterator
template<typename Key, typename Value> typedef Pair& HashTable< Key, Value >::Reference
template<typename Key, typename Value> typedef U32 HashTable< Key, Value >::SizeType
template<typename Key, typename Value> typedef Pair HashTable< Key, Value >::ValueType
Constructor & Destructor Documentation
template<typename Key , typename Value > HashTable< Key, Value >::HashTable ()
template<typename Key , typename Value > HashTable< Key, Value >::~HashTable ()
References destructInPlace(), dMemset(), ClassChunker< T >::freeBlocks(), DictHash::hash(), DictHash::nextPrime(), and HashTable< Key, Value >::size().
template<typename Key , typename Value > HashTable< Key, Value >::HashTable (const HashTable< Key, Value > & p)
Member Function Documentation
template<typename Key , typename Value > HashTable< Key, Value >::Iterator HashTable< Key, Value >::begin () inline
Iterator to first element.
Referenced by HashMap< typeAssetId, AssetDefinition * >::contains(), Material::StageData::hasValidTex(), and Map< U32, ID3D11SamplerState * >::tryGetValue().
template<typename Key , typename Value > HashTable< Key, Value >::ConstIterator HashTable< Key, Value >::begin () const inline
Iterator to first element.
template<typename Key , typename Value > void HashTable< Key, Value >::clear (void) inline
Empty the HashTable.
Referenced by HashMap< typeAssetId, AssetDefinition * >::~HashMap(), and Map< U32, ID3D11SamplerState * >::~Map().
template<typename Key , typename Value > F32 HashTable< Key, Value >::collisions () const inline
Returns the average number of nodes per bucket.
template<typename Key, typename Value > S32 HashTable< Key, Value >::count (const Key & key) const
Count the number of matching keys in the table.
template<typename Key , typename Value > HashTable< Key, Value >::Iterator HashTable< Key, Value >::end () inline
Iterator to last element + 1.
Referenced by AssetManager::acquireAsset(), HashMap< typeAssetId, AssetDefinition * >::contains(), Material::StageData::getTex(), Material::StageData::hasValidTex(), HashTable< Key, Value >::insertUnique(), Material::StageData::setTex(), and Map< U32, ID3D11SamplerState * >::tryGetValue().
template<typename Key , typename Value > HashTable< Key, Value >::ConstIterator HashTable< Key, Value >::end () const inline
Iterator to last element + 1.
template<typename Key , typename Value > void HashTable< Key, Value >::erase (Iterator node)
Erase the given entry.
References ClassChunker< T >::free().
Referenced by Material::StageData::setTex(), HashMap< typeAssetId, AssetDefinition * >::~HashMap(), and Map< U32, ID3D11SamplerState * >::~Map().
template<typename Key, typename Value > void HashTable< Key, Value >::erase (const Key & key)
Erase all matching keys from the table.
References ClassChunker< T >::free().
template<typename Key, typename Value> void HashTable< Key, Value >::erase (const Key & key, const Value & value)
Erase entry for this key-value pair.
References ClassChunker< T >::free().
template<typename Key, typename Value > HashTable< Key, Value >::Iterator HashTable< Key, Value >::find (const Key & key)
Find the first entry for the given key.
Referenced by AssetManager::acquireAsset(), Material::StageData::getTex(), Material::StageData::setTex(), Map< U32, ID3D11SamplerState * >::tryGetValue(), HashMap< typeAssetId, AssetDefinition * >::~HashMap(), and Map< U32, ID3D11SamplerState * >::~Map().
template<typename Key, typename Value > HashTable< Key, Value >::ConstIterator HashTable< Key, Value >::find (const Key & key) const
Find the first entry for the given key.
template<typename Key, typename Value> bool HashTable< Key, Value >::find (const Key & key, Value & value)
Find the first entry for the given key.
template<typename Key, typename Value > HashTable< Key, Value >::Iterator HashTable< Key, Value >::findOrInsert (const Key & key)
Find the key, or insert a one if it doesn't exist.
Returns the first key in the table that matches, or inserts one if there are none.
References ClassChunker< T >::alloc().
Referenced by Material::StageData::setTex().
template<typename Key, typename Value> HashTable< Key, Value >::Iterator HashTable< Key, Value >::insertEqual (const Key & key, const Value & x)
Insert the key value pair and allow duplicates.
This insert method allows duplicate keys. Keys are grouped together but are not sorted.
References ClassChunker< T >::alloc().
template<typename Key, typename Value> HashTable< Key, Value >::Iterator HashTable< Key, Value >::insertUnique (const Key & key, const Value & x)
Insert the key value pair but don't insert duplicates.
This insert method does not insert duplicate keys. If the key already exists in the table the function will fail and end() is returned.
References ClassChunker< T >::alloc(), and HashTable< Key, Value >::end().
template<typename Key , typename Value > bool HashTable< Key, Value >::isEmpty () const inline
Returns true if the table is empty.
Referenced by HashMap< typeAssetId, AssetDefinition * >::~HashMap(), and Map< U32, ID3D11SamplerState * >::~Map().
template<typename Key , typename Value > void HashTable< Key, Value >::operator= (const HashTable< Key, Value > & p)
template<typename Key , typename Value > void HashTable< Key, Value >::resize (U32 size) inline
Resize the bucket table for an estimated number of elements.
This method will optimize the hash bucket table size to hold the given number of elements. The size argument is a hint, and will not be the exact size of the table. If the table is sized down below it's optimal size, the next insert will cause it to be resized again. Normally this function is used to avoid resizes when the number of elements that will be inserted is known in advance.
References DataChunker::setChunkSize().
Referenced by Map< U32, ID3D11SamplerState * >::~Map().
template<typename Key , typename Value > U32 HashTable< Key, Value >::size () const inline
Return the number of elements.
Referenced by AssetManager::getReferencedAssetCount(), HashMap< typeAssetId, AssetDefinition * >::~HashMap(), HashTable< Key, Value >::~HashTable(), and Map< U32, ID3D11SamplerState * >::~Map().
template<typename Key , typename Value > U32 HashTable< Key, Value >::tableSize () const inline
Return the size of the hash bucket table.
Copyright © GarageGames, LLC. All Rights Reserved.