ModuleDefinition Class Reference
Main Modules Class List Namespace List Online
ModuleDefinition Class Reference
#include <module/moduleDefinition.h>
Classes
struct ModuleDependency
Module dependency.
Public Types
typedef Vector< AssetDefinition * > typeModuleAssetsVector
typedef Vector< ModuleDependency > typeModuleDependencyVector
Public Types inherited from SimSet
typedef SimObject Parent
enum SetModification {
SetCleared,
SetObjectAdded,
SetObjectRemoved
}
typedef Signal< void(SetModification modification, SimSet *set, SimObject *object) > SetModificationSignal
Signal for letting observers know when objects are added to or removed from the set.
typedef SimObjectList::iterator iterator
typedef SimObjectList::value_type value
Public Types inherited from SimObject
typedef ConsoleObject Parent
enum WriteFlags {
SelectedOnly = BIT(0),
NoName = BIT(1),
IgnoreCanSave = BIT(2)
}
Flags passed to SimObject::write.
Public Types inherited from EngineObject
typedef void(* DebugEnumInstancesCallback) (EngineObject *)
Type of callback function for iterating over EngineObject instances.
Public Member Functions
ModuleDefinition ()
virtual ~ModuleDefinition ()
bool addDependency (const char *pModuleId, const U32 versionId)
DECLARE_CONOBJECT (ModuleDefinition)
Declare Console Object.
StringTableEntry getAssetTagsManifest (void) const
StringTableEntry getAuthor (void) const
U32 getBuildId (void) const
StringTableEntry getCreateFunction (void) const
bool getCriticalMerge (void) const
const typeModuleDependencyVector & getDependencies (void) const
bool getDependency (const U32 dependencyIndex, ModuleDependency &dependency) const
U32 getDependencyCount (void) const
Specialized dependency control.
bool getDeprecated (void) const
StringTableEntry getDestroyFunction (void) const
bool getEnabled (void) const
S32 getLoadCount (void) const
bool getLocked (void) const
typeModuleAssetsVector & getModuleAssets (void)
StringTableEntry getModuleDescription (void) const
StringTableEntry getModuleFile (void) const
StringTableEntry getModuleFilePath (void) const
StringTableEntry getModuleGroup (void) const
StringTableEntry getModuleId (void) const
ModuleManager * getModuleManager (void) const
StringTableEntry getModulePath (void) const
StringTableEntry getModuleScriptFilePath (void) const
StringTableEntry getModuleType (void) const
bool getOverrideExistingObjects (void) const
SimObjectId getScopeSet (void) const
StringTableEntry getScriptFile (void) const
StringTableEntry getSignature (void) const
bool getSynchronized (void) const
U32 getVersionId (void) const
void increaseLoadCount (void)
void reduceLoadCount (void)
bool removeDependency (const char *pModuleId)
bool save (void)
void setAssetTagsManifest (const char *pTagsAssetManifest)
Module assets.
void setAuthor (const char *pAuthor)
void setBuildId (const U32 buildId)
void setCreateFunction (const char *pCreateFunction)
void setCriticalMerge (const bool mergeCritical)
void setDependencies (const typeModuleDependencyVector &dependencies)
void setDeprecated (const bool deprecated)
void setDestroyFunction (const char *pDestroyFunction)
void setEnabled (const bool enabled)
void setLocked (const bool status)
void setModuleDescription (const char *pModuleDescription)
void setModuleFile (const char *pModuleDefinitionFile)
void setModuleFilePath (const char *pModuleDefinitionFilePath)
void setModuleGroup (const char *pModuleGroup)
void setModuleId (const char *pModuleId)
Module definition.
void setModulePath (const char *pModulePath)
Module location.
void setModuleScriptFilePath (const char *pModuleScriptFilePath)
void setModuleType (const char *pModuleType)
void setOverrideExistingObjects (const bool overrideExistingObj)
void setScriptFile (const char *pScriptFile)
void setSignature (const char *pSignature)
Miscellaneous.
void setSynchronized (const bool synchronized)
void setVersionId (const U32 versionId)
Public Member Functions inherited from SimSet
SimSet ()
~SimSet ()
virtual void addTamlChild (SimObject *pSimObject)
Called when Taml attempts to populate an objects children during a read.
void callOnChildren (const String &method, S32 argc, ConsoleValueRef argv[], bool executeOnChildGroups=true)
virtual SimSet * clone ()
Return a shallow copy of this object.
DECLARE_CONOBJECT (SimSet)
SimObject * findObject (SimObject *object)
Find the given object in this set.
virtual SimObject * findObject (const char *name)
Find a named sub-object of this object.
template<class T >
void findObjectByCallback (bool(*fn)(T *), Vector< T * > &foundObjects)
Add all child objects (including children of children) to the foundObjects Vector which are of type T and for which DecideAddObjectCallback return true;.
virtual SimObject * findObjectByInternalName (StringTableEntry internalName, bool searchChildren=false)
SimObject * findObjectByLineNumber (const char *fileName, S32 declarationLine, bool searchChildren=false)
template<class T >
void findObjectByType (Vector< T * > &foundObjects)
Add all child objects (including children of children) to the foundObjects Vector which are of type T.
SimObject * getRandom ()
const SetModificationSignal & getSetModificationSignal () const
Return the signal that is triggered when an object is added to or removed from the set.
SetModificationSignal & getSetModificationSignal ()
virtual SimObject * getTamlChild (const U32 childIndex) const
Called when Taml attempts to compile a list of children.
virtual U32 getTamlChildCount (void) const
Called when Taml attempts to compile a list of children.
void lock ()
virtual void onDeleteNotify (SimObject *object)
Called when a SimObject is deleted.
virtual void onRemove ()
Called when the object is removed from the sim.
virtual bool readObject (Stream *stream)
U32 sizeRecursive ()
Return the number of objects in this set as well as all sets that are contained in this set and its children.
void unlock ()
virtual void write (Stream &stream, U32 tabStop, U32 flags=0)
Output the TorqueScript to recreate this object.
virtual bool writeObject (Stream *stream)
virtual void addObject (SimObject *object)
Add the given object to the set.
virtual void removeObject (SimObject *object)
Remove the given object from the set.
virtual void pushObject (SimObject *object)
Add the given object to the end of the object list of this set.
virtual bool acceptsAsChild (SimObject *object) const
Return true if this set accepts the given object as a child.
void deleteAllObjects ()
Deletes all the objects in the set.
virtual void popObject ()
Remove an object from the end of the list.
void bringObjectToFront (SimObject *obj)
void pushObjectToBack (SimObject *obj)
void scriptSort (const String &scriptCallbackFn)
Performs a sort of the objects in the set using a script callback function to do the comparison.
SimObject * front ()
SimObject * first ()
SimObject * last ()
bool empty () const
S32 size () const
iterator begin ()
iterator end ()
value operator[] (S32 index)
iterator find (iterator first, iterator last, SimObject *obj)
iterator find (SimObject *obj)
virtual bool reOrder (SimObject *obj, SimObject *target=0)
Reorder the position of "obj" to either be the last object in the list or, if "target" is given, to come before "target" in the list of children.
SimObject * at (S32 index) const
Return the object at the given index.
virtual void clear ()
Remove all objects from this set.
Public Member Functions inherited from SimObject
virtual void copyTo (SimObject *object)
Copy SimObject to another SimObject (Originally designed for T2D).
DECLARE_CONOBJECT (SimObject)
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
virtual void getConsoleMethodData (const char *fname, S32 routingId, S32 *type, S32 *minArgs, S32 *maxArgs, void **callback, const char **usage)
Namespace * getNamespace ()
Return the object's namespace.
StringTableEntry getProgenitorFile (void) const
virtual bool handlesConsoleMethod (const char *fname, S32 *routingId)
void setProgenitorFile (const char *pFile)
const char * tabComplete (const char *prevText, S32 baseLen, bool)
Get next matching item in namespace.
virtual bool writeField (StringTableEntry fieldname, const char *value)
Determine whether or not a field should be written.
virtual void writeFields (Stream &stream, U32 tabStop)
Write the fields of this object in TorqueScript.
void setCanSaveDynamicFields (bool bCanSave)
Set whether fields created at runtime should be saved. Default is true.
bool getCanSaveDynamicFields ()
Get whether fields created at runtime should be saved. Default is true.
SimObject * getCopySource () const
Return the object that this object is copying fields from.
void setCopySource (SimObject *object)
Set the object that this object should be copying fields from.
void assignFieldsFrom (SimObject *obj)
Copy fields from another object onto this one.
void assignDynamicFieldsFrom (SimObject *obj)
Copy dynamic fields from another object onto this one.
Notify * removeNotify (void *ptr, Notify::Type)
Remove a notification from the list.
void deleteNotify (SimObject *obj)
Notify an object when we are deleted.
void clearNotify (SimObject *obj)
Notify an object when we are cleared.
void clearAllNotifications ()
Remove all notifications for this object.
void processDeleteNotifies ()
Send out deletion notifications.
void registerReference (SimObject **obj)
Register a reference to this object.
void unregisterReference (SimObject **obj)
Unregister a reference to this object.
SimPersistID * getPersistentId () const
Return the persistent ID assigned to this object or NULL.
SimPersistID * getOrCreatePersistentId ()
Return the persistent ID assigned to this object or assign one to it if it has none.
StringTableEntry getClassNamespace () const
Return name of class namespace set on this object.
StringTableEntry getSuperClassNamespace () const
Return name of superclass namespace set on this object.
void setClassNamespace (const char *classNamespace)
void setSuperClassNamespace (const char *superClassNamespace)
virtual SimObject * deepClone ()
Return a deep copy of this object.
const char * getDataField (StringTableEntry slotName, const char *array)
Get the value of a field on the object.
void setDataField (StringTableEntry slotName, const char *array, const char *value)
Set the value of a field on the object.
const char * getPrefixedDataField (StringTableEntry fieldName, const char *array)
void setPrefixedDataField (StringTableEntry fieldName, const char *array, const char *value)
const char * getPrefixedDynamicDataField (StringTableEntry fieldName, const char *array, const S32 fieldType=-1)
void setPrefixedDynamicDataField (StringTableEntry fieldName, const char *array, const char *value, const S32 fieldType=-1)
StringTableEntry getDataFieldPrefix (StringTableEntry fieldName)
U32 getDataFieldType (StringTableEntry slotName, const char *array)
Get the type of a field on the object.
void setDataFieldType (const U32 fieldTypeId, StringTableEntry slotName, const char *array)
Set the type of a dynamic field on the object.
void setDataFieldType (const char *typeName, StringTableEntry slotName, const char *array)
SimFieldDictionary * getFieldDictionary ()
Get reference to the dictionary containing dynamic fields.
virtual StringTableEntry getComponentName ()
void setInternalName (const char *newname)
These functions support internal naming that is not namespace bound for locating child controls in a generic way.
StringTableEntry getInternalName () const
Get the internal name of this control.
void setOriginalName (const char *originalName)
Set the original name of this control.
StringTableEntry getOriginalName () const
Get the original name of this control.
void setFilename (const char *file)
These functions allow you to set and access the filename where this object was created.
StringTableEntry getFilename () const
Get the filename.
void setDeclarationLine (U32 lineNumber)
These functions are used to track the line number (1-based) on which the object was created if it was loaded from script.
S32 getDeclarationLine () const
Get the declaration line number.
virtual bool save (const char *pcFilePath, bool bOnlySelected=false, const char *preappend=NULL)
Save object as a TorqueScript File.
virtual bool isMethod (const char *methodName)
Check if a method exists in the objects current namespace.
virtual bool isField (const char *fieldName, bool includeStatic=true, bool includeDynamic=true)
Return true if the field is defined on the object.
SimObjectId getId () const
Return the unique numeric object ID.
const char * getIdString () const
Return the object ID as a string.
StringTableEntry getName () const
Return the name of this object.
SimGroup * getGroup () const
Return the SimGroup that this object is contained in.
void assignName (const char *name)
Assign the given name to this object.
void setId (SimObjectId id)
bool isChildOfGroup (SimGroup *pGroup)
bool isProperlyAdded () const
bool isDeleted () const
bool isRemoved () const
virtual bool isLocked () const
virtual bool isHidden () const
virtual void setHidden (bool b)
bool isSelected () const
bool isExpanded () const
bool isEditorOnly () const
bool isNameChangeAllowed () const
bool isAutoDeleted () const
void setSelected (bool sel)
void setExpanded (bool exp)
void setModDynamicFields (bool dyn)
void setModStaticFields (bool sta)
bool canModDynamicFields ()
bool canModStaticFields ()
void setAutoDelete (bool val)
void setEditorOnly (bool val)
void setNameChangeAllowed (bool val)
bool getCanSave () const
Returns boolean specifying if the object can be serialized.
virtual void setCanSave (bool val)
Set serialization flag.
bool isSelectedRecursive () const
Returns true if this object is selected or any group it is a member of is.
SimObject ()
virtual ~SimObject ()
virtual bool processArguments (S32 argc, ConsoleValueRef *argv)
Process constructor options. (ie, new SimObject(1,2,3))
virtual bool onAdd ()
Called when the object is added to the sim.
virtual void onGroupAdd ()
Called when the object is added to a SimGroup.
virtual void onGroupRemove ()
Called when the object is removed from a SimGroup.
virtual void onNameChange (const char *name)
Called when the object's name is changed.
virtual void onPostAdd ()
Called when the adding of the object to the sim is complete, all sub-objects have been processed as well.
virtual void onStaticModified (const char *slotName, const char *newValue=NULL)
Specifically, these are called by setDataField when a static or dynamic field is modified, see the console details.
virtual void onDynamicModified (const char *slotName, const char *newValue=NULL)
Called when a dynamic field is modified.
virtual void inspectPreApply ()
Called before any property of the object is changed in the world editor.
virtual void inspectPostApply ()
Called after any property of the object is changed in the world editor.
virtual void onEditorEnable ()
Called when the editor is activated.
virtual void onEditorDisable ()
Called when the editor is deactivated.
bool registerObject ()
Register an object with the object system.
bool registerObject (U32 id)
Register the object, forcing the id.
bool registerObject (const char *name)
Register the object, assigning the name.
bool registerObject (const char *name, U32 id)
Register the object, assigning a name and ID.
void unregisterObject ()
Unregister the object from Sim.
void deleteObject ()
Unregister, mark as deleted, and free the object.
void safeDeleteObject ()
Performs a safe delayed delete of the object using a sim event.
bool addToSet (SimObjectId)
bool addToSet (const char *)
bool removeFromSet (SimObjectId)
bool removeFromSet (const char *)
virtual String describeSelf () const
Return a textual description of the object.
void dumpToConsole (bool includeFunctions=true)
Dump the contents of this object to the console.
virtual void dumpClassHierarchy ()
added this so that you can print the entire class hierarchy, including script objects,
virtual void dumpGroupHierarchy ()
Print the SimGroup hierarchy of this object to the console.
Public Member Functions inherited from ConsoleObject
ConsoleObject ()
virtual AbstractClassRep * getClassRep () const
Gets the ClassRep.
const AbstractClassRep::Field * findField (StringTableEntry fieldName) const
Get a reference to a field by name.
bool setField (const char *fieldName, const char *value)
Set the value of a field.
void logMessage (const char *fmt,...) const
Logs with Con::printf.
void logWarning (const char *fmt,...) const
Logs with Con::warnf.
void logError (const char *fmt,...) const
Logs with Con::errorf.
const AbstractClassRep::FieldList & getFieldList () const
Get a list of all the fields. This information cannot be modified.
AbstractClassRep::FieldList & getModifiableFieldList ()
Get a list of all the fields, set up so we can modify them.
bool & getDynamicGroupExpand ()
Get a handle to a boolean telling us if we expanded the dynamic group.
S32 getClassId (U32 netClassGroup) const
Get our network-layer class id.
StringTableEntry getClassName () const
Get our compiler and platform independent class name.
Public Member Functions inherited from EngineObject
EngineObject ()
virtual ~EngineObject ()
DECLARE_ABSTRACT_CLASS (EngineObject, void)
DECLARE_INSCOPE (_GLOBALSCOPE)
IEngineObjectPool * getEngineObjectPool () const
Return the pool of EngineObjects to which this object belongs.
void operator delete (void *ptr)
Release the given object's memory in the pool it has been allocated from.
void * operator new (size_t size)
void * operator new (size_t size, IEngineObjectPool *pool)
void * operator new (size_t size TORQUE_TMM_ARGS_DECL)
Allocate a new object in the default object pool.
void * operator new (size_t size, IEngineObjectPool *pool TORQUE_TMM_ARGS_DECL)
Allocate a new object in the given object pool.
void * operator new (size_t size, void *ptr)
Placement new.
Public Member Functions inherited from StrongRefBase
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Static Public Member Functions
static void initPersistFields ()
Engine.
Static Public Member Functions inherited from SimObject
static SimObject * __findObject (const char *id)
static const char * __getObjectId (ConsoleObject *object)
static void initPersistFields ()
static void setForcedId (SimObjectId id)
Force an Id on the next registered object.
Static Public Member Functions inherited from ConsoleObject
static const char * __category ()
static const char * __description ()
static void consoleInit ()
Register global constant variables and do other one-time initialization tasks in a subclass of ConsoleObject.
static void initPersistFields ()
Register dynamic fields in a subclass of ConsoleObject.
static const char * lookupClassName (const U32 in_classTag)
Get the classname from a class tag.
static ConsoleObject * create (const char *in_pClassName)
static ConsoleObject * create (const U32 groupId, const U32 typeId, const U32 in_classId)
static void addGroup (const char *in_pGroupname, const char *in_pGroupDocs=NULL)
Mark the beginning of a group of fields.
static void endGroup (const char *in_pGroupname)
Mark the end of a group of fields.
static void addArray (const char *arrayName, S32 count)
Marks the start of a fixed size array of fields.
static void endArray (const char *arrayName)
Marks the end of an array of fields.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a complex field.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::WriteDataNotify in_writeDataFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, const char *in_pFieldDocs, U32 flags=0)
Register a simple field.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::WriteDataNotify in_writeDataFn, const char *in_pFieldDocs, U32 flags=0)
static void addFieldV (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, TypeValidator *v, const char *in_pFieldDocs=NULL)
Register a validated field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, AbstractClassRep::WriteDataNotify in_writeDataFn=&defaultProtectedWriteFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a complex protected field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, AbstractClassRep::WriteDataNotify in_writeDataFn=&defaultProtectedWriteFn, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a simple protected field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addDeprecatedField (const char *fieldName)
Add a deprecated field.
static bool removeField (const char *in_pFieldname)
Remove a field.
static AbstractClassRep * getStaticClassRep ()
Get the abstract class information for this class.
static AbstractClassRep * getParentStaticClassRep ()
Get the abstract class information for this class's superclass.
static ConsoleObject * __findObject (const char *)
static const char * __getObjectId (ConsoleObject *)
Static Public Member Functions inherited from EngineObject
static void debugDumpInstances ()
Dump describeSelf()s of all live ConsoleObjects to the console.
static void debugEnumInstances (const std::type_info &type, DebugEnumInstancesCallback callback)
Call the given callback for all instances of the given type.
static void debugEnumInstances (const char *className, DebugEnumInstancesCallback callback)
Same as above but uses an export class name and also includes inheritance (i.e.
Static Protected Member Functions
static const char * getDependencies (void *obj, const char *data)
static const char * getScopeSet (void *obj, const char *data)
static const char * getSignature (void *obj, const char *data)
static bool setAssetTagsManifest (void *obj, const char *index, const char *data)
Asset manifest.
static bool setAuthor (void *obj, const char *index, const char *data)
static bool setBuildId (void *obj, const char *index, const char *data)
static bool setCreateFunction (void *obj, const char *index, const char *data)
static bool setDependencies (void *obj, const char *index, const char *data)
static bool setDeprecated (void *obj, const char *index, const char *data)
static bool setDestroyFunction (void *obj, const char *index, const char *data)
static bool setEnabled (void *obj, const char *index, const char *data)
static bool setModuleDescription (void *obj, const char *index, const char *data)
static bool setModuleGroup (void *obj, const char *index, const char *data)
static bool setModuleId (void *obj, const char *index, const char *data)
static bool setModuleType (void *obj, const char *index, const char *data)
static bool setOverrideExistingObjects (void *obj, const char *index, const char *data)
static bool setScriptFile (void *obj, const char *index, const char *data)
static bool setSynchronized (void *obj, const char *index, const char *data)
static bool setVersionId (void *obj, const char *index, const char *data)
static bool writeAssetTagsManifest (void *obj, StringTableEntry pFieldName)
static bool writeAuthor (void *obj, StringTableEntry pFieldName)
static bool writeBuildId (void *obj, StringTableEntry pFieldName)
static bool writeCreateFunction (void *obj, StringTableEntry pFieldName)
static bool writeCriticalMerge (void *obj, StringTableEntry pFieldName)
static bool writeDependencies (void *obj, StringTableEntry pFieldName)
static bool writeDeprecated (void *obj, StringTableEntry pFieldName)
static bool writeDestroyFunction (void *obj, StringTableEntry pFieldName)
static bool writeEnabled (void *obj, StringTableEntry pFieldName)
static bool writeModuleDescription (void *obj, StringTableEntry pFieldName)
static bool writeModuleType (void *obj, StringTableEntry pFieldName)
static bool writeOverrideExistingObjects (void *obj, StringTableEntry pFieldName)
static bool writeScriptFile (void *obj, StringTableEntry pFieldName)
static bool writeSynchronized (void *obj, StringTableEntry pFieldName)
Static Protected Member Functions inherited from SimObject
static bool _setPersistentID (void *object, const char *index, const char *data)
Static Protected Member Functions inherited from EngineObject
static void * _allocateObject (size_t size, IEngineObjectPool *pool TORQUE_TMM_ARGS_DECL)
Additional Inherited Members
Public Attributes inherited from EngineObject
DECLARE_INSTANTIABLE
Static Public Attributes inherited from ConsoleObject
static const bool __smIsDatablock = false
Subclasses of ConsoleObjects that are datablocks should redefine this static member variable and set it to true.
Protected Types inherited from EngineObject
typedef ::FalseType __IsDisposableType
typedef ::FalseType __IsSingletonType
Protected Member Functions inherited from SimSet
DECLARE_CALLBACK (void, onObjectAdded,(SimObject *object))
DECLARE_CALLBACK (void, onObjectRemoved,(SimObject *object))
Protected Member Functions inherited from SimObject
virtual void _destroySelf ()
Subclasses should overload this method instead of the public destroySelf().
virtual String _getLogMessage (const char *fmt, va_list args) const
We can provide more detail, like object name and id.
virtual void _onSelected ()
Called when the object is selected in the editor.
virtual void _onUnselected ()
Called when the object is unselected in the editor.
object incRefCount ()
virtual void onTamlAddParent (SimObject *pParentObject)
Called after Taml has finished reading the object and has added the object to any parent.
virtual void onTamlCustomRead (const TamlCustomNodes &customNodes)
Called during the reading of the object to allow custom properties to be read.
virtual void onTamlCustomWrite (TamlCustomNodes &customNodes)
Called during the writing of the object to allow custom properties to be written.
virtual void onTamlPostRead (const TamlCustomNodes &customNodes)
Called after Taml has finished reading the object.
virtual void onTamlPostWrite (void)
Called after Taml has finished writing the object.
virtual void onTamlPreRead (void)
Called prior to Taml reading the object.
virtual void onTamlPreWrite (void)
Taml callbacks.
object registerObject ()
void linkNamespaces ()
Perform namespace linking on this object.
void unlinkNamespaces ()
Undo namespace linking on this object.
Protected Member Functions inherited from ConsoleObject
ConsoleObject (const ConsoleObject &)
Protected Member Functions inherited from EngineObject
object incRefCount ()
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Protected Attributes inherited from SimSet
void * mMutex
SetModificationSignal mSetModificationSignal
Signal that is triggered when objects are added or removed from the set.
SimObjectList objectList
Protected Attributes inherited from SimObject
DEFINE_CREATE_METHOD
SimObjectId mId
Id number for this object.
StringTableEntry mInternalName
Internal name assigned to the object. Not set by default.
return object
bool mCanSaveFieldDictionary
Whether dynamic fields should be saved out in serialization. Defaults to true.
SimPersistID * mPersistentId
Persistent ID assigned to this object.
Namespace * mNameSpace
The namespace in which method lookup for this object begins.
StringTableEntry mClassName
Name of namespace to use as class namespace.
StringTableEntry mSuperClassName
Name of namespace to use as class super namespace.
Protected Attributes inherited from EngineObject
DEFINE_CREATE_METHOD
return object
Protected Attributes inherited from StrongRefBase
U32 mRefCount
reference counter for StrongRefPtr objects
Static Protected Attributes inherited from SimObject
static SimObjectId smForcedId
The Id to force upon the object. Poor object.
static bool smForceId
Force a registered object to use the given Id. Cleared upon use.
Detailed Description
See also
moduleGroup
Member Typedef Documentation
typedef Vector<AssetDefinition*> ModuleDefinition::typeModuleAssetsVector
typedef Vector<ModuleDependency> ModuleDefinition::typeModuleDependencyVector
Constructor & Destructor Documentation
ModuleDefinition::ModuleDefinition ()
virtual ModuleDefinition::~ModuleDefinition () inline virtual
References initPersistFields().
Member Function Documentation
bool ModuleDefinition::addDependency (const char * pModuleId, const U32 versionId)
Referenced by getDependencyCount().
ModuleDefinition::DECLARE_CONOBJECT (ModuleDefinition)
Declare Console Object.
Referenced by getModuleManager().
StringTableEntry ModuleDefinition::getAssetTagsManifest (void) const inline
Referenced by writeAssetTagsManifest().
StringTableEntry ModuleDefinition::getAuthor (void) const inline
Referenced by writeAuthor().
U32 ModuleDefinition::getBuildId (void) const inline
Referenced by writeBuildId().
StringTableEntry ModuleDefinition::getCreateFunction (void) const inline
Referenced by writeCreateFunction().
bool ModuleDefinition::getCriticalMerge (void) const inline
Referenced by writeCriticalMerge().
const typeModuleDependencyVector& ModuleDefinition::getDependencies (void) const inline
Referenced by getDependencies(), and writeDependencies().
static const char* ModuleDefinition::getDependencies (void * obj, const char * data) inline static protected
References Vector< T >::begin(), Vector< T >::end(), getDependencies(), Con::getReturnBuffer(), ModuleDefinition::ModuleDependency::mModuleId, ModuleDefinition::ModuleDependency::mVersionId, and Vector< T >::size().
bool ModuleDefinition::getDependency (const U32 dependencyIndex, ModuleDependency & dependency) const
Referenced by getDependencyCount().
U32 ModuleDefinition::getDependencyCount (void) const inline
Specialized dependency control.
References addDependency(), getDependency(), removeDependency(), and Vector< T >::size().
bool ModuleDefinition::getDeprecated (void) const inline
Referenced by writeDeprecated().
StringTableEntry ModuleDefinition::getDestroyFunction (void) const inline
Referenced by writeDestroyFunction().
bool ModuleDefinition::getEnabled (void) const inline
Referenced by writeEnabled().
S32 ModuleDefinition::getLoadCount (void) const inline
bool ModuleDefinition::getLocked (void) const inline
typeModuleAssetsVector& ModuleDefinition::getModuleAssets (void) inline
StringTableEntry ModuleDefinition::getModuleDescription (void) const inline
Referenced by writeModuleDescription().
StringTableEntry ModuleDefinition::getModuleFile (void) const inline
StringTableEntry ModuleDefinition::getModuleFilePath (void) const inline
StringTableEntry ModuleDefinition::getModuleGroup (void) const inline
StringTableEntry ModuleDefinition::getModuleId (void) const inline
References ModuleDefinition::ModuleDependency::mModuleId.
ModuleManager* ModuleDefinition::getModuleManager (void) const inline
References DECLARE_CONOBJECT(), and save().
StringTableEntry ModuleDefinition::getModulePath (void) const inline
StringTableEntry ModuleDefinition::getModuleScriptFilePath (void) const inline
StringTableEntry ModuleDefinition::getModuleType (void) const inline
Referenced by writeModuleType().
bool ModuleDefinition::getOverrideExistingObjects (void) const inline
Referenced by writeOverrideExistingObjects().
SimObjectId ModuleDefinition::getScopeSet (void) const inline
static const char* ModuleDefinition::getScopeSet (void * obj, const char * data) inline static protected
References Con::getIntArg(), and getScopeSet().
Referenced by getScopeSet().
StringTableEntry ModuleDefinition::getScriptFile (void) const inline
Referenced by writeScriptFile().
StringTableEntry ModuleDefinition::getSignature (void) const inline
static const char* ModuleDefinition::getSignature (void * obj, const char * data) inline static protected
References getSignature().
Referenced by getSignature().
bool ModuleDefinition::getSynchronized (void) const inline
Referenced by writeSynchronized().
U32 ModuleDefinition::getVersionId (void) const inline
References ModuleDefinition::ModuleDependency::mVersionId.
void ModuleDefinition::increaseLoadCount (void) inline
static void ModuleDefinition::initPersistFields () static
Engine.
Referenced by ~ModuleDefinition().
void ModuleDefinition::reduceLoadCount (void) inline
bool ModuleDefinition::removeDependency (const char * pModuleId)
Referenced by getDependencyCount().
bool ModuleDefinition::save (void)
Referenced by getModuleManager().
void ModuleDefinition::setAssetTagsManifest (const char * pTagsAssetManifest) inline
Module assets.
static bool ModuleDefinition::setAssetTagsManifest (void * obj, const char * index, const char * data) inline static protected
Asset manifest.
References setAssetTagsManifest().
Referenced by setAssetTagsManifest().
void ModuleDefinition::setAuthor (const char * pAuthor) inline
static bool ModuleDefinition::setAuthor (void * obj, const char * index, const char * data) inline static protected
References setAuthor().
Referenced by setAuthor().
void ModuleDefinition::setBuildId (const U32 buildId) inline
static bool ModuleDefinition::setBuildId (void * obj, const char * index, const char * data) inline static protected
References dAtoi(), and setBuildId().
Referenced by setBuildId().
void ModuleDefinition::setCreateFunction (const char * pCreateFunction) inline
static bool ModuleDefinition::setCreateFunction (void * obj, const char * index, const char * data) inline static protected
References setCreateFunction().
Referenced by setCreateFunction().
void ModuleDefinition::setCriticalMerge (const bool mergeCritical) inline
void ModuleDefinition::setDependencies (const typeModuleDependencyVector & dependencies) inline
References Vector< T >::clear(), and Vector< T >::merge().
Referenced by setDependencies().
static bool ModuleDefinition::setDependencies (void * obj, const char * index, const char * data) inline static protected
References dAtoi(), StringUnit::getUnit(), StringUnit::getUnitCount(), Vector< T >::push_back(), and setDependencies().
void ModuleDefinition::setDeprecated (const bool deprecated) inline
static bool ModuleDefinition::setDeprecated (void * obj, const char * index, const char * data) inline static protected
References dAtob(), and setDeprecated().
Referenced by setDeprecated().
void ModuleDefinition::setDestroyFunction (const char * pDestroyFunction) inline
static bool ModuleDefinition::setDestroyFunction (void * obj, const char * index, const char * data) inline static protected
References setDestroyFunction().
Referenced by setDestroyFunction().
void ModuleDefinition::setEnabled (const bool enabled) inline
static bool ModuleDefinition::setEnabled (void * obj, const char * index, const char * data) inline static protected
References dAtob(), and setEnabled().
Referenced by setEnabled().
void ModuleDefinition::setLocked (const bool status) inline virtual
Reimplemented from SimObject.
void ModuleDefinition::setModuleDescription (const char * pModuleDescription) inline
static bool ModuleDefinition::setModuleDescription (void * obj, const char * index, const char * data) inline static protected
References setModuleDescription().
Referenced by setModuleDescription().
void ModuleDefinition::setModuleFile (const char * pModuleDefinitionFile) inline
void ModuleDefinition::setModuleFilePath (const char * pModuleDefinitionFilePath) inline
void ModuleDefinition::setModuleGroup (const char * pModuleGroup) inline
static bool ModuleDefinition::setModuleGroup (void * obj, const char * index, const char * data) inline static protected
References setModuleGroup().
Referenced by setModuleGroup().
void ModuleDefinition::setModuleId (const char * pModuleId) inline
Module definition.
static bool ModuleDefinition::setModuleId (void * obj, const char * index, const char * data) inline static protected
References setModuleId().
Referenced by setModuleId().
void ModuleDefinition::setModulePath (const char * pModulePath) inline
Module location.
void ModuleDefinition::setModuleScriptFilePath (const char * pModuleScriptFilePath) inline
void ModuleDefinition::setModuleType (const char * pModuleType) inline
static bool ModuleDefinition::setModuleType (void * obj, const char * index, const char * data) inline static protected
References setModuleType().
Referenced by setModuleType().
void ModuleDefinition::setOverrideExistingObjects (const bool overrideExistingObj) inline
static bool ModuleDefinition::setOverrideExistingObjects (void * obj, const char * index, const char * data) inline static protected
References dAtob(), and setOverrideExistingObjects().
Referenced by setOverrideExistingObjects().
void ModuleDefinition::setScriptFile (const char * pScriptFile) inline
static bool ModuleDefinition::setScriptFile (void * obj, const char * index, const char * data) inline static protected
References setScriptFile().
Referenced by setScriptFile().
void ModuleDefinition::setSignature (const char * pSignature) inline
Miscellaneous.
void ModuleDefinition::setSynchronized (const bool synchronized) inline
static bool ModuleDefinition::setSynchronized (void * obj, const char * index, const char * data) inline static protected
References dAtob(), and setSynchronized().
Referenced by setSynchronized().
void ModuleDefinition::setVersionId (const U32 versionId) inline
static bool ModuleDefinition::setVersionId (void * obj, const char * index, const char * data) inline static protected
References dAtoi(), and setVersionId().
Referenced by setVersionId().
static bool ModuleDefinition::writeAssetTagsManifest (void * obj, StringTableEntry pFieldName) inline static protected
References getAssetTagsManifest().
static bool ModuleDefinition::writeAuthor (void * obj, StringTableEntry pFieldName) inline static protected
References getAuthor().
static bool ModuleDefinition::writeBuildId (void * obj, StringTableEntry pFieldName) inline static protected
References getBuildId().
static bool ModuleDefinition::writeCreateFunction (void * obj, StringTableEntry pFieldName) inline static protected
References getCreateFunction().
static bool ModuleDefinition::writeCriticalMerge (void * obj, StringTableEntry pFieldName) inline static protected
References getCriticalMerge().
static bool ModuleDefinition::writeDependencies (void * obj, StringTableEntry pFieldName) inline static protected
References getDependencies(), and Vector< T >::size().
static bool ModuleDefinition::writeDeprecated (void * obj, StringTableEntry pFieldName) inline static protected
References getDeprecated().
static bool ModuleDefinition::writeDestroyFunction (void * obj, StringTableEntry pFieldName) inline static protected
References getDestroyFunction().
static bool ModuleDefinition::writeEnabled (void * obj, StringTableEntry pFieldName) inline static protected
References getEnabled().
static bool ModuleDefinition::writeModuleDescription (void * obj, StringTableEntry pFieldName) inline static protected
References getModuleDescription().
static bool ModuleDefinition::writeModuleType (void * obj, StringTableEntry pFieldName) inline static protected
References getModuleType().
static bool ModuleDefinition::writeOverrideExistingObjects (void * obj, StringTableEntry pFieldName) inline static protected
References getOverrideExistingObjects().
static bool ModuleDefinition::writeScriptFile (void * obj, StringTableEntry pFieldName) inline static protected
References getScriptFile().
static bool ModuleDefinition::writeSynchronized (void * obj, StringTableEntry pFieldName) inline static protected
References getSynchronized().
Copyright © GarageGames, LLC. All Rights Reserved.