GFXGLVertexDecl Class Reference
Main Modules Class List Namespace List Online
GFXGLVertexDecl Class Reference
#include <gfx/gl/gfxGLVertexDecl.h>
Classes
struct glVertexAttribData
Public Member Functions
GFXGLVertexDecl ()
void init (const GFXVertexFormat *format)
void prepareBuffer_old (U32 stream, GLint mBuffer, GLint mDivisor) const
void prepareVertexFormat () const
void updateActiveVertexAttrib (U32 lastActiveMask) const
Public Member Functions inherited from GFXVertexDecl
virtual ~GFXVertexDecl ()
Protected Member Functions
void _initVerticesFormat (U32 stream)
void _initVerticesFormat2 ()
Protected Attributes
Vector< glVertexAttribData > glVerticesFormat
const GFXVertexFormat * mFormat
U32 mVertexAttribActiveMask
GLuint mVertexSize [4]
Constructor & Destructor Documentation
GFXGLVertexDecl::GFXGLVertexDecl () inline
References init(), prepareBuffer_old(), prepareVertexFormat(), and updateActiveVertexAttrib().
Member Function Documentation
void GFXGLVertexDecl::_initVerticesFormat (U32 stream) protected
void GFXGLVertexDecl::_initVerticesFormat2 () protected
void GFXGLVertexDecl::init (const GFXVertexFormat * format)
Referenced by GFXGLVertexDecl().
void GFXGLVertexDecl::prepareBuffer_old (U32 stream, GLint mBuffer, GLint mDivisor) const
Referenced by GFXGLVertexDecl().
void GFXGLVertexDecl::prepareVertexFormat () const
Referenced by GFXGLVertexDecl().
void GFXGLVertexDecl::updateActiveVertexAttrib (U32 lastActiveMask) const
Referenced by GFXGLVertexDecl().
Member Data Documentation
Vector<glVertexAttribData> GFXGLVertexDecl::glVerticesFormat protected
const GFXVertexFormat* GFXGLVertexDecl::mFormat protected
U32 GFXGLVertexDecl::mVertexAttribActiveMask protected
GLuint GFXGLVertexDecl::mVertexSize[4] protected
Copyright © GarageGames, LLC. All Rights Reserved.