FindMatch Class Reference
Main Modules Class List Namespace List Online
FindMatch Class Reference
#include <core/strings/findMatch.h>
Public Member Functions
FindMatch (U32 _maxMatches=256)
FindMatch (char *_expression, U32 _maxMatches=256)
~FindMatch ()
void clear ()
bool findMatch (const char *string, bool caseSensitive=false)
bool isFull () const
S32 numMatches () const
void setExpression (const char *_expression)
Static Public Member Functions
static bool isMatch (const char *exp, const char *string, bool caseSensitive=false)
static bool isMatchMultipleExprs (const char *exps, const char *str, bool caseSensitive)
Public Attributes
Vector< char * > matchList
Constructor & Destructor Documentation
FindMatch::FindMatch (U32 _maxMatches = 256)
FindMatch::FindMatch (char * _expression, U32 _maxMatches = 256)
FindMatch::~FindMatch ()
Member Function Documentation
void FindMatch::clear (void) inline
References Vector< T >::clear().
bool FindMatch::findMatch (const char * string, bool caseSensitive = false)
bool FindMatch::isFull () const inline
References Vector< T >::size().
static bool FindMatch::isMatch (const char * exp, const char * string, bool caseSensitive = false) static
static bool FindMatch::isMatchMultipleExprs (const char * exps, const char * str, bool caseSensitive) static
S32 FindMatch::numMatches () const inline
References Vector< T >::size().
void FindMatch::setExpression (const char * _expression)
Member Data Documentation
Vector<char *> FindMatch::matchList
Copyright © GarageGames, LLC. All Rights Reserved.