BitVector Class Reference
Main Modules Class List Namespace List Online
BitVector Class Reference
Manage a vector of bits of arbitrary size.
#include <core/bitVector.h>
Public Member Functions
BitVector ()
Default constructor which creates an bit vector with a bit size of zero.
BitVector (U32 sizeInBits)
Constructs a bit vector with the desired size.
BitVector (const BitVector &r)
Copy constructor.
~BitVector ()
Destructor.
void copy (const BitVector &from)
Copy the content of another bit vector.
BitVector & operator= (const BitVector &r)
Copy the contents of another bit vector.
Size Management
bool empty () const
Return true if the bit vector is empty.
void setSize (U32 sizeInBits)
Resizes the bit vector.
U32 getSize () const
Returns the size in bits.
U32 getByteSize () const
Returns the 32bit aligned size in bytes.
const U8 * getBits () const
Returns the bits.
U8 * getBits ()
Mutators
Note that bits are specified by index, unlike BitSet32.
void set (U32 bit)
Set the specified bit.
void set (U32 bit, bool on)
Set the specified bit on or off.
void set ()
Set all the bits.
void clear (U32 bit)
Clear the specified bit.
void clear ()
Clear all the bits.
void combineOR (const BitVector &other)
Does an OR operation between BitVectors.
bool test (U32 bit) const
Test that the specified bit is set.
bool testAny (const BitVector &vector) const
Test this vector's bits against all the corresponding bits in vector and return true if any of the bits that are set in vector are also set in this vector.
bool testAll (const BitVector &vector) const
Test this vector's bits against all the corresponding bits in vector and return true if all of the bits that are set in vector are also set in this vector.
bool testAll () const
Return true if all bits are set.
bool testAllClear () const
Return true if all bits are clear.
Protected Member Functions
void _resize (U32 sizeInBits, bool copyBits)
Internal function which resizes the bit array.
bool _test (const BitVector &vector, bool all) const
Static Protected Member Functions
static U32 calcByteSize (const U32 numBits)
Returns a size in bytes which is 32bit aligned and can hold all the requested bits.
Protected Attributes
U8 * mBits
The array of bytes that stores our bits.
U32 mByteSize
The allocated size of the bit array.
U32 mSize
The size of the vector in bits.
Detailed Description
Manage a vector of bits of arbitrary size.
Constructor & Destructor Documentation
BitVector::BitVector () inline
Default constructor which creates an bit vector with a bit size of zero.
References mBits, mByteSize, and mSize.
BitVector::BitVector (U32 sizeInBits) inline
Constructs a bit vector with the desired size.
Note
The resulting vector is not cleared.
References mBits, mByteSize, mSize, and setSize().
BitVector::BitVector (const BitVector & r) inline
Copy constructor.
References copy(), mBits, mByteSize, and mSize.
BitVector::~BitVector () inline
Destructor.
References mBits, mByteSize, and mSize.
Member Function Documentation
void BitVector::_resize (U32 sizeInBits, bool copyBits) protected
Internal function which resizes the bit array.
Referenced by copy(), and setSize().
bool BitVector::_test (const BitVector & vector, bool all) const protected
Referenced by testAll(), and testAny().
U32 BitVector::calcByteSize (const U32 numBits) inline static protected
Returns a size in bytes which is 32bit aligned and can hold all the requested bits.
void BitVector::clear (U32 bit) inline
Clear the specified bit.
References mBits, and mSize.
Referenced by BitMatrix::clearAllBits().
void BitVector::clear (void) inline
Clear all the bits.
References dMemset(), getByteSize(), mBits, and mSize.
Referenced by getBits().
void BitVector::combineOR (const BitVector & other)
Does an OR operation between BitVectors.
Referenced by getBits().
void BitVector::copy (const BitVector & from) inline
Copy the content of another bit vector.
References _resize(), dMemcpy(), getBits(), getByteSize(), getSize(), mBits, and mSize.
Referenced by BitVector(), getBits(), and operator=().
bool BitVector::empty () const inline
Return true if the bit vector is empty.
References setSize().
const U8* BitVector::getBits () const inline
Returns the bits.
References mBits.
Referenced by copy().
U8* BitVector::getBits () inline
References clear(), combineOR(), copy(), mBits, operator=(), and test().
U32 BitVector::getByteSize () const inline
Returns the 32bit aligned size in bytes.
References mByteSize.
Referenced by clear(), copy(), and set().
U32 BitVector::getSize () const inline
Returns the size in bits.
References mSize.
Referenced by copy().
BitVector & BitVector::operator= (const BitVector & r) inline
Copy the contents of another bit vector.
References copy().
Referenced by getBits().
void BitVector::set (U32 bit) inline
Set the specified bit.
References mBits, and mSize.
Referenced by BitMatrix::setAllBits(), and BitMatrix::setBit().
void BitVector::set (U32 bit, bool on) inline
Set the specified bit on or off.
References mBits, and mSize.
void BitVector::set () inline
Set all the bits.
References dMemset(), getByteSize(), mBits, and mSize.
void BitVector::setSize (U32 sizeInBits) inline
Resizes the bit vector.
Note
The new bits in the vector are not cleared and contain random garbage bits.
References _resize().
Referenced by BitVector(), and empty().
bool BitVector::test (U32 bit) const inline
Test that the specified bit is set.
References mBits, and mSize.
Referenced by getBits(), BitMatrix::isAnySetCol(), and BitMatrix::isAnySetRow().
bool BitVector::testAll (const BitVector & vector) const inline
Test this vector's bits against all the corresponding bits in vector and return true if all of the bits that are set in vector are also set in this vector.
Parameters
vector Bit vector of the same size.
References _test(), testAll(), and testAllClear().
bool BitVector::testAll () const
Return true if all bits are set.
Referenced by testAll().
bool BitVector::testAllClear () const
Return true if all bits are clear.
Referenced by testAll().
bool BitVector::testAny (const BitVector & vector) const inline
Test this vector's bits against all the corresponding bits in vector and return true if any of the bits that are set in vector are also set in this vector.
Parameters
vector Bit vector of the same size.
References _test().
Member Data Documentation
U8* BitVector::mBits protected
The array of bytes that stores our bits.
Referenced by BitVector(), clear(), copy(), getBits(), set(), test(), and ~BitVector().
U32 BitVector::mByteSize protected
The allocated size of the bit array.
Referenced by BitVector(), getByteSize(), and ~BitVector().
U32 BitVector::mSize protected
The size of the vector in bits.
Referenced by BitVector(), clear(), copy(), getSize(), set(), test(), and ~BitVector().
Copyright © GarageGames, LLC. All Rights Reserved.