BasicLightManager Class Reference
Main Modules Class List Namespace List Online
BasicLightManager Class Reference
#include <lighting/basic/basicLightManager.h>
Classes
struct LightingShaderConstants
Public Member Functions
virtual void activate (SceneManager *sceneManager)
virtual void deactivate ()
virtual bool isCompatible () const
virtual void setLightInfo (ProcessedMaterial *pmat, const Material *mat, const SceneData &sgData, const SceneRenderState *state, U32 pass, GFXShaderConstBuffer *shaderConsts)
Sets shader constants / textures for light infos.
virtual bool setTextureStage (const SceneData &sgData, const U32 currTexFlag, const U32 textureSlot, GFXShaderConstBuffer *shaderConsts, ShaderConstHandles *handles)
Allows us to set textures during the Material::setTextureStage call, return true if we've done work.
Public Member Functions inherited from LightManager
LightManager (const char *name, const char *id)
virtual ~LightManager ()
void getAllUnsortedLights (Vector< LightInfo * > *list) const
Returns all unsorted and un-scored lights (both global and local).
virtual LightInfo * getDefaultLight ()
const char * getId () const
Return an id string used to load different versions of light manager specific assets.
const char * getName () const
Return an id string used to load different versions of light manager specific assets.
virtual AvailableSLInterfaces * getSceneLightingInterface ()
SceneManager * getSceneManager ()
virtual LightInfo * getSpecialLight (SpecialLightTypesEnum type, bool useDefault=true)
Returns the special light or the default light if useDefault is true.
virtual bool isActive () const
Returns true if this light manager is active.
virtual bool lightScene (const char *callback, const char *param)
Called when the static scene lighting (aka lightmaps) should be computed.
virtual void registerGlobalLight (LightInfo *light, SimObject *obj)
virtual void registerGlobalLights (const Frustum *frustum, bool staticlighting)
virtual void registerLocalLight (LightInfo *light)
virtual void setSpecialLight (SpecialLightTypesEnum type, LightInfo *light)
Set a special light type.
virtual void unregisterAllLights ()
virtual void unregisterGlobalLight (LightInfo *light)
virtual void unregisterLocalLight (LightInfo *light)
Static Public Member Functions
static F32 getShadowFilterDistance ()
static const char * getSingletonName ()
Static Public Member Functions inherited from LightManager
static LightInfo * createLightInfo (LightInfo *light=NULL)
static LightManager * findByName (const char *name)
static LightManager * getActiveLM ()
Returns the active LM.
static void getLightManagerNames (String *outString)
Returns a tab seperated list of available light managers.
static void initLightFields ()
Protected Types
typedef Map< GFXShader *, LightingShaderConstants * > LightConstantMap
Protected Member Functions
BasicLightManager ()
virtual ~BasicLightManager ()
virtual void _addLightInfoEx (LightInfo *lightInfo)
Attaches any LightInfoEx data for this manager to the light info object.
virtual void _initLightFields ()
void _onPreRender (SceneManager *sceneManger, const SceneRenderState *state)
Protected Member Functions inherited from LightManager
RenderDeferredMgr * _findDeferredRenderBin ()
Find the pre-pass render bin on the scene's default render pass.
Protected Attributes
LightConstantMap mConstantLookup
SimObjectPtr< RenderDeferredMgr > mDeferredRenderBin
LightingShaderConstants * mLastConstants
GFXShaderRef mLastShader
blTerrainSystem * mTerrainSystem
PlatformTimer * mTimer
A timer used for tracking update time.
Protected Attributes inherited from LightManager
AvailableSLInterfaces * mAvailableSLInterfaces
The scene lighting interfaces for lightmap generation.
Point3F mCullPos
The root culling position used for special sun light placement.
LightInfo * mDefaultLight
A dummy default light used when no lights happen to be registered with the manager.
const String mId
The constant light manager identifier initialized in the constructor.
bool mIsActive
Is true if this light manager has been activated.
const String mName
The constant light manager name initialized in the constructor.
LightInfoList mRegisteredLights
The list of global registered lights which is initialized before the scene is rendered.
SceneManager * mSceneManager
The scene graph the light manager is associated with.
LightInfo * mSpecialLights [slSpecialLightTypesCount]
The registered special light list.
Static Protected Attributes
static U32 smActiveShadowPlugins
Statics used for light manager/projected shadow metrics.
static U32 smElapsedUpdateMs
static F32 smProjectedShadowFilterDistance
This is used to determine the distance at which the shadow filtering PostEffect will be enabled for ProjectedShadow.
static U32 smShadowsUpdated
Static Protected Attributes inherited from LightManager
static LightManager * smActiveLM
The current active light manager.
Additional Inherited Members
Public Types inherited from LightManager
enum SpecialLightTypesEnum {
slSunLightType,
slSpecialLightTypesCount
}
Static Public Attributes inherited from LightManager
static Signal< void(const char *, bool)> smActivateSignal
The light manager activation signal.
Static Protected Member Functions inherited from LightManager
static LightManagerMap & _getLightManagers ()
Returns the static light manager map.
static void _update4LightConsts (const SceneData &sgData, GFXShaderConstHandle *lightPositionSC, GFXShaderConstHandle *lightDiffuseSC, GFXShaderConstHandle *lightAmbientSC, GFXShaderConstHandle *lightInvRadiusSqSC, GFXShaderConstHandle *lightSpotDirSC, GFXShaderConstHandle *lightSpotAngleSC, GFXShaderConstHandle *lightSpotFalloffSC, GFXShaderConstBuffer *shaderConsts)
This helper function sets the shader constansts for the stock 4 light forward lighting code.
Member Typedef Documentation
typedef Map<GFXShader*, LightingShaderConstants*> BasicLightManager::LightConstantMap protected
Constructor & Destructor Documentation
BasicLightManager::BasicLightManager () protected
Referenced by _initLightFields().
virtual BasicLightManager::~BasicLightManager () protected virtual
Referenced by _initLightFields().
Member Function Documentation
virtual void BasicLightManager::_addLightInfoEx (LightInfo * lightInfo) inline protected virtual
Attaches any LightInfoEx data for this manager to the light info object.
Implements LightManager.
virtual void BasicLightManager::_initLightFields () inline protected virtual
Implements LightManager.
References _onPreRender(), BasicLightManager(), and ~BasicLightManager().
void BasicLightManager::_onPreRender (SceneManager * sceneManger, const SceneRenderState * state) protected
Referenced by _initLightFields().
virtual void BasicLightManager::activate (SceneManager * sceneManager) virtual
Reimplemented from LightManager.
virtual void BasicLightManager::deactivate () virtual
Reimplemented from LightManager.
static F32 BasicLightManager::getShadowFilterDistance () inline static
References smProjectedShadowFilterDistance.
static const char* BasicLightManager::getSingletonName () inline static
virtual bool BasicLightManager::isCompatible () const virtual
Implements LightManager.
virtual void BasicLightManager::setLightInfo (ProcessedMaterial * pmat, const Material * mat, const SceneData & sgData, const SceneRenderState * state, U32 pass, GFXShaderConstBuffer * shaderConsts) virtual
Sets shader constants / textures for light infos.
Implements LightManager.
virtual bool BasicLightManager::setTextureStage (const SceneData & sgData, const U32 currTexFlag, const U32 textureSlot, GFXShaderConstBuffer * shaderConsts, ShaderConstHandles * handles) inline virtual
Allows us to set textures during the Material::setTextureStage call, return true if we've done work.
Implements LightManager.
Member Data Documentation
LightConstantMap BasicLightManager::mConstantLookup protected
SimObjectPtr<RenderDeferredMgr> BasicLightManager::mDeferredRenderBin protected
LightingShaderConstants* BasicLightManager::mLastConstants protected
GFXShaderRef BasicLightManager::mLastShader protected
blTerrainSystem* BasicLightManager::mTerrainSystem protected
PlatformTimer* BasicLightManager::mTimer protected
A timer used for tracking update time.
U32 BasicLightManager::smActiveShadowPlugins static protected
Statics used for light manager/projected shadow metrics.
U32 BasicLightManager::smElapsedUpdateMs static protected
F32 BasicLightManager::smProjectedShadowFilterDistance static protected
This is used to determine the distance at which the shadow filtering PostEffect will be enabled for ProjectedShadow.
Referenced by getShadowFilterDistance().
U32 BasicLightManager::smShadowsUpdated static protected
Copyright © GarageGames, LLC. All Rights Reserved.