GFXGLWindowTarget Class Reference
Main Modules Class List Namespace List Online
GFXGLWindowTarget Class Reference
#include <gfx/gl/gfxGLWindowTarget.h>
Public Member Functions
GFXGLWindowTarget (PlatformWindow *win, GFXDevice *d)
~GFXGLWindowTarget ()
void _onAppSignal (WindowId wnd, S32 event)
void createPixelFormat ()
virtual GFXFormat getFormat ()
Returns the texture format of the render target.
const Point2I getSize ()
Returns the size in pixels of the render target.
void makeActive ()
virtual bool present ()
Present latest buffer, if buffer swapping is in effect.
virtual void resetMode ()
Notify the target that the video mode on the window has changed.
virtual void resolveTo (GFXTextureObject *obj)
Copy this surface to the passed GFXTextureObject.
virtual void resurrect ()
When called the resource should restore all device sensitive information destroyed by zombify()
virtual void zombify ()
When called the resource should destroy all device sensitive information (e.g. D3D resources in D3DPOOL_DEFAULT.
Public Member Functions inherited from GFXWindowTarget
GFXWindowTarget ()
GFXWindowTarget (PlatformWindow *windowObject)
virtual ~GFXWindowTarget ()
PlatformWindow * getWindow ()
Returns a pointer to the window this target is bound to.
Public Member Functions inherited from GFXTarget
GFXTarget ()
Constructor to initialize the state tracking logic.
virtual ~GFXTarget ()
virtual void activate ()
This is called to set the render target.
virtual void deactivate ()
This is called when the target is not being used anymore.
virtual const String describeSelf () const
The resource should put a description of itself (number of vertices, size/width of texture, etc.) in buffer.
const bool isPendingState () const
Called to check if we have pending state for the device to apply.
virtual void preserve ()
This tells the target that the contents of this target should be restored when activate() is next called.
Public Member Functions inherited from StrongRefBase
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Public Member Functions inherited from GFXResource
GFXResource ()
virtual ~GFXResource ()
void clearFlag ()
GFXResource * getNextResource () const
GFXDevice * getOwningDevice () const
GFXResource * getPrevResource () const
bool isFlagged ()
void registerResourceWithDevice (GFXDevice *device)
Registers this resource with the given device.
void setFlag ()
Additional Inherited Members
Protected Member Functions inherited from GFXTarget
void invalidateState ()
Called whenever a change is made to this target.
void stateApplied ()
Called when the device has applied pending state.
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Protected Attributes inherited from GFXWindowTarget
PlatformWindow * mWindow
Protected Attributes inherited from StrongRefBase
U32 mRefCount
reference counter for StrongRefPtr objects
Constructor & Destructor Documentation
GFXGLWindowTarget::GFXGLWindowTarget (PlatformWindow * win, GFXDevice * d)
GFXGLWindowTarget::~GFXGLWindowTarget ()
Member Function Documentation
void GFXGLWindowTarget::_onAppSignal (WindowId wnd, S32 event)
Referenced by resurrect().
void GFXGLWindowTarget::createPixelFormat ()
Referenced by resurrect().
virtual GFXFormat GFXGLWindowTarget::getFormat () inline virtual
Returns the texture format of the render target.
Implements GFXTarget.
References makeActive(), present(), and resetMode().
const Point2I GFXGLWindowTarget::getSize () inline virtual
Returns the size in pixels of the render target.
Implements GFXTarget.
References PlatformWindow::getClientExtent(), and GFXWindowTarget::mWindow.
void GFXGLWindowTarget::makeActive ()
Referenced by getFormat().
virtual bool GFXGLWindowTarget::present () virtual
Present latest buffer, if buffer swapping is in effect.
Implements GFXWindowTarget.
Referenced by getFormat().
virtual void GFXGLWindowTarget::resetMode () virtual
Notify the target that the video mode on the window has changed.
Implements GFXWindowTarget.
Referenced by getFormat().
virtual void GFXGLWindowTarget::resolveTo (GFXTextureObject * tex) virtual
Copy this surface to the passed GFXTextureObject.
Parameters
tex The GFXTextureObject to copy to.
Reimplemented from GFXTarget.
Referenced by resurrect().
virtual void GFXGLWindowTarget::resurrect () inline virtual
When called the resource should restore all device sensitive information destroyed by zombify()
Implements GFXResource.
References _onAppSignal(), createPixelFormat(), and resolveTo().
virtual void GFXGLWindowTarget::zombify () inline virtual
When called the resource should destroy all device sensitive information (e.g. D3D resources in D3DPOOL_DEFAULT.
Implements GFXResource.
Copyright © GarageGames, LLC. All Rights Reserved.