NetObject Class Reference
Main Modules Class List Namespace List Online
NetObject Class Reference
Superclass for ghostable networked objects.
#include <sim/netObject.h>
Public Member Functions
NetObject ()
~NetObject ()
virtual void clearMaskBits (U32 orMask)
Clear the specified bits from the dirty mask.
void clearScopeAlways ()
Stop scoping the object to all connections.
virtual String describeSelf () const
Return a textual description of the object.
virtual U32 filterMaskBits (U32 mask, NetConnection *connection)
U32 getNetIndex ()
Get the ghost index of this object.
virtual F32 getUpdatePriority (CameraScopeQuery *focusObject, U32 updateMask, S32 updateSkips)
This returns a value which is used to prioritize which objects need to be updated.
bool isClientObject () const
Is this a client object?
bool isGhost () const
Is this is a ghost?
bool isGhostable () const
Is this object ghostable?
bool isGhostAlways () const
Should this object always be ghosted?
bool isScopeable () const
Is this object subject to scoping?
bool isScopeLocal () const
Should this object only be visible to the client which created it?
bool isServerObject () const
Is this a server object?
virtual void onCameraScopeQuery (NetConnection *cr, CameraScopeQuery *camInfo)
Queries the object about information used to determine scope.
virtual U32 packUpdate (NetConnection *conn, U32 mask, BitStream *stream)
Instructs this object to pack its state for transfer over the network.
virtual void setMaskBits (U32 orMask)
Used to mark a bit as dirty; ie, that its corresponding set of fields need to be transmitted next update.
void setScopeAlways ()
Scope the object to all connections.
virtual void unpackUpdate (NetConnection *conn, BitStream *stream)
Instructs this object to read state data previously packed with packUpdate.
Public Member Functions inherited from SimGroup
~SimGroup ()
void addObject (SimObject *object, SimObjectId id)
void addObject (SimObject *object, const char *name)
virtual void addObject (SimObject *object)
Add the given object to the set.
virtual void clear ()
Remove all objects from this set.
virtual SimGroup * clone ()
Return a shallow copy of this object.
DECLARE_CONOBJECT (SimGroup)
virtual SimGroup * deepClone ()
Return a deep copy of this object.
virtual SimObject * findObject (const char *name)
Find a named sub-object of this object.
virtual void popObject ()
Remove an object from the end of the list.
virtual bool processArguments (S32 argc, ConsoleValueRef *argv)
Process constructor options. (ie, new SimObject(1,2,3))
virtual void pushObject (SimObject *object)
Add the given object to the end of the object list of this set.
virtual void removeObject (SimObject *object)
Remove the given object from the set.
Public Member Functions inherited from SimSet
SimSet ()
~SimSet ()
virtual void addTamlChild (SimObject *pSimObject)
Called when Taml attempts to populate an objects children during a read.
void callOnChildren (const String &method, S32 argc, ConsoleValueRef argv[], bool executeOnChildGroups=true)
DECLARE_CONOBJECT (SimSet)
SimObject * findObject (SimObject *object)
Find the given object in this set.
template<class T >
void findObjectByCallback (bool(*fn)(T *), Vector< T * > &foundObjects)
Add all child objects (including children of children) to the foundObjects Vector which are of type T and for which DecideAddObjectCallback return true;.
virtual SimObject * findObjectByInternalName (StringTableEntry internalName, bool searchChildren=false)
SimObject * findObjectByLineNumber (const char *fileName, S32 declarationLine, bool searchChildren=false)
template<class T >
void findObjectByType (Vector< T * > &foundObjects)
Add all child objects (including children of children) to the foundObjects Vector which are of type T.
SimObject * getRandom ()
const SetModificationSignal & getSetModificationSignal () const
Return the signal that is triggered when an object is added to or removed from the set.
SetModificationSignal & getSetModificationSignal ()
virtual SimObject * getTamlChild (const U32 childIndex) const
Called when Taml attempts to compile a list of children.
virtual U32 getTamlChildCount (void) const
Called when Taml attempts to compile a list of children.
void lock ()
virtual void onDeleteNotify (SimObject *object)
Called when a SimObject is deleted.
virtual bool readObject (Stream *stream)
U32 sizeRecursive ()
Return the number of objects in this set as well as all sets that are contained in this set and its children.
void unlock ()
virtual void write (Stream &stream, U32 tabStop, U32 flags=0)
Output the TorqueScript to recreate this object.
virtual bool writeObject (Stream *stream)
virtual bool acceptsAsChild (SimObject *object) const
Return true if this set accepts the given object as a child.
void deleteAllObjects ()
Deletes all the objects in the set.
void bringObjectToFront (SimObject *obj)
void pushObjectToBack (SimObject *obj)
void scriptSort (const String &scriptCallbackFn)
Performs a sort of the objects in the set using a script callback function to do the comparison.
SimObject * front ()
SimObject * first ()
SimObject * last ()
bool empty () const
S32 size () const
iterator begin ()
iterator end ()
value operator[] (S32 index)
iterator find (iterator first, iterator last, SimObject *obj)
iterator find (SimObject *obj)
virtual bool reOrder (SimObject *obj, SimObject *target=0)
Reorder the position of "obj" to either be the last object in the list or, if "target" is given, to come before "target" in the list of children.
SimObject * at (S32 index) const
Return the object at the given index.
Public Member Functions inherited from SimObject
virtual void copyTo (SimObject *object)
Copy SimObject to another SimObject (Originally designed for T2D).
DECLARE_CONOBJECT (SimObject)
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
virtual void getConsoleMethodData (const char *fname, S32 routingId, S32 *type, S32 *minArgs, S32 *maxArgs, void **callback, const char **usage)
Namespace * getNamespace ()
Return the object's namespace.
StringTableEntry getProgenitorFile (void) const
virtual bool handlesConsoleMethod (const char *fname, S32 *routingId)
void setProgenitorFile (const char *pFile)
const char * tabComplete (const char *prevText, S32 baseLen, bool)
Get next matching item in namespace.
virtual bool writeField (StringTableEntry fieldname, const char *value)
Determine whether or not a field should be written.
virtual void writeFields (Stream &stream, U32 tabStop)
Write the fields of this object in TorqueScript.
void setCanSaveDynamicFields (bool bCanSave)
Set whether fields created at runtime should be saved. Default is true.
bool getCanSaveDynamicFields ()
Get whether fields created at runtime should be saved. Default is true.
SimObject * getCopySource () const
Return the object that this object is copying fields from.
void setCopySource (SimObject *object)
Set the object that this object should be copying fields from.
void assignFieldsFrom (SimObject *obj)
Copy fields from another object onto this one.
void assignDynamicFieldsFrom (SimObject *obj)
Copy dynamic fields from another object onto this one.
Notify * removeNotify (void *ptr, Notify::Type)
Remove a notification from the list.
void deleteNotify (SimObject *obj)
Notify an object when we are deleted.
void clearNotify (SimObject *obj)
Notify an object when we are cleared.
void clearAllNotifications ()
Remove all notifications for this object.
void processDeleteNotifies ()
Send out deletion notifications.
void registerReference (SimObject **obj)
Register a reference to this object.
void unregisterReference (SimObject **obj)
Unregister a reference to this object.
SimPersistID * getPersistentId () const
Return the persistent ID assigned to this object or NULL.
SimPersistID * getOrCreatePersistentId ()
Return the persistent ID assigned to this object or assign one to it if it has none.
StringTableEntry getClassNamespace () const
Return name of class namespace set on this object.
StringTableEntry getSuperClassNamespace () const
Return name of superclass namespace set on this object.
void setClassNamespace (const char *classNamespace)
void setSuperClassNamespace (const char *superClassNamespace)
const char * getDataField (StringTableEntry slotName, const char *array)
Get the value of a field on the object.
void setDataField (StringTableEntry slotName, const char *array, const char *value)
Set the value of a field on the object.
const char * getPrefixedDataField (StringTableEntry fieldName, const char *array)
void setPrefixedDataField (StringTableEntry fieldName, const char *array, const char *value)
const char * getPrefixedDynamicDataField (StringTableEntry fieldName, const char *array, const S32 fieldType=-1)
void setPrefixedDynamicDataField (StringTableEntry fieldName, const char *array, const char *value, const S32 fieldType=-1)
StringTableEntry getDataFieldPrefix (StringTableEntry fieldName)
U32 getDataFieldType (StringTableEntry slotName, const char *array)
Get the type of a field on the object.
void setDataFieldType (const U32 fieldTypeId, StringTableEntry slotName, const char *array)
Set the type of a dynamic field on the object.
void setDataFieldType (const char *typeName, StringTableEntry slotName, const char *array)
SimFieldDictionary * getFieldDictionary ()
Get reference to the dictionary containing dynamic fields.
virtual StringTableEntry getComponentName ()
void setInternalName (const char *newname)
These functions support internal naming that is not namespace bound for locating child controls in a generic way.
StringTableEntry getInternalName () const
Get the internal name of this control.
void setOriginalName (const char *originalName)
Set the original name of this control.
StringTableEntry getOriginalName () const
Get the original name of this control.
void setFilename (const char *file)
These functions allow you to set and access the filename where this object was created.
StringTableEntry getFilename () const
Get the filename.
void setDeclarationLine (U32 lineNumber)
These functions are used to track the line number (1-based) on which the object was created if it was loaded from script.
S32 getDeclarationLine () const
Get the declaration line number.
virtual bool save (const char *pcFilePath, bool bOnlySelected=false, const char *preappend=NULL)
Save object as a TorqueScript File.
virtual bool isMethod (const char *methodName)
Check if a method exists in the objects current namespace.
virtual bool isField (const char *fieldName, bool includeStatic=true, bool includeDynamic=true)
Return true if the field is defined on the object.
SimObjectId getId () const
Return the unique numeric object ID.
const char * getIdString () const
Return the object ID as a string.
StringTableEntry getName () const
Return the name of this object.
SimGroup * getGroup () const
Return the SimGroup that this object is contained in.
void assignName (const char *name)
Assign the given name to this object.
void setId (SimObjectId id)
bool isChildOfGroup (SimGroup *pGroup)
bool isProperlyAdded () const
bool isDeleted () const
bool isRemoved () const
virtual bool isLocked () const
virtual void setLocked (bool b)
virtual bool isHidden () const
virtual void setHidden (bool b)
bool isSelected () const
bool isExpanded () const
bool isEditorOnly () const
bool isNameChangeAllowed () const
bool isAutoDeleted () const
void setSelected (bool sel)
void setExpanded (bool exp)
void setModDynamicFields (bool dyn)
void setModStaticFields (bool sta)
bool canModDynamicFields ()
bool canModStaticFields ()
void setAutoDelete (bool val)
void setEditorOnly (bool val)
void setNameChangeAllowed (bool val)
bool getCanSave () const
Returns boolean specifying if the object can be serialized.
virtual void setCanSave (bool val)
Set serialization flag.
bool isSelectedRecursive () const
Returns true if this object is selected or any group it is a member of is.
SimObject ()
virtual ~SimObject ()
virtual void onGroupAdd ()
Called when the object is added to a SimGroup.
virtual void onGroupRemove ()
Called when the object is removed from a SimGroup.
virtual void onNameChange (const char *name)
Called when the object's name is changed.
virtual void onPostAdd ()
Called when the adding of the object to the sim is complete, all sub-objects have been processed as well.
virtual void onStaticModified (const char *slotName, const char *newValue=NULL)
Specifically, these are called by setDataField when a static or dynamic field is modified, see the console details.
virtual void onDynamicModified (const char *slotName, const char *newValue=NULL)
Called when a dynamic field is modified.
virtual void inspectPreApply ()
Called before any property of the object is changed in the world editor.
virtual void inspectPostApply ()
Called after any property of the object is changed in the world editor.
virtual void onEditorEnable ()
Called when the editor is activated.
virtual void onEditorDisable ()
Called when the editor is deactivated.
bool registerObject ()
Register an object with the object system.
bool registerObject (U32 id)
Register the object, forcing the id.
bool registerObject (const char *name)
Register the object, assigning the name.
bool registerObject (const char *name, U32 id)
Register the object, assigning a name and ID.
void unregisterObject ()
Unregister the object from Sim.
void deleteObject ()
Unregister, mark as deleted, and free the object.
void safeDeleteObject ()
Performs a safe delayed delete of the object using a sim event.
bool addToSet (SimObjectId)
bool addToSet (const char *)
bool removeFromSet (SimObjectId)
bool removeFromSet (const char *)
void dumpToConsole (bool includeFunctions=true)
Dump the contents of this object to the console.
virtual void dumpClassHierarchy ()
added this so that you can print the entire class hierarchy, including script objects,
virtual void dumpGroupHierarchy ()
Print the SimGroup hierarchy of this object to the console.
Public Member Functions inherited from ConsoleObject
ConsoleObject ()
virtual AbstractClassRep * getClassRep () const
Gets the ClassRep.
const AbstractClassRep::Field * findField (StringTableEntry fieldName) const
Get a reference to a field by name.
bool setField (const char *fieldName, const char *value)
Set the value of a field.
void logMessage (const char *fmt,...) const
Logs with Con::printf.
void logWarning (const char *fmt,...) const
Logs with Con::warnf.
void logError (const char *fmt,...) const
Logs with Con::errorf.
const AbstractClassRep::FieldList & getFieldList () const
Get a list of all the fields. This information cannot be modified.
AbstractClassRep::FieldList & getModifiableFieldList ()
Get a list of all the fields, set up so we can modify them.
bool & getDynamicGroupExpand ()
Get a handle to a boolean telling us if we expanded the dynamic group.
S32 getClassId (U32 netClassGroup) const
Get our network-layer class id.
StringTableEntry getClassName () const
Get our compiler and platform independent class name.
Public Member Functions inherited from EngineObject
EngineObject ()
virtual ~EngineObject ()
DECLARE_ABSTRACT_CLASS (EngineObject, void)
DECLARE_INSCOPE (_GLOBALSCOPE)
IEngineObjectPool * getEngineObjectPool () const
Return the pool of EngineObjects to which this object belongs.
void operator delete (void *ptr)
Release the given object's memory in the pool it has been allocated from.
void * operator new (size_t size)
void * operator new (size_t size, IEngineObjectPool *pool)
void * operator new (size_t size TORQUE_TMM_ARGS_DECL)
Allocate a new object in the default object pool.
void * operator new (size_t size, IEngineObjectPool *pool TORQUE_TMM_ARGS_DECL)
Allocate a new object in the given object pool.
void * operator new (size_t size, void *ptr)
Placement new.
Public Member Functions inherited from StrongRefBase
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Static Public Member Functions
static void collapseDirtyList ()
Static Public Member Functions inherited from SimObject
static SimObject * __findObject (const char *id)
static const char * __getObjectId (ConsoleObject *object)
static void initPersistFields ()
static void setForcedId (SimObjectId id)
Force an Id on the next registered object.
Static Public Member Functions inherited from ConsoleObject
static const char * __category ()
static const char * __description ()
static void consoleInit ()
Register global constant variables and do other one-time initialization tasks in a subclass of ConsoleObject.
static void initPersistFields ()
Register dynamic fields in a subclass of ConsoleObject.
static const char * lookupClassName (const U32 in_classTag)
Get the classname from a class tag.
static ConsoleObject * create (const char *in_pClassName)
static ConsoleObject * create (const U32 groupId, const U32 typeId, const U32 in_classId)
static void addGroup (const char *in_pGroupname, const char *in_pGroupDocs=NULL)
Mark the beginning of a group of fields.
static void endGroup (const char *in_pGroupname)
Mark the end of a group of fields.
static void addArray (const char *arrayName, S32 count)
Marks the start of a fixed size array of fields.
static void endArray (const char *arrayName)
Marks the end of an array of fields.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a complex field.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::WriteDataNotify in_writeDataFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, const char *in_pFieldDocs, U32 flags=0)
Register a simple field.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::WriteDataNotify in_writeDataFn, const char *in_pFieldDocs, U32 flags=0)
static void addFieldV (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, TypeValidator *v, const char *in_pFieldDocs=NULL)
Register a validated field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, AbstractClassRep::WriteDataNotify in_writeDataFn=&defaultProtectedWriteFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a complex protected field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, AbstractClassRep::WriteDataNotify in_writeDataFn=&defaultProtectedWriteFn, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a simple protected field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addDeprecatedField (const char *fieldName)
Add a deprecated field.
static bool removeField (const char *in_pFieldname)
Remove a field.
static AbstractClassRep * getStaticClassRep ()
Get the abstract class information for this class.
static AbstractClassRep * getParentStaticClassRep ()
Get the abstract class information for this class's superclass.
static ConsoleObject * __findObject (const char *)
static const char * __getObjectId (ConsoleObject *)
Static Public Member Functions inherited from EngineObject
static void debugDumpInstances ()
Dump describeSelf()s of all live ConsoleObjects to the console.
static void debugEnumInstances (const std::type_info &type, DebugEnumInstancesCallback callback)
Call the given callback for all instances of the given type.
static void debugEnumInstances (const char *className, DebugEnumInstancesCallback callback)
Same as above but uses an export class name and also includes inheritance (i.e.
Protected Types
enum NetFlags {
IsGhost = BIT(1),
ScopeAlways = BIT(6),
ScopeLocal = BIT(7),
Ghostable = BIT(8),
MaxNetFlagBit = 15
}
Protected Types inherited from EngineObject
typedef ::FalseType __IsDisposableType
typedef ::FalseType __IsSingletonType
Protected Attributes
SimObjectPtr< NetObject > mClientObject
Pointer to the client object on a local connection.
GhostInfo * mFirstObjectRef
Head of a linked list storing GhostInfos referencing this NetObject.
BitSet32 mNetFlags
Flag values from NetFlags.
U32 mNetIndex
The index of this ghost in the GhostManager on the server.
SimObjectPtr< NetObject > mServerObject
Pointer to the server object on a local connection.
Protected Attributes inherited from SimSet
void * mMutex
SetModificationSignal mSetModificationSignal
Signal that is triggered when objects are added or removed from the set.
SimObjectList objectList
Protected Attributes inherited from SimObject
DEFINE_CREATE_METHOD
SimObjectId mId
Id number for this object.
StringTableEntry mInternalName
Internal name assigned to the object. Not set by default.
return object
bool mCanSaveFieldDictionary
Whether dynamic fields should be saved out in serialization. Defaults to true.
SimPersistID * mPersistentId
Persistent ID assigned to this object.
Namespace * mNameSpace
The namespace in which method lookup for this object begins.
StringTableEntry mClassName
Name of namespace to use as class namespace.
StringTableEntry mSuperClassName
Name of namespace to use as class super namespace.
Protected Attributes inherited from EngineObject
DEFINE_CREATE_METHOD
return object
Protected Attributes inherited from StrongRefBase
U32 mRefCount
reference counter for StrongRefPtr objects
Miscellaneous
DECLARE_CONOBJECT (NetObject)
bool onAdd ()
Called when the object is added to the sim.
void onRemove ()
Called when the object is removed from the sim.
static void initPersistFields ()
Short-Circuited Networking
When we are running with client and server on the same system (which can happen be either when we are doing a single player game, or if we're hosting a multiplayer game and having someone playing on the same instance), we can do some short circuited code to enhance performance.
These variables are used to make it simpler; if we are running in short-circuited mode, the ghosted client gets the server object while the server gets the client object.
Note
"Premature optimization is the root of all evil" - Donald Knuth. The current codebase uses this feature in three small places, mostly for non-speed-related purposes.
NetObject * getServerObject () const
Returns a pointer to the server object when on a local connection.
NetObject * getClientObject () const
Returns a pointer to the client object when on a local connection.
template<class T >
static T * getServerObject (T *netObj)
Template form for the callers convenience.
template<class T >
static T * getClientObject (T *netObj)
Template form for the callers convenience.
Additional Inherited Members
Public Types inherited from SimGroup
typedef SimSet Parent
Public Types inherited from SimSet
typedef SimObject Parent
enum SetModification {
SetCleared,
SetObjectAdded,
SetObjectRemoved
}
typedef Signal< void(SetModification modification, SimSet *set, SimObject *object) > SetModificationSignal
Signal for letting observers know when objects are added to or removed from the set.
typedef SimObjectList::iterator iterator
typedef SimObjectList::value_type value
Public Types inherited from SimObject
typedef ConsoleObject Parent
enum WriteFlags {
SelectedOnly = BIT(0),
NoName = BIT(1),
IgnoreCanSave = BIT(2)
}
Flags passed to SimObject::write.
Public Types inherited from EngineObject
typedef void(* DebugEnumInstancesCallback) (EngineObject *)
Type of callback function for iterating over EngineObject instances.
Public Attributes inherited from EngineObject
DECLARE_INSTANTIABLE
Static Public Attributes inherited from ConsoleObject
static const bool __smIsDatablock = false
Subclasses of ConsoleObjects that are datablocks should redefine this static member variable and set it to true.
Protected Member Functions inherited from SimSet
DECLARE_CALLBACK (void, onObjectAdded,(SimObject *object))
DECLARE_CALLBACK (void, onObjectRemoved,(SimObject *object))
Protected Member Functions inherited from SimObject
virtual void _destroySelf ()
Subclasses should overload this method instead of the public destroySelf().
virtual String _getLogMessage (const char *fmt, va_list args) const
We can provide more detail, like object name and id.
virtual void _onSelected ()
Called when the object is selected in the editor.
virtual void _onUnselected ()
Called when the object is unselected in the editor.
object incRefCount ()
virtual void onTamlAddParent (SimObject *pParentObject)
Called after Taml has finished reading the object and has added the object to any parent.
virtual void onTamlCustomRead (const TamlCustomNodes &customNodes)
Called during the reading of the object to allow custom properties to be read.
virtual void onTamlCustomWrite (TamlCustomNodes &customNodes)
Called during the writing of the object to allow custom properties to be written.
virtual void onTamlPostRead (const TamlCustomNodes &customNodes)
Called after Taml has finished reading the object.
virtual void onTamlPostWrite (void)
Called after Taml has finished writing the object.
virtual void onTamlPreRead (void)
Called prior to Taml reading the object.
virtual void onTamlPreWrite (void)
Taml callbacks.
object registerObject ()
void linkNamespaces ()
Perform namespace linking on this object.
void unlinkNamespaces ()
Undo namespace linking on this object.
Protected Member Functions inherited from ConsoleObject
ConsoleObject (const ConsoleObject &)
Protected Member Functions inherited from EngineObject
object incRefCount ()
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Static Protected Member Functions inherited from SimObject
static bool _setPersistentID (void *object, const char *index, const char *data)
Static Protected Member Functions inherited from EngineObject
static void * _allocateObject (size_t size, IEngineObjectPool *pool TORQUE_TMM_ARGS_DECL)
Static Protected Attributes inherited from SimObject
static SimObjectId smForcedId
The Id to force upon the object. Poor object.
static bool smForceId
Force a registered object to use the given Id. Cleared upon use.
Detailed Description
Superclass for ghostable networked objects.
Introduction To NetObject And Ghosting
One of the most powerful aspects of Torque's networking code is its support for ghosting and prioritized, most-recent-state network updates. The way this works is a bit complex, but it is immensely efficient. Let's run through the steps that the server goes through for each client in this part of Torque's networking:
First, the server determines what objects are in-scope for the client. This is done by calling onCameraScopeQuery() on the object which is considered the "scope" object. This is usually the player object, but it can be something else. (For instance, the current vehicle, or a object we're remote controlling.)
Second, it ghosts them to the client; this is implemented in netGhost.cc.
Finally, it sends updates as needed, by checking the dirty list and packing updates.
There several significant advantages to using this networking system:
Efficient network usage, since we only send data that has changed. In addition, since we only care about most-recent data, if a packet is dropped, we don't waste effort trying to deliver stale data.
Cheating protection; since we don't deliver information about game objects which aren't in scope, we dramatically reduce the ability of clients to hack the game and gain a meaningful advantage. (For instance, they can't find out about things behind them, since objects behind them don't fall in scope.) In addition, since ghost IDs are assigned per-client, it's difficult for any sort of co-ordination between cheaters to occur.
NetConnection contains the Ghost Manager implementation, which deals with transferring data to the appropriate clients and keeping state in synch.
An Example Implementation
The basis of the ghost implementation in Torque is NetObject. It tracks the dirty flags for the various states that the object trackers, and does some other book-keeping to allow more efficient operation of the networking layer.
Using a NetObject is very simple; let's go through a simple example implementation:
class SimpleNetObject : public NetObject
{
public:
  typedef NetObject Parent;
  DECLARE_CONOBJECT(SimpleNetObject);
Above is the standard boilerplate code for a Torque class. You can find out more about this in SimObject.
char message1[256];
char message2[256];
enum States {
   Message1Mask = BIT(0),
   Message2Mask = BIT(1),
};
For our example, we're having two "states" that we keep track of, message1 and message2. In a real object, we might map our states to health and position, or some other set of fields. You have 32 bits to work with, so it's possible to be very specific when defining states. In general, you should try to use as few states as possible (you never know when you'll need to expand your object's functionality!), and in fact, most of your fields will end up changing all at once, so it's not worth it to be too fine-grained. (As an example, position and velocity on Player are controlled by the same bit, as one rarely changes without the other changing, too.)
SimpleNetObject()
{
   // in order for an object to be considered by the network system,
   // the Ghostable net flag must be set.
   // the ScopeAlways flag indicates that the object is always scoped
   // on all active connections.
   mNetFlags.set(ScopeAlways | Ghostable);
   dStrcpy(message1, "Hello World 1!");
   dStrcpy(message2, "Hello World 2!");
}
Here is the constructor. Here, you see that we initialize our net flags to show that we should always be scoped, and that we're to be taken into consideration for ghosting. We also provide some initial values for the message fields.
U32 packUpdate(NetConnection *, U32 mask, BitStream *stream)
{
   // check which states need to be updated, and update them
   if(stream->writeFlag(mask & Message1Mask))
      stream->writeString(message1);
   if(stream->writeFlag(mask & Message2Mask))
      stream->writeString(message2);
   // the return value from packUpdate can set which states still
   // need to be updated for this object.
   return 0;
}
Here's half of the meat of the networking code, the packUpdate() function. (The other half, unpackUpdate(), we'll get to in a second.) The comments in the code pretty much explain everything, however, notice that the code follows a pattern of if(writeFlag(mask & StateMask)) { ... write data ... }. The packUpdate()/unpackUpdate() functions are responsible for reading and writing the dirty bits to the bitstream by themselves.
void unpackUpdate(NetConnection *, BitStream *stream)
{
   // the unpackUpdate function must be symmetrical to packUpdate
   if(stream->readFlag())
   {
      stream->readString(message1);
      Con::printf("Got message1: %s", message1);
   }
   if(stream->readFlag())
   {
      stream->readString(message2);
      Con::printf("Got message2: %s", message2);
   }
}
The other half of the networking code in any NetObject, unpackUpdate(). In our simple example, all that the code does is print the new messages to the console; however, in a more advanced object, you might trigger animations, update complex object properties, or even spawn new objects, based on what packet data you unpack.
void setMessage1(const char *msg)
{
   setMaskBits(Message1Mask);
   dStrcpy(message1, msg);
}
void setMessage2(const char *msg)
{
   setMaskBits(Message2Mask);
   dStrcpy(message2, msg);
}
Here are the accessors for the two properties. It is good to encapsulate your state variables, so that you don't have to remember to make a call to setMaskBits every time you change anything; the accessors can do it for you. In a more complex object, you might need to set multiple mask bits when you change something; this can be done using the | operator, for instance, setMaskBits(Message1Mask | Message2Mask); if you changed both messages.
IMPLEMENT_CO_NETOBJECT_V1(SimpleNetObject);
ConsoleMethod(SimpleNetObject, setMessage1, void, 3, 3, "(string msg) Set message 1.")
{
   object->setMessage1(argv[2]);
}
ConsoleMethod(SimpleNetObject, setMessage2, void, 3, 3, "(string msg) Set message 2.")
{
   object->setMessage2(argv[2]);
}
Finally, we use the NetObject implementation macro, IMPLEMENT_CO_NETOBJECT_V1(), to implement our NetObject. It is important that we use this, as it makes Torque perform certain initialization tasks that allow us to send the object over the network. IMPLEMENT_CONOBJECT() doesn't perform these tasks, see the documentation on AbstractClassRep for more details.
Member Enumeration Documentation
enum NetObject::NetFlags protected
Enumerator
IsGhost
This is a ghost.
ScopeAlways
Object always ghosts to clients.
ScopeLocal
Ghost only to local client.
Ghostable
Set if this object CAN ghost.
MaxNetFlagBit
Constructor & Destructor Documentation
NetObject::NetObject ()
NetObject::~NetObject ()
Member Function Documentation
virtual void NetObject::clearMaskBits (U32 orMask) virtual
Clear the specified bits from the dirty mask.
Parameters
orMask Bits to clear
void NetObject::clearScopeAlways ()
Stop scoping the object to all connections.
The object's ScopeAlways flag is cleared and the object is removed from all current active connections.
static void NetObject::collapseDirtyList () static
NetObject::DECLARE_CONOBJECT (NetObject)
virtual String NetObject::describeSelf () const virtual
Return a textual description of the object.
Reimplemented from SimObject.
Reimplemented in Portal, SceneSimpleZone, and SceneRootZone.
virtual U32 NetObject::filterMaskBits (U32 mask, NetConnection * connection) inline virtual
NetObject* NetObject::getClientObject () const inline
Returns a pointer to the client object when on a local connection.
template<class T > static T* NetObject::getClientObject (T * netObj) inline static
Template form for the callers convenience.
References T.
U32 NetObject::getNetIndex () inline
Get the ghost index of this object.
NetObject* NetObject::getServerObject () const inline
Returns a pointer to the server object when on a local connection.
template<class T > static T* NetObject::getServerObject (T * netObj) inline static
Template form for the callers convenience.
References T.
virtual F32 NetObject::getUpdatePriority (CameraScopeQuery * focusObject, U32 updateMask, S32 updateSkips) virtual
This returns a value which is used to prioritize which objects need to be updated.
In NetObject, our returned priority is 0.1 * updateSkips, so that less recently updated objects are more likely to be updated.
In subclasses, this can be adjusted. For instance, ShapeBase provides priority based on proximity to the camera.
Parameters
focusObject Information from a previous call to onCameraScopeQuery.
updateMask Current update mask.
updateSkips Number of ticks we haven't been updated for.
Returns
A floating point value indicating priority. These are typically < 5.0.
Reimplemented in ShapeBase, GameBase, and Projectile.
static void NetObject::initPersistFields () static
bool NetObject::isClientObject () const inline
Is this a client object?
Referenced by SceneTracker::_isTrackableObject().
bool NetObject::isGhost () const inline
Is this is a ghost?
bool NetObject::isGhostable () const inline
Is this object ghostable?
bool NetObject::isGhostAlways () const inline
Should this object always be ghosted?
bool NetObject::isScopeable () const inline
Is this object subject to scoping?
bool NetObject::isScopeLocal () const inline
Should this object only be visible to the client which created it?
bool NetObject::isServerObject () const inline
Is this a server object?
bool NetObject::onAdd () virtual
Called when the object is added to the sim.
Reimplemented from SimObject.
Reimplemented in ShapeBase, Player, TerrainBlock, Vehicle, AITurretShape, GameBase, RigidShape, fxFoliageReplicator, Precipitation, PhysicsShape, Camera, WheeledVehicle, SFXEmitter, ParticleEmitter, CameraBookmark, FlyingVehicle, Projectile, TurretShape, PlayerControllerComponent, Item, Splash, ConvexShape, Explosion, Lightning, AIPlayer, RigidBodyComponent, Debris, SpawnSphere, HoverVehicle, PhysicsDebris, GroundCover, TSStatic, Trigger, MeshComponent, LevelInfo, WayPoint, ProximityMine, fxShapeReplicator, Ribbon, PathCamera, CollisionTrigger, RenderMeshExample, LightBase, RenderObjectExample, ScenePolyhedralObject< SceneSimpleZone >, ScenePolyhedralObject< SceneSpace >, RenderShapeExample, AnimationComponent, Component, CameraComponent, ParticleEmitterNode, AccumulationVolume, Entity, MissionMarker, StaticShape, PhysicalZone, RibbonNode, OcclusionVolume, GroundPlane, Prefab, CameraOrbiterComponent, MissionArea, PhysicsForce, StateMachineComponent, TriggerComponent, and VehicleBlocker.
virtual void NetObject::onCameraScopeQuery (NetConnection * cr, CameraScopeQuery * camInfo) virtual
Queries the object about information used to determine scope.
Something that is 'in scope' is somehow interesting to the client.
If we are a NetConnection's scope object, it calls this method to determine how things should be scoped; basically, we tell it our field of view with camInfo, and have the opportunity to manually mark items as "in scope" as we see fit.
By default, we just mark all ghostable objects as in scope.
Parameters
cr Net connection requesting scope information.
camInfo Information about what this object can see.
Reimplemented in ShapeBase, Player, SceneObject, Entity, and CameraComponent.
void NetObject::onRemove () virtual
Called when the object is removed from the sim.
Reimplemented from SimGroup.
Reimplemented in ShapeBase, Player, TerrainBlock, Vehicle, AITurretShape, GameBase, RigidShape, fxFoliageReplicator, Precipitation, PhysicsShape, Camera, WheeledVehicle, SFXEmitter, ParticleEmitter, CameraBookmark, FlyingVehicle, Projectile, TurretShape, PlayerControllerComponent, Item, Splash, ConvexShape, Explosion, Lightning, AIPlayer, RigidBodyComponent, Debris, HoverVehicle, PhysicsDebris, GroundCover, Ribbon, TSStatic, Trigger, MeshComponent, LevelInfo, ProximityMine, fxShapeReplicator, PathCamera, CollisionTrigger, RenderMeshExample, LightBase, RenderObjectExample, RenderShapeExample, AnimationComponent, Component, CameraComponent, ParticleEmitterNode, AccumulationVolume, Entity, MissionMarker, StaticShape, PhysicalZone, RibbonNode, GroundPlane, Prefab, CameraOrbiterComponent, MissionArea, PhysicsForce, StateMachineComponent, TriggerComponent, and VehicleBlocker.
virtual U32 NetObject::packUpdate (NetConnection * conn, U32 mask, BitStream * stream) virtual
Instructs this object to pack its state for transfer over the network.
Parameters
conn Net connection being used
mask Mask indicating fields to transmit.
stream Bitstream to pack data to
Returns
Any bits which were not dealt with. The value is stored by the networking system. Don't set bits you weren't passed.
Reimplemented in ShapeBase, Player, SceneObject, TerrainBlock, MeshRoad, River, GameBase, AITurretShape, RigidShape, SceneZoneSpace, Precipitation, PhysicsShape, fxFoliageReplicator, WheeledVehicle, Camera, Lightning, Vehicle, SFXEmitter, VolumetricFog, TSStatic, NavMesh, ForestWindEmitter, CameraBookmark, TurretShape, HoverVehicle, Portal, FlyingVehicle, Splash, Item, Projectile, Component, PlayerControllerComponent, Forest, DecalRoad, RigidBodyComponent, ConvexShape, WaterObject, Entity, SpawnSphere, Marker, LevelInfo, GroundCover, MeshComponent, Trigger, OpenVRTrackedObject, SceneSimpleZone, ProximityMine, Sun, WayPoint, PathCamera, WaterBlock, CollisionComponent, fxShapeReplicator, NavPath, RenderMeshExample, LightBase, CollisionTrigger, WaterPlane, PhysicsComponent, RenderObjectExample, ParticleEmitterNode, CoverPoint, ScenePolyhedralObject< SceneSimpleZone >, ScenePolyhedralObject< SceneSpace >, AnimationComponent, RenderShapeExample, AccumulationVolume, RibbonNode, ScatterSky, CameraComponent, SkyBox, TimeOfDay, MissionMarker, StaticShape, CloudLayer, PhysicalZone, SceneSpace, BasicClouds, MissionArea, Prefab, CameraOrbiterComponent, GroundPlane, StateMachineComponent, SceneAmbientSoundObject< ScenePolyhedralObject< SceneSpace > >, SceneAmbientSoundObject< ScenePolyhedralZone >, SpotLight, VehicleBlocker, PointLight, and TriggerComponent.
virtual void NetObject::setMaskBits (U32 orMask) virtual
Used to mark a bit as dirty; ie, that its corresponding set of fields need to be transmitted next update.
Parameters
orMask Bit(s) to set
Referenced by CoverPoint::setOccupied(), Entity::setRotation(), CameraComponent::setRotOffset(), and CoverPoint::setSize().
void NetObject::setScopeAlways ()
Scope the object to all connections.
The object is marked as ScopeAlways and is immediately ghosted to all active connections. This function has no effect if the object is not marked as Ghostable.
virtual void NetObject::unpackUpdate (NetConnection * conn, BitStream * stream) virtual
Instructs this object to read state data previously packed with packUpdate.
Parameters
conn Net connection being used
stream stream to read from
Reimplemented in ShapeBase, Player, SceneObject, TerrainBlock, MeshRoad, River, GameBase, AITurretShape, RigidShape, SceneZoneSpace, Precipitation, PhysicsShape, fxFoliageReplicator, WheeledVehicle, Camera, Lightning, Vehicle, SFXEmitter, VolumetricFog, TSStatic, NavMesh, ForestWindEmitter, CameraBookmark, TurretShape, HoverVehicle, Portal, FlyingVehicle, Splash, Item, Projectile, Component, PlayerControllerComponent, Forest, DecalRoad, RigidBodyComponent, ConvexShape, WaterObject, Entity, SpawnSphere, Marker, LevelInfo, GroundCover, MeshComponent, Trigger, OpenVRTrackedObject, SceneSimpleZone, ProximityMine, Sun, WayPoint, PathCamera, WaterBlock, CollisionComponent, RenderMeshExample, fxShapeReplicator, NavPath, LightBase, RenderObjectExample, CollisionTrigger, WaterPlane, PhysicsComponent, ParticleEmitterNode, CoverPoint, RenderShapeExample, ScenePolyhedralObject< SceneSimpleZone >, ScenePolyhedralObject< SceneSpace >, AnimationComponent, AccumulationVolume, RibbonNode, ScatterSky, CameraComponent, SkyBox, TimeOfDay, MissionMarker, StaticShape, CloudLayer, PhysicalZone, SceneSpace, BasicClouds, MissionArea, Prefab, CameraOrbiterComponent, GroundPlane, StateMachineComponent, SceneAmbientSoundObject< ScenePolyhedralObject< SceneSpace > >, SceneAmbientSoundObject< ScenePolyhedralZone >, SpotLight, VehicleBlocker, PointLight, and TriggerComponent.
Member Data Documentation
SimObjectPtr<NetObject> NetObject::mClientObject protected
Pointer to the client object on a local connection.
See also
getClientObject
GhostInfo* NetObject::mFirstObjectRef protected
Head of a linked list storing GhostInfos referencing this NetObject.
BitSet32 NetObject::mNetFlags protected
Flag values from NetFlags.
Referenced by fxShapeReplicatedStatic::touchNetFlags().
U32 NetObject::mNetIndex protected
The index of this ghost in the GhostManager on the server.
SimObjectPtr<NetObject> NetObject::mServerObject protected
Pointer to the server object on a local connection.
See also
getServerObject
Copyright © GarageGames, LLC. All Rights Reserved.