PlaneF Class Reference
Main Modules Class List Namespace List Online
PlaneF Class Reference
A 3D plane defined by a normal and a distance along the normal.
#include <math/mPlane.h>
Public Member Functions
F32 distToPlane (const Point3F &cp) const
Return the distance of the given point from the plane.
const Point3F & getNormal () const
Return the plane's normal.
Point3F getPosition () const
Return the plane's position.
void invert ()
bool isHorizontal () const
bool isParallelTo (const PlaneF &plane, F32 epsilon=POINT_EPSILON) const
bool isPerpendicularTo (const PlaneF &plane, F32 epsilon=POINT_EPSILON) const
bool isVertical () const
void neg ()
Point3F project (const Point3F &pt) const
Project the given point onto the plane.
void shiftX (F32 xx)
void shiftY (F32 yy)
void shiftZ (F32 zz)
Initialization
PlaneF ()
PlaneF (const Point3F &p, const Point3F &n)
PlaneF (F32 _x, F32 _y, F32 _z, F32 _d)
NOTE: d is the NEGATIVE distance along the xyz normal.
PlaneF (const Point3F &j, const Point3F &k, const Point3F &l)
void set (F32 _x, F32 _y, F32 _z)
void set (F32 _x, F32 _y, F32 _z, F32 _d)
NOTE: d is the NEGATIVE distance along the xyz normal.
void set (const Point3F &p, const Point3F &n)
void set (const Point3F &k, const Point3F &j, const Point3F &l)
void setPoint (const Point3F &p)
Calculate the coefficients of the plane passing through a point with the given normal.
void setXY (F32 zz)
void setYZ (F32 xx)
void setXZ (F32 yy)
void setXY (const Point3F &P, F32 dir)
void setYZ (const Point3F &P, F32 dir)
void setXZ (const Point3F &P, F32 dir)
Clipping
U32 clipPolygon (const Point3F *inVertices, U32 inNumVertices, Point3F *outVertices) const
Clip a convex polygon by the plane.
bool clipSegment (const Point3F &start, const Point3F &end, Point3F &outNewEnd) const
Clip a line segment by the plane.
Public Member Functions inherited from Point3F
Point3F ()
Point3F (const Point3F &)
Point3F (F32 _x, F32 _y, F32 _z)
Point3F (F32 xyz)
Point2F asPoint2F () const
Returns the x and y coords as a Point2F.
void convolve (const Point3F &)
void convolveInverse (const Point3F &)
bool equal (const Point3F &compare, F32 epsilon=POINT_EPSILON) const
U32 getGreatestComponentIndex () const
U32 getLeastComponentIndex () const
void interpolate (const Point3F &, const Point3F &, F32)
bool isUnitLength () const
bool isZero () const
F32 least () const
Returns the smallest absolute value.
F32 len () const
F32 lenSquared () const
F32 magnitudeSafe () const
F32 most () const
Returns the greatest absolute value.
void neg ()
void normalize ()
void normalize (F32 val)
void normalizeSafe ()
bool operator!= (const Point3F &) const
Point3F operator* (F32) const
Point3F operator* (const Point3F &) const
Point3F & operator*= (F32)
Point3F & operator*= (const Point3F &)
Point3F operator+ (const Point3F &) const
Point3F & operator+= (const Point3F &)
Point3F operator- (const Point3F &) const
Point3F operator- () const
Point3F & operator-= (const Point3F &)
Point3F operator/ (F32) const
Point3F operator/ (const Point3F &) const
Point3F & operator/= (F32)
Point3F & operator/= (const Point3F &)
Point3F & operator= (const Point3D &)
bool operator== (const Point3F &) const
void set (F32 xyz)
void set (F32 _x, F32 _y, F32 _z)
void set (const Point3F &)
void setMax (const Point3F &)
void setMin (const Point3F &)
void zero ()
Public Attributes
F32 d
NEGATIVE distance along the xyz normal.
Public Attributes inherited from Point3F
F32 x
F32 y
F32 z
Intersection
enum Side {
Front = 1,
On = 0,
Back = -1
}
Side whichSide (const Point3F &cp) const
Compute on which side of the plane the given point lies.
Side whichSide (const SphereF &sphere) const
Compute which side the given sphere lies on.
Side whichSide (const Box3F &aabb) const
Compute which side the given AABB lies on.
Side whichSide (const OrientedBox3F &obb) const
Compute which side the given OBB lies on.
Side whichSideBox (const Point3F &center, const Point3F &axisx, const Point3F &axisy, const Point3F &axisz) const
Compute which side the given box lies on.
F32 intersect (const Point3F &start, const Point3F &end) const
Compute the distance at which the ray traveling from start in the direction of intersects the plane.
bool intersect (const Point3F &start, const Point3F &dir, Point3F *outHit) const
bool intersect (const PlaneF &plane, Point3F &outLineOrigin, Point3F &outLineDirection) const
Compute the intersection between two planes.
Additional Inherited Members
Static Public Attributes inherited from Point3F
static const Point3F Max
static const Point3F Min
static const Point3F One
static const Point3F UnitX
static const Point3F UnitY
static const Point3F UnitZ
static const Point3F Zero
Detailed Description
A 3D plane defined by a normal and a distance along the normal.
Note
The distance is stored negative.
Member Enumeration Documentation
enum PlaneF::Side
Enumerator
Front
On
Back
Constructor & Destructor Documentation
PlaneF::PlaneF () inline
References distToPlane(), invert(), neg(), project(), setPoint(), setXY(), setXZ(), setYZ(), shiftX(), shiftY(), and shiftZ().
PlaneF::PlaneF (const Point3F & p, const Point3F & n) inline
PlaneF::PlaneF (F32 _x, F32 _y, F32 _z, F32 _d) inline
NOTE: d is the NEGATIVE distance along the xyz normal.
PlaneF::PlaneF (const Point3F & j, const Point3F & k, const Point3F & l) inline
Member Function Documentation
U32 PlaneF::clipPolygon (const Point3F * inVertices, U32 inNumVertices, Point3F * outVertices) const
Clip a convex polygon by the plane.
The resulting polygon will be the input polygon minus the part on the negative side of the plane. The input polygon must be convex and inVertices must be in CCW or CW order.
Parameters
inVertices Array holding the vertices of the input polygon.
inNumVertices Number of vertices in inVertices.
outVertices Array to hold the vertices of the clipped polygon. Must have space for one additional vertex in case the polygon is split by the plane such that an additional vertex appears. Must not be the same as inVertices.
Returns
Number of vertices in the clipped polygon, i.e. number of vertices in outVertices.
Note
Be aware that if the polygon fully lies on the negative side of the plane, the resulting outNumVertices will be zero, i.e. no polygon will result from the clip.
Referenced by PlaneSet< T >::clipPolygon().
bool PlaneF::clipSegment (const Point3F & start, const Point3F & end, Point3F & outNewEnd) const
Clip a line segment by the plane.
Parameters
start Start point of the line segment.
end End point of the line segment.
outNewEnd New end point if there is an intersection with the plane.
Returns
True
Referenced by PolyhedronImpl< Base >::constructIntersection().
F32 PlaneF::distToPlane (const Point3F & cp) const inline
Return the distance of the given point from the plane.
References d, Point3F::x, Point3F::y, and Point3F::z.
Referenced by intersect(), PlaneD::intersect(), PlaneF(), project(), PlaneD::project(), whichSide(), PlaneD::whichSide(), whichSideBox(), and PlaneD::whichSideBox().
const Point3F& PlaneF::getNormal () const inline
Return the plane's normal.
Point3F PlaneF::getPosition () const inline
Return the plane's position.
References d, isHorizontal(), isParallelTo(), isPerpendicularTo(), isVertical(), Point3F::Point3F(), Point3F::x, Point3F::y, and Point3F::z.
F32 PlaneF::intersect (const Point3F & start, const Point3F & end) const inline
Compute the distance at which the ray traveling from start in the direction of intersects the plane.
Parameters
start Starting point of the ray.
end Point in the direction of which the ray travels from start.
Returns
The distance (as a fraction/multiple of the length of the vector between start and end) at which the ray intersects the plane or PARALLEL_PLANE if the ray is parallel to the plane.
References distToPlane().
Referenced by PlaneSet< T >::clipSegment().
bool PlaneF::intersect (const Point3F & start, const Point3F & dir, Point3F * outHit) const inline
References distToPlane().
bool PlaneF::intersect (const PlaneF & plane, Point3F & outLineOrigin, Point3F & outLineDirection) const
Compute the intersection between two planes.
Parameters
plane Plane to intersect with.
outLineOrigin Used to store the origin of the resulting intersection line.
outLineDirection Used to store the direction of the resulting intersection line.
Returns
True if there is an intersection or false if the two planes are coplanar.
void PlaneF::invert () inline
References d, Point3F::x, Point3F::y, and Point3F::z.
Referenced by neg(), PlaneD::neg(), and PlaneF().
bool PlaneF::isHorizontal () const inline
References Point3F::x, and Point3F::y.
Referenced by getPosition().
bool PlaneF::isParallelTo (const PlaneF & plane, F32 epsilon = POINT_EPSILON) const
Referenced by getPosition().
bool PlaneF::isPerpendicularTo (const PlaneF & plane, F32 epsilon = POINT_EPSILON) const
Referenced by getPosition().
bool PlaneF::isVertical () const inline
References Point3F::x, Point3F::y, and Point3F::z.
Referenced by getPosition().
void PlaneF::neg () inline
References invert().
Referenced by PlaneF().
Point3F PlaneF::project (const Point3F & pt) const inline
Project the given point onto the plane.
References distToPlane(), Point3F::Point3F(), Point3F::x, Point3F::y, and Point3F::z.
Referenced by PlaneF().
void PlaneF::set (F32 _x, F32 _y, F32 _z) inline
References Point3F::set().
Referenced by WaterFogData::WaterFogData().
void PlaneF::set (F32 _x, F32 _y, F32 _z, F32 _d) inline
NOTE: d is the NEGATIVE distance along the xyz normal.
References d, and Point3F::set().
void PlaneF::set (const Point3F & p, const Point3F & n) inline
References d, Point3F::normalize(), Point3F::x, Point3F::y, and Point3F::z.
void PlaneF::set (const Point3F & k, const Point3F & j, const Point3F & l) inline
References d, Point3F::x, Point3F::y, and Point3F::z.
void PlaneF::setPoint (const Point3F & p) inline
Calculate the coefficients of the plane passing through a point with the given normal.
References d, Point3F::x, Point3F::y, and Point3F::z.
Referenced by PlaneF().
void PlaneF::setXY (F32 zz) inline
References d, Point3F::x, Point3F::y, and Point3F::z.
Referenced by PlaneF().
void PlaneF::setXY (const Point3F & P, F32 dir) inline
References d, Point3F::x, Point3F::y, and Point3F::z.
void PlaneF::setXZ (F32 yy) inline
References d, Point3F::x, Point3F::y, and Point3F::z.
Referenced by PlaneF().
void PlaneF::setXZ (const Point3F & P, F32 dir) inline
References d, Point3F::x, Point3F::y, and Point3F::z.
void PlaneF::setYZ (F32 xx) inline
References d, Point3F::x, Point3F::y, and Point3F::z.
Referenced by PlaneF().
void PlaneF::setYZ (const Point3F & P, F32 dir) inline
References d, Point3F::x, Point3F::y, and Point3F::z.
void PlaneF::shiftX (F32 xx) inline
References d, and Point3F::x.
Referenced by PlaneF().
void PlaneF::shiftY (F32 yy) inline
References d, and Point3F::y.
Referenced by PlaneF().
void PlaneF::shiftZ (F32 zz) inline
References d, and Point3F::z.
Referenced by PlaneF().
PlaneF::Side PlaneF::whichSide (const Point3F & cp) const inline
Compute on which side of the plane the given point lies.
References Back, distToPlane(), Front, and On.
Referenced by PlaneSet< T >::_testOverlap(), PolyhedronImpl< Base >::constructIntersection(), PolyhedronBoxIntersector< Polyhedron >::test(), and whichSide().
PlaneF::Side PlaneF::whichSide (const SphereF & sphere) const inline
Compute which side the given sphere lies on.
References Back, SphereF::center, distToPlane(), Front, On, and SphereF::radius.
PlaneF::Side PlaneF::whichSide (const Box3F & aabb) const inline
Compute which side the given AABB lies on.
References Back, Front, Box3F::maxExtents, Box3F::minExtents, On, whichSide(), Point3F::x, Point3F::y, and Point3F::z.
PlaneF::Side PlaneF::whichSide (const OrientedBox3F & obb) const inline
Compute which side the given OBB lies on.
References Back, distToPlane(), Front, OrientedBox3F::getAxis(), OrientedBox3F::getCenter(), OrientedBox3F::getHalfExtents(), On, Point3F::x, Point3F::y, and Point3F::z.
PlaneF::Side PlaneF::whichSideBox (const Point3F & center, const Point3F & axisx, const Point3F & axisy, const Point3F & axisz) const inline
Compute which side the given box lies on.
Parameters
center Center point.
axisx X-Axis vector. Length is box half-extent along X.
axisy Y-Axis vector. Length is box half-extent along Y.
axisz Z-Axis vector. Length is box half-extent along Z.
Returns
Side that the given box is on.
References Back, distToPlane(), Front, and On.
Member Data Documentation
F32 PlaneF::d
NEGATIVE distance along the xyz normal.
Referenced by distToPlane(), PlaneD::distToPlane(), getPosition(), invert(), PlaneD::invert(), PlaneD::PlaneD(), set(), PlaneD::set(), setPoint(), PlaneD::setPoint(), setXY(), PlaneD::setXY(), setXZ(), PlaneD::setXZ(), setYZ(), PlaneD::setYZ(), shiftX(), PlaneD::shiftX(), shiftY(), PlaneD::shiftY(), shiftZ(), PlaneD::shiftZ(), PlaneSet< T >::testPlanes(), and ScenePolyhedralObject< Base, P >::writeFields().
Copyright © GarageGames, LLC. All Rights Reserved.