x86UNIXPlatformState Class Reference
Main Modules Class List Namespace List Online
x86UNIXPlatformState Class Reference
#include <platformX86UNIX/x86UNIXState.h>
Public Member Functions
x86UNIXPlatformState ()
bool getCDAudioEnabled ()
S32 getDesktopBpp ()
Point2I getDesktopSize ()
Display * getDisplayPointer ()
bool getDSleep ()
const char * getExeName ()
const char * getExePathName ()
int getScreenNumber ()
Screen * getScreenPointer ()
bool getUseRedirect ()
Window getWindow ()
const char * getWindowName ()
Point2I & getWindowSize ()
bool isDedicated ()
bool isXWindowsRunning ()
void setCDAudioEnabled (bool enabled)
void setDedicated (bool dedicated)
void setDesktopBpp (S32 bpp)
void setDesktopSize (S32 horizontal, S32 vertical)
void setDisplayPointer (Display *displayPointer)
void setDSleep (bool enabled)
void setExePathName (const char *exePathName)
void setScreenNumber (int newNumber)
void setScreenPointer (Screen *newScreenPointer)
void setUseRedirect (bool enabled)
void setWindow (Window newWindow)
void setWindowActive (bool windowActive)
void setWindowCreated (bool windowCreated)
void setWindowLocked (bool windowLocked)
void setWindowName (const char *windowName)
void setWindowSize (S32 horizontal, S32 vertical)
void setWindowSize (Point2I size)
void setXWindowsRunning (bool running)
bool windowActive ()
bool windowCreated ()
bool windowLocked ()
Public Attributes
U32 currentTime
Constructor & Destructor Documentation
x86UNIXPlatformState::x86UNIXPlatformState () inline
References Point2I::set(), setExePathName(), and setWindowName().
Member Function Documentation
bool x86UNIXPlatformState::getCDAudioEnabled () inline
S32 x86UNIXPlatformState::getDesktopBpp () inline
Point2I x86UNIXPlatformState::getDesktopSize () inline
Display* x86UNIXPlatformState::getDisplayPointer () inline
Referenced by DisplayPtrManager::getDisplayPointer().
bool x86UNIXPlatformState::getDSleep () inline
const char* x86UNIXPlatformState::getExeName () inline
const char* x86UNIXPlatformState::getExePathName () inline
int x86UNIXPlatformState::getScreenNumber () inline
Screen* x86UNIXPlatformState::getScreenPointer () inline
bool x86UNIXPlatformState::getUseRedirect () inline
Window x86UNIXPlatformState::getWindow () inline
const char* x86UNIXPlatformState::getWindowName () inline
Point2I& x86UNIXPlatformState::getWindowSize () inline
bool x86UNIXPlatformState::isDedicated () inline
bool x86UNIXPlatformState::isXWindowsRunning () inline
void x86UNIXPlatformState::setCDAudioEnabled (bool enabled) inline
void x86UNIXPlatformState::setDedicated (bool dedicated) inline
void x86UNIXPlatformState::setDesktopBpp (S32 bpp) inline
void x86UNIXPlatformState::setDesktopSize (S32 horizontal, S32 vertical) inline
References Point2I::set().
void x86UNIXPlatformState::setDisplayPointer (Display * displayPointer) inline
void x86UNIXPlatformState::setDSleep (bool enabled) inline
void x86UNIXPlatformState::setExePathName (const char * exePathName) inline
Referenced by x86UNIXPlatformState().
void x86UNIXPlatformState::setScreenNumber (int newNumber) inline
void x86UNIXPlatformState::setScreenPointer (Screen * newScreenPointer) inline
void x86UNIXPlatformState::setUseRedirect (bool enabled) inline
void x86UNIXPlatformState::setWindow (Window newWindow) inline
void x86UNIXPlatformState::setWindowActive (bool windowActive) inline
References windowActive().
void x86UNIXPlatformState::setWindowCreated (bool windowCreated) inline
References windowCreated().
void x86UNIXPlatformState::setWindowLocked (bool windowLocked) inline
References windowLocked().
void x86UNIXPlatformState::setWindowName (const char * windowName) inline
Referenced by x86UNIXPlatformState().
void x86UNIXPlatformState::setWindowSize (S32 horizontal, S32 vertical) inline
References Point2I::set().
void x86UNIXPlatformState::setWindowSize (Point2I size) inline
void x86UNIXPlatformState::setXWindowsRunning (bool running) inline
bool x86UNIXPlatformState::windowActive () inline
Referenced by setWindowActive().
bool x86UNIXPlatformState::windowCreated () inline
Referenced by setWindowCreated().
bool x86UNIXPlatformState::windowLocked () inline
Referenced by setWindowLocked().
Member Data Documentation
U32 x86UNIXPlatformState::currentTime
Copyright © GarageGames, LLC. All Rights Reserved.