Torque::UUID Class Reference
Main Modules Class List Namespace List Online
Torque::UUID Class Reference
A universally unique identifier.
#include <core/util/uuid.h>
Public Types
typedef void Parent
Public Member Functions
UUID ()
bool fromString (const char *str)
Parse a text string generated by UUIDToString back into a universally unique identifier (UUID).
void generate ()
Generate a new universally unique identifier (UUID).
U32 getHash () const
Return a hash value for this UUID.
bool isNull () const
bool operator!= (const UUID &uuid) const
bool operator== (const UUID &uuid) const
String toString () const
Convert the given universally unique identifier to a printed string representation.
Protected Attributes
U32 a
U16 b
U16 c
U8 d
U8 e
U8 f [6]
Static Protected Attributes
static UUID smNull
Detailed Description
A universally unique identifier.
Member Typedef Documentation
typedef void Torque::UUID::Parent
Constructor & Destructor Documentation
Torque::UUID::UUID () inline
References dMemset().
Member Function Documentation
bool Torque::UUID::fromString (const char * str)
Parse a text string generated by UUIDToString back into a universally unique identifier (UUID).
Referenced by isNull().
void Torque::UUID::generate ()
Generate a new universally unique identifier (UUID).
Referenced by isNull().
U32 Torque::UUID::getHash () const
Return a hash value for this UUID.
Referenced by DictHash::hash(), and isNull().
bool Torque::UUID::isNull (void) const inline
References fromString(), generate(), getHash(), and toString().
bool Torque::UUID::operator!= (const UUID & uuid) const inline
bool Torque::UUID::operator== (const UUID & uuid) const inline
References dMemcmp().
String Torque::UUID::toString () const
Convert the given universally unique identifier to a printed string representation.
Referenced by isNull().
Member Data Documentation
U32 Torque::UUID::a protected
U16 Torque::UUID::b protected
U16 Torque::UUID::c protected
U8 Torque::UUID::d protected
U8 Torque::UUID::e protected
U8 Torque::UUID::f[6] protected
UUID Torque::UUID::smNull static protected
Copyright © GarageGames, LLC. All Rights Reserved.