EngineEnumTable Class Reference
Main Modules Class List Namespace List Online
EngineEnumTable Class Reference
Table of values for an enumeration or bitfield type.
#include <console/engineTypeInfo.h>
Classes
struct Value
A value in an enumeration.
Public Member Functions
EngineEnumTable (U32 numValues, const Value *values)
U32 getNumValues () const
Return the number of Values in this enumeration/bitfield.
const Value & operator[] (U32 index) const
Get the enum value at the given index.
Protected Attributes
U32 mNumValues
Number of values in this enumeration.
const Value * mValues
Records for all the enum values.
Detailed Description
Table of values for an enumeration or bitfield type.
Constructor & Destructor Documentation
EngineEnumTable::EngineEnumTable (U32 numValues, const Value * values) inline
Member Function Documentation
U32 EngineEnumTable::getNumValues () const inline
Return the number of Values in this enumeration/bitfield.
References mNumValues.
Referenced by EnumConsoleBaseType::getData(), operator[](), and EnumConsoleBaseType::setData().
const Value& EngineEnumTable::operator[] (U32 index) const inline
Get the enum value at the given index.
References getNumValues().
Member Data Documentation
U32 EngineEnumTable::mNumValues protected
Number of values in this enumeration.
Referenced by getNumValues().
const Value* EngineEnumTable::mValues protected
Records for all the enum values.
Copyright © GarageGames, LLC. All Rights Reserved.