rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator > Class Template Reference
Main Modules Class List Namespace List Online
rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator > Class Template Reference
JSON writer.
#include <persistence/rapidjson/writer.h>
Classes
struct Level
Information for each nested level.
Public Types
typedef SourceEncoding::Ch Ch
Public Member Functions
Writer (OutputStream &os, Allocator *allocator=0, size_t levelDepth=kDefaultLevelDepth)
Writer & String (const Ch *str)
Simpler but slower overload.
Writer & Null ()
Writer & Bool (bool b)
Writer & Int (int i)
Writer & Uint (unsigned u)
Writer & Int64 (int64_t i64)
Writer & Uint64 (uint64_t u64)
Writer & Double (double d)
Writer & String (const Ch *str, SizeType length, bool copy=false)
Writer & StartObject ()
Writer & EndObject (SizeType memberCount=0)
Writer & StartArray ()
Writer & EndArray (SizeType elementCount=0)
Protected Member Functions
void Prefix (Type type)
void WriteBool (bool b)
void WriteDouble (double d)
void WriteEndArray ()
void WriteEndObject ()
void WriteInt (int i)
void WriteInt64 (int64_t i64)
void WriteNull ()
void WriteStartArray ()
void WriteStartObject ()
void WriteString (const Ch *str, SizeType length)
void WriteUint (unsigned u)
void WriteUint64 (uint64_t u64)
Protected Attributes
internal::Stack< Allocator > level_stack_
OutputStream & os_
Static Protected Attributes
static const size_t kDefaultLevelDepth = 32
Detailed Description
template<typename OutputStream, typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>>
class rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >
JSON writer.
Writer implements the concept Handler. It generates JSON text by events to an output os.
User may programmatically calls the functions of a writer to generate JSON text.
On the other side, a writer can also be passed to objects that generates events,
for example Reader::Parse() and Document::Accept().
Template Parameters
OutputStream Type of output stream.
SourceEncoding Encoding of both source strings.
TargetEncoding Encoding of and output stream.
Member Typedef Documentation
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> typedef SourceEncoding::Ch rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Ch
Constructor & Destructor Documentation
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Writer (OutputStream & os, Allocator * allocator = 0, size_t levelDepth = kDefaultLevelDepth) inline
Member Function Documentation
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> Writer& rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Bool (bool b) inline
References rapidjson::kFalseType, rapidjson::kTrueType, rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Prefix(), and rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteBool().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> Writer& rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Double (double d) inline
References rapidjson::kNumberType, rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Prefix(), and rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteDouble().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> Writer& rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::EndArray (SizeType elementCount = 0) inline
References rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::level_stack_, rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::os_, and rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteEndArray().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> Writer& rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::EndObject (SizeType memberCount = 0) inline
References rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::level_stack_, rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::os_, and rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteEndObject().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> Writer& rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Int (int i) inline
References rapidjson::kNumberType, rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Prefix(), and rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteInt().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> Writer& rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Int64 (int64_t i64) inline
References rapidjson::kNumberType, rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Prefix(), and rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteInt64().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> Writer& rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Null () inline
References rapidjson::kNullType, rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Prefix(), and rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteNull().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> void rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Prefix (Type type) inline protected
References rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Level::inArray, rapidjson::kArrayType, rapidjson::kObjectType, rapidjson::kStringType, rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::level_stack_, rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::os_, and rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Level::valueCount.
Referenced by rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Bool(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Double(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Int(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Int64(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Null(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::StartArray(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::StartObject(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::String(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Uint(), and rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Uint64().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> Writer& rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::StartArray () inline
References rapidjson::kArrayType, rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::level_stack_, rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Prefix(), and rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteStartArray().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> Writer& rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::StartObject () inline
References rapidjson::kObjectType, rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::level_stack_, rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Prefix(), and rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteStartObject().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> Writer& rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::String (const Ch * str, SizeType length, bool copy = false) inline
References rapidjson::kStringType, rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Prefix(), and rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteString().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> Writer& rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::String (const Ch * str) inline
Simpler but slower overload.
References rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::String(), and rapidjson::internal::StrLen().
Referenced by rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::String().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> Writer& rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Uint (unsigned u) inline
References rapidjson::kNumberType, rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Prefix(), and rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteUint().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> Writer& rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Uint64 (uint64_t u64) inline
References rapidjson::kNumberType, rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Prefix(), and rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteUint64().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> void rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteBool (bool b) inline protected
References rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::os_.
Referenced by rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Bool(), and rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Bool().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> void rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteDouble (double d) inline protected
References rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::os_.
Referenced by rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Double(), and rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Double().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> void rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteEndArray () inline protected
References rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::os_.
Referenced by rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::EndArray(), and rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::EndArray().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> void rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteEndObject () inline protected
References rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::os_.
Referenced by rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::EndObject(), and rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::EndObject().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> void rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteInt (int i) inline protected
References rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::os_, and rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteUint().
Referenced by rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Int(), and rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Int().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> void rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteInt64 (int64_t i64) inline protected
References rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::os_, and rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteUint64().
Referenced by rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Int64(), and rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Int64().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> void rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteNull () inline protected
References rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::os_.
Referenced by rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Null(), and rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Null().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> void rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteStartArray () inline protected
References rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::os_.
Referenced by rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::StartArray(), and rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::StartArray().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> void rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteStartObject () inline protected
References rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::os_.
Referenced by rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::StartObject(), and rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::StartObject().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> void rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteString (const Ch * str, SizeType length) inline protected
References rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::os_, rapidjson::GenericStringStream< Encoding >::Peek(), rapidjson::GenericStringStream< Encoding >::Take(), rapidjson::GenericStringStream< Encoding >::Tell(), and rapidjson::Transcoder< SourceEncoding, TargetEncoding >::Transcode().
Referenced by rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::String(), and rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::String().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> void rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteUint (unsigned u) inline protected
References rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::os_.
Referenced by rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Uint(), rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Uint(), and rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteInt().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> void rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteUint64 (uint64_t u64) inline protected
References rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::os_.
Referenced by rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Uint64(), rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Uint64(), and rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteInt64().
Member Data Documentation
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> const size_t rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::kDefaultLevelDepth = 32 static protected
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> internal::Stack<Allocator> rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::level_stack_ protected
Referenced by rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::EndArray(), rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::EndArray(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::EndObject(), rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::EndObject(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Prefix(), rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::PrettyPrefix(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::StartArray(), rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::StartArray(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::StartObject(), rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::StartObject(), and rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteIndent().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> OutputStream& rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::os_ protected
Referenced by rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::EndArray(), rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::EndArray(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::EndObject(), rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::EndObject(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Prefix(), rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::PrettyPrefix(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteBool(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteDouble(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteEndArray(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteEndObject(), rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteIndent(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteInt(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteInt64(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteNull(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteStartArray(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteStartObject(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteString(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteUint(), and rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteUint64().
Copyright © GarageGames, LLC. All Rights Reserved.