LightManager Class Reference
Main Modules Class List Namespace List Online
LightManager Class Reference abstract
#include <lighting/lightManager.h>
Public Types
enum SpecialLightTypesEnum {
slSunLightType,
slSpecialLightTypesCount
}
Public Member Functions
LightManager (const char *name, const char *id)
virtual ~LightManager ()
virtual void activate (SceneManager *sceneManager)
virtual void deactivate ()
void getAllUnsortedLights (Vector< LightInfo * > *list) const
Returns all unsorted and un-scored lights (both global and local).
virtual LightInfo * getDefaultLight ()
const char * getId () const
Return an id string used to load different versions of light manager specific assets.
const char * getName () const
Return an id string used to load different versions of light manager specific assets.
virtual AvailableSLInterfaces * getSceneLightingInterface ()
SceneManager * getSceneManager ()
virtual LightInfo * getSpecialLight (SpecialLightTypesEnum type, bool useDefault=true)
Returns the special light or the default light if useDefault is true.
virtual bool isActive () const
Returns true if this light manager is active.
virtual bool isCompatible () const =0
virtual bool lightScene (const char *callback, const char *param)
Called when the static scene lighting (aka lightmaps) should be computed.
virtual void registerGlobalLight (LightInfo *light, SimObject *obj)
virtual void registerGlobalLights (const Frustum *frustum, bool staticlighting)
virtual void registerLocalLight (LightInfo *light)
virtual void setLightInfo (ProcessedMaterial *pmat, const Material *mat, const SceneData &sgData, const SceneRenderState *state, U32 pass, GFXShaderConstBuffer *shaderConsts)=0
Sets shader constants / textures for light infos.
virtual void setSpecialLight (SpecialLightTypesEnum type, LightInfo *light)
Set a special light type.
virtual bool setTextureStage (const SceneData &sgData, const U32 currTexFlag, const U32 textureSlot, GFXShaderConstBuffer *shaderConsts, ShaderConstHandles *handles)=0
Allows us to set textures during the Material::setTextureStage call, return true if we've done work.
virtual void unregisterAllLights ()
virtual void unregisterGlobalLight (LightInfo *light)
virtual void unregisterLocalLight (LightInfo *light)
Static Public Member Functions
static LightInfo * createLightInfo (LightInfo *light=NULL)
static LightManager * findByName (const char *name)
static LightManager * getActiveLM ()
Returns the active LM.
static void getLightManagerNames (String *outString)
Returns a tab seperated list of available light managers.
static void initLightFields ()
Static Public Attributes
static Signal< void(const char *, bool)> smActivateSignal
The light manager activation signal.
Protected Member Functions
virtual void _addLightInfoEx (LightInfo *lightInfo)=0
Attaches any LightInfoEx data for this manager to the light info object.
RenderDeferredMgr * _findDeferredRenderBin ()
Find the pre-pass render bin on the scene's default render pass.
virtual void _initLightFields ()=0
Static Protected Member Functions
static LightManagerMap & _getLightManagers ()
Returns the static light manager map.
static void _update4LightConsts (const SceneData &sgData, GFXShaderConstHandle *lightPositionSC, GFXShaderConstHandle *lightDiffuseSC, GFXShaderConstHandle *lightAmbientSC, GFXShaderConstHandle *lightInvRadiusSqSC, GFXShaderConstHandle *lightSpotDirSC, GFXShaderConstHandle *lightSpotAngleSC, GFXShaderConstHandle *lightSpotFalloffSC, GFXShaderConstBuffer *shaderConsts)
This helper function sets the shader constansts for the stock 4 light forward lighting code.
Protected Attributes
AvailableSLInterfaces * mAvailableSLInterfaces
The scene lighting interfaces for lightmap generation.
Point3F mCullPos
The root culling position used for special sun light placement.
LightInfo * mDefaultLight
A dummy default light used when no lights happen to be registered with the manager.
const String mId
The constant light manager identifier initialized in the constructor.
bool mIsActive
Is true if this light manager has been activated.
const String mName
The constant light manager name initialized in the constructor.
LightInfoList mRegisteredLights
The list of global registered lights which is initialized before the scene is rendered.
SceneManager * mSceneManager
The scene graph the light manager is associated with.
LightInfo * mSpecialLights [slSpecialLightTypesCount]
The registered special light list.
Static Protected Attributes
static LightManager * smActiveLM
The current active light manager.
Member Enumeration Documentation
enum LightManager::SpecialLightTypesEnum
Enumerator
slSunLightType
slSpecialLightTypesCount
Constructor & Destructor Documentation
LightManager::LightManager (const char * name, const char * id)
virtual LightManager::~LightManager () virtual
Member Function Documentation
virtual void LightManager::_addLightInfoEx (LightInfo * lightInfo) protected pure virtual
Attaches any LightInfoEx data for this manager to the light info object.
Implemented in AdvancedLightManager, and BasicLightManager.
RenderDeferredMgr* LightManager::_findDeferredRenderBin () protected
Find the pre-pass render bin on the scene's default render pass.
static LightManagerMap& LightManager::_getLightManagers () static protected
Returns the static light manager map.
virtual void LightManager::_initLightFields () protected pure virtual
Implemented in AdvancedLightManager, and BasicLightManager.
static void LightManager::_update4LightConsts (const SceneData & sgData, GFXShaderConstHandle * lightPositionSC, GFXShaderConstHandle * lightDiffuseSC, GFXShaderConstHandle * lightAmbientSC, GFXShaderConstHandle * lightInvRadiusSqSC, GFXShaderConstHandle * lightSpotDirSC, GFXShaderConstHandle * lightSpotAngleSC, GFXShaderConstHandle * lightSpotFalloffSC, GFXShaderConstBuffer * shaderConsts) static protected
This helper function sets the shader constansts for the stock 4 light forward lighting code.
virtual void LightManager::activate (SceneManager * sceneManager) virtual
Reimplemented in AdvancedLightManager, and BasicLightManager.
Referenced by getSceneManager().
static LightInfo* LightManager::createLightInfo (LightInfo * light = NULL) static
virtual void LightManager::deactivate () virtual
Reimplemented in AdvancedLightManager, and BasicLightManager.
Referenced by getSceneManager().
static LightManager* LightManager::findByName (const char * name) static
static LightManager* LightManager::getActiveLM () inline static
Returns the active LM.
References smActiveLM.
void LightManager::getAllUnsortedLights (Vector< LightInfo * > * list) const
Returns all unsorted and un-scored lights (both global and local).
Referenced by getSceneManager().
virtual LightInfo* LightManager::getDefaultLight () virtual
Referenced by getSceneManager().
const char* LightManager::getId () const inline
Return an id string used to load different versions of light manager specific assets.
It shoud be short, contain no spaces, and be safe for filename use.
References String::c_str(), and mId.
static void LightManager::getLightManagerNames (String * outString) static
Returns a tab seperated list of available light managers.
const char* LightManager::getName () const inline
Return an id string used to load different versions of light manager specific assets.
It shoud be short, contain no spaces, and be safe for filename use.
References String::c_str(), and mName.
virtual AvailableSLInterfaces* LightManager::getSceneLightingInterface () virtual
Referenced by getSceneManager().
SceneManager* LightManager::getSceneManager () inline
References activate(), deactivate(), getAllUnsortedLights(), getDefaultLight(), getSceneLightingInterface(), getSpecialLight(), isCompatible(), lightScene(), mSceneManager, registerGlobalLight(), registerGlobalLights(), registerLocalLight(), setLightInfo(), setSpecialLight(), setTextureStage(), unregisterAllLights(), unregisterGlobalLight(), and unregisterLocalLight().
virtual LightInfo* LightManager::getSpecialLight (SpecialLightTypesEnum type, bool useDefault = true) virtual
Returns the special light or the default light if useDefault is true.
See also
getDefaultLight
Referenced by getSceneManager().
static void LightManager::initLightFields () static
virtual bool LightManager::isActive () const inline virtual
Returns true if this light manager is active.
References mIsActive.
virtual bool LightManager::isCompatible () const pure virtual
Implemented in AdvancedLightManager, and BasicLightManager.
Referenced by getSceneManager().
virtual bool LightManager::lightScene (const char * callback, const char * param) virtual
Called when the static scene lighting (aka lightmaps) should be computed.
Referenced by getSceneManager().
virtual void LightManager::registerGlobalLight (LightInfo * light, SimObject * obj) virtual
Reimplemented in AdvancedLightManager.
Referenced by getSceneManager().
virtual void LightManager::registerGlobalLights (const Frustum * frustum, bool staticlighting) virtual
Referenced by getSceneManager().
virtual void LightManager::registerLocalLight (LightInfo * light) virtual
Referenced by getSceneManager().
virtual void LightManager::setLightInfo (ProcessedMaterial * pmat, const Material * mat, const SceneData & sgData, const SceneRenderState * state, U32 pass, GFXShaderConstBuffer * shaderConsts) pure virtual
Sets shader constants / textures for light infos.
Implemented in AdvancedLightManager, and BasicLightManager.
Referenced by getSceneManager().
virtual void LightManager::setSpecialLight (SpecialLightTypesEnum type, LightInfo * light) virtual
Set a special light type.
Referenced by getSceneManager().
virtual bool LightManager::setTextureStage (const SceneData & sgData, const U32 currTexFlag, const U32 textureSlot, GFXShaderConstBuffer * shaderConsts, ShaderConstHandles * handles) pure virtual
Allows us to set textures during the Material::setTextureStage call, return true if we've done work.
Implemented in AdvancedLightManager, and BasicLightManager.
Referenced by getSceneManager().
virtual void LightManager::unregisterAllLights () virtual
Reimplemented in AdvancedLightManager.
Referenced by getSceneManager().
virtual void LightManager::unregisterGlobalLight (LightInfo * light) virtual
Referenced by getSceneManager().
virtual void LightManager::unregisterLocalLight (LightInfo * light) virtual
Referenced by getSceneManager().
Member Data Documentation
AvailableSLInterfaces* LightManager::mAvailableSLInterfaces protected
The scene lighting interfaces for lightmap generation.
Point3F LightManager::mCullPos protected
The root culling position used for special sun light placement.
See also
setSpecialLight
LightInfo* LightManager::mDefaultLight protected
A dummy default light used when no lights happen to be registered with the manager.
const String LightManager::mId protected
The constant light manager identifier initialized in the constructor.
Referenced by getId().
bool LightManager::mIsActive protected
Is true if this light manager has been activated.
Referenced by isActive().
const String LightManager::mName protected
The constant light manager name initialized in the constructor.
Referenced by getName().
LightInfoList LightManager::mRegisteredLights protected
The list of global registered lights which is initialized before the scene is rendered.
SceneManager* LightManager::mSceneManager protected
The scene graph the light manager is associated with.
Referenced by getSceneManager().
LightInfo* LightManager::mSpecialLights[slSpecialLightTypesCount] protected
The registered special light list.
Signal<void(const char*,bool)> LightManager::smActivateSignal static
The light manager activation signal.
LightManager* LightManager::smActiveLM static protected
The current active light manager.
Referenced by getActiveLM().
Copyright © GarageGames, LLC. All Rights Reserved.