GFXShader Class Reference
Main Modules Class List Namespace List Online
GFXShader Class Reference abstract
#include <gfx/gfxShader.h>
Public Member Functions
virtual ~GFXShader ()
The destructor.
virtual GFXShaderConstBufferRef allocConstBuffer ()=0
Allocate a constant buffer.
const String describeSelf () const
The resource should put a description of itself (number of vertices, size/width of texture, etc.) in buffer.
virtual GFXShaderConstHandle * findShaderConstHandle (const String &name)=0
Returns a shader constant handle for the name constant, if the variable doesn't exist NULL is returned.
virtual U32 getAlignmentValue (const GFXShaderConstType constType) const =0
Returns the alignment value for constType.
virtual bool getDisassembly (String &outStr) const
Device specific shaders can override this method to return the shader disassembly.
GFXVertexFormat * getInstancingFormat ()
const String & getPixelShaderFile () const
Returns the pixel shader file path.
F32 getPixVersion () const
Returns the required vertex format for this shader.
U32 getReloadKey () const
Returns a counter which is incremented each time this shader is reloaded.
Signal< void()> getReloadSignal ()
virtual const Vector< GFXShaderConstDesc > & getShaderConstDesc () const =0
Returns our list of shader constants, the material can get this and just set the constants it knows about.
virtual GFXShaderConstHandle * getShaderConstHandle (const String &name)=0
Returns a shader constant handle for the name constant.
const String & getVertexShaderFile () const
Returns the vertex shader file path.
bool init (const Torque::Path &vertFile, const Torque::Path &pixFile, F32 pixVersion, const Vector< GFXShaderMacro > &macros)
Deprecated. Remove on T3D 4.0.
bool init (const Torque::Path &vertFile, const Torque::Path &pixFile, F32 pixVersion, const Vector< GFXShaderMacro > &macros, const Vector< String > &samplerNames, GFXVertexFormat *instanceFormat=NULL)
bool reload ()
Reloads the shader from disk.
Public Member Functions inherited from StrongRefBase
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Public Member Functions inherited from GFXResource
GFXResource ()
virtual ~GFXResource ()
void clearFlag ()
GFXResource * getNextResource () const
GFXDevice * getOwningDevice () const
GFXResource * getPrevResource () const
bool isFlagged ()
void registerResourceWithDevice (GFXDevice *device)
Registers this resource with the given device.
virtual void resurrect ()=0
When called the resource should restore all device sensitive information destroyed by zombify()
void setFlag ()
virtual void zombify ()=0
When called the resource should destroy all device sensitive information (e.g. D3D resources in D3DPOOL_DEFAULT.
Static Public Member Functions
static void addGlobalMacro (const String &name, const String &value=String::EmptyString)
Adds a global shader macro which will be merged with the script defined macros on every shader reload.
static bool removeGlobalMacro (const String &name)
Removes an existing global macro by name.
static void setLogging (bool logErrors, bool logWarning)
Toggle logging for shader errors.
Protected Member Functions
GFXShader ()
A protected constructor so it cannot be instantiated.
virtual bool _init ()=0
Internal initialization function overloaded for each GFX device type.
void _onFileChanged (const Torque::Path &path)
Called when the shader files change on disk.
void _unlinkBuffer (GFXShaderConstBuffer *buf)
Buffers call this from their destructor (so we don't have to ref count them).
void _updateDesc ()
Called to update the description string after init.
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Protected Attributes
Vector< GFXShaderConstBuffer * > mActiveBuffers
Vector of buffers that reference this shader.
String mDescription
GFXVertexFormat * mInstancingFormat
Vector< GFXShaderMacro > mMacros
The macros to be passed to the shader.
Torque::Path mPixelFile
The pixel shader file.
F32 mPixVersion
The pixel version this is compiled for.
U32 mReloadKey
Counter that is incremented each time this shader is reloaded.
Signal< void()> mReloadSignal
Vector< String > mSamplerNamesOrdered
Ordered SamplerNames We need to store a list of sampler for allow OpenGL to assign correct location for each sampler.
Torque::Path mVertexFile
The vertex shader file.
Protected Attributes inherited from StrongRefBase
U32 mRefCount
reference counter for StrongRefPtr objects
Static Protected Attributes
static Vector< GFXShaderMacro > smGlobalMacros
These are system wide shader macros which are merged with shader specific macros at creation.
static bool smLogErrors
If true the shader errors are spewed to the console.
static bool smLogWarnings
If true the shader warnings are spewed to the console.
Constructor & Destructor Documentation
GFXShader::GFXShader () protected
A protected constructor so it cannot be instantiated.
virtual GFXShader::~GFXShader () virtual
The destructor.
Member Function Documentation
virtual bool GFXShader::_init () protected pure virtual
Internal initialization function overloaded for each GFX device type.
Implemented in GFXD3D11Shader, and GFXGLShader.
void GFXShader::_onFileChanged (const Torque::Path & path) inline protected
Called when the shader files change on disk.
void GFXShader::_unlinkBuffer (GFXShaderConstBuffer * buf) protected
Buffers call this from their destructor (so we don't have to ref count them).
void GFXShader::_updateDesc () protected
Called to update the description string after init.
static void GFXShader::addGlobalMacro (const String & name, const String & value = String::EmptyString) static
Adds a global shader macro which will be merged with the script defined macros on every shader reload.
The macro will replace the value of an existing macro of the same name.
For the new macro to take effect all the shaders/materials in the system need to be reloaded.
See also
MaterialManager::flushAndReInitInstances
ShaderData::reloadAll
virtual GFXShaderConstBufferRef GFXShader::allocConstBuffer () pure virtual
Allocate a constant buffer.
Implemented in GFXD3D11Shader, and GFXGLShader.
const String GFXShader::describeSelf () const inline virtual
The resource should put a description of itself (number of vertices, size/width of texture, etc.) in buffer.
Implements GFXResource.
Reimplemented in GFXGLShader.
virtual GFXShaderConstHandle* GFXShader::findShaderConstHandle (const String & name) pure virtual
Returns a shader constant handle for the name constant, if the variable doesn't exist NULL is returned.
Implemented in GFXD3D11Shader, and GFXGLShader.
virtual U32 GFXShader::getAlignmentValue (const GFXShaderConstType constType) const pure virtual
Returns the alignment value for constType.
Implemented in GFXD3D11Shader, and GFXGLShader.
virtual bool GFXShader::getDisassembly (String & outStr) const inline virtual
Device specific shaders can override this method to return the shader disassembly.
Reimplemented in GFXD3D11Shader.
GFXVertexFormat* GFXShader::getInstancingFormat () inline
const String& GFXShader::getPixelShaderFile () const inline
Returns the pixel shader file path.
References Torque::Path::getFullPath().
F32 GFXShader::getPixVersion () const inline
Returns the required vertex format for this shader.
Returns the pixel shader version.
U32 GFXShader::getReloadKey () const inline
Returns a counter which is incremented each time this shader is reloaded.
Signal<void()> GFXShader::getReloadSignal () inline
References GFXShaderConstDesc::constType, and GFXShaderConstDesc::name.
virtual const Vector<GFXShaderConstDesc>& GFXShader::getShaderConstDesc () const pure virtual
Returns our list of shader constants, the material can get this and just set the constants it knows about.
Implemented in GFXD3D11Shader, and GFXGLShader.
virtual GFXShaderConstHandle* GFXShader::getShaderConstHandle (const String & name) pure virtual
Returns a shader constant handle for the name constant.
Since shaders can reload and later have handles that didn't exist originally this will return a handle in an invalid state if the constant doesn't exist at this time.
Implemented in GFXD3D11Shader, and GFXGLShader.
const String& GFXShader::getVertexShaderFile () const inline
Returns the vertex shader file path.
References Torque::Path::getFullPath().
bool GFXShader::init (const Torque::Path & vertFile, const Torque::Path & pixFile, F32 pixVersion, const Vector< GFXShaderMacro > & macros)
Deprecated. Remove on T3D 4.0.
bool GFXShader::init (const Torque::Path & vertFile, const Torque::Path & pixFile, F32 pixVersion, const Vector< GFXShaderMacro > & macros, const Vector< String > & samplerNames, GFXVertexFormat * instanceFormat = NULL)
bool GFXShader::reload ()
Reloads the shader from disk.
Referenced by GFXGLShader::resurrect().
static bool GFXShader::removeGlobalMacro (const String & name) static
Removes an existing global macro by name.
See also
addGlobalMacro
static void GFXShader::setLogging (bool logErrors, bool logWarning) inline static
Toggle logging for shader errors.
Member Data Documentation
Vector<GFXShaderConstBuffer*> GFXShader::mActiveBuffers protected
Vector of buffers that reference this shader.
It is the responsibility of the derived shader class to populate this vector and to notify them when this shader is reloaded. Classes derived from GFXShaderConstBuffer should call _unlinkBuffer from their destructor.
String GFXShader::mDescription protected
GFXVertexFormat* GFXShader::mInstancingFormat protected
Vector<GFXShaderMacro> GFXShader::mMacros protected
The macros to be passed to the shader.
Torque::Path GFXShader::mPixelFile protected
The pixel shader file.
F32 GFXShader::mPixVersion protected
The pixel version this is compiled for.
U32 GFXShader::mReloadKey protected
Counter that is incremented each time this shader is reloaded.
Signal<void()> GFXShader::mReloadSignal protected
Vector<String> GFXShader::mSamplerNamesOrdered protected
Ordered SamplerNames We need to store a list of sampler for allow OpenGL to assign correct location for each sampler.
GLSL 150 not allow explicit uniform location. Only used on OpenGL
Torque::Path GFXShader::mVertexFile protected
The vertex shader file.
Vector<GFXShaderMacro> GFXShader::smGlobalMacros static protected
These are system wide shader macros which are merged with shader specific macros at creation.
bool GFXShader::smLogErrors static protected
If true the shader errors are spewed to the console.
bool GFXShader::smLogWarnings static protected
If true the shader warnings are spewed to the console.
Copyright © GarageGames, LLC. All Rights Reserved.