StrongRefBase Class Reference
Main Modules Class List Namespace List Online
StrongRefBase Class Reference
Base class for objects which can be strongly referenced (i.e., as long as reference exists, object will exist, when all strong references go away, object is destroyed).
#include <core/util/refBase.h>
Public Member Functions
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Protected Attributes
U32 mRefCount
reference counter for StrongRefPtr objects
Additional Inherited Members
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Detailed Description
Base class for objects which can be strongly referenced (i.e., as long as reference exists, object will exist, when all strong references go away, object is destroyed).
Constructor & Destructor Documentation
StrongRefBase::StrongRefBase () inline
Member Function Documentation
void StrongRefBase::decRefCount () inline
Decrements the reference count.
Referenced by StrongObjectRef::decRef(), and Message::freeReference().
virtual void StrongRefBase::destroySelf () inline virtual
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
Reimplemented in SimObject, StaticEngineObject, EngineObject, SFXBuffer, GFXTextureObject, and ResourceBase::Header.
U32 StrongRefBase::getRefCount () const inline
void StrongRefBase::incRefCount () inline
Increments the reference count.
Referenced by StrongObjectRef::incRef().
Member Data Documentation
U32 StrongRefBase::mRefCount protected
reference counter for StrongRefPtr objects
Copyright © GarageGames, LLC. All Rights Reserved.