Point2D Class Reference
Main Modules Class List Namespace List Online
Point2D Class Reference
2D high-precision point.
#include <math/mPoint2.h>
Public Member Functions
Point2D ()
Create uninitialized point.
Point2D (const Point2D &)
Copy constructor.
Point2D (F64 _x, F64 _y)
Create point from coordinates.
void convolve (const Point2D &)
void convolveInverse (const Point2D &)
void interpolate (const Point2D &a, const Point2D &b, const F64 c)
Interpolate from a to b, based on c.
bool isZero () const
F64 len () const
F64 lenSquared () const
void neg ()
void normalize ()
void normalize (F64 val)
operator const F64 * () const
operator F64 * ()
bool operator!= (const Point2D &) const
Point2D operator* (F64) const
Point2D & operator*= (F64)
Point2D operator+ (const Point2D &) const
Point2D & operator+= (const Point2D &)
Point2D operator- (const Point2D &) const
Point2D operator- () const
Point2D & operator-= (const Point2D &)
Point2D operator/ (F64) const
Point2D & operator/= (F64)
bool operator== (const Point2D &) const
void set (F64 _x, F64 _y)
Set point's coordinates.
void setMax (const Point2D &)
Store greater co-ordinates.
void setMin (const Point2D &)
Store lesser co-ordinates.
void zero ()
Zero all values.
Public Attributes
F64 x
X co-ordinate.
F64 y
Y co-ordinate.
Static Public Attributes
static const Point2D One
static const Point2D Zero
Detailed Description
2D high-precision point.
Uses F64 internally.
Constructor & Destructor Documentation
Point2D::Point2D () inline
Create uninitialized point.
Referenced by operator*(), operator+(), operator-(), and operator/().
Point2D::Point2D (const Point2D & _copy) inline
Copy constructor.
Point2D::Point2D (F64 _x, F64 _y) inline
Create point from coordinates.
Member Function Documentation
void Point2D::convolve (const Point2D & c) inline
References x, and y.
void Point2D::convolveInverse (const Point2D & c) inline
References x, and y.
void Point2D::interpolate (const Point2D & a, const Point2D & b, const F64 c) inline
Interpolate from a to b, based on c.
Parameters
a Starting point.
b Ending point.
c Interpolation factor (0.0 .. 1.0).
References x, and y.
bool Point2D::isZero () const inline
References x, and y.
F64 Point2D::len () const inline
References x, and y.
F64 Point2D::lenSquared () const inline
References x, and y.
void Point2D::neg () inline
References x, and y.
void Point2D::normalize () inline
void Point2D::normalize (F64 val) inline
References operator*(), Point2F::x, and Point2F::y.
Point2D::operator const F64 * () const inline
References Point2I::convolve(), Point2I::isZero(), Point2I::len(), Point2I::lenSquared(), Point2I::neg(), Point2I::operator!=(), Point2I::operator*(), Point2I::operator*=(), Point2I::operator+(), Point2I::operator+=(), Point2I::operator-(), Point2I::operator-=(), Point2I::operator/(), Point2I::operator/=(), Point2I::operator==(), and Point2I::x.
Point2D::operator F64 * () inline
References Point2I::x.
bool Point2D::operator!= (const Point2D & _test) const inline
References operator==().
Point2D Point2D::operator* (F64 _mul) const inline
References Point2D(), x, and y.
Referenced by normalize().
Point2D & Point2D::operator*= (F64 _mul) inline
References x, and y.
Point2D Point2D::operator+ (const Point2D & _add) const inline
References Point2D(), x, and y.
Point2D & Point2D::operator+= (const Point2D & _add) inline
References x, and y.
Point2D Point2D::operator- (const Point2D & _rSub) const inline
References Point2D(), x, and y.
Point2D Point2D::operator- () const inline
References Point2D(), x, and y.
Point2D & Point2D::operator-= (const Point2D & _rSub) inline
References x, and y.
Point2D Point2D::operator/ (F64 _div) const inline
References Point2D(), x, and y.
Point2D & Point2D::operator/= (F64 _div) inline
References x, and y.
bool Point2D::operator== (const Point2D & _test) const inline
References x, and y.
Referenced by operator!=().
void Point2D::set (F64 _x, F64 _y) inline
Set point's coordinates.
References x, and y.
void Point2D::setMax (const Point2D & _test) inline
Store greater co-ordinates.
References x, and y.
void Point2D::setMin (const Point2D & _test) inline
Store lesser co-ordinates.
References x, and y.
void Point2D::zero () inline
Zero all values.
References x, and y.
Member Data Documentation
const Point2D Point2D::One static
F64 Point2D::x
X co-ordinate.
Referenced by convolve(), convolveInverse(), interpolate(), RectD::intersect(), RectD::isValidRect(), isZero(), len(), RectD::len_x(), lenSquared(), neg(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator==(), set(), setMax(), setMin(), and zero().
F64 Point2D::y
Y co-ordinate.
Referenced by convolve(), convolveInverse(), interpolate(), RectD::intersect(), RectD::isValidRect(), isZero(), len(), RectD::len_y(), lenSquared(), neg(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator==(), set(), setMax(), setMin(), and zero().
const Point2D Point2D::Zero static
Copyright © GarageGames, LLC. All Rights Reserved.