BlobShadow Class Reference
Main Modules Class List Namespace List Online
BlobShadow Class Reference
#include <lighting/common/blobShadow.h>
Public Member Functions
BlobShadow (SceneObject *parentobject, LightInfo *light, TSShapeInstance *shapeinstance)
~BlobShadow ()
U32 getLastRenderTime () const
bool prepare (const Point3F &pos, Point3F lightDir, F32 shadowLen)
void render (F32 camDist, const TSRenderState &rdata)
void setRadius (F32 radius)
void setRadius (TSShapeInstance *, const Point3F &scale)
bool shouldRender (F32 camDist)
void update (const SceneRenderState *state)
Public Member Functions inherited from ShadowBase
virtual ~ShadowBase ()
virtual const F32 getScore () const =0
virtual bool shouldRender (const SceneRenderState *state)=0
Static Public Member Functions
static void deleteGenericShadowBitmap ()
static void generateGenericShadowBitmap (S32 dim)
Constructor & Destructor Documentation
BlobShadow::BlobShadow (SceneObject * parentobject, LightInfo * light, TSShapeInstance * shapeinstance)
BlobShadow::~BlobShadow ()
Member Function Documentation
static void BlobShadow::deleteGenericShadowBitmap () static
Referenced by getLastRenderTime().
static void BlobShadow::generateGenericShadowBitmap (S32 dim) static
Referenced by getLastRenderTime().
U32 BlobShadow::getLastRenderTime () const inline virtual
Implements ShadowBase.
References deleteGenericShadowBitmap(), and generateGenericShadowBitmap().
bool BlobShadow::prepare (const Point3F & pos, Point3F lightDir, F32 shadowLen)
void BlobShadow::render (F32 camDist, const TSRenderState & rdata) virtual
Implements ShadowBase.
Referenced by update().
void BlobShadow::setRadius (F32 radius)
void BlobShadow::setRadius (TSShapeInstance * , const Point3F & scale)
bool BlobShadow::shouldRender (F32 camDist)
void BlobShadow::update (const SceneRenderState * state) inline virtual
Implements ShadowBase.
References render().
Copyright © GarageGames, LLC. All Rights Reserved.