ConsoleValue Class Reference
Main Modules Class List Namespace List Online
ConsoleValue Class Reference
Console System
#include <console/console.h>
Public Types
enum {
TypeInternalInt = -5,
TypeInternalFloat = -4,
TypeInternalStringStackPtr = -3,
TypeInternalStackString = -2,
TypeInternalString = -1
}
Public Member Functions
ConsoleValue ()
~ConsoleValue ()
void cleanup ()
bool getBoolValue ()
F32 getFloatValue ()
U32 getIntValue ()
S32 getSignedIntValue ()
StringStackPtr getStringStackPtr ()
const char * getStringValue ()
void init ()
void setBoolValue (bool val)
void setFloatValue (F32 val)
void setIntValue (U32 val)
void setIntValue (S32 val)
void setStackStringValue (const char *value)
void setStringStackPtrValue (StringStackPtr ptr)
void setStringValue (const char *value)
Public Attributes
union {
struct {
U32 bufferLen
F32 fval
U32 ival
char * sval
}
struct {
void * dataPtr
The real data pointer.
const EnumTable * enumTable
The enum lookup table for enumerated types.
}
};
S32 type
Member Enumeration Documentation
anonymous enum
Enumerator
TypeInternalInt
TypeInternalFloat
TypeInternalStringStackPtr
TypeInternalStackString
TypeInternalString
Constructor & Destructor Documentation
ConsoleValue::ConsoleValue () inline
ConsoleValue::~ConsoleValue () inline
Member Function Documentation
void ConsoleValue::cleanup () inline
References dFree(), TypeInternalString, and typeValueEmpty.
Referenced by Dictionary::Entry::reset().
bool ConsoleValue::getBoolValue ()
Referenced by dAtob(), and ConsoleValueRef::getBoolValue().
F32 ConsoleValue::getFloatValue ()
Referenced by ConsoleValueRef::getFloatValue(), and Dictionary::Entry::getFloatValue().
U32 ConsoleValue::getIntValue ()
Referenced by ConsoleValueRef::getIntValue(), and Dictionary::Entry::getIntValue().
S32 ConsoleValue::getSignedIntValue ()
Referenced by ConsoleValueRef::getSignedIntValue().
StringStackPtr ConsoleValue::getStringStackPtr ()
Referenced by ConsoleValueRef::getStringStackPtrValue().
const char* ConsoleValue::getStringValue ()
Referenced by ConsoleValueRef::getStringValue(), and Dictionary::Entry::getStringValue().
void ConsoleValue::init () inline
References typeValueEmpty.
Referenced by Dictionary::Entry::Entry().
void ConsoleValue::setBoolValue (bool val)
void ConsoleValue::setFloatValue (F32 val)
Referenced by Dictionary::Entry::setFloatValue().
void ConsoleValue::setIntValue (U32 val)
Referenced by Dictionary::Entry::setIntValue().
void ConsoleValue::setIntValue (S32 val)
void ConsoleValue::setStackStringValue (const char * value)
Referenced by _EngineConsoleCallbackHelper::call(), _EngineConsoleExecCallbackHelper< P1 >::call(), and _EngineConsoleExecCallbackHelper< const char * >::call().
void ConsoleValue::setStringStackPtrValue (StringStackPtr ptr)
Referenced by Dictionary::Entry::setStringStackPtrValue().
void ConsoleValue::setStringValue (const char * value)
Referenced by Dictionary::Entry::setStringValue().
Member Data Documentation
union { ... }
U32 ConsoleValue::bufferLen
void* ConsoleValue::dataPtr
The real data pointer.
const EnumTable* ConsoleValue::enumTable
The enum lookup table for enumerated types.
F32 ConsoleValue::fval
U32 ConsoleValue::ival
char* ConsoleValue::sval
S32 ConsoleValue::type
Referenced by ConsoleValueRef::getType(), ConsoleValueRef::isFloat(), ConsoleValueRef::isInt(), ConsoleValueRef::isString(), and ConsoleValueRef::isStringStackPtr().
Copyright © GarageGames, LLC. All Rights Reserved.