ThreadPool::Context Class Reference
Main Modules Class List Namespace List Online
ThreadPool::Context Class Reference
A ThreadPool context defines a logical context in which WorkItems are being executed.
#include <platform/threads/threadPool.h>
Public Member Functions
Context (const char *name, Context *parent, F32 priorityBias)
~Context ()
F32 getAccumulatedPriorityBias ()
Context * getChild (const char *name)
Context * getChildren () const
Return the first child context.
const char * getName () const
Return the name of the worker threading context.
Context * getParent () const
Return the superordinate node to the current context.
F32 getPriorityBias () const
Return the context's own work item priority bias.
Context * getSibling () const
Return the next sibling to the current context.
void setPriorityBias (F32 value)
Static Public Member Functions
static Context * ROOT_CONTEXT ()
Return the root context.
Protected Member Functions
void updateAccumulatedPriorityBiases ()
Recursively update cached accumulated priority biases.
Protected Attributes
F32 mAccumulatedPriorityBias
Accumulated scale factor.
Context * mChildren
First child.
const char * mName
Name of this context. Should be unique in parent namespace.
Context * mParent
Superordinate context; scales this context's priority bias.
F32 mPriorityBias
Priority scale factor of this context.
Context * mSibling
Next sibling in child chain.
Static Protected Attributes
static Context smRootContext
The root context; does not modify priorities. All contexts should be direct or indirect children of this one.
Detailed Description
A ThreadPool context defines a logical context in which WorkItems are being executed.
Their primary use is for biasing priorities of WorkItems.
Contexts are arranged in a tree hierarchy. Each parent node's priority bias scales all the priority biases underneath it.
Note that instances of this class are meant to be instantiated globally only.
Constructor & Destructor Documentation
ThreadPool::Context::Context (const char * name, Context * parent, F32 priorityBias)
ThreadPool::Context::~Context ()
Member Function Documentation
F32 ThreadPool::Context::getAccumulatedPriorityBias ()
Referenced by ROOT_CONTEXT().
Context* ThreadPool::Context::getChild (const char * name)
Referenced by ROOT_CONTEXT().
Context* ThreadPool::Context::getChildren () const inline
Return the first child context.
References mChildren.
const char* ThreadPool::Context::getName () const inline
Return the name of the worker threading context.
References mName.
Context* ThreadPool::Context::getParent () const inline
Return the superordinate node to the current context.
References mParent.
F32 ThreadPool::Context::getPriorityBias () const inline
Return the context's own work item priority bias.
References mPriorityBias.
Context* ThreadPool::Context::getSibling () const inline
Return the next sibling to the current context.
References mSibling.
static Context* ThreadPool::Context::ROOT_CONTEXT () inline static
Return the root context.
References getAccumulatedPriorityBias(), getChild(), setPriorityBias(), and smRootContext.
Referenced by AsyncPacketBufferedInputStream< SFXStreamRef, SFXStreamPacket >::_newReadItem().
void ThreadPool::Context::setPriorityBias (F32 value)
Referenced by ROOT_CONTEXT().
void ThreadPool::Context::updateAccumulatedPriorityBiases () protected
Recursively update cached accumulated priority biases.
Member Data Documentation
F32 ThreadPool::Context::mAccumulatedPriorityBias protected
Accumulated scale factor.
Context* ThreadPool::Context::mChildren protected
First child.
Referenced by getChildren().
const char* ThreadPool::Context::mName protected
Name of this context. Should be unique in parent namespace.
Referenced by getName().
Context* ThreadPool::Context::mParent protected
Superordinate context; scales this context's priority bias.
Referenced by getParent().
F32 ThreadPool::Context::mPriorityBias protected
Priority scale factor of this context.
Referenced by getPriorityBias().
Context* ThreadPool::Context::mSibling protected
Next sibling in child chain.
Referenced by getSibling().
Context ThreadPool::Context::smRootContext static protected
The root context; does not modify priorities. All contexts should be direct or indirect children of this one.
Referenced by ROOT_CONTEXT().
Copyright © GarageGames, LLC. All Rights Reserved.