BitSet32 Class Reference
Main Modules Class List Namespace List Online
BitSet32 Class Reference
A convenience class to manipulate a set of bits.
#include <core/bitSet.h>
Public Member Functions
BitSet32 ()
BitSet32 (const BitSet32 &in_rCopy)
BitSet32 (const U32 in_mask)
void clear ()
Clear all bits.
void clear (const U32 m)
Clear the specified bit(s).
U32 getMask () const
operator U32 () const
void set ()
Set all bits to true.
void set (const U32 m)
Set the specified bit(s) to true.
void set (BitSet32 s, bool b)
Masked-set the bitset; ie, using s as the mask and then setting the masked bits to b.
bool test (const U32 m) const
Are any of the specified bit(s) set?
bool testStrict (const U32 m) const
Are ALL the specified bit(s) set?
void toggle (const U32 m)
Toggle the specified bit(s).
Operator Overloads
BitSet32 & operator= (const U32 m)
BitSet32 & operator|= (const U32 m)
BitSet32 & operator&= (const U32 m)
BitSet32 & operator^= (const U32 m)
BitSet32 operator| (const U32 m) const
BitSet32 operator& (const U32 m) const
BitSet32 operator^ (const U32 m) const
Detailed Description
A convenience class to manipulate a set of bits.
Notice that bits are accessed directly, ie, by passing a variable with the relevant bit set or not, instead of passing the index of the relevant bit.
Constructor & Destructor Documentation
BitSet32::BitSet32 () inline
Referenced by operator&(), operator^(), and operator|().
BitSet32::BitSet32 (const BitSet32 & in_rCopy) inline
BitSet32::BitSet32 (const U32 in_mask) inline
Member Function Documentation
void BitSet32::clear (void) inline
Clear all bits.
Referenced by SFXObject< 3 >::clearFlags(), SimObject::setAutoDelete(), SimObject::setCanSave(), SimObject::setEditorOnly(), SimObject::setExpanded(), SimObject::setModDynamicFields(), SimObject::setModStaticFields(), SimObject::setNameChangeAllowed(), and fxShapeReplicatedStatic::touchNetFlags().
void BitSet32::clear (const U32 m) inline
Clear the specified bit(s).
U32 BitSet32::getMask () const inline
BitSet32::operator U32 () const inline
BitSet32 BitSet32::operator& (const U32 m) const inline
References BitSet32().
BitSet32& BitSet32::operator&= (const U32 m) inline
BitSet32& BitSet32::operator= (const U32 m) inline
BitSet32 BitSet32::operator^ (const U32 m) const inline
References BitSet32().
BitSet32& BitSet32::operator^= (const U32 m) inline
BitSet32 BitSet32::operator| (const U32 m) const inline
References BitSet32().
BitSet32& BitSet32::operator|= (const U32 m) inline
void BitSet32::set () inline
Set all bits to true.
Referenced by ScopeTrackerObject< NUM_DIMENSIONS >::ScopeTrackerObject(), CreatorTree::Node::select(), SimObject::setAutoDelete(), SimObject::setCanSave(), SFXSource::setCone(), SimObject::setEditorOnly(), SimObject::setExpanded(), GuiTreeViewCtrl::Item::setFiltered(), SFXObject< 3 >::setFlags(), NetConnection::setIsConnectionToServer(), NetConnection::setIsLocalClientConnection(), SFXSource::setMinMaxDistance(), SimObject::setModDynamicFields(), SimObject::setModStaticFields(), SimObject::setNameChangeAllowed(), NetConnection::setNetworkConnection(), SFXSource::setPitch(), SFXSource::setPriority(), SFXSource::setVolume(), and fxShapeReplicatedStatic::touchNetFlags().
void BitSet32::set (const U32 m) inline
Set the specified bit(s) to true.
void BitSet32::set (BitSet32 s, bool b) inline
Masked-set the bitset; ie, using s as the mask and then setting the masked bits to b.
bool BitSet32::test (const U32 m) const inline
Are any of the specified bit(s) set?
Referenced by SFXSoundscape::_isOverridden(), SFXSoundscape::_isUnique(), SimObject::canModDynamicFields(), SimObject::canModStaticFields(), SimObject::getCanSave(), ServerInfo::hasResponded(), EngineTypeInfo::isAbstract(), SimObject::isAutoDeleted(), EngineFunctionInfo::isCallout(), NetConnection::isConnectionToServer(), DDSFile::isCubemap(), SceneObject::isCullingDisabledInEditor(), ServerInfo::isDedicated(), SimObject::isDeleted(), EngineTypeInfo::isDisposable(), GuiTreeViewCtrl::Item::isDragAllowed(), GuiTreeViewCtrl::Item::isDragTargetAllowed(), SimObject::isEditorOnly(), SFXObject< 3 >::isEmitter(), CreatorTree::Node::isExpanded(), SimObject::isExpanded(), GuiTreeViewCtrl::Item::isFiltered(), CreatorTree::Node::isGroup(), SimObject::isHidden(), GuiTreeViewCtrl::Item::isInspectorData(), EngineTypeInfo::isInstantiable(), ServerInfo::isLinux(), SFXObject< 3 >::isListener(), SimObject::isLocked(), ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::isMax(), ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::isMin(), SimObject::isNameChangeAllowed(), NetConnection::isNetworkConnection(), SFXObject< 3 >::isOccluder(), SceneObject::isOccludingSound(), ServerInfo::isPassworded(), SFXObject< 3 >::isPortal(), SimObject::isProperlyAdded(), ServerInfo::isQuerying(), ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::isReference(), SimObject::isRemoved(), CreatorTree::Node::isRoot(), CreatorTree::Node::isSelected(), SimObject::isSelected(), EngineTypeInfo::isSingleton(), ServerInfo::isTimedOut(), ServerInfo::isUpdating(), EngineTypeInfo::isVariadic(), SceneObject::isVisualOccluder(), SFXObject< 3 >::isZone(), GuiTreeViewCtrl::Item::showInternalNameOnly(), and GuiTreeViewCtrl::Item::showObjectNameOnly().
bool BitSet32::testStrict (const U32 m) const inline
Are ALL the specified bit(s) set?
void BitSet32::toggle (const U32 m) inline
Toggle the specified bit(s).
Copyright © GarageGames, LLC. All Rights Reserved.