HifiClientProcessList Class Reference
Main Modules Class List Namespace List Online
HifiClientProcessList Class Reference
List to keep track of GameBases to process.
#include <T3D/gameBase/hifi/hifiGameProcess.h>
Public Member Functions
HifiClientProcessList ()
bool advanceTime (SimTime timeDelta)
Returns true if a tick was processed.
void clientCatchup (GameConnection *)
Called after a correction packet is received from the server.
Public Member Functions inherited from ClientProcessList
ClientProcessList ()
void addObject (ProcessObject *pobj)
Public Member Functions inherited from ProcessList
ProcessList ()
virtual ~ProcessList ()
void dumpToConsole ()
F32 getLastDelta ()
F32 getLastInterpDelta ()
SimTime getLastTime ()
U32 getTotalTicks ()
bool isDirty ()
void markDirty ()
PostTickSignal & postTickSignal ()
PreTickSignal & preTickSignal ()
Static Public Member Functions
static void init ()
static void shutdown ()
Static Public Member Functions inherited from ClientProcessList
static ClientProcessList * get ()
Protected Member Functions
void advanceObjects ()
void ageTickCache (S32 numToAge, S32 len)
void forceHifiReset (bool reset)
U32 getTotalTicks ()
void onAdvanceObjects ()
void onTickObject (ProcessObject *)
void setCatchup (U32 catchup)
void skipAdvanceObjects (U32 ms)
void updateMoveSync (S32 moveDiff)
Protected Member Functions inherited from ClientProcessList
bool doBacklogged (SimTime timeDelta)
Returns true if backlogged.
void onPreTickObject (ProcessObject *pobj)
Protected Member Functions inherited from ProcessList
GameBase * getGameBase (ProcessObject *obj)
void orderList ()
Protected Attributes
U32 mCatchup
bool mForceHifiReset
U32 mSkipAdvanceObjectsMs
Protected Attributes inherited from ProcessList
U32 mCurrentTag
bool mDirty
ProcessObject mHead
F32 mLastDelta
SimTime mLastTick
SimTime mLastTime
PostTickSignal mPostTick
PreTickSignal mPreTick
U32 mTotalTicks
Additional Inherited Members
Static Protected Attributes inherited from ClientProcessList
static ClientProcessList * smClientProcessList
Detailed Description
List to keep track of GameBases to process.
Constructor & Destructor Documentation
HifiClientProcessList::HifiClientProcessList ()
Member Function Documentation
void HifiClientProcessList::advanceObjects () protected virtual
Reimplemented from ProcessList.
Referenced by skipAdvanceObjects().
bool HifiClientProcessList::advanceTime (SimTime timeDelta) virtual
Returns true if a tick was processed.
Reimplemented from ProcessList.
void HifiClientProcessList::ageTickCache (S32 numToAge, S32 len) protected
void HifiClientProcessList::clientCatchup (GameConnection * conn) virtual
Called after a correction packet is received from the server.
If the control object was corrected it will now play back any moves which were rolled back.
Reimplemented from ClientProcessList.
void HifiClientProcessList::forceHifiReset (bool reset) inline protected
References mForceHifiReset, and MoveList::reset().
U32 HifiClientProcessList::getTotalTicks () inline protected
References ProcessList::mTotalTicks, and updateMoveSync().
static void HifiClientProcessList::init () static
Referenced by HifiServerProcessList::HifiServerProcessList().
void HifiClientProcessList::onAdvanceObjects () protected virtual
Reimplemented from ProcessList.
Referenced by skipAdvanceObjects().
void HifiClientProcessList::onTickObject (ProcessObject *) protected virtual
Reimplemented from ProcessList.
Referenced by HifiServerProcessList::HifiServerProcessList(), and skipAdvanceObjects().
void HifiClientProcessList::setCatchup (U32 catchup) inline protected
References mCatchup.
static void HifiClientProcessList::shutdown () static
Referenced by HifiServerProcessList::HifiServerProcessList().
void HifiClientProcessList::skipAdvanceObjects (U32 ms) inline protected
References advanceObjects(), mSkipAdvanceObjectsMs, onAdvanceObjects(), and onTickObject().
void HifiClientProcessList::updateMoveSync (S32 moveDiff) protected
Referenced by getTotalTicks().
Member Data Documentation
U32 HifiClientProcessList::mCatchup protected
Referenced by setCatchup().
bool HifiClientProcessList::mForceHifiReset protected
Referenced by forceHifiReset().
U32 HifiClientProcessList::mSkipAdvanceObjectsMs protected
Referenced by skipAdvanceObjects().
Copyright © GarageGames, LLC. All Rights Reserved.