ThreadSafeFreeList< T > Class Template Reference
Main Modules Class List Namespace List Online
ThreadSafeFreeList< T > Class Template Reference
Freelist for re-using allocations in a concurrent setting.
#include <platform/threads/threadSafeFreeList.h>
Public Member Functions
ThreadSafeFreeList (U32 numPreAlloc=0)
Create the freelist.
~ThreadSafeFreeList ()
void * alloc ()
Return memory for a new instance.
void dumpDebug ()
void free (void *ptr)
Return the memory allocated to the given instance to the freelist.
Protected Member Functions
T *& getNext (T *ptr)
Protected Attributes
T * mFreeList
S32 mNumNodesFree
S32 mNumNodesTotal
Detailed Description
template<class T>
class ThreadSafeFreeList< T >
Freelist for re-using allocations in a concurrent setting.
Note
Make sure that there are no more allocations in use when the free list is destructed.
Allocated instances come with a reference already counted on the instance.
Parameters
T Type of elements to allocate; must be derived from ThreadSafeRefCount and have at least define one additional pointer-sized field.
Constructor & Destructor Documentation
template<class T> ThreadSafeFreeList< T >::ThreadSafeFreeList (U32 numPreAlloc = 0) inline
Create the freelist.
Parameters
numPreAlloc Number of instances to pre-allocate.
template<class T> ThreadSafeFreeList< T >::~ThreadSafeFreeList () inline
Member Function Documentation
template<class T> void* ThreadSafeFreeList< T >::alloc () inline
Return memory for a new instance.
Referenced by ThreadSafeFreeList< ThreadSafeDeque::Node >::ThreadSafeFreeList().
template<class T> void ThreadSafeFreeList< T >::dumpDebug () inline
Referenced by ThreadSafeDeque< GBitmap * >::dumpDebug().
template<class T> void ThreadSafeFreeList< T >::free (void * ptr) inline
Return the memory allocated to the given instance to the freelist.
Referenced by ThreadSafeFreeList< ThreadSafeDeque::Node >::ThreadSafeFreeList().
template<class T> T*& ThreadSafeFreeList< T >::getNext (T * ptr) inline protected
Referenced by ThreadSafeFreeList< ThreadSafeDeque::Node >::alloc(), ThreadSafeFreeList< ThreadSafeDeque::Node >::free(), and ThreadSafeFreeList< ThreadSafeDeque::Node >::~ThreadSafeFreeList().
Member Data Documentation
template<class T> T* ThreadSafeFreeList< T >::mFreeList protected
Referenced by ThreadSafeFreeList< ThreadSafeDeque::Node >::free().
template<class T> S32 ThreadSafeFreeList< T >::mNumNodesFree protected
template<class T> S32 ThreadSafeFreeList< T >::mNumNodesTotal protected
Copyright © GarageGames, LLC. All Rights Reserved.