Mutex Class Reference
Main Modules Class List Namespace List Online
Mutex Class Reference
#include <platform/threads/mutex.h>
Public Member Functions
Mutex ()
virtual ~Mutex ()
virtual bool lock (bool block=true)
virtual void unlock ()
Static Public Member Functions
static void * createMutex ()
static void destroyMutex (void *mutex)
static bool lockMutex (void *mutex, bool block=true)
static void unlockMutex (void *mutex)
Protected Attributes
PlatformMutexData * mData
Constructor & Destructor Documentation
Mutex::Mutex ()
Referenced by createMutex().
virtual Mutex::~Mutex () virtual
Member Function Documentation
static void* Mutex::createMutex () inline static
References Mutex().
static void Mutex::destroyMutex (void * mutex) inline static
virtual bool Mutex::lock (bool block = true) virtual
Referenced by ThreadManager::addThread(), ThreadManager::getThreadById(), lockMutex(), FModFNTable::Thunk< FN >::operator()(), and ThreadManager::removeThread().
static bool Mutex::lockMutex (void * mutex, bool block = true) inline static
References lock().
Referenced by MutexHandle::lock(), and SimSet::lock().
virtual void Mutex::unlock () virtual
Referenced by ThreadManager::addThread(), ThreadManager::getThreadById(), FModFNTable::Thunk< FN >::operator()(), ThreadManager::removeThread(), unlockMutex(), and MutexHandle::~MutexHandle().
static void Mutex::unlockMutex (void * mutex) inline static
References unlock().
Referenced by MutexHandle::unlock(), and SimSet::unlock().
Member Data Documentation
PlatformMutexData* Mutex::mData protected
Copyright © GarageGames, LLC. All Rights Reserved.