Process Class Reference
Main Modules Class List Namespace List Online
Process Class Reference
Event generation signal.
#include <core/util/journal/process.h>
Static Public Member Functions
static S32 getReturnStatus ()
get the current return status code we've been asked to end with.
static bool init ()
Trigger the registered init functions.
static void notify (Delegate< void()> del, F32 order=PROCESS_DEFAULT_ORDER)
static void notify (SignalSlot< void()> &slot, F32 order=PROCESS_DEFAULT_ORDER)
template<class T >
static void notify (T func, F32 order=PROCESS_DEFAULT_ORDER)
template<class T , class U >
static void notify (T obj, U func, F32 order=PROCESS_DEFAULT_ORDER)
static void notifyCommandLine (Delegate< void(S32, const char **)> del, F32 order=PROCESS_DEFAULT_ORDER)
template<class T >
static void notifyCommandLine (T func, F32 order=PROCESS_DEFAULT_ORDER)
static void notifyInit (Delegate< bool()> del, F32 order=PROCESS_DEFAULT_ORDER)
template<class T >
static void notifyInit (T func, F32 order=PROCESS_DEFAULT_ORDER)
static void notifyShutdown (Delegate< bool(void)> del, F32 order=PROCESS_DEFAULT_ORDER)
template<class T >
static void notifyShutdown (T func, F32 order=PROCESS_DEFAULT_ORDER)
static bool processEvents ()
Trigger the ProcessSignal and replay journal events.
static void remove (Delegate< void()> del)
template<class T >
static void remove (T func)
template<class T , class U >
static void remove (T obj, U func)
static void requestShutdown (S32 status=0)
Ask the processEvents() function to shutdown.
static bool shutdown ()
Trigger the registered shutdown functions.
Detailed Description
Event generation signal.
Objects that generate events need to register a callback with this signal and should only generate events from within the callback.
This signal is triggered from the ProcessEvents() method.
Member Function Documentation
static S32 Process::getReturnStatus () static
get the current return status code we've been asked to end with.
Referenced by notifyShutdown().
static bool Process::init () static
Trigger the registered init functions.
Referenced by notifyShutdown().
static void Process::notify (Delegate< void()> del, F32 order = PROCESS_DEFAULT_ORDER) inline static
References SignalBaseT< Signature >::notify().
Referenced by ProcessRegisterProcessing::ProcessRegisterProcessing().
static void Process::notify (SignalSlot< void()> & slot, F32 order = PROCESS_DEFAULT_ORDER) inline static
References SignalBaseT< Signature >::notify().
template<class T > static void Process::notify (T func, F32 order = PROCESS_DEFAULT_ORDER) inline static
References SignalBaseT< Signature >::notify().
template<class T , class U > static void Process::notify (T obj, U func, F32 order = PROCESS_DEFAULT_ORDER) inline static
References SignalBaseT< Signature >::notify().
static void Process::notifyCommandLine (Delegate< void(S32, const char **)> del, F32 order = PROCESS_DEFAULT_ORDER) inline static
Referenced by ProcessRegisterCommandLine::ProcessRegisterCommandLine().
template<class T > static void Process::notifyCommandLine (T func, F32 order = PROCESS_DEFAULT_ORDER) inline static
static void Process::notifyInit (Delegate< bool()> del, F32 order = PROCESS_DEFAULT_ORDER) inline static
template<class T > static void Process::notifyInit (T func, F32 order = PROCESS_DEFAULT_ORDER) inline static
static void Process::notifyShutdown (Delegate< bool(void)> del, F32 order = PROCESS_DEFAULT_ORDER) inline static
template<class T > static void Process::notifyShutdown (T func, F32 order = PROCESS_DEFAULT_ORDER) inline static
References getReturnStatus(), init(), and shutdown().
static bool Process::processEvents () static
Trigger the ProcessSignal and replay journal events.
The ProcessSignal is triggered during which all events are generated, journaled, and delivered using the EventSignal classes. Event producers should only generate events from within the function they register with ProcessSignal. ProcessSignal is also triggered during event playback, though all new events are thrown away so as not to interfere with journal playback. This function returns false if Process::requestShutdown() has been called, otherwise it returns true.
NOTE: This should only be called from main loops - it should really be private, but we need to sort out how to handle the unit test cases
static void Process::remove (Delegate< void()> del) inline static
References SignalBaseT< Signature >::remove().
template<class T > static void Process::remove (T func) inline static
References SignalBaseT< Signature >::remove().
template<class T , class U > static void Process::remove (T obj, U func) inline static
References SignalBaseT< Signature >::remove().
static void Process::requestShutdown (S32 status = 0) static
Ask the processEvents() function to shutdown.
static bool Process::shutdown () static
Trigger the registered shutdown functions.
Referenced by notifyShutdown().
Copyright © GarageGames, LLC. All Rights Reserved.