TamlCustomNodes Class Reference
Main Modules Class List Namespace List Online
TamlCustomNodes Class Reference
#include <persistence/taml/tamlCustom.h>
Public Member Functions
TamlCustomNodes ()
virtual ~TamlCustomNodes ()
TamlCustomNode * addNode (const char *pNodeName, const bool ignoreEmpty=true)
const TamlCustomNode * findNode (const char *pNodeName) const
const TamlCustomNodeVector & getNodes (void) const
void removeNode (const U32 index)
virtual void resetState (void)
Constructor & Destructor Documentation
TamlCustomNodes::TamlCustomNodes () inline
virtual TamlCustomNodes::~TamlCustomNodes () inline virtual
References TamlCustomField::resetState().
Member Function Documentation
TamlCustomNode* TamlCustomNodes::addNode (const char * pNodeName, const bool ignoreEmpty = true) inline
References FactoryCache< T >::cacheObject(), FactoryCache< T >::createObject(), TamlCustomNode::getNodeName(), TamlCustomNode::setIgnoreEmpty(), TamlCustomNode::setNodeName(), and Con::warnf().
const TamlCustomNode* TamlCustomNodes::findNode (const char * pNodeName) const inline
References Vector< T >::begin().
const TamlCustomNodeVector& TamlCustomNodes::getNodes (void) const inline
void TamlCustomNodes::removeNode (const U32 index) inline
References FactoryCache< T >::cacheObject().
virtual void TamlCustomNodes::resetState (void) inline virtual
Implements IFactoryObjectReset.
References FactoryCache< T >::cacheObject().
Copyright © GarageGames, LLC. All Rights Reserved.