FrameAllocator Class Reference
Main Modules Class List Namespace List Online
FrameAllocator Class Reference
Temporary memory pool for per-frame allocations.
#include <core/frameAllocator.h>
Static Public Member Functions
static void * alloc (const U32 allocSize)
static void destroy ()
static U32 getHighWaterMark ()
static U32 getMaxFrameAllocation ()
static U32 getWaterMark ()
static void init (const U32 frameSize)
static void setWaterMark (const U32)
Detailed Description
Temporary memory pool for per-frame allocations.
In the course of rendering a frame, it is often necessary to allocate many small chunks of memory, then free them all in a batch. For instance, say we're allocating storage for some vertex calculations:
// Get FrameAllocator memory...
U32 waterMark = FrameAllocator::getWaterMark();
F32 * ptr = (F32*)FrameAllocator::alloc(sizeof(F32)*2*targetMesh->vertsPerFrame);
... calculations ...
// Free frameAllocator memory
FrameAllocator::setWaterMark(waterMark);
Member Function Documentation
void * FrameAllocator::alloc (const U32 allocSize) inline static
Referenced by FrameAllocatorMarker::alloc(), SilhouetteExtractorBasePerspective< PolyhedronType >::begin(), SilhouetteExtractorBaseOrtho< Polyhedron >::begin(), FrameTemp< T >::FrameTemp(), and FrameAllocatorLockableHelper::lock().
void FrameAllocator::destroy (void) inline static
U32 FrameAllocator::getHighWaterMark () inline static
static U32 FrameAllocator::getMaxFrameAllocation () inline static
U32 FrameAllocator::getWaterMark () inline static
Referenced by SilhouetteExtractorBasePerspective< PolyhedronType >::begin(), SilhouetteExtractorBaseOrtho< Polyhedron >::begin(), FrameAllocatorMarker::FrameAllocatorMarker(), FrameTemp< T >::FrameTemp(), FrameAllocatorLockableHelper::lock(), and FrameAllocatorLockableHelper::unlock().
void FrameAllocator::init (const U32 frameSize) inline static
void FrameAllocator::setWaterMark (const U32 waterMark) inline static
Referenced by SilhouetteExtractorBasePerspective< PolyhedronType >::end(), SilhouetteExtractorBaseOrtho< Polyhedron >::end(), FrameAllocatorLockableHelper::unlock(), FrameAllocatorMarker::~FrameAllocatorMarker(), and FrameTemp< T >::~FrameTemp().
Copyright © GarageGames, LLC. All Rights Reserved.