SimFieldDictionary Class Reference
Main Modules Class List Namespace List Online
SimFieldDictionary Class Reference
Dictionary to keep track of dynamic fields on SimObject.
#include <console/simFieldDictionary.h>
Classes
struct Entry
Public Types
enum { HashTableSize = 19 }
Public Member Functions
SimFieldDictionary ()
~SimFieldDictionary ()
void assignFrom (SimFieldDictionary *dict)
Entry * findDynamicField (const String &fieldName) const
Entry * findDynamicField (StringTableEntry fieldName) const
U32 getFieldType (StringTableEntry slotName) const
const char * getFieldValue (StringTableEntry slotName)
U32 getNumFields () const
const U32 getVersion () const
Entry * operator[] (U32 index)
void printFields (SimObject *obj)
void setFieldType (StringTableEntry slotName, const char *typeString)
void setFieldType (StringTableEntry slotName, const U32 typeId)
void setFieldType (StringTableEntry slotName, ConsoleBaseType *type)
void setFieldValue (StringTableEntry slotName, const char *value)
void writeFields (SimObject *obj, Stream &strem, U32 tabStop)
Public Attributes
Entry * mHashTable [HashTableSize]
Detailed Description
Dictionary to keep track of dynamic fields on SimObject.
Member Enumeration Documentation
anonymous enum
Enumerator
HashTableSize
Constructor & Destructor Documentation
SimFieldDictionary::SimFieldDictionary ()
Referenced by getVersion().
SimFieldDictionary::~SimFieldDictionary ()
Referenced by getVersion().
Member Function Documentation
void SimFieldDictionary::assignFrom (SimFieldDictionary * dict)
Referenced by getVersion().
Entry* SimFieldDictionary::findDynamicField (const String & fieldName) const
Referenced by getVersion().
Entry* SimFieldDictionary::findDynamicField (StringTableEntry fieldName) const
U32 SimFieldDictionary::getFieldType (StringTableEntry slotName) const
Referenced by getVersion().
const char* SimFieldDictionary::getFieldValue (StringTableEntry slotName)
Referenced by getVersion().
U32 SimFieldDictionary::getNumFields () const inline
References operator[]().
const U32 SimFieldDictionary::getVersion () const inline
References assignFrom(), findDynamicField(), getFieldType(), getFieldValue(), printFields(), setFieldType(), setFieldValue(), SimFieldDictionary(), SimFieldDictionary::Entry::slotName, SimFieldDictionary::Entry::type, SimFieldDictionary::Entry::value, writeFields(), and ~SimFieldDictionary().
Entry* SimFieldDictionary::operator[] (U32 index)
Referenced by getNumFields().
void SimFieldDictionary::printFields (SimObject * obj)
Referenced by getVersion().
void SimFieldDictionary::setFieldType (StringTableEntry slotName, const char * typeString)
Referenced by getVersion().
void SimFieldDictionary::setFieldType (StringTableEntry slotName, const U32 typeId)
void SimFieldDictionary::setFieldType (StringTableEntry slotName, ConsoleBaseType * type)
void SimFieldDictionary::setFieldValue (StringTableEntry slotName, const char * value)
Referenced by getVersion().
void SimFieldDictionary::writeFields (SimObject * obj, Stream & strem, U32 tabStop)
Referenced by getVersion().
Member Data Documentation
Entry* SimFieldDictionary::mHashTable[HashTableSize]
Copyright © GarageGames, LLC. All Rights Reserved.