WeakRefBase Class Reference
Main Modules Class List Namespace List Online
WeakRefBase Class Reference
Base class for objects which can be weakly referenced (i.e., reference goes away when object is destroyed).
#include <core/util/refBase.h>
Classes
class WeakReference
Weak reference to WeakRefBase.
Public Member Functions
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Protected Member Functions
void clearWeakReferences ()
Detailed Description
Base class for objects which can be weakly referenced (i.e., reference goes away when object is destroyed).
Constructor & Destructor Documentation
WeakRefBase::WeakRefBase () inline
virtual WeakRefBase::~WeakRefBase () inline virtual
References clearWeakReferences(), and getWeakReference().
Member Function Documentation
void WeakRefBase::clearWeakReferences () inline protected
Referenced by ~WeakRefBase().
WeakRefBase::WeakReference * WeakRefBase::getWeakReference () inline
Referenced by ~WeakRefBase().
Copyright © GarageGames, LLC. All Rights Reserved.