SceneZoneCullingState Class Reference
Main Modules Class List Namespace List Online
SceneZoneCullingState Class Reference
Culling state for a zone.
#include <scene/culling/sceneZoneCullingState.h>
Classes
struct CullingVolumeIterator
Iterator over the culling volumes assigned to a zone.
struct CullingVolumeLink
A culling volume linked to a zone.
Public Types
enum CullingTestResult {
CullingTestPositiveByInclusion,
CullingTestPositiveByOcclusion,
CullingTestNegative
}
Result of a culling test in a zone.
Public Member Functions
SceneZoneCullingState ()
Zone states are constructed by SceneCullingState.
CullingVolumeLink * getCullingVolumes () const
Return the list of culling volumes attached to the zone.
bool hasIncluders () const
Return true if the zone has inclusion volumes assigned to it.
bool hasMultipleVolumes () const
Return true if the zone has more than one culling volume assigned to it.
bool hasOccluders () const
Return true if the zone has occlusion volumes assigned to it.
bool isZoneVisible () const
Return true if the zone is visible.
CullingTestResult testVolumes (const Box3F &aabb, bool occludersOnly=false) const
Test whether the culling volumes added to the zone test positive on the given AABB, i.e.
CullingTestResult testVolumes (const OrientedBox3F &obb, bool occludersOnly=false) const
Test whether the culling volumes added to the zone test positive on the given OBB, i.e.
CullingTestResult testVolumes (const SphereF &sphere, bool occludersOnly=false) const
Test whether the culling volumes added to the zone test positive on the given sphere, i.e.
Protected Member Functions
void _sortVolumes () const
Sort the culling volumes such that the volumes with the highest probability of rejecting objects come first in the list.
template<typename T >
CullingTestResult _testVolumes (T bounds, bool occludersOnly) const
Culling volume test abstracted over bounding volume type.
Static Protected Member Functions
static void _insertSorted (CullingVolumeLink *&head, CullingVolumeLink *&tail, CullingVolumeLink *link)
Insert the volume in link at the proper position in the list represented by head and tail.
Protected Attributes
bool mCanShortcuit
Whether tests can be short-circuited, i.e.
CullingVolumeLink * mCullingVolumes
Link of culling volumes defining the visibility state of the zone.
bool mHaveIncluders
Whether there are inclusion volumes on this state.
bool mHaveOccluders
Whether there are occlusion volumes on this state.
bool mHaveSortedVolumes
Whether culling volumes for this zone state have already been sorted.
Detailed Description
Culling state for a zone.
Zone states keep track of the culling volumes that are generated during traversal for a particular zone in a scene.
Note
This class has no meaningful constructor; the memory for all zone states is cleared en bloc.
Member Enumeration Documentation
enum SceneZoneCullingState::CullingTestResult
Result of a culling test in a zone.
Enumerator
CullingTestPositiveByInclusion
An includer tested positive on the bounding volume.
CullingTestPositiveByOcclusion
An occluder tested positive on the bounding volume.
CullingTestNegative
None of the culling volumes included or excluded the bounding volume.
Constructor & Destructor Documentation
SceneZoneCullingState::SceneZoneCullingState () inline
Zone states are constructed by SceneCullingState.
This constructor should not be used otherwise. It is public due to the use through Vector in SceneCullingState.
Member Function Documentation
static void SceneZoneCullingState::_insertSorted (CullingVolumeLink *& head, CullingVolumeLink *& tail, CullingVolumeLink * link) static protected
Insert the volume in link at the proper position in the list represented by head and tail.
void SceneZoneCullingState::_sortVolumes () const protected
Sort the culling volumes such that the volumes with the highest probability of rejecting objects come first in the list.
Also, make sure that all occluders come before all includers so that occlusion is handled correctly.
Referenced by getCullingVolumes().
template<typename T > CullingTestResult SceneZoneCullingState::_testVolumes (T bounds, bool occludersOnly) const protected
Culling volume test abstracted over bounding volume type.
CullingVolumeLink* SceneZoneCullingState::getCullingVolumes () const inline
Return the list of culling volumes attached to the zone.
References _sortVolumes(), mCullingVolumes, and testVolumes().
bool SceneZoneCullingState::hasIncluders () const inline
Return true if the zone has inclusion volumes assigned to it.
References mHaveIncluders.
bool SceneZoneCullingState::hasMultipleVolumes () const inline
Return true if the zone has more than one culling volume assigned to it.
References SceneZoneCullingState::CullingVolumeLink::mNext.
bool SceneZoneCullingState::hasOccluders () const inline
Return true if the zone has occlusion volumes assigned to it.
References mHaveOccluders.
bool SceneZoneCullingState::isZoneVisible () const inline
Return true if the zone is visible.
This is the case if any includers have been added to the zone's rendering state.
References mHaveIncluders.
CullingTestResult SceneZoneCullingState::testVolumes (const Box3F & aabb, bool occludersOnly = false) const
Test whether the culling volumes added to the zone test positive on the given AABB, i.e.
whether they include or exclude the given AABB.
Referenced by getCullingVolumes().
CullingTestResult SceneZoneCullingState::testVolumes (const OrientedBox3F & obb, bool occludersOnly = false) const
Test whether the culling volumes added to the zone test positive on the given OBB, i.e.
whether they include or exclude the given OBB.
Parameters
obb An OBB described by 8 points.
invertedOnly If true, only inverted cullers are tested.
CullingTestResult SceneZoneCullingState::testVolumes (const SphereF & sphere, bool occludersOnly = false) const
Test whether the culling volumes added to the zone test positive on the given sphere, i.e.
whether they include or exclude the given sphere.
Member Data Documentation
bool SceneZoneCullingState::mCanShortcuit protected
Whether tests can be short-circuited, i.e.
the first culler that rejects or accepts will cause the test to terminate. This is the case if there are no includers inside occluders, i.e. if occluders can be trusted to fully exclude any space they cover.
CullingVolumeLink* SceneZoneCullingState::mCullingVolumes mutable protected
Link of culling volumes defining the visibility state of the zone.
Since there may be multiple portals leading into a zone or multiple occluders inside a zone, we may have multiple culling volumes.
Referenced by getCullingVolumes().
bool SceneZoneCullingState::mHaveIncluders protected
Whether there are inclusion volumes on this state.
Referenced by hasIncluders(), and isZoneVisible().
bool SceneZoneCullingState::mHaveOccluders protected
Whether there are occlusion volumes on this state.
Referenced by hasOccluders().
bool SceneZoneCullingState::mHaveSortedVolumes mutable protected
Whether culling volumes for this zone state have already been sorted.
Copyright © GarageGames, LLC. All Rights Reserved.