SceneObjectLink Class Reference
Main Modules Class List Namespace List Online
SceneObjectLink Class Reference
A SceneObjectLink represents the link between a SceneObject and a SceneTracker.
#include <scene/sceneTracker.h>
Public Types
typedef void Parent
Public Member Functions
SceneObjectLink (SceneTracker *tracker, SceneObject *object)
virtual ~SceneObjectLink ()
SceneObjectLink * getNextLink () const
SceneObject * getObject () const
SceneObjectLink * getPrevLink () const
SceneTracker * getTracker () const
void update ()
Notify the associated tracker that the transform state of the scene object represented by this link has changed.
Static Public Member Functions
static SceneObjectLink * getLinkForTracker (SceneTracker *tracker, SceneObject *fromObject)
Protected Attributes
SceneObjectLink * mNextLink
Next scope link on this SceneObject; NULL if last.
SceneObject * mObject
SceneObject being linked to; always set and never changes.
SceneObjectLink * mPrevLink
Previous scope link on this SceneObject; NULL if first.
SceneTracker * mTracker
The scene tracker to which this link belongs.
Detailed Description
A SceneObjectLink represents the link between a SceneObject and a SceneTracker.
Member Typedef Documentation
typedef void SceneObjectLink::Parent
Constructor & Destructor Documentation
SceneObjectLink::SceneObjectLink (SceneTracker * tracker, SceneObject * object)
virtual SceneObjectLink::~SceneObjectLink () virtual
Member Function Documentation
static SceneObjectLink* SceneObjectLink::getLinkForTracker (SceneTracker * tracker, SceneObject * fromObject) static
Referenced by getPrevLink().
SceneObjectLink* SceneObjectLink::getNextLink () const inline
Returns
The next link in this link chain.
References mNextLink.
SceneObject* SceneObjectLink::getObject () const inline
Returns
The object being linked to.
References mObject.
SceneObjectLink* SceneObjectLink::getPrevLink () const inline
Returns
The previous link in this link chain.
References getLinkForTracker(), mPrevLink, and update().
SceneTracker* SceneObjectLink::getTracker () const inline
Returns
The SceneScopeTracker managing this link.
References mTracker.
void SceneObjectLink::update ()
Notify the associated tracker that the transform state of the scene object represented by this link has changed.
Referenced by getPrevLink().
Member Data Documentation
SceneObjectLink* SceneObjectLink::mNextLink protected
Next scope link on this SceneObject; NULL if last.
Referenced by getNextLink().
SceneObject* SceneObjectLink::mObject protected
SceneObject being linked to; always set and never changes.
Referenced by getObject().
SceneObjectLink* SceneObjectLink::mPrevLink protected
Previous scope link on this SceneObject; NULL if first.
Referenced by getPrevLink().
SceneTracker* SceneObjectLink::mTracker protected
The scene tracker to which this link belongs.
Referenced by getTracker().
Copyright © GarageGames, LLC. All Rights Reserved.