Material Class Reference
Main Modules Class List Namespace List Online
Material Class Reference
The basic material definition.
#include <materials/materialDefinition.h>
Classes
class StageData
Public Types
enum AnimType {
Scroll = 1,
Rotate = 2,
Wave = 4,
Scale = 8,
Sequence = 16
}
enum BlendOp {
None = 0,
Mul,
Add,
AddAlpha,
Sub,
LerpAlpha,
ToneMap,
NumBlendTypes
}
enum Constants {
MAX_TEX_PER_PASS = 8,
MAX_STAGES = 4,
NUM_EFFECT_COLOR_STAGES = 2
}
enum TexType {
NoTexture = 0,
Standard = 1,
Detail,
Bump,
DetailBump,
Env,
Cube,
SGCube,
Lightmap,
ToneMapTex,
Mask,
BackBuff,
ReflectBuff,
Misc,
DynamicLight,
DynamicLightMask,
NormalizeCube,
TexTarget,
AccuMap,
DynamicShadowMap
}
enum WaveType {
Sin = 0,
Triangle,
Square
}
Public Types inherited from SimObject
typedef ConsoleObject Parent
enum WriteFlags {
SelectedOnly = BIT(0),
NoName = BIT(1),
IgnoreCanSave = BIT(2)
}
Flags passed to SimObject::write.
Public Types inherited from EngineObject
typedef void(* DebugEnumInstancesCallback) (EngineObject *)
Type of callback function for iterating over EngineObject instances.
Public Member Functions
Material ()
Material interface.
virtual bool castsDynamicShadows () const
virtual bool castsShadows () const
virtual BaseMatInstance * createMatInstance ()
Allocates and returns a BaseMatInstance for this material.
DECLARE_CONOBJECT (Material)
void flush ()
const String & getPath () const
virtual void inspectPostApply ()
Called after any property of the object is changed in the world editor.
virtual bool isAutoGenerated () const
virtual bool isDoubleSided () const
virtual bool isLightmapped () const
virtual bool isTranslucent () const
virtual bool onAdd ()
Called when the object is added to the sim.
virtual void onRemove ()
Called when the object is removed from the sim.
void reload ()
Re-initializes all the material instances that use this material.
virtual void setAutoGenerated (bool isAutoGenerated)
void updateTimeBasedParams ()
Called to update time based parameters for a material.
virtual bool writeField (StringTableEntry fieldname, const char *value)
Determine whether or not a field should be written.
Public Member Functions inherited from SimObject
virtual void copyTo (SimObject *object)
Copy SimObject to another SimObject (Originally designed for T2D).
DECLARE_CONOBJECT (SimObject)
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
virtual SimObject * findObject (const char *name)
Find a named sub-object of this object.
virtual void getConsoleMethodData (const char *fname, S32 routingId, S32 *type, S32 *minArgs, S32 *maxArgs, void **callback, const char **usage)
Namespace * getNamespace ()
Return the object's namespace.
StringTableEntry getProgenitorFile (void) const
virtual bool handlesConsoleMethod (const char *fname, S32 *routingId)
void setProgenitorFile (const char *pFile)
const char * tabComplete (const char *prevText, S32 baseLen, bool)
Get next matching item in namespace.
virtual void write (Stream &stream, U32 tabStop, U32 flags=0)
Output the TorqueScript to recreate this object.
virtual void writeFields (Stream &stream, U32 tabStop)
Write the fields of this object in TorqueScript.
virtual bool writeObject (Stream *stream)
virtual bool readObject (Stream *stream)
void setCanSaveDynamicFields (bool bCanSave)
Set whether fields created at runtime should be saved. Default is true.
bool getCanSaveDynamicFields ()
Get whether fields created at runtime should be saved. Default is true.
SimObject * getCopySource () const
Return the object that this object is copying fields from.
void setCopySource (SimObject *object)
Set the object that this object should be copying fields from.
void assignFieldsFrom (SimObject *obj)
Copy fields from another object onto this one.
void assignDynamicFieldsFrom (SimObject *obj)
Copy dynamic fields from another object onto this one.
Notify * removeNotify (void *ptr, Notify::Type)
Remove a notification from the list.
void deleteNotify (SimObject *obj)
Notify an object when we are deleted.
void clearNotify (SimObject *obj)
Notify an object when we are cleared.
void clearAllNotifications ()
Remove all notifications for this object.
void processDeleteNotifies ()
Send out deletion notifications.
void registerReference (SimObject **obj)
Register a reference to this object.
void unregisterReference (SimObject **obj)
Unregister a reference to this object.
SimPersistID * getPersistentId () const
Return the persistent ID assigned to this object or NULL.
SimPersistID * getOrCreatePersistentId ()
Return the persistent ID assigned to this object or assign one to it if it has none.
StringTableEntry getClassNamespace () const
Return name of class namespace set on this object.
StringTableEntry getSuperClassNamespace () const
Return name of superclass namespace set on this object.
void setClassNamespace (const char *classNamespace)
void setSuperClassNamespace (const char *superClassNamespace)
virtual SimObject * clone ()
Return a shallow copy of this object.
virtual SimObject * deepClone ()
Return a deep copy of this object.
const char * getDataField (StringTableEntry slotName, const char *array)
Get the value of a field on the object.
void setDataField (StringTableEntry slotName, const char *array, const char *value)
Set the value of a field on the object.
const char * getPrefixedDataField (StringTableEntry fieldName, const char *array)
void setPrefixedDataField (StringTableEntry fieldName, const char *array, const char *value)
const char * getPrefixedDynamicDataField (StringTableEntry fieldName, const char *array, const S32 fieldType=-1)
void setPrefixedDynamicDataField (StringTableEntry fieldName, const char *array, const char *value, const S32 fieldType=-1)
StringTableEntry getDataFieldPrefix (StringTableEntry fieldName)
U32 getDataFieldType (StringTableEntry slotName, const char *array)
Get the type of a field on the object.
void setDataFieldType (const U32 fieldTypeId, StringTableEntry slotName, const char *array)
Set the type of a dynamic field on the object.
void setDataFieldType (const char *typeName, StringTableEntry slotName, const char *array)
SimFieldDictionary * getFieldDictionary ()
Get reference to the dictionary containing dynamic fields.
virtual StringTableEntry getComponentName ()
void setInternalName (const char *newname)
These functions support internal naming that is not namespace bound for locating child controls in a generic way.
StringTableEntry getInternalName () const
Get the internal name of this control.
void setOriginalName (const char *originalName)
Set the original name of this control.
StringTableEntry getOriginalName () const
Get the original name of this control.
void setFilename (const char *file)
These functions allow you to set and access the filename where this object was created.
StringTableEntry getFilename () const
Get the filename.
void setDeclarationLine (U32 lineNumber)
These functions are used to track the line number (1-based) on which the object was created if it was loaded from script.
S32 getDeclarationLine () const
Get the declaration line number.
virtual bool save (const char *pcFilePath, bool bOnlySelected=false, const char *preappend=NULL)
Save object as a TorqueScript File.
virtual bool isMethod (const char *methodName)
Check if a method exists in the objects current namespace.
virtual bool isField (const char *fieldName, bool includeStatic=true, bool includeDynamic=true)
Return true if the field is defined on the object.
SimObjectId getId () const
Return the unique numeric object ID.
const char * getIdString () const
Return the object ID as a string.
StringTableEntry getName () const
Return the name of this object.
SimGroup * getGroup () const
Return the SimGroup that this object is contained in.
void assignName (const char *name)
Assign the given name to this object.
void setId (SimObjectId id)
bool isChildOfGroup (SimGroup *pGroup)
bool isProperlyAdded () const
bool isDeleted () const
bool isRemoved () const
virtual bool isLocked () const
virtual void setLocked (bool b)
virtual bool isHidden () const
virtual void setHidden (bool b)
bool isSelected () const
bool isExpanded () const
bool isEditorOnly () const
bool isNameChangeAllowed () const
bool isAutoDeleted () const
void setSelected (bool sel)
void setExpanded (bool exp)
void setModDynamicFields (bool dyn)
void setModStaticFields (bool sta)
bool canModDynamicFields ()
bool canModStaticFields ()
void setAutoDelete (bool val)
void setEditorOnly (bool val)
void setNameChangeAllowed (bool val)
bool getCanSave () const
Returns boolean specifying if the object can be serialized.
virtual void setCanSave (bool val)
Set serialization flag.
bool isSelectedRecursive () const
Returns true if this object is selected or any group it is a member of is.
SimObject ()
virtual ~SimObject ()
virtual bool processArguments (S32 argc, ConsoleValueRef *argv)
Process constructor options. (ie, new SimObject(1,2,3))
virtual void onGroupAdd ()
Called when the object is added to a SimGroup.
virtual void onGroupRemove ()
Called when the object is removed from a SimGroup.
virtual void onNameChange (const char *name)
Called when the object's name is changed.
virtual void onPostAdd ()
Called when the adding of the object to the sim is complete, all sub-objects have been processed as well.
virtual void onStaticModified (const char *slotName, const char *newValue=NULL)
Specifically, these are called by setDataField when a static or dynamic field is modified, see the console details.
virtual void onDynamicModified (const char *slotName, const char *newValue=NULL)
Called when a dynamic field is modified.
virtual void inspectPreApply ()
Called before any property of the object is changed in the world editor.
virtual void onDeleteNotify (SimObject *object)
Called when a SimObject is deleted.
virtual void onEditorEnable ()
Called when the editor is activated.
virtual void onEditorDisable ()
Called when the editor is deactivated.
bool registerObject ()
Register an object with the object system.
bool registerObject (U32 id)
Register the object, forcing the id.
bool registerObject (const char *name)
Register the object, assigning the name.
bool registerObject (const char *name, U32 id)
Register the object, assigning a name and ID.
void unregisterObject ()
Unregister the object from Sim.
void deleteObject ()
Unregister, mark as deleted, and free the object.
void safeDeleteObject ()
Performs a safe delayed delete of the object using a sim event.
bool addToSet (SimObjectId)
bool addToSet (const char *)
bool removeFromSet (SimObjectId)
bool removeFromSet (const char *)
virtual String describeSelf () const
Return a textual description of the object.
void dumpToConsole (bool includeFunctions=true)
Dump the contents of this object to the console.
virtual void dumpClassHierarchy ()
added this so that you can print the entire class hierarchy, including script objects,
virtual void dumpGroupHierarchy ()
Print the SimGroup hierarchy of this object to the console.
Public Member Functions inherited from ConsoleObject
ConsoleObject ()
virtual AbstractClassRep * getClassRep () const
Gets the ClassRep.
const AbstractClassRep::Field * findField (StringTableEntry fieldName) const
Get a reference to a field by name.
bool setField (const char *fieldName, const char *value)
Set the value of a field.
void logMessage (const char *fmt,...) const
Logs with Con::printf.
void logWarning (const char *fmt,...) const
Logs with Con::warnf.
void logError (const char *fmt,...) const
Logs with Con::errorf.
const AbstractClassRep::FieldList & getFieldList () const
Get a list of all the fields. This information cannot be modified.
AbstractClassRep::FieldList & getModifiableFieldList ()
Get a list of all the fields, set up so we can modify them.
bool & getDynamicGroupExpand ()
Get a handle to a boolean telling us if we expanded the dynamic group.
S32 getClassId (U32 netClassGroup) const
Get our network-layer class id.
StringTableEntry getClassName () const
Get our compiler and platform independent class name.
Public Member Functions inherited from EngineObject
EngineObject ()
virtual ~EngineObject ()
DECLARE_ABSTRACT_CLASS (EngineObject, void)
DECLARE_INSCOPE (_GLOBALSCOPE)
IEngineObjectPool * getEngineObjectPool () const
Return the pool of EngineObjects to which this object belongs.
void operator delete (void *ptr)
Release the given object's memory in the pool it has been allocated from.
void * operator new (size_t size)
void * operator new (size_t size, IEngineObjectPool *pool)
void * operator new (size_t size TORQUE_TMM_ARGS_DECL)
Allocate a new object in the default object pool.
void * operator new (size_t size, IEngineObjectPool *pool TORQUE_TMM_ARGS_DECL)
Allocate a new object in the given object pool.
void * operator new (size_t size, void *ptr)
Placement new.
Public Member Functions inherited from StrongRefBase
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Static Public Member Functions
static bool _setAccuEnabled (void *object, const char *index, const char *data)
static GFXCubemap * GetNormalizeCube ()
static void initPersistFields ()
Static Public Member Functions inherited from SimObject
static SimObject * __findObject (const char *id)
static const char * __getObjectId (ConsoleObject *object)
static void initPersistFields ()
static void setForcedId (SimObjectId id)
Force an Id on the next registered object.
Static Public Member Functions inherited from ConsoleObject
static const char * __category ()
static const char * __description ()
static void consoleInit ()
Register global constant variables and do other one-time initialization tasks in a subclass of ConsoleObject.
static void initPersistFields ()
Register dynamic fields in a subclass of ConsoleObject.
static const char * lookupClassName (const U32 in_classTag)
Get the classname from a class tag.
static ConsoleObject * create (const char *in_pClassName)
static ConsoleObject * create (const U32 groupId, const U32 typeId, const U32 in_classId)
static void addGroup (const char *in_pGroupname, const char *in_pGroupDocs=NULL)
Mark the beginning of a group of fields.
static void endGroup (const char *in_pGroupname)
Mark the end of a group of fields.
static void addArray (const char *arrayName, S32 count)
Marks the start of a fixed size array of fields.
static void endArray (const char *arrayName)
Marks the end of an array of fields.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a complex field.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::WriteDataNotify in_writeDataFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, const char *in_pFieldDocs, U32 flags=0)
Register a simple field.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::WriteDataNotify in_writeDataFn, const char *in_pFieldDocs, U32 flags=0)
static void addFieldV (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, TypeValidator *v, const char *in_pFieldDocs=NULL)
Register a validated field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, AbstractClassRep::WriteDataNotify in_writeDataFn=&defaultProtectedWriteFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a complex protected field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, AbstractClassRep::WriteDataNotify in_writeDataFn=&defaultProtectedWriteFn, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a simple protected field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addDeprecatedField (const char *fieldName)
Add a deprecated field.
static bool removeField (const char *in_pFieldname)
Remove a field.
static AbstractClassRep * getStaticClassRep ()
Get the abstract class information for this class.
static AbstractClassRep * getParentStaticClassRep ()
Get the abstract class information for this class's superclass.
static ConsoleObject * __findObject (const char *)
static const char * __getObjectId (ConsoleObject *)
Static Public Member Functions inherited from EngineObject
static void debugDumpInstances ()
Dump describeSelf()s of all live ConsoleObjects to the console.
static void debugEnumInstances (const std::type_info &type, DebugEnumInstancesCallback callback)
Call the given callback for all instances of the given type.
static void debugEnumInstances (const char *className, DebugEnumInstancesCallback callback)
Same as above but uses an export class name and also includes inheritance (i.e.
Public Attributes
F32 mAccuCoverage [MAX_STAGES]
F32 mAccuDirection [MAX_STAGES]
bool mAccuEnabled [MAX_STAGES]
F32 mAccuScale [MAX_STAGES]
F32 mAccuSpecular [MAX_STAGES]
F32 mAccuStrength [MAX_STAGES]
U32 mAlphaRef
bool mAlphaTest
U32 mAnimFlags [MAX_STAGES]
bool mAutoGenerated
bool mCastDynamicShadows
bool mCastShadows
A generic setting which tells the system to skip generation of shadows from this material.
Point2I mCellIndex [MAX_STAGES]
Point2I mCellLayout [MAX_STAGES]
U32 mCellSize [MAX_STAGES]
CubemapData * mCubemapData
String mCubemapName
FileName mDetailMapFilename [MAX_STAGES]
FileName mDetailNormalMapFilename [MAX_STAGES]
A second normal map which repeats at the detail map scale and blended with the base normal map.
F32 mDetailNormalMapStrength [MAX_STAGES]
The strength scalar for the detail normal map.
Point2F mDetailScale [MAX_STAGES]
The repetition scale of the detail texture over the base texture.
ColorF mDiffuse [MAX_STAGES]
This color is the diffuse color of the material or if it has a texture it is multiplied against the diffuse texture color.
FileName mDiffuseMapFilename [MAX_STAGES]
bool mDoubleSided
bool mDynamicCubemap
bool mEmissive [MAX_STAGES]
bool mGlow [MAX_STAGES]
Point4F mImposterLimits
Specual imposter rendering paramters.
Vector< RectF > mImposterUVs
Special array of UVs for imposter rendering.
FileName mLightMapFilename [MAX_STAGES]
String mMapTo
F32 mMatInfoFlags [MAX_STAGES]
F32 mMinnaertConstant [MAX_STAGES]
bool mNormalMapAtlas [MAX_STAGES]
FileName mNormalMapFilename [MAX_STAGES]
FileName mOverlayMapFilename [MAX_STAGES]
F32 mParallaxScale [MAX_STAGES]
bool mPixelSpecular [MAX_STAGES]
bool mPlanarReflection
Point2F mRotPivotOffset [MAX_STAGES]
F32 mRotPos [MAX_STAGES]
F32 mRotSpeed [MAX_STAGES]
Point2F mScrollDir [MAX_STAGES]
Point2F mScrollOffset [MAX_STAGES]
F32 mScrollSpeed [MAX_STAGES]
F32 mSeqFramePerSec [MAX_STAGES]
F32 mSeqSegSize [MAX_STAGES]
ColorF mSpecular [MAX_STAGES]
FileName mSpecularMapFilename [MAX_STAGES]
F32 mSpecularPower [MAX_STAGES]
F32 mSpecularStrength [MAX_STAGES]
bool mSubSurface [MAX_STAGES]
ColorF mSubSurfaceColor [MAX_STAGES]
F32 mSubSurfaceRolloff [MAX_STAGES]
FileName mToneMapFilename [MAX_STAGES]
bool mTranslucent
BlendOp mTranslucentBlendOp
bool mTranslucentZWrite
bool mUseAnisotropic [MAX_STAGES]
If the stage should use anisotropic filtering.
bool mUseMetalness [MAX_STAGES]
bool mVertColor [MAX_STAGES]
If true for a stage, vertex colors are multiplied against diffuse colors.
bool mVertLit [MAX_STAGES]
F32 mWaveAmp [MAX_STAGES]
F32 mWaveFreq [MAX_STAGES]
F32 mWavePos [MAX_STAGES]
U32 mWaveType [MAX_STAGES]
bool mShowFootprints
If true, show footprints when walking on surface with this material. Defaults to false.
bool mShowDust
If true, show dust emitters (footpuffs, hover trails, etc) when on surface with this material. Defaults to false.
ColorF mEffectColor [NUM_EFFECT_COLOR_STAGES]
Color to use for particle effects and such when located on this material.
S32 mFootstepSoundId
Footstep sound to play when walking on surface with this material.
S32 mImpactSoundId
SFXTrack * mFootstepSoundCustom
Sound effect to play when walking on surface with this material.
SFXTrack * mImpactSoundCustom
F32 mFriction
Friction coefficient when moving along surface.
F32 mDirectSoundOcclusion
Amount of volume occlusion on direct sounds.
F32 mReverbSoundOcclusion
Amount of volume occlusion on reverb sounds.
Public Attributes inherited from EngineObject
DECLARE_INSTANTIABLE
Static Public Attributes
static bool sAllowTextureTargetAssignment
Static Public Attributes inherited from ConsoleObject
static const bool __smIsDatablock = false
Subclasses of ConsoleObjects that are datablocks should redefine this static member variable and set it to true.
Protected Member Functions
virtual void _mapMaterial ()
Map this material to the texture specified in the "mapTo" data variable.
Protected Member Functions inherited from SimObject
virtual void _destroySelf ()
Subclasses should overload this method instead of the public destroySelf().
virtual String _getLogMessage (const char *fmt, va_list args) const
We can provide more detail, like object name and id.
virtual void _onSelected ()
Called when the object is selected in the editor.
virtual void _onUnselected ()
Called when the object is unselected in the editor.
object incRefCount ()
virtual void onTamlAddParent (SimObject *pParentObject)
Called after Taml has finished reading the object and has added the object to any parent.
virtual void onTamlCustomRead (const TamlCustomNodes &customNodes)
Called during the reading of the object to allow custom properties to be read.
virtual void onTamlCustomWrite (TamlCustomNodes &customNodes)
Called during the writing of the object to allow custom properties to be written.
virtual void onTamlPostRead (const TamlCustomNodes &customNodes)
Called after Taml has finished reading the object.
virtual void onTamlPostWrite (void)
Called after Taml has finished writing the object.
virtual void onTamlPreRead (void)
Called prior to Taml reading the object.
virtual void onTamlPreWrite (void)
Taml callbacks.
object registerObject ()
void linkNamespaces ()
Perform namespace linking on this object.
void unlinkNamespaces ()
Undo namespace linking on this object.
Protected Member Functions inherited from ConsoleObject
ConsoleObject (const ConsoleObject &)
Protected Member Functions inherited from EngineObject
object incRefCount ()
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Protected Attributes
U32 mLastUpdateTime
String mPath
Protected Attributes inherited from SimObject
DEFINE_CREATE_METHOD
SimObjectId mId
Id number for this object.
StringTableEntry mInternalName
Internal name assigned to the object. Not set by default.
return object
bool mCanSaveFieldDictionary
Whether dynamic fields should be saved out in serialization. Defaults to true.
SimPersistID * mPersistentId
Persistent ID assigned to this object.
Namespace * mNameSpace
The namespace in which method lookup for this object begins.
StringTableEntry mClassName
Name of namespace to use as class namespace.
StringTableEntry mSuperClassName
Name of namespace to use as class super namespace.
Protected Attributes inherited from EngineObject
DEFINE_CREATE_METHOD
return object
Protected Attributes inherited from StrongRefBase
U32 mRefCount
reference counter for StrongRefPtr objects
Static Protected Attributes
static EnumTable mAnimFlagTable
static EnumTable mBlendOpTable
static EnumTable mWaveTypeTable
Static Protected Attributes inherited from SimObject
static SimObjectId smForcedId
The Id to force upon the object. Poor object.
static bool smForceId
Force a registered object to use the given Id. Cleared upon use.
Additional Inherited Members
Protected Types inherited from EngineObject
typedef ::FalseType __IsDisposableType
typedef ::FalseType __IsSingletonType
Static Protected Member Functions inherited from SimObject
static bool _setPersistentID (void *object, const char *index, const char *data)
Static Protected Member Functions inherited from EngineObject
static void * _allocateObject (size_t size, IEngineObjectPool *pool TORQUE_TMM_ARGS_DECL)
Detailed Description
The basic material definition.
Member Enumeration Documentation
enum Material::AnimType
Enumerator
Scroll
Rotate
Wave
Scale
Sequence
enum Material::BlendOp
Enumerator
None
Mul
Add
AddAlpha
Sub
LerpAlpha
ToneMap
NumBlendTypes
enum Material::Constants
Enumerator
MAX_TEX_PER_PASS
Number of textures per pass.
MAX_STAGES
NUM_EFFECT_COLOR_STAGES
Number of effect color definitions for transitioning effects.
enum Material::TexType
Enumerator
NoTexture
Standard
Detail
Bump
DetailBump
Env
Cube
SGCube
Lightmap
ToneMapTex
Mask
BackBuff
ReflectBuff
Misc
DynamicLight
DynamicLightMask
NormalizeCube
TexTarget
AccuMap
DynamicShadowMap
enum Material::WaveType
Enumerator
Sin
Triangle
Square
Constructor & Destructor Documentation
Material::Material ()
Material interface.
Member Function Documentation
virtual void Material::_mapMaterial () protected virtual
Map this material to the texture specified in the "mapTo" data variable.
Reimplemented in CustomMaterial.
static bool Material::_setAccuEnabled (void * object, const char * index, const char * data) static
Referenced by getPath().
virtual bool Material::castsDynamicShadows () const inline virtual
Implements BaseMaterialDefinition.
References mCastDynamicShadows.
virtual bool Material::castsShadows () const inline virtual
Implements BaseMaterialDefinition.
References mCastShadows.
virtual BaseMatInstance* Material::createMatInstance () virtual
Allocates and returns a BaseMatInstance for this material.
Caller is responsible for freeing the instance
Implements BaseMaterialDefinition.
Material::DECLARE_CONOBJECT (Material)
Referenced by getPath().
void Material::flush ()
Referenced by getPath().
static GFXCubemap* Material::GetNormalizeCube () static
const String& Material::getPath (void) const inline
References _setAccuEnabled(), DECLARE_CONOBJECT(), flush(), initPersistFields(), inspectPostApply(), mPath, onAdd(), onRemove(), reload(), updateTimeBasedParams(), and writeField().
static void Material::initPersistFields () static
Referenced by getPath().
virtual void Material::inspectPostApply () virtual
Called after any property of the object is changed in the world editor.
See also
inspectPreApply
Reimplemented from SimObject.
Referenced by getPath().
virtual bool Material::isAutoGenerated () const inline virtual
References mAutoGenerated.
Referenced by setAutoGenerated().
virtual bool Material::isDoubleSided () const inline virtual
Implements BaseMaterialDefinition.
References mDoubleSided.
virtual bool Material::isLightmapped () const virtual
Implements BaseMaterialDefinition.
Referenced by setAutoGenerated().
virtual bool Material::isTranslucent () const inline virtual
Implements BaseMaterialDefinition.
References None.
virtual bool Material::onAdd () virtual
Called when the object is added to the sim.
Reimplemented from SimObject.
Reimplemented in CustomMaterial.
Referenced by getPath().
virtual void Material::onRemove () virtual
Called when the object is removed from the sim.
Reimplemented from SimObject.
Reimplemented in CustomMaterial.
Referenced by getPath().
void Material::reload ()
Re-initializes all the material instances that use this material.
Referenced by getPath().
virtual void Material::setAutoGenerated (bool isAutoGenerated) inline virtual
References isAutoGenerated(), and isLightmapped().
void Material::updateTimeBasedParams ()
Called to update time based parameters for a material.
Ensures that it only happens once per tick.
Referenced by getPath().
virtual bool Material::writeField (StringTableEntry fieldname, const char * value) virtual
Determine whether or not a field should be written.
Parameters
fiedname The name of the field being written.
value The value of the field.
Reimplemented from SimObject.
Referenced by getPath().
Member Data Documentation
F32 Material::mAccuCoverage[MAX_STAGES]
F32 Material::mAccuDirection[MAX_STAGES]
bool Material::mAccuEnabled[MAX_STAGES]
F32 Material::mAccuScale[MAX_STAGES]
F32 Material::mAccuSpecular[MAX_STAGES]
F32 Material::mAccuStrength[MAX_STAGES]
U32 Material::mAlphaRef
bool Material::mAlphaTest
U32 Material::mAnimFlags[MAX_STAGES]
EnumTable Material::mAnimFlagTable static protected
bool Material::mAutoGenerated
Referenced by isAutoGenerated().
EnumTable Material::mBlendOpTable static protected
bool Material::mCastDynamicShadows
Referenced by castsDynamicShadows().
bool Material::mCastShadows
A generic setting which tells the system to skip generation of shadows from this material.
Referenced by castsShadows().
Point2I Material::mCellIndex[MAX_STAGES]
Point2I Material::mCellLayout[MAX_STAGES]
U32 Material::mCellSize[MAX_STAGES]
CubemapData* Material::mCubemapData
String Material::mCubemapName
FileName Material::mDetailMapFilename[MAX_STAGES]
FileName Material::mDetailNormalMapFilename[MAX_STAGES]
A second normal map which repeats at the detail map scale and blended with the base normal map.
F32 Material::mDetailNormalMapStrength[MAX_STAGES]
The strength scalar for the detail normal map.
Point2F Material::mDetailScale[MAX_STAGES]
The repetition scale of the detail texture over the base texture.
ColorF Material::mDiffuse[MAX_STAGES]
This color is the diffuse color of the material or if it has a texture it is multiplied against the diffuse texture color.
FileName Material::mDiffuseMapFilename[MAX_STAGES]
F32 Material::mDirectSoundOcclusion
Amount of volume occlusion on direct sounds.
bool Material::mDoubleSided
Referenced by isDoubleSided().
bool Material::mDynamicCubemap
ColorF Material::mEffectColor[NUM_EFFECT_COLOR_STAGES]
Color to use for particle effects and such when located on this material.
bool Material::mEmissive[MAX_STAGES]
SFXTrack* Material::mFootstepSoundCustom
Sound effect to play when walking on surface with this material.
If defined, overrides mFootstepSoundId.
See also
mFootstepSoundId
S32 Material::mFootstepSoundId
Footstep sound to play when walking on surface with this material.
Numeric ID of footstep sound defined on player datablock (0 == soft, 1 == hard, 2 == metal, 3 == snow). Defaults to -1 which deactivates default sound.
See also
mFootstepSoundCustom
F32 Material::mFriction
Friction coefficient when moving along surface.
bool Material::mGlow[MAX_STAGES]
SFXTrack* Material::mImpactSoundCustom
S32 Material::mImpactSoundId
Point4F Material::mImposterLimits
Specual imposter rendering paramters.
See also
TSLastDetail
Vector<RectF> Material::mImposterUVs
Special array of UVs for imposter rendering.
See also
TSLastDetail
U32 Material::mLastUpdateTime protected
FileName Material::mLightMapFilename[MAX_STAGES]
String Material::mMapTo
F32 Material::mMatInfoFlags[MAX_STAGES]
F32 Material::mMinnaertConstant[MAX_STAGES]
bool Material::mNormalMapAtlas[MAX_STAGES]
FileName Material::mNormalMapFilename[MAX_STAGES]
FileName Material::mOverlayMapFilename[MAX_STAGES]
F32 Material::mParallaxScale[MAX_STAGES]
String Material::mPath protected
Referenced by getPath().
bool Material::mPixelSpecular[MAX_STAGES]
bool Material::mPlanarReflection
F32 Material::mReverbSoundOcclusion
Amount of volume occlusion on reverb sounds.
Point2F Material::mRotPivotOffset[MAX_STAGES]
F32 Material::mRotPos[MAX_STAGES]
F32 Material::mRotSpeed[MAX_STAGES]
Point2F Material::mScrollDir[MAX_STAGES]
Point2F Material::mScrollOffset[MAX_STAGES]
F32 Material::mScrollSpeed[MAX_STAGES]
F32 Material::mSeqFramePerSec[MAX_STAGES]
F32 Material::mSeqSegSize[MAX_STAGES]
bool Material::mShowDust
If true, show dust emitters (footpuffs, hover trails, etc) when on surface with this material. Defaults to false.
bool Material::mShowFootprints
If true, show footprints when walking on surface with this material. Defaults to false.
Behavioral properties.
ColorF Material::mSpecular[MAX_STAGES]
FileName Material::mSpecularMapFilename[MAX_STAGES]
F32 Material::mSpecularPower[MAX_STAGES]
F32 Material::mSpecularStrength[MAX_STAGES]
bool Material::mSubSurface[MAX_STAGES]
ColorF Material::mSubSurfaceColor[MAX_STAGES]
F32 Material::mSubSurfaceRolloff[MAX_STAGES]
FileName Material::mToneMapFilename[MAX_STAGES]
bool Material::mTranslucent
BlendOp Material::mTranslucentBlendOp
bool Material::mTranslucentZWrite
bool Material::mUseAnisotropic[MAX_STAGES]
If the stage should use anisotropic filtering.
bool Material::mUseMetalness[MAX_STAGES]
bool Material::mVertColor[MAX_STAGES]
If true for a stage, vertex colors are multiplied against diffuse colors.
bool Material::mVertLit[MAX_STAGES]
F32 Material::mWaveAmp[MAX_STAGES]
F32 Material::mWaveFreq[MAX_STAGES]
F32 Material::mWavePos[MAX_STAGES]
U32 Material::mWaveType[MAX_STAGES]
EnumTable Material::mWaveTypeTable static protected
bool Material::sAllowTextureTargetAssignment static
Copyright © GarageGames, LLC. All Rights Reserved.