ConsoleValueRef Class Reference
Main Modules Class List Namespace List Online
ConsoleValueRef Class Reference
Console System
#include <console/console.h>
Public Member Functions
ConsoleValueRef ()
ConsoleValueRef (const ConsoleValueRef &ref)
~ConsoleValueRef ()
bool getBoolValue ()
F32 getFloatValue ()
U32 getIntValue ()
S32 getSignedIntValue ()
StringStackPtr getStringStackPtrValue ()
const char * getStringValue ()
S32 getType ()
bool isFloat ()
bool isInt ()
bool isString ()
bool isStringStackPtr ()
operator const char * ()
operator F32 ()
operator S32 ()
operator String ()
operator U32 ()
ConsoleValueRef & operator= (const ConsoleValueRef &other)
ConsoleValueRef & operator= (const char *newValue)
ConsoleValueRef & operator= (U32 newValue)
ConsoleValueRef & operator= (S32 newValue)
ConsoleValueRef & operator= (F32 newValue)
ConsoleValueRef & operator= (F64 newValue)
Static Public Member Functions
static ConsoleValueRef fromValue (ConsoleValue *value)
Public Attributes
ConsoleValue * value
Constructor & Destructor Documentation
ConsoleValueRef::ConsoleValueRef () inline
ConsoleValueRef::~ConsoleValueRef () inline
ConsoleValueRef::ConsoleValueRef (const ConsoleValueRef & ref)
Member Function Documentation
static ConsoleValueRef ConsoleValueRef::fromValue (ConsoleValue * value) inline static
References value.
bool ConsoleValueRef::getBoolValue () inline
References ConsoleValue::getBoolValue().
F32 ConsoleValueRef::getFloatValue () inline
References ConsoleValue::getFloatValue().
Referenced by dAtof().
U32 ConsoleValueRef::getIntValue () inline
References ConsoleValue::getIntValue().
S32 ConsoleValueRef::getSignedIntValue () inline
References ConsoleValue::getSignedIntValue().
Referenced by dAtoi().
StringStackPtr ConsoleValueRef::getStringStackPtrValue () inline
References ConsoleValue::getStringStackPtr().
const char* ConsoleValueRef::getStringValue () inline
References ConsoleValue::getStringValue().
Referenced by EngineUnmarshallData< const char * >::operator()(), and EngineUnmarshallData< T * >::operator()().
S32 ConsoleValueRef::getType () inline
References ConsoleValue::type.
bool ConsoleValueRef::isFloat () inline
References ConsoleValue::type, and ConsoleValue::TypeInternalFloat.
bool ConsoleValueRef::isInt () inline
References ConsoleValue::type, and ConsoleValue::TypeInternalInt.
bool ConsoleValueRef::isString () inline
References ConsoleValue::type, and ConsoleValue::TypeInternalStringStackPtr.
bool ConsoleValueRef::isStringStackPtr () inline
References ConsoleValue::type, and ConsoleValue::TypeInternalStringStackPtr.
ConsoleValueRef::operator const char * () inline
ConsoleValueRef::operator F32 () inline
ConsoleValueRef::operator S32 () inline
ConsoleValueRef::operator String () inline
ConsoleValueRef::operator U32 () inline
ConsoleValueRef& ConsoleValueRef::operator= (const ConsoleValueRef & other)
ConsoleValueRef& ConsoleValueRef::operator= (const char * newValue)
ConsoleValueRef& ConsoleValueRef::operator= (U32 newValue)
ConsoleValueRef& ConsoleValueRef::operator= (S32 newValue)
ConsoleValueRef& ConsoleValueRef::operator= (F32 newValue)
ConsoleValueRef& ConsoleValueRef::operator= (F64 newValue)
Member Data Documentation
ConsoleValue* ConsoleValueRef::value
Referenced by _EngineConsoleExecCallbackHelper< const char * >::call(), and fromValue().
Copyright © GarageGames, LLC. All Rights Reserved.