GFXVertexBuffer Class Reference
Main Modules Class List Namespace List Online
GFXVertexBuffer Class Reference abstract
#include <gfx/gfxVertexBuffer.h>
Public Member Functions
GFXVertexBuffer (GFXDevice *device, U32 numVerts, const GFXVertexFormat *vertexFormat, U32 vertexSize, GFXBufferType bufferType)
virtual const String describeSelf () const
The resource should put a description of itself (number of vertices, size/width of texture, etc.) in buffer.
virtual void lock (U32 vertexStart, U32 vertexEnd, void **vertexPtr)=0
virtual void prepare ()=0
virtual void unlock ()=0
Public Member Functions inherited from StrongRefBase
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Public Member Functions inherited from GFXResource
GFXResource ()
virtual ~GFXResource ()
void clearFlag ()
GFXResource * getNextResource () const
GFXDevice * getOwningDevice () const
GFXResource * getPrevResource () const
bool isFlagged ()
void registerResourceWithDevice (GFXDevice *device)
Registers this resource with the given device.
virtual void resurrect ()=0
When called the resource should restore all device sensitive information destroyed by zombify()
void setFlag ()
virtual void zombify ()=0
When called the resource should destroy all device sensitive information (e.g. D3D resources in D3DPOOL_DEFAULT.
Public Attributes
bool isLocked
U32 lockedVertexEnd
void * lockedVertexPtr
U32 lockedVertexStart
GFXBufferType mBufferType
GFX buffer type (static, dynamic or volatile).
GFXDevice * mDevice
Device this vertex buffer was allocated on.
U32 mNumVerts
Number of vertices in this buffer.
GFXVertexFormat mVertexFormat
A copy of the vertex format for this buffer.
U32 mVertexSize
Vertex size in bytes.
U32 mVolatileStart
Additional Inherited Members
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Protected Attributes inherited from StrongRefBase
U32 mRefCount
reference counter for StrongRefPtr objects
Constructor & Destructor Documentation
GFXVertexBuffer::GFXVertexBuffer (GFXDevice * device, U32 numVerts, const GFXVertexFormat * vertexFormat, U32 vertexSize, GFXBufferType bufferType) inline
References GFXVertexFormat::copy(), describeSelf(), GFXVertexFormat::getDecl(), lock(), prepare(), and unlock().
Member Function Documentation
virtual const String GFXVertexBuffer::describeSelf () const virtual
The resource should put a description of itself (number of vertices, size/width of texture, etc.) in buffer.
Implements GFXResource.
Referenced by GFXVertexBuffer().
virtual void GFXVertexBuffer::lock (U32 vertexStart, U32 vertexEnd, void ** vertexPtr) pure virtual
Implemented in GFXD3D11VertexBuffer, and GFXGLVertexBuffer.
Referenced by GFXVertexBuffer().
virtual void GFXVertexBuffer::prepare () pure virtual
Implemented in GFXD3D11VertexBuffer, and GFXGLVertexBuffer.
Referenced by GFXVertexBuffer().
virtual void GFXVertexBuffer::unlock () pure virtual
Implemented in GFXD3D11VertexBuffer, and GFXGLVertexBuffer.
Referenced by GFXVertexBuffer().
Member Data Documentation
bool GFXVertexBuffer::isLocked
U32 GFXVertexBuffer::lockedVertexEnd
Referenced by GFXD3D11VertexBuffer::GFXD3D11VertexBuffer(), and GFXVertexBufferHandle< GFXWaterVertex >::operator[]().
void* GFXVertexBuffer::lockedVertexPtr
Referenced by GFXVertexBufferHandleBase::lock(), and GFXVertexBufferHandle< GFXWaterVertex >::operator[]().
U32 GFXVertexBuffer::lockedVertexStart
Referenced by GFXD3D11VertexBuffer::GFXD3D11VertexBuffer(), and GFXVertexBufferHandle< GFXWaterVertex >::operator[]().
GFXBufferType GFXVertexBuffer::mBufferType
GFX buffer type (static, dynamic or volatile).
Referenced by GFXVertexBufferHandleBase::lock().
GFXDevice* GFXVertexBuffer::mDevice
Device this vertex buffer was allocated on.
U32 GFXVertexBuffer::mNumVerts
Number of vertices in this buffer.
Referenced by GFXVertexBufferHandleBase::lock().
GFXVertexFormat GFXVertexBuffer::mVertexFormat
A copy of the vertex format for this buffer.
Referenced by GFXDevice::setVertexBuffer().
U32 GFXVertexBuffer::mVertexSize
Vertex size in bytes.
U32 GFXVertexBuffer::mVolatileStart
Copyright © GarageGames, LLC. All Rights Reserved.