MatInstance Class Reference
Main Modules Class List Namespace List Online
MatInstance Class Reference
#include <materials/matInstance.h>
Public Member Functions
virtual ~MatInstance ()
virtual void addShaderMacro (const String &name, const String &value)
Adds a shader macro which will be passed to the shader during initialization.
virtual void addStateBlockDesc (const GFXStateBlockDesc &desc)
Adds this stateblock to the base state block used during initialization.
virtual MaterialParameters * allocMaterialParameters ()
Get a MaterialParameters block for this BaseMatInstance, caller is responsible for freeing it.
virtual void dumpShaderInfo () const
virtual U32 getCurPass ()
virtual U32 getCurStageNum ()
virtual const FeatureSet & getFeatures () const
Returns the active features in use by this material.
virtual Material * getMaterial ()
Returns the material this instance is based on.
virtual MaterialParameterHandle * getMaterialParameterHandle (const String &name)
Returns a MaterialParameterHandle for name.
virtual MaterialParameters * getMaterialParameters ()
Get the current parameters for this BaseMatInstance (BaseMatInstances are created with a default active MaterialParameters which is managed by BaseMatInstance.
virtual RenderPassData * getPass (U32 pass)
ProcessedMaterial * getProcessedMaterial () const
virtual const FeatureSet & getRequestedFeatures () const
Returns the features that were requested at material creation time which may differ from the active features.
virtual const MatStateHint & getStateHint () const
Returns the state hint which can be used for sorting and fast comparisions of the equality of a material instance.
virtual SimObject * getUserObject () const
virtual const GFXStateBlockDesc & getUserStateBlock () const
virtual const GFXVertexFormat * getVertexFormat () const
virtual bool hasAccumulation ()
virtual bool hasGlow ()
virtual bool init (const FeatureSet &features, const GFXVertexFormat *vertexFormat)
virtual bool isCustomMaterial () const
Returns true if this MatInstance is built from a CustomMaterial.
virtual bool isForwardLit () const
Returns true if the material is forward lit and requires a list of lights which affect it when rendering.
virtual bool isHardwareSkinned () const
virtual bool isInstanced () const
Returns true if this material is instanced.
virtual bool reInit ()
Reinitializes the material using the previous initialization parameters.
virtual void setBuffers (GFXVertexBufferHandleBase *vertBuffer, GFXPrimitiveBufferHandle *primBuffer)
Sets the vertex and primitive buffers as well as the instancing stream buffer for the current material if the material is instanced.
virtual void setMaterialParameters (MaterialParameters *param)
Set the current parameters for this BaseMatInstance.
virtual void setNodeTransforms (const MatrixF *address, const U32 numTransforms)
Sets node transforms for the current stage. Used for hardware skinning.
virtual void setSceneInfo (SceneRenderState *, const SceneData &sgData)
This initializes various material scene state settings and should be called after setupPass() within the pass loop.
virtual void setTextureStages (SceneRenderState *state, const SceneData &sgData)
This is normally called from within setupPass() automatically, so its unnecessary to do so manually unless a texture stage has changed.
virtual void setTransforms (const MatrixSet &matrixSet, SceneRenderState *state)
This initializes the material transforms and should be called after setupPass() within the pass loop.
virtual bool setupPass (SceneRenderState *, const SceneData &sgData)
Sets up the next rendering pass for this material.
virtual void setUserObject (SimObject *userObject)
Sets a SimObject which will passed into ShaderFeature::createConstHandles.
virtual bool stepInstance ()
Used to increment the instance buffer for this material.
virtual void updateStateBlocks ()
Updates the state blocks for this material.
Public Member Functions inherited from BaseMatInstance
virtual ~BaseMatInstance ()
MatFeaturesDelegate & getFeaturesDelegate ()
bool hasNormalMap () const
Fast test for use of normal maps in this material.
bool isValid ()
Returns true if init has been successfully called.
bool usesHardwareSkinning () const
void addHook (MatInstanceHook *hook)
template<class HOOK >
HOOK * getHook ()
Helper function for getting a hook.
MatInstanceHook * getHook (const MatInstanceHookType &type) const
void deleteHook (const MatInstanceHookType &type)
U32 deleteAllHooks ()
Protected Member Functions
MatInstance (Material &mat)
Create a material instance by reference to a Material.
virtual ProcessedMaterial * getShaderMaterial ()
virtual bool processMaterial ()
Protected Attributes
MatInstParameters * mActiveParameters
bool mCreatedFromCustomMaterial
S32 mCurPass
Vector< MatInstanceParameterHandle * > mCurrentHandles
Vector< MatInstParameters * > mCurrentParameters
MatInstParameters * mDefaultParameters
FeatureSet mFeatureList
The features requested at material creation time.
bool mIsForwardLit
If the processed material requires forward lighting or not.
bool mIsHardwareSkinned
If the processed material requires bone transforms.
Material * mMaterial
U32 mMaxStages
ProcessedMaterial * mProcessedMaterial
GFXStateBlockDesc mUserDefinedState
Vector< GFXShaderMacro > mUserMacros
SimObject * mUserObject
const GFXVertexFormat * mVertexFormat
The vertex format on which this material will render.
Protected Attributes inherited from BaseMatInstance
MatFeaturesDelegate mFeaturesDelegate
bool mHasNormalMaps
This is set by initialization and used by the deferred.
Vector< MatInstanceHook * > mHooks
The array of active material hooks indexed by a MatInstanceHookType.
bool mIsValid
Should be true if init has been called and it succeeded.
bool mUsesHardwareSkinning
This material makes use of bone transforms.
Constructor & Destructor Documentation
virtual MatInstance::~MatInstance () virtual
MatInstance::MatInstance (Material & mat) protected
Create a material instance by reference to a Material.
Member Function Documentation
virtual void MatInstance::addShaderMacro (const String & name, const String & value) virtual
Adds a shader macro which will be passed to the shader during initialization.
See also
init
Implements BaseMatInstance.
virtual void MatInstance::addStateBlockDesc (const GFXStateBlockDesc & desc) virtual
Adds this stateblock to the base state block used during initialization.
See also
init
Implements BaseMatInstance.
virtual MaterialParameters* MatInstance::allocMaterialParameters () virtual
Get a MaterialParameters block for this BaseMatInstance, caller is responsible for freeing it.
Implements BaseMatInstance.
virtual void MatInstance::dumpShaderInfo () const virtual
Implements BaseMatInstance.
Referenced by getRequestedFeatures().
virtual U32 MatInstance::getCurPass () inline virtual
Implements BaseMatInstance.
References getCurStageNum(), getPass(), getStateHint(), and mCurPass.
virtual U32 MatInstance::getCurStageNum () virtual
Implements BaseMatInstance.
Referenced by getCurPass().
virtual const FeatureSet& MatInstance::getFeatures () const virtual
Returns the active features in use by this material.
See also
getRequestedFeatures
Implements BaseMatInstance.
Referenced by getVertexFormat().
virtual Material* MatInstance::getMaterial () inline virtual
Returns the material this instance is based on.
Implements BaseMatInstance.
References hasAccumulation(), hasGlow(), and mMaterial.
virtual MaterialParameterHandle* MatInstance::getMaterialParameterHandle (const String & name) virtual
Returns a MaterialParameterHandle for name.
Implements BaseMatInstance.
virtual MaterialParameters* MatInstance::getMaterialParameters () virtual
Get the current parameters for this BaseMatInstance (BaseMatInstances are created with a default active MaterialParameters which is managed by BaseMatInstance.
Implements BaseMatInstance.
virtual RenderPassData* MatInstance::getPass (U32 pass) virtual
Implements BaseMatInstance.
Referenced by getCurPass().
ProcessedMaterial* MatInstance::getProcessedMaterial () const inline
References mProcessedMaterial.
virtual const FeatureSet& MatInstance::getRequestedFeatures () const inline virtual
Returns the features that were requested at material creation time which may differ from the active features.
See also
getFeatures
Implements BaseMatInstance.
References dumpShaderInfo(), and mFeatureList.
virtual ProcessedMaterial* MatInstance::getShaderMaterial () protected virtual
Reimplemented in DeferredMatInstance.
virtual const MatStateHint& MatInstance::getStateHint () const virtual
Returns the state hint which can be used for sorting and fast comparisions of the equality of a material instance.
Implements BaseMatInstance.
Referenced by getCurPass().
virtual SimObject* MatInstance::getUserObject () const inline virtual
Implements BaseMatInstance.
References mUserObject.
virtual const GFXStateBlockDesc& MatInstance::getUserStateBlock () const inline virtual
Implements BaseMatInstance.
References mUserDefinedState.
virtual const GFXVertexFormat* MatInstance::getVertexFormat () const inline virtual
Implements BaseMatInstance.
References getFeatures(), and mVertexFormat.
virtual bool MatInstance::hasAccumulation () virtual
Implements BaseMatInstance.
Referenced by getMaterial().
virtual bool MatInstance::hasGlow () virtual
Implements BaseMatInstance.
Referenced by getMaterial().
virtual bool MatInstance::init (const FeatureSet & features, const GFXVertexFormat * vertexFormat) virtual
Parameters
features The features you want to allow for this material.
vertexFormat The vertex format on which this material will be rendered.
See also
GFXVertexFormat
FeatureSet
Implements BaseMatInstance.
Reimplemented in DeferredMatInstance, and LightMatInstance.
Referenced by ReflectionMaterialHook::getReflectMat().
virtual bool MatInstance::isCustomMaterial () const inline virtual
Returns true if this MatInstance is built from a CustomMaterial.
Implements BaseMatInstance.
References mCreatedFromCustomMaterial.
virtual bool MatInstance::isForwardLit () const inline virtual
Returns true if the material is forward lit and requires a list of lights which affect it when rendering.
Implements BaseMatInstance.
References mIsForwardLit.
virtual bool MatInstance::isHardwareSkinned () const inline virtual
References mIsHardwareSkinned.
virtual bool MatInstance::isInstanced () const virtual
Returns true if this material is instanced.
Implements BaseMatInstance.
virtual bool MatInstance::processMaterial () protected virtual
virtual bool MatInstance::reInit () virtual
Reinitializes the material using the previous initialization parameters.
See also
init
Implements BaseMatInstance.
virtual void MatInstance::setBuffers (GFXVertexBufferHandleBase * vertBuffer, GFXPrimitiveBufferHandle * primBuffer) virtual
Sets the vertex and primitive buffers as well as the instancing stream buffer for the current material if the material is instanced.
Implements BaseMatInstance.
virtual void MatInstance::setMaterialParameters (MaterialParameters * param) virtual
Set the current parameters for this BaseMatInstance.
Implements BaseMatInstance.
virtual void MatInstance::setNodeTransforms (const MatrixF * address, const U32 numTransforms) virtual
Sets node transforms for the current stage. Used for hardware skinning.
Implements BaseMatInstance.
virtual void MatInstance::setSceneInfo (SceneRenderState * state, const SceneData & sgData) virtual
This initializes various material scene state settings and should be called after setupPass() within the pass loop.
See also
setupPass
Implements BaseMatInstance.
virtual void MatInstance::setTextureStages (SceneRenderState * , const SceneData & sgData) virtual
This is normally called from within setupPass() automatically, so its unnecessary to do so manually unless a texture stage has changed.
If so it should be called after setupPass() within the pass loop.
See also
setupPass
Implements BaseMatInstance.
virtual void MatInstance::setTransforms (const MatrixSet & matrixSet, SceneRenderState * state) virtual
This initializes the material transforms and should be called after setupPass() within the pass loop.
See also
setupPass
Implements BaseMatInstance.
virtual bool MatInstance::setupPass (SceneRenderState * state, const SceneData & sgData) virtual
Sets up the next rendering pass for this material.
It is typically called like so...
while(mat->setupPass(state, sgData))
{
   mat->setTransforms(...);
   mat->setSceneInfo(...);
   ...
   GFX->drawPrimitive();
}
Implements BaseMatInstance.
Reimplemented in LightMatInstance, ShadowMatInstance, and ReflectionMatInstance.
virtual void MatInstance::setUserObject (SimObject * userObject) inline virtual
Sets a SimObject which will passed into ShaderFeature::createConstHandles.
Normal features do not make use of this, it is for special class specific or user designed features.
Implements BaseMatInstance.
References mUserObject.
virtual bool MatInstance::stepInstance () virtual
Used to increment the instance buffer for this material.
Implements BaseMatInstance.
virtual void MatInstance::updateStateBlocks () virtual
Updates the state blocks for this material.
Implements BaseMatInstance.
Member Data Documentation
MatInstParameters* MatInstance::mActiveParameters protected
bool MatInstance::mCreatedFromCustomMaterial protected
Referenced by isCustomMaterial().
S32 MatInstance::mCurPass protected
Referenced by getCurPass().
Vector<MatInstanceParameterHandle*> MatInstance::mCurrentHandles protected
Vector<MatInstParameters*> MatInstance::mCurrentParameters protected
MatInstParameters* MatInstance::mDefaultParameters protected
FeatureSet MatInstance::mFeatureList protected
The features requested at material creation time.
Referenced by getRequestedFeatures().
bool MatInstance::mIsForwardLit protected
If the processed material requires forward lighting or not.
Referenced by isForwardLit().
bool MatInstance::mIsHardwareSkinned protected
If the processed material requires bone transforms.
Referenced by isHardwareSkinned().
Material* MatInstance::mMaterial protected
Referenced by getMaterial().
U32 MatInstance::mMaxStages protected
ProcessedMaterial* MatInstance::mProcessedMaterial protected
Referenced by getProcessedMaterial().
GFXStateBlockDesc MatInstance::mUserDefinedState protected
Referenced by getUserStateBlock().
Vector<GFXShaderMacro> MatInstance::mUserMacros protected
SimObject* MatInstance::mUserObject protected
Referenced by getUserObject(), and setUserObject().
const GFXVertexFormat* MatInstance::mVertexFormat protected
The vertex format on which this material will render.
Referenced by getVertexFormat().
Copyright © GarageGames, LLC. All Rights Reserved.