AnimatedElementList< T > Struct Template Reference
Main Modules Class List Namespace List Online
AnimatedElementList< T > Struct Template Reference
#include <ts/collada/colladaUtils.h>
Public Member Functions
AnimatedElementList (const daeElement *e=0)
T getValue (F32 time)
bool isAnimated ()
bool isAnimated (F32 start, F32 end)
Public Member Functions inherited from AnimatedElement< T >
AnimatedElement (const daeElement *e=0)
T getValue (F32 time)
Get the value of the element at the specified time.
bool isAnimated ()
Check if the element has any animations channels.
bool isAnimated (F32 start, F32 end)
Additional Inherited Members
Public Attributes inherited from AnimatedElement< T >
T defaultVal
Default value (used when element is NULL)
const daeElement * element
The Collada element (can be NULL)
Constructor & Destructor Documentation
template<class T > AnimatedElementList< T >::AnimatedElementList (const daeElement * e = 0) inline
Member Function Documentation
template<class T > T AnimatedElementList< T >::getValue (F32 time) inline
References AnimData::enabled, AnimData::getAnimChannels(), AnimData::interpValue(), Vector< T >::size(), T, AnimData::targetValueCount, and AnimData::targetValueOffset.
template<class T > bool AnimatedElementList< T >::isAnimated () inline
template<class T > bool AnimatedElementList< T >::isAnimated (F32 start, F32 end) inline
Copyright © GarageGames, LLC. All Rights Reserved.