EngineUnmarshallData< T * > Struct Template Reference
Main Modules Class List Namespace List Online
EngineUnmarshallData< T * > Struct Template Reference
#include <console/engineAPI.h>
Public Member Functions
T * operator() (ConsoleValueRef &ref) const
T * operator() (const char *str) const
Member Function Documentation
template<typename T > T* EngineUnmarshallData< T * >::operator() (ConsoleValueRef & ref) const inline
References Sim::findObject(), ConsoleValueRef::getStringValue(), and T.
template<typename T > T* EngineUnmarshallData< T * >::operator() (const char * str) const inline
References Sim::findObject(), and T.
Copyright © GarageGames, LLC. All Rights Reserved.