Var Struct Reference
Main Modules Class List Namespace List Online
Var Struct Reference
#include <shaderGen/langElement.h>
Public Member Functions
Var ()
Var (const char *name, const char *type)
virtual void print (Stream &stream)
void setConnectName (const char *newName)
void setStructName (const char *newName)
void setType (const char *newType)
void setUniform (const String &constType, const String &constName, ConstantSortPosition sortPos)
Public Member Functions inherited from LangElement
LangElement ()
virtual ~LangElement ()
void setName (const char *newName)
Static Public Member Functions
static U32 getTexUnitNum (U32 numElements=1)
static void reset ()
Static Public Member Functions inherited from LangElement
static void deleteElements ()
static LangElement * find (const char *name)
Public Attributes
U32 arraySize
char connectName [32]
bool connector
U32 constNum
ConstantSortPosition constSortPos
U32 rank
bool sampler
U8 structName [32]
U32 texCoordNum
bool texture
U8 type [32]
bool uniform
bool vertData
Public Attributes inherited from LangElement
U8 name [32]
Static Public Attributes
static U32 texUnitCount
Static Public Attributes inherited from LangElement
static Vector< LangElement * > elementList
Detailed Description
Var - Variable - used to specify a variable to be used in a shader. Var stores information such that when it is printed out, its context can be identified and the proper information will automatically be printed. For instance, if a variable is created with 'uniform' set to true, when the shader function definition is printed, it will automatically add that variable to the incoming parameters of the shader. There are several similar cases such as when a new variable is declared within a shader.
example:
Var *modelview = new Var;
modelview->setType("float4x4");
modelview->setName("modelview");
modelview->uniform = true;
modelview->constSortPos = cspPass;
it prints out in the shader declaration as:
ConnectData main(VertData IN,
                  uniform float4x4 modelview : register(C0) )
Constructor & Destructor Documentation
Var::Var ()
Var::Var (const char * name, const char * type)
Member Function Documentation
static U32 Var::getTexUnitNum (U32 numElements = 1) static
virtual void Var::print (Stream & stream) virtual
Reimplemented from LangElement.
static void Var::reset () static
void Var::setConnectName (const char * newName)
void Var::setStructName (const char * newName)
void Var::setType (const char * newType)
Referenced by AccuScaleFeature::processPix(), AccuDirectionFeature::processPix(), AccuStrengthFeature::processPix(), AccuCoverageFeature::processPix(), and AccuSpecularFeature::processPix().
void Var::setUniform (const String & constType, const String & constName, ConstantSortPosition sortPos)
Member Data Documentation
U32 Var::arraySize
char Var::connectName[32]
bool Var::connector
U32 Var::constNum
ConstantSortPosition Var::constSortPos
Referenced by AccuScaleFeature::processPix(), AccuDirectionFeature::processPix(), AccuStrengthFeature::processPix(), AccuCoverageFeature::processPix(), and AccuSpecularFeature::processPix().
U32 Var::rank
bool Var::sampler
U8 Var::structName[32]
U32 Var::texCoordNum
bool Var::texture
U32 Var::texUnitCount static
U8 Var::type[32]
bool Var::uniform
Referenced by AccuScaleFeature::processPix(), AccuDirectionFeature::processPix(), AccuStrengthFeature::processPix(), AccuCoverageFeature::processPix(), and AccuSpecularFeature::processPix().
bool Var::vertData
Copyright © GarageGames, LLC. All Rights Reserved.