SceneData Struct Reference
Main Modules Class List Namespace List Online
SceneData Struct Reference
#include <materials/sceneData.h>
Public Types
enum BinType {
RegularBin = 0,
GlowBin,
DeferredBin
}
The special bin types.
Public Member Functions
SceneData ()
Constructor.
void init (const SceneRenderState *state, BinType type=RegularBin)
Initializes the data with the scene state setting common scene wide parameters.
void setFogParams (const FogData &data)
Public Attributes
GFXTextureObject * accuTex
ColorF ambientLightColor
GFXTextureObject * backBuffTex
BinType binType
This defines when we're rendering a special bin type that the material or lighting system needs to know about.
GFXCubemap * cubemap
ColorF fogColor
F32 fogDensity
F32 fogDensityOffset
F32 fogHeightFalloff
GFXTextureObject * lightmap
LightInfo * lights [8]
The current lights to use in rendering in order of the light importance.
void * materialHint
A generic hint value passed from the game code down to the material for use by shader features.
GFXTextureObject * miscTex
const MatrixF * objTrans
GFXTextureObject * reflectTex
F32 visibility
bool wireframe
Enables wireframe rendering for the object.
Member Enumeration Documentation
enum SceneData::BinType
The special bin types.
Enumerator
RegularBin
A normal render bin that isn't one of the special bins we care about.
GlowBin
The glow render bin.
See also
RenderGlowMgr
DeferredBin
The deferred render bin.
Constructor & Destructor Documentation
SceneData::SceneData () inline
Constructor.
References dMemset(), and MatrixF::Identity.
Member Function Documentation
void SceneData::init (const SceneRenderState * state, BinType type = RegularBin) inline
Initializes the data with the scene state setting common scene wide parameters.
References dMemset(), SceneRenderState::getAmbientLightColor(), SceneManager::getFogData(), SceneRenderState::getSceneManager(), GFXDevice::getWireframe(), MatrixF::Identity, and setFogParams().
void SceneData::setFogParams (const FogData & data) inline
References FogData::atmosphereHeight, FogData::color, FogData::density, and FogData::densityOffset.
Referenced by init().
Member Data Documentation
GFXTextureObject* SceneData::accuTex
ColorF SceneData::ambientLightColor
GFXTextureObject* SceneData::backBuffTex
BinType SceneData::binType
This defines when we're rendering a special bin type that the material or lighting system needs to know about.
GFXCubemap* SceneData::cubemap
ColorF SceneData::fogColor
F32 SceneData::fogDensity
F32 SceneData::fogDensityOffset
F32 SceneData::fogHeightFalloff
GFXTextureObject* SceneData::lightmap
LightInfo* SceneData::lights[8]
The current lights to use in rendering in order of the light importance.
void* SceneData::materialHint
A generic hint value passed from the game code down to the material for use by shader features.
GFXTextureObject* SceneData::miscTex
const MatrixF* SceneData::objTrans
GFXTextureObject* SceneData::reflectTex
F32 SceneData::visibility
bool SceneData::wireframe
Enables wireframe rendering for the object.
Copyright © GarageGames, LLC. All Rights Reserved.