PolyhedronVectorData Struct Reference
Main Modules Class List Namespace List Online
PolyhedronVectorData Struct Reference
Polyhedron data stored in Vectors.
#include <math/mPolyhedron.h>
Public Types
typedef Vector< Edge > EdgeListType
typedef Vector< PlaneF > PlaneListType
typedef Vector< Point3F > PointListType
Public Types inherited from PolyhedronData
typedef Edge EdgeType
typedef PlaneF PlaneType
typedef Point3F PointType
Public Member Functions
PolyhedronVectorData ()
void buildBox (const MatrixF &mat, const Box3F &box, bool invertNormals=false)
void buildFromPlanes (const PlaneSetF &planes)
Build a polyhedron from the given set of planes.
operator AnyPolyhedron () const
Conversion to the common polyhedron type.
Accessors
U32 getNumPlanes () const
Return the number of planes that make up this polyhedron.
PlaneF * getPlanes () const
Return the planes that make up the polyhedron.
U32 getNumPoints () const
Return the number of points that this polyhedron has.
Point3F * getPoints () const
U32 getNumEdges () const
Return the number of edges that this polyhedron has.
Edge * getEdges () const
Public Attributes
EdgeListType edgeList
List of edges.
PlaneListType planeList
List of planes. Note that by default, the normals facing inwards.
PointListType pointList
List of vertices.
Additional Inherited Members
Static Public Member Functions inherited from PolyhedronData
template<typename Polyhedron >
static void buildBoxData (Polyhedron &poly, const MatrixF &mat, const Box3F &box, bool invertNormals=false)
Detailed Description
Polyhedron data stored in Vectors.
Member Typedef Documentation
typedef Vector< Edge > PolyhedronVectorData::EdgeListType
typedef Vector< PlaneF > PolyhedronVectorData::PlaneListType
typedef Vector< Point3F > PolyhedronVectorData::PointListType
Constructor & Destructor Documentation
PolyhedronVectorData::PolyhedronVectorData () inline
Member Function Documentation
void PolyhedronVectorData::buildBox (const MatrixF & mat, const Box3F & box, bool invertNormals = false) inline
References PolyhedronData::buildBoxData(), and Vector< T >::setSize().
void PolyhedronVectorData::buildFromPlanes (const PlaneSetF & planes)
Build a polyhedron from the given set of planes.
Edge* PolyhedronVectorData::getEdges () const inline
References Vector< T >::address().
U32 PolyhedronVectorData::getNumEdges () const inline
Return the number of edges that this polyhedron has.
References Vector< T >::size().
U32 PolyhedronVectorData::getNumPlanes () const inline
Return the number of planes that make up this polyhedron.
References Vector< T >::size().
U32 PolyhedronVectorData::getNumPoints () const inline
Return the number of points that this polyhedron has.
References Vector< T >::size().
PlaneF* PolyhedronVectorData::getPlanes () const inline
Return the planes that make up the polyhedron.
Note
The normals of these planes are facing inwards.
References Vector< T >::address().
Point3F* PolyhedronVectorData::getPoints () const inline
References Vector< T >::address().
PolyhedronVectorData::operator AnyPolyhedron () const inline
Conversion to the common polyhedron type.
Member Data Documentation
EdgeListType PolyhedronVectorData::edgeList
List of edges.
PlaneListType PolyhedronVectorData::planeList
List of planes. Note that by default, the normals facing inwards.
PointListType PolyhedronVectorData::pointList
List of vertices.
Copyright © GarageGames, LLC. All Rights Reserved.