matrix:
  include:
  - os: osx
    env: ADDITIONAL_CMAKE_ARGS="-DTORQUE_TESTING=off -DTORQUE_PHYSICS_BULLET=on" DEPLOYABLE_CONF=true #CXXFLAGS="-fgnu-inline-asm -fasm-blocks"
    osx_image: xcode8
    compiler: clang

language: cpp

install:
- brew install sdl2
- sudo brew link sdl2
- source ./Tools/travis/install.sh

script:
- |
  if [[ $TRAVIS_OS_NAME = linux ]];then
  docker_exec ./Tools/travis/script.sh
  else
  ./Tools/travis/script.sh
  fi

