ConditionerFeature Class Reference
Main Modules Class List Namespace List Online
ConditionerFeature Class Reference
#include <shaderGen/conditionerFeature.h>
Public Types
enum MethodType {
ConditionMethod = 0,
UnconditionMethod,
NumMethodTypes
}
Public Types inherited from ShaderFeature
enum OutputTarget {
DefaultTarget = 1 << 0,
RenderTarget1 = 1 << 1,
RenderTarget2 = 1 << 2,
RenderTarget3 = 1 << 3
}
Public Member Functions
ConditionerFeature (const GFXFormat bufferFormat)
virtual ~ConditionerFeature ()
virtual LangElement * assignColor (LangElement *elem, Material::BlendOp blend, LangElement *lerpElem=NULL, ShaderFeature::OutputTarget outputTarget=ShaderFeature::DefaultTarget)
Helper function for applying the color to shader output.
virtual LangElement * assignOutput (Var *unconditionedOutput, ShaderFeature::OutputTarget outputTarget=ShaderFeature::DefaultTarget)
virtual LangElement * expandNormalMap (LangElement *sampleNormalOp, LangElement *normalDecl, LangElement *normalVar, const MaterialFeatureData &fd)
Expand and assign a normal map. This takes care of compressed normal maps as well.
virtual Material::BlendOp getBlendOp ()
Identifies what type of blending a feature uses.
virtual GFXFormat getBufferFormat () const
virtual ConditionerMethodDependency * getConditionerMethodDependency (MethodType methodType)
virtual const String & getShaderMethodName (MethodType methodType)
virtual Var * getVertTexCoord (const String &name)
Get the incoming base texture coords - useful for bumpmap and detail maps.
virtual bool setBufferFormat (const GFXFormat bufferFormat)
virtual LangElement * setupTexSpaceMat (Vector< ShaderComponent * > &componentList, Var **texSpaceMat)
Set up a texture space matrix - to pass into pixel shader.
Public Member Functions inherited from ShaderFeature
ShaderFeature ()
virtual ~ShaderFeature ()
virtual void addDependency (const ShaderDependency *depends)
Adds a dependency to this shader feature.
virtual ShaderFeatureConstHandles * createConstHandles (GFXShader *shader, SimObject *userObject)
virtual void determineFeature (Material *material, const GFXVertexFormat *vertexFormat, U32 stageNum, const FeatureType &type, const FeatureSet &features, MaterialFeatureData *outFeatureData)
virtual const Vector< const ShaderDependency * > & getDependencies () const
Gets the dependency list for this shader feature.
virtual String getName ()=0
Returns the name of this feature.
LangElement * getOutput () const
returns output from a processed vertex or pixel shader
virtual U32 getOutputTargets (const MaterialFeatureData &fd) const
Gets the render target this shader feature is assigning data to.
const char * getOutputTargetVarName (OutputTarget target=DefaultTarget) const
Returns the name of output targer var.
virtual const char * getOutputVarName () const
Returns the output variable name for this feature if it applies.
S32 getProcessIndex () const
virtual Resources getResources (const MaterialFeatureData &fd)
Returns the resource requirements of this feature based on what other features are present.
virtual void processPix (Vector< ShaderComponent * > &componentList, const MaterialFeatureData &fd)
virtual void processPixMacros (Vector< GFXShaderMacro > &macros, const MaterialFeatureData &fd)
Allows the feature to add macros to pixel shader compiles.
virtual void processVert (Vector< ShaderComponent * > &componentList, const MaterialFeatureData &fd)
virtual void processVertMacros (Vector< GFXShaderMacro > &macros, const MaterialFeatureData &fd)
Allows the feature to add macros to vertex shader compiles.
virtual void reset ()
Called after processing the vertex and processing the pixel to cleanup any temporary structures stored in the feature.
void setInstancingFormat (GFXVertexFormat *format)
void setProcessIndex (S32 index)
virtual void setTexData (Material::StageData &stageDat, const MaterialFeatureData &fd, RenderPassData &passData, U32 &texIndex)
Fills texture related info in RenderPassData for this feature.
Static Public Member Functions
static void updateConditioners ()
Static Public Member Functions inherited from ShaderFeature
static Var * findOrCreateLocal (const char *name, const char *type, MultiLine *multi)
A simpler helper function which either finds the existing local var or creates one.
Static Public Attributes
static const String ConditionerIncludeFileName
Protected Member Functions
virtual Var * _conditionOutput (Var *unconditionedOutput, MultiLine *meta)
void _print (Stream *stream)
virtual void _printMethod (MethodType methodType, const String &methodName, Stream &stream)
virtual Var * _unconditionInput (Var *conditionedInput, MultiLine *meta)
virtual void printFooterComment (MethodType methodType, const String &methodName, Stream &stream, MultiLine *meta)
virtual void printHeaderComment (MethodType methodType, const String &methodName, Stream &stream, MultiLine *meta)
virtual void printMethodFooter (MethodType methodType, Var *retVar, Stream &stream, MultiLine *meta)
virtual Var * printMethodHeader (MethodType methodType, const String &methodName, Stream &stream, MultiLine *meta)
Static Protected Member Functions
static void _updateConditioners ()
Protected Attributes
GFXFormat mBufferFormat
String mConditionMethodName
ConditionerMethodDependency * mMethodDependency [NumMethodTypes]
String mShaderIncludePath
String mUnconditionMethodName
Protected Attributes inherited from ShaderFeature
Vector< const ShaderDependency * > mDependencies
The list of unique shader dependencies.
S32 mProcessIndex
LangElement * output
Static Protected Attributes
static Vector< ConditionerFeature * > smConditioners
static bool smDirtyConditioners
Additional Inherited Members
Public Attributes inherited from ShaderFeature
GFXVertexFormat * mInstancingFormat
const GFXVertexFormat * mVertexFormat
Member Enumeration Documentation
enum ConditionerFeature::MethodType
Enumerator
ConditionMethod
Method used to take unconditioned data, and turn it into a format that can be written to the conditioned buffer.
UnconditionMethod
Method used to take conditioned data from a buffer, and extract what is stored.
NumMethodTypes
Constructor & Destructor Documentation
ConditionerFeature::ConditionerFeature (const GFXFormat bufferFormat)
virtual ConditionerFeature::~ConditionerFeature () virtual
Member Function Documentation
virtual Var* ConditionerFeature::_conditionOutput (Var * unconditionedOutput, MultiLine * meta) protected virtual
Reimplemented in LinearEyeDepthConditioner, GBufferConditionerGLSL, GBufferConditionerHLSL, and AdvancedLightBufferConditioner.
void ConditionerFeature::_print (Stream * stream) protected
virtual void ConditionerFeature::_printMethod (MethodType methodType, const String & methodName, Stream & stream) protected virtual
virtual Var* ConditionerFeature::_unconditionInput (Var * conditionedInput, MultiLine * meta) protected virtual
Reimplemented in LinearEyeDepthConditioner, GBufferConditionerGLSL, GBufferConditionerHLSL, and AdvancedLightBufferConditioner.
static void ConditionerFeature::_updateConditioners () static protected
Referenced by updateConditioners().
virtual LangElement* ConditionerFeature::assignColor (LangElement * elem, Material::BlendOp blend, LangElement * lerpElem = NULL, ShaderFeature::OutputTarget outputTarget = ShaderFeature::DefaultTarget) inline virtual
Helper function for applying the color to shader output.
Parameters
elem The rbg or rgba color to assign.
blend The type of blending to perform.
lerpElem The optional lerp parameter when doing a LerpAlpha blend, if not set then the elem is used.
Implements ShaderFeature.
References assignOutput(), ShaderFeature::DefaultTarget, getConditionerMethodDependency(), and getShaderMethodName().
virtual LangElement* ConditionerFeature::assignOutput (Var * unconditionedOutput, ShaderFeature::OutputTarget outputTarget = ShaderFeature::DefaultTarget) virtual
Referenced by assignColor().
virtual LangElement* ConditionerFeature::expandNormalMap (LangElement * sampleNormalOp, LangElement * normalDecl, LangElement * normalVar, const MaterialFeatureData & fd) inline virtual
Expand and assign a normal map. This takes care of compressed normal maps as well.
Implements ShaderFeature.
virtual Material::BlendOp ConditionerFeature::getBlendOp () inline virtual
Identifies what type of blending a feature uses.
This is used to group features with the same blend operation together in a multipass situation.
Reimplemented from ShaderFeature.
References Material::None.
virtual GFXFormat ConditionerFeature::getBufferFormat () const inline virtual
References mBufferFormat.
virtual ConditionerMethodDependency* ConditionerFeature::getConditionerMethodDependency (MethodType methodType) virtual
Referenced by assignColor().
virtual const String& ConditionerFeature::getShaderMethodName (MethodType methodType) virtual
Referenced by assignColor().
virtual Var* ConditionerFeature::getVertTexCoord (const String & name) inline virtual
Get the incoming base texture coords - useful for bumpmap and detail maps.
Implements ShaderFeature.
virtual void ConditionerFeature::printFooterComment (MethodType methodType, const String & methodName, Stream & stream, MultiLine * meta) protected virtual
virtual void ConditionerFeature::printHeaderComment (MethodType methodType, const String & methodName, Stream & stream, MultiLine * meta) protected virtual
virtual void ConditionerFeature::printMethodFooter (MethodType methodType, Var * retVar, Stream & stream, MultiLine * meta) protected virtual
Reimplemented in AdvancedLightBufferConditioner.
virtual Var* ConditionerFeature::printMethodHeader (MethodType methodType, const String & methodName, Stream & stream, MultiLine * meta) protected virtual
Reimplemented in LinearEyeDepthConditioner, GBufferConditionerGLSL, GBufferConditionerHLSL, and AdvancedLightBufferConditioner.
virtual bool ConditionerFeature::setBufferFormat (const GFXFormat bufferFormat) inline virtual
References mBufferFormat.
virtual LangElement* ConditionerFeature::setupTexSpaceMat (Vector< ShaderComponent * > & componentList, Var ** texSpaceMat) inline virtual
Set up a texture space matrix - to pass into pixel shader.
Implements ShaderFeature.
static void ConditionerFeature::updateConditioners () inline static
References _updateConditioners(), and smDirtyConditioners.
Member Data Documentation
const String ConditionerFeature::ConditionerIncludeFileName static
GFXFormat ConditionerFeature::mBufferFormat protected
Referenced by getBufferFormat(), and setBufferFormat().
String ConditionerFeature::mConditionMethodName protected
ConditionerMethodDependency* ConditionerFeature::mMethodDependency[NumMethodTypes] protected
String ConditionerFeature::mShaderIncludePath protected
String ConditionerFeature::mUnconditionMethodName protected
Vector<ConditionerFeature*> ConditionerFeature::smConditioners static protected
bool ConditionerFeature::smDirtyConditioners static protected
Referenced by updateConditioners().
Copyright © GarageGames, LLC. All Rights Reserved.