ResourceHolderBase Class Reference
Main Modules Class List Namespace List Online
ResourceHolderBase Class Reference
#include <core/resource.h>
Public Member Functions
virtual ~ResourceHolderBase ()
void * getResource () const
Static Public Attributes
static FreeListChunker< ResourceHolderBase > smHolderFactory
Protected Member Functions
ResourceHolderBase (void *p)
Protected Attributes
void * mRes
Constructor & Destructor Documentation
virtual ResourceHolderBase::~ResourceHolderBase () inline virtual
ResourceHolderBase::ResourceHolderBase (void * p) inline protected
Member Function Documentation
void* ResourceHolderBase::getResource () const inline
References mRes.
Referenced by Resource< TSShape >::getUnloadSignal(), Resource< TSShape >::operator const TSShape *(), Resource< TSShape >::operator TSShape *(), Resource< TSShape >::operator*(), and Resource< TSShape >::operator->().
Member Data Documentation
void* ResourceHolderBase::mRes protected
Referenced by getResource(), and ResourceHolder< T >::~ResourceHolder().
FreeListChunker<ResourceHolderBase> ResourceHolderBase::smHolderFactory static
Referenced by Resource< TSShape >::getUnloadSignal().
Copyright © GarageGames, LLC. All Rights Reserved.