Zip::Compressor Class Reference
Main Modules Class List Namespace List Online
Zip::Compressor Class Reference abstract
Zip Code » Zip Code Internals
#include <core/util/zip/compressor.h>
Public Member Functions
Compressor (S32 method, const char *name)
virtual ~Compressor ()
virtual Stream * createReadStream (const CentralDir *cdir, Stream *zipStream)=0
virtual Stream * createWriteStream (const CentralDir *cdir, Stream *zipStream)=0
S32 getMethod ()
const char * getName ()
Static Public Member Functions
static Compressor * findCompressor (const char *name)
static Compressor * findCompressor (S32 method)
Protected Attributes
S32 mMethod
The compression method as in the Zip header.
const char * mName
The name of the compression method.
Constructor & Destructor Documentation
Zip::Compressor::Compressor (S32 method, const char * name)
virtual Zip::Compressor::~Compressor () inline virtual
Member Function Documentation
virtual Stream* Zip::Compressor::createReadStream (const CentralDir * cdir, Stream * zipStream) pure virtual
Referenced by getMethod().
virtual Stream* Zip::Compressor::createWriteStream (const CentralDir * cdir, Stream * zipStream) pure virtual
Referenced by getMethod().
static Compressor* Zip::Compressor::findCompressor (const char * name) static
Referenced by Zip::ZipArchive::createNewFile(), and getMethod().
static Compressor* Zip::Compressor::findCompressor (S32 method) static
S32 Zip::Compressor::getMethod () inline
References createReadStream(), createWriteStream(), findCompressor(), and mMethod.
const char* Zip::Compressor::getName () inline
References mName.
Member Data Documentation
S32 Zip::Compressor::mMethod protected
The compression method as in the Zip header.
Referenced by getMethod().
const char* Zip::Compressor::mName protected
The name of the compression method.
Referenced by getName().
Copyright © GarageGames, LLC. All Rights Reserved.