ConvexFeature Class Reference
Main Modules Class List Namespace List Online
ConvexFeature Class Reference
#include <collision/convex.h>
Classes
struct Edge
struct Face
Public Member Functions
ConvexFeature ()
bool collide (ConvexFeature &cf, CollisionList *cList, F32 tol=0.1)
bool inVolume (const Point3F &v)
void reset ()
void testEdge (ConvexFeature *cf, const Point3F &s1, const Point3F &e1, CollisionList *cList, F32 tol)
void testVertex (const Point3F &v, CollisionList *cList, bool, F32 tol)
Public Attributes
BaseMatInstance * material
Vector< Edge > mEdgeList
Vector< Face > mFaceList
Vector< Point3F > mVertexList
SceneObject * object
Constructor & Destructor Documentation
ConvexFeature::ConvexFeature () inline
References collide(), inVolume(), reset(), testEdge(), and testVertex().
Member Function Documentation
bool ConvexFeature::collide (ConvexFeature & cf, CollisionList * cList, F32 tol = 0.1)
Referenced by ConvexFeature().
bool ConvexFeature::inVolume (const Point3F & v)
Referenced by ConvexFeature().
void ConvexFeature::reset ()
Referenced by ConvexFeature().
void ConvexFeature::testEdge (ConvexFeature * cf, const Point3F & s1, const Point3F & e1, CollisionList * cList, F32 tol)
Referenced by ConvexFeature().
void ConvexFeature::testVertex (const Point3F & v, CollisionList * cList, bool , F32 tol)
Referenced by ConvexFeature().
Member Data Documentation
BaseMatInstance* ConvexFeature::material
Vector<Edge> ConvexFeature::mEdgeList
Vector<Face> ConvexFeature::mFaceList
Vector<Point3F> ConvexFeature::mVertexList
SceneObject* ConvexFeature::object
Copyright © GarageGames, LLC. All Rights Reserved.