GFXD3D11QueryFence Class Reference
Main Modules Class List Namespace List Online
GFXD3D11QueryFence Class Reference
#include <gfx/D3D11/gfxD3D11QueryFence.h>
Public Member Functions
GFXD3D11QueryFence (GFXDevice *device)
virtual ~GFXD3D11QueryFence ()
virtual void block ()
This method will not return until the fence has been processed by the GPU.
virtual const String describeSelf () const
The resource should put a description of itself (number of vertices, size/width of texture, etc.) in buffer.
virtual FenceStatus getStatus () const
This is a non-blocking call to get the status of the fence.
virtual void issue ()
This method inserts the fence into the command buffer.
virtual void resurrect ()
When called the resource should restore all device sensitive information destroyed by zombify()
virtual void zombify ()
When called the resource should destroy all device sensitive information (e.g. D3D resources in D3DPOOL_DEFAULT.
Public Member Functions inherited from GFXFence
GFXFence (GFXDevice *device)
virtual ~GFXFence ()
Public Member Functions inherited from GFXResource
GFXResource ()
virtual ~GFXResource ()
void clearFlag ()
GFXResource * getNextResource () const
GFXDevice * getOwningDevice () const
GFXResource * getPrevResource () const
bool isFlagged ()
void registerResourceWithDevice (GFXDevice *device)
Registers this resource with the given device.
void setFlag ()
Additional Inherited Members
Public Types inherited from GFXFence
enum FenceStatus {
Unset,
Pending,
Processed,
Unsupported
}
The states returned by getStatus()
Protected Attributes inherited from GFXFence
GFXDevice * mDevice
Constructor & Destructor Documentation
GFXD3D11QueryFence::GFXD3D11QueryFence (GFXDevice * device) inline
References block(), describeSelf(), getStatus(), issue(), resurrect(), zombify(), and ~GFXD3D11QueryFence().
virtual GFXD3D11QueryFence::~GFXD3D11QueryFence () virtual
Referenced by GFXD3D11QueryFence().
Member Function Documentation
virtual void GFXD3D11QueryFence::block () virtual
This method will not return until the fence has been processed by the GPU.
Implements GFXFence.
Referenced by GFXD3D11QueryFence().
virtual const String GFXD3D11QueryFence::describeSelf () const virtual
The resource should put a description of itself (number of vertices, size/width of texture, etc.) in buffer.
Implements GFXResource.
Referenced by GFXD3D11QueryFence().
virtual FenceStatus GFXD3D11QueryFence::getStatus () const virtual
This is a non-blocking call to get the status of the fence.
See also
GFXFence::FenceStatus
Implements GFXFence.
Referenced by GFXD3D11QueryFence().
virtual void GFXD3D11QueryFence::issue () virtual
This method inserts the fence into the command buffer.
Implements GFXFence.
Referenced by GFXD3D11QueryFence().
virtual void GFXD3D11QueryFence::resurrect () virtual
When called the resource should restore all device sensitive information destroyed by zombify()
Implements GFXResource.
Referenced by GFXD3D11QueryFence().
virtual void GFXD3D11QueryFence::zombify () virtual
When called the resource should destroy all device sensitive information (e.g. D3D resources in D3DPOOL_DEFAULT.
Implements GFXResource.
Referenced by GFXD3D11QueryFence().
Copyright © GarageGames, LLC. All Rights Reserved.