ShapeBaseConvex Class Reference
Main Modules Class List Namespace List Online
ShapeBaseConvex Class Reference
#include <T3D/shapeBase.h>
Public Member Functions
ShapeBaseConvex ()
ShapeBaseConvex (const ShapeBaseConvex &cv)
void findNodeTransform ()
Box3F getBoundingBox () const
Returns the bounding box for the object this is built around in world space.
Box3F getBoundingBox (const MatrixF &mat, const Point3F &scale) const
Returns the object space bounding box for the object this is built around transformed and scaled.
void getFeatures (const MatrixF &mat, const VectorF &n, ConvexFeature *cf)
This is used by the GJK collision in Vehicle.
void getPolyList (AbstractPolyList *list)
Builds a collision poly list out of this convex.
const MatrixF & getTransform () const
Returns the transform of the object this is built around.
Point3F support (const VectorF &v) const
Returns the farthest point, along a vector, still bound by the convex.
Public Member Functions inherited from Convex
Convex ()
Constructor.
virtual ~Convex ()
Destructor.
void addToWorkingList (Convex *ptr)
Adds the provided Convex to the list of objects within the bounds of this Convex.
void clearWorkingList ()
Clear out the working collision list of objects.
void collectGarbage ()
Runs through the linked list of Convex objects and removes the ones with no references.
CollisionState * findClosestState (const MatrixF &mat, const Point3F &scale, const F32 dontCareDist=1)
Finds the closest.
bool getCollisionInfo (const MatrixF &mat, const Point3F &scale, CollisionList *cList, F32 tol)
SceneObject * getObject () const
Returns the object this Convex is built from.
virtual const Point3F & getScale () const
Returns the scale of the object this is built around.
CollisionStateList * getStateList () const
Returns the list of objects this object is testing against.
ConvexType getType () const
Returns the type of this Convex.
CollisionWorkingList & getWorkingList ()
Returns the list of objects currently inside the bounds of this Convex.
void nukeList ()
Deletes all convex objects in the list.
void registerObject (Convex *convex)
Registers another Convex by linking it after this one.
virtual void render ()
Render this convex for debugging purposes.
virtual void renderWorkingList ()
Render convex(s) for debugging purposes.
void updateStateList (const MatrixF &mat, const Point3F &scale, const Point3F *displacement=NULL)
Updates the CollisionStateList (mList) with new collision states and removing ones no longer under consideration.
void updateWorkingList (const Box3F &box, const U32 colMask)
Updates the working collision list of objects which are currently colliding with (inside the bounds of) this Convex.
Public Attributes
Box3F box
U32 hullId
MatrixF * transform
Protected Attributes
MatrixF * nodeTransform
ShapeBase * pShapeBase
Protected Attributes inherited from Convex
CollisionStateList mList
Objects we're testing against.
SceneObject * mObject
Object this Convex is built around.
CollisionWorkingList mReference
Other convex testing against us.
ConvexType mType
Type of Convex this is.
CollisionWorkingList mWorking
Objects within our bounds.
Constructor & Destructor Documentation
ShapeBaseConvex::ShapeBaseConvex () inline
References Convex::mType.
ShapeBaseConvex::ShapeBaseConvex (const ShapeBaseConvex & cv) inline
References box, findNodeTransform(), getBoundingBox(), getFeatures(), getPolyList(), getTransform(), hullId, Convex::mObject, nodeTransform, pShapeBase, and support().
Member Function Documentation
void ShapeBaseConvex::findNodeTransform ()
Referenced by ShapeBaseConvex().
Box3F ShapeBaseConvex::getBoundingBox () const virtual
Returns the bounding box for the object this is built around in world space.
Reimplemented from Convex.
Referenced by ShapeBaseConvex().
Box3F ShapeBaseConvex::getBoundingBox (const MatrixF & mat, const Point3F & scale) const virtual
Returns the object space bounding box for the object this is built around transformed and scaled.
Parameters
mat Matrix to transform the object-space box by
scale Scaling factor to scale the bounding box by
Reimplemented from Convex.
void ShapeBaseConvex::getFeatures (const MatrixF & mat, const VectorF & n, ConvexFeature * cf) virtual
This is used by the GJK collision in Vehicle.
The Convex class should add verts, edges, and faces to the passed ConvexFeature that face towards the passed normal vector. Verts added in this way should also be transformed by the passed matrix.
Parameters
mat Transform which should be applied to verts added to the ConvexFeature
n Normal vector
cf ConvexFeature to add data to.
Reimplemented from Convex.
Referenced by ShapeBaseConvex().
void ShapeBaseConvex::getPolyList (AbstractPolyList * list) virtual
Builds a collision poly list out of this convex.
Parameters
list (Out) Poly list built
Reimplemented from Convex.
Referenced by ShapeBaseConvex().
const MatrixF& ShapeBaseConvex::getTransform () const virtual
Returns the transform of the object this is built around.
Reimplemented from Convex.
Referenced by ShapeBaseConvex().
Point3F ShapeBaseConvex::support (const VectorF & v) const virtual
Returns the farthest point, along a vector, still bound by the convex.
Parameters
v Vector
Reimplemented from Convex.
Referenced by ShapeBaseConvex().
Member Data Documentation
Box3F ShapeBaseConvex::box
Referenced by ShapeBase::calcClassRenderData(), and ShapeBaseConvex().
U32 ShapeBaseConvex::hullId
Referenced by ShapeBaseConvex().
MatrixF* ShapeBaseConvex::nodeTransform protected
Referenced by ShapeBaseConvex().
ShapeBase* ShapeBaseConvex::pShapeBase protected
Referenced by ShapeBaseConvex().
MatrixF* ShapeBaseConvex::transform
Copyright © GarageGames, LLC. All Rights Reserved.