PlatformWindowManager Class Reference
Main Modules Class List Namespace List Online
PlatformWindowManager Class Reference abstract
Abstract representation of a manager for native OS windows.
#include <windowManager/platformWindowMgr.h>
Public Member Functions
PlatformWindowManager ()
virtual ~PlatformWindowManager ()
virtual void buildMonitorsList ()
virtual PlatformWindow * createWindow (GFXDevice *device, const GFXVideoMode &mode)=0
Create a new window, appropriate for the specified device and mode.
virtual S32 findFirstMatchingMonitor (const char *name)
virtual S32 getDesktopBitDepth ()=0
Retrieve the currently set desktop bit depth.
virtual Point2I getDesktopResolution ()=0
Retrieve the currently set desktop resolution.
virtual PlatformWindow * getFirstWindow ()=0
Get the first window in the window list.
virtual PlatformWindow * getFocusedWindow ()=0
Get the window that currently has the input focus or NULL.
virtual U32 getMonitorCount ()
virtual const char * getMonitorName (U32 index)
virtual RectI getMonitorRect (U32 index)
virtual void getMonitorRegions (Vector< RectI > &regions)=0
Populate a vector with all monitors and their extents in window space.
virtual void * getParentWindow ()=0
Get the parent window.
virtual RectI getPrimaryDesktopArea ()=0
Return the extents in window coordinates of the primary desktop area.
virtual PlatformWindow * getWindowById (WindowId id)=0
Get a window from a device ID.
virtual void getWindows (VectorPtr< PlatformWindow * > &windows)=0
Populate a list with references to all the windows created from this manager.
virtual void lowerCurtain ()=0
This method cues the appearance of that window ("lowering the curtain").
virtual void raiseCurtain ()=0
virtual void setDisplayWindow (bool set)
This method indicates to created windows to show as normal.
virtual void setParentWindow (void *newParent)=0
Set the parent window.
Static Public Member Functions
static PlatformWindowManager * get ()
Get Global Singleton.
static void processCmdLineArgs (const S32 argc, const char **argv)
Protected Member Functions
S32 getNextId ()
Get the next available window Id.
Detailed Description
Abstract representation of a manager for native OS windows.
The PlatformWindowManager interface provides a variety of methods for querying the current desktop configuration, as well as allocating and retrieving existing windows. It may also manage application-level event handling.
Constructor & Destructor Documentation
PlatformWindowManager::PlatformWindowManager () inline
virtual PlatformWindowManager::~PlatformWindowManager () inline virtual
References getDesktopBitDepth(), getDesktopResolution(), getPrimaryDesktopArea(), and processCmdLineArgs().
Member Function Documentation
virtual void PlatformWindowManager::buildMonitorsList () inline virtual
Reimplemented in PlatformWindowManagerSDL, and Win32WindowManager.
virtual PlatformWindow* PlatformWindowManager::createWindow (GFXDevice * device, const GFXVideoMode & mode) pure virtual
Create a new window, appropriate for the specified device and mode.
Returns
Pointer to the new window.
Implemented in PlatformWindowManagerSDL, Win32WindowManager, and MacWindowManager.
Referenced by getMonitorRect().
virtual S32 PlatformWindowManager::findFirstMatchingMonitor (const char * name) inline virtual
Reimplemented in PlatformWindowManagerSDL, and Win32WindowManager.
static PlatformWindowManager* PlatformWindowManager::get () static
Get Global Singleton.
virtual S32 PlatformWindowManager::getDesktopBitDepth () pure virtual
Retrieve the currently set desktop bit depth.
Returns
The current desktop bit depth, or -1 if an error occurred
Implemented in PlatformWindowManagerSDL, Win32WindowManager, and MacWindowManager.
Referenced by ~PlatformWindowManager().
virtual Point2I PlatformWindowManager::getDesktopResolution () pure virtual
Retrieve the currently set desktop resolution.
Returns
The current desktop bit depth, or Point2I(-1,-1) if an error occurred
Implemented in PlatformWindowManagerSDL, Win32WindowManager, and MacWindowManager.
Referenced by ~PlatformWindowManager().
virtual PlatformWindow* PlatformWindowManager::getFirstWindow () pure virtual
Get the first window in the window list.
Returns
The first window in the list, or NULL if no windows found
Implemented in PlatformWindowManagerSDL, Win32WindowManager, and MacWindowManager.
Referenced by getMonitorRect().
virtual PlatformWindow* PlatformWindowManager::getFocusedWindow () pure virtual
Get the window that currently has the input focus or NULL.
Implemented in PlatformWindowManagerSDL, Win32WindowManager, and MacWindowManager.
Referenced by getMonitorRect().
virtual U32 PlatformWindowManager::getMonitorCount () inline virtual
Reimplemented in PlatformWindowManagerSDL, and Win32WindowManager.
virtual const char* PlatformWindowManager::getMonitorName (U32 index) inline virtual
Reimplemented in PlatformWindowManagerSDL, and Win32WindowManager.
virtual RectI PlatformWindowManager::getMonitorRect (U32 index) inline virtual
Reimplemented in PlatformWindowManagerSDL, and Win32WindowManager.
References createWindow(), getFirstWindow(), getFocusedWindow(), getMonitorRegions(), getParentWindow(), getWindowById(), getWindows(), lowerCurtain(), raiseCurtain(), and setParentWindow().
virtual void PlatformWindowManager::getMonitorRegions (Vector< RectI > & regions) pure virtual
Populate a vector with all monitors and their extents in window space.
Implemented in PlatformWindowManagerSDL, Win32WindowManager, and MacWindowManager.
Referenced by getMonitorRect().
S32 PlatformWindowManager::getNextId () inline protected
Get the next available window Id.
virtual void* PlatformWindowManager::getParentWindow () pure virtual
Get the parent window.
Implemented in PlatformWindowManagerSDL, Win32WindowManager, and MacWindowManager.
Referenced by getMonitorRect().
virtual RectI PlatformWindowManager::getPrimaryDesktopArea () pure virtual
Return the extents in window coordinates of the primary desktop area.
On a single monitor system this is just the display extents. On a multimon system this is the primary monitor (which Torque should launch on).
Implemented in PlatformWindowManagerSDL, Win32WindowManager, and MacWindowManager.
Referenced by ~PlatformWindowManager().
virtual PlatformWindow* PlatformWindowManager::getWindowById (WindowId id) pure virtual
Get a window from a device ID.
Returns
The window associated with the specified ID, or NULL if no match was found.
Implemented in PlatformWindowManagerSDL, Win32WindowManager, and MacWindowManager.
Referenced by getMonitorRect().
virtual void PlatformWindowManager::getWindows (VectorPtr< PlatformWindow * > & windows) pure virtual
Populate a list with references to all the windows created from this manager.
Implemented in PlatformWindowManagerSDL, Win32WindowManager, and MacWindowManager.
Referenced by getMonitorRect().
virtual void PlatformWindowManager::lowerCurtain () pure virtual
This method cues the appearance of that window ("lowering the curtain").
Implemented in PlatformWindowManagerSDL, Win32WindowManager, and MacWindowManager.
Referenced by getMonitorRect().
static void PlatformWindowManager::processCmdLineArgs (const S32 argc, const char ** argv) static
Referenced by ~PlatformWindowManager().
virtual void PlatformWindowManager::raiseCurtain () pure virtual
See also
lowerCurtain
This method removes the curtain window.
Implemented in PlatformWindowManagerSDL, Win32WindowManager, and MacWindowManager.
Referenced by getMonitorRect().
virtual void PlatformWindowManager::setDisplayWindow (bool set) inline virtual
This method indicates to created windows to show as normal.
Reimplemented in PlatformWindowManagerSDL, and Win32WindowManager.
virtual void PlatformWindowManager::setParentWindow (void * newParent) pure virtual
Set the parent window.
This can be used to render in a child window.
Implemented in PlatformWindowManagerSDL, Win32WindowManager, and MacWindowManager.
Referenced by getMonitorRect().
Copyright © GarageGames, LLC. All Rights Reserved.