_SourceReader Class Reference
Main Modules Class List Namespace List Online
_SourceReader Class Reference
#include <ts/collada/colladaUtils.h>
Public Member Functions
_SourceReader ()
ColorI getColorIValue (S32 index) const
F32 getFloatValue (S32 index) const
MatrixF getMatrixFValue (S32 index) const
Point2F getPoint2FValue (S32 index) const
Point3F getPoint3FValue (S32 index) const
const double * getStringArrayData (S32 index) const
const char * getStringValue (S32 index) const
bool initFromSource (const domSource *src, const char *paramNames[]=0)
void reset ()
S32 size () const
S32 stride () const
Constructor & Destructor Documentation
_SourceReader::_SourceReader () inline
Member Function Documentation
ColorI _SourceReader::getColorIValue (S32 index) const inline
References ColorI::alpha, ColorI::blue, ColorI::green, and ColorI::red.
F32 _SourceReader::getFloatValue (S32 index) const inline
MatrixF _SourceReader::getMatrixFValue (S32 index) const inline
Point2F _SourceReader::getPoint2FValue (S32 index) const inline
References Point2F::set().
Point3F _SourceReader::getPoint3FValue (S32 index) const inline
References Point3F::set().
const double* _SourceReader::getStringArrayData (S32 index) const inline
const char* _SourceReader::getStringValue (S32 index) const inline
bool _SourceReader::initFromSource (const domSource * src, const char * paramNames[] = 0) inline
References Vector< T >::clear(), Vector< T >::last(), Vector< T >::push_back(), and Vector< T >::size().
void _SourceReader::reset (void) inline
References Vector< T >::clear().
S32 _SourceReader::size () const inline
S32 _SourceReader::stride () const inline
Copyright © GarageGames, LLC. All Rights Reserved.