TSLastDetail Class Reference
Main Modules Class List Namespace List Online
TSLastDetail Class Reference
This neat little class renders the object to a texture so that when the object is far away, it can be drawn as a billboard instead of a mesh.
#include <ts/tsLastDetail.h>
Public Member Functions
TSLastDetail (TSShape *shape, const String &cachePath, U32 numEquatorSteps, U32 numPolarSteps, F32 polarAngle, bool includePoles, S32 dl, S32 dim)
~TSLastDetail ()
void deleteImposterCacheTextures ()
Helper function which deletes the cached imposter texture files from disk.
BaseMatInstance * getMatInstance () const
Returns the material instance used to render this imposter.
F32 getRadius () const
Returns the radius.
void render (const TSRenderState &rdata, F32 alpha)
Internal function called from TSShapeInstance to submit an imposter render instance.
void update (bool forceUpdate=false)
Loads the imposter images by reading them from the disk or generating them if the TSShape is more recient than the cached imposter textures.
Static Public Member Functions
static void updateImposterImages (bool forceUpdate=false)
Calls update on all TSLastDetail objects in the system.
Static Public Attributes
static bool smCanShadow
Global preference for rendering imposters to shadows.
Protected Member Functions
String _getDiffuseMapPath () const
Helper which returns the imposter diffuse map path.
String _getNormalMapPath () const
Helper which returns the imposter normal map path.
void _update ()
This update actually regenerates the imposter images.
void _validateDim ()
Protected Attributes
String mCachePath
This is the path of the object, which is where we'll be storing our cache for rendered imposters.
Point3F mCenter
The center offset for the bounding sphere used to render the imposter.
S32 mDim
The square dimensions of each captured imposter image.
S32 mDl
The shape detail level to capture into the imposters.
GFXVertexFormat mImposterVertDecl
The combined imposter state and corner data vertex format used for rendering with multiple streams.
bool mIncludePoles
If true we captures polar images in the imposter texture.
SimObjectPtr< Material > mMaterial
The material for this imposter.
BaseMatInstance * mMatInstance
The material instance used to render this imposter.
U32 mNumEquatorSteps
The number steps around the equator of the globe at which we capture an imposter.
U32 mNumPolarSteps
The number of steps to go from equator to each polar region (0 means equator only) at which we capture an imposter.
F32 mPolarAngle
The angle in radians of sub-polar regions.
F32 mRadius
The bounding radius of the shape used to size the billboard.
TSShape * mShape
The shape which we're impostering.
Static Protected Attributes
static Vector< TSLastDetail * > smLastDetails
This is a global list of all the TSLastDetail objects in the system.
static const U32 smMaxTexSize = 2048
The maximum texture size for a billboard texture.
Detailed Description
This neat little class renders the object to a texture so that when the object is far away, it can be drawn as a billboard instead of a mesh.
This happens when the model is first loaded as to keep the realtime render as fast as possible. It also renders the model from a few different perspectives so that it would actually pass as a model instead of a silly old billboard. In other words, this is an imposter.
Constructor & Destructor Documentation
TSLastDetail::TSLastDetail (TSShape * shape, const String & cachePath, U32 numEquatorSteps, U32 numPolarSteps, F32 polarAngle, bool includePoles, S32 dl, S32 dim)
Referenced by _getNormalMapPath().
TSLastDetail::~TSLastDetail ()
Referenced by _getNormalMapPath().
Member Function Documentation
String TSLastDetail::_getDiffuseMapPath () const inline protected
Helper which returns the imposter diffuse map path.
String TSLastDetail::_getNormalMapPath () const inline protected
Helper which returns the imposter normal map path.
References TSLastDetail(), and ~TSLastDetail().
void TSLastDetail::_update () protected
This update actually regenerates the imposter images.
void TSLastDetail::_validateDim () protected
void TSLastDetail::deleteImposterCacheTextures ()
Helper function which deletes the cached imposter texture files from disk.
Referenced by getMatInstance().
BaseMatInstance* TSLastDetail::getMatInstance () const inline
Returns the material instance used to render this imposter.
References deleteImposterCacheTextures(), and mMatInstance.
F32 TSLastDetail::getRadius () const inline
Returns the radius.
See also
mRadius
References mRadius.
void TSLastDetail::render (const TSRenderState & rdata, F32 alpha)
Internal function called from TSShapeInstance to submit an imposter render instance.
void TSLastDetail::update (bool forceUpdate = false)
Loads the imposter images by reading them from the disk or generating them if the TSShape is more recient than the cached imposter textures.
This should not be called from within any rendering code.
Parameters
forceUpdate If true the disk cache is invalidated and new imposter images are rendered.
static void TSLastDetail::updateImposterImages (bool forceUpdate = false) static
Calls update on all TSLastDetail objects in the system.
See also
update()
Member Data Documentation
String TSLastDetail::mCachePath protected
This is the path of the object, which is where we'll be storing our cache for rendered imposters.
Point3F TSLastDetail::mCenter protected
The center offset for the bounding sphere used to render the imposter.
S32 TSLastDetail::mDim protected
The square dimensions of each captured imposter image.
S32 TSLastDetail::mDl protected
The shape detail level to capture into the imposters.
GFXVertexFormat TSLastDetail::mImposterVertDecl protected
The combined imposter state and corner data vertex format used for rendering with multiple streams.
bool TSLastDetail::mIncludePoles protected
If true we captures polar images in the imposter texture.
SimObjectPtr<Material> TSLastDetail::mMaterial protected
The material for this imposter.
BaseMatInstance* TSLastDetail::mMatInstance protected
The material instance used to render this imposter.
Referenced by getMatInstance().
U32 TSLastDetail::mNumEquatorSteps protected
The number steps around the equator of the globe at which we capture an imposter.
U32 TSLastDetail::mNumPolarSteps protected
The number of steps to go from equator to each polar region (0 means equator only) at which we capture an imposter.
F32 TSLastDetail::mPolarAngle protected
The angle in radians of sub-polar regions.
F32 TSLastDetail::mRadius protected
The bounding radius of the shape used to size the billboard.
Referenced by getRadius().
TSShape* TSLastDetail::mShape protected
The shape which we're impostering.
bool TSLastDetail::smCanShadow static
Global preference for rendering imposters to shadows.
Vector<TSLastDetail*> TSLastDetail::smLastDetails static protected
This is a global list of all the TSLastDetail objects in the system.
const U32 TSLastDetail::smMaxTexSize = 2048 static protected
The maximum texture size for a billboard texture.
Copyright © GarageGames, LLC. All Rights Reserved.