Journal Class Reference
Main Modules Class List Namespace List Online
Journal Class Reference
Journaling System.
#include <core/util/journal/journal.h>
Public Member Functions
template<class Func , class A , class B , class C , class D , class E , class F , class G , class H , class I , class J , class K , class L , class M >
Method (Func,(Func func, A a, B b, C c, D d, E e, F f, G g, H h, I i, J j, K k, L l, M m),(a, b, c, d, e, f, g, h, i, j, k, l, m)) template< class Func
class B class C class D class E class F class G class H class I class J class K class L Method (Func,(Func func, A a, B b, C c, D d, E e, F f, G g, H h, I i, J j, K k, L l),(a, b, c, d, e, f, g, h, i, j, k, l)) template< class Func
class B class C class D class E class F class G class H class I class J Method (Func,(Func func, A a, B b, C c, D d, E e, F f, G g, H h, I i, J j),(a, b, c, d, e, f, g, h, i, j)) template< class Func
class B class C class D class E class F Method (Func,(Func func, A a, B b, C c, D d, E e, F f),(a, b, c, d, e, f)) template< class Func
class B class C class D class E Method (Func,(Func func, A a, B b, C c, D d, E e),(a, b, c, d, e)) template< class Func
class B class C class D class E class F class G class H class I Method (Func,(Func func, A a, B b, C c, D d, E e, F f, G g, H h, I i),(a, b, c, d, e, f, g, h, i)) template< class Func
class B class C class D Method (Func,(Func func, A a, B b, C c, D d),(a, b, c, d)) template< class Func
class B class C Method (Func,(Func func, A a, B b, C c),(a, b, c)) template< class Func
class B class C class D class E class F class G class H class I class J class K Method (Func,(Func func, A a, B b, C c, D d, E e, F f, G g, H h, I i, J j, K k),(a, b, c, d, e, f, g, h, i, j, k)) template< class Func
class B class C class D class E class F class G class H Method (Func,(Func func, A a, B b, C c, D d, E e, F f, G g, H h),(a, b, c, d, e, f, g, h)) template< class Func
class B Method (Func,(Func func, A a, B b),(a, b)) template< class Func
class B class A Method (Func,(Func func, A a),(a)) template< class Func > Method(Func
class B class C class D class E class F class G Method (Func,(Func func, A a, B b, C c, D d, E e, F f, G g),(a, b, c, d, e, f, g)) template< class Func
class B class C class D class E class F class G class H class I class J class K Method ((Func func, A a, B b, C c, D d, E e, F f, G g, H h, I i, J j, K k),(mFile, id, a, b, c, d, e, f, g, h, i, j, k),(a, b, c, d, e, f, g, h, i, j, k)) template< class Func
class B class C class D class E class F class G class H class I class J Method ((Func func, A a, B b, C c, D d, E e, F f, G g, H h, I i, J j),(mFile, id, a, b, c, d, e, f, g, h, i, j),(a, b, c, d, e, f, g, h, i, j)) template< class Func
class B class C class D class E class F class G class H class I Method ((Func func, A a, B b, C c, D d, E e, F f, G g, H h, I i),(mFile, id, a, b, c, d, e, f, g, h, i),(a, b, c, d, e, f, g, h, i)) template< class Func
class B class C class D class E class F class G class H Method ((Func func, A a, B b, C c, D d, E e, F f, G g, H h),(mFile, id, a, b, c, d, e, f, g, h),(a, b, c, d, e, f, g, h)) template< class Func
class B class C class D class E class F class G Method ((Func func, A a, B b, C c, D d, E e, F f, G g),(mFile, id, a, b, c, d, e, f, g),(a, b, c, d, e, f, g)) template< class Func
class B class C class D class E class F Method ((Func func, A a, B b, C c, D d, E e, F f),(mFile, id, a, b, c, d, e, f),(a, b, c, d, e, f)) template< class Func
class B class C class D class E Method ((Func func, A a, B b, C c, D d, E e),(mFile, id, a, b, c, d, e),(a, b, c, d, e)) template< class Func
class B class C class D Method ((Func func, A a, B b, C c, D d),(mFile, id, a, b, c, d),(a, b, c, d)) template< class Func
class B class C Method ((Func func, A a, B b, C c),(mFile, id, a, b, c),(a, b, c)) template< class Func
class B Method ((Func func, A a, B b),(mFile, id, a, b),(a, b)) template< class Func
class B class A Method ((Func func, A a),(mFile, id, a),(a)) template< class Func > Method((Func func)
template<class Func , class A , class B , class C , class D , class E , class F , class G , class H , class I , class J , class K , class L , class M >
Method ((Func func, A a, B b, C c, D d, E e, F f, G g, H h, I i, J j, K k, L l, M m),(mFile, id, a, b, c, d, e, f, g, h, i, j, k, l, m),(a, b, c, d, e, f, g, h, i, j, k, l, m)) template< class Func
class B class C class D class E class F class G class H class I class J class K class L Method ((Func func, A a, B b, C c, D d, E e, F f, G g, H h, I i, J j, K k, L l),(mFile, id, a, b, c, d, e, f, g, h, i, j, k, l),(a, b, c, d, e, f, g, h, i, j, k, l)) template< class Func
class B class C class D class E class F class G class H Method ((Obj *obj, void(Obj::*method)(A, B, C, D, E, F, G, H), A a, B b, C c, D d, E e, F f, G g, H h),(mFile, id, a, b, c, d, e, f, g, h),(a, b, c, d, e, f, g, h)) template< class Obj
class B class A Method ((Obj *obj, void(Obj::*method)(A), A a),(mFile, id, a),(a)) template< class Obj > Method((Obj *obj
class B class C class D class E class F class G Method ((Obj *obj, void(Obj::*method)(A, B, C, D, E, F, G), A a, B b, C c, D d, E e, F f, G g),(mFile, id, a, b, c, d, e, f, g),(a, b, c, d, e, f, g)) template< class Obj
class B class C class D class E class F Method ((Obj *obj, void(Obj::*method)(A, B, C, D, E, F), A a, B b, C c, D d, E e, F f),(mFile, id, a, b, c, d, e, f),(a, b, c, d, e, f)) template< class Obj
class B class C class D class E Method ((Obj *obj, void(Obj::*method)(A, B, C, D, E), A a, B b, C c, D d, E e),(mFile, id, a, b, c, d, e),(a, b, c, d, e)) template< class Obj
class B class C class D Method ((Obj *obj, void(Obj::*method)(A, B, C, D), A a, B b, C c, D d),(mFile, id, a, b, c, d),(a, b, c, d)) template< class Obj
class B class C Method ((Obj *obj, void(Obj::*method)(A, B, C), A a, B b, C c),(mFile, id, a, b, c),(a, b, c)) template< class Obj
class B Method ((Obj *obj, void(Obj::*method)(A, B), A a, B b),(mFile, id, a, b),(a, b)) template< class Obj
template<class Obj , class A , class B , class C , class D , class E , class F , class G , class H , class I , class J , class K , class L , class M >
Method ((Obj *obj, void(Obj::*method)(A, B, C, D, E, F, G, H, I, J, K, L, M), A a, B b, C c, D d, E e, F f, G g, H h, I i, J j, K k, L l, M m),(mFile, id, a, b, c, d, e, f, g, h, i, j, k, l, m),(a, b, c, d, e, f, g, h, i, j, k, l, m)) template< class Obj
class B class C class D class E class F class G class H class I Method ((Obj *obj, void(Obj::*method)(A, B, C, D, E, F, G, H, I), A a, B b, C c, D d, E e, F f, G g, H h, I i),(mFile, id, a, b, c, d, e, f, g, h, i),(a, b, c, d, e, f, g, h, i)) template< class Obj
class B class C class D class E class F class G class H class I class J class K class L Method ((Obj *obj, void(Obj::*method)(A, B, C, D, E, F, G, H, I, J, K, L), A a, B b, C c, D d, E e, F f, G g, H h, I i, J j, K k, L l),(mFile, id, a, b, c, d, e, f, g, h, i, j, k, l),(a, b, c, d, e, f, g, h, i, j, k, l)) template< class Obj
class B class C class D class E class F class G class H class I class J class K Method ((Obj *obj, void(Obj::*method)(A, B, C, D, E, F, G, H, I, J, K), A a, B b, C c, D d, E e, F f, G g, H h, I i, J j, K k),(mFile, id, a, b, c, d, e, f, g, h, i, j, k),(a, b, c, d, e, f, g, h, i, j, k)) template< class Obj
class B class C class D class E class F class G class H class I class J Method ((Obj *obj, void(Obj::*method)(A, B, C, D, E, F, G, H, I, J), A a, B b, C c, D d, E e, F f, G g, H h, I i, J j),(mFile, id, a, b, c, d, e, f, g, h, i, j),(a, b, c, d, e, f, g, h, i, j)) template< class Obj
template<class A , class B , class C , class D , class E , class F , class G , class H , class I , class J , class K , class L , class M >
Method ((A &a, B &b, C &c, D &d, E &e, F &f, G &g, H &h, I &i, J &j, K &k, L &l, M &m),(mFile, a, b, c, d, e, f, g, h, i, j, k, l, m))
template<class A , class B , class C , class D , class E , class F , class G , class H , class I , class J , class K , class L >
Method ((A &a, B &b, C &c, D &d, E &e, F &f, G &g, H &h, I &i, J &j, K &k, L &l),(mFile, a, b, c, d, e, f, g, h, i, j, k, l))
template<class A , class B , class C , class D , class E , class F , class G , class H , class I , class J , class K >
Method ((A &a, B &b, C &c, D &d, E &e, F &f, G &g, H &h, I &i, J &j, K &k),(mFile, a, b, c, d, e, f, g, h, i, j, k))
template<class A , class B , class C , class D , class E , class F , class G , class H , class I , class J >
Method ((A &a, B &b, C &c, D &d, E &e, F &f, G &g, H &h, I &i, J &j),(mFile, a, b, c, d, e, f, g, h, i, j))
template<class A , class B , class C , class D , class E , class F , class G , class H , class I >
Method ((A &a, B &b, C &c, D &d, E &e, F &f, G &g, H &h, I &i),(mFile, a, b, c, d, e, f, g, h, i))
template<class A , class B , class C , class D , class E , class F , class G , class H >
Method ((A &a, B &b, C &c, D &d, E &e, F &f, G &g, H &h),(mFile, a, b, c, d, e, f, g, h))
template<class A , class B , class C , class D , class E , class F , class G >
Method ((A &a, B &b, C &c, D &d, E &e, F &f, G &g),(mFile, a, b, c, d, e, f, g))
template<class A , class B , class C , class D , class E , class F >
Method ((A &a, B &b, C &c, D &d, E &e, F &f),(mFile, a, b, c, d, e, f))
template<class A , class B , class C , class D , class E >
Method ((A &a, B &b, C &c, D &d, E &e),(mFile, a, b, c, d, e))
template<class A , class B , class C , class D >
Method ((A &a, B &b, C &c, D &d),(mFile, a, b, c, d))
template<class A , class B , class C >
Method ((A &a, B &b, C &c),(mFile, a, b, c))
template<class A , class B >
Method ((A &a, B &b),(mFile, a, b))
template<class A >
Method ((A &a),(mFile, a))
template<class A , class B , class C , class D , class E , class F , class G , class H , class I , class J , class K , class L , class M >
Method ((A &a, B &b, C &c, D &d, E &e, F &f, G &g, H &h, I &i, J &j, K &k, L &l, M &m),(mFile, a, b, c, d, e, f, g, h, i, j, k, l, m))
template<class A , class B , class C , class D , class E , class F , class G , class H , class I , class J , class K , class L >
Method ((A &a, B &b, C &c, D &d, E &e, F &f, G &g, H &h, I &i, J &j, K &k, L &l),(mFile, a, b, c, d, e, f, g, h, i, j, k, l))
template<class A , class B , class C , class D , class E , class F , class G , class H , class I , class J , class K >
Method ((A &a, B &b, C &c, D &d, E &e, F &f, G &g, H &h, I &i, J &j, K &k),(mFile, a, b, c, d, e, f, g, h, i, j, k))
template<class A , class B , class C , class D , class E , class F , class G , class H , class I , class J >
Method ((A &a, B &b, C &c, D &d, E &e, F &f, G &g, H &h, I &i, J &j),(mFile, a, b, c, d, e, f, g, h, i, j))
template<class A , class B , class C , class D , class E , class F , class G , class H , class I >
Method ((A &a, B &b, C &c, D &d, E &e, F &f, G &g, H &h, I &i),(mFile, a, b, c, d, e, f, g, h, i))
template<class A , class B , class C , class D , class E , class F , class G , class H >
Method ((A &a, B &b, C &c, D &d, E &e, F &f, G &g, H &h),(mFile, a, b, c, d, e, f, g, h))
template<class A , class B , class C , class D , class E , class F , class G >
Method ((A &a, B &b, C &c, D &d, E &e, F &f, G &g),(mFile, a, b, c, d, e, f, g))
template<class A , class B , class C , class D , class E , class F >
Method ((A &a, B &b, C &c, D &d, E &e, F &f),(mFile, a, b, c, d, e, f))
template<class A , class B , class C , class D , class E >
Method ((A &a, B &b, C &c, D &d, E &e),(mFile, a, b, c, d, e))
template<class A , class B , class C , class D >
Method ((A &a, B &b, C &c, D &d),(mFile, a, b, c, d))
template<class A , class B , class C >
Method ((A &a, B &b, C &c),(mFile, a, b, c))
template<class A , class B >
Method ((A &a, B &b),(mFile, a, b))
template<class A >
Method ((A &a),(mFile, a))
Static Public Member Functions
template<typename T >
static void DeclareFunction (T func)
Register a function with the journalling system.
template<typename T , typename U >
static void DeclareFunction (T obj, U method)
static void Disable ()
static bool IsDispatching ()
Returns true if a function is being dispatched.
static bool IsPlaying ()
Returns true if in play mode.
static bool IsRecording ()
Returns true if in recording mode.
static void Play (const char *file)
static bool PlayNext ()
template<typename T >
static void Read (T *v)
static bool Read (U32 size, void *buffer)
static void ReadString (char str[256])
static void Record (const char *file)
template<typename T , typename U >
static void RemoveFunction (T obj, U method)
static void Stop ()
template<typename T >
static void Write (const T &v)
static bool Write (U32 size, void *buffer)
static void WriteString (const char str[256])
Public Attributes
class B class A Func func
class B class A id
class B class A void(Obj::* id)
class B class A void(Obj::* method)())
class B class A mFile
class B class A void(Obj::* mFile)
Detailed Description
Journaling System.
The journaling system is used to record external events and non-deterministic values from an execution run in order that the run may be re-played for debugging purposes. The journaling system is integrated into the platform library, though not all platform calls are journaled.
File system calls are not journaled, so any modified files must be reset to their original state before playback. Only a single journal can be recored or played back at a time.
For the journals to play back correctly, journal events cannot be triggered during the processing of another event.
Member Function Documentation
template<typename T > static void Journal::DeclareFunction (T func) inline static
Register a function with the journalling system.
References func.
Referenced by JournaledSignal< void()>::JournaledSignal(), JournaledSignal< void(A)>::JournaledSignal(), JournaledSignal< void(A, B)>::JournaledSignal(), JournaledSignal< void(A, B, C)>::JournaledSignal(), JournaledSignal< void(A, B, C, D)>::JournaledSignal(), JournaledSignal< void(A, B, C, D, E)>::JournaledSignal(), JournaledSignal< void(A, B, C, D, E, F)>::JournaledSignal(), JournaledSignal< void(A, B, C, D, E, F, G)>::JournaledSignal(), JournaledSignal< void(A, B, C, D, E, F, G, H)>::JournaledSignal(), JournaledSignal< void(A, B, C, D, E, F, G, H, I, J, K)>::JournaledSignal(), JournaledSignal< void(A, B, C, D, E, F, G, H, I, J, K, L)>::JournaledSignal(), and JournaledSignal< void(A, B, C, D, E, F, G, H, I, J, K, L, M)>::JournaledSignal().
template<typename T , typename U > static void Journal::DeclareFunction (T obj, U method) inline static
References method.
static void Journal::Disable () static
static bool Journal::IsDispatching () inline static
Returns true if a function is being dispatched.
static bool Journal::IsPlaying () inline static
Returns true if in play mode.
Referenced by Read(), and ReadString().
static bool Journal::IsRecording () inline static
Returns true if in recording mode.
Referenced by Write(), and WriteString().
template<class Func , class A , class B , class C , class D , class E , class F , class G , class H , class I , class J , class K , class L , class M > Journal::Method (Func , (Func func, A a, B b, C c, D d, E e, F f, G g, H h, I i, J j, K k, L l, M m) , (a, b, c, d, e, f, g, h, i, j, k, l, m))
Referenced by RemoveFunction().
class B class C class D class E class F class G class H class I class J class K class L Journal::Method (Func , (Func func, A a, B b, C c, D d, E e, F f, G g, H h, I i, J j, K k, L l) , (a, b, c, d, e, f, g, h, i, j, k, l))
class B class C class D class E class F class G class H class I class J class K Journal::Method (Func , (Func func, A a, B b, C c, D d, E e, F f, G g, H h, I i, J j, K k) , (a, b, c, d, e, f, g, h, i, j, k))
class B class C class D class E class F class G class H class I class J Journal::Method (Func , (Func func, A a, B b, C c, D d, E e, F f, G g, H h, I i, J j) , (a, b, c, d, e, f, g, h, i, j))
class B class C class D class E class F class G class H class I Journal::Method (Func , (Func func, A a, B b, C c, D d, E e, F f, G g, H h, I i) , (a, b, c, d, e, f, g, h, i))
class B class C class D class E class F class G class H Journal::Method (Func , (Func func, A a, B b, C c, D d, E e, F f, G g, H h) , (a, b, c, d, e, f, g, h))
class B class C class D class E class F class G Journal::Method (Func , (Func func, A a, B b, C c, D d, E e, F f, G g) , (a, b, c, d, e, f, g))
class B class C class D class E class F Journal::Method (Func , (Func func, A a, B b, C c, D d, E e, F f) , (a, b, c, d, e, f))
class B class C class D class E Journal::Method (Func , (Func func, A a, B b, C c, D d, E e) , (a, b, c, d, e))
class B class C class D Journal::Method (Func , (Func func, A a, B b, C c, D d) , (a, b, c, d))
class B class C Journal::Method (Func , (Func func, A a, B b, C c) , (a, b, c))
class B Journal::Method (Func , (Func func, A a, B b) , (a, b))
class B class A Journal::Method (Func , (Func func, A a) , (a))
class B class C class D class E class F class G class H class I class J class K class L Journal::Method ((Func func, A a, B b, C c, D d, E e, F f, G g, H h, I i, J j, K k, L l) , (mFile, id, a, b, c, d, e, f, g, h, i, j, k, l) , (a, b, c, d, e, f, g, h, i, j, k, l))
class B class C class D class E class F class G class H class I class J class K Journal::Method ((Func func, A a, B b, C c, D d, E e, F f, G g, H h, I i, J j, K k) , (mFile, id, a, b, c, d, e, f, g, h, i, j, k) , (a, b, c, d, e, f, g, h, i, j, k))
class B class C class D class E class F class G class H class I class J Journal::Method ((Func func, A a, B b, C c, D d, E e, F f, G g, H h, I i, J j) , (mFile, id, a, b, c, d, e, f, g, h, i, j) , (a, b, c, d, e, f, g, h, i, j))
class B class C class D class E class F class G class H class I Journal::Method ((Func func, A a, B b, C c, D d, E e, F f, G g, H h, I i) , (mFile, id, a, b, c, d, e, f, g, h, i) , (a, b, c, d, e, f, g, h, i))
class B class C class D class E class F class G class H Journal::Method ((Func func, A a, B b, C c, D d, E e, F f, G g, H h) , (mFile, id, a, b, c, d, e, f, g, h) , (a, b, c, d, e, f, g, h))
class B class C class D class E class F class G Journal::Method ((Func func, A a, B b, C c, D d, E e, F f, G g) , (mFile, id, a, b, c, d, e, f, g) , (a, b, c, d, e, f, g))
class B class C class D class E class F Journal::Method ((Func func, A a, B b, C c, D d, E e, F f) , (mFile, id, a, b, c, d, e, f) , (a, b, c, d, e, f))
class B class C class D class E Journal::Method ((Func func, A a, B b, C c, D d, E e) , (mFile, id, a, b, c, d, e) , (a, b, c, d, e))
class B class C class D Journal::Method ((Func func, A a, B b, C c, D d) , (mFile, id, a, b, c, d) , (a, b, c, d))
class B class C Journal::Method ((Func func, A a, B b, C c) , (mFile, id, a, b, c) , (a, b, c))
class B Journal::Method ((Func func, A a, B b) , (mFile, id, a, b) , (a, b))
class B class A Journal::Method ((Func func, A a) , (mFile, id, a) , (a))
template<class Func , class A , class B , class C , class D , class E , class F , class G , class H , class I , class J , class K , class L , class M > Journal::Method ((Func func, A a, B b, C c, D d, E e, F f, G g, H h, I i, J j, K k, L l, M m) , (mFile, id, a, b, c, d, e, f, g, h, i, j, k, l, m) , (a, b, c, d, e, f, g, h, i, j, k, l, m))
class B Journal::Method ((Obj *obj, void(Obj::*)(A, B) method, A a, B b)
template<class Obj , class A , class B , class C , class D , class E , class F , class G , class H , class I , class J , class K , class L , class M > Journal::Method ((Obj *obj, void(Obj::*)(A, B, C, D, E, F, G, H, I, J, K, L, M) method, A a, B b, C c, D d, E e, F f, G g, H h, I i, J j, K k, L l, M m)
class B class C class D class E class F class G class H class I class J class K class L Journal::Method ((Obj *obj, void(Obj::*)(A, B, C, D, E, F, G, H, I, J, K, L) method, A a, B b, C c, D d, E e, F f, G g, H h, I i, J j, K k, L l)
class B class C class D class E class F class G class H class I class J class K Journal::Method ((Obj *obj, void(Obj::*)(A, B, C, D, E, F, G, H, I, J, K) method, A a, B b, C c, D d, E e, F f, G g, H h, I i, J j, K k)
class B class C class D class E class F class G class H class I class J Journal::Method ((Obj *obj, void(Obj::*)(A, B, C, D, E, F, G, H, I, J) method, A a, B b, C c, D d, E e, F f, G g, H h, I i, J j)
class B class C class D class E class F class G class H class I Journal::Method ((Obj *obj, void(Obj::*)(A, B, C, D, E, F, G, H, I) method, A a, B b, C c, D d, E e, F f, G g, H h, I i)
class B class C class D class E class F class G class H Journal::Method ((Obj *obj, void(Obj::*)(A, B, C, D, E, F, G, H) method, A a, B b, C c, D d, E e, F f, G g, H h)
class B class C class D class E class F class G Journal::Method ((Obj *obj, void(Obj::*)(A, B, C, D, E, F, G) method, A a, B b, C c, D d, E e, F f, G g)
class B class C class D class E class F Journal::Method ((Obj *obj, void(Obj::*)(A, B, C, D, E, F) method, A a, B b, C c, D d, E e, F f)
class B class C class D class E Journal::Method ((Obj *obj, void(Obj::*)(A, B, C, D, E) method, A a, B b, C c, D d, E e)
class B class C class D Journal::Method ((Obj *obj, void(Obj::*)(A, B, C, D) method, A a, B b, C c, D d)
class B class C Journal::Method ((Obj *obj, void(Obj::*)(A, B, C) method, A a, B b, C c)
class B class A Journal::Method ((Obj *obj, void(Obj::*)(A) method, A a)
template<class A , class B , class C , class D , class E , class F , class G , class H , class I , class J , class K , class L , class M > Journal::Method ((A &a, B &b, C &c, D &d, E &e, F &f, G &g, H &h, I &i, J &j, K &k, L &l, M &m) , (mFile, a, b, c, d, e, f, g, h, i, j, k, l, m))
template<class A , class B , class C , class D , class E , class F , class G , class H , class I , class J , class K , class L > Journal::Method ((A &a, B &b, C &c, D &d, E &e, F &f, G &g, H &h, I &i, J &j, K &k, L &l) , (mFile, a, b, c, d, e, f, g, h, i, j, k, l))
template<class A , class B , class C , class D , class E , class F , class G , class H , class I , class J , class K > Journal::Method ((A &a, B &b, C &c, D &d, E &e, F &f, G &g, H &h, I &i, J &j, K &k) , (mFile, a, b, c, d, e, f, g, h, i, j, k))
template<class A , class B , class C , class D , class E , class F , class G , class H , class I , class J > Journal::Method ((A &a, B &b, C &c, D &d, E &e, F &f, G &g, H &h, I &i, J &j) , (mFile, a, b, c, d, e, f, g, h, i, j))
template<class A , class B , class C , class D , class E , class F , class G , class H , class I > Journal::Method ((A &a, B &b, C &c, D &d, E &e, F &f, G &g, H &h, I &i) , (mFile, a, b, c, d, e, f, g, h, i))
template<class A , class B , class C , class D , class E , class F , class G , class H > Journal::Method ((A &a, B &b, C &c, D &d, E &e, F &f, G &g, H &h) , (mFile, a, b, c, d, e, f, g, h))
template<class A , class B , class C , class D , class E , class F , class G > Journal::Method ((A &a, B &b, C &c, D &d, E &e, F &f, G &g) , (mFile, a, b, c, d, e, f, g))
template<class A , class B , class C , class D , class E , class F > Journal::Method ((A &a, B &b, C &c, D &d, E &e, F &f) , (mFile, a, b, c, d, e, f))
template<class A , class B , class C , class D , class E > Journal::Method ((A &a, B &b, C &c, D &d, E &e) , (mFile, a, b, c, d, e))
template<class A , class B , class C , class D > Journal::Method ((A &a, B &b, C &c, D &d) , (mFile, a, b, c, d))
template<class A , class B , class C > Journal::Method ((A &a, B &b, C &c) , (mFile, a, b, c))
template<class A , class B > Journal::Method ((A &a, B &b) , (mFile, a, b))
template<class A > Journal::Method ((A &a) , (mFile, a))
template<class A , class B , class C , class D , class E , class F , class G , class H , class I , class J , class K , class L , class M > Journal::Method ((A &a, B &b, C &c, D &d, E &e, F &f, G &g, H &h, I &i, J &j, K &k, L &l, M &m) , (mFile, a, b, c, d, e, f, g, h, i, j, k, l, m))
template<class A , class B , class C , class D , class E , class F , class G , class H , class I , class J , class K , class L > Journal::Method ((A &a, B &b, C &c, D &d, E &e, F &f, G &g, H &h, I &i, J &j, K &k, L &l) , (mFile, a, b, c, d, e, f, g, h, i, j, k, l))
template<class A , class B , class C , class D , class E , class F , class G , class H , class I , class J , class K > Journal::Method ((A &a, B &b, C &c, D &d, E &e, F &f, G &g, H &h, I &i, J &j, K &k) , (mFile, a, b, c, d, e, f, g, h, i, j, k))
template<class A , class B , class C , class D , class E , class F , class G , class H , class I , class J > Journal::Method ((A &a, B &b, C &c, D &d, E &e, F &f, G &g, H &h, I &i, J &j) , (mFile, a, b, c, d, e, f, g, h, i, j))
template<class A , class B , class C , class D , class E , class F , class G , class H , class I > Journal::Method ((A &a, B &b, C &c, D &d, E &e, F &f, G &g, H &h, I &i) , (mFile, a, b, c, d, e, f, g, h, i))
template<class A , class B , class C , class D , class E , class F , class G , class H > Journal::Method ((A &a, B &b, C &c, D &d, E &e, F &f, G &g, H &h) , (mFile, a, b, c, d, e, f, g, h))
template<class A , class B , class C , class D , class E , class F , class G > Journal::Method ((A &a, B &b, C &c, D &d, E &e, F &f, G &g) , (mFile, a, b, c, d, e, f, g))
template<class A , class B , class C , class D , class E , class F > Journal::Method ((A &a, B &b, C &c, D &d, E &e, F &f) , (mFile, a, b, c, d, e, f))
template<class A , class B , class C , class D , class E > Journal::Method ((A &a, B &b, C &c, D &d, E &e) , (mFile, a, b, c, d, e))
template<class A , class B , class C , class D > Journal::Method ((A &a, B &b, C &c, D &d) , (mFile, a, b, c, d))
template<class A , class B , class C > Journal::Method ((A &a, B &b, C &c) , (mFile, a, b, c))
template<class A , class B > Journal::Method ((A &a, B &b) , (mFile, a, b))
template<class A > Journal::Method ((A &a) , (mFile, a))
static void Journal::Play (const char * file) static
static bool Journal::PlayNext () static
template<typename T > static void Journal::Read (T * v) inline static
References IsPlaying(), and Stream::read().
static bool Journal::Read (U32 size, void * buffer) inline static
References IsPlaying(), and Stream::read().
static void Journal::ReadString (char str[256]) inline static
References IsPlaying(), and Stream::readString().
static void Journal::Record (const char * file) static
template<typename T , typename U > static void Journal::RemoveFunction (T obj, U method) inline static
References func, and Method().
Referenced by JournaledSignal< void()>::~JournaledSignal(), JournaledSignal< void(A)>::~JournaledSignal(), JournaledSignal< void(A, B)>::~JournaledSignal(), JournaledSignal< void(A, B, C)>::~JournaledSignal(), JournaledSignal< void(A, B, C, D)>::~JournaledSignal(), JournaledSignal< void(A, B, C, D, E)>::~JournaledSignal(), JournaledSignal< void(A, B, C, D, E, F)>::~JournaledSignal(), JournaledSignal< void(A, B, C, D, E, F, G)>::~JournaledSignal(), JournaledSignal< void(A, B, C, D, E, F, G, H)>::~JournaledSignal(), JournaledSignal< void(A, B, C, D, E, F, G, H, I, J, K)>::~JournaledSignal(), JournaledSignal< void(A, B, C, D, E, F, G, H, I, J, K, L)>::~JournaledSignal(), and JournaledSignal< void(A, B, C, D, E, F, G, H, I, J, K, L, M)>::~JournaledSignal().
static void Journal::Stop () static
template<typename T > static void Journal::Write (const T & v) inline static
References IsRecording(), and Stream::write().
static bool Journal::Write (U32 size, void * buffer) inline static
References IsRecording(), and Stream::write().
static void Journal::WriteString (const char str[256]) inline static
References IsRecording(), and Stream::writeString().
Member Data Documentation
class B class A Func Journal::func
Referenced by DeclareFunction(), and RemoveFunction().
class B class A Journal::id
class B class A void(Obj::* Journal::id)
class B class A void(Obj::* Journal::method) ())
Referenced by DeclareFunction().
class B class A Journal::mFile
class B class A void(Obj::* Journal::mFile)
Copyright © GarageGames, LLC. All Rights Reserved.