StringBuffer Class Reference
Main Modules Class List Namespace List Online
StringBuffer Class Reference
Utility class to wrap string manipulation in a representation independent way.
#include <core/stringBuffer.h>
Classes
struct RequestCounts
Public Member Functions
StringBuffer ()
StringBuffer (const StringBuffer &copy)
StringBuffer (const StringBuffer *in)
StringBuffer (const UTF8 *in)
StringBuffer (const UTF16 *in)
~StringBuffer ()
void append (const StringBuffer &in)
void append (const UTF8 *in)
void append (const UTF16 *in)
void append (const UTF16 *in, U32 len)
UTF16 * createCopy () const
UTF8 * createCopy8 () const
Get a copy of the contents of the string buffer.
UTF16 * createSubstring16 (const U32 start, const U32 len) const
UTF8 * createSubstring8 (const U32 start, const U32 len) const
Get a pointer to a substring of length 'len' starting from 'start'.
void cut (const U32 start, const U32 len)
const UTF16 getChar (const U32 offset) const
void getCopy (UTF16 *buff, const U32 buffSize) const
void getCopy8 (UTF8 *buff, const U32 buffSize) const
const UTF16 * getPtr () const
Get a pointer to the StringBuffer's data store.
const UTF8 * getPtr8 () const
const U32 getUTF8BufferSizeEstimate () const
Get an upper bound size estimate for a UTF8 buffer to hold this string.
void insert (const U32 charOffset, const StringBuffer &in)
void insert (const U32 charOffset, const UTF8 *in)
void insert (const U32 charOffset, const UTF16 *in)
void insert (const U32 charOffset, const UTF16 *in, const U32 len)
const U32 length () const
void set (const StringBuffer *in)
void set (const UTF8 *in)
void set (const UTF16 *in)
void setChar (const U32 offset, UTF16 c)
StringBuffer substring (const U32 start, const U32 len) const
Get a StringBuffer substring of length 'len' starting from 'start'.
Public Attributes
RequestCounts * rc
Detailed Description
Utility class to wrap string manipulation in a representation independent way.
Length does NOT include the null terminator.
Constructor & Destructor Documentation
StringBuffer::StringBuffer ()
StringBuffer::StringBuffer (const StringBuffer & copy)
StringBuffer::StringBuffer (const StringBuffer * in)
StringBuffer::StringBuffer (const UTF8 * in)
StringBuffer::StringBuffer (const UTF16 * in)
StringBuffer::~StringBuffer ()
Member Function Documentation
void StringBuffer::append (const StringBuffer & in)
void StringBuffer::append (const UTF8 * in)
void StringBuffer::append (const UTF16 * in)
void StringBuffer::append (const UTF16 * in, U32 len)
UTF16* StringBuffer::createCopy () const
Referenced by getUTF8BufferSizeEstimate().
UTF8* StringBuffer::createCopy8 () const
Get a copy of the contents of the string buffer.
You must delete[] the returned copy when you are done with it. This follows the "create rule".
Referenced by getUTF8BufferSizeEstimate().
UTF16* StringBuffer::createSubstring16 (const U32 start, const U32 len) const
UTF8* StringBuffer::createSubstring8 (const U32 start, const U32 len) const
Get a pointer to a substring of length 'len' starting from 'start'.
Returns a raw pointer to a unicode string. You must delete[] the returned string when you are done with it. This follows the "create rule".
void StringBuffer::cut (const U32 start, const U32 len)
const UTF16 StringBuffer::getChar (const U32 offset) const
void StringBuffer::getCopy (UTF16 * buff, const U32 buffSize) const
Referenced by getUTF8BufferSizeEstimate().
void StringBuffer::getCopy8 (UTF8 * buff, const U32 buffSize) const
Referenced by getUTF8BufferSizeEstimate().
const UTF16* StringBuffer::getPtr () const
Get a pointer to the StringBuffer's data store.
Use this in situations where you can be sure that the StringBuffer will not be modified out from under you. The win here is, you avoid yet another data copy. Data copy is slow on most modern hardware.
Referenced by getUTF8BufferSizeEstimate().
const UTF8* StringBuffer::getPtr8 () const
Referenced by getUTF8BufferSizeEstimate().
const U32 StringBuffer::getUTF8BufferSizeEstimate () const inline
Get an upper bound size estimate for a UTF8 buffer to hold this string.
References createCopy(), createCopy8(), getCopy(), getCopy8(), getPtr(), getPtr8(), length(), StringBuffer::RequestCounts::requestCount16, and StringBuffer::RequestCounts::requestCount8.
void StringBuffer::insert (const U32 charOffset, const StringBuffer & in)
void StringBuffer::insert (const U32 charOffset, const UTF8 * in)
void StringBuffer::insert (const U32 charOffset, const UTF16 * in)
void StringBuffer::insert (const U32 charOffset, const UTF16 * in, const U32 len)
const U32 StringBuffer::length () const inline
References Vector< T >::size().
Referenced by getUTF8BufferSizeEstimate().
void StringBuffer::set (const StringBuffer * in)
void StringBuffer::set (const UTF8 * in)
void StringBuffer::set (const UTF16 * in)
void StringBuffer::setChar (const U32 offset, UTF16 c)
StringBuffer StringBuffer::substring (const U32 start, const U32 len) const
Get a StringBuffer substring of length 'len' starting from 'start'.
Returns a new StringBuffer by value;
Member Data Documentation
RequestCounts* StringBuffer::rc
Copyright © GarageGames, LLC. All Rights Reserved.