SceneAmbientSoundObject< Base > Class Template Reference
Main Modules Class List Namespace List Online
SceneAmbientSoundObject< Base > Class Template Reference
Template mixin to add ability to hold a custom SFXAmbience to a SceneObject.
#include <scene/mixin/sceneAmbientSoundObject.h>
Public Types
typedef Base Parent
Public Member Functions
SceneAmbientSoundObject ()
virtual SFXAmbience * getSoundAmbience () const
virtual U32 packUpdate (NetConnection *connection, U32 mask, BitStream *stream)
void setSoundAmbience (SFXAmbience *ambience)
Set the ambient sound properties for the space.
virtual void unpackUpdate (NetConnection *connection, BitStream *stream)
Static Public Member Functions
static void initPersistFields ()
Protected Types
enum {
SoundMask = Parent::NextFreeMask << 0,
NextFreeMask = Parent::NextFreeMask << 1
}
Protected Attributes
SFXAmbience * mSoundAmbience
Ambient sound properties for this space.
Detailed Description
template<typename Base>
class SceneAmbientSoundObject< Base >
Template mixin to add ability to hold a custom SFXAmbience to a SceneObject.
Member Typedef Documentation
template<typename Base> typedef Base SceneAmbientSoundObject< Base >::Parent
Member Enumeration Documentation
template<typename Base> anonymous enum protected
Enumerator
SoundMask
Ambient sound properties have changed.
NextFreeMask
Constructor & Destructor Documentation
template<typename Base > SceneAmbientSoundObject< Base >::SceneAmbientSoundObject ()
Member Function Documentation
template<typename Base> virtual SFXAmbience* SceneAmbientSoundObject< Base >::getSoundAmbience () const inline virtual
template<typename Base > void SceneAmbientSoundObject< Base >::initPersistFields (void) static
References SceneAmbientSoundObject< Base >::mSoundAmbience, and Offset.
template<typename Base > U32 SceneAmbientSoundObject< Base >::packUpdate (NetConnection * connection, U32 mask, BitStream * stream) virtual
Reimplemented in Portal.
References SceneAmbientSoundObject< Base >::mSoundAmbience, SceneAmbientSoundObject< Base >::SoundMask, and BitStream::writeFlag().
template<typename Base > void SceneAmbientSoundObject< Base >::setSoundAmbience (SFXAmbience * ambience)
Set the ambient sound properties for the space.
References SceneAmbientSoundObject< Base >::mSoundAmbience, SFX3DWorld::notifyChanged(), SceneAmbientSoundObject< Base >::setSoundAmbience(), and SceneAmbientSoundObject< Base >::SoundMask.
Referenced by SceneAmbientSoundObject< Base >::setSoundAmbience(), and SceneAmbientSoundObject< Base >::unpackUpdate().
template<typename Base > void SceneAmbientSoundObject< Base >::unpackUpdate (NetConnection * connection, BitStream * stream) virtual
Reimplemented in Portal.
References String::c_str(), Con::errorf(), BitStream::readFlag(), and SceneAmbientSoundObject< Base >::setSoundAmbience().
Member Data Documentation
template<typename Base> SFXAmbience* SceneAmbientSoundObject< Base >::mSoundAmbience protected
Ambient sound properties for this space.
Referenced by SceneAmbientSoundObject< ScenePolyhedralZone >::getSoundAmbience(), SceneAmbientSoundObject< Base >::initPersistFields(), SceneAmbientSoundObject< Base >::packUpdate(), and SceneAmbientSoundObject< Base >::setSoundAmbience().
Copyright © GarageGames, LLC. All Rights Reserved.