MRandomGenerator Class Reference
Main Modules Class List Namespace List Online
MRandomGenerator Class Reference abstract
Base class for random number generators.
#include <math/mRandom.h>
Public Member Functions
virtual ~MRandomGenerator ()
S32 getSeed ()
virtual F32 randF (void)
0.0 .. 1.0 F32 random number generator
F32 randF (F32 i, F32 n)
i..n F32 random number generator
virtual U32 randI (void)=0
0..2^31 random number generator
S32 randI (S32 i, S32 n)
i..n integer random number generator
void setSeed ()
virtual void setSeed (S32 s)=0
Protected Member Functions
MRandomGenerator ()
Protected Attributes
S32 mSeed
Detailed Description
Base class for random number generators.
Constructor & Destructor Documentation
MRandomGenerator::MRandomGenerator () inline protected
virtual MRandomGenerator::~MRandomGenerator () inline virtual
References setSeed().
Member Function Documentation
S32 MRandomGenerator::getSeed () inline
References mSeed, randF(), randI(), and setSeed().
F32 MRandomGenerator::randF (void) inline virtual
0.0 .. 1.0 F32 random number generator
References randI().
Referenced by MRandomSet< T >::get(), getSeed(), SFXVariantFloat< NUM_SLOTS >::getValue(), and randF().
F32 MRandomGenerator::randF (F32 i, F32 n) inline
i..n F32 random number generator
References randF().
virtual U32 MRandomGenerator::randI (void) pure virtual
0..2^31 random number generator
Implemented in MRandomR250, and MRandomLCG.
Referenced by getSeed(), randF(), randI(), MRandomLCG::randI(), MRandomLCG::~MRandomLCG(), and MRandomR250::~MRandomR250().
S32 MRandomGenerator::randI (S32 i, S32 n) inline
i..n integer random number generator
References randI().
void MRandomGenerator::setSeed ()
Referenced by getSeed(), ~MRandomGenerator(), MRandomLCG::~MRandomLCG(), and MRandomR250::~MRandomR250().
virtual void MRandomGenerator::setSeed (S32 s) pure virtual
Implemented in MRandomR250, and MRandomLCG.
Member Data Documentation
S32 MRandomGenerator::mSeed protected
Referenced by getSeed().
Copyright © GarageGames, LLC. All Rights Reserved.