PlaneD Class Reference
Main Modules Class List Namespace List Online
PlaneD Class Reference
#include <math/mPlane.h>
Public Types
enum Side {
Front = 1,
On = 0,
Back = -1
}
Public Member Functions
PlaneD ()
PlaneD (const PlaneF &copy)
PlaneD (const Point3D &p, const Point3D &n)
PlaneD (F64 _x, F64 _y, F64 _z, F64 _d)
NOTE: d is the NEGATIVE distance along the xyz normal.
PlaneD (const Point3D &j, const Point3D &k, const Point3D &l)
F64 distToPlane (const Point3D &cp) const
F64 intersect (const Point3D &start, const Point3D &end) const
void invert ()
bool isHorizontal () const
bool isVertical () const
void neg ()
Point3D project (const Point3D &pt) const
void set (const F64 _x, const F64 _y, const F64 _z)
void set (const Point3D &p, const Point3D &n)
void set (const Point3D &k, const Point3D &j, const Point3D &l)
void setPoint (const Point3D &p)
void setXY (F64 zz)
void setXY (const Point3D &P, F64 dir)
void setXZ (F64 yy)
void setXZ (const Point3D &P, F64 dir)
void setYZ (F64 xx)
void setYZ (const Point3D &P, F64 dir)
void shiftX (F64 xx)
void shiftY (F64 yy)
void shiftZ (F64 zz)
Side whichSide (const Point3D &cp) const
Side whichSideBox (const Point3D &center, const Point3D &axisx, const Point3D &axisy, const Point3D &axisz) const
Public Member Functions inherited from Point3D
Point3D ()
Point3D (const Point3D &)
Point3D (const Point3F &)
Point3D (F64 xyz)
Point3D (F64 _x, F64 _y, F64 _z)
void convolve (const Point3D &)
void convolveInverse (const Point3D &)
void interpolate (const Point3D &, const Point3D &, F64)
bool isZero () const
F64 len () const
F64 lenSquared () const
F64 magnitudeSafe () const
void neg ()
void normalize ()
void normalize (F64 val)
void normalizeSafe ()
operator const F64 * () const
operator F64 * ()
bool operator!= (const Point3D &) const
Point3D operator* (F64) const
Point3D & operator*= (F64)
Point3D operator+ (const Point3D &) const
Point3D & operator+= (const Point3D &)
Point3D operator- (const Point3D &) const
Point3D operator- () const
Point3D & operator-= (const Point3D &)
Point3D operator/ (F64) const
Point3D & operator/= (F64)
bool operator== (const Point3D &) const
void set (F64 xyz)
void set (F64 _x, F64 _y, F64 _z)
void setMax (const Point3D &)
void setMin (const Point3D &)
Point3F toPoint3F () const
void zero ()
Public Attributes
F64 d
NOTE: d is the NEGATIVE distance along the xyz normal.
Public Attributes inherited from Point3D
F64 x
F64 y
F64 z
Additional Inherited Members
Static Public Attributes inherited from Point3D
static const Point3D One
static const Point3D Zero
Member Enumeration Documentation
enum PlaneD::Side
Enumerator
Front
On
Back
Constructor & Destructor Documentation
PlaneD::PlaneD () inline
PlaneD::PlaneD (const PlaneF & copy) inline
References PlaneF::d, Point3F::x, Point3F::y, and Point3F::z.
PlaneD::PlaneD (const Point3D & p, const Point3D & n) inline
PlaneD::PlaneD (F64 _x, F64 _y, F64 _z, F64 _d) inline
NOTE: d is the NEGATIVE distance along the xyz normal.
References PlaneF::d, Point3F::x, Point3F::y, and Point3F::z.
PlaneD::PlaneD (const Point3D & j, const Point3D & k, const Point3D & l) inline
Member Function Documentation
F64 PlaneD::distToPlane (const Point3D & cp) const inline
References PlaneF::d, Point3F::x, Point3D::x, Point3F::y, Point3D::y, Point3F::z, and Point3D::z.
F64 PlaneD::intersect (const Point3D & start, const Point3D & end) const inline
References PlaneF::distToPlane().
void PlaneD::invert () inline
References PlaneF::d, Point3F::x, Point3F::y, and Point3F::z.
bool PlaneD::isHorizontal () const inline
References Point3F::x, and Point3F::y.
bool PlaneD::isVertical () const inline
References Point3F::x, Point3F::y, and Point3F::z.
void PlaneD::neg () inline
References PlaneF::invert().
Point3D PlaneD::project (const Point3D & pt) const inline
References PlaneF::distToPlane(), Point3F::x, Point3D::x, Point3F::y, Point3D::y, Point3F::z, and Point3D::z.
void PlaneD::set (const F64 _x, const F64 _y, const F64 _z) inline
References Point3D::set().
void PlaneD::set (const Point3D & p, const Point3D & n) inline
References PlaneF::d, Point3F::normalize(), Point3F::x, Point3D::x, Point3F::y, Point3D::y, Point3F::z, and Point3D::z.
void PlaneD::set (const Point3D & k, const Point3D & j, const Point3D & l) inline
References PlaneF::d, Point3F::x, Point3D::x, Point3F::y, Point3D::y, Point3F::z, and Point3D::z.
void PlaneD::setPoint (const Point3D & p) inline
References PlaneF::d, Point3F::x, Point3D::x, Point3F::y, Point3D::y, Point3F::z, and Point3D::z.
void PlaneD::setXY (F64 zz) inline
References PlaneF::d, Point3F::x, Point3F::y, and Point3F::z.
void PlaneD::setXY (const Point3D & P, F64 dir) inline
References PlaneF::d, Point3F::x, Point3F::y, Point3F::z, and Point3D::z.
void PlaneD::setXZ (F64 yy) inline
References PlaneF::d, Point3F::x, Point3F::y, and Point3F::z.
void PlaneD::setXZ (const Point3D & P, F64 dir) inline
References PlaneF::d, Point3F::x, Point3F::y, Point3D::y, and Point3F::z.
void PlaneD::setYZ (F64 xx) inline
References PlaneF::d, Point3F::x, Point3F::y, and Point3F::z.
void PlaneD::setYZ (const Point3D & P, F64 dir) inline
References PlaneF::d, Point3F::x, Point3D::x, Point3F::y, and Point3F::z.
void PlaneD::shiftX (F64 xx) inline
References PlaneF::d, and Point3F::x.
void PlaneD::shiftY (F64 yy) inline
References PlaneF::d, and Point3F::y.
void PlaneD::shiftZ (F64 zz) inline
References PlaneF::d, and Point3F::z.
PlaneD::Side PlaneD::whichSide (const Point3D & cp) const inline
References PlaneF::Back, PlaneF::distToPlane(), PlaneF::Front, and PlaneF::On.
PlaneD::Side PlaneD::whichSideBox (const Point3D & center, const Point3D & axisx, const Point3D & axisy, const Point3D & axisz) const inline
References PlaneF::Back, PlaneF::distToPlane(), PlaneF::Front, and PlaneF::On.
Member Data Documentation
F64 PlaneD::d
NOTE: d is the NEGATIVE distance along the xyz normal.
Copyright © GarageGames, LLC. All Rights Reserved.