TSIntegerSet Class Reference
Main Modules Class List Namespace List Online
TSIntegerSet Class Reference
The standard mathmatical set, where there are no duplicates.
#include <ts/tsIntegerSet.h>
Public Member Functions
TSIntegerSet ()
TSIntegerSet (const TSIntegerSet &)
void clear (S32 index)
Sets this bit to false.
void clearAll (S32 upto=MAX_TS_SET_SIZE)
Sets all bits to false.
void copy (const TSIntegerSet &)
copy one integer set into another
S32 count (S32 upto=MAX_TS_SET_SIZE) const
Counts set bits.
void difference (const TSIntegerSet &)
xor (a | b) & (!(a & b))
S32 end () const
void erase (S32 index)
void insert (S32 index, bool value)
void intersect (const TSIntegerSet &)
intersection (a & b)
void next (S32 &i) const
void operator= (const TSIntegerSet &otherSet)
void overlap (const TSIntegerSet &)
union (a | b)
void read (Stream *)
void set (S32 index)
Set this bit to true.
void setAll (S32 upto=MAX_TS_SET_SIZE)
Sets all bits to true.
S32 start () const
void takeAway (const TSIntegerSet &)
subtraction (a - b)
bool test (S32 index) const
Is this bit true?
bool testAll (S32 upto=MAX_TS_SET_SIZE) const
Tests all bits for true.
void write (Stream *) const
Detailed Description
The standard mathmatical set, where there are no duplicates.
However, this set uses bits instead of numbers.
Constructor & Destructor Documentation
TSIntegerSet::TSIntegerSet ()
Referenced by operator=().
TSIntegerSet::TSIntegerSet (const TSIntegerSet &)
Member Function Documentation
void TSIntegerSet::clear (S32 index) inline
Sets this bit to false.
void TSIntegerSet::clearAll (S32 upto = MAX_TS_SET_SIZE)
Sets all bits to false.
void TSIntegerSet::copy (const TSIntegerSet &)
copy one integer set into another
Referenced by operator=().
S32 TSIntegerSet::count (S32 upto = MAX_TS_SET_SIZE) const
Counts set bits.
void TSIntegerSet::difference (const TSIntegerSet &)
xor (a | b) & (!(a & b))
S32 TSIntegerSet::end () const
Referenced by operator=().
void TSIntegerSet::erase (S32 index)
void TSIntegerSet::insert (S32 index, bool value)
void TSIntegerSet::intersect (const TSIntegerSet &)
intersection (a & b)
void TSIntegerSet::next (S32 & i) const
Referenced by operator=().
void TSIntegerSet::operator= (const TSIntegerSet & otherSet) inline
References copy(), end(), next(), read(), start(), TSIntegerSet(), and write().
void TSIntegerSet::overlap (const TSIntegerSet &)
union (a | b)
void TSIntegerSet::read (Stream *)
Referenced by operator=().
void TSIntegerSet::set (S32 index) inline
Set this bit to true.
void TSIntegerSet::setAll (S32 upto = MAX_TS_SET_SIZE)
Sets all bits to true.
S32 TSIntegerSet::start () const
Referenced by operator=().
void TSIntegerSet::takeAway (const TSIntegerSet &)
subtraction (a - b)
bool TSIntegerSet::test (S32 index) const inline
Is this bit true?
bool TSIntegerSet::testAll (S32 upto = MAX_TS_SET_SIZE) const
Tests all bits for true.
void TSIntegerSet::write (Stream *) const
Referenced by operator=().
Copyright © GarageGames, LLC. All Rights Reserved.