T3DSceneClient Class Reference
Main Modules Class List Namespace List Online
T3DSceneClient Class Reference
#include <T3D/sceneComponent/T3DSceneClient.h>
Public Member Functions
T3DSceneClient ()
T3DSceneClient * getNextSceneClient ()
StringTableEntry getSceneClientName ()
T3DSceneComponent * getSceneGroup ()
StringTableEntry getSceneGroupName ()
void setNextSceneClient (T3DSceneClient *client)
void setSceneClientName (const char *name)
void setSceneGroupName (const char *name)
Protected Member Functions
bool onComponentRegister (SimComponent *owner)
void registerInterfaces (SimComponent *owner)
Protected Attributes
T3DSceneClient * _nextClient
StringTableEntry _sceneClientName
T3DSceneComponent * _sceneGroup
StringTableEntry _sceneGroupName
Constructor & Destructor Documentation
T3DSceneClient::T3DSceneClient () inline
References _nextClient, _sceneClientName, _sceneGroup, and _sceneGroupName.
Member Function Documentation
T3DSceneClient* T3DSceneClient::getNextSceneClient () inline
References _nextClient.
StringTableEntry T3DSceneClient::getSceneClientName () inline
References _sceneClientName.
T3DSceneComponent* T3DSceneClient::getSceneGroup () inline
References _sceneGroup.
StringTableEntry T3DSceneClient::getSceneGroupName () inline
References _sceneGroupName, and setSceneGroupName().
bool T3DSceneClient::onComponentRegister (SimComponent * owner) protected
Referenced by setSceneClientName().
void T3DSceneClient::registerInterfaces (SimComponent * owner) protected
Referenced by setSceneClientName().
void T3DSceneClient::setNextSceneClient (T3DSceneClient * client) inline
References _nextClient.
void T3DSceneClient::setSceneClientName (const char * name) inline
References _sceneClientName, onComponentRegister(), and registerInterfaces().
void T3DSceneClient::setSceneGroupName (const char * name)
Referenced by getSceneGroupName().
Member Data Documentation
T3DSceneClient* T3DSceneClient::_nextClient protected
Referenced by getNextSceneClient(), setNextSceneClient(), and T3DSceneClient().
StringTableEntry T3DSceneClient::_sceneClientName protected
Referenced by getSceneClientName(), setSceneClientName(), and T3DSceneClient().
T3DSceneComponent* T3DSceneClient::_sceneGroup protected
Referenced by getSceneGroup(), and T3DSceneClient().
StringTableEntry T3DSceneClient::_sceneGroupName protected
Referenced by getSceneGroupName(), and T3DSceneClient().
Copyright © GarageGames, LLC. All Rights Reserved.