TSShapeInstance Class Reference
Main Modules Class List Namespace List Online
TSShapeInstance Class Reference
An instance of a 3space shape.
#include <ts/tsShapeInstance.h>
Classes
struct MeshObjectInstance
These are set up by default based on shape data.
struct ObjectInstance
Base class for all renderable objects, including mesh objects and decal objects.
struct RenderData
struct TSCallbackRecord
Public Types
enum {
MaskNodeRotation = 0x01,
MaskNodePosX = 0x02,
MaskNodePosY = 0x04,
MaskNodePosZ = 0x08,
MaskNodeBlend = 0x10,
MaskNodeAll = MaskNodeRotation|MaskNodePosX|MaskNodePosY|MaskNodePosZ|MaskNodeBlend,
MaskNodeAllButBlend = MaskNodeRotation|MaskNodePosX|MaskNodePosY|MaskNodePosZ,
MaskNodeAllButRotation = MaskNodePosX|MaskNodePosY|MaskNodePosZ|MaskNodeBlend,
MaskNodeAllButPosX = MaskNodeRotation|MaskNodePosY|MaskNodePosZ|MaskNodeBlend,
MaskNodeAllButPosY = MaskNodeRotation|MaskNodePosX|MaskNodePosZ|MaskNodeBlend,
MaskNodeAllButPosZ = MaskNodeRotation|MaskNodePosX|MaskNodePosY|MaskNodeBlend,
MaskNodeHandsOff = 0x20,
MaskNodeCallback = 0x40
}
enum {
TransformDirty = BIT(0),
VisDirty = BIT(1),
FrameDirty = BIT(2),
MatFrameDirty = BIT(3),
ThreadDirty = BIT(4),
AllDirtyMask = TransformDirty | VisDirty | FrameDirty | MatFrameDirty | ThreadDirty
}
Public Member Functions
TSShapeInstance (const Resource< TSShape > &shape, bool loadMaterials=true)
TSShapeInstance (TSShape *pShape, bool loadMaterials=true)
~TSShapeInstance ()
void animate ()
void animate (S32 dl)
void animateFrame (S32 ss)
void animateMatFrame (S32 ss)
void animateNodes (S32 ss)
void animateNodeSubtrees (bool forceFull=true)
void animateSubtrees (bool forceFull=true)
void animateVisibility (S32 ss)
bool bufferNeedsUpdate (S32 objectDetail, S32 start, S32 end)
bool buildConvexOpcode (const MatrixF &objMat, const Point3F &objScale, S32 objectDetail, const Box3F &bounds, Convex *c, Convex *list)
void buildInstanceData (TSShape *, bool loadMaterials)
bool buildPolyList (AbstractPolyList *, S32 dl)
bool buildPolyListOpcode (S32 dl, AbstractPolyList *polyList, const Box3F &box)
bool castRay (const Point3F &start, const Point3F &end, RayInfo *, S32 dl)
bool castRayOpcode (S32 objectDetail, const Point3F &start, const Point3F &end, RayInfo *)
bool castRayRendered (const Point3F &start, const Point3F &end, RayInfo *, S32 dl)
void clearDirty (U32 dirty)
void cloneMaterialList (const FeatureSet *features=NULL)
Call this to own the material list – i.e., we'll make a copy of the currently set material list and be responsible for deleting it.
void computeBounds (S32 dl, Box3F &bounds)
uses current transforms to compute bounding box around a detail level see like named method on shape if you want to use default transforms
void dump (Stream &)
void dumpNode (Stream &, S32 level, S32 nodeIndex, Vector< S32 > &detailSizes)
S32 getCurrentDetail () const
F32 getCurrentIntraDetail () const
bool getFeatures (const MatrixF &mat, const Point3F &n, ConvexFeature *, S32 dl)
TSMaterialList * getMaterialList () const
U32 getNumDetails () const
TSShape * getShape () const
S32 getTargetCount () const
Get the number of material targets in this shape instance.
const String & getTargetName (S32 mapToNameIndex) const
Get the indexed material target (may differ from the base TSShape material list if this instance has been reskinned).
bool hasAccumulation ()
void initMaterialList (const FeatureSet *features=NULL)
Initializes or re-initializes the material list with an optional feature set.
void initMeshObjects ()
void initNodeTransforms ()
bool inTransition ()
bool ownMaterialList () const
void prepCollision ()
bool quickLOS (const Point3F &start, const Point3F &end, S32 dl)
void render (const TSRenderState &rdata)
void render (const TSRenderState &rdata, S32 dl, F32 intraDL=0.0f)
void reSkin (String newBaseName, String oldBaseName=String::EmptyString)
void setCurrentDetail (S32 dl, F32 intraDL=1.0f)
S32 setDetailFromDistance (const SceneRenderState *state, F32 scaledDist)
Selects the current detail level using the scaled distance between your object and the camera.
S32 setDetailFromPosAndScale (const SceneRenderState *state, const Point3F &pos, const Point3F &scale)
Helper function which internally calls setDetailFromDistance.
S32 setDetailFromScreenError (F32 errorTOL)
Sets the current detail level using the legacy screen error metric.
void setDirty (U32 dirty)
void setMaterialList (TSMaterialList *matList)
Set the material list without taking ownership.
void setMeshForceHidden (const char *meshName, bool hidden)
Sets the 'forceHidden' state on the named mesh.
void setMeshForceHidden (S32 meshIndex, bool hidden)
Sets the 'forceHidden' state on a mesh.
void setUseOwnBuffer ()
Point3F support (const Point3F &v, S32 dl)
Node Masking
set node masking...
void setNodeAnimationState (S32 nodeIndex, U32 animationState, TSCallback *callback=NULL)
U32 getNodeAnimationState (S32 nodeIndex)
Trigger states
check trigger value
bool getTriggerState (U32 stateNum, bool clearState=true)
void setTriggerState (U32 stateNum, bool on)
void setTriggerStateBit (U32 stateBit, bool on)
Debris Management
void incDebrisRefCount ()
void decDebrisRefCount ()
U32 getDebrisRefCount () const
AlphaAlways
AlphaAlways allows the entire model to become translucent at the same value
void setAlphaAlways (F32 value)
F32 getAlphaAlwaysValue () const
bool getAlphaAlways () const
void renderDebugNormals (F32 normalScalar, S32 dl)
Debugging.
void renderDebugNodes ()
Render all node transforms as small axis gizmos.
void listMeshes (const String &state) const
Print mesh data to the console, valid String parameters are Visible, Hidden, or All.
Animation Scale
Query about animated scale
bool animatesScale ()
bool animatesUniformScale ()
bool animatesAlignedScale ()
bool animatesArbitraryScale ()
bool scaleCurrentlyAnimated ()
Ground Transforms
The animator of a model can make the bounding box animate along with the object.
Doing so will move the object with the bounding box. The ground transform turns the world bounding box into the post-animation bounding box when such a technique is used. However, few models actually use this technique.
void animateGround ()
clears previous ground transform
MatrixF & getGroundTransform ()
void deltaGround (TSThread *, F32 start, F32 end, MatrixF *mat=NULL)
void deltaGround1 (TSThread *, F32 start, F32 end, MatrixF &mat)
Thread Control
Threads! In order to animate an object, first you need to have an animation in the object.
Then, you need to get the TSShape of the object:
TSShape* shape = mShapeInstance->getShape());
Next, get the sequence and store::
S32 seq = shape->findSequence("foo"));
Create a new thread (if needed):
TSThread* thread = mShapeInstance->addThread();
Finally, set the position in the sequence:
mShapeInstance->setSequence(thread, seq, 0)
TSThread * addThread ()
Create a new thread.
TSThread * getThread (S32 threadNumber)
void destroyThread (TSThread *thread)
Destroy a thread!
U32 threadCount ()
How many threads are there?
void setSequence (TSThread *, S32 seq, F32 pos)
Get the thread a sequence.
void transitionToSequence (TSThread *, S32 seq, F32 pos, F32 duration, bool continuePlay)
Transition to a sequence.
void clearTransition (TSThread *)
Stop transitions.
U32 getSequence (TSThread *)
Get the sequence of the thread.
void setBlendEnabled (TSThread *, bool blendOn)
Set whether or not the thread will blend.
bool getBlendEnabled (TSThread *)
Does this thread blend?
void setPriority (TSThread *, F32 priority)
Set thread priority.
F32 getPriority (TSThread *thread)
Get thread priority.
F32 getTime (TSThread *thread)
Get how long the thread has been playing.
F32 getPos (TSThread *thread)
Get the position in the thread.
void setTime (TSThread *thread, F32 time)
Set how long into the thread to use.
void setPos (TSThread *thread, F32 pos)
Set the position of the thread.
bool isInTransition (TSThread *thread)
Is this thread in transition?
F32 getTimeScale (TSThread *thread)
Get the time scale of the thread.
void setTimeScale (TSThread *thread, F32)
Set the time scale of the thread.
F32 getDuration (TSThread *thread)
Get the duration of the thread.
F32 getScaledDuration (TSThread *thread)
Get the duration of the thread with the scale factored in.
S32 getKeyframeCount (TSThread *thread)
Get the number of keyframes.
S32 getKeyframeNumber (TSThread *thread)
Get which keyframe the thread is on.
void setKeyframeNumber (TSThread *thread, S32 kf)
Set which keyframe the thread is on.
void advanceTime (F32 delta, TSThread *)
advance time on a particular thread
void advanceTime (F32 delta)
advance time on all threads
void advancePos (F32 delta, TSThread *)
advance pos on a particular thread
void advancePos (F32 delta)
advance pos on all threads
Public Attributes
void * mData
available for use by app...initialized to 0
U32 * mDirtyFlags
TSMaterialList * mMaterialList
by default, points to hShape material list
Vector< MeshObjectInstance > mMeshObjects
Vector< MatrixF > mNodeTransforms
storage space for node transforms
Reference Transform Vectors
unused until first transition
Vector< Quat16 > mNodeReferenceRotations
Vector< Point3F > mNodeReferenceTranslations
Vector< F32 > mNodeReferenceUniformScales
Vector< Point3F > mNodeReferenceScaleFactors
Vector< Quat16 > mNodeReferenceArbitraryScaleRots
Static Public Attributes
static F32 smDetailAdjust
Scale pixel size by this amount when selecting detail levels.
static F32 smLastPixelSize
static F32 smLastScaledDistance
static F32 smLastScreenErrorTolerance
For debugging / metrics.
static S32 smNumSkipRenderDetails
never choose detail level number below this value (except if only way to get a visible detail)
static F32 smSmallestVisiblePixelSize
If this is set to a positive pixel value shapes with a smaller pixel size than this will skip rendering entirely.
Workspace for Node Transforms
static Vector< QuatF > smNodeCurrentRotations
static Vector< Point3F > smNodeCurrentTranslations
static Vector< F32 > smNodeCurrentUniformScales
static Vector< Point3F > smNodeCurrentAlignedScales
static Vector< TSScale > smNodeCurrentArbitraryScales
static Vector< MatrixF > smNodeLocalTransforms
static TSIntegerSet smNodeLocalTransformDirty
Threads
keep track of who controls what on currently animating shape
static Vector< TSThread * > smRotationThreads
static Vector< TSThread * > smTranslationThreads
static Vector< TSThread * > smScaleThreads
Protected Member Functions
void addPath (TSThread *gt, F32 start, F32 end, MatrixF *mat=NULL)
bool initGround ()
Protected Attributes
U32 debrisRefCount
bool mAlphaAlways
F32 mAlphaAlwaysValue
TSIntegerSet mCallbackNodes
S32 mCurrentDetailLevel
F32 mCurrentIntraDetailLevel
0-1, how far along from current to next (higher) detail level...
TSIntegerSet mDisableBlendNodes
TSIntegerSet mHandsOffNodes
Nodes that aren't animated through threads automatically.
TSIntegerSet mMaskPosXNodes
TSIntegerSet mMaskPosYNodes
TSIntegerSet mMaskPosZNodes
TSIntegerSet mMaskRotationNodes
keep track of nodes with animation restrictions put on them
Vector< TSCallbackRecord > mNodeCallbacks
bool mOwnMaterialList
Does this own the material list pointer?
bool mScaleCurrentlyAnimated
TSShape * mShape
This should always point to a valid shape and should equal mShapeResource if it was created from a resource.
Resource< TSShape > mShapeResource
This is only valid when the instance was created from a resource.
TSVertexBufferHandle mSoftwareVertexBuffer
Vertex buffer used for software skinning this instance.
Vector< TSThread * > mThreadList
Vector< TSThread * > mTransitionThreads
U32 mTriggerStates
state variables
bool mUseOverrideTexture
bool mUseOwnBuffer
Force using our own copy of the vertex buffer.
Ground Transform Data
MatrixF mGroundTransform
TSThread * mGroundThread
Transition nodes
keep track of nodes that are involved in a transition
Note
this only tracks nodes we're transitioning from... nodes we're transitioning to are implicitly handled (i.e., we don't need to keep track of them)
TSIntegerSet mTransitionRotationNodes
TSIntegerSet mTransitionTranslationNodes
TSIntegerSet mTransitionScaleNodes
Detailed Description
An instance of a 3space shape.
Introduction
A 3space model represents a significant amount of data. There are multiple meshes, skeleton information, as well as animation data. Some of this, like the skeletal transforms, are unique for each instance of the model (as different instances are likely to be in different states of animation), while most of it, like texturing information and vertex data, is the same amongst all instances of the shape.
To keep this data from being replicated for every instance of a 3shape object, Torque uses the ResManager to instantiate and track TSShape objects. TSShape handles reading and writing 3space models, as well as keeping track of static model data, as discussed above. TSShapeInstance keeps track of all instance specific data, such as the currently playing sequences or the active node transforms.
TSShapeInstance contains all the functionality for 3space models, while TSShape acts as a repository for common data.
What Does TSShapeInstance Do?
TSShapeInstance handles several areas of functionality:
Collision.
Rendering.
Animation.
Updating skeletal transforms.
Ballooning (see setShapeBalloon() and getShapeBalloon())
For an excellent example of how to render a TSShape in game, see TSStatic. For examples of how to procedurally animate models, look at Player::updateLookAnimation().
Member Enumeration Documentation
anonymous enum
Enumerator
MaskNodeRotation
MaskNodePosX
MaskNodePosY
MaskNodePosZ
MaskNodeBlend
MaskNodeAll
MaskNodeAllButBlend
MaskNodeAllButRotation
MaskNodeAllButPosX
MaskNodeAllButPosY
MaskNodeAllButPosZ
MaskNodeHandsOff
meaning, don't even set to default, programmer controls it (blend still applies)
MaskNodeCallback
meaning, get local transform via callback function (see setCallback) callback data2 is node index, callback return value is pointer to local transform Note: won't get this callback everytime you animate...application responsibility to make sure matrix pointer continues to point to valid and updated local transform
anonymous enum
Enumerator
TransformDirty
VisDirty
FrameDirty
MatFrameDirty
ThreadDirty
AllDirtyMask
Constructor & Destructor Documentation
TSShapeInstance::TSShapeInstance (const Resource< TSShape > & shape, bool loadMaterials = true)
TSShapeInstance::TSShapeInstance (TSShape * pShape, bool loadMaterials = true)
TSShapeInstance::~TSShapeInstance ()
Member Function Documentation
void TSShapeInstance::addPath (TSThread * gt, F32 start, F32 end, MatrixF * mat = NULL) protected
TSThread* TSShapeInstance::addThread ()
Create a new thread.
void TSShapeInstance::advancePos (F32 delta, TSThread *)
advance pos on a particular thread
void TSShapeInstance::advancePos (F32 delta)
advance pos on all threads
void TSShapeInstance::advanceTime (F32 delta, TSThread *)
advance time on a particular thread
void TSShapeInstance::advanceTime (F32 delta)
advance time on all threads
void TSShapeInstance::animate () inline
References animate().
Referenced by animate().
void TSShapeInstance::animate (S32 dl)
void TSShapeInstance::animateFrame (S32 ss)
void TSShapeInstance::animateGround ()
clears previous ground transform
void TSShapeInstance::animateMatFrame (S32 ss)
void TSShapeInstance::animateNodes (S32 ss)
void TSShapeInstance::animateNodeSubtrees (bool forceFull = true)
bool TSShapeInstance::animatesAlignedScale () inline
References TSShape::AlignedScale, and TSShape::mFlags.
bool TSShapeInstance::animatesArbitraryScale () inline
References TSShape::ArbitraryScale, and TSShape::mFlags.
bool TSShapeInstance::animatesScale () inline
References TSShape::AnyScale, and TSShape::mFlags.
void TSShapeInstance::animateSubtrees (bool forceFull = true)
bool TSShapeInstance::animatesUniformScale () inline
References TSShape::mFlags, and TSShape::UniformScale.
void TSShapeInstance::animateVisibility (S32 ss)
bool TSShapeInstance::bufferNeedsUpdate (S32 objectDetail, S32 start, S32 end)
bool TSShapeInstance::buildConvexOpcode (const MatrixF & objMat, const Point3F & objScale, S32 objectDetail, const Box3F & bounds, Convex * c, Convex * list)
void TSShapeInstance::buildInstanceData (TSShape * , bool loadMaterials)
bool TSShapeInstance::buildPolyList (AbstractPolyList * , S32 dl)
bool TSShapeInstance::buildPolyListOpcode (S32 dl, AbstractPolyList * polyList, const Box3F & box)
bool TSShapeInstance::castRay (const Point3F & start, const Point3F & end, RayInfo * , S32 dl)
bool TSShapeInstance::castRayOpcode (S32 objectDetail, const Point3F & start, const Point3F & end, RayInfo *)
bool TSShapeInstance::castRayRendered (const Point3F & start, const Point3F & end, RayInfo * , S32 dl)
void TSShapeInstance::clearDirty (U32 dirty)
void TSShapeInstance::clearTransition (TSThread *)
Stop transitions.
void TSShapeInstance::cloneMaterialList (const FeatureSet * features = NULL)
Call this to own the material list – i.e., we'll make a copy of the currently set material list and be responsible for deleting it.
You can pass an optional feature set for initializing the cloned materials.
void TSShapeInstance::computeBounds (S32 dl, Box3F & bounds)
uses current transforms to compute bounding box around a detail level see like named method on shape if you want to use default transforms
void TSShapeInstance::decDebrisRefCount () inline
void TSShapeInstance::deltaGround (TSThread * , F32 start, F32 end, MatrixF * mat = NULL)
void TSShapeInstance::deltaGround1 (TSThread * , F32 start, F32 end, MatrixF & mat)
void TSShapeInstance::destroyThread (TSThread * thread)
Destroy a thread!
void TSShapeInstance::dump (Stream &)
void TSShapeInstance::dumpNode (Stream & , S32 level, S32 nodeIndex, Vector< S32 > & detailSizes)
bool TSShapeInstance::getAlphaAlways () const inline
F32 TSShapeInstance::getAlphaAlwaysValue () const inline
bool TSShapeInstance::getBlendEnabled (TSThread *)
Does this thread blend?
S32 TSShapeInstance::getCurrentDetail () const inline
F32 TSShapeInstance::getCurrentIntraDetail () const inline
U32 TSShapeInstance::getDebrisRefCount () const inline
F32 TSShapeInstance::getDuration (TSThread * thread)
Get the duration of the thread.
bool TSShapeInstance::getFeatures (const MatrixF & mat, const Point3F & n, ConvexFeature * , S32 dl)
MatrixF& TSShapeInstance::getGroundTransform () inline
S32 TSShapeInstance::getKeyframeCount (TSThread * thread)
Get the number of keyframes.
S32 TSShapeInstance::getKeyframeNumber (TSThread * thread)
Get which keyframe the thread is on.
TSMaterialList* TSShapeInstance::getMaterialList () const inline
U32 TSShapeInstance::getNodeAnimationState (S32 nodeIndex)
U32 TSShapeInstance::getNumDetails () const inline
References TSShape::details.
F32 TSShapeInstance::getPos (TSThread * thread)
Get the position in the thread.
F32 TSShapeInstance::getPriority (TSThread * thread)
Get thread priority.
F32 TSShapeInstance::getScaledDuration (TSThread * thread)
Get the duration of the thread with the scale factored in.
U32 TSShapeInstance::getSequence (TSThread *)
Get the sequence of the thread.
TSShape* TSShapeInstance::getShape (void) const inline
Referenced by TSPartInstance::getNumDetails(), fxShapeReplicatedStatic::getShape(), and TSPartInstance::getShape().
S32 TSShapeInstance::getTargetCount () const inline
Get the number of material targets in this shape instance.
const String& TSShapeInstance::getTargetName (S32 mapToNameIndex) const inline
Get the indexed material target (may differ from the base TSShape material list if this instance has been reskinned).
References String::EmptyString.
TSThread* TSShapeInstance::getThread (S32 threadNumber)
Note
threads can change order, best to hold onto a thread from the start
F32 TSShapeInstance::getTime (TSThread * thread)
Get how long the thread has been playing.
F32 TSShapeInstance::getTimeScale (TSThread * thread)
Get the time scale of the thread.
bool TSShapeInstance::getTriggerState (U32 stateNum, bool clearState = true)
bool TSShapeInstance::hasAccumulation ()
void TSShapeInstance::incDebrisRefCount () inline
bool TSShapeInstance::initGround () protected
void TSShapeInstance::initMaterialList (const FeatureSet * features = NULL)
Initializes or re-initializes the material list with an optional feature set.
void TSShapeInstance::initMeshObjects ()
void TSShapeInstance::initNodeTransforms ()
bool TSShapeInstance::inTransition () inline
References Vector< T >::empty().
bool TSShapeInstance::isInTransition (TSThread * thread)
Is this thread in transition?
void TSShapeInstance::listMeshes (const String & state) const
Print mesh data to the console, valid String parameters are Visible, Hidden, or All.
bool TSShapeInstance::ownMaterialList () const inline
void TSShapeInstance::prepCollision ()
bool TSShapeInstance::quickLOS (const Point3F & start, const Point3F & end, S32 dl) inline
void TSShapeInstance::render (const TSRenderState & rdata)
void TSShapeInstance::render (const TSRenderState & rdata, S32 dl, F32 intraDL = 0.0f)
void TSShapeInstance::renderDebugNodes ()
Render all node transforms as small axis gizmos.
It is recommended that prior to calling this, shapeInstance::animate is called so that nodes are in object space and that the GFX state is setup for rendering in model space.
void TSShapeInstance::renderDebugNormals (F32 normalScalar, S32 dl)
Debugging.
Renders the vertex normals assuming the GFX state is setup for rendering in model space.
void TSShapeInstance::reSkin (String newBaseName, String oldBaseName = String::EmptyString)
bool TSShapeInstance::scaleCurrentlyAnimated () inline
void TSShapeInstance::setAlphaAlways (F32 value) inline
void TSShapeInstance::setBlendEnabled (TSThread * , bool blendOn)
Set whether or not the thread will blend.
void TSShapeInstance::setCurrentDetail (S32 dl, F32 intraDL = 1.0f)
S32 TSShapeInstance::setDetailFromDistance (const SceneRenderState * state, F32 scaledDist)
Selects the current detail level using the scaled distance between your object and the camera.
See also
TSShape::Detail.
S32 TSShapeInstance::setDetailFromPosAndScale (const SceneRenderState * state, const Point3F & pos, const Point3F & scale)
Helper function which internally calls setDetailFromDistance.
S32 TSShapeInstance::setDetailFromScreenError (F32 errorTOL)
Sets the current detail level using the legacy screen error metric.
void TSShapeInstance::setDirty (U32 dirty)
void TSShapeInstance::setKeyframeNumber (TSThread * thread, S32 kf)
Set which keyframe the thread is on.
void TSShapeInstance::setMaterialList (TSMaterialList * matList)
Set the material list without taking ownership.
See also
cloneMaterialList
void TSShapeInstance::setMeshForceHidden (const char * meshName, bool hidden)
Sets the 'forceHidden' state on the named mesh.
See also
MeshObjectInstance::forceHidden
void TSShapeInstance::setMeshForceHidden (S32 meshIndex, bool hidden)
Sets the 'forceHidden' state on a mesh.
See also
MeshObjectInstance::forceHidden
void TSShapeInstance::setNodeAnimationState (S32 nodeIndex, U32 animationState, TSCallback * callback = NULL)
void TSShapeInstance::setPos (TSThread * thread, F32 pos)
Set the position of the thread.
void TSShapeInstance::setPriority (TSThread * , F32 priority)
Set thread priority.
void TSShapeInstance::setSequence (TSThread * , S32 seq, F32 pos)
Get the thread a sequence.
void TSShapeInstance::setTime (TSThread * thread, F32 time)
Set how long into the thread to use.
void TSShapeInstance::setTimeScale (TSThread * thread, F32)
Set the time scale of the thread.
void TSShapeInstance::setTriggerState (U32 stateNum, bool on)
void TSShapeInstance::setTriggerStateBit (U32 stateBit, bool on)
void TSShapeInstance::setUseOwnBuffer ()
Point3F TSShapeInstance::support (const Point3F & v, S32 dl)
U32 TSShapeInstance::threadCount ()
How many threads are there?
void TSShapeInstance::transitionToSequence (TSThread * , S32 seq, F32 pos, F32 duration, bool continuePlay)
Transition to a sequence.
Member Data Documentation
U32 TSShapeInstance::debrisRefCount protected
bool TSShapeInstance::mAlphaAlways protected
F32 TSShapeInstance::mAlphaAlwaysValue protected
TSIntegerSet TSShapeInstance::mCallbackNodes protected
S32 TSShapeInstance::mCurrentDetailLevel protected
F32 TSShapeInstance::mCurrentIntraDetailLevel protected
0-1, how far along from current to next (higher) detail level...
0=at this dl, 1=at higher detail level, where higher means bigger size on screen for dl=0, we use twice detail level 0's size as the size of the "next" dl
void* TSShapeInstance::mData
available for use by app...initialized to 0
U32* TSShapeInstance::mDirtyFlags
TSIntegerSet TSShapeInstance::mDisableBlendNodes protected
TSThread* TSShapeInstance::mGroundThread protected
MatrixF TSShapeInstance::mGroundTransform protected
TSIntegerSet TSShapeInstance::mHandsOffNodes protected
Nodes that aren't animated through threads automatically.
TSIntegerSet TSShapeInstance::mMaskPosXNodes protected
TSIntegerSet TSShapeInstance::mMaskPosYNodes protected
TSIntegerSet TSShapeInstance::mMaskPosZNodes protected
TSIntegerSet TSShapeInstance::mMaskRotationNodes protected
keep track of nodes with animation restrictions put on them
TSMaterialList* TSShapeInstance::mMaterialList
by default, points to hShape material list
Vector<MeshObjectInstance> TSShapeInstance::mMeshObjects
Vector<TSCallbackRecord> TSShapeInstance::mNodeCallbacks protected
Vector<Quat16> TSShapeInstance::mNodeReferenceArbitraryScaleRots
Vector<Quat16> TSShapeInstance::mNodeReferenceRotations
Vector<Point3F> TSShapeInstance::mNodeReferenceScaleFactors
Vector<Point3F> TSShapeInstance::mNodeReferenceTranslations
Vector<F32> TSShapeInstance::mNodeReferenceUniformScales
Vector<MatrixF> TSShapeInstance::mNodeTransforms
storage space for node transforms
bool TSShapeInstance::mOwnMaterialList protected
Does this own the material list pointer?
bool TSShapeInstance::mScaleCurrentlyAnimated protected
TSShape* TSShapeInstance::mShape protected
This should always point to a valid shape and should equal mShapeResource if it was created from a resource.
Referenced by TSThread::getSequence(), and TSThread::getSequenceName().
Resource<TSShape> TSShapeInstance::mShapeResource protected
This is only valid when the instance was created from a resource.
Else it is null.
TSVertexBufferHandle TSShapeInstance::mSoftwareVertexBuffer protected
Vertex buffer used for software skinning this instance.
Vector<TSThread*> TSShapeInstance::mThreadList protected
TSIntegerSet TSShapeInstance::mTransitionRotationNodes protected
TSIntegerSet TSShapeInstance::mTransitionScaleNodes protected
Vector<TSThread*> TSShapeInstance::mTransitionThreads protected
TSIntegerSet TSShapeInstance::mTransitionTranslationNodes protected
U32 TSShapeInstance::mTriggerStates protected
state variables
bool TSShapeInstance::mUseOverrideTexture protected
bool TSShapeInstance::mUseOwnBuffer protected
Force using our own copy of the vertex buffer.
F32 TSShapeInstance::smDetailAdjust static
Scale pixel size by this amount when selecting detail levels.
F32 TSShapeInstance::smLastPixelSize static
F32 TSShapeInstance::smLastScaledDistance static
F32 TSShapeInstance::smLastScreenErrorTolerance static
For debugging / metrics.
Vector<Point3F> TSShapeInstance::smNodeCurrentAlignedScales static
Vector<TSScale> TSShapeInstance::smNodeCurrentArbitraryScales static
Vector<QuatF> TSShapeInstance::smNodeCurrentRotations static
Vector<Point3F> TSShapeInstance::smNodeCurrentTranslations static
Vector<F32> TSShapeInstance::smNodeCurrentUniformScales static
TSIntegerSet TSShapeInstance::smNodeLocalTransformDirty static
Vector<MatrixF> TSShapeInstance::smNodeLocalTransforms static
S32 TSShapeInstance::smNumSkipRenderDetails static
never choose detail level number below this value (except if only way to get a visible detail)
Vector<TSThread*> TSShapeInstance::smRotationThreads static
Vector<TSThread*> TSShapeInstance::smScaleThreads static
F32 TSShapeInstance::smSmallestVisiblePixelSize static
If this is set to a positive pixel value shapes with a smaller pixel size than this will skip rendering entirely.
Vector<TSThread*> TSShapeInstance::smTranslationThreads static
Copyright © GarageGames, LLC. All Rights Reserved.