WindEmitter Class Reference
Main Modules Class List Namespace List Online
WindEmitter Class Reference
#include <T3D/fx/windEmitter.h>
Public Member Functions
WindEmitter ()
~WindEmitter ()
const Point3F & getCenter () const
F32 getRadius () const
F32 getStrength () const
F32 getTurbulenceFrequency () const
F32 getTurbulenceStrength () const
const VectorF & getVelocity () const
operator const SphereF & () const
void setPosition (const Point3F &pos)
void setRadius (F32 radius)
void setStrength (F32 strength)
void setTurbulency (F32 frequency, F32 strength)
void update (const Point3F &pos, const VectorF &velocity)
Static Public Member Functions
static bool findBest (const Point3F &cameraPos, const VectorF &cameraDir, F32 viewDistance, U32 maxResults, WindEmitterList *results)
Static Protected Member Functions
static S32 QSORT_CALLBACK _sortByScore (const void *a, const void *b)
Protected Attributes
bool mEnabled
F32 mScore
SphereF mSphere
F32 mStrength
F32 mTurbulenceFrequency
F32 mTurbulenceStrength
VectorF mVelocity
Static Protected Attributes
static WindEmitterList smAllEmitters
Constructor & Destructor Documentation
WindEmitter::WindEmitter ()
WindEmitter::~WindEmitter ()
Member Function Documentation
static S32 QSORT_CALLBACK WindEmitter::_sortByScore (const void * a, const void * b) static protected
static bool WindEmitter::findBest (const Point3F & cameraPos, const VectorF & cameraDir, F32 viewDistance, U32 maxResults, WindEmitterList * results) static
Referenced by getVelocity().
const Point3F& WindEmitter::getCenter () const inline
References SphereF::center, and mSphere.
F32 WindEmitter::getRadius () const inline
References mSphere, and SphereF::radius.
F32 WindEmitter::getStrength () const inline
References mStrength.
F32 WindEmitter::getTurbulenceFrequency () const inline
References mTurbulenceFrequency.
F32 WindEmitter::getTurbulenceStrength () const inline
References mTurbulenceStrength.
const VectorF& WindEmitter::getVelocity () const inline
References findBest(), and mVelocity.
WindEmitter::operator const SphereF & () const inline
References mSphere, setPosition(), setRadius(), setStrength(), setTurbulency(), and update().
void WindEmitter::setPosition (const Point3F & pos)
Referenced by operator const SphereF &().
void WindEmitter::setRadius (F32 radius)
Referenced by operator const SphereF &().
void WindEmitter::setStrength (F32 strength)
Referenced by operator const SphereF &().
void WindEmitter::setTurbulency (F32 frequency, F32 strength)
Referenced by operator const SphereF &().
void WindEmitter::update (const Point3F & pos, const VectorF & velocity)
Referenced by operator const SphereF &().
Member Data Documentation
bool WindEmitter::mEnabled protected
F32 WindEmitter::mScore protected
SphereF WindEmitter::mSphere protected
Referenced by getCenter(), getRadius(), and operator const SphereF &().
F32 WindEmitter::mStrength protected
Referenced by getStrength().
F32 WindEmitter::mTurbulenceFrequency protected
Referenced by getTurbulenceFrequency().
F32 WindEmitter::mTurbulenceStrength protected
Referenced by getTurbulenceStrength().
VectorF WindEmitter::mVelocity protected
Referenced by getVelocity().
WindEmitterList WindEmitter::smAllEmitters static protected
Copyright © GarageGames, LLC. All Rights Reserved.