GenericTimeSource< Timer, Tick > Class Template Reference
Main Modules Class List Namespace List Online
GenericTimeSource< Timer, Tick > Class Template Reference
#include <core/util/timeSource.h>
Public Types
typedef IPositionable< Tick > Parent
typedef Tick TickType
Public Types inherited from IPositionable< Tick >
typedef void Parent
typedef Tick PositionType
The type used to indicate positions.
Public Types inherited from IProcess
typedef void Parent
Public Types inherited from IResettable
typedef void Parent
Public Member Functions
GenericTimeSource ()
TickType getPosition () const
Return the number of ticks since the time source has been started.
bool isPaused () const
bool isStarted () const
virtual void pause ()
Pause the process.
virtual void reset ()
Reset to the initial state.
void setPosition (TickType pos)
Set the current position to be "pos".
virtual void start ()
Start the process.
virtual void stop ()
Stop the process.
Protected Attributes
TickType mPauseTime
TickType mStartTime
Timer mTimer
Member Typedef Documentation
template<class Timer = RealMSTimer, typename Tick = typename Timer::TickType> typedef IPositionable< Tick > GenericTimeSource< Timer, Tick >::Parent
template<class Timer = RealMSTimer, typename Tick = typename Timer::TickType> typedef Tick GenericTimeSource< Timer, Tick >::TickType
Constructor & Destructor Documentation
template<class Timer = RealMSTimer, typename Tick = typename Timer::TickType> GenericTimeSource< Timer, Tick >::GenericTimeSource () inline
Member Function Documentation
template<class Timer = RealMSTimer, typename Tick = typename Timer::TickType> TickType GenericTimeSource< Timer, Tick >::getPosition () const inline virtual
Return the number of ticks since the time source has been started.
Implements IPositionable< Tick >.
Referenced by SFXNullVoice::_getPlayTime(), InterpolatedChangeProperty< T, TimeSource >::_update(), and InterpolatedChangeProperty< T, TimeSource >::setTargetValue().
template<class Timer = RealMSTimer, typename Tick = typename Timer::TickType> bool GenericTimeSource< Timer, Tick >::isPaused () const inline
template<class Timer = RealMSTimer, typename Tick = typename Timer::TickType> bool GenericTimeSource< Timer, Tick >::isStarted () const inline
template<class Timer = RealMSTimer, typename Tick = typename Timer::TickType> virtual void GenericTimeSource< Timer, Tick >::pause () inline virtual
Pause the process.
Implements IProcess.
template<class Timer = RealMSTimer, typename Tick = typename Timer::TickType> virtual void GenericTimeSource< Timer, Tick >::reset () inline virtual
Reset to the initial state.
Implements IResettable.
template<class Timer = RealMSTimer, typename Tick = typename Timer::TickType> void GenericTimeSource< Timer, Tick >::setPosition (TickType pos) inline virtual
Set the current position to be "pos".
Parameters
pos The new position.
Implements IPositionable< Tick >.
template<class Timer = RealMSTimer, typename Tick = typename Timer::TickType> virtual void GenericTimeSource< Timer, Tick >::start () inline virtual
Start the process.
Implements IProcess.
Referenced by InterpolatedChangeProperty< ColorF >::InterpolatedChangeProperty().
template<class Timer = RealMSTimer, typename Tick = typename Timer::TickType> virtual void GenericTimeSource< Timer, Tick >::stop () inline virtual
Stop the process.
Implements IProcess.
Member Data Documentation
template<class Timer = RealMSTimer, typename Tick = typename Timer::TickType> TickType GenericTimeSource< Timer, Tick >::mPauseTime protected
template<class Timer = RealMSTimer, typename Tick = typename Timer::TickType> TickType GenericTimeSource< Timer, Tick >::mStartTime protected
template<class Timer = RealMSTimer, typename Tick = typename Timer::TickType> Timer GenericTimeSource< Timer, Tick >::mTimer protected
Copyright © GarageGames, LLC. All Rights Reserved.