SFXMemoryStream Class Reference
Main Modules Class List Namespace List Online
SFXMemoryStream Class Reference
A stream filter that converts sample packets from its source stream to a continuous sample stream.
#include <sfx/sfxMemoryStream.h>
Public Types
typedef SFXStream Parent
Public Types inherited from SFXStream
typedef void Parent
Public Types inherited from ThreadSafeRefCount< SFXStream >
typedef void Parent
Public Types inherited from IResettable
typedef void Parent
Public Types inherited from IInputStreamFilter< U8, IInputStream< RawData * > * >
typedef IInputStream< U8 > Parent
typedef SourceStreamType::ElementType SourceElementType
The element type of the source stream.
typedef TypeTraits< IInputStream< RawData * > * >::BaseType SourceStreamType
Public Member Functions
SFXMemoryStream (const SFXFormat &format, SourceStreamType *stream, U32 numSamples=U32_MAX)
U32 getDataLength () const
The data size in bytes of the decompressed PCM data.
U32 getDuration () const
The length of the sound in milliseconds.
const SFXFormat & getFormat () const
The format of the data in the stream.
U32 getSampleCount () const
The number of samples in the data stream.
bool isEOS () const
Returns true if we've reached the end of the stream.
U32 read (U8 *buffer, U32 length)
Reads data from the stream and decompresses it into PCM samples.
void reset ()
Resets the stream to restart reading data from the begining.
Public Member Functions inherited from SFXStream
virtual ~SFXStream ()
Destructor.
virtual SFXStream * clone () const
Make a copy of this stream with its own private state, so new independent read() operations can be issued on the same data stream.
Public Member Functions inherited from ThreadSafeRefCount< SFXStream >
ThreadSafeRefCount ()
ThreadSafeRefCount (bool noSet)
void addRef ()
Increase the reference count on the object.
void clearLowestBit ()
U32 getRefCount () const
Get the current reference count.
bool isShared () const
void release ()
Decrease the object's reference count and delete the object, if the count drops to zero and claiming the object by the current thread succeeds.
Public Member Functions inherited from IInputStreamFilter< U8, IInputStream< RawData * > * >
IInputStreamFilter (const IInputStream< RawData * > * &stream)
Construct a filter reading elements from "stream".
const IInputStream< RawData * > * & getSourceStream () const
Return the stream from which this filter is reading its source elements.
IInputStream< RawData * > * & getSourceStream ()
Protected Attributes
RawData * mCurrentPacket
The current sample data packet.
U32 mCurrentPacketOffset
Read offset in the current sample data packet.
SFXFormat mFormat
U32 mNumSamplesLeft
Number of samples left to be read from stream.
U32 mNumSamplesTotal
Total number of samples in the stream.
Protected Attributes inherited from ThreadSafeRefCount< SFXStream >
U32 mRefCount
Reference count and claim bit. Note that this increments in steps of two.
Additional Inherited Members
Static Public Member Functions inherited from ThreadSafeRefCount< SFXStream >
static SFXStream * safeRead (SFXStream *const volatile &refPtr)
Dereference a reference-counted pointer in a multi-thread safe way.
Static Protected Member Functions inherited from ThreadSafeRefCount< SFXStream >
static U32 decrementAndTestAndSet (U32 &refCount)
Decrement the given reference count.
Detailed Description
A stream filter that converts sample packets from its source stream to a continuous sample stream.
Useful for feeding sound from a source that pushes sample data in discrete packets.
Note
For the SFXMemoryStream to allow a reset(), the source input stream must implement IResettable.
Member Typedef Documentation
typedef SFXStream SFXMemoryStream::Parent
Constructor & Destructor Documentation
SFXMemoryStream::SFXMemoryStream (const SFXFormat & format, SourceStreamType * stream, U32 numSamples = U32_MAX)
Member Function Documentation
U32 SFXMemoryStream::getDataLength () const inline virtual
The data size in bytes of the decompressed PCM data.
Implements SFXStream.
References SFXFormat::getDataLength(), and getDuration().
U32 SFXMemoryStream::getDuration () const inline virtual
The length of the sound in milliseconds.
Implements SFXStream.
References SFXFormat::getDuration().
Referenced by getDataLength().
const SFXFormat& SFXMemoryStream::getFormat () const inline virtual
The format of the data in the stream.
Implements SFXStream.
References mFormat.
U32 SFXMemoryStream::getSampleCount () const inline virtual
The number of samples in the data stream.
Implements SFXStream.
References mNumSamplesTotal.
bool SFXMemoryStream::isEOS () const inline virtual
Returns true if we've reached the end of the stream.
Implements SFXStream.
References read(), and reset().
U32 SFXMemoryStream::read (U8 * buffer, U32 length) virtual
Reads data from the stream and decompresses it into PCM samples.
Parameters
length Number of bytes to read.
Implements SFXStream.
Referenced by isEOS().
void SFXMemoryStream::reset () virtual
Resets the stream to restart reading data from the begining.
Implements SFXStream.
Referenced by isEOS().
Member Data Documentation
RawData* SFXMemoryStream::mCurrentPacket protected
The current sample data packet.
U32 SFXMemoryStream::mCurrentPacketOffset protected
Read offset in the current sample data packet.
SFXFormat SFXMemoryStream::mFormat protected
Referenced by getFormat().
U32 SFXMemoryStream::mNumSamplesLeft protected
Number of samples left to be read from stream.
Locked to U32_MAX for stream of indefinite size.
U32 SFXMemoryStream::mNumSamplesTotal protected
Total number of samples in the stream.
If this is U32_MAX, the stream is considered to be of indefinite size.
Referenced by getSampleCount().
Copyright © GarageGames, LLC. All Rights Reserved.