GFXGLCardProfiler Class Reference
Main Modules Class List Namespace List Online
GFXGLCardProfiler Class Reference
A note on workarounds - The following settings are used exclusively to work around driver bugs: GL::Workaround::needsExplicitGenerateMipmap GL::Workaround::X1600DepthBufferCopy GL::Workaround::HD2600DepthBufferCopy If you find that you need to work around additional driver bugs, add a new setting of the form GL::Workaround::<name> and set it to false in GFXGLCardProfiler::setupCardCapabilities() Enclose your workaround code in if(GFX->getCardProfiler()->queryProfile("GL::Workaround::<name>")) { <workaround> } Remember to set the work around to true in the card profile script!
#include <gfx/gl/gfxGLCardProfiler.h>
Public Member Functions
void init ()
Set load script files and generally initialize things.
Public Member Functions inherited from GFXCardProfiler
GFXCardProfiler ()
Called for a profile for a given device.
virtual ~GFXCardProfiler ()
U32 queryProfile (const String &cap)
Called to query a capability.
U32 queryProfile (const String &cap, U32 defaultValue)
Same as queryProfile(), but a default can be specified to indicate what value should be returned if the profiler doesn't know anything about it.
void setCapability (const String &cap, U32 value)
Set the specified capability to the specified value.
bool checkFormat (const GFXFormat fmt, const GFXTextureProfile *profile, bool &inOutAutogenMips)
Queries support for the specified texture format, and texture profile.
const String & getVersionString () const
const String & getCardString () const
const String & getChipString () const
U32 getVideoMemoryInMB () const
Protected Member Functions
virtual bool _queryCardCap (const String &query, U32 &foundResult)
Implementation specific query code.
virtual bool _queryFormat (const GFXFormat fmt, const GFXTextureProfile *profile, bool &inOutAutogenMips)
virtual const String & getRendererString () const
virtual void setupCardCapabilities ()
Protected Member Functions inherited from GFXCardProfiler
void loadProfileScript (const char *scriptName)
Load a specified script file from the profiles directory, if it exists.
void loadProfileScripts (const String &render, const String &vendor, const String &card, const String &version)
Load the script files in order for the specified card profile tuple.
String strippedString (const char *string)
Additional Inherited Members
Protected Attributes inherited from GFXCardProfiler
Map< String, U32 > mCapDictionary
Capability dictionary.
String mVersionString
String mCardDescription
String mChipSet
U32 mVideoMemory
Detailed Description
A note on workarounds - The following settings are used exclusively to work around driver bugs: GL::Workaround::needsExplicitGenerateMipmap GL::Workaround::X1600DepthBufferCopy GL::Workaround::HD2600DepthBufferCopy If you find that you need to work around additional driver bugs, add a new setting of the form GL::Workaround::<name> and set it to false in GFXGLCardProfiler::setupCardCapabilities() Enclose your workaround code in if(GFX->getCardProfiler()->queryProfile("GL::Workaround::<name>")) { <workaround> } Remember to set the work around to true in the card profile script!
Member Function Documentation
virtual bool GFXGLCardProfiler::_queryCardCap (const String & query, U32 & foundResult) protected virtual
Implementation specific query code.
This function is meant to be overridden by the specific implementation class.
Some query strings are handled by the external implementation while others must be done by the specific implementation. This is given first chance to return a result, then the generic rules are applied.
Parameters
query Capability being queried.
foundResult Result to return to the caller. If the function returns true then this value is returned as the result of the query.
Implements GFXCardProfiler.
Referenced by getRendererString().
virtual bool GFXGLCardProfiler::_queryFormat (const GFXFormat fmt, const GFXTextureProfile * profile, bool & inOutAutogenMips) protected virtual
Implements GFXCardProfiler.
Referenced by getRendererString().
virtual const String& GFXGLCardProfiler::getRendererString () const inline protected virtual
Implements GFXCardProfiler.
References _queryCardCap(), _queryFormat(), and setupCardCapabilities().
void GFXGLCardProfiler::init () virtual
Set load script files and generally initialize things.
Implements GFXCardProfiler.
virtual void GFXGLCardProfiler::setupCardCapabilities () protected virtual
Implements GFXCardProfiler.
Referenced by getRendererString().
Copyright © GarageGames, LLC. All Rights Reserved.