WinFont Class Reference
Main Modules Class List Namespace List Online
WinFont Class Reference
#include <platformWin32/winFont.h>
Public Member Functions
WinFont ()
virtual ~WinFont ()
virtual bool create (const char *name, dsize_t size, U32 charset=TGE_ANSI_CHARSET)
This is just for createPlatformFont to call.
virtual PlatformFont::CharInfo & getCharInfo (const UTF16 ch) const
virtual PlatformFont::CharInfo & getCharInfo (const UTF8 *str) const
virtual U32 getFontBaseLine () const
virtual U32 getFontHeight () const
virtual bool isValidChar (const UTF16 ch) const
Is the specified character valid for rendering?
virtual bool isValidChar (const UTF8 *str) const
Public Member Functions inherited from PlatformFont
virtual ~PlatformFont ()
Additional Inherited Members
Static Public Member Functions inherited from PlatformFont
static void enumeratePlatformFonts (Vector< StringTableEntry > &fonts, UTF16 *fontFamily=NULL)
Constructor & Destructor Documentation
WinFont::WinFont ()
virtual WinFont::~WinFont () virtual
Member Function Documentation
virtual bool WinFont::create (const char * name, dsize_t size, U32 charset = TGE_ANSI_CHARSET) virtual
This is just for createPlatformFont to call.
Implements PlatformFont.
Referenced by getFontBaseLine().
virtual PlatformFont::CharInfo& WinFont::getCharInfo (const UTF16 ch) const virtual
Implements PlatformFont.
Referenced by getFontBaseLine().
virtual PlatformFont::CharInfo& WinFont::getCharInfo (const UTF8 * str) const virtual
Implements PlatformFont.
virtual U32 WinFont::getFontBaseLine () const inline virtual
Implements PlatformFont.
References create(), and getCharInfo().
virtual U32 WinFont::getFontHeight () const inline virtual
Implements PlatformFont.
virtual bool WinFont::isValidChar (const UTF16 ch) const virtual
Is the specified character valid for rendering?
Implements PlatformFont.
virtual bool WinFont::isValidChar (const UTF8 * str) const virtual
Implements PlatformFont.
Copyright © GarageGames, LLC. All Rights Reserved.