ColladaPrimitive< T > Class Template Reference
Main Modules Class List Namespace List Online
ColladaPrimitive< T > Class Template Reference
Template child class for supported Collada primitive elements.
#include <ts/collada/colladaUtils.h>
Public Member Functions
ColladaPrimitive (const daeElement *e)
~ColladaPrimitive ()
const char * getElementName ()
Most primitives can use these common implementations.
const domInputLocalOffset_Array & getInputs ()
const char * getMaterial ()
S32 getStride () const
const domListOfUInts * getTriangleData ()
Each supported primitive needs to implement this method (and convert to triangles if required)
template<>
const domListOfUInts * getTriangleData ()
template<>
const domListOfUInts * getTriangleData ()
template<>
const domListOfUInts * getTriangleData ()
template<>
const domListOfUInts * getTriangleData ()
template<>
const domListOfUInts * getTriangleData ()
Public Member Functions inherited from BasePrimitive
virtual ~BasePrimitive ()
Additional Inherited Members
Static Public Member Functions inherited from BasePrimitive
static BasePrimitive * get (const daeElement *element)
Construct a child class based on the type of Collada element.
static bool isPrimitive (const daeElement *element)
Return true if the element is a geometric primitive type.
static bool isSupportedPrimitive (const daeElement *element)
Return true if the element is a supported primitive type.
Detailed Description
template<class T>
class ColladaPrimitive< T >
Template child class for supported Collada primitive elements.
Constructor & Destructor Documentation
template<class T > ColladaPrimitive< T >::ColladaPrimitive (const daeElement * e) inline
template<class T > ColladaPrimitive< T >::~ColladaPrimitive () inline
Member Function Documentation
template<class T > const char* ColladaPrimitive< T >::getElementName () inline virtual
Most primitives can use these common implementations.
Implements BasePrimitive.
template<class T > const domInputLocalOffset_Array& ColladaPrimitive< T >::getInputs () inline virtual
Implements BasePrimitive.
template<class T > const char* ColladaPrimitive< T >::getMaterial () inline virtual
Implements BasePrimitive.
template<class T > S32 ColladaPrimitive< T >::getStride () const inline virtual
Implements BasePrimitive.
template<class T > const domListOfUInts* ColladaPrimitive< T >::getTriangleData () inline virtual
Each supported primitive needs to implement this method (and convert to triangles if required)
Implements BasePrimitive.
template<> const domListOfUInts * ColladaPrimitive< domTriangles >::getTriangleData () inline virtual
Implements BasePrimitive.
template<> const domListOfUInts * ColladaPrimitive< domTristrips >::getTriangleData () inline virtual
Implements BasePrimitive.
template<> const domListOfUInts * ColladaPrimitive< domTrifans >::getTriangleData () inline virtual
Implements BasePrimitive.
template<> const domListOfUInts * ColladaPrimitive< domPolygons >::getTriangleData () inline virtual
Implements BasePrimitive.
template<> const domListOfUInts * ColladaPrimitive< domPolylist >::getTriangleData () inline virtual
Implements BasePrimitive.
References dAtob(), dAtof(), dAtoi(), T, and Con::warnf().
Copyright © GarageGames, LLC. All Rights Reserved.