ForestCellBatch Class Reference
Main Modules Class List Namespace List Online
ForestCellBatch Class Reference abstract
#include <forest/forestCellBatch.h>
Public Member Functions
ForestCellBatch ()
virtual ~ForestCellBatch ()
bool add (const ForestItem &item)
S32 getItemCount () const
const Box3F & getWorldBox () const
void render (SceneRenderState *state)
Protected Member Functions
virtual bool _prepBatch (const ForestItem &item)=0
virtual void _rebuildBatch ()=0
virtual void _render (const SceneRenderState *state)=0
Protected Attributes
Box3F mBounds
The world space bounding box of this batch.
bool mDirty
Used to detect when the batch rendering objects need to be repacked.
Vector< ForestItem > mItems
The items in the batch.
Constructor & Destructor Documentation
ForestCellBatch::ForestCellBatch ()
virtual ForestCellBatch::~ForestCellBatch () virtual
Member Function Documentation
virtual bool ForestCellBatch::_prepBatch (const ForestItem & item) protected pure virtual
Implemented in TSForestCellBatch.
virtual void ForestCellBatch::_rebuildBatch () protected pure virtual
Implemented in TSForestCellBatch.
virtual void ForestCellBatch::_render (const SceneRenderState * state) protected pure virtual
Implemented in TSForestCellBatch.
bool ForestCellBatch::add (const ForestItem & item)
S32 ForestCellBatch::getItemCount () const inline
References render(), and Vector< T >::size().
const Box3F& ForestCellBatch::getWorldBox () const inline
References mBounds.
void ForestCellBatch::render (SceneRenderState * state)
Referenced by getItemCount().
Member Data Documentation
Box3F ForestCellBatch::mBounds protected
The world space bounding box of this batch.
Referenced by getWorldBox().
bool ForestCellBatch::mDirty protected
Used to detect when the batch rendering objects need to be repacked.
Vector<ForestItem> ForestCellBatch::mItems protected
The items in the batch.
Copyright © GarageGames, LLC. All Rights Reserved.