RectI Class Reference
Main Modules Class List Namespace List Online
RectI Class Reference
#include <math/mRect.h>
Public Member Functions
RectI ()
RectI (const Point2I &in_rMin, const Point2I &in_rExtent)
RectI (const S32 in_left, const S32 in_top, const S32 in_width, const S32 in_height)
S32 area () const
Returns the area of the rectangle.
bool contains (const RectI &R) const
void inset (S32 x, S32 y)
bool intersect (const RectI &clipRect)
bool isValidRect () const
S32 len_x () const
S32 len_y () const
bool operator!= (const RectI &) const
bool operator== (const RectI &) const
bool overlaps (RectI R) const
bool pointInRect (const Point2I &pt) const
void set (const Point2I &in_rMin, const Point2I &in_rExtent)
void set (const S32 in_left, const S32 in_top, const S32 in_width, const S32 in_height)
void unionRects (const RectI &)
Public Attributes
Point2I extent
Point2I point
Static Public Attributes
static const RectI One
A rect of 1,1 extent.
static const RectI Zero
A rect of zero extent.
Constructor & Destructor Documentation
RectI::RectI () inline
References contains(), inset(), intersect(), len_x(), len_y(), overlaps(), pointInRect(), and unionRects().
RectI::RectI (const Point2I & in_rMin, const Point2I & in_rExtent) inline
RectI::RectI (const S32 in_left, const S32 in_top, const S32 in_width, const S32 in_height) inline
Member Function Documentation
S32 RectI::area () const inline
Returns the area of the rectangle.
References operator!=(), operator==(), Point2I::x, and Point2I::y.
bool RectI::contains (const RectI & R) const inline
References extent, point, Point2I::x, and Point2I::y.
Referenced by RectF::contains(), and RectI().
void RectI::inset (S32 x, S32 y) inline
References extent, point, Point2I::x, and Point2I::y.
Referenced by Edge::operator const RectI(), RectD::RectD(), RectF::RectF(), and RectI().
bool RectI::intersect (const RectI & clipRect) inline
References extent, isValidRect(), point, Point2I::x, and Point2I::y.
Referenced by overlaps(), RectD::RectD(), RectF::RectF(), and RectI().
bool RectI::isValidRect () const inline
References Point2I::x, and Point2I::y.
Referenced by intersect().
S32 RectI::len_x () const inline
References extent, and Point2I::x.
Referenced by RectF::contains(), RectD::RectD(), and RectI().
S32 RectI::len_y () const inline
References extent, and Point2I::y.
Referenced by RectF::contains(), RectD::RectD(), and RectI().
bool RectI::operator!= (const RectI & in_rCompare) const inline
Referenced by area().
bool RectI::operator== (const RectI & in_rCompare) const inline
References extent, and point.
Referenced by area().
bool RectI::overlaps (RectI R) const inline
References intersect().
Referenced by Edge::hit(), RectF::RectF(), and RectI().
bool RectI::pointInRect (const Point2I & pt) const inline
References extent, point, Point2I::x, and Point2I::y.
Referenced by RectF::RectF(), and RectI().
void RectI::set (const Point2I & in_rMin, const Point2I & in_rExtent) inline
References extent, and point.
void RectI::set (const S32 in_left, const S32 in_top, const S32 in_width, const S32 in_height) inline
References extent, point, and Point2I::set().
void RectI::unionRects (const RectI & u) inline
References extent, point, Point2I::x, and Point2I::y.
Referenced by RectF::contains(), and RectI().
Member Data Documentation
Point2I RectI::extent
Referenced by RectClipper::clipPoint(), GuiRolloutCtrl::collapse(), contains(), GuiEditCtrl::drawCrossSection(), EdgeRectI::EdgeRectI(), GuiRolloutCtrl::expand(), RectSpacingI::expandRect(), GuiControl::getExtent(), GuiControl::getHeight(), GuiControl::getWidth(), inset(), RectF::inset(), RectD::inset(), RectSpacingI::insetRect(), intersect(), len_x(), len_y(), PlatformWindow::lockSize(), operator==(), pointInRect(), set(), GuiEditCtrl::snapDelta(), and unionRects().
const RectI RectI::One static
A rect of 1,1 extent.
Point2I RectI::point
Referenced by RectClipper::clipPoint(), contains(), RectF::contains(), GuiEditCtrl::drawCrossSection(), EdgeRectI::EdgeRectI(), RectSpacingI::expandRect(), GuiControl::getGlobalBounds(), GuiControl::getLeft(), GuiControl::getPosition(), GuiControl::getTop(), inset(), RectF::inset(), RectD::inset(), RectSpacingI::insetRect(), intersect(), operator==(), pointInRect(), set(), GuiEditCtrl::snapDelta(), and unionRects().
const RectI RectI::Zero static
A rect of zero extent.
Copyright © GarageGames, LLC. All Rights Reserved.