GuiControl Class Reference
Main Modules Class List Namespace List Online
GuiControl Class Reference
Gui System » Core
#include <gui/core/guiControl.h>
Public Types
enum { NoCheckParentCanSave = BIT(31) }
Additional write flags for GuiControls.
enum horizSizingOptions {
horizResizeRight = 0,
horizResizeWidth,
horizResizeLeft,
horizResizeCenter,
horizResizeRelative,
horizResizeAspectLeft,
horizResizeAspectRight,
horizResizeAspectCenter,
horizResizeWindowRelative
}
typedef SimGroup Parent
enum vertSizingOptions {
vertResizeBottom = 0,
vertResizeHeight,
vertResizeTop,
vertResizeCenter,
vertResizeRelative,
vertResizeAspectTop,
vertResizeAspectBottom,
vertResizeAspectCenter,
vertResizeWindowRelative
}
Public Types inherited from SimGroup
typedef SimSet Parent
Public Types inherited from SimSet
typedef SimObject Parent
enum SetModification {
SetCleared,
SetObjectAdded,
SetObjectRemoved
}
typedef Signal< void(SetModification modification, SimSet *set, SimObject *object) > SetModificationSignal
Signal for letting observers know when objects are added to or removed from the set.
typedef SimObjectList::iterator iterator
typedef SimObjectList::value_type value
Public Types inherited from SimObject
typedef ConsoleObject Parent
enum WriteFlags {
SelectedOnly = BIT(0),
NoName = BIT(1),
IgnoreCanSave = BIT(2)
}
Flags passed to SimObject::write.
Public Types inherited from EngineObject
typedef void(* DebugEnumInstancesCallback) (EngineObject *)
Type of callback function for iterating over EngineObject instances.
Public Member Functions
void awaken ()
Called when this control and its children have been wired up.
U32 clipText (String &inOutText, U32 width) const
Returns text clipped to fit within a pixel width.
virtual bool controlIsChild (GuiControl *child)
Returns true if the provided control is a child (grandchild, or great-grandchild) of this one.
const char * getConsoleCommand ()
Returns the name of the function bound to this GuiControl.
GuiControlProfile * getControlProfile ()
Returns our profile (and finds the profile if it hasn't been set yet)
virtual void getCursor (GuiCursor *&cursor, bool &showCursor, const GuiEvent &lastGuiEvent)
Get information about the cursor.
LangTable * getGUILangTable (void)
const UTF8 * getGUIString (S32 id)
RenderTooltipDelegate & getRenderTooltipDelegate ()
Return the delegate used to render tooltips on this control.
const RenderTooltipDelegate & getRenderTooltipDelegate () const
virtual void getScrollLineSizes (U32 *rowHeight, U32 *columnWidth)
Get information about the size of a scroll line.
String & getTooltip ()
Returns the tooltip.
GuiControlProfile * getTooltipProfile ()
Returns our tooltip profile (and finds the profile if it hasn't been set yet)
void inspectPostApply ()
Called after any property of the object is changed in the world editor.
void inspectPreApply ()
Called before any property of the object is changed in the world editor.
virtual void onAction ()
Occurs when this control performs its "action".
virtual bool onInputEvent (const InputEventInfo &event)
General input handler.
void preRender ()
Pre-render this control and all its children.
void renderJustifiedText (Point2I offset, Point2I extent, const char *text)
Renders justified text using the profile.
void setConsoleCommand (const String &newCmd)
Set the name of the console function bound to, such as a script function a button calls when clicked.
void setConsoleVariable (const char *variable)
Set the name of the console variable which this GuiObject is bound to.
void setControlProfile (GuiControlProfile *prof)
Sets the control profile for this control.
void setTooltipProfile (GuiControlProfile *prof)
Sets the tooltip profile for this control.
void sleep ()
Called when this control is no more.
Editor
These functions are used by the GUI Editor
void setSizing (S32 horz, S32 vert)
Sets the size of the GuiControl.
void write (Stream &stream, U32 tabStop, U32 flags)
Overrides Parent Serialization to allow specific controls to not be saved (Dynamic Controls, etc)
bool getCanSaveParent ()
Returns boolean as to whether any parent of this control has the 'no serialization' flag set.
Accessors
const Point2I & getPosition () const
Returns position of the control.
const Point2I & getExtent () const
Returns extents of the control.
const RectI getBounds () const
Returns the bounds of the control.
const RectI getGlobalBounds ()
virtual Point2I getMinExtent () const
Returns minimum size the control can be.
virtual void setMinExtent (const Point2I &newMinExtent)
const S32 getLeft () const
Returns the X position of the control.
const S32 getTop () const
Returns the Y position of the control.
const S32 getWidth () const
Returns the width of the control.
const S32 getHeight () const
Returns the height of the control.
const S32 getHorizSizing () const
const S32 getVertSizing () const
Flags
virtual void setVisible (bool value)
Sets the visibility of the control.
bool isVisible () const
Returns true if the object is visible.
virtual bool isHidden () const
virtual void setHidden (bool state)
void setCanHit (bool value)
virtual void setActive (bool value)
Sets the status of this control as active and responding or inactive.
bool isActive ()
Returns true if this control is active.
bool isAwake ()
Returns true if this control is awake.
Children
void addObject (SimObject *obj)
Adds an object as a child of this object.
void removeObject (SimObject *obj)
Removes a child object from this control.
GuiControl * getParent ()
Returns the control which owns this one.
GuiCanvas * getRoot ()
Returns the root canvas of this control.
virtual bool acceptsAsChild (SimObject *object) const
Return true if this set accepts the given object as a child.
virtual void onGroupRemove ()
Called when the object is removed from a SimGroup.
Coordinates
Point2I localToGlobalCoord (const Point2I &src)
Translates local coordinates (wrt this object) into global coordinates.
Point2I globalToLocalCoord (const Point2I &src)
Returns global coordinates translated into local space.
Resizing
virtual bool resize (const Point2I &newPosition, const Point2I &newExtent)
Changes the size and/or position of this control.
virtual bool setPosition (const Point2I &newPosition)
Changes the position of this control.
void setPosition (const S32 x, const S32 y)
virtual bool setExtent (const Point2I &newExtent)
Changes the size of this control.
void setExtent (const S32 width, const S32 height)
virtual bool setBounds (const RectI &newBounds)
Changes the bounds of this control.
void setBounds (const S32 left, const S32 top, const S32 width, const S32 height)
virtual void setLeft (S32 newLeft)
Changes the X position of this control.
virtual void setTop (S32 newTop)
Changes the Y position of this control.
virtual void setWidth (S32 newWidth)
Changes the width of this control.
virtual void setHeight (S32 newHeight)
Changes the height of this control.
virtual void childResized (GuiControl *child)
Called when a child control of the object is resized.
virtual void parentResized (const RectI &oldParentRect, const RectI &newParentRect)
Called when this objects parent is resized.
Rendering
virtual void onRender (Point2I offset, const RectI &updateRect)
Called when this control is to render itself.
void renderChildControls (Point2I offset, const RectI &updateRect)
Called when this control should render its children.
void setUpdateRegion (Point2I pos, Point2I ext)
Sets the area (local coordinates) this control wants refreshed each frame.
virtual void setUpdate ()
Sets the update area of the control to encompass the whole control.
Events
If you subclass these, make sure to call the Parent::'s versions.
virtual bool onWake ()
Called when this object is asked to wake up returns true if it's actually awake at the end.
virtual void onSleep ()
Called when this object is asked to sleep.
virtual void onPreRender ()
Do special pre-render processing.
virtual void onRemove ()
Called when this object is removed.
virtual void onChildRemoved (GuiControl *child)
Called when one of this objects children is removed.
virtual bool onAdd ()
Called when this object is added to the scene.
virtual void onDeleteNotify (SimObject *object)
Called when the mProfile or mToolTipProfile is deleted.
virtual void onChildAdded (GuiControl *child)
Called when this object has a new child.
Mouse Events
These functions are called when the input event which is in the name of the function occurs.
virtual void onMouseUp (const GuiEvent &event)
virtual void onMouseDown (const GuiEvent &event)
virtual void onMouseMove (const GuiEvent &event)
virtual void onMouseDragged (const GuiEvent &event)
virtual void onMouseEnter (const GuiEvent &event)
virtual void onMouseLeave (const GuiEvent &event)
virtual bool onMouseWheelUp (const GuiEvent &event)
virtual bool onMouseWheelDown (const GuiEvent &event)
virtual void onRightMouseDown (const GuiEvent &event)
virtual void onRightMouseUp (const GuiEvent &event)
virtual void onRightMouseDragged (const GuiEvent &event)
virtual void onMiddleMouseDown (const GuiEvent &event)
virtual void onMiddleMouseUp (const GuiEvent &event)
virtual void onMiddleMouseDragged (const GuiEvent &event)
Gamepad Events
These functions are called when the input event which is in the name of the function occurs.
virtual bool onGamepadButtonDown (const GuiEvent &event)
Default behavior is call-through to onKeyDown.
virtual bool onGamepadButtonUp (const GuiEvent &event)
Default behavior is call-through to onKeyUp.
virtual bool onGamepadAxisUp (const GuiEvent &event)
virtual bool onGamepadAxisDown (const GuiEvent &event)
virtual bool onGamepadAxisLeft (const GuiEvent &event)
virtual bool onGamepadAxisRight (const GuiEvent &event)
virtual bool onGamepadTrigger (const GuiEvent &event)
Editor Mouse Events
These functions are called when the input event which is in the name of the function occurs.
Conversely from normal mouse events, these have a boolean return value that, if they return true, the editor will NOT act on them or be able to respond to this particular event.
This is particularly useful for when writing controls so that they may become aware of the editor and allow customization of their data or appearance as if they were actually in use. For example, the GuiTabBookCtrl catches on mouse down to select a tab and NOT let the editor do any instant group manipulation.
virtual bool onMouseDownEditor (const GuiEvent &event, Point2I offset)
Called when a mouseDown event occurs on a control and the GUI editor is active.
virtual bool onMouseUpEditor (const GuiEvent &event, Point2I offset)
Called when a mouseUp event occurs on a control and the GUI editor is active.
virtual bool onRightMouseDownEditor (const GuiEvent &event, Point2I offset)
Called when a rightMouseDown event occurs on a control and the GUI editor is active.
virtual bool onMouseDraggedEditor (const GuiEvent &event, Point2I offset)
Called when a mouseDragged event occurs on a control and the GUI editor is active.
Tabs
virtual GuiControl * findFirstTabable ()
Find the first tab-accessible child of this control.
virtual GuiControl * findLastTabable (bool firstCall=true)
Find the last tab-accessible child of this control.
virtual GuiControl * findPrevTabable (GuiControl *curResponder, bool firstCall=true)
Find previous tab-accessible control with respect to the provided one.
virtual GuiControl * findNextTabable (GuiControl *curResponder, bool firstCall=true)
Find next tab-accessible control with regards to the provided control.
First Responder
A first responder is the control which reacts first, in it's responder chain, to keyboard events The responder chain is set for each parent and so there is only one first responder amongst it's children.
virtual void setFirstResponder (GuiControl *firstResponder)
Sets the first responder for child controls.
virtual void makeFirstResponder (bool value)
Sets up this control to be the first in it's group to respond to an input event.
bool isFirstResponder ()
Returns true if this control is a first responder.
virtual void setFirstResponder ()
Sets this object to be a first responder.
void clearFirstResponder ()
Clears the first responder for this chain.
GuiControl * getFirstResponder ()
Returns the first responder for this chain.
virtual void onGainFirstResponder ()
Occurs when the control gains first-responder status.
virtual void onLoseFirstResponder ()
Occurs when the control loses first-responder status.
Keyboard Events
void addAcceleratorKey ()
Adds the accelerator key for this object to the canvas.
virtual void buildAcceleratorMap ()
Adds this control's accelerator key to the accelerator map, and recursively tells all children to do the same.
virtual void acceleratorKeyPress (U32 index)
Occurs when the accelerator key for this control is pressed.
virtual void acceleratorKeyRelease (U32 index)
Occurs when the accelerator key for this control is released.
virtual bool onKeyDown (const GuiEvent &event)
Happens when a key is depressed.
virtual bool onKeyUp (const GuiEvent &event)
Happens when a key is released.
virtual bool onKeyRepeat (const GuiEvent &event)
Happens when a key is held down, resulting in repeated keystrokes.
Peer Messaging
Used to send a message to other GUIControls which are children of the same parent.
This is mostly used by radio controls.
void messageSiblings (S32 message)
Send a message to all siblings.
virtual void onMessage (GuiControl *sender, S32 msg)
Receive a message from another control.
Canvas Events
Functions called by the canvas
virtual void onDialogPush ()
Called if this object is a dialog, when it is added to the visible layers.
virtual void onDialogPop ()
Called if this object is a dialog, when it is removed from the visible layers.
Public Member Functions inherited from SimGroup
~SimGroup ()
void addObject (SimObject *object, SimObjectId id)
void addObject (SimObject *object, const char *name)
virtual void clear ()
Remove all objects from this set.
virtual SimGroup * clone ()
Return a shallow copy of this object.
DECLARE_CONOBJECT (SimGroup)
virtual SimGroup * deepClone ()
Return a deep copy of this object.
virtual SimObject * findObject (const char *name)
Find a named sub-object of this object.
virtual void popObject ()
Remove an object from the end of the list.
virtual void pushObject (SimObject *object)
Add the given object to the end of the object list of this set.
Public Member Functions inherited from SimSet
SimSet ()
~SimSet ()
virtual void addTamlChild (SimObject *pSimObject)
Called when Taml attempts to populate an objects children during a read.
void callOnChildren (const String &method, S32 argc, ConsoleValueRef argv[], bool executeOnChildGroups=true)
DECLARE_CONOBJECT (SimSet)
SimObject * findObject (SimObject *object)
Find the given object in this set.
template<class T >
void findObjectByCallback (bool(*fn)(T *), Vector< T * > &foundObjects)
Add all child objects (including children of children) to the foundObjects Vector which are of type T and for which DecideAddObjectCallback return true;.
virtual SimObject * findObjectByInternalName (StringTableEntry internalName, bool searchChildren=false)
SimObject * findObjectByLineNumber (const char *fileName, S32 declarationLine, bool searchChildren=false)
template<class T >
void findObjectByType (Vector< T * > &foundObjects)
Add all child objects (including children of children) to the foundObjects Vector which are of type T.
SimObject * getRandom ()
const SetModificationSignal & getSetModificationSignal () const
Return the signal that is triggered when an object is added to or removed from the set.
SetModificationSignal & getSetModificationSignal ()
virtual SimObject * getTamlChild (const U32 childIndex) const
Called when Taml attempts to compile a list of children.
virtual U32 getTamlChildCount (void) const
Called when Taml attempts to compile a list of children.
void lock ()
virtual bool readObject (Stream *stream)
U32 sizeRecursive ()
Return the number of objects in this set as well as all sets that are contained in this set and its children.
void unlock ()
virtual bool writeObject (Stream *stream)
void deleteAllObjects ()
Deletes all the objects in the set.
void bringObjectToFront (SimObject *obj)
void pushObjectToBack (SimObject *obj)
void scriptSort (const String &scriptCallbackFn)
Performs a sort of the objects in the set using a script callback function to do the comparison.
SimObject * front ()
SimObject * first ()
SimObject * last ()
bool empty () const
S32 size () const
iterator begin ()
iterator end ()
value operator[] (S32 index)
iterator find (iterator first, iterator last, SimObject *obj)
iterator find (SimObject *obj)
virtual bool reOrder (SimObject *obj, SimObject *target=0)
Reorder the position of "obj" to either be the last object in the list or, if "target" is given, to come before "target" in the list of children.
SimObject * at (S32 index) const
Return the object at the given index.
Public Member Functions inherited from SimObject
virtual void copyTo (SimObject *object)
Copy SimObject to another SimObject (Originally designed for T2D).
DECLARE_CONOBJECT (SimObject)
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
virtual void getConsoleMethodData (const char *fname, S32 routingId, S32 *type, S32 *minArgs, S32 *maxArgs, void **callback, const char **usage)
Namespace * getNamespace ()
Return the object's namespace.
StringTableEntry getProgenitorFile (void) const
virtual bool handlesConsoleMethod (const char *fname, S32 *routingId)
void setProgenitorFile (const char *pFile)
const char * tabComplete (const char *prevText, S32 baseLen, bool)
Get next matching item in namespace.
virtual bool writeField (StringTableEntry fieldname, const char *value)
Determine whether or not a field should be written.
virtual void writeFields (Stream &stream, U32 tabStop)
Write the fields of this object in TorqueScript.
void setCanSaveDynamicFields (bool bCanSave)
Set whether fields created at runtime should be saved. Default is true.
bool getCanSaveDynamicFields ()
Get whether fields created at runtime should be saved. Default is true.
SimObject * getCopySource () const
Return the object that this object is copying fields from.
void setCopySource (SimObject *object)
Set the object that this object should be copying fields from.
void assignFieldsFrom (SimObject *obj)
Copy fields from another object onto this one.
void assignDynamicFieldsFrom (SimObject *obj)
Copy dynamic fields from another object onto this one.
Notify * removeNotify (void *ptr, Notify::Type)
Remove a notification from the list.
void deleteNotify (SimObject *obj)
Notify an object when we are deleted.
void clearNotify (SimObject *obj)
Notify an object when we are cleared.
void clearAllNotifications ()
Remove all notifications for this object.
void processDeleteNotifies ()
Send out deletion notifications.
void registerReference (SimObject **obj)
Register a reference to this object.
void unregisterReference (SimObject **obj)
Unregister a reference to this object.
SimPersistID * getPersistentId () const
Return the persistent ID assigned to this object or NULL.
SimPersistID * getOrCreatePersistentId ()
Return the persistent ID assigned to this object or assign one to it if it has none.
StringTableEntry getClassNamespace () const
Return name of class namespace set on this object.
StringTableEntry getSuperClassNamespace () const
Return name of superclass namespace set on this object.
void setClassNamespace (const char *classNamespace)
void setSuperClassNamespace (const char *superClassNamespace)
const char * getDataField (StringTableEntry slotName, const char *array)
Get the value of a field on the object.
void setDataField (StringTableEntry slotName, const char *array, const char *value)
Set the value of a field on the object.
const char * getPrefixedDataField (StringTableEntry fieldName, const char *array)
void setPrefixedDataField (StringTableEntry fieldName, const char *array, const char *value)
const char * getPrefixedDynamicDataField (StringTableEntry fieldName, const char *array, const S32 fieldType=-1)
void setPrefixedDynamicDataField (StringTableEntry fieldName, const char *array, const char *value, const S32 fieldType=-1)
StringTableEntry getDataFieldPrefix (StringTableEntry fieldName)
U32 getDataFieldType (StringTableEntry slotName, const char *array)
Get the type of a field on the object.
void setDataFieldType (const U32 fieldTypeId, StringTableEntry slotName, const char *array)
Set the type of a dynamic field on the object.
void setDataFieldType (const char *typeName, StringTableEntry slotName, const char *array)
SimFieldDictionary * getFieldDictionary ()
Get reference to the dictionary containing dynamic fields.
virtual StringTableEntry getComponentName ()
void setInternalName (const char *newname)
These functions support internal naming that is not namespace bound for locating child controls in a generic way.
StringTableEntry getInternalName () const
Get the internal name of this control.
void setOriginalName (const char *originalName)
Set the original name of this control.
StringTableEntry getOriginalName () const
Get the original name of this control.
void setFilename (const char *file)
These functions allow you to set and access the filename where this object was created.
StringTableEntry getFilename () const
Get the filename.
void setDeclarationLine (U32 lineNumber)
These functions are used to track the line number (1-based) on which the object was created if it was loaded from script.
S32 getDeclarationLine () const
Get the declaration line number.
virtual bool save (const char *pcFilePath, bool bOnlySelected=false, const char *preappend=NULL)
Save object as a TorqueScript File.
virtual bool isMethod (const char *methodName)
Check if a method exists in the objects current namespace.
virtual bool isField (const char *fieldName, bool includeStatic=true, bool includeDynamic=true)
Return true if the field is defined on the object.
SimObjectId getId () const
Return the unique numeric object ID.
const char * getIdString () const
Return the object ID as a string.
StringTableEntry getName () const
Return the name of this object.
SimGroup * getGroup () const
Return the SimGroup that this object is contained in.
void assignName (const char *name)
Assign the given name to this object.
void setId (SimObjectId id)
bool isChildOfGroup (SimGroup *pGroup)
bool isProperlyAdded () const
bool isDeleted () const
bool isRemoved () const
virtual bool isLocked () const
virtual void setLocked (bool b)
bool isSelected () const
bool isExpanded () const
bool isEditorOnly () const
bool isNameChangeAllowed () const
bool isAutoDeleted () const
void setSelected (bool sel)
void setExpanded (bool exp)
void setModDynamicFields (bool dyn)
void setModStaticFields (bool sta)
bool canModDynamicFields ()
bool canModStaticFields ()
void setAutoDelete (bool val)
void setEditorOnly (bool val)
void setNameChangeAllowed (bool val)
bool getCanSave () const
Returns boolean specifying if the object can be serialized.
virtual void setCanSave (bool val)
Set serialization flag.
bool isSelectedRecursive () const
Returns true if this object is selected or any group it is a member of is.
SimObject ()
virtual ~SimObject ()
virtual void onGroupAdd ()
Called when the object is added to a SimGroup.
virtual void onNameChange (const char *name)
Called when the object's name is changed.
virtual void onPostAdd ()
Called when the adding of the object to the sim is complete, all sub-objects have been processed as well.
virtual void onStaticModified (const char *slotName, const char *newValue=NULL)
Specifically, these are called by setDataField when a static or dynamic field is modified, see the console details.
virtual void onDynamicModified (const char *slotName, const char *newValue=NULL)
Called when a dynamic field is modified.
virtual void onEditorEnable ()
Called when the editor is activated.
virtual void onEditorDisable ()
Called when the editor is deactivated.
bool registerObject ()
Register an object with the object system.
bool registerObject (U32 id)
Register the object, forcing the id.
bool registerObject (const char *name)
Register the object, assigning the name.
bool registerObject (const char *name, U32 id)
Register the object, assigning a name and ID.
void unregisterObject ()
Unregister the object from Sim.
void deleteObject ()
Unregister, mark as deleted, and free the object.
void safeDeleteObject ()
Performs a safe delayed delete of the object using a sim event.
bool addToSet (SimObjectId)
bool addToSet (const char *)
bool removeFromSet (SimObjectId)
bool removeFromSet (const char *)
virtual String describeSelf () const
Return a textual description of the object.
void dumpToConsole (bool includeFunctions=true)
Dump the contents of this object to the console.
virtual void dumpClassHierarchy ()
added this so that you can print the entire class hierarchy, including script objects,
virtual void dumpGroupHierarchy ()
Print the SimGroup hierarchy of this object to the console.
Public Member Functions inherited from ConsoleObject
ConsoleObject ()
virtual AbstractClassRep * getClassRep () const
Gets the ClassRep.
const AbstractClassRep::Field * findField (StringTableEntry fieldName) const
Get a reference to a field by name.
bool setField (const char *fieldName, const char *value)
Set the value of a field.
void logMessage (const char *fmt,...) const
Logs with Con::printf.
void logWarning (const char *fmt,...) const
Logs with Con::warnf.
void logError (const char *fmt,...) const
Logs with Con::errorf.
const AbstractClassRep::FieldList & getFieldList () const
Get a list of all the fields. This information cannot be modified.
AbstractClassRep::FieldList & getModifiableFieldList ()
Get a list of all the fields, set up so we can modify them.
bool & getDynamicGroupExpand ()
Get a handle to a boolean telling us if we expanded the dynamic group.
S32 getClassId (U32 netClassGroup) const
Get our network-layer class id.
StringTableEntry getClassName () const
Get our compiler and platform independent class name.
Public Member Functions inherited from EngineObject
EngineObject ()
virtual ~EngineObject ()
DECLARE_ABSTRACT_CLASS (EngineObject, void)
DECLARE_INSCOPE (_GLOBALSCOPE)
IEngineObjectPool * getEngineObjectPool () const
Return the pool of EngineObjects to which this object belongs.
void operator delete (void *ptr)
Release the given object's memory in the pool it has been allocated from.
void * operator new (size_t size)
void * operator new (size_t size, IEngineObjectPool *pool)
void * operator new (size_t size TORQUE_TMM_ARGS_DECL)
Allocate a new object in the default object pool.
void * operator new (size_t size, IEngineObjectPool *pool TORQUE_TMM_ARGS_DECL)
Allocate a new object in the given object pool.
void * operator new (size_t size, void *ptr)
Placement new.
Public Member Functions inherited from StrongRefBase
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Static Public Member Functions
static bool _setActive (void *object, const char *index, const char *data)
static bool _setVisible (void *object, const char *index, const char *data)
Static Public Member Functions inherited from SimObject
static SimObject * __findObject (const char *id)
static const char * __getObjectId (ConsoleObject *object)
static void initPersistFields ()
static void setForcedId (SimObjectId id)
Force an Id on the next registered object.
Static Public Member Functions inherited from ConsoleObject
static const char * __category ()
static const char * __description ()
static void consoleInit ()
Register global constant variables and do other one-time initialization tasks in a subclass of ConsoleObject.
static void initPersistFields ()
Register dynamic fields in a subclass of ConsoleObject.
static const char * lookupClassName (const U32 in_classTag)
Get the classname from a class tag.
static ConsoleObject * create (const char *in_pClassName)
static ConsoleObject * create (const U32 groupId, const U32 typeId, const U32 in_classId)
static void addGroup (const char *in_pGroupname, const char *in_pGroupDocs=NULL)
Mark the beginning of a group of fields.
static void endGroup (const char *in_pGroupname)
Mark the end of a group of fields.
static void addArray (const char *arrayName, S32 count)
Marks the start of a fixed size array of fields.
static void endArray (const char *arrayName)
Marks the end of an array of fields.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a complex field.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::WriteDataNotify in_writeDataFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, const char *in_pFieldDocs, U32 flags=0)
Register a simple field.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::WriteDataNotify in_writeDataFn, const char *in_pFieldDocs, U32 flags=0)
static void addFieldV (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, TypeValidator *v, const char *in_pFieldDocs=NULL)
Register a validated field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, AbstractClassRep::WriteDataNotify in_writeDataFn=&defaultProtectedWriteFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a complex protected field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, AbstractClassRep::WriteDataNotify in_writeDataFn=&defaultProtectedWriteFn, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a simple protected field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addDeprecatedField (const char *fieldName)
Add a deprecated field.
static bool removeField (const char *in_pFieldname)
Remove a field.
static AbstractClassRep * getStaticClassRep ()
Get the abstract class information for this class.
static AbstractClassRep * getParentStaticClassRep ()
Get the abstract class information for this class's superclass.
static ConsoleObject * __findObject (const char *)
static const char * __getObjectId (ConsoleObject *)
Static Public Member Functions inherited from EngineObject
static void debugDumpInstances ()
Dump describeSelf()s of all live ConsoleObjects to the console.
static void debugEnumInstances (const std::type_info &type, DebugEnumInstancesCallback callback)
Call the given callback for all instances of the given type.
static void debugEnumInstances (const char *className, DebugEnumInstancesCallback callback)
Same as above but uses an export class name and also includes inheritance (i.e.
Protected Attributes
GuiControlProfile * mProfile
The profile for this gui (data settings that are likely to be shared by multiple guis)
GuiControlProfile * mTooltipProfile
The profile for any tooltips.
Protected Attributes inherited from SimSet
void * mMutex
SetModificationSignal mSetModificationSignal
Signal that is triggered when objects are added or removed from the set.
SimObjectList objectList
Protected Attributes inherited from SimObject
DEFINE_CREATE_METHOD
SimObjectId mId
Id number for this object.
StringTableEntry mInternalName
Internal name assigned to the object. Not set by default.
return object
bool mCanSaveFieldDictionary
Whether dynamic fields should be saved out in serialization. Defaults to true.
SimPersistID * mPersistentId
Persistent ID assigned to this object.
Namespace * mNameSpace
The namespace in which method lookup for this object begins.
StringTableEntry mClassName
Name of namespace to use as class namespace.
StringTableEntry mSuperClassName
Name of namespace to use as class super namespace.
Protected Attributes inherited from EngineObject
DEFINE_CREATE_METHOD
return object
Protected Attributes inherited from StrongRefBase
U32 mRefCount
reference counter for StrongRefPtr objects
Static Protected Attributes
Design Time Editor Access
static GuiEditCtrl * smEditorHandle
static GuiEditCtrl pointer that gives controls access to editor-NULL if editor is closed
Static Protected Attributes inherited from SimObject
static SimObjectId smForcedId
The Id to force upon the object. Poor object.
static bool smForceId
Force a registered object to use the given Id. Cleared upon use.
Control State
typedef Vector< Vector< GuiWindowCtrl * > > CollapseGroupVec
S32 mTipHoverTime
RenderTooltipDelegate mRenderTooltipDelegate
Delegate called to render a tooltip for this control.
bool mVisible
bool mActive
bool mAwake
bool mSetFirstResponder
bool mIsContainer
if true, then the GuiEditor can drag other controls into this one.
bool mCanResize
bool mCanHit
S32 mLayer
Point2I mMinExtent
StringTableEntry mLangTableName
LangTable * mLangTable
bool mNotifyChildrenResized
CollapseGroupVec mCollapseGroupVec
S32 mHorizSizing
Set from horizSizingOptions.
S32 mVertSizing
Set from vertSizingOptions.
StringTableEntry mAcceleratorKey
StringTableEntry mConsoleVariable
String mConsoleCommand
String mAltConsoleCommand
String mTooltip
static bool smDesignTime
static GuiControl boolean that specifies if the GUI Editor is active
static bool setProfileProt (void *object, const char *index, const char *data)
static bool setTooltipProfileProt (void *object, const char *index, const char *data)
bool defaultTooltipRender (const Point2I &hoverPos, const Point2I &cursorPos, const char *tipText=NULL)
The default tooltip rendering function.
Keyboard Input
GuiControl * mFirstResponder
static GuiControl * smPrevResponder
static GuiControl * smCurResponder
Console
GFXStateBlockRef mDefaultGuiSB
static GuiControl * smThisControl
$ThisControl variable for callback execution.
const char * evaluate (const char *str)
Set $ThisControl and evaluate the given script code.
void setVariable (const char *value)
Sets the value of the console variable bound to this control.
void setIntVariable (S32 value)
Sets the value of the console variable bound to this control.
void setFloatVariable (F32 value)
Sets the value of the console variable bound to this control.
const char * getVariable ()
Returns value of control's bound variable as a string.
S32 getIntVariable ()
Returns value of control's bound variable as a integer.
F32 getFloatVariable ()
Returns value of control's bound variable as a float.
virtual const char * getScriptValue ()
Returns the value of the variable bound to this object.
virtual void setScriptValue (const char *value)
Sets the value of the variable bound to this object.
Callbacks
Executes a console command, and returns the result.
The global console variable $ThisControl is set to the id of the calling control. WARNING: because multiple controls may set $ThisControl, at any time, the value of $ThisControl should be stored in a local variable by the callback code. The use of the $ThisControl variable is not thread safe.
DECLARE_CALLBACK (void, onAdd,())
DECLARE_CALLBACK (void, onRemove,())
DECLARE_CALLBACK (void, onWake,())
DECLARE_CALLBACK (void, onSleep,())
DECLARE_CALLBACK (void, onLoseFirstResponder,())
DECLARE_CALLBACK (void, onGainFirstResponder,())
DECLARE_CALLBACK (void, onAction,())
DECLARE_CALLBACK (void, onVisible,(bool state))
DECLARE_CALLBACK (void, onActive,(bool state))
DECLARE_CALLBACK (void, onDialogPush,())
DECLARE_CALLBACK (void, onDialogPop,())
DECLARE_CALLBACK (void, onControlDragEnter,(GuiControl *control, const Point2I &dropPoint))
DECLARE_CALLBACK (void, onControlDragExit,(GuiControl *control, const Point2I &dropPoint))
DECLARE_CALLBACK (void, onControlDragged,(GuiControl *control, const Point2I &dropPoint))
DECLARE_CALLBACK (void, onControlDropped,(GuiControl *control, const Point2I &dropPoint))
const char * execConsoleCallback ()
Executes mConsoleCommand, and returns the result.
const char * execAltConsoleCallback ()
Executes mAltConsoleCommand, and returns the result.
Initialization
DECLARE_CONOBJECT (GuiControl)
DECLARE_CATEGORY ("Gui Core")
DECLARE_DESCRIPTION ("Base class for GUI controls. Can also be used as a generic container.")
GuiControl ()
virtual ~GuiControl ()
virtual bool processArguments (S32 argc, ConsoleValueRef *argv)
Process constructor options. (ie, new SimObject(1,2,3))
static void initPersistFields ()
static void consoleInit ()
Input (Keyboard/Mouse)
enum EHitTestFlags {
HIT_FullBoxOnly = BIT(0),
HIT_ParentPreventsChildHit = BIT(1),
HIT_AddParentHits = BIT(2),
HIT_NoCanHitNoRecurse = BIT(3)
}
virtual bool pointInControl (const Point2I &parentCoordPoint)
This function will return true if the provided coordinates (wrt parent object) are within the bounds of this control.
bool cursorInControl ()
Returns true if the global cursor is inside this control.
virtual GuiControl * findHitControl (const Point2I &pt, S32 initialLayer=-1)
Returns the control which the provided point is under, with layering.
virtual bool findHitControls (const RectI &rect, Vector< GuiControl * > &outResult, U32 flags=0, S32 initialLayer=-1, U32 depth=0)
void mouseLock (GuiControl *lockingControl)
Lock the mouse within the provided control.
void mouseLock ()
Turn on mouse locking with last used lock control.
void mouseUnlock ()
Unlock the mouse.
bool isMouseLocked ()
Returns true if the mouse is locked.
Additional Inherited Members
Public Attributes inherited from EngineObject
DECLARE_INSTANTIABLE
Static Public Attributes inherited from ConsoleObject
static const bool __smIsDatablock = false
Subclasses of ConsoleObjects that are datablocks should redefine this static member variable and set it to true.
Protected Types inherited from EngineObject
typedef ::FalseType __IsDisposableType
typedef ::FalseType __IsSingletonType
Protected Member Functions inherited from SimSet
DECLARE_CALLBACK (void, onObjectAdded,(SimObject *object))
DECLARE_CALLBACK (void, onObjectRemoved,(SimObject *object))
Protected Member Functions inherited from SimObject
virtual void _destroySelf ()
Subclasses should overload this method instead of the public destroySelf().
virtual String _getLogMessage (const char *fmt, va_list args) const
We can provide more detail, like object name and id.
virtual void _onSelected ()
Called when the object is selected in the editor.
virtual void _onUnselected ()
Called when the object is unselected in the editor.
object incRefCount ()
virtual void onTamlAddParent (SimObject *pParentObject)
Called after Taml has finished reading the object and has added the object to any parent.
virtual void onTamlCustomRead (const TamlCustomNodes &customNodes)
Called during the reading of the object to allow custom properties to be read.
virtual void onTamlCustomWrite (TamlCustomNodes &customNodes)
Called during the writing of the object to allow custom properties to be written.
virtual void onTamlPostRead (const TamlCustomNodes &customNodes)
Called after Taml has finished reading the object.
virtual void onTamlPostWrite (void)
Called after Taml has finished writing the object.
virtual void onTamlPreRead (void)
Called prior to Taml reading the object.
virtual void onTamlPreWrite (void)
Taml callbacks.
object registerObject ()
void linkNamespaces ()
Perform namespace linking on this object.
void unlinkNamespaces ()
Undo namespace linking on this object.
Protected Member Functions inherited from ConsoleObject
ConsoleObject (const ConsoleObject &)
Protected Member Functions inherited from EngineObject
object incRefCount ()
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Static Protected Member Functions inherited from SimObject
static bool _setPersistentID (void *object, const char *index, const char *data)
Static Protected Member Functions inherited from EngineObject
static void * _allocateObject (size_t size, IEngineObjectPool *pool TORQUE_TMM_ARGS_DECL)
Member Typedef Documentation
typedef Vector< Vector< GuiWindowCtrl *> > GuiControl::CollapseGroupVec protected
typedef SimGroup GuiControl::Parent
Member Enumeration Documentation
anonymous enum
Additional write flags for GuiControls.
Enumerator
NoCheckParentCanSave
Don't inherit mCanSave=false from parents.
enum GuiControl::EHitTestFlags
Enumerator
HIT_FullBoxOnly
Hit only counts if all of a control's bounds are within the hit rectangle.
HIT_ParentPreventsChildHit
A positive hit test on a parent control will prevent hit tests on children.
HIT_AddParentHits
Parent's that get hit should be added regardless of whether any of their children get hit, too.
HIT_NoCanHitNoRecurse
A hit-disabled control will not recurse into children.
enum GuiControl::horizSizingOptions
Enumerator
horizResizeRight
fixed on the left and width
horizResizeWidth
fixed on the left and right
horizResizeLeft
fixed on the right and width
horizResizeCenter
horizResizeRelative
resize relative
horizResizeAspectLeft
resize relative to height delta (offset Left)
horizResizeAspectRight
resize relative to height delta (offset Right)
horizResizeAspectCenter
resize relative to height delta (Centered)
horizResizeWindowRelative
resize window relative
enum GuiControl::vertSizingOptions
Enumerator
vertResizeBottom
fixed on the top and in height
vertResizeHeight
fixed on the top and bottom
vertResizeTop
fixed in height and on the bottom
vertResizeCenter
vertResizeRelative
resize relative
vertResizeAspectTop
resize relative to width delta (offset Left)
vertResizeAspectBottom
resize relative to width delta (offset Right)
vertResizeAspectCenter
resize relative to width delta Centered)
vertResizeWindowRelative
resize window relative
Constructor & Destructor Documentation
GuiControl::GuiControl ()
Referenced by _setActive().
virtual GuiControl::~GuiControl () virtual
Referenced by _setActive().
Member Function Documentation
static bool GuiControl::_setActive (void * object, const char * index, const char * data) inline static
References consoleInit(), dAtob(), DECLARE_CATEGORY(), DECLARE_CONOBJECT(), DECLARE_DESCRIPTION(), getCanSaveParent(), GuiControl(), initPersistFields(), SimObject::object, processArguments(), setActive(), setSizing(), write(), and ~GuiControl().
static bool GuiControl::_setVisible (void * object, const char * index, const char * data) inline static
References dAtob(), SimObject::object, and setVisible().
virtual void GuiControl::acceleratorKeyPress (U32 index) virtual
Occurs when the accelerator key for this control is pressed.
Parameters
index Index in the accelerator map of the key
Reimplemented in GuiMenuBar, and GuiButtonBaseCtrl.
Referenced by getFirstResponder().
virtual void GuiControl::acceleratorKeyRelease (U32 index) virtual
Occurs when the accelerator key for this control is released.
Parameters
index Index in the accelerator map of the key
Reimplemented in GuiButtonBaseCtrl.
Referenced by getFirstResponder().
virtual bool GuiControl::acceptsAsChild (SimObject * object) const virtual
Return true if this set accepts the given object as a child.
This method should be overridden for set classes that restrict membership.
Reimplemented from SimSet.
Reimplemented in GuiTabBookCtrl, and GuiFormCtrl.
Referenced by isAwake().
void GuiControl::addAcceleratorKey ()
Adds the accelerator key for this object to the canvas.
Referenced by getFirstResponder(), and GuiCanvas::mouseRightButtonDown().
void GuiControl::addObject (SimObject * obj) virtual
Adds an object as a child of this object.
Parameters
obj New child object of this control
Reimplemented from SimGroup.
Referenced by isAwake().
void GuiControl::awaken ()
Called when this control and its children have been wired up.
Referenced by setBounds().
virtual void GuiControl::buildAcceleratorMap () virtual
Adds this control's accelerator key to the accelerator map, and recursively tells all children to do the same.
Referenced by getFirstResponder().
virtual void GuiControl::childResized (GuiControl * child) virtual
Called when a child control of the object is resized.
Parameters
child Child object
Reimplemented in GuiInspectorTypeBitMask32, GuiTabBookCtrl, GuiScrollCtrl, GuiAutoScrollCtrl, GuiRolloutCtrl, GuiContainer, GuiStackControl, and GuiDynamicCtrlArrayControl.
Referenced by setBounds(), and GuiInspectorTypeBitMask32::~GuiInspectorTypeBitMask32().
void GuiControl::clearFirstResponder ()
Clears the first responder for this chain.
Referenced by onMouseDraggedEditor().
U32 GuiControl::clipText (String & inOutText, U32 width) const
Returns text clipped to fit within a pixel width.
The clipping occurs on the right side and "..." is appended. It returns width of the final clipped text in pixels.
Referenced by getControlProfile().
static void GuiControl::consoleInit () static
Referenced by GuiInspectorTypeColorI::_getColorConversionFunction(), GuiInspectorTypeSFXDescriptionName::_getDatablockSet(), GuiInspectorTypeSFXTrackName::_getDatablockSet(), GuiInspectorTypeSFXEnvironmentName::_getDatablockSet(), GuiInspectorTypeSFXAmbienceName::_getDatablockSet(), _setActive(), GuiInspectorTypeRegularMaterialName::GuiInspectorTypeRegularMaterialName(), GuiInspectorTypeTerrainMaterialIndex::GuiInspectorTypeTerrainMaterialIndex(), GuiInspectorTypeTerrainMaterialName::GuiInspectorTypeTerrainMaterialName(), and GuiInspectorTypeBitMask32::~GuiInspectorTypeBitMask32().
virtual bool GuiControl::controlIsChild (GuiControl * child) virtual
Returns true if the provided control is a child (grandchild, or great-grandchild) of this one.
Parameters
child Control to test
Referenced by onMouseDraggedEditor().
bool GuiControl::cursorInControl ()
Returns true if the global cursor is inside this control.
Referenced by setBounds().
GuiControl::DECLARE_CALLBACK (void , onAdd , ()) protected
GuiControl::DECLARE_CALLBACK (void , onRemove , ()) protected
GuiControl::DECLARE_CALLBACK (void , onWake , ()) protected
GuiControl::DECLARE_CALLBACK (void , onSleep , ()) protected
GuiControl::DECLARE_CALLBACK (void , onLoseFirstResponder , ()) protected
GuiControl::DECLARE_CALLBACK (void , onGainFirstResponder , ()) protected
GuiControl::DECLARE_CALLBACK (void , onAction , ()) protected
GuiControl::DECLARE_CALLBACK (void , onVisible , (bool state)) protected
GuiControl::DECLARE_CALLBACK (void , onActive , (bool state)) protected
GuiControl::DECLARE_CALLBACK (void , onDialogPush , ()) protected
GuiControl::DECLARE_CALLBACK (void , onDialogPop , ()) protected
GuiControl::DECLARE_CALLBACK (void , onControlDragEnter , (GuiControl *control, const Point2I &dropPoint)) protected
GuiControl::DECLARE_CALLBACK (void , onControlDragExit , (GuiControl *control, const Point2I &dropPoint)) protected
GuiControl::DECLARE_CALLBACK (void , onControlDragged , (GuiControl *control, const Point2I &dropPoint)) protected
GuiControl::DECLARE_CALLBACK (void , onControlDropped , (GuiControl *control, const Point2I &dropPoint)) protected
GuiControl::DECLARE_CATEGORY ("Gui Core")
Referenced by _setActive(), GuiPopUpMenuCtrl::getNumEntries(), and GuiPopUpMenuCtrlEx::getNumEntries().
GuiControl::DECLARE_CONOBJECT (GuiControl)
Referenced by _setActive(), GuiPopUpMenuCtrl::getNumEntries(), and GuiPopUpMenuCtrlEx::getNumEntries().
GuiControl::DECLARE_DESCRIPTION ("Base class for GUI controls. Can also be used as a generic container.")
Referenced by _setActive(), GuiPopUpMenuCtrlEx::getNumEntries(), GuiPopUpMenuCtrl::getNumEntries(), and GuiSliderCtrl::setScriptValue().
bool GuiControl::defaultTooltipRender (const Point2I & hoverPos, const Point2I & cursorPos, const char * tipText = NULL) protected
The default tooltip rendering function.
See also
RenderTooltipDelegate
const char* GuiControl::evaluate (const char * str) protected
Set $ThisControl and evaluate the given script code.
const char* GuiControl::execAltConsoleCallback ()
Executes mAltConsoleCommand, and returns the result.
Referenced by getTooltip().
const char* GuiControl::execConsoleCallback ()
Executes mConsoleCommand, and returns the result.
Referenced by getTooltip().
virtual GuiControl* GuiControl::findFirstTabable () virtual
Find the first tab-accessible child of this control.
Referenced by onMouseDraggedEditor().
virtual GuiControl* GuiControl::findHitControl (const Point2I & pt, S32 initialLayer = -1) virtual
Returns the control which the provided point is under, with layering.
Parameters
pt Point to test
initialLayer Layer of gui objects to begin the search
Reimplemented in GuiScrollCtrl, GuiWindowCtrl, GuiInspector, and GuiTabPageCtrl.
Referenced by setBounds().
virtual bool GuiControl::findHitControls (const RectI & rect, Vector< GuiControl * > & outResult, U32 flags = 0, S32 initialLayer = -1, U32 depth = 0) virtual
virtual GuiControl* GuiControl::findLastTabable (bool firstCall = true) virtual
Find the last tab-accessible child of this control.
Parameters
firstCall Set to true to clear the global previous responder
Referenced by onMouseDraggedEditor().
virtual GuiControl* GuiControl::findNextTabable (GuiControl * curResponder, bool firstCall = true) virtual
Find next tab-accessible control with regards to the provided control.
Parameters
curResponder Current control
firstCall Set to true to clear the global current responder
Reimplemented in GuiWindowCtrl, and GuiTabPageCtrl.
Referenced by onMouseDraggedEditor().
virtual GuiControl* GuiControl::findPrevTabable (GuiControl * curResponder, bool firstCall = true) virtual
Find previous tab-accessible control with respect to the provided one.
Parameters
curResponder Current control
firstCall Set to true to clear the global previous responder
Reimplemented in GuiWindowCtrl, and GuiTabPageCtrl.
Referenced by onMouseDraggedEditor().
const RectI GuiControl::getBounds () const inline
Returns the bounds of the control.
Referenced by getGlobalBounds().
bool GuiControl::getCanSaveParent ()
Returns boolean as to whether any parent of this control has the 'no serialization' flag set.
Referenced by _setActive().
const char* GuiControl::getConsoleCommand ()
Returns the name of the function bound to this GuiControl.
GuiControlProfile* GuiControl::getControlProfile () inline
Returns our profile (and finds the profile if it hasn't been set yet)
References clipText(), inspectPostApply(), inspectPreApply(), messageSiblings(), mProfile, onAction(), onDialogPop(), onDialogPush(), onMessage(), renderJustifiedText(), and setControlProfile().
virtual void GuiControl::getCursor (GuiCursor *& cursor, bool & showCursor, const GuiEvent & lastGuiEvent) virtual
Get information about the cursor.
Parameters
cursor Cursor information will be stored here
showCursor Will be set to true if the cursor is visible
lastGuiEvent GuiEvent containing cursor position and modifier keys (ie ctrl, shift, alt etc)
Reimplemented in GuiEditCtrl, GuiMLTextCtrl, GuiWindowCtrl, GuiFrameSetCtrl, GuiSplitContainer, GuiInspector, and EditTSCtrl.
Referenced by isAwake().
const Point2I& GuiControl::getExtent () const inline
Returns extents of the control.
References RectI::extent.
GuiControl* GuiControl::getFirstResponder () inline
Returns the first responder for this chain.
References acceleratorKeyPress(), acceleratorKeyRelease(), addAcceleratorKey(), buildAcceleratorMap(), mFirstResponder, onGainFirstResponder(), onKeyDown(), onKeyRepeat(), onKeyUp(), and onLoseFirstResponder().
F32 GuiControl::getFloatVariable () protected
Returns value of control's bound variable as a float.
const RectI GuiControl::getGlobalBounds () inline
References getBounds(), localToGlobalCoord(), and RectI::point.
LangTable* GuiControl::getGUILangTable (void)
const UTF8* GuiControl::getGUIString (S32 id)
const S32 GuiControl::getHeight () const inline
Returns the height of the control.
References RectI::extent, and Point2I::y.
Referenced by GuiFrameSetCtrl::hitVerticalDivider().
const S32 GuiControl::getHorizSizing () const inline
References mHorizSizing.
S32 GuiControl::getIntVariable () protected
Returns value of control's bound variable as a integer.
const S32 GuiControl::getLeft () const inline
Returns the X position of the control.
References RectI::point, and Point2I::x.
virtual Point2I GuiControl::getMinExtent () const inline virtual
Returns minimum size the control can be.
Reimplemented in GuiSplitContainer.
References mMinExtent.
GuiControl* GuiControl::getParent ()
Returns the control which owns this one.
Referenced by isAwake().
const Point2I& GuiControl::getPosition () const inline
Returns position of the control.
References RectI::point.
RenderTooltipDelegate& GuiControl::getRenderTooltipDelegate () inline
Return the delegate used to render tooltips on this control.
References mRenderTooltipDelegate.
const RenderTooltipDelegate& GuiControl::getRenderTooltipDelegate () const inline
References mRenderTooltipDelegate.
GuiCanvas* GuiControl::getRoot ()
Returns the root canvas of this control.
Referenced by isAwake().
virtual const char* GuiControl::getScriptValue () virtual
Returns the value of the variable bound to this object.
Reimplemented in GuiMLTextCtrl, GuiPopUpMenuCtrl, GuiPopUpMenuCtrlEx, GuiTextEditCtrl, GuiColorPickerCtrl, GuiButtonBaseCtrl, GuiTextCtrl, GuiTextListCtrl, GuiConsoleTextCtrl, GuiProgressBitmapCtrl, and GuiProgressCtrl.
Referenced by setBounds().
virtual void GuiControl::getScrollLineSizes (U32 * rowHeight, U32 * columnWidth) virtual
Get information about the size of a scroll line.
Parameters
rowHeight The height, in pixels, of a row
columnWidth The width, in pixels, of a column
Referenced by isAwake().
String& GuiControl::getTooltip () inline
Returns the tooltip.
References execAltConsoleCallback(), execConsoleCallback(), and mTooltip.
GuiControlProfile* GuiControl::getTooltipProfile () inline
Returns our tooltip profile (and finds the profile if it hasn't been set yet)
References mTooltipProfile, and setTooltipProfile().
const S32 GuiControl::getTop () const inline
Returns the Y position of the control.
References RectI::point, and Point2I::y.
const char* GuiControl::getVariable () protected
Returns value of control's bound variable as a string.
const S32 GuiControl::getVertSizing () const inline
References mVertSizing, and setVisible().
const S32 GuiControl::getWidth () const inline
Returns the width of the control.
References RectI::extent, and Point2I::x.
Referenced by GuiFrameSetCtrl::hitHorizontalDivider().
Point2I GuiControl::globalToLocalCoord (const Point2I & src)
Returns global coordinates translated into local space.
Parameters
src Global coordinates to translate
Referenced by isAwake().
static void GuiControl::initPersistFields () static
Referenced by _setActive(), GuiPopUpMenuCtrl::getNumEntries(), and GuiPopUpMenuCtrlEx::getNumEntries().
void GuiControl::inspectPostApply () virtual
Called after any property of the object is changed in the world editor.
See also
inspectPreApply
Reimplemented from SimObject.
Reimplemented in GuiMessageVectorCtrl.
Referenced by getControlProfile(), and GuiGradientCtrl::updateColor().
void GuiControl::inspectPreApply () virtual
Called before any property of the object is changed in the world editor.
The calling order here is:
inspectPreApply()
...
calls to setDataField()
...
inspectPostApply()
Reimplemented from SimObject.
Referenced by getControlProfile(), and GuiGradientCtrl::updateColor().
bool GuiControl::isActive () inline
Returns true if this control is active.
References mActive.
bool GuiControl::isAwake () inline
Returns true if this control is awake.
References acceptsAsChild(), addObject(), getCursor(), getParent(), getRoot(), getScrollLineSizes(), globalToLocalCoord(), localToGlobalCoord(), mAwake, onGroupRemove(), removeObject(), resize(), and setPosition().
bool GuiControl::isFirstResponder ()
Returns true if this control is a first responder.
Referenced by GuiScrollCtrl::getCurHitRegion(), and onMouseDraggedEditor().
virtual bool GuiControl::isHidden () const inline virtual
Reimplemented from SimObject.
References isVisible().
Referenced by GuiParticleGraphCtrl::~GuiParticleGraphCtrl().
bool GuiControl::isMouseLocked ()
Returns true if the mouse is locked.
bool GuiControl::isVisible () const inline
Returns true if the object is visible.
References mVisible.
Referenced by isHidden().
Point2I GuiControl::localToGlobalCoord (const Point2I & src)
Translates local coordinates (wrt this object) into global coordinates.
Parameters
src Local coordinates to translate
Referenced by getGlobalBounds(), and isAwake().
virtual void GuiControl::makeFirstResponder (bool value) virtual
Sets up this control to be the first in it's group to respond to an input event.
Parameters
value True if this should be a first responder
Referenced by onMouseDraggedEditor().
void GuiControl::messageSiblings (S32 message)
Send a message to all siblings.
Referenced by getControlProfile().
void GuiControl::mouseLock (GuiControl * lockingControl)
Lock the mouse within the provided control.
Parameters
lockingControl Control to lock the mouse within
void GuiControl::mouseLock ()
Turn on mouse locking with last used lock control.
Referenced by GuiCanvas::getCursorExtent().
void GuiControl::mouseUnlock ()
Unlock the mouse.
Referenced by GuiCanvas::getCursorExtent().
virtual void GuiControl::onAction () virtual
Occurs when this control performs its "action".
Reimplemented in GuiMenuBar, GuiBitmapButtonCtrl, GuiPopUpMenuCtrlEx, GuiPopUpMenuCtrl, and GuiButtonBaseCtrl.
Referenced by getControlProfile().
virtual bool GuiControl::onAdd () virtual
Called when this object is added to the scene.
Reimplemented from SimObject.
Reimplemented in GuiTreeViewCtrl, GuiInspectorTypeBitMask32, TerrainEditor, WorldEditor, GuiEditCtrl, GuiMLTextCtrl, GuiCanvas, GuiInspectorField, GuiRolloutCtrl, GuiGradientCtrl, GuiPopUpMenuCtrlEx, GuiPopUpMenuCtrl, EditTSCtrl, GuiGameListMenuCtrl, GuiGameListOptionsCtrl, GuiMissionAreaCtrl, GuiFrameSetCtrl, GuiTextEditCtrl, OpenVROverlay, GuiRiverEditorCtrl, GuiSplitContainer, GuiTerrPreviewCtrl, GuiInspectorGroup, GuiMessageVectorCtrl, GameTSCtrl, GuiMeshRoadEditorCtrl, GuiNavEditorCtrl, GuiInspectorNodeListField, GuiRoadEditorCtrl, GuiTextCtrl, ForestEditorCtrl, GuiConvexEditorCtrl, guiAnimBitmapCtrl, GuiDecalEditorCtrl, GuiInspectorEntityGroup, EditManager, GuiInspectorCustomField, GuiInspectorComponentGroup, GuiInspectorVariableField, GuiInspectorDynamicField, GuiMissionAreaEditorCtrl, and GuiOffscreenCanvas.
Referenced by setBounds(), and GuiGradientCtrl::updateColor().
virtual void GuiControl::onChildAdded (GuiControl * child) virtual
Called when this object has a new child.
Reimplemented in GuiTabBookCtrl, GuiAutoScrollCtrl, GuiContainer, and GuiScriptNotifyCtrl.
Referenced by setBounds().
virtual void GuiControl::onChildRemoved (GuiControl * child) virtual
Called when one of this objects children is removed.
Reimplemented in GuiAutoScrollCtrl, GuiTabBookCtrl, GuiContainer, and GuiScriptNotifyCtrl.
Referenced by setBounds().
virtual void GuiControl::onDeleteNotify (SimObject * object) virtual
Called when the mProfile or mToolTipProfile is deleted.
Reimplemented from SimSet.
Reimplemented in TerrainEditor, and GuiInspector.
Referenced by setBounds().
virtual void GuiControl::onDialogPop () virtual
Called if this object is a dialog, when it is removed from the visible layers.
Reimplemented in GuiScriptNotifyCtrl.
Referenced by getControlProfile().
virtual void GuiControl::onDialogPush () virtual
Called if this object is a dialog, when it is added to the visible layers.
Reimplemented in GuiScriptNotifyCtrl.
Referenced by getControlProfile().
virtual void GuiControl::onGainFirstResponder () virtual
Occurs when the control gains first-responder status.
Referenced by getFirstResponder().
virtual bool GuiControl::onGamepadAxisDown (const GuiEvent & event) virtual
Reimplemented in GuiGameListMenuCtrl.
virtual bool GuiControl::onGamepadAxisLeft (const GuiEvent & event) virtual
Reimplemented in GuiGameListOptionsCtrl.
virtual bool GuiControl::onGamepadAxisRight (const GuiEvent & event) virtual
Reimplemented in GuiGameListOptionsCtrl.
virtual bool GuiControl::onGamepadAxisUp (const GuiEvent & event) virtual
Reimplemented in GuiGameListMenuCtrl.
virtual bool GuiControl::onGamepadButtonDown (const GuiEvent & event) virtual
Default behavior is call-through to onKeyDown.
virtual bool GuiControl::onGamepadButtonUp (const GuiEvent & event) virtual
Default behavior is call-through to onKeyUp.
virtual bool GuiControl::onGamepadTrigger (const GuiEvent & event) virtual
virtual void GuiControl::onGroupRemove () virtual
Called when the object is removed from a SimGroup.
Reimplemented from SimObject.
Referenced by isAwake().
virtual bool GuiControl::onInputEvent (const InputEventInfo & event) virtual
General input handler.
Reimplemented in TerrainEditor, EditTSCtrl, and GuiInputCtrl.
virtual bool GuiControl::onKeyDown (const GuiEvent & event) virtual
Happens when a key is depressed.
Parameters
event Event descriptor (which contains the key)
Reimplemented in GuiTreeViewCtrl, GuiEditCtrl, GuiMLTextCtrl, GuiWindowCtrl, GuiTabBookCtrl, GuiScrollCtrl, GuiPopUpMenuCtrlEx, GuiPopUpMenuCtrl, GuiListBoxCtrl, GuiTextEditCtrl, GuiGameListMenuCtrl, GuiButtonBaseCtrl, GuiTextListCtrl, GuiArrayCtrl, GuiGameListOptionsCtrl, GuiRiverEditorCtrl, GuiMenuTextListCtrl, GuiFadeinBitmapCtrl, GuiMeshRoadEditorCtrl, GuiRoadEditorCtrl, GuiPopupTextListCtrl, GuiPopupTextListCtrlEx, GuiConvexEditorCtrl, GuiTextEditSliderCtrl, GuiTextEditSliderBitmapCtrl, GuiPopupMenuTextListCtrl, GuiConsoleEditCtrl, and GuiMLTextEditCtrl.
Referenced by getFirstResponder().
virtual bool GuiControl::onKeyRepeat (const GuiEvent & event) virtual
Happens when a key is held down, resulting in repeated keystrokes.
Parameters
event Event descriptor (which contains the key)
Reimplemented in GuiGameListMenuCtrl, and GuiGameListOptionsCtrl.
Referenced by getFirstResponder().
virtual bool GuiControl::onKeyUp (const GuiEvent & event) virtual
Happens when a key is released.
Parameters
event Event descriptor (which contains the key)
Reimplemented in GuiButtonBaseCtrl, and GuiConvexEditorCtrl.
Referenced by getFirstResponder().
virtual void GuiControl::onLoseFirstResponder () virtual
Occurs when the control loses first-responder status.
Reimplemented in GuiTextEditCtrl, GuiScriptNotifyCtrl, and GuiMLTextEditCtrl.
Referenced by getFirstResponder().
virtual void GuiControl::onMessage (GuiControl * sender, S32 msg) virtual
Receive a message from another control.
Reimplemented in GuiButtonBaseCtrl.
Referenced by getControlProfile().
virtual void GuiControl::onMiddleMouseDown (const GuiEvent & event) virtual
Reimplemented in GuiTreeViewCtrl, GuiShapeEdPreview, GuiMaterialPreview, GuiDecoyCtrl, EditTSCtrl, and GameTSCtrl.
virtual void GuiControl::onMiddleMouseDragged (const GuiEvent & event) virtual
Reimplemented in GuiShapeEdPreview, GuiMaterialPreview, GuiDecoyCtrl, and EditTSCtrl.
virtual void GuiControl::onMiddleMouseUp (const GuiEvent & event) virtual
Reimplemented in GuiShapeEdPreview, GuiMaterialPreview, GuiDecoyCtrl, EditTSCtrl, and GameTSCtrl.
virtual void GuiControl::onMouseDown (const GuiEvent & event) virtual
Reimplemented in GuiTreeViewCtrl, GuiEditCtrl, GuiMLTextCtrl, GuiWindowCtrl, GuiObjectView, GuiTabBookCtrl, GuiScrollCtrl, GuiMenuBar, GuiInspectorField, GuiShapeEdPreview, GuiColorPickerCtrl, GuiPopUpMenuCtrlEx, GuiPopUpMenuCtrl, GuiRolloutCtrl, GuiTextEditCtrl, GuiGameListMenuCtrl, GuiGradientCtrl, GuiListBoxCtrl, GuiMissionAreaCtrl, GuiFormCtrl, CreatorTree, GuiFrameSetCtrl, GuiButtonBaseCtrl, GuiParticleGraphCtrl, GuiPaneControl, GuiArrayCtrl, DbgFileView, GuiSliderCtrl, GuiMaterialPreview, GuiMenuTextListCtrl, GuiSplitContainer, GuiPopupMenuBackgroundCtrl, GuiMessageVectorCtrl, GuiDirectoryFileListCtrl, GuiDragAndDropControl, GuiFadeinBitmapCtrl, GuiFilterCtrl, GuiTextEditSliderCtrl, GuiTextEditSliderBitmapCtrl, GuiInspector, GuiPopupMenuTextListCtrl, GuiSubmenuBackgroundCtrl, GuiBubbleTextCtrl, GuiTabPageCtrl, GuiMouseEventCtrl, GameTSCtrl, GuiRectHandles, EditTSCtrl, GuiDecoyCtrl, GuiPopUpBackgroundCtrl, GuiPopUpBackgroundCtrlEx, GuiMenuBackgroundCtrl, and GuiGradientSwatchCtrl.
virtual bool GuiControl::onMouseDownEditor (const GuiEvent & event, Point2I offset) inline virtual
Called when a mouseDown event occurs on a control and the GUI editor is active.
Parameters
event the GuiEvent which caused the call to this function
offset the offset which is representative of the units x and y that the editor takes up on screen
Reimplemented in GuiTabBookCtrl, GuiScrollCtrl, and GuiTabPageCtrl.
virtual void GuiControl::onMouseDragged (const GuiEvent & event) virtual
Reimplemented in GuiTreeViewCtrl, GuiEditCtrl, GuiMLTextCtrl, GuiObjectView, GuiWindowCtrl, GuiTabBookCtrl, GuiScrollCtrl, GuiMenuBar, GuiShapeEdPreview, GuiColorPickerCtrl, GuiGameListMenuCtrl, GuiTextEditCtrl, GuiListBoxCtrl, GuiMissionAreaCtrl, GuiFrameSetCtrl, CreatorTree, GuiButtonBaseCtrl, GuiParticleGraphCtrl, GuiArrayCtrl, DbgFileView, GuiSliderCtrl, GuiMaterialPreview, GuiSplitContainer, GuiPopupMenuBackgroundCtrl, GuiDragAndDropControl, GuiFilterCtrl, GuiTextEditSliderCtrl, GuiTextEditSliderBitmapCtrl, GuiInspector, GuiMouseEventCtrl, EditTSCtrl, GuiDecoyCtrl, GuiRectHandles, GuiMenuBackgroundCtrl, and GuiGradientSwatchCtrl.
virtual bool GuiControl::onMouseDraggedEditor (const GuiEvent & event, Point2I offset) inline virtual
Called when a mouseDragged event occurs on a control and the GUI editor is active.
Parameters
event the GuiEvent which caused the call to this function
offset the offset which is representative of the units x and y that the editor takes up on screen
References clearFirstResponder(), controlIsChild(), findFirstTabable(), findLastTabable(), findNextTabable(), findPrevTabable(), isFirstResponder(), makeFirstResponder(), and setFirstResponder().
virtual void GuiControl::onMouseEnter (const GuiEvent & event) virtual
Reimplemented in GuiTreeViewCtrl, GuiObjectView, GuiColorPickerCtrl, GuiPopUpMenuCtrlEx, GuiPopUpMenuCtrl, GuiGradientCtrl, GuiMissionAreaCtrl, GuiFormCtrl, GuiButtonBaseCtrl, GuiPaneControl, GuiArrayCtrl, GuiSliderCtrl, GuiMaterialPreview, GuiMouseEventCtrl, EditTSCtrl, and GuiDecoyCtrl.
virtual void GuiControl::onMouseLeave (const GuiEvent & event) virtual
Reimplemented in GuiTreeViewCtrl, GuiObjectView, GuiTabBookCtrl, GuiMenuBar, GuiColorPickerCtrl, GuiGameListMenuCtrl, GuiPopUpMenuCtrlEx, GuiPopUpMenuCtrl, GuiGradientCtrl, GuiMissionAreaCtrl, GuiFormCtrl, GuiButtonBaseCtrl, GuiPaneControl, GuiArrayCtrl, GuiSliderCtrl, GuiMaterialPreview, GuiMouseEventCtrl, EditTSCtrl, and GuiDecoyCtrl.
virtual void GuiControl::onMouseMove (const GuiEvent & event) virtual
Reimplemented in GuiTreeViewCtrl, GuiWindowCtrl, GuiTabBookCtrl, GuiMenuBar, GuiShapeEdPreview, GuiGameListMenuCtrl, GuiColorPickerCtrl, GuiInspectorMountingGroup, GuiMissionAreaCtrl, GuiFormCtrl, GuiPaneControl, GuiParticleGraphCtrl, GuiArrayCtrl, GuiPopupMenuBackgroundCtrl, GuiPopupTextListCtrlEx, GuiInspector, GameTSCtrl, GuiMouseEventCtrl, GuiInspectorEntityGroup, EditTSCtrl, GuiDecoyCtrl, GuiInspectorComponentGroup, and GuiMenuBackgroundCtrl.
Referenced by GuiInspectorMountingGroup::GuiInspectorMountingGroup().
virtual void GuiControl::onMouseUp (const GuiEvent & event) virtual
Reimplemented in GuiTreeViewCtrl, GuiEditCtrl, GuiMLTextCtrl, GuiWindowCtrl, GuiObjectView, GuiTabBookCtrl, GuiScrollCtrl, GuiMenuBar, GuiShapeEdPreview, GuiGameListMenuCtrl, GuiColorPickerCtrl, GuiPopUpMenuCtrlEx, GuiPopUpMenuCtrl, GuiRolloutCtrl, GuiTextEditCtrl, GuiListBoxCtrl, GuiGradientCtrl, GuiMissionAreaCtrl, CreatorTree, GuiFormCtrl, GuiFrameSetCtrl, GuiButtonBaseCtrl, GuiParticleGraphCtrl, GuiPaneControl, GuiArrayCtrl, DbgFileView, GuiGameListOptionsCtrl, GuiSliderCtrl, GuiMaterialPreview, GuiMenuTextListCtrl, GuiSplitContainer, GuiDragAndDropControl, GuiMessageVectorCtrl, GuiFilterCtrl, GuiPopupTextListCtrl, GuiPopupTextListCtrlEx, GuiTextEditSliderCtrl, GuiTextEditSliderBitmapCtrl, ForestEditorCtrl, GuiInspector, GuiPopupMenuTextListCtrl, GameTSCtrl, GuiMouseEventCtrl, GuiRectHandles, EditTSCtrl, and GuiDecoyCtrl.
virtual bool GuiControl::onMouseUpEditor (const GuiEvent & event, Point2I offset) inline virtual
Called when a mouseUp event occurs on a control and the GUI editor is active.
Parameters
event the GuiEvent which caused the call to this function
offset the offset which is representative of the units x and y that the editor takes up on screen
Reimplemented in GuiRolloutCtrl.
virtual bool GuiControl::onMouseWheelDown (const GuiEvent & event) virtual
Reimplemented in TerrainEditor, GuiScrollCtrl, GuiSliderCtrl, GuiMaterialPreview, ForestEditorCtrl, GuiTextEditSliderCtrl, GuiTextEditSliderBitmapCtrl, EditTSCtrl, and GuiDecoyCtrl.
virtual bool GuiControl::onMouseWheelUp (const GuiEvent & event) virtual
Reimplemented in TerrainEditor, GuiScrollCtrl, GuiSliderCtrl, GuiMaterialPreview, ForestEditorCtrl, GuiTextEditSliderCtrl, GuiTextEditSliderBitmapCtrl, EditTSCtrl, and GuiDecoyCtrl.
virtual void GuiControl::onPreRender () virtual
Do special pre-render processing.
Reimplemented in GuiTreeViewCtrl, TerrainEditor, GuiMLTextCtrl, GuiEditCtrl, GuiScrollCtrl, GuiMenuBar, GuiTextEditCtrl, GuiContainer, GuiTSCtrl, DbgFileView, GuiTerrPreviewCtrl, GuiFilterCtrl, GuiTextCtrl, GuiConsoleTextCtrl, GuiTextEditSliderBitmapCtrl, GuiTextEditSliderCtrl, GuiFadeinBitmapCtrl, GuiProgressBitmapCtrl, GuiConsole, GuiProgressCtrl, and GuiToggleButtonCtrl.
Referenced by setBounds().
virtual void GuiControl::onRemove () virtual
Called when this object is removed.
Reimplemented from SimGroup.
Reimplemented in GuiEditCtrl, GuiCanvas, EditTSCtrl, GuiTextListCtrl, OpenVROverlay, GuiMessageVectorCtrl, GuiConvexEditorCtrl, GuiInspector, and GuiOffscreenCanvas.
Referenced by setBounds().
virtual void GuiControl::onRender (Point2I offset, const RectI & updateRect) virtual
Called when this control is to render itself.
Parameters
offset The location this control is to begin rendering
updateRect The screen area this control has drawing access to
Reimplemented in GuiTreeViewCtrl, GuiMLTextCtrl, GuiWindowCtrl, GuiEditCtrl, GuiScrollCtrl, GuiMenuBar, GuiInspectorField, EditTSCtrl, GuiRolloutCtrl, GuiBitmapButtonCtrl, GuiTextEditCtrl, GuiPopUpMenuCtrlEx, GuiPopUpMenuCtrl, GuiTabBookCtrl, GuiListBoxCtrl, GuiTSCtrl, GuiGradientCtrl, GuiColorPickerCtrl, GuiMissionAreaCtrl, GuiIconButtonCtrl, GuiGameListMenuCtrl, GuiParticleGraphCtrl, GuiFrameSetCtrl, GuiPaneControl, GuiSliderCtrl, GuiFormCtrl, GuiArrayCtrl, GuiGameListOptionsCtrl, GuiTerrPreviewCtrl, GuiFilterCtrl, GuiTextCtrl, GuiSplitContainer, GuiRiverEditorCtrl, GuiGraphCtrl, GuiFadeinBitmapCtrl, GuiConsoleTextCtrl, GuiTextEditSliderBitmapCtrl, GuiTextEditSliderCtrl, GuiNavEditorCtrl, GuiProgressBitmapCtrl, GuiMessageVectorCtrl, GuiBitmapCtrl, GuiTabPageCtrl, GuiRoadEditorCtrl, GuiToolboxButtonCtrl, GuiMaterialCtrl, GameTSCtrl, GuiSwatchButtonCtrl, GuiDecalEditorCtrl, GuiSeparatorCtrl, guiAnimBitmapCtrl, GuiPanel, GuiRectHandles, GuiEaseViewCtrl, GuiProgressCtrl, GuiCheckBoxCtrl, GuiGradientSwatchCtrl, GuiMLTextEditCtrl, GuiBackgroundCtrl, GuiBitmapBarCtrl, GuiButtonCtrl, GuiToggleButtonCtrl, and GuiChunkedBitmapCtrl.
Referenced by setBounds().
virtual void GuiControl::onRightMouseDown (const GuiEvent & event) virtual
Reimplemented in GuiTreeViewCtrl, GuiEditCtrl, GuiObjectView, GuiShapeEdPreview, GuiParticleGraphCtrl, GuiArrayCtrl, GuiMaterialPreview, GuiDecoyCtrl, GuiMouseEventCtrl, EditTSCtrl, GameTSCtrl, and GuiGradientSwatchCtrl.
virtual bool GuiControl::onRightMouseDownEditor (const GuiEvent & event, Point2I offset) inline virtual
Called when a rightMouseDown event occurs on a control and the GUI editor is active.
Parameters
event the GuiEvent which caused the call to this function
offset the offset which is representative of the units x and y that the editor takes up on screen
virtual void GuiControl::onRightMouseDragged (const GuiEvent & event) virtual
Reimplemented in GuiObjectView, GuiShapeEdPreview, GuiParticleGraphCtrl, GuiMaterialPreview, GuiDecoyCtrl, GuiMouseEventCtrl, and EditTSCtrl.
virtual void GuiControl::onRightMouseUp (const GuiEvent & event) virtual
Reimplemented in GuiTreeViewCtrl, GuiObjectView, GuiTabBookCtrl, GuiShapeEdPreview, GuiInspectorField, GuiRolloutCtrl, GuiParticleGraphCtrl, GuiButtonBaseCtrl, GuiMaterialPreview, GuiDecoyCtrl, GuiMouseEventCtrl, EditTSCtrl, and GameTSCtrl.
virtual void GuiControl::onSleep () virtual
Called when this object is asked to sleep.
Reimplemented in GuiTreeViewCtrl, TerrainEditor, GuiMLTextCtrl, GuiWindowCtrl, GuiScrollCtrl, GuiEditCtrl, GuiBitmapButtonCtrl, GuiMenuBar, GuiTSCtrl, GuiAutoScrollCtrl, GuiPopUpMenuCtrlEx, GuiPopUpMenuCtrl, GuiMissionAreaCtrl, GuiIconButtonCtrl, GuiFormCtrl, GuiStackControl, GuiRiverEditorCtrl, GuiNavEditorCtrl, GuiMessageVectorCtrl, GuiTerrPreviewCtrl, GuiMeshRoadEditorCtrl, GuiArrayCtrl, GuiRoadEditorCtrl, ForestEditorCtrl, GuiConsoleTextCtrl, GuiBitmapCtrl, GuiConvexEditorCtrl, GuiDecalEditorCtrl, GuiMaterialCtrl, GuiToolboxButtonCtrl, GuiControlArrayControl, GuiEaseViewCtrl, GuiTabPageCtrl, EditManager, GuiInputCtrl, and GuiChunkedBitmapCtrl.
Referenced by setBounds().
virtual bool GuiControl::onWake () virtual
Called when this object is asked to wake up returns true if it's actually awake at the end.
Reimplemented in GuiTreeViewCtrl, TerrainEditor, GuiMLTextCtrl, GuiWindowCtrl, GuiObjectView, GuiScrollCtrl, GuiEditCtrl, GuiShapeEdPreview, GuiFrameSetCtrl, GuiBitmapButtonCtrl, GuiMenuBar, GuiTSCtrl, GuiAutoScrollCtrl, GuiRolloutCtrl, GuiTabBookCtrl, GuiPopUpMenuCtrlEx, GuiPopUpMenuCtrl, GuiListBoxCtrl, GuiGameListMenuCtrl, GuiMissionAreaCtrl, GuiParticleGraphCtrl, CreatorTree, GuiIconButtonCtrl, GuiFormCtrl, GuiPaneControl, GuiTextListCtrl, GuiSliderCtrl, GuiButtonBaseCtrl, GuiStackControl, GuiMaterialPreview, DbgFileView, GuiDirectoryFileListCtrl, GuiFadeinBitmapCtrl, GuiSplitContainer, GuiTextEditSliderBitmapCtrl, GuiProgressBitmapCtrl, GuiFilterCtrl, GuiMessageVectorCtrl, GuiTerrPreviewCtrl, GuiArrayCtrl, ForestEditorCtrl, GuiConsoleTextCtrl, GuiBitmapCtrl, GuiConsole, GuiTextCtrl, GuiConvexEditorCtrl, GuiSwatchButtonCtrl, GuiFileTreeCtrl, GuiDecalEditorCtrl, GuiMaterialCtrl, GuiToolboxButtonCtrl, GuiMLTextEditCtrl, GuiControlArrayControl, GuiEaseViewCtrl, GuiCheckBoxCtrl, GuiGradientSwatchCtrl, GuiTabPageCtrl, EditManager, GuiInputCtrl, GuiButtonCtrl, and GuiChunkedBitmapCtrl.
Referenced by setBounds().
virtual void GuiControl::parentResized (const RectI & oldParentRect, const RectI & newParentRect) virtual
Called when this objects parent is resized.
Parameters
oldParentRect The old rectangle of the parent object
newParentRect The new rectangle of the parent object
Reimplemented in GuiMLTextCtrl, GuiWindowCtrl, GuiContainer, GuiListBoxCtrl, GuiSliderCtrl, GuiSplitContainer, GuiMessageVectorCtrl, GuiScriptNotifyCtrl, and GuiInspector.
Referenced by setBounds().
virtual bool GuiControl::pointInControl (const Point2I & parentCoordPoint) virtual
This function will return true if the provided coordinates (wrt parent object) are within the bounds of this control.
Parameters
parentCoordPoint Coordinates to test
Reimplemented in GuiBitmapButtonCtrl, and GuiSubmenuBackgroundCtrl.
Referenced by setBounds().
void GuiControl::preRender ()
Pre-render this control and all its children.
Referenced by setBounds().
virtual bool GuiControl::processArguments (S32 argc, ConsoleValueRef * argv) virtual
Process constructor options. (ie, new SimObject(1,2,3))
Reimplemented from SimGroup.
Referenced by _setActive().
void GuiControl::removeObject (SimObject * obj) virtual
Removes a child object from this control.
Parameters
obj Object to remove from this control
Reimplemented from SimGroup.
Referenced by isAwake().
void GuiControl::renderChildControls (Point2I offset, const RectI & updateRect)
Called when this control should render its children.
Parameters
offset The location this control is to begin rendering
updateRect The screen area this control has drawing access to
Referenced by setBounds().
void GuiControl::renderJustifiedText (Point2I offset, Point2I extent, const char * text)
Renders justified text using the profile.
Note
This should move into the graphics library at some point
Referenced by getControlProfile().
virtual bool GuiControl::resize (const Point2I & newPosition, const Point2I & newExtent) virtual
Changes the size and/or position of this control.
Parameters
newPosition New position of this control
newExtent New size of this control
Reimplemented in GuiInspectorTypeBitMask32Helper, GuiInspectorTypeBitMask32, GuiInspectorTypeColor, GuiInspectorTypeEaseF, GuiMLTextCtrl, GuiInspectorTypeFileName, GuiTabBookCtrl, GuiScrollCtrl, GuiWindowCtrl, GuiInspectorField, GuiRolloutCtrl, GuiAutoScrollCtrl, GuiContainer, GuiInspectorMountingGroup, GuiIconButtonCtrl, GuiPaneControl, GuiFrameSetCtrl, GuiSliderCtrl, GuiFormCtrl, GuiSplitContainer, GuiStackControl, GuiScriptNotifyCtrl, GuiInspector, GuiDynamicCtrlArrayControl, GuiMLTextEditCtrl, and GuiControlArrayControl.
Referenced by isAwake().
virtual void GuiControl::setActive (bool value) virtual
Sets the status of this control as active and responding or inactive.
Parameters
value True if this is active
Reimplemented in GuiSliderCtrl.
Referenced by _setActive(), and setCanHit().
virtual bool GuiControl::setBounds (const RectI & newBounds) virtual
Changes the bounds of this control.
Parameters
newBounds New bounds of this control
Referenced by setBounds(), and setExtent().
void GuiControl::setBounds (const S32 left, const S32 top, const S32 width, const S32 height) inline
References awaken(), childResized(), cursorInControl(), findHitControl(), getScriptValue(), onAdd(), onChildAdded(), onChildRemoved(), onDeleteNotify(), onPreRender(), onRemove(), onRender(), onSleep(), onWake(), parentResized(), pointInControl(), preRender(), renderChildControls(), setBounds(), setHeight(), setLeft(), setScriptValue(), setTop(), setUpdate(), setUpdateRegion(), setWidth(), and sleep().
void GuiControl::setCanHit (bool value) inline
References setActive().
void GuiControl::setConsoleCommand (const String & newCmd)
Set the name of the console function bound to, such as a script function a button calls when clicked.
Parameters
newCmd Console function to attach to this GuiControl
void GuiControl::setConsoleVariable (const char * variable)
Set the name of the console variable which this GuiObject is bound to.
Parameters
variable Variable name
void GuiControl::setControlProfile (GuiControlProfile * prof)
Sets the control profile for this control.
See also
GuiControlProfile
Parameters
prof Control profile to apply
Referenced by getControlProfile().
virtual bool GuiControl::setExtent (const Point2I & newExtent) virtual
Changes the size of this control.
Parameters
newExtent New size of this control
Referenced by setPosition().
void GuiControl::setExtent (const S32 width, const S32 height) inline
References setBounds(), and setExtent().
Referenced by setExtent().
virtual void GuiControl::setFirstResponder (GuiControl * firstResponder) virtual
Sets the first responder for child controls.
Parameters
firstResponder First responder for this chain
Reimplemented in GuiCanvas, GuiInspectorField, and GuiScriptNotifyCtrl.
virtual void GuiControl::setFirstResponder () virtual
Sets this object to be a first responder.
Reimplemented in GuiTextEditCtrl, GuiScriptNotifyCtrl, and GuiMLTextEditCtrl.
Referenced by GuiInspectorField::getInspector(), GuiCanvas::mouseRightButtonDown(), and onMouseDraggedEditor().
void GuiControl::setFloatVariable (F32 value) protected
Sets the value of the console variable bound to this control.
Parameters
value Float value to assign to control's console variable
virtual void GuiControl::setHeight (S32 newHeight) virtual
Changes the height of this control.
Parameters
newHeight New Height of this control
Referenced by setBounds().
virtual void GuiControl::setHidden (bool state) inline virtual
Reimplemented from SimObject.
References setVisible().
void GuiControl::setIntVariable (S32 value) protected
Sets the value of the console variable bound to this control.
Parameters
value Integer value to assign to control's console variable
virtual void GuiControl::setLeft (S32 newLeft) virtual
Changes the X position of this control.
Parameters
newXPosition New X Position of this control
Referenced by setBounds().
virtual void GuiControl::setMinExtent (const Point2I & newMinExtent) inline virtual
virtual bool GuiControl::setPosition (const Point2I & newPosition) virtual
Changes the position of this control.
Parameters
newPosition New position of this control
Referenced by isAwake().
void GuiControl::setPosition (const S32 x, const S32 y) inline
References setExtent(), and setPosition().
Referenced by setPosition().
static bool GuiControl::setProfileProt (void * object, const char * index, const char * data) static protected
virtual void GuiControl::setScriptValue (const char * value) virtual
Sets the value of the variable bound to this object.
Reimplemented in GuiMLTextCtrl, GuiTextEditCtrl, GuiColorPickerCtrl, GuiButtonBaseCtrl, GuiSliderCtrl, GuiTextCtrl, GuiTextListCtrl, GuiConsoleTextCtrl, GuiProgressBitmapCtrl, and GuiProgressCtrl.
Referenced by setBounds().
void GuiControl::setSizing (S32 horz, S32 vert)
Sets the size of the GuiControl.
Parameters
horz Width of the control
vert Height of the control
Referenced by _setActive().
void GuiControl::setTooltipProfile (GuiControlProfile * prof)
Sets the tooltip profile for this control.
See also
GuiControlProfile
Parameters
prof Tooltip profile to apply
Referenced by getTooltipProfile().
static bool GuiControl::setTooltipProfileProt (void * object, const char * index, const char * data) static protected
virtual void GuiControl::setTop (S32 newTop) virtual
Changes the Y position of this control.
Parameters
newYPosition New Y Position of this control
Referenced by setBounds().
virtual void GuiControl::setUpdate () virtual
Sets the update area of the control to encompass the whole control.
Reimplemented in GuiTabBookCtrl.
Referenced by setBounds().
void GuiControl::setUpdateRegion (Point2I pos, Point2I ext)
Sets the area (local coordinates) this control wants refreshed each frame.
Parameters
pos UpperLeft point on rectangle of refresh area
ext Extent of update rect
Referenced by setBounds().
void GuiControl::setVariable (const char * value) protected
Sets the value of the console variable bound to this control.
Parameters
value String value to assign to control's console variable
virtual void GuiControl::setVisible (bool value) virtual
Sets the visibility of the control.
Parameters
value True if object should be visible
Reimplemented in GuiConvexEditorCtrl, and GuiPanel.
Referenced by _setVisible(), getVertSizing(), setHidden(), and GuiPanel::setVisible().
virtual void GuiControl::setWidth (S32 newWidth) virtual
Changes the width of this control.
Parameters
newWidth New width of this control
Referenced by setBounds().
void GuiControl::sleep ()
Called when this control is no more.
Referenced by setBounds().
void GuiControl::write (Stream & stream, U32 tabStop, U32 flags) virtual
Overrides Parent Serialization to allow specific controls to not be saved (Dynamic Controls, etc)
Reimplemented from SimSet.
Referenced by _setActive().
Member Data Documentation
StringTableEntry GuiControl::mAcceleratorKey protected
bool GuiControl::mActive protected
Referenced by GuiBitmapButtonCtrl::getState(), and isActive().
String GuiControl::mAltConsoleCommand protected
bool GuiControl::mAwake protected
Referenced by isAwake().
bool GuiControl::mCanHit protected
bool GuiControl::mCanResize protected
CollapseGroupVec GuiControl::mCollapseGroupVec protected
String GuiControl::mConsoleCommand protected
StringTableEntry GuiControl::mConsoleVariable protected
GFXStateBlockRef GuiControl::mDefaultGuiSB protected
GuiControl* GuiControl::mFirstResponder protected
Referenced by getFirstResponder().
S32 GuiControl::mHorizSizing protected
Set from horizSizingOptions.
Referenced by getHorizSizing().
bool GuiControl::mIsContainer protected
if true, then the GuiEditor can drag other controls into this one.
LangTable* GuiControl::mLangTable protected
StringTableEntry GuiControl::mLangTableName protected
S32 GuiControl::mLayer protected
Point2I GuiControl::mMinExtent protected
Referenced by getMinExtent().
bool GuiControl::mNotifyChildrenResized protected
GuiControlProfile* GuiControl::mProfile protected
The profile for this gui (data settings that are likely to be shared by multiple guis)
Referenced by getControlProfile(), Gizmo::getProfile(), and Gizmo::setProfile().
RenderTooltipDelegate GuiControl::mRenderTooltipDelegate protected
Delegate called to render a tooltip for this control.
By default this will be set to defaultTooltipRender.
Referenced by getRenderTooltipDelegate().
bool GuiControl::mSetFirstResponder protected
S32 GuiControl::mTipHoverTime protected
String GuiControl::mTooltip protected
Referenced by getTooltip().
GuiControlProfile* GuiControl::mTooltipProfile protected
The profile for any tooltips.
Referenced by getTooltipProfile().
S32 GuiControl::mVertSizing protected
Set from vertSizingOptions.
Referenced by getVertSizing().
bool GuiControl::mVisible protected
Referenced by isVisible().
GuiControl* GuiControl::smCurResponder static protected
bool GuiControl::smDesignTime static protected
static GuiControl boolean that specifies if the GUI Editor is active
GuiEditCtrl* GuiControl::smEditorHandle static protected
static GuiEditCtrl pointer that gives controls access to editor-NULL if editor is closed
GuiControl* GuiControl::smPrevResponder static protected
GuiControl* GuiControl::smThisControl static protected
$ThisControl variable for callback execution.
Copyright © GarageGames, LLC. All Rights Reserved.