EngineFunctionInfo Class Reference
Main Modules Class List Namespace List Online
EngineFunctionInfo Class Reference
A function exported by the engine for interfacing with the control layer.
#include <console/engineFunctions.h>
Public Member Functions
EngineFunctionInfo (const char *name, EngineExportScope *scope, const char *docString, const char *protoypeString, const char *bindingName, const EngineTypeInfo *functionType, const EngineFunctionDefaultArguments *defaultArgs, void *address, U32 flags)
DECLARE_CLASS (EngineFunctionInfo, EngineExport)
const EngineTypeInfo * getArgumentType (U32 index) const
const char * getBindingName () const
Return the DLL export symbol name.
const EngineFunctionDefaultArguments * getDefaultArguments () const
Return the vector storing the default argument values.
const char * getFunctionName () const
Return the name of the function.
const EngineTypeInfo * getFunctionType () const
Return the type of this function.
U32 getNumArguments () const
Return the number of arguments that this function takes.
const char * getPrototypeString () const
Return the function's full prototype string including the return type, function name, and argument list.
const EngineTypeInfo * getReturnType () const
Return the return type of the function.
bool isCallout () const
Test whether this is a callout function.
bool isVariadic () const
Test whether the function is variadic, i.e. takes a variable number of arguments.
Public Member Functions inherited from EngineExport
DECLARE_ABSTRACT_CLASS (EngineExport, StaticEngineObject)
DECLARE_INSCOPE (ReflectionAPI)
const char * getDocString () const
Return the documentation string for this type.
EngineExportKind getExportKind () const
Return the kind of entity being exported.
const char * getExportName () const
Return the name of the export.
EngineExportScope * getExportScope () const
Return the scope that contains this export.
String getFullyQualifiedExportName () const
Return the fully qualified name of this export starting from the global export scope.
EngineExport * getNextExport () const
Get the next export in the link chain of the export's associated scope.
Public Member Functions inherited from StaticEngineObject
StaticEngineObject ()
DECLARE_ABSTRACT_CLASS (StaticEngineObject, EngineObject)
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
Public Member Functions inherited from EngineObject
EngineObject ()
virtual ~EngineObject ()
DECLARE_ABSTRACT_CLASS (EngineObject, void)
DECLARE_INSCOPE (_GLOBALSCOPE)
virtual String describeSelf () const
Return a string that describes this instance. Meant primarily for debugging.
IEngineObjectPool * getEngineObjectPool () const
Return the pool of EngineObjects to which this object belongs.
void operator delete (void *ptr)
Release the given object's memory in the pool it has been allocated from.
void * operator new (size_t size)
void * operator new (size_t size, IEngineObjectPool *pool)
void * operator new (size_t size TORQUE_TMM_ARGS_DECL)
Allocate a new object in the default object pool.
void * operator new (size_t size, IEngineObjectPool *pool TORQUE_TMM_ARGS_DECL)
Allocate a new object in the given object pool.
void * operator new (size_t size, void *ptr)
Placement new.
Public Member Functions inherited from StrongRefBase
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Static Public Member Functions
static void resetAllCallouts ()
Reset all callout function pointers back to NULL. This deactivates all callbacks.
Static Public Member Functions inherited from EngineObject
static void debugDumpInstances ()
Dump describeSelf()s of all live ConsoleObjects to the console.
static void debugEnumInstances (const std::type_info &type, DebugEnumInstancesCallback callback)
Call the given callback for all instances of the given type.
static void debugEnumInstances (const char *className, DebugEnumInstancesCallback callback)
Same as above but uses an export class name and also includes inheritance (i.e.
Protected Attributes
void * mAddress
Address of either the function implementation or the variable taking the address of a call-out.
const char * mBindingName
Name of the DLL symbol denoting the address of the exported entity.
const EngineFunctionDefaultArguments * mDefaultArgumentValues
Default values for the function arguments.
BitSet32 mFunctionFlags
A combination of EngineFunctionFlags.
const EngineTypeInfo * mFunctionType
The type of the function.
EngineFunctionInfo * mNextFunction
Next function in the global link chain of engine functions.
const char * mPrototypeString
Full function prototype string.
Protected Attributes inherited from EngineExport
const char * mDocString
Documentation string.
EngineExportKind mExportKind
Kind of export.
const char * mExportName
Name of the export.
EngineExportScope * mExportScope
The scope in which this export is defined.
EngineExport * mNextExport
Next export in the link chain of the export's scope.
Protected Attributes inherited from EngineObject
DEFINE_CREATE_METHOD
return object
Protected Attributes inherited from StrongRefBase
U32 mRefCount
reference counter for StrongRefPtr objects
Static Protected Attributes
static EngineFunctionInfo * smFirstFunction
First function in the global link chain of engine functions.
Additional Inherited Members
Public Types inherited from EngineObject
typedef void(* DebugEnumInstancesCallback) (EngineObject *)
Type of callback function for iterating over EngineObject instances.
Public Attributes inherited from StaticEngineObject
DECLARE_NONINSTANTIABLE
Public Attributes inherited from EngineObject
DECLARE_INSTANTIABLE
Protected Types inherited from EngineObject
typedef ::FalseType __IsDisposableType
typedef ::FalseType __IsSingletonType
Protected Member Functions inherited from EngineExport
EngineExport (const char *name, EngineExportKind kind, EngineExportScope *scope, const char *docString)
Protected constructor as this is an abstract class.
Protected Member Functions inherited from EngineObject
virtual void _destroySelf ()
Subclasses should overload this method instead of the public destroySelf().
object incRefCount ()
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Static Protected Member Functions inherited from EngineObject
static void * _allocateObject (size_t size, IEngineObjectPool *pool TORQUE_TMM_ARGS_DECL)
Detailed Description
A function exported by the engine for interfacing with the control layer.
A function can either be a call-in, transfering control flow from the control layer to the engine, or a call-out, transfering control flow from the engine to the control layer.
All engine API functions use the native C (cdecl) calling convention.
Be aware that there a no implicit parameters to functions. This, for example, means that methods will simply list an object type parameter as their first argument but otherwise be indistinguishable from other functions.
Variadic functions are supported.
String Arguments and Return Values
Strings passed through the API are assumed to be owned by the caller. They must persist for the entire duration of a call.
Strings returned by a function are assumed to be in transient storage that will be overwritten by subsequent API calls. If the caller wants to preserve a string, it is responsible to copying strings to its own memory. This will happen with most higher-level control layers anyway.
Default Arguments
As the engine API export system is set up to not require hand-written code in generated wrappers per se, the export system seeks to include a maximum possible amount of information in the export structures. To this end, where applicable, information about suggested default values for arguments to the engine API functions is stored in the export structures. It is up to the wrapper generator if and how it makes use of this information.
Default arguments are represented by capturing raw stack frame vectors of the arguments to functions. These frames could be used as default images for passing arguments in stack frames, though wrapper generators may actually want to read out individual argument values and include them in function prototypes within the generated code.
Call-ins
Call-ins are exposed as native entry points. The control layer must be able to natively marshall arguments and call DLL function exports using C calling conventions.
Call-outs
Call-outs are exposed as pointer-sized memory locations into which the control layer needs to install addresses of functions that receive the call from the engine back into the control layer. The function has to follow C calling conventions and
A call-out will initially be set to NULL and while being NULL, will simply cause the engine to skip and ignore the call-out. This allows the control layer to only install call-outs it is actually interested in.
Constructor & Destructor Documentation
EngineFunctionInfo::EngineFunctionInfo (const char * name, EngineExportScope * scope, const char * docString, const char * protoypeString, const char * bindingName, const EngineTypeInfo * functionType, const EngineFunctionDefaultArguments * defaultArgs, void * address, U32 flags)
Member Function Documentation
EngineFunctionInfo::DECLARE_CLASS (EngineFunctionInfo , EngineExport)
const EngineTypeInfo* EngineFunctionInfo::getArgumentType (U32 index) const inline
const char* EngineFunctionInfo::getBindingName () const inline
Return the DLL export symbol name.
const EngineFunctionDefaultArguments* EngineFunctionInfo::getDefaultArguments () const inline
Return the vector storing the default argument values.
const char* EngineFunctionInfo::getFunctionName () const inline
Return the name of the function.
const EngineTypeInfo* EngineFunctionInfo::getFunctionType () const inline
Return the type of this function.
U32 EngineFunctionInfo::getNumArguments () const inline
Return the number of arguments that this function takes.
If the function is variadic, this is the number of fixed arguments.
const char* EngineFunctionInfo::getPrototypeString () const inline
Return the function's full prototype string including the return type, function name, and argument list.
const EngineTypeInfo* EngineFunctionInfo::getReturnType () const inline
Return the return type of the function.
References EngineTypeInfo::getArgumentTypeTable(), and EngineArgumentTypeTable::getReturnType().
bool EngineFunctionInfo::isCallout () const inline
Test whether this is a callout function.
References BitSet32::test().
bool EngineFunctionInfo::isVariadic () const inline
Test whether the function is variadic, i.e. takes a variable number of arguments.
References EngineTypeInfo::isVariadic().
static void EngineFunctionInfo::resetAllCallouts () static
Reset all callout function pointers back to NULL. This deactivates all callbacks.
Member Data Documentation
void* EngineFunctionInfo::mAddress protected
Address of either the function implementation or the variable taking the address of a call-out.
const char* EngineFunctionInfo::mBindingName protected
Name of the DLL symbol denoting the address of the exported entity.
const EngineFunctionDefaultArguments* EngineFunctionInfo::mDefaultArgumentValues protected
Default values for the function arguments.
BitSet32 EngineFunctionInfo::mFunctionFlags protected
A combination of EngineFunctionFlags.
const EngineTypeInfo* EngineFunctionInfo::mFunctionType protected
The type of the function.
EngineFunctionInfo* EngineFunctionInfo::mNextFunction protected
Next function in the global link chain of engine functions.
const char* EngineFunctionInfo::mPrototypeString protected
Full function prototype string.
Useful for quick printing and most importantly, this will be the only place containing information about the argument names.
EngineFunctionInfo* EngineFunctionInfo::smFirstFunction static protected
First function in the global link chain of engine functions.
Copyright © GarageGames, LLC. All Rights Reserved.