Transform3DInPlace Class Reference
Main Modules Class List Namespace List Online
Transform3DInPlace Class Reference
#include <T3D/sceneComponent/T3DTransform.h>
Public Member Functions
Transform3DInPlace ()
void getLocalMatrix (MatrixF &localMat, bool includeLocalScale) const
void getObjectMatrix (MatrixF &objectMat, bool includeLocalScale) const
Point3F getPosition () const
QuatF getRotation () const
Point3F getScale () const
void getWorldMatrix (MatrixF &worldMat, bool includeLocalScale) const
void setLocalMatrix (const MatrixF &localMat)
void setPosition (const Point3F &position)
void setRotation (const QuatF &rotation)
void setScale (const Point3F &scale)
Public Member Functions inherited from Transform3D
IDirtyListener * getDirtyListener () const
MatrixF getLocalMatrix () const
MatrixF getObjectMatrix () const
Transform3D * getParentTransform () const
MatrixF getWorldMatrix () const
bool hasLocalScale () const
bool hasObjectScale () const
bool hasWorldScale () const
bool isChildOf (Transform3D *parent, bool recursive) const
void setDirtyListener (IDirtyListener *dirtyListener)
void setObjectMatrix (const MatrixF &objMatrix)
void setParentTransform (Transform3D *parent)
void setWorldMatrix (const MatrixF &world)
Protected Attributes
Point3F _position
QuatF _rotation
Point3F _scale
Protected Attributes inherited from Transform3D
IDirtyListener * _dirtyListener
U32 _flags
Transform3D * _parentTransform
Additional Inherited Members
Protected Types inherited from Transform3D
enum TransformFlags {
None = 0,
LocalHasScale = 1 << 0,
LocalPositionDirty = 1 << 1,
LocalRotationDirty = 1 << 2,
LocalScaleDirty = 1 << 3,
LocalDirty = LocalPositionDirty | LocalRotationDirty | LocalScaleDirty,
ParentDirty = 1 << 4,
LastFlag = 1 << 4
}
Constructor & Destructor Documentation
Transform3DInPlace::Transform3DInPlace () inline
References Transform3D::getLocalMatrix(), Transform3D::getObjectMatrix(), Transform3D::getPosition(), Transform3D::getRotation(), Transform3D::getScale(), Transform3D::getWorldMatrix(), Transform3D::setLocalMatrix(), Transform3D::setPosition(), Transform3D::setRotation(), and Transform3D::setScale().
Member Function Documentation
void Transform3DInPlace::getLocalMatrix (MatrixF & localMat, bool includeLocalScale) const virtual
Implements Transform3D.
void Transform3DInPlace::getObjectMatrix (MatrixF & objectMat, bool includeLocalScale) const virtual
Implements Transform3D.
Point3F Transform3DInPlace::getPosition () const virtual
Implements Transform3D.
QuatF Transform3DInPlace::getRotation () const virtual
Implements Transform3D.
Point3F Transform3DInPlace::getScale () const virtual
Implements Transform3D.
void Transform3DInPlace::getWorldMatrix (MatrixF & worldMat, bool includeLocalScale) const virtual
Implements Transform3D.
void Transform3DInPlace::setLocalMatrix (const MatrixF & localMat) virtual
Implements Transform3D.
void Transform3DInPlace::setPosition (const Point3F & position) virtual
Implements Transform3D.
void Transform3DInPlace::setRotation (const QuatF & rotation) virtual
Implements Transform3D.
void Transform3DInPlace::setScale (const Point3F & scale) virtual
Implements Transform3D.
Member Data Documentation
Point3F Transform3DInPlace::_position protected
QuatF Transform3DInPlace::_rotation protected
Point3F Transform3DInPlace::_scale protected
Copyright © GarageGames, LLC. All Rights Reserved.