SimEvent Class Reference
Main Modules Class List Namespace List Online
SimEvent Class Reference abstract
Represents a queued event in the sim.
#include <console/simEvents.h>
Public Member Functions
SimEvent ()
virtual ~SimEvent ()
Destructor.
virtual void process (SimObject *object)=0
A dummy virtual destructor is required so that subclasses can be deleted properly.
Public Attributes
SimObject * destObject
of addition to the list.
SimEvent * nextEvent
Linked list details - pointer to next item in the list.
U32 sequenceCount
Unique ID.
SimTime startTime
When the event was posted.
SimTime time
When the event is scheduled to occur.
Detailed Description
Represents a queued event in the sim.
Sim provides an event queue for your convenience, which can be used to schedule events. A few things which use this event queue:
- The scene lighting system. In order to keep the game
  responsive while scene lighting occurs, the lighting
  process is divided into little chunks. In implementation
  terms, there is a subclass of SimEvent called
  SceneLightingProcessEvent. The process method of this
  subclass calls into the lighting code, telling it to
  perform the next chunk of lighting calculations.
- The schedule() console function uses a subclass of
  SimEvent called SimConsoleEvent to keep track of
  scheduled events.
Constructor & Destructor Documentation
SimEvent::SimEvent () inline
virtual SimEvent::~SimEvent () inline virtual
Destructor.
References process().
Member Function Documentation
virtual void SimEvent::process (SimObject * object) pure virtual
A dummy virtual destructor is required so that subclasses can be deleted properly.
Function called when event occurs.
This is where the meat of your event's implementation goes.
See any of the subclasses for ideas of what goes in here.
The event is deleted immediately after processing. If the object referenced in destObject is deleted, then the event is not called. The even will be executed unconditionally if the object referenced is NULL.
Parameters
object Object stored in destObject.
Implemented in sgSceneLightingProcessEvent, SimDelegateEvent, SimConsoleThreadExecEvent, ForestBrushToolEvent, SimConsoleEvent, and DecalRoadUpdateEvent.
Referenced by SimConsoleThreadExecEvent::getCB(), and ~SimEvent().
Member Data Documentation
SimObject* SimEvent::destObject
of addition to the list.
Object on which this event will be applied.
SimEvent* SimEvent::nextEvent
Linked list details - pointer to next item in the list.
U32 SimEvent::sequenceCount
Unique ID.
These are assigned sequentially based on order
SimTime SimEvent::startTime
When the event was posted.
SimTime SimEvent::time
When the event is scheduled to occur.
Copyright © GarageGames, LLC. All Rights Reserved.