PhysicsPlayer Class Reference
Main Modules Class List Namespace List Online
PhysicsPlayer Class Reference abstract
#include <T3D/physics/physicsPlayer.h>
Public Member Functions
PhysicsPlayer ()
virtual ~PhysicsPlayer ()
virtual void disableCollision ()=0
virtual void enableCollision ()=0
virtual void findContact (SceneObject **contactObject, VectorF *contactNormal, Vector< SceneObject * > *outOverlapObjects) const =0
virtual void init (const char *type, const Point3F &size, F32 runSurfaceCos, F32 stepHeight, SceneObject *obj, PhysicsWorld *world)=0
virtual Point3F move (const VectorF &displacement, CollisionList &outCol)=0
virtual void setSpacials (const Point3F &nPos, const Point3F &nSize)=0
virtual bool testSpacials (const Point3F &nPos, const Point3F &nSize) const =0
Public Member Functions inherited from PhysicsObject
virtual ~PhysicsObject ()
virtual MatrixF & getTransform (MatrixF *outMatrix)=0
Returns the transform of the physics body at the last processed simulation tick.
const PhysicsUserData & getUserData () const
PhysicsUserData & getUserData ()
virtual PhysicsWorld * getWorld ()=0
Returns the physics world this object is a member of.
virtual Box3F getWorldBounds ()=0
Returns the world aligned bounding box containing the PhysicsObject.
virtual bool isSimulationEnabled ()=0
void queueCallback (U32 ms, Delegate< void()> callback)
virtual void setSimulationEnabled (bool enabled)=0
Set false to skip simulation of this object or temporarily remove it from the physics simulation.
virtual void setTransform (const MatrixF &transform)=0
Sets the transform on the physics object.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Additional Inherited Members
Protected Member Functions inherited from PhysicsObject
PhysicsObject ()
You shouldn't be creating this object directly.
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Protected Attributes inherited from PhysicsObject
U32 mQueuedEvent
The last queued callback event.
PhysicsUserData mUserData
The user data object assigned to this object.
Constructor & Destructor Documentation
PhysicsPlayer::PhysicsPlayer () inline
virtual PhysicsPlayer::~PhysicsPlayer () inline virtual
References disableCollision(), enableCollision(), findContact(), init(), move(), setSpacials(), and testSpacials().
Member Function Documentation
virtual void PhysicsPlayer::disableCollision () pure virtual
Implemented in BtPlayer, and Px3Player.
Referenced by ~PhysicsPlayer().
virtual void PhysicsPlayer::enableCollision () pure virtual
Implemented in BtPlayer, and Px3Player.
Referenced by ~PhysicsPlayer().
virtual void PhysicsPlayer::findContact (SceneObject ** contactObject, VectorF * contactNormal, Vector< SceneObject * > * outOverlapObjects) const pure virtual
Implemented in BtPlayer, and Px3Player.
Referenced by ~PhysicsPlayer().
virtual void PhysicsPlayer::init (const char * type, const Point3F & size, F32 runSurfaceCos, F32 stepHeight, SceneObject * obj, PhysicsWorld * world) pure virtual
Implemented in BtPlayer, and Px3Player.
Referenced by ~PhysicsPlayer().
virtual Point3F PhysicsPlayer::move (const VectorF & displacement, CollisionList & outCol) pure virtual
Implemented in BtPlayer, and Px3Player.
Referenced by ~PhysicsPlayer().
virtual void PhysicsPlayer::setSpacials (const Point3F & nPos, const Point3F & nSize) pure virtual
Implemented in BtPlayer, and Px3Player.
Referenced by ~PhysicsPlayer().
virtual bool PhysicsPlayer::testSpacials (const Point3F & nPos, const Point3F & nSize) const pure virtual
Implemented in BtPlayer, and Px3Player.
Referenced by ~PhysicsPlayer().
Copyright © GarageGames, LLC. All Rights Reserved.