BanList Class Reference
Main Modules Class List Namespace List Online
BanList Class Reference
Helper class to keep track of bans.
#include <app/banList.h>
Classes
struct BanInfo
Public Member Functions
BanList ()
void addBan (S32 uniqueId, const char *TA, S32 banTime)
void addBanRelative (S32 uniqueId, const char *TA, S32 numSeconds)
DECLARE_STATIC_CLASS (BanList)
void exportToFile (const char *fileName)
bool isBanned (S32 uniqueId, const char *TA)
bool isTAEq (const char *bannedTA, const char *TA)
void removeBan (S32 uniqueId, const char *TA)
Static Public Member Functions
static BanList * instance ()
Protected Attributes
Vector< BanInfo > list
Static Protected Attributes
static BanList * smInstance
Detailed Description
Helper class to keep track of bans.
Constructor & Destructor Documentation
BanList::BanList ()
Member Function Documentation
void BanList::addBan (S32 uniqueId, const char * TA, S32 banTime)
Referenced by instance().
void BanList::addBanRelative (S32 uniqueId, const char * TA, S32 numSeconds)
Referenced by instance().
BanList::DECLARE_STATIC_CLASS (BanList)
void BanList::exportToFile (const char * fileName)
Referenced by instance().
static BanList* BanList::instance () inline static
References addBan(), addBanRelative(), exportToFile(), isBanned(), isTAEq(), removeBan(), smInstance, and BanList::BanInfo::uniqueId.
bool BanList::isBanned (S32 uniqueId, const char * TA)
Referenced by instance().
bool BanList::isTAEq (const char * bannedTA, const char * TA)
Referenced by instance().
void BanList::removeBan (S32 uniqueId, const char * TA)
Referenced by instance().
Member Data Documentation
Vector< BanInfo > BanList::list protected
BanList* BanList::smInstance static protected
Referenced by instance().
Copyright © GarageGames, LLC. All Rights Reserved.