Torque::ByteBuffer Class Reference
Main Modules Class List Namespace List Online
Torque::ByteBuffer Class Reference
#include <core/util/byteBuffer.h>
Public Member Functions
ByteBuffer ()
ByteBuffer (U8 *dataPtr, U32 bufferSize)
Create a ByteBuffer from a chunk of memory.
ByteBuffer (U32 bufferSize)
Create a ByteBuffer of the specified size.
ByteBuffer (const ByteBuffer &theBuffer)
Copy constructor.
~ByteBuffer ()
void appendBuffer (const U8 *dataBuffer, U32 bufferSize)
Appends the specified buffer to the end of the byte buffer.
void appendBuffer (const ByteBuffer &theBuffer)
Appends the specified ByteBuffer to the end of this byte buffer.
void clear ()
Clear the buffer.
U8 * getBuffer ()
const U8 * getBuffer () const
U32 getBufferSize () const
ByteBuffer getCopy () const
Copy the data in the buffer.
ByteBuffer & operator= (const ByteBuffer &theBuffer)
void resize (U32 newBufferSize)
Resize the buffer.
void setBuffer (U8 *dataPtr, U32 bufferSize, bool copyData)
Set the ByteBuffer to point to a new chunk of memory.
Constructor & Destructor Documentation
Torque::ByteBuffer::ByteBuffer ()
Torque::ByteBuffer::ByteBuffer (U8 * dataPtr, U32 bufferSize)
Create a ByteBuffer from a chunk of memory.
Torque::ByteBuffer::ByteBuffer (U32 bufferSize)
Create a ByteBuffer of the specified size.
Torque::ByteBuffer::ByteBuffer (const ByteBuffer & theBuffer)
Copy constructor.
Torque::ByteBuffer::~ByteBuffer ()
Member Function Documentation
void Torque::ByteBuffer::appendBuffer (const U8 * dataBuffer, U32 bufferSize)
Appends the specified buffer to the end of the byte buffer.
Referenced by appendBuffer().
void Torque::ByteBuffer::appendBuffer (const ByteBuffer & theBuffer) inline
Appends the specified ByteBuffer to the end of this byte buffer.
References appendBuffer(), clear(), getBuffer(), getBufferSize(), and getCopy().
void Torque::ByteBuffer::clear ()
Clear the buffer.
Referenced by appendBuffer().
U8* Torque::ByteBuffer::getBuffer ()
Referenced by appendBuffer().
const U8* Torque::ByteBuffer::getBuffer () const
U32 Torque::ByteBuffer::getBufferSize () const
Referenced by appendBuffer().
ByteBuffer Torque::ByteBuffer::getCopy () const
Copy the data in the buffer.
Referenced by appendBuffer().
ByteBuffer& Torque::ByteBuffer::operator= (const ByteBuffer & theBuffer)
void Torque::ByteBuffer::resize (U32 newBufferSize)
Resize the buffer.
void Torque::ByteBuffer::setBuffer (U8 * dataPtr, U32 bufferSize, bool copyData)
Set the ByteBuffer to point to a new chunk of memory.
Copyright © GarageGames, LLC. All Rights Reserved.