LightMapParams Class Reference
Main Modules Class List Namespace List Online
LightMapParams Class Reference
#include <lighting/common/lightMapParams.h>
Public Member Functions
LightMapParams (LightInfo *light)
virtual ~LightMapParams ()
virtual const LightInfoExType & getType () const
virtual void packUpdate (BitStream *stream) const
virtual void set (const LightInfoEx *ex)
Copy the values from the other LightInfoEx.
virtual void unpackUpdate (BitStream *stream)
Public Member Functions inherited from LightInfoEx
virtual ~LightInfoEx ()
Basic destructor so we can delete the extended info without knowing the concrete type.
Public Attributes
bool includeLightmappedGeometryInShadow
This light should render lightmapped geometry during its shadow-map update (ignored if 'representedInLightmap' is false)
bool representedInLightmap
This light is represented in lightmaps (static light, default: false)
ColorF shadowDarkenColor
The color that should be used to multiply-blend dynamic shadows onto lightmapped geometry (ignored if 'representedInLightmap' is false)
Static Public Attributes
static LightInfoExType Type
The LightInfoEx hook type.
Constructor & Destructor Documentation
LightMapParams::LightMapParams (LightInfo * light)
virtual LightMapParams::~LightMapParams () virtual
Member Function Documentation
virtual const LightInfoExType& LightMapParams::getType () const inline virtual
Implements LightInfoEx.
References packUpdate(), Type, and unpackUpdate().
virtual void LightMapParams::packUpdate (BitStream * stream) const virtual
Reimplemented from LightInfoEx.
Referenced by getType().
virtual void LightMapParams::set (const LightInfoEx * ex) virtual
Copy the values from the other LightInfoEx.
Reimplemented from LightInfoEx.
virtual void LightMapParams::unpackUpdate (BitStream * stream) virtual
Reimplemented from LightInfoEx.
Referenced by getType().
Member Data Documentation
bool LightMapParams::includeLightmappedGeometryInShadow
This light should render lightmapped geometry during its shadow-map update (ignored if 'representedInLightmap' is false)
bool LightMapParams::representedInLightmap
This light is represented in lightmaps (static light, default: false)
ColorF LightMapParams::shadowDarkenColor
The color that should be used to multiply-blend dynamic shadows onto lightmapped geometry (ignored if 'representedInLightmap' is false)
LightInfoExType LightMapParams::Type static
The LightInfoEx hook type.
Referenced by getType().
Copyright © GarageGames, LLC. All Rights Reserved.