BasicSceneObjectLightingPlugin Class Reference
Main Modules Class List Namespace List Online
BasicSceneObjectLightingPlugin Class Reference
#include <lighting/basic/basicSceneObjectLightingPlugin.h>
Public Member Functions
BasicSceneObjectLightingPlugin (SceneObject *parent)
~BasicSceneObjectLightingPlugin ()
const F32 getScore () const
virtual U32 packUpdate (SceneObject *obj, U32 checkMask, NetConnection *conn, U32 mask, BitStream *stream)
virtual void renderShadow (SceneRenderState *state)
virtual void reset ()
Reset light plugin to clean state.
virtual void unpackUpdate (SceneObject *obj, NetConnection *conn, BitStream *stream)
virtual void updateShadow (SceneRenderState *state)
Public Member Functions inherited from SceneObjectLightingPlugin
virtual ~SceneObjectLightingPlugin ()
Static Public Member Functions
static void cleanupPluginInstances ()
static Vector< BasicSceneObjectLightingPlugin * > * getPluginInstances ()
static void resetAll ()
Constructor & Destructor Documentation
BasicSceneObjectLightingPlugin::BasicSceneObjectLightingPlugin (SceneObject * parent)
BasicSceneObjectLightingPlugin::~BasicSceneObjectLightingPlugin ()
Member Function Documentation
static void BasicSceneObjectLightingPlugin::cleanupPluginInstances () static
Referenced by getPluginInstances().
static Vector<BasicSceneObjectLightingPlugin*>* BasicSceneObjectLightingPlugin::getPluginInstances () inline static
References cleanupPluginInstances(), getScore(), renderShadow(), resetAll(), and updateShadow().
const F32 BasicSceneObjectLightingPlugin::getScore () const
Referenced by getPluginInstances().
virtual U32 BasicSceneObjectLightingPlugin::packUpdate (SceneObject * obj, U32 checkMask, NetConnection * conn, U32 mask, BitStream * stream) inline virtual
Implements SceneObjectLightingPlugin.
virtual void BasicSceneObjectLightingPlugin::renderShadow (SceneRenderState * state) virtual
Referenced by getPluginInstances().
virtual void BasicSceneObjectLightingPlugin::reset (void) virtual
Reset light plugin to clean state.
Reimplemented from SceneObjectLightingPlugin.
Referenced by unpackUpdate().
static void BasicSceneObjectLightingPlugin::resetAll () static
Referenced by getPluginInstances().
virtual void BasicSceneObjectLightingPlugin::unpackUpdate (SceneObject * obj, NetConnection * conn, BitStream * stream) inline virtual
Implements SceneObjectLightingPlugin.
References reset().
virtual void BasicSceneObjectLightingPlugin::updateShadow (SceneRenderState * state) virtual
Referenced by getPluginInstances().
Copyright © GarageGames, LLC. All Rights Reserved.