ForestData Class Reference
Main Modules Class List Namespace List Online
ForestData Class Reference
This is the data file for Forests.
#include <forest/forestDataFile.h>
Public Member Functions
ForestData ()
virtual ~ForestData ()
const ForestItem & addItem (ForestItemData *data, const Point3F &position, F32 rotation, F32 scale)
const ForestItem & addItem (ForestItemKey key, ForestItemData *data, const MatrixF &xfm, F32 scale)
void buildPhysicsRep (Forest *forest)
bool castRay (const Point3F &start, const Point3F &end, RayInfo *outInfo, bool rendered) const
void clear ()
Deletes all the data and resets the file to an empty state.
void clearPhysicsRep (Forest *forest)
const ForestItem & findItem (ForestItemKey key, const Point3F &keyPosition) const
Performs a search using the position to limit tested cells.
const ForestItem & findItem (ForestItemKey key) const
Does an exhaustive search thru all cells looking for the item.
void getCells (const Frustum &frustum, Vector< ForestCell * > *outCells) const
Returns all the top level cells which intersect the frustum.
void getCells (Vector< ForestCell * > *outCells) const
Returns all top level cells.
U32 getDatablocks (Vector< ForestItemData * > *outVector) const
Gathers all the datablocks used and returns the count.
U32 getItems (Vector< ForestItem > *outItems) const
Fills a vector with a copy of all the items in the data set.
U32 getItems (const Frustum &culler, Vector< ForestItem > *outItems) const
Fills a vector with a copy of all items in the Frustum.
U32 getItems (const Box3F &box, Vector< ForestItem > *outItems) const
Returns a copy of all the items that intersect the box.
U32 getItems (const Point3F &point, F32 radius, Vector< ForestItem > *outItems) const
Returns a copy of all the items that intersect the sphere.
U32 getItems (const Point2F &point, F32 radius, Vector< ForestItem > *outItems) const
Returns a copy of all the items that intersect the 2D circle ignoring the z component.
U32 getItems (const ForestItemData *data, Vector< ForestItem > *outItems) const
Returns a copy of all the items that share the input item datablock.
bool isDirty () const
bool read (Stream &stream)
void regenCells ()
Helper for debugging cell generation.
bool removeItem (ForestItemKey key, const Point3F &keyPosition)
const ForestItem & updateItem (ForestItemKey key, const Point3F &keyPosition, ForestItemData *newData, const MatrixF &newXfm, F32 newscale)
const ForestItem & updateItem (ForestItem &item)
bool write (const char *path)
Protected Types
enum { FILE_VERSION = 1 }
typedef HashTable< Point2I, ForestCell * > BucketTable
Protected Member Functions
ForestCell * _findBucket (const Point2I &key) const
Finds the bucket with the given Point2I key or returns NULL.
ForestCell * _findBucket (const Point3F &pos) const
Finds the best top level bucket for the ForestItem 'key' position or returns NULL.
ForestCell * _findOrCreateBucket (const Point3F &pos)
Find the best top level bucket for the given position or returns a new one.
void _onItemReload ()
Static Protected Member Functions
static Point2I _getBucketKey (const Point3F &pos)
Converts a ForestItem's Point3F 'KeyPosition' to a Point2I key we index into BucketTable with.
Protected Attributes
BucketTable mBuckets
The top level cell buckets which allows us to have virtually unbounded range.
bool mIsDirty
Set to true if the file is dirty and needs to be saved before being destroyed.
Static Protected Attributes
static const U32 BUCKET_DIM = 2000
Set the bucket dimensions to 2km x 2km.
static U32 smNextItemId
The next free item id.
Detailed Description
This is the data file for Forests.
Member Typedef Documentation
typedef HashTable<Point2I,ForestCell*> ForestData::BucketTable protected
Member Enumeration Documentation
anonymous enum protected
Enumerator
FILE_VERSION
Constructor & Destructor Documentation
ForestData::ForestData ()
virtual ForestData::~ForestData () virtual
Member Function Documentation
ForestCell* ForestData::_findBucket (const Point2I & key) const protected
Finds the bucket with the given Point2I key or returns NULL.
Referenced by _findBucket().
ForestCell * ForestData::_findBucket (const Point3F & pos) const inline protected
Finds the best top level bucket for the ForestItem 'key' position or returns NULL.
References _findBucket(), and _getBucketKey().
ForestCell* ForestData::_findOrCreateBucket (const Point3F & pos) protected
Find the best top level bucket for the given position or returns a new one.
Point2I ForestData::_getBucketKey (const Point3F & pos) inline static protected
Converts a ForestItem's Point3F 'KeyPosition' to a Point2I key we index into BucketTable with.
References BUCKET_DIM, Point3F::x, and Point3F::y.
Referenced by _findBucket().
void ForestData::_onItemReload () protected
const ForestItem& ForestData::addItem (ForestItemData * data, const Point3F & position, F32 rotation, F32 scale)
Referenced by isDirty().
const ForestItem& ForestData::addItem (ForestItemKey key, ForestItemData * data, const MatrixF & xfm, F32 scale)
void ForestData::buildPhysicsRep (Forest * forest)
Referenced by isDirty().
bool ForestData::castRay (const Point3F & start, const Point3F & end, RayInfo * outInfo, bool rendered) const
Referenced by isDirty().
void ForestData::clear ()
Deletes all the data and resets the file to an empty state.
Referenced by Forest::clear(), and isDirty().
void ForestData::clearPhysicsRep (Forest * forest)
Referenced by isDirty().
const ForestItem& ForestData::findItem (ForestItemKey key, const Point3F & keyPosition) const
Performs a search using the position to limit tested cells.
Referenced by isDirty().
const ForestItem& ForestData::findItem (ForestItemKey key) const
Does an exhaustive search thru all cells looking for the item.
This method is slow and should be avoided.
void ForestData::getCells (const Frustum & frustum, Vector< ForestCell * > * outCells) const
Returns all the top level cells which intersect the frustum.
Referenced by isDirty().
void ForestData::getCells (Vector< ForestCell * > * outCells) const
Returns all top level cells.
U32 ForestData::getDatablocks (Vector< ForestItemData * > * outVector) const
Gathers all the datablocks used and returns the count.
Referenced by isDirty().
U32 ForestData::getItems (Vector< ForestItem > * outItems) const
Fills a vector with a copy of all the items in the data set.
Parameters
outItems The output vector of items.
Returns
The count of items found.
Referenced by isDirty().
U32 ForestData::getItems (const Frustum & culler, Vector< ForestItem > * outItems) const
Fills a vector with a copy of all items in the Frustum.
Note that this IS expensive and this is not how Forest internally collects items for rendering. This is here for ForestSelectionTool.
Parameters
The Frustum to cull with.
outItems The output vector of items.
Returns
The count of items found.
U32 ForestData::getItems (const Box3F & box, Vector< ForestItem > * outItems) const
Returns a copy of all the items that intersect the box.
If the output vector is NULL then it will early out on the first found item returning 1.
Parameters
box The search box.
outItems The output vector of items or NULL.
Returns
The count of items found.
U32 ForestData::getItems (const Point3F & point, F32 radius, Vector< ForestItem > * outItems) const
Returns a copy of all the items that intersect the sphere.
If the output vector is NULL then it will early out on the first found item returning 1.
Parameters
point The center of the search sphere.
radius The radius of the search sphere.
outItems The output vector of items or NULL.
Returns
The count of items found.
U32 ForestData::getItems (const Point2F & point, F32 radius, Vector< ForestItem > * outItems) const
Returns a copy of all the items that intersect the 2D circle ignoring the z component.
If the output vector is NULL then it will early out on the first found item returning 1.
Parameters
point The center point of the search circle.
radius The radius of the search circle.
outItems The output vector of items or NULL.
Returns
The count of items found.
U32 ForestData::getItems (const ForestItemData * data, Vector< ForestItem > * outItems) const
Returns a copy of all the items that share the input item datablock.
Parameters
data The datablock to search for.
outItems The output vector of items.
Returns
The count of items found.
bool ForestData::isDirty () const inline
References addItem(), buildPhysicsRep(), castRay(), clear(), clearPhysicsRep(), findItem(), getCells(), getDatablocks(), getItems(), mIsDirty, read(), regenCells(), removeItem(), updateItem(), and write().
bool ForestData::read (Stream & stream)
Referenced by isDirty().
void ForestData::regenCells ()
Helper for debugging cell generation.
Referenced by isDirty().
bool ForestData::removeItem (ForestItemKey key, const Point3F & keyPosition)
Referenced by isDirty().
const ForestItem& ForestData::updateItem (ForestItemKey key, const Point3F & keyPosition, ForestItemData * newData, const MatrixF & newXfm, F32 newscale)
Referenced by isDirty().
const ForestItem& ForestData::updateItem (ForestItem & item)
bool ForestData::write (const char * path)
Referenced by isDirty().
Member Data Documentation
const U32 ForestData::BUCKET_DIM = 2000 static protected
Set the bucket dimensions to 2km x 2km.
Referenced by _getBucketKey().
BucketTable ForestData::mBuckets protected
The top level cell buckets which allows us to have virtually unbounded range.
bool ForestData::mIsDirty protected
Set to true if the file is dirty and needs to be saved before being destroyed.
Referenced by isDirty().
U32 ForestData::smNextItemId static protected
The next free item id.
Copyright © GarageGames, LLC. All Rights Reserved.