Message System
Main Modules Class List Namespace List Online
Message System
Most of the message system docs are currently just stubs and will be fleshed out soon.
Namespaces
Dispatcher
Namespace for the message dispatcher functions.
Classes
class Dispatcher::IMessageListener
Listener interface for objects that receive messages.
struct Dispatcher::MessageQueue
Internal class for tracking message queues.
class EventManager
The EventManager class is a wrapper for the standard messaging system.
class Message
Base class for messages.
class MessageForwarder
Forward messages from one queue to another.
class ScriptMsgListener
Script accessible version of Dispatcher::IMessageListener.
Message Queue Management
bool Dispatcher::isQueueRegistered (const char *name)
Check if a message queue is registered.
void Dispatcher::registerMessageQueue (const char *name)
Register a message queue.
const char * Dispatcher::registerAnonMessageQueue ()
Register an anonymous message queue.
void Dispatcher::unregisterMessageQueue (const char *name)
Unregister a message queue.
bool Dispatcher::registerMessageListener (const char *queue, IMessageListener *listener)
Register a listener with a queue to receive messages.
void Dispatcher::unregisterMessageListener (const char *queue, IMessageListener *listener)
Unregister a listener with a queue.
Message Dispatcher
bool Dispatcher::dispatchMessage (const char *queue, const char *msg, const char *data)
Dispatch a message to a queue.
bool Dispatcher::dispatchMessageObject (const char *queue, Message *msg)
Dispatch a message object to a queue.
Internal Functions
bool Dispatcher::lockDispatcherMutex ()
Internal function: Lock the dispatcher mutex.
void Dispatcher::unlockDispatcherMutex ()
Internal function: Unlock the dispatcher mutex.
MessageQueue * Dispatcher::getMessageQueue (const char *name)
Internal function: obtain message queue.
Detailed Description
Most of the message system docs are currently just stubs and will be fleshed out soon.
Function Documentation
bool Dispatcher::dispatchMessage (const char * queue, const char * msg, const char * data)
Dispatch a message to a queue.
Parameters
queue Queue to dispatch the message to
msg Message to dispatch
data Data for message
Returns
true for success, false for failure
See also
dispatchMessageObject()
Referenced by Dispatcher::MessageQueue::dispatchMessageObject().
bool Dispatcher::dispatchMessageObject (const char * queue, Message * msg)
Dispatch a message object to a queue.
Parameters
queue Queue to dispatch the message to
msg Message to dispatch
Returns
true for success, false for failure
See also
dispatchMessage()
Referenced by Dispatcher::MessageQueue::dispatchMessageObject().
MessageQueue* Dispatcher::getMessageQueue (const char * name)
Internal function: obtain message queue.
Dispatcher mutex must be locked.
Parameters
name Name of the queue
Returns
Message queue
See also
lockDispatcherMutex(), unlockDispatcherMutex()
Referenced by Dispatcher::MessageQueue::dispatchMessageObject().
bool Dispatcher::isQueueRegistered (const char * name)
Check if a message queue is registered.
Parameters
name The name of the message queue
Returns
true if the queue is registered, false otherwise
See also
registerMessageQueue(), unregisterMessageQueue()
Referenced by Dispatcher::MessageQueue::dispatchMessageObject().
bool Dispatcher::lockDispatcherMutex ()
Internal function: Lock the dispatcher mutex.
Returns
true for success, false for failure
See also
unlockDispatcherMutex()
Referenced by Dispatcher::MessageQueue::dispatchMessageObject().
const char* Dispatcher::registerAnonMessageQueue ()
Register an anonymous message queue.
Returns
name of anonymous message queue for passing to other functions
See also
isQueueRegistered(), unregisterMessageQueue()
Referenced by Dispatcher::MessageQueue::dispatchMessageObject().
bool Dispatcher::registerMessageListener (const char * queue, IMessageListener * listener)
Register a listener with a queue to receive messages.
Parameters
queue The name of the queue to register the listener with
listener The listener interface that receives messages
Returns
true for success, false otherwise
See also
unregisterMessageListener()
Referenced by Dispatcher::MessageQueue::dispatchMessageObject().
void Dispatcher::registerMessageQueue (const char * name)
Register a message queue.
Parameters
name The name of the message queue to register
See also
isQueueRegistered(), unregisterMessageQueue()
Referenced by Dispatcher::MessageQueue::dispatchMessageObject().
void Dispatcher::unlockDispatcherMutex ()
Internal function: Unlock the dispatcher mutex.
See also
lockDispatcherMutex()
Referenced by Dispatcher::MessageQueue::dispatchMessageObject().
void Dispatcher::unregisterMessageListener (const char * queue, IMessageListener * listener)
Unregister a listener with a queue.
Parameters
queue The name of the queue to unregister the listener
listener The listener interface that was passed to registerMessageListener()
See also
registerMessageListener()
Referenced by Dispatcher::MessageQueue::dispatchMessageObject().
void Dispatcher::unregisterMessageQueue (const char * name)
Unregister a message queue.
Parameters
name The name of the message queue
See also
registerMessageQueue(), isQueueRegistered()
Referenced by Dispatcher::MessageQueue::dispatchMessageObject().
Copyright © GarageGames, LLC. All Rights Reserved.