SilhouetteExtractorBaseOrtho< Polyhedron > Struct Template Reference
Main Modules Class List Namespace List Online
SilhouetteExtractorBaseOrtho< Polyhedron > Struct Template Reference
Silhouette extraction routines for orthographic projections.
#include <math/mSilhouetteExtractor.h>
Public Member Functions
SilhouetteExtractorBaseOrtho (const Polyhedron &polyhedron)
void begin (const Point3F &viewDirOS) const
Initialize the extractor.
void end () const
Finish extraction.
bool isSilhouetteEdge (U32 edgeIndex) const
Return true if the given edge is a silhouette edge with respect to the view direction.
Additional Inherited Members
Public Types inherited from SilhouetteExtractorBase< Polyhedron >
typedef Polyhedron PolyhedronType
Protected Member Functions inherited from SilhouetteExtractorBase< Polyhedron >
SilhouetteExtractorBase (const PolyhedronType &polyhedron)
Protected Attributes inherited from SilhouetteExtractorBase< Polyhedron >
const PolyhedronType * mPolyhedron
The polyhedron from which we are extracting silhouettes.
Detailed Description
template<typename Polyhedron>
struct SilhouetteExtractorBaseOrtho< Polyhedron >
Silhouette extraction routines for orthographic projections.
Constructor & Destructor Documentation
template<typename Polyhedron > SilhouetteExtractorBaseOrtho< Polyhedron >::SilhouetteExtractorBaseOrtho (const Polyhedron & polyhedron) inline
Member Function Documentation
template<typename Polyhedron > void SilhouetteExtractorBaseOrtho< Polyhedron >::begin (const Point3F & viewDirOS) const inline
Initialize the extractor.
References FrameAllocator::alloc(), FrameAllocator::getWaterMark(), and SilhouetteExtractorBase< Polyhedron >::mPolyhedron.
Referenced by SilhouetteExtractorOrtho< Polyhedron >::extractSilhouette().
template<typename Polyhedron > void SilhouetteExtractorBaseOrtho< Polyhedron >::end () const inline
Finish extraction.
References FrameAllocator::setWaterMark().
Referenced by SilhouetteExtractorOrtho< Polyhedron >::extractSilhouette().
template<typename Polyhedron > bool SilhouetteExtractorBaseOrtho< Polyhedron >::isSilhouetteEdge (U32 edgeIndex) const inline
Return true if the given edge is a silhouette edge with respect to the view direction.
Parameters
edgeIndex Index of edge to test.
Returns
True if the given edge is a silhouette in the projection along the view direction.
Note
This method depends on inward-facing normals!
References SilhouetteExtractorBase< Polyhedron >::mPolyhedron.
Copyright © GarageGames, LLC. All Rights Reserved.