SimConsoleThreadExecCallback Struct Reference
Main Modules Class List Namespace List Online
SimConsoleThreadExecCallback Struct Reference
Used by Con::threadSafeExecute()
#include <console/simEvents.h>
Public Member Functions
SimConsoleThreadExecCallback ()
~SimConsoleThreadExecCallback ()
void handleCallback (ConsoleValueRef ret)
ConsoleValueRef waitForResult ()
Public Attributes
ConsoleValueRef retVal
Semaphore * sem
Detailed Description
Used by Con::threadSafeExecute()
Constructor & Destructor Documentation
SimConsoleThreadExecCallback::SimConsoleThreadExecCallback ()
SimConsoleThreadExecCallback::~SimConsoleThreadExecCallback ()
Member Function Documentation
void SimConsoleThreadExecCallback::handleCallback (ConsoleValueRef ret)
ConsoleValueRef SimConsoleThreadExecCallback::waitForResult ()
Referenced by _EngineConsoleCallbackHelper::call(), _EngineConsoleExecCallbackHelper< P1 >::call(), and _EngineConsoleExecCallbackHelper< const char * >::call().
Member Data Documentation
ConsoleValueRef SimConsoleThreadExecCallback::retVal
Semaphore* SimConsoleThreadExecCallback::sem
Copyright © GarageGames, LLC. All Rights Reserved.