ColladaUtils::ImportOptions Struct Reference
Main Modules Class List Namespace List Online
ColladaUtils::ImportOptions Struct Reference
#include <ts/collada/colladaUtils.h>
Public Types
enum eLodType {
DetectDTS = 0,
SingleSize,
TrailingNumber,
NumLodTypes
}
Public Member Functions
ImportOptions ()
void reset ()
Public Attributes
bool adjustCenter
bool adjustFloor
String alwaysImport
String alwaysImportMesh
bool forceUpdateMaterials
bool ignoreNodeScale
eLodType lodType
String matNamePrefix
String neverImport
String neverImportMesh
S32 singleDetailSize
F32 unit
domUpAxisType upAxis
bool useDiffuseNames
Member Enumeration Documentation
enum ColladaUtils::ImportOptions::eLodType
Enumerator
DetectDTS
SingleSize
TrailingNumber
NumLodTypes
Constructor & Destructor Documentation
ColladaUtils::ImportOptions::ImportOptions () inline
References reset().
Member Function Documentation
void ColladaUtils::ImportOptions::reset (void) inline
References ColladaUtils::applyConditioners(), ColladaUtils::collapsePath(), ColladaUtils::convertTransform(), DetectDTS, String::EmptyString, ColladaUtils::exportColladaHeader(), ColladaUtils::exportColladaMaterials(), ColladaUtils::exportColladaMesh(), ColladaUtils::exportColladaScene(), ColladaUtils::exportColladaTriangles(), ColladaUtils::exportToCollada(), ColladaUtils::findEffectCommonProfile(), ColladaUtils::findEffectDiffuse(), ColladaUtils::findEffectSpecular(), ColladaUtils::findTexture(), ColladaUtils::getOptions(), ColladaUtils::getSamplerImagePath(), ColladaUtils::getTextureSampler(), Point3F::normalize(), Point3F::normalizeSafe(), ColladaUtils::resolveImagePath(), MatrixF::scale(), MatrixF::setColumn(), AngAxisF::setMatrix(), MatrixF::setPosition(), T, Point3F::x, Point3F::y, and Point3F::z.
Referenced by ImportOptions().
Member Data Documentation
bool ColladaUtils::ImportOptions::adjustCenter
bool ColladaUtils::ImportOptions::adjustFloor
String ColladaUtils::ImportOptions::alwaysImport
String ColladaUtils::ImportOptions::alwaysImportMesh
bool ColladaUtils::ImportOptions::forceUpdateMaterials
bool ColladaUtils::ImportOptions::ignoreNodeScale
eLodType ColladaUtils::ImportOptions::lodType
String ColladaUtils::ImportOptions::matNamePrefix
String ColladaUtils::ImportOptions::neverImport
String ColladaUtils::ImportOptions::neverImportMesh
S32 ColladaUtils::ImportOptions::singleDetailSize
F32 ColladaUtils::ImportOptions::unit
domUpAxisType ColladaUtils::ImportOptions::upAxis
bool ColladaUtils::ImportOptions::useDiffuseNames
Copyright © GarageGames, LLC. All Rights Reserved.