rapidjson::BaseReaderHandler< Encoding > Struct Template Reference
Main Modules Class List Namespace List Online
rapidjson::BaseReaderHandler< Encoding > Struct Template Reference
Default implementation of Handler.
#include <persistence/rapidjson/reader.h>
Public Types
typedef Encoding::Ch Ch
Public Member Functions
void Bool (bool)
void Default ()
void Double (double)
void EndArray (SizeType)
void EndObject (SizeType)
void Int (int)
void Int64 (int64_t)
void Null ()
void StartArray ()
void StartObject ()
void String (const Ch *, SizeType, bool)
void Uint (unsigned)
void Uint64 (uint64_t)
Detailed Description
template<typename Encoding = UTF8<>>
struct rapidjson::BaseReaderHandler< Encoding >
Default implementation of Handler.
This can be used as base class of any reader handler.
Member Typedef Documentation
template<typename Encoding = UTF8<>> typedef Encoding::Ch rapidjson::BaseReaderHandler< Encoding >::Ch
Member Function Documentation
template<typename Encoding = UTF8<>> void rapidjson::BaseReaderHandler< Encoding >::Bool (bool) inline
References rapidjson::BaseReaderHandler< Encoding >::Default().
template<typename Encoding = UTF8<>> void rapidjson::BaseReaderHandler< Encoding >::Default () inline
Referenced by rapidjson::BaseReaderHandler< Encoding >::Bool(), rapidjson::BaseReaderHandler< Encoding >::Double(), rapidjson::BaseReaderHandler< Encoding >::EndArray(), rapidjson::BaseReaderHandler< Encoding >::EndObject(), rapidjson::BaseReaderHandler< Encoding >::Int(), rapidjson::BaseReaderHandler< Encoding >::Int64(), rapidjson::BaseReaderHandler< Encoding >::Null(), rapidjson::BaseReaderHandler< Encoding >::StartArray(), rapidjson::BaseReaderHandler< Encoding >::StartObject(), rapidjson::BaseReaderHandler< Encoding >::String(), rapidjson::BaseReaderHandler< Encoding >::Uint(), and rapidjson::BaseReaderHandler< Encoding >::Uint64().
template<typename Encoding = UTF8<>> void rapidjson::BaseReaderHandler< Encoding >::Double (double) inline
References rapidjson::BaseReaderHandler< Encoding >::Default().
template<typename Encoding = UTF8<>> void rapidjson::BaseReaderHandler< Encoding >::EndArray (SizeType) inline
References rapidjson::BaseReaderHandler< Encoding >::Default().
template<typename Encoding = UTF8<>> void rapidjson::BaseReaderHandler< Encoding >::EndObject (SizeType) inline
References rapidjson::BaseReaderHandler< Encoding >::Default().
template<typename Encoding = UTF8<>> void rapidjson::BaseReaderHandler< Encoding >::Int (int) inline
References rapidjson::BaseReaderHandler< Encoding >::Default().
template<typename Encoding = UTF8<>> void rapidjson::BaseReaderHandler< Encoding >::Int64 (int64_t) inline
References rapidjson::BaseReaderHandler< Encoding >::Default().
template<typename Encoding = UTF8<>> void rapidjson::BaseReaderHandler< Encoding >::Null () inline
References rapidjson::BaseReaderHandler< Encoding >::Default().
template<typename Encoding = UTF8<>> void rapidjson::BaseReaderHandler< Encoding >::StartArray () inline
References rapidjson::BaseReaderHandler< Encoding >::Default().
template<typename Encoding = UTF8<>> void rapidjson::BaseReaderHandler< Encoding >::StartObject () inline
References rapidjson::BaseReaderHandler< Encoding >::Default().
template<typename Encoding = UTF8<>> void rapidjson::BaseReaderHandler< Encoding >::String (const Ch * , SizeType , bool) inline
References rapidjson::BaseReaderHandler< Encoding >::Default().
template<typename Encoding = UTF8<>> void rapidjson::BaseReaderHandler< Encoding >::Uint (unsigned) inline
References rapidjson::BaseReaderHandler< Encoding >::Default().
template<typename Encoding = UTF8<>> void rapidjson::BaseReaderHandler< Encoding >::Uint64 (uint64_t) inline
References rapidjson::BaseReaderHandler< Encoding >::Default().
Copyright © GarageGames, LLC. All Rights Reserved.