rapidjson::GenericStringStream< Encoding > Struct Template Reference
Main Modules Class List Namespace List Online
rapidjson::GenericStringStream< Encoding > Struct Template Reference
Read-only string stream.
#include <persistence/rapidjson/rapidjson.h>
Public Types
typedef Encoding::Ch Ch
Public Member Functions
GenericStringStream (const Ch *src)
void Flush ()
Ch Peek () const
void Put (Ch)
Ch * PutBegin ()
size_t PutEnd (Ch *)
Ch Take ()
size_t Tell () const
Public Attributes
const Ch * head_
Original head of the string.
const Ch * src_
Current read position.
Detailed Description
template<typename Encoding>
struct rapidjson::GenericStringStream< Encoding >
Read-only string stream.
Member Typedef Documentation
template<typename Encoding> typedef Encoding::Ch rapidjson::GenericStringStream< Encoding >::Ch
Constructor & Destructor Documentation
template<typename Encoding> rapidjson::GenericStringStream< Encoding >::GenericStringStream (const Ch * src) inline
Member Function Documentation
template<typename Encoding> void rapidjson::GenericStringStream< Encoding >::Flush () inline
template<typename Encoding> Ch rapidjson::GenericStringStream< Encoding >::Peek () const inline
Referenced by rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteString().
template<typename Encoding> void rapidjson::GenericStringStream< Encoding >::Put (Ch) inline
template<typename Encoding> Ch* rapidjson::GenericStringStream< Encoding >::PutBegin () inline
template<typename Encoding> size_t rapidjson::GenericStringStream< Encoding >::PutEnd (Ch *) inline
template<typename Encoding> Ch rapidjson::GenericStringStream< Encoding >::Take () inline
Referenced by rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteString().
template<typename Encoding> size_t rapidjson::GenericStringStream< Encoding >::Tell () const inline
Referenced by rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteString().
Member Data Documentation
template<typename Encoding> const Ch* rapidjson::GenericStringStream< Encoding >::head_
Original head of the string.
template<typename Encoding> const Ch* rapidjson::GenericStringStream< Encoding >::src_
Current read position.
Referenced by rapidjson::SkipWhitespace().
Copyright © GarageGames, LLC. All Rights Reserved.