AnimData Struct Reference
Main Modules Class List Namespace List Online
AnimData Struct Reference
#include <ts/collada/colladaUtils.h>
Public Member Functions
AnimData ()
void interpValue (F32 t, U32 offset, double *value) const
void interpValue (F32 t, U32 offset, const char **value) const
F32 invertParamCubic (F32 param, F32 x0, F32 x1, F32 x2, F32 x3) const
void parseTargetString (const char *target, S32 fullCount, const char *elements[])
Static Public Member Functions
static AnimChannels * getAnimChannels (const daeElement *element)
Get the animation channels for the Collada element (if any)
Public Attributes
bool enabled
_SourceReader input
!< Used to select animation channels for the current clip
_SourceReader inTangent
_SourceReader interpolation
_SourceReader output
_SourceReader outTangent
U32 targetValueCount
Number of values animated (from OUTPUT source array)
U32 targetValueOffset
Offset into the target element (for arrays of values)
Constructor & Destructor Documentation
AnimData::AnimData () inline
Member Function Documentation
static AnimChannels* AnimData::getAnimChannels (const daeElement * element) inline static
Get the animation channels for the Collada element (if any)
Referenced by AnimatedElement< double >::getValue(), AnimatedElementList< T >::getValue(), and AnimatedElement< double >::isAnimated().
void AnimData::interpValue (F32 t, U32 offset, double * value) const
Referenced by AnimatedElement< double >::getValue(), and AnimatedElementList< T >::getValue().
void AnimData::interpValue (F32 t, U32 offset, const char ** value) const
F32 AnimData::invertParamCubic (F32 param, F32 x0, F32 x1, F32 x2, F32 x3) const
void AnimData::parseTargetString (const char * target, S32 fullCount, const char * elements[])
Member Data Documentation
bool AnimData::enabled
Referenced by AnimatedElement< double >::getValue(), and AnimatedElementList< T >::getValue().
_SourceReader AnimData::input
!< Used to select animation channels for the current clip
_SourceReader AnimData::inTangent
_SourceReader AnimData::interpolation
_SourceReader AnimData::output
_SourceReader AnimData::outTangent
U32 AnimData::targetValueCount
Number of values animated (from OUTPUT source array)
Referenced by AnimatedElementList< T >::getValue().
U32 AnimData::targetValueOffset
Offset into the target element (for arrays of values)
Referenced by AnimatedElementList< T >::getValue().
Copyright © GarageGames, LLC. All Rights Reserved.