ScopeTracker< NUM_DIMENSIONS, Object > Class Template Reference
Main Modules Class List Namespace List Online
ScopeTracker< NUM_DIMENSIONS, Object > Class Template Reference
Helper class to track the position of a point in N-dimensional space relative to a collection of N-dimensional volumes.
#include <util/scopeTracker.h>
Public Types
typedef ObjectType::TrackingNode NodeType
typedef TypeTraits< Object >::BaseType ObjectType
typedef void Parent
Public Member Functions
ScopeTracker ()
void debugDump ()
Object getReferenceObject () const
void registerObject (Object object)
Add a volume object to the world.
void setReferenceObject (Object object)
void unregisterObject (Object object)
Remove a volume object from the world.
void updateObject (Object object)
Update the position of the object in the world.
Protected Types
enum {
MIN = 0,
MAX = 1
}
Protected Member Functions
Scoping
virtual void _onScopeIn (Object object)
virtual void _onScopeOut (Object object)
void _setScope (Object object)
Set the scoping state of the given object.
Tracking
void _insertTrackingNode (U32 dimension, NodeType *node)
void _removeTrackingNode (U32 dimension, NodeType *node)
void _moveTrackingNode (U32 dimension, NodeType *node, F32 newPos)
void _initTracking ()
void _uninitTracking ()
Protected Attributes
NodeType mBoundaryNodes [NUM_DIMENSIONS][2]
Vector< Object > mPotentialScopeInObjects
Object mReferenceObject
The reference object.
NodeType * mTrackingList [NUM_DIMENSIONS][2]
Detailed Description
template<S32 NUM_DIMENSIONS, typename Object>
class ScopeTracker< NUM_DIMENSIONS, Object >
Helper class to track the position of a point in N-dimensional space relative to a collection of N-dimensional volumes.
This class works by breaking the N-dimensional case down into N one-dimensional cases. By tracking objects independently along each of their axes, intersection testing becomes a trivial matter of doing point-on-line tests. The line segments can be conveniently represented as ordered linked lists along which the reference point is being moved.
To determine N-dimensional containment of the reference point, the result of each of the one-dimensional point-on-line tests simply has to be combined. If the point lies on each of N 1D segments of a given volume, then the point is fully contained in the volume.
This class may be used in places where otherwise a spatial subdivision scheme would be necessary in order to limit the number of containment tests triggered by each movement of the reference point. Once the tracker has been set up, each position change of an object or the reference center will result in a usually small number of incremental list updates.
Another advantage is that this class makes it easy to reduce 3D tracking to 2D tracking if tracking on the height axis isn't important.
The following interface must be implemented by the given "Object" type:
struct Object : public ScopeTrackerObject< NUM_DIMENSIONS >
{
   /// Return the position of the object in world-space.
   void getPosition( F32 pos[ NUM_DIMENSIONS ] ) const;
   /// If this object is the reference object, this method should return the world-space pivot
   /// point in the object that will be the world reference center.
   void getReferenceCenter( F32 pos[ NUM_DIMENSIONS ] ) const;
   /// Return the object's bounding box in world-space.
   void getBounds( F32 minBounds[ NUM_DIMENSIONS ], F32 maxBounds[ NUM_DIMENSIONS ] ) const;
};
Terminology:
"In Scope": A volume is in scope if it fully contains the reference center.
"Reference Object": Object that is the designated center of the world.
Parameters
NUM_DIMENSIONS Number of dimensions to track; must be <=4.
Object Value type for objects tracked by the ScopeTracker. Must have pointer behavior.
Member Typedef Documentation
template<S32 NUM_DIMENSIONS, typename Object> typedef ObjectType::TrackingNode ScopeTracker< NUM_DIMENSIONS, Object >::NodeType
template<S32 NUM_DIMENSIONS, typename Object> typedef TypeTraits< Object >::BaseType ScopeTracker< NUM_DIMENSIONS, Object >::ObjectType
template<S32 NUM_DIMENSIONS, typename Object> typedef void ScopeTracker< NUM_DIMENSIONS, Object >::Parent
Member Enumeration Documentation
template<S32 NUM_DIMENSIONS, typename Object> anonymous enum protected
Enumerator
MIN
MAX
Constructor & Destructor Documentation
template<S32 NUM_DIMENSIONS, class Object > ScopeTracker< NUM_DIMENSIONS, Object >::ScopeTracker ()
References dMemset(), ScopeTracker< NUM_DIMENSIONS, Object >::MAX, ScopeTracker< NUM_DIMENSIONS, Object >::mBoundaryNodes, ScopeTracker< NUM_DIMENSIONS, Object >::MIN, ScopeTracker< NUM_DIMENSIONS, Object >::mPotentialScopeInObjects, and ScopeTracker< NUM_DIMENSIONS, Object >::mTrackingList.
Member Function Documentation
template<S32 NUM_DIMENSIONS, class Object > void ScopeTracker< NUM_DIMENSIONS, Object >::_initTracking () protected
References ScopeTracker< NUM_DIMENSIONS, Object >::_insertTrackingNode(), ScopeTracker< NUM_DIMENSIONS, Object >::_onScopeIn(), ScopeTracker< NUM_DIMENSIONS, Object >::getReferenceObject(), ScopeTracker< NUM_DIMENSIONS, Object >::mReferenceObject, and ScopeTracker< NUM_DIMENSIONS, Object >::mTrackingList.
Referenced by ScopeTracker< NUM_DIMENSIONS, Object >::setReferenceObject().
template<S32 NUM_DIMENSIONS, class Object > void ScopeTracker< NUM_DIMENSIONS, Object >::_insertTrackingNode (U32 dimension, NodeType * node) protected
References ScopeTracker< NUM_DIMENSIONS, Object >::MIN, and ScopeTracker< NUM_DIMENSIONS, Object >::mTrackingList.
Referenced by ScopeTracker< NUM_DIMENSIONS, Object >::_initTracking(), and ScopeTracker< NUM_DIMENSIONS, Object >::registerObject().
template<S32 NUM_DIMENSIONS, class Object > void ScopeTracker< NUM_DIMENSIONS, Object >::_moveTrackingNode (U32 dimension, NodeType * node, F32 newPos) protected
References ScopeTracker< NUM_DIMENSIONS, Object >::_onScopeOut(), ScopeTracker< NUM_DIMENSIONS, Object >::mPotentialScopeInObjects, and Vector< T >::push_back().
Referenced by ScopeTracker< NUM_DIMENSIONS, Object >::updateObject().
template<S32 NUM_DIMENSIONS, typename Object> virtual void ScopeTracker< NUM_DIMENSIONS, Object >::_onScopeIn (Object object) inline protected virtual
Reimplemented in SFXWorld< NUM_DIMENSIONS, Object >, and SFXWorld< 3, SFX3DObject * >.
Referenced by ScopeTracker< NUM_DIMENSIONS, Object >::_initTracking(), ScopeTracker< NUM_DIMENSIONS, Object >::_setScope(), and ScopeTracker< NUM_DIMENSIONS, Object >::updateObject().
template<S32 NUM_DIMENSIONS, typename Object> virtual void ScopeTracker< NUM_DIMENSIONS, Object >::_onScopeOut (Object object) inline protected virtual
Reimplemented in SFXWorld< NUM_DIMENSIONS, Object >, and SFXWorld< 3, SFX3DObject * >.
Referenced by ScopeTracker< NUM_DIMENSIONS, Object >::_moveTrackingNode(), ScopeTracker< NUM_DIMENSIONS, Object >::_setScope(), ScopeTracker< NUM_DIMENSIONS, Object >::_uninitTracking(), ScopeTracker< NUM_DIMENSIONS, Object >::unregisterObject(), and ScopeTracker< NUM_DIMENSIONS, Object >::updateObject().
template<S32 NUM_DIMENSIONS, class Object > void ScopeTracker< NUM_DIMENSIONS, Object >::_removeTrackingNode (U32 dimension, NodeType * node) protected
Referenced by ScopeTracker< NUM_DIMENSIONS, Object >::_uninitTracking(), and ScopeTracker< NUM_DIMENSIONS, Object >::unregisterObject().
template<S32 NUM_DIMENSIONS, class Object> void ScopeTracker< NUM_DIMENSIONS, Object >::_setScope (Object object) protected
Set the scoping state of the given object.
References ScopeTracker< NUM_DIMENSIONS, Object >::_onScopeIn(), ScopeTracker< NUM_DIMENSIONS, Object >::_onScopeOut(), and ScopeTracker< NUM_DIMENSIONS, Object >::mReferenceObject.
Referenced by ScopeTracker< NUM_DIMENSIONS, Object >::registerObject().
template<S32 NUM_DIMENSIONS, class Object > void ScopeTracker< NUM_DIMENSIONS, Object >::_uninitTracking () protected
References ScopeTracker< NUM_DIMENSIONS, Object >::_onScopeOut(), ScopeTracker< NUM_DIMENSIONS, Object >::_removeTrackingNode(), ScopeTracker< NUM_DIMENSIONS, Object >::getReferenceObject(), ScopeTracker< NUM_DIMENSIONS, Object >::mReferenceObject, and ScopeTracker< NUM_DIMENSIONS, Object >::mTrackingList.
Referenced by ScopeTracker< NUM_DIMENSIONS, Object >::setReferenceObject().
template<S32 NUM_DIMENSIONS, class Object > void ScopeTracker< NUM_DIMENSIONS, Object >::debugDump ()
References String::c_str(), ScopeTracker< NUM_DIMENSIONS, Object >::mTrackingList, and Con::printf().
template<S32 NUM_DIMENSIONS, typename Object> Object ScopeTracker< NUM_DIMENSIONS, Object >::getReferenceObject () const inline
Referenced by ScopeTracker< NUM_DIMENSIONS, Object >::_initTracking(), and ScopeTracker< NUM_DIMENSIONS, Object >::_uninitTracking().
template<S32 NUM_DIMENSIONS, class Object> void ScopeTracker< NUM_DIMENSIONS, Object >::registerObject (Object object)
Add a volume object to the world.
References ScopeTracker< NUM_DIMENSIONS, Object >::_insertTrackingNode(), and ScopeTracker< NUM_DIMENSIONS, Object >::_setScope().
template<S32 NUM_DIMENSIONS, class Object> void ScopeTracker< NUM_DIMENSIONS, Object >::setReferenceObject (Object object)
Note
Switching reference centers is potentially costly.
References ScopeTracker< NUM_DIMENSIONS, Object >::_initTracking(), ScopeTracker< NUM_DIMENSIONS, Object >::_uninitTracking(), ScopeTracker< NUM_DIMENSIONS, Object >::mReferenceObject, and Platform::outputDebugString().
template<S32 NUM_DIMENSIONS, class Object> void ScopeTracker< NUM_DIMENSIONS, Object >::unregisterObject (Object object)
Remove a volume object from the world.
References ScopeTracker< NUM_DIMENSIONS, Object >::_onScopeOut(), and ScopeTracker< NUM_DIMENSIONS, Object >::_removeTrackingNode().
template<S32 NUM_DIMENSIONS, class Object> void ScopeTracker< NUM_DIMENSIONS, Object >::updateObject (Object object)
Update the position of the object in the world.
References ScopeTracker< NUM_DIMENSIONS, Object >::_moveTrackingNode(), ScopeTracker< NUM_DIMENSIONS, Object >::_onScopeIn(), ScopeTracker< NUM_DIMENSIONS, Object >::_onScopeOut(), Vector< T >::decrement(), Vector< T >::empty(), Vector< T >::last(), ScopeTracker< NUM_DIMENSIONS, Object >::mPotentialScopeInObjects, and ScopeTracker< NUM_DIMENSIONS, Object >::mReferenceObject.
Member Data Documentation
template<S32 NUM_DIMENSIONS, typename Object> NodeType ScopeTracker< NUM_DIMENSIONS, Object >::mBoundaryNodes[NUM_DIMENSIONS][2] protected
Referenced by ScopeTracker< NUM_DIMENSIONS, Object >::ScopeTracker().
template<S32 NUM_DIMENSIONS, typename Object> Vector< Object > ScopeTracker< NUM_DIMENSIONS, Object >::mPotentialScopeInObjects protected
Referenced by ScopeTracker< NUM_DIMENSIONS, Object >::_moveTrackingNode(), ScopeTracker< NUM_DIMENSIONS, Object >::ScopeTracker(), and ScopeTracker< NUM_DIMENSIONS, Object >::updateObject().
template<S32 NUM_DIMENSIONS, typename Object> Object ScopeTracker< NUM_DIMENSIONS, Object >::mReferenceObject protected
The reference object.
This is the center relative to which all tracking occurs. Any other object is in scope when it contains the reference object.
Referenced by ScopeTracker< NUM_DIMENSIONS, Object >::_initTracking(), ScopeTracker< NUM_DIMENSIONS, Object >::_setScope(), ScopeTracker< NUM_DIMENSIONS, Object >::_uninitTracking(), ScopeTracker< NUM_DIMENSIONS, Object >::setReferenceObject(), and ScopeTracker< NUM_DIMENSIONS, Object >::updateObject().
template<S32 NUM_DIMENSIONS, typename Object> NodeType* ScopeTracker< NUM_DIMENSIONS, Object >::mTrackingList[NUM_DIMENSIONS][2] protected
Referenced by ScopeTracker< NUM_DIMENSIONS, Object >::_initTracking(), ScopeTracker< NUM_DIMENSIONS, Object >::_insertTrackingNode(), ScopeTracker< NUM_DIMENSIONS, Object >::_uninitTracking(), ScopeTracker< NUM_DIMENSIONS, Object >::debugDump(), and ScopeTracker< NUM_DIMENSIONS, Object >::ScopeTracker().
Copyright © GarageGames, LLC. All Rights Reserved.