GFXD3D11TextureTarget Class Reference
Main Modules Class List Namespace List Online
GFXD3D11TextureTarget Class Reference
#include <gfx/D3D11/gfxD3D11Target.h>
Public Member Functions
GFXD3D11TextureTarget ()
~GFXD3D11TextureTarget ()
virtual void activate ()
This is called to set the render target.
virtual void attachTexture (RenderSlot slot, GFXTextureObject *tex, U32 mipLevel=0, U32 zOffset=0)
Attach a surface to a given slot as part of this render target.
virtual void attachTexture (RenderSlot slot, GFXCubemap *tex, U32 face, U32 mipLevel=0)
Support binding to cubemaps.
virtual void deactivate ()
This is called when the target is not being used anymore.
virtual GFXFormat getFormat ()
Returns the texture format of the render target.
virtual const Point2I getSize ()
Returns the size in pixels of the render target.
virtual void resolve ()
Resolve the current render target data to the associated textures.
virtual void resolveTo (GFXTextureObject *tex)
Note we always copy the Color0 RenderSlot.
void resurrect ()
When called the resource should restore all device sensitive information destroyed by zombify()
void zombify ()
When called the resource should destroy all device sensitive information (e.g. D3D resources in D3DPOOL_DEFAULT.
Public Member Functions inherited from GFXTextureTarget
virtual ~GFXTextureTarget ()
Public Member Functions inherited from GFXTarget
GFXTarget ()
Constructor to initialize the state tracking logic.
virtual ~GFXTarget ()
virtual const String describeSelf () const
The resource should put a description of itself (number of vertices, size/width of texture, etc.) in buffer.
const bool isPendingState () const
Called to check if we have pending state for the device to apply.
virtual void preserve ()
This tells the target that the contents of this target should be restored when activate() is next called.
Public Member Functions inherited from StrongRefBase
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Public Member Functions inherited from GFXResource
GFXResource ()
virtual ~GFXResource ()
void clearFlag ()
GFXResource * getNextResource () const
GFXDevice * getOwningDevice () const
GFXResource * getPrevResource () const
bool isFlagged ()
void registerResourceWithDevice (GFXDevice *device)
Registers this resource with the given device.
void setFlag ()
Additional Inherited Members
Public Types inherited from GFXTextureTarget
enum RenderSlot {
DepthStencil,
Color0,
Color1,
Color2,
Color3,
Color4,
MaxRenderSlotId
}
Static Public Attributes inherited from GFXTextureTarget
static GFXTextureObject * sDefaultDepthStencil
Protected Member Functions inherited from GFXTarget
void invalidateState ()
Called whenever a change is made to this target.
void stateApplied ()
Called when the device has applied pending state.
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Protected Attributes inherited from StrongRefBase
U32 mRefCount
reference counter for StrongRefPtr objects
Constructor & Destructor Documentation
GFXD3D11TextureTarget::GFXD3D11TextureTarget ()
GFXD3D11TextureTarget::~GFXD3D11TextureTarget ()
Member Function Documentation
virtual void GFXD3D11TextureTarget::activate () virtual
This is called to set the render target.
Reimplemented from GFXTarget.
Referenced by getFormat().
virtual void GFXD3D11TextureTarget::attachTexture (RenderSlot slot, GFXTextureObject * tex, U32 mipLevel = 0, U32 zOffset = 0) virtual
Attach a surface to a given slot as part of this render target.
Parameters
slot What slot is used for multiple render target (MRT) effects. Most of the time you'll use Color0.
tex A texture and miplevel to bind for rendering, or else NULL/0 to clear a slot.
mipLevel What level of this texture are we rendering to?
zOffset If this is a depth texture, what z level are we rendering to?
Implements GFXTextureTarget.
Referenced by getFormat().
virtual void GFXD3D11TextureTarget::attachTexture (RenderSlot slot, GFXCubemap * tex, U32 face, U32 mipLevel = 0) virtual
Support binding to cubemaps.
Parameters
slot What slot is used for multiple render target (MRT) effects. Most of the time you'll use Color0.
tex What cubemap will we be rendering to?
face A face identifier.
mipLevel What level of this texture are we rendering to?
Implements GFXTextureTarget.
virtual void GFXD3D11TextureTarget::deactivate () virtual
This is called when the target is not being used anymore.
Reimplemented from GFXTarget.
Referenced by getFormat().
virtual GFXFormat GFXD3D11TextureTarget::getFormat () inline virtual
Returns the texture format of the render target.
Implements GFXTarget.
References activate(), attachTexture(), deactivate(), resolve(), resolveTo(), resurrect(), and zombify().
virtual const Point2I GFXD3D11TextureTarget::getSize () inline virtual
Returns the size in pixels of the render target.
Implements GFXTarget.
virtual void GFXD3D11TextureTarget::resolve () virtual
Resolve the current render target data to the associated textures.
This method will get called automatically when a rendertarget is changed, before new geometry is drawn to a different rendertarget. This method can also be called to gather render target data without switching targets.
By default, this method will resolve all color targets.
Implements GFXTextureTarget.
Referenced by getFormat().
virtual void GFXD3D11TextureTarget::resolveTo (GFXTextureObject * tex) virtual
Note we always copy the Color0 RenderSlot.
Reimplemented from GFXTarget.
Referenced by getFormat().
void GFXD3D11TextureTarget::resurrect () virtual
When called the resource should restore all device sensitive information destroyed by zombify()
Implements GFXResource.
Referenced by getFormat().
void GFXD3D11TextureTarget::zombify () virtual
When called the resource should destroy all device sensitive information (e.g. D3D resources in D3DPOOL_DEFAULT.
Implements GFXResource.
Referenced by getFormat().
Copyright © GarageGames, LLC. All Rights Reserved.