RectD Class Reference
Main Modules Class List Namespace List Online
RectD Class Reference
#include <math/mRect.h>
Public Member Functions
RectD ()
RectD (const Point2D &in_rMin, const Point2D &in_rExtent)
RectD (const F64 in_left, const F64 in_top, const F64 in_width, const F64 in_height)
void inset (F64 x, F64 y)
bool intersect (const RectD &clipRect)
bool isValidRect () const
F64 len_x () const
F64 len_y () const
Public Attributes
Point2D extent
Point2D point
Constructor & Destructor Documentation
RectD::RectD () inline
References RectI::inset(), RectI::intersect(), RectI::len_x(), and RectI::len_y().
RectD::RectD (const Point2D & in_rMin, const Point2D & in_rExtent) inline
RectD::RectD (const F64 in_left, const F64 in_top, const F64 in_width, const F64 in_height) inline
Member Function Documentation
void RectD::inset (F64 x, F64 y) inline
References RectI::extent, RectI::point, Point2I::x, and Point2I::y.
bool RectD::intersect (const RectD & clipRect) inline
References extent, isValidRect(), point, Point2D::x, and Point2D::y.
bool RectD::isValidRect () const inline
References Point2D::x, and Point2D::y.
Referenced by intersect().
F64 RectD::len_x () const inline
References extent, and Point2D::x.
F64 RectD::len_y () const inline
References extent, and Point2D::y.
Member Data Documentation
Point2D RectD::extent
Referenced by intersect(), len_x(), and len_y().
Point2D RectD::point
Referenced by intersect().
Copyright © GarageGames, LLC. All Rights Reserved.