ShadowBase Class Reference
Main Modules Class List Namespace List Online
ShadowBase Class Reference abstract
#include <lighting/common/shadowBase.h>
Public Member Functions
virtual ~ShadowBase ()
virtual U32 getLastRenderTime () const =0
virtual const F32 getScore () const =0
virtual void render (F32 camDist, const TSRenderState &rdata)=0
virtual bool shouldRender (const SceneRenderState *state)=0
virtual void update (const SceneRenderState *state)=0
Constructor & Destructor Documentation
virtual ShadowBase::~ShadowBase () inline virtual
References getLastRenderTime(), getScore(), render(), shouldRender(), and update().
Member Function Documentation
virtual U32 ShadowBase::getLastRenderTime () const pure virtual
Implemented in ProjectedShadow, and BlobShadow.
Referenced by ~ShadowBase().
virtual const F32 ShadowBase::getScore () const pure virtual
Implemented in ProjectedShadow.
Referenced by ~ShadowBase().
virtual void ShadowBase::render (F32 camDist, const TSRenderState & rdata) pure virtual
Implemented in ProjectedShadow, and BlobShadow.
Referenced by ~ShadowBase().
virtual bool ShadowBase::shouldRender (const SceneRenderState * state) pure virtual
Implemented in ProjectedShadow.
Referenced by ~ShadowBase().
virtual void ShadowBase::update (const SceneRenderState * state) pure virtual
Implemented in ProjectedShadow, and BlobShadow.
Referenced by ~ShadowBase().
Copyright © GarageGames, LLC. All Rights Reserved.