BtPlayer Class Reference
Main Modules Class List Namespace List Online
BtPlayer Class Reference
#include <T3D/physics/bullet/btPlayer.h>
Public Member Functions
BtPlayer ()
virtual ~BtPlayer ()
virtual void disableCollision ()
virtual void enableCollision ()
virtual void findContact (SceneObject **contactObject, VectorF *contactNormal, Vector< SceneObject * > *outOverlapObjects) const
virtual MatrixF & getTransform (MatrixF *outMatrix)
Returns the transform of the physics body at the last processed simulation tick.
virtual PhysicsWorld * getWorld ()
Returns the physics world this object is a member of.
virtual Box3F getWorldBounds ()
Returns the world aligned bounding box containing the PhysicsObject.
virtual void init (const char *type, const Point3F &size, F32 runSurfaceCos, F32 stepHeight, SceneObject *obj, PhysicsWorld *world)
virtual bool isSimulationEnabled ()
virtual Point3F move (const VectorF &displacement, CollisionList &outCol)
virtual void setScale (const Point3F &scale)
virtual void setSimulationEnabled (bool enabled)
Set false to skip simulation of this object or temporarily remove it from the physics simulation.
virtual void setSpacials (const Point3F &nPos, const Point3F &nSize)
virtual void setTransform (const MatrixF &transform)
Sets the transform on the physics object.
virtual bool testSpacials (const Point3F &nPos, const Point3F &nSize) const
Public Member Functions inherited from PhysicsPlayer
PhysicsPlayer ()
virtual ~PhysicsPlayer ()
Public Member Functions inherited from PhysicsObject
virtual ~PhysicsObject ()
const PhysicsUserData & getUserData () const
PhysicsUserData & getUserData ()
void queueCallback (U32 ms, Delegate< void()> callback)
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Protected Member Functions
bool _recoverFromPenetration ()
void _releaseController ()
void _stepForward (btVector3 *inOutCurrPos, const btVector3 &displacement, CollisionList *outCol)
bool _sweep (btVector3 *inOutCurrPos, const btVector3 &disp, CollisionList *outCol)
Protected Member Functions inherited from PhysicsObject
PhysicsObject ()
You shouldn't be creating this object directly.
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Protected Attributes
btConvexShape * mColShape
btPairCachingGhostObject * mGhostObject
SceneObject * mObject
F32 mOriginOffset
F32 mSlopeAngle
F32 mStepHeight
BtWorld * mWorld
Protected Attributes inherited from PhysicsObject
U32 mQueuedEvent
The last queued callback event.
PhysicsUserData mUserData
The user data object assigned to this object.
Constructor & Destructor Documentation
BtPlayer::BtPlayer ()
virtual BtPlayer::~BtPlayer () virtual
Member Function Documentation
bool BtPlayer::_recoverFromPenetration () protected
void BtPlayer::_releaseController () protected
void BtPlayer::_stepForward (btVector3 * inOutCurrPos, const btVector3 & displacement, CollisionList * outCol) protected
bool BtPlayer::_sweep (btVector3 * inOutCurrPos, const btVector3 & disp, CollisionList * outCol) protected
virtual void BtPlayer::disableCollision () virtual
Implements PhysicsPlayer.
Referenced by setSpacials().
virtual void BtPlayer::enableCollision () virtual
Implements PhysicsPlayer.
Referenced by setSpacials().
virtual void BtPlayer::findContact (SceneObject ** contactObject, VectorF * contactNormal, Vector< SceneObject * > * outOverlapObjects) const virtual
Implements PhysicsPlayer.
Referenced by isSimulationEnabled().
virtual MatrixF& BtPlayer::getTransform (MatrixF * outMatrix) virtual
Returns the transform of the physics body at the last processed simulation tick.
Implements PhysicsObject.
virtual PhysicsWorld* BtPlayer::getWorld () virtual
Returns the physics world this object is a member of.
Implements PhysicsObject.
virtual Box3F BtPlayer::getWorldBounds () inline virtual
Returns the world aligned bounding box containing the PhysicsObject.
Implements PhysicsObject.
References Box3F::Invalid.
virtual void BtPlayer::init (const char * type, const Point3F & size, F32 runSurfaceCos, F32 stepHeight, SceneObject * obj, PhysicsWorld * world) virtual
Implements PhysicsPlayer.
Referenced by isSimulationEnabled().
virtual bool BtPlayer::isSimulationEnabled () inline virtual
Implements PhysicsObject.
References findContact(), init(), and move().
virtual Point3F BtPlayer::move (const VectorF & displacement, CollisionList & outCol) virtual
Implements PhysicsPlayer.
Referenced by isSimulationEnabled().
virtual void BtPlayer::setScale (const Point3F & scale) virtual
virtual void BtPlayer::setSimulationEnabled (bool enabled) inline virtual
Set false to skip simulation of this object or temporarily remove it from the physics simulation.
Implementation is PhysicsPlugin specific.
Implements PhysicsObject.
virtual void BtPlayer::setSpacials (const Point3F & nPos, const Point3F & nSize) inline virtual
Implements PhysicsPlayer.
References disableCollision(), and enableCollision().
virtual void BtPlayer::setTransform (const MatrixF & transform) virtual
Sets the transform on the physics object.
For static objects this is only intended to be used for for infrequent changes when editing the mission.
Implements PhysicsObject.
virtual bool BtPlayer::testSpacials (const Point3F & nPos, const Point3F & nSize) const inline virtual
Implements PhysicsPlayer.
Member Data Documentation
btConvexShape* BtPlayer::mColShape protected
btPairCachingGhostObject* BtPlayer::mGhostObject protected
SceneObject* BtPlayer::mObject protected
F32 BtPlayer::mOriginOffset protected
F32 BtPlayer::mSlopeAngle protected
F32 BtPlayer::mStepHeight protected
BtWorld* BtPlayer::mWorld protected
Copyright © GarageGames, LLC. All Rights Reserved.