TelnetDebugger Class Reference
Main Modules Class List Namespace List Online
TelnetDebugger Class Reference
Telnet debug service implementation.
#include <console/telnetDebugger.h>
Public Member Functions
void addAllBreakpoints (CodeBlock *code)
void breakProcess ()
void clearCodeBlockPointers (CodeBlock *code)
void disconnect ()
void executionStopped (CodeBlock *code, U32 lineNumber)
bool isConnected () const
void popStackFrame ()
void process ()
void processConsoleLine (const char *consoleLine)
void pushStackFrame ()
void send (const char *s)
void setDebugParameters (S32 port, const char *password, bool waitForClient)
Static Public Member Functions
static void create ()
static void destroy ()
Detailed Description
Telnet debug service implementation.
This is the C++ side of the built-in Torque debugger.
To use the debugger, use dbgSetParameters(port, password); in the console of the server to enable debugger connections. Then on some other system, start up the app (you don't have to start a game or connect to the server) and exec("common/debugger/debugger.cs"); in the console. Then use the debugger GUI to connect to the server with the right port and password.
See also
http://www.planettribes.com/tribes2/editing.shtml for more thorough discussion.
Member Function Documentation
void TelnetDebugger::addAllBreakpoints (CodeBlock * code)
Referenced by isConnected().
void TelnetDebugger::breakProcess ()
Referenced by isConnected().
void TelnetDebugger::clearCodeBlockPointers (CodeBlock * code)
Referenced by isConnected().
static void TelnetDebugger::create () static
static void TelnetDebugger::destroy () static
void TelnetDebugger::disconnect ()
void TelnetDebugger::executionStopped (CodeBlock * code, U32 lineNumber)
Referenced by isConnected().
bool TelnetDebugger::isConnected () const inline
References addAllBreakpoints(), breakProcess(), clearCodeBlockPointers(), executionStopped(), popStackFrame(), process(), processConsoleLine(), pushStackFrame(), send(), and setDebugParameters().
void TelnetDebugger::popStackFrame ()
Referenced by isConnected().
void TelnetDebugger::process ()
Referenced by isConnected().
void TelnetDebugger::processConsoleLine (const char * consoleLine)
Referenced by isConnected().
void TelnetDebugger::pushStackFrame ()
Referenced by isConnected().
void TelnetDebugger::send (const char * s)
Referenced by isConnected().
void TelnetDebugger::setDebugParameters (S32 port, const char * password, bool waitForClient)
Referenced by isConnected().
Copyright © GarageGames, LLC. All Rights Reserved.