RiverSegment Class Reference
Main Modules Class List Namespace List Online
RiverSegment Class Reference
#include <environment/river.h>
Public Member Functions
RiverSegment ()
RiverSegment (RiverSlice *rs0, RiverSlice *rs1)
bool containsPoint (const Point3F &pnt) const
F32 distanceToSurface (const Point3F &pnt) const
Point3F getFaceCenter (U32 faceIdx) const
Point3F getP00 () const
Point3F getP01 () const
Point3F getP10 () const
Point3F getP11 () const
Point3F getSurfaceCenter () const
Point3F getSurfaceNormal () const
bool intersectBox (const Box3F &bounds) const
Point3F & operator[] (U32)
const Point3F & operator[] (U32) const
Point3F & operator[] (S32 i)
const Point3F & operator[] (S32 i) const
void set (RiverSlice *rs0, RiverSlice *rs1)
F32 TexCoordEnd ()
F32 TexCoordStart ()
Public Attributes
U32 columns
U32 endIndex
U32 endVert
U32 mPlaneCount
PlaneF mPlanes [6]
U32 numTriangles
U32 numVerts
U32 rows
RiverSlice * slice0
RiverSlice * slice1
U32 startIndex
U32 startVert
Box3F worldbounds
Protected Member Functions
PlaneF _getBestPlane (const Point3F *p0, const Point3F *p1, const Point3F *p2, const Point3F *p3)
Constructor & Destructor Documentation
RiverSegment::RiverSegment ()
RiverSegment::RiverSegment (RiverSlice * rs0, RiverSlice * rs1)
Member Function Documentation
PlaneF RiverSegment::_getBestPlane (const Point3F * p0, const Point3F * p1, const Point3F * p2, const Point3F * p3) protected
bool RiverSegment::containsPoint (const Point3F & pnt) const
F32 RiverSegment::distanceToSurface (const Point3F & pnt) const
Point3F RiverSegment::getFaceCenter (U32 faceIdx) const
Point3F RiverSegment::getP00 () const inline
Point3F RiverSegment::getP01 () const inline
Point3F RiverSegment::getP10 () const inline
Point3F RiverSegment::getP11 () const inline
Point3F RiverSegment::getSurfaceCenter () const inline
Point3F RiverSegment::getSurfaceNormal () const inline
bool RiverSegment::intersectBox (const Box3F & bounds) const
Point3F & RiverSegment::operator[] (U32 index) inline
References RiverSlice::p0, RiverSlice::p2, RiverSlice::pb0, and RiverSlice::pb2.
const Point3F & RiverSegment::operator[] (U32 index) const inline
References RiverSlice::p0, RiverSlice::p2, RiverSlice::pb0, and RiverSlice::pb2.
Point3F& RiverSegment::operator[] (S32 i) inline
References operator[]().
Referenced by operator[]().
const Point3F& RiverSegment::operator[] (S32 i) const inline
References operator[]().
Referenced by operator[]().
void RiverSegment::set (RiverSlice * rs0, RiverSlice * rs1)
F32 RiverSegment::TexCoordEnd () inline
F32 RiverSegment::TexCoordStart () inline
Member Data Documentation
U32 RiverSegment::columns
U32 RiverSegment::endIndex
U32 RiverSegment::endVert
U32 RiverSegment::mPlaneCount
PlaneF RiverSegment::mPlanes[6]
U32 RiverSegment::numTriangles
U32 RiverSegment::numVerts
U32 RiverSegment::rows
RiverSlice* RiverSegment::slice0
RiverSlice* RiverSegment::slice1
U32 RiverSegment::startIndex
U32 RiverSegment::startVert
Box3F RiverSegment::worldbounds
Copyright © GarageGames, LLC. All Rights Reserved.