TypeValidator Class Reference
Main Modules Class List Namespace List Online
TypeValidator Class Reference abstract
#include <console/typeValidators.h>
Public Member Functions
void consoleError (SimObject *object, const char *format,...)
Prints a console error message for the validator.
virtual void validateType (SimObject *object, void *typePtr)=0
validateType is called for each assigned value on the field this validator is attached to.
Public Attributes
S32 fieldIndex
Member Function Documentation
void TypeValidator::consoleError (SimObject * object, const char * format, ...)
Prints a console error message for the validator.
The message is prefaced with with:
className objectName (objectId) - invalid value for fieldName: msg
virtual void TypeValidator::validateType (SimObject * object, void * typePtr) pure virtual
validateType is called for each assigned value on the field this validator is attached to.
Implemented in Point3NormalizeValidator, IRangeValidatorScaled, IRangeValidator, and FRangeValidator.
Referenced by FRangeValidator::FRangeValidator(), IRangeValidator::IRangeValidator(), IRangeValidatorScaled::IRangeValidatorScaled(), and Point3NormalizeValidator::Point3NormalizeValidator().
Member Data Documentation
S32 TypeValidator::fieldIndex
Copyright © GarageGames, LLC. All Rights Reserved.