ColladaAppSequence Class Reference
Main Modules Class List Namespace List Online
ColladaAppSequence Class Reference
#include <ts/collada/colladaAppSequence.h>
Public Member Functions
ColladaAppSequence (const domAnimation_clip *clip)
~ColladaAppSequence ()
F32 getBlendRefTime ()
const domAnimation_clip * getClip () const
F32 getEnd () const
U32 getFlags () const
const char * getName () const
S32 getNumTriggers ()
F32 getPriority ()
F32 getStart () const
void getTrigger (S32 index, TSShape::Trigger &trigger)
void setActive (bool active)
void setEnd (F32 end)
Public Member Functions inherited from AppSequence
AppSequence ()
virtual ~AppSequence ()
virtual F32 getBlendRefTime () const
virtual S32 getNumTriggers () const
virtual F32 getPriority () const
virtual void getTrigger (S32 index, TSShape::Trigger &trigger) const
Additional Inherited Members
Public Attributes inherited from AppSequence
S32 fps
Constructor & Destructor Documentation
ColladaAppSequence::ColladaAppSequence (const domAnimation_clip * clip)
ColladaAppSequence::~ColladaAppSequence ()
Member Function Documentation
F32 ColladaAppSequence::getBlendRefTime ()
Referenced by setEnd().
const domAnimation_clip* ColladaAppSequence::getClip () const inline
References getName(), getNumTriggers(), and getTrigger().
F32 ColladaAppSequence::getEnd () const inline virtual
Reimplemented from AppSequence.
U32 ColladaAppSequence::getFlags () const virtual
Reimplemented from AppSequence.
Referenced by setEnd().
const char* ColladaAppSequence::getName () const virtual
Reimplemented from AppSequence.
Referenced by getClip().
S32 ColladaAppSequence::getNumTriggers ()
Referenced by getClip().
F32 ColladaAppSequence::getPriority ()
Referenced by setEnd().
F32 ColladaAppSequence::getStart () const inline virtual
Reimplemented from AppSequence.
void ColladaAppSequence::getTrigger (S32 index, TSShape::Trigger & trigger)
Referenced by getClip().
void ColladaAppSequence::setActive (bool active) virtual
Reimplemented from AppSequence.
void ColladaAppSequence::setEnd (F32 end) inline
References getBlendRefTime(), getFlags(), and getPriority().
Copyright © GarageGames, LLC. All Rights Reserved.