BtDebugDraw Class Reference
Main Modules Class List Namespace List Online
BtDebugDraw Class Reference
#include <T3D/physics/bullet/btDebugDraw.h>
Public Member Functions
BtDebugDraw ()
virtual void draw3dText (const btVector3 &location, const char *textString)
virtual void drawContactPoint (const btVector3 &PointOnB, const btVector3 &normalOnB, btScalar distance, int lifeTime, const btVector3 &color)
virtual void drawLine (const btVector3 &from, const btVector3 &to, const btVector3 &color)
virtual void drawTriangle (const btVector3 &v0, const btVector3 &v1, const btVector3 &v2, const btVector3 &color, btScalar)
void flush ()
Call this after debug drawing to submit any remaining primitives for rendering.
virtual int getDebugMode () const
virtual void reportErrorWarning (const char *warningString)
void setCuller (const Frustum *culler)
Sets the culler which we use to cull out primitives that are completely offscreen.
virtual void setDebugMode (int debugMode)
Protected Attributes
const Frustum * mCuller
The frustum to use for culling or NULL.
U32 mVertexCount
The number of verts we've used in rendering.
Constructor & Destructor Documentation
BtDebugDraw::BtDebugDraw () inline
Member Function Documentation
virtual void BtDebugDraw::draw3dText (const btVector3 & location, const char * textString) inline virtual
virtual void BtDebugDraw::drawContactPoint (const btVector3 & PointOnB, const btVector3 & normalOnB, btScalar distance, int lifeTime, const btVector3 & color) virtual
Referenced by setCuller().
virtual void BtDebugDraw::drawLine (const btVector3 & from, const btVector3 & to, const btVector3 & color) virtual
Referenced by setCuller().
virtual void BtDebugDraw::drawTriangle (const btVector3 & v0, const btVector3 & v1, const btVector3 & v2, const btVector3 & color, btScalar) virtual
Referenced by setCuller().
void BtDebugDraw::flush ()
Call this after debug drawing to submit any remaining primitives for rendering.
Referenced by setCuller().
virtual int BtDebugDraw::getDebugMode () const inline virtual
virtual void BtDebugDraw::reportErrorWarning (const char * warningString) inline virtual
void BtDebugDraw::setCuller (const Frustum * culler) inline
Sets the culler which we use to cull out primitives that are completely offscreen.
References drawContactPoint(), drawLine(), drawTriangle(), and flush().
virtual void BtDebugDraw::setDebugMode (int debugMode) inline virtual
Member Data Documentation
const Frustum* BtDebugDraw::mCuller protected
The frustum to use for culling or NULL.
U32 BtDebugDraw::mVertexCount protected
The number of verts we've used in rendering.
Copyright © GarageGames, LLC. All Rights Reserved.