AsyncPacketBufferedInputStream< Stream, Packet > Class Template Reference
Main Modules Class List Namespace List Online
AsyncPacketBufferedInputStream< Stream, Packet > Class Template Reference
A packet stream turns a continuous stream of elements into a stream of discrete packets of elements.
#include <platform/async/asyncPacketStream.h>
Classes
class PacketReadItem
Asynchronous work item for reading a packet from the source stream.
Public Types
typedef Packet PacketType
typedef AsyncBufferedInputStream< Packet *, Stream > Parent
typedef TypeTraits< Stream >::BaseType StreamType
Public Types inherited from AsyncBufferedInputStream< Packet *, Stream >
enum
typedef Parent::ElementType ElementType
Type of elements read, buffered, and returned by this stream.
typedef IInputStreamFilter< Packet *, Stream > Parent
typedef Parent::SourceElementType SourceElementType
Type of elements being read from the source stream.
typedef Parent::SourceStreamType SourceStreamType
Type of the source stream being read by this stream.
Public Types inherited from IInputStreamFilter< Packet *, Stream >
typedef IInputStream< Packet * > Parent
typedef SourceStreamType::ElementType SourceElementType
The element type of the source stream.
typedef TypeTraits< Stream >::BaseType SourceStreamType
Public Types inherited from IInputStream< Packet * >
typedef Packet * ElementType
The element type of this input stream.
typedef void Parent
Public Types inherited from ThreadSafeRefCount< AsyncBufferedInputStream< Packet *, Stream > >
typedef void Parent
Public Member Functions
AsyncPacketBufferedInputStream (const Stream &stream, U32 packetSize, U32 numSourceElementsToRead=0, U32 numReadAhead=Parent::DEFAULT_STREAM_LOOKAHEAD, bool isLooping=false, ThreadPool *pool=&ThreadPool::GLOBAL(), ThreadContext *context=ThreadContext::ROOT_CONTEXT())
Construct a new packet stream reading from "stream".
U32 getPacketSize () const
Public Member Functions inherited from AsyncBufferedInputStream< Packet *, Stream >
AsyncBufferedInputStream (const Stream &stream, U32 numSourceElementsToRead=0, U32 numReadAhead=DEFAULT_STREAM_LOOKAHEAD, bool isLooping=false, ThreadPool *pool=&ThreadPool::GLOBAL(), ThreadContext *context=ThreadContext::ROOT_CONTEXT())
Construct a new buffered stream reading from "source".
virtual ~AsyncBufferedInputStream ()
U32 getReadAhead () const
bool isLooping () const
virtual U32 read (ElementType *buffer, U32 num)
Read the next "num" elements into "buffer".
void start ()
Initiate the request chain of the element stream.
void stop ()
Call for the request chain of the element stream to stop at the next synchronization point.
Public Member Functions inherited from IInputStreamFilter< Packet *, Stream >
IInputStreamFilter (const Stream &stream)
Construct a filter reading elements from "stream".
const Stream & getSourceStream () const
Return the stream from which this filter is reading its source elements.
Stream & getSourceStream ()
Public Member Functions inherited from ThreadSafeRefCount< AsyncBufferedInputStream< Packet *, Stream > >
ThreadSafeRefCount ()
ThreadSafeRefCount (bool noSet)
void addRef ()
Increase the reference count on the object.
void clearLowestBit ()
U32 getRefCount () const
Get the current reference count.
bool isShared () const
void release ()
Decrease the object's reference count and delete the object, if the count drops to zero and claiming the object by the current thread succeeds.
Protected Types
typedef ThreadSafeRef< PacketReadItem > PacketReadItemRef
Protected Types inherited from AsyncBufferedInputStream< Packet *, Stream >
typedef ThreadSafeDeque< ElementType > ElementList
Stream elements are kept on deques that can be concurrently accessed by multiple threads.
Protected Member Functions
virtual PacketType * _newPacket (U32 packetSize)
Create a new stream packet of the given size.
virtual void _newReadItem (PacketReadItemRef &outRef, PacketType *packet, U32 numElements)
Create a new work item that reads "numElements" into "packet".
virtual void _requestNext ()
Request the next packet from the underlying stream.
Protected Member Functions inherited from AsyncBufferedInputStream< Packet *, Stream >
virtual void _onArrival (const ElementType &element)
Called when an element read has been completed on the underlying stream.
Protected Attributes
U32 mNextPacketIndex
Running number of next stream packet.
U32 mNumTotalSourceElements
Total number of elements in the source stream.
U32 mPacketSize
Number of elements to read per packet.
Protected Attributes inherited from AsyncBufferedInputStream< Packet *, Stream >
ElementList mBufferedElements
List of buffered elements.
bool mIsLooping
If true, the stream will restart over from the beginning once it has been read in entirety.
bool mIsStopped
If true, no further requests should be issued on this stream.
U32 mMaxBufferedElements
Maximum number of elements allowed on buffer list.
U32 mNumBufferedElements
Number of elements currently on buffer list.
U32 mNumRemainingSourceElements
Number of source elements remaining in the source stream.
ThreadContext * mThreadContext
The thread context used for prioritizing read items in the pool.
ThreadPool * mThreadPool
The thread pool to which read items are queued.
Protected Attributes inherited from ThreadSafeRefCount< AsyncBufferedInputStream< Packet *, Stream > >
U32 mRefCount
Reference count and claim bit. Note that this increments in steps of two.
Additional Inherited Members
Static Public Member Functions inherited from ThreadSafeRefCount< AsyncBufferedInputStream< Packet *, Stream > >
static AsyncBufferedInputStream< Packet *, Stream > * safeRead (AsyncBufferedInputStream< Packet *, Stream > *const volatile &refPtr)
Dereference a reference-counted pointer in a multi-thread safe way.
Static Protected Member Functions inherited from ThreadSafeRefCount< AsyncBufferedInputStream< Packet *, Stream > >
static U32 decrementAndTestAndSet (U32 &refCount)
Decrement the given reference count.
Detailed Description
template<typename Stream, class Packet = AsyncPacket< typename TypeTraits< Stream >::BaseType::ElementType >>
class AsyncPacketBufferedInputStream< Stream, Packet >
A packet stream turns a continuous stream of elements into a stream of discrete packets of elements.
All packets are of the exact same size even if, for end-of-stream packets, they actually contain less data than their actual size. Extraneous space is cleared.
Note
For looping streams, the stream must implement the IResettable interface.
Member Typedef Documentation
template<typename Stream, class Packet = AsyncPacket< typename TypeTraits< Stream >::BaseType::ElementType >> typedef ThreadSafeRef< PacketReadItem > AsyncPacketBufferedInputStream< Stream, Packet >::PacketReadItemRef protected
template<typename Stream, class Packet = AsyncPacket< typename TypeTraits< Stream >::BaseType::ElementType >> typedef Packet AsyncPacketBufferedInputStream< Stream, Packet >::PacketType
template<typename Stream, class Packet = AsyncPacket< typename TypeTraits< Stream >::BaseType::ElementType >> typedef AsyncBufferedInputStream< Packet*, Stream > AsyncPacketBufferedInputStream< Stream, Packet >::Parent
template<typename Stream, class Packet = AsyncPacket< typename TypeTraits< Stream >::BaseType::ElementType >> typedef TypeTraits< Stream >::BaseType AsyncPacketBufferedInputStream< Stream, Packet >::StreamType
Constructor & Destructor Documentation
template<typename Stream, class Packet > AsyncPacketBufferedInputStream< Stream, Packet >::AsyncPacketBufferedInputStream (const Stream & stream, U32 packetSize, U32 numSourceElementsToRead = 0, U32 numReadAhead = Parent::DEFAULT_STREAM_LOOKAHEAD, bool isLooping = false, ThreadPool * pool = &ThreadPool::GLOBAL(), ThreadContext * context = ThreadContext::ROOT_CONTEXT())
Construct a new packet stream reading from "stream".
Note
If looping is used and "stream" is not read from the beginning, "stream" should implement IPositionable<U32> or ISizeable<U32> so the async stream can tell how many elements there actually are in the stream after resetting.
Parameters
stream The source stream from which to read the actual data elements.
packetSize Size of stream packets returned by the stream in number of elements.
numSourceElementsToRead Number of elements to read from "stream".
numReadAhead Number of packets to read and buffer in advance.
isLooping If true, the packet stream will loop infinitely over the source stream.
pool The ThreadPool to use for asynchronous packet reads.
context The ThreadContext to place asynchronous packet reads in.
References IPositionable< P >::getPosition(), ISizeable< T >::getSize(), and Platform::outputDebugString().
Referenced by AsyncPacketBufferedInputStream< SFXStreamRef, SFXStreamPacket >::getPacketSize().
Member Function Documentation
template<typename Stream, class Packet = AsyncPacket< typename TypeTraits< Stream >::BaseType::ElementType >> virtual PacketType* AsyncPacketBufferedInputStream< Stream, Packet >::_newPacket (U32 packetSize) inline protected virtual
Create a new stream packet of the given size.
Reimplemented in SFXInternal::SFXAsyncStream.
template<typename Stream, class Packet = AsyncPacket< typename TypeTraits< Stream >::BaseType::ElementType >> virtual void AsyncPacketBufferedInputStream< Stream, Packet >::_newReadItem (PacketReadItemRef & outRef, PacketType * packet, U32 numElements) inline protected virtual
Create a new work item that reads "numElements" into "packet".
template<typename Stream , class Packet > void AsyncPacketBufferedInputStream< Stream, Packet >::_requestNext () protected virtual
Request the next packet from the underlying stream.
Implements AsyncBufferedInputStream< Packet *, Stream >.
Reimplemented in SFXInternal::SFXAsyncStream.
References Platform::outputDebugString(), and IResettable::reset().
template<typename Stream, class Packet = AsyncPacket< typename TypeTraits< Stream >::BaseType::ElementType >> U32 AsyncPacketBufferedInputStream< Stream, Packet >::getPacketSize () const inline
Returns
the size of stream packets returned by this stream in number of elements.
Member Data Documentation
template<typename Stream, class Packet = AsyncPacket< typename TypeTraits< Stream >::BaseType::ElementType >> U32 AsyncPacketBufferedInputStream< Stream, Packet >::mNextPacketIndex protected
Running number of next stream packet.
template<typename Stream, class Packet = AsyncPacket< typename TypeTraits< Stream >::BaseType::ElementType >> U32 AsyncPacketBufferedInputStream< Stream, Packet >::mNumTotalSourceElements protected
Total number of elements in the source stream.
template<typename Stream, class Packet = AsyncPacket< typename TypeTraits< Stream >::BaseType::ElementType >> U32 AsyncPacketBufferedInputStream< Stream, Packet >::mPacketSize protected
Number of elements to read per packet.
Copyright © GarageGames, LLC. All Rights Reserved.