ColladaExtension_effect Class Reference
Main Modules Class List Namespace List Online
ColladaExtension_effect Class Reference
Extensions for the <effect> element (and its children)
#include <ts/collada/colladaExtensions.h>
Public Member Functions
ColladaExtension_effect (const domEffect *effect)
bool animatesTextureTransform (F32 start, F32 end)
Check if any of the MAYA texture transform elements are animated within the interval.
void applyTextureTransform (Point2F &uv, F32 time)
Apply the MAYA texture transform to the given UV coordinates.
Public Member Functions inherited from ColladaExtension
ColladaExtension ()
virtual ~ColladaExtension ()
Public Attributes
domFx_sampler2D_common_complexType * bumpSampler
AnimatedFloat coverageU
AnimatedFloat coverageV
bool double_sided
bool mirrorU
bool mirrorV
AnimatedFloat noiseU
AnimatedFloat noiseV
AnimatedFloat offsetU
AnimatedFloat offsetV
AnimatedFloat repeatU
AnimatedFloat repeatV
AnimatedFloat rotateFrame
AnimatedFloat rotateUV
AnimatedBool stagger
AnimatedFloat translateFrameU
AnimatedFloat translateFrameV
bool wrapU
bool wrapV
Additional Inherited Members
Protected Member Functions inherited from ColladaExtension
template<class T >
const domTechnique * findExtraTechnique (const T *element, const char *name) const
Find the technique with the named profile.
const domTechnique * findExtraTechnique (const domCommon_color_or_texture_type_complexType::domTexture *element, const char *name) const
The <texture> element does not define an extra_array, so need a specialized version of the template.
const domAny * findParam (const char *name)
Find the parameter with the given name.
template<typename T >
void get (const char *name, T &value, T defaultVal)
Get the value of the named parameter (use defaultVal if parameter not found)
template<typename T >
void get (const char *name, AnimatedElement< T > &value, T defaultVal)
Get the value of the named animated parameter (use defaultVal if parameter not found)
Protected Attributes inherited from ColladaExtension
const domTechnique * pTechnique
Detailed Description
Extensions for the <effect> element (and its children)
Constructor & Destructor Documentation
ColladaExtension_effect::ColladaExtension_effect (const domEffect * effect) inline
References ColladaUtils::findEffectCommonProfile(), ColladaUtils::findEffectDiffuse(), ColladaExtension::findExtraTechnique(), ColladaUtils::getTextureSampler(), and ColladaExtension::pTechnique.
Member Function Documentation
bool ColladaExtension_effect::animatesTextureTransform (F32 start, F32 end)
Check if any of the MAYA texture transform elements are animated within the interval.
void ColladaExtension_effect::applyTextureTransform (Point2F & uv, F32 time)
Apply the MAYA texture transform to the given UV coordinates.
Member Data Documentation
domFx_sampler2D_common_complexType* ColladaExtension_effect::bumpSampler
AnimatedFloat ColladaExtension_effect::coverageU
AnimatedFloat ColladaExtension_effect::coverageV
bool ColladaExtension_effect::double_sided
bool ColladaExtension_effect::mirrorU
bool ColladaExtension_effect::mirrorV
AnimatedFloat ColladaExtension_effect::noiseU
AnimatedFloat ColladaExtension_effect::noiseV
AnimatedFloat ColladaExtension_effect::offsetU
AnimatedFloat ColladaExtension_effect::offsetV
AnimatedFloat ColladaExtension_effect::repeatU
AnimatedFloat ColladaExtension_effect::repeatV
AnimatedFloat ColladaExtension_effect::rotateFrame
AnimatedFloat ColladaExtension_effect::rotateUV
AnimatedBool ColladaExtension_effect::stagger
AnimatedFloat ColladaExtension_effect::translateFrameU
AnimatedFloat ColladaExtension_effect::translateFrameV
bool ColladaExtension_effect::wrapU
bool ColladaExtension_effect::wrapV
Copyright © GarageGames, LLC. All Rights Reserved.