ColorI Class Reference
Main Modules Class List Namespace List Online
ColorI Class Reference
#include <core/color.h>
Classes
struct Hsb
Public Member Functions
ColorI ()
ColorI (const ColorI &in_rCopy)
ColorI (const Hsb &color)
ColorI (const U8 in_r, const U8 in_g, const U8 in_b, const U8 in_a=U8(255))
ColorI (const ColorI &in_rCopy, const U8 in_a)
ColorI (const char *pStockColorName)
S32 convertFromHex (const String &hex) const
U16 get4444 () const
U16 get565 () const
U32 getABGRPack () const
U32 getARGBEndian () const
U32 getARGBPack () const
U32 getBGRPack () const
String getHex () const
Hsb getHSB () const
U32 getRGBAPack () const
U32 getRGBEndian () const
U32 getRGBPack () const
void HSLtoRGB_Subfunction (U32 &c, const F64 &temp1, const F64 &temp2, const F64 &temp3)
void interpolate (const ColorI &in_rC1, const ColorI &in_rC2, const F32 in_factor)
operator ColorF () const
bool operator!= (const ColorI &) const
ColorI operator* (const F32 in_mul) const
ColorI operator* (const S32 in_mul) const
ColorI & operator*= (const F32 in_mul)
ColorI & operator*= (const S32 in_mul)
ColorI operator+ (const ColorI &in_rAdd) const
ColorI & operator+= (const ColorI &in_rAdd)
ColorI operator/ (const S32 in_mul) const
ColorI & operator/= (const S32 in_mul)
bool operator== (const ColorI &) const
void set (const Hsb &color)
void set (const String &hex)
void set (const U8 in_r, const U8 in_g, const U8 in_b, const U8 in_a=U8(255))
void set (const ColorI &in_rCopy, const U8 in_a)
void set (const char *pStockColorName)
StringTableEntry StockColor (void)
ColorI toGamma ()
ColorI toLinear ()
Static Public Member Functions
static const ColorI & StockColor (const char *pStockColorName)
Public Attributes
U8 alpha
U8 blue
U8 green
U8 red
Static Public Attributes
static const ColorI BLACK
static const ColorI BLUE
static const ColorI GREEN
static const ColorI ONE
static const ColorI RED
static const ColorI WHITE
static const ColorI ZERO
Constructor & Destructor Documentation
ColorI::ColorI () inline
References ColorF::ColorF(), ColorF::getABGRPack(), ColorF::getARGBPack(), ColorF::getRGBAPack(), ColorF::interpolate(), ColorF::operator!=(), ColorF::operator*(), ColorF::operator*=(), ColorF::operator+(), ColorF::operator+=(), ColorF::operator/(), ColorF::operator/=(), ColorF::operator==(), ColorF::red, ColorF::StockColor(), ColorF::toGamma(), and ColorF::toLinear().
ColorI::ColorI (const ColorI & in_rCopy) inline
References ColorF::alpha, alpha, ColorF::blue, blue, ColorF::green, green, ColorF::red, and red.
ColorI::ColorI (const Hsb & color) inline
ColorI::ColorI (const U8 in_r, const U8 in_g, const U8 in_b, const U8 in_a = U8(255)) inline
ColorI::ColorI (const ColorI & in_rCopy, const U8 in_a) inline
ColorI::ColorI (const char * pStockColorName)
Member Function Documentation
S32 ColorI::convertFromHex (const String & hex) const inline
References Con::errorf(), and String::length().
U16 ColorI::get4444 () const inline
References ColorF::alpha, ColorF::blue, ColorF::green, and ColorF::red.
U16 ColorI::get565 () const inline
References ColorF::blue, ColorF::green, and ColorF::red.
U32 ColorI::getABGRPack () const inline
References ColorF::alpha, ColorF::blue, ColorF::green, and ColorF::red.
U32 ColorI::getARGBEndian () const inline
References ColorF::getABGRPack(), and ColorF::getARGBPack().
U32 ColorI::getARGBPack () const inline
References ColorF::alpha, ColorF::blue, ColorF::green, and ColorF::red.
U32 ColorI::getBGRPack () const inline
References ColorF::blue, ColorF::green, and ColorF::red.
String ColorI::getHex () const inline
References ColorF::blue, ColorF::green, and ColorF::red.
ColorI::Hsb ColorI::getHSB () const inline
References ColorF::blue, ColorI::Hsb::brightness, ColorF::green, ColorI::Hsb::hue, ColorF::red, and ColorI::Hsb::sat.
U32 ColorI::getRGBAPack () const inline
References ColorF::alpha, ColorF::blue, ColorF::green, and ColorF::red.
U32 ColorI::getRGBEndian () const inline
U32 ColorI::getRGBPack () const inline
References ColorF::blue, ColorF::green, and ColorF::red.
void ColorI::HSLtoRGB_Subfunction (U32 & c, const F64 & temp1, const F64 & temp2, const F64 & temp3) inline
void ColorI::interpolate (const ColorI & in_rC1, const ColorI & in_rC2, const F32 in_factor) inline
References ColorF::alpha, alpha, ColorF::blue, blue, ColorF::green, green, ColorF::red, and red.
ColorI::operator ColorF () const inline
References ColorF::alpha, ColorF::blue, ColorF::ColorF(), ColorF::green, and ColorF::red.
bool ColorI::operator!= (const ColorI & in_Cmp) const inline
References ColorF::alpha, alpha, ColorF::blue, blue, ColorF::green, green, ColorF::red, and red.
ColorI ColorI::operator* (const F32 in_mul) const inline
ColorI ColorI::operator* (const S32 in_mul) const inline
ColorI & ColorI::operator*= (const F32 in_mul) inline
References ColorF::alpha, ColorF::blue, ColorF::green, and ColorF::red.
ColorI & ColorI::operator*= (const S32 in_mul) inline
References ColorF::alpha, ColorF::blue, ColorF::green, and ColorF::red.
ColorI ColorI::operator+ (const ColorI & in_rAdd) const inline
References ColorF::alpha, alpha, ColorF::blue, blue, ColorF::green, green, ColorF::red, and red.
ColorI & ColorI::operator+= (const ColorI & in_rAdd) inline
References ColorF::alpha, alpha, ColorF::blue, blue, ColorF::green, green, ColorF::red, and red.
ColorI ColorI::operator/ (const S32 in_mul) const inline
ColorI & ColorI::operator/= (const S32 in_mul) inline
References ColorF::alpha, ColorF::blue, ColorF::green, and ColorF::red.
bool ColorI::operator== (const ColorI & in_Cmp) const inline
References ColorF::alpha, alpha, ColorF::blue, blue, ColorF::green, green, ColorF::red, and red.
void ColorI::set (const Hsb & color) inline
References ColorF::blue, ColorI::Hsb::brightness, ColorF::green, ColorI::Hsb::hue, ColorF::red, and ColorI::Hsb::sat.
Referenced by TamlCustomField::getFieldValue(), and WaterFogData::WaterFogData().
void ColorI::set (const String & hex) inline
References ColorF::blue, ColorF::green, ColorF::red, and String::substr().
void ColorI::set (const U8 in_r, const U8 in_g, const U8 in_b, const U8 in_a = U8(255)) inline
References ColorF::alpha, ColorF::blue, ColorF::green, and ColorF::red.
void ColorI::set (const ColorI & in_rCopy, const U8 in_a) inline
References ColorF::alpha, ColorF::blue, blue, ColorF::green, green, ColorF::red, and red.
void ColorI::set (const char * pStockColorName)
static const ColorI& ColorI::StockColor (const char * pStockColorName) static
StringTableEntry ColorI::StockColor (void)
ColorI ColorI::toGamma () inline
References ColorF::ColorF(), and ColorF::toGamma().
ColorI ColorI::toLinear () inline
References ColorF::ColorF(), and ColorF::toLinear().
Member Data Documentation
U8 ColorI::alpha
Referenced by ColorI(), _SourceReader::getColorIValue(), interpolate(), operator!=(), operator+(), operator+=(), and operator==().
const ColorI ColorI::BLACK static
Referenced by SceneSpace::_getDefaultEditorWireframeColor().
U8 ColorI::blue
Referenced by ColorI(), _SourceReader::getColorIValue(), interpolate(), operator!=(), operator+(), operator+=(), operator==(), and set().
const ColorI ColorI::BLUE static
U8 ColorI::green
Referenced by ColorI(), _SourceReader::getColorIValue(), interpolate(), operator!=(), operator+(), operator+=(), operator==(), and set().
const ColorI ColorI::GREEN static
const ColorI ColorI::ONE static
U8 ColorI::red
Referenced by ColorI(), _SourceReader::getColorIValue(), interpolate(), operator!=(), operator+(), operator+=(), operator==(), and set().
const ColorI ColorI::RED static
const ColorI ColorI::WHITE static
Referenced by ConvexShape::getSurfaces().
const ColorI ColorI::ZERO static
Copyright © GarageGames, LLC. All Rights Reserved.