UnmanagedVector< T > Class Template Reference
Main Modules Class List Namespace List Online
UnmanagedVector< T > Class Template Reference
An array that does not manage the memory it gets passed.
#include <core/util/tUnmanagedVector.h>
Public Types
typedef const T * const_iterator
typedef T * iterator
Public Member Functions
UnmanagedVector ()
UnmanagedVector (T *array, U32 count)
const T * address () const
T * address ()
iterator begin ()
const_iterator begin () const
void clear ()
bool empty () const
iterator end ()
const_iterator end () const
const T & first () const
T & first ()
const T & last () const
T & last ()
const T & operator[] (U32 index) const
T & operator[] (U32 index)
U32 size () const
Protected Attributes
T * mArray
U32 mCount
Detailed Description
template<typename T>
class UnmanagedVector< T >
An array that does not manage the memory it gets passed.
Conversely, the array cannot be enlarged.
Note
As the array does not manage the instances it uses, it will also not destruct them when it is itself destructed.
Member Typedef Documentation
template<typename T> typedef const T* UnmanagedVector< T >::const_iterator
template<typename T> typedef T* UnmanagedVector< T >::iterator
Constructor & Destructor Documentation
template<typename T> UnmanagedVector< T >::UnmanagedVector () inline
template<typename T> UnmanagedVector< T >::UnmanagedVector (T * array, U32 count) inline
Member Function Documentation
template<typename T> const T* UnmanagedVector< T >::address () const inline
Referenced by PolyhedronUnmanagedVectorData::getEdges(), PolyhedronUnmanagedVectorData::getPlanes(), and PolyhedronUnmanagedVectorData::getPoints().
template<typename T> T* UnmanagedVector< T >::address () inline
template<typename T> iterator UnmanagedVector< T >::begin () inline
template<typename T> const_iterator UnmanagedVector< T >::begin () const inline
template<typename T> void UnmanagedVector< T >::clear (void) inline
template<typename T> bool UnmanagedVector< T >::empty () const inline
Referenced by UnmanagedVector< Edge >::first(), and UnmanagedVector< Edge >::last().
template<typename T> iterator UnmanagedVector< T >::end () inline
template<typename T> const_iterator UnmanagedVector< T >::end () const inline
template<typename T> const T& UnmanagedVector< T >::first () const inline
template<typename T> T& UnmanagedVector< T >::first () inline
template<typename T> const T& UnmanagedVector< T >::last () const inline
template<typename T> T& UnmanagedVector< T >::last () inline
template<typename T> const T& UnmanagedVector< T >::operator[] (U32 index) const inline
template<typename T> T& UnmanagedVector< T >::operator[] (U32 index) inline
template<typename T> U32 UnmanagedVector< T >::size () const inline
Referenced by PolyhedronUnmanagedVectorData::getNumEdges(), PolyhedronUnmanagedVectorData::getNumPlanes(), PolyhedronUnmanagedVectorData::getNumPoints(), and UnmanagedVector< Edge >::operator[]().
Member Data Documentation
template<typename T> T* UnmanagedVector< T >::mArray protected
Referenced by UnmanagedVector< Edge >::address().
template<typename T> U32 UnmanagedVector< T >::mCount protected
Referenced by UnmanagedVector< Edge >::end(), and UnmanagedVector< Edge >::size().
Copyright © GarageGames, LLC. All Rights Reserved.