ThreadPool Class Reference
Main Modules Class List Namespace List Online
ThreadPool Class Reference
Asynchronous work manager.
#include <platform/threads/threadPool.h>
Classes
class Context
A ThreadPool context defines a logical context in which WorkItems are being executed.
struct GlobalThreadPool
class WorkItem
An action to execute on a worker thread from the pool.
Public Types
typedef ThreadSafeRef< WorkItem > WorkItemPtr
Public Member Functions
ThreadPool (const char *name, U32 numThreads=0)
Create a new thread pool with the given number of worker threads.
~ThreadPool ()
void flushWorkItems (S32 timeOut=-1)
For the global pool, it is very important to only ever call this function on the main thread and to let work items only ever come from the main thread.
F32 getQueueTimeBasedPriorityBoost () const
Return the priority increment applied to work items on each passing of the update interval.
U32 getQueueUpdateInterval () const
Return the interval in which item priorities are updated on the queue.
void queueWorkItem (WorkItem *item)
void setQueueTimeBasedPriorityBoost (F32 value)
Set the priority increment applied to work items on each update interval.
void setQueueUpdateInterval (U32 milliSeconds)
Set the update interval of the work item queue to the given value.
void shutdown ()
Manually shutdown threads outside of static destructors.
void waitForAllItems (S32 timeOut=-1)
If you're using a non-global thread pool to parallelise some work, you may want to block until all the parallel work is complete.
Static Public Member Functions
static bool & getForceAllMainThread ()
static U32 & getMainThreadThresholdTimeMS ()
static ThreadPool & GLOBAL ()
Return the global thread pool singleton.
static void processMainThreadWorkItems ()
Process work items waiting on the main thread's work queue.
static void queueWorkItemOnMainThread (WorkItem *item)
Add a work item to the main thread's work queue.
Protected Types
typedef ThreadSafePriorityQueueWithUpdate< WorkItemWrapper, F32 > QueueType
Protected Attributes
String mName
Name of this pool. Mainly for debugging. Used to name worker threads.
U32 mNumPendingItems
Number of work items that have not yet completed execution.
U32 mNumThreads
Number of worker threads spawned by the pool.
U32 mNumThreadsAwake
Number of worker threads in non-sleeping state.
U32 mNumThreadsReady
Number of worker threads guaranteed to be non-blocking.
Semaphore mSemaphore
Semaphore used to wake up threads, if necessary.
WorkerThread * mThreads
List of worker threads.
QueueType mWorkItemQueue
Threaded priority queue for concurrent access by worker threads.
Static Protected Attributes
static bool smForceAllMainThread
Force all work items to execute on main thread; turns this into a single-threaded system.
static QueueType smMainThreadQueue
Work queue for main thread; can be used to ping back work items to main thread that need processing that can only happen on main thread.
static U32 smMainThreadTimeMS
Detailed Description
Asynchronous work manager.
Thread pooling allows to submit work items for background execution. Each work item will be placed on a queue and, based on a total priority ordering, executed when it has the highest priority and a worker thread becomes available.
Note
The global pool maintains the invariant that only the main thread may submit items in order to be able to flush the item queue reliably from the main thread itself. If other threads were issuing items to the queue, the queue may never empty out and the main thread will deadlock.
Flushing is the simplest method to guarantee that no asynchronous operation is pending in a specific case (deletion of the target object being the most common case). However, when possible, avoid this situation and design your work items to operate independently, e.g. by having only a single point of access to data that may have disappeared in the meantime and putting a check around that single access so that the item will silently die when its target object has disappeared.
The cleanest safe solution to this is to create a separate concurrently reference-counted structure that holds all interfacing state and functionality shared between a work item and its issueing code. This way the host object can safely disappear with the interfacing structure automatically being released once the last concurrent work item has been processed or discarded.
Member Typedef Documentation
typedef ThreadSafePriorityQueueWithUpdate< WorkItemWrapper, F32 > ThreadPool::QueueType protected
typedef ThreadSafeRef< WorkItem > ThreadPool::WorkItemPtr
Constructor & Destructor Documentation
ThreadPool::ThreadPool (const char * name, U32 numThreads = 0)
Create a new thread pool with the given number of worker threads.
If numThreads is zero (the default), the number of threads created will be based on the number of CPU cores available.
Parameters
numThreads Number of threads to create or zero for default.
ThreadPool::~ThreadPool ()
Member Function Documentation
void ThreadPool::flushWorkItems (S32 timeOut = -1)
For the global pool, it is very important to only ever call this function on the main thread and to let work items only ever come from the main thread.
Otherwise this function has the potential of dead-locking as new work items may constantly be fed to the queue without it ever getting empty.
Parameters
timeOut Soft limit on the number of milliseconds to wait for the queue to flush out. -1 = infinite.
static bool& ThreadPool::getForceAllMainThread () inline static
References GLOBAL(), and smForceAllMainThread.
static U32& ThreadPool::getMainThreadThresholdTimeMS () inline static
References smMainThreadTimeMS.
F32 ThreadPool::getQueueTimeBasedPriorityBoost () const inline
Return the priority increment applied to work items on each passing of the update interval.
U32 ThreadPool::getQueueUpdateInterval () const inline
Return the interval in which item priorities are updated on the queue.
Returns
update interval in milliseconds.
ThreadPool & ThreadPool::GLOBAL () inline static
Return the global thread pool singleton.
References ManagedSingleton< GlobalThreadPool >::instance().
Referenced by AsyncPacketBufferedInputStream< SFXStreamRef, SFXStreamPacket >::_newReadItem(), and getForceAllMainThread().
static void ThreadPool::processMainThreadWorkItems () static
Process work items waiting on the main thread's work queue.
There is a soft limit imposed on the time this method is allowed to run so as to balance frame-to-frame load. However, work items, once their processing is initiated, will not be suspended and will run for as long as they take to complete, so make sure individual items perform as little work as necessary.
See also
ThreadPool::getMainThreadThesholdTimeMS
void ThreadPool::queueWorkItem (WorkItem * item)
Referenced by AsyncSingleBufferedInputStream< T, Stream, ReadItem >::_requestNext().
static void ThreadPool::queueWorkItemOnMainThread (WorkItem * item) static
Add a work item to the main thread's work queue.
The main thread's work queue will be processed each frame using a set timeout to limit the work being done. Nonetheless, work items will not be suspended in-midst of processing, so make sure that whatever work you issue to the main thread is light work or you may see short hangs in gameplay.
To reiterate this: any code executed through this interface directly adds to frame processing time on the main thread.
This method may (and is meant to) be called from threads other than the main thread.
void ThreadPool::setQueueTimeBasedPriorityBoost (F32 value) inline
Set the priority increment applied to work items on each update interval.
Parameters
value Priority increment. Set to zero to deactivate.
void ThreadPool::setQueueUpdateInterval (U32 milliSeconds) inline
Set the update interval of the work item queue to the given value.
Parameters
milliSeconds Time between updates in milliseconds.
void ThreadPool::shutdown ()
Manually shutdown threads outside of static destructors.
void ThreadPool::waitForAllItems (S32 timeOut = -1)
If you're using a non-global thread pool to parallelise some work, you may want to block until all the parallel work is complete.
As with flushWorkItems, this method may block indefinitely if new items keep getting added to the pool before old ones finish.
This method will not wait for items queued on the main thread using queueWorkItemOnMainThread!
Parameters
timeOut Soft limit on the number of milliseconds to wait for all items to complete. -1 = infinite.
Member Data Documentation
String ThreadPool::mName protected
Name of this pool. Mainly for debugging. Used to name worker threads.
U32 ThreadPool::mNumPendingItems protected
Number of work items that have not yet completed execution.
U32 ThreadPool::mNumThreads protected
Number of worker threads spawned by the pool.
U32 ThreadPool::mNumThreadsAwake protected
Number of worker threads in non-sleeping state.
U32 ThreadPool::mNumThreadsReady protected
Number of worker threads guaranteed to be non-blocking.
Semaphore ThreadPool::mSemaphore protected
Semaphore used to wake up threads, if necessary.
WorkerThread* ThreadPool::mThreads protected
List of worker threads.
QueueType ThreadPool::mWorkItemQueue protected
Threaded priority queue for concurrent access by worker threads.
bool ThreadPool::smForceAllMainThread static protected
Force all work items to execute on main thread; turns this into a single-threaded system.
Primarily useful to find whether malfunctions are caused by parallel execution or not.
Referenced by getForceAllMainThread().
QueueType ThreadPool::smMainThreadQueue static protected
Work queue for main thread; can be used to ping back work items to main thread that need processing that can only happen on main thread.
U32 ThreadPool::smMainThreadTimeMS static protected
Referenced by getMainThreadThresholdTimeMS().
Copyright © GarageGames, LLC. All Rights Reserved.