SFXResource Class Reference
Main Modules Class List Namespace List Online
SFXResource Class Reference
This is the base class for all sound file resources including streamed sound files.
#include <sfx/sfxResource.h>
Public Types
typedef void Parent
Public Member Functions
virtual ~SFXResource ()
The destructor.
U32 getDuration () const
Returns the total playback time milliseconds.
const String & getFileName ()
Return the path to the sound file.
const SFXFormat & getFormat () const
The format of the data in the resource.
SFXStream * openStream ()
Open a stream for reading the resource's sample data.
Static Public Member Functions
static bool exists (String filename)
A helper function which returns true if the sound resource exists.
static Resource< SFXResource > load (String filename)
This is a helper function used by SFXProfile for load a sound resource.
Protected Member Functions
SFXResource ()
The constructor is protected.
SFXResource (String fileName, SFXStream *stream)
Construct a resource instance for the given file.
Protected Attributes
U32 mDuration
The length of the sample in milliseconds.
String mFileName
Path to the sound file.
SFXFormat mFormat
The format of the sample data.
Detailed Description
This is the base class for all sound file resources including streamed sound files.
It acts much like an always in-core header to the actual sound data which is read through an SFXStream.
The first step occurs at ResourceManager::load() time at which only the header information, the format, size frequency, and looping flag, are loaded from the sound file. This provides just the nessasary information to simulate sound playback for sounds playing just out of the users hearing range.
The second step loads the actual sound data or begins filling the stream buffer. This is triggered by a call to openStream(). SFXProfile, for example, does this when mPreload is enabled.
Member Typedef Documentation
typedef void SFXResource::Parent
Constructor & Destructor Documentation
SFXResource::SFXResource () protected
The constructor is protected.
See also
SFXResource::load()
SFXResource::SFXResource (String fileName, SFXStream * stream) protected
Construct a resource instance for the given file.
Format and duration are read from the given stream.
virtual SFXResource::~SFXResource () inline virtual
The destructor.
References exists(), and load().
Member Function Documentation
static bool SFXResource::exists (String filename) static
A helper function which returns true if the sound resource exists.
Parameters
filename The sound file path with or without extension.
Referenced by ~SFXResource().
U32 SFXResource::getDuration () const inline
Returns the total playback time milliseconds.
References mDuration.
const String& SFXResource::getFileName () inline
Return the path to the sound file.
References mFileName.
const SFXFormat& SFXResource::getFormat () const inline
The format of the data in the resource.
References mFormat, and openStream().
static Resource< SFXResource > SFXResource::load (String filename) static
This is a helper function used by SFXProfile for load a sound resource.
It takes care of trying different types for extension-less filenames.
Parameters
filename The sound file path with or without extension.
Referenced by ~SFXResource().
SFXStream* SFXResource::openStream ()
Open a stream for reading the resource's sample data.
Referenced by getFormat().
Member Data Documentation
U32 SFXResource::mDuration protected
The length of the sample in milliseconds.
Referenced by getDuration().
String SFXResource::mFileName protected
Path to the sound file.
Referenced by getFileName().
SFXFormat SFXResource::mFormat protected
The format of the sample data.
Referenced by getFormat().
Copyright © GarageGames, LLC. All Rights Reserved.