BtCollision Class Reference
Main Modules Class List Namespace List Online
BtCollision Class Reference
#include <T3D/physics/bullet/btCollision.h>
Public Member Functions
BtCollision ()
virtual ~BtCollision ()
virtual void addBox (const Point3F &halfWidth, const MatrixF &localXfm)
Add a box to the collision shape.
virtual void addCapsule (F32 radius, F32 height, const MatrixF &localXfm)
Add a Y axis capsule to the collision shape.
virtual bool addConvex (const Point3F *points, U32 count, const MatrixF &localXfm)
Add a point cloud convex hull to the collision shape.
virtual bool addHeightfield (const U16 *heights, const bool *holes, U32 blockSize, F32 metersPerSample, const MatrixF &localXfm)
Add a heightfield to the collision shape.
virtual void addPlane (const PlaneF &plane)
Add an infinite plane to the collision shape.
virtual void addSphere (F32 radius, const MatrixF &localXfm)
Add a sphere to the collision shape.
virtual bool addTriangleMesh (const Point3F *vert, U32 vertCount, const U32 *index, U32 triCount, const MatrixF &localXfm)
Add a triangle mesh to the collision shape.
const MatrixF & getLocalTransform () const
btCollisionShape * getShape ()
Return the Bullet collision shape.
Public Member Functions inherited from StrongRefBase
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Protected Member Functions
void _addShape (btCollisionShape *shape, const MatrixF &localXfm)
Helper for adding shapes.
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Protected Attributes
btCompoundShape * mCompound
The compound if we have more than one collision shape.
MatrixF mLocalXfm
The local transform for the collision shape or identity if this is a compound.
Vector< btTriangleMesh * > mMeshInterfaces
If we have any triangle mesh collision shapes then we need to store the mesh data.
Vector< btCollisionShape * > mShapes
The concrete collision shapes.
Protected Attributes inherited from StrongRefBase
U32 mRefCount
reference counter for StrongRefPtr objects
Constructor & Destructor Documentation
BtCollision::BtCollision ()
virtual BtCollision::~BtCollision () virtual
Member Function Documentation
void BtCollision::_addShape (btCollisionShape * shape, const MatrixF & localXfm) protected
Helper for adding shapes.
virtual void BtCollision::addBox (const Point3F & halfWidth, const MatrixF & localXfm) virtual
Add a box to the collision shape.
Implements PhysicsCollision.
Referenced by getLocalTransform().
virtual void BtCollision::addCapsule (F32 radius, F32 height, const MatrixF & localXfm) virtual
Add a Y axis capsule to the collision shape.
Implements PhysicsCollision.
Referenced by getLocalTransform().
virtual bool BtCollision::addConvex (const Point3F * points, U32 count, const MatrixF & localXfm) virtual
Add a point cloud convex hull to the collision shape.
Implements PhysicsCollision.
Referenced by getLocalTransform().
virtual bool BtCollision::addHeightfield (const U16 * heights, const bool * holes, U32 blockSize, F32 metersPerSample, const MatrixF & localXfm) virtual
Add a heightfield to the collision shape.
Implements PhysicsCollision.
Referenced by getLocalTransform().
virtual void BtCollision::addPlane (const PlaneF & plane) virtual
Add an infinite plane to the collision shape.
This shape is assumed to be static in some physics providers and will at times be faked with a large box.
Implements PhysicsCollision.
Referenced by getLocalTransform().
virtual void BtCollision::addSphere (F32 radius, const MatrixF & localXfm) virtual
Add a sphere to the collision shape.
Implements PhysicsCollision.
Referenced by getLocalTransform().
virtual bool BtCollision::addTriangleMesh (const Point3F * vert, U32 vertCount, const U32 * index, U32 triCount, const MatrixF & localXfm) virtual
Add a triangle mesh to the collision shape.
Implements PhysicsCollision.
Referenced by getLocalTransform().
const MatrixF& BtCollision::getLocalTransform () const inline
References addBox(), addCapsule(), addConvex(), addHeightfield(), addPlane(), addSphere(), addTriangleMesh(), and mLocalXfm.
btCollisionShape* BtCollision::getShape ()
Return the Bullet collision shape.
Member Data Documentation
btCompoundShape* BtCollision::mCompound protected
The compound if we have more than one collision shape.
MatrixF BtCollision::mLocalXfm protected
The local transform for the collision shape or identity if this is a compound.
Referenced by getLocalTransform().
Vector<btTriangleMesh*> BtCollision::mMeshInterfaces protected
If we have any triangle mesh collision shapes then we need to store the mesh data.
Vector<btCollisionShape*> BtCollision::mShapes protected
The concrete collision shapes.
Copyright © GarageGames, LLC. All Rights Reserved.