HashMap< Key, Value, Sequence > Class Template Reference
Main Modules Class List Namespace List Online
HashMap< Key, Value, Sequence > Class Template Reference
A HashMap template class.
#include <core/util/tDictionary.h>
Public Types
typedef Parent::ConstIterator const_iterator
typedef const Pair & ConstReference
typedef S32 DifferenceType
typedef Parent::Iterator iterator
typedef Parent::Pair Pair
typedef Pair & Reference
typedef U32 SizeType
typedef Pair ValueType
Public Member Functions
HashMap ()
HashMap (const HashMap &p)
~HashMap ()
iterator begin ()
iterator to first element
const_iterator begin () const
iterator to first element
void clear ()
Empty the HashMap.
bool contains (const Key &a)
iterator end ()
IIterator to last element + 1.
const_iterator end () const
iterator to last element + 1
void erase (iterator)
Erase the given entry.
void erase (const Key &key)
Erase the key from the map.
iterator find (const Key &)
Find entry for the given key.
const_iterator find (const Key &) const
Find entry for the given key.
iterator insert (const Key &key, const Value &)
Insert the key value pair but don't allow duplicates.
bool isEmpty () const
Returns true if the map is empty.
Value & operator[] (const Key &)
Index using the given key. If the key is not currently in the map it is added.
U32 size () const
Return the number of elements.
Detailed Description
template<typename Key, typename Value, class Sequence = HashTable<Key, Value>>
class HashMap< Key, Value, Sequence >
A HashMap template class.
The map class maps between a key and an associated value. Keys are unique. The hash table class is used as the default implementation so the the key must be hashable, see util/hash.h for details.
Member Typedef Documentation
template<typename Key, typename Value, class Sequence = HashTable<Key, Value>> typedef Parent::ConstIterator HashMap< Key, Value, Sequence >::const_iterator
template<typename Key, typename Value, class Sequence = HashTable<Key, Value>> typedef const Pair& HashMap< Key, Value, Sequence >::ConstReference
template<typename Key, typename Value, class Sequence = HashTable<Key, Value>> typedef S32 HashMap< Key, Value, Sequence >::DifferenceType
template<typename Key, typename Value, class Sequence = HashTable<Key, Value>> typedef Parent::Iterator HashMap< Key, Value, Sequence >::iterator
template<typename Key, typename Value, class Sequence = HashTable<Key, Value>> typedef Parent::Pair HashMap< Key, Value, Sequence >::Pair
template<typename Key, typename Value, class Sequence = HashTable<Key, Value>> typedef Pair& HashMap< Key, Value, Sequence >::Reference
template<typename Key, typename Value, class Sequence = HashTable<Key, Value>> typedef U32 HashMap< Key, Value, Sequence >::SizeType
template<typename Key, typename Value, class Sequence = HashTable<Key, Value>> typedef Pair HashMap< Key, Value, Sequence >::ValueType
Constructor & Destructor Documentation
template<typename Key, typename Value, class Sequence = HashTable<Key, Value>> HashMap< Key, Value, Sequence >::HashMap () inline
template<typename Key, typename Value, class Sequence = HashTable<Key, Value>> HashMap< Key, Value, Sequence >::~HashMap () inline
template<typename Key , typename Value , class Sequence > HashMap< Key, Value, Sequence >::HashMap (const HashMap< Key, Value, Sequence > & p)
Member Function Documentation
template<typename Key , typename Value , class Sequence > HashMap< Key, Value, Sequence >::iterator HashMap< Key, Value, Sequence >::begin () inline
iterator to first element
template<typename Key , typename Value , class Sequence > HashMap< Key, Value, Sequence >::const_iterator HashMap< Key, Value, Sequence >::begin () const inline
iterator to first element
template<typename Key , typename Value , class Sequence > void HashMap< Key, Value, Sequence >::clear (void) inline
Empty the HashMap.
Referenced by TamlAssetReferencedVisitor::clear().
template<typename Key, typename Value, class Sequence = HashTable<Key, Value>> bool HashMap< Key, Value, Sequence >::contains (const Key & a) inline
Referenced by TamlAssetReferencedVisitor::visit().
template<typename Key , typename Value , class Sequence > HashMap< Key, Value, Sequence >::iterator HashMap< Key, Value, Sequence >::end () inline
IIterator to last element + 1.
template<typename Key , typename Value , class Sequence > HashMap< Key, Value, Sequence >::const_iterator HashMap< Key, Value, Sequence >::end () const inline
iterator to last element + 1
template<typename Key , typename Value , class Sequence > void HashMap< Key, Value, Sequence >::erase (iterator node)
Erase the given entry.
template<typename Key, typename Value , class Sequence > void HashMap< Key, Value, Sequence >::erase (const Key & key)
Erase the key from the map.
template<typename Key, typename Value , class Sequence > HashMap< Key, Value, Sequence >::iterator HashMap< Key, Value, Sequence >::find (const Key & key)
Find entry for the given key.
template<typename Key, typename Value, class Sequence = HashTable<Key, Value>> const_iterator HashMap< Key, Value, Sequence >::find (const Key &) const
Find entry for the given key.
template<typename Key, typename Value, class Sequence > HashMap< Key, Value, Sequence >::iterator HashMap< Key, Value, Sequence >::insert (const Key & key, const Value & x)
Insert the key value pair but don't allow duplicates.
The map class does not allow duplicates keys. If the key already exists in the map the function will fail and return end().
Referenced by TamlAssetReferencedVisitor::visit().
template<typename Key , typename Value , class Sequence > bool HashMap< Key, Value, Sequence >::isEmpty () const inline
Returns true if the map is empty.
template<typename Key, typename Value , class Sequence > Value & HashMap< Key, Value, Sequence >::operator[] (const Key & key) inline
Index using the given key. If the key is not currently in the map it is added.
template<typename Key , typename Value , class Sequence > U32 HashMap< Key, Value, Sequence >::size () const inline
Return the number of elements.
Referenced by AssetManager::getDeclaredAssetCount(), and AssetTagsManifest::getTagCount().
Copyright © GarageGames, LLC. All Rights Reserved.