Torque::Time Class Reference
Main Modules Class List Namespace List Online
Torque::Time Class Reference
64 bit time representation with ten microsecond resolution.
#include <core/util/timeClass.h>
Classes
struct DateTime
Public Member Functions
Time ()
Time (S64 time)
Time (S32 year, S32 month, S32 day, S32 hour, S32 minute, S32 second, S32 microsecond)
Time (const DateTime &dateTime)
void get (S32 *year, S32 *month, S32 *day, S32 *hour, S32 *minute, S32 *second, S32 *microsecond) const
S64 getInternalRepresentation () const
S64 getMicroseconds () const
S64 getMilliseconds () const
S64 getSeconds () const
operator Tester * () const
bool operator! () const
bool operator!= (const Time &time) const
template<typename T >
Time operator* (T scaler) const
Time operator+ () const
Time operator+ (const Time &time) const
const Time & operator+= (const Time time)
Time operator- () const
Time operator- (const Time &time) const
const Time & operator-= (const Time time)
S64 operator/ (const Time &time) const
template<typename T >
Time operator/ (T scaler) const
bool operator< (const Time &time) const
bool operator<= (const Time &time) const
bool operator== (const Time &time) const
bool operator> (const Time &time) const
bool operator>= (const Time &time) const
bool set (S32 year, S32 month, S32 day, S32 hour, S32 minute, S32 second, S32 microsecond)
Static Public Member Functions
static void getCurrentDateTime (DateTime &dateTime)
static Time getCurrentTime ()
Static Public Attributes
static const S64 OneDay = TORQUE_CONSTANT_S64(8640000000)
static const S64 OneHour = TORQUE_CONSTANT_S64(360000000)
static const S64 OneMillisecond = TORQUE_CONSTANT_S64(100)
static const S64 OneMinute = TORQUE_CONSTANT_S64(6000000)
static const S64 OneSecond = TORQUE_CONSTANT_S64(100000)
Friends
template<typename T >
Time operator* (T scaler, Time t)
Detailed Description
64 bit time representation with ten microsecond resolution.
Constructor & Destructor Documentation
Torque::Time::Time () inline
Referenced by operator*(), operator+(), operator-(), operator/(), Torque::read(), Torque::UnixTimeToTime(), and Torque::Win32FileTimeToTime().
Torque::Time::Time (S64 time) inline explicit
Torque::Time::Time (S32 year, S32 month, S32 day, S32 hour, S32 minute, S32 second, S32 microsecond) inline
References Torque::Time::DateTime::day, Torque::Time::DateTime::hour, Torque::Time::DateTime::microsecond, Torque::Time::DateTime::minute, Torque::Time::DateTime::month, Torque::Time::DateTime::second, and Torque::Time::DateTime::year.
Torque::Time::Time (const DateTime & dateTime) inline
References Torque::Time::DateTime::day, Torque::Time::DateTime::hour, Torque::Time::DateTime::microsecond, Torque::Time::DateTime::minute, Torque::Time::DateTime::month, Torque::Time::DateTime::second, and Torque::Time::DateTime::year.
Member Function Documentation
void Torque::Time::get (S32 * year, S32 * month, S32 * day, S32 * hour, S32 * minute, S32 * second, S32 * microsecond) const
static void Torque::Time::getCurrentDateTime (DateTime & dateTime) static
static Time Torque::Time::getCurrentTime () static
S64 Torque::Time::getInternalRepresentation () const inline
Referenced by operator Tester *(), and Torque::write().
S64 Torque::Time::getMicroseconds () const inline
Referenced by operator Tester *().
S64 Torque::Time::getMilliseconds () const inline
References Torque::TimeConstant::OneMillisecond().
Referenced by operator Tester *().
S64 Torque::Time::getSeconds () const inline
References Torque::TimeConstant::OneSecond().
Referenced by operator Tester *().
Torque::Time::operator Tester * () const inline
References getInternalRepresentation(), getMicroseconds(), getMilliseconds(), getSeconds(), and operator!().
bool Torque::Time::operator! () const inline
Referenced by operator Tester *().
bool Torque::Time::operator!= (const Time & time) const inline
template<typename T > Time Torque::Time::operator* (T scaler) const inline
References Time().
Time Torque::Time::operator+ () const inline
References Time().
Time Torque::Time::operator+ (const Time & time) const inline
References Time().
const Time & Torque::Time::operator+= (const Time time) inline
Time Torque::Time::operator- () const inline
References Time().
Time Torque::Time::operator- (const Time & time) const inline
References Time().
const Time & Torque::Time::operator-= (const Time time) inline
S64 Torque::Time::operator/ (const Time & time) const inline
template<typename T > Time Torque::Time::operator/ (T scaler) const inline
References Time().
bool Torque::Time::operator< (const Time & time) const inline
bool Torque::Time::operator<= (const Time & time) const inline
bool Torque::Time::operator== (const Time & time) const inline
bool Torque::Time::operator> (const Time & time) const inline
bool Torque::Time::operator>= (const Time & time) const inline
bool Torque::Time::set (S32 year, S32 month, S32 day, S32 hour, S32 minute, S32 second, S32 microsecond)
Friends And Related Function Documentation
template<typename T > Time operator* (T scaler, Time t) friend
Member Data Documentation
const S64 Torque::Time::OneDay = TORQUE_CONSTANT_S64(8640000000) static
const S64 Torque::Time::OneHour = TORQUE_CONSTANT_S64(360000000) static
const S64 Torque::Time::OneMillisecond = TORQUE_CONSTANT_S64(100) static
const S64 Torque::Time::OneMinute = TORQUE_CONSTANT_S64(6000000) static
const S64 Torque::Time::OneSecond = TORQUE_CONSTANT_S64(100000) static
Copyright © GarageGames, LLC. All Rights Reserved.