SFXSoundscapeManager Class Reference
Main Modules Class List Namespace List Online
SFXSoundscapeManager Class Reference
The soundscape manager produces a dynamic mix between multiple active soundscapes.
#include <sfx/sfxSoundscape.h>
Public Types
typedef void Parent
Public Member Functions
SFXSoundscapeManager ()
~SFXSoundscapeManager ()
SFXSoundscape * getGlobalSoundscape () const
Return the topmost soundscape.
U32 getNumTotalSoundscapes () const
Return the total number of soundscape instances currently on the stack.
SFXSoundscape * insertSoundscape (U32 index, SFXAmbience *ambience)
Insert a new soundscape instance associated with the given ambient space at the given stack index.
void removeSoundscape (SFXSoundscape *soundscape)
Remove the given soundscape from the stack.
void update ()
Update the current soundscape mix.
Protected Member Functions
S32 _findOnStack (SFXAmbience *ambience, const Vector< SFXSoundscape * > &stack)
Found the topmost instance on the given stack associated with the given ambient space.
S32 _findTopmostReverbOnStack (const Vector< SFXSoundscape * > &stack)
Find the topmost soundscape on the given stack that has a reverb environment defined on its ambient space.
void _notifyAmbienceChanged (SFXAmbience *ambience)
Method hooked up to the SFXAmbience change signal to automatically make soundscapes using the given ambience as dirty and trigger a recomputation of their properties.
Protected Attributes
FreeListChunker< SFXSoundscape > mChunker
Memory manager of soundscape instances.
S32 mCurrentReverbIndex
Index into mStack for the soundscape that defines the current reverb settings.
SFXAmbience * mDefaultGlobalAmbience
Default global SFXAmbience. Not a registered object.
Vector< SFXSoundscape * > mFadeStack
Stack of soundscape that are currently being faded out.
Vector< SFXSoundscape * > mStack
Linear stack of soundscapes.
Detailed Description
The soundscape manager produces a dynamic mix between multiple active soundscapes.
Note
The more layered soundscapes there are, the costlier ambient sound updates will get.
Member Typedef Documentation
typedef void SFXSoundscapeManager::Parent
Constructor & Destructor Documentation
SFXSoundscapeManager::SFXSoundscapeManager ()
SFXSoundscapeManager::~SFXSoundscapeManager ()
Member Function Documentation
S32 SFXSoundscapeManager::_findOnStack (SFXAmbience * ambience, const Vector< SFXSoundscape * > & stack) protected
Found the topmost instance on the given stack associated with the given ambient space.
S32 SFXSoundscapeManager::_findTopmostReverbOnStack (const Vector< SFXSoundscape * > & stack) protected
Find the topmost soundscape on the given stack that has a reverb environment defined on its ambient space.
void SFXSoundscapeManager::_notifyAmbienceChanged (SFXAmbience * ambience) protected
Method hooked up to the SFXAmbience change signal to automatically make soundscapes using the given ambience as dirty and trigger a recomputation of their properties.
SFXSoundscape* SFXSoundscapeManager::getGlobalSoundscape () const inline
Return the topmost soundscape.
This soundscape is always defined and cannot be removed.
U32 SFXSoundscapeManager::getNumTotalSoundscapes () const inline
Return the total number of soundscape instances currently on the stack.
Always >=1.
References Vector< T >::size().
SFXSoundscape* SFXSoundscapeManager::insertSoundscape (U32 index, SFXAmbience * ambience)
Insert a new soundscape instance associated with the given ambient space at the given stack index.
Referenced by SFXWorld< NUM_DIMENSIONS, Object >::update().
void SFXSoundscapeManager::removeSoundscape (SFXSoundscape * soundscape)
Remove the given soundscape from the stack.
Referenced by SFXWorld< NUM_DIMENSIONS, Object >::update().
void SFXSoundscapeManager::update ()
Update the current soundscape mix.
Member Data Documentation
FreeListChunker< SFXSoundscape > SFXSoundscapeManager::mChunker protected
Memory manager of soundscape instances.
S32 SFXSoundscapeManager::mCurrentReverbIndex protected
Index into mStack for the soundscape that defines the current reverb settings.
-1 if no current ambience has reverb settings.
SFXAmbience* SFXSoundscapeManager::mDefaultGlobalAmbience protected
Default global SFXAmbience. Not a registered object.
Vector< SFXSoundscape* > SFXSoundscapeManager::mFadeStack protected
Stack of soundscape that are currently being faded out.
These are kept around so that when their ambient spaces are activated again, they can be brought back with their fades simply being reversed.
All soundscapes on this stack are unique.
Vector< SFXSoundscape* > SFXSoundscapeManager::mStack protected
Linear stack of soundscapes.
Evaluated bottom to top. Scapes being faded out are always last on the stack.
Copyright © GarageGames, LLC. All Rights Reserved.