LeapMotionDevice::MotionListener Class Reference
Main Modules Class List Namespace List Online
LeapMotionDevice::MotionListener Class Reference
#include <platform/input/leapMotion/leapMotionDevice.h>
Public Member Functions
MotionListener ()
virtual ~MotionListener ()
virtual void onConnect (const Leap::Controller &controller)
virtual void onDisconnect (const Leap::Controller &controller)
Constructor & Destructor Documentation
LeapMotionDevice::MotionListener::MotionListener () inline
virtual LeapMotionDevice::MotionListener::~MotionListener () inline virtual
References onConnect(), and onDisconnect().
Member Function Documentation
virtual void LeapMotionDevice::MotionListener::onConnect (const Leap::Controller & controller) virtual
Referenced by ~MotionListener().
virtual void LeapMotionDevice::MotionListener::onDisconnect (const Leap::Controller & controller) virtual
Referenced by ~MotionListener().
Copyright © GarageGames, LLC. All Rights Reserved.