CodeBlock Class Reference
Main Modules Class List Namespace List Online
CodeBlock Class Reference
Core TorqueScript code management class.
#include <console/codeBlock.h>
Public Member Functions
CodeBlock ()
~CodeBlock ()
void addToCodeList ()
void calcBreakList ()
void clearAllBreaks ()
void clearBreakpoint (U32 lineNumber)
bool compile (const char *dsoName, StringTableEntry fileName, const char *script, bool overrideNoDso=false)
ConsoleValueRef compileExec (StringTableEntry fileName, const char *script, bool noCalls, S32 setFrame=-1)
Compiles and executes a block of script storing the compiled code in this CodeBlock.
void decRefCount ()
void dumpInstructions (U32 startIp=0, bool upToReturn=false)
ConsoleValueRef exec (U32 offset, const char *fnName, Namespace *ns, U32 argc, ConsoleValueRef *argv, bool noCalls, StringTableEntry packageName, S32 setFrame=-1)
Executes the existing code in the CodeBlock.
void findBreakLine (U32 ip, U32 &line, U32 &instruction)
U32 findFirstBreakLine (U32 lineNumber)
Returns the first breakable line or 0 if none was found.
const char * getFileLine (U32 ip)
String getFunctionArgs (U32 offset)
void incRefCount ()
bool read (StringTableEntry fileName, Stream &st)
void removeFromCodeList ()
void setAllBreaks ()
bool setBreakpoint (U32 lineNumber)
Set a OP_BREAK instruction on a line.
Static Public Member Functions
static CodeBlock * find (StringTableEntry)
static CodeBlock * getCodeBlockList ()
static CodeBlock * getCurrentBlock ()
static StringTableEntry getCurrentCodeBlockFullPath ()
static StringTableEntry getCurrentCodeBlockModName ()
static StringTableEntry getCurrentCodeBlockName ()
Public Attributes
U32 * breakList
U32 breakListSize
U32 * code
U32 codeSize
StringTableEntry fullPath
F64 * functionFloats
char * functionStrings
U32 functionStringsMaxLen
F64 * globalFloats
char * globalStrings
U32 globalStringsMaxLen
U32 lineBreakPairCount
U32 * lineBreakPairs
StringTableEntry modPath
StringTableEntry name
CodeBlock * nextFile
U32 refCount
Static Public Attributes
static Compiler::ConsoleParser * smCurrentParser
static bool smInFunction
Detailed Description
Core TorqueScript code management class.
This class represents a block of code, usually mapped directly to a file.
Constructor & Destructor Documentation
CodeBlock::CodeBlock ()
Referenced by getCodeBlockList().
CodeBlock::~CodeBlock ()
Referenced by getCodeBlockList().
Member Function Documentation
void CodeBlock::addToCodeList ()
void CodeBlock::calcBreakList ()
void CodeBlock::clearAllBreaks ()
void CodeBlock::clearBreakpoint (U32 lineNumber)
bool CodeBlock::compile (const char * dsoName, StringTableEntry fileName, const char * script, bool overrideNoDso = false)
ConsoleValueRef CodeBlock::compileExec (StringTableEntry fileName, const char * script, bool noCalls, S32 setFrame = -1)
Compiles and executes a block of script storing the compiled code in this CodeBlock.
If there is no filename breakpoints will not be generated and the CodeBlock will not be added to the linked list of loaded CodeBlocks. Note that if the script contains no executable statements the CodeBlock will delete itself on return an empty string. The return string is any result of the code executed, if any, or an empty string.
Parameters
fileName The file name, including path and extension, for the block of code or an empty string.
script The script code to compile and execute.
noCalls Skips calling functions from the script.
setFrame A zero based index of the stack frame to execute the code with, zero being the top of the stack. If the the index is -1 a new frame is created. If the index is out of range the top stack frame is used.
void CodeBlock::decRefCount ()
void CodeBlock::dumpInstructions (U32 startIp = 0, bool upToReturn = false)
ConsoleValueRef CodeBlock::exec (U32 offset, const char * fnName, Namespace * ns, U32 argc, ConsoleValueRef * argv, bool noCalls, StringTableEntry packageName, S32 setFrame = -1)
Executes the existing code in the CodeBlock.
The return string is any result of the code executed, if any, or an empty string.
Parameters
offset The instruction offset to start executing from.
fnName The name of the function to execute or null.
ns The namespace of the function to execute or null.
argc The number of parameters passed to the function or zero to execute code outside of a function.
argv The function parameter list.
noCalls Skips calling functions from the script.
setFrame A zero based index of the stack frame to execute the code with, zero being the top of the stack. If the the index is -1 a new frame is created. If the index is out of range the top stack frame is used.
packageName The code package name or null.
static CodeBlock* CodeBlock::find (StringTableEntry) static
Referenced by getCodeBlockList().
void CodeBlock::findBreakLine (U32 ip, U32 & line, U32 & instruction)
U32 CodeBlock::findFirstBreakLine (U32 lineNumber)
Returns the first breakable line or 0 if none was found.
Parameters
lineNumber The one based line number.
static CodeBlock* CodeBlock::getCodeBlockList () inline static
References CodeBlock(), find(), getCurrentCodeBlockFullPath(), getCurrentCodeBlockModName(), getCurrentCodeBlockName(), and ~CodeBlock().
static CodeBlock* CodeBlock::getCurrentBlock () inline static
static StringTableEntry CodeBlock::getCurrentCodeBlockFullPath () static
Referenced by getCodeBlockList().
static StringTableEntry CodeBlock::getCurrentCodeBlockModName () static
Referenced by getCodeBlockList().
static StringTableEntry CodeBlock::getCurrentCodeBlockName () static
Referenced by getCodeBlockList().
const char* CodeBlock::getFileLine (U32 ip)
String CodeBlock::getFunctionArgs (U32 offset)
void CodeBlock::incRefCount ()
bool CodeBlock::read (StringTableEntry fileName, Stream & st)
void CodeBlock::removeFromCodeList ()
void CodeBlock::setAllBreaks ()
bool CodeBlock::setBreakpoint (U32 lineNumber)
Set a OP_BREAK instruction on a line.
If a break is not possible on that line it returns false.
Parameters
lineNumber The one based line number.
Member Data Documentation
U32* CodeBlock::breakList
U32 CodeBlock::breakListSize
U32* CodeBlock::code
U32 CodeBlock::codeSize
StringTableEntry CodeBlock::fullPath
F64* CodeBlock::functionFloats
char* CodeBlock::functionStrings
U32 CodeBlock::functionStringsMaxLen
F64* CodeBlock::globalFloats
char* CodeBlock::globalStrings
U32 CodeBlock::globalStringsMaxLen
U32 CodeBlock::lineBreakPairCount
U32* CodeBlock::lineBreakPairs
StringTableEntry CodeBlock::modPath
StringTableEntry CodeBlock::name
CodeBlock* CodeBlock::nextFile
U32 CodeBlock::refCount
Compiler::ConsoleParser* CodeBlock::smCurrentParser static
bool CodeBlock::smInFunction static
Copyright © GarageGames, LLC. All Rights Reserved.