SFXFMODVoice Class Reference
Main Modules Class List Namespace List Online
SFXFMODVoice Class Reference
#include <sfx/fmod/sfxFMODVoice.h>
Public Member Functions
virtual ~SFXFMODVoice ()
bool isVirtual () const
Returns true if the voice is virtualized on the device.
void play (bool looping)
Starts playback from the current position.
void setCone (F32 innerAngle, F32 outerAngle, F32 outerVolume)
Set sound cone of a 3D sound.
void setMinMaxDistance (F32 min, F32 max)
SFXVoice.
void setPitch (F32 pitch)
Sets the pitch scale.
void setPriority (F32 priority)
Set the priority of this voice.
void setReverb (const SFXSoundReverbProperties &reverb)
Set the reverb properties for playback of this sound.
void setTransform (const MatrixF &transform)
Sets the position and orientation for a 3d voice.
void setVelocity (const VectorF &velocity)
Sets the velocity for a 3d voice.
void setVolume (F32 volume)
Sets the volume.
Public Member Functions inherited from SFXVoice
virtual ~SFXVoice ()
The destructor.
const SFXFormat & getFormat () const
virtual U32 getPosition () const
Return the current playback position (in number of samples).
virtual SFXStatus getStatus () const
virtual void pause ()
Pauses playback.
virtual void setPosition (U32 sample)
Sets the playback position to the given sample count.
virtual void setRolloffFactor (F32 factor)
Set the distance attenuation rolloff factor. Support by device optional.
virtual void stop ()
Stops playback and moves the position to the start.
Public Member Functions inherited from StrongRefBase
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Static Public Member Functions
static SFXFMODVoice * create (SFXFMODDevice *device, SFXFMODBuffer *buffer)
Protected Types
enum ESettings {
SET_MinMaxDistance = BIT(0),
SET_Velocity = BIT(1),
SET_Transform = BIT(2),
SET_Volume = BIT(3),
SET_Pitch = BIT(4),
SET_Cone = BIT(5),
SET_Priority = BIT(6),
SET_Reverb = BIT(7)
}
Protected Member Functions
SFXFMODVoice (SFXFMODDevice *device, SFXFMODBuffer *buffer)
bool _assignChannel ()
SFXFMODBuffer * _getBuffer () const
virtual void _pause ()
Pause playback on the device.
virtual void _play ()
Start playback on the device.
virtual void _seek (U32 sample)
Set the playback cursor on the device.
virtual SFXStatus _status () const
Return the current playback status (playing, paused, or stopped).
virtual void _stop ()
Stop playback on the device.
virtual U32 _tell () const
Get the playback cursor on the device.
Protected Member Functions inherited from SFXVoice
SFXVoice (SFXBuffer *buffer)
void _attachToBuffer ()
virtual void _onBufferStatusChange (SFXBuffer *buffer, SFXBuffer::Status newStatus)
Hooked up to SFXBuffer::mOnStatusChange of mBuffer.
void _resetStream (U32 sampleStartPos, bool triggerUpdate=true)
Reset streaming of the voice by cloning the current streaming source and letting the resulting stream start from sampleStartPos.
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Protected Attributes
FMOD_CHANNEL * mChannel
F32 mConeInnerAngle
F32 mConeOuterAngle
F32 mConeOuterVolume
SFXFMODDevice * mDevice
FMOD_VECTOR mDirection
F32 mFrequency
F32 mMaxDistance
F32 mMinDistance
FMOD_MODE mMode
FMOD_VECTOR mPosition
F32 mPriority
FMOD_REVERB_CHANNELPROPERTIES mReverb
BitSet32 mSetFlags
FMOD_VECTOR mVelocity
F32 mVolume
Protected Attributes inherited from SFXVoice
WeakRefPtr< SFXBuffer > mBuffer
Sound data played back by the voice.
U32 mOffset
For streaming voices, this keeps track of play start offset after seeking.
volatile SFXStatus mStatus
Current playback status.
Protected Attributes inherited from StrongRefBase
U32 mRefCount
reference counter for StrongRefPtr objects
Additional Inherited Members
Public Types inherited from SFXVoice
typedef void Parent
Public Types inherited from IPositionable< U32 >
typedef void Parent
typedef U32 PositionType
The type used to indicate positions.
Static Public Attributes inherited from SFXVoice
static Signal< void(SFXVoice *) > smVoiceCreatedSignal
static Signal< void(SFXVoice *) > smVoiceDestroyedSignal
Member Enumeration Documentation
enum SFXFMODVoice::ESettings protected
Enumerator
SET_MinMaxDistance
SET_Velocity
SET_Transform
SET_Volume
SET_Pitch
SET_Cone
SET_Priority
SET_Reverb
Constructor & Destructor Documentation
SFXFMODVoice::SFXFMODVoice (SFXFMODDevice * device, SFXFMODBuffer * buffer) protected
virtual SFXFMODVoice::~SFXFMODVoice () virtual
Referenced by _getBuffer().
Member Function Documentation
bool SFXFMODVoice::_assignChannel () protected
SFXFMODBuffer* SFXFMODVoice::_getBuffer () const inline protected
References _pause(), _play(), _seek(), _status(), _stop(), _tell(), create(), WeakRefPtr< T >::getPointer(), isVirtual(), SFXVoice::mBuffer, play(), setCone(), setMinMaxDistance(), setPitch(), setPriority(), setReverb(), setTransform(), setVelocity(), setVolume(), and ~SFXFMODVoice().
virtual void SFXFMODVoice::_pause () protected virtual
Pause playback on the device.
Note
Called from both the SFX update thread and the main thread.
Implements SFXVoice.
Referenced by _getBuffer().
virtual void SFXFMODVoice::_play () protected virtual
Start playback on the device.
Note
Called from both the SFX update thread and the main thread.
Implements SFXVoice.
Referenced by _getBuffer().
virtual void SFXFMODVoice::_seek (U32 sample) protected virtual
Set the playback cursor on the device.
Note
Only used for non-streaming voices.
Implements SFXVoice.
Referenced by _getBuffer().
virtual SFXStatus SFXFMODVoice::_status () const protected virtual
Return the current playback status (playing, paused, or stopped).
Default status is stopped.
Implements SFXVoice.
Referenced by _getBuffer().
virtual void SFXFMODVoice::_stop () protected virtual
Stop playback on the device.
Note
Called from both the SFX update thread and the main thread.
Implements SFXVoice.
Referenced by _getBuffer().
virtual U32 SFXFMODVoice::_tell () const protected virtual
Get the playback cursor on the device.
When the voice is playing or paused, this method must return a valid sample position. When the voice is stopped, the result of this method is undefined.
For streaming voices that are looping, the sample position must be a total count of the number of samples played so far which thus includes the count of all cycles before the current one. For non-looping voices, this behavior is optional.
Note
This is called for both streaming and non-streaming voices.
Implements SFXVoice.
Referenced by _getBuffer().
static SFXFMODVoice* SFXFMODVoice::create (SFXFMODDevice * device, SFXFMODBuffer * buffer) static
Referenced by _getBuffer().
bool SFXFMODVoice::isVirtual () const virtual
Returns true if the voice is virtualized on the device.
Note
Always false on devices that do not support voice management.
Reimplemented from SFXVoice.
Referenced by _getBuffer().
void SFXFMODVoice::play (bool looping) virtual
Starts playback from the current position.
Reimplemented from SFXVoice.
Referenced by _getBuffer().
void SFXFMODVoice::setCone (F32 innerAngle, F32 outerAngle, F32 outerVolume) virtual
Set sound cone of a 3D sound.
Parameters
innerAngle Inner cone angle in degrees.
outerAngle Outer cone angle in degrees.
outerVolume Outer volume factor.
Implements SFXVoice.
Referenced by _getBuffer().
void SFXFMODVoice::setMinMaxDistance (F32 min, F32 max) virtual
SFXVoice.
Implements SFXVoice.
Referenced by _getBuffer().
void SFXFMODVoice::setPitch (F32 pitch) virtual
Sets the pitch scale.
Implements SFXVoice.
Referenced by _getBuffer().
void SFXFMODVoice::setPriority (F32 priority) virtual
Set the priority of this voice.
Default 1.0.
Note
Has no effect on devices that do not support voice management.
Reimplemented from SFXVoice.
Referenced by _getBuffer().
void SFXFMODVoice::setReverb (const SFXSoundReverbProperties & reverb) virtual
Set the reverb properties for playback of this sound.
Note
Has no effect on devices that do not support reverb.
Reimplemented from SFXVoice.
Referenced by _getBuffer().
void SFXFMODVoice::setTransform (const MatrixF & transform) virtual
Sets the position and orientation for a 3d voice.
Implements SFXVoice.
Referenced by _getBuffer().
void SFXFMODVoice::setVelocity (const VectorF & velocity) virtual
Sets the velocity for a 3d voice.
Implements SFXVoice.
Referenced by _getBuffer().
void SFXFMODVoice::setVolume (F32 volume) virtual
Sets the volume.
Implements SFXVoice.
Referenced by _getBuffer().
Member Data Documentation
FMOD_CHANNEL* SFXFMODVoice::mChannel mutable protected
F32 SFXFMODVoice::mConeInnerAngle protected
F32 SFXFMODVoice::mConeOuterAngle protected
F32 SFXFMODVoice::mConeOuterVolume protected
SFXFMODDevice* SFXFMODVoice::mDevice protected
FMOD_VECTOR SFXFMODVoice::mDirection protected
F32 SFXFMODVoice::mFrequency protected
F32 SFXFMODVoice::mMaxDistance protected
F32 SFXFMODVoice::mMinDistance protected
FMOD_MODE SFXFMODVoice::mMode protected
FMOD_VECTOR SFXFMODVoice::mPosition protected
F32 SFXFMODVoice::mPriority protected
FMOD_REVERB_CHANNELPROPERTIES SFXFMODVoice::mReverb protected
BitSet32 SFXFMODVoice::mSetFlags protected
FMOD_VECTOR SFXFMODVoice::mVelocity protected
F32 SFXFMODVoice::mVolume protected
Copyright © GarageGames, LLC. All Rights Reserved.