SceneZoneSpaceManager Class Reference
Main Modules Class List Namespace List Online
SceneZoneSpaceManager Class Reference
Object that manages zone spaces in a scene.
#include <scene/zones/sceneZoneSpaceManager.h>
Classes
class ZoneContentIterator
Iterator for the contents of a given zone.
Public Types
enum : U32 {
RootZoneId = 0,
InvalidZoneId = 0xFFFFFFFF
}
typedef Signal< void(SceneZoneSpaceManager *) > ZoningChangedSignal
A signal used to notify that the zone setup of the scene has changed.
Public Member Functions
SceneZoneSpaceManager (SceneContainer *container)
~SceneZoneSpaceManager ()
void updateZoningState ()
Bring the zoning state of the scene up to date.
Objects
void registerObject (SceneObject *object)
Add zoning state to the given object.
void unregisterObject (SceneObject *object)
Remove the given object from the zoning state.
void notifyObjectChanged (SceneObject *object)
Let the manager know that state relevant to zoning of the given object has changed.
void updateObject (SceneObject *object)
Update the zoning state of the given object.
Debugging
void verifyState ()
Verify the current zoning state.
void dumpZoneStates (bool update=true)
Dump the current state of all zone spaces in the scene to the console.
Protected Member Functions
void _addToOutdoorZone (SceneObject *object)
Assign the given object to the outdoor zone.
void _addToZoneList (U32 zoneId, SceneObject *object)
Add to given object to the zone list of the given zone.
void _clearZoneList (U32 zoneId)
Clear all objects assigned to the given zone.
void _compactZonesCheck ()
Check to see if we have accumulated a lot of unallocate zone IDs and if so, compact the zoning lists by reassigning IDs.
SceneObject::ZoneRef * _findInZoneList (U32 zoneId, SceneObject *object) const
Find the given object in the zone list of the given zone.
S32 _getZoneSpaceIndex (SceneZoneSpace *object) const
Return the index into mZoneSpaces for the given object or -1 if is not a zone manager.
void _queryZoneSpaces (const Box3F &area) const
Fill mZoneSpacesQueryList with all ZoneObjectType objects in the given area.
void _rezoneObject (SceneObject *object)
Update the zoning state of the given object.
void _rezoneObjects (const Box3F &area)
Rezone all objects in the given area.
void _zoneInsert (SceneObject *object, bool queryListInitialized=false)
Attach zoning state to the given object.
void _zoneRemove (SceneObject *object)
Detach zoning state from the given object.
Protected Attributes
SceneContainer * mContainer
Scene container that holds the zone spaces we are managing.
U32 mNumActiveZones
Number of zone IDs that are in active use.
U32 mNumTotalAllocatedZones
Total number of zones that have been allocated in the scene.
SceneRootZone * mRootZone
The root and outdoor zone of the scene.
Vector< SceneObject::ZoneRef * > mZoneLists
Object list for each zone in the scene.
Vector< SceneZoneSpace * > mZoneSpaces
Collection of objects that manage zones.
Vector< SceneObject * > mZoneSpacesQueryList
Vector used repeatedly for zone space queries on the container.
Dirty Lists
Updating the zoning state of a scene is done en block rather than individually for each object as it changes transforms or size.
Box3F mDirtyArea
Area of the scene that needs to be rezoned.
Vector< SceneZoneSpace * > mDirtyZoneSpaces
List of zone spaces that have changed state and need updating.
Vector< SceneObject * > mDirtyObjects
List of objects (non-zone spaces) that have changed state and need updating.
Static Protected Attributes
static ClassChunker< SceneObject::ZoneRef > smZoneRefChunker
Allocator for ZoneRefs.
Zones
SceneRootZone * getRootZone () const
Return the root zone of the scene.
void registerZones (SceneZoneSpace *object, U32 numZones)
Register a zone manager.
void unregisterZones (SceneZoneSpace *object)
Unregister a zone manager.
bool isValidZoneId (const U32 zoneId) const
Return true if the given ID belongs to a currently registered zone.
SceneZoneSpace * getZoneOwner (const U32 zoneId) const
Get the scene object that contains the zone with the given ID.
U32 getNumZones () const
Return the total number of zones in the scene.
U32 getNumActiveZones () const
Return the effective amount of used zone IDs in the scene.
U32 getNumZoneSpaces () const
Return the total number of objects in the scene that manage zones.
void findZone (const Point3F &point, SceneZoneSpace *&outZoneSpace, U32 &outZoneID) const
Find the zone that contains the given point.
U32 findZones (const Box3F &area, Vector< U32 > &outZones) const
Collect the IDs of all zones that overlap the given area.
static ZoningChangedSignal & getZoningChangedSignal ()
Detailed Description
Object that manages zone spaces in a scene.
Member Typedef Documentation
typedef Signal< void(SceneZoneSpaceManager*) > SceneZoneSpaceManager::ZoningChangedSignal
A signal used to notify that the zone setup of the scene has changed.
Note
If you use this signal to maintain state that depends on the zoning setup, it's best to not immediately update the sate in response to this signal. The reason is that during loading and editing, the signal may be fired a lot and continuously updating dependent data may waste a lot of time.
Member Enumeration Documentation
anonymous enum : U32
Enumerator
RootZoneId
Zone ID of the exterior zone.
InvalidZoneId
Constant to indicate an invalid zone ID.
Constructor & Destructor Documentation
SceneZoneSpaceManager::SceneZoneSpaceManager (SceneContainer * container)
SceneZoneSpaceManager::~SceneZoneSpaceManager ()
Member Function Documentation
void SceneZoneSpaceManager::_addToOutdoorZone (SceneObject * object) protected
Assign the given object to the outdoor zone.
void SceneZoneSpaceManager::_addToZoneList (U32 zoneId, SceneObject * object) protected
Add to given object to the zone list of the given zone.
void SceneZoneSpaceManager::_clearZoneList (U32 zoneId) protected
Clear all objects assigned to the given zone.
Note
This does not remove the first link in the zone list which is the link back to the zone manager.
void SceneZoneSpaceManager::_compactZonesCheck () protected
Check to see if we have accumulated a lot of unallocate zone IDs and if so, compact the zoning lists by reassigning IDs.
This method may alter all zone IDs in the scene!
SceneObject::ZoneRef* SceneZoneSpaceManager::_findInZoneList (U32 zoneId, SceneObject * object) const protected
Find the given object in the zone list of the given zone.
S32 SceneZoneSpaceManager::_getZoneSpaceIndex (SceneZoneSpace * object) const protected
Return the index into mZoneSpaces for the given object or -1 if is not a zone manager.
void SceneZoneSpaceManager::_queryZoneSpaces (const Box3F & area) const protected
Fill mZoneSpacesQueryList with all ZoneObjectType objects in the given area.
void SceneZoneSpaceManager::_rezoneObject (SceneObject * object) protected
Update the zoning state of the given object.
void SceneZoneSpaceManager::_rezoneObjects (const Box3F & area) protected
Rezone all objects in the given area.
Referenced by SceneZoneSpaceManager::ZoneContentIterator::ZoneContentIterator().
void SceneZoneSpaceManager::_zoneInsert (SceneObject * object, bool queryListInitialized = false) protected
Attach zoning state to the given object.
void SceneZoneSpaceManager::_zoneRemove (SceneObject * object) protected
Detach zoning state from the given object.
void SceneZoneSpaceManager::dumpZoneStates (bool update = true)
Dump the current state of all zone spaces in the scene to the console.
Parameters
update If true, zoning state states are updated first; if false, zoning is dumped as is.
Referenced by getZoningChangedSignal().
void SceneZoneSpaceManager::findZone (const Point3F & point, SceneZoneSpace *& outZoneSpace, U32 & outZoneID) const
Find the zone that contains the given point.
Note that the result can be any zone containing the given point.
Referenced by getNumZoneSpaces().
U32 SceneZoneSpaceManager::findZones (const Box3F & area, Vector< U32 > & outZones) const
Collect the IDs of all zones that overlap the given area.
Parameters
area AABB of scene space to query.
outZones IDs of all overlapped zones are added to this vector.
Returns
Number of zones that have been added to outZones. Always at least 1 as at least the outdoor zone always overlaps the given area (though if another zone manager fully contains area, the outdoor zone will not be added to the list).
Referenced by getNumZoneSpaces().
U32 SceneZoneSpaceManager::getNumActiveZones () const inline
Return the effective amount of used zone IDs in the scene.
References mNumActiveZones.
U32 SceneZoneSpaceManager::getNumZones () const inline
Return the total number of zones in the scene.
References mNumTotalAllocatedZones.
Referenced by SceneZoneSpaceManager::ZoneContentIterator::ZoneContentIterator().
U32 SceneZoneSpaceManager::getNumZoneSpaces () const inline
Return the total number of objects in the scene that manage zones.
References findZone(), findZones(), and Vector< T >::size().
SceneRootZone* SceneZoneSpaceManager::getRootZone () const inline
Return the root zone of the scene.
References mRootZone, registerZones(), and unregisterZones().
SceneZoneSpace* SceneZoneSpaceManager::getZoneOwner (const U32 zoneId) const inline
Get the scene object that contains the zone with the given ID.
Parameters
zoneId ID of the zone. Must be valid.
Returns
The zone space that has registered the given zone.
References isValidZoneId().
Referenced by SceneZoneSpaceManager::ZoneContentIterator::ZoneContentIterator().
static ZoningChangedSignal& SceneZoneSpaceManager::getZoningChangedSignal () inline static
References dumpZoneStates(), and verifyState().
bool SceneZoneSpaceManager::isValidZoneId (const U32 zoneId) const inline
Return true if the given ID belongs to a currently registered zone.
Referenced by getZoneOwner().
void SceneZoneSpaceManager::notifyObjectChanged (SceneObject * object)
Let the manager know that state relevant to zoning of the given object has changed.
void SceneZoneSpaceManager::registerObject (SceneObject * object)
Add zoning state to the given object.
void SceneZoneSpaceManager::registerZones (SceneZoneSpace * object, U32 numZones)
Register a zone manager.
Parameters
object SceneZoneSpace object that contains zones.
numZones Number of zones that object contains.
Referenced by getRootZone().
void SceneZoneSpaceManager::unregisterObject (SceneObject * object)
Remove the given object from the zoning state.
void SceneZoneSpaceManager::unregisterZones (SceneZoneSpace * object)
Unregister a zone manager.
Parameters
object Object that contains zones.
Referenced by getRootZone().
void SceneZoneSpaceManager::updateObject (SceneObject * object)
Update the zoning state of the given object.
void SceneZoneSpaceManager::updateZoningState ()
Bring the zoning state of the scene up to date.
This will cause objects that have moved or have been resized to be rezoned and will updated regions of the scene that had their zoning setup changed.
Note
This method depends on proper use of notifyObjectChanged().
void SceneZoneSpaceManager::verifyState ()
Verify the current zoning state.
This makes sure all the connectivity information and all the zone assignments appear to be correct.
Referenced by getZoningChangedSignal().
Member Data Documentation
SceneContainer* SceneZoneSpaceManager::mContainer protected
Scene container that holds the zone spaces we are managing.
Box3F SceneZoneSpaceManager::mDirtyArea protected
Area of the scene that needs to be rezoned.
Vector< SceneObject* > SceneZoneSpaceManager::mDirtyObjects protected
List of objects (non-zone spaces) that have changed state and need updating.
Vector< SceneZoneSpace* > SceneZoneSpaceManager::mDirtyZoneSpaces protected
List of zone spaces that have changed state and need updating.
U32 SceneZoneSpaceManager::mNumActiveZones protected
Number of zone IDs that are in active use.
Referenced by getNumActiveZones().
U32 SceneZoneSpaceManager::mNumTotalAllocatedZones protected
Total number of zones that have been allocated in the scene.
Referenced by getNumZones().
SceneRootZone* SceneZoneSpaceManager::mRootZone protected
The root and outdoor zone of the scene.
Referenced by getRootZone().
Vector< SceneObject::ZoneRef* > SceneZoneSpaceManager::mZoneLists protected
Object list for each zone in the scene.
First entry in the list points back to the zone manager.
Referenced by SceneZoneSpaceManager::ZoneContentIterator::ZoneContentIterator().
Vector< SceneZoneSpace* > SceneZoneSpaceManager::mZoneSpaces protected
Collection of objects that manage zones.
Vector< SceneObject* > SceneZoneSpaceManager::mZoneSpacesQueryList mutable protected
Vector used repeatedly for zone space queries on the container.
ClassChunker< SceneObject::ZoneRef > SceneZoneSpaceManager::smZoneRefChunker static protected
Allocator for ZoneRefs.
Copyright © GarageGames, LLC. All Rights Reserved.