ConnectionProtocol Class Reference
Main Modules Class List Namespace List Online
ConnectionProtocol Class Reference abstract
The base class for Torque's networking protocol.
#include <core/dnet.h>
Public Member Functions
ConnectionProtocol ()
void buildSendPacketHeader (BitStream *bstream, S32 packetType=0)
bool connectionEstablished ()
virtual void handleConnectionEstablished ()=0
virtual void handleNotify (bool recvd)=0
virtual void handlePacket (BitStream *bstream)=0
virtual void keepAlive ()=0
virtual void processRawPacket (BitStream *bstream)
virtual bool readDemoStartBlock (BitStream *stream)
void sendAckPacket ()
virtual Net::Error sendPacket (BitStream *bstream)=0
void sendPingPacket ()
void setConnectionEstablished ()
void setConnectSequence (U32 connectSeq)
bool windowFull ()
virtual void writeDemoStartBlock (ResizeBitStream *stream)
Protected Attributes
U32 mAckMask
bool mConnectionEstablished
U32 mConnectSequence
U32 mHighestAckedSeq
U32 mLastRecvAckAck
U32 mLastSendSeq
U32 mLastSeqRecvd
U32 mLastSeqRecvdAtSend [32]
Detailed Description
The base class for Torque's networking protocol.
This implements a sliding window connected message stream over an unreliable transport (UDP). It provides a simple notify protocol to allow subclasses to be aware of what packets were sent succesfully and which failed.
Basically, a window size of 32 is provided, and each packet contains in the header a bitmask, acknowledging the receipt (or failure to receive) of the last 32 packets.
See also
NetConnection, NetProtocol
Constructor & Destructor Documentation
ConnectionProtocol::ConnectionProtocol ()
Member Function Documentation
void ConnectionProtocol::buildSendPacketHeader (BitStream * bstream, S32 packetType = 0)
bool ConnectionProtocol::connectionEstablished ()
Referenced by setConnectionEstablished().
virtual void ConnectionProtocol::handleConnectionEstablished () pure virtual
Implemented in NetConnection.
Referenced by setConnectSequence().
virtual void ConnectionProtocol::handleNotify (bool recvd) pure virtual
Implemented in NetConnection.
Referenced by setConnectSequence().
virtual void ConnectionProtocol::handlePacket (BitStream * bstream) pure virtual
Implemented in NetConnection.
Referenced by setConnectSequence().
virtual void ConnectionProtocol::keepAlive () pure virtual
Implemented in NetConnection.
Referenced by setConnectSequence().
virtual void ConnectionProtocol::processRawPacket (BitStream * bstream) virtual
Reimplemented in NetConnection.
Referenced by setConnectSequence().
virtual bool ConnectionProtocol::readDemoStartBlock (BitStream * stream) virtual
Reimplemented in NetConnection, and GameConnection.
Referenced by setConnectSequence().
void ConnectionProtocol::sendAckPacket ()
virtual Net::Error ConnectionProtocol::sendPacket (BitStream * bstream) pure virtual
Implemented in NetConnection.
Referenced by setConnectSequence().
void ConnectionProtocol::sendPingPacket ()
void ConnectionProtocol::setConnectionEstablished () inline
References connectionEstablished(), and windowFull().
void ConnectionProtocol::setConnectSequence (U32 connectSeq) inline
References handleConnectionEstablished(), handleNotify(), handlePacket(), keepAlive(), processRawPacket(), readDemoStartBlock(), sendPacket(), and writeDemoStartBlock().
bool ConnectionProtocol::windowFull ()
Referenced by setConnectionEstablished().
virtual void ConnectionProtocol::writeDemoStartBlock (ResizeBitStream * stream) virtual
Reimplemented in NetConnection, and GameConnection.
Referenced by setConnectSequence().
Member Data Documentation
U32 ConnectionProtocol::mAckMask protected
bool ConnectionProtocol::mConnectionEstablished protected
U32 ConnectionProtocol::mConnectSequence protected
U32 ConnectionProtocol::mHighestAckedSeq protected
U32 ConnectionProtocol::mLastRecvAckAck protected
U32 ConnectionProtocol::mLastSendSeq protected
U32 ConnectionProtocol::mLastSeqRecvd protected
U32 ConnectionProtocol::mLastSeqRecvdAtSend[32] protected
Copyright © GarageGames, LLC. All Rights Reserved.