SceneZoneSpace Class Reference
Main Modules Class List Namespace List Online
SceneZoneSpace Class Reference abstract
Abstract base class for an object that manages zones in a scene.
#include <scene/zones/sceneZoneSpace.h>
Classes
struct ZoneSpaceRef
Link to another zone space.
Public Types
enum { InvalidZoneGroup = 0 }
typedef SceneSpace Parent
enum ZoneFlags { ZoneFlag_IsClosedOffSpace = BIT(0) }
Public Types inherited from SceneSpace
typedef SceneObject Parent
Public Types inherited from SceneObject
enum {
MaxObjectZones = 128,
NumMountPoints = 32,
NumMountPointBits = 5
}
typedef NetObject Parent
enum SceneObjectFlags {
RenderEnabledFlag = BIT(0),
SelectionEnabledFlag = BIT(1),
DisableCullingInEditorFlag = BIT(2),
VisualOccluderFlag = BIT(3),
SoundOccluderFlag = BIT(4),
NextFreeFlag = BIT(5)
}
Bit-flags stored in mObjectFlags.
enum SceneObjectMasks {
InitialUpdateMask = BIT(0),
ScaleMask = BIT(1),
FlagMask = BIT(2),
MountedMask = BIT(3),
NextFreeMask = BIT(4)
}
Networking dirty mask.
Public Types inherited from SimGroup
typedef SimSet Parent
Public Types inherited from SimSet
typedef SimObject Parent
enum SetModification {
SetCleared,
SetObjectAdded,
SetObjectRemoved
}
typedef Signal< void(SetModification modification, SimSet *set, SimObject *object) > SetModificationSignal
Signal for letting observers know when objects are added to or removed from the set.
typedef SimObjectList::iterator iterator
typedef SimObjectList::value_type value
Public Types inherited from SimObject
typedef ConsoleObject Parent
enum WriteFlags {
SelectedOnly = BIT(0),
NoName = BIT(1),
IgnoreCanSave = BIT(2)
}
Flags passed to SimObject::write.
Public Types inherited from EngineObject
typedef void(* DebugEnumInstancesCallback) (EngineObject *)
Type of callback function for iterating over EngineObject instances.
Public Member Functions
SceneZoneSpace ()
virtual ~SceneZoneSpace ()
void dumpZoneState (bool update=true)
Dump a listing of all objects assigned to this zone space to the console as well as a list of all connected spaces.
virtual bool getZoneAmbientLightColor (U32 zone, ColorF &outColor) const
Get the ambient light color of the given zone in this space or return false if the given zone does not have an ambient light color assigned to it.
U32 getZoneGroup () const
Return the zone group that this zone space belongs to.
U32 getZoneRange () const
Return the number of zones that are managed by this object.
U32 getZoneRangeStart () const
Gets the index of the first zone this object manages in the collection of zones or 0xFFFFFFFF if the object is not managing zones.
bool isRootZone () const
Return true if this is the outdoor zone.
virtual U32 packUpdate (NetConnection *connection, U32 mask, BitStream *stream)
Instructs this object to pack its state for transfer over the network.
void setZoneGroup (U32 group)
Set the zone group of this zone space.
virtual void unpackUpdate (NetConnection *connection, BitStream *stream)
Instructs this object to read state data previously packed with packUpdate.
virtual bool writeField (StringTableEntry fieldName, const char *value)
Determine whether or not a field should be written.
Containment Tests
virtual bool getOverlappingZones (const Box3F &aabb, U32 *zones, U32 &numZones)=0
virtual bool getOverlappingZones (SceneObject *obj, U32 *outZones, U32 &outNumZones)
Find the zones in this object that obj is part of.
virtual U32 getPointZone (const Point3F &p)=0
Returns the ID of the zone that are managed by this object that contains p.
Connectivity
virtual void connectZoneSpace (SceneZoneSpace *zoneSpace)
Connect this zone space to the given zone space.
virtual void disconnectZoneSpace (SceneZoneSpace *zoneSpace)
If the object is a zone space, then this method is called to instruct the object to remove any zone connectivity to zoneSpace.
Traversals
virtual void traverseZones (SceneTraversalState *state)=0
Traverse into the zones of this space.
virtual void traverseZones (SceneTraversalState *state, U32 startZoneId)=0
Traverse the zones in this space starting with the given zone.
Public Member Functions inherited from SceneSpace
SceneSpace ()
~SceneSpace ()
virtual bool onAdd ()
Called when the object is added to the sim.
virtual void onEditorDisable ()
Called when the editor is deactivated.
virtual void onEditorEnable ()
Called when the editor is activated.
virtual void onRemove ()
Called when the object is removed from the sim.
virtual void prepRenderImage (SceneRenderState *state)
Called when the SceneManager is ready for the registration of render instances.
virtual void setTransform (const MatrixF &mat)
Sets the Object -> World transform.
Public Member Functions inherited from SceneObject
SceneObject ()
virtual ~SceneObject ()
virtual void clearProcessAfter ()
Clears the effects of a call to processAfter()
DECLARE_CONOBJECT (SceneObject)
virtual ProcessObject * getAfterObject () const
Returns the object that this processes after.
ProcessList * getProcessList () const
Return the ProcessList for this object to use.
U32 getTypeMask () const
Return the type mask that indicates to which broad object categories this object belongs.
virtual void inspectPostApply ()
Called after any property of the object is changed in the world editor.
virtual void onCameraScopeQuery (NetConnection *connection, CameraScopeQuery *query)
Queries the object about information used to determine scope.
virtual void onDeleteNotify (SimObject *object)
Called when a SimObject is deleted.
virtual void processAfter (ProcessObject *obj)
Force this object to process after some other object.
virtual void setProcessTick (bool t)
Set the status of tick processing.
SceneManager * getSceneManager () const
Return the SceneManager that this SceneObject belongs to.
void addToScene ()
Adds object to the client or server container depending on the object.
void removeFromScene ()
Removes the object from the client/server container.
SceneContainer * getContainer ()
Returns a pointer to the container that contains this object.
bool isRenderEnabled () const
Return true if this object is rendered.
void setRenderEnabled (bool value)
Set whether the object gets rendered.
bool isSelectionEnabled () const
Return true if this object can be selected in the editor.
void setSelectionEnabled (bool value)
Set whether the object can be selected in the editor.
bool isCullingDisabledInEditor () const
Return true if the object doesn't want to be subjected to culling when in the editor.
bool isVisualOccluder () const
Return true if the object should be taken into account for visual occlusion.
virtual void disableCollision ()
Disables collisions for this object including raycasts.
virtual void enableCollision ()
Enables collisions for this object.
bool isCollisionEnabled () const
Returns true if collisions are enabled.
virtual void onCollision (SceneObject *object, const VectorF &vec)
This gets called when an object collides with this object.
virtual bool isDisplacable () const
Returns true if this object allows itself to be displaced.
virtual Point3F getMomentum () const
Returns the momentum of this object.
virtual void setMomentum (const Point3F &momentum)
Sets the momentum of this object.
virtual F32 getMass () const
Returns the mass of this object.
virtual bool displaceObject (const Point3F &displaceVector)
Displaces this object by a vector.
virtual const MatrixF & getTransform () const
Returns the transform which can be used to convert object space to world space.
const MatrixF & getWorldTransform () const
Returns the transform which can be used to convert world space into object space.
const VectorF & getScale () const
Returns the scale of the object.
const Box3F & getObjBox () const
Returns the bounding box for this object in local coordinates.
const Box3F & getWorldBox () const
Returns the bounding box for this object in world coordinates.
const SphereF & getWorldSphere () const
Returns the bounding sphere for this object in world coordinates.
Point3F getBoxCenter () const
Returns the center of the bounding box in world coordinates.
virtual void setScale (const VectorF &scale)
Sets the scale for the object.
virtual void setRenderTransform (const MatrixF &mat)
This sets the render transform for this object.
const MatrixF & getRenderTransform () const
Returns the render transform.
const MatrixF & getRenderWorldTransform () const
Returns the render transform to convert world to local coordinates.
const Box3F & getRenderWorldBox () const
Returns the render world box.
virtual void setHidden (bool hidden)
Sets the state of this object as hidden or not.
virtual void buildConvex (const Box3F &box, Convex *convex)
Builds a convex hull for this object.
virtual bool buildPolyList (PolyListContext context, AbstractPolyList *polyList, const Box3F &box, const SphereF &sphere)
Builds a list of polygons which intersect a bounding volume.
virtual bool castRay (const Point3F &start, const Point3F &end, RayInfo *info)
Casts a ray and obtain collision information, returns true if RayInfo is modified.
virtual bool castRayRendered (const Point3F &start, const Point3F &end, RayInfo *info)
Casts a ray against rendered geometry, returns true if RayInfo is modified.
virtual void buildSilhouette (const SceneCameraState &cameraState, Vector< Point3F > &outPoints)
Build a world-space silhouette polygon for the object for the given camera settings.
virtual bool containsPoint (const Point3F &point)
Return true if the given point is contained by the object's (collision) shape.
virtual bool collideBox (const Point3F &start, const Point3F &end, RayInfo *info)
virtual Point3F getPosition () const
Returns the position of the object.
Point3F getRenderPosition () const
Returns the render-position of the object.
void setPosition (const Point3F &pos)
Sets the position of the object.
virtual Point3F getVelocity () const
Gets the velocity of the object.
virtual void setVelocity (const Point3F &v)
Sets the velocity of the object.
virtual void applyImpulse (const Point3F &pos, const VectorF &vec)
Applies an impulse force to this object.
virtual void applyRadialImpulse (const Point3F &origin, F32 radius, F32 magnitude)
Applies a radial impulse to the object using the impulse origin and force.
virtual F32 distanceTo (const Point3F &pnt) const
Returns the distance from this object to a point.
bool isOccludingSound () const
Return whether the object's collision shape is blocking sound.
virtual SFXAmbience * getSoundAmbience () const
Return the ambient sound space active inside the volume of this object or NULL if the object does not have its own ambient space.
void setLightingPlugin (SceneObjectLightingPlugin *plugin)
SceneObjectLightingPlugin * getLightingPlugin ()
const bool isGlobalBounds () const
void setGlobalBounds ()
If global bounds are set to be true, then the object is assumed to have an infinitely large bounding box for collision and rendering purposes.
virtual void mountObject (SceneObject *obj, S32 node, const MatrixF &xfm=MatrixF::Identity)
ex: Mount B to A at A's node N A.mountObject(B, N)
virtual void unmountObject (SceneObject *obj)
Remove an object mounting.
virtual void unmount ()
Unmount this object from it's mount.
virtual void onMount (SceneObject *obj, S32 node)
Callback when this object is mounted.
virtual void onUnmount (SceneObject *obj, S32 node)
Callback when this object is unmounted.
virtual void getMountTransform (S32 index, const MatrixF &xfm, MatrixF *outMat)
virtual void getRenderMountTransform (F32 delta, S32 index, const MatrixF &xfm, MatrixF *outMat)
virtual SceneObject * getObjectMount ()
Return the object that this object is mounted to.
virtual SceneObject * getMountLink ()
Return object link of next object mounted to this object's mount.
virtual SceneObject * getMountList ()
Returns object list of objects mounted to this object.
virtual U32 getMountNode ()
Returns the mount id that this is mounted to.
virtual bool isMounted ()
Returns true if this object is mounted to anything at all Also try to resolve the PID to objectId here if it is pending.
virtual S32 getMountedObjectCount ()
Returns the number of object mounted along with this.
virtual SceneObject * getMountedObject (S32 idx)
Returns the object mounted at a position in the mount list.
virtual S32 getMountedObjectNode (S32 idx)
Returns the node the object at idx is mounted to.
virtual SceneObject * getMountNodeObject (S32 node)
Returns the object a object on the mount list is mounted to.
void resolveMountPID ()
Public Member Functions inherited from NetObject
NetObject ()
~NetObject ()
virtual void clearMaskBits (U32 orMask)
Clear the specified bits from the dirty mask.
void clearScopeAlways ()
Stop scoping the object to all connections.
virtual String describeSelf () const
Return a textual description of the object.
virtual U32 filterMaskBits (U32 mask, NetConnection *connection)
U32 getNetIndex ()
Get the ghost index of this object.
virtual F32 getUpdatePriority (CameraScopeQuery *focusObject, U32 updateMask, S32 updateSkips)
This returns a value which is used to prioritize which objects need to be updated.
bool isClientObject () const
Is this a client object?
bool isGhost () const
Is this is a ghost?
bool isGhostable () const
Is this object ghostable?
bool isGhostAlways () const
Should this object always be ghosted?
bool isScopeable () const
Is this object subject to scoping?
bool isScopeLocal () const
Should this object only be visible to the client which created it?
bool isServerObject () const
Is this a server object?
virtual void setMaskBits (U32 orMask)
Used to mark a bit as dirty; ie, that its corresponding set of fields need to be transmitted next update.
void setScopeAlways ()
Scope the object to all connections.
DECLARE_CONOBJECT (NetObject)
bool onAdd ()
Called when the object is added to the sim.
void onRemove ()
Called when the object is removed from the sim.
NetObject * getServerObject () const
Returns a pointer to the server object when on a local connection.
NetObject * getClientObject () const
Returns a pointer to the client object when on a local connection.
Public Member Functions inherited from SimGroup
~SimGroup ()
void addObject (SimObject *object, SimObjectId id)
void addObject (SimObject *object, const char *name)
virtual void addObject (SimObject *object)
Add the given object to the set.
virtual void clear ()
Remove all objects from this set.
virtual SimGroup * clone ()
Return a shallow copy of this object.
DECLARE_CONOBJECT (SimGroup)
virtual SimGroup * deepClone ()
Return a deep copy of this object.
virtual SimObject * findObject (const char *name)
Find a named sub-object of this object.
virtual void popObject ()
Remove an object from the end of the list.
virtual bool processArguments (S32 argc, ConsoleValueRef *argv)
Process constructor options. (ie, new SimObject(1,2,3))
virtual void pushObject (SimObject *object)
Add the given object to the end of the object list of this set.
virtual void removeObject (SimObject *object)
Remove the given object from the set.
Public Member Functions inherited from SimSet
SimSet ()
~SimSet ()
virtual void addTamlChild (SimObject *pSimObject)
Called when Taml attempts to populate an objects children during a read.
void callOnChildren (const String &method, S32 argc, ConsoleValueRef argv[], bool executeOnChildGroups=true)
DECLARE_CONOBJECT (SimSet)
SimObject * findObject (SimObject *object)
Find the given object in this set.
template<class T >
void findObjectByCallback (bool(*fn)(T *), Vector< T * > &foundObjects)
Add all child objects (including children of children) to the foundObjects Vector which are of type T and for which DecideAddObjectCallback return true;.
virtual SimObject * findObjectByInternalName (StringTableEntry internalName, bool searchChildren=false)
SimObject * findObjectByLineNumber (const char *fileName, S32 declarationLine, bool searchChildren=false)
template<class T >
void findObjectByType (Vector< T * > &foundObjects)
Add all child objects (including children of children) to the foundObjects Vector which are of type T.
SimObject * getRandom ()
const SetModificationSignal & getSetModificationSignal () const
Return the signal that is triggered when an object is added to or removed from the set.
SetModificationSignal & getSetModificationSignal ()
virtual SimObject * getTamlChild (const U32 childIndex) const
Called when Taml attempts to compile a list of children.
virtual U32 getTamlChildCount (void) const
Called when Taml attempts to compile a list of children.
void lock ()
virtual bool readObject (Stream *stream)
U32 sizeRecursive ()
Return the number of objects in this set as well as all sets that are contained in this set and its children.
void unlock ()
virtual void write (Stream &stream, U32 tabStop, U32 flags=0)
Output the TorqueScript to recreate this object.
virtual bool writeObject (Stream *stream)
virtual bool acceptsAsChild (SimObject *object) const
Return true if this set accepts the given object as a child.
void deleteAllObjects ()
Deletes all the objects in the set.
void bringObjectToFront (SimObject *obj)
void pushObjectToBack (SimObject *obj)
void scriptSort (const String &scriptCallbackFn)
Performs a sort of the objects in the set using a script callback function to do the comparison.
SimObject * front ()
SimObject * first ()
SimObject * last ()
bool empty () const
S32 size () const
iterator begin ()
iterator end ()
value operator[] (S32 index)
iterator find (iterator first, iterator last, SimObject *obj)
iterator find (SimObject *obj)
virtual bool reOrder (SimObject *obj, SimObject *target=0)
Reorder the position of "obj" to either be the last object in the list or, if "target" is given, to come before "target" in the list of children.
SimObject * at (S32 index) const
Return the object at the given index.
Public Member Functions inherited from SimObject
virtual void copyTo (SimObject *object)
Copy SimObject to another SimObject (Originally designed for T2D).
DECLARE_CONOBJECT (SimObject)
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
virtual void getConsoleMethodData (const char *fname, S32 routingId, S32 *type, S32 *minArgs, S32 *maxArgs, void **callback, const char **usage)
Namespace * getNamespace ()
Return the object's namespace.
StringTableEntry getProgenitorFile (void) const
virtual bool handlesConsoleMethod (const char *fname, S32 *routingId)
void setProgenitorFile (const char *pFile)
const char * tabComplete (const char *prevText, S32 baseLen, bool)
Get next matching item in namespace.
virtual void writeFields (Stream &stream, U32 tabStop)
Write the fields of this object in TorqueScript.
void setCanSaveDynamicFields (bool bCanSave)
Set whether fields created at runtime should be saved. Default is true.
bool getCanSaveDynamicFields ()
Get whether fields created at runtime should be saved. Default is true.
SimObject * getCopySource () const
Return the object that this object is copying fields from.
void setCopySource (SimObject *object)
Set the object that this object should be copying fields from.
void assignFieldsFrom (SimObject *obj)
Copy fields from another object onto this one.
void assignDynamicFieldsFrom (SimObject *obj)
Copy dynamic fields from another object onto this one.
Notify * removeNotify (void *ptr, Notify::Type)
Remove a notification from the list.
void deleteNotify (SimObject *obj)
Notify an object when we are deleted.
void clearNotify (SimObject *obj)
Notify an object when we are cleared.
void clearAllNotifications ()
Remove all notifications for this object.
void processDeleteNotifies ()
Send out deletion notifications.
void registerReference (SimObject **obj)
Register a reference to this object.
void unregisterReference (SimObject **obj)
Unregister a reference to this object.
SimPersistID * getPersistentId () const
Return the persistent ID assigned to this object or NULL.
SimPersistID * getOrCreatePersistentId ()
Return the persistent ID assigned to this object or assign one to it if it has none.
StringTableEntry getClassNamespace () const
Return name of class namespace set on this object.
StringTableEntry getSuperClassNamespace () const
Return name of superclass namespace set on this object.
void setClassNamespace (const char *classNamespace)
void setSuperClassNamespace (const char *superClassNamespace)
const char * getDataField (StringTableEntry slotName, const char *array)
Get the value of a field on the object.
void setDataField (StringTableEntry slotName, const char *array, const char *value)
Set the value of a field on the object.
const char * getPrefixedDataField (StringTableEntry fieldName, const char *array)
void setPrefixedDataField (StringTableEntry fieldName, const char *array, const char *value)
const char * getPrefixedDynamicDataField (StringTableEntry fieldName, const char *array, const S32 fieldType=-1)
void setPrefixedDynamicDataField (StringTableEntry fieldName, const char *array, const char *value, const S32 fieldType=-1)
StringTableEntry getDataFieldPrefix (StringTableEntry fieldName)
U32 getDataFieldType (StringTableEntry slotName, const char *array)
Get the type of a field on the object.
void setDataFieldType (const U32 fieldTypeId, StringTableEntry slotName, const char *array)
Set the type of a dynamic field on the object.
void setDataFieldType (const char *typeName, StringTableEntry slotName, const char *array)
SimFieldDictionary * getFieldDictionary ()
Get reference to the dictionary containing dynamic fields.
virtual StringTableEntry getComponentName ()
void setInternalName (const char *newname)
These functions support internal naming that is not namespace bound for locating child controls in a generic way.
StringTableEntry getInternalName () const
Get the internal name of this control.
void setOriginalName (const char *originalName)
Set the original name of this control.
StringTableEntry getOriginalName () const
Get the original name of this control.
void setFilename (const char *file)
These functions allow you to set and access the filename where this object was created.
StringTableEntry getFilename () const
Get the filename.
void setDeclarationLine (U32 lineNumber)
These functions are used to track the line number (1-based) on which the object was created if it was loaded from script.
S32 getDeclarationLine () const
Get the declaration line number.
virtual bool save (const char *pcFilePath, bool bOnlySelected=false, const char *preappend=NULL)
Save object as a TorqueScript File.
virtual bool isMethod (const char *methodName)
Check if a method exists in the objects current namespace.
virtual bool isField (const char *fieldName, bool includeStatic=true, bool includeDynamic=true)
Return true if the field is defined on the object.
SimObjectId getId () const
Return the unique numeric object ID.
const char * getIdString () const
Return the object ID as a string.
StringTableEntry getName () const
Return the name of this object.
SimGroup * getGroup () const
Return the SimGroup that this object is contained in.
void assignName (const char *name)
Assign the given name to this object.
void setId (SimObjectId id)
bool isChildOfGroup (SimGroup *pGroup)
bool isProperlyAdded () const
bool isDeleted () const
bool isRemoved () const
virtual bool isLocked () const
virtual void setLocked (bool b)
virtual bool isHidden () const
bool isSelected () const
bool isExpanded () const
bool isEditorOnly () const
bool isNameChangeAllowed () const
bool isAutoDeleted () const
void setSelected (bool sel)
void setExpanded (bool exp)
void setModDynamicFields (bool dyn)
void setModStaticFields (bool sta)
bool canModDynamicFields ()
bool canModStaticFields ()
void setAutoDelete (bool val)
void setEditorOnly (bool val)
void setNameChangeAllowed (bool val)
bool getCanSave () const
Returns boolean specifying if the object can be serialized.
virtual void setCanSave (bool val)
Set serialization flag.
bool isSelectedRecursive () const
Returns true if this object is selected or any group it is a member of is.
SimObject ()
virtual ~SimObject ()
virtual void onGroupAdd ()
Called when the object is added to a SimGroup.
virtual void onGroupRemove ()
Called when the object is removed from a SimGroup.
virtual void onNameChange (const char *name)
Called when the object's name is changed.
virtual void onPostAdd ()
Called when the adding of the object to the sim is complete, all sub-objects have been processed as well.
virtual void onStaticModified (const char *slotName, const char *newValue=NULL)
Specifically, these are called by setDataField when a static or dynamic field is modified, see the console details.
virtual void onDynamicModified (const char *slotName, const char *newValue=NULL)
Called when a dynamic field is modified.
virtual void inspectPreApply ()
Called before any property of the object is changed in the world editor.
bool registerObject ()
Register an object with the object system.
bool registerObject (U32 id)
Register the object, forcing the id.
bool registerObject (const char *name)
Register the object, assigning the name.
bool registerObject (const char *name, U32 id)
Register the object, assigning a name and ID.
void unregisterObject ()
Unregister the object from Sim.
void deleteObject ()
Unregister, mark as deleted, and free the object.
void safeDeleteObject ()
Performs a safe delayed delete of the object using a sim event.
bool addToSet (SimObjectId)
bool addToSet (const char *)
bool removeFromSet (SimObjectId)
bool removeFromSet (const char *)
void dumpToConsole (bool includeFunctions=true)
Dump the contents of this object to the console.
virtual void dumpClassHierarchy ()
added this so that you can print the entire class hierarchy, including script objects,
virtual void dumpGroupHierarchy ()
Print the SimGroup hierarchy of this object to the console.
Public Member Functions inherited from ConsoleObject
ConsoleObject ()
virtual AbstractClassRep * getClassRep () const
Gets the ClassRep.
const AbstractClassRep::Field * findField (StringTableEntry fieldName) const
Get a reference to a field by name.
bool setField (const char *fieldName, const char *value)
Set the value of a field.
void logMessage (const char *fmt,...) const
Logs with Con::printf.
void logWarning (const char *fmt,...) const
Logs with Con::warnf.
void logError (const char *fmt,...) const
Logs with Con::errorf.
const AbstractClassRep::FieldList & getFieldList () const
Get a list of all the fields. This information cannot be modified.
AbstractClassRep::FieldList & getModifiableFieldList ()
Get a list of all the fields, set up so we can modify them.
bool & getDynamicGroupExpand ()
Get a handle to a boolean telling us if we expanded the dynamic group.
S32 getClassId (U32 netClassGroup) const
Get our network-layer class id.
StringTableEntry getClassName () const
Get our compiler and platform independent class name.
Public Member Functions inherited from EngineObject
EngineObject ()
virtual ~EngineObject ()
DECLARE_ABSTRACT_CLASS (EngineObject, void)
DECLARE_INSCOPE (_GLOBALSCOPE)
IEngineObjectPool * getEngineObjectPool () const
Return the pool of EngineObjects to which this object belongs.
void operator delete (void *ptr)
Release the given object's memory in the pool it has been allocated from.
void * operator new (size_t size)
void * operator new (size_t size, IEngineObjectPool *pool)
void * operator new (size_t size TORQUE_TMM_ARGS_DECL)
Allocate a new object in the default object pool.
void * operator new (size_t size, IEngineObjectPool *pool TORQUE_TMM_ARGS_DECL)
Allocate a new object in the given object pool.
void * operator new (size_t size, void *ptr)
Placement new.
Public Member Functions inherited from StrongRefBase
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Public Member Functions inherited from ProcessObject
ProcessObject ()
virtual ~ProcessObject ()
virtual void advanceTime (F32 dt)
Advances simulation time for animations.
virtual GameConnection * getControllingClient ()
This is really implemented in GameBase and is only here to avoid casts within ProcessList.
virtual U32 getPacketDataChecksum (GameConnection *conn)
This is really implemented in GameBase and is only here to avoid casts within ProcessList.
virtual void interpolateTick (F32 delta)
Interpolates between tick events.
bool isTicking () const
Returns true if this object processes ticks.
void plJoin (ProcessObject *)
void plLinkAfter (ProcessObject *)
void plLinkBefore (ProcessObject *)
void plUnlink ()
virtual void preprocessMove (Move *move)
Allow object to modify the Move before it is ticked or sent to the server.
virtual void processTick (const Move *move)
Processes a move event and updates object state once every 32 milliseconds.
void removeFromProcessList ()
Removes this object from the tick-processing list.
Static Public Member Functions
static void initPersistFields ()
Static Public Member Functions inherited from SceneObject
static void initPersistFields ()
Static Public Member Functions inherited from NetObject
static void collapseDirtyList ()
static void initPersistFields ()
template<class T >
static T * getServerObject (T *netObj)
Template form for the callers convenience.
template<class T >
static T * getClientObject (T *netObj)
Template form for the callers convenience.
Static Public Member Functions inherited from SimObject
static SimObject * __findObject (const char *id)
static const char * __getObjectId (ConsoleObject *object)
static void initPersistFields ()
static void setForcedId (SimObjectId id)
Force an Id on the next registered object.
Static Public Member Functions inherited from ConsoleObject
static const char * __category ()
static const char * __description ()
static void consoleInit ()
Register global constant variables and do other one-time initialization tasks in a subclass of ConsoleObject.
static void initPersistFields ()
Register dynamic fields in a subclass of ConsoleObject.
static const char * lookupClassName (const U32 in_classTag)
Get the classname from a class tag.
static ConsoleObject * create (const char *in_pClassName)
static ConsoleObject * create (const U32 groupId, const U32 typeId, const U32 in_classId)
static void addGroup (const char *in_pGroupname, const char *in_pGroupDocs=NULL)
Mark the beginning of a group of fields.
static void endGroup (const char *in_pGroupname)
Mark the end of a group of fields.
static void addArray (const char *arrayName, S32 count)
Marks the start of a fixed size array of fields.
static void endArray (const char *arrayName)
Marks the end of an array of fields.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a complex field.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::WriteDataNotify in_writeDataFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, const char *in_pFieldDocs, U32 flags=0)
Register a simple field.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::WriteDataNotify in_writeDataFn, const char *in_pFieldDocs, U32 flags=0)
static void addFieldV (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, TypeValidator *v, const char *in_pFieldDocs=NULL)
Register a validated field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, AbstractClassRep::WriteDataNotify in_writeDataFn=&defaultProtectedWriteFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a complex protected field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, AbstractClassRep::WriteDataNotify in_writeDataFn=&defaultProtectedWriteFn, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a simple protected field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addDeprecatedField (const char *fieldName)
Add a deprecated field.
static bool removeField (const char *in_pFieldname)
Remove a field.
static AbstractClassRep * getStaticClassRep ()
Get the abstract class information for this class.
static AbstractClassRep * getParentStaticClassRep ()
Get the abstract class information for this class's superclass.
static ConsoleObject * __findObject (const char *)
static const char * __getObjectId (ConsoleObject *)
Static Public Member Functions inherited from EngineObject
static void debugDumpInstances ()
Dump describeSelf()s of all live ConsoleObjects to the console.
static void debugEnumInstances (const std::type_info &type, DebugEnumInstancesCallback callback)
Call the given callback for all instances of the given type.
static void debugEnumInstances (const char *className, DebugEnumInstancesCallback callback)
Same as above but uses an export class name and also includes inheritance (i.e.
Protected Types
enum {
ZoneGroupMask = Parent::NextFreeMask << 0,
NextFreeMask = Parent::NextFreeMask << 1
}
Protected Types inherited from SceneSpace
enum {
TransformMask = Parent::NextFreeMask << 0,
NextFreeMask = Parent::NextFreeMask << 1
}
Protected Types inherited from NetObject
enum NetFlags {
IsGhost = BIT(1),
ScopeAlways = BIT(6),
ScopeLocal = BIT(7),
Ghostable = BIT(8),
MaxNetFlagBit = 15
}
Protected Types inherited from EngineObject
typedef ::FalseType __IsDisposableType
typedef ::FalseType __IsSingletonType
Protected Member Functions
virtual void onSceneRemove ()
Called when this is removed from its current SceneManager.
SceneManager Notifications
These methods are called when SceneManager assigns or removes objects to/from our zones.
virtual void _onZoneAddObject (SceneObject *object, const U32 *zoneIDs, U32 numZones)
Called by the SceneManager when an object is added to one or more zones that are managed by this object.
virtual void _onZoneRemoveObject (SceneObject *object)
Called by the SceneManager when an object that was previously added to one or more zones managed by this object is now removed.
Protected Member Functions inherited from SceneSpace
virtual BaseMatInstance * _createEditorRenderMaterial ()
virtual ColorI _getDefaultEditorSolidColor () const
virtual ColorI _getDefaultEditorWireframeColor () const
virtual void _renderObject (ObjectRenderInst *ri, SceneRenderState *state, BaseMatInstance *overrideMat)
Render a visualization of the volume.
Protected Member Functions inherited from SceneObject
virtual U32 getObjectFlagMax () const
Returns the greatest object flag bit defined.
virtual bool onSceneAdd ()
Called when this is added to a SceneManager.
void _updateZoningState () const
Refresh the zoning state of this object, if it isn't up-to-date anymore.
ZoneRef * _getZoneRefHead () const
Return the first link in the zone list of this object.
U32 _getNumCurrZones () const
Gets the number of zones containing this object.
U32 _getCurrZone (const U32 index) const
Returns the nth zone containing this object.
void resetWorldBox ()
Regenerates the world-space bounding box and bounding sphere.
void resetRenderWorldBox ()
Regenerates the render-world-space bounding box and sphere.
void resetObjectBox ()
Regenerates the object-space bounding box from the world-space bounding box, the world space to object space transform, and the object scale.
virtual void onScaleChanged ()
Called when the size of the object changes.
U32 getContainerSeqKey () const
Returns the container sequence key.
void setContainerSeqKey (const U32 key)
Sets the container sequence key.
Protected Member Functions inherited from SimSet
DECLARE_CALLBACK (void, onObjectAdded,(SimObject *object))
DECLARE_CALLBACK (void, onObjectRemoved,(SimObject *object))
Protected Member Functions inherited from SimObject
virtual void _destroySelf ()
Subclasses should overload this method instead of the public destroySelf().
virtual String _getLogMessage (const char *fmt, va_list args) const
We can provide more detail, like object name and id.
virtual void _onSelected ()
Called when the object is selected in the editor.
virtual void _onUnselected ()
Called when the object is unselected in the editor.
object incRefCount ()
virtual void onTamlAddParent (SimObject *pParentObject)
Called after Taml has finished reading the object and has added the object to any parent.
virtual void onTamlCustomRead (const TamlCustomNodes &customNodes)
Called during the reading of the object to allow custom properties to be read.
virtual void onTamlCustomWrite (TamlCustomNodes &customNodes)
Called during the writing of the object to allow custom properties to be written.
virtual void onTamlPostRead (const TamlCustomNodes &customNodes)
Called after Taml has finished reading the object.
virtual void onTamlPostWrite (void)
Called after Taml has finished writing the object.
virtual void onTamlPreRead (void)
Called prior to Taml reading the object.
virtual void onTamlPreWrite (void)
Taml callbacks.
object registerObject ()
void linkNamespaces ()
Perform namespace linking on this object.
void unlinkNamespaces ()
Undo namespace linking on this object.
Protected Member Functions inherited from ConsoleObject
ConsoleObject (const ConsoleObject &)
Protected Member Functions inherited from EngineObject
object incRefCount ()
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Protected Attributes
SceneZoneSpaceManager * mManager
The manager to which this zone space is registered.
U32 mNumZones
Number of zones managed by #obj.
BitSet32 mZoneFlags
U32 mZoneGroup
Group which the zone is assigned to.
U32 mZoneRangeStart
ID of first zone defined by object.
Protected Attributes inherited from SceneSpace
BaseMatInstance * mEditorRenderMaterial
Protected Attributes inherited from SceneObject
SimObjectPtr< SceneObject > mAfterObject
Object which must be ticked before this object.
SceneObjectLightingPlugin * mLightPlugin
SceneObjectLightingPlugin attached to this object.
BitSet32 mObjectFlags
Combination of SceneObjectFlags.
SceneManager * mSceneManager
SceneManager to which this SceneObject belongs.
SceneObjectLink * mSceneObjectLinks
Links installed by SceneTrackers attached to this object.
U32 mTypeMask
Object type mask.
MountInfo mMount
SimPersistID * mMountPID
bool mZoneRefDirty
If an object moves, its zoning state needs to be updated.
U32 mNumCurrZones
Number of zones this object is assigned to.
ZoneRef * mZoneRefHead
List of zones that this object is part of.
MatrixF mObjToWorld
Transform from object space to world space.
MatrixF mWorldToObj
Transform from world space to object space (inverse).
Point3F mObjScale
Object scale.
Box3F mObjBox
Bounding box in object space.
Box3F mWorldBox
Bounding box (AABB) in world space.
SphereF mWorldSphere
Bounding sphere in world space.
MatrixF mRenderObjToWorld
Render matrix to transform object space to world space.
MatrixF mRenderWorldToObj
Render matrix to transform world space to object space.
Box3F mRenderWorldBox
Render bounding box in world space.
SphereF mRenderWorldSphere
Render bounding sphere in world space.
bool mGlobalBounds
Whether this object is considered to have an infinite bounding box.
S32 mCollisionCount
SceneContainer * mContainer
Container database that the object is assigned to.
U32 mContainerSeqKey
SceneContainer sequence key.
SceneObjectRef * mBinRefHead
U32 mBinMinX
U32 mBinMaxX
U32 mBinMinY
U32 mBinMaxY
Protected Attributes inherited from NetObject
SimObjectPtr< NetObject > mClientObject
Pointer to the client object on a local connection.
GhostInfo * mFirstObjectRef
Head of a linked list storing GhostInfos referencing this NetObject.
BitSet32 mNetFlags
Flag values from NetFlags.
U32 mNetIndex
The index of this ghost in the GhostManager on the server.
SimObjectPtr< NetObject > mServerObject
Pointer to the server object on a local connection.
Protected Attributes inherited from SimSet
void * mMutex
SetModificationSignal mSetModificationSignal
Signal that is triggered when objects are added or removed from the set.
SimObjectList objectList
Protected Attributes inherited from SimObject
DEFINE_CREATE_METHOD
SimObjectId mId
Id number for this object.
StringTableEntry mInternalName
Internal name assigned to the object. Not set by default.
return object
bool mCanSaveFieldDictionary
Whether dynamic fields should be saved out in serialization. Defaults to true.
SimPersistID * mPersistentId
Persistent ID assigned to this object.
Namespace * mNameSpace
The namespace in which method lookup for this object begins.
StringTableEntry mClassName
Name of namespace to use as class namespace.
StringTableEntry mSuperClassName
Name of namespace to use as class super namespace.
Protected Attributes inherited from EngineObject
DEFINE_CREATE_METHOD
return object
Protected Attributes inherited from StrongRefBase
U32 mRefCount
reference counter for StrongRefPtr objects
Occluders
Zone spaces keep track of the occluders that get added to them so that during traversal, they can be taken on board as early as possible.
This allows traversals themselves to take occlusion into account.
Vector< SceneObject * > mOccluders
Occluders in this space.
void _addOccluder (SceneObject *object)
Add the given object to the list of occluders in this zone space.
void _removeOccluder (SceneObject *object)
Remove the given object from the list of occluders in this zone space.
void _addOccludersToCullingState (SceneCullingState *state) const
Register the occluders in this zone with the given culling state.
Zone Space Connectivity
ZoneSpaceRef * mConnectedZoneSpaces
List of zone spaces that this space is connected to.
static ClassChunker< ZoneSpaceRef > smZoneSpaceRefChunker
Allocator for ZoneSpaceRefs.
virtual void _disconnectAllZoneSpaces ()
Disconnect all zone spaces currently connected to this space.
virtual void _traverseConnectedZoneSpaces (SceneTraversalState *state)
Hand the traversal over to connected zone spaces.
virtual bool _automaticallyConnectZoneSpace (SceneZoneSpace *zoneSpace) const
Return true if the given zone space, which has crossed into this space, should be automatically connected.
Additional Inherited Members
Public Attributes inherited from SceneObject
GFXTextureObject * mAccuTex
bool mPathfindingIgnore
Public Attributes inherited from EngineObject
DECLARE_INSTANTIABLE
Public Attributes inherited from ProcessObject
bool mIsGameBase
U32 mOrderGUID
Link mProcessLink
U32 mProcessTag
bool mProcessTick
Static Public Attributes inherited from SceneObject
static Signal< void(SceneObject *) > smSceneObjectAdd
Triggered when a SceneObject onAdd is called.
static Signal< void(SceneObject *) > smSceneObjectRemove
Triggered when a SceneObject onRemove is called.
Static Public Attributes inherited from ConsoleObject
static const bool __smIsDatablock = false
Subclasses of ConsoleObjects that are datablocks should redefine this static member variable and set it to true.
Static Protected Member Functions inherited from SimObject
static bool _setPersistentID (void *object, const char *index, const char *data)
Static Protected Member Functions inherited from EngineObject
static void * _allocateObject (size_t size, IEngineObjectPool *pool TORQUE_TMM_ARGS_DECL)
Static Protected Attributes inherited from SimObject
static SimObjectId smForcedId
The Id to force upon the object. Poor object.
static bool smForceId
Force a registered object to use the given Id. Cleared upon use.
Detailed Description
Abstract base class for an object that manages zones in a scene.
This class adds the ability to SceneSpace to define and manage zones within the object's space. Zones are used to determine visibility in a scene.
Each zone space manages one or more zones in a scene. All the zones must be within the AABB of the zone space but within that AABB, the zone space is free to distribute and manage zones in arbitrary fashion.
For scene traversal, zone spaces are interconnected. By default, zone spaces get a chance to connect to each other when being moved into each other's zones. An exception to this is the root zone since it is both immobile and without position and (limited) extents. If a zone space wants to connect to the root zone, it must do so manually (same goes for disconnecting).
Member Typedef Documentation
typedef SceneSpace SceneZoneSpace::Parent
Member Enumeration Documentation
anonymous enum protected
Enumerator
ZoneGroupMask
NextFreeMask
anonymous enum
Enumerator
InvalidZoneGroup
enum SceneZoneSpace::ZoneFlags
Enumerator
ZoneFlag_IsClosedOffSpace
Whether this zoning space is "closed off" or not.
When connections between zoning spaces are established, by default only spaces that are closed off are connected to those that are not and vice versa. This defines a natural progression where spaces that explicitly want to propagate traversals are connected to those that want to contain it.
This flag is set by default.
Constructor & Destructor Documentation
SceneZoneSpace::SceneZoneSpace ()
virtual SceneZoneSpace::~SceneZoneSpace () virtual
Member Function Documentation
void SceneZoneSpace::_addOccluder (SceneObject * object) protected
Add the given object to the list of occluders in this zone space.
void SceneZoneSpace::_addOccludersToCullingState (SceneCullingState * state) const protected
Register the occluders in this zone with the given culling state.
virtual bool SceneZoneSpace::_automaticallyConnectZoneSpace (SceneZoneSpace * zoneSpace) const protected virtual
Return true if the given zone space, which has crossed into this space, should be automatically connected.
Note that event
virtual void SceneZoneSpace::_disconnectAllZoneSpaces () protected virtual
Disconnect all zone spaces currently connected to this space.
Reimplemented in Portal.
virtual void SceneZoneSpace::_onZoneAddObject (SceneObject * object, const U32 * zoneIDs, U32 numZones) protected virtual
Called by the SceneManager when an object is added to one or more zones that are managed by this object.
virtual void SceneZoneSpace::_onZoneRemoveObject (SceneObject * object) protected virtual
Called by the SceneManager when an object that was previously added to one or more zones managed by this object is now removed.
void SceneZoneSpace::_removeOccluder (SceneObject * object) protected
Remove the given object from the list of occluders in this zone space.
virtual void SceneZoneSpace::_traverseConnectedZoneSpaces (SceneTraversalState * state) protected virtual
Hand the traversal over to connected zone spaces.
Reimplemented in Portal.
virtual void SceneZoneSpace::connectZoneSpace (SceneZoneSpace * zoneSpace) virtual
Connect this zone space to the given zone space.
Parameters
zoneSpace A zone space.
Note
Connectivity is reset when a zone space is moved!
Reimplemented in Portal.
Referenced by getZoneAmbientLightColor().
virtual void SceneZoneSpace::disconnectZoneSpace (SceneZoneSpace * zoneSpace) virtual
If the object is a zone space, then this method is called to instruct the object to remove any zone connectivity to zoneSpace.
Parameters
zoneSpace A zone space which had previously been passed to connectZoneSpace().
Reimplemented in Portal.
Referenced by getZoneAmbientLightColor().
void SceneZoneSpace::dumpZoneState (bool update = true)
Dump a listing of all objects assigned to this zone space to the console as well as a list of all connected spaces.
Parameters
update Whether to update the zone contents before dumping. Since the zoning states of SceneObjects are updated lazily, the contents of a zone can be outdated.
Referenced by getZoneGroup().
virtual bool SceneZoneSpace::getOverlappingZones (const Box3F & aabb, U32 * zones, U32 & numZones) pure virtual
Implemented in SceneSimpleZone, ScenePolyhedralZone, and SceneRootZone.
Referenced by getZoneAmbientLightColor().
virtual bool SceneZoneSpace::getOverlappingZones (SceneObject * obj, U32 * outZones, U32 & outNumZones) virtual
Find the zones in this object that obj is part of.
Parameters
obj Object in question.
outZones Indices of zones containing the object. Must have at least as many entries as there as zones in this object or SceneObject::MaxObjectZones, whichever is smaller. Note that implementations should never write more than SceneObject::MaxObjectZones entries.
outNumZones Number of elements in the returned array.
Returns
Return true if the world box of obj is fully contained within the zones of this object or false if it is at least partially outside of them.
virtual U32 SceneZoneSpace::getPointZone (const Point3F & p) pure virtual
Returns the ID of the zone that are managed by this object that contains p.
Parameters
p Point to test.
Returns
ID of the zone containing p or InvalidZoneId if none of the zones defined by this object contain the point.
Implemented in SceneSimpleZone.
Referenced by getZoneAmbientLightColor().
virtual bool SceneZoneSpace::getZoneAmbientLightColor (U32 zone, ColorF & outColor) const inline virtual
Get the ambient light color of the given zone in this space or return false if the given zone does not have an ambient light color assigned to it.
Reimplemented in SceneSimpleZone.
References connectZoneSpace(), disconnectZoneSpace(), getOverlappingZones(), getPointZone(), initPersistFields(), packUpdate(), traverseZones(), unpackUpdate(), and writeField().
U32 SceneZoneSpace::getZoneGroup () const inline
Return the zone group that this zone space belongs to.
0 by default which means the zone space is not allocated to a specific zone group.
References dumpZoneState(), mZoneGroup, and setZoneGroup().
U32 SceneZoneSpace::getZoneRange () const inline
Return the number of zones that are managed by this object.
References mNumZones.
U32 SceneZoneSpace::getZoneRangeStart () const inline
Gets the index of the first zone this object manages in the collection of zones or 0xFFFFFFFF if the object is not managing zones.
References mZoneRangeStart.
Referenced by isRootZone().
static void SceneZoneSpace::initPersistFields () static
Referenced by getZoneAmbientLightColor().
bool SceneZoneSpace::isRootZone () const inline
Return true if this is the outdoor zone.
References getZoneRangeStart().
virtual void SceneZoneSpace::onSceneRemove () protected virtual
Called when this is removed from its current SceneManager.
Reimplemented from SceneObject.
Reimplemented in Portal, and SceneRootZone.
virtual U32 SceneZoneSpace::packUpdate (NetConnection * conn, U32 mask, BitStream * stream) virtual
Instructs this object to pack its state for transfer over the network.
Parameters
conn Net connection being used
mask Mask indicating fields to transmit.
stream Bitstream to pack data to
Returns
Any bits which were not dealt with. The value is stored by the networking system. Don't set bits you weren't passed.
Reimplemented from SceneSpace.
Reimplemented in Portal, SceneSimpleZone, ScenePolyhedralObject< SceneSimpleZone >, and SceneAmbientSoundObject< ScenePolyhedralZone >.
Referenced by getZoneAmbientLightColor().
void SceneZoneSpace::setZoneGroup (U32 group)
Set the zone group of this zone space.
Zone spaces in the same group will connect even if not connecting by default. Set to 0 to deactivate.
Referenced by getZoneGroup().
virtual void SceneZoneSpace::traverseZones (SceneTraversalState * state) pure virtual
Traverse into the zones of this space.
Set the render states of those zones and add the frustums that lead into them.
The traversal stack is expected to not be empty and the topmost entry on the stack should be the zone of another manager from which traversal is handed over to this manager.
Parameters
state Scene traversal state.
Note
If the zone's of a zone space are reached via different traversal paths, this method will be called multiple times on the same space.
Implemented in SceneSimpleZone.
Referenced by getZoneAmbientLightColor().
virtual void SceneZoneSpace::traverseZones (SceneTraversalState * state, U32 startZoneId) pure virtual
Traverse the zones in this space starting with the given zone.
Where appropriate, traversal should be handed off to connected spaces.
Parameters
state State which should be updated by the traversal.
startZoneId ID of zone in this manager in which to start traversal.
Implemented in Portal, and SceneSimpleZone.
virtual void SceneZoneSpace::unpackUpdate (NetConnection * conn, BitStream * stream) virtual
Instructs this object to read state data previously packed with packUpdate.
Parameters
conn Net connection being used
stream stream to read from
Reimplemented from SceneSpace.
Reimplemented in Portal, SceneSimpleZone, ScenePolyhedralObject< SceneSimpleZone >, and SceneAmbientSoundObject< ScenePolyhedralZone >.
Referenced by getZoneAmbientLightColor().
virtual bool SceneZoneSpace::writeField (StringTableEntry fieldname, const char * value) virtual
Determine whether or not a field should be written.
Parameters
fiedname The name of the field being written.
value The value of the field.
Reimplemented from SceneObject.
Reimplemented in Portal, and ScenePolyhedralObject< SceneSimpleZone >.
Referenced by getZoneAmbientLightColor().
Member Data Documentation
ZoneSpaceRef* SceneZoneSpace::mConnectedZoneSpaces protected
List of zone spaces that this space is connected to.
This is used for traversals.
SceneZoneSpaceManager* SceneZoneSpace::mManager protected
The manager to which this zone space is registered.
U32 SceneZoneSpace::mNumZones protected
Number of zones managed by #obj.
IDs are consecutive starting with mZoneRangeStart.
Referenced by getZoneRange().
Vector< SceneObject* > SceneZoneSpace::mOccluders protected
Occluders in this space.
Every object that is assigned to this space and has the OccluderObjectType flag set, is added to this list.
BitSet32 SceneZoneSpace::mZoneFlags protected
U32 SceneZoneSpace::mZoneGroup protected
Group which the zone is assigned to.
Zone spaces that would normally not connect do connect if they are assigned the same zone group. O to disable (default).
Referenced by getZoneGroup().
U32 SceneZoneSpace::mZoneRangeStart protected
ID of first zone defined by object.
Referenced by getZoneRangeStart().
ClassChunker< ZoneSpaceRef > SceneZoneSpace::smZoneSpaceRefChunker static protected
Allocator for ZoneSpaceRefs.
Copyright © GarageGames, LLC. All Rights Reserved.