GuiEditCtrl Class Reference
Main Modules Class List Namespace List Online
GuiEditCtrl Class Reference
Native side of the GUI editor.
#include <gui/editor/guiEditCtrl.h>
Public Types
enum guideAxis {
GuideVertical,
GuideHorizontal
}
enum Justification {
JUSTIFY_LEFT,
JUSTIFY_CENTER_VERTICAL,
JUSTIFY_RIGHT,
JUSTIFY_TOP,
JUSTIFY_BOTTOM,
SPACING_VERTICAL,
SPACING_HORIZONTAL,
JUSTIFY_CENTER_HORIZONTAL
}
enum mouseModes {
Selecting,
MovingSelection,
SizingSelection,
DragSelecting,
DragGuide,
DragClone
}
typedef GuiControl Parent
enum sizingModes {
sizingNone = 0,
sizingLeft = 1,
sizingRight = 2,
sizingTop = 4,
sizingBottom = 8
}
enum snappingAxis {
SnapVertical,
SnapHorizontal
}
enum snappingEdges {
SnapEdgeMin,
SnapEdgeMid,
SnapEdgeMax
}
Public Types inherited from GuiControl
enum { NoCheckParentCanSave = BIT(31) }
Additional write flags for GuiControls.
enum horizSizingOptions {
horizResizeRight = 0,
horizResizeWidth,
horizResizeLeft,
horizResizeCenter,
horizResizeRelative,
horizResizeAspectLeft,
horizResizeAspectRight,
horizResizeAspectCenter,
horizResizeWindowRelative
}
typedef SimGroup Parent
enum vertSizingOptions {
vertResizeBottom = 0,
vertResizeHeight,
vertResizeTop,
vertResizeCenter,
vertResizeRelative,
vertResizeAspectTop,
vertResizeAspectBottom,
vertResizeAspectCenter,
vertResizeWindowRelative
}
enum EHitTestFlags {
HIT_FullBoxOnly = BIT(0),
HIT_ParentPreventsChildHit = BIT(1),
HIT_AddParentHits = BIT(2),
HIT_NoCanHitNoRecurse = BIT(3)
}
Public Types inherited from SimGroup
typedef SimSet Parent
Public Types inherited from SimSet
typedef SimObject Parent
enum SetModification {
SetCleared,
SetObjectAdded,
SetObjectRemoved
}
typedef Signal< void(SetModification modification, SimSet *set, SimObject *object) > SetModificationSignal
Signal for letting observers know when objects are added to or removed from the set.
typedef SimObjectList::iterator iterator
typedef SimObjectList::value_type value
Public Types inherited from SimObject
typedef ConsoleObject Parent
enum WriteFlags {
SelectedOnly = BIT(0),
NoName = BIT(1),
IgnoreCanSave = BIT(2)
}
Flags passed to SimObject::write.
Public Types inherited from EngineObject
typedef void(* DebugEnumInstancesCallback) (EngineObject *)
Type of callback function for iterating over EngineObject instances.
Public Member Functions
GuiEditCtrl ()
U32 addGuide (guideAxis axis, U32 offset)
void addNewControl (GuiControl *ctrl)
void addSelectControlAt (const Point2I &pos)
void addSelectControlsInRegion (const RectI &rect, U32 hitTestFlags=0)
void addSelection (S32 id)
void addSelection (GuiControl *ctrl)
void bringToFront ()
void canHitSelectedControls (bool state=true)
void clearGuides (guideAxis axis)
void clearSelection ()
void cloneSelection ()
void controlInspectPostApply (GuiControl *object)
void controlInspectPreApply (GuiControl *object)
DECLARE_CATEGORY ("Gui Editor")
DECLARE_CONOBJECT (GuiEditCtrl)
DECLARE_DESCRIPTION ("Implements the framework for the GUI editor.")
void deleteSelection ()
void drawNut (const Point2I &nut, ColorI &outlineColor, ColorI &nutColor)
void drawNuts (RectI &box, ColorI &outlineColor, ColorI &nutColor)
void fitIntoParents (bool width=true, bool height=true)
GuiControl * getAddSet () const
GuiControl * getContentControl () const
GuiControl * getCurrentAddSet ()
void getCursor (GuiCursor *&cursor, bool &showCursor, const GuiEvent &lastGuiEvent)
Get information about the cursor.
void getDragRect (RectI &b)
mouseModes getMouseMode () const
U32 getNumSelected () const
const Vector< GuiControl * > & getSelected () const
SimSet * getSelectedSet ()
RectI getSelectionBounds () const
RectI getSelectionGlobalBounds () const
U32 getSelectionSize () const
S32 getSizingHitKnobs (const Point2I &pt, const RectI &box)
SimGroup * getTrash ()
void justifySelection (Justification j)
void loadSelection (const char *filename)
void moveAndSnapSelection (const Point2I &delta, bool callback=true)
void moveSelection (const Point2I &delta, bool callback=true)
void moveSelectionToCtrl (GuiControl *ctrl, bool callback=true)
virtual bool onAdd ()
Called when this object is added to the scene.
bool onKeyDown (const GuiEvent &event)
Happens when a key is depressed.
void onMouseDown (const GuiEvent &event)
void onMouseDragged (const GuiEvent &event)
void onMouseUp (const GuiEvent &event)
void onPreRender ()
Do special pre-render processing.
virtual void onRemove ()
Called when this object is removed.
void onRender (Point2I offset, const RectI &updateRect)
Called when this control is to render itself.
void onRightMouseDown (const GuiEvent &event)
void onSleep ()
Called when this object is asked to sleep.
bool onWake ()
Called when this object is asked to wake up returns true if it's actually awake at the end.
void pushToBack ()
void readGuides (guideAxis axis, GuiControl *ctrl)
void redo ()
void removeSelection (S32 id)
void removeSelection (GuiControl *ctrl)
void resizeControlsInSelectionBy (const Point2I &delta, U32 mode)
void saveSelection (const char *filename)
void select (GuiControl *ctrl)
void selectAll ()
void selectChildren (bool addToSelection=false)
bool selectionContains (GuiControl *ctrl)
bool selectionContainsParentOf (GuiControl *ctrl)
void selectParents (bool addToSelection=false)
void setContentControl (GuiControl *ctrl)
void setCurrentAddSet (GuiControl *ctrl, bool clearSelection=true)
void setEditMode (bool value)
void setSelection (GuiControl *ctrl, bool inclusive=false)
void setSnapToGrid (U32 gridsize)
void undo ()
void writeGuides (guideAxis axis, GuiControl *ctrl)
Public Member Functions inherited from GuiControl
void awaken ()
Called when this control and its children have been wired up.
U32 clipText (String &inOutText, U32 width) const
Returns text clipped to fit within a pixel width.
virtual bool controlIsChild (GuiControl *child)
Returns true if the provided control is a child (grandchild, or great-grandchild) of this one.
const char * getConsoleCommand ()
Returns the name of the function bound to this GuiControl.
GuiControlProfile * getControlProfile ()
Returns our profile (and finds the profile if it hasn't been set yet)
LangTable * getGUILangTable (void)
const UTF8 * getGUIString (S32 id)
RenderTooltipDelegate & getRenderTooltipDelegate ()
Return the delegate used to render tooltips on this control.
const RenderTooltipDelegate & getRenderTooltipDelegate () const
virtual void getScrollLineSizes (U32 *rowHeight, U32 *columnWidth)
Get information about the size of a scroll line.
String & getTooltip ()
Returns the tooltip.
GuiControlProfile * getTooltipProfile ()
Returns our tooltip profile (and finds the profile if it hasn't been set yet)
void inspectPostApply ()
Called after any property of the object is changed in the world editor.
void inspectPreApply ()
Called before any property of the object is changed in the world editor.
virtual void onAction ()
Occurs when this control performs its "action".
virtual bool onInputEvent (const InputEventInfo &event)
General input handler.
void preRender ()
Pre-render this control and all its children.
void renderJustifiedText (Point2I offset, Point2I extent, const char *text)
Renders justified text using the profile.
void setConsoleCommand (const String &newCmd)
Set the name of the console function bound to, such as a script function a button calls when clicked.
void setConsoleVariable (const char *variable)
Set the name of the console variable which this GuiObject is bound to.
void setControlProfile (GuiControlProfile *prof)
Sets the control profile for this control.
void setTooltipProfile (GuiControlProfile *prof)
Sets the tooltip profile for this control.
void sleep ()
Called when this control is no more.
void setSizing (S32 horz, S32 vert)
Sets the size of the GuiControl.
void write (Stream &stream, U32 tabStop, U32 flags)
Overrides Parent Serialization to allow specific controls to not be saved (Dynamic Controls, etc)
bool getCanSaveParent ()
Returns boolean as to whether any parent of this control has the 'no serialization' flag set.
const Point2I & getPosition () const
Returns position of the control.
const Point2I & getExtent () const
Returns extents of the control.
const RectI getBounds () const
Returns the bounds of the control.
const RectI getGlobalBounds ()
virtual Point2I getMinExtent () const
Returns minimum size the control can be.
virtual void setMinExtent (const Point2I &newMinExtent)
const S32 getLeft () const
Returns the X position of the control.
const S32 getTop () const
Returns the Y position of the control.
const S32 getWidth () const
Returns the width of the control.
const S32 getHeight () const
Returns the height of the control.
const S32 getHorizSizing () const
const S32 getVertSizing () const
virtual void setVisible (bool value)
Sets the visibility of the control.
bool isVisible () const
Returns true if the object is visible.
virtual bool isHidden () const
virtual void setHidden (bool state)
void setCanHit (bool value)
virtual void setActive (bool value)
Sets the status of this control as active and responding or inactive.
bool isActive ()
Returns true if this control is active.
bool isAwake ()
Returns true if this control is awake.
void addObject (SimObject *obj)
Adds an object as a child of this object.
void removeObject (SimObject *obj)
Removes a child object from this control.
GuiControl * getParent ()
Returns the control which owns this one.
GuiCanvas * getRoot ()
Returns the root canvas of this control.
virtual bool acceptsAsChild (SimObject *object) const
Return true if this set accepts the given object as a child.
virtual void onGroupRemove ()
Called when the object is removed from a SimGroup.
Point2I localToGlobalCoord (const Point2I &src)
Translates local coordinates (wrt this object) into global coordinates.
Point2I globalToLocalCoord (const Point2I &src)
Returns global coordinates translated into local space.
virtual bool resize (const Point2I &newPosition, const Point2I &newExtent)
Changes the size and/or position of this control.
virtual bool setPosition (const Point2I &newPosition)
Changes the position of this control.
void setPosition (const S32 x, const S32 y)
virtual bool setExtent (const Point2I &newExtent)
Changes the size of this control.
void setExtent (const S32 width, const S32 height)
virtual bool setBounds (const RectI &newBounds)
Changes the bounds of this control.
void setBounds (const S32 left, const S32 top, const S32 width, const S32 height)
virtual void setLeft (S32 newLeft)
Changes the X position of this control.
virtual void setTop (S32 newTop)
Changes the Y position of this control.
virtual void setWidth (S32 newWidth)
Changes the width of this control.
virtual void setHeight (S32 newHeight)
Changes the height of this control.
virtual void childResized (GuiControl *child)
Called when a child control of the object is resized.
virtual void parentResized (const RectI &oldParentRect, const RectI &newParentRect)
Called when this objects parent is resized.
void renderChildControls (Point2I offset, const RectI &updateRect)
Called when this control should render its children.
void setUpdateRegion (Point2I pos, Point2I ext)
Sets the area (local coordinates) this control wants refreshed each frame.
virtual void setUpdate ()
Sets the update area of the control to encompass the whole control.
virtual void onChildRemoved (GuiControl *child)
Called when one of this objects children is removed.
virtual void onDeleteNotify (SimObject *object)
Called when the mProfile or mToolTipProfile is deleted.
virtual void onChildAdded (GuiControl *child)
Called when this object has a new child.
virtual void onMouseMove (const GuiEvent &event)
virtual void onMouseEnter (const GuiEvent &event)
virtual void onMouseLeave (const GuiEvent &event)
virtual bool onMouseWheelUp (const GuiEvent &event)
virtual bool onMouseWheelDown (const GuiEvent &event)
virtual void onRightMouseUp (const GuiEvent &event)
virtual void onRightMouseDragged (const GuiEvent &event)
virtual void onMiddleMouseDown (const GuiEvent &event)
virtual void onMiddleMouseUp (const GuiEvent &event)
virtual void onMiddleMouseDragged (const GuiEvent &event)
virtual bool onGamepadButtonDown (const GuiEvent &event)
Default behavior is call-through to onKeyDown.
virtual bool onGamepadButtonUp (const GuiEvent &event)
Default behavior is call-through to onKeyUp.
virtual bool onGamepadAxisUp (const GuiEvent &event)
virtual bool onGamepadAxisDown (const GuiEvent &event)
virtual bool onGamepadAxisLeft (const GuiEvent &event)
virtual bool onGamepadAxisRight (const GuiEvent &event)
virtual bool onGamepadTrigger (const GuiEvent &event)
virtual bool onMouseDownEditor (const GuiEvent &event, Point2I offset)
Called when a mouseDown event occurs on a control and the GUI editor is active.
virtual bool onMouseUpEditor (const GuiEvent &event, Point2I offset)
Called when a mouseUp event occurs on a control and the GUI editor is active.
virtual bool onRightMouseDownEditor (const GuiEvent &event, Point2I offset)
Called when a rightMouseDown event occurs on a control and the GUI editor is active.
virtual bool onMouseDraggedEditor (const GuiEvent &event, Point2I offset)
Called when a mouseDragged event occurs on a control and the GUI editor is active.
virtual GuiControl * findFirstTabable ()
Find the first tab-accessible child of this control.
virtual GuiControl * findLastTabable (bool firstCall=true)
Find the last tab-accessible child of this control.
virtual GuiControl * findPrevTabable (GuiControl *curResponder, bool firstCall=true)
Find previous tab-accessible control with respect to the provided one.
virtual GuiControl * findNextTabable (GuiControl *curResponder, bool firstCall=true)
Find next tab-accessible control with regards to the provided control.
virtual void setFirstResponder (GuiControl *firstResponder)
Sets the first responder for child controls.
virtual void makeFirstResponder (bool value)
Sets up this control to be the first in it's group to respond to an input event.
bool isFirstResponder ()
Returns true if this control is a first responder.
virtual void setFirstResponder ()
Sets this object to be a first responder.
void clearFirstResponder ()
Clears the first responder for this chain.
GuiControl * getFirstResponder ()
Returns the first responder for this chain.
virtual void onGainFirstResponder ()
Occurs when the control gains first-responder status.
virtual void onLoseFirstResponder ()
Occurs when the control loses first-responder status.
void addAcceleratorKey ()
Adds the accelerator key for this object to the canvas.
virtual void buildAcceleratorMap ()
Adds this control's accelerator key to the accelerator map, and recursively tells all children to do the same.
virtual void acceleratorKeyPress (U32 index)
Occurs when the accelerator key for this control is pressed.
virtual void acceleratorKeyRelease (U32 index)
Occurs when the accelerator key for this control is released.
virtual bool onKeyUp (const GuiEvent &event)
Happens when a key is released.
virtual bool onKeyRepeat (const GuiEvent &event)
Happens when a key is held down, resulting in repeated keystrokes.
void messageSiblings (S32 message)
Send a message to all siblings.
virtual void onMessage (GuiControl *sender, S32 msg)
Receive a message from another control.
virtual void onDialogPush ()
Called if this object is a dialog, when it is added to the visible layers.
virtual void onDialogPop ()
Called if this object is a dialog, when it is removed from the visible layers.
virtual const char * getScriptValue ()
Returns the value of the variable bound to this object.
virtual void setScriptValue (const char *value)
Sets the value of the variable bound to this object.
const char * execConsoleCallback ()
Executes mConsoleCommand, and returns the result.
const char * execAltConsoleCallback ()
Executes mAltConsoleCommand, and returns the result.
DECLARE_CONOBJECT (GuiControl)
DECLARE_CATEGORY ("Gui Core")
DECLARE_DESCRIPTION ("Base class for GUI controls. Can also be used as a generic container.")
GuiControl ()
virtual ~GuiControl ()
virtual bool processArguments (S32 argc, ConsoleValueRef *argv)
Process constructor options. (ie, new SimObject(1,2,3))
virtual bool pointInControl (const Point2I &parentCoordPoint)
This function will return true if the provided coordinates (wrt parent object) are within the bounds of this control.
bool cursorInControl ()
Returns true if the global cursor is inside this control.
virtual GuiControl * findHitControl (const Point2I &pt, S32 initialLayer=-1)
Returns the control which the provided point is under, with layering.
virtual bool findHitControls (const RectI &rect, Vector< GuiControl * > &outResult, U32 flags=0, S32 initialLayer=-1, U32 depth=0)
void mouseLock (GuiControl *lockingControl)
Lock the mouse within the provided control.
void mouseLock ()
Turn on mouse locking with last used lock control.
void mouseUnlock ()
Unlock the mouse.
bool isMouseLocked ()
Returns true if the mouse is locked.
Public Member Functions inherited from SimGroup
~SimGroup ()
void addObject (SimObject *object, SimObjectId id)
void addObject (SimObject *object, const char *name)
virtual void clear ()
Remove all objects from this set.
virtual SimGroup * clone ()
Return a shallow copy of this object.
DECLARE_CONOBJECT (SimGroup)
virtual SimGroup * deepClone ()
Return a deep copy of this object.
virtual SimObject * findObject (const char *name)
Find a named sub-object of this object.
virtual void popObject ()
Remove an object from the end of the list.
virtual void pushObject (SimObject *object)
Add the given object to the end of the object list of this set.
Public Member Functions inherited from SimSet
SimSet ()
~SimSet ()
virtual void addTamlChild (SimObject *pSimObject)
Called when Taml attempts to populate an objects children during a read.
void callOnChildren (const String &method, S32 argc, ConsoleValueRef argv[], bool executeOnChildGroups=true)
DECLARE_CONOBJECT (SimSet)
SimObject * findObject (SimObject *object)
Find the given object in this set.
template<class T >
void findObjectByCallback (bool(*fn)(T *), Vector< T * > &foundObjects)
Add all child objects (including children of children) to the foundObjects Vector which are of type T and for which DecideAddObjectCallback return true;.
virtual SimObject * findObjectByInternalName (StringTableEntry internalName, bool searchChildren=false)
SimObject * findObjectByLineNumber (const char *fileName, S32 declarationLine, bool searchChildren=false)
template<class T >
void findObjectByType (Vector< T * > &foundObjects)
Add all child objects (including children of children) to the foundObjects Vector which are of type T.
SimObject * getRandom ()
const SetModificationSignal & getSetModificationSignal () const
Return the signal that is triggered when an object is added to or removed from the set.
SetModificationSignal & getSetModificationSignal ()
virtual SimObject * getTamlChild (const U32 childIndex) const
Called when Taml attempts to compile a list of children.
virtual U32 getTamlChildCount (void) const
Called when Taml attempts to compile a list of children.
void lock ()
virtual bool readObject (Stream *stream)
U32 sizeRecursive ()
Return the number of objects in this set as well as all sets that are contained in this set and its children.
void unlock ()
virtual bool writeObject (Stream *stream)
void deleteAllObjects ()
Deletes all the objects in the set.
void bringObjectToFront (SimObject *obj)
void pushObjectToBack (SimObject *obj)
void scriptSort (const String &scriptCallbackFn)
Performs a sort of the objects in the set using a script callback function to do the comparison.
SimObject * front ()
SimObject * first ()
SimObject * last ()
bool empty () const
S32 size () const
iterator begin ()
iterator end ()
value operator[] (S32 index)
iterator find (iterator first, iterator last, SimObject *obj)
iterator find (SimObject *obj)
virtual bool reOrder (SimObject *obj, SimObject *target=0)
Reorder the position of "obj" to either be the last object in the list or, if "target" is given, to come before "target" in the list of children.
SimObject * at (S32 index) const
Return the object at the given index.
Public Member Functions inherited from SimObject
virtual void copyTo (SimObject *object)
Copy SimObject to another SimObject (Originally designed for T2D).
DECLARE_CONOBJECT (SimObject)
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
virtual void getConsoleMethodData (const char *fname, S32 routingId, S32 *type, S32 *minArgs, S32 *maxArgs, void **callback, const char **usage)
Namespace * getNamespace ()
Return the object's namespace.
StringTableEntry getProgenitorFile (void) const
virtual bool handlesConsoleMethod (const char *fname, S32 *routingId)
void setProgenitorFile (const char *pFile)
const char * tabComplete (const char *prevText, S32 baseLen, bool)
Get next matching item in namespace.
virtual bool writeField (StringTableEntry fieldname, const char *value)
Determine whether or not a field should be written.
virtual void writeFields (Stream &stream, U32 tabStop)
Write the fields of this object in TorqueScript.
void setCanSaveDynamicFields (bool bCanSave)
Set whether fields created at runtime should be saved. Default is true.
bool getCanSaveDynamicFields ()
Get whether fields created at runtime should be saved. Default is true.
SimObject * getCopySource () const
Return the object that this object is copying fields from.
void setCopySource (SimObject *object)
Set the object that this object should be copying fields from.
void assignFieldsFrom (SimObject *obj)
Copy fields from another object onto this one.
void assignDynamicFieldsFrom (SimObject *obj)
Copy dynamic fields from another object onto this one.
Notify * removeNotify (void *ptr, Notify::Type)
Remove a notification from the list.
void deleteNotify (SimObject *obj)
Notify an object when we are deleted.
void clearNotify (SimObject *obj)
Notify an object when we are cleared.
void clearAllNotifications ()
Remove all notifications for this object.
void processDeleteNotifies ()
Send out deletion notifications.
void registerReference (SimObject **obj)
Register a reference to this object.
void unregisterReference (SimObject **obj)
Unregister a reference to this object.
SimPersistID * getPersistentId () const
Return the persistent ID assigned to this object or NULL.
SimPersistID * getOrCreatePersistentId ()
Return the persistent ID assigned to this object or assign one to it if it has none.
StringTableEntry getClassNamespace () const
Return name of class namespace set on this object.
StringTableEntry getSuperClassNamespace () const
Return name of superclass namespace set on this object.
void setClassNamespace (const char *classNamespace)
void setSuperClassNamespace (const char *superClassNamespace)
const char * getDataField (StringTableEntry slotName, const char *array)
Get the value of a field on the object.
void setDataField (StringTableEntry slotName, const char *array, const char *value)
Set the value of a field on the object.
const char * getPrefixedDataField (StringTableEntry fieldName, const char *array)
void setPrefixedDataField (StringTableEntry fieldName, const char *array, const char *value)
const char * getPrefixedDynamicDataField (StringTableEntry fieldName, const char *array, const S32 fieldType=-1)
void setPrefixedDynamicDataField (StringTableEntry fieldName, const char *array, const char *value, const S32 fieldType=-1)
StringTableEntry getDataFieldPrefix (StringTableEntry fieldName)
U32 getDataFieldType (StringTableEntry slotName, const char *array)
Get the type of a field on the object.
void setDataFieldType (const U32 fieldTypeId, StringTableEntry slotName, const char *array)
Set the type of a dynamic field on the object.
void setDataFieldType (const char *typeName, StringTableEntry slotName, const char *array)
SimFieldDictionary * getFieldDictionary ()
Get reference to the dictionary containing dynamic fields.
virtual StringTableEntry getComponentName ()
void setInternalName (const char *newname)
These functions support internal naming that is not namespace bound for locating child controls in a generic way.
StringTableEntry getInternalName () const
Get the internal name of this control.
void setOriginalName (const char *originalName)
Set the original name of this control.
StringTableEntry getOriginalName () const
Get the original name of this control.
void setFilename (const char *file)
These functions allow you to set and access the filename where this object was created.
StringTableEntry getFilename () const
Get the filename.
void setDeclarationLine (U32 lineNumber)
These functions are used to track the line number (1-based) on which the object was created if it was loaded from script.
S32 getDeclarationLine () const
Get the declaration line number.
virtual bool save (const char *pcFilePath, bool bOnlySelected=false, const char *preappend=NULL)
Save object as a TorqueScript File.
virtual bool isMethod (const char *methodName)
Check if a method exists in the objects current namespace.
virtual bool isField (const char *fieldName, bool includeStatic=true, bool includeDynamic=true)
Return true if the field is defined on the object.
SimObjectId getId () const
Return the unique numeric object ID.
const char * getIdString () const
Return the object ID as a string.
StringTableEntry getName () const
Return the name of this object.
SimGroup * getGroup () const
Return the SimGroup that this object is contained in.
void assignName (const char *name)
Assign the given name to this object.
void setId (SimObjectId id)
bool isChildOfGroup (SimGroup *pGroup)
bool isProperlyAdded () const
bool isDeleted () const
bool isRemoved () const
virtual bool isLocked () const
virtual void setLocked (bool b)
bool isSelected () const
bool isExpanded () const
bool isEditorOnly () const
bool isNameChangeAllowed () const
bool isAutoDeleted () const
void setSelected (bool sel)
void setExpanded (bool exp)
void setModDynamicFields (bool dyn)
void setModStaticFields (bool sta)
bool canModDynamicFields ()
bool canModStaticFields ()
void setAutoDelete (bool val)
void setEditorOnly (bool val)
void setNameChangeAllowed (bool val)
bool getCanSave () const
Returns boolean specifying if the object can be serialized.
virtual void setCanSave (bool val)
Set serialization flag.
bool isSelectedRecursive () const
Returns true if this object is selected or any group it is a member of is.
SimObject ()
virtual ~SimObject ()
virtual void onGroupAdd ()
Called when the object is added to a SimGroup.
virtual void onNameChange (const char *name)
Called when the object's name is changed.
virtual void onPostAdd ()
Called when the adding of the object to the sim is complete, all sub-objects have been processed as well.
virtual void onStaticModified (const char *slotName, const char *newValue=NULL)
Specifically, these are called by setDataField when a static or dynamic field is modified, see the console details.
virtual void onDynamicModified (const char *slotName, const char *newValue=NULL)
Called when a dynamic field is modified.
virtual void onEditorEnable ()
Called when the editor is activated.
virtual void onEditorDisable ()
Called when the editor is deactivated.
bool registerObject ()
Register an object with the object system.
bool registerObject (U32 id)
Register the object, forcing the id.
bool registerObject (const char *name)
Register the object, assigning the name.
bool registerObject (const char *name, U32 id)
Register the object, assigning a name and ID.
void unregisterObject ()
Unregister the object from Sim.
void deleteObject ()
Unregister, mark as deleted, and free the object.
void safeDeleteObject ()
Performs a safe delayed delete of the object using a sim event.
bool addToSet (SimObjectId)
bool addToSet (const char *)
bool removeFromSet (SimObjectId)
bool removeFromSet (const char *)
virtual String describeSelf () const
Return a textual description of the object.
void dumpToConsole (bool includeFunctions=true)
Dump the contents of this object to the console.
virtual void dumpClassHierarchy ()
added this so that you can print the entire class hierarchy, including script objects,
virtual void dumpGroupHierarchy ()
Print the SimGroup hierarchy of this object to the console.
Public Member Functions inherited from ConsoleObject
ConsoleObject ()
virtual AbstractClassRep * getClassRep () const
Gets the ClassRep.
const AbstractClassRep::Field * findField (StringTableEntry fieldName) const
Get a reference to a field by name.
bool setField (const char *fieldName, const char *value)
Set the value of a field.
void logMessage (const char *fmt,...) const
Logs with Con::printf.
void logWarning (const char *fmt,...) const
Logs with Con::warnf.
void logError (const char *fmt,...) const
Logs with Con::errorf.
const AbstractClassRep::FieldList & getFieldList () const
Get a list of all the fields. This information cannot be modified.
AbstractClassRep::FieldList & getModifiableFieldList ()
Get a list of all the fields, set up so we can modify them.
bool & getDynamicGroupExpand ()
Get a handle to a boolean telling us if we expanded the dynamic group.
S32 getClassId (U32 netClassGroup) const
Get our network-layer class id.
StringTableEntry getClassName () const
Get our compiler and platform independent class name.
Public Member Functions inherited from EngineObject
EngineObject ()
virtual ~EngineObject ()
DECLARE_ABSTRACT_CLASS (EngineObject, void)
DECLARE_INSCOPE (_GLOBALSCOPE)
IEngineObjectPool * getEngineObjectPool () const
Return the pool of EngineObjects to which this object belongs.
void operator delete (void *ptr)
Release the given object's memory in the pool it has been allocated from.
void * operator new (size_t size)
void * operator new (size_t size, IEngineObjectPool *pool)
void * operator new (size_t size TORQUE_TMM_ARGS_DECL)
Allocate a new object in the default object pool.
void * operator new (size_t size, IEngineObjectPool *pool TORQUE_TMM_ARGS_DECL)
Allocate a new object in the given object pool.
void * operator new (size_t size, void *ptr)
Placement new.
Public Member Functions inherited from StrongRefBase
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Static Public Member Functions
static void initPersistFields ()
Static Public Member Functions inherited from GuiControl
static bool _setActive (void *object, const char *index, const char *data)
static bool _setVisible (void *object, const char *index, const char *data)
static void initPersistFields ()
static void consoleInit ()
Static Public Member Functions inherited from SimObject
static SimObject * __findObject (const char *id)
static const char * __getObjectId (ConsoleObject *object)
static void initPersistFields ()
static void setForcedId (SimObjectId id)
Force an Id on the next registered object.
Static Public Member Functions inherited from ConsoleObject
static const char * __category ()
static const char * __description ()
static void consoleInit ()
Register global constant variables and do other one-time initialization tasks in a subclass of ConsoleObject.
static void initPersistFields ()
Register dynamic fields in a subclass of ConsoleObject.
static const char * lookupClassName (const U32 in_classTag)
Get the classname from a class tag.
static ConsoleObject * create (const char *in_pClassName)
static ConsoleObject * create (const U32 groupId, const U32 typeId, const U32 in_classId)
static void addGroup (const char *in_pGroupname, const char *in_pGroupDocs=NULL)
Mark the beginning of a group of fields.
static void endGroup (const char *in_pGroupname)
Mark the end of a group of fields.
static void addArray (const char *arrayName, S32 count)
Marks the start of a fixed size array of fields.
static void endArray (const char *arrayName)
Marks the end of an array of fields.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a complex field.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::WriteDataNotify in_writeDataFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, const char *in_pFieldDocs, U32 flags=0)
Register a simple field.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::WriteDataNotify in_writeDataFn, const char *in_pFieldDocs, U32 flags=0)
static void addFieldV (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, TypeValidator *v, const char *in_pFieldDocs=NULL)
Register a validated field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, AbstractClassRep::WriteDataNotify in_writeDataFn=&defaultProtectedWriteFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a complex protected field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, AbstractClassRep::WriteDataNotify in_writeDataFn=&defaultProtectedWriteFn, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a simple protected field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addDeprecatedField (const char *fieldName)
Add a deprecated field.
static bool removeField (const char *in_pFieldname)
Remove a field.
static AbstractClassRep * getStaticClassRep ()
Get the abstract class information for this class.
static AbstractClassRep * getParentStaticClassRep ()
Get the abstract class information for this class's superclass.
static ConsoleObject * __findObject (const char *)
static const char * __getObjectId (ConsoleObject *)
Static Public Member Functions inherited from EngineObject
static void debugDumpInstances ()
Dump describeSelf()s of all live ConsoleObjects to the console.
static void debugEnumInstances (const std::type_info &type, DebugEnumInstancesCallback callback)
Call the given callback for all instances of the given type.
static void debugEnumInstances (const char *className, DebugEnumInstancesCallback callback)
Same as above but uses an export class name and also includes inheritance (i.e.
Protected Types
enum {
NUT_SIZE = 4,
MIN_GRID_SIZE = 3
}
typedef SimObjectPtr< GuiControl > GuiControlPtr
typedef Vector< GuiControl * > GuiControlVector
Protected Types inherited from GuiControl
typedef Vector< Vector< GuiWindowCtrl * > > CollapseGroupVec
Protected Types inherited from EngineObject
typedef ::FalseType __IsDisposableType
typedef ::FalseType __IsSingletonType
Protected Member Functions
void doControlSnap (const GuiEvent &event, const RectI &selectionBounds, const RectI &selectionBoundsGlobal, Point2I &delta)
void doGridSnap (const GuiEvent &event, const RectI &selectionBounds, const RectI &selectionBoundsGlobal, Point2I &delta)
void doGuideSnap (const GuiEvent &event, const RectI &selectionBounds, const RectI &selectionBoundsGlobal, Point2I &delta)
void doSnapping (const GuiEvent &event, const RectI &selectionBounds, Point2I &delta)
S32 findGuide (guideAxis axis, const Point2I &point, U32 tolerance=0)
void findSnaps (snappingAxis axis, const Point2I &mousePoint, const RectI &minRegion, const RectI &midRegion, const RectI &maxRegion)
RectI getSnapRegion (snappingAxis axis, const Point2I &center) const
void registerSnap (snappingAxis axis, const Point2I &mousePoint, const Point2I &point, snappingEdges edge, GuiControl *ctrl=NULL)
void setMouseMode (mouseModes mode)
void snapToGrid (Point2I &point)
void startDragClone (const Point2I &startPoint)
void startDragMove (const Point2I &startPoint)
void startDragRectangle (const Point2I &startPoint)
void startMouseGuideDrag (guideAxis axis, U32 index, bool lockMouse=true)
void updateSelectedSet ()
Callbacks
DECLARE_CALLBACK (void, onHierarchyChanged,())
DECLARE_CALLBACK (void, onDelete,())
DECLARE_CALLBACK (void, onPreEdit,(SimSet *selection))
DECLARE_CALLBACK (void, onPostEdit,(SimSet *selection))
DECLARE_CALLBACK (void, onClearSelected,())
DECLARE_CALLBACK (void, onSelect,(GuiControl *control))
DECLARE_CALLBACK (void, onAddSelected,(GuiControl *control))
DECLARE_CALLBACK (void, onRemoveSelected,(GuiControl *control))
DECLARE_CALLBACK (void, onPreSelectionNudged,(SimSet *selection))
DECLARE_CALLBACK (void, onPostSelectionNudged,(SimSet *selection))
DECLARE_CALLBACK (void, onSelectionMoved,(GuiControl *control))
DECLARE_CALLBACK (void, onSelectionCloned,(SimSet *selection))
DECLARE_CALLBACK (void, onTrashSelection,(SimSet *selection))
DECLARE_CALLBACK (void, onAddNewCtrl,(GuiControl *control))
DECLARE_CALLBACK (void, onAddNewCtrlSet,(SimSet *set))
DECLARE_CALLBACK (void, onSelectionResized,(GuiControl *control))
DECLARE_CALLBACK (void, onFitIntoParent,(bool width, bool height))
DECLARE_CALLBACK (void, onMouseModeChange,())
DECLARE_CALLBACK (void, onControlInspectPreApply,(GuiControl *control))
DECLARE_CALLBACK (void, onControlInspectPostApply,(GuiControl *control))
Protected Member Functions inherited from GuiControl
bool defaultTooltipRender (const Point2I &hoverPos, const Point2I &cursorPos, const char *tipText=NULL)
The default tooltip rendering function.
const char * evaluate (const char *str)
Set $ThisControl and evaluate the given script code.
void setVariable (const char *value)
Sets the value of the console variable bound to this control.
void setIntVariable (S32 value)
Sets the value of the console variable bound to this control.
void setFloatVariable (F32 value)
Sets the value of the console variable bound to this control.
const char * getVariable ()
Returns value of control's bound variable as a string.
S32 getIntVariable ()
Returns value of control's bound variable as a integer.
F32 getFloatVariable ()
Returns value of control's bound variable as a float.
DECLARE_CALLBACK (void, onAdd,())
DECLARE_CALLBACK (void, onRemove,())
DECLARE_CALLBACK (void, onWake,())
DECLARE_CALLBACK (void, onSleep,())
DECLARE_CALLBACK (void, onLoseFirstResponder,())
DECLARE_CALLBACK (void, onGainFirstResponder,())
DECLARE_CALLBACK (void, onAction,())
DECLARE_CALLBACK (void, onVisible,(bool state))
DECLARE_CALLBACK (void, onActive,(bool state))
DECLARE_CALLBACK (void, onDialogPush,())
DECLARE_CALLBACK (void, onDialogPop,())
DECLARE_CALLBACK (void, onControlDragEnter,(GuiControl *control, const Point2I &dropPoint))
DECLARE_CALLBACK (void, onControlDragExit,(GuiControl *control, const Point2I &dropPoint))
DECLARE_CALLBACK (void, onControlDragged,(GuiControl *control, const Point2I &dropPoint))
DECLARE_CALLBACK (void, onControlDropped,(GuiControl *control, const Point2I &dropPoint))
Protected Member Functions inherited from SimSet
DECLARE_CALLBACK (void, onObjectAdded,(SimObject *object))
DECLARE_CALLBACK (void, onObjectRemoved,(SimObject *object))
Protected Member Functions inherited from SimObject
virtual void _destroySelf ()
Subclasses should overload this method instead of the public destroySelf().
virtual String _getLogMessage (const char *fmt, va_list args) const
We can provide more detail, like object name and id.
virtual void _onSelected ()
Called when the object is selected in the editor.
virtual void _onUnselected ()
Called when the object is unselected in the editor.
object incRefCount ()
virtual void onTamlAddParent (SimObject *pParentObject)
Called after Taml has finished reading the object and has added the object to any parent.
virtual void onTamlCustomRead (const TamlCustomNodes &customNodes)
Called during the reading of the object to allow custom properties to be read.
virtual void onTamlCustomWrite (TamlCustomNodes &customNodes)
Called during the writing of the object to allow custom properties to be written.
virtual void onTamlPostRead (const TamlCustomNodes &customNodes)
Called after Taml has finished reading the object.
virtual void onTamlPostWrite (void)
Called after Taml has finished writing the object.
virtual void onTamlPreRead (void)
Called prior to Taml reading the object.
virtual void onTamlPreWrite (void)
Taml callbacks.
object registerObject ()
void linkNamespaces ()
Perform namespace linking on this object.
void unlinkNamespaces ()
Undo namespace linking on this object.
Protected Member Functions inherited from ConsoleObject
ConsoleObject (const ConsoleObject &)
Protected Member Functions inherited from EngineObject
object incRefCount ()
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Static Protected Member Functions
static void drawCrossSection (U32 axis, S32 offset, const RectI &bounds, ColorI color, GFXDrawUtil *drawer)
static bool inNut (const Point2I &pt, S32 x, S32 y)
static void snapDelta (snappingAxis axis, snappingEdges edge, S32 offset, const RectI &bounds, Point2I &delta)
Static Protected Member Functions inherited from GuiControl
static bool setProfileProt (void *object, const char *index, const char *data)
static bool setTooltipProfileProt (void *object, const char *index, const char *data)
Static Protected Member Functions inherited from SimObject
static bool _setPersistentID (void *object, const char *index, const char *data)
Static Protected Member Functions inherited from EngineObject
static void * _allocateObject (size_t size, IEngineObjectPool *pool TORQUE_TMM_ARGS_DECL)
Protected Attributes
GuiControlPtr mContentControl
GuiControlPtr mCurrentAddSet
GFXVertexBufferHandle< GFXVertexPCT > mDots
GFXStateBlockRef mDotSB
bool mDragAddSelection
Point2I mDragBeginPoint
Vector< Point2I > mDragBeginPoints
bool mDragGuide [2]
U32 mDragGuideIndex [2]
Indices of the guide's being dragged in DragGuide mouse mode.
bool mDragMoveUndo
bool mDrawBorderLines
bool mDrawGuides
bool mFullBoxSelection
Point2I mGridSnap
Vector< U32 > mGuides [2]
The guides defined on the current content control.
Point2I mLastDragPos
Point2I mLastMousePos
mouseModes mMouseDownMode
GuiControlVector mSelectedControls
SimSet * mSelectedSet
Point2I mSelectionAnchor
sizingModes mSizingMode
snappingEdges mSnapEdge [2]
Identification of edge being snapped for each axis.
GuiControlVector mSnapHits [2]
Hit testing lists for each axis.
S32 mSnapOffset [2]
Reference point on snap line for each axis.
bool mSnapped [2]
Snap flag for each axis. If true, we are currently snapped in a drag.
S32 mSnapSensitivity
Snap distance in pixels.
GuiControlPtr mSnapTargets [2]
Controls providing the snap reference lines on each axis.
bool mSnapToCanvas
If true, edge and center snapping will work against canvas (= content control).
bool mSnapToCenters
If true, selection centers will snap to other control centers.
bool mSnapToControls
If true, edge and center snapping will work against controls.
bool mSnapToEdges
If true, selection edges will snap to other control edges.
bool mSnapToGuides
If true, edge and center snapping will work against guides.
SimGroup * mTrash
Protected Attributes inherited from GuiControl
GuiControlProfile * mProfile
The profile for this gui (data settings that are likely to be shared by multiple guis)
GuiControlProfile * mTooltipProfile
The profile for any tooltips.
S32 mTipHoverTime
RenderTooltipDelegate mRenderTooltipDelegate
Delegate called to render a tooltip for this control.
bool mVisible
bool mActive
bool mAwake
bool mSetFirstResponder
bool mIsContainer
if true, then the GuiEditor can drag other controls into this one.
bool mCanResize
bool mCanHit
S32 mLayer
Point2I mMinExtent
StringTableEntry mLangTableName
LangTable * mLangTable
bool mNotifyChildrenResized
CollapseGroupVec mCollapseGroupVec
S32 mHorizSizing
Set from horizSizingOptions.
S32 mVertSizing
Set from vertSizingOptions.
StringTableEntry mAcceleratorKey
StringTableEntry mConsoleVariable
String mConsoleCommand
String mAltConsoleCommand
String mTooltip
GuiControl * mFirstResponder
GFXStateBlockRef mDefaultGuiSB
Protected Attributes inherited from SimSet
void * mMutex
SetModificationSignal mSetModificationSignal
Signal that is triggered when objects are added or removed from the set.
SimObjectList objectList
Protected Attributes inherited from SimObject
DEFINE_CREATE_METHOD
SimObjectId mId
Id number for this object.
StringTableEntry mInternalName
Internal name assigned to the object. Not set by default.
return object
bool mCanSaveFieldDictionary
Whether dynamic fields should be saved out in serialization. Defaults to true.
SimPersistID * mPersistentId
Persistent ID assigned to this object.
Namespace * mNameSpace
The namespace in which method lookup for this object begins.
StringTableEntry mClassName
Name of namespace to use as class namespace.
StringTableEntry mSuperClassName
Name of namespace to use as class super namespace.
Protected Attributes inherited from EngineObject
DEFINE_CREATE_METHOD
return object
Protected Attributes inherited from StrongRefBase
U32 mRefCount
reference counter for StrongRefPtr objects
Static Protected Attributes
static StringTableEntry smGuidesPropertyName [2]
Static Protected Attributes inherited from GuiControl
static GuiEditCtrl * smEditorHandle
static GuiEditCtrl pointer that gives controls access to editor-NULL if editor is closed
static bool smDesignTime
static GuiControl boolean that specifies if the GUI Editor is active
static GuiControl * smPrevResponder
static GuiControl * smCurResponder
static GuiControl * smThisControl
$ThisControl variable for callback execution.
Static Protected Attributes inherited from SimObject
static SimObjectId smForcedId
The Id to force upon the object. Poor object.
static bool smForceId
Force a registered object to use the given Id. Cleared upon use.
Additional Inherited Members
Public Attributes inherited from EngineObject
DECLARE_INSTANTIABLE
Static Public Attributes inherited from ConsoleObject
static const bool __smIsDatablock = false
Subclasses of ConsoleObjects that are datablocks should redefine this static member variable and set it to true.
Detailed Description
Native side of the GUI editor.
Member Typedef Documentation
typedef SimObjectPtr< GuiControl > GuiEditCtrl::GuiControlPtr protected
typedef Vector< GuiControl* > GuiEditCtrl::GuiControlVector protected
typedef GuiControl GuiEditCtrl::Parent
Member Enumeration Documentation
anonymous enum protected
Enumerator
NUT_SIZE
MIN_GRID_SIZE
enum GuiEditCtrl::guideAxis
Enumerator
GuideVertical
GuideHorizontal
enum GuiEditCtrl::Justification
Enumerator
JUSTIFY_LEFT
JUSTIFY_CENTER_VERTICAL
JUSTIFY_RIGHT
JUSTIFY_TOP
JUSTIFY_BOTTOM
SPACING_VERTICAL
SPACING_HORIZONTAL
JUSTIFY_CENTER_HORIZONTAL
enum GuiEditCtrl::mouseModes
Enumerator
Selecting
MovingSelection
SizingSelection
DragSelecting
DragGuide
DragClone
enum GuiEditCtrl::sizingModes
Enumerator
sizingNone
sizingLeft
sizingRight
sizingTop
sizingBottom
enum GuiEditCtrl::snappingAxis
Enumerator
SnapVertical
SnapHorizontal
enum GuiEditCtrl::snappingEdges
Enumerator
SnapEdgeMin
SnapEdgeMid
SnapEdgeMax
Constructor & Destructor Documentation
GuiEditCtrl::GuiEditCtrl ()
Referenced by snapDelta().
Member Function Documentation
U32 GuiEditCtrl::addGuide (guideAxis axis, U32 offset) inline
References Vector< T >::push_back(), readGuides(), Vector< T >::size(), and writeGuides().
void GuiEditCtrl::addNewControl (GuiControl * ctrl)
Referenced by getContentControl().
void GuiEditCtrl::addSelectControlAt (const Point2I & pos)
Referenced by getContentControl().
void GuiEditCtrl::addSelectControlsInRegion (const RectI & rect, U32 hitTestFlags = 0)
Referenced by getContentControl().
void GuiEditCtrl::addSelection (S32 id)
Referenced by getContentControl().
void GuiEditCtrl::addSelection (GuiControl * ctrl)
void GuiEditCtrl::bringToFront ()
Referenced by getContentControl().
void GuiEditCtrl::canHitSelectedControls (bool state = true)
Referenced by getContentControl().
void GuiEditCtrl::clearGuides (guideAxis axis) inline
References Vector< T >::clear(), controlInspectPostApply(), controlInspectPreApply(), getCursor(), redo(), and undo().
void GuiEditCtrl::clearSelection ()
Referenced by getContentControl().
void GuiEditCtrl::cloneSelection ()
Referenced by getContentControl().
void GuiEditCtrl::controlInspectPostApply (GuiControl * object)
Referenced by clearGuides().
void GuiEditCtrl::controlInspectPreApply (GuiControl * object)
Referenced by clearGuides().
GuiEditCtrl::DECLARE_CALLBACK (void , onHierarchyChanged , ()) protected
GuiEditCtrl::DECLARE_CALLBACK (void , onDelete , ()) protected
GuiEditCtrl::DECLARE_CALLBACK (void , onPreEdit , (SimSet *selection)) protected
GuiEditCtrl::DECLARE_CALLBACK (void , onPostEdit , (SimSet *selection)) protected
GuiEditCtrl::DECLARE_CALLBACK (void , onClearSelected , ()) protected
GuiEditCtrl::DECLARE_CALLBACK (void , onSelect , (GuiControl *control)) protected
GuiEditCtrl::DECLARE_CALLBACK (void , onAddSelected , (GuiControl *control)) protected
GuiEditCtrl::DECLARE_CALLBACK (void , onRemoveSelected , (GuiControl *control)) protected
GuiEditCtrl::DECLARE_CALLBACK (void , onPreSelectionNudged , (SimSet *selection)) protected
GuiEditCtrl::DECLARE_CALLBACK (void , onPostSelectionNudged , (SimSet *selection)) protected
GuiEditCtrl::DECLARE_CALLBACK (void , onSelectionMoved , (GuiControl *control)) protected
GuiEditCtrl::DECLARE_CALLBACK (void , onSelectionCloned , (SimSet *selection)) protected
GuiEditCtrl::DECLARE_CALLBACK (void , onTrashSelection , (SimSet *selection)) protected
GuiEditCtrl::DECLARE_CALLBACK (void , onAddNewCtrl , (GuiControl *control)) protected
GuiEditCtrl::DECLARE_CALLBACK (void , onAddNewCtrlSet , (SimSet *set)) protected
GuiEditCtrl::DECLARE_CALLBACK (void , onSelectionResized , (GuiControl *control)) protected
GuiEditCtrl::DECLARE_CALLBACK (void , onFitIntoParent , (bool width, bool height)) protected
GuiEditCtrl::DECLARE_CALLBACK (void , onMouseModeChange , ()) protected
GuiEditCtrl::DECLARE_CALLBACK (void , onControlInspectPreApply , (GuiControl *control)) protected
GuiEditCtrl::DECLARE_CALLBACK (void , onControlInspectPostApply , (GuiControl *control)) protected
GuiEditCtrl::DECLARE_CATEGORY ("Gui Editor")
Referenced by snapDelta().
GuiEditCtrl::DECLARE_CONOBJECT (GuiEditCtrl)
Referenced by snapDelta().
GuiEditCtrl::DECLARE_DESCRIPTION ("Implements the framework for the GUI editor.")
Referenced by snapDelta().
void GuiEditCtrl::deleteSelection ()
Referenced by getContentControl().
void GuiEditCtrl::doControlSnap (const GuiEvent & event, const RectI & selectionBounds, const RectI & selectionBoundsGlobal, Point2I & delta) protected
void GuiEditCtrl::doGridSnap (const GuiEvent & event, const RectI & selectionBounds, const RectI & selectionBoundsGlobal, Point2I & delta) protected
void GuiEditCtrl::doGuideSnap (const GuiEvent & event, const RectI & selectionBounds, const RectI & selectionBoundsGlobal, Point2I & delta) protected
void GuiEditCtrl::doSnapping (const GuiEvent & event, const RectI & selectionBounds, Point2I & delta) protected
static void GuiEditCtrl::drawCrossSection (U32 axis, S32 offset, const RectI & bounds, ColorI color, GFXDrawUtil * drawer) inline static protected
References GFXDrawUtil::drawLine(), SimSet::end(), RectI::extent, RectI::point, Point2I::x, and Point2I::y.
void GuiEditCtrl::drawNut (const Point2I & nut, ColorI & outlineColor, ColorI & nutColor)
Referenced by getContentControl().
void GuiEditCtrl::drawNuts (RectI & box, ColorI & outlineColor, ColorI & nutColor)
Referenced by getContentControl().
S32 GuiEditCtrl::findGuide (guideAxis axis, const Point2I & point, U32 tolerance = 0) protected
void GuiEditCtrl::findSnaps (snappingAxis axis, const Point2I & mousePoint, const RectI & minRegion, const RectI & midRegion, const RectI & maxRegion) protected
void GuiEditCtrl::fitIntoParents (bool width = true, bool height = true)
Referenced by getContentControl().
GuiControl* GuiEditCtrl::getAddSet () const inline
References mCurrentAddSet, onKeyDown(), onMouseDown(), onMouseDragged(), onMouseUp(), and onRightMouseDown().
GuiControl* GuiEditCtrl::getContentControl () const inline
References addNewControl(), addSelectControlAt(), addSelectControlsInRegion(), addSelection(), bringToFront(), canHitSelectedControls(), clearSelection(), cloneSelection(), deleteSelection(), drawNut(), drawNuts(), fitIntoParents(), getCurrentAddSet(), getDragRect(), getSelectionBounds(), getSelectionGlobalBounds(), getSizingHitKnobs(), justifySelection(), loadSelection(), mContentControl, moveAndSnapSelection(), moveSelection(), moveSelectionToCtrl(), onPreRender(), onRender(), pushToBack(), removeSelection(), resizeControlsInSelectionBy(), saveSelection(), select(), selectAll(), selectChildren(), selectionContains(), selectionContainsParentOf(), selectParents(), setContentControl(), setCurrentAddSet(), setEditMode(), and setSelection().
GuiControl* GuiEditCtrl::getCurrentAddSet ()
Referenced by getContentControl().
void GuiEditCtrl::getCursor (GuiCursor *& cursor, bool & showCursor, const GuiEvent & lastGuiEvent) virtual
Get information about the cursor.
Parameters
cursor Cursor information will be stored here
showCursor Will be set to true if the cursor is visible
lastGuiEvent GuiEvent containing cursor position and modifier keys (ie ctrl, shift, alt etc)
Reimplemented from GuiControl.
Referenced by clearGuides().
void GuiEditCtrl::getDragRect (RectI & b)
Referenced by getContentControl().
mouseModes GuiEditCtrl::getMouseMode () const inline
References mMouseDownMode, onAdd(), onRemove(), and setSnapToGrid().
U32 GuiEditCtrl::getNumSelected () const inline
References Vector< T >::size().
const Vector<GuiControl *>& GuiEditCtrl::getSelected () const inline
References mSelectedControls.
SimSet* GuiEditCtrl::getSelectedSet () inline
References mSelectedSet, and updateSelectedSet().
RectI GuiEditCtrl::getSelectionBounds () const
Referenced by getContentControl().
RectI GuiEditCtrl::getSelectionGlobalBounds () const
Referenced by getContentControl().
U32 GuiEditCtrl::getSelectionSize () const inline
References Vector< T >::size().
S32 GuiEditCtrl::getSizingHitKnobs (const Point2I & pt, const RectI & box)
Referenced by getContentControl().
RectI GuiEditCtrl::getSnapRegion (snappingAxis axis, const Point2I & center) const protected
SimGroup* GuiEditCtrl::getTrash () inline
References mTrash.
static void GuiEditCtrl::initPersistFields () static
Referenced by snapDelta().
static bool GuiEditCtrl::inNut (const Point2I & pt, S32 x, S32 y) inline static protected
References NUT_SIZE, Point2I::x, and Point2I::y.
void GuiEditCtrl::justifySelection (Justification j)
Referenced by getContentControl().
void GuiEditCtrl::loadSelection (const char * filename)
Referenced by getContentControl().
void GuiEditCtrl::moveAndSnapSelection (const Point2I & delta, bool callback = true)
Referenced by getContentControl().
void GuiEditCtrl::moveSelection (const Point2I & delta, bool callback = true)
Referenced by getContentControl().
void GuiEditCtrl::moveSelectionToCtrl (GuiControl * ctrl, bool callback = true)
Referenced by getContentControl().
virtual bool GuiEditCtrl::onAdd () virtual
Called when this object is added to the scene.
Reimplemented from GuiControl.
Referenced by getMouseMode().
bool GuiEditCtrl::onKeyDown (const GuiEvent & event) virtual
Happens when a key is depressed.
Parameters
event Event descriptor (which contains the key)
Reimplemented from GuiControl.
Referenced by getAddSet().
void GuiEditCtrl::onMouseDown (const GuiEvent & event) virtual
Reimplemented from GuiControl.
Referenced by getAddSet().
void GuiEditCtrl::onMouseDragged (const GuiEvent & event) virtual
Reimplemented from GuiControl.
Referenced by getAddSet().
void GuiEditCtrl::onMouseUp (const GuiEvent & event) virtual
Reimplemented from GuiControl.
Referenced by getAddSet().
void GuiEditCtrl::onPreRender () virtual
Do special pre-render processing.
Reimplemented from GuiControl.
Referenced by getContentControl().
virtual void GuiEditCtrl::onRemove () virtual
Called when this object is removed.
Reimplemented from GuiControl.
Referenced by getMouseMode().
void GuiEditCtrl::onRender (Point2I offset, const RectI & updateRect) virtual
Called when this control is to render itself.
Parameters
offset The location this control is to begin rendering
updateRect The screen area this control has drawing access to
Reimplemented from GuiControl.
Referenced by getContentControl().
void GuiEditCtrl::onRightMouseDown (const GuiEvent & event) virtual
Reimplemented from GuiControl.
Referenced by getAddSet().
void GuiEditCtrl::onSleep () virtual
Called when this object is asked to sleep.
Reimplemented from GuiControl.
Referenced by snapDelta().
bool GuiEditCtrl::onWake () virtual
Called when this object is asked to wake up returns true if it's actually awake at the end.
Reimplemented from GuiControl.
Referenced by snapDelta().
void GuiEditCtrl::pushToBack ()
Referenced by getContentControl().
void GuiEditCtrl::readGuides (guideAxis axis, GuiControl * ctrl)
Referenced by addGuide().
void GuiEditCtrl::redo ()
Referenced by clearGuides().
void GuiEditCtrl::registerSnap (snappingAxis axis, const Point2I & mousePoint, const Point2I & point, snappingEdges edge, GuiControl * ctrl = NULL) protected
void GuiEditCtrl::removeSelection (S32 id)
Referenced by getContentControl().
void GuiEditCtrl::removeSelection (GuiControl * ctrl)
void GuiEditCtrl::resizeControlsInSelectionBy (const Point2I & delta, U32 mode)
Referenced by getContentControl().
void GuiEditCtrl::saveSelection (const char * filename)
Referenced by getContentControl().
void GuiEditCtrl::select (GuiControl * ctrl)
Referenced by getContentControl().
void GuiEditCtrl::selectAll ()
Referenced by getContentControl().
void GuiEditCtrl::selectChildren (bool addToSelection = false)
Referenced by getContentControl().
bool GuiEditCtrl::selectionContains (GuiControl * ctrl)
Referenced by getContentControl().
bool GuiEditCtrl::selectionContainsParentOf (GuiControl * ctrl)
Referenced by getContentControl().
void GuiEditCtrl::selectParents (bool addToSelection = false)
Referenced by getContentControl().
void GuiEditCtrl::setContentControl (GuiControl * ctrl)
Referenced by getContentControl().
void GuiEditCtrl::setCurrentAddSet (GuiControl * ctrl, bool clearSelection = true)
Referenced by getContentControl().
void GuiEditCtrl::setEditMode (bool value)
Referenced by getContentControl().
void GuiEditCtrl::setMouseMode (mouseModes mode) protected
void GuiEditCtrl::setSelection (GuiControl * ctrl, bool inclusive = false)
Referenced by getContentControl().
void GuiEditCtrl::setSnapToGrid (U32 gridsize)
Referenced by getMouseMode().
static void GuiEditCtrl::snapDelta (snappingAxis axis, snappingEdges edge, S32 offset, const RectI & bounds, Point2I & delta) inline static protected
References DECLARE_CATEGORY(), DECLARE_CONOBJECT(), DECLARE_DESCRIPTION(), RectI::extent, GuiEditCtrl(), initPersistFields(), onSleep(), onWake(), RectI::point, SnapEdgeMid, SnapEdgeMin, SnapVertical, Point2I::x, and Point2I::y.
void GuiEditCtrl::snapToGrid (Point2I & point) protected
void GuiEditCtrl::startDragClone (const Point2I & startPoint) protected
void GuiEditCtrl::startDragMove (const Point2I & startPoint) protected
void GuiEditCtrl::startDragRectangle (const Point2I & startPoint) protected
void GuiEditCtrl::startMouseGuideDrag (guideAxis axis, U32 index, bool lockMouse = true) protected
void GuiEditCtrl::undo ()
Referenced by clearGuides().
void GuiEditCtrl::updateSelectedSet () protected
Referenced by getSelectedSet().
void GuiEditCtrl::writeGuides (guideAxis axis, GuiControl * ctrl)
Referenced by addGuide().
Member Data Documentation
GuiControlPtr GuiEditCtrl::mContentControl protected
Referenced by getContentControl().
GuiControlPtr GuiEditCtrl::mCurrentAddSet protected
Referenced by getAddSet().
GFXVertexBufferHandle<GFXVertexPCT> GuiEditCtrl::mDots protected
GFXStateBlockRef GuiEditCtrl::mDotSB protected
bool GuiEditCtrl::mDragAddSelection protected
Point2I GuiEditCtrl::mDragBeginPoint protected
Vector<Point2I> GuiEditCtrl::mDragBeginPoints protected
bool GuiEditCtrl::mDragGuide[2] protected
U32 GuiEditCtrl::mDragGuideIndex[2] protected
Indices of the guide's being dragged in DragGuide mouse mode.
bool GuiEditCtrl::mDragMoveUndo protected
bool GuiEditCtrl::mDrawBorderLines protected
bool GuiEditCtrl::mDrawGuides protected
bool GuiEditCtrl::mFullBoxSelection protected
Point2I GuiEditCtrl::mGridSnap protected
Vector< U32 > GuiEditCtrl::mGuides[2] protected
The guides defined on the current content control.
Point2I GuiEditCtrl::mLastDragPos protected
Point2I GuiEditCtrl::mLastMousePos protected
mouseModes GuiEditCtrl::mMouseDownMode protected
Referenced by getMouseMode().
GuiControlVector GuiEditCtrl::mSelectedControls protected
Referenced by getSelected().
SimSet* GuiEditCtrl::mSelectedSet protected
Referenced by getSelectedSet().
Point2I GuiEditCtrl::mSelectionAnchor protected
sizingModes GuiEditCtrl::mSizingMode protected
snappingEdges GuiEditCtrl::mSnapEdge[2] protected
Identification of edge being snapped for each axis.
GuiControlVector GuiEditCtrl::mSnapHits[2] protected
Hit testing lists for each axis.
S32 GuiEditCtrl::mSnapOffset[2] protected
Reference point on snap line for each axis.
bool GuiEditCtrl::mSnapped[2] protected
Snap flag for each axis. If true, we are currently snapped in a drag.
S32 GuiEditCtrl::mSnapSensitivity protected
Snap distance in pixels.
GuiControlPtr GuiEditCtrl::mSnapTargets[2] protected
Controls providing the snap reference lines on each axis.
bool GuiEditCtrl::mSnapToCanvas protected
If true, edge and center snapping will work against canvas (= content control).
bool GuiEditCtrl::mSnapToCenters protected
If true, selection centers will snap to other control centers.
bool GuiEditCtrl::mSnapToControls protected
If true, edge and center snapping will work against controls.
bool GuiEditCtrl::mSnapToEdges protected
If true, selection edges will snap to other control edges.
bool GuiEditCtrl::mSnapToGuides protected
If true, edge and center snapping will work against guides.
SimGroup* GuiEditCtrl::mTrash protected
Referenced by getTrash().
StringTableEntry GuiEditCtrl::smGuidesPropertyName[2] static protected
Copyright © GarageGames, LLC. All Rights Reserved.