ScatterSky Class Reference
Main Modules Class List Namespace List Online
ScatterSky Class Reference
#include <environment/scatterSky.h>
Public Types
enum MaskBits {
UpdateMask = Parent::NextFreeMask,
TimeMask = Parent::NextFreeMask << 1,
NextFreeMask = Parent::NextFreeMask << 2
}
Public Types inherited from SceneObject
enum {
MaxObjectZones = 128,
NumMountPoints = 32,
NumMountPointBits = 5
}
typedef NetObject Parent
enum SceneObjectFlags {
RenderEnabledFlag = BIT(0),
SelectionEnabledFlag = BIT(1),
DisableCullingInEditorFlag = BIT(2),
VisualOccluderFlag = BIT(3),
SoundOccluderFlag = BIT(4),
NextFreeFlag = BIT(5)
}
Bit-flags stored in mObjectFlags.
enum SceneObjectMasks {
InitialUpdateMask = BIT(0),
ScaleMask = BIT(1),
FlagMask = BIT(2),
MountedMask = BIT(3),
NextFreeMask = BIT(4)
}
Networking dirty mask.
Public Types inherited from SimGroup
typedef SimSet Parent
Public Types inherited from SimSet
typedef SimObject Parent
enum SetModification {
SetCleared,
SetObjectAdded,
SetObjectRemoved
}
typedef Signal< void(SetModification modification, SimSet *set, SimObject *object) > SetModificationSignal
Signal for letting observers know when objects are added to or removed from the set.
typedef SimObjectList::iterator iterator
typedef SimObjectList::value_type value
Public Types inherited from SimObject
typedef ConsoleObject Parent
enum WriteFlags {
SelectedOnly = BIT(0),
NoName = BIT(1),
IgnoreCanSave = BIT(2)
}
Flags passed to SimObject::write.
Public Types inherited from EngineObject
typedef void(* DebugEnumInstancesCallback) (EngineObject *)
Type of callback function for iterating over EngineObject instances.
Public Member Functions
ScatterSky ()
~ScatterSky ()
DECLARE_CONOBJECT (ScatterSky)
F32 getAzimuth () const
F32 getElevation () const
virtual LightInfo * getLight ()
void inspectPostApply ()
Called after any property of the object is changed in the world editor.
bool onAdd ()
Called when the object is added to the sim.
void onRemove ()
Called when the object is removed from the sim.
U32 packUpdate (NetConnection *conn, U32 mask, BitStream *stream)
Instructs this object to pack its state for transfer over the network.
void prepRenderImage (SceneRenderState *state)
Called when the SceneManager is ready for the registration of render instances.
void setAzimuth (F32 azimuth)
void setElevation (F32 elevation)
virtual void submitLights (LightManager *lm, bool staticLighting)
Submit lights to the light manager passed in.
void unpackUpdate (NetConnection *conn, BitStream *stream)
Instructs this object to read state data previously packed with packUpdate.
Public Member Functions inherited from SceneObject
SceneObject ()
virtual ~SceneObject ()
virtual void clearProcessAfter ()
Clears the effects of a call to processAfter()
DECLARE_CONOBJECT (SceneObject)
virtual ProcessObject * getAfterObject () const
Returns the object that this processes after.
ProcessList * getProcessList () const
Return the ProcessList for this object to use.
U32 getTypeMask () const
Return the type mask that indicates to which broad object categories this object belongs.
virtual void onCameraScopeQuery (NetConnection *connection, CameraScopeQuery *query)
Queries the object about information used to determine scope.
virtual void onDeleteNotify (SimObject *object)
Called when a SimObject is deleted.
virtual void processAfter (ProcessObject *obj)
Force this object to process after some other object.
virtual void setProcessTick (bool t)
Set the status of tick processing.
virtual bool writeField (StringTableEntry fieldName, const char *value)
Determine whether or not a field should be written.
SceneManager * getSceneManager () const
Return the SceneManager that this SceneObject belongs to.
void addToScene ()
Adds object to the client or server container depending on the object.
void removeFromScene ()
Removes the object from the client/server container.
SceneContainer * getContainer ()
Returns a pointer to the container that contains this object.
bool isRenderEnabled () const
Return true if this object is rendered.
void setRenderEnabled (bool value)
Set whether the object gets rendered.
bool isSelectionEnabled () const
Return true if this object can be selected in the editor.
void setSelectionEnabled (bool value)
Set whether the object can be selected in the editor.
bool isCullingDisabledInEditor () const
Return true if the object doesn't want to be subjected to culling when in the editor.
bool isVisualOccluder () const
Return true if the object should be taken into account for visual occlusion.
virtual void disableCollision ()
Disables collisions for this object including raycasts.
virtual void enableCollision ()
Enables collisions for this object.
bool isCollisionEnabled () const
Returns true if collisions are enabled.
virtual void onCollision (SceneObject *object, const VectorF &vec)
This gets called when an object collides with this object.
virtual bool isDisplacable () const
Returns true if this object allows itself to be displaced.
virtual Point3F getMomentum () const
Returns the momentum of this object.
virtual void setMomentum (const Point3F &momentum)
Sets the momentum of this object.
virtual F32 getMass () const
Returns the mass of this object.
virtual bool displaceObject (const Point3F &displaceVector)
Displaces this object by a vector.
virtual const MatrixF & getTransform () const
Returns the transform which can be used to convert object space to world space.
const MatrixF & getWorldTransform () const
Returns the transform which can be used to convert world space into object space.
const VectorF & getScale () const
Returns the scale of the object.
const Box3F & getObjBox () const
Returns the bounding box for this object in local coordinates.
const Box3F & getWorldBox () const
Returns the bounding box for this object in world coordinates.
const SphereF & getWorldSphere () const
Returns the bounding sphere for this object in world coordinates.
Point3F getBoxCenter () const
Returns the center of the bounding box in world coordinates.
virtual void setTransform (const MatrixF &mat)
Sets the Object -> World transform.
virtual void setScale (const VectorF &scale)
Sets the scale for the object.
virtual void setRenderTransform (const MatrixF &mat)
This sets the render transform for this object.
const MatrixF & getRenderTransform () const
Returns the render transform.
const MatrixF & getRenderWorldTransform () const
Returns the render transform to convert world to local coordinates.
const Box3F & getRenderWorldBox () const
Returns the render world box.
virtual void setHidden (bool hidden)
Sets the state of this object as hidden or not.
virtual void buildConvex (const Box3F &box, Convex *convex)
Builds a convex hull for this object.
virtual bool buildPolyList (PolyListContext context, AbstractPolyList *polyList, const Box3F &box, const SphereF &sphere)
Builds a list of polygons which intersect a bounding volume.
virtual bool castRay (const Point3F &start, const Point3F &end, RayInfo *info)
Casts a ray and obtain collision information, returns true if RayInfo is modified.
virtual bool castRayRendered (const Point3F &start, const Point3F &end, RayInfo *info)
Casts a ray against rendered geometry, returns true if RayInfo is modified.
virtual void buildSilhouette (const SceneCameraState &cameraState, Vector< Point3F > &outPoints)
Build a world-space silhouette polygon for the object for the given camera settings.
virtual bool containsPoint (const Point3F &point)
Return true if the given point is contained by the object's (collision) shape.
virtual bool collideBox (const Point3F &start, const Point3F &end, RayInfo *info)
virtual Point3F getPosition () const
Returns the position of the object.
Point3F getRenderPosition () const
Returns the render-position of the object.
void setPosition (const Point3F &pos)
Sets the position of the object.
virtual Point3F getVelocity () const
Gets the velocity of the object.
virtual void setVelocity (const Point3F &v)
Sets the velocity of the object.
virtual void applyImpulse (const Point3F &pos, const VectorF &vec)
Applies an impulse force to this object.
virtual void applyRadialImpulse (const Point3F &origin, F32 radius, F32 magnitude)
Applies a radial impulse to the object using the impulse origin and force.
virtual F32 distanceTo (const Point3F &pnt) const
Returns the distance from this object to a point.
bool isOccludingSound () const
Return whether the object's collision shape is blocking sound.
virtual SFXAmbience * getSoundAmbience () const
Return the ambient sound space active inside the volume of this object or NULL if the object does not have its own ambient space.
void setLightingPlugin (SceneObjectLightingPlugin *plugin)
SceneObjectLightingPlugin * getLightingPlugin ()
const bool isGlobalBounds () const
void setGlobalBounds ()
If global bounds are set to be true, then the object is assumed to have an infinitely large bounding box for collision and rendering purposes.
virtual void mountObject (SceneObject *obj, S32 node, const MatrixF &xfm=MatrixF::Identity)
ex: Mount B to A at A's node N A.mountObject(B, N)
virtual void unmountObject (SceneObject *obj)
Remove an object mounting.
virtual void unmount ()
Unmount this object from it's mount.
virtual void onMount (SceneObject *obj, S32 node)
Callback when this object is mounted.
virtual void onUnmount (SceneObject *obj, S32 node)
Callback when this object is unmounted.
virtual void getMountTransform (S32 index, const MatrixF &xfm, MatrixF *outMat)
virtual void getRenderMountTransform (F32 delta, S32 index, const MatrixF &xfm, MatrixF *outMat)
virtual SceneObject * getObjectMount ()
Return the object that this object is mounted to.
virtual SceneObject * getMountLink ()
Return object link of next object mounted to this object's mount.
virtual SceneObject * getMountList ()
Returns object list of objects mounted to this object.
virtual U32 getMountNode ()
Returns the mount id that this is mounted to.
virtual bool isMounted ()
Returns true if this object is mounted to anything at all Also try to resolve the PID to objectId here if it is pending.
virtual S32 getMountedObjectCount ()
Returns the number of object mounted along with this.
virtual SceneObject * getMountedObject (S32 idx)
Returns the object mounted at a position in the mount list.
virtual S32 getMountedObjectNode (S32 idx)
Returns the node the object at idx is mounted to.
virtual SceneObject * getMountNodeObject (S32 node)
Returns the object a object on the mount list is mounted to.
void resolveMountPID ()
Public Member Functions inherited from NetObject
NetObject ()
~NetObject ()
virtual void clearMaskBits (U32 orMask)
Clear the specified bits from the dirty mask.
void clearScopeAlways ()
Stop scoping the object to all connections.
virtual String describeSelf () const
Return a textual description of the object.
virtual U32 filterMaskBits (U32 mask, NetConnection *connection)
U32 getNetIndex ()
Get the ghost index of this object.
virtual F32 getUpdatePriority (CameraScopeQuery *focusObject, U32 updateMask, S32 updateSkips)
This returns a value which is used to prioritize which objects need to be updated.
bool isClientObject () const
Is this a client object?
bool isGhost () const
Is this is a ghost?
bool isGhostable () const
Is this object ghostable?
bool isGhostAlways () const
Should this object always be ghosted?
bool isScopeable () const
Is this object subject to scoping?
bool isScopeLocal () const
Should this object only be visible to the client which created it?
bool isServerObject () const
Is this a server object?
virtual void setMaskBits (U32 orMask)
Used to mark a bit as dirty; ie, that its corresponding set of fields need to be transmitted next update.
void setScopeAlways ()
Scope the object to all connections.
DECLARE_CONOBJECT (NetObject)
bool onAdd ()
Called when the object is added to the sim.
void onRemove ()
Called when the object is removed from the sim.
NetObject * getServerObject () const
Returns a pointer to the server object when on a local connection.
NetObject * getClientObject () const
Returns a pointer to the client object when on a local connection.
Public Member Functions inherited from SimGroup
~SimGroup ()
void addObject (SimObject *object, SimObjectId id)
void addObject (SimObject *object, const char *name)
virtual void addObject (SimObject *object)
Add the given object to the set.
virtual void clear ()
Remove all objects from this set.
virtual SimGroup * clone ()
Return a shallow copy of this object.
DECLARE_CONOBJECT (SimGroup)
virtual SimGroup * deepClone ()
Return a deep copy of this object.
virtual SimObject * findObject (const char *name)
Find a named sub-object of this object.
virtual void popObject ()
Remove an object from the end of the list.
virtual bool processArguments (S32 argc, ConsoleValueRef *argv)
Process constructor options. (ie, new SimObject(1,2,3))
virtual void pushObject (SimObject *object)
Add the given object to the end of the object list of this set.
virtual void removeObject (SimObject *object)
Remove the given object from the set.
Public Member Functions inherited from SimSet
SimSet ()
~SimSet ()
virtual void addTamlChild (SimObject *pSimObject)
Called when Taml attempts to populate an objects children during a read.
void callOnChildren (const String &method, S32 argc, ConsoleValueRef argv[], bool executeOnChildGroups=true)
DECLARE_CONOBJECT (SimSet)
SimObject * findObject (SimObject *object)
Find the given object in this set.
template<class T >
void findObjectByCallback (bool(*fn)(T *), Vector< T * > &foundObjects)
Add all child objects (including children of children) to the foundObjects Vector which are of type T and for which DecideAddObjectCallback return true;.
virtual SimObject * findObjectByInternalName (StringTableEntry internalName, bool searchChildren=false)
SimObject * findObjectByLineNumber (const char *fileName, S32 declarationLine, bool searchChildren=false)
template<class T >
void findObjectByType (Vector< T * > &foundObjects)
Add all child objects (including children of children) to the foundObjects Vector which are of type T.
SimObject * getRandom ()
const SetModificationSignal & getSetModificationSignal () const
Return the signal that is triggered when an object is added to or removed from the set.
SetModificationSignal & getSetModificationSignal ()
virtual SimObject * getTamlChild (const U32 childIndex) const
Called when Taml attempts to compile a list of children.
virtual U32 getTamlChildCount (void) const
Called when Taml attempts to compile a list of children.
void lock ()
virtual bool readObject (Stream *stream)
U32 sizeRecursive ()
Return the number of objects in this set as well as all sets that are contained in this set and its children.
void unlock ()
virtual void write (Stream &stream, U32 tabStop, U32 flags=0)
Output the TorqueScript to recreate this object.
virtual bool writeObject (Stream *stream)
virtual bool acceptsAsChild (SimObject *object) const
Return true if this set accepts the given object as a child.
void deleteAllObjects ()
Deletes all the objects in the set.
void bringObjectToFront (SimObject *obj)
void pushObjectToBack (SimObject *obj)
void scriptSort (const String &scriptCallbackFn)
Performs a sort of the objects in the set using a script callback function to do the comparison.
SimObject * front ()
SimObject * first ()
SimObject * last ()
bool empty () const
S32 size () const
iterator begin ()
iterator end ()
value operator[] (S32 index)
iterator find (iterator first, iterator last, SimObject *obj)
iterator find (SimObject *obj)
virtual bool reOrder (SimObject *obj, SimObject *target=0)
Reorder the position of "obj" to either be the last object in the list or, if "target" is given, to come before "target" in the list of children.
SimObject * at (S32 index) const
Return the object at the given index.
Public Member Functions inherited from SimObject
virtual void copyTo (SimObject *object)
Copy SimObject to another SimObject (Originally designed for T2D).
DECLARE_CONOBJECT (SimObject)
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
virtual void getConsoleMethodData (const char *fname, S32 routingId, S32 *type, S32 *minArgs, S32 *maxArgs, void **callback, const char **usage)
Namespace * getNamespace ()
Return the object's namespace.
StringTableEntry getProgenitorFile (void) const
virtual bool handlesConsoleMethod (const char *fname, S32 *routingId)
void setProgenitorFile (const char *pFile)
const char * tabComplete (const char *prevText, S32 baseLen, bool)
Get next matching item in namespace.
virtual void writeFields (Stream &stream, U32 tabStop)
Write the fields of this object in TorqueScript.
void setCanSaveDynamicFields (bool bCanSave)
Set whether fields created at runtime should be saved. Default is true.
bool getCanSaveDynamicFields ()
Get whether fields created at runtime should be saved. Default is true.
SimObject * getCopySource () const
Return the object that this object is copying fields from.
void setCopySource (SimObject *object)
Set the object that this object should be copying fields from.
void assignFieldsFrom (SimObject *obj)
Copy fields from another object onto this one.
void assignDynamicFieldsFrom (SimObject *obj)
Copy dynamic fields from another object onto this one.
Notify * removeNotify (void *ptr, Notify::Type)
Remove a notification from the list.
void deleteNotify (SimObject *obj)
Notify an object when we are deleted.
void clearNotify (SimObject *obj)
Notify an object when we are cleared.
void clearAllNotifications ()
Remove all notifications for this object.
void processDeleteNotifies ()
Send out deletion notifications.
void registerReference (SimObject **obj)
Register a reference to this object.
void unregisterReference (SimObject **obj)
Unregister a reference to this object.
SimPersistID * getPersistentId () const
Return the persistent ID assigned to this object or NULL.
SimPersistID * getOrCreatePersistentId ()
Return the persistent ID assigned to this object or assign one to it if it has none.
StringTableEntry getClassNamespace () const
Return name of class namespace set on this object.
StringTableEntry getSuperClassNamespace () const
Return name of superclass namespace set on this object.
void setClassNamespace (const char *classNamespace)
void setSuperClassNamespace (const char *superClassNamespace)
const char * getDataField (StringTableEntry slotName, const char *array)
Get the value of a field on the object.
void setDataField (StringTableEntry slotName, const char *array, const char *value)
Set the value of a field on the object.
const char * getPrefixedDataField (StringTableEntry fieldName, const char *array)
void setPrefixedDataField (StringTableEntry fieldName, const char *array, const char *value)
const char * getPrefixedDynamicDataField (StringTableEntry fieldName, const char *array, const S32 fieldType=-1)
void setPrefixedDynamicDataField (StringTableEntry fieldName, const char *array, const char *value, const S32 fieldType=-1)
StringTableEntry getDataFieldPrefix (StringTableEntry fieldName)
U32 getDataFieldType (StringTableEntry slotName, const char *array)
Get the type of a field on the object.
void setDataFieldType (const U32 fieldTypeId, StringTableEntry slotName, const char *array)
Set the type of a dynamic field on the object.
void setDataFieldType (const char *typeName, StringTableEntry slotName, const char *array)
SimFieldDictionary * getFieldDictionary ()
Get reference to the dictionary containing dynamic fields.
virtual StringTableEntry getComponentName ()
void setInternalName (const char *newname)
These functions support internal naming that is not namespace bound for locating child controls in a generic way.
StringTableEntry getInternalName () const
Get the internal name of this control.
void setOriginalName (const char *originalName)
Set the original name of this control.
StringTableEntry getOriginalName () const
Get the original name of this control.
void setFilename (const char *file)
These functions allow you to set and access the filename where this object was created.
StringTableEntry getFilename () const
Get the filename.
void setDeclarationLine (U32 lineNumber)
These functions are used to track the line number (1-based) on which the object was created if it was loaded from script.
S32 getDeclarationLine () const
Get the declaration line number.
virtual bool save (const char *pcFilePath, bool bOnlySelected=false, const char *preappend=NULL)
Save object as a TorqueScript File.
virtual bool isMethod (const char *methodName)
Check if a method exists in the objects current namespace.
virtual bool isField (const char *fieldName, bool includeStatic=true, bool includeDynamic=true)
Return true if the field is defined on the object.
SimObjectId getId () const
Return the unique numeric object ID.
const char * getIdString () const
Return the object ID as a string.
StringTableEntry getName () const
Return the name of this object.
SimGroup * getGroup () const
Return the SimGroup that this object is contained in.
void assignName (const char *name)
Assign the given name to this object.
void setId (SimObjectId id)
bool isChildOfGroup (SimGroup *pGroup)
bool isProperlyAdded () const
bool isDeleted () const
bool isRemoved () const
virtual bool isLocked () const
virtual void setLocked (bool b)
virtual bool isHidden () const
bool isSelected () const
bool isExpanded () const
bool isEditorOnly () const
bool isNameChangeAllowed () const
bool isAutoDeleted () const
void setSelected (bool sel)
void setExpanded (bool exp)
void setModDynamicFields (bool dyn)
void setModStaticFields (bool sta)
bool canModDynamicFields ()
bool canModStaticFields ()
void setAutoDelete (bool val)
void setEditorOnly (bool val)
void setNameChangeAllowed (bool val)
bool getCanSave () const
Returns boolean specifying if the object can be serialized.
virtual void setCanSave (bool val)
Set serialization flag.
bool isSelectedRecursive () const
Returns true if this object is selected or any group it is a member of is.
SimObject ()
virtual ~SimObject ()
virtual void onGroupAdd ()
Called when the object is added to a SimGroup.
virtual void onGroupRemove ()
Called when the object is removed from a SimGroup.
virtual void onNameChange (const char *name)
Called when the object's name is changed.
virtual void onPostAdd ()
Called when the adding of the object to the sim is complete, all sub-objects have been processed as well.
virtual void onStaticModified (const char *slotName, const char *newValue=NULL)
Specifically, these are called by setDataField when a static or dynamic field is modified, see the console details.
virtual void onDynamicModified (const char *slotName, const char *newValue=NULL)
Called when a dynamic field is modified.
virtual void inspectPreApply ()
Called before any property of the object is changed in the world editor.
virtual void onEditorEnable ()
Called when the editor is activated.
virtual void onEditorDisable ()
Called when the editor is deactivated.
bool registerObject ()
Register an object with the object system.
bool registerObject (U32 id)
Register the object, forcing the id.
bool registerObject (const char *name)
Register the object, assigning the name.
bool registerObject (const char *name, U32 id)
Register the object, assigning a name and ID.
void unregisterObject ()
Unregister the object from Sim.
void deleteObject ()
Unregister, mark as deleted, and free the object.
void safeDeleteObject ()
Performs a safe delayed delete of the object using a sim event.
bool addToSet (SimObjectId)
bool addToSet (const char *)
bool removeFromSet (SimObjectId)
bool removeFromSet (const char *)
void dumpToConsole (bool includeFunctions=true)
Dump the contents of this object to the console.
virtual void dumpClassHierarchy ()
added this so that you can print the entire class hierarchy, including script objects,
virtual void dumpGroupHierarchy ()
Print the SimGroup hierarchy of this object to the console.
Public Member Functions inherited from ConsoleObject
ConsoleObject ()
virtual AbstractClassRep * getClassRep () const
Gets the ClassRep.
const AbstractClassRep::Field * findField (StringTableEntry fieldName) const
Get a reference to a field by name.
bool setField (const char *fieldName, const char *value)
Set the value of a field.
void logMessage (const char *fmt,...) const
Logs with Con::printf.
void logWarning (const char *fmt,...) const
Logs with Con::warnf.
void logError (const char *fmt,...) const
Logs with Con::errorf.
const AbstractClassRep::FieldList & getFieldList () const
Get a list of all the fields. This information cannot be modified.
AbstractClassRep::FieldList & getModifiableFieldList ()
Get a list of all the fields, set up so we can modify them.
bool & getDynamicGroupExpand ()
Get a handle to a boolean telling us if we expanded the dynamic group.
S32 getClassId (U32 netClassGroup) const
Get our network-layer class id.
StringTableEntry getClassName () const
Get our compiler and platform independent class name.
Public Member Functions inherited from EngineObject
EngineObject ()
virtual ~EngineObject ()
DECLARE_ABSTRACT_CLASS (EngineObject, void)
DECLARE_INSCOPE (_GLOBALSCOPE)
IEngineObjectPool * getEngineObjectPool () const
Return the pool of EngineObjects to which this object belongs.
void operator delete (void *ptr)
Release the given object's memory in the pool it has been allocated from.
void * operator new (size_t size)
void * operator new (size_t size, IEngineObjectPool *pool)
void * operator new (size_t size TORQUE_TMM_ARGS_DECL)
Allocate a new object in the default object pool.
void * operator new (size_t size, IEngineObjectPool *pool TORQUE_TMM_ARGS_DECL)
Allocate a new object in the given object pool.
void * operator new (size_t size, void *ptr)
Placement new.
Public Member Functions inherited from StrongRefBase
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Public Member Functions inherited from ProcessObject
ProcessObject ()
virtual ~ProcessObject ()
virtual void advanceTime (F32 dt)
Advances simulation time for animations.
virtual GameConnection * getControllingClient ()
This is really implemented in GameBase and is only here to avoid casts within ProcessList.
virtual U32 getPacketDataChecksum (GameConnection *conn)
This is really implemented in GameBase and is only here to avoid casts within ProcessList.
virtual void interpolateTick (F32 delta)
Interpolates between tick events.
bool isTicking () const
Returns true if this object processes ticks.
void plJoin (ProcessObject *)
void plLinkAfter (ProcessObject *)
void plLinkBefore (ProcessObject *)
void plUnlink ()
virtual void preprocessMove (Move *move)
Allow object to modify the Move before it is ticked or sent to the server.
virtual void processTick (const Move *move)
Processes a move event and updates object state once every 32 milliseconds.
void removeFromProcessList ()
Removes this object from the tick-processing list.
Public Member Functions inherited from ISceneLight
virtual ~ISceneLight ()
Static Public Member Functions
static void initPersistFields ()
Static Public Member Functions inherited from SceneObject
static void initPersistFields ()
Static Public Member Functions inherited from NetObject
static void collapseDirtyList ()
static void initPersistFields ()
template<class T >
static T * getServerObject (T *netObj)
Template form for the callers convenience.
template<class T >
static T * getClientObject (T *netObj)
Template form for the callers convenience.
Static Public Member Functions inherited from SimObject
static SimObject * __findObject (const char *id)
static const char * __getObjectId (ConsoleObject *object)
static void initPersistFields ()
static void setForcedId (SimObjectId id)
Force an Id on the next registered object.
Static Public Member Functions inherited from ConsoleObject
static const char * __category ()
static const char * __description ()
static void consoleInit ()
Register global constant variables and do other one-time initialization tasks in a subclass of ConsoleObject.
static void initPersistFields ()
Register dynamic fields in a subclass of ConsoleObject.
static const char * lookupClassName (const U32 in_classTag)
Get the classname from a class tag.
static ConsoleObject * create (const char *in_pClassName)
static ConsoleObject * create (const U32 groupId, const U32 typeId, const U32 in_classId)
static void addGroup (const char *in_pGroupname, const char *in_pGroupDocs=NULL)
Mark the beginning of a group of fields.
static void endGroup (const char *in_pGroupname)
Mark the end of a group of fields.
static void addArray (const char *arrayName, S32 count)
Marks the start of a fixed size array of fields.
static void endArray (const char *arrayName)
Marks the end of an array of fields.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a complex field.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::WriteDataNotify in_writeDataFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, const char *in_pFieldDocs, U32 flags=0)
Register a simple field.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::WriteDataNotify in_writeDataFn, const char *in_pFieldDocs, U32 flags=0)
static void addFieldV (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, TypeValidator *v, const char *in_pFieldDocs=NULL)
Register a validated field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, AbstractClassRep::WriteDataNotify in_writeDataFn=&defaultProtectedWriteFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a complex protected field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, AbstractClassRep::WriteDataNotify in_writeDataFn=&defaultProtectedWriteFn, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a simple protected field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addDeprecatedField (const char *fieldName)
Add a deprecated field.
static bool removeField (const char *in_pFieldname)
Remove a field.
static AbstractClassRep * getStaticClassRep ()
Get the abstract class information for this class.
static AbstractClassRep * getParentStaticClassRep ()
Get the abstract class information for this class's superclass.
static ConsoleObject * __findObject (const char *)
static const char * __getObjectId (ConsoleObject *)
Static Public Member Functions inherited from EngineObject
static void debugDumpInstances ()
Dump describeSelf()s of all live ConsoleObjects to the console.
static void debugEnumInstances (const std::type_info &type, DebugEnumInstancesCallback callback)
Call the given callback for all instances of the given type.
static void debugEnumInstances (const char *className, DebugEnumInstancesCallback callback)
Same as above but uses an export class name and also includes inheritance (i.e.
Protected Member Functions
void _conformLights ()
void _debugRender (ObjectRenderInst *ri, SceneRenderState *state, BaseMatInstance *overrideMat)
void _generateSkyPoints ()
void _getAmbientColor (ColorF *outColor)
void _getColor (const Point3F &pos, ColorF *outColor)
void _getFogColor (ColorF *outColor)
F32 _getMiePhase (F32 fCos, F32 fCos2, F32 g, F32 g2)
F32 _getRayleighPhase (F32 fCos2)
void _getSunColor (ColorF *outColor)
void _initCurves ()
void _initMoon ()
bool _initShader ()
void _initVBIB ()
void _interpolateColors ()
virtual void _onSelected ()
Called when the object is selected in the editor.
virtual void _onUnselected ()
Called when the object is unselected in the editor.
void _render (ObjectRenderInst *ri, SceneRenderState *state, BaseMatInstance *overrideMat)
void _renderMoon (ObjectRenderInst *ri, SceneRenderState *state, BaseMatInstance *overrideMat)
void _updateTimeOfDay (TimeOfDay *timeofDay, F32 time)
F32 _vernierScale (F32 fCos)
Protected Member Functions inherited from SceneObject
virtual U32 getObjectFlagMax () const
Returns the greatest object flag bit defined.
virtual bool onSceneAdd ()
Called when this is added to a SceneManager.
virtual void onSceneRemove ()
Called when this is removed from its current SceneManager.
void _updateZoningState () const
Refresh the zoning state of this object, if it isn't up-to-date anymore.
ZoneRef * _getZoneRefHead () const
Return the first link in the zone list of this object.
U32 _getNumCurrZones () const
Gets the number of zones containing this object.
U32 _getCurrZone (const U32 index) const
Returns the nth zone containing this object.
void resetWorldBox ()
Regenerates the world-space bounding box and bounding sphere.
void resetRenderWorldBox ()
Regenerates the render-world-space bounding box and sphere.
void resetObjectBox ()
Regenerates the object-space bounding box from the world-space bounding box, the world space to object space transform, and the object scale.
virtual void onScaleChanged ()
Called when the size of the object changes.
U32 getContainerSeqKey () const
Returns the container sequence key.
void setContainerSeqKey (const U32 key)
Sets the container sequence key.
Protected Member Functions inherited from SimSet
DECLARE_CALLBACK (void, onObjectAdded,(SimObject *object))
DECLARE_CALLBACK (void, onObjectRemoved,(SimObject *object))
Protected Member Functions inherited from SimObject
virtual void _destroySelf ()
Subclasses should overload this method instead of the public destroySelf().
virtual String _getLogMessage (const char *fmt, va_list args) const
We can provide more detail, like object name and id.
object incRefCount ()
virtual void onTamlAddParent (SimObject *pParentObject)
Called after Taml has finished reading the object and has added the object to any parent.
virtual void onTamlCustomRead (const TamlCustomNodes &customNodes)
Called during the reading of the object to allow custom properties to be read.
virtual void onTamlCustomWrite (TamlCustomNodes &customNodes)
Called during the writing of the object to allow custom properties to be written.
virtual void onTamlPostRead (const TamlCustomNodes &customNodes)
Called after Taml has finished reading the object.
virtual void onTamlPostWrite (void)
Called after Taml has finished writing the object.
virtual void onTamlPreRead (void)
Called prior to Taml reading the object.
virtual void onTamlPreWrite (void)
Taml callbacks.
object registerObject ()
void linkNamespaces ()
Perform namespace linking on this object.
void unlinkNamespaces ()
Undo namespace linking on this object.
Protected Member Functions inherited from ConsoleObject
ConsoleObject (const ConsoleObject &)
Protected Member Functions inherited from EngineObject
object incRefCount ()
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Static Protected Member Functions
static bool ptSetAzimuth (void *object, const char *index, const char *data)
static bool ptSetElevation (void *object, const char *index, const char *data)
Static Protected Member Functions inherited from SimObject
static bool _setPersistentID (void *object, const char *index, const char *data)
Static Protected Member Functions inherited from EngineObject
static void * _allocateObject (size_t size, IEngineObjectPool *pool TORQUE_TMM_ARGS_DECL)
Protected Attributes
ColorF mAmbientColor
Not a field.
ColorF mAmbientScale
F32 mBrightness
GFXShaderConstHandle * mCamPosSC
bool mCastShadows
ColorF mColorize
F32 mColorizeAmt
GFXShaderConstHandle * mColorizeSC
FloatCurve mCurves [CURVE_COUNT]
bool mDirty
S32 mDynamicRefreshFreq
F32 mExposure
LightFlareData * mFlareData
F32 mFlareScale
LightFlareState mFlareState
ColorF mFogColor
Not a field.
ColorF mFogScale
GFXShaderConstHandle * mInverseWavelengthSC
LightInfo * mLight
VectorF mLightDir
GFXShaderConstHandle * mLightDirSC
MatrixSet * mMatrixSet
F32 mMiePhaseAssymetry
F32 mMieScaleDepth
F32 mMieScattering
F32 mMieScattering4PI
GFXShaderConstHandle * mMiscSC
GFXShaderConstHandle * mModelViewProjSC
F32 mMoonAzimuth
F32 mMoonElevation
bool mMoonEnabled
VectorF mMoonLightDir
BaseMatInstance * mMoonMatInst
String mMoonMatName
F32 mMoonScale
ColorF mMoonTint
ColorF mNightColor
GFXShaderConstHandle * mNightColorSC
CubemapData * mNightCubemap
String mNightCubemapName
ColorF mNightFogColor
F32 mNightInterpolant
GFXShaderConstHandle * mNightInterpolantAndExposureSC
F32 mOuterRadius
GFXPrimitiveBufferHandle mPrimBuffer
U32 mPrimCount
F32 mRayleighScaleDepth
F32 mRayleighScattering
F32 mRayleighScattering4PI
F32 mScale
GFXShaderConstHandle * mScatteringCoefficientsSC
GFXShaderRef mShader
GFXShaderConstBufferRef mShaderConsts
F32 mSkyBrightness
Vector< Point3F > mSkyPoints
F32 mSphereInnerRadius
F32 mSphereOuterRadius
GFXShaderConstHandle * mSphereRadiiSC
GFXStateBlockRef mStateBlock
S32 mStaticRefreshFreq
F32 mSunAzimuth
ColorF mSunColor
Not a field.
VectorF mSunDir
GFXShaderConstHandle * mSunDirSC
F32 mSunElevation
ColorF mSunScale
F32 mSunSize
F32 mTimeOfDay
GFXShaderConstHandle * mUseCubemapSC
bool mUseNightCubemap
GFXVertexBufferHandle< GFXVertexP > mVB
U32 mVertCount
ColorF mWavelength
F32 mWavelength4 [3]
F32 mZOffset
Protected Attributes inherited from SceneObject
SimObjectPtr< SceneObject > mAfterObject
Object which must be ticked before this object.
SceneObjectLightingPlugin * mLightPlugin
SceneObjectLightingPlugin attached to this object.
BitSet32 mObjectFlags
Combination of SceneObjectFlags.
SceneManager * mSceneManager
SceneManager to which this SceneObject belongs.
SceneObjectLink * mSceneObjectLinks
Links installed by SceneTrackers attached to this object.
U32 mTypeMask
Object type mask.
bool mZoneRefDirty
If an object moves, its zoning state needs to be updated.
U32 mNumCurrZones
Number of zones this object is assigned to.
ZoneRef * mZoneRefHead
List of zones that this object is part of.
MountInfo mMount
SimPersistID * mMountPID
MatrixF mObjToWorld
Transform from object space to world space.
MatrixF mWorldToObj
Transform from world space to object space (inverse).
Point3F mObjScale
Object scale.
Box3F mObjBox
Bounding box in object space.
Box3F mWorldBox
Bounding box (AABB) in world space.
SphereF mWorldSphere
Bounding sphere in world space.
MatrixF mRenderObjToWorld
Render matrix to transform object space to world space.
MatrixF mRenderWorldToObj
Render matrix to transform world space to object space.
Box3F mRenderWorldBox
Render bounding box in world space.
SphereF mRenderWorldSphere
Render bounding sphere in world space.
bool mGlobalBounds
Whether this object is considered to have an infinite bounding box.
S32 mCollisionCount
SceneContainer * mContainer
Container database that the object is assigned to.
U32 mContainerSeqKey
SceneContainer sequence key.
SceneObjectRef * mBinRefHead
U32 mBinMinX
U32 mBinMaxX
U32 mBinMinY
U32 mBinMaxY
Protected Attributes inherited from NetObject
SimObjectPtr< NetObject > mClientObject
Pointer to the client object on a local connection.
GhostInfo * mFirstObjectRef
Head of a linked list storing GhostInfos referencing this NetObject.
BitSet32 mNetFlags
Flag values from NetFlags.
U32 mNetIndex
The index of this ghost in the GhostManager on the server.
SimObjectPtr< NetObject > mServerObject
Pointer to the server object on a local connection.
Protected Attributes inherited from SimSet
void * mMutex
SetModificationSignal mSetModificationSignal
Signal that is triggered when objects are added or removed from the set.
SimObjectList objectList
Protected Attributes inherited from SimObject
DEFINE_CREATE_METHOD
SimObjectId mId
Id number for this object.
StringTableEntry mInternalName
Internal name assigned to the object. Not set by default.
return object
bool mCanSaveFieldDictionary
Whether dynamic fields should be saved out in serialization. Defaults to true.
SimPersistID * mPersistentId
Persistent ID assigned to this object.
Namespace * mNameSpace
The namespace in which method lookup for this object begins.
StringTableEntry mClassName
Name of namespace to use as class namespace.
StringTableEntry mSuperClassName
Name of namespace to use as class super namespace.
Protected Attributes inherited from EngineObject
DEFINE_CREATE_METHOD
return object
Protected Attributes inherited from StrongRefBase
U32 mRefCount
reference counter for StrongRefPtr objects
Static Protected Attributes
static const F32 smAtmosphereRadius
static const F32 smEarthRadius
static const F32 smViewerHeight
Static Protected Attributes inherited from SimObject
static SimObjectId smForcedId
The Id to force upon the object. Poor object.
static bool smForceId
Force a registered object to use the given Id. Cleared upon use.
Additional Inherited Members
Public Attributes inherited from SceneObject
GFXTextureObject * mAccuTex
bool mPathfindingIgnore
Public Attributes inherited from EngineObject
DECLARE_INSTANTIABLE
Public Attributes inherited from ProcessObject
bool mIsGameBase
U32 mOrderGUID
Link mProcessLink
U32 mProcessTag
bool mProcessTick
Static Public Attributes inherited from SceneObject
static Signal< void(SceneObject *) > smSceneObjectAdd
Triggered when a SceneObject onAdd is called.
static Signal< void(SceneObject *) > smSceneObjectRemove
Triggered when a SceneObject onRemove is called.
Static Public Attributes inherited from ConsoleObject
static const bool __smIsDatablock = false
Subclasses of ConsoleObjects that are datablocks should redefine this static member variable and set it to true.
Protected Types inherited from NetObject
enum NetFlags {
IsGhost = BIT(1),
ScopeAlways = BIT(6),
ScopeLocal = BIT(7),
Ghostable = BIT(8),
MaxNetFlagBit = 15
}
Protected Types inherited from EngineObject
typedef ::FalseType __IsDisposableType
typedef ::FalseType __IsSingletonType
Member Enumeration Documentation
enum ScatterSky::MaskBits
Enumerator
UpdateMask
TimeMask
NextFreeMask
Constructor & Destructor Documentation
ScatterSky::ScatterSky ()
ScatterSky::~ScatterSky ()
Member Function Documentation
void ScatterSky::_conformLights () protected
Referenced by getElevation().
void ScatterSky::_debugRender (ObjectRenderInst * ri, SceneRenderState * state, BaseMatInstance * overrideMat) protected
Referenced by getElevation().
void ScatterSky::_generateSkyPoints () protected
Referenced by getElevation().
void ScatterSky::_getAmbientColor (ColorF * outColor) protected
Referenced by getElevation().
void ScatterSky::_getColor (const Point3F & pos, ColorF * outColor) protected
Referenced by getElevation().
void ScatterSky::_getFogColor (ColorF * outColor) protected
Referenced by getElevation().
F32 ScatterSky::_getMiePhase (F32 fCos, F32 fCos2, F32 g, F32 g2) protected
Referenced by getElevation().
F32 ScatterSky::_getRayleighPhase (F32 fCos2) protected
Referenced by getElevation().
void ScatterSky::_getSunColor (ColorF * outColor) protected
Referenced by getElevation().
void ScatterSky::_initCurves () protected
Referenced by getElevation().
void ScatterSky::_initMoon () protected
Referenced by getElevation().
bool ScatterSky::_initShader () protected
Referenced by getElevation().
void ScatterSky::_initVBIB () protected
Referenced by getElevation().
void ScatterSky::_interpolateColors () protected
Referenced by getElevation().
virtual void ScatterSky::_onSelected () protected virtual
Called when the object is selected in the editor.
Reimplemented from SimObject.
Referenced by getElevation().
virtual void ScatterSky::_onUnselected () protected virtual
Called when the object is unselected in the editor.
Reimplemented from SimObject.
Referenced by getElevation().
void ScatterSky::_render (ObjectRenderInst * ri, SceneRenderState * state, BaseMatInstance * overrideMat) protected
Referenced by getElevation().
void ScatterSky::_renderMoon (ObjectRenderInst * ri, SceneRenderState * state, BaseMatInstance * overrideMat) protected
Referenced by getElevation().
void ScatterSky::_updateTimeOfDay (TimeOfDay * timeofDay, F32 time) protected
Referenced by getElevation().
F32 ScatterSky::_vernierScale (F32 fCos) protected
Referenced by getElevation().
ScatterSky::DECLARE_CONOBJECT (ScatterSky)
Referenced by getLight().
F32 ScatterSky::getAzimuth () const inline
References mSunAzimuth.
F32 ScatterSky::getElevation () const inline
References _conformLights(), _debugRender(), _generateSkyPoints(), _getAmbientColor(), _getColor(), _getFogColor(), _getMiePhase(), _getRayleighPhase(), _getSunColor(), _initCurves(), _initMoon(), _initShader(), _initVBIB(), _interpolateColors(), _onSelected(), _onUnselected(), _render(), _renderMoon(), _updateTimeOfDay(), _vernierScale(), mSunElevation, ptSetAzimuth(), and ptSetElevation().
virtual LightInfo* ScatterSky::getLight () inline virtual
Implements ISceneLight.
References DECLARE_CONOBJECT(), initPersistFields(), inspectPostApply(), mLight, packUpdate(), prepRenderImage(), setAzimuth(), setElevation(), and unpackUpdate().
static void ScatterSky::initPersistFields () static
Referenced by getLight().
void ScatterSky::inspectPostApply () virtual
Called after any property of the object is changed in the world editor.
See also
inspectPreApply
Reimplemented from SceneObject.
Referenced by getLight().
bool ScatterSky::onAdd () virtual
Called when the object is added to the sim.
Reimplemented from SceneObject.
void ScatterSky::onRemove () virtual
Called when the object is removed from the sim.
Reimplemented from SceneObject.
U32 ScatterSky::packUpdate (NetConnection * conn, U32 mask, BitStream * stream) virtual
Instructs this object to pack its state for transfer over the network.
Parameters
conn Net connection being used
mask Mask indicating fields to transmit.
stream Bitstream to pack data to
Returns
Any bits which were not dealt with. The value is stored by the networking system. Don't set bits you weren't passed.
Reimplemented from SceneObject.
Referenced by getLight().
void ScatterSky::prepRenderImage (SceneRenderState * state) virtual
Called when the SceneManager is ready for the registration of render instances.
Parameters
state Rendering state.
Reimplemented from SceneObject.
Referenced by getLight().
static bool ScatterSky::ptSetAzimuth (void * object, const char * index, const char * data) static protected
Referenced by getElevation().
static bool ScatterSky::ptSetElevation (void * object, const char * index, const char * data) static protected
Referenced by getElevation().
void ScatterSky::setAzimuth (F32 azimuth)
Referenced by getLight().
void ScatterSky::setElevation (F32 elevation)
Referenced by getLight().
virtual void ScatterSky::submitLights (LightManager * lm, bool staticLighting) virtual
Submit lights to the light manager passed in.
Implements ISceneLight.
void ScatterSky::unpackUpdate (NetConnection * conn, BitStream * stream) virtual
Instructs this object to read state data previously packed with packUpdate.
Parameters
conn Net connection being used
stream stream to read from
Reimplemented from SceneObject.
Referenced by getLight().
Member Data Documentation
ColorF ScatterSky::mAmbientColor protected
Not a field.
ColorF ScatterSky::mAmbientScale protected
F32 ScatterSky::mBrightness protected
GFXShaderConstHandle* ScatterSky::mCamPosSC protected
bool ScatterSky::mCastShadows protected
ColorF ScatterSky::mColorize protected
F32 ScatterSky::mColorizeAmt protected
GFXShaderConstHandle* ScatterSky::mColorizeSC protected
FloatCurve ScatterSky::mCurves[CURVE_COUNT] protected
bool ScatterSky::mDirty protected
S32 ScatterSky::mDynamicRefreshFreq protected
F32 ScatterSky::mExposure protected
LightFlareData* ScatterSky::mFlareData protected
F32 ScatterSky::mFlareScale protected
LightFlareState ScatterSky::mFlareState protected
ColorF ScatterSky::mFogColor protected
Not a field.
ColorF ScatterSky::mFogScale protected
GFXShaderConstHandle* ScatterSky::mInverseWavelengthSC protected
LightInfo* ScatterSky::mLight protected
Referenced by getLight().
VectorF ScatterSky::mLightDir protected
GFXShaderConstHandle* ScatterSky::mLightDirSC protected
MatrixSet* ScatterSky::mMatrixSet protected
F32 ScatterSky::mMiePhaseAssymetry protected
F32 ScatterSky::mMieScaleDepth protected
F32 ScatterSky::mMieScattering protected
F32 ScatterSky::mMieScattering4PI protected
GFXShaderConstHandle* ScatterSky::mMiscSC protected
GFXShaderConstHandle* ScatterSky::mModelViewProjSC protected
F32 ScatterSky::mMoonAzimuth protected
F32 ScatterSky::mMoonElevation protected
bool ScatterSky::mMoonEnabled protected
VectorF ScatterSky::mMoonLightDir protected
BaseMatInstance* ScatterSky::mMoonMatInst protected
String ScatterSky::mMoonMatName protected
F32 ScatterSky::mMoonScale protected
ColorF ScatterSky::mMoonTint protected
ColorF ScatterSky::mNightColor protected
GFXShaderConstHandle* ScatterSky::mNightColorSC protected
CubemapData* ScatterSky::mNightCubemap protected
String ScatterSky::mNightCubemapName protected
ColorF ScatterSky::mNightFogColor protected
F32 ScatterSky::mNightInterpolant protected
GFXShaderConstHandle* ScatterSky::mNightInterpolantAndExposureSC protected
F32 ScatterSky::mOuterRadius protected
GFXPrimitiveBufferHandle ScatterSky::mPrimBuffer protected
U32 ScatterSky::mPrimCount protected
F32 ScatterSky::mRayleighScaleDepth protected
F32 ScatterSky::mRayleighScattering protected
F32 ScatterSky::mRayleighScattering4PI protected
F32 ScatterSky::mScale protected
GFXShaderConstHandle* ScatterSky::mScatteringCoefficientsSC protected
GFXShaderRef ScatterSky::mShader protected
GFXShaderConstBufferRef ScatterSky::mShaderConsts protected
F32 ScatterSky::mSkyBrightness protected
Vector<Point3F> ScatterSky::mSkyPoints protected
F32 ScatterSky::mSphereInnerRadius protected
F32 ScatterSky::mSphereOuterRadius protected
GFXShaderConstHandle* ScatterSky::mSphereRadiiSC protected
GFXStateBlockRef ScatterSky::mStateBlock protected
S32 ScatterSky::mStaticRefreshFreq protected
F32 ScatterSky::mSunAzimuth protected
Referenced by getAzimuth().
ColorF ScatterSky::mSunColor protected
Not a field.
VectorF ScatterSky::mSunDir protected
GFXShaderConstHandle* ScatterSky::mSunDirSC protected
F32 ScatterSky::mSunElevation protected
Referenced by getElevation().
ColorF ScatterSky::mSunScale protected
F32 ScatterSky::mSunSize protected
F32 ScatterSky::mTimeOfDay protected
GFXShaderConstHandle* ScatterSky::mUseCubemapSC protected
bool ScatterSky::mUseNightCubemap protected
GFXVertexBufferHandle<GFXVertexP> ScatterSky::mVB protected
U32 ScatterSky::mVertCount protected
ColorF ScatterSky::mWavelength protected
F32 ScatterSky::mWavelength4[3] protected
F32 ScatterSky::mZOffset protected
const F32 ScatterSky::smAtmosphereRadius static protected
const F32 ScatterSky::smEarthRadius static protected
const F32 ScatterSky::smViewerHeight static protected
Copyright © GarageGames, LLC. All Rights Reserved.