ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode Class Reference
Main Modules Class List Namespace List Online
ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode Class Reference
TrackingNodes are used to track object bounds along individual world axes.
#include <util/scopeTracker.h>
Public Types
enum EFlags {
FLAG_Min = BIT(0),
FLAG_Max = BIT(1),
FLAG_Reference = BIT(2)
}
typedef void Parent
Public Member Functions
TrackingNode ()
TrackingNode * getNext () const
ScopeTrackerObject * getObject () const
Return the object to which this tracking node belongs.
TrackingNode * getOpposite () const
F32 getPosition () const
TrackingNode * getPrev () const
bool isMax () const
Return true if this is the right/upper bound node of an object.
bool isMin () const
Return true if this is left/lower bound node of an object.
bool isReference () const
Return true if this is the reference center tracking node.
void setNext (TrackingNode *node)
void setPosition (F32 value)
void setPrev (TrackingNode *node)
Public Attributes
BitSet32 mFlags
TrackingNode * mNext
Next node on axis tracking chain.
ScopeTrackerObject * mObject
The object being tracked by this node or NULL.
TrackingNode * mOpposite
F32 mPosition
Distance along axis.
TrackingNode * mPrev
Previous node on axis tracking chain.
Detailed Description
template<S32 NUM_DIMENSIONS>
class ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode
TrackingNodes are used to track object bounds along individual world axes.
Member Typedef Documentation
template<S32 NUM_DIMENSIONS> typedef void ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::Parent
Member Enumeration Documentation
template<S32 NUM_DIMENSIONS> enum ScopeTrackerObject::TrackingNode::EFlags
Enumerator
FLAG_Min
FLAG_Max
FLAG_Reference
Constructor & Destructor Documentation
template<S32 NUM_DIMENSIONS> ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::TrackingNode () inline
Member Function Documentation
template<S32 NUM_DIMENSIONS> TrackingNode* ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::getNext () const inline
References ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::mNext.
Referenced by ScopeTrackerObject< NUM_DIMENSIONS >::isRegistered().
template<S32 NUM_DIMENSIONS> ScopeTrackerObject* ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::getObject () const inline
Return the object to which this tracking node belongs.
References ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::mObject.
template<S32 NUM_DIMENSIONS> TrackingNode* ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::getOpposite () const inline
References ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::mOpposite.
template<S32 NUM_DIMENSIONS> F32 ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::getPosition () const inline
References ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::mPosition.
Referenced by ScopeTrackerObject< NUM_DIMENSIONS >::getMaxTrackingNode().
template<S32 NUM_DIMENSIONS> TrackingNode* ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::getPrev () const inline
References ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::mPrev.
template<S32 NUM_DIMENSIONS> bool ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::isMax () const inline
Return true if this is the right/upper bound node of an object.
References ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::FLAG_Max, and BitSet32::test().
template<S32 NUM_DIMENSIONS> bool ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::isMin () const inline
Return true if this is left/lower bound node of an object.
References ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::FLAG_Min, and BitSet32::test().
template<S32 NUM_DIMENSIONS> bool ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::isReference () const inline
Return true if this is the reference center tracking node.
There will only ever be one such node on each tracking list.
References ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::FLAG_Reference, and BitSet32::test().
template<S32 NUM_DIMENSIONS> void ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::setNext (TrackingNode * node) inline
template<S32 NUM_DIMENSIONS> void ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::setPosition (F32 value) inline
template<S32 NUM_DIMENSIONS> void ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::setPrev (TrackingNode * node) inline
Member Data Documentation
template<S32 NUM_DIMENSIONS> BitSet32 ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::mFlags
Referenced by ScopeTrackerObject< NUM_DIMENSIONS >::ScopeTrackerObject().
template<S32 NUM_DIMENSIONS> TrackingNode* ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::mNext
Next node on axis tracking chain.
Referenced by ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::getNext().
template<S32 NUM_DIMENSIONS> ScopeTrackerObject* ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::mObject
The object being tracked by this node or NULL.
Referenced by ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::getObject(), and ScopeTrackerObject< NUM_DIMENSIONS >::ScopeTrackerObject().
template<S32 NUM_DIMENSIONS> TrackingNode* ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::mOpposite
Referenced by ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::getOpposite(), and ScopeTrackerObject< NUM_DIMENSIONS >::ScopeTrackerObject().
template<S32 NUM_DIMENSIONS> F32 ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::mPosition
Distance along axis.
Referenced by ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::getPosition().
template<S32 NUM_DIMENSIONS> TrackingNode* ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::mPrev
Previous node on axis tracking chain.
Referenced by ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::getPrev().
Copyright © GarageGames, LLC. All Rights Reserved.