RawDataT< T > Class Template Reference
Main Modules Class List Namespace List Online
RawDataT< T > Class Template Reference
#include <core/util/rawData.h>
Public Types
typedef void Parent
typedef RawDataT< T > ThisType
typedef T ValueType
Type of elements in the buffer.
Public Member Functions
RawDataT ()
RawDataT (T *data, U32 size, bool ownMemory=false)
RawDataT (const ThisType &rd)
~RawDataT ()
void alloc (const U32 newSize)
void operator= (const ThisType &rd)
void reset ()
Static Public Member Functions
template<class Self >
static Self * allocInline (U32 numElements TORQUE_TMM_ARGS_DECL)
Allocate a RawDataT instance inline with its data elements.
Public Attributes
T * data
The data buffer.
bool ownMemory
If true, the structure own the data buffer and will delete[] it on destruction.
U32 size
Number of elements in the buffer.
Member Typedef Documentation
template<typename T> typedef void RawDataT< T >::Parent
template<typename T> typedef RawDataT< T > RawDataT< T >::ThisType
template<typename T> typedef T RawDataT< T >::ValueType
Type of elements in the buffer.
Constructor & Destructor Documentation
template<typename T> RawDataT< T >::RawDataT () inline
template<typename T> RawDataT< T >::RawDataT (T * data, U32 size, bool ownMemory = false) inline
template<typename T> RawDataT< T >::RawDataT (const ThisType & rd) inline
References RawDataT< T >::data, and RawDataT< T >::size.
template<typename T> RawDataT< T >::~RawDataT () inline
References RawDataT< T >::reset().
Member Function Documentation
template<typename T> void RawDataT< T >::alloc (const U32 newSize) inline
References RawDataT< T >::reset().
template<typename T> template<class Self > static Self* RawDataT< T >::allocInline (U32 numElements TORQUE_TMM_ARGS_DECL) inline static
Allocate a RawDataT instance inline with its data elements.
Parameters
Self RawDataT instance type; this is a type parameter so this can work with types derived from RawDataT.
References RawDataT< T >::data, and dMalloc_r().
template<typename T> void RawDataT< T >::operator= (const ThisType & rd) inline
References RawDataT< T >::data, and RawDataT< T >::size.
template<typename T> void RawDataT< T >::reset (void) inline
References RawDataT< T >::data.
Referenced by RawDataT< T >::alloc(), AsyncPacketBufferedInputStream< Stream, Packet >::PacketReadItem::execute(), and RawDataT< T >::~RawDataT().
Member Data Documentation
template<typename T> T* RawDataT< T >::data
The data buffer.
Referenced by RawDataT< T >::allocInline(), RawDataT< T >::operator=(), RawDataT< T >::RawDataT(), and RawDataT< T >::reset().
template<typename T> bool RawDataT< T >::ownMemory
If true, the structure own the data buffer and will delete[] it on destruction.
template<typename T> U32 RawDataT< T >::size
Number of elements in the buffer.
Referenced by RawDataT< T >::operator=(), and RawDataT< T >::RawDataT().
Copyright © GarageGames, LLC. All Rights Reserved.