SFXBuffer Class Reference
Main Modules Class List Namespace List Online
SFXBuffer Class Reference abstract
The buffer interface hides the details of how the device holds sound data for playback.
#include <sfx/sfxBuffer.h>
Classes
struct AsyncState
Encapsulates the async I/O state of the sound buffer.
Public Types
typedef void Parent
enum Status {
STATUS_Null,
STATUS_Loading,
STATUS_Ready,
STATUS_Blocked,
STATUS_AtEnd
}
Status indicators for sound buffers.
Public Types inherited from IPolled
typedef void Parent
Public Types inherited from IOutputStream< SFXInternal::SFXStreamPacket * >
typedef SFXInternal::SFXStreamPacket * ElementType
The element type of this input stream.
typedef void Parent
Public Member Functions
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
U32 getDuration () const
const SFXFormat & getFormat () const
virtual U32 getMemoryUsed () const
U32 getNumSamples () const
Status getStatus () const
bool isAtEnd () const
bool isBlocked () const
bool isDead () const
bool isLoading () const
bool isReady () const
bool isStreaming () const
bool isUnique () const
void load ()
Start the async request chain for the buffer.
virtual bool update ()
Update the object state.
Public Member Functions inherited from StrongRefBase
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Public Member Functions inherited from IOutputStream< SFXInternal::SFXStreamPacket * >
virtual void write (const ElementType *buffer, U32 num)=0
Write "num" elements from "buffer" to the stream at its current position.
Public Attributes
Signal< void(SFXBuffer *buffer, Status newStatus) > mOnStatusChange
Signal that is triggered when the buffer status changes.
Static Public Attributes
static Signal< void(SFXBuffer *) > smBufferDestroyedSignal
This signal is triggered from SFXBuffer's destructor so the sound system can keep track of buffers being released on the device.
Protected Types
typedef ThreadSafeRef< AsyncState > AsyncStatePtr
typedef SFXInternal::SFXAsyncQueue * SFXAsyncQueuePtr
typedef ThreadSafeRef< SFXInternal::SFXAsyncStream > SFXAsyncStreamPtr
Protected Member Functions
SFXBuffer (const ThreadSafeRef< SFXStream > &stream, SFXDescription *description, bool createAsyncState=true)
Create a new buffer from stream using the parameters in description.
SFXBuffer (SFXDescription *description)
Create a buffer with just a description.
virtual ~SFXBuffer ()
virtual void _flush ()=0
Flush all queue state for this buffer on the device.
void _setStatus (Status status)
Set the buffer status and trigger mOnStatusChange if the status changes.
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Protected Attributes
AsyncStatePtr mAsyncState
Pointer to structure keeping the asynchronous I/O state of the buffer.
U32 mDuration
Total playback time of the associated sound stream in milliseconds.
SFXFormat mFormat
The sound sample format used by the buffer.
bool mIsDead
If true, the buffer is dead and will be deleted.
bool mIsLooping
For streaming buffers, tells whether the source stream loops.
bool mIsStreaming
If true, this is a continuously streaming buffer.
bool mIsUnique
If true, this buffer can only have a single SFXVoice attached.
Status mStatus
The buffer readiness status.
StrongWeakRefPtr< SFXVoice > mUniqueVoice
If this is a unique buffer (i.e.
Protected Attributes inherited from StrongRefBase
U32 mRefCount
reference counter for StrongRefPtr objects
Friends
void SFXInternal::PurgeDeadBuffers ()
Detailed Description
The buffer interface hides the details of how the device holds sound data for playback.
A sound buffer may either be loaded once completely and then played as needed or it may be progressively streamed from an SFXStream. In the latter case, there can only be a single voice tied to the buffer.
Note
SFXDevice is the last instance when it comes to ownership of SFXBuffers. If the SFXDevice goes away, it will take all SFXBuffers with it, regardless of whether there are still strong refs to it. Use StrongWeakRefPtrs to keep pointers to SFXBuffers!
See also
SFXStream
Member Typedef Documentation
typedef ThreadSafeRef< AsyncState > SFXBuffer::AsyncStatePtr protected
typedef void SFXBuffer::Parent
typedef SFXInternal::SFXAsyncQueue* SFXBuffer::SFXAsyncQueuePtr protected
typedef ThreadSafeRef< SFXInternal::SFXAsyncStream > SFXBuffer::SFXAsyncStreamPtr protected
Member Enumeration Documentation
enum SFXBuffer::Status
Status indicators for sound buffers.
Enumerator
STATUS_Null
Initial state.
STATUS_Loading
Buffer has requested data and is waiting for queue to fill up.
STATUS_Ready
Playback queue is fed and ready (non-stream buffers will stop at this state).
STATUS_Blocked
Queue is starved and playback thus held until further data is available (streaming buffers only).
STATUS_AtEnd
Buffer has read all its streaming data (streaming buffers only).
Constructor & Destructor Documentation
SFXBuffer::SFXBuffer (const ThreadSafeRef< SFXStream > & stream, SFXDescription * description, bool createAsyncState = true) protected
Create a new buffer from stream using the parameters in description.
Parameters
stream Sound stream from which to read sound data into the buffer.
description Sound setup description.
createAsyncState If true, the asynchronous loading state for the buffer will be set up in the constructor. This is mainly useful for the null device which creates dummy buffers that do not need the async state to be in place. All other buffers do.
SFXBuffer::SFXBuffer (SFXDescription * description) protected
Create a buffer with just a description.
This is used by devices who fully take over loading and streaming.
virtual SFXBuffer::~SFXBuffer () protected virtual
Member Function Documentation
virtual void SFXBuffer::_flush () protected pure virtual
Flush all queue state for this buffer on the device.
Note
Called on the SFX update thread.
Implemented in SFXInternal::SFXWrapAroundBuffer, SFXALBuffer, SFXDSBuffer, SFXXAudioBuffer, SFXFMODBuffer, and SFXNullBuffer.
void SFXBuffer::_setStatus (Status status) protected
Set the buffer status and trigger mOnStatusChange if the status changes.
Note
Called on both the SFX update thread and the main thread.
virtual void SFXBuffer::destroySelf () virtual
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
Reimplemented from StrongRefBase.
U32 SFXBuffer::getDuration () const inline
Returns
The total playback time of the buffer in milliseconds.
const SFXFormat& SFXBuffer::getFormat () const inline
Returns
The sound sample format used by the buffer.
Referenced by SFXALBuffer::_getALFormat(), and SFXVoice::getFormat().
virtual U32 SFXBuffer::getMemoryUsed () const inline virtual
Returns
The number of bytes consumed by this sound buffer.
Reimplemented in SFXInternal::SFXWrapAroundBuffer, and SFXFMODBuffer.
U32 SFXBuffer::getNumSamples () const inline
Returns
The total number of samples in the buffer.
Referenced by SFXInternal::SFXVoiceTimeSource::getPosition().
Status SFXBuffer::getStatus () const inline
Returns
The current buffer loading/queue status.
bool SFXBuffer::isAtEnd () const inline
Returns
True if the buffer has exhausted its source stream
bool SFXBuffer::isBlocked () const inline
Returns
True if the buffer's packet queue has been starved and is waiting for data.
bool SFXBuffer::isDead () const inline
Returns
True if the buffer is pending deletion.
bool SFXBuffer::isLoading () const inline
Returns
True if the buffer's packet queue is still loading.
bool SFXBuffer::isReady () const inline
Returns
True if the buffer's packet queue is loaded and ready for playback.
bool SFXBuffer::isStreaming () const inline
Returns
True if the buffer does continuous sound streaming.
bool SFXBuffer::isUnique () const inline
Returns
True if the buffer can only have a single SFXVoice attached to it.
void SFXBuffer::load ()
Start the async request chain for the buffer.
virtual bool SFXBuffer::update () virtual
Update the object state.
Implements IPolled.
Friends And Related Function Documentation
void SFXInternal::PurgeDeadBuffers () friend
Member Data Documentation
AsyncStatePtr SFXBuffer::mAsyncState protected
Pointer to structure keeping the asynchronous I/O state of the buffer.
For non-streaming buffers, this is released as soon as all data is loaded.
To allow seeking in streaming buffers even after playback has ended, we do not release the async state of these buffers until the buffer is actually released itself. This allows to always access the associated input stream.
Note
For devices that handle loading/streaming on their own, this will not be set.
U32 SFXBuffer::mDuration protected
Total playback time of the associated sound stream in milliseconds.
Note
For streaming buffers, this will not correspond to the actual playtime of the device buffer.
SFXFormat SFXBuffer::mFormat protected
The sound sample format used by the buffer.
bool SFXBuffer::mIsDead protected
If true, the buffer is dead and will be deleted.
Can't be in status for synchronization reasons.
bool SFXBuffer::mIsLooping protected
For streaming buffers, tells whether the source stream loops.
bool SFXBuffer::mIsStreaming protected
If true, this is a continuously streaming buffer.
bool SFXBuffer::mIsUnique protected
If true, this buffer can only have a single SFXVoice attached.
Signal< void(SFXBuffer* buffer, Status newStatus) > SFXBuffer::mOnStatusChange
Signal that is triggered when the buffer status changes.
Note
This signal is triggered on the same thread that the buffer update code runs on.
Status SFXBuffer::mStatus protected
The buffer readiness status.
StrongWeakRefPtr< SFXVoice > SFXBuffer::mUniqueVoice protected
If this is a unique buffer (i.e.
a streaming buffer), then this holds the reference to the unique voice.
Referenced by SFXXAudioBuffer::_getUniqueVoice(), and SFXALBuffer::_getUniqueVoice().
Signal< void(SFXBuffer*) > SFXBuffer::smBufferDestroyedSignal static
This signal is triggered from SFXBuffer's destructor so the sound system can keep track of buffers being released on the device.
Copyright © GarageGames, LLC. All Rights Reserved.