SceneCullingVolume Class Reference
Main Modules Class List Namespace List Online
SceneCullingVolume Class Reference
A volume used to include or exclude space in a scene.
#include <scene/culling/sceneCullingVolume.h>
Public Types
enum Type {
Includer,
Occluder
}
Type of culling.
Public Member Functions
SceneCullingVolume ()
Create an uninitialized culling volume.
SceneCullingVolume (Type type, const PlaneSetF &planes)
const PlaneSetF & getPlanes () const
Return the set of clipping planes that defines the culling volume.
Type getType () const
Return the type of volume defined by this culling volume, i.e.
bool isIncluder () const
Return true if this is an inclusion volume.
bool isOccluder () const
Return true if this is an occlusion volume.
Sorting
Before testing, culling volumes will be sorted by decreasing probability of causing test positives.
Thus, the sort point of a volume should be a rough metric of the amount of scene/screen space it covers.
Note that sort points for occluders are independent of sort points for includers.
F32 getSortPoint () const
Return the sort point value of the volume.
void setSortPoint (F32 value)
Testing
bool test (const Box3F &aabb) const
Return true if the volume accepts the given AABB.
bool test (const OrientedBox3F &obb) const
Return true if the volume accepts the given OBB.
bool test (const SphereF &sphere) const
Return true if the volume accepts the given sphere.
Protected Member Functions
template<typename B >
bool _testBounds (const B &bounds) const
Test the given bounds against this culling volume.
Protected Attributes
PlaneSetF mClippingPlanes
The set of clipping planes that defines the clipping volume for this culler.
F32 mSortPoint
Type mType
What type of culling volume this is.
Detailed Description
A volume used to include or exclude space in a scene.
Culling volumes are represented as sets of clipping planes.
Note
Culling is performed in world space so the plane data for culling volumes must be in world space too.
Member Enumeration Documentation
enum SceneCullingVolume::Type
Type of culling.
Enumerator
Includer
Occluder
Constructor & Destructor Documentation
SceneCullingVolume::SceneCullingVolume () inline
Create an uninitialized culling volume.
SceneCullingVolume::SceneCullingVolume (Type type, const PlaneSetF & planes) inline
Member Function Documentation
template<typename B > bool SceneCullingVolume::_testBounds (const B & bounds) const inline protected
Test the given bounds against this culling volume.
Note that we allow false positives here for includers. This will only cause an occasional object to be classified as intersecting when in fact it is outside. This is still better though than requiring the expensive intersection tests for all intersecting objects.
Returns
True if the culling volume accepts the given bounds.
References getPlanes(), PlaneSet< T >::isContained(), and isOccluder().
Referenced by test().
const PlaneSetF& SceneCullingVolume::getPlanes () const inline
Return the set of clipping planes that defines the culling volume.
References mClippingPlanes.
Referenced by _testBounds().
F32 SceneCullingVolume::getSortPoint () const inline
Return the sort point value of the volume.
The larger the value, the more likely the volume is to cause positive test results with bounding volumes.
References mSortPoint.
Type SceneCullingVolume::getType () const inline
Return the type of volume defined by this culling volume, i.e.
whether it includes or excludes space.
References mType.
Referenced by isIncluder(), and isOccluder().
bool SceneCullingVolume::isIncluder () const inline
Return true if this is an inclusion volume.
References getType(), and Includer.
bool SceneCullingVolume::isOccluder () const inline
Return true if this is an occlusion volume.
References getType(), and Occluder.
Referenced by _testBounds().
void SceneCullingVolume::setSortPoint (F32 value) inline
bool SceneCullingVolume::test (const Box3F & aabb) const inline
Return true if the volume accepts the given AABB.
References _testBounds().
bool SceneCullingVolume::test (const OrientedBox3F & obb) const inline
Return true if the volume accepts the given OBB.
References _testBounds().
bool SceneCullingVolume::test (const SphereF & sphere) const inline
Return true if the volume accepts the given sphere.
References _testBounds().
Member Data Documentation
PlaneSetF SceneCullingVolume::mClippingPlanes protected
The set of clipping planes that defines the clipping volume for this culler.
Referenced by getPlanes().
F32 SceneCullingVolume::mSortPoint protected
Referenced by getSortPoint().
Type SceneCullingVolume::mType protected
What type of culling volume this is.
Referenced by getType().
Copyright © GarageGames, LLC. All Rights Reserved.