ThreadSafeDeque< T > Class Template Reference
Main Modules Class List Namespace List Online
ThreadSafeDeque< T > Class Template Reference
Fast, lock-free double-ended queue for concurrent access.
#include <platform/threads/threadSafeDeque.h>
Classes
class DeleteNode
class Node
List node.
Public Types
typedef T ValueType
Public Member Functions
ThreadSafeDeque ()
Construct an empty deque.
~ThreadSafeDeque ()
void dumpDebug ()
bool isEmpty ()
void pushBack (const ValueType &value)
Append the given value to the list.
void pushFront (const ValueType &value)
Prepend the given value to the list.
bool tryPopBack (ValueType &outValue)
Try to take the rightmost value from the deque.
bool tryPopFront (ValueType &outValue)
Try to take the leftmost value from the deque.
Protected Types
typedef ThreadSafeRef< Node > NodeRef
Protected Member Functions
NodeRef getHead ()
NodeRef getTail ()
Protected Attributes
ThreadSafeFreeList< Node > mFreeList
Free list for list nodes.
NodeRef mHead
Reference to the head node.
S32 mNumValues
NodeRef mTail
Detailed Description
template<typename T>
class ThreadSafeDeque< T >
Fast, lock-free double-ended queue for concurrent access.
Parameters
T Type of list elements; must have default contructor.
Member Typedef Documentation
template<typename T> typedef ThreadSafeRef< Node > ThreadSafeDeque< T >::NodeRef protected
template<typename T> typedef T ThreadSafeDeque< T >::ValueType
Constructor & Destructor Documentation
template<typename T> ThreadSafeDeque< T >::ThreadSafeDeque () inline
Construct an empty deque.
template<typename T> ThreadSafeDeque< T >::~ThreadSafeDeque () inline
Member Function Documentation
template<typename T> void ThreadSafeDeque< T >::dumpDebug () inline
template<typename T > ThreadSafeDeque< T >::NodeRef ThreadSafeDeque< T >::getHead () protected
Returns
the leftmost node in the list.
Note
Updates the list state and may purge deleted nodes.
References ThreadSafeRef< T >::isTagged(), ThreadSafeDeque< T >::mHead, ThreadSafeDeque< T >::mTail, ThreadSafeRef< Node >::TAG_Set, ThreadSafeRef< Node >::TAG_Unset, and ThreadSafeRef< T >::trySetFromTo().
Referenced by ThreadSafeDeque< GBitmap * >::isEmpty(), ThreadSafeDeque< T >::pushFront(), and ThreadSafeDeque< T >::tryPopFront().
template<typename T > ThreadSafeDeque< T >::NodeRef ThreadSafeDeque< T >::getTail () protected
Returns
the rightmost node in the list.
Note
Updates the list state and may purge deleted nodes.
References ThreadSafeRef< T >::isTagged(), ThreadSafeDeque< T >::mHead, ThreadSafeDeque< T >::mTail, ThreadSafeRef< Node >::TAG_Set, ThreadSafeRef< Node >::TAG_Unset, and ThreadSafeRef< T >::trySetFromTo().
Referenced by ThreadSafeDeque< GBitmap * >::isEmpty(), ThreadSafeDeque< T >::pushBack(), and ThreadSafeDeque< T >::tryPopBack().
template<typename T> bool ThreadSafeDeque< T >::isEmpty (void) inline
Returns
true if the queue is empty.
Referenced by ThreadSafeDeque< GBitmap * >::~ThreadSafeDeque().
template<typename T > void ThreadSafeDeque< T >::pushBack (const ValueType & value)
Append the given value to the list.
References ThreadSafeDeque< T >::getTail(), ThreadSafeDeque< T >::Node::mFreeList, ThreadSafeDeque< T >::mHead, ThreadSafeDeque< T >::mNumValues, ThreadSafeDeque< T >::Node::Node(), ThreadSafeRef< Node >::TAG_FailIfSet, ThreadSafeRef< T >::trySetFromTo(), and ThreadSafeRef< Node >::unsafeWrite().
Referenced by AsyncBufferedInputStream< T, Stream >::_onArrival(), AsyncUpdateList::add(), ThreadSafeDeque< GBitmap * >::isEmpty(), and OggTheoraDecoder::reusePacket().
template<typename T > void ThreadSafeDeque< T >::pushFront (const ValueType & value)
Prepend the given value to the list.
References ThreadSafeDeque< T >::getHead(), ThreadSafeDeque< T >::Node::mFreeList, ThreadSafeDeque< T >::mHead, ThreadSafeDeque< T >::mNumValues, ThreadSafeDeque< T >::Node::Node(), ThreadSafeRef< Node >::TAG_FailIfSet, ThreadSafeRef< T >::trySetFromTo(), and ThreadSafeRef< Node >::unsafeWrite().
Referenced by ThreadSafeDeque< GBitmap * >::isEmpty().
template<typename T > bool ThreadSafeDeque< T >::tryPopBack (ValueType & outValue)
Try to take the rightmost value from the deque.
Fails if the deque is empty at the time the method tries to take a node from the list.
References ThreadSafeDeque< T >::getTail(), ThreadSafeDeque< T >::mNumValues, ThreadSafeRef< Node >::TAG_SetOrFail, and ThreadSafeRef< T >::trySetFromTo().
Referenced by ThreadSafeDeque< GBitmap * >::isEmpty().
template<typename T > bool ThreadSafeDeque< T >::tryPopFront (ValueType & outValue)
Try to take the leftmost value from the deque.
Fails if the deque is empty at the time the method tries to take a node from the list.
References ThreadSafeDeque< T >::getHead(), ThreadSafeDeque< T >::mNumValues, ThreadSafeRef< Node >::TAG_SetOrFail, and ThreadSafeRef< T >::trySetFromTo().
Referenced by ThreadSafeDeque< GBitmap * >::isEmpty(), SFXInternal::PurgeDeadBuffers(), AsyncBufferedInputStream< T, Stream >::read(), AsyncBufferedInputStream< T, Stream >::~AsyncBufferedInputStream(), and ThreadSafeDeque< GBitmap * >::~ThreadSafeDeque().
Member Data Documentation
template<typename T> ThreadSafeFreeList< Node > ThreadSafeDeque< T >::mFreeList protected
Free list for list nodes.
template<typename T> NodeRef ThreadSafeDeque< T >::mHead protected
Reference to the head node.
Referenced by ThreadSafeDeque< T >::getHead(), ThreadSafeDeque< T >::getTail(), ThreadSafeDeque< T >::pushBack(), and ThreadSafeDeque< T >::pushFront().
template<typename T> S32 ThreadSafeDeque< T >::mNumValues protected
Referenced by ThreadSafeDeque< T >::pushBack(), ThreadSafeDeque< T >::pushFront(), ThreadSafeDeque< T >::tryPopBack(), and ThreadSafeDeque< T >::tryPopFront().
template<typename T> NodeRef ThreadSafeDeque< T >::mTail protected
Referenced by ThreadSafeDeque< T >::getHead(), and ThreadSafeDeque< T >::getTail().
Copyright © GarageGames, LLC. All Rights Reserved.