MaterialManager Class Reference
Main Modules Class List Namespace List Online
MaterialManager Class Reference
#include <materials/materialManager.h>
Public Types
typedef Signal< void()> FlushSignal
Signal used to notify systems that procedural shaders have been flushed.
Public Member Functions
MaterialManager ()
~MaterialManager ()
Material * allocateAndRegister (const String &objectName, const String &mapToName=String())
BaseMatInstance * createMatInstance (const String &matName)
BaseMatInstance * createMatInstance (const String &matName, const GFXVertexFormat *vertexFormat)
BaseMatInstance * createMatInstance (const String &matName, const FeatureSet &features, const GFXVertexFormat *vertexFormat)
BaseMatInstance * createMeshDebugMatInstance (const ColorF &meshColor)
BaseMatInstance * createWarningMatInstance ()
Allocate and return an instance of special materials. Caller is responsible for the memory.
void dumpMaterialInstances (BaseMaterialDefinition *target=NULL) const
void flushAndReInitInstances ()
Flushes all the procedural shaders and re-initializes all the active materials instances immediately.
void flushInstance (BaseMaterialDefinition *target)
U32 getDefaultAnisotropy () const
Get the default texture anisotropy.
const FeatureSet & getDefaultFeatures () const
The default feature set for materials.
F32 getDeltaTime () const
const FeatureSet & getExclusionFeatures () const
The feature exclusion list for disabling features.
FlushSignal & getFlushSignal ()
Returns the signal used to notify systems that the procedural shaders have been flushed.
U32 getLastUpdateTime () const
String getMapEntry (const String &textureName) const
Material * getMaterialDefinitionByName (const String &matName)
SimSet * getMaterialSet ()
BaseMatInstance * getMeshDebugMatInstance (const ColorF &meshColor)
bool getPrePassEnabled () const
Get the prepass enabled state.
F32 getTotalTime () const
BaseMatInstance * getWarningMatInstance ()
Gets the global warning material instance, callers should not free this copy.
void mapMaterial (const String &textureName, const String &materialName)
void recalcFeaturesFromPrefs ()
void reInitInstance (BaseMaterialDefinition *target)
Re-initializes the material instances for a specific target material.
void setPrePassEnabled (bool enabled)
Set the prepass enabled state.
void updateTime ()
Static Public Member Functions
static const char * getSingletonName ()
Static Public Member Functions inherited from ManagedSingleton< MaterialManager >
static void createSingleton ()
Create the singleton instance.
static void deleteSingleton ()
Destroy the singleton instance.
static MaterialManager * instance ()
Return the singleton instance.
static MaterialManager * instanceOrNull ()
Return the singleton instance or NULL if it has been deleted or not yet constructed.
Protected Types
typedef Map< U32, BaseMatInstance * > DebugMaterialMap
typedef Map< String, String > MaterialMap
Protected Member Functions
bool _handleGFXEvent (GFXDevice::GFXDeviceEventType event)
void _onDisableMaterialFeature ()
Called when one of the feature disabling $pref::s are changed.
void _onLMActivate (const char *lm, bool activate)
void _track (MatInstance *)
void _untrack (MatInstance *)
void _updateDefaultAnisotropy ()
Called when $pref::Video::defaultAnisotropy is changed.
Protected Attributes
F32 mAccumTime
S32 mDefaultAnisotropy
The default max anisotropy used in texture filtering.
FeatureSet mDefaultFeatures
The default material features.
F32 mDt
FeatureSet mExclusionFeatures
The feature exclusion set.
bool mFlushAndReInit
If set we flush and reinitialize all materials at the start of the next rendered frame.
FlushSignal mFlushSignal
Signal used to notify systems that procedural shaders have been flushed.
U32 mLastTime
MaterialMap mMaterialMap
SimSet * mMaterialSet
Vector< BaseMatInstance * > mMatInstanceList
DebugMaterialMap mMeshDebugMaterialInsts
bool mUsingPrePass
BaseMatInstance * mWarningInst
Member Typedef Documentation
typedef Map<U32, BaseMatInstance *> MaterialManager::DebugMaterialMap protected
typedef Signal<void()> MaterialManager::FlushSignal
Signal used to notify systems that procedural shaders have been flushed.
typedef Map<String, String> MaterialManager::MaterialMap protected
Constructor & Destructor Documentation
MaterialManager::MaterialManager ()
MaterialManager::~MaterialManager ()
Member Function Documentation
bool MaterialManager::_handleGFXEvent (GFXDevice::GFXDeviceEventType event) protected
void MaterialManager::_onDisableMaterialFeature () inline protected
Called when one of the feature disabling $pref::s are changed.
void MaterialManager::_onLMActivate (const char * lm, bool activate) protected
See also
LightManager::smActivateSignal
void MaterialManager::_track (MatInstance *) protected
void MaterialManager::_untrack (MatInstance *) protected
void MaterialManager::_updateDefaultAnisotropy () protected
Called when $pref::Video::defaultAnisotropy is changed.
Material* MaterialManager::allocateAndRegister (const String & objectName, const String & mapToName = String())
Referenced by getSingletonName().
BaseMatInstance* MaterialManager::createMatInstance (const String & matName)
Referenced by getSingletonName().
BaseMatInstance* MaterialManager::createMatInstance (const String & matName, const GFXVertexFormat * vertexFormat)
BaseMatInstance* MaterialManager::createMatInstance (const String & matName, const FeatureSet & features, const GFXVertexFormat * vertexFormat)
BaseMatInstance* MaterialManager::createMeshDebugMatInstance (const ColorF & meshColor)
Referenced by getPrePassEnabled().
BaseMatInstance* MaterialManager::createWarningMatInstance ()
Allocate and return an instance of special materials. Caller is responsible for the memory.
Referenced by getDefaultAnisotropy().
void MaterialManager::dumpMaterialInstances (BaseMaterialDefinition * target = NULL) const
Referenced by getPrePassEnabled().
void MaterialManager::flushAndReInitInstances ()
Flushes all the procedural shaders and re-initializes all the active materials instances immediately.
Referenced by getFlushSignal().
void MaterialManager::flushInstance (BaseMaterialDefinition * target)
Referenced by getFlushSignal().
U32 MaterialManager::getDefaultAnisotropy () const inline
Get the default texture anisotropy.
References createWarningMatInstance(), getWarningMatInstance(), and mDefaultAnisotropy.
const FeatureSet& MaterialManager::getDefaultFeatures () const inline
The default feature set for materials.
References mDefaultFeatures.
F32 MaterialManager::getDeltaTime () const inline
References mDt.
const FeatureSet& MaterialManager::getExclusionFeatures () const inline
The feature exclusion list for disabling features.
References mExclusionFeatures, and recalcFeaturesFromPrefs().
FlushSignal& MaterialManager::getFlushSignal () inline
Returns the signal used to notify systems that the procedural shaders have been flushed.
References flushAndReInitInstances(), flushInstance(), mFlushSignal, and reInitInstance().
U32 MaterialManager::getLastUpdateTime () const inline
References mLastTime.
String MaterialManager::getMapEntry (const String & textureName) const
Referenced by getSingletonName().
Material* MaterialManager::getMaterialDefinitionByName (const String & matName)
Referenced by getSingletonName().
SimSet* MaterialManager::getMaterialSet ()
Referenced by getSingletonName().
BaseMatInstance* MaterialManager::getMeshDebugMatInstance (const ColorF & meshColor)
Referenced by getPrePassEnabled().
bool MaterialManager::getPrePassEnabled () const inline
Get the prepass enabled state.
References createMeshDebugMatInstance(), dumpMaterialInstances(), getMeshDebugMatInstance(), mUsingPrePass, and updateTime().
static const char* MaterialManager::getSingletonName () inline static
References allocateAndRegister(), createMatInstance(), getMapEntry(), getMaterialDefinitionByName(), getMaterialSet(), and mapMaterial().
F32 MaterialManager::getTotalTime () const inline
References mAccumTime.
BaseMatInstance* MaterialManager::getWarningMatInstance ()
Gets the global warning material instance, callers should not free this copy.
Referenced by getDefaultAnisotropy().
void MaterialManager::mapMaterial (const String & textureName, const String & materialName)
Referenced by getSingletonName().
void MaterialManager::recalcFeaturesFromPrefs ()
Referenced by getExclusionFeatures().
void MaterialManager::reInitInstance (BaseMaterialDefinition * target)
Re-initializes the material instances for a specific target material.
Referenced by getFlushSignal().
void MaterialManager::setPrePassEnabled (bool enabled) inline
Set the prepass enabled state.
References mUsingPrePass.
void MaterialManager::updateTime ()
Referenced by getPrePassEnabled().
Member Data Documentation
F32 MaterialManager::mAccumTime protected
Referenced by getTotalTime().
S32 MaterialManager::mDefaultAnisotropy protected
The default max anisotropy used in texture filtering.
Referenced by getDefaultAnisotropy().
FeatureSet MaterialManager::mDefaultFeatures protected
The default material features.
Referenced by getDefaultFeatures().
F32 MaterialManager::mDt protected
Referenced by getDeltaTime().
FeatureSet MaterialManager::mExclusionFeatures protected
The feature exclusion set.
Referenced by getExclusionFeatures().
bool MaterialManager::mFlushAndReInit protected
If set we flush and reinitialize all materials at the start of the next rendered frame.
FlushSignal MaterialManager::mFlushSignal protected
Signal used to notify systems that procedural shaders have been flushed.
Referenced by getFlushSignal().
U32 MaterialManager::mLastTime protected
Referenced by getLastUpdateTime().
MaterialMap MaterialManager::mMaterialMap protected
SimSet* MaterialManager::mMaterialSet protected
Vector<BaseMatInstance*> MaterialManager::mMatInstanceList protected
DebugMaterialMap MaterialManager::mMeshDebugMaterialInsts protected
bool MaterialManager::mUsingPrePass protected
Referenced by getPrePassEnabled(), and setPrePassEnabled().
BaseMatInstance* MaterialManager::mWarningInst protected
Copyright © GarageGames, LLC. All Rights Reserved.