SceneCullingState Class Reference
Main Modules Class List Namespace List Online
SceneCullingState Class Reference
An object that gathers the culling state for a scene.
#include <scene/culling/sceneCullingState.h>
Public Member Functions
SceneCullingState (SceneManager *sceneManager, const SceneCameraState &cameraState)
void clearExtraPlanesCull ()
Clear planes for extra culling.
void debugRenderCullingVolumes () const
Queue debug visualizations of the culling volumes of all currently selected zones (or, if no zone is selected, all volumes in the outdoor zone) to the debug drawer.
const Frustum & getCameraFrustum () const
Return the root frustum which is used to set up scene visibility.
const SceneCameraState & getCameraState () const
Return the viewing state that defines how the scene is being viewed.
const Frustum & getCullingFrustum () const
Return the root frustum which is used to set up scene visibility.
const SceneCullingVolume & getRootVolume () const
Return the root culling volume that corresponds to the camera frustum.
SceneManager * getSceneManager () const
Return the scene which is being culled in this state.
bool isOccludedWithExtraPlanesCull (const Box3F &box) const
Check extra planes culling.
void setExtraPlanesCull (const PlaneSetF &cull)
Set planes for extra culling.
Zones
bool disableZoneCulling () const
If true, culling will only be performed against the root frustum and not against frustums of individual zones.
void disableZoneCulling (bool value)
bool isWithinVisibleZone (SceneObject *object) const
Return true if any of the zones that the object is currently are visible.
const BitVector & getZoneVisibilityFlags () const
Return a bit vector with one bit for each zone in the scene.
const SceneZoneCullingState & getZoneState (U32 zoneId) const
Return the culling state for a particular zone.
SceneZoneCullingState & getZoneState (U32 zoneId)
Returns the culling state for a particular zone.
bool addCullingVolumeToZone (U32 zoneId, const SceneCullingVolume &volume)
Add a culling volume to the visibility state of the given zone.
bool addCullingVolumeToZone (U32 zoneId, SceneCullingVolume::Type type, const AnyPolyhedron &polyhedron)
Copy the data from the given polyhedron to the culling state, create a new culling volume it and add it to the current culling state of the given zone.
bool createCullingVolume (const Point3F *vertices, U32 numVertices, SceneCullingVolume::Type type, SceneCullingVolume &outVolume)
Create a new culling volume by extruding the given polygon away from the viewpoint.
Memory Management
Rather than allocating a lot of individual point and plane data for the culling volumes, it is more efficient to batch allocate chunks of memory and then release all the memory for all culling volumes in one go.
This is facilitated by this interface.
void * allocateData (U32 size)
Allocate memory from this culling state.
template<typename T >
T * allocateData (U32 num)
Allocate memory for num instances of T from this culling state.
Static Public Attributes
static bool smDisableTerrainOcclusion
Used to disable the somewhat expensive terrain occlusion testing done in during scene culling.
static bool smDisableZoneCulling
Whether to force zone culling to off by default.
Occluder Restrictions
Size restrictions on occlusion culling volumes.
Any occlusion volume that does not meet these minimum requirements is not accepted into the rendering state.
Having independent restrictions on both width and height allows filtering out occluders that might have a lot of area but only by covering very thin stretches of the screen.
static U32 smMaxOccludersPerZone
If more than this number of occlusion volumes are added to a ZoneState, then the occlusions volumes corresponding to the smallest amount of screen real estate get dropped such as to never exceed this total number of occlusion volumes.
static F32 smOccluderMinHeightPercentage
Percentage of camera-space frustum near plane height that an occlusion culler must at least fill in order to not be rejected.
static F32 smOccluderMinWidthPercentage
Percentage of camera-space frustum near plane width that an occlusion culler must at least fill in order to not be rejected.
Protected Attributes
Vector< SceneObject * > mAddedOccluderObjects
Occluders that have been added to this render state.
SceneCameraState mCameraState
The viewing state that defines how the scene is being viewed.
Frustum mCullingFrustum
The root culling frustum, which may be different from the camera frustum.
DataChunker mDataChunker
Allocator for culling data that can be freed in one go when the culling state is freed.
bool mDisableTerrainOcclusion
If true, occlusion checks will not be done against the terrains in the scene.
bool mDisableZoneCulling
If true, all objects will only be tested against the root frustum.
PlaneSetF mExtraPlanesCull
Extra planes for culling.
SceneCullingVolume mRootVolume
The root culling volume corresponding to the culling frustum.
SceneManager * mSceneManager
Scene which is being culled.
Vector< SceneZoneCullingState > mZoneStates
ZoneState entries for all zones in the scene.
BitVector mZoneVisibilityFlags
Visibility and Occlusion
enum CullOptions {
CullEditorOverrides = BIT(0),
DontCullRenderDisabled = BIT(1)
}
U32 cullObjects (SceneObject **objects, U32 numObjects, U32 cullOptions=0) const
Cull the given list of objects according to the current culling state.
bool isCulled (SceneObject *object) const
Return true if the given object is culled according to the current culling state.
bool isCulled (const Box3F &aabb, const U32 *zones, U32 numZones) const
Return true if the given AABB is culled in any of the given zones.
bool isCulled (const OrientedBox3F &obb, const U32 *zones, U32 numZones) const
Return true if the given OBB is culled in any of the given zones.
bool isCulled (const SphereF &sphere, const U32 *zones, U32 numZones) const
Return true if the given sphere is culled in any of the given zones.
bool isOccluded (SceneObject *object) const
Return true if the given object is occluded according to the current culling state.
bool isOccluded (const Box3F &aabb, const U32 *zones, U32 numZones) const
Return true if the given AABB is occluded according to the current culling state.
bool isOccluded (const OrientedBox3F &obb, const U32 *zones, U32 numZones) const
Return true if the given OBB is occluded according to the current culling state.
bool isOccluded (const SphereF &sphere, const U32 *zones, U32 numZones) const
Return true if the given sphere is occluded according to the current culling state.
void addOccluder (SceneObject *object)
Add the occlusion information contained in the given object.
bool isOccludedByTerrain (SceneObject *object) const
Test whether the given object is occluded by any of the terrains in the scene.
void setDisableTerrainOcclusion (bool value)
Set whether isCulled() should do terrain occlusion checks or not.
Detailed Description
An object that gathers the culling state for a scene.
Member Enumeration Documentation
enum SceneCullingState::CullOptions
Enumerator
CullEditorOverrides
Cull objects that have their SceneObject::DisableCullingInEditorFlag set.
By default, these objects will not get culled if the editor is active.
DontCullRenderDisabled
Do not cull objects that are render-disabled.
See also
SceneObject::isRenderEnabled()
Constructor & Destructor Documentation
SceneCullingState::SceneCullingState (SceneManager * sceneManager, const SceneCameraState & cameraState)
Member Function Documentation
bool SceneCullingState::addCullingVolumeToZone (U32 zoneId, const SceneCullingVolume & volume)
Add a culling volume to the visibility state of the given zone.
Parameters
zoneId ID of zone to which to add the given frustum's visibility information.
volume A culling volume. Note that the data in the volume must have a lifetime at least as long as the culling state.
Returns
True if the visibility state of the zone has changed, i.e. if the volume was either added in whole or merged with an existing set of planes. If the visibility state of the zone has not changed, returns false.
Referenced by getZoneState().
bool SceneCullingState::addCullingVolumeToZone (U32 zoneId, SceneCullingVolume::Type type, const AnyPolyhedron & polyhedron)
Copy the data from the given polyhedron to the culling state, create a new culling volume it and add it to the current culling state of the given zone.
Parameters
zoneId ID of zone to which to add the given frustum's visibility information.
type Which type of culling volume to add.
polyhedron Polyhedron describing the space of the culling volume.
void SceneCullingState::addOccluder (SceneObject * object)
Add the occlusion information contained in the given object.
Note
This should only be called after all positive frustums have been added to the zone state.
Referenced by isCulled().
void* SceneCullingState::allocateData (U32 size) inline
Allocate memory from this culling state.
The memory is freed when the culling state is destroyed.
References DataChunker::alloc().
template<typename T > T* SceneCullingState::allocateData (U32 num) inline
Allocate memory for num instances of T from this culling state.
References allocateData(), debugRenderCullingVolumes(), and T.
Referenced by allocateData().
void SceneCullingState::clearExtraPlanesCull () inline
Clear planes for extra culling.
bool SceneCullingState::createCullingVolume (const Point3F * vertices, U32 numVertices, SceneCullingVolume::Type type, SceneCullingVolume & outVolume)
Create a new culling volume by extruding the given polygon away from the viewpoint.
Parameters
vertices Array of polygon vertices.
numVertices Number of vertices in vertices.
type Type of culling volume to create.
outVolume (out) Receives the generated volume, if successful.
Returns
True if a volume could be generated from the given polygon or false if not.
Referenced by getZoneState().
U32 SceneCullingState::cullObjects (SceneObject ** objects, U32 numObjects, U32 cullOptions = 0) const
Cull the given list of objects according to the current culling state.
Parameters
object Array of objects. This array will be modified in place.
numObjects Number of objects in objects.
cullOptions Combination of CullOptions.
Returns
Number of objects remaining in the list.
Referenced by isCulled().
void SceneCullingState::debugRenderCullingVolumes () const
Queue debug visualizations of the culling volumes of all currently selected zones (or, if no zone is selected, all volumes in the outdoor zone) to the debug drawer.
Referenced by allocateData().
bool SceneCullingState::disableZoneCulling () const inline
If true, culling will only be performed against the root frustum and not against frustums of individual zones.
Note
This also disables occluders as these are added to the zone frustums.
References mDisableZoneCulling.
void SceneCullingState::disableZoneCulling (bool value) inline
References isWithinVisibleZone().
const Frustum& SceneCullingState::getCameraFrustum () const inline
Return the root frustum which is used to set up scene visibility.
References getCameraState(), and SceneCameraState::getFrustum().
Referenced by SceneRenderState::getCameraFrustum().
const SceneCameraState& SceneCullingState::getCameraState () const inline
Return the viewing state that defines how the scene is being viewed.
References mCameraState.
Referenced by getCameraFrustum(), SceneRenderState::getCameraPosition(), SceneRenderState::getCameraTransform(), and SceneRenderState::getViewport().
const Frustum& SceneCullingState::getCullingFrustum () const inline
Return the root frustum which is used to set up scene visibility.
References mCullingFrustum.
Referenced by SceneRenderState::getCullingFrustum().
const SceneCullingVolume& SceneCullingState::getRootVolume () const inline
Return the root culling volume that corresponds to the camera frustum.
Note
This volume omits the near and far plane of the frustum's polyhedron as these will be tested separately during culling. Testing them repeatedly just wastes time.
References mRootVolume.
SceneManager* SceneCullingState::getSceneManager () const inline
Return the scene which is being culled in this state.
References mSceneManager.
const SceneZoneCullingState& SceneCullingState::getZoneState (U32 zoneId) const inline
Return the culling state for a particular zone.
Parameters
zoneId Numeric ID of zone.
References Vector< T >::size().
Referenced by getZoneState().
SceneZoneCullingState& SceneCullingState::getZoneState (U32 zoneId) inline
Returns the culling state for a particular zone.
Parameters
zoneId Numeric ID of zone.
References addCullingVolumeToZone(), createCullingVolume(), and getZoneState().
const BitVector& SceneCullingState::getZoneVisibilityFlags () const inline
Return a bit vector with one bit for each zone in the scene.
If the bit is set, the zone has includer culling volumes attached to it and thus is visible.
References mZoneVisibilityFlags.
bool SceneCullingState::isCulled (SceneObject * object) const inline
Return true if the given object is culled according to the current culling state.
References addOccluder(), cullObjects(), isOccluded(), and isOccludedByTerrain().
bool SceneCullingState::isCulled (const Box3F & aabb, const U32 * zones, U32 numZones) const
Return true if the given AABB is culled in any of the given zones.
bool SceneCullingState::isCulled (const OrientedBox3F & obb, const U32 * zones, U32 numZones) const
Return true if the given OBB is culled in any of the given zones.
bool SceneCullingState::isCulled (const SphereF & sphere, const U32 * zones, U32 numZones) const
Return true if the given sphere is culled in any of the given zones.
bool SceneCullingState::isOccluded (SceneObject * object) const
Return true if the given object is occluded according to the current culling state.
Referenced by isCulled().
bool SceneCullingState::isOccluded (const Box3F & aabb, const U32 * zones, U32 numZones) const
Return true if the given AABB is occluded according to the current culling state.
bool SceneCullingState::isOccluded (const OrientedBox3F & obb, const U32 * zones, U32 numZones) const
Return true if the given OBB is occluded according to the current culling state.
bool SceneCullingState::isOccluded (const SphereF & sphere, const U32 * zones, U32 numZones) const
Return true if the given sphere is occluded according to the current culling state.
bool SceneCullingState::isOccludedByTerrain (SceneObject * object) const
Test whether the given object is occluded by any of the terrains in the scene.
Referenced by isCulled().
bool SceneCullingState::isOccludedWithExtraPlanesCull (const Box3F & box) const inline
Check extra planes culling.
References PlaneSet< T >::getNumPlanes(), T, and PlaneSet< T >::testPotentialIntersection().
bool SceneCullingState::isWithinVisibleZone (SceneObject * object) const
Return true if any of the zones that the object is currently are visible.
Referenced by disableZoneCulling().
void SceneCullingState::setDisableTerrainOcclusion (bool value) inline
Set whether isCulled() should do terrain occlusion checks or not.
void SceneCullingState::setExtraPlanesCull (const PlaneSetF & cull) inline
Set planes for extra culling.
Member Data Documentation
Vector< SceneObject* > SceneCullingState::mAddedOccluderObjects protected
Occluders that have been added to this render state.
Adding an occluder does not necessarily result in an occluder volume being added. To not repeatedly try to process the same occluder object, all objects that are added are recorded here.
SceneCameraState SceneCullingState::mCameraState protected
The viewing state that defines how the scene is being viewed.
Referenced by getCameraState().
Frustum SceneCullingState::mCullingFrustum protected
The root culling frustum, which may be different from the camera frustum.
Referenced by getCullingFrustum().
DataChunker SceneCullingState::mDataChunker protected
Allocator for culling data that can be freed in one go when the culling state is freed.
bool SceneCullingState::mDisableTerrainOcclusion protected
If true, occlusion checks will not be done against the terrains in the scene.
bool SceneCullingState::mDisableZoneCulling protected
If true, all objects will only be tested against the root frustum.
Referenced by disableZoneCulling().
PlaneSetF SceneCullingState::mExtraPlanesCull protected
Extra planes for culling.
SceneCullingVolume SceneCullingState::mRootVolume protected
The root culling volume corresponding to the culling frustum.
Referenced by getRootVolume().
SceneManager* SceneCullingState::mSceneManager protected
Scene which is being culled.
Referenced by getSceneManager().
Vector< SceneZoneCullingState > SceneCullingState::mZoneStates protected
ZoneState entries for all zones in the scene.
BitVector SceneCullingState::mZoneVisibilityFlags protected
Referenced by getZoneVisibilityFlags().
bool SceneCullingState::smDisableTerrainOcclusion static
Used to disable the somewhat expensive terrain occlusion testing done in during scene culling.
bool SceneCullingState::smDisableZoneCulling static
Whether to force zone culling to off by default.
U32 SceneCullingState::smMaxOccludersPerZone static
If more than this number of occlusion volumes are added to a ZoneState, then the occlusions volumes corresponding to the smallest amount of screen real estate get dropped such as to never exceed this total number of occlusion volumes.
F32 SceneCullingState::smOccluderMinHeightPercentage static
Percentage of camera-space frustum near plane height that an occlusion culler must at least fill in order to not be rejected.
Note
The height computed for occluders is only an estimate.
F32 SceneCullingState::smOccluderMinWidthPercentage static
Percentage of camera-space frustum near plane width that an occlusion culler must at least fill in order to not be rejected.
Note
The width computed for occluders is only an estimate.
Copyright © GarageGames, LLC. All Rights Reserved.