NamedTexTarget Class Reference
Main Modules Class List Namespace List Online
NamedTexTarget Class Reference
#include <materials/matTextureTarget.h>
Public Types
typedef Delegate< GFXTextureObject *(U32)> TexDelegate
The delegate used to override the getTexture method.
Public Member Functions
NamedTexTarget ()
virtual ~NamedTexTarget ()
ConditionerFeature * getConditioner () const
const String & getName () const
Returns the target name we were registered with.
void getShaderMacros (Vector< GFXShaderMacro > *outMacros)
GFXTextureObject * getTexture (U32 index=0) const
TexDelegate & getTextureDelegate ()
const TexDelegate & getTextureDelegate () const
const RectI & getViewport () const
bool isRegistered () const
bool registerWithName (const String &name)
void release ()
Release all the textures.
void setConditioner (ConditionerFeature *cond)
void setSamplerState (const GFXSamplerStateDesc &desc)
void setTexture (GFXTextureObject *tex)
void setTexture (U32 index, GFXTextureObject *tex)
void setupSamplerState (GFXSamplerStateDesc *desc) const
void setViewport (const RectI &viewport)
void unregister ()
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Static Public Member Functions
static NamedTexTarget * find (const String &name)
Protected Types
typedef Map< String, NamedTexTarget * > TargetMap
Protected Attributes
ConditionerFeature * mConditioner
bool mIsRegistered
String mName
The target name we were registered with.
GFXSamplerStateDesc mSamplerDesc
GFXTexHandle mTex [4]
The held textures.
TexDelegate mTexDelegate
RectI mViewport
Static Protected Attributes
static TargetMap smTargets
Additional Inherited Members
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Member Typedef Documentation
typedef Map<String,NamedTexTarget*> NamedTexTarget::TargetMap protected
typedef Delegate<GFXTextureObject*(U32)> NamedTexTarget::TexDelegate
The delegate used to override the getTexture method.
See also
getTexture
Constructor & Destructor Documentation
NamedTexTarget::NamedTexTarget ()
virtual NamedTexTarget::~NamedTexTarget () virtual
Member Function Documentation
static NamedTexTarget* NamedTexTarget::find (const String & name) static
ConditionerFeature* NamedTexTarget::getConditioner () const inline
References getShaderMacros(), and mConditioner.
const String& NamedTexTarget::getName () const inline
Returns the target name we were registered with.
References mName.
void NamedTexTarget::getShaderMacros (Vector< GFXShaderMacro > * outMacros)
Referenced by getConditioner().
GFXTextureObject * NamedTexTarget::getTexture (U32 index = 0) const inline
References mTex, and mTexDelegate.
Referenced by setTexture().
TexDelegate& NamedTexTarget::getTextureDelegate () inline
See also
getTexture
References mTexDelegate.
const TexDelegate& NamedTexTarget::getTextureDelegate () const inline
References mTexDelegate, and release().
const RectI& NamedTexTarget::getViewport () const inline
References mViewport.
bool NamedTexTarget::isRegistered () const inline
References mIsRegistered.
Referenced by PostEffect::_onTextureEvent().
bool NamedTexTarget::registerWithName (const String & name)
void NamedTexTarget::release ()
Release all the textures.
Referenced by getTextureDelegate().
void NamedTexTarget::setConditioner (ConditionerFeature * cond) inline
References mConditioner.
void NamedTexTarget::setSamplerState (const GFXSamplerStateDesc & desc) inline
References mSamplerDesc.
void NamedTexTarget::setTexture (GFXTextureObject * tex) inline
References getTexture(), and setTexture().
Referenced by setTexture().
void NamedTexTarget::setTexture (U32 index, GFXTextureObject * tex)
void NamedTexTarget::setupSamplerState (GFXSamplerStateDesc * desc) const inline
References mSamplerDesc.
void NamedTexTarget::setViewport (const RectI & viewport) inline
References mViewport.
void NamedTexTarget::unregister ()
Member Data Documentation
ConditionerFeature* NamedTexTarget::mConditioner protected
Referenced by getConditioner(), and setConditioner().
bool NamedTexTarget::mIsRegistered protected
Referenced by isRegistered().
String NamedTexTarget::mName protected
The target name we were registered with.
Referenced by getName().
GFXSamplerStateDesc NamedTexTarget::mSamplerDesc protected
Referenced by setSamplerState(), and setupSamplerState().
GFXTexHandle NamedTexTarget::mTex[4] protected
The held textures.
Referenced by getTexture().
TexDelegate NamedTexTarget::mTexDelegate protected
Referenced by getTexture(), and getTextureDelegate().
RectI NamedTexTarget::mViewport protected
Referenced by getViewport(), and setViewport().
TargetMap NamedTexTarget::smTargets static protected
Copyright © GarageGames, LLC. All Rights Reserved.