DecalSphere Class Reference
Main Modules Class List Namespace List Online
DecalSphere Class Reference
A bounding sphere in world space and a list of DecalInstance(s) contained by it.
#include <T3D/decal/decalSphere.h>
Public Member Functions
DecalSphere ()
DecalSphere (const Point3F &position, F32 radius)
bool tryAddItem (DecalInstance *inst)
void updateWorldSphere ()
Recompute mWorldSphere from the current instance list.
void updateZoning (SceneZoneSpaceManager *zoneManager)
Recompute the zoning information from the current bounds.
Public Attributes
Vector< DecalInstance * > mItems
Decal instances in this sphere.
SphereF mWorldSphere
World-space sphere corresponding to this DecalSphere.
Vector< U32 > mZones
Zones that intersect with this sphere.
Static Public Attributes
static F32 smDistanceTolerance
static F32 smRadiusTolerance
Detailed Description
A bounding sphere in world space and a list of DecalInstance(s) contained by it.
DecalInstance(s) are organized/binned in this fashion as a lookup and culling optimization.
Constructor & Destructor Documentation
DecalSphere::DecalSphere () inline
References mItems, and mZones.
DecalSphere::DecalSphere (const Point3F & position, F32 radius) inline
References SphereF::center, mItems, mWorldSphere, mZones, SphereF::radius, updateWorldSphere(), and updateZoning().
Member Function Documentation
bool DecalSphere::tryAddItem (DecalInstance * inst)
void DecalSphere::updateWorldSphere ()
Recompute mWorldSphere from the current instance list.
Referenced by DecalSphere().
void DecalSphere::updateZoning (SceneZoneSpaceManager * zoneManager)
Recompute the zoning information from the current bounds.
Referenced by DecalSphere().
Member Data Documentation
Vector< DecalInstance* > DecalSphere::mItems
Decal instances in this sphere.
Referenced by DecalSphere().
SphereF DecalSphere::mWorldSphere
World-space sphere corresponding to this DecalSphere.
Referenced by DecalSphere().
Vector< U32 > DecalSphere::mZones
Zones that intersect with this sphere.
If this is empty, the zoning state of the sphere is uninitialized.
Referenced by DecalSphere().
F32 DecalSphere::smDistanceTolerance static
F32 DecalSphere::smRadiusTolerance static
Copyright © GarageGames, LLC. All Rights Reserved.