GFXD3D9CardProfiler Class Reference
Main Modules Class List Namespace List Online
GFXD3D9CardProfiler Class Reference
#include <gfx/D3D9/gfxD3D9CardProfiler.h>
Public Member Functions
GFXD3D9CardProfiler (U32 adapterIndex)
~GFXD3D9CardProfiler ()
void init ()
Set load script files and generally initialize things.
Public Member Functions inherited from GFXCardProfiler
GFXCardProfiler ()
Called for a profile for a given device.
virtual ~GFXCardProfiler ()
U32 queryProfile (const String &cap)
Called to query a capability.
U32 queryProfile (const String &cap, U32 defaultValue)
Same as queryProfile(), but a default can be specified to indicate what value should be returned if the profiler doesn't know anything about it.
void setCapability (const String &cap, U32 value)
Set the specified capability to the specified value.
bool checkFormat (const GFXFormat fmt, const GFXTextureProfile *profile, bool &inOutAutogenMips)
Queries support for the specified texture format, and texture profile.
const String & getVersionString () const
const String & getCardString () const
const String & getChipString () const
U32 getVideoMemoryInMB () const
Protected Member Functions
bool _queryCardCap (const String &query, U32 &foundResult)
Implementation specific query code.
bool _queryFormat (const GFXFormat fmt, const GFXTextureProfile *profile, bool &inOutAutogenMips)
const String & getRendererString () const
void setupCardCapabilities ()
Protected Member Functions inherited from GFXCardProfiler
void loadProfileScript (const char *scriptName)
Load a specified script file from the profiles directory, if it exists.
void loadProfileScripts (const String &render, const String &vendor, const String &card, const String &version)
Load the script files in order for the specified card profile tuple.
String strippedString (const char *string)
Additional Inherited Members
Protected Attributes inherited from GFXCardProfiler
Map< String, U32 > mCapDictionary
Capability dictionary.
String mVersionString
String mCardDescription
String mChipSet
U32 mVideoMemory
Constructor & Destructor Documentation
GFXD3D9CardProfiler::GFXD3D9CardProfiler (U32 adapterIndex)
GFXD3D9CardProfiler::~GFXD3D9CardProfiler ()
Member Function Documentation
bool GFXD3D9CardProfiler::_queryCardCap (const String & query, U32 & foundResult) protected virtual
Implementation specific query code.
This function is meant to be overridden by the specific implementation class.
Some query strings are handled by the external implementation while others must be done by the specific implementation. This is given first chance to return a result, then the generic rules are applied.
Parameters
query Capability being queried.
foundResult Result to return to the caller. If the function returns true then this value is returned as the result of the query.
Implements GFXCardProfiler.
Referenced by getRendererString().
bool GFXD3D9CardProfiler::_queryFormat (const GFXFormat fmt, const GFXTextureProfile * profile, bool & inOutAutogenMips) protected virtual
Implements GFXCardProfiler.
Referenced by getRendererString().
const String& GFXD3D9CardProfiler::getRendererString () const inline protected virtual
Implements GFXCardProfiler.
References _queryCardCap(), _queryFormat(), and setupCardCapabilities().
void GFXD3D9CardProfiler::init () virtual
Set load script files and generally initialize things.
Implements GFXCardProfiler.
void GFXD3D9CardProfiler::setupCardCapabilities () protected virtual
Implements GFXCardProfiler.
Referenced by getRendererString().
Copyright © GarageGames, LLC. All Rights Reserved.