NetStringHandle Class Reference
Main Modules Class List Namespace List Online
NetStringHandle Class Reference
#include <sim/netStringTable.h>
Public Member Functions
NetStringHandle ()
NetStringHandle (const NetStringHandle &string)
NetStringHandle (const char *string)
NetStringHandle (U32 initIndex)
~NetStringHandle ()
U32 getIndex () const
const char * getString () const
bool isNull () const
bool isValidString () const
bool operator!= (const NetStringHandle &s) const
NetStringHandle & operator= (const NetStringHandle &s)
bool operator== (const NetStringHandle &s) const
void setFromIndex (U32 newIndex)
Constructor & Destructor Documentation
NetStringHandle::NetStringHandle () inline
NetStringHandle::NetStringHandle (const NetStringHandle & string) inline
NetStringHandle::NetStringHandle (const char * string) inline
NetStringHandle::NetStringHandle (U32 initIndex) inline
NetStringHandle::~NetStringHandle () inline
References NetStringTable::removeString().
Member Function Documentation
U32 NetStringHandle::getIndex () const inline
const char* NetStringHandle::getString () const inline
References NetStringTable::lookupString().
Referenced by ShapeBase::getShapeName(), and ShapeBase::getSkinName().
bool NetStringHandle::isNull (void) const inline
bool NetStringHandle::isValidString () const inline
bool NetStringHandle::operator!= (const NetStringHandle & s) const inline
NetStringHandle& NetStringHandle::operator= (const NetStringHandle & s) inline
References NetStringTable::removeString().
bool NetStringHandle::operator== (const NetStringHandle & s) const inline
void NetStringHandle::setFromIndex (U32 newIndex) inline
References NetStringTable::removeString().
Copyright © GarageGames, LLC. All Rights Reserved.