Object Management Trickery
Main Modules Class List Namespace List Online
Object Management Trickery
These functions are to construct and destruct objects in memory without causing a free or malloc call to occur.
Classes
struct Math
Macros
#define _new new(__FILE__, __LINE__)
#define dALIGN(decl) decl
The dALIGN macro ensures the passed declaration is data aligned at 16 byte boundaries.
#define dALIGN_BEGIN()
#define dALIGN_END()
#define dMalloc(x) dMalloc_r(x, __FILE__, __LINE__)
#define dRealloc(x, y) dRealloc_r(x, y, __FILE__, __LINE__)
#define new _new
#define TORQUE_TMM_ARGS , fileName, lineNum
#define TORQUE_TMM_ARGS_DECL , const char* fileName, const U32 lineNum
Memory functions.
#define TORQUE_TMM_LOC , __FILE__, __LINE__
Typedefs
typedef void * FILE_HANDLE
Enumerations
enum DFILE_STATUS { DFILE_OK = 1 }
Functions
template<class T >
T * constructArrayInPlace (T *p, U32 num)
template<class T >
T * constructInPlace (T *p)
Constructs an object that already has memory allocated for it.
template<class T >
T * constructInPlace (T *p, const T *copy)
Copy constructs an object that already has memory allocated for it.
template<class T , class T2 >
T * constructInPlace (T *ptr, T2 t2)
template<class T , class T2 , class T3 >
T * constructInPlace (T *ptr, T2 t2, T3 t3)
template<class T , class T2 , class T3 , class T4 >
T * constructInPlace (T *ptr, T2 t2, T3 t3, T4 t4)
template<class T , class T2 , class T3 , class T4 , class T5 >
T * constructInPlace (T *ptr, T2 t2, T3 t3, T4 t4, T5 t5)
template<class T , class S >
void dCopyArray (T *dst, const S *src, dsize_t size)
template<class T >
void dCopyArray (T *dst, const T *src, dsize_t size)
template<class T >
void destructInPlace (T *p)
Destructs an object without freeing the memory associated with it.
void dFileClose (FILE_HANDLE handle)
bool dFileDelete (const char *name)
S32 dFileRead (FILE_HANDLE handle, U32 bytes, char *dst, DFILE_STATUS &error)
bool dFileRename (const char *oldName, const char *newName)
bool dFileTouch (const char *name)
S32 dFileWrite (FILE_HANDLE handle, U32 bytes, const char *dst, DFILE_STATUS &error)
void dFree (void *in_pFree)
void dFree (const void *p)
void dFree_aligned (void *)
void * dMalloc_aligned (dsize_t in_size, S32 alignment)
void * dMalloc_r (dsize_t in_size, const char *, const dsize_t)
S32 dMemcmp (const void *ptr1, const void *ptr2, dsize_t size)
void * dMemcpy (void *dst, const void *src, dsize_t size)
void * dMemmove (void *dst, const void *src, dsize_t size)
void * dMemset (void *dst, S32 c, dsize_t size)
FILE_HANDLE dOpenFileRead (const char *name, DFILE_STATUS &error)
FILE_HANDLE dOpenFileReadWrite (const char *name, bool append, DFILE_STATUS &error)
bool dPathCopy (const char *fromName, const char *toName, bool nooverwrite=true)
void dRealFree (void *)
void * dRealloc_r (void *in_pResize, dsize_t in_size, const char *, const dsize_t)
void * dRealMalloc (dsize_t)
void FN_CDECL operator delete (void *ptr)
void FN_CDECL operator delete[] (void *ptr)
void *FN_CDECL operator new (dsize_t size, const char *, const U32)
void *FN_CDECL operator new[] (dsize_t size, const char *, const U32)
StringTableEntry osGetTemporaryDirectory ()
void setBreakAlloc (dsize_t)
void setMinimumAllocUnit (U32)
Detailed Description
These functions are to construct and destruct objects in memory without causing a free or malloc call to occur.
This is so that we don't have to worry about allocating, say, space for a hundred NetAddresses with a single malloc call, calling delete on a single NetAdress, and having it try to free memory out from under us.
Macro Definition Documentation
#define _new new(__FILE__, __LINE__)
#define dALIGN (decl) decl
The dALIGN macro ensures the passed declaration is data aligned at 16 byte boundaries.
#define dALIGN_BEGIN ()
#define dALIGN_END ()
Referenced by MatrixSet::restoreSceneViewProjection().
#define dMalloc (x) dMalloc_r(x, __FILE__, __LINE__)
Referenced by ThreadSafeFreeList< ThreadSafeDeque::Node >::alloc(), FixedSizeDeque< QueuedPacket >::FixedSizeDeque(), ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::operator new(), GBitmap::swizzle(), and TempAlloc< T >::TempAlloc().
#define dRealloc (x, y) dRealloc_r(x, y, __FILE__, __LINE__)
Referenced by StringStack::validateArgBufferSize(), and StringStack::validateBufferSize().
#define new _new
#define TORQUE_TMM_ARGS , fileName, lineNum
#define TORQUE_TMM_ARGS_DECL , const char* fileName, const U32 lineNum
Memory functions.
Referenced by EngineObject::_destroySelf(), and EngineCRuntimeObjectPool::instance().
#define TORQUE_TMM_LOC , __FILE__, __LINE__
Referenced by TypeTraits< RawDataT< T > * >::Construct::single().
Typedef Documentation
typedef void* FILE_HANDLE
Enumeration Type Documentation
enum DFILE_STATUS
Enumerator
DFILE_OK
Function Documentation
template<class T > T* constructArrayInPlace (T * p, U32 num) inline
References T.
template<class T > T* constructInPlace (T * p) inline
Constructs an object that already has memory allocated for it.
References T.
Referenced by _Private::_InstantiableConcreteClass< T >::_construct(), ClassChunker< SceneZoneSpace::ZoneSpaceRef >::alloc(), Vector< T >::construct(), Resource< TSShape >::getUnloadSignal(), Vector< T >::increment(), Vector< T >::insert(), Vector< T >::merge(), and AlignedArray< T >::setCapacity().
template<class T > T* constructInPlace (T * p, const T * copy) inline
Copy constructs an object that already has memory allocated for it.
References T.
template<class T , class T2 > T* constructInPlace (T * ptr, T2 t2) inline
References T.
template<class T , class T2 , class T3 > T* constructInPlace (T * ptr, T2 t2, T3 t3) inline
References T.
template<class T , class T2 , class T3 , class T4 > T* constructInPlace (T * ptr, T2 t2, T3 t3, T4 t4) inline
References T.
template<class T , class T2 , class T3 , class T4 , class T5 > T* constructInPlace (T * ptr, T2 t2, T3 t3, T4 t4, T5 t5) inline
References T.
template<class T , class S > void dCopyArray (T * dst, const S * src, dsize_t size)
References dMemcmp(), dMemcpy(), dMemmove(), dMemset(), and T.
template<class T > void dCopyArray (T * dst, const T * src, dsize_t size)
References dMemcpy(), and T.
template<class T > void destructInPlace (T * p) inline
Destructs an object without freeing the memory associated with it.
Referenced by _Private::_InstantiableConcreteClass< T >::_destruct(), Vector< T >::decrement(), Vector< T >::destroy(), ThreadSafeDeque< T >::DeleteNode::destroy(), EngineStructTypeInfo< T >::destructInstance(), Vector< T >::erase(), Vector< T >::erase_fast(), ClassChunker< SceneZoneSpace::ZoneSpaceRef >::free(), FixedSizeDeque< QueuedPacket >::popBack(), FixedSizeDeque< QueuedPacket >::popFront(), TypeTraits< RawDataT< T > * >::Destruct::single(), FixedSizeDeque< QueuedPacket >::~FixedSizeDeque(), and HashTable< Key, Value >::~HashTable().
void dFileClose (FILE_HANDLE handle)
bool dFileDelete (const char * name)
S32 dFileRead (FILE_HANDLE handle, U32 bytes, char * dst, DFILE_STATUS & error)
bool dFileRename (const char * oldName, const char * newName)
bool dFileTouch (const char * name)
S32 dFileWrite (FILE_HANDLE handle, U32 bytes, const char * dst, DFILE_STATUS & error)
void dFree (void * in_pFree)
Referenced by ConsoleValue::cleanup(), dFree(), ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::operator delete(), TypeTraits< RawDataT< T > * >::Destruct::single(), GBitmap::swizzle(), CodeStream::~CodeStream(), FixedSizeDeque< QueuedPacket >::~FixedSizeDeque(), StringStack::~StringStack(), TempAlloc< T >::~TempAlloc(), ThreadSafeFreeList< ThreadSafeDeque::Node >::~ThreadSafeFreeList(), and Vector< T >::~Vector().
void dFree (const void * p) inline
References dFree().
void dFree_aligned (void *)
Referenced by TSShapeVertexArray::set(), and TSMesh::TSMeshVertexArray::set().
void* dMalloc_aligned (dsize_t in_size, S32 alignment)
void* dMalloc_r (dsize_t in_size, const char * , const dsize_t)
Referenced by RawDataT< T >::allocInline().
S32 dMemcmp (const void * ptr1, const void * ptr2, dsize_t size)
Referenced by dCopyArray(), NetAddress::isEqual(), GenericConstBuffer::isEqual(), NetAddress::isSameAddress(), NetAddress::isSameAddressAndPort(), RenderBinManager::newPassNeeded(), Torque::UUID::operator==(), and GFXSamplerStateDesc::operator==().
void* dMemcpy (void * dst, const void * src, dsize_t size)
Referenced by PlaneSet< T >::clipPolygon(), BitVector::copy(), dCopyArray(), OculusVRHMDDevice::getFovPorts(), OculusVRHMDDevice::getStereoViewports(), Swizzle< T, mapLength >::InPlace(), Vector< T >::set(), GFXDevice::setStereoEyeOffsets(), GFXDevice::setStereoEyeTransforms(), GFXDevice::setStereoFovPort(), GFXDevice::setSteroViewports(), Swizzle< T, mapLength >::Swizzle(), GBitmap::swizzle(), and NullSwizzle< T, mapLength >::ToBuffer().
void* dMemmove (void * dst, const void * src, dsize_t size)
Referenced by dCopyArray(), Vector< T >::erase(), Vector< T >::erase_fast(), and Vector< T >::insert().
void* dMemset (void * dst, S32 c, dsize_t size)
Referenced by ThreadSafeFreeList< ThreadSafeDeque::Node >::alloc(), LightAnimData::AnimValue< 3 >::AnimValue(), _ConstructPrim::array(), SFXXAudioBuffer::Buffer::Buffer(), GFXTextureProfileStats::clear(), TerrainRenderInst::clear(), BitVector::clear(), ImposterRenderInst::clear(), ImposterBatchRenderInst::clear(), Player::Death::clear(), BitMatrix::clearAllBits(), dCopyArray(), GFXAdapter::GFXAdapter(), GFXPrimitive::GFXPrimitive(), GFXPrimitiveBuffer::GFXPrimitiveBuffer(), SceneData::init(), ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::Node(), ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::operator new(), ShaderFeature::Resources::Resources(), SceneData::SceneData(), ScopeTracker< NUM_DIMENSIONS, Object >::ScopeTracker(), BitVector::set(), BitMatrix::setAllBits(), AlignedArray< T >::setCapacity(), BitVectorW::setDims(), SFXPlayList::SlotData::SlotData(), StringStack::StringStack(), TriListOpt::TriData::TriData(), Torque::UUID::UUID(), SFXPlayList::VariantFloat::VariantFloat(), and HashTable< Key, Value >::~HashTable().
FILE_HANDLE dOpenFileRead (const char * name, DFILE_STATUS & error)
FILE_HANDLE dOpenFileReadWrite (const char * name, bool append, DFILE_STATUS & error)
bool dPathCopy (const char * fromName, const char * toName, bool nooverwrite = true)
void dRealFree (void *)
void* dRealloc_r (void * in_pResize, dsize_t in_size, const char * , const dsize_t)
void* dRealMalloc (dsize_t)
void FN_CDECL operator delete (void * ptr)
void FN_CDECL operator delete[] (void * ptr)
void* FN_CDECL operator new (dsize_t size, const char * , const U32)
void* FN_CDECL operator new[] (dsize_t size, const char * , const U32)
StringTableEntry osGetTemporaryDirectory ()
void setBreakAlloc (dsize_t)
void setMinimumAllocUnit (U32)
Copyright © GarageGames, LLC. All Rights Reserved.