PrimBuild Namespace Reference
Main Modules Class List Namespace List Online
PrimBuild Namespace Reference
Primitive Builder.
Functions
void begin (GFXPrimitiveType type, U32 maxVerts)
void beginToBuffer (GFXPrimitiveType type, U32 maxVerts)
void color (const ColorI &)
void color (const ColorF &)
void color3f (F32 red, F32 green, F32 blue)
void color3i (U8 red, U8 green, U8 blue)
void color4f (F32 red, F32 green, F32 blue, F32 alpha)
void color4i (U8 red, U8 green, U8 blue, U8 alpha)
void colorWhite ()
void end (bool useGenericShaders=true)
GFXVertexBuffer * endToBuffer (U32 &outNumPrims)
void shutdown ()
void texCoord2f (F32 x, F32 y)
void vertex2f (F32 x, F32 y)
void vertex2fv (const F32 *data)
void vertex2fv (const Point2F &pnt)
void vertex2fv (const Point2F *pnt)
void vertex2i (S32 x, S32 y)
void vertex3f (F32 x, F32 y, F32 z)
void vertex3fv (const F32 *data)
void vertex3fv (const Point3F &pnt)
void vertex3fv (const Point3F *pnt)
void vertex3i (S32 x, S32 y, S32 z)
Variables
const ColorI _colWhite
Detailed Description
Primitive Builder.
A simple interface to put together lines and polygons quickly and easily - OpenGL style. This is basically a convenient way to fill a vertex buffer, then draw it.
There are two ways to use it. You can use the begin() and end() calls to have it draw immediately after calling end(). This is the "OpenGL" or "immediate" style of usage.
The other way to use this is to use the beginToBuffer() and endToBuffer() calls, which let you store the results of your intermediate calls for later use. This is much more efficient than using the immediate style.
Function Documentation
void PrimBuild::begin (GFXPrimitiveType type, U32 maxVerts)
void PrimBuild::beginToBuffer (GFXPrimitiveType type, U32 maxVerts)
void PrimBuild::color (const ColorI &)
Referenced by colorWhite(), and vertex3i().
void PrimBuild::color (const ColorF &)
void PrimBuild::color3f (F32 red, F32 green, F32 blue)
Referenced by vertex3i().
void PrimBuild::color3i (U8 red, U8 green, U8 blue)
Referenced by vertex3i().
void PrimBuild::color4f (F32 red, F32 green, F32 blue, F32 alpha)
Referenced by vertex3i().
void PrimBuild::color4i (U8 red, U8 green, U8 blue, U8 alpha)
Referenced by vertex3i().
void PrimBuild::colorWhite () inline
References color(), shutdown(), and texCoord2f().
void PrimBuild::end (bool useGenericShaders = true)
GFXVertexBuffer* PrimBuild::endToBuffer (U32 & outNumPrims)
void PrimBuild::shutdown ()
Referenced by colorWhite().
void PrimBuild::texCoord2f (F32 x, F32 y)
Referenced by colorWhite().
void PrimBuild::vertex2f (F32 x, F32 y)
Referenced by vertex2i().
void PrimBuild::vertex2fv (const F32 * data)
Referenced by vertex2fv().
void PrimBuild::vertex2fv (const Point2F & pnt) inline
References vertex2fv().
void PrimBuild::vertex2fv (const Point2F * pnt) inline
References vertex2fv(), and vertex3fv().
void PrimBuild::vertex2i (S32 x, S32 y) inline
References vertex2f().
void PrimBuild::vertex3f (F32 x, F32 y, F32 z)
Referenced by vertex3i().
void PrimBuild::vertex3fv (const F32 * data)
Referenced by vertex2fv(), and vertex3fv().
void PrimBuild::vertex3fv (const Point3F & pnt) inline
References vertex3fv().
void PrimBuild::vertex3fv (const Point3F * pnt) inline
References vertex3fv().
void PrimBuild::vertex3i (S32 x, S32 y, S32 z) inline
References color(), color3f(), color3i(), color4f(), color4i(), and vertex3f().
Variable Documentation
const ColorI PrimBuild::_colWhite
Copyright © GarageGames, LLC. All Rights Reserved.