Sim Namespace Reference
Main Modules Class List Namespace List Online
Sim Namespace Reference
Functions
void advanceTime (SimTime delta)
void advanceToTime (SimTime time)
void cancelEvent (U32 eventId)
void cancelPendingEvents (SimObject *obj)
DeclareNamedGroup (ActionMapGroup) DeclareNamedGroup(ClientGroup) DeclareNamedGroup(GuiGroup) DeclareNamedGroup(GuiDataGroup) DeclareNamedGroup(TCPGroup) DeclareNamedGroup(ClientConnectionGroup) DeclareNamedGroup(SFXParameterGroup)
DeclareNamedSet (ActiveActionMapSet) DeclareNamedSet(GhostAlwaysSet) DeclareNamedSet(WayPointSet) DeclareNamedSet(fxReplicatorSet) DeclareNamedSet(fxFoliageSet) DeclareNamedSet(BehaviorSet) DeclareNamedSet(MaterialSet) DeclareNamedSet(SFXSourceSet)
DeclareNamedSet (SFXDescriptionSet)
DeclareNamedSet (SFXTrackSet)
DeclareNamedSet (SFXEnvironmentSet)
DeclareNamedSet (SFXStateSet)
DeclareNamedSet (SFXAmbienceSet)
DeclareNamedSet (TerrainMaterialSet)
DeclareNamedSet (DataBlockSet)
DeclareNamedSet (sgMissionLightingFilterSet)
SimObject * findObject (ConsoleValueRef &)
SimObject * findObject (SimObjectId)
SimObject * findObject (const char *name)
SimObject * findObject (const char *fileName, S32 declarationLine)
template<class T >
bool findObject (ConsoleValueRef &ref, T *&t)
template<class T >
bool findObject (SimObjectId iD, T *&t)
template<class T >
bool findObject (const char *objectName, T *&t)
SimTime getCurrentTime ()
SimDataBlockGroup * getDataBlockGroup ()
U32 getEventTimeLeft (U32 eventId)
SimGroup * getRootGroup ()
U32 getScheduleDuration (U32 eventId)
SimTime getTargetTime ()
U32 getTimeSinceStart (U32 eventId)
String getUniqueInternalName (const char *inName, SimSet *inSet, bool searchChildren)
Appends numbers to inName until an internal name not taken in the inSet is found.
String getUniqueName (const char *inName)
Appends numbers to inName until an unused SimObject name is created.
void init ()
bool isEventPending (U32 eventId)
bool isShuttingDown ()
bool isValidObjectName (const char *name)
Return true if the given name string makes for a valid object name.
SimObject * loadObjectStream (Stream *stream)
SimObject * loadObjectStream (const char *filename)
U32 postCurrentEvent (SimObject *obj, SimEvent *evt)
U32 postCurrentEvent (SimObjectId obj, SimEvent *evt)
U32 postCurrentEvent (const char *obj, SimEvent *evt)
U32 postEvent (SimObject *, SimEvent *, SimTime targetTime)
a target time of 0 on an event means current event
U32 postEvent (SimObjectId iD, SimEvent *evt, SimTime targetTime)
U32 postEvent (const char *objectName, SimEvent *evt, SimTime targetTime)
bool saveObject (SimObject *obj, Stream *stream)
bool saveObject (SimObject *obj, const char *filename)
void shutdown ()
SimObject * spawnObject (String spawnClass, String spawnDataBlock=String::EmptyString, String spawnName=String::EmptyString, String spawnProperties=String::EmptyString, String spawnScript=String::EmptyString)
Function Documentation
void Sim::advanceTime (SimTime delta)
Referenced by findObject().
void Sim::advanceToTime (SimTime time)
Referenced by findObject().
void Sim::cancelEvent (U32 eventId)
Referenced by postCurrentEvent().
void Sim::cancelPendingEvents (SimObject * obj)
Referenced by postCurrentEvent().
Sim::DeclareNamedGroup (ActionMapGroup)
Sim::DeclareNamedSet (ActiveActionMapSet)
Sim::DeclareNamedSet (SFXDescriptionSet)
Sim::DeclareNamedSet (SFXTrackSet)
Sim::DeclareNamedSet (SFXEnvironmentSet)
Sim::DeclareNamedSet (SFXStateSet)
Sim::DeclareNamedSet (SFXAmbienceSet)
Sim::DeclareNamedSet (TerrainMaterialSet)
Sim::DeclareNamedSet (DataBlockSet)
Sim::DeclareNamedSet (sgMissionLightingFilterSet)
SimObject* Sim::findObject (ConsoleValueRef &)
Referenced by SimObject::__findObject(), SimObjectRef< T >::_get(), RenderPassStateBin::_setStateToken(), findObject(), DecalData::getSet(), EngineUnmarshallData< T * >::operator()(), and postEvent().
SimObject* Sim::findObject (SimObjectId)
SimObject* Sim::findObject (const char * name)
SimObject* Sim::findObject (const char * fileName, S32 declarationLine)
template<class T > bool Sim::findObject (ConsoleValueRef & ref, T *& t) inline
References findObject(), and T.
template<class T > bool Sim::findObject (SimObjectId iD, T *& t) inline
References findObject(), and T.
template<class T > bool Sim::findObject (const char * objectName, T *& t) inline
References advanceTime(), advanceToTime(), String::EmptyString, findObject(), getCurrentTime(), getTargetTime(), postEvent(), spawnObject(), and T.
SimTime Sim::getCurrentTime ()
Referenced by _EngineConsoleCallbackHelper::call(), _EngineConsoleExecCallbackHelper< P1 >::call(), _EngineConsoleExecCallbackHelper< const char * >::call(), findObject(), SimMSTimer::getTick(), and postCurrentEvent().
SimDataBlockGroup* Sim::getDataBlockGroup ()
Referenced by GuiInspectorDatablockField::_getDatablockSet().
U32 Sim::getEventTimeLeft (U32 eventId)
Referenced by postCurrentEvent().
SimGroup* Sim::getRootGroup ()
Referenced by _EngineConsoleCallbackHelper::call(), _EngineConsoleExecCallbackHelper< const char * >::call(), and DecalData::getSet().
U32 Sim::getScheduleDuration (U32 eventId)
Referenced by postCurrentEvent().
SimTime Sim::getTargetTime ()
Referenced by findObject().
U32 Sim::getTimeSinceStart (U32 eventId)
Referenced by postCurrentEvent().
String Sim::getUniqueInternalName (const char * inName, SimSet * inSet, bool searchChildren)
Appends numbers to inName until an internal name not taken in the inSet is found.
Referenced by postCurrentEvent().
String Sim::getUniqueName (const char * inName)
Appends numbers to inName until an unused SimObject name is created.
Referenced by postCurrentEvent().
void Sim::init ()
bool Sim::isEventPending (U32 eventId)
Referenced by postCurrentEvent().
bool Sim::isShuttingDown ()
bool Sim::isValidObjectName (const char * name)
Return true if the given name string makes for a valid object name.
Empty strings and NULL are also treated as valid names (anonymous objects).
Referenced by postCurrentEvent().
SimObject* Sim::loadObjectStream (Stream * stream)
Referenced by postCurrentEvent().
SimObject* Sim::loadObjectStream (const char * filename)
U32 Sim::postCurrentEvent (SimObject * obj, SimEvent * evt) inline
References getCurrentTime(), and postEvent().
U32 Sim::postCurrentEvent (SimObjectId obj, SimEvent * evt) inline
References getCurrentTime(), and postEvent().
U32 Sim::postCurrentEvent (const char * obj, SimEvent * evt) inline
References cancelEvent(), cancelPendingEvents(), getCurrentTime(), getEventTimeLeft(), getScheduleDuration(), getTimeSinceStart(), getUniqueInternalName(), getUniqueName(), isEventPending(), isValidObjectName(), loadObjectStream(), postEvent(), and saveObject().
U32 Sim::postEvent (SimObject * , SimEvent * , SimTime targetTime)
a target time of 0 on an event means current event
Referenced by _EngineConsoleCallbackHelper::call(), _EngineConsoleExecCallbackHelper< P1 >::call(), _EngineConsoleExecCallbackHelper< const char * >::call(), findObject(), postCurrentEvent(), and postEvent().
U32 Sim::postEvent (SimObjectId iD, SimEvent * evt, SimTime targetTime) inline
References findObject(), and postEvent().
U32 Sim::postEvent (const char * objectName, SimEvent * evt, SimTime targetTime) inline
References findObject(), and postEvent().
bool Sim::saveObject (SimObject * obj, Stream * stream)
Referenced by postCurrentEvent().
bool Sim::saveObject (SimObject * obj, const char * filename)
void Sim::shutdown ()
SimObject* Sim::spawnObject (String spawnClass, String spawnDataBlock = String::EmptyString, String spawnName = String::EmptyString, String spawnProperties = String::EmptyString, String spawnScript = String::EmptyString)
Referenced by findObject().
Copyright © GarageGames, LLC. All Rights Reserved.