Audio Namespace Reference
Main Modules Class List Namespace List Online
Audio Namespace Reference
Functions
F32 DBToLinear (F32 value)
bool doesSupportDynamix ()
bool doesSupportIASIG ()
bool libraryInit (const char *library)
void libraryInitExtensions ()
void libraryShutdown ()
F32 linearToDB (F32 value)
Function Documentation
F32 Audio::DBToLinear (F32 value)
Referenced by doesSupportDynamix().
bool Audio::doesSupportDynamix () inline
References DBToLinear(), and linearToDB().
bool Audio::doesSupportIASIG () inline
bool Audio::libraryInit (const char * library)
void Audio::libraryInitExtensions ()
void Audio::libraryShutdown ()
F32 Audio::linearToDB (F32 value)
Referenced by doesSupportDynamix().
Copyright © GarageGames, LLC. All Rights Reserved.