Dictionary::Entry Struct Reference
Main Modules Class List Namespace List Online
Dictionary::Entry Struct Reference
#include <console/consoleInternal.h>
Public Types
typedef Signal< void()> NotifySignal
Public Member Functions
Entry ()
Entry (StringTableEntry name)
~Entry ()
F32 getFloatValue ()
U32 getIntValue ()
const char * getStringValue ()
void reset ()
void setFloatValue (F32 val)
void setIntValue (U32 val)
void setStringStackPtrValue (StringStackPtr newValue)
void setStringValue (const char *newValue)
Public Attributes
bool mIsConstant
Whether this is a constant that cannot be assigned to.
Entry * mNext
const char * mUsage
Usage doc string.
StringTableEntry name
Entry * nextEntry
NotifySignal * notify
The optional notification signal called when a value is assigned to this variable.
ConsoleValue value
Member Typedef Documentation
typedef Signal<void()> Dictionary::Entry::NotifySignal
Constructor & Destructor Documentation
Dictionary::Entry::Entry () inline
References Namespace::Entry::Entry(), and ConsoleValue::init().
Dictionary::Entry::Entry (StringTableEntry name)
Dictionary::Entry::~Entry ()
Member Function Documentation
F32 Dictionary::Entry::getFloatValue () inline
References ConsoleValue::getFloatValue().
U32 Dictionary::Entry::getIntValue () inline
References ConsoleValue::getIntValue().
const char* Dictionary::Entry::getStringValue () inline
References ConsoleValue::getStringValue().
void Dictionary::Entry::reset (void) inline
References ConsoleValue::cleanup().
void Dictionary::Entry::setFloatValue (F32 val) inline
References Con::errorf(), ConsoleValue::setFloatValue(), and Signal< void()>::trigger().
void Dictionary::Entry::setIntValue (U32 val) inline
References Con::errorf(), ConsoleValue::setIntValue(), and Signal< void()>::trigger().
void Dictionary::Entry::setStringStackPtrValue (StringStackPtr newValue) inline
References Con::errorf(), ConsoleValue::setStringStackPtrValue(), and Signal< void()>::trigger().
void Dictionary::Entry::setStringValue (const char * newValue) inline
References Con::errorf(), ConsoleValue::setStringValue(), and Signal< void()>::trigger().
Member Data Documentation
bool Dictionary::Entry::mIsConstant
Whether this is a constant that cannot be assigned to.
Entry* Dictionary::Entry::mNext
const char* Dictionary::Entry::mUsage
Usage doc string.
StringTableEntry Dictionary::Entry::name
Entry* Dictionary::Entry::nextEntry
NotifySignal* Dictionary::Entry::notify
The optional notification signal called when a value is assigned to this variable.
ConsoleValue Dictionary::Entry::value
Copyright © GarageGames, LLC. All Rights Reserved.