GFXStateBlockDesc Struct Reference
Main Modules Class List Namespace List Online
GFXStateBlockDesc Struct Reference
GFXStateBlockDesc defines a render state, which is then used to create a GFXStateBlock instance.
#include <gfx/gfxStateBlock.h>
Public Member Functions
GFXStateBlockDesc ()
void addDesc (const GFXStateBlockDesc &desc)
Adds data from desc to this description, uses *defined parameters in desc to figure out what blocks of state to actually copy from desc.
const String describeSelf () const
Returns a string that describes the options set (used by GFXStateBlock::describeSelf)
U32 getHashValue () const
Returns the hash value of this state description.
void setAlphaTest (bool enable, GFXCmpFunc func=GFXCmpGreaterEqual, S32 alphaRef=0)
void setBlend (bool enable, GFXBlend src=GFXBlendSrcAlpha, GFXBlend dest=GFXBlendInvSrcAlpha, GFXBlendOp op=GFXBlendOpAdd)
void setColorWrites (bool red, bool green, bool blue, bool alpha)
void setCullMode (GFXCullMode m)
Utility functions to make setting up stateblock descriptions less wordy.
void setFillModePoint ()
Helpers for setting the fill modes.
void setFillModeSolid ()
void setFillModeWireframe ()
void setSeparateAlphaBlend (bool enable, GFXBlend src=GFXBlendOne, GFXBlend dest=GFXBlendZero, GFXBlendOp op=GFXBlendOpAdd)
void setZReadWrite (bool read, bool write=true)
Public Attributes
bool alphaDefined
bool alphaTestEnable
GFXCmpFunc alphaTestFunc
S32 alphaTestRef
bool blendDefined
GFXBlend blendDest
bool blendEnable
GFXBlendOp blendOp
GFXBlend blendSrc
bool colorWriteAlpha
bool colorWriteBlue
bool colorWriteDefined
bool colorWriteGreen
bool colorWriteRed
bool cullDefined
GFXCullMode cullMode
bool ffLighting
GFXFillMode fillMode
GFXSamplerStateDesc samplers [TEXTURE_STAGE_COUNT]
bool samplersDefined
bool stencilDefined
bool stencilEnable
GFXStencilOp stencilFailOp
GFXCmpFunc stencilFunc
U32 stencilMask
GFXStencilOp stencilPassOp
U32 stencilRef
U32 stencilWriteMask
GFXStencilOp stencilZFailOp
ColorI textureFactor
bool vertexColorEnable
F32 zBias
bool zDefined
bool zEnable
GFXCmpFunc zFunc
F32 zSlopeBias
bool zWriteEnable
Separate Alpha Blending
bool separateAlphaBlendDefined
bool separateAlphaBlendEnable
GFXBlend separateAlphaBlendSrc
GFXBlend separateAlphaBlendDest
GFXBlendOp separateAlphaBlendOp
Detailed Description
GFXStateBlockDesc defines a render state, which is then used to create a GFXStateBlock instance.
Constructor & Destructor Documentation
GFXStateBlockDesc::GFXStateBlockDesc ()
Member Function Documentation
void GFXStateBlockDesc::addDesc (const GFXStateBlockDesc & desc)
Adds data from desc to this description, uses *defined parameters in desc to figure out what blocks of state to actually copy from desc.
const String GFXStateBlockDesc::describeSelf () const
Returns a string that describes the options set (used by GFXStateBlock::describeSelf)
U32 GFXStateBlockDesc::getHashValue () const
Returns the hash value of this state description.
void GFXStateBlockDesc::setAlphaTest (bool enable, GFXCmpFunc func = GFXCmpGreaterEqual, S32 alphaRef = 0)
void GFXStateBlockDesc::setBlend (bool enable, GFXBlend src = GFXBlendSrcAlpha, GFXBlend dest = GFXBlendInvSrcAlpha, GFXBlendOp op = GFXBlendOpAdd)
Referenced by ScenePolyhedralObject< Base, P >::_renderObject().
void GFXStateBlockDesc::setColorWrites (bool red, bool green, bool blue, bool alpha)
void GFXStateBlockDesc::setCullMode (GFXCullMode m)
Utility functions to make setting up stateblock descriptions less wordy.
Referenced by ScenePolyhedralObject< Base, P >::_renderObject().
void GFXStateBlockDesc::setFillModePoint () inline
Helpers for setting the fill modes.
void GFXStateBlockDesc::setFillModeSolid () inline
void GFXStateBlockDesc::setFillModeWireframe () inline
Referenced by ScenePolyhedralObject< Base, P >::_renderObject().
void GFXStateBlockDesc::setSeparateAlphaBlend (bool enable, GFXBlend src = GFXBlendOne, GFXBlend dest = GFXBlendZero, GFXBlendOp op = GFXBlendOpAdd)
void GFXStateBlockDesc::setZReadWrite (bool read, bool write = true)
Referenced by ScenePolyhedralObject< Base, P >::_renderObject().
Member Data Documentation
bool GFXStateBlockDesc::alphaDefined
bool GFXStateBlockDesc::alphaTestEnable
GFXCmpFunc GFXStateBlockDesc::alphaTestFunc
S32 GFXStateBlockDesc::alphaTestRef
bool GFXStateBlockDesc::blendDefined
GFXBlend GFXStateBlockDesc::blendDest
bool GFXStateBlockDesc::blendEnable
GFXBlendOp GFXStateBlockDesc::blendOp
GFXBlend GFXStateBlockDesc::blendSrc
bool GFXStateBlockDesc::colorWriteAlpha
bool GFXStateBlockDesc::colorWriteBlue
bool GFXStateBlockDesc::colorWriteDefined
bool GFXStateBlockDesc::colorWriteGreen
bool GFXStateBlockDesc::colorWriteRed
bool GFXStateBlockDesc::cullDefined
GFXCullMode GFXStateBlockDesc::cullMode
bool GFXStateBlockDesc::ffLighting
GFXFillMode GFXStateBlockDesc::fillMode
GFXSamplerStateDesc GFXStateBlockDesc::samplers[TEXTURE_STAGE_COUNT]
bool GFXStateBlockDesc::samplersDefined
bool GFXStateBlockDesc::separateAlphaBlendDefined
GFXBlend GFXStateBlockDesc::separateAlphaBlendDest
bool GFXStateBlockDesc::separateAlphaBlendEnable
GFXBlendOp GFXStateBlockDesc::separateAlphaBlendOp
GFXBlend GFXStateBlockDesc::separateAlphaBlendSrc
bool GFXStateBlockDesc::stencilDefined
bool GFXStateBlockDesc::stencilEnable
GFXStencilOp GFXStateBlockDesc::stencilFailOp
GFXCmpFunc GFXStateBlockDesc::stencilFunc
U32 GFXStateBlockDesc::stencilMask
GFXStencilOp GFXStateBlockDesc::stencilPassOp
U32 GFXStateBlockDesc::stencilRef
U32 GFXStateBlockDesc::stencilWriteMask
GFXStencilOp GFXStateBlockDesc::stencilZFailOp
ColorI GFXStateBlockDesc::textureFactor
bool GFXStateBlockDesc::vertexColorEnable
F32 GFXStateBlockDesc::zBias
bool GFXStateBlockDesc::zDefined
bool GFXStateBlockDesc::zEnable
GFXCmpFunc GFXStateBlockDesc::zFunc
F32 GFXStateBlockDesc::zSlopeBias
bool GFXStateBlockDesc::zWriteEnable
Copyright © GarageGames, LLC. All Rights Reserved.