RenderPassData Struct Reference
Main Modules Class List Namespace List Online
RenderPassData Struct Reference
This contains the common data needed to render a pass.
#include <materials/processedMaterial.h>
Classes
struct TexSlotT
Public Types
enum {
STATE_REFLECT = 1,
STATE_TRANSLUCENT = 2,
STATE_GLOW = 4,
STATE_WIREFRAME = 8,
STATE_MAX = 16
}
State permutations, used to index into the render states array.
Public Member Functions
RenderPassData ()
virtual ~RenderPassData ()
virtual String describeSelf () const
Creates and returns a unique description string.
virtual void reset ()
Public Attributes
Material::BlendOp mBlendOp
GFXCubemapHandle mCubeMap
The cubemap to use when the texture type is set to Material::Cube.
MaterialFeatureData mFeatureData
bool mGlow
U32 mNumTex
U32 mNumTexReg
GFXStateBlockRef mRenderStates [STATE_MAX]
String mSamplerNames [Material::MAX_TEX_PER_PASS]
U32 mStageNum
struct RenderPassData::TexSlotT mTexSlot [Material::MAX_TEX_PER_PASS]
U32 mTexType [Material::MAX_TEX_PER_PASS]
Detailed Description
This contains the common data needed to render a pass.
Member Enumeration Documentation
anonymous enum
State permutations, used to index into the render states array.
See also
mRenderStates
Enumerator
STATE_REFLECT
STATE_TRANSLUCENT
STATE_GLOW
STATE_WIREFRAME
STATE_MAX
Constructor & Destructor Documentation
RenderPassData::RenderPassData ()
virtual RenderPassData::~RenderPassData () inline virtual
References describeSelf(), and reset().
Member Function Documentation
virtual String RenderPassData::describeSelf () const virtual
Creates and returns a unique description string.
Reimplemented in ShaderRenderPassData.
Referenced by ~RenderPassData().
virtual void RenderPassData::reset () virtual
Reimplemented in ShaderRenderPassData.
Referenced by ~RenderPassData().
Member Data Documentation
Material::BlendOp RenderPassData::mBlendOp
GFXCubemapHandle RenderPassData::mCubeMap
The cubemap to use when the texture type is set to Material::Cube.
See also
mTexType
MaterialFeatureData RenderPassData::mFeatureData
bool RenderPassData::mGlow
U32 RenderPassData::mNumTex
U32 RenderPassData::mNumTexReg
GFXStateBlockRef RenderPassData::mRenderStates[STATE_MAX]
String RenderPassData::mSamplerNames[Material::MAX_TEX_PER_PASS]
U32 RenderPassData::mStageNum
struct RenderPassData::TexSlotT RenderPassData::mTexSlot[Material::MAX_TEX_PER_PASS]
U32 RenderPassData::mTexType[Material::MAX_TEX_PER_PASS]
Copyright © GarageGames, LLC. All Rights Reserved.