rapidjson::AutoUTF< CharType > Struct Template Reference
Main Modules Class List Namespace List Online
rapidjson::AutoUTF< CharType > Struct Template Reference
Dynamically select encoding according to stream's runtime-specified UTF encoding type.
#include <persistence/rapidjson/encodings.h>
Public Types
typedef CharType Ch
Static Public Member Functions
template<typename InputStream >
static RAPIDJSON_FORCEINLINE bool Decode (InputStream &is, unsigned *codepoint)
template<typename OutputStream >
static RAPIDJSON_FORCEINLINE void Encode (OutputStream &os, unsigned codepoint)
template<typename InputStream , typename OutputStream >
static RAPIDJSON_FORCEINLINE bool Validate (InputStream &is, OutputStream &os)
Detailed Description
template<typename CharType>
struct rapidjson::AutoUTF< CharType >
Dynamically select encoding according to stream's runtime-specified UTF encoding type.
Note
This class can be used with AutoUTFInputtStream and AutoUTFOutputStream, which provides GetType().
Member Typedef Documentation
template<typename CharType > typedef CharType rapidjson::AutoUTF< CharType >::Ch
Member Function Documentation
template<typename CharType > template<typename InputStream > static RAPIDJSON_FORCEINLINE bool rapidjson::AutoUTF< CharType >::Decode (InputStream & is, unsigned * codepoint) inline static
References rapidjson::UTF8< CharType >::Decode().
template<typename CharType > template<typename OutputStream > static RAPIDJSON_FORCEINLINE void rapidjson::AutoUTF< CharType >::Encode (OutputStream & os, unsigned codepoint) inline static
References rapidjson::UTF8< CharType >::Encode().
template<typename CharType > template<typename InputStream , typename OutputStream > static RAPIDJSON_FORCEINLINE bool rapidjson::AutoUTF< CharType >::Validate (InputStream & is, OutputStream & os) inline static
References rapidjson::UTF8< CharType >::Validate().
Copyright © GarageGames, LLC. All Rights Reserved.