PlatformPopupMenuData Struct Reference
Main Modules Class List Namespace List Online
PlatformPopupMenuData Struct Reference
#include <platformSDL/menus/PlatformSDLPopupMenuData.h>
Public Member Functions
PlatformPopupMenuData ()
~PlatformPopupMenuData ()
void insertAccelerator (EventDescriptor &desc, U32 id)
void removeAccelerator (U32 id)
void setAccelleratorEnabled (U32 id, bool enabled)
Public Attributes
MenuBar * mMenuBar
GuiMenuBar::Menu * mMenuGui
Static Public Attributes
static const U8 mCheckedBitmapIdx = 0
static Map< GuiMenuBar::Menu *, PopupMenu * > mMenuMap
Constructor & Destructor Documentation
PlatformPopupMenuData::PlatformPopupMenuData () inline
PlatformPopupMenuData::~PlatformPopupMenuData () inline
References insertAccelerator(), removeAccelerator(), and setAccelleratorEnabled().
Member Function Documentation
void PlatformPopupMenuData::insertAccelerator (EventDescriptor & desc, U32 id)
Referenced by ~PlatformPopupMenuData().
void PlatformPopupMenuData::removeAccelerator (U32 id)
Referenced by ~PlatformPopupMenuData().
void PlatformPopupMenuData::setAccelleratorEnabled (U32 id, bool enabled)
Referenced by ~PlatformPopupMenuData().
Member Data Documentation
const U8 PlatformPopupMenuData::mCheckedBitmapIdx = 0 static
MenuBar* PlatformPopupMenuData::mMenuBar
GuiMenuBar::Menu* PlatformPopupMenuData::mMenuGui
Map<GuiMenuBar::Menu*, PopupMenu*> PlatformPopupMenuData::mMenuMap static
Referenced by GuiPlatformGenericMenuBar::menuItemSelected().
Copyright © GarageGames, LLC. All Rights Reserved.