PolyhedronImpl< Base > Struct Template Reference
Main Modules Class List Namespace List Online
PolyhedronImpl< Base > Struct Template Reference
A polyhedron.
#include <math/mPolyhedron.h>
Public Types
typedef Base::Edge Edge
typedef Base::EdgeListType EdgeListType
typedef Base::PlaneListType PlaneListType
typedef Base::PointListType PointListType
Public Member Functions
PolyhedronImpl ()
Construct an empty polyhedron.
PolyhedronImpl (PlaneListType planes, PointListType points, EdgeListType edges)
Construct a polyhedron described by the given planes and edges.
Box3F getBounds () const
Return the AABB around the polyhedron.
Point3F getCenterPoint () const
Return the median point of all points defined on the polyhedron.
Transform
void transform (const MatrixF &matrix, const Point3F &scale=Point3F::One)
Transform the polyhedron using the given transform matrix and scale.
Containment
bool isContained (const Point3F &point, F32 epsilon=0.f) const
bool isContained (const Point3F *points, U32 numPoints) const
bool isContained (const Box3F &aabb) const
bool isContained (const SphereF &sphere) const
bool isContained (const OrientedBox3F &obb) const
Intersection
All of these intersection methods are approximate in that they can produce false positives on GeometryIntersecting.
For precise testing, use Intersector.
OverlapTestResult testPotentialIntersection (const Box3F &aabb) const
OverlapTestResult testPotentialIntersection (const SphereF &sphere) const
OverlapTestResult testPotentialIntersection (const OrientedBox3F &obb) const
U32 testPlanes (const Box3F &bounds, U32 planeMask=0xFFFFFFFF, F32 expand=0.0f) const
Clipping
Functionality to clip other geometries against the polyhedron.
bool clipSegment (Point3F &pnt0, Point3F &pnt1) const
U32 clipPolygon (const Point3F *inVertices, U32 inNumVertices, Point3F *outVertices, U32 maxOutVertices) const
Construction
Operations for constructing solids and polygons through boolean operations involving the polyhedron.
U32 constructIntersection (const PlaneF &plane, Point3F *outPoints, U32 maxOutPoints) const
Build the intersection of this polyhedron with the given plane.
Extraction
template<typename IndexType >
U32 extractFace (U32 plane, IndexType *outIndices, U32 maxOutIndices) const
Extract the polygon for the given plane.
Protected Member Functions
template<typename P >
OverlapTestResult _testOverlap (const P &bounds) const
Detailed Description
template<typename Base = PolyhedronVectorData>
struct PolyhedronImpl< Base >
A polyhedron.
Polyhedrons are stored as both sets of planes as well sets of edges and vertices (basically a winged-edge format).
Polyhedrons must be convex.
Note
The default orientation for the plane normals of a polyhedron is inwards.
Member Typedef Documentation
template<typename Base = PolyhedronVectorData> typedef Base::Edge PolyhedronImpl< Base >::Edge
template<typename Base = PolyhedronVectorData> typedef Base::EdgeListType PolyhedronImpl< Base >::EdgeListType
template<typename Base = PolyhedronVectorData> typedef Base::PlaneListType PolyhedronImpl< Base >::PlaneListType
template<typename Base = PolyhedronVectorData> typedef Base::PointListType PolyhedronImpl< Base >::PointListType
Constructor & Destructor Documentation
template<typename Base = PolyhedronVectorData> PolyhedronImpl< Base >::PolyhedronImpl () inline
Construct an empty polyhedron.
template<typename Base = PolyhedronVectorData> PolyhedronImpl< Base >::PolyhedronImpl (PlaneListType planes, PointListType points, EdgeListType edges) inline
Construct a polyhedron described by the given planes and edges.
Member Function Documentation
template<typename Base = PolyhedronVectorData> template<typename P > OverlapTestResult PolyhedronImpl< Base >::_testOverlap (const P & bounds) const protected
template<typename Base = PolyhedronVectorData> U32 PolyhedronImpl< Base >::clipPolygon (const Point3F * inVertices, U32 inNumVertices, Point3F * outVertices, U32 maxOutVertices) const inline
See also
PlaneSet::clipPolygon
template<typename Base = PolyhedronVectorData> bool PolyhedronImpl< Base >::clipSegment (Point3F & pnt0, Point3F & pnt1) const inline
See also
PlaneSet::clipSegment
template<typename Base > U32 PolyhedronImpl< Base >::constructIntersection (const PlaneF & plane, Point3F * outPoints, U32 maxOutPoints) const
Build the intersection of this polyhedron with the given plane.
The result is a polygon.
Parameters
plane Plane to intersect the polyhedron with.
outPoints (out) Array where the resulting polygon points are stored. A safe size is to just allocate as many points as there are edges in the polyhedron. If you know the maximum number of vertices that can result from the intersection (for example, 4 for a box), then it is ok to only allocate that much.
maxOutPoints Number of points that can be stored in outPoints. If insufficient, the return value will be 0.
Returns
The number of points written to outPoints. If there is no intersection between the given plane and the polyhedron, this will be zero.
Note
The resulting points will be ordered to form a proper polygon but there is no guarantee on which direction the ordering is in compared to the plane.
References PlaneF::clipSegment(), PlaneF::Front, PlaneF::On, and PlaneF::whichSide().
template<typename Base > template<typename IndexType > U32 PolyhedronImpl< Base >::extractFace (U32 plane, IndexType * outIndices, U32 maxOutIndices) const
Extract the polygon for the given plane.
The resulting indices will be CW ordered if the plane normals on the polyhedron are facing inwards and CCW ordered otherwise.
Parameters
plane Index of the plane on the polyhedron.
outIndices Array where the resulting vertex indices will be stored. Must have enough room. If you don't know the exact size that you need, just allocate one index for any point in the mesh.
maxOutIndices The number of indices that can be stored in outIndices. If insufficient, the return value will be 0.
Returns
Number of indices written to outIndices.
Note
This method relies on correct CW ordering of edges with respect to face[0].
template<typename Base = PolyhedronVectorData> Box3F PolyhedronImpl< Base >::getBounds () const inline
Return the AABB around the polyhedron.
template<typename Base > Point3F PolyhedronImpl< Base >::getCenterPoint () const
Return the median point of all points defined on the polyhedron.
template<typename Base = PolyhedronVectorData> bool PolyhedronImpl< Base >::isContained (const Point3F & point, F32 epsilon = 0.f) const inline
See also
PlaneSet::isContained(const Point3F&,F32)
template<typename Base = PolyhedronVectorData> bool PolyhedronImpl< Base >::isContained (const Point3F * points, U32 numPoints) const inline
See also
PlaneSet::isContained(const Point3F*,U32)
template<typename Base = PolyhedronVectorData> bool PolyhedronImpl< Base >::isContained (const Box3F & aabb) const inline
See also
PlaneSet::isContained(const Box3F&)
template<typename Base = PolyhedronVectorData> bool PolyhedronImpl< Base >::isContained (const SphereF & sphere) const inline
See also
PlaneSet::isContained(const SphereF&)
template<typename Base = PolyhedronVectorData> bool PolyhedronImpl< Base >::isContained (const OrientedBox3F & obb) const inline
See also
PlaneSet::isContained(const OrientedBox3F&)
template<typename Base = PolyhedronVectorData> U32 PolyhedronImpl< Base >::testPlanes (const Box3F & bounds, U32 planeMask = 0xFFFFFFFF, F32 expand = 0.0f) const inline
See also
PlaneSet::testPlanes
template<typename Base = PolyhedronVectorData> OverlapTestResult PolyhedronImpl< Base >::testPotentialIntersection (const Box3F & aabb) const inline
See also
PlaneSet::testPotentialIntersection(const Box3F&)
template<typename Base = PolyhedronVectorData> OverlapTestResult PolyhedronImpl< Base >::testPotentialIntersection (const SphereF & sphere) const inline
See also
PlaneSet::testPotentialIntersection(const SphereF&)
template<typename Base = PolyhedronVectorData> OverlapTestResult PolyhedronImpl< Base >::testPotentialIntersection (const OrientedBox3F & obb) const inline
See also
PlaneSet::testPotentialIntersection(const OrientedBox3F&)
template<typename Base > void PolyhedronImpl< Base >::transform (const MatrixF & matrix, const Point3F & scale = Point3F::One)
Transform the polyhedron using the given transform matrix and scale.
References MatrixF::mulP(), PlaneTransformer::set(), and PlaneTransformer::transform().
Copyright © GarageGames, LLC. All Rights Reserved.