Stream Class Reference
Main Modules Class List Namespace List Online
Stream Class Reference abstract
Base stream class for streaming data across a specific media.
#include <core/stream/stream.h>
Public Types
enum Capability {
StreamWrite = BIT(0),
StreamRead = BIT(1),
StreamPosition = BIT(2)
}
enum StreamStatus {
Ok = 0,
IOError,
EOS,
IllegalCall,
Closed,
UnknownError
}
Status constants for the stream.
Public Member Functions
Stream ()
virtual ~Stream ()
virtual Stream * clone () const
Create an exact replica of this stream.
bool copyFrom (Stream *other)
Copy the contents of another stream into this one.
virtual U32 getPosition () const =0
Gets the position in the stream.
Stream::StreamStatus getStatus () const
Gets the status of the stream.
virtual U32 getStreamSize ()=0
Gets the size of the stream.
virtual bool hasCapability (const Capability caps) const =0
Checks to see if this stream has the capability of a given function.
bool Put (char character)
void read (String *str)
bool read (ColorI *)
Read an integral color from the stream.
bool read (ColorF *)
Read a floating point color from the stream.
bool read (NetAddress *)
Read a network address from the stream.
bool read (NetSocket *)
Read a network socket from the stream.
bool read (RawData *)
Read some raw data from the stream.
bool read (Torque::ByteBuffer *)
Read some raw data from the stream.
bool read (const U32 in_numBytes, void *out_pBuffer)
bool read (bool *out_pRead)
void readLine (U8 *buffer, U32 bufferSize)
Reads a line from the stream.
void readLongString (U32 maxStringLen, char *stringBuf)
Reads a string that could potentially be more than 255 characters long.
virtual void readString (char stringBuf[256])
Reads a string of maximum 255 characters long.
const char * readSTString (bool casesens=false)
Reads a string and inserts it into the StringTable.
virtual bool setPosition (const U32 in_newPosition)=0
Sets the position of the stream. Returns if the new position is valid or not.
void write (const String &str)
bool write (const ColorI &)
Write an integral color to the stream.
bool write (const ColorF &)
Write a floating point color to the stream.
bool write (const NetAddress &)
Write a network address to the stream.
bool write (const NetSocket &)
Write a network socket to the stream.
bool write (const RawData &)
Write some raw data onto the stream.
bool write (const Torque::ByteBuffer &)
Write some raw data onto the stream.
bool write (const U32 in_numBytes, const void *in_pBuffer)
bool write (const bool &in_rWrite)
bool writeFormattedBuffer (const char *format,...)
Writes a formatted buffer to the stream.
void writeLine (const U8 *buffer)
writes a line to the stream
void writeLongString (U32 maxStringLen, const char *string)
Writes a string to the stream.
virtual void writeString (const char *stringBuf, S32 maxLen=255)
Writes a string to the stream.
bool writeStringBuffer (const char *buffer)
Writes a NULL terminated string buffer.
void writeTabs (U32 count)
Write a number of tabs to this stream.
void writeText (const char *text)
Write raw text to the stream.
Static Public Member Functions
static const char * getStatusString (const StreamStatus in_status)
Gets a printable string form of the status.
Protected Member Functions
virtual bool _read (const U32 in_numBytes, void *out_pBuffer)=0
virtual void _read (String *str)
virtual bool _write (const U32 in_numBytes, const void *in_pBuffer)=0
virtual void _write (const String &str)
void setStatus (const StreamStatus in_newStatus)
Detailed Description
Base stream class for streaming data across a specific media.
Member Enumeration Documentation
enum Stream::Capability
Enumerator
StreamWrite
Can this stream write?
StreamRead
Can this stream read?
StreamPosition
Can this stream position?
enum Stream::StreamStatus
Status constants for the stream.
Enumerator
Ok
Ok!
IOError
Read or Write error.
EOS
End of Stream reached (mostly for reads)
IllegalCall
An unsupported operation used. Always w/ accompanied by AssertWarn.
Closed
Tried to operate on a closed stream (or detached filter)
UnknownError
Catchall.
Constructor & Destructor Documentation
Stream::Stream ()
virtual Stream::~Stream () inline virtual
Member Function Documentation
virtual bool Stream::_read (const U32 in_numBytes, void * out_pBuffer) protected pure virtual
Implemented in BitStream, Zip::ZipStatFilter, ZipSubWStream, MemStream, ZipSubRStream, FileStream, ZipCryptRStream, ResizeFilterStream, and FilterStream.
virtual void Stream::_read (String * str) protected virtual
virtual bool Stream::_write (const U32 in_numBytes, const void * in_pBuffer) protected pure virtual
Implemented in BitStream, Zip::ZipStatFilter, ZipSubWStream, MemStream, FileStream, and FilterStream.
virtual void Stream::_write (const String & str) protected virtual
virtual Stream* Stream::clone () const virtual
Create an exact replica of this stream.
Return NULL if the cloning fails.
Reimplemented in FileStream.
bool Stream::copyFrom (Stream * other)
Copy the contents of another stream into this one.
Referenced by StreamObject::copyFrom().
virtual U32 Stream::getPosition () const pure virtual
Gets the position in the stream.
Implemented in BitStream, ZipSubWStream, MemStream, ZipSubRStream, ResizeFilterStream, ZipCryptRStream, FileStream, and FilterStream.
Referenced by StreamObject::getPosition().
Stream::StreamStatus Stream::getStatus () const inline
Gets the status of the stream.
Referenced by StreamObject::isEOS().
static const char* Stream::getStatusString (const StreamStatus in_status) static
Gets a printable string form of the status.
virtual U32 Stream::getStreamSize () pure virtual
Gets the size of the stream.
Implemented in BitStream, ZipSubWStream, MemStream, ZipSubRStream, ResizeFilterStream, FileStream, and FilterStream.
Referenced by StreamObject::getStreamSize().
virtual bool Stream::hasCapability (const Capability caps) const pure virtual
Checks to see if this stream has the capability of a given function.
Implemented in BitStream, ZipSubWStream, MemStream, ZipSubRStream, FileStream, and FilterStream.
bool Stream::Put (char character) inline
References Torque::write().
void Stream::read (String * str) inline
References Torque::read(), and Torque::write().
Referenced by Zip::ZipStatFilter::_read(), Journal::Read(), IOHelper::reads(), and SetMissionCRCEvent::unpack().
bool Stream::read (ColorI *)
Read an integral color from the stream.
bool Stream::read (ColorF *)
Read a floating point color from the stream.
bool Stream::read (NetAddress *)
Read a network address from the stream.
bool Stream::read (NetSocket *)
Read a network socket from the stream.
bool Stream::read (RawData *)
Read some raw data from the stream.
bool Stream::read (Torque::ByteBuffer *)
Read some raw data from the stream.
bool Stream::read (const U32 in_numBytes, void * out_pBuffer) inline
bool Stream::read (bool * out_pRead) inline
References Torque::read().
void Stream::readLine (U8 * buffer, U32 bufferSize)
Reads a line from the stream.
Parameters
buffer buffer to be read into
bufferSize max size of the buffer. Will not read more than the "bufferSize"
void Stream::readLongString (U32 maxStringLen, char * stringBuf)
Reads a string that could potentially be more than 255 characters long.
Parameters
maxStringLen Maximum length to read. If the string is longer than maxStringLen, only maxStringLen bytes will be read.
stringBuf buffer where data is read into
virtual void Stream::readString (char stringBuf[256]) virtual
Reads a string of maximum 255 characters long.
Reimplemented in BitStream.
Referenced by Journal::ReadString().
const char* Stream::readSTString (bool casesens = false)
Reads a string and inserts it into the StringTable.
See also
StringTable
Referenced by StreamObject::readSTString().
virtual bool Stream::setPosition (const U32 in_newPosition) pure virtual
Sets the position of the stream. Returns if the new position is valid or not.
Implemented in BitStream, ZipSubWStream, MemStream, ZipSubRStream, Zip::ZipTempStream, ResizeFilterStream, ZipCryptRStream, FileStream, and FilterStream.
Referenced by StreamObject::setPosition().
void Stream::setStatus (const StreamStatus in_newStatus) inline protected
void Stream::write (const String & str) inline
Referenced by Zip::ZipStatFilter::_write(), SetMissionCRCEvent::pack(), Journal::Write(), ScenePolyhedralObject< Base, P >::writeFields(), and IOHelper::writes().
bool Stream::write (const ColorI &)
Write an integral color to the stream.
bool Stream::write (const ColorF &)
Write a floating point color to the stream.
bool Stream::write (const NetAddress &)
Write a network address to the stream.
bool Stream::write (const NetSocket &)
Write a network socket to the stream.
bool Stream::write (const RawData &)
Write some raw data onto the stream.
bool Stream::write (const Torque::ByteBuffer &)
Write some raw data onto the stream.
bool Stream::write (const U32 in_numBytes, const void * in_pBuffer) inline
References DECLARE_OVERLOADED_READ, and DECLARE_OVERLOADED_WRITE.
bool Stream::write (const bool & in_rWrite) inline
References Torque::write().
bool Stream::writeFormattedBuffer (const char * format, ...)
Writes a formatted buffer to the stream.
NOTE: A maximum string length of 4K is allowed.
void Stream::writeLine (const U8 * buffer)
writes a line to the stream
Referenced by ScenePolyhedralObject< Base, P >::writeFields(), and StreamObject::writeLine().
void Stream::writeLongString (U32 maxStringLen, const char * string)
Writes a string to the stream.
This function is slightly unstable. Only use this if you have a valid string that is not empty. writeString is safer.
Referenced by StreamObject::writeLongString().
virtual void Stream::writeString (const char * stringBuf, S32 maxLen = 255) virtual
Writes a string to the stream.
Reimplemented in BitStream.
Referenced by StreamObject::writeString(), and Journal::WriteString().
bool Stream::writeStringBuffer (const char * buffer) inline
Writes a NULL terminated string buffer.
References Torque::write().
void Stream::writeTabs (U32 count) inline
Write a number of tabs to this stream.
References Torque::write().
Referenced by ScenePolyhedralObject< Base, P >::writeFields().
void Stream::writeText (const char * text)
Write raw text to the stream.
Copyright © GarageGames, LLC. All Rights Reserved.