MeshRoadSegment Class Reference
Main Modules Class List Namespace List Online
MeshRoadSegment Class Reference
#include <environment/meshRoad.h>
Public Member Functions
MeshRoadSegment ()
MeshRoadSegment (MeshRoadSlice *rs0, MeshRoadSlice *rs1, const MatrixF &roadMat)
bool containsPoint (const Point3F &pnt) const
F32 distanceToSurface (const Point3F &pnt) const
const Point3F & getP00 () const
const Point3F & getP01 () const
const Point3F & getP10 () const
const Point3F & getP11 () const
Point3F getSurfaceCenter () const
Point3F getSurfaceNormal () const
const Box3F & getWorldBounds () const
bool intersectBox (const Box3F &bounds) const
F32 length () const
Point3F & operator[] (U32)
const Point3F & operator[] (U32) const
Point3F & operator[] (S32 i)
const Point3F & operator[] (S32 i) const
void set (MeshRoadSlice *rs0, MeshRoadSlice *rs1)
F32 TexCoordEnd () const
F32 TexCoordStart () const
Public Attributes
MeshRoadSlice * slice0
MeshRoadSlice * slice1
Protected Attributes
U32 columns
U32 endIndex
U32 endVert
U32 mPlaneCount
PlaneF mPlanes [6]
U32 numTriangles
U32 numVerts
Box3F objectbounds
U32 rows
U32 startIndex
U32 startVert
Box3F worldbounds
Constructor & Destructor Documentation
MeshRoadSegment::MeshRoadSegment ()
MeshRoadSegment::MeshRoadSegment (MeshRoadSlice * rs0, MeshRoadSlice * rs1, const MatrixF & roadMat)
Member Function Documentation
bool MeshRoadSegment::containsPoint (const Point3F & pnt) const
F32 MeshRoadSegment::distanceToSurface (const Point3F & pnt) const
const Point3F& MeshRoadSegment::getP00 () const inline
const Point3F& MeshRoadSegment::getP01 () const inline
const Point3F& MeshRoadSegment::getP10 () const inline
const Point3F& MeshRoadSegment::getP11 () const inline
Point3F MeshRoadSegment::getSurfaceCenter () const inline
Point3F MeshRoadSegment::getSurfaceNormal () const inline
const Box3F& MeshRoadSegment::getWorldBounds () const inline
bool MeshRoadSegment::intersectBox (const Box3F & bounds) const
F32 MeshRoadSegment::length () const inline
Point3F & MeshRoadSegment::operator[] (U32 index) inline
References MeshRoadSlice::p0, MeshRoadSlice::p2, MeshRoadSlice::pb0, and MeshRoadSlice::pb2.
const Point3F & MeshRoadSegment::operator[] (U32 index) const inline
References MeshRoadSlice::p0, MeshRoadSlice::p2, MeshRoadSlice::pb0, and MeshRoadSlice::pb2.
Point3F& MeshRoadSegment::operator[] (S32 i) inline
References operator[]().
Referenced by operator[]().
const Point3F& MeshRoadSegment::operator[] (S32 i) const inline
References operator[]().
Referenced by operator[]().
void MeshRoadSegment::set (MeshRoadSlice * rs0, MeshRoadSlice * rs1)
F32 MeshRoadSegment::TexCoordEnd () const inline
F32 MeshRoadSegment::TexCoordStart () const inline
Member Data Documentation
U32 MeshRoadSegment::columns protected
U32 MeshRoadSegment::endIndex protected
U32 MeshRoadSegment::endVert protected
U32 MeshRoadSegment::mPlaneCount protected
PlaneF MeshRoadSegment::mPlanes[6] protected
U32 MeshRoadSegment::numTriangles protected
U32 MeshRoadSegment::numVerts protected
Box3F MeshRoadSegment::objectbounds protected
U32 MeshRoadSegment::rows protected
MeshRoadSlice* MeshRoadSegment::slice0
MeshRoadSlice* MeshRoadSegment::slice1
U32 MeshRoadSegment::startIndex protected
U32 MeshRoadSegment::startVert protected
Box3F MeshRoadSegment::worldbounds protected
Copyright © GarageGames, LLC. All Rights Reserved.