VertexPolyList Class Reference
Main Modules Class List Namespace List Online
VertexPolyList Class Reference
A simple polylist which only gathers the unique verticies passed to it.
#include <collision/vertexPolyList.h>
Public Member Functions
VertexPolyList ()
virtual ~VertexPolyList ()
U32 addPlane (const PlaneF &plane)
Adds a plane to the poly list, and returns an ID number for that point.
U32 addPoint (const Point3F &p)
Adds a point to the poly list, and returns an ID number for that point.
void begin (BaseMatInstance *material, U32 surfaceKey)
Start a surface.
void clear ()
Clears any captured verts.
void end ()
Mark the end of a surface.
const PlaneF & getIndexedPlane (const U32 index)
A helper function to convert a plane index to a PlaneF structure.
Vector< Point3F > & getVertexList ()
Returns the vertex list.
const Vector< Point3F > & getVertexList () const
Returns the constant vertex list.
bool isEmpty () const
Returns true if the polylist contains no verts.
void plane (U32 v1, U32 v2, U32 v3)
Indicate the plane of the surface.
void plane (const PlaneF &p)
Indicate the plane of the surface.
void plane (const U32 index)
Indicate the plane of the surface.
void vertex (U32 vi)
Reference a vertex which is in this surface.
Public Member Functions inherited from AbstractPolyList
AbstractPolyList ()
virtual ~AbstractPolyList ()
void setBaseTransform (const MatrixF &mat)
void setTransform (const MatrixF *mat, const Point3F &scale)
Sets the transform applying to the current stream of vertices.
void getTransform (MatrixF *mat, Point3F *scale)
Gets the transform applying to the current stream of vertices.
void setObject (SceneObject *)
This is called by the object which is currently feeding us vertices, to tell us who it is.
void addBox (const Box3F &box, BaseMatInstance *material=NULL)
Add a box via the query interface (below).
void doConstruct ()
virtual U32 addPointAndNormal (const Point3F &p, const Point3F &normal)
Adds a point and normal to the poly list, and returns an ID number for them.
virtual bool getMapping (MatrixF *, Box3F *)
Return list transform and bounds in list space.
void setInterestNormal (const Point3F &normal)
void clearInterestNormal ()
virtual bool isInterestedInPlane (const PlaneF &plane)
virtual bool isInterestedInPlane (const U32 index)
Protected Attributes
Vector< Point3F > mVertexList
The unique verts we captured.
Protected Attributes inherited from AbstractPolyList
MatrixF mBaseMatrix
SceneObject * mCurrObject
Point3F mInterestNormal
bool mInterestNormalRegistered
MatrixF mMatrix
PlaneTransformer mPlaneTransformer
Point3F mScale
MatrixF mTransformMatrix
Additional Inherited Members
Detailed Description
A simple polylist which only gathers the unique verticies passed to it.
Constructor & Destructor Documentation
VertexPolyList::VertexPolyList ()
virtual VertexPolyList::~VertexPolyList () inline virtual
References addPoint().
Member Function Documentation
U32 VertexPolyList::addPlane (const PlaneF & plane) inline virtual
Adds a plane to the poly list, and returns an ID number for that point.
Implements AbstractPolyList.
U32 VertexPolyList::addPoint (const Point3F & p) virtual
Adds a point to the poly list, and returns an ID number for that point.
Implements AbstractPolyList.
Referenced by ~VertexPolyList().
void VertexPolyList::begin (BaseMatInstance * material, U32 surfaceKey) inline virtual
Start a surface.
Parameters
material A material ID for this surface.
surfaceKey A key value to associate with this surface.
Implements AbstractPolyList.
void VertexPolyList::clear ()
Clears any captured verts.
Referenced by end().
void VertexPolyList::end () inline virtual
Mark the end of a surface.
Implements AbstractPolyList.
References clear(), and getIndexedPlane().
const PlaneF& VertexPolyList::getIndexedPlane (const U32 index) virtual
A helper function to convert a plane index to a PlaneF structure.
Implements AbstractPolyList.
Referenced by end().
Vector<Point3F>& VertexPolyList::getVertexList () inline
Returns the vertex list.
References mVertexList.
const Vector<Point3F>& VertexPolyList::getVertexList () const inline
Returns the constant vertex list.
References mVertexList.
bool VertexPolyList::isEmpty () const inline virtual
Returns true if the polylist contains no verts.
Implements AbstractPolyList.
References Vector< T >::empty(), and mVertexList.
void VertexPolyList::plane (U32 v1, U32 v2, U32 v3) inline virtual
Indicate the plane of the surface.
Implements AbstractPolyList.
void VertexPolyList::plane (const PlaneF & p) inline virtual
Indicate the plane of the surface.
Implements AbstractPolyList.
void VertexPolyList::plane (const U32 index) inline virtual
Indicate the plane of the surface.
Implements AbstractPolyList.
void VertexPolyList::vertex (U32 vi) inline virtual
Reference a vertex which is in this surface.
Implements AbstractPolyList.
Member Data Documentation
Vector<Point3F> VertexPolyList::mVertexList protected
The unique verts we captured.
Referenced by getVertexList(), and isEmpty().
Copyright © GarageGames, LLC. All Rights Reserved.