Polytope Class Reference
Main Modules Class List Namespace List Online
Polytope Class Reference
#include <collision/polytope.h>
Classes
struct Collision
struct Edge
struct Face
struct StackElement
struct Vertex
struct Volume
Public Types
typedef Vector< Edge > EdgeList
typedef Vector< Face > FaceList
typedef Vector< Vertex > VertexList
typedef Vector< Volume > VolumeList
typedef Vector< StackElement > VolumeStack
Public Member Functions
Polytope ()
void buildBox (const MatrixF &transform, const Box3F &box)
bool didIntersect ()
void extrudeFace (S32 fi, const VectorF &vec, Polytope *out)
bool findCollision (const VectorF &vec, Polytope::Collision *best)
void intersect (SimObject *, const BSPNode *node)
Public Attributes
EdgeList mEdgeList
FaceList mFaceList
VertexList mVertexList
VolumeList mVolumeList
S32 sideCount
Member Typedef Documentation
typedef Vector<Edge> Polytope::EdgeList
typedef Vector<Face> Polytope::FaceList
typedef Vector<Vertex> Polytope::VertexList
typedef Vector<Volume> Polytope::VolumeList
typedef Vector<StackElement> Polytope::VolumeStack
Constructor & Destructor Documentation
Polytope::Polytope ()
Member Function Documentation
void Polytope::buildBox (const MatrixF & transform, const Box3F & box)
bool Polytope::didIntersect () inline
References extrudeFace(), findCollision(), and Vector< T >::size().
void Polytope::extrudeFace (S32 fi, const VectorF & vec, Polytope * out)
Referenced by didIntersect().
bool Polytope::findCollision (const VectorF & vec, Polytope::Collision * best)
Referenced by didIntersect().
void Polytope::intersect (SimObject * , const BSPNode * node)
Member Data Documentation
EdgeList Polytope::mEdgeList
FaceList Polytope::mFaceList
VertexList Polytope::mVertexList
VolumeList Polytope::mVolumeList
S32 Polytope::sideCount
Copyright © GarageGames, LLC. All Rights Reserved.