MaterialList Class Reference
Main Modules Class List Namespace List Online
MaterialList Class Reference
#include <materials/materialList.h>
Public Member Functions
MaterialList ()
MaterialList (U32 materialCount, const char **materialNames)
MaterialList (const MaterialList *)
Note: this is not to be confused with MaterialList(const MaterialList&).
virtual ~MaterialList ()
void clearMatInstList ()
bool empty () const
virtual void free ()
GFXTextureObject * getDiffuseTexture (U32 index)
BaseMatInstance * getMaterialInst (U32 index) const
Return the material instance or NULL if the index is out of bounds.
const String & getMaterialName (U32 index) const
const Vector< String > & getMaterialNameList () const
void initMatInstances (const FeatureSet &features, const GFXVertexFormat *vertexFormat)
Initialize material instances in material list.
void mapMaterials ()
U32 push_back (const String &filename, Material *=0)
bool read (Stream &stream)
bool readText (Stream &stream, U8 firstByte)
bool readText (Stream &stream)
void set (U32 materialCount, const char **materialNames)
void setMaterialInst (BaseMatInstance *matInst, U32 index)
void setMaterialName (U32 index, const String &name)
void setTextureLookupPath (const String &path)
U32 size () const
bool write (Stream &stream)
bool writeText (Stream &stream)
Public Attributes
Vector< BaseMatInstance * > mMatInstList
Protected Member Functions
virtual void mapMaterial (U32 index)
Protected Attributes
String mLookupPath
Vector< String > mMaterialNames
Material 'mapTo' targets.
Constructor & Destructor Documentation
MaterialList::MaterialList ()
MaterialList::MaterialList (U32 materialCount, const char ** materialNames)
virtual MaterialList::~MaterialList () virtual
MaterialList::MaterialList (const MaterialList *) explicit
Note: this is not to be confused with MaterialList(const MaterialList&).
Copying a material list in the middle of it's lifetime is not a good thing, so we force it to copy at construction time by restricting the copy syntax to ML* pML = new ML(&copy);
Member Function Documentation
void MaterialList::clearMatInstList ()
Referenced by setTextureLookupPath().
bool MaterialList::empty () const inline
References Vector< T >::empty(), and mMaterialNames.
virtual void MaterialList::free () virtual
Reimplemented in TSMaterialList.
Referenced by setTextureLookupPath().
GFXTextureObject* MaterialList::getDiffuseTexture (U32 index)
Referenced by getMaterialName().
BaseMatInstance* MaterialList::getMaterialInst (U32 index) const inline
Return the material instance or NULL if the index is out of bounds.
References mMatInstList, setMaterialInst(), and Vector< T >::size().
const String& MaterialList::getMaterialName (U32 index) const inline
References getDiffuseTexture(), and mMaterialNames.
const Vector<String>& MaterialList::getMaterialNameList () const inline
References mMaterialNames.
void MaterialList::initMatInstances (const FeatureSet & features, const GFXVertexFormat * vertexFormat)
Initialize material instances in material list.
Referenced by size().
virtual void MaterialList::mapMaterial (U32 index) protected virtual
Reimplemented in TSMaterialList.
void MaterialList::mapMaterials ()
Referenced by size().
U32 MaterialList::push_back (const String & filename, Material * = 0)
Referenced by setTextureLookupPath().
bool MaterialList::read (Stream & stream)
Referenced by size().
bool MaterialList::readText (Stream & stream, U8 firstByte)
Referenced by size().
bool MaterialList::readText (Stream & stream)
void MaterialList::set (U32 materialCount, const char ** materialNames)
void MaterialList::setMaterialInst (BaseMatInstance * matInst, U32 index)
Referenced by getMaterialInst().
void MaterialList::setMaterialName (U32 index, const String & name)
Referenced by setTextureLookupPath().
void MaterialList::setTextureLookupPath (const String & path) inline
References clearMatInstList(), free(), mLookupPath, push_back(), and setMaterialName().
U32 MaterialList::size () const inline
References initMatInstances(), mapMaterials(), mMaterialNames, read(), readText(), Vector< T >::size(), write(), and writeText().
bool MaterialList::write (Stream & stream)
Referenced by size().
bool MaterialList::writeText (Stream & stream)
Referenced by size().
Member Data Documentation
String MaterialList::mLookupPath protected
Referenced by setTextureLookupPath().
Vector<String> MaterialList::mMaterialNames protected
Material 'mapTo' targets.
Referenced by empty(), getMaterialName(), getMaterialNameList(), and size().
Vector<BaseMatInstance*> MaterialList::mMatInstList
Referenced by getMaterialInst().
Copyright © GarageGames, LLC. All Rights Reserved.