SimpleQueryList Class Reference
Main Modules Class List Namespace List Online
SimpleQueryList Class Reference
For simple queries. Simply creates a vector of the objects.
#include <scene/sceneContainer.h>
Public Member Functions
SimpleQueryList ()
void insertObject (SceneObject *obj)
Static Public Member Functions
static void insertionCallback (SceneObject *obj, void *key)
Public Attributes
Vector< SceneObject * > mList
Detailed Description
For simple queries. Simply creates a vector of the objects.
Constructor & Destructor Documentation
SimpleQueryList::SimpleQueryList () inline
Member Function Documentation
static void SimpleQueryList::insertionCallback (SceneObject * obj, void * key) inline static
References insertObject().
void SimpleQueryList::insertObject (SceneObject * obj) inline
References Vector< T >::push_back().
Referenced by insertionCallback().
Member Data Documentation
Vector< SceneObject* > SimpleQueryList::mList
Copyright © GarageGames, LLC. All Rights Reserved.