NavContext Class Reference
Main Modules Class List Namespace List Online
NavContext Class Reference
Implements the rcContext interface in Torque.
#include <navigation/navContext.h>
Public Member Functions
NavContext ()
Default constructor.
void log (const rcLogCategory category, const String &msg)
Protected Member Functions
virtual int doGetAccumulatedTime (const rcTimerLabel label) const
Returns the total accumulated time of the specified performance timer.
virtual void doLog (const rcLogCategory category, const char *msg, const int len)
Logs a message.
virtual void doResetLog ()
Clears all log entries.
virtual void doResetTimers ()
Clears all timers. (Resets all to unused.)
virtual void doStartTimer (const rcTimerLabel label)
Starts the specified performance timer.
virtual void doStopTimer (const rcTimerLabel label)
Stops the specified performance timer.
Detailed Description
Implements the rcContext interface in Torque.
Constructor & Destructor Documentation
NavContext::NavContext () inline
Default constructor.
References doGetAccumulatedTime(), doLog(), doResetLog(), doResetTimers(), doStartTimer(), doStopTimer(), and log().
Member Function Documentation
virtual int NavContext::doGetAccumulatedTime (const rcTimerLabel label) const protected virtual
Returns the total accumulated time of the specified performance timer.
Parameters
[in] label The category of the timer.
Returns
The accumulated time of the timer, or -1 if timers are disabled or the timer has never been started.
Referenced by NavContext().
virtual void NavContext::doLog (const rcLogCategory category, const char * msg, const int len) protected virtual
Logs a message.
Parameters
[in] category The category of the message.
[in] msg The formatted message.
[in] len The length of the formatted message.
Referenced by NavContext().
virtual void NavContext::doResetLog () protected virtual
Clears all log entries.
Referenced by NavContext().
virtual void NavContext::doResetTimers () protected virtual
Clears all timers. (Resets all to unused.)
Referenced by NavContext().
virtual void NavContext::doStartTimer (const rcTimerLabel label) protected virtual
Starts the specified performance timer.
Parameters
[in] label The category of timer.
Referenced by NavContext().
virtual void NavContext::doStopTimer (const rcTimerLabel label) protected virtual
Stops the specified performance timer.
Parameters
[in] label The category of the timer.
Referenced by NavContext().
void NavContext::log (const rcLogCategory category, const String & msg)
Referenced by NavContext().
Copyright © GarageGames, LLC. All Rights Reserved.