PlatformCursorControllerSDL Class Reference
Main Modules Class List Namespace List Online
PlatformCursorControllerSDL Class Reference
#include <windowManager/sdl/sdlCursorController.h>
Public Member Functions
PlatformCursorControllerSDL (PlatformWindow *owner)
virtual void getCursorPosition (Point2I &point)
S32 getDoubleClickHeight ()
U32 getDoubleClickTime ()
S32 getDoubleClickWidth ()
virtual bool isCursorVisible ()
virtual void setCursorPosition (S32 x, S32 y)
void setCursorShape (U32 cursorID)
void setCursorShape (const UTF8 *fileName, bool reload)
virtual void setCursorVisible (bool visible)
Public Member Functions inherited from PlatformCursorController
PlatformCursorController (PlatformWindow *owner)
virtual ~PlatformCursorController ()
virtual void popCursor ()
virtual void pushCursor (S32 cursorID)
virtual void pushCursor (const UTF8 *fileName)
virtual void refreshCursor ()
virtual void setCursorShape (const Cursor_Shape &shape, bool reload)
Additional Inherited Members
Public Types inherited from PlatformCursorController
enum {
curArrow = 0,
curWait,
curPlus,
curResizeVert,
curResizeHorz,
curResizeAll,
curIBeam,
curResizeNESW,
curResizeNWSE,
curHand
}
Protected Attributes inherited from PlatformCursorController
Vector< Cursor_Shape > mCursors
PlatformWindow * mOwner
The PlatformWindow that owns this Cursor Controller.
Constructor & Destructor Documentation
PlatformCursorControllerSDL::PlatformCursorControllerSDL (PlatformWindow * owner) inline
References PlatformCursorController::curArrow, getCursorPosition(), getDoubleClickHeight(), getDoubleClickTime(), getDoubleClickWidth(), isCursorVisible(), PlatformCursorController::pushCursor(), setCursorPosition(), setCursorShape(), and setCursorVisible().
Member Function Documentation
virtual void PlatformCursorControllerSDL::getCursorPosition (Point2I & point) virtual
Implements PlatformCursorController.
Referenced by PlatformCursorControllerSDL().
S32 PlatformCursorControllerSDL::getDoubleClickHeight () virtual
Implements PlatformCursorController.
Referenced by PlatformCursorControllerSDL().
U32 PlatformCursorControllerSDL::getDoubleClickTime () virtual
Implements PlatformCursorController.
Referenced by PlatformCursorControllerSDL().
S32 PlatformCursorControllerSDL::getDoubleClickWidth () virtual
Implements PlatformCursorController.
Referenced by PlatformCursorControllerSDL().
virtual bool PlatformCursorControllerSDL::isCursorVisible () virtual
Implements PlatformCursorController.
Referenced by PlatformCursorControllerSDL().
virtual void PlatformCursorControllerSDL::setCursorPosition (S32 x, S32 y) virtual
Implements PlatformCursorController.
Referenced by PlatformCursorControllerSDL().
void PlatformCursorControllerSDL::setCursorShape (U32 cursorID) virtual
Implements PlatformCursorController.
Referenced by PlatformCursorControllerSDL().
void PlatformCursorControllerSDL::setCursorShape (const UTF8 * fileName, bool reload) virtual
Implements PlatformCursorController.
virtual void PlatformCursorControllerSDL::setCursorVisible (bool visible) virtual
Implements PlatformCursorController.
Referenced by PlatformCursorControllerSDL().
Copyright © GarageGames, LLC. All Rights Reserved.