OculusVRHMDDevice Class Reference
Main Modules Class List Namespace List Online
OculusVRHMDDevice Class Reference
#include <platform/input/oculusVR/oculusVRHMDDevice.h>
Public Types
enum SimulationTypes { ST_RIFT_PREVIEW }
Public Member Functions
OculusVRHMDDevice ()
~OculusVRHMDDevice ()
void cleanUp ()
void clearRenderTargets ()
void dismissWarning ()
String dumpMetrics ()
Point2I generateRenderTarget (GFXTextureTargetRef &target, GFXTexHandle &depth, Point2I desiredSize)
virtual GameConnection * getCurrentConnection ()
S32 getDisplayDeviceId () const
const char * getDisplayDeviceType () const
void getEyeOffsets (Point3F *offsets) const
Returns eye offsets in torque coordinate space, i.e. z being up, x being left-right, and y being depth (forward).
void getFovPorts (FovPort *dest) const
void getFrameEyePose (DisplayPose *outPose, U32 eyeId) const
F32 getIPD () const
F32 getLensSeparation () const
const char * getManufacturer () const
GFXTexHandle getPreviewTexture ()
const char * getProductName () const
F32 getProfileIPD () const
const Point2F & getProjectionCenterOffset () const
const Point2I & getResolution () const
const Point2F & getScreenSize () const
OculusVRSensorDevice * getSensorDevice ()
void getStereoTargets (GFXTextureTarget **dest) const
void getStereoViewports (RectI *dest) const
U32 getVersion () const
bool isDisplayingWarning ()
bool isValid () const
void onDeviceDestroy ()
void onEndFrame ()
void onStartFrame ()
void set (ovrHmd hmd, ovrGraphicsLuid luid, U32 actionCodeIndex)
virtual void setCurrentConnection (GameConnection *connection)
void setDrawCanvas (GuiCanvas *canvas)
Designates canvas we are drawing to. Also updates render targets.
void setIPD (F32 ipd)
void setOptimalDisplaySize (GuiCanvas *canvas)
bool setupTargets ()
void updateCaps ()
Public Attributes
F32 mCurrentPixelDensity
ovrTexture * mDebugMirrorTexture
GFXTexHandle mDebugMirrorTextureHandle
ovrLayerDirect mDebugRenderLayer
GFXTexHandle mDebugStereoTexture
GFXDevice::GFXDeviceRenderStyles mDesiredRenderingMode
GuiCanvas * mDrawCanvas
GFXTextureTargetRef mEyeRT [2]
RectI mEyeViewport [2]
ovrTrackingState mLastTrackingState
ovrLayerEyeFov mRenderLayer
GFXFormat mRTFormat
ovrViewScaleDesc mScaleDesc
GFXTexHandle mStereoDepthTexture
GFXTextureTargetRef mStereoRT
OculusTexture * mTextureSwapSet
F32 smDesiredPixelDensity
Protected Member Functions
void updateRenderInfo ()
Protected Attributes
U32 mActionCodeIndex
GameConnection * mConnection
U32 mCurrentCaps
ovrHmd mDevice
String mDisplayDeviceType
S32 mDisplayId
ovrEyeRenderDesc mEyeRenderDesc [2]
bool mFrameReady
F32 mInterpupillaryDistance
bool mIsValid
F32 mLensSeparation
ovrGraphicsLuid mLuid
String mManufacturer
String mProductName
F32 mProfileInterpupillaryDistance
Point2F mProjectionCenterOffset
bool mRenderConfigurationDirty
Point2I mResolution
Point2F mScreenSize
OculusVRSensorDevice * mSensor
U32 mSupportedCaps
bool mTimewarp
U32 mVersion
bool mVsync
Member Enumeration Documentation
enum OculusVRHMDDevice::SimulationTypes
Enumerator
ST_RIFT_PREVIEW
Constructor & Destructor Documentation
OculusVRHMDDevice::OculusVRHMDDevice ()
OculusVRHMDDevice::~OculusVRHMDDevice ()
Member Function Documentation
void OculusVRHMDDevice::cleanUp ()
void OculusVRHMDDevice::clearRenderTargets ()
Referenced by getEyeOffsets().
void OculusVRHMDDevice::dismissWarning ()
Referenced by getEyeOffsets().
String OculusVRHMDDevice::dumpMetrics ()
Referenced by getCurrentConnection().
Point2I OculusVRHMDDevice::generateRenderTarget (GFXTextureTargetRef & target, GFXTexHandle & depth, Point2I desiredSize)
Referenced by getEyeOffsets().
virtual GameConnection* OculusVRHMDDevice::getCurrentConnection () inline virtual
References dumpMetrics(), getPreviewTexture(), and mConnection.
S32 OculusVRHMDDevice::getDisplayDeviceId () const inline
References mDisplayId.
const char* OculusVRHMDDevice::getDisplayDeviceType () const inline
References String::c_str().
void OculusVRHMDDevice::getEyeOffsets (Point3F * offsets) const inline
Returns eye offsets in torque coordinate space, i.e. z being up, x being left-right, and y being depth (forward).
References clearRenderTargets(), dismissWarning(), generateRenderTarget(), getFrameEyePose(), isDisplayingWarning(), onDeviceDestroy(), onEndFrame(), onStartFrame(), setupTargets(), and updateCaps().
void OculusVRHMDDevice::getFovPorts (FovPort * dest) const inline
References dMemcpy(), and mRenderLayer.
void OculusVRHMDDevice::getFrameEyePose (DisplayPose * outPose, U32 eyeId) const
Referenced by getEyeOffsets().
F32 OculusVRHMDDevice::getIPD () const inline
References mInterpupillaryDistance, and setIPD().
F32 OculusVRHMDDevice::getLensSeparation () const inline
References mLensSeparation.
const char* OculusVRHMDDevice::getManufacturer () const inline
References String::c_str().
GFXTexHandle OculusVRHMDDevice::getPreviewTexture ()
Referenced by getCurrentConnection().
const char* OculusVRHMDDevice::getProductName () const inline
References String::c_str().
F32 OculusVRHMDDevice::getProfileIPD () const inline
References mProfileInterpupillaryDistance.
const Point2F& OculusVRHMDDevice::getProjectionCenterOffset () const inline
References mProjectionCenterOffset.
const Point2I& OculusVRHMDDevice::getResolution () const inline
References mResolution.
const Point2F& OculusVRHMDDevice::getScreenSize () const inline
References mScreenSize.
OculusVRSensorDevice* OculusVRHMDDevice::getSensorDevice () inline
References mSensor.
void OculusVRHMDDevice::getStereoTargets (GFXTextureTarget ** dest) const inline
References mEyeRT.
void OculusVRHMDDevice::getStereoViewports (RectI * dest) const inline
References dMemcpy(), and mEyeViewport.
U32 OculusVRHMDDevice::getVersion () const inline
References mVersion.
bool OculusVRHMDDevice::isDisplayingWarning ()
Referenced by getEyeOffsets().
bool OculusVRHMDDevice::isValid () const inline
References mIsValid.
void OculusVRHMDDevice::onDeviceDestroy ()
Referenced by getEyeOffsets().
void OculusVRHMDDevice::onEndFrame ()
Referenced by getEyeOffsets().
void OculusVRHMDDevice::onStartFrame ()
Referenced by getEyeOffsets().
void OculusVRHMDDevice::set (ovrHmd hmd, ovrGraphicsLuid luid, U32 actionCodeIndex)
virtual void OculusVRHMDDevice::setCurrentConnection (GameConnection * connection) inline virtual
void OculusVRHMDDevice::setDrawCanvas (GuiCanvas * canvas) inline
Designates canvas we are drawing to. Also updates render targets.
References mDrawCanvas, and updateRenderInfo().
void OculusVRHMDDevice::setIPD (F32 ipd)
Referenced by getIPD().
void OculusVRHMDDevice::setOptimalDisplaySize (GuiCanvas * canvas)
bool OculusVRHMDDevice::setupTargets ()
Referenced by getEyeOffsets().
void OculusVRHMDDevice::updateCaps ()
Referenced by getEyeOffsets().
void OculusVRHMDDevice::updateRenderInfo () protected
Referenced by setDrawCanvas().
Member Data Documentation
U32 OculusVRHMDDevice::mActionCodeIndex protected
GameConnection* OculusVRHMDDevice::mConnection protected
Referenced by getCurrentConnection().
U32 OculusVRHMDDevice::mCurrentCaps protected
F32 OculusVRHMDDevice::mCurrentPixelDensity
ovrTexture* OculusVRHMDDevice::mDebugMirrorTexture
GFXTexHandle OculusVRHMDDevice::mDebugMirrorTextureHandle
ovrLayerDirect OculusVRHMDDevice::mDebugRenderLayer
GFXTexHandle OculusVRHMDDevice::mDebugStereoTexture
GFXDevice::GFXDeviceRenderStyles OculusVRHMDDevice::mDesiredRenderingMode
ovrHmd OculusVRHMDDevice::mDevice protected
String OculusVRHMDDevice::mDisplayDeviceType protected
S32 OculusVRHMDDevice::mDisplayId protected
Referenced by getDisplayDeviceId().
GuiCanvas* OculusVRHMDDevice::mDrawCanvas
Referenced by setDrawCanvas().
ovrEyeRenderDesc OculusVRHMDDevice::mEyeRenderDesc[2] protected
GFXTextureTargetRef OculusVRHMDDevice::mEyeRT[2]
Referenced by getStereoTargets().
RectI OculusVRHMDDevice::mEyeViewport[2]
Referenced by getStereoViewports().
bool OculusVRHMDDevice::mFrameReady protected
F32 OculusVRHMDDevice::mInterpupillaryDistance protected
Referenced by getIPD().
bool OculusVRHMDDevice::mIsValid protected
Referenced by isValid().
ovrTrackingState OculusVRHMDDevice::mLastTrackingState
F32 OculusVRHMDDevice::mLensSeparation protected
Referenced by getLensSeparation().
ovrGraphicsLuid OculusVRHMDDevice::mLuid protected
String OculusVRHMDDevice::mManufacturer protected
String OculusVRHMDDevice::mProductName protected
F32 OculusVRHMDDevice::mProfileInterpupillaryDistance protected
Referenced by getProfileIPD().
Point2F OculusVRHMDDevice::mProjectionCenterOffset protected
Referenced by getProjectionCenterOffset().
bool OculusVRHMDDevice::mRenderConfigurationDirty protected
ovrLayerEyeFov OculusVRHMDDevice::mRenderLayer
Referenced by getFovPorts().
Point2I OculusVRHMDDevice::mResolution protected
Referenced by getResolution().
GFXFormat OculusVRHMDDevice::mRTFormat
ovrViewScaleDesc OculusVRHMDDevice::mScaleDesc
Point2F OculusVRHMDDevice::mScreenSize protected
Referenced by getScreenSize().
OculusVRSensorDevice* OculusVRHMDDevice::mSensor protected
Referenced by getSensorDevice().
GFXTexHandle OculusVRHMDDevice::mStereoDepthTexture
GFXTextureTargetRef OculusVRHMDDevice::mStereoRT
U32 OculusVRHMDDevice::mSupportedCaps protected
OculusTexture* OculusVRHMDDevice::mTextureSwapSet
bool OculusVRHMDDevice::mTimewarp protected
U32 OculusVRHMDDevice::mVersion protected
Referenced by getVersion().
bool OculusVRHMDDevice::mVsync protected
F32 OculusVRHMDDevice::smDesiredPixelDensity
Copyright © GarageGames, LLC. All Rights Reserved.