RotationF Class Reference
Main Modules Class List Namespace List Online
RotationF Class Reference
Rotation Interop Utility class.
#include <math/mRotation.h>
Public Types
enum RotationTypes {
Euler = 0,
AxisAngle
}
enum UnitFormat {
Radians = 0,
Degrees
}
Public Member Functions
RotationF ()
Create an uninitialized point.
RotationF (const RotationF &)
Copy constructor.
RotationF (EulerF euler, UnitFormat format=Radians)
RotationF (F32 _x, F32 _y, F32 _z, UnitFormat format=Radians)
RotationF (AngAxisF aa, UnitFormat format=Radians)
RotationF (QuatF quat)
RotationF (MatrixF mat)
AngAxisF asAxisAngle (UnitFormat format=Radians) const
EulerF asEulerF (UnitFormat format=Radians) const
MatrixF asMatrixF () const
QuatF asQuatF () const
VectorF getDirection ()
void interpolate (const RotationF &_pt1, const RotationF &_pt2, F32 _factor)
F32 len () const
void lookAt (const Point3F &_origin, const Point3F &_target, const Point3F &_up=Point3F(0, 0, 1))
void normalize ()
S32 operator!= (const EulerF &) const
S32 operator!= (const AngAxisF &) const
S32 operator!= (const QuatF &) const
S32 operator!= (const MatrixF &) const
S32 operator!= (const RotationF &) const
RotationF operator+ (const EulerF &) const
RotationF operator+ (const AngAxisF &) const
RotationF operator+ (const QuatF &) const
RotationF operator+ (const MatrixF &) const
RotationF operator+ (const RotationF &) const
RotationF & operator+= (const EulerF &)
RotationF & operator+= (const AngAxisF &)
RotationF & operator+= (const QuatF &)
RotationF & operator+= (const MatrixF &)
RotationF & operator+= (const RotationF &)
RotationF operator- (const EulerF &) const
RotationF operator- (const AngAxisF &) const
RotationF operator- (const QuatF &) const
RotationF operator- (const MatrixF &) const
RotationF operator- (const RotationF &) const
RotationF & operator-= (const EulerF &)
RotationF & operator-= (const AngAxisF &)
RotationF & operator-= (const QuatF &)
RotationF & operator-= (const MatrixF &)
RotationF & operator-= (const RotationF &)
RotationF operator= (const EulerF &)
RotationF operator= (const AngAxisF &)
RotationF operator= (const QuatF &)
RotationF operator= (const MatrixF &)
RotationF & operator= (const RotationF &)
S32 operator== (const EulerF &) const
S32 operator== (const AngAxisF &) const
S32 operator== (const QuatF &) const
S32 operator== (const MatrixF &) const
S32 operator== (const RotationF &) const
void set (EulerF euler, UnitFormat format=Radians)
void set (F32 _x, F32 _y, F32 _z, UnitFormat format=Radians)
void set (AngAxisF aa, UnitFormat format=Radians)
void set (QuatF _quat)
void set (MatrixF _mat)
Public Attributes
RotationTypes mRotationType
F32 w
W co-ordinate.
F32 x
X co-ordinate.
F32 y
Y co-ordinate.
F32 z
Z co-ordinate.
Detailed Description
Rotation Interop Utility class.
Useful for easily handling rotations/orientations in transforms while manipulating or converting between formats.
Member Enumeration Documentation
enum RotationF::RotationTypes
Enumerator
Euler
AxisAngle
enum RotationF::UnitFormat
Enumerator
Radians
Degrees
Constructor & Destructor Documentation
RotationF::RotationF () inline
Create an uninitialized point.
References AxisAngle.
Referenced by operator!=(), operator+(), operator+=(), operator-(), operator-=(), operator=(), and operator==().
RotationF::RotationF (const RotationF & _copy) inline
Copy constructor.
RotationF::RotationF (EulerF euler, UnitFormat format = Radians)
RotationF::RotationF (F32 _x, F32 _y, F32 _z, UnitFormat format = Radians)
RotationF::RotationF (AngAxisF aa, UnitFormat format = Radians)
RotationF::RotationF (QuatF quat)
RotationF::RotationF (MatrixF mat)
Member Function Documentation
AngAxisF RotationF::asAxisAngle (UnitFormat format = Radians) const
EulerF RotationF::asEulerF (UnitFormat format = Radians) const
MatrixF RotationF::asMatrixF () const
Referenced by operator+(), operator+=(), operator-(), and operator-=().
QuatF RotationF::asQuatF () const
VectorF RotationF::getDirection ()
void RotationF::interpolate (const RotationF & _pt1, const RotationF & _pt2, F32 _factor)
F32 RotationF::len () const
void RotationF::lookAt (const Point3F & _origin, const Point3F & _target, const Point3F & _up = Point3F(0, 0, 1))
void RotationF::normalize ()
S32 RotationF::operator!= (const EulerF & _euler) const inline
References RotationF().
S32 RotationF::operator!= (const AngAxisF & _aa) const inline
References RotationF().
S32 RotationF::operator!= (const QuatF & _quat) const inline
References RotationF().
S32 RotationF::operator!= (const MatrixF & _mat) const inline
References RotationF().
int RotationF::operator!= (const RotationF & _rotation) const inline
References w, x, y, and z.
RotationF RotationF::operator+ (const EulerF & _euler) const inline
References Radians, and RotationF().
RotationF RotationF::operator+ (const AngAxisF & _aa) const inline
References Radians, and RotationF().
RotationF RotationF::operator+ (const QuatF & _quat) const inline
References RotationF().
RotationF RotationF::operator+ (const MatrixF & _mat) const inline
References RotationF().
RotationF RotationF::operator+ (const RotationF & _rotation) const inline
References asMatrixF(), Euler, MatrixF::mul(), set(), x, y, and z.
RotationF & RotationF::operator+= (const EulerF & _euler) inline
References Radians, and RotationF().
RotationF & RotationF::operator+= (const AngAxisF & _aa) inline
References Radians, and RotationF().
RotationF & RotationF::operator+= (const QuatF & _quat) inline
References RotationF().
RotationF & RotationF::operator+= (const MatrixF & _mat) inline
References RotationF().
RotationF & RotationF::operator+= (const RotationF & _rotation) inline
References asMatrixF(), Euler, MatrixF::mul(), x, y, and z.
RotationF RotationF::operator- (const EulerF & _euler) const inline
References Radians, and RotationF().
RotationF RotationF::operator- (const AngAxisF & _aa) const inline
References Radians, and RotationF().
RotationF RotationF::operator- (const QuatF & _quat) const inline
References RotationF().
RotationF RotationF::operator- (const MatrixF & _mat) const inline
References RotationF().
RotationF RotationF::operator- (const RotationF & _rotation) const inline
References asMatrixF(), Euler, MatrixF::inverse(), MatrixF::mul(), set(), x, y, and z.
RotationF & RotationF::operator-= (const EulerF & _euler) inline
References Radians, and RotationF().
RotationF & RotationF::operator-= (const AngAxisF & _aa) inline
References Radians, and RotationF().
RotationF & RotationF::operator-= (const QuatF & _quat) inline
References RotationF().
RotationF & RotationF::operator-= (const MatrixF & _mat) inline
References RotationF().
RotationF & RotationF::operator-= (const RotationF & _rotation) inline
References asMatrixF(), Euler, MatrixF::inverse(), MatrixF::mul(), x, y, and z.
RotationF RotationF::operator= (const EulerF & _euler) inline
References Radians, and RotationF().
RotationF RotationF::operator= (const AngAxisF & _aa) inline
References Radians, and RotationF().
RotationF RotationF::operator= (const QuatF & _quat) inline
References RotationF().
RotationF RotationF::operator= (const MatrixF & _mat) inline
References RotationF().
RotationF & RotationF::operator= (const RotationF & _rotation) inline
References mRotationType, w, x, y, and z.
S32 RotationF::operator== (const EulerF & _euler) const inline
References RotationF().
S32 RotationF::operator== (const AngAxisF & _aa) const inline
References RotationF().
S32 RotationF::operator== (const QuatF & _quat) const inline
References RotationF().
S32 RotationF::operator== (const MatrixF & _mat) const inline
References RotationF().
int RotationF::operator== (const RotationF & _rotation) const inline
References w, x, y, and z.
void RotationF::set (EulerF euler, UnitFormat format = Radians)
Referenced by operator+(), and operator-().
void RotationF::set (F32 _x, F32 _y, F32 _z, UnitFormat format = Radians)
void RotationF::set (AngAxisF aa, UnitFormat format = Radians)
void RotationF::set (QuatF _quat)
void RotationF::set (MatrixF _mat)
Member Data Documentation
RotationTypes RotationF::mRotationType
Referenced by operator=().
F32 RotationF::w
W co-ordinate.
Referenced by operator!=(), operator=(), and operator==().
F32 RotationF::x
X co-ordinate.
Referenced by operator!=(), operator+(), operator+=(), operator-(), operator-=(), operator=(), and operator==().
F32 RotationF::y
Y co-ordinate.
Referenced by operator!=(), operator+(), operator+=(), operator-(), operator-=(), operator=(), and operator==().
F32 RotationF::z
Z co-ordinate.
Referenced by operator!=(), operator+(), operator+=(), operator-(), operator-=(), operator=(), and operator==().
Copyright © GarageGames, LLC. All Rights Reserved.