MacWindow Class Reference
Main Modules Class List Namespace List Online
MacWindow Class Reference
#include <windowManager/mac/macWindow.h>
Public Member Functions
virtual ~MacWindow ()
void _associateMouse ()
void _centerMouse ()
void _disassociateCocoaWindow ()
void _dissociateMouse ()
void _doMouseLockNow ()
Does the work of actually locking or unlocking the mouse, based on the value of shouldLockMouse().
void _skipAnotherMouseEvent ()
bool _skipNextMouseEvent ()
void _skippedMouseEvent ()
virtual void centerWindow ()
virtual void clearFocus ()
virtual bool clearFullscreen ()
If we're fullscreen, this function returns us to desktop mode.
virtual Point2I clientToScreen (const Point2I &pos)
Convert the coordinate given in this window space to screen coordinates.
virtual void close ()
Destroy the window on screen.
virtual const RectI getBounds () const
Get the position and size (fullscreen windows are always at (0,0)).
virtual const char * getCaption ()
Get the window's caption.
virtual const Point2I getClientExtent ()
Get the Client Area Extent (Resolution) of this window.
CGDirectDisplayID getDisplay ()
CGRect getDisplayBounds ()
virtual GFXDevice * getGFXDevice ()
Return a pointer to the GFX device this window is bound to.
virtual GFXWindowTarget * getGFXTarget ()
Return a pointer to this window's render target.
CGRect getMainDisplayBounds ()
virtual PlatformWindow * getNextWindow () const
virtual void * getPlatformDrawable () const
Get the platform specific object needed to create or attach an accelerated graohics drawing context on or to the window Win32 D3D and OpenGL typically needs an HWND Mac Cocoa OpenGL typically needs an NSOpenGLView Mac Carbon OpenGL typically needs a WindowRef.
virtual const Point2I getPosition ()
Get the position of this window.
virtual const GFXVideoMode & getVideoMode ()
Get our current video mode - if the window has been resized, it will reflect this.
virtual WindowId getWindowId ()
Get the ID that uniquely identifies this window in the context of its window manager.
virtual void hide ()
Hide the window on screen.
virtual bool isFocused ()
Returns true if the window has input focus.
virtual bool isFullscreen ()
virtual bool isMaximized ()
Returns true if the window is maximized.
virtual bool isMinimized ()
Returns true if the window is minimized.
virtual bool isMouseLocked () const
Is the mouse locked ?
virtual bool isOpen ()
Returns true if the window is instantiated in the OS.
virtual bool isVisible ()
Returns true if the window is visible.
virtual void maximize ()
Maximize the window on screen.
virtual void minimize ()
Minimize the window on screen.
virtual void restore ()
Restore the window from a Maximized or Minimized state.
virtual Point2I screenToClient (const Point2I &pos)
Convert the given screen coordinates to coordinates in this window space.
virtual void setBounds (const RectI &newBounds)
The bounds of a Window are defined as the entire area occupied by that Window.
virtual bool setCaption (const char *windowText)
Set the window's caption.
virtual void setClientExtent (const Point2I newExtent)
The Client Rectangle or "Render Area" of a window is the area that is occupied by a given client that is rendering to that window.
void setDisplay (CGDirectDisplayID display)
virtual void setFocus ()
Set Focused State (Foreground)
virtual void setMouseLocked (bool enable)
Lock the mouse to this window.
virtual void setPosition (const Point2I newPosition)
The Position of a window is always in relation to the very upper left of the window.
virtual bool setSize (const Point2I &newSize)
Resize the window to have a new size (but be in the same position).
virtual bool setType (S32 windowType)
virtual void setVideoMode (const GFXVideoMode &mode)
Set the video mode for this window.
virtual bool shouldLockMouse () const
Should the mouse be locked at the next opportunity ?
virtual void show ()
Show the window on screen.
Public Member Functions inherited from PlatformWindow
virtual ~PlatformWindow ()
To get rid of a window, just delete it.
virtual bool getAcceleratorsEnabled () const
Returns true if native OS keyboard accelerators are enabled.
WindowInputGenerator * getInputGenerator () const
virtual Point2I getLockedSize ()
Returns the locked window size.
virtual Point2I getMinimumWindowSize ()
Returns the current minimum window size for this window.
virtual void * getSystemWindow (const WindowSystem system)
virtual bool isSizeLocked ()
Returns true if the window size is locked.
virtual void lockSize (bool locked)
Locks/unlocks window resizing.
virtual void setAcceleratorsEnabled (const bool enabled)
Used to disable native OS keyboard accelerators.
virtual void setInputController (IProcessInput *controller)
Get the WindowController associated with this window.
virtual void setMinimumWindowSize (Point2I minSize)
Sets a minimum window size.
void setSuppressReset (bool suppress)
Set the flag that determines whether to suppress a GFXDevice reset.
void setFullscreen (const bool fullscreen)
Acquire the entire screen.
virtual void setBackground (bool val)
Set Idle State (Background)
virtual bool getBackground ()
Get Idle State (Background)
virtual void setOffscreenRender (bool val)
Set whether this window is intended for offscreen rendering An offscreen window will never be shown or lose focus.
virtual bool getOffscreenRender ()
Set whether this window is intended for offscreen rendering.
virtual void setDisplayWindow (bool val)
Set whether this window is should display as normal.
virtual void setKeyboardTranslation (const bool enabled)
Set if relevant keypress events should be translated into character input events.
virtual bool getKeyboardTranslation () const
Returns true if keyboard translation is enabled.
virtual bool shouldNotTranslate (U32 modifiers, U32 keyCode) const
Returns true if the given keypress event should not be translated.
virtual PlatformCursorController * getCursorController ()
virtual void setCursorPosition (S32 x, S32 y)
Set the cursor position based on logical coordinates from the upper-right corner.
virtual void getCursorPosition (Point2I &point)
Get the cursor position based on logical coordinates from the upper-right corner.
virtual void setCursorVisible (bool visible)
Set the cursor visibility on this window.
virtual bool isCursorVisible ()
Get the cursor visibility on this window.
Static Public Member Functions
static void hideBrowserWindow (bool hide)
static void setSafariWindow (NSWindow *window, S32 x=0, S32 y=0, S32 width=0, S32 height=0)
Static Public Member Functions inherited from PlatformWindow
static ScreenResChangeSignal & getScreenResChangeSignal ()
Protected Member Functions
virtual void _setFullscreen (bool fullScreen)
Protected Member Functions inherited from PlatformWindow
PlatformWindow ()
Protected constructor so that the win.
virtual void _setVideoMode (const GFXVideoMode &mode)
Additional Inherited Members
Public Types inherited from PlatformWindow
enum WindowSystem {
WindowSystem_Unknown = 0,
WindowSystem_Windows,
WindowSystem_X11
}
Public Attributes inherited from PlatformWindow
AppEvent appEvent
MouseEvent mouseEvent
MouseWheelEvent wheelEvent
ButtonEvent buttonEvent
LinearEvent linearEvent
KeyEvent keyEvent
CharEvent charEvent
DisplayEvent displayEvent
ResizeEvent resizeEvent
IdleEvent idleEvent
Protected Attributes inherited from PlatformWindow
PlatformCursorController * mCursorController
Cursor Controller for this Window.
bool mDisplayWindow
This is set as part of the canvas being shown, and flags that the windows should render as normal from now on.
bool mEnableAccelerators
When Torque GuiText input controls have focus they need to disable native OS keyboard accelerator translation.
bool mEnableKeyboardTranslation
Are we enabling IME or other keyboard input translation services, or concerned about raw input?
bool mIsBackground
Is Idle?
Point2I mLockedSize
When the resize is locked, this will be used as both minimum and maximum window size.
Point2I mMinimumSize
Minimum allowed size for this window.
bool mOffscreenRender
Offscreen Render.
bool mResizeLocked
When this is true, resizing is locked.
bool mSuppressReset
Suppress device resets.
WindowId mWindowId
An opaque ID used to resolve references to this Window.
WindowInputGenerator * mWindowInputGenerator
Window Mouse/Key input Controller for this Window.
Static Protected Attributes inherited from PlatformWindow
static ScreenResChangeSignal smScreenResChangeSignal
Constructor & Destructor Documentation
virtual MacWindow::~MacWindow () virtual
Member Function Documentation
void MacWindow::_associateMouse ()
Referenced by _skippedMouseEvent().
void MacWindow::_centerMouse ()
Referenced by _skippedMouseEvent().
void MacWindow::_disassociateCocoaWindow ()
Referenced by _skippedMouseEvent().
void MacWindow::_dissociateMouse ()
Referenced by _skippedMouseEvent().
void MacWindow::_doMouseLockNow ()
Does the work of actually locking or unlocking the mouse, based on the value of shouldLockMouse().
Disassociates the cursor movement from the mouse input and hides the mouse when locking. Re-associates cursor movement with mouse input and shows the mouse when unlocking.
Returns true if we locked or unlocked the mouse. Returns false if the mouse was already in the correct state.
Referenced by _skippedMouseEvent(), and setMouseLocked().
virtual void MacWindow::_setFullscreen (bool fullScreen) protected virtual
Reimplemented from PlatformWindow.
Referenced by _skippedMouseEvent().
void MacWindow::_skipAnotherMouseEvent () inline
bool MacWindow::_skipNextMouseEvent () inline
void MacWindow::_skippedMouseEvent () inline
References _associateMouse(), _centerMouse(), _disassociateCocoaWindow(), _dissociateMouse(), _doMouseLockNow(), _setFullscreen(), hideBrowserWindow(), and setSafariWindow().
virtual void MacWindow::centerWindow () virtual
Reimplemented from PlatformWindow.
Referenced by shouldLockMouse().
virtual void MacWindow::clearFocus () virtual
Referenced by setType().
virtual bool MacWindow::clearFullscreen () inline virtual
If we're fullscreen, this function returns us to desktop mode.
This will be either the last mode that we had that was not fullscreen, or the equivalent mode, windowed.
Implements PlatformWindow.
virtual Point2I MacWindow::clientToScreen (const Point2I & point) virtual
Convert the coordinate given in this window space to screen coordinates.
Implements PlatformWindow.
Referenced by shouldLockMouse().
virtual void MacWindow::close () virtual
Destroy the window on screen.
Implements PlatformWindow.
Referenced by setType().
virtual const RectI MacWindow::getBounds () const virtual
Get the position and size (fullscreen windows are always at (0,0)).
Implements PlatformWindow.
Referenced by shouldLockMouse().
virtual const char* MacWindow::getCaption () inline virtual
Get the window's caption.
Implements PlatformWindow.
virtual const Point2I MacWindow::getClientExtent () virtual
Get the Client Area Extent (Resolution) of this window.
Implements PlatformWindow.
Referenced by shouldLockMouse().
CGDirectDisplayID MacWindow::getDisplay () inline
CGRect MacWindow::getDisplayBounds () inline
virtual GFXDevice* MacWindow::getGFXDevice () inline virtual
Return a pointer to the GFX device this window is bound to.
A GFX device may use many windows, but a window can only be used by a single GFX device.
Implements PlatformWindow.
virtual GFXWindowTarget* MacWindow::getGFXTarget () inline virtual
Return a pointer to this window's render target.
By setting window targets from different windows, we can effect rendering to multiple windows from a single device.
Implements PlatformWindow.
References setVideoMode().
CGRect MacWindow::getMainDisplayBounds () inline
virtual PlatformWindow* MacWindow::getNextWindow () const virtual
Implements PlatformWindow.
Referenced by isFullscreen().
virtual void* MacWindow::getPlatformDrawable () const virtual
Get the platform specific object needed to create or attach an accelerated graohics drawing context on or to the window Win32 D3D and OpenGL typically needs an HWND Mac Cocoa OpenGL typically needs an NSOpenGLView Mac Carbon OpenGL typically needs a WindowRef.
Implements PlatformWindow.
Referenced by setType().
virtual const Point2I MacWindow::getPosition () virtual
Get the position of this window.
Implements PlatformWindow.
Referenced by shouldLockMouse().
virtual const GFXVideoMode& MacWindow::getVideoMode () inline virtual
Get our current video mode - if the window has been resized, it will reflect this.
Implements PlatformWindow.
virtual WindowId MacWindow::getWindowId () inline virtual
Get the ID that uniquely identifies this window in the context of its window manager.
Reimplemented from PlatformWindow.
References PlatformWindow::mWindowId, and setDisplay().
virtual void MacWindow::hide () virtual
Hide the window on screen.
Implements PlatformWindow.
Referenced by setType().
static void MacWindow::hideBrowserWindow (bool hide) static
Referenced by _skippedMouseEvent().
virtual bool MacWindow::isFocused () virtual
Returns true if the window has input focus.
Implements PlatformWindow.
Referenced by setMouseLocked(), and setType().
virtual bool MacWindow::isFullscreen () inline virtual
Returns
true if this window is fullscreen, false otherwise.
Implements PlatformWindow.
References getNextWindow().
virtual bool MacWindow::isMaximized () virtual
Returns true if the window is maximized.
Implements PlatformWindow.
Referenced by setType().
virtual bool MacWindow::isMinimized () virtual
Returns true if the window is minimized.
Implements PlatformWindow.
Referenced by setType().
virtual bool MacWindow::isMouseLocked () const inline virtual
Is the mouse locked ?
Implements PlatformWindow.
virtual bool MacWindow::isOpen () virtual
Returns true if the window is instantiated in the OS.
Implements PlatformWindow.
Referenced by setType().
virtual bool MacWindow::isVisible () virtual
Returns true if the window is visible.
Implements PlatformWindow.
Referenced by setType().
virtual void MacWindow::maximize () virtual
Maximize the window on screen.
Implements PlatformWindow.
Referenced by setType().
virtual void MacWindow::minimize () virtual
Minimize the window on screen.
Implements PlatformWindow.
Referenced by setType().
virtual void MacWindow::restore () virtual
Restore the window from a Maximized or Minimized state.
Implements PlatformWindow.
Referenced by setType().
virtual Point2I MacWindow::screenToClient (const Point2I & point) virtual
Convert the given screen coordinates to coordinates in this window space.
Implements PlatformWindow.
Referenced by shouldLockMouse().
virtual void MacWindow::setBounds (const RectI & newBounds) virtual
The bounds of a Window are defined as the entire area occupied by that Window.
This includes the area needed for a title-bar, menu, borders, and other non-client elements.Resize the window to have some new bounds.
Implements PlatformWindow.
Referenced by shouldLockMouse().
virtual bool MacWindow::setCaption (const char * cap) virtual
Set the window's caption.
Implements PlatformWindow.
Referenced by shouldLockMouse().
virtual void MacWindow::setClientExtent (const Point2I newExtent) virtual
The Client Rectangle or "Render Area" of a window is the area that is occupied by a given client that is rendering to that window.
This does not include the area occupied by a title-bar, menu, borders or other non-client elements.Set the Client Area Extent (Resolution) of this window
Implements PlatformWindow.
Referenced by shouldLockMouse().
void MacWindow::setDisplay (CGDirectDisplayID display)
Referenced by getWindowId().
virtual void MacWindow::setFocus () virtual
Set Focused State (Foreground)
Claim OS input focus for this window
Reimplemented from PlatformWindow.
Referenced by setType().
virtual void MacWindow::setMouseLocked (bool enable) inline virtual
Lock the mouse to this window.
When this is set, the mouse will always be returned to the center of the client area after every mouse event. The mouse will also be hidden while it is locked.
The mouse cannot be moved out of the bounds of the window, but the window may lose focus (for instance by an alt-tab or other event). While the window lacks focus, no mouse events will be reported.
Implements PlatformWindow.
References _doMouseLockNow(), and isFocused().
virtual void MacWindow::setPosition (const Point2I newPosition) virtual
The Position of a window is always in relation to the very upper left of the window.
This means that saying setPosition at 0,0 will put the position of the window title-bar (if one exists) at 0,0 and the Client area will be offset from that point by the space needed for the Non-Client area.Set the position of this window
Implements PlatformWindow.
Referenced by shouldLockMouse().
static void MacWindow::setSafariWindow (NSWindow * window, S32 x = 0, S32 y = 0, S32 width = 0, S32 height = 0) static
Referenced by _skippedMouseEvent().
virtual bool MacWindow::setSize (const Point2I & newSize) virtual
Resize the window to have a new size (but be in the same position).
Implements PlatformWindow.
Referenced by shouldLockMouse().
virtual bool MacWindow::setType (S32 windowType) inline virtual
References clearFocus(), close(), getPlatformDrawable(), hide(), isFocused(), isMaximized(), isMinimized(), isOpen(), isVisible(), maximize(), minimize(), restore(), setFocus(), and show().
virtual void MacWindow::setVideoMode (const GFXVideoMode & mode) virtual
Set the video mode for this window.
Reimplemented from PlatformWindow.
Referenced by getGFXTarget().
virtual bool MacWindow::shouldLockMouse () const inline virtual
Should the mouse be locked at the next opportunity ?
This flag is set to the current state of the mouse lock on a window, to specify the preferred lock status of the mouse in a platform window.
This is important for situations where a call is made to setMouseLocked, and the window is not in a state that it can be cleanly locked. Take for example if it was called while the window is in the background, then it is not appropriate to lock the window, but rather the window should query this state at it's next opportunity and lock the mouse if requested.
Implements PlatformWindow.
References centerWindow(), clientToScreen(), getBounds(), getClientExtent(), getPosition(), screenToClient(), setBounds(), setCaption(), setClientExtent(), setPosition(), and setSize().
virtual void MacWindow::show () virtual
Show the window on screen.
Implements PlatformWindow.
Referenced by setType().
Copyright © GarageGames, LLC. All Rights Reserved.