fsTiXmlUnknown Class Reference
Main Modules Class List Namespace List Online
fsTiXmlUnknown Class Reference
#include <persistence/taml/fsTinyXml.h>
Public Member Functions
virtual TiXmlNode * Clone () const
virtual void Print (FileStream &stream, int depth) const
Member Function Documentation
virtual TiXmlNode* fsTiXmlUnknown::Clone () const inline virtual
References fsTiXmlDocument::Print(), fsTiXmlAttribute::Print(), fsTiXmlDeclaration::Print(), fsTiXmlElement::Print(), fsTiXmlComment::Print(), fsTiXmlText::Print(), and Print().
virtual void fsTiXmlUnknown::Print (FileStream & stream, int depth) const virtual
Implements fsTiXmlNode.
Referenced by Clone().
Copyright © GarageGames, LLC. All Rights Reserved.