LangFile Class Reference
Main Modules Class List Namespace List Online
LangFile Class Reference
Class for working with language files.
#include <i18n/lang.h>
Public Member Functions
LangFile (const UTF8 *langName=NULL)
virtual ~LangFile ()
bool activateLanguage (void)
U32 addString (const UTF8 *str)
void deactivateLanguage (void)
const UTF8 * getLangFile (void)
const UTF8 * getLangName (void)
S32 getNumStrings (void)
const UTF8 * getString (U32 id)
bool isLoaded (void)
bool load (const UTF8 *filename)
bool load (Stream *s)
bool save (const UTF8 *filename)
bool save (Stream *s)
void setLangFile (const UTF8 *langFile)
void setLangName (const UTF8 *newName)
void setString (U32 id, const UTF8 *str)
Protected Member Functions
void freeTable ()
Protected Attributes
UTF8 * mLangFile
UTF8 * mLangName
Vector< UTF8 * > mStringTable
Detailed Description
Class for working with language files.
Constructor & Destructor Documentation
LangFile::LangFile (const UTF8 * langName = NULL)
virtual LangFile::~LangFile () virtual
Member Function Documentation
bool LangFile::activateLanguage (void)
Referenced by getLangFile().
U32 LangFile::addString (const UTF8 * str)
void LangFile::deactivateLanguage (void)
Referenced by getLangFile().
void LangFile::freeTable () protected
const UTF8* LangFile::getLangFile (void) inline
References activateLanguage(), deactivateLanguage(), mLangFile, and setLangFile().
const UTF8* LangFile::getLangName (void) inline
References mLangName.
S32 LangFile::getNumStrings (void) inline
References Vector< T >::size().
const UTF8* LangFile::getString (U32 id)
Referenced by LangTable::getNumLang().
bool LangFile::isLoaded (void) inline
References Vector< T >::size().
bool LangFile::load (const UTF8 * filename)
bool LangFile::load (Stream * s)
bool LangFile::save (const UTF8 * filename)
bool LangFile::save (Stream * s)
void LangFile::setLangFile (const UTF8 * langFile)
Referenced by getLangFile().
void LangFile::setLangName (const UTF8 * newName)
void LangFile::setString (U32 id, const UTF8 * str)
Member Data Documentation
UTF8* LangFile::mLangFile protected
Referenced by getLangFile().
UTF8* LangFile::mLangName protected
Referenced by getLangName().
Vector<UTF8 *> LangFile::mStringTable protected
Copyright © GarageGames, LLC. All Rights Reserved.