TerrainAction Class Reference
Main Modules Class List Namespace List Online
TerrainAction Class Reference abstract
#include <gui/worldEditor/terrainActions.h>
Public Types
enum Type {
Begin = 0,
Update,
End,
Process
}
Public Member Functions
TerrainAction (TerrainEditor *editor)
virtual ~TerrainAction ()
virtual StringTableEntry getName ()=0
virtual void process (Selection *sel, const Gui3DMouseEvent &event, bool selChanged, Type type)=0
virtual bool useMouseBrush ()
Protected Attributes
TerrainEditor * mTerrainEditor
Member Enumeration Documentation
enum TerrainAction::Type
Enumerator
Begin
Update
End
Process
Constructor & Destructor Documentation
virtual TerrainAction::~TerrainAction () inline virtual
TerrainAction::TerrainAction (TerrainEditor * editor) inline
References getName().
Member Function Documentation
virtual StringTableEntry TerrainAction::getName () pure virtual
Implemented in PaintNoiseAction, SmoothSlopeAction, SmoothHeightAction, FlattenHeightAction, AdjustHeightAction, BrushAdjustHeightAction, ScaleHeightAction, ClearEmptyAction, SetEmptyAction, SetHeightAction, LowerHeightAction, RaiseHeightAction, ClearMaterialsAction, PaintMaterialAction, OutlineSelectAction, SoftSelectAction, ClearAction, DeselectAction, and SelectAction.
Referenced by TerrainAction().
virtual void TerrainAction::process (Selection * sel, const Gui3DMouseEvent & event, bool selChanged, Type type) pure virtual
Implemented in PaintNoiseAction, SmoothSlopeAction, SmoothHeightAction, FlattenHeightAction, AdjustHeightAction, BrushAdjustHeightAction, ScaleHeightAction, ClearEmptyAction, SetEmptyAction, SetHeightAction, LowerHeightAction, RaiseHeightAction, ClearMaterialsAction, PaintMaterialAction, OutlineSelectAction, SoftSelectAction, ClearAction, DeselectAction, and SelectAction.
Referenced by SelectAction::getName(), DeselectAction::getName(), SoftSelectAction::getName(), OutlineSelectAction::getName(), PaintMaterialAction::getName(), ClearMaterialsAction::getName(), RaiseHeightAction::getName(), LowerHeightAction::getName(), SetHeightAction::getName(), SetEmptyAction::getName(), ClearEmptyAction::getName(), ScaleHeightAction::getName(), BrushAdjustHeightAction::getName(), AdjustHeightAction::getName(), FlattenHeightAction::getName(), SmoothHeightAction::getName(), SmoothSlopeAction::getName(), and PaintNoiseAction::getName().
virtual bool TerrainAction::useMouseBrush () inline virtual
Reimplemented in AdjustHeightAction, OutlineSelectAction, and ClearAction.
Member Data Documentation
TerrainEditor* TerrainAction::mTerrainEditor protected
Referenced by ClearAction::useMouseBrush().
Copyright © GarageGames, LLC. All Rights Reserved.