NetInterface Class Reference
Main Modules Class List Namespace List Online
NetInterface Class Reference
NetInterface class.
#include <sim/netInterface.h>
Public Types
enum PacketTypes {
MasterServerGameTypesRequest = 2,
MasterServerGameTypesResponse = 4,
MasterServerListRequest = 6,
MasterServerListResponse = 8,
GameMasterInfoRequest = 10,
GameMasterInfoResponse = 12,
GamePingRequest = 14,
GamePingResponse = 16,
GameInfoRequest = 18,
GameInfoResponse = 20,
GameHeartbeat = 22,
GGCPacket = 24,
ConnectChallengeRequest = 26,
ConnectChallengeReject = 28,
ConnectChallengeResponse = 30,
ConnectRequest = 32,
ConnectReject = 34,
ConnectAccept = 36,
Disconnect = 38,
MasterServerExtendedListResponse = 40,
MasterServerChallenge = 42,
MasterServerExtendedListRequest = 44
}
PacketType is encoded as the first byte of each packet.
Public Member Functions
NetInterface ()
void checkTimeouts ()
Checks for timeouts on all valid and pending connections.
bool doesAllowConnections ()
Returns whether or not this NetInterface allows connections from remote hosts.
virtual void handleInfoPacket (const NetAddress *address, U8 packetType, BitStream *stream)
Handles all packets that don't fall into the category of connection handshake or game data.
void processClient ()
Checks all connections marked as client to server for packet sends.
virtual void processPacketReceiveEvent (NetAddress srcAddress, RawData packetData)
Dispatch function for processing all network packets through this NetInterface.
void processServer ()
Checks all connections marked as server to client for packet sends.
void sendDisconnectPacket (NetConnection *conn, const char *reason)
Send a disconnect packet on a connection, along with a reason.
void setAllowsConnections (bool conn)
Sets whether or not this NetInterface allows connections from remote hosts.
void startConnection (NetConnection *conn)
Begins the connection handshaking process for a connection.
Protected Types
enum NetInterfaceConstants {
MaxPendingConnects = 20,
ChallengeRetryCount = 4,
ChallengeRetryTime = 2500,
ConnectRetryCount = 4,
ConnectRetryTime = 2500,
TimeoutCheckInterval = 1500
}
Protected Member Functions
void computeNetMD5 (const NetAddress *address, U32 connectSequence, U32 addressDigest[4])
Calculate an MD5 sum representing a connection, and store it into addressDigest.
void initRandomData ()
Initialize random data.
Connection management
Most of these are pretty self-explanatory.
void addPendingConnection (NetConnection *conn)
NetConnection * findPendingConnection (const NetAddress *address, U32 packetSequence)
void removePendingConnection (NetConnection *conn)
void sendConnectChallengeRequest (NetConnection *conn)
void handleConnectChallengeRequest (const NetAddress *addr, BitStream *stream)
void handleConnectChallengeResponse (const NetAddress *address, BitStream *stream)
void sendConnectRequest (NetConnection *conn)
void handleConnectRequest (const NetAddress *address, BitStream *stream)
void sendConnectAccept (NetConnection *conn)
void handleConnectAccept (const NetAddress *address, BitStream *stream)
void sendConnectReject (NetConnection *conn, const char *reason)
void handleConnectReject (const NetAddress *address, BitStream *stream)
void handleDisconnect (const NetAddress *address, BitStream *stream)
Protected Attributes
bool mAllowConnections
Is this NetInterface allowing connections at this time?
U32 mLastTimeoutCheckTime
Last time all the active connections were checked for timeouts.
Vector< NetConnection * > mPendingConnections
List of connections that are in the startup phase.
bool mRandomDataInitialized
Have we initialized our random number generator?
U32 mRandomHashData [12]
Data that gets hashed with connect challenge requests to prevent connection spoofing.
Detailed Description
NetInterface class.
Manages all valid and pending notify protocol connections.
See also
NetConnection, GameConnection, NetObject, NetEvent
Member Enumeration Documentation
enum NetInterface::NetInterfaceConstants protected
Enumerator
MaxPendingConnects
Maximum number of pending connections. If new connection requests come in before.
ChallengeRetryCount
Number of times to send connect challenge requests before giving up.
ChallengeRetryTime
Timeout interval in milliseconds before retrying connect challenge.
ConnectRetryCount
Number of times to send connect requests before giving up.
ConnectRetryTime
Timeout interval in milliseconds before retrying connect request.
TimeoutCheckInterval
Interval in milliseconds between checking for connection timeouts.
enum NetInterface::PacketTypes
PacketType is encoded as the first byte of each packet.
If the LSB of the first byte is set (i.e. if the type number is odd), then the packet is a data protocol packet, otherwise it's an OOB packet, suitable for use in strange protocols, like game querying or connection initialization.
Enumerator
MasterServerGameTypesRequest
MasterServerGameTypesResponse
MasterServerListRequest
MasterServerListResponse
GameMasterInfoRequest
GameMasterInfoResponse
GamePingRequest
GamePingResponse
GameInfoRequest
GameInfoResponse
GameHeartbeat
GGCPacket
ConnectChallengeRequest
ConnectChallengeReject
ConnectChallengeResponse
ConnectRequest
ConnectReject
ConnectAccept
Disconnect
MasterServerExtendedListResponse
MasterServerChallenge
MasterServerExtendedListRequest
Constructor & Destructor Documentation
NetInterface::NetInterface ()
Member Function Documentation
void NetInterface::addPendingConnection (NetConnection * conn) protected
void NetInterface::checkTimeouts ()
Checks for timeouts on all valid and pending connections.
Referenced by setAllowsConnections().
void NetInterface::computeNetMD5 (const NetAddress * address, U32 connectSequence, U32 addressDigest[4]) protected
Calculate an MD5 sum representing a connection, and store it into addressDigest.
bool NetInterface::doesAllowConnections () inline
Returns whether or not this NetInterface allows connections from remote hosts.
References mAllowConnections.
NetConnection* NetInterface::findPendingConnection (const NetAddress * address, U32 packetSequence) protected
void NetInterface::handleConnectAccept (const NetAddress * address, BitStream * stream) protected
void NetInterface::handleConnectChallengeRequest (const NetAddress * addr, BitStream * stream) protected
void NetInterface::handleConnectChallengeResponse (const NetAddress * address, BitStream * stream) protected
void NetInterface::handleConnectReject (const NetAddress * address, BitStream * stream) protected
void NetInterface::handleConnectRequest (const NetAddress * address, BitStream * stream) protected
void NetInterface::handleDisconnect (const NetAddress * address, BitStream * stream) protected
virtual void NetInterface::handleInfoPacket (const NetAddress * address, U8 packetType, BitStream * stream) virtual
Handles all packets that don't fall into the category of connection handshake or game data.
Referenced by setAllowsConnections().
void NetInterface::initRandomData () protected
Initialize random data.
void NetInterface::processClient ()
Checks all connections marked as client to server for packet sends.
Referenced by setAllowsConnections().
virtual void NetInterface::processPacketReceiveEvent (NetAddress srcAddress, RawData packetData) virtual
Dispatch function for processing all network packets through this NetInterface.
Referenced by setAllowsConnections().
void NetInterface::processServer ()
Checks all connections marked as server to client for packet sends.
Referenced by setAllowsConnections().
void NetInterface::removePendingConnection (NetConnection * conn) protected
void NetInterface::sendConnectAccept (NetConnection * conn) protected
void NetInterface::sendConnectChallengeRequest (NetConnection * conn) protected
void NetInterface::sendConnectReject (NetConnection * conn, const char * reason) protected
void NetInterface::sendConnectRequest (NetConnection * conn) protected
void NetInterface::sendDisconnectPacket (NetConnection * conn, const char * reason)
Send a disconnect packet on a connection, along with a reason.
Referenced by setAllowsConnections().
void NetInterface::setAllowsConnections (bool conn) inline
Sets whether or not this NetInterface allows connections from remote hosts.
References checkTimeouts(), handleInfoPacket(), processClient(), processPacketReceiveEvent(), processServer(), sendDisconnectPacket(), and startConnection().
void NetInterface::startConnection (NetConnection * conn)
Begins the connection handshaking process for a connection.
Referenced by setAllowsConnections().
Member Data Documentation
bool NetInterface::mAllowConnections protected
Is this NetInterface allowing connections at this time?
Referenced by doesAllowConnections().
U32 NetInterface::mLastTimeoutCheckTime protected
Last time all the active connections were checked for timeouts.
Vector<NetConnection *> NetInterface::mPendingConnections protected
List of connections that are in the startup phase.
bool NetInterface::mRandomDataInitialized protected
Have we initialized our random number generator?
U32 NetInterface::mRandomHashData[12] protected
Data that gets hashed with connect challenge requests to prevent connection spoofing.
Copyright © GarageGames, LLC. All Rights Reserved.