sgSceneLightingProcessEvent Class Reference
Main Modules Class List Namespace List Online
sgSceneLightingProcessEvent Class Reference
#include <lighting/common/sceneLighting.h>
Public Types
enum sgEventTypes {
sgLightingStartEventType,
sgLightingCompleteEventType,
sgSGPassSetupEventType,
sgSGObjectStartEventType,
sgSGObjectCompleteEventType,
sgSGObjectProcessEventType,
sgTGEPassSetupEventType,
sgTGELightStartEventType,
sgTGELightCompleteEventType,
sgTGELightProcessEventType
}
Public Member Functions
sgSceneLightingProcessEvent (U32 lightIndex, S32 objectIndex, U32 event)
void process (SimObject *object)
A dummy virtual destructor is required so that subclasses can be deleted properly.
Public Member Functions inherited from SimEvent
SimEvent ()
virtual ~SimEvent ()
Destructor.
Additional Inherited Members
Public Attributes inherited from SimEvent
SimObject * destObject
of addition to the list.
SimEvent * nextEvent
Linked list details - pointer to next item in the list.
U32 sequenceCount
Unique ID.
SimTime startTime
When the event was posted.
SimTime time
When the event is scheduled to occur.
Member Enumeration Documentation
enum sgSceneLightingProcessEvent::sgEventTypes
Enumerator
sgLightingStartEventType
sgLightingCompleteEventType
sgSGPassSetupEventType
sgSGObjectStartEventType
sgSGObjectCompleteEventType
sgSGObjectProcessEventType
sgTGEPassSetupEventType
sgTGELightStartEventType
sgTGELightCompleteEventType
sgTGELightProcessEventType
Constructor & Destructor Documentation
sgSceneLightingProcessEvent::sgSceneLightingProcessEvent (U32 lightIndex, S32 objectIndex, U32 event) inline
Member Function Documentation
void sgSceneLightingProcessEvent::process (SimObject * object) inline virtual
A dummy virtual destructor is required so that subclasses can be deleted properly.
Function called when event occurs.
This is where the meat of your event's implementation goes.
See any of the subclasses for ideas of what goes in here.
The event is deleted immediately after processing. If the object referenced in destObject is deleted, then the event is not called. The even will be executed unconditionally if the object referenced is NULL.
Parameters
object Object stored in destObject.
Implements SimEvent.
References SimObject::object, SceneLighting::sgLightingCompleteEvent(), SceneLighting::sgLightingStartEvent(), SceneLighting::sgSGObjectCompleteEvent(), SceneLighting::sgSGObjectProcessEvent(), SceneLighting::sgSGObjectStartEvent(), SceneLighting::sgSGPassSetupEvent(), SceneLighting::sgTGELightCompleteEvent(), SceneLighting::sgTGELightProcessEvent(), SceneLighting::sgTGELightStartEvent(), and SceneLighting::sgTGEPassSetupEvent().
Copyright © GarageGames, LLC. All Rights Reserved.