LightInfo Class Reference
Main Modules Class List Namespace List Online
LightInfo Class Reference
This is the base light information class that will be tracked by the engine.
#include <lighting/lightInfo.h>
Public Types
enum Type {
Point = 0,
Spot = 1,
Vector = 2,
Ambient = 3,
Count = 4
}
Public Member Functions
LightInfo ()
~LightInfo ()
void addExtended (LightInfoEx *lightInfoEx)
Adds the extended info to the light deleting the existing extended info if it has one.
void deleteAllLightInfoEx ()
void deleteExtended (const LightInfoExType &type)
Delete all registered LightInfoEx instances of the given type.
void enableDebugRendering (bool value)
const ColorF & getAmbient () const
F32 getBrightness () const
bool getCastShadows () const
const ColorF & getColor () const
VectorF getDirection () const
S32 getDynamicRefreshFreq () const
template<class ExClass >
ExClass * getExtended () const
Helper function for getting the extended light info.
LightInfoEx * getExtended (const LightInfoExType &type) const
Returns the extended light info for the selected type.
F32 getInnerConeAngle () const
F32 getOuterConeAngle () const
Point3F getPosition () const
F32 getPriority () const
const Point3F & getRange () const
F32 getScore () const
S32 getStaticRefreshFreq () const
const MatrixF & getTransform () const
Type getType () const
void getWorldToLightProj (MatrixF *outMatrix) const
bool isDebugRenderingEnabled () const
void packExtended (BitStream *stream) const
void set (const LightInfo *light)
void setAmbient (const ColorF &val)
void setBrightness (F32 val)
void setCastShadows (bool castShadows)
void setColor (const ColorF &val)
void setDirection (const VectorF &val)
void setDynamicRefreshFreq (S32 _dynamicRefreshFreq)
void setGFXLight (GFXLightInfo *light)
void setInnerConeAngle (F32 val)
void setOuterConeAngle (F32 val)
void setPosition (const Point3F &pos)
void setPriority (F32 priority)
void setRange (const Point3F &range)
void setRange (F32 range)
void setScore (F32 score)
void setStaticRefreshFreq (S32 _staticRefreshFreq)
void setTransform (const MatrixF &xfm)
void setType (Type val)
void unpackExtended (BitStream *stream)
Protected Attributes
ColorF mAmbient
F32 mBrightness
bool mCastShadows
ColorF mColor
The primary light color.
bool mDebugRender
Whether to render debugging visualizations for this light.
S32 mDynamicRefreshFreq
::Vector< LightInfoEx * > mExtended
F32 mInnerConeAngle
F32 mOuterConeAngle
F32 mPriority
The priority of this light used for light and shadow scoring.
Point3F mRange
F32 mScore
A temporary which holds the score used when prioritizing lights for rendering.
S32 mStaticRefreshFreq
MatrixF mTransform
Type mType
Detailed Description
This is the base light information class that will be tracked by the engine.
Should basically contain a bounding volume and methods to interact with the rest of the system (for example, setting GFX fixed function lights).
Member Enumeration Documentation
enum LightInfo::Type
Enumerator
Point
Spot
Vector
Ambient
Count
Constructor & Destructor Documentation
LightInfo::LightInfo ()
LightInfo::~LightInfo ()
Member Function Documentation
void LightInfo::addExtended (LightInfoEx * lightInfoEx)
Adds the extended info to the light deleting the existing extended info if it has one.
void LightInfo::deleteAllLightInfoEx ()
void LightInfo::deleteExtended (const LightInfoExType & type)
Delete all registered LightInfoEx instances of the given type.
void LightInfo::enableDebugRendering (bool value) inline
const ColorF& LightInfo::getAmbient () const inline
F32 LightInfo::getBrightness () const inline
bool LightInfo::getCastShadows () const inline
const ColorF& LightInfo::getColor () const inline
VectorF LightInfo::getDirection () const inline
References MatrixF::getForwardVector().
S32 LightInfo::getDynamicRefreshFreq () const inline
template<class ExClass > ExClass* LightInfo::getExtended () const inline
Helper function for getting the extended light info.
See also
getExtended
References getExtended().
Referenced by getExtended().
LightInfoEx* LightInfo::getExtended (const LightInfoExType & type) const
Returns the extended light info for the selected type.
F32 LightInfo::getInnerConeAngle () const inline
F32 LightInfo::getOuterConeAngle () const inline
Point3F LightInfo::getPosition () const inline
References MatrixF::getPosition().
F32 LightInfo::getPriority () const inline
const Point3F& LightInfo::getRange () const inline
F32 LightInfo::getScore () const inline
S32 LightInfo::getStaticRefreshFreq () const inline
const MatrixF& LightInfo::getTransform () const inline
Type LightInfo::getType () const inline
void LightInfo::getWorldToLightProj (MatrixF * outMatrix) const
bool LightInfo::isDebugRenderingEnabled () const inline
void LightInfo::packExtended (BitStream * stream) const
void LightInfo::set (const LightInfo * light)
void LightInfo::setAmbient (const ColorF & val) inline
void LightInfo::setBrightness (F32 val) inline
void LightInfo::setCastShadows (bool castShadows) inline
void LightInfo::setColor (const ColorF & val) inline
void LightInfo::setDirection (const VectorF & val)
void LightInfo::setDynamicRefreshFreq (S32 _dynamicRefreshFreq) inline
void LightInfo::setGFXLight (GFXLightInfo * light)
void LightInfo::setInnerConeAngle (F32 val) inline
void LightInfo::setOuterConeAngle (F32 val) inline
void LightInfo::setPosition (const Point3F & pos) inline
References MatrixF::setPosition().
void LightInfo::setPriority (F32 priority) inline
void LightInfo::setRange (const Point3F & range) inline
void LightInfo::setRange (F32 range) inline
References Point3F::set().
void LightInfo::setScore (F32 score) inline
void LightInfo::setStaticRefreshFreq (S32 _staticRefreshFreq) inline
void LightInfo::setTransform (const MatrixF & xfm) inline
void LightInfo::setType (Type val) inline
void LightInfo::unpackExtended (BitStream * stream)
Member Data Documentation
ColorF LightInfo::mAmbient protected
F32 LightInfo::mBrightness protected
bool LightInfo::mCastShadows protected
ColorF LightInfo::mColor protected
The primary light color.
bool LightInfo::mDebugRender protected
Whether to render debugging visualizations for this light.
S32 LightInfo::mDynamicRefreshFreq protected
::Vector<LightInfoEx*> LightInfo::mExtended protected
F32 LightInfo::mInnerConeAngle protected
F32 LightInfo::mOuterConeAngle protected
F32 LightInfo::mPriority protected
The priority of this light used for light and shadow scoring.
Point3F LightInfo::mRange protected
F32 LightInfo::mScore protected
A temporary which holds the score used when prioritizing lights for rendering.
S32 LightInfo::mStaticRefreshFreq protected
MatrixF LightInfo::mTransform protected
Type LightInfo::mType protected
Copyright © GarageGames, LLC. All Rights Reserved.