NamedFactory< Type > Class Template Reference
Main Modules Class List Namespace List Online
NamedFactory< Type > Class Template Reference
A helper template class for registering creation methods to name strings.
#include <core/util/tNamedFactory.h>
Static Public Member Functions
static void add (const char *name, FactorySig func)
Add a new creation method to the factory.
static Type * create (const char *name)
Create an object instance by name.
static Type * create ()
Create an object instance of the first entry in the factory.
Protected Types
typedef Map< String, FactorySig > FactoryMap
typedef Type *(* FactorySig) ()
Static Protected Member Functions
static FactoryMap & getFactoryMap ()
Detailed Description
template<typename Type>
class NamedFactory< Type >
A helper template class for registering creation methods to name strings.
Member Typedef Documentation
template<typename Type > typedef Map<String,FactorySig> NamedFactory< Type >::FactoryMap protected
template<typename Type > typedef Type*(* NamedFactory< Type >::FactorySig) () protected
Member Function Documentation
template<typename Type > static void NamedFactory< Type >::add (const char * name, FactorySig func) inline static
Add a new creation method to the factory.
References NamedFactory< Type >::getFactoryMap(), and Map< Key, Value, Sequence >::insert().
template<typename Type > static Type* NamedFactory< Type >::create (const char * name) inline static
Create an object instance by name.
References Map< Key, Value, Sequence >::find(), and NamedFactory< Type >::getFactoryMap().
template<typename Type > static Type* NamedFactory< Type >::create (void) inline static
Create an object instance of the first entry in the factory.
References Map< Key, Value, Sequence >::begin(), and NamedFactory< Type >::getFactoryMap().
template<typename Type > static FactoryMap& NamedFactory< Type >::getFactoryMap () inline static protected
Referenced by NamedFactory< Type >::add(), and NamedFactory< Type >::create().
Copyright © GarageGames, LLC. All Rights Reserved.