AIPlayer Class Reference
Main Modules Class List Namespace List Online
AIPlayer Class Reference
#include <T3D/aiPlayer.h>
Public Types
enum MoveState {
ModeStop,
ModeMove,
ModeStuck,
ModeSlowing
}
Public Types inherited from Player
enum Pose {
StandPose = 0,
SprintPose,
CrouchPose,
PronePose,
SwimPose,
NumPoseBits = 3
}
Public Types inherited from ShapeBase
enum DamageState {
Enabled,
Disabled,
Destroyed,
NumDamageStates,
NumDamageStateBits = 2
}
This enum indexes into the sDamageStateName array.
typedef GameBase Parent
enum PublicConstants {
ThreadSequenceBits = 6,
MaxSequenceIndex = (1 << ThreadSequenceBits) - 1,
EnergyLevelBits = 5,
DamageLevelBits = 6,
DamageStateBits = 2,
MaxSoundThreads = 4,
MaxScriptThreads = 4,
MaxMountedImages = 4,
MaxImageEmitters = 3,
NumImageBits = 3,
CollisionTimeoutValue = 250
}
enum ShapeBaseMasks {
NameMask = Parent::NextFreeMask,
DamageMask = Parent::NextFreeMask << 1,
NoWarpMask = Parent::NextFreeMask << 2,
CloakMask = Parent::NextFreeMask << 3,
SkinMask = Parent::NextFreeMask << 4,
MeshHiddenMask = Parent::NextFreeMask << 5,
SoundMaskN = Parent::NextFreeMask << 6,
ThreadMaskN = SoundMaskN << MaxSoundThreads,
ImageMaskN = ThreadMaskN << MaxScriptThreads,
NextFreeMask = ImageMaskN << MaxMountedImages
}
enum BaseMaskConstants {
SoundMask = (SoundMaskN << MaxSoundThreads) - SoundMaskN,
ThreadMask = (ThreadMaskN << MaxScriptThreads) - ThreadMaskN,
ImageMask = (ImageMaskN << MaxMountedImages) - ImageMaskN
}
Public Types inherited from GameBase
enum {
NetOrdered = BIT(Parent::MaxNetFlagBit+1),
NetNearbyAdded = BIT(Parent::MaxNetFlagBit+2),
GhostUpdated = BIT(Parent::MaxNetFlagBit+3),
TickLast = BIT(Parent::MaxNetFlagBit+4),
NewGhost = BIT(Parent::MaxNetFlagBit+5),
HiFiPassive = BIT(Parent::MaxNetFlagBit+6),
MaxNetFlagBit = Parent::MaxNetFlagBit+6
}
enum GameBaseMasks {
DataBlockMask = Parent::NextFreeMask << 0,
ExtendedInfoMask = Parent::NextFreeMask << 1,
NextFreeMask = Parent::NextFreeMask << 2
}
Public Types inherited from SceneObject
enum {
MaxObjectZones = 128,
NumMountPoints = 32,
NumMountPointBits = 5
}
typedef NetObject Parent
enum SceneObjectFlags {
RenderEnabledFlag = BIT(0),
SelectionEnabledFlag = BIT(1),
DisableCullingInEditorFlag = BIT(2),
VisualOccluderFlag = BIT(3),
SoundOccluderFlag = BIT(4),
NextFreeFlag = BIT(5)
}
Bit-flags stored in mObjectFlags.
enum SceneObjectMasks {
InitialUpdateMask = BIT(0),
ScaleMask = BIT(1),
FlagMask = BIT(2),
MountedMask = BIT(3),
NextFreeMask = BIT(4)
}
Networking dirty mask.
Public Types inherited from SimGroup
typedef SimSet Parent
Public Types inherited from SimSet
typedef SimObject Parent
enum SetModification {
SetCleared,
SetObjectAdded,
SetObjectRemoved
}
typedef Signal< void(SetModification modification, SimSet *set, SimObject *object) > SetModificationSignal
Signal for letting observers know when objects are added to or removed from the set.
typedef SimObjectList::iterator iterator
typedef SimObjectList::value_type value
Public Types inherited from SimObject
typedef ConsoleObject Parent
enum WriteFlags {
SelectedOnly = BIT(0),
NoName = BIT(1),
IgnoreCanSave = BIT(2)
}
Flags passed to SimObject::write.
Public Types inherited from EngineObject
typedef void(* DebugEnumInstancesCallback) (EngineObject *)
Type of callback function for iterating over EngineObject instances.
Public Member Functions
AIPlayer ()
~AIPlayer ()
bool checkInFoV (GameBase *target=NULL, F32 camFov=45.0f, bool _checkEnabled=false)
bool checkInLos (GameBase *target=NULL, bool _useMuzzle=false, bool _checkEnabled=false)
void clearAim ()
void clearCover ()
Stop searching for cover.
void clearFollow ()
Stop following me!
void clearMoveTriggers ()
void clearPath ()
Clear out the current path.
DECLARE_CONOBJECT (AIPlayer)
Point3F getAimLocation () const
GameBase * getAimObject () const
virtual bool getAIMove (Move *move)
S32 getAiPose ()
Point3F getMoveDestination () const
F32 getMoveSpeed () const
F32 getMoveTolerance () const
bool getMoveTrigger (U32 slot) const
void getMuzzleVector (U32 imageSlot, VectorF *vec)
Gets the muzzle vector of a specified slot.
F32 getTargetDistance (GameBase *target, bool _checkEnabled)
bool onAdd ()
Called when the object is added to the sim.
void onRemove ()
Called when the object is removed from the sim.
void setAimLocation (const Point3F &location)
void setAimObject (GameBase *targetObject)
void setAimObject (GameBase *targetObject, const Point3F &offset)
void setAiPose (S32 pose)
void setMoveDestination (const Point3F &location, bool slowdown)
void setMoveSpeed (const F32 speed)
void setMoveTolerance (const F32 tolerance)
void setMoveTrigger (U32 slot, const bool isSet=true)
void stopMove ()
virtual void updateMove (const Move *move)
Update the movement.
Public Member Functions inherited from Player
Player ()
~Player ()
void advanceTime (F32 dt)
Advances simulation time for animations.
void allowAllPoses ()
void allowCrouching (bool state)
void allowJetJumping (bool state)
void allowJumping (bool state)
void allowProne (bool state)
void allowSprinting (bool state)
void allowSwimming (bool state)
void applyImpulse (const Point3F &pos, const VectorF &vec)
Apply an impulse at the given point, with magnitude/direction of vec.
void buildConvex (const Box3F &box, Convex *convex)
Builds a convex hull for this object.
bool buildPolyList (PolyListContext context, AbstractPolyList *polyList, const Box3F &box, const SphereF &sphere)
Builds a list of polygons which intersect a bounding volume.
bool canCrouch ()
bool canJetJump ()
Can the player jet?
bool canJump ()
Can the player jump?
bool canProne ()
bool canSprint ()
bool canStand ()
bool canSwim ()
Can the player swim?
bool castRay (const Point3F &start, const Point3F &end, RayInfo *info)
Casts a ray and obtain collision information, returns true if RayInfo is modified.
bool checkDismountPosition (const MatrixF &oldPos, const MatrixF &newPos)
Is it safe to dismount here?
DECLARE_CONOBJECT (Player)
virtual bool displaceObject (const Point3F &displaceVector)
Displaces this object by a vector.
const String & getArmThread () const
ShapeBase * getControlObject ()
Returns the object this is controlling.
void getDamageLocation (const Point3F &in_rPos, const char *&out_rpVert, const char *&out_rpQuad)
const Point3F & getHeadRotation ()
Get the rotation of the head of the player.
F32 getMaxForwardVelocity () const
virtual Point3F getMomentum () const
Returns the momentum of this object.
void getMuzzlePointAI (U32 imageSlot, Point3F *point)
PhysicsPlayer * getPhysicsRep () const
Pose getPose () const
Standing / Crouched / Prone or Swimming.
virtual const char * getPoseName () const
const Point3F & getRotation ()
Get the rotation of the player.
F32 getSpeed () const
const char * getStateName ()
Point3F getVelocity () const
Gets the velocity of the object.
bool haveContact () const
Is it in contact with something.
void interpolateTick (F32 delta)
Interpolates between tick events.
bool isControlObject ()
virtual bool isDisplacable () const
Returns true if this object allows itself to be displaced.
bool onAdd ()
Called when the object is added to the sim.
void onCameraScopeQuery (NetConnection *cr, CameraScopeQuery *)
Queries the object about information used to determine scope.
bool onNewDataBlock (GameBaseData *dptr, bool reload)
Called when a new datablock is set.
void onRemove ()
Called when the object is removed from the sim.
void onScaleChanged ()
Called when the size of the object changes.
U32 packUpdate (NetConnection *conn, U32 mask, BitStream *stream)
Instructs this object to pack its state for transfer over the network.
virtual void prepRenderImage (SceneRenderState *state)
virtual void processTick (const Move *move)
Processes a move event and updates object state once every 32 milliseconds.
void readPacketData (GameConnection *conn, BitStream *stream)
Read data written with writePacketData() and update the object state.
virtual void renderConvex (ObjectRenderInst *ri, SceneRenderState *state, BaseMatInstance *overrideMat)
virtual void renderMountedImage (U32 imageSlot, TSRenderState &rstate, SceneRenderState *state)
Virtualize this so other classes may override it for custom reasons.
bool setActionThread (const char *sequence, bool hold, bool wait, bool fsp=false)
bool setArmThread (const char *sequence)
void setControlObject (ShapeBase *obj)
sets the object this is controlling
virtual void setMomentum (const Point3F &momentum)
Sets the momentum of this object.
void setPose (Pose pose)
Setting this from script directly might not actually work, This is really just a helper for the player class so that its bounding box will get resized appropriately when the pose changes.
void setVelocity (const VectorF &vel)
Sets the velocity of this object.
void unpackUpdate (NetConnection *conn, BitStream *stream)
Instructs this object to read state data previously packed with packUpdate.
void updateWorkingCollisionSet ()
void writePacketData (GameConnection *conn, BitStream *stream)
Write state information necessary to perform client side prediction of an object.
void setTransform (const MatrixF &mat)
Sets the Object -> World transform.
void getEyeTransform (MatrixF *mat)
Returns the eye transform of this shape, IE the eyes of a player.
void getEyeBaseTransform (MatrixF *mat, bool includeBank)
Returns the eye transform of this shape without including mounted images, IE the eyes of a player.
void getRenderEyeTransform (MatrixF *mat)
void getRenderEyeBaseTransform (MatrixF *mat, bool includeBank)
void getCameraParameters (F32 *min, F32 *max, Point3F *offset, MatrixF *rot)
Gets the minimum viewing distance, maximum viewing distance, camera offsetand rotation for this object, if the world were to be viewed through its eyes.
void getMuzzleTransform (U32 imageSlot, MatrixF *mat)
Muzzle transform of mounted object in world space.
void getRenderMuzzleTransform (U32 imageSlot, MatrixF *mat)
Public Member Functions inherited from ShapeBase
ShapeBase ()
~ShapeBase ()
void advanceTime (F32 dt)
Advances simulation time for animations.
void buildConvex (const Box3F &box, Convex *convex)
Builds a convex hull for this object.
bool buildPolyList (PolyListContext context, AbstractPolyList *polyList, const Box3F &box, const SphereF &sphere)
Builds a list of polygons which intersect a bounding volume.
bool castRay (const Point3F &start, const Point3F &end, RayInfo *info)
Casts a ray and obtain collision information, returns true if RayInfo is modified.
bool castRayRendered (const Point3F &start, const Point3F &end, RayInfo *info)
Casts a ray against rendered geometry, returns true if RayInfo is modified.
DECLARE_CONOBJECT (ShapeBase)
Point3F getAIRepairPoint ()
Returns where the AI should be to repair this object.
virtual WaterObject * getCurrentWaterObject ()
Returns the water object we are colliding with, it is up to derived classes to actually set this object.
F32 getLiquidHeight ()
Returns the height of the liquid on this object.
virtual F32 getMass () const
Returns the mass of this object.
TSShapeInstance * getShapeInstance ()
F32 getWaterCoverage ()
Returns the percentage of this object covered by water.
void onCameraScopeQuery (NetConnection *cr, CameraScopeQuery *camInfo)
Control object scoping.
bool pointInWater (Point3F &point)
Returns true if the point specified is in the water.
void processTick (const Move *move)
Processes a move event and updates object state once every 32 milliseconds.
void setCurrentWaterObject (WaterObject *obj)
virtual bool mountImage (ShapeBaseImageData *image, U32 imageSlot, bool loaded, NetStringHandle &skinNameHandle)
Mount an image (ShapeBaseImage) onto an image slot.
virtual bool unmountImage (U32 imageSlot)
Unmount an image from a slot.
ShapeBaseImageData * getMountedImage (U32 imageSlot)
Gets the information on the image mounted in a slot.
MountedImage * getImageStruct (U32 imageSlot)
Gets the mounted image on on a slot.
TSShapeInstance * getImageShapeInstance (U32 imageSlot)
ShapeBaseImageData * getPendingImage (U32 imageSlot)
Gets the next image which will be put in an image slot.
bool isImageFiring (U32 imageSlot)
Returns true if the mounted image is firing.
bool isImageAltFiring (U32 imageSlot)
Returns true if the mounted image is alternate firing.
bool isImageReloading (U32 imageSlot)
Returns true if the mounted image is reloading.
bool isImageReady (U32 imageSlot, U32 ns=(U32)-1, U32 depth=0)
This will return true if, when triggered, the object will fire.
bool isImageMounted (ShapeBaseImageData *image)
Returns true if the specified image is mounted.
S32 getMountSlot (ShapeBaseImageData *image)
Returns the slot which the image specified is mounted on.
NetStringHandle getImageSkinTag (U32 imageSlot)
Returns the skin for the image in a slot.
bool hasImageState (U32 imageSlot, const char *state)
Check if the given state exists on the mounted Image.
const char * getImageState (U32 imageSlot)
Returns the image state as a string.
void setImageGenericTriggerState (U32 imageSlot, U32 trigger, bool state)
Sets the generic trigger state of the image.
bool getImageGenericTriggerState (U32 imageSlot, U32 trigger)
Returns the generic trigger state of the image.
void setImageTriggerState (U32 imageSlot, bool trigger)
Sets the trigger state of the image (Ie trigger pulled down on gun)
bool getImageTriggerState (U32 imageSlot)
Returns the trigger state of the image.
void setImageAltTriggerState (U32 imageSlot, bool trigger)
Sets the alt trigger state of the image (Ie trigger pulled down on gun)
bool getImageAltTriggerState (U32 imageSlot)
Returns the alt trigger state of the image.
void setImageAmmoState (U32 imageSlot, bool ammo)
Sets the flag if the image uses ammo or energy.
bool getImageAmmoState (U32 imageSlot)
Returns true if the image uses ammo, not energy.
void setImageWetState (U32 imageSlot, bool wet)
Sets the image as wet or not, IE if you wanted a gun not to function underwater.
bool getImageWetState (U32 imageSlot)
Returns true if image is wet.
void setImageMotionState (U32 imageSlot, bool motion)
Sets the image as in motion or not, IE if you wanted a gun not to sway while the player is in motion.
bool getImageMotionState (U32 imageSlot)
Returns true if image is in motion.
void setImageTargetState (U32 imageSlot, bool ammo)
Sets the flag if the image has a target.
bool getImageTargetState (U32 imageSlot)
Returns true if the image has a target.
void setImageLoadedState (U32 imageSlot, bool loaded)
Sets the flag of if the image is loaded with ammo.
bool getImageLoadedState (U32 imageSlot)
Returns true if object is loaded with ammo.
void setImageScriptAnimPrefix (U32 imageSlot, NetStringHandle prefix)
Set the script animation prefix for the image.
NetStringHandle getImageScriptAnimPrefix (U32 imageSlot)
Get the script animation prefix for the image.
bool getCorrectedAim (const MatrixF &muzMat, VectorF *result)
Modify muzzle, if needed, to aim at whatever is straight in front of eye.
void getMuzzlePoint (U32 imageSlot, Point3F *pos)
Gets the point of the muzzle of the image.
void forceUncloak (const char *reason)
Force uncloaking of object.
void setCloakedState (bool cloaked)
Set cloaked state of object.
bool getCloakedState ()
Returns true if object is cloaked.
F32 getCloakLevel ()
Returns level of cloaking, as it's not an instant "now you see it, now you don't".
F32 getFadeVal ()
void setAllMeshesHidden (bool forceHidden)
Change the hidden state on all the meshes.
void setMeshHidden (S32 meshIndex, bool forceHidden)
Set the force hidden state on a mesh.
void setMeshHidden (const char *meshName, bool forceHidden)
Set the force hidden state on a named mesh.
void dumpMeshVisibility ()
Prints the list of meshes and their visibility state to the console for debugging purposes.
void notifyCollision ()
Go through all the items in the collision queue and call onCollision on them all.
void queueCollision (SceneObject *object, const VectorF &vec)
Add a collision to the queue of collisions waiting to be handled.
virtual void onCollision (SceneObject *object, const VectorF &vec)
bool onAdd ()
Called when the object is added to the sim.
void onRemove ()
Called when the object is removed from the sim.
void onSceneRemove ()
Called when this is removed from its current SceneManager.
bool onNewDataBlock (GameBaseData *dptr, bool reload)
Called when a new datablock is set.
void setShapeName (const char *)
const char * getShapeName ()
void setSkinName (const char *)
const char * getSkinName ()
void setDamageLevel (F32 damage)
Sets the amount of damage on this object.
void setDamageState (DamageState state)
Changes the object's damage state.
bool setDamageState (const char *state)
Changes the object's damage state, based on a named state.
const char * getDamageStateName ()
Returns the name of the current damage state as a string.
DamageState getDamageState ()
Returns the current damage state.
bool isDestroyed ()
Returns true if the object is destroyed.
void setRepairRate (F32 rate)
Sets the rate at which the object regenerates damage.
F32 getDamageLevel ()
Returns damage amount.
F32 getDamageValue ()
Returns the damage percentage.
F32 getMaxDamage ()
Returns the datablock.maxDamage value.
F32 getRepairRate ()
Returns the rate at which the object regenerates damage.
void applyDamage (F32 amount)
Adds damage to an object.
void applyRepair (F32 amount)
Removes damage to an object.
void setDamageDir (const VectorF &vec)
Sets the direction from which the damage is coming.
virtual void setEnergyLevel (F32 energy)
Sets the level of energy for this object.
void setRechargeRate (F32 rate)
Sets the rate at which the energy replentishes itself.
F32 getEnergyLevel ()
Returns the amount of energy in the object.
F32 getEnergyValue ()
Returns the percentage of energy, 0.0 - 1.0.
F32 getRechargeRate ()
Returns the recharge rate.
virtual void blowUp ()
Makes the shape explode.
void playAudio (U32 slot, SFXTrack *track)
Plays an audio sound from a mounted object.
void playAudio (U32 slot, SFXProfile *profile)
void stopAudio (U32 slot)
Stops audio from a mounted object.
const char * getThreadSequenceName (U32 slot)
bool setThreadSequence (U32 slot, S32 seq, bool reset=true)
Sets the animation thread for a mounted object.
void updateThread (Thread &st)
Update the animation thread.
bool stopThread (U32 slot)
Stop the current thread from playing on a mounted object.
bool destroyThread (U32 slot)
Destroys the given animation thread.
bool pauseThread (U32 slot)
Pause the running animation thread.
bool playThread (U32 slot)
Start playing the running animation thread again.
bool setThreadPosition (U32 slot, F32 pos)
Set the thread position.
bool setThreadDir (U32 slot, bool forward)
Toggle the thread as reversed or normal (For example, sidestep-right reversed is sidestep-left)
bool setThreadTimeScale (U32 slot, F32 timeScale)
Set the thread time scale.
void advanceThreads (F32 dt)
Advance all animation threads attached to this shapebase.
virtual void onMount (SceneObject *obj, S32 node)
Callback when this object is mounted.
virtual void getMountTransform (S32 index, const MatrixF &xfm, MatrixF *outMat)
virtual void getRenderMountTransform (F32 delta, S32 index, const MatrixF &xfm, MatrixF *outMat)
virtual void getCameraTransform (F32 *pos, MatrixF *mat)
Gets the camera to world space transform matrix.
virtual void getEyeCameraTransform (IDisplayDevice *display, U32 eyeId, MatrixF *outMat)
Gets the view transform for a particular eye, taking into account the current absolute orient and position values of the display device.
S32 getNodeIndex (U32 imageSlot, StringTableEntry nodeName)
Gets the index of a node inside a mounted image given the name.
virtual void getRetractionTransform (U32 imageSlot, MatrixF *mat)
The retraction transform is the muzzle transform in world space.
virtual void getImageTransform (U32 imageSlot, MatrixF *mat)
Gets the transform of a mounted image in world space.
virtual void getImageTransform (U32 imageSlot, S32 node, MatrixF *mat)
Gets the transform of a node on a mounted image in world space.
virtual void getImageTransform (U32 imageSlot, StringTableEntry nodeName, MatrixF *mat)
Gets the transform of a node on a mounted image in world space.
virtual void getRenderRetractionTransform (U32 index, MatrixF *mat)
virtual void getRenderImageTransform (U32 imageSlot, MatrixF *mat, bool noEyeOffset=false)
virtual void getRenderImageTransform (U32 index, S32 node, MatrixF *mat)
virtual void getRenderImageTransform (U32 index, StringTableEntry nodeName, MatrixF *mat)
virtual void getRenderMuzzleVector (U32 imageSlot, VectorF *vec)
virtual void getRenderMuzzlePoint (U32 imageSlot, Point3F *pos)
virtual F32 getDamageFlash () const
Returns the level of screenflash that should be used.
virtual void setDamageFlash (const F32 amt)
Sets the flash level.
virtual F32 getWhiteOut () const
White out is the flash-grenade blindness effect This returns the level of flash to create.
virtual void setWhiteOut (const F32)
Set the level of flash blindness.
ShapeBase * getControllingObject ()
Returns the object controlling this object.
virtual void setControllingObject (ShapeBase *obj)
Sets the controlling object.
bool isControlled ()
Returns true if this object is controlling by something.
bool isFirstPerson () const
Returns true if this object is being used as a camera in first person.
bool useObjsEyePoint () const
Returns true if the camera uses this objects eye point (defined by modeler)
bool onlyFirstPerson () const
Returns true if this object can only be used as a first person camera.
virtual F32 getCameraFov ()
Returns the vertical field of view in degrees for this object if used as a camera.
virtual F32 getDefaultCameraFov ()
Returns the default vertical field of view in degrees if this object is used as a camera.
virtual void setCameraFov (F32 fov)
Sets the vertical field of view in degrees for this object if used as a camera.
virtual bool isValidCameraFov (F32 fov)
Returns true if the vertical FOV in degrees is within allowable parameters of the datablock.
TSShape const * getShape ()
Returns the renderable shape of this object.
virtual void prepBatchRender (SceneRenderState *state, S32 mountedImageIndex)
Used from ShapeBase::_prepRenderImage() to submit render instances for the main shape or its mounted elements.
bool didRenderLastRender ()
Returns true if the last frame calculated rendered.
virtual void setHidden (bool hidden)
Sets the state of this object as hidden or not.
bool isInvincible ()
Returns true if this object can be damaged.
void startFade (F32 fadeTime, F32 fadeDelay=0.0, bool fadeOut=true)
Start fade of object in/out.
virtual void submitLights (LightManager *lm, bool staticLighting)
Traverses mounted objects and registers light sources with the light manager.
virtual LightInfo * getLight ()
F32 getUpdatePriority (CameraScopeQuery *focusObject, U32 updateMask, S32 updateSkips)
This returns a value which is used to prioritize which objects need to be updated.
U32 packUpdate (NetConnection *conn, U32 mask, BitStream *stream)
Instructs this object to pack its state for transfer over the network.
void unpackUpdate (NetConnection *conn, BitStream *stream)
Instructs this object to read state data previously packed with packUpdate.
void writePacketData (GameConnection *conn, BitStream *stream)
Write state information necessary to perform client side prediction of an object.
void readPacketData (GameConnection *conn, BitStream *stream)
Read data written with writePacketData() and update the object state.
Public Member Functions inherited from GameBase
GameBase ()
~GameBase ()
DECLARE_CONOBJECT (GameBase)
bool setDataBlock (GameBaseData *dptr)
Assigns this object a datablock and loads attributes with onNewDataBlock.
GameBaseData * getDataBlock ()
Returns the datablock for this object.
void inspectPostApply ()
Called after any property of the object is changed in the world editor.
void scriptOnAdd ()
Executes the 'onAdd' script function for this object.
void scriptOnNewDataBlock ()
Executes the 'onNewDataBlock' script function for this object.
void scriptOnRemove ()
Executes the 'onRemove' script function for this object.
void setGhostUpdated (bool b)
Set or clear the GhostUpdated bit in our NetFlags.
bool isGhostUpdated () const
Returns true if the GhostUpdated bit in our NetFlags is set.
void setNewGhost (bool n)
Set or clear the NewGhost bit in our NetFlags.
bool isNewGhost () const
Returns true if the NewGhost bit in out NetFlags is set.
void setNetNearbyAdded (bool b)
Set or clear the NetNearbyAdded bit in our NetFlags.
bool isNetNearbyAdded () const
Returns true if the NetNearby bit in our NetFlags is set.
bool isHifiPassive () const
Returns true if the HiFiPassive bit in our NetFlags is set.
bool isTickLast () const
Returns true if the TickLast bit in our NetFlags is set.
bool isNetOrdered () const
Returns true if the NetOrdered bit in our NetFlags is set.
virtual void computeNetSmooth (F32 backDelta)
Called during client catchup under the hifi-net model.
TickCache & getTickCache ()
Returns TickCache used under the hifi-net model.
virtual U32 getPacketDataChecksum (GameConnection *conn)
Gets the checksum for packet data.
GameConnection * getControllingClient ()
Returns the client controlling this object.
const GameConnection * getControllingClient () const
MoveList * getMoveList ()
Returns the MoveList of the client controlling this object.
virtual void setControlObject (GameBase *)
DECLARE_CALLBACK (void, setControl,(bool controlled))
Public Member Functions inherited from SceneObject
SceneObject ()
virtual ~SceneObject ()
virtual void clearProcessAfter ()
Clears the effects of a call to processAfter()
DECLARE_CONOBJECT (SceneObject)
virtual ProcessObject * getAfterObject () const
Returns the object that this processes after.
ProcessList * getProcessList () const
Return the ProcessList for this object to use.
U32 getTypeMask () const
Return the type mask that indicates to which broad object categories this object belongs.
virtual void processAfter (ProcessObject *obj)
Force this object to process after some other object.
virtual void setProcessTick (bool t)
Set the status of tick processing.
virtual bool writeField (StringTableEntry fieldName, const char *value)
Determine whether or not a field should be written.
SceneManager * getSceneManager () const
Return the SceneManager that this SceneObject belongs to.
void addToScene ()
Adds object to the client or server container depending on the object.
void removeFromScene ()
Removes the object from the client/server container.
SceneContainer * getContainer ()
Returns a pointer to the container that contains this object.
bool isRenderEnabled () const
Return true if this object is rendered.
void setRenderEnabled (bool value)
Set whether the object gets rendered.
bool isSelectionEnabled () const
Return true if this object can be selected in the editor.
void setSelectionEnabled (bool value)
Set whether the object can be selected in the editor.
bool isCullingDisabledInEditor () const
Return true if the object doesn't want to be subjected to culling when in the editor.
bool isVisualOccluder () const
Return true if the object should be taken into account for visual occlusion.
virtual void disableCollision ()
Disables collisions for this object including raycasts.
virtual void enableCollision ()
Enables collisions for this object.
bool isCollisionEnabled () const
Returns true if collisions are enabled.
virtual const MatrixF & getTransform () const
Returns the transform which can be used to convert object space to world space.
const MatrixF & getWorldTransform () const
Returns the transform which can be used to convert world space into object space.
const VectorF & getScale () const
Returns the scale of the object.
const Box3F & getObjBox () const
Returns the bounding box for this object in local coordinates.
const Box3F & getWorldBox () const
Returns the bounding box for this object in world coordinates.
const SphereF & getWorldSphere () const
Returns the bounding sphere for this object in world coordinates.
Point3F getBoxCenter () const
Returns the center of the bounding box in world coordinates.
virtual void setScale (const VectorF &scale)
Sets the scale for the object.
virtual void setRenderTransform (const MatrixF &mat)
This sets the render transform for this object.
const MatrixF & getRenderTransform () const
Returns the render transform.
const MatrixF & getRenderWorldTransform () const
Returns the render transform to convert world to local coordinates.
const Box3F & getRenderWorldBox () const
Returns the render world box.
virtual void buildSilhouette (const SceneCameraState &cameraState, Vector< Point3F > &outPoints)
Build a world-space silhouette polygon for the object for the given camera settings.
virtual bool containsPoint (const Point3F &point)
Return true if the given point is contained by the object's (collision) shape.
virtual bool collideBox (const Point3F &start, const Point3F &end, RayInfo *info)
virtual Point3F getPosition () const
Returns the position of the object.
Point3F getRenderPosition () const
Returns the render-position of the object.
void setPosition (const Point3F &pos)
Sets the position of the object.
virtual void applyRadialImpulse (const Point3F &origin, F32 radius, F32 magnitude)
Applies a radial impulse to the object using the impulse origin and force.
virtual F32 distanceTo (const Point3F &pnt) const
Returns the distance from this object to a point.
bool isOccludingSound () const
Return whether the object's collision shape is blocking sound.
virtual SFXAmbience * getSoundAmbience () const
Return the ambient sound space active inside the volume of this object or NULL if the object does not have its own ambient space.
void setLightingPlugin (SceneObjectLightingPlugin *plugin)
SceneObjectLightingPlugin * getLightingPlugin ()
const bool isGlobalBounds () const
void setGlobalBounds ()
If global bounds are set to be true, then the object is assumed to have an infinitely large bounding box for collision and rendering purposes.
virtual void mountObject (SceneObject *obj, S32 node, const MatrixF &xfm=MatrixF::Identity)
ex: Mount B to A at A's node N A.mountObject(B, N)
virtual void unmountObject (SceneObject *obj)
Remove an object mounting.
virtual SceneObject * getObjectMount ()
Return the object that this object is mounted to.
virtual SceneObject * getMountLink ()
Return object link of next object mounted to this object's mount.
virtual SceneObject * getMountList ()
Returns object list of objects mounted to this object.
virtual U32 getMountNode ()
Returns the mount id that this is mounted to.
virtual bool isMounted ()
Returns true if this object is mounted to anything at all Also try to resolve the PID to objectId here if it is pending.
virtual S32 getMountedObjectCount ()
Returns the number of object mounted along with this.
virtual SceneObject * getMountedObject (S32 idx)
Returns the object mounted at a position in the mount list.
virtual S32 getMountedObjectNode (S32 idx)
Returns the node the object at idx is mounted to.
virtual SceneObject * getMountNodeObject (S32 node)
Returns the object a object on the mount list is mounted to.
void resolveMountPID ()
Public Member Functions inherited from NetObject
NetObject ()
~NetObject ()
virtual void clearMaskBits (U32 orMask)
Clear the specified bits from the dirty mask.
void clearScopeAlways ()
Stop scoping the object to all connections.
virtual String describeSelf () const
Return a textual description of the object.
virtual U32 filterMaskBits (U32 mask, NetConnection *connection)
U32 getNetIndex ()
Get the ghost index of this object.
bool isClientObject () const
Is this a client object?
bool isGhost () const
Is this is a ghost?
bool isGhostable () const
Is this object ghostable?
bool isGhostAlways () const
Should this object always be ghosted?
bool isScopeable () const
Is this object subject to scoping?
bool isScopeLocal () const
Should this object only be visible to the client which created it?
bool isServerObject () const
Is this a server object?
virtual void setMaskBits (U32 orMask)
Used to mark a bit as dirty; ie, that its corresponding set of fields need to be transmitted next update.
void setScopeAlways ()
Scope the object to all connections.
DECLARE_CONOBJECT (NetObject)
NetObject * getServerObject () const
Returns a pointer to the server object when on a local connection.
NetObject * getClientObject () const
Returns a pointer to the client object when on a local connection.
Public Member Functions inherited from SimGroup
~SimGroup ()
void addObject (SimObject *object, SimObjectId id)
void addObject (SimObject *object, const char *name)
virtual void addObject (SimObject *object)
Add the given object to the set.
virtual void clear ()
Remove all objects from this set.
virtual SimGroup * clone ()
Return a shallow copy of this object.
DECLARE_CONOBJECT (SimGroup)
virtual SimGroup * deepClone ()
Return a deep copy of this object.
virtual SimObject * findObject (const char *name)
Find a named sub-object of this object.
virtual void popObject ()
Remove an object from the end of the list.
virtual bool processArguments (S32 argc, ConsoleValueRef *argv)
Process constructor options. (ie, new SimObject(1,2,3))
virtual void pushObject (SimObject *object)
Add the given object to the end of the object list of this set.
virtual void removeObject (SimObject *object)
Remove the given object from the set.
Public Member Functions inherited from SimSet
SimSet ()
~SimSet ()
virtual void addTamlChild (SimObject *pSimObject)
Called when Taml attempts to populate an objects children during a read.
void callOnChildren (const String &method, S32 argc, ConsoleValueRef argv[], bool executeOnChildGroups=true)
DECLARE_CONOBJECT (SimSet)
SimObject * findObject (SimObject *object)
Find the given object in this set.
template<class T >
void findObjectByCallback (bool(*fn)(T *), Vector< T * > &foundObjects)
Add all child objects (including children of children) to the foundObjects Vector which are of type T and for which DecideAddObjectCallback return true;.
virtual SimObject * findObjectByInternalName (StringTableEntry internalName, bool searchChildren=false)
SimObject * findObjectByLineNumber (const char *fileName, S32 declarationLine, bool searchChildren=false)
template<class T >
void findObjectByType (Vector< T * > &foundObjects)
Add all child objects (including children of children) to the foundObjects Vector which are of type T.
SimObject * getRandom ()
const SetModificationSignal & getSetModificationSignal () const
Return the signal that is triggered when an object is added to or removed from the set.
SetModificationSignal & getSetModificationSignal ()
virtual SimObject * getTamlChild (const U32 childIndex) const
Called when Taml attempts to compile a list of children.
virtual U32 getTamlChildCount (void) const
Called when Taml attempts to compile a list of children.
void lock ()
virtual bool readObject (Stream *stream)
U32 sizeRecursive ()
Return the number of objects in this set as well as all sets that are contained in this set and its children.
void unlock ()
virtual void write (Stream &stream, U32 tabStop, U32 flags=0)
Output the TorqueScript to recreate this object.
virtual bool writeObject (Stream *stream)
virtual bool acceptsAsChild (SimObject *object) const
Return true if this set accepts the given object as a child.
void deleteAllObjects ()
Deletes all the objects in the set.
void bringObjectToFront (SimObject *obj)
void pushObjectToBack (SimObject *obj)
void scriptSort (const String &scriptCallbackFn)
Performs a sort of the objects in the set using a script callback function to do the comparison.
SimObject * front ()
SimObject * first ()
SimObject * last ()
bool empty () const
S32 size () const
iterator begin ()
iterator end ()
value operator[] (S32 index)
iterator find (iterator first, iterator last, SimObject *obj)
iterator find (SimObject *obj)
virtual bool reOrder (SimObject *obj, SimObject *target=0)
Reorder the position of "obj" to either be the last object in the list or, if "target" is given, to come before "target" in the list of children.
SimObject * at (S32 index) const
Return the object at the given index.
Public Member Functions inherited from SimObject
virtual void copyTo (SimObject *object)
Copy SimObject to another SimObject (Originally designed for T2D).
DECLARE_CONOBJECT (SimObject)
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
virtual void getConsoleMethodData (const char *fname, S32 routingId, S32 *type, S32 *minArgs, S32 *maxArgs, void **callback, const char **usage)
Namespace * getNamespace ()
Return the object's namespace.
StringTableEntry getProgenitorFile (void) const
virtual bool handlesConsoleMethod (const char *fname, S32 *routingId)
void setProgenitorFile (const char *pFile)
const char * tabComplete (const char *prevText, S32 baseLen, bool)
Get next matching item in namespace.
virtual void writeFields (Stream &stream, U32 tabStop)
Write the fields of this object in TorqueScript.
void setCanSaveDynamicFields (bool bCanSave)
Set whether fields created at runtime should be saved. Default is true.
bool getCanSaveDynamicFields ()
Get whether fields created at runtime should be saved. Default is true.
SimObject * getCopySource () const
Return the object that this object is copying fields from.
void setCopySource (SimObject *object)
Set the object that this object should be copying fields from.
void assignFieldsFrom (SimObject *obj)
Copy fields from another object onto this one.
void assignDynamicFieldsFrom (SimObject *obj)
Copy dynamic fields from another object onto this one.
Notify * removeNotify (void *ptr, Notify::Type)
Remove a notification from the list.
void deleteNotify (SimObject *obj)
Notify an object when we are deleted.
void clearNotify (SimObject *obj)
Notify an object when we are cleared.
void clearAllNotifications ()
Remove all notifications for this object.
void processDeleteNotifies ()
Send out deletion notifications.
void registerReference (SimObject **obj)
Register a reference to this object.
void unregisterReference (SimObject **obj)
Unregister a reference to this object.
SimPersistID * getPersistentId () const
Return the persistent ID assigned to this object or NULL.
SimPersistID * getOrCreatePersistentId ()
Return the persistent ID assigned to this object or assign one to it if it has none.
StringTableEntry getClassNamespace () const
Return name of class namespace set on this object.
StringTableEntry getSuperClassNamespace () const
Return name of superclass namespace set on this object.
void setClassNamespace (const char *classNamespace)
void setSuperClassNamespace (const char *superClassNamespace)
const char * getDataField (StringTableEntry slotName, const char *array)
Get the value of a field on the object.
void setDataField (StringTableEntry slotName, const char *array, const char *value)
Set the value of a field on the object.
const char * getPrefixedDataField (StringTableEntry fieldName, const char *array)
void setPrefixedDataField (StringTableEntry fieldName, const char *array, const char *value)
const char * getPrefixedDynamicDataField (StringTableEntry fieldName, const char *array, const S32 fieldType=-1)
void setPrefixedDynamicDataField (StringTableEntry fieldName, const char *array, const char *value, const S32 fieldType=-1)
StringTableEntry getDataFieldPrefix (StringTableEntry fieldName)
U32 getDataFieldType (StringTableEntry slotName, const char *array)
Get the type of a field on the object.
void setDataFieldType (const U32 fieldTypeId, StringTableEntry slotName, const char *array)
Set the type of a dynamic field on the object.
void setDataFieldType (const char *typeName, StringTableEntry slotName, const char *array)
SimFieldDictionary * getFieldDictionary ()
Get reference to the dictionary containing dynamic fields.
virtual StringTableEntry getComponentName ()
void setInternalName (const char *newname)
These functions support internal naming that is not namespace bound for locating child controls in a generic way.
StringTableEntry getInternalName () const
Get the internal name of this control.
void setOriginalName (const char *originalName)
Set the original name of this control.
StringTableEntry getOriginalName () const
Get the original name of this control.
void setFilename (const char *file)
These functions allow you to set and access the filename where this object was created.
StringTableEntry getFilename () const
Get the filename.
void setDeclarationLine (U32 lineNumber)
These functions are used to track the line number (1-based) on which the object was created if it was loaded from script.
S32 getDeclarationLine () const
Get the declaration line number.
virtual bool save (const char *pcFilePath, bool bOnlySelected=false, const char *preappend=NULL)
Save object as a TorqueScript File.
virtual bool isMethod (const char *methodName)
Check if a method exists in the objects current namespace.
virtual bool isField (const char *fieldName, bool includeStatic=true, bool includeDynamic=true)
Return true if the field is defined on the object.
SimObjectId getId () const
Return the unique numeric object ID.
const char * getIdString () const
Return the object ID as a string.
StringTableEntry getName () const
Return the name of this object.
SimGroup * getGroup () const
Return the SimGroup that this object is contained in.
void assignName (const char *name)
Assign the given name to this object.
void setId (SimObjectId id)
bool isChildOfGroup (SimGroup *pGroup)
bool isProperlyAdded () const
bool isDeleted () const
bool isRemoved () const
virtual bool isLocked () const
virtual void setLocked (bool b)
virtual bool isHidden () const
bool isSelected () const
bool isExpanded () const
bool isEditorOnly () const
bool isNameChangeAllowed () const
bool isAutoDeleted () const
void setSelected (bool sel)
void setExpanded (bool exp)
void setModDynamicFields (bool dyn)
void setModStaticFields (bool sta)
bool canModDynamicFields ()
bool canModStaticFields ()
void setAutoDelete (bool val)
void setEditorOnly (bool val)
void setNameChangeAllowed (bool val)
bool getCanSave () const
Returns boolean specifying if the object can be serialized.
virtual void setCanSave (bool val)
Set serialization flag.
bool isSelectedRecursive () const
Returns true if this object is selected or any group it is a member of is.
SimObject ()
virtual ~SimObject ()
virtual void onGroupAdd ()
Called when the object is added to a SimGroup.
virtual void onGroupRemove ()
Called when the object is removed from a SimGroup.
virtual void onNameChange (const char *name)
Called when the object's name is changed.
virtual void onPostAdd ()
Called when the adding of the object to the sim is complete, all sub-objects have been processed as well.
virtual void onStaticModified (const char *slotName, const char *newValue=NULL)
Specifically, these are called by setDataField when a static or dynamic field is modified, see the console details.
virtual void onDynamicModified (const char *slotName, const char *newValue=NULL)
Called when a dynamic field is modified.
virtual void inspectPreApply ()
Called before any property of the object is changed in the world editor.
virtual void onEditorEnable ()
Called when the editor is activated.
virtual void onEditorDisable ()
Called when the editor is deactivated.
bool registerObject ()
Register an object with the object system.
bool registerObject (U32 id)
Register the object, forcing the id.
bool registerObject (const char *name)
Register the object, assigning the name.
bool registerObject (const char *name, U32 id)
Register the object, assigning a name and ID.
void unregisterObject ()
Unregister the object from Sim.
void deleteObject ()
Unregister, mark as deleted, and free the object.
void safeDeleteObject ()
Performs a safe delayed delete of the object using a sim event.
bool addToSet (SimObjectId)
bool addToSet (const char *)
bool removeFromSet (SimObjectId)
bool removeFromSet (const char *)
void dumpToConsole (bool includeFunctions=true)
Dump the contents of this object to the console.
virtual void dumpClassHierarchy ()
added this so that you can print the entire class hierarchy, including script objects,
virtual void dumpGroupHierarchy ()
Print the SimGroup hierarchy of this object to the console.
Public Member Functions inherited from ConsoleObject
ConsoleObject ()
virtual AbstractClassRep * getClassRep () const
Gets the ClassRep.
const AbstractClassRep::Field * findField (StringTableEntry fieldName) const
Get a reference to a field by name.
bool setField (const char *fieldName, const char *value)
Set the value of a field.
void logMessage (const char *fmt,...) const
Logs with Con::printf.
void logWarning (const char *fmt,...) const
Logs with Con::warnf.
void logError (const char *fmt,...) const
Logs with Con::errorf.
const AbstractClassRep::FieldList & getFieldList () const
Get a list of all the fields. This information cannot be modified.
AbstractClassRep::FieldList & getModifiableFieldList ()
Get a list of all the fields, set up so we can modify them.
bool & getDynamicGroupExpand ()
Get a handle to a boolean telling us if we expanded the dynamic group.
S32 getClassId (U32 netClassGroup) const
Get our network-layer class id.
StringTableEntry getClassName () const
Get our compiler and platform independent class name.
Public Member Functions inherited from EngineObject
EngineObject ()
virtual ~EngineObject ()
DECLARE_ABSTRACT_CLASS (EngineObject, void)
DECLARE_INSCOPE (_GLOBALSCOPE)
IEngineObjectPool * getEngineObjectPool () const
Return the pool of EngineObjects to which this object belongs.
void operator delete (void *ptr)
Release the given object's memory in the pool it has been allocated from.
void * operator new (size_t size)
void * operator new (size_t size, IEngineObjectPool *pool)
void * operator new (size_t size TORQUE_TMM_ARGS_DECL)
Allocate a new object in the default object pool.
void * operator new (size_t size, IEngineObjectPool *pool TORQUE_TMM_ARGS_DECL)
Allocate a new object in the given object pool.
void * operator new (size_t size, void *ptr)
Placement new.
Public Member Functions inherited from StrongRefBase
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Public Member Functions inherited from ProcessObject
ProcessObject ()
virtual ~ProcessObject ()
bool isTicking () const
Returns true if this object processes ticks.
void plJoin (ProcessObject *)
void plLinkAfter (ProcessObject *)
void plLinkBefore (ProcessObject *)
void plUnlink ()
virtual void preprocessMove (Move *move)
Allow object to modify the Move before it is ticked or sent to the server.
void removeFromProcessList ()
Removes this object from the tick-processing list.
Public Member Functions inherited from ISceneLight
virtual ~ISceneLight ()
Static Public Member Functions
static void initPersistFields ()
Static Public Member Functions inherited from Player
static void consoleInit ()
Static Public Member Functions inherited from ShapeBase
static const char * _getFieldSkin (void *object, const char *data)
static bool _setFieldSkin (void *object, const char *index, const char *data)
static void initPersistFields ()
static void consoleInit ()
static void incRenderFrame ()
Increments the last rendered frame number.
Static Public Member Functions inherited from GameBase
static void initPersistFields ()
static void consoleInit ()
Static Public Member Functions inherited from SceneObject
static void initPersistFields ()
Static Public Member Functions inherited from NetObject
static void collapseDirtyList ()
static void initPersistFields ()
template<class T >
static T * getServerObject (T *netObj)
Template form for the callers convenience.
template<class T >
static T * getClientObject (T *netObj)
Template form for the callers convenience.
Static Public Member Functions inherited from SimObject
static SimObject * __findObject (const char *id)
static const char * __getObjectId (ConsoleObject *object)
static void initPersistFields ()
static void setForcedId (SimObjectId id)
Force an Id on the next registered object.
Static Public Member Functions inherited from ConsoleObject
static const char * __category ()
static const char * __description ()
static void consoleInit ()
Register global constant variables and do other one-time initialization tasks in a subclass of ConsoleObject.
static void initPersistFields ()
Register dynamic fields in a subclass of ConsoleObject.
static const char * lookupClassName (const U32 in_classTag)
Get the classname from a class tag.
static AbstractClassRep * getStaticClassRep ()
Get the abstract class information for this class.
static AbstractClassRep * getParentStaticClassRep ()
Get the abstract class information for this class's superclass.
static ConsoleObject * create (const char *in_pClassName)
static ConsoleObject * create (const U32 groupId, const U32 typeId, const U32 in_classId)
static void addGroup (const char *in_pGroupname, const char *in_pGroupDocs=NULL)
Mark the beginning of a group of fields.
static void endGroup (const char *in_pGroupname)
Mark the end of a group of fields.
static void addArray (const char *arrayName, S32 count)
Marks the start of a fixed size array of fields.
static void endArray (const char *arrayName)
Marks the end of an array of fields.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a complex field.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::WriteDataNotify in_writeDataFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, const char *in_pFieldDocs, U32 flags=0)
Register a simple field.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::WriteDataNotify in_writeDataFn, const char *in_pFieldDocs, U32 flags=0)
static void addFieldV (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, TypeValidator *v, const char *in_pFieldDocs=NULL)
Register a validated field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, AbstractClassRep::WriteDataNotify in_writeDataFn=&defaultProtectedWriteFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a complex protected field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, AbstractClassRep::WriteDataNotify in_writeDataFn=&defaultProtectedWriteFn, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a simple protected field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addDeprecatedField (const char *fieldName)
Add a deprecated field.
static bool removeField (const char *in_pFieldname)
Remove a field.
static ConsoleObject * __findObject (const char *)
static const char * __getObjectId (ConsoleObject *)
Static Public Member Functions inherited from EngineObject
static void debugDumpInstances ()
Dump describeSelf()s of all live ConsoleObjects to the console.
static void debugEnumInstances (const std::type_info &type, DebugEnumInstancesCallback callback)
Call the given callback for all instances of the given type.
static void debugEnumInstances (const char *className, DebugEnumInstancesCallback callback)
Same as above but uses an export class name and also includes inheritance (i.e.
Protected Member Functions
virtual void onReachDestination ()
virtual void onStuck ()
Protected Member Functions inherited from Player
F32 _doCollisionImpact (const Collision *collision, bool fallingCollision)
void _findContact (SceneObject **contactObject, VectorF *contactNormal, Vector< SceneObject * > *outOverlapObjects)
void _handleCollision (const Collision &collision)
Point3F _move (const F32 travelTime, Collision *outCol)
Interpolate movement.
void buildImagePrefixPaths (String *prefixPaths)
void calcClassRenderData ()
Preprender logic.
void checkMissionArea ()
See if the player is still in the mission area.
S32 convertActionToImagePrefix (U32 action)
F32 deathDelta (Point3F &delta)
void disableHeadZCalc ()
void enableHeadZCalc ()
void findContact (bool *run, bool *jump, VectorF *contactNormal)
S32 findPrefixSequence (String *prefixPaths, const String &baseSeq)
virtual U32 getArmAction () const
virtual const char * getImageAnimPrefix (U32 imageSlot, S32 imageShapeIndex)
Get the animation prefix for the image.
bool inDeathAnim ()
Are we in the process of dying?
bool inSittingAnim ()
virtual void onImage (U32 imageSlot, bool unmount)
virtual void onImageAnimThreadChange (U32 imageSlot, S32 imageShapeIndex, ShapeBaseImageData::StateData *lastState, const char *anim, F32 pos, F32 timeScale, bool reset=false)
virtual void onImageAnimThreadUpdate (U32 imageSlot, S32 imageShapeIndex, F32 dt)
virtual void onImageRecoil (U32 imageSlot, ShapeBaseImageData::StateData::RecoilState)
virtual void onImageStateAnimation (U32 imageSlot, const char *seqName, bool direction, bool scaleToState, F32 stateTimeOutValue)
virtual void pickActionAnimation ()
virtual void pickBestMoveAction (U32 startAnim, U32 endAnim, U32 *action, bool *forward) const
void playFootstepSound (bool triggeredLeft, Material *contactMaterial, SceneObject *contactObject)
Play sound for foot contact.
void playImpactSound ()
Play an impact sound.
virtual void reSkin ()
Do a reskin if necessary.
virtual void setActionThread (U32 action, bool forward, bool hold=false, bool wait=false, bool fsp=false, bool forceSet=false)
virtual bool setArmThread (U32 action)
void setControllingClient (GameConnection *client)
Set which client is controlling this player.
void setPosition (const Point3F &pos, const Point3F &viewRot)
void setRenderPosition (const Point3F &pos, const Point3F &viewRot, F32 dt=-1)
void setState (ActionState state, U32 ticks=0)
bool step (Point3F *pos, F32 *maxStep, F32 time)
virtual void updateActionThread ()
void updateAnimation (F32 dt)
Update other animations.
void updateAnimationTree (bool firstPerson)
virtual void updateDamageLevel ()
virtual void updateDamageState ()
void updateDeathOffsets ()
void updateLookAnimation (F32 dT=0.f)
Update head animation.
virtual bool updatePos (const F32 travelTime=TickSec)
void updateState ()
virtual void onUnmount (SceneObject *obj, S32 node)
Callback when this object is unmounted.
virtual void unmount ()
Unmount this object from it's mount.
void updateSplash ()
Update the splash effect.
void updateFroth (F32 dt)
Update any froth.
void updateWaterSounds (F32 dt)
Update water sounds.
void createSplash (Point3F &pos, F32 speed)
Creates a splash.
bool collidingWithWater (Point3F &waterHeight)
Are we colliding with water?
Protected Member Functions inherited from ShapeBase
void _prepRenderImage (SceneRenderState *state, bool renderSelf, bool renderMountedImages)
The inner prep render function that does the standard work to render the shapes.
void _renderBoundingBox (ObjectRenderInst *ri, SceneRenderState *state, BaseMatInstance *)
Renders the shape bounds as well as the bounds of all mounted shape images.
DECLARE_CALLBACK (F32, validateCameraFov,(F32 fov))
void emitDust (ParticleEmitter *emitter, F32 triggerHeight, const Point3F &offset, U32 numMilliseconds, const Point3F &axis=Point3F::Zero)
void updateAudioPos ()
Recalculates the spacial sound based on the current position of the object emitting the sound.
void updateAudioState (Sound &st)
Updates the audio state of the supplied sound.
void updateContainer ()
Update bouyency and drag properties.
void updateMass ()
This recalculates the total mass of the object, and all mounted objects.
void updateServerAudio ()
Prune out non looping sounds from the sound manager which have expired.
void _updateHiddenMeshes ()
Sync the shape instance with the hidden mesh bit vector.
void scriptCallback (U32 imageSlot, const char *function)
Utility function to call script functions which have to do with ShapeBase objects.
virtual void setImage (U32 imageSlot, ShapeBaseImageData *imageData, NetStringHandle &skinNameHandle, bool loaded=true, bool ammo=false, bool triggerDown=false, bool altTriggerDown=false, bool motion=false, bool genericTrigger0=false, bool genericTrigger1=false, bool genericTrigger2=false, bool genericTrigger3=false, bool target=false)
Assign a ShapeBaseImage to an image slot.
void resetImageSlot (U32 imageSlot)
Clear out an image slot.
U32 getImageFireState (U32 imageSlot)
Get the firing action state of the image.
U32 getImageAltFireState (U32 imageSlot)
Get the alternate firing action state of the image.
U32 getImageReloadState (U32 imageSlot)
Get the reload action state of the image.
void setImageState (U32 imageSlot, U32 state, bool force=false)
Sets the state of the image by state index.
void updateAnimThread (U32 imageSlot, S32 imageShapeIndex, ShapeBaseImageData::StateData *lastState=NULL)
void updateImageAnimation (U32 imageSlot, F32 dt)
Advance animation on a image.
void updateImageState (U32 imageSlot, F32 dt)
Advance state of image.
void startImageEmitter (MountedImage &image, ShapeBaseImageData::StateData &state)
Start up the particle emitter for the this shapebase.
Light * getImageLight (U32 imageSlot)
Get light information for a mounted image.
U32 getImageShapeIndex (const MountedImage &image) const
Get the shape index to use for a mounted image.
virtual void onDeleteNotify (SimObject *)
Called when a SimObject is deleted.
virtual void ejectShellCasing (U32 imageSlot)
virtual void shakeCamera (U32 imageSlot)
virtual void onImpact (SceneObject *obj, const VectorF &vec)
virtual void onImpact (const VectorF &vec)
Protected Member Functions inherited from SceneObject
virtual U32 getObjectFlagMax () const
Returns the greatest object flag bit defined.
virtual bool onSceneAdd ()
Called when this is added to a SceneManager.
void _updateZoningState () const
Refresh the zoning state of this object, if it isn't up-to-date anymore.
ZoneRef * _getZoneRefHead () const
Return the first link in the zone list of this object.
U32 _getNumCurrZones () const
Gets the number of zones containing this object.
U32 _getCurrZone (const U32 index) const
Returns the nth zone containing this object.
void resetWorldBox ()
Regenerates the world-space bounding box and bounding sphere.
void resetRenderWorldBox ()
Regenerates the render-world-space bounding box and sphere.
void resetObjectBox ()
Regenerates the object-space bounding box from the world-space bounding box, the world space to object space transform, and the object scale.
U32 getContainerSeqKey () const
Returns the container sequence key.
void setContainerSeqKey (const U32 key)
Sets the container sequence key.
Protected Member Functions inherited from SimSet
DECLARE_CALLBACK (void, onObjectAdded,(SimObject *object))
DECLARE_CALLBACK (void, onObjectRemoved,(SimObject *object))
Protected Member Functions inherited from SimObject
virtual void _destroySelf ()
Subclasses should overload this method instead of the public destroySelf().
virtual String _getLogMessage (const char *fmt, va_list args) const
We can provide more detail, like object name and id.
virtual void _onSelected ()
Called when the object is selected in the editor.
virtual void _onUnselected ()
Called when the object is unselected in the editor.
object incRefCount ()
virtual void onTamlAddParent (SimObject *pParentObject)
Called after Taml has finished reading the object and has added the object to any parent.
virtual void onTamlCustomRead (const TamlCustomNodes &customNodes)
Called during the reading of the object to allow custom properties to be read.
virtual void onTamlCustomWrite (TamlCustomNodes &customNodes)
Called during the writing of the object to allow custom properties to be written.
virtual void onTamlPostRead (const TamlCustomNodes &customNodes)
Called after Taml has finished reading the object.
virtual void onTamlPostWrite (void)
Called after Taml has finished writing the object.
virtual void onTamlPreRead (void)
Called prior to Taml reading the object.
virtual void onTamlPreWrite (void)
Taml callbacks.
object registerObject ()
void linkNamespaces ()
Perform namespace linking on this object.
void unlinkNamespaces ()
Undo namespace linking on this object.
Protected Member Functions inherited from ConsoleObject
ConsoleObject (const ConsoleObject &)
Protected Member Functions inherited from EngineObject
object incRefCount ()
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Additional Inherited Members
Public Attributes inherited from Player
OrthoBoxConvex mConvex
Box3F mScaledBox
Box3F mWorkingQueryBox
Public Attributes inherited from ShapeBase
CubeReflector mCubeReflector
CollisionTimeout * mTimeoutList
Public Attributes inherited from SceneObject
GFXTextureObject * mAccuTex
bool mPathfindingIgnore
Public Attributes inherited from EngineObject
DECLARE_INSTANTIABLE
Public Attributes inherited from ProcessObject
bool mIsGameBase
U32 mOrderGUID
Link mProcessLink
U32 mProcessTag
bool mProcessTick
Static Public Attributes inherited from Player
static S32 smExtendedMoveHeadPosRotIndex
The ExtendedMove position/rotation index used for head movements.
Static Public Attributes inherited from ShapeBase
static F32 sCloakSpeed
static F32 sDamageFlashDec
static F32 sFullCorrectionDistance
static U32 sLastRenderFrame
static F32 sWhiteoutDec
static CollisionTimeout * sFreeTimeoutList
Static Public Attributes inherited from GameBase
static bool gShowBoundingBox
Should we render bounding boxes?
Static Public Attributes inherited from SceneObject
static Signal< void(SceneObject *) > smSceneObjectAdd
Triggered when a SceneObject onAdd is called.
static Signal< void(SceneObject *) > smSceneObjectRemove
Triggered when a SceneObject onRemove is called.
Static Public Attributes inherited from ConsoleObject
static const bool __smIsDatablock = false
Subclasses of ConsoleObjects that are datablocks should redefine this static member variable and set it to true.
Protected Types inherited from Player
enum ActionState {
NullState,
MoveState,
RecoverState,
NumStateBits = 3
}
Main player state.
enum MaskBits {
ActionMask = Parent::NextFreeMask << 0,
MoveMask = Parent::NextFreeMask << 1,
ImpactMask = Parent::NextFreeMask << 2,
NextFreeMask = Parent::NextFreeMask << 3
}
Bit masks for different types of events.
Protected Types inherited from NetObject
enum NetFlags {
IsGhost = BIT(1),
ScopeAlways = BIT(6),
ScopeLocal = BIT(7),
Ghostable = BIT(8),
MaxNetFlagBit = 15
}
Protected Types inherited from EngineObject
typedef ::FalseType __IsDisposableType
typedef ::FalseType __IsSingletonType
Static Protected Member Functions inherited from GameBase
static bool setDataBlockProperty (void *object, const char *index, const char *data)
Static Protected Member Functions inherited from SimObject
static bool _setPersistentID (void *object, const char *index, const char *data)
Static Protected Member Functions inherited from EngineObject
static void * _allocateObject (size_t size, IEngineObjectPool *pool TORQUE_TMM_ARGS_DECL)
Protected Attributes inherited from Player
StateDelta delta
Used for interpolation on the client.
bool mAllowCrouching
bool mAllowJetJumping
bool mAllowJumping
bool mAllowProne
bool mAllowSprinting
bool mAllowSwimming
Point3F mAnchorPoint
Pos compression anchor.
F32 mBubbleEmitterTime
struct Player::ContactInfo mContactInfo
S32 mContactTimer
Ticks since last contact.
SimObjectPtr< ShapeBase > mControlObject
Controlling object.
PlayerData * mDataBlock
MMmmmmm...datablock...
struct Player::Death mDeath
bool mFalling
Falling in mid-air?
Point3F mHead
Head rotation, uses only x & z.
S32 mImpactSound
bool mInMissionArea
Are we in the mission area?
bool mInWater
Is true if WaterCoverage is greater than zero.
bool mJetting
S32 mJumpDelay
Delay till next jump.
U32 mJumpSurfaceLastContact
How long it's been since the player landed (ticks)
Point3F mJumpSurfaceNormal
Normal of the surface the player last jumped on.
F32 mLastAbsolutePitch
Stores that last absolute pitch value as passed in by ExtendedMove.
F32 mLastAbsoluteRoll
Stores that last absolute roll value as passed in by ExtendedMove.
F32 mLastAbsoluteYaw
Stores that last absolute yaw value as passed in by ExtendedMove.
Point3F mLastPos
Holds the last position for physics updates.
Point3F mLastWaterPos
Same as mLastPos, but for water.
S32 mMountPending
mMountPending suppresses tickDelay countdown so players will sit until their mount, or another animation, comes through (or 13 seconds elapses).
SFXSource * mMoveBubbleSound
Sound for moving bubbles.
PhysicsPlayer * mPhysicsRep
Pose mPose
S32 mPredictionCount
Number of ticks to predict.
F32 mRecoverDelay
When bypassing the legacy recover system and only using the land sequence, this is how long the player will be in the land sequence.
S32 mRecoverTicks
same as recoverTicks in the player datablock
U32 mReversePending
Point3F mRot
Body rotation, uses only z.
TSThread * mShapeFPAmbientThread [ShapeBase::MaxMountedImages]
TSThread * mShapeFPAnimThread [ShapeBase::MaxMountedImages]
TSThread * mShapeFPFlashThread [ShapeBase::MaxMountedImages]
TSShapeInstance * mShapeFPInstance [ShapeBase::MaxMountedImages]
TSThread * mShapeFPSpinThread [ShapeBase::MaxMountedImages]
TSThread * mShapeFPVisThread [ShapeBase::MaxMountedImages]
SimObjectPtr< ParticleEmitter > mSplashEmitter [PlayerData::NUM_SPLASH_EMITTERS]
ActionState mState
What is the player doing?
bool mSwimming
Is true if WaterCoverage is above the swimming threshold.
bool mUseHeadZCalc
Including mHead.z in transform calculations.
VectorF mVelocity
Velocity.
SFXSource * mWaterBreathSound
Sound for underwater breath.
F32 mWeaponBackFraction
Amount to slide the weapon back (if it's up against something)
struct Player::ActionAnimation mActionAnimation
struct Player::ArmAnimation mArmAnimation
TSThread * mArmThread
TSThread * mHeadVThread
TSThread * mHeadHThread
TSThread * mRecoilThread
TSThread * mImageStateThread
Protected Attributes inherited from ShapeBase
ShapeBase * mControllingObject
Controlling object.
F32 mDamageFlash
ShapeBaseData * mDataBlock
Datablock.
bool mFlipFadeVal
bool mIsAiControlled
Is this object AI controlled?
F32 mLastRenderDistance
U32 mLastRenderFrame
ShapeBase * mShapeBaseMount
bool mTrigger [MaxTriggerKeys]
What triggers are set, if any.
F32 mWhiteOut
Sound mSoundThread [MaxSoundThreads]
Thread mScriptThread [MaxScriptThreads]
bool mMoveMotion
Indicates that a Move has come in requesting x, y or z motion.
MountedImage mMountedImageList [MaxMountedImages]
TSShapeInstance * mShapeInstance
Convex * mConvexList
NetStringHandle mSkinNameHandle
String mAppliedSkinName
NetStringHandle mShapeNameHandle
Name sent to client.
S32 mAiPose
Current pose.
F32 mEnergy
Current enery level.
F32 mRechargeRate
Energy recharge rate (in units/tick).
F32 mMass
Mass.
F32 mOneOverMass
Inverse of mass.
F32 mDrag
Drag.
F32 mBuoyancy
Buoyancy factor.
String mLiquidType
Type of liquid (if any) we are in.
F32 mLiquidHeight
Height of liquid around us (from 0..1).
F32 mWaterCoverage
Percent of this object covered by water.
Point3F mAppliedForce
F32 mGravityMod
F32 mDamage
F32 mRepairRate
F32 mRepairReserve
DamageState mDamageState
TSThread * mDamageThread
TSThread * mHulkThread
VectorF damageDir
bool mCloaked
F32 mCloakLevel
bool mFadeOut
bool mFading
F32 mFadeVal
F32 mFadeElapsedTime
F32 mFadeTime
F32 mFadeDelay
F32 mCameraFov
The camera vertical FOV in degrees.
bool mIsControlled
Client side controlled flag.
BitVector mMeshHidden
A bit vector of the meshes forced to be hidden.
Protected Attributes inherited from GameBase
F32 mCameraFov
WaterObject * mCurrentWaterObject
The WaterObject we are currently within.
Protected Attributes inherited from SceneObject
SimObjectPtr< SceneObject > mAfterObject
Object which must be ticked before this object.
SceneObjectLightingPlugin * mLightPlugin
SceneObjectLightingPlugin attached to this object.
BitSet32 mObjectFlags
Combination of SceneObjectFlags.
SceneManager * mSceneManager
SceneManager to which this SceneObject belongs.
SceneObjectLink * mSceneObjectLinks
Links installed by SceneTrackers attached to this object.
U32 mTypeMask
Object type mask.
bool mZoneRefDirty
If an object moves, its zoning state needs to be updated.
U32 mNumCurrZones
Number of zones this object is assigned to.
ZoneRef * mZoneRefHead
List of zones that this object is part of.
MountInfo mMount
SimPersistID * mMountPID
MatrixF mObjToWorld
Transform from object space to world space.
MatrixF mWorldToObj
Transform from world space to object space (inverse).
Point3F mObjScale
Object scale.
Box3F mObjBox
Bounding box in object space.
Box3F mWorldBox
Bounding box (AABB) in world space.
SphereF mWorldSphere
Bounding sphere in world space.
MatrixF mRenderObjToWorld
Render matrix to transform object space to world space.
MatrixF mRenderWorldToObj
Render matrix to transform world space to object space.
Box3F mRenderWorldBox
Render bounding box in world space.
SphereF mRenderWorldSphere
Render bounding sphere in world space.
bool mGlobalBounds
Whether this object is considered to have an infinite bounding box.
S32 mCollisionCount
SceneContainer * mContainer
Container database that the object is assigned to.
U32 mContainerSeqKey
SceneContainer sequence key.
SceneObjectRef * mBinRefHead
U32 mBinMinX
U32 mBinMaxX
U32 mBinMinY
U32 mBinMaxY
Protected Attributes inherited from NetObject
SimObjectPtr< NetObject > mClientObject
Pointer to the client object on a local connection.
GhostInfo * mFirstObjectRef
Head of a linked list storing GhostInfos referencing this NetObject.
BitSet32 mNetFlags
Flag values from NetFlags.
U32 mNetIndex
The index of this ghost in the GhostManager on the server.
SimObjectPtr< NetObject > mServerObject
Pointer to the server object on a local connection.
Protected Attributes inherited from SimSet
void * mMutex
SetModificationSignal mSetModificationSignal
Signal that is triggered when objects are added or removed from the set.
SimObjectList objectList
Protected Attributes inherited from SimObject
DEFINE_CREATE_METHOD
SimObjectId mId
Id number for this object.
StringTableEntry mInternalName
Internal name assigned to the object. Not set by default.
return object
bool mCanSaveFieldDictionary
Whether dynamic fields should be saved out in serialization. Defaults to true.
SimPersistID * mPersistentId
Persistent ID assigned to this object.
Namespace * mNameSpace
The namespace in which method lookup for this object begins.
StringTableEntry mClassName
Name of namespace to use as class namespace.
StringTableEntry mSuperClassName
Name of namespace to use as class super namespace.
Protected Attributes inherited from EngineObject
DEFINE_CREATE_METHOD
return object
Protected Attributes inherited from StrongRefBase
U32 mRefCount
reference counter for StrongRefPtr objects
Static Protected Attributes inherited from Player
static F32 mGravity
Gravity.
Static Protected Attributes inherited from SimObject
static SimObjectId smForcedId
The Id to force upon the object. Poor object.
static bool smForceId
Force a registered object to use the given Id. Cleared upon use.
Member Enumeration Documentation
enum AIPlayer::MoveState
Enumerator
ModeStop
ModeMove
ModeStuck
ModeSlowing
Constructor & Destructor Documentation
AIPlayer::AIPlayer ()
AIPlayer::~AIPlayer ()
Member Function Documentation
bool AIPlayer::checkInFoV (GameBase * target = NULL, F32 camFov = 45.0f, bool _checkEnabled = false)
Referenced by getAimLocation().
bool AIPlayer::checkInLos (GameBase * target = NULL, bool _useMuzzle = false, bool _checkEnabled = false)
Referenced by getAimLocation().
void AIPlayer::clearAim ()
Referenced by getAimLocation().
void AIPlayer::clearCover ()
Stop searching for cover.
void AIPlayer::clearFollow ()
Stop following me!
void AIPlayer::clearMoveTriggers ()
Referenced by getMoveDestination().
void AIPlayer::clearPath ()
Clear out the current path.
AIPlayer::DECLARE_CONOBJECT (AIPlayer)
Point3F AIPlayer::getAimLocation () const inline
References checkInFoV(), checkInLos(), clearAim(), getMuzzleVector(), getTargetDistance(), and setMoveSpeed().
GameBase* AIPlayer::getAimObject () const inline
References setAimLocation().
virtual bool AIPlayer::getAIMove (Move * move) virtual
Reimplemented from Player.
S32 AIPlayer::getAiPose ()
Referenced by getMoveDestination().
Point3F AIPlayer::getMoveDestination () const inline
References clearMoveTriggers(), getAiPose(), getMoveTrigger(), setAiPose(), setMoveTrigger(), SimSet::size(), and stopMove().
F32 AIPlayer::getMoveSpeed () const inline
References setMoveTolerance().
F32 AIPlayer::getMoveTolerance () const inline
References setMoveDestination().
bool AIPlayer::getMoveTrigger (U32 slot) const
Referenced by getMoveDestination().
void AIPlayer::getMuzzleVector (U32 imageSlot, VectorF * vec) virtual
Gets the muzzle vector of a specified slot.
Parameters
imageSlot Image slot to check transform for
vec Muzzle vector (out)
Reimplemented from Player.
Referenced by getAimLocation().
F32 AIPlayer::getTargetDistance (GameBase * target, bool _checkEnabled)
Referenced by getAimLocation().
static void AIPlayer::initPersistFields () static
bool AIPlayer::onAdd () virtual
Called when the object is added to the sim.
Reimplemented from SceneObject.
virtual void AIPlayer::onReachDestination () protected virtual
void AIPlayer::onRemove () virtual
Called when the object is removed from the sim.
Reimplemented from SceneObject.
virtual void AIPlayer::onStuck () protected virtual
void AIPlayer::setAimLocation (const Point3F & location)
Referenced by getAimObject().
void AIPlayer::setAimObject (GameBase * targetObject)
void AIPlayer::setAimObject (GameBase * targetObject, const Point3F & offset)
void AIPlayer::setAiPose (S32 pose)
Referenced by getMoveDestination().
void AIPlayer::setMoveDestination (const Point3F & location, bool slowdown)
Referenced by getMoveTolerance().
void AIPlayer::setMoveSpeed (const F32 speed)
Referenced by getAimLocation().
void AIPlayer::setMoveTolerance (const F32 tolerance)
Referenced by getMoveSpeed().
void AIPlayer::setMoveTrigger (U32 slot, const bool isSet = true)
Referenced by getMoveDestination().
void AIPlayer::stopMove ()
Referenced by getMoveDestination().
virtual void AIPlayer::updateMove (const Move * move) virtual
Update the movement.
Reimplemented from Player.
Copyright © GarageGames, LLC. All Rights Reserved.