SFXSoundscape Class Reference
Main Modules Class List Namespace List Online
SFXSoundscape Class Reference
An instance of an SFXAmbience on the soundscape mixer stack.
#include <sfx/sfxSoundscape.h>
Public Types
enum DirtyBits : U32 {
AmbienceDirty = BIT(0),
AllDirty = 0xFFFFFFFF
}
enum Flags {
FlagOverridden = BIT(0),
FlagUnique = BIT(1)
}
typedef void Parent
Public Member Functions
SFXSoundscape (SFXAmbience *ambience)
Create a soundscape associated with the given ambient space.
SFXAmbience * getAmbience () const
Return the ambient space associated with this soundscape.
void setAmbience (SFXAmbience *ambience)
Set the ambient space associated with this soundscape.
Protected Member Functions
bool _isOverridden () const
Return true if another soundscape lower down the stack is using the same ambient space as this soundscape.
bool _isUnique () const
Return true if this soundscape is the only soundscape using the assigned ambient space.
Protected Attributes
SFXAmbience * mAmbience
The ambient space assigned to this soundscape.
BitSet32 mDirtyBits
BitSet32 mFlags
SimObjectPtr< SFXSource > mSource
The current soundtrack playing in this soundscape.
SFXState * mStates [SFXAmbience::MaxStates]
States activated by this soundscape.
Detailed Description
An instance of an SFXAmbience on the soundscape mixer stack.
Member Typedef Documentation
typedef void SFXSoundscape::Parent
Member Enumeration Documentation
enum SFXSoundscape::DirtyBits : U32
Enumerator
AmbienceDirty
Associated ambience has changed.
AllDirty
enum SFXSoundscape::Flags
Enumerator
FlagOverridden
Same ambience is pushed lower down onto the stack.
FlagUnique
No other instance of this ambience on stack.
Constructor & Destructor Documentation
SFXSoundscape::SFXSoundscape (SFXAmbience * ambience)
Create a soundscape associated with the given ambient space.
Referenced by _isUnique().
Member Function Documentation
bool SFXSoundscape::_isOverridden () const inline protected
Return true if another soundscape lower down the stack is using the same ambient space as this soundscape.
References FlagOverridden, and BitSet32::test().
bool SFXSoundscape::_isUnique () const inline protected
Return true if this soundscape is the only soundscape using the assigned ambient space.
References FlagUnique, SFXSoundscape(), and BitSet32::test().
SFXAmbience* SFXSoundscape::getAmbience () const inline
Return the ambient space associated with this soundscape.
References mAmbience, and setAmbience().
void SFXSoundscape::setAmbience (SFXAmbience * ambience)
Set the ambient space associated with this soundscape.
Triggers corresponding recomputations on the next soundscape manager update.
Referenced by getAmbience(), and SFXWorld< NUM_DIMENSIONS, Object >::notifyChanged().
Member Data Documentation
SFXAmbience* SFXSoundscape::mAmbience protected
The ambient space assigned to this soundscape.
Referenced by getAmbience().
BitSet32 SFXSoundscape::mDirtyBits protected
BitSet32 SFXSoundscape::mFlags protected
SimObjectPtr< SFXSource > SFXSoundscape::mSource protected
The current soundtrack playing in this soundscape.
This is either the ambient track or the surround sound track depending on whether
SFXState* SFXSoundscape::mStates[SFXAmbience::MaxStates] protected
States activated by this soundscape.
Copyright © GarageGames, LLC. All Rights Reserved.