SimObjectRef< T > Class Template Reference
Main Modules Class List Namespace List Online
SimObjectRef< T > Class Template Reference
#include <console/simObjectRef.h>
Public Member Functions
SimObjectRef ()
operator T * ()
T * operator-> ()
SimObjectRef< T > & operator= (U32 id)
SimObjectRef< T > & operator= (const char *name)
Static Public Attributes
static S32 _smTypeId = 0
Protected Member Functions
T * _get ()
void _set (U32 id)
void _set (const char *name)
Protected Attributes
U32 mId
StringTableEntry mName
T * mObject
Constructor & Destructor Documentation
template<class T> SimObjectRef< T >::SimObjectRef () inline
Member Function Documentation
template<class T > T * SimObjectRef< T >::_get () protected
References Sim::findObject(), SimObjectRef< T >::mId, SimObjectRef< T >::mName, and SimObjectRef< T >::mObject.
Referenced by SimObjectRef< T >::operator T *(), SimObjectRef< PhysicsDebrisData >::operator->(), and SimObjectRef< PhysicsDebrisData >::operator=().
template<class T > void SimObjectRef< T >::_set (U32 id) protected
References SimObjectRef< T >::mId, SimObjectRef< T >::mName, and SimObjectRef< T >::mObject.
Referenced by SimObjectRef< PhysicsDebrisData >::operator=().
template<class T > void SimObjectRef< T >::_set (const char * name) protected
References SimObjectRef< T >::mId, SimObjectRef< T >::mName, and SimObjectRef< T >::mObject.
template<class T> SimObjectRef< T >::operator T * () inline
References SimObjectRef< T >::_get().
template<class T> T* SimObjectRef< T >::operator-> (void) inline
template<class T> SimObjectRef<T>& SimObjectRef< T >::operator= (U32 id) inline
template<class T> SimObjectRef<T>& SimObjectRef< T >::operator= (const char * name) inline
Member Data Documentation
template<class T> S32 SimObjectRef< T >::_smTypeId = 0 static
template<class T> U32 SimObjectRef< T >::mId protected
Referenced by SimObjectRef< T >::_get(), and SimObjectRef< T >::_set().
template<class T> StringTableEntry SimObjectRef< T >::mName protected
Referenced by SimObjectRef< T >::_get(), and SimObjectRef< T >::_set().
template<class T> T* SimObjectRef< T >::mObject protected
Referenced by SimObjectRef< T >::_get(), and SimObjectRef< T >::_set().
Copyright © GarageGames, LLC. All Rights Reserved.