FactoryCache< T > Class Template Reference
Main Modules Class List Namespace List Online
FactoryCache< T > Class Template Reference
#include <core/factoryCache.h>
Public Member Functions
FactoryCache ()
virtual ~FactoryCache ()
void cacheObject (T *pObject)
T * createObject (void)
void purgeCache (void)
Constructor & Destructor Documentation
template<class T> FactoryCache< T >::FactoryCache () inline
template<class T> virtual FactoryCache< T >::~FactoryCache () inline virtual
Member Function Documentation
template<class T> void FactoryCache< T >::cacheObject (T * pObject) inline
References IFactoryObjectReset::resetState().
Referenced by TamlCustomNodes::addNode(), TamlCustomNode::getIgnoreEmpty(), TamlCustomNode::removeNode(), TamlCustomNodes::removeNode(), TamlCustomNode::resetState(), and TamlCustomNodes::resetState().
template<class T> T* FactoryCache< T >::createObject (void) inline
References T.
Referenced by TamlCustomNode::addField(), TamlCustomNode::addNode(), TamlCustomNodes::addNode(), and TamlCustomNode::getIgnoreEmpty().
template<class T> void FactoryCache< T >::purgeCache (void) inline
Copyright © GarageGames, LLC. All Rights Reserved.