ColladaExtension Class Reference
Main Modules Class List Namespace List Online
ColladaExtension Class Reference
#include <ts/collada/colladaExtensions.h>
Public Member Functions
ColladaExtension ()
virtual ~ColladaExtension ()
Protected Member Functions
template<class T >
const domTechnique * findExtraTechnique (const T *element, const char *name) const
Find the technique with the named profile.
const domTechnique * findExtraTechnique (const domCommon_color_or_texture_type_complexType::domTexture *element, const char *name) const
The <texture> element does not define an extra_array, so need a specialized version of the template.
const domAny * findParam (const char *name)
Find the parameter with the given name.
template<typename T >
void get (const char *name, T &value, T defaultVal)
Get the value of the named parameter (use defaultVal if parameter not found)
template<typename T >
void get (const char *name, AnimatedElement< T > &value, T defaultVal)
Get the value of the named animated parameter (use defaultVal if parameter not found)
Protected Attributes
const domTechnique * pTechnique
Constructor & Destructor Documentation
ColladaExtension::ColladaExtension () inline
virtual ColladaExtension::~ColladaExtension () inline virtual
Member Function Documentation
template<class T > const domTechnique* ColladaExtension::findExtraTechnique (const T * element, const char * name) const inline protected
Find the technique with the named profile.
Referenced by ColladaExtension_animation_clip::ColladaExtension_animation_clip(), ColladaExtension_effect::ColladaExtension_effect(), ColladaExtension_geometry::ColladaExtension_geometry(), and ColladaExtension_node::ColladaExtension_node().
const domTechnique* ColladaExtension::findExtraTechnique (const domCommon_color_or_texture_type_complexType::domTexture * element, const char * name) const inline protected
The <texture> element does not define an extra_array, so need a specialized version of the template.
const domAny* ColladaExtension::findParam (const char * name) inline protected
Find the parameter with the given name.
Referenced by get().
template<typename T > void ColladaExtension::get (const char * name, T & value, T defaultVal) inline protected
Get the value of the named parameter (use defaultVal if parameter not found)
References findParam().
template<typename T > void ColladaExtension::get (const char * name, AnimatedElement< T > & value, T defaultVal) inline protected
Get the value of the named animated parameter (use defaultVal if parameter not found)
References findParam().
Member Data Documentation
const domTechnique* ColladaExtension::pTechnique protected
Referenced by ColladaExtension_animation_clip::ColladaExtension_animation_clip(), ColladaExtension_effect::ColladaExtension_effect(), ColladaExtension_geometry::ColladaExtension_geometry(), and ColladaExtension_node::ColladaExtension_node().
Copyright © GarageGames, LLC. All Rights Reserved.