fxShapeReplicator::tagFieldData Class Reference
Main Modules Class List Namespace List Online
fxShapeReplicator::tagFieldData Class Reference
#include <T3D/fx/fxShapeReplicator.h>
Public Member Functions
tagFieldData ()
Public Attributes
bool mAlignToTerrain
S32 mAllowedTerrainSlope
bool mAllowOnTerrain
bool mAllowOnWater
bool mAllowStatics
bool mAllowWaterSurface
bool mHideReplications
U32 mInnerRadiusX
U32 mInnerRadiusY
bool mInteractions
S32 mOffsetZ
U32 mOuterRadiusX
U32 mOuterRadiusY
ColorF mPlaceAreaColour
U32 mPlacementBandHeight
U32 mSeed
U32 mShapeCount
StringTableEntry mShapeFile
U32 mShapeRetries
Point3F mShapeRotateMax
Point3F mShapeRotateMin
Point3F mShapeScaleMax
Point3F mShapeScaleMin
bool mShowPlacementArea
Point3F mTerrainAlignment
Constructor & Destructor Documentation
fxShapeReplicator::tagFieldData::tagFieldData () inline
References fxShapeReplicatedStatic::DECLARE_CONOBJECT(), ColorF::set(), and Point3F::set().
Member Data Documentation
bool fxShapeReplicator::tagFieldData::mAlignToTerrain
S32 fxShapeReplicator::tagFieldData::mAllowedTerrainSlope
bool fxShapeReplicator::tagFieldData::mAllowOnTerrain
bool fxShapeReplicator::tagFieldData::mAllowOnWater
bool fxShapeReplicator::tagFieldData::mAllowStatics
bool fxShapeReplicator::tagFieldData::mAllowWaterSurface
bool fxShapeReplicator::tagFieldData::mHideReplications
U32 fxShapeReplicator::tagFieldData::mInnerRadiusX
U32 fxShapeReplicator::tagFieldData::mInnerRadiusY
bool fxShapeReplicator::tagFieldData::mInteractions
S32 fxShapeReplicator::tagFieldData::mOffsetZ
U32 fxShapeReplicator::tagFieldData::mOuterRadiusX
U32 fxShapeReplicator::tagFieldData::mOuterRadiusY
ColorF fxShapeReplicator::tagFieldData::mPlaceAreaColour
U32 fxShapeReplicator::tagFieldData::mPlacementBandHeight
U32 fxShapeReplicator::tagFieldData::mSeed
U32 fxShapeReplicator::tagFieldData::mShapeCount
StringTableEntry fxShapeReplicator::tagFieldData::mShapeFile
U32 fxShapeReplicator::tagFieldData::mShapeRetries
Point3F fxShapeReplicator::tagFieldData::mShapeRotateMax
Point3F fxShapeReplicator::tagFieldData::mShapeRotateMin
Point3F fxShapeReplicator::tagFieldData::mShapeScaleMax
Point3F fxShapeReplicator::tagFieldData::mShapeScaleMin
bool fxShapeReplicator::tagFieldData::mShowPlacementArea
Point3F fxShapeReplicator::tagFieldData::mTerrainAlignment
Copyright © GarageGames, LLC. All Rights Reserved.