DecalDataFile Class Reference
Main Modules Class List Namespace List Online
DecalDataFile Class Reference
This is the data file for decals.
#include <T3D/decal/decalDataFile.h>
Public Member Functions
DecalDataFile ()
virtual ~DecalDataFile ()
void clear ()
Deletes all the data and resets the file to an empty state.
Vector< DecalSphere * > & getSphereList ()
const Vector< DecalSphere * > & getSphereList () const
bool isDirty () const
Return true if the decal data has been modified since the last save or load.
I/O
bool write (Stream &stream)
Write the decal data to the given stream.
bool read (Stream &stream)
Read the decal data from the given stream.
Decal Management
DecalInstance * addDecal (const Point3F &pos, const Point3F &normal, const Point3F &tangent, DecalData *decalData, F32 decalScale, S32 decalTexIndex, U8 flags)
Create a new decal in this file using the given data.
void removeDecal (DecalInstance *inst)
Remove a decal from the file.
void notifyDecalModified (DecalInstance *inst)
Let the file know that the data of the given decal has changed.
Protected Types
enum { FILE_VERSION = 5 }
Protected Attributes
bool mIsDirty
Set to true if the file is dirty and needs to be saved before being destroyed.
Memory Management
FreeListChunker< DecalInstance > mChunker
Allocator for DecalInstances.
DecalInstance * _allocateInstance ()
Allocate a new, uninitialized DecalInstance.
void _freeInstance (DecalInstance *decal)
Free the memory of the given DecalInstance.
Instance Management
DecalSphere * mSphereWithLastInsertion
The decal sphere that we have last insert an item into.
Vector< DecalSphere * > mSphereList
List of bounding sphere shapes that contain and organize DecalInstances for optimized culling and lookup.
void _addDecalToSpheres (DecalInstance *inst)
Add the given decal to the sphere list.
bool _removeDecalFromSpheres (DecalInstance *inst)
Remove the decal from the sphere list.
Detailed Description
This is the data file for decals.
Not intended to be used directly, do your work with decals via the DecalManager.
Member Enumeration Documentation
anonymous enum protected
Enumerator
FILE_VERSION
Constructor & Destructor Documentation
DecalDataFile::DecalDataFile ()
virtual DecalDataFile::~DecalDataFile () virtual
Member Function Documentation
void DecalDataFile::_addDecalToSpheres (DecalInstance * inst) protected
Add the given decal to the sphere list.
DecalInstance* DecalDataFile::_allocateInstance () inline protected
Allocate a new, uninitialized DecalInstance.
References FreeListChunker< T >::alloc().
void DecalDataFile::_freeInstance (DecalInstance * decal) inline protected
Free the memory of the given DecalInstance.
References FreeListChunker< T >::free().
bool DecalDataFile::_removeDecalFromSpheres (DecalInstance * inst) protected
Remove the decal from the sphere list.
DecalInstance* DecalDataFile::addDecal (const Point3F & pos, const Point3F & normal, const Point3F & tangent, DecalData * decalData, F32 decalScale, S32 decalTexIndex, U8 flags)
Create a new decal in this file using the given data.
Referenced by isDirty().
void DecalDataFile::clear ()
Deletes all the data and resets the file to an empty state.
Referenced by isDirty().
Vector< DecalSphere* >& DecalDataFile::getSphereList () inline
References mSphereList.
const Vector< DecalSphere* >& DecalDataFile::getSphereList () const inline
References mSphereList.
bool DecalDataFile::isDirty () const inline
Return true if the decal data has been modified since the last save or load.
References addDecal(), clear(), mIsDirty, notifyDecalModified(), read(), removeDecal(), and write().
void DecalDataFile::notifyDecalModified (DecalInstance * inst)
Let the file know that the data of the given decal has changed.
Referenced by isDirty().
bool DecalDataFile::read (Stream & stream)
Read the decal data from the given stream.
Referenced by isDirty().
void DecalDataFile::removeDecal (DecalInstance * inst)
Remove a decal from the file.
Referenced by isDirty().
bool DecalDataFile::write (Stream & stream)
Write the decal data to the given stream.
Referenced by isDirty().
Member Data Documentation
FreeListChunker< DecalInstance > DecalDataFile::mChunker protected
Allocator for DecalInstances.
bool DecalDataFile::mIsDirty protected
Set to true if the file is dirty and needs to be saved before being destroyed.
Referenced by isDirty().
Vector< DecalSphere* > DecalDataFile::mSphereList protected
List of bounding sphere shapes that contain and organize DecalInstances for optimized culling and lookup.
Referenced by getSphereList().
DecalSphere* DecalDataFile::mSphereWithLastInsertion protected
The decal sphere that we have last insert an item into.
This sphere is most likely to be a good candidate for the next insertion so test this sphere first.
Copyright © GarageGames, LLC. All Rights Reserved.