TerrCell Class Reference
Main Modules Class List Namespace List Online
TerrCell Class Reference
The TerrCell is a single quadrant of the terrain geometry quadtree.
#include <terrain/terrCell.h>
Public Member Functions
TerrCell ()
virtual ~TerrCell ()
void cullCells (const SceneRenderState *state, const Point3F &objLodPos, Vector< TerrCell * > *outCells)
void deleteMaterials ()
Deletes the materials for this cell and all its children.
const Box3F & getBounds () const
F32 getDistanceTo (const Point3F &pt) const
TerrainCellMaterial * getMaterial ()
U64 getMaterials () const
Point2I getPoint () const
void getRenderPrimitive (GFXPrimitive *prim, GFXVertexBufferHandleBase *vertBuff, GFXPrimitiveBufferHandle *primBuff) const
U32 getSize () const
SphereF getSphereBounds () const
Returns the object space sphere bounds.
F32 getSqDistanceTo (const Point3F &pt) const
const BitVector & getZoneOverlap () const
Returns a bit vector of what zones overlap this cell.
bool isLeaf () const
Return true if this is a leaf cell, i.e. a cell without children.
void preloadMaterials ()
Forces the loading of the materials for this cell and all its child cells.
void updateGrid (const RectI &gridRect, bool opacityOnly=false)
void updateOBBs ()
Update the world-space OBBs used for culling.
void updateZoning (const SceneZoneSpaceManager *zoneManager)
void renderBounds () const
Debug Rendering.
Static Public Member Functions
static void createPrimBuffer (GFXPrimitiveBufferHandle *primBuffer)
Initializes a primitive buffer for rendering any cell.
static TerrCell * init (TerrainBlock *terrain)
Protected Member Functions
void _init (TerrainBlock *terrain, const Point2I &point, U32 size, U32 level)
bool _isVertIndexEmpty (U32 index) const
void _updateBounds ()
void _updateMaterials ()
void _updateOBB ()
Update mOBB from the current terrain transform state.
void _updatePrimitiveBuffer ()
void _updateVertexBuffer ()
Protected Attributes
Box3F mBounds
The bounding box of this cell in TerrainBlock object space.
TerrCell * mChildren [4]
The child cells of this one.
Vector< U32 > mEmptyVertexList
A list of all empty vertices for this cell.
bool mHasEmpty
Indicates if this cell has any empty squares.
bool mIsInteriorOnly
Whether this cell is fully contained inside interior zones.
U32 mLevel
The level of this cell within the quadtree (of cells) where zero is the root and one is a direct child of the root, etc.
TerrainCellMaterial * mMaterial
The material used to render the cell.
U64 mMaterials
This bit flag tells us which materials effect this cell and is used for optimizing rendering.
OrientedBox3F mOBB
The OBB of this cell in world space.
Point2I mPoint
GFXPrimitiveBufferHandle mPrimBuffer
The handle to the static primitive buffer for this cell.
F32 mRadius
The bounding radius of this cell.
U32 mSize
TerrainBlock * mTerrain
The terrain this cell is based on.
U32 mTriCount
Triangle count for our own primitive buffer, if any.
GFXVertexBufferHandle< TerrVertex > mVertexBuffer
The handle to the static vertex buffer which holds the vertices for this cell.
BitVector mZoneOverlap
The zone overlap for this cell.
Static Protected Attributes
static const U32 smMinCellSize
static const U32 smPBSize
static const U32 smTriCount
static const U32 smVBSize
static const U32 smVBStride
Statics used in VB and PB generation.
Detailed Description
The TerrCell is a single quadrant of the terrain geometry quadtree.
Constructor & Destructor Documentation
TerrCell::TerrCell ()
virtual TerrCell::~TerrCell () virtual
Member Function Documentation
void TerrCell::_init (TerrainBlock * terrain, const Point2I & point, U32 size, U32 level) protected
bool TerrCell::_isVertIndexEmpty (U32 index) const inline protected
References mEmptyVertexList, and Vector< T >::size().
void TerrCell::_updateBounds () protected
void TerrCell::_updateMaterials () protected
void TerrCell::_updateOBB () protected
Update mOBB from the current terrain transform state.
void TerrCell::_updatePrimitiveBuffer () protected
void TerrCell::_updateVertexBuffer () protected
static void TerrCell::createPrimBuffer (GFXPrimitiveBufferHandle * primBuffer) static
Initializes a primitive buffer for rendering any cell.
Referenced by getPoint().
void TerrCell::cullCells (const SceneRenderState * state, const Point3F & objLodPos, Vector< TerrCell * > * outCells)
void TerrCell::deleteMaterials ()
Deletes the materials for this cell and all its children.
They will be recreate on the next request.
Referenced by isLeaf().
const Box3F& TerrCell::getBounds () const inline
References mBounds.
F32 TerrCell::getDistanceTo (const Point3F & pt) const inline
References Box3F::getCenter(), mBounds, and mRadius.
Referenced by getSphereBounds().
TerrainCellMaterial* TerrCell::getMaterial ()
Referenced by getZoneOverlap().
U64 TerrCell::getMaterials () const inline
References mMaterials.
Point2I TerrCell::getPoint () const inline
References createPrimBuffer(), mPoint, and renderBounds().
void TerrCell::getRenderPrimitive (GFXPrimitive * prim, GFXVertexBufferHandleBase * vertBuff, GFXPrimitiveBufferHandle * primBuff) const
U32 TerrCell::getSize () const inline
References mSize.
SphereF TerrCell::getSphereBounds () const inline
Returns the object space sphere bounds.
References Box3F::getCenter(), getDistanceTo(), getSqDistanceTo(), and mRadius.
F32 TerrCell::getSqDistanceTo (const Point3F & pt) const
Referenced by getSphereBounds().
const BitVector& TerrCell::getZoneOverlap () const inline
Returns a bit vector of what zones overlap this cell.
References getMaterial(), mZoneOverlap, and preloadMaterials().
static TerrCell* TerrCell::init (TerrainBlock * terrain) static
bool TerrCell::isLeaf () const inline
Return true if this is a leaf cell, i.e. a cell without children.
References deleteMaterials().
void TerrCell::preloadMaterials ()
Forces the loading of the materials for this cell and all its child cells.
Referenced by getZoneOverlap().
void TerrCell::renderBounds () const
Debug Rendering.
Renders the debug bounds for this cell.
Referenced by getPoint().
void TerrCell::updateGrid (const RectI & gridRect, bool opacityOnly = false)
void TerrCell::updateOBBs ()
Update the world-space OBBs used for culling.
void TerrCell::updateZoning (const SceneZoneSpaceManager * zoneManager)
Member Data Documentation
Box3F TerrCell::mBounds protected
The bounding box of this cell in TerrainBlock object space.
Referenced by getBounds(), and getDistanceTo().
TerrCell* TerrCell::mChildren[4] protected
The child cells of this one.
Vector<U32> TerrCell::mEmptyVertexList protected
A list of all empty vertices for this cell.
Referenced by _isVertIndexEmpty().
bool TerrCell::mHasEmpty protected
Indicates if this cell has any empty squares.
bool TerrCell::mIsInteriorOnly protected
Whether this cell is fully contained inside interior zones.
U32 TerrCell::mLevel protected
The level of this cell within the quadtree (of cells) where zero is the root and one is a direct child of the root, etc.
TerrainCellMaterial* TerrCell::mMaterial protected
The material used to render the cell.
U64 TerrCell::mMaterials protected
This bit flag tells us which materials effect this cell and is used for optimizing rendering.
See also
TerrainFile::mMaterialAlphaMap
Referenced by getMaterials().
OrientedBox3F TerrCell::mOBB protected
The OBB of this cell in world space.
Point2I TerrCell::mPoint protected
Referenced by getPoint().
GFXPrimitiveBufferHandle TerrCell::mPrimBuffer protected
The handle to the static primitive buffer for this cell.
It is only used if this cell has any empty squares
F32 TerrCell::mRadius protected
The bounding radius of this cell.
Referenced by getDistanceTo(), and getSphereBounds().
U32 TerrCell::mSize protected
Referenced by getSize().
TerrainBlock* TerrCell::mTerrain protected
The terrain this cell is based on.
U32 TerrCell::mTriCount protected
Triangle count for our own primitive buffer, if any.
GFXVertexBufferHandle<TerrVertex> TerrCell::mVertexBuffer protected
The handle to the static vertex buffer which holds the vertices for this cell.
BitVector TerrCell::mZoneOverlap protected
The zone overlap for this cell.
Note
The bit for the outdoor zone is never set.
Referenced by getZoneOverlap().
const U32 TerrCell::smMinCellSize static protected
const U32 TerrCell::smPBSize static protected
const U32 TerrCell::smTriCount static protected
const U32 TerrCell::smVBSize static protected
const U32 TerrCell::smVBStride static protected
Statics used in VB and PB generation.
Copyright © GarageGames, LLC. All Rights Reserved.