BaseMatInstance Class Reference
Main Modules Class List Namespace List Online
BaseMatInstance Class Reference abstract
#include <materials/baseMatInstance.h>
Public Member Functions
virtual ~BaseMatInstance ()
virtual void addShaderMacro (const String &name, const String &value)=0
Adds a shader macro which will be passed to the shader during initialization.
virtual void addStateBlockDesc (const GFXStateBlockDesc &desc)=0
Adds this stateblock to the base state block used during initialization.
virtual MaterialParameters * allocMaterialParameters ()=0
Get a MaterialParameters block for this BaseMatInstance, caller is responsible for freeing it.
virtual void dumpShaderInfo () const =0
virtual U32 getCurPass ()=0
virtual U32 getCurStageNum ()=0
virtual const FeatureSet & getFeatures () const =0
Returns the active features in use by this material.
MatFeaturesDelegate & getFeaturesDelegate ()
virtual BaseMaterialDefinition * getMaterial ()=0
Returns the material this instance is based on.
virtual MaterialParameterHandle * getMaterialParameterHandle (const String &name)=0
Returns a MaterialParameterHandle for name.
virtual MaterialParameters * getMaterialParameters ()=0
Get the current parameters for this BaseMatInstance (BaseMatInstances are created with a default active MaterialParameters which is managed by BaseMatInstance.
virtual RenderPassData * getPass (U32 pass)=0
virtual const FeatureSet & getRequestedFeatures () const =0
Returns the features that were requested at material creation time which may differ from the active features.
virtual const MatStateHint & getStateHint () const =0
Returns the state hint which can be used for sorting and fast comparisions of the equality of a material instance.
virtual SimObject * getUserObject () const =0
virtual const GFXStateBlockDesc & getUserStateBlock () const =0
virtual const GFXVertexFormat * getVertexFormat () const =0
virtual bool hasAccumulation ()=0
virtual bool hasGlow ()=0
bool hasNormalMap () const
Fast test for use of normal maps in this material.
virtual bool init (const FeatureSet &features, const GFXVertexFormat *vertexFormat)=0
virtual bool isCustomMaterial () const =0
Returns true if this MatInstance is built from a CustomMaterial.
virtual bool isForwardLit () const =0
Returns true if the material is forward lit and requires a list of lights which affect it when rendering.
virtual bool isInstanced () const =0
Returns true if this material is instanced.
bool isValid ()
Returns true if init has been successfully called.
virtual bool reInit ()=0
Reinitializes the material using the previous initialization parameters.
virtual void setBuffers (GFXVertexBufferHandleBase *vertBuffer, GFXPrimitiveBufferHandle *primBuffer)=0
Sets the vertex and primitive buffers as well as the instancing stream buffer for the current material if the material is instanced.
virtual void setMaterialParameters (MaterialParameters *param)=0
Set the current parameters for this BaseMatInstance.
virtual void setNodeTransforms (const MatrixF *address, const U32 numTransforms)=0
Sets node transforms for the current stage. Used for hardware skinning.
virtual void setSceneInfo (SceneRenderState *state, const SceneData &sgData)=0
This initializes various material scene state settings and should be called after setupPass() within the pass loop.
virtual void setTextureStages (SceneRenderState *, const SceneData &sgData)=0
This is normally called from within setupPass() automatically, so its unnecessary to do so manually unless a texture stage has changed.
virtual void setTransforms (const MatrixSet &matrixSet, SceneRenderState *state)=0
This initializes the material transforms and should be called after setupPass() within the pass loop.
virtual bool setupPass (SceneRenderState *state, const SceneData &sgData)=0
Sets up the next rendering pass for this material.
virtual void setUserObject (SimObject *userObject)=0
Sets a SimObject which will passed into ShaderFeature::createConstHandles.
virtual bool stepInstance ()=0
Used to increment the instance buffer for this material.
virtual void updateStateBlocks ()=0
Updates the state blocks for this material.
bool usesHardwareSkinning () const
Material Hook functions
void addHook (MatInstanceHook *hook)
template<class HOOK >
HOOK * getHook ()
Helper function for getting a hook.
MatInstanceHook * getHook (const MatInstanceHookType &type) const
void deleteHook (const MatInstanceHookType &type)
U32 deleteAllHooks ()
Protected Attributes
MatFeaturesDelegate mFeaturesDelegate
bool mHasNormalMaps
This is set by initialization and used by the prepass.
Vector< MatInstanceHook * > mHooks
The array of active material hooks indexed by a MatInstanceHookType.
bool mIsValid
Should be true if init has been called and it succeeded.
bool mUsesHardwareSkinning
This material makes use of bone transforms.
Constructor & Destructor Documentation
virtual BaseMatInstance::~BaseMatInstance () virtual
Member Function Documentation
void BaseMatInstance::addHook (MatInstanceHook * hook)
Referenced by getFeaturesDelegate(), and RenderPrePassMgr::getPrePassMaterial().
virtual void BaseMatInstance::addShaderMacro (const String & name, const String & value) pure virtual
Adds a shader macro which will be passed to the shader during initialization.
See also
init
Implemented in MatInstance.
Referenced by isValid().
virtual void BaseMatInstance::addStateBlockDesc (const GFXStateBlockDesc & desc) pure virtual
Adds this stateblock to the base state block used during initialization.
See also
init
Implemented in MatInstance.
Referenced by isValid().
virtual MaterialParameters* BaseMatInstance::allocMaterialParameters () pure virtual
Get a MaterialParameters block for this BaseMatInstance, caller is responsible for freeing it.
Implemented in MatInstance.
Referenced by isValid().
U32 BaseMatInstance::deleteAllHooks ()
Referenced by getHook().
void BaseMatInstance::deleteHook (const MatInstanceHookType & type)
Referenced by getHook().
virtual void BaseMatInstance::dumpShaderInfo () const pure virtual
Implemented in MatInstance.
Referenced by isValid().
virtual U32 BaseMatInstance::getCurPass () pure virtual
Implemented in MatInstance.
Referenced by isValid().
virtual U32 BaseMatInstance::getCurStageNum () pure virtual
Implemented in MatInstance.
Referenced by isValid().
virtual const FeatureSet& BaseMatInstance::getFeatures () const pure virtual
Returns the active features in use by this material.
See also
getRequestedFeatures
Implemented in MatInstance.
Referenced by isValid().
MatFeaturesDelegate& BaseMatInstance::getFeaturesDelegate () inline
References addHook(), isCustomMaterial(), and mFeaturesDelegate.
template<class HOOK > HOOK* BaseMatInstance::getHook () inline
Helper function for getting a hook.
See also
getHook
References deleteAllHooks(), deleteHook(), getHook(), and getUserStateBlock().
Referenced by getHook(), and RenderPrePassMgr::getPrePassMaterial().
MatInstanceHook* BaseMatInstance::getHook (const MatInstanceHookType & type) const
virtual BaseMaterialDefinition* BaseMatInstance::getMaterial () pure virtual
Returns the material this instance is based on.
Implemented in MatInstance.
Referenced by isValid().
virtual MaterialParameterHandle* BaseMatInstance::getMaterialParameterHandle (const String & name) pure virtual
Returns a MaterialParameterHandle for name.
Implemented in MatInstance.
Referenced by isValid().
virtual MaterialParameters* BaseMatInstance::getMaterialParameters () pure virtual
Get the current parameters for this BaseMatInstance (BaseMatInstances are created with a default active MaterialParameters which is managed by BaseMatInstance.
Implemented in MatInstance.
Referenced by isValid().
virtual RenderPassData* BaseMatInstance::getPass (U32 pass) pure virtual
Implemented in MatInstance.
Referenced by isValid().
virtual const FeatureSet& BaseMatInstance::getRequestedFeatures () const pure virtual
Returns the features that were requested at material creation time which may differ from the active features.
See also
getFeatures
Implemented in MatInstance.
Referenced by isValid().
virtual const MatStateHint& BaseMatInstance::getStateHint () const pure virtual
Returns the state hint which can be used for sorting and fast comparisions of the equality of a material instance.
Implemented in MatInstance.
Referenced by isValid(), and RenderBinManager::newPassNeeded().
virtual SimObject* BaseMatInstance::getUserObject () const pure virtual
Implemented in MatInstance.
Referenced by isValid().
virtual const GFXStateBlockDesc& BaseMatInstance::getUserStateBlock () const pure virtual
Implemented in MatInstance.
Referenced by getHook().
virtual const GFXVertexFormat* BaseMatInstance::getVertexFormat () const pure virtual
Implemented in MatInstance.
Referenced by isValid().
virtual bool BaseMatInstance::hasAccumulation () pure virtual
Implemented in MatInstance.
Referenced by isValid().
virtual bool BaseMatInstance::hasGlow () pure virtual
Implemented in MatInstance.
Referenced by isValid().
bool BaseMatInstance::hasNormalMap () const inline
Fast test for use of normal maps in this material.
References mHasNormalMaps.
virtual bool BaseMatInstance::init (const FeatureSet & features, const GFXVertexFormat * vertexFormat) pure virtual
Parameters
features The features you want to allow for this material.
vertexFormat The vertex format on which this material will be rendered.
See also
GFXVertexFormat
FeatureSet
Implemented in PrePassMatInstance, LightMatInstance, and MatInstance.
virtual bool BaseMatInstance::isCustomMaterial () const pure virtual
Returns true if this MatInstance is built from a CustomMaterial.
Implemented in MatInstance.
Referenced by getFeaturesDelegate().
virtual bool BaseMatInstance::isForwardLit () const pure virtual
Returns true if the material is forward lit and requires a list of lights which affect it when rendering.
Implemented in MatInstance.
Referenced by isValid().
virtual bool BaseMatInstance::isInstanced () const pure virtual
Returns true if this material is instanced.
Implemented in MatInstance.
Referenced by isValid().
bool BaseMatInstance::isValid () inline
Returns true if init has been successfully called.
It is up to the derived class to set this value properly.
References addShaderMacro(), addStateBlockDesc(), allocMaterialParameters(), dumpShaderInfo(), getCurPass(), getCurStageNum(), getFeatures(), getMaterial(), getMaterialParameterHandle(), getMaterialParameters(), getPass(), getRequestedFeatures(), getStateHint(), getUserObject(), getVertexFormat(), hasAccumulation(), hasGlow(), isForwardLit(), isInstanced(), mIsValid, setBuffers(), setMaterialParameters(), setNodeTransforms(), setSceneInfo(), setTextureStages(), setTransforms(), setupPass(), setUserObject(), stepInstance(), and updateStateBlocks().
virtual bool BaseMatInstance::reInit () pure virtual
Reinitializes the material using the previous initialization parameters.
See also
init
Implemented in MatInstance.
virtual void BaseMatInstance::setBuffers (GFXVertexBufferHandleBase * vertBuffer, GFXPrimitiveBufferHandle * primBuffer) pure virtual
Sets the vertex and primitive buffers as well as the instancing stream buffer for the current material if the material is instanced.
Implemented in MatInstance.
Referenced by isValid().
virtual void BaseMatInstance::setMaterialParameters (MaterialParameters * param) pure virtual
Set the current parameters for this BaseMatInstance.
Implemented in MatInstance.
Referenced by isValid().
virtual void BaseMatInstance::setNodeTransforms (const MatrixF * address, const U32 numTransforms) pure virtual
Sets node transforms for the current stage. Used for hardware skinning.
Implemented in MatInstance.
Referenced by isValid().
virtual void BaseMatInstance::setSceneInfo (SceneRenderState * state, const SceneData & sgData) pure virtual
This initializes various material scene state settings and should be called after setupPass() within the pass loop.
See also
setupPass
Implemented in MatInstance.
Referenced by isValid().
virtual void BaseMatInstance::setTextureStages (SceneRenderState * , const SceneData & sgData) pure virtual
This is normally called from within setupPass() automatically, so its unnecessary to do so manually unless a texture stage has changed.
If so it should be called after setupPass() within the pass loop.
See also
setupPass
Implemented in MatInstance.
Referenced by isValid().
virtual void BaseMatInstance::setTransforms (const MatrixSet & matrixSet, SceneRenderState * state) pure virtual
This initializes the material transforms and should be called after setupPass() within the pass loop.
See also
setupPass
Implemented in MatInstance.
Referenced by isValid().
virtual bool BaseMatInstance::setupPass (SceneRenderState * state, const SceneData & sgData) pure virtual
Sets up the next rendering pass for this material.
It is typically called like so...
while(mat->setupPass(state, sgData))
{
   mat->setTransforms(...);
   mat->setSceneInfo(...);
   ...
   GFX->drawPrimitive();
}
Implemented in LightMatInstance, MatInstance, ShadowMatInstance, and ReflectionMatInstance.
Referenced by isValid().
virtual void BaseMatInstance::setUserObject (SimObject * userObject) pure virtual
Sets a SimObject which will passed into ShaderFeature::createConstHandles.
Normal features do not make use of this, it is for special class specific or user designed features.
Implemented in MatInstance.
Referenced by isValid().
virtual bool BaseMatInstance::stepInstance () pure virtual
Used to increment the instance buffer for this material.
Implemented in MatInstance.
Referenced by isValid().
virtual void BaseMatInstance::updateStateBlocks () pure virtual
Updates the state blocks for this material.
Implemented in MatInstance.
Referenced by isValid().
bool BaseMatInstance::usesHardwareSkinning () const inline
References mUsesHardwareSkinning.
Member Data Documentation
MatFeaturesDelegate BaseMatInstance::mFeaturesDelegate protected
Referenced by getFeaturesDelegate().
bool BaseMatInstance::mHasNormalMaps protected
This is set by initialization and used by the prepass.
Referenced by hasNormalMap().
Vector<MatInstanceHook*> BaseMatInstance::mHooks protected
The array of active material hooks indexed by a MatInstanceHookType.
bool BaseMatInstance::mIsValid protected
Should be true if init has been called and it succeeded.
It is up to the derived class to set this variable appropriately.
Referenced by isValid().
bool BaseMatInstance::mUsesHardwareSkinning protected
This material makes use of bone transforms.
Referenced by usesHardwareSkinning().
Copyright © GarageGames, LLC. All Rights Reserved.