GFXTransformSaver Class Reference
Main Modules Class List Namespace List Online
GFXTransformSaver Class Reference
Helper class to store viewport and matrix stack state, and restore it later.
#include <gfx/gfxTransformSaver.h>
Public Member Functions
GFXTransformSaver (bool saveDataNow=true, bool restoreDataOnDestruct=true)
Constructor - controls how data is saved.
~GFXTransformSaver ()
const MatrixF & getProjectionMatrix () const
Returns the saved projection matrix.
const MatrixF & getViewMatrix () const
Returns the saved projection matrix.
const RectI & getViewport () const
Returns the saved viewport.
void restore ()
void save ()
Protected Attributes
bool mHaveSavedData
bool mRestoreSavedDataOnDestruct
MatrixF mSavedProjectionMatrix
MatrixF mSavedViewMatrix
RectI mSavedViewport
Detailed Description
Helper class to store viewport and matrix stack state, and restore it later.
When doing complex out-of-scene rendering, for instance, doing a render to texture operation that needs its own transform state, it is very easy to nuke important rendering state, like the viewport or the projection matrix stored in vertex shader constant zero.
This class simplifies save and cleanup of those properties. You can either treat it as a stack helper, e.g.
void myFunc()
{
   GFXTransformSaver saver;
   // Lots of nasty render state changes...
   // Everything is magically cleaned up when saver is destructed!
}
Or you can manually control when you do saves or restores:
void myFunc()
{
   GFXTransformSaver saver(false, false);
   if(!somePrecondition)
      return false;     // Note early out.
   saver.save();
   // Lots of nasty render state changes...
   // If we had passed (false, true) to the constructor then it would
   // clean up automagically for us; but we want to do it manually.
   saver.restore();
}
Constructor & Destructor Documentation
GFXTransformSaver::GFXTransformSaver (bool saveDataNow = true, bool restoreDataOnDestruct = true) inline
Constructor - controls how data is saved.
Parameters
saveDataNow If true, indicates that saveData() should be called immediately. Otherwise, you can do it manually.
restoreDataOnDestruct If true, indicates that restoreData() should be called on destruct. Otherwise, you'll have to do it manually.
References save().
GFXTransformSaver::~GFXTransformSaver () inline
References restore().
Member Function Documentation
const MatrixF& GFXTransformSaver::getProjectionMatrix () const inline
Returns the saved projection matrix.
References mSavedProjectionMatrix.
const MatrixF& GFXTransformSaver::getViewMatrix () const inline
Returns the saved projection matrix.
References mSavedViewMatrix.
const RectI& GFXTransformSaver::getViewport () const inline
Returns the saved viewport.
References mSavedViewport.
void GFXTransformSaver::restore () inline
Referenced by ~GFXTransformSaver().
void GFXTransformSaver::save () inline
Referenced by GFXTransformSaver().
Member Data Documentation
bool GFXTransformSaver::mHaveSavedData protected
bool GFXTransformSaver::mRestoreSavedDataOnDestruct protected
MatrixF GFXTransformSaver::mSavedProjectionMatrix protected
Referenced by getProjectionMatrix().
MatrixF GFXTransformSaver::mSavedViewMatrix protected
Referenced by getViewMatrix().
RectI GFXTransformSaver::mSavedViewport protected
Referenced by getViewport().
Copyright © GarageGames, LLC. All Rights Reserved.