GenericConstBuffer Class Reference
Main Modules Class List Namespace List Online
GenericConstBuffer Class Reference
This class manages shader constant data in a system memory buffer.
#include <gfx/genericConstBuffer.h>
Public Member Functions
GenericConstBuffer (GenericConstBufferLayout *layout)
~GenericConstBuffer ()
Set shader constant values
Actually set shader constant values
Parameters
name Name of the constant, this should be a name contained in the array returned in getShaderConstDesc, if an invalid name is used, its ignored, but it's not an error.
GenericConstBufferLayout * mLayout
The buffer layout.
U8 * mBuffer
The pointer to the contant store or NULL if the layout is empty.
U32 mDirtyStart
The byte offset to the start of the dirty range within the buffer or U32_MAX if the buffer is not dirty.
U32 mDirtyEnd
The btye offset to the end of the dirty range within the buffer or 0 if the buffer is not dirty.
Vector< bool > mWasAssigned
A vector used to keep track if a constant has beed assigned a value or not.
void set (const GenericConstBufferLayout::ParamDesc &pd, const F32 f)
void set (const GenericConstBufferLayout::ParamDesc &pd, const Point2F &fv)
void set (const GenericConstBufferLayout::ParamDesc &pd, const Point3F &fv)
void set (const GenericConstBufferLayout::ParamDesc &pd, const Point4F &fv)
void set (const GenericConstBufferLayout::ParamDesc &pd, const PlaneF &fv)
void set (const GenericConstBufferLayout::ParamDesc &pd, const ColorF &fv)
void set (const GenericConstBufferLayout::ParamDesc &pd, const S32 f)
void set (const GenericConstBufferLayout::ParamDesc &pd, const Point2I &fv)
void set (const GenericConstBufferLayout::ParamDesc &pd, const Point3I &fv)
void set (const GenericConstBufferLayout::ParamDesc &pd, const Point4I &fv)
void set (const GenericConstBufferLayout::ParamDesc &pd, const AlignedArray< F32 > &fv)
void set (const GenericConstBufferLayout::ParamDesc &pd, const AlignedArray< Point2F > &fv)
void set (const GenericConstBufferLayout::ParamDesc &pd, const AlignedArray< Point3F > &fv)
void set (const GenericConstBufferLayout::ParamDesc &pd, const AlignedArray< Point4F > &fv)
void set (const GenericConstBufferLayout::ParamDesc &pd, const AlignedArray< S32 > &fv)
void set (const GenericConstBufferLayout::ParamDesc &pd, const AlignedArray< Point2I > &fv)
void set (const GenericConstBufferLayout::ParamDesc &pd, const AlignedArray< Point3I > &fv)
void set (const GenericConstBufferLayout::ParamDesc &pd, const AlignedArray< Point4I > &fv)
void set (const GenericConstBufferLayout::ParamDesc &pd, const MatrixF &mat, const GFXShaderConstType matrixType)
void set (const GenericConstBufferLayout::ParamDesc &pd, const MatrixF *mat, const U32 arraySize, const GFXShaderConstType matrixType)
const U8 * getDirtyBuffer (U32 *start, U32 *size)
Gets the dirty buffer range and clears the dirty state at the same time.
const U8 * getEntireBuffer ()
Gets the entire buffer ignoring dirty range.
void setDirty (bool dirty)
Sets the entire buffer as dirty or clears the dirty state.
bool isDirty () const
Returns true if the buffer has been modified since the last call to getDirtyBuffer or setDirty.
bool isEqual (const GenericConstBuffer *buffer) const
Returns true if have the same layout and hold the same data as the input buffer.
GenericConstBufferLayout * getLayout () const
Returns our layout object.
void assertUnassignedConstants (const char *shaderName)
Helper function used to assert on unset constants.
const U8 * getBuffer () const
Returns a pointer to the raw buffer.
void internalSet (const GenericConstBufferLayout::ParamDesc &pd, const GFXShaderConstType constType, const U32 size, const void *data)
Called by the inlined set functions above to do the real dirty work of copying the data to the right location within the buffer.
Detailed Description
This class manages shader constant data in a system memory buffer.
It is used by device specific classes for batching together many constant changes which are then copied to the device thru a single API call.
See also
GenericConstBufferLayout
Constructor & Destructor Documentation
GenericConstBuffer::GenericConstBuffer (GenericConstBufferLayout * layout)
GenericConstBuffer::~GenericConstBuffer ()
Member Function Documentation
void GenericConstBuffer::assertUnassignedConstants (const char * shaderName)
Helper function used to assert on unset constants.
const U8* GenericConstBuffer::getBuffer () const inline protected
Returns a pointer to the raw buffer.
References GenericConstBufferLayout::ParamDesc::constType.
Referenced by isEqual().
const U8 * GenericConstBuffer::getDirtyBuffer (U32 * start, U32 * size) inline
Gets the dirty buffer range and clears the dirty state at the same time.
const U8 * GenericConstBuffer::getEntireBuffer () inline
Gets the entire buffer ignoring dirty range.
GenericConstBufferLayout* GenericConstBuffer::getLayout () const inline
Returns our layout object.
void GenericConstBuffer::internalSet (const GenericConstBufferLayout::ParamDesc & pd, const GFXShaderConstType constType, const U32 size, const void * data) inline protected
Called by the inlined set functions above to do the real dirty work of copying the data to the right location within the buffer.
References GenericConstBufferLayout::ParamDesc::index, GenericConstBufferLayout::ParamDesc::offset, and GenericConstBufferLayout::ParamDesc::size.
bool GenericConstBuffer::isDirty () const inline
Returns true if the buffer has been modified since the last call to getDirtyBuffer or setDirty.
The buffer is not dirty on initial creation.
See also
getDirtyBuffer
setDirty
bool GenericConstBuffer::isEqual (const GenericConstBuffer * buffer) const inline
Returns true if have the same layout and hold the same data as the input buffer.
References dMemcmp(), getBuffer(), GenericConstBufferLayout::getBufferSize(), and mLayout.
void GenericConstBuffer::set (const GenericConstBufferLayout::ParamDesc & pd, const F32 f) inline
void GenericConstBuffer::set (const GenericConstBufferLayout::ParamDesc & pd, const Point2F & fv) inline
void GenericConstBuffer::set (const GenericConstBufferLayout::ParamDesc & pd, const Point3F & fv) inline
void GenericConstBuffer::set (const GenericConstBufferLayout::ParamDesc & pd, const Point4F & fv) inline
void GenericConstBuffer::set (const GenericConstBufferLayout::ParamDesc & pd, const PlaneF & fv) inline
void GenericConstBuffer::set (const GenericConstBufferLayout::ParamDesc & pd, const ColorF & fv) inline
void GenericConstBuffer::set (const GenericConstBufferLayout::ParamDesc & pd, const S32 f) inline
void GenericConstBuffer::set (const GenericConstBufferLayout::ParamDesc & pd, const Point2I & fv) inline
void GenericConstBuffer::set (const GenericConstBufferLayout::ParamDesc & pd, const Point3I & fv) inline
void GenericConstBuffer::set (const GenericConstBufferLayout::ParamDesc & pd, const Point4I & fv) inline
void GenericConstBuffer::set (const GenericConstBufferLayout::ParamDesc & pd, const AlignedArray< F32 > & fv) inline
void GenericConstBuffer::set (const GenericConstBufferLayout::ParamDesc & pd, const AlignedArray< Point2F > & fv) inline
void GenericConstBuffer::set (const GenericConstBufferLayout::ParamDesc & pd, const AlignedArray< Point3F > & fv) inline
void GenericConstBuffer::set (const GenericConstBufferLayout::ParamDesc & pd, const AlignedArray< Point4F > & fv) inline
void GenericConstBuffer::set (const GenericConstBufferLayout::ParamDesc & pd, const AlignedArray< S32 > & fv) inline
void GenericConstBuffer::set (const GenericConstBufferLayout::ParamDesc & pd, const AlignedArray< Point2I > & fv) inline
void GenericConstBuffer::set (const GenericConstBufferLayout::ParamDesc & pd, const AlignedArray< Point3I > & fv) inline
void GenericConstBuffer::set (const GenericConstBufferLayout::ParamDesc & pd, const AlignedArray< Point4I > & fv) inline
void GenericConstBuffer::set (const GenericConstBufferLayout::ParamDesc & pd, const MatrixF & mat, const GFXShaderConstType matrixType) inline
void GenericConstBuffer::set (const GenericConstBufferLayout::ParamDesc & pd, const MatrixF * mat, const U32 arraySize, const GFXShaderConstType matrixType) inline
References GenericConstBufferLayout::ParamDesc::size.
void GenericConstBuffer::setDirty (bool dirty) inline
Sets the entire buffer as dirty or clears the dirty state.
Member Data Documentation
U8* GenericConstBuffer::mBuffer protected
The pointer to the contant store or NULL if the layout is empty.
U32 GenericConstBuffer::mDirtyEnd protected
The btye offset to the end of the dirty range within the buffer or 0 if the buffer is not dirty.
U32 GenericConstBuffer::mDirtyStart protected
The byte offset to the start of the dirty range within the buffer or U32_MAX if the buffer is not dirty.
GenericConstBufferLayout* GenericConstBuffer::mLayout protected
The buffer layout.
Referenced by isEqual().
Vector<bool> GenericConstBuffer::mWasAssigned protected
A vector used to keep track if a constant has beed assigned a value or not.
See also
assertUnassignedConstants
Copyright © GarageGames, LLC. All Rights Reserved.