StateMachine Class Reference
Main Modules Class List Namespace List Online
StateMachine Class Reference
#include <T3D/components/game/stateMachine.h>
Classes
struct State
struct StateField
struct StateTransition
struct UniqueReference
Public Member Functions
StateMachine ()
virtual ~StateMachine ()
void checkTransitions (const char *slotName, const char *newValue)
S32 findFieldByName (const char *name)
State & getCurrentState ()
const char * getCurrentStateName ()
StateField getField (U32 index)
S32 getFieldsCount ()
const char * getStateByIndex (S32 index)
State & getStateByName (const char *name)
S32 getStateCount ()
void loadStateMachineFile ()
bool passComparitorCheck (const char *var, StateTransition::Condition transitionRule)
void readConditions (StateTransition &newTransition)
bool readFieldComparitor (StateTransition::Condition *condition, SimXMLDocument *reader)
bool readFieldName (StateField *newField, SimXMLDocument *reader)
bool readFieldValue (StateField *field, SimXMLDocument *reader)
bool readStateName (State *state, SimXMLDocument *reader)
void readStates ()
bool readStateScriptFunction (State *state, SimXMLDocument *reader)
void readTransitions (State &currentState)
bool readTransitonTarget (StateTransition *transition, SimXMLDocument *reader)
void setState (const char *stateName, bool clearFields=true)
void update ()
Public Attributes
StringTableEntry mStateMachineFile
Signal< void(StateMachine *, S32 stateIdx) > onStateChanged
Protected Attributes
State * mCurCreateState
State * mCurCreateSuperState
State mCurrentState
Vector< StateField > mFields
StringTableEntry mStartingState
Vector< State > mStates
F32 mStateStartTime
F32 mStateTime
Vector< UniqueReference > mUniqueReferences
SimObjectPtr< SimXMLDocument > mXMLReader
Constructor & Destructor Documentation
StateMachine::StateMachine ()
virtual StateMachine::~StateMachine () virtual
Member Function Documentation
void StateMachine::checkTransitions (const char * slotName, const char * newValue)
Referenced by getStateCount().
S32 StateMachine::findFieldByName (const char * name)
Referenced by getStateCount().
State& StateMachine::getCurrentState () inline
References mCurrentState.
const char* StateMachine::getCurrentStateName () inline
References StateMachine::State::stateName.
StateField StateMachine::getField (U32 index) inline
References Vector< T >::size().
S32 StateMachine::getFieldsCount () inline
References Vector< T >::size().
const char* StateMachine::getStateByIndex (S32 index)
Referenced by getStateCount().
State& StateMachine::getStateByName (const char * name)
Referenced by getStateCount().
S32 StateMachine::getStateCount () inline
References checkTransitions(), findFieldByName(), getStateByIndex(), getStateByName(), StateMachine::StateField::name, passComparitorCheck(), and Vector< T >::size().
void StateMachine::loadStateMachineFile ()
bool StateMachine::passComparitorCheck (const char * var, StateTransition::Condition transitionRule)
Referenced by getStateCount().
void StateMachine::readConditions (StateTransition & newTransition)
bool StateMachine::readFieldComparitor (StateTransition::Condition * condition, SimXMLDocument * reader) inline
References SimXMLDocument::getData(), SimXMLDocument::popElement(), SimXMLDocument::pushFirstChildElement(), and StateMachine::StateTransition::Condition::triggerComparitor.
bool StateMachine::readFieldName (StateField * newField, SimXMLDocument * reader) inline
References SimXMLDocument::getData(), StateMachine::StateField::name, SimXMLDocument::popElement(), and SimXMLDocument::pushFirstChildElement().
bool StateMachine::readFieldValue (StateField * field, SimXMLDocument * reader) inline
References StateMachine::StateField::BooleanType, dAtob(), dAtof(), StateMachine::StateField::fieldType, SimXMLDocument::getData(), StateMachine::StateField::NumberType, SimXMLDocument::popElement(), SimXMLDocument::pushFirstChildElement(), StateMachine::StateField::StringType, StateMachine::StateField::triggerBoolVal, StateMachine::StateField::triggerNumVal, and StateMachine::StateField::triggerStringVal.
bool StateMachine::readStateName (State * state, SimXMLDocument * reader) inline
References SimXMLDocument::getData(), SimXMLDocument::popElement(), SimXMLDocument::pushFirstChildElement(), and StateMachine::State::stateName.
void StateMachine::readStates ()
bool StateMachine::readStateScriptFunction (State * state, SimXMLDocument * reader) inline
References StateMachine::State::callbackName, SimXMLDocument::getData(), SimXMLDocument::popElement(), and SimXMLDocument::pushFirstChildElement().
void StateMachine::readTransitions (State & currentState)
bool StateMachine::readTransitonTarget (StateTransition * transition, SimXMLDocument * reader) inline
References SimXMLDocument::getData(), StateMachine::StateTransition::mStateTarget, SimXMLDocument::popElement(), and SimXMLDocument::pushFirstChildElement().
void StateMachine::setState (const char * stateName, bool clearFields = true)
void StateMachine::update ()
Member Data Documentation
State* StateMachine::mCurCreateState protected
State* StateMachine::mCurCreateSuperState protected
State StateMachine::mCurrentState protected
Referenced by getCurrentState().
Vector<StateField> StateMachine::mFields protected
StringTableEntry StateMachine::mStartingState protected
StringTableEntry StateMachine::mStateMachineFile
Vector<State> StateMachine::mStates protected
F32 StateMachine::mStateStartTime protected
F32 StateMachine::mStateTime protected
Vector<UniqueReference> StateMachine::mUniqueReferences protected
SimObjectPtr<SimXMLDocument> StateMachine::mXMLReader protected
Signal< void(StateMachine*, S32 stateIdx) > StateMachine::onStateChanged
Copyright © GarageGames, LLC. All Rights Reserved.