ZipSubWStream Class Reference
Main Modules Class List Namespace List Online
ZipSubWStream Class Reference
#include <core/util/zip/zipSubStream.h>
Public Member Functions
ZipSubWStream ()
virtual ~ZipSubWStream ()
bool attachStream (Stream *io_pSlaveStream)
void detachStream ()
virtual U32 getLastBytesRead ()
virtual U32 getLastBytesWritten ()
U32 getPosition () const
Gets the position in the stream.
Stream * getStream ()
U32 getStreamSize ()
Gets the size of the stream.
bool hasCapability (const Capability) const
Checks to see if this stream has the capability of a given function.
bool setPosition (const U32 in_newPosition)
Sets the position of the stream. Returns if the new position is valid or not.
Public Member Functions inherited from FilterStream
virtual ~FilterStream ()
Public Member Functions inherited from Stream
Stream ()
virtual ~Stream ()
virtual Stream * clone () const
Create an exact replica of this stream.
bool copyFrom (Stream *other)
Copy the contents of another stream into this one.
Stream::StreamStatus getStatus () const
Gets the status of the stream.
bool Put (char character)
void read (String *str)
bool read (ColorI *)
Read an integral color from the stream.
bool read (ColorF *)
Read a floating point color from the stream.
bool read (NetAddress *)
Read a network address from the stream.
bool read (NetSocket *)
Read a network socket from the stream.
bool read (RawData *)
Read some raw data from the stream.
bool read (Torque::ByteBuffer *)
Read some raw data from the stream.
bool read (const U32 in_numBytes, void *out_pBuffer)
bool read (bool *out_pRead)
void readLine (U8 *buffer, U32 bufferSize)
Reads a line from the stream.
void readLongString (U32 maxStringLen, char *stringBuf)
Reads a string that could potentially be more than 255 characters long.
virtual void readString (char stringBuf[256])
Reads a string of maximum 255 characters long.
const char * readSTString (bool casesens=false)
Reads a string and inserts it into the StringTable.
void write (const String &str)
bool write (const ColorI &)
Write an integral color to the stream.
bool write (const ColorF &)
Write a floating point color to the stream.
bool write (const NetAddress &)
Write a network address to the stream.
bool write (const NetSocket &)
Write a network socket to the stream.
bool write (const RawData &)
Write some raw data onto the stream.
bool write (const Torque::ByteBuffer &)
Write some raw data onto the stream.
bool write (const U32 in_numBytes, const void *in_pBuffer)
bool write (const bool &in_rWrite)
bool writeFormattedBuffer (const char *format,...)
Writes a formatted buffer to the stream.
void writeLine (const U8 *buffer)
writes a line to the stream
void writeLongString (U32 maxStringLen, const char *string)
Writes a string to the stream.
virtual void writeString (const char *stringBuf, S32 maxLen=255)
Writes a string to the stream.
bool writeStringBuffer (const char *buffer)
Writes a NULL terminated string buffer.
void writeTabs (U32 count)
Write a number of tabs to this stream.
void writeText (const char *text)
Write raw text to the stream.
Public Member Functions inherited from IStreamByteCount
virtual ~IStreamByteCount ()
Protected Member Functions
bool _read (const U32 in_numBytes, void *out_pBuffer)
bool _write (const U32 in_numBytes, const void *in_pBuffer)
Protected Member Functions inherited from Stream
virtual void _read (String *str)
virtual void _write (const String &str)
void setStatus (const StreamStatus in_newStatus)
Additional Inherited Members
Public Types inherited from Stream
enum Capability {
StreamWrite = BIT(0),
StreamRead = BIT(1),
StreamPosition = BIT(2)
}
enum StreamStatus {
Ok = 0,
IOError,
EOS,
IllegalCall,
Closed,
UnknownError
}
Status constants for the stream.
Static Public Member Functions inherited from Stream
static const char * getStatusString (const StreamStatus in_status)
Gets a printable string form of the status.
Constructor & Destructor Documentation
ZipSubWStream::ZipSubWStream ()
virtual ZipSubWStream::~ZipSubWStream () virtual
Member Function Documentation
bool ZipSubWStream::_read (const U32 in_numBytes, void * out_pBuffer) protected virtual
Reimplemented from FilterStream.
bool ZipSubWStream::_write (const U32 in_numBytes, const void * in_pBuffer) protected virtual
Reimplemented from FilterStream.
bool ZipSubWStream::attachStream (Stream * io_pSlaveStream) virtual
Implements FilterStream.
void ZipSubWStream::detachStream () virtual
Implements FilterStream.
virtual U32 ZipSubWStream::getLastBytesRead () inline virtual
Implements IStreamByteCount.
virtual U32 ZipSubWStream::getLastBytesWritten () inline virtual
Implements IStreamByteCount.
References ZipSubRStream::_read(), FilterStream::_write(), ZipSubRStream::attachStream(), ZipSubRStream::detachStream(), ZipSubRStream::getPosition(), ZipSubRStream::getStream(), ZipSubRStream::getStreamSize(), ZipSubRStream::hasCapability(), and ZipSubRStream::setPosition().
U32 ZipSubWStream::getPosition () const virtual
Gets the position in the stream.
Reimplemented from FilterStream.
Stream* ZipSubWStream::getStream () virtual
Implements FilterStream.
U32 ZipSubWStream::getStreamSize () virtual
Gets the size of the stream.
Reimplemented from FilterStream.
bool ZipSubWStream::hasCapability (const Capability caps) const virtual
Checks to see if this stream has the capability of a given function.
Reimplemented from FilterStream.
bool ZipSubWStream::setPosition (const U32 in_newPosition) virtual
Sets the position of the stream. Returns if the new position is valid or not.
Reimplemented from FilterStream.
Copyright © GarageGames, LLC. All Rights Reserved.