CRC Namespace Reference
Main Modules Class List Namespace List Online
CRC Namespace Reference
Functions
U32 calculateCRC (const void *buffer, S32 len, U32 crcVal=INITIAL_CRC_VALUE)
U32 calculateCRCStream (Stream *stream, U32 crcVal=INITIAL_CRC_VALUE)
Variables
const U32 CRC_POSTCOND_VALUE = 0xFFFFFFFF
Value XORd with the CRC to post condition it (ones complement)
const U32 INITIAL_CRC_VALUE = 0xFFFFFFFF
Initial value for CRCs.
const U32 INVALID_CRC = 0xFFFFFFFF
An invalid CRC.
Function Documentation
U32 CRC::calculateCRC (const void * buffer, S32 len, U32 crcVal = INITIAL_CRC_VALUE)
Referenced by Zip::ZipStatFilter::_read(), Zip::ZipStatFilter::_write(), and InfiniteBitStream::getCRC().
U32 CRC::calculateCRCStream (Stream * stream, U32 crcVal = INITIAL_CRC_VALUE)
Variable Documentation
const U32 CRC::CRC_POSTCOND_VALUE = 0xFFFFFFFF
Value XORd with the CRC to post condition it (ones complement)
Referenced by Zip::ZipStatFilter::detachStream().
const U32 CRC::INITIAL_CRC_VALUE = 0xFFFFFFFF
Initial value for CRCs.
Referenced by Zip::ZipStatFilter::attachStream().
const U32 CRC::INVALID_CRC = 0xFFFFFFFF
An invalid CRC.
Copyright © GarageGames, LLC. All Rights Reserved.