FrustumData Struct Reference
Main Modules Class List Namespace List Online
FrustumData Struct Reference
Polyhedron data for use by frustums.
#include <math/util/frustum.h>
Public Types
enum { EdgeCount = 12 }
enum {
PlaneLeft,
PlaneRight,
PlaneNear,
PlaneFar,
PlaneTop,
PlaneBottom,
PlaneCount
}
Indices for the planes in a frustum.
enum : U32 {
PlaneMaskLeft = (1 << PlaneLeft),
PlaneMaskRight = (1 << PlaneRight),
PlaneMaskTop = (1 << PlaneTop),
PlaneMaskBottom = (1 << PlaneBottom),
PlaneMaskNear = (1 << PlaneNear),
PlaneMaskFar = (1 << PlaneFar),
PlaneMaskAll = 0xFFFFFFFF
}
Used to mask out planes for testing.
enum CornerPoints {
NearTopLeft,
NearTopRight,
NearBottomLeft,
NearBottomRight,
FarTopLeft,
FarTopRight,
FarBottomLeft,
FarBottomRight,
CornerPointCount
}
Indices for the corner points of the frustum.
typedef FixedSizeVector< Edge, EdgeCount > EdgeListType
enum PlaneCenters {
PlaneLeftCenter,
PlaneRightCenter,
PlaneTopCenter,
PlaneBottomCenter,
PlaneNearCenter,
PlaneFarCenter
}
Indices for the center points of the frustum planes.
typedef FixedSizeVector< PlaneF, PlaneCount > PlaneListType
typedef FixedSizeVector< Point3F, CornerPointCount > PointListType
Public Types inherited from PolyhedronData
typedef Edge EdgeType
typedef PlaneF PlaneType
typedef Point3F PointType
Public Member Functions
operator AnyPolyhedron () const
Protected Member Functions
FrustumData ()
void _update () const
Update the point and plane data from the current frustum settings.
Protected Attributes
F32 mFarDist
bool mIsInverted
Whether the frustum is inverted, i.e.
bool mIsOrtho
Determines whether this Frustum is orthographic or perspective.
F32 mNearBottom
F32 mNearDist
F32 mNearLeft
The size of the near plane used to generate the frustum points and planes.
F32 mNearRight
F32 mNearTop
Point3F mPosition
Camera position extracted from tarnsform.
MatrixF mTransform
Used to transform the frustum points from camera space into the desired clipping space.
Lazily Updated Data
bool mDirty
When true, points, planes and bounds must be re-calculated before use.
PlaneListType mPlanes
PointListType mPoints
Point3F mPlaneCenters [PlaneCount]
The center points of the individual faces of the frustum.
Box3F mBounds
The clipping-space axis-aligned bounding box which contains the extents of the frustum.
Static Protected Attributes
static EdgeListType smEdges
Static edge list.
Accessors
static U32 getNumPlanes ()
Return the number of planes that a frustum has.
static U32 getNumPoints ()
Return the number of corner points that a frustum has.
static U32 getNumEdges ()
Return the number of edges that a frustum has.
static const Edge * getEdges ()
Return the edge definitions for a frustum.
const PlaneF * getPlanes () const
Return the planes that make up the polyhedron.
const Point3F * getPoints () const
Additional Inherited Members
Static Public Member Functions inherited from PolyhedronData
template<typename Polyhedron >
static void buildBoxData (Polyhedron &poly, const MatrixF &mat, const Box3F &box, bool invertNormals=false)
Detailed Description
Polyhedron data for use by frustums.
Uses fixed-size vectors and a static vector for the edge list as that never changes between frustums.
Member Typedef Documentation
typedef FixedSizeVector< Edge, EdgeCount > FrustumData::EdgeListType
typedef FixedSizeVector< PlaneF, PlaneCount > FrustumData::PlaneListType
typedef FixedSizeVector< Point3F, CornerPointCount > FrustumData::PointListType
Member Enumeration Documentation
anonymous enum
Enumerator
EdgeCount
anonymous enum
Indices for the planes in a frustum.
Note the planes are ordered left, right, near, far, top, bottom for getting early rejections from the typical horizontal scene.
Enumerator
PlaneLeft
PlaneRight
PlaneNear
PlaneFar
PlaneTop
PlaneBottom
PlaneCount
The total number of frustum planes.
anonymous enum : U32
Used to mask out planes for testing.
Enumerator
PlaneMaskLeft
PlaneMaskRight
PlaneMaskTop
PlaneMaskBottom
PlaneMaskNear
PlaneMaskFar
PlaneMaskAll
enum FrustumData::CornerPoints
Indices for the corner points of the frustum.
Enumerator
NearTopLeft
NearTopRight
NearBottomLeft
NearBottomRight
FarTopLeft
FarTopRight
FarBottomLeft
FarBottomRight
CornerPointCount
Total number of corner points.
enum FrustumData::PlaneCenters
Indices for the center points of the frustum planes.
Enumerator
PlaneLeftCenter
PlaneRightCenter
PlaneTopCenter
PlaneBottomCenter
PlaneNearCenter
PlaneFarCenter
Constructor & Destructor Documentation
FrustumData::FrustumData () inline protected
Member Function Documentation
void FrustumData::_update () const protected
Update the point and plane data from the current frustum settings.
static const Edge* FrustumData::getEdges () inline static
Return the edge definitions for a frustum.
References FixedSizeVector< T, SIZE >::address().
static U32 FrustumData::getNumEdges () inline static
Return the number of edges that a frustum has.
static U32 FrustumData::getNumPlanes () inline static
Return the number of planes that a frustum has.
static U32 FrustumData::getNumPoints () inline static
Return the number of corner points that a frustum has.
const PlaneF* FrustumData::getPlanes () const inline
Return the planes that make up the polyhedron.
Note
The normals of these planes are facing inwards.
References FixedSizeVector< T, SIZE >::address().
const Point3F* FrustumData::getPoints () const inline
References FixedSizeVector< T, SIZE >::address().
FrustumData::operator AnyPolyhedron () const inline
Member Data Documentation
Box3F FrustumData::mBounds mutable protected
The clipping-space axis-aligned bounding box which contains the extents of the frustum.
bool FrustumData::mDirty mutable protected
When true, points, planes and bounds must be re-calculated before use.
F32 FrustumData::mFarDist protected
Referenced by Frustum::operator==().
bool FrustumData::mIsInverted protected
Whether the frustum is inverted, i.e.
whether the planes are facing outwards rather than inwards.
bool FrustumData::mIsOrtho protected
Determines whether this Frustum is orthographic or perspective.
F32 FrustumData::mNearBottom protected
Referenced by Frustum::operator==().
F32 FrustumData::mNearDist protected
Referenced by Frustum::operator==().
F32 FrustumData::mNearLeft protected
The size of the near plane used to generate the frustum points and planes.
Referenced by Frustum::operator==().
F32 FrustumData::mNearRight protected
F32 FrustumData::mNearTop protected
Referenced by Frustum::operator==().
Point3F FrustumData::mPlaneCenters[PlaneCount] mutable protected
The center points of the individual faces of the frustum.
PlaneListType FrustumData::mPlanes mutable protected
PointListType FrustumData::mPoints mutable protected
Point3F FrustumData::mPosition protected
Camera position extracted from tarnsform.
MatrixF FrustumData::mTransform protected
Used to transform the frustum points from camera space into the desired clipping space.
EdgeListType FrustumData::smEdges static protected
Static edge list.
Shared by all frustum polyhedrons since they are always constructed the same way.
Copyright © GarageGames, LLC. All Rights Reserved.