PolyhedronBoxIntersector< Polyhedron > Struct Template Reference
Main Modules Class List Namespace List Online
PolyhedronBoxIntersector< Polyhedron > Struct Template Reference
Convex polyhedron / AABB intersection.
#include <math/mIntersector.h>
Public Types
typedef IntersectorBase< Polyhedron, Box3F > Parent
typedef Polyhedron PolyhedronType
Public Types inherited from IntersectorBase< Polyhedron, Box3F >
typedef Box3F TesteeType
typedef Polyhedron TesterType
Public Member Functions
PolyhedronBoxIntersector ()
PolyhedronBoxIntersector (const PolyhedronType &polyhedron, const MatrixF &objToWorld, const Point3F &scale, const Box3F &wsBounds)
OverlapTestResult test (const Box3F &box) const
Public Member Functions inherited from IntersectorBase< Polyhedron, Box3F >
IntersectorBase ()
IntersectorBase (const TesterType &tester)
Protected Member Functions
void _preprocess (const MatrixF &objToWorld, const Point3F &scale)
Run the preprocessing step on the current polyhedron.
Point2F _project (U32 axis, const Point3F &p)
Project the point orthogonally down the given axis such that the orientation of the resulting coordinate system remains right-handed.
Protected Attributes
Box3F mBounds
Bounds of the polyhedron.
Vector< Point3F > mEdgeLines
Edge line equations.
Point3I mNumEdgeLines
Number of silhouette edges for each of the orthographic projections.
Vector< PlaneF > mPlanes
World-space planes.
Protected Attributes inherited from IntersectorBase< Polyhedron, Box3F >
TesterType mTester
Detailed Description
template<typename Polyhedron>
struct PolyhedronBoxIntersector< Polyhedron >
Convex polyhedron / AABB intersection.
This class implements the algorithm described in "Detecting Intersection of a Rectangular Solid and a Convex Polyhedron", Graphics Gems IV, Chapter 1.7, by Ned Greene.
The polyhedron is preprocessed when an object of this class is constructed.
This class also assumes that the polyhedron is represented in object space and thus also stores local copies of the polyhedron's planes transformed into world space.
The approach of the algorithm is simple. It uses a maximum of three successive stages to determine intersection. Each stage can early out if it can draw a conclusive result already.
Simple tests of the polyhedron's bounding box against the input box.
Standard test on plane set.
Plane tests reduced to 2D and done for each of the orthographic side projections.
Note
The intersector depends on planes facing inwards.
Member Typedef Documentation
template<typename Polyhedron> typedef IntersectorBase< Polyhedron, Box3F > PolyhedronBoxIntersector< Polyhedron >::Parent
template<typename Polyhedron> typedef Polyhedron PolyhedronBoxIntersector< Polyhedron >::PolyhedronType
Constructor & Destructor Documentation
template<typename Polyhedron> PolyhedronBoxIntersector< Polyhedron >::PolyhedronBoxIntersector () inline
template<typename Polyhedron> PolyhedronBoxIntersector< Polyhedron >::PolyhedronBoxIntersector (const PolyhedronType & polyhedron, const MatrixF & objToWorld, const Point3F & scale, const Box3F & wsBounds) inline
Member Function Documentation
template<typename Polyhedron > void PolyhedronBoxIntersector< Polyhedron >::_preprocess (const MatrixF & objToWorld, const Point3F & scale) protected
Run the preprocessing step on the current polyhedron.
References Point3F::convolve(), IntersectorBase< Tester, Testee >::mTester, MatrixF::mulP(), Point2F::normalize(), PlaneTransformer::set(), PlaneTransformer::transform(), Point2F::x, and Point2F::y.
template<typename Polyhedron> Point2F PolyhedronBoxIntersector< Polyhedron >::_project (U32 axis, const Point3F & p) inline protected
Project the point orthogonally down the given axis such that the orientation of the resulting coordinate system remains right-handed.
template<typename Polyhedron > OverlapTestResult PolyhedronBoxIntersector< Polyhedron >::test (const Box3F & box) const
References PlaneF::Back, PlaneF::Front, Box3F::isContained(), Box3F::maxExtents, Box3F::minExtents, PlaneF::whichSide(), Point3F::x, Point2F::x, Point3F::y, Point2F::y, and Point3F::z.
Member Data Documentation
template<typename Polyhedron> Box3F PolyhedronBoxIntersector< Polyhedron >::mBounds protected
Bounds of the polyhedron.
template<typename Polyhedron> Vector< Point3F > PolyhedronBoxIntersector< Polyhedron >::mEdgeLines protected
Edge line equations.
X projection first, then Y, then Z. X of each equation is mapped to a, Y to b, and Z to c of the standard implicit form of line equations.
template<typename Polyhedron> Point3I PolyhedronBoxIntersector< Polyhedron >::mNumEdgeLines protected
Number of silhouette edges for each of the orthographic projections.
template<typename Polyhedron> Vector< PlaneF > PolyhedronBoxIntersector< Polyhedron >::mPlanes protected
World-space planes.
Copyright © GarageGames, LLC. All Rights Reserved.