TamlParser Class Reference
Main Modules Class List Namespace List Online
TamlParser Class Reference abstract
#include <persistence/taml/tamlParser.h>
Public Member Functions
TamlParser ()
virtual ~TamlParser ()
virtual bool accept (const char *pFilename, TamlVisitor &visitor)=0
Accept visitor.
virtual bool canChangeProperty (void)=0
Whether the parser can change a property or not.
StringTableEntry getParsingFilename (void) const
void setParsingFilename (const char *pFilename)
Filename.
Detailed Description
See also
tamlGroup
Constructor & Destructor Documentation
TamlParser::TamlParser () inline
virtual TamlParser::~TamlParser () inline virtual
References accept(), and canChangeProperty().
Member Function Documentation
virtual bool TamlParser::accept (const char * pFilename, TamlVisitor & visitor) pure virtual
Accept visitor.
Implemented in TamlJSONParser, and TamlXmlParser.
Referenced by ~TamlParser().
virtual bool TamlParser::canChangeProperty (void) pure virtual
Whether the parser can change a property or not.
Implemented in TamlJSONParser, and TamlXmlParser.
Referenced by ~TamlParser().
StringTableEntry TamlParser::getParsingFilename (void) const inline
Referenced by TamlAssetDeclaredVisitor::visit().
void TamlParser::setParsingFilename (const char * pFilename) inline
Filename.
Copyright © GarageGames, LLC. All Rights Reserved.