Tokenizer Class Reference
Main Modules Class List Namespace List Online
Tokenizer Class Reference
#include <core/tokenizer.h>
Public Types
enum { MaxTokenSize = 1023 }
Public Member Functions
Tokenizer ()
~Tokenizer ()
bool advanceToken (const bool crossLine, const bool assertAvailable=false)
void buildLinePositions ()
bool clear ()
bool endOfFile ()
bool findToken (const char *pCmp)
bool findToken (U32 start, const char *pCmp)
U32 getCurrentLine ()
U32 getCurrentPos () const
const char * getFileName () const
U32 getLinePosition (const U32 pos, U32 lowIndex=0, S32 highIndex=-1)
const char * getNextToken ()
const char * getToken () const
U32 getTokenLineOffset ()
bool openFile (const char *pFileName)
bool openFile (Stream *pStream)
bool regressToken (const bool crossLine)
bool reset ()
void setBuffer (const char *buffer, U32 bufferSize)
bool setCurrentPos (U32 pos)
void setSingleTokens (const char *singleTokens)
bool tokenAvailable ()
bool tokenICmp (const char *pCmp) const
bool tokenIsQuoted () const
Member Enumeration Documentation
anonymous enum
Enumerator
MaxTokenSize
Constructor & Destructor Documentation
Tokenizer::Tokenizer ()
Tokenizer::~Tokenizer ()
Member Function Documentation
bool Tokenizer::advanceToken (const bool crossLine, const bool assertAvailable = false)
void Tokenizer::buildLinePositions ()
bool Tokenizer::clear ()
Referenced by getCurrentPos().
bool Tokenizer::endOfFile ()
Referenced by getCurrentPos().
bool Tokenizer::findToken (const char * pCmp)
Referenced by tokenIsQuoted().
bool Tokenizer::findToken (U32 start, const char * pCmp)
U32 Tokenizer::getCurrentLine ()
Referenced by getFileName().
U32 Tokenizer::getCurrentPos () const inline
References clear(), endOfFile(), reset(), and setCurrentPos().
const char* Tokenizer::getFileName () const inline
References getCurrentLine(), getLinePosition(), and getTokenLineOffset().
U32 Tokenizer::getLinePosition (const U32 pos, U32 lowIndex = 0, S32 highIndex = -1)
Referenced by getFileName().
const char* Tokenizer::getNextToken ()
const char* Tokenizer::getToken () const
U32 Tokenizer::getTokenLineOffset ()
Referenced by getFileName().
bool Tokenizer::openFile (const char * pFileName)
bool Tokenizer::openFile (Stream * pStream)
bool Tokenizer::regressToken (const bool crossLine)
bool Tokenizer::reset ()
Referenced by getCurrentPos().
void Tokenizer::setBuffer (const char * buffer, U32 bufferSize)
bool Tokenizer::setCurrentPos (U32 pos)
Referenced by getCurrentPos().
void Tokenizer::setSingleTokens (const char * singleTokens)
bool Tokenizer::tokenAvailable ()
bool Tokenizer::tokenICmp (const char * pCmp) const
bool Tokenizer::tokenIsQuoted () const inline
References findToken().
Copyright © GarageGames, LLC. All Rights Reserved.