EngineObject Class Reference
Main Modules Class List Namespace List Online
EngineObject Class Reference
Base class for all objects that may be passed to the control layer.
#include <console/engineObject.h>
Public Member Functions
EngineObject ()
virtual ~EngineObject ()
DECLARE_ABSTRACT_CLASS (EngineObject, void)
DECLARE_INSCOPE (_GLOBALSCOPE)
virtual String describeSelf () const
Return a string that describes this instance. Meant primarily for debugging.
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
IEngineObjectPool * getEngineObjectPool () const
Return the pool of EngineObjects to which this object belongs.
void operator delete (void *ptr)
Release the given object's memory in the pool it has been allocated from.
void * operator new (size_t size)
void * operator new (size_t size, IEngineObjectPool *pool)
void * operator new (size_t size TORQUE_TMM_ARGS_DECL)
Allocate a new object in the default object pool.
void * operator new (size_t size, IEngineObjectPool *pool TORQUE_TMM_ARGS_DECL)
Allocate a new object in the given object pool.
void * operator new (size_t size, void *ptr)
Placement new.
Public Member Functions inherited from StrongRefBase
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Public Attributes
DECLARE_INSTANTIABLE
Protected Types
typedef ::FalseType __IsDisposableType
typedef ::FalseType __IsSingletonType
Protected Member Functions
virtual void _destroySelf ()
Subclasses should overload this method instead of the public destroySelf().
object incRefCount ()
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Static Protected Member Functions
static void * _allocateObject (size_t size, IEngineObjectPool *pool TORQUE_TMM_ARGS_DECL)
Protected Attributes
DEFINE_CREATE_METHOD
return object
Protected Attributes inherited from StrongRefBase
U32 mRefCount
reference counter for StrongRefPtr objects
Friends
void *& _USERDATA (EngineObject *)
const EngineTypeInfo * TYPEOF (const EngineObject *)
Return the type info object for the dynamic type of the given object.
Instance Tracking (debugging only)
In debug builds, all EngineObjects are kept on a global list so that it is easy to enumerate all live objects at any time.
Note
This is NOT thread-safe.
typedef void(* DebugEnumInstancesCallback) (EngineObject *)
Type of callback function for iterating over EngineObject instances.
static void debugDumpInstances ()
Dump describeSelf()s of all live ConsoleObjects to the console.
static void debugEnumInstances (const std::type_info &type, DebugEnumInstancesCallback callback)
Call the given callback for all instances of the given type.
static void debugEnumInstances (const char *className, DebugEnumInstancesCallback callback)
Same as above but uses an export class name and also includes inheritance (i.e.
Detailed Description
Base class for all objects that may be passed to the control layer.
A set of rules applies to all EngineObject-derived classes:
Every EngineObject class must have a default constructor.
The default constructor and the destructor of every EngineObject class must be public.
If an EngineObject class inherits from multiple classes, the class leading back to EngineObject must be the first class in the list to ensure binary-compatible class layouts.
EngineObjects are cooperatively reference-counted by both the engine as well as the control layer.
Member Typedef Documentation
typedef ::FalseType EngineObject::__IsDisposableType protected
typedef ::FalseType EngineObject::__IsSingletonType protected
typedef void(* EngineObject::DebugEnumInstancesCallback) (EngineObject *)
Type of callback function for iterating over EngineObject instances.
Constructor & Destructor Documentation
EngineObject::EngineObject ()
Referenced by _destroySelf().
virtual EngineObject::~EngineObject () virtual
Referenced by _destroySelf().
Member Function Documentation
static void* EngineObject::_allocateObject (size_t size, IEngineObjectPool *pool TORQUE_TMM_ARGS_DECL) static protected
Referenced by _destroySelf().
virtual void EngineObject::_destroySelf () inline protected virtual
Subclasses should overload this method instead of the public destroySelf().
Reimplemented in SimObject.
References _allocateObject(), describeSelf(), EngineObject(), TORQUE_TMM_ARGS_DECL, and ~EngineObject().
static void EngineObject::debugDumpInstances () static
Dump describeSelf()s of all live ConsoleObjects to the console.
static void EngineObject::debugEnumInstances (const std::type_info & type, DebugEnumInstancesCallback callback) static
Call the given callback for all instances of the given type.
Callback may also be NULL in which case the method just iterates over all instances of the given type. This is useful for setting a breakpoint during debugging.
static void EngineObject::debugEnumInstances (const char * className, DebugEnumInstancesCallback callback) static
Same as above but uses an export class name and also includes inheritance (i.e.
enumerates all instances of the given class and its subclasses).
EngineObject::DECLARE_ABSTRACT_CLASS (EngineObject , void)
EngineObject::DECLARE_INSCOPE (_GLOBALSCOPE)
virtual String EngineObject::describeSelf () const virtual
Return a string that describes this instance. Meant primarily for debugging.
Reimplemented in SimObject, NetObject, Portal, SceneSimpleZone, and SceneRootZone.
Referenced by _destroySelf().
virtual void EngineObject::destroySelf () virtual
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
Reimplemented from StrongRefBase.
Reimplemented in SimObject, and StaticEngineObject.
IEngineObjectPool* EngineObject::getEngineObjectPool () const inline
Return the pool of EngineObjects to which this object belongs.
References StaticEngineObject::destroySelf().
object EngineObject::incRefCount () protected
void EngineObject::operator delete (void * ptr)
Release the given object's memory in the pool it has been allocated from.
void* EngineObject::operator new (size_t size)
void* EngineObject::operator new (size_t size, IEngineObjectPool * pool)
void* EngineObject::operator new (size_t size TORQUE_TMM_ARGS_DECL)
Allocate a new object in the default object pool.
Parameters
size Size of the object in bytes.
Returns
Memory block for new object; never NULL.
void* EngineObject::operator new (size_t size, IEngineObjectPool *pool TORQUE_TMM_ARGS_DECL)
Allocate a new object in the given object pool.
If the given pool's allocateObject returns NULL, the method will fall back to the default pool.
Parameters
size Size of the object in bytes.
pool Object pool to allocate the object in.
Returns
Memory block for the new object; never NULL.
void* EngineObject::operator new (size_t size, void * ptr) inline
Placement new.
Friends And Related Function Documentation
void*& _USERDATA (EngineObject *) friend
const EngineTypeInfo* TYPEOF (const EngineObject * object) friend
Return the type info object for the dynamic type of the given object.
Parameters
object An EngineObject or NULL.
Returns
An EngineTypeInfo instance or NULL if object is NULL.
Member Data Documentation
EngineObject::DECLARE_INSTANTIABLE
EngineObject::DEFINE_CREATE_METHOD protected
Initial value:
{
         T* object = new T
return EngineObject::object protected
Copyright © GarageGames, LLC. All Rights Reserved.