GFXGLShader Class Reference
Main Modules Class List Namespace List Online
GFXGLShader Class Reference
#include <gfx/gl/gfxGLShader.h>
Public Member Functions
GFXGLShader ()
virtual ~GFXGLShader ()
void useProgram ()
Activates this shader in the GL context.
GFXShader interface
virtual GFXShaderConstHandle * getShaderConstHandle (const String &name)
Returns a shader constant handle for the name constant.
virtual GFXShaderConstHandle * findShaderConstHandle (const String &name)
Returns a shader constant handle for the name constant, if the variable doesn't exist NULL is returned.
virtual const Vector< GFXShaderConstDesc > & getShaderConstDesc () const
Returns our list of shader constants, the material can get this and just set the constants it knows about.
virtual U32 getAlignmentValue (const GFXShaderConstType constType) const
Returns the alignment value for constType.
virtual GFXShaderConstBufferRef allocConstBuffer ()
Allocate a constant buffer.
GFXResource interface
virtual void zombify ()
When called the resource should destroy all device sensitive information (e.g. D3D resources in D3DPOOL_DEFAULT.
virtual void resurrect ()
When called the resource should restore all device sensitive information destroyed by zombify()
virtual const String describeSelf () const
The resource should put a description of itself (number of vertices, size/width of texture, etc.) in buffer.
Public Member Functions inherited from GFXShader
virtual ~GFXShader ()
The destructor.
virtual bool getDisassembly (String &outStr) const
Device specific shaders can override this method to return the shader disassembly.
GFXVertexFormat * getInstancingFormat ()
const String & getPixelShaderFile () const
Returns the pixel shader file path.
F32 getPixVersion () const
Returns the required vertex format for this shader.
U32 getReloadKey () const
Returns a counter which is incremented each time this shader is reloaded.
Signal< void()> getReloadSignal ()
const String & getVertexShaderFile () const
Returns the vertex shader file path.
bool init (const Torque::Path &vertFile, const Torque::Path &pixFile, F32 pixVersion, const Vector< GFXShaderMacro > &macros)
Deprecated. Remove on T3D 4.0.
bool init (const Torque::Path &vertFile, const Torque::Path &pixFile, F32 pixVersion, const Vector< GFXShaderMacro > &macros, const Vector< String > &samplerNames, GFXVertexFormat *instanceFormat=NULL)
bool reload ()
Reloads the shader from disk.
Public Member Functions inherited from StrongRefBase
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Public Member Functions inherited from GFXResource
GFXResource ()
virtual ~GFXResource ()
void clearFlag ()
GFXResource * getNextResource () const
GFXDevice * getOwningDevice () const
GFXResource * getPrevResource () const
bool isFlagged ()
void registerResourceWithDevice (GFXDevice *device)
Registers this resource with the given device.
void setFlag ()
Protected Member Functions
virtual bool _init ()
Internal initialization function overloaded for each GFX device type.
void clearShaders ()
void initConstantDescs ()
void initHandles ()
bool initShader (const Torque::Path &file, bool isVertex, const Vector< GFXShaderMacro > &macros)
void setConstantsFromBuffer (GFXGLShaderConstBuffer *buffer)
Protected Member Functions inherited from GFXShader
GFXShader ()
A protected constructor so it cannot be instantiated.
void _onFileChanged (const Torque::Path &path)
Called when the shader files change on disk.
void _unlinkBuffer (GFXShaderConstBuffer *buf)
Buffers call this from their destructor (so we don't have to ref count them).
void _updateDesc ()
Called to update the description string after init.
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Static Protected Member Functions
static char * _handleIncludes (const Torque::Path &path, FileStream *s)
static bool _loadShaderFromStream (GLuint shader, const Torque::Path &path, FileStream *s, const Vector< GFXShaderMacro > &macros)
Protected Attributes
Vector< GFXShaderConstDesc > mConstants
U8 * mConstBuffer
U32 mConstBufferSize
HandleMap mHandles
Vector< GFXGLShaderConstHandle * > mValidHandles
Internal GL handles
GLuint mVertexShader
GLuint mPixelShader
GLuint mProgram
Protected Attributes inherited from GFXShader
Vector< GFXShaderConstBuffer * > mActiveBuffers
Vector of buffers that reference this shader.
String mDescription
GFXVertexFormat * mInstancingFormat
Vector< GFXShaderMacro > mMacros
The macros to be passed to the shader.
Torque::Path mPixelFile
The pixel shader file.
F32 mPixVersion
The pixel version this is compiled for.
U32 mReloadKey
Counter that is incremented each time this shader is reloaded.
Signal< void()> mReloadSignal
Vector< String > mSamplerNamesOrdered
Ordered SamplerNames We need to store a list of sampler for allow OpenGL to assign correct location for each sampler.
Torque::Path mVertexFile
The vertex shader file.
Protected Attributes inherited from StrongRefBase
U32 mRefCount
reference counter for StrongRefPtr objects
Additional Inherited Members
Static Public Member Functions inherited from GFXShader
static void addGlobalMacro (const String &name, const String &value=String::EmptyString)
Adds a global shader macro which will be merged with the script defined macros on every shader reload.
static bool removeGlobalMacro (const String &name)
Removes an existing global macro by name.
static void setLogging (bool logErrors, bool logWarning)
Toggle logging for shader errors.
Static Protected Attributes inherited from GFXShader
static Vector< GFXShaderMacro > smGlobalMacros
These are system wide shader macros which are merged with shader specific macros at creation.
static bool smLogErrors
If true the shader errors are spewed to the console.
static bool smLogWarnings
If true the shader warnings are spewed to the console.
Constructor & Destructor Documentation
GFXGLShader::GFXGLShader ()
virtual GFXGLShader::~GFXGLShader () virtual
Member Function Documentation
static char* GFXGLShader::_handleIncludes (const Torque::Path & path, FileStream * s) static protected
virtual bool GFXGLShader::_init () protected virtual
Internal initialization function overloaded for each GFX device type.
Implements GFXShader.
static bool GFXGLShader::_loadShaderFromStream (GLuint shader, const Torque::Path & path, FileStream * s, const Vector< GFXShaderMacro > & macros) static protected
virtual GFXShaderConstBufferRef GFXGLShader::allocConstBuffer () virtual
Allocate a constant buffer.
Implements GFXShader.
void GFXGLShader::clearShaders () protected
virtual const String GFXGLShader::describeSelf () const virtual
The resource should put a description of itself (number of vertices, size/width of texture, etc.) in buffer.
Reimplemented from GFXShader.
Referenced by GFXGLShaderConstBuffer::getShader(), and resurrect().
virtual GFXShaderConstHandle* GFXGLShader::findShaderConstHandle (const String & name) virtual
Returns a shader constant handle for the name constant, if the variable doesn't exist NULL is returned.
Implements GFXShader.
virtual U32 GFXGLShader::getAlignmentValue (const GFXShaderConstType constType) const virtual
Returns the alignment value for constType.
Implements GFXShader.
virtual const Vector<GFXShaderConstDesc>& GFXGLShader::getShaderConstDesc () const virtual
Returns our list of shader constants, the material can get this and just set the constants it knows about.
Implements GFXShader.
virtual GFXShaderConstHandle* GFXGLShader::getShaderConstHandle (const String & name) virtual
Returns a shader constant handle for the name constant.
Since shaders can reload and later have handles that didn't exist originally this will return a handle in an invalid state if the constant doesn't exist at this time.
Implements GFXShader.
void GFXGLShader::initConstantDescs () protected
void GFXGLShader::initHandles () protected
bool GFXGLShader::initShader (const Torque::Path & file, bool isVertex, const Vector< GFXShaderMacro > & macros) protected
virtual void GFXGLShader::resurrect () inline virtual
When called the resource should restore all device sensitive information destroyed by zombify()
Implements GFXResource.
References describeSelf(), GFXShader::reload(), and useProgram().
void GFXGLShader::setConstantsFromBuffer (GFXGLShaderConstBuffer * buffer) protected
void GFXGLShader::useProgram ()
Activates this shader in the GL context.
Referenced by resurrect().
virtual void GFXGLShader::zombify () virtual
When called the resource should destroy all device sensitive information (e.g. D3D resources in D3DPOOL_DEFAULT.
Implements GFXResource.
Member Data Documentation
Vector<GFXShaderConstDesc> GFXGLShader::mConstants protected
U8* GFXGLShader::mConstBuffer protected
U32 GFXGLShader::mConstBufferSize protected
HandleMap GFXGLShader::mHandles protected
GLuint GFXGLShader::mPixelShader protected
GLuint GFXGLShader::mProgram protected
Vector<GFXGLShaderConstHandle*> GFXGLShader::mValidHandles protected
GLuint GFXGLShader::mVertexShader protected
Copyright © GarageGames, LLC. All Rights Reserved.