Win32Window Class Reference
Main Modules Class List Namespace List Online
Win32Window Class Reference
Implementation of a window on Win32.
#include <windowManager/win32/win32Window.h>
Classes
struct Accelerator
Public Types
typedef Vector< Accelerator > AcceleratorList
Public Types inherited from PlatformWindow
enum WindowSystem {
WindowSystem_Unknown = 0,
WindowSystem_Windows,
WindowSystem_X11
}
Public Member Functions
Win32Window ()
~Win32Window ()
virtual void _setFullscreen (const bool fullscreen)
void addAccelerators (AcceleratorList &list)
Add a list of accelerators to this window.
virtual void centerWindow ()
virtual bool clearFullscreen ()
If we're fullscreen, this function returns us to desktop mode.
virtual Point2I clientToScreen (const Point2I &pos)
Convert the coordinate given in this window space to screen coordinates.
virtual void close ()
Destroy the window on screen.
virtual void defaultRender ()
Provide a simple GDI-based render for when the game is not rendering.
virtual const RectI getBounds () const
Get the position and size (fullscreen windows are always at (0,0)).
virtual const char * getCaption ()
Get the window's caption.
virtual const Point2I getClientExtent ()
Get the Client Area Extent (Resolution) of this window.
virtual GFXDevice * getGFXDevice ()
Return a pointer to the GFX device this window is bound to.
virtual GFXWindowTarget * getGFXTarget ()
Return a pointer to this window's render target.
HWND & getHWND ()
Return the HWND (win32 window handle) for this window.
HMENU & getMenuHandle ()
virtual PlatformWindow * getNextWindow () const
virtual void * getPlatformDrawable () const
Return the platform specific object needed to create or attach an accelerated graohics drawing context on or to the window.
virtual const Point2I getPosition ()
Get the position of this window.
virtual void * getSystemWindow (const WindowSystem system)
virtual const GFXVideoMode & getVideoMode ()
Get our current video mode - if the window has been resized, it will reflect this.
virtual WindowId getWindowId ()
Get the ID that uniquely identifies this window in the context of its window manager.
virtual void hide ()
Hide the window on screen.
bool isAccelerator (const InputEventInfo &info)
Returns true if info matches an accelerator.
virtual bool isFocused ()
Returns true if the window has input focus.
virtual bool isFullscreen ()
virtual bool isMaximized ()
Returns true if the window is maximized.
virtual bool isMinimized ()
Returns true if the window is minimized.
virtual bool isMouseLocked () const
Is the mouse locked ?
virtual bool isOpen ()
Returns true if the window is instantiated in the OS.
virtual bool isVisible ()
Returns true if the window is visible.
virtual void maximize ()
Maximize the window on screen.
virtual void minimize ()
Minimize the window on screen.
void removeAccelerators (AcceleratorList &list)
Remove a list of accelerators from this window.
virtual void restore ()
Restore the window from a Maximized or Minimized state.
virtual Point2I screenToClient (const Point2I &pos)
Convert the given screen coordinates to coordinates in this window space.
virtual void setBounds (const RectI &newBounds)
The bounds of a Window are defined as the entire area occupied by that Window.
virtual bool setCaption (const char *cap)
Set the window's caption.
virtual void setClientExtent (const Point2I newExtent)
The Client Rectangle or "Render Area" of a window is the area that is occupied by a given client that is rendering to that window.
virtual void setFocus ()
Set Focused State (Foreground)
void setMenuHandle (HMENU menuHandle)
virtual void setMouseLocked (bool enable)
Lock the mouse to this window.
virtual void setPosition (const Point2I newPosition)
The Position of a window is always in relation to the very upper left of the window.
virtual bool setSize (const Point2I &newSize)
Resize the window to have a new size (but be in the same position).
virtual void setVideoMode (const GFXVideoMode &mode)
Set the video mode for this window.
virtual bool shouldLockMouse () const
Should the mouse be locked at the next opportunity ?
virtual void show ()
Show the window on screen.
bool translateMessage (MSG &msg)
Allow windows to translate messages. Used for accelerators.
Public Member Functions inherited from PlatformWindow
virtual ~PlatformWindow ()
To get rid of a window, just delete it.
virtual bool getAcceleratorsEnabled () const
Returns true if native OS keyboard accelerators are enabled.
WindowInputGenerator * getInputGenerator () const
virtual Point2I getLockedSize ()
Returns the locked window size.
virtual Point2I getMinimumWindowSize ()
Returns the current minimum window size for this window.
virtual bool isSizeLocked ()
Returns true if the window size is locked.
virtual void lockSize (bool locked)
Locks/unlocks window resizing.
virtual void setAcceleratorsEnabled (const bool enabled)
Used to disable native OS keyboard accelerators.
virtual void setInputController (IProcessInput *controller)
Get the WindowController associated with this window.
virtual void setMinimumWindowSize (Point2I minSize)
Sets a minimum window size.
void setSuppressReset (bool suppress)
Set the flag that determines whether to suppress a GFXDevice reset.
void setFullscreen (const bool fullscreen)
Acquire the entire screen.
virtual void setBackground (bool val)
Set Idle State (Background)
virtual bool getBackground ()
Get Idle State (Background)
virtual void setOffscreenRender (bool val)
Set whether this window is intended for offscreen rendering An offscreen window will never be shown or lose focus.
virtual bool getOffscreenRender ()
Set whether this window is intended for offscreen rendering.
virtual void setDisplayWindow (bool val)
Set whether this window is should display as normal.
virtual void setKeyboardTranslation (const bool enabled)
Set if relevant keypress events should be translated into character input events.
virtual bool getKeyboardTranslation () const
Returns true if keyboard translation is enabled.
virtual bool shouldNotTranslate (U32 modifiers, U32 keyCode) const
Returns true if the given keypress event should not be translated.
virtual PlatformCursorController * getCursorController ()
virtual void setCursorPosition (S32 x, S32 y)
Set the cursor position based on logical coordinates from the upper-right corner.
virtual void getCursorPosition (Point2I &point)
Get the cursor position based on logical coordinates from the upper-right corner.
virtual void setCursorVisible (bool visible)
Set the cursor visibility on this window.
virtual bool isCursorVisible ()
Get the cursor visibility on this window.
Static Public Member Functions
static const UTF16 * getCurtainWindowClassName ()
Return the class name for the curtain window class.
static const UTF16 * getWindowClassName ()
Return the class name for the windows we create with this class.
Static Public Member Functions inherited from PlatformWindow
static ScreenResChangeSignal & getScreenResChangeSignal ()
Additional Inherited Members
Public Attributes inherited from PlatformWindow
AppEvent appEvent
MouseEvent mouseEvent
MouseWheelEvent wheelEvent
ButtonEvent buttonEvent
LinearEvent linearEvent
KeyEvent keyEvent
CharEvent charEvent
DisplayEvent displayEvent
ResizeEvent resizeEvent
IdleEvent idleEvent
Protected Member Functions inherited from PlatformWindow
PlatformWindow ()
Protected constructor so that the win.
virtual void _setVideoMode (const GFXVideoMode &mode)
Protected Attributes inherited from PlatformWindow
PlatformCursorController * mCursorController
Cursor Controller for this Window.
bool mDisplayWindow
This is set as part of the canvas being shown, and flags that the windows should render as normal from now on.
bool mEnableAccelerators
When Torque GuiText input controls have focus they need to disable native OS keyboard accelerator translation.
bool mEnableKeyboardTranslation
Are we enabling IME or other keyboard input translation services, or concerned about raw input?
bool mIsBackground
Is Idle?
Point2I mLockedSize
When the resize is locked, this will be used as both minimum and maximum window size.
Point2I mMinimumSize
Minimum allowed size for this window.
bool mOffscreenRender
Offscreen Render.
bool mResizeLocked
When this is true, resizing is locked.
bool mSuppressReset
Suppress device resets.
WindowId mWindowId
An opaque ID used to resolve references to this Window.
WindowInputGenerator * mWindowInputGenerator
Window Mouse/Key input Controller for this Window.
Static Protected Attributes inherited from PlatformWindow
static ScreenResChangeSignal smScreenResChangeSignal
Detailed Description
Implementation of a window on Win32.
Member Typedef Documentation
typedef Vector<Accelerator> Win32Window::AcceleratorList
Constructor & Destructor Documentation
Win32Window::Win32Window ()
Win32Window::~Win32Window ()
Member Function Documentation
virtual void Win32Window::_setFullscreen (const bool fullscreen) virtual
Reimplemented from PlatformWindow.
Referenced by setMenuHandle().
void Win32Window::addAccelerators (AcceleratorList & list)
Add a list of accelerators to this window.
Referenced by setMenuHandle().
virtual void Win32Window::centerWindow () virtual
Reimplemented from PlatformWindow.
Referenced by setMenuHandle().
virtual bool Win32Window::clearFullscreen () virtual
If we're fullscreen, this function returns us to desktop mode.
This will be either the last mode that we had that was not fullscreen, or the equivalent mode, windowed.
Implements PlatformWindow.
Referenced by setMenuHandle().
virtual Point2I Win32Window::clientToScreen (const Point2I & point) virtual
Convert the coordinate given in this window space to screen coordinates.
Implements PlatformWindow.
Referenced by setMenuHandle().
virtual void Win32Window::close () virtual
Destroy the window on screen.
Implements PlatformWindow.
Referenced by setMenuHandle().
virtual void Win32Window::defaultRender () virtual
Provide a simple GDI-based render for when the game is not rendering.
Referenced by getNextWindow().
virtual const RectI Win32Window::getBounds () const virtual
Get the position and size (fullscreen windows are always at (0,0)).
Implements PlatformWindow.
Referenced by setMenuHandle().
virtual const char* Win32Window::getCaption () virtual
Get the window's caption.
Implements PlatformWindow.
Referenced by setMenuHandle().
virtual const Point2I Win32Window::getClientExtent () virtual
Get the Client Area Extent (Resolution) of this window.
Implements PlatformWindow.
Referenced by setMenuHandle().
static const UTF16* Win32Window::getCurtainWindowClassName () static
Return the class name for the curtain window class.
Referenced by getNextWindow().
virtual GFXDevice* Win32Window::getGFXDevice () virtual
Return a pointer to the GFX device this window is bound to.
A GFX device may use many windows, but a window can only be used by a single GFX device.
Implements PlatformWindow.
Referenced by setMenuHandle().
virtual GFXWindowTarget* Win32Window::getGFXTarget () virtual
Return a pointer to this window's render target.
By setting window targets from different windows, we can effect rendering to multiple windows from a single device.
Implements PlatformWindow.
Referenced by setMenuHandle().
HWND& Win32Window::getHWND () inline
Return the HWND (win32 window handle) for this window.
References getSystemWindow().
HMENU& Win32Window::getMenuHandle () inline
virtual PlatformWindow* Win32Window::getNextWindow () const inline virtual
Implements PlatformWindow.
References defaultRender(), getCurtainWindowClassName(), and getWindowClassName().
virtual void* Win32Window::getPlatformDrawable () const inline virtual
Return the platform specific object needed to create or attach an accelerated graohics drawing context on or to the window.
Implements PlatformWindow.
virtual const Point2I Win32Window::getPosition () virtual
Get the position of this window.
Implements PlatformWindow.
Referenced by setMenuHandle().
virtual void* Win32Window::getSystemWindow (const WindowSystem system) virtual
Reimplemented from PlatformWindow.
Referenced by getHWND().
virtual const GFXVideoMode& Win32Window::getVideoMode () virtual
Get our current video mode - if the window has been resized, it will reflect this.
Implements PlatformWindow.
Referenced by setMenuHandle().
static const UTF16* Win32Window::getWindowClassName () static
Return the class name for the windows we create with this class.
Referenced by getNextWindow().
virtual WindowId Win32Window::getWindowId () virtual
Get the ID that uniquely identifies this window in the context of its window manager.
Reimplemented from PlatformWindow.
Referenced by shouldLockMouse().
virtual void Win32Window::hide () virtual
Hide the window on screen.
Implements PlatformWindow.
Referenced by setMenuHandle().
bool Win32Window::isAccelerator (const InputEventInfo & info)
Returns true if info matches an accelerator.
Referenced by setMenuHandle().
virtual bool Win32Window::isFocused () virtual
Returns true if the window has input focus.
Implements PlatformWindow.
Referenced by setMenuHandle().
virtual bool Win32Window::isFullscreen () virtual
Returns
true if this window is fullscreen, false otherwise.
Implements PlatformWindow.
Referenced by setMenuHandle().
virtual bool Win32Window::isMaximized () virtual
Returns true if the window is maximized.
Implements PlatformWindow.
Referenced by setMenuHandle().
virtual bool Win32Window::isMinimized () virtual
Returns true if the window is minimized.
Implements PlatformWindow.
Referenced by setMenuHandle().
virtual bool Win32Window::isMouseLocked () const inline virtual
Is the mouse locked ?
Implements PlatformWindow.
virtual bool Win32Window::isOpen () virtual
Returns true if the window is instantiated in the OS.
Implements PlatformWindow.
Referenced by setMenuHandle().
virtual bool Win32Window::isVisible () virtual
Returns true if the window is visible.
Implements PlatformWindow.
Referenced by setMenuHandle().
virtual void Win32Window::maximize () virtual
Maximize the window on screen.
Implements PlatformWindow.
Referenced by setMenuHandle().
virtual void Win32Window::minimize () virtual
Minimize the window on screen.
Implements PlatformWindow.
Referenced by setMenuHandle().
void Win32Window::removeAccelerators (AcceleratorList & list)
Remove a list of accelerators from this window.
Referenced by setMenuHandle().
virtual void Win32Window::restore () virtual
Restore the window from a Maximized or Minimized state.
Implements PlatformWindow.
Referenced by setMenuHandle().
virtual Point2I Win32Window::screenToClient (const Point2I & point) virtual
Convert the given screen coordinates to coordinates in this window space.
Implements PlatformWindow.
Referenced by setMenuHandle().
virtual void Win32Window::setBounds (const RectI & newBounds) virtual
The bounds of a Window are defined as the entire area occupied by that Window.
This includes the area needed for a title-bar, menu, borders, and other non-client elements.Resize the window to have some new bounds.
Implements PlatformWindow.
Referenced by setMenuHandle().
virtual bool Win32Window::setCaption (const char * cap) virtual
Set the window's caption.
Implements PlatformWindow.
Referenced by setMenuHandle().
virtual void Win32Window::setClientExtent (const Point2I newExtent) virtual
The Client Rectangle or "Render Area" of a window is the area that is occupied by a given client that is rendering to that window.
This does not include the area occupied by a title-bar, menu, borders or other non-client elements.Set the Client Area Extent (Resolution) of this window
Implements PlatformWindow.
Referenced by setMenuHandle().
virtual void Win32Window::setFocus () virtual
Set Focused State (Foreground)
Claim OS input focus for this window
Reimplemented from PlatformWindow.
Referenced by setMenuHandle().
void Win32Window::setMenuHandle (HMENU menuHandle) inline
References _setFullscreen(), addAccelerators(), centerWindow(), clearFullscreen(), clientToScreen(), close(), getBounds(), getCaption(), getClientExtent(), getGFXDevice(), getGFXTarget(), getPosition(), getVideoMode(), hide(), isAccelerator(), isFocused(), isFullscreen(), isMaximized(), isMinimized(), isOpen(), isVisible(), maximize(), minimize(), removeAccelerators(), restore(), screenToClient(), setBounds(), setCaption(), setClientExtent(), setFocus(), setMouseLocked(), setPosition(), setSize(), setVideoMode(), show(), and translateMessage().
virtual void Win32Window::setMouseLocked (bool enable) virtual
Lock the mouse to this window.
When this is set, the mouse will always be returned to the center of the client area after every mouse event. The mouse will also be hidden while it is locked.
The mouse cannot be moved out of the bounds of the window, but the window may lose focus (for instance by an alt-tab or other event). While the window lacks focus, no mouse events will be reported.
Implements PlatformWindow.
Referenced by setMenuHandle().
virtual void Win32Window::setPosition (const Point2I newPosition) virtual
The Position of a window is always in relation to the very upper left of the window.
This means that saying setPosition at 0,0 will put the position of the window title-bar (if one exists) at 0,0 and the Client area will be offset from that point by the space needed for the Non-Client area.Set the position of this window
Implements PlatformWindow.
Referenced by setMenuHandle().
virtual bool Win32Window::setSize (const Point2I & newSize) virtual
Resize the window to have a new size (but be in the same position).
Implements PlatformWindow.
Referenced by setMenuHandle().
virtual void Win32Window::setVideoMode (const GFXVideoMode & mode) virtual
Set the video mode for this window.
Reimplemented from PlatformWindow.
Referenced by setMenuHandle().
virtual bool Win32Window::shouldLockMouse () const inline virtual
Should the mouse be locked at the next opportunity ?
This flag is set to the current state of the mouse lock on a window, to specify the preferred lock status of the mouse in a platform window.
This is important for situations where a call is made to setMouseLocked, and the window is not in a state that it can be cleanly locked. Take for example if it was called while the window is in the background, then it is not appropriate to lock the window, but rather the window should query this state at it's next opportunity and lock the mouse if requested.
Implements PlatformWindow.
References getWindowId().
virtual void Win32Window::show () virtual
Show the window on screen.
Implements PlatformWindow.
Referenced by setMenuHandle().
bool Win32Window::translateMessage (MSG & msg)
Allow windows to translate messages. Used for accelerators.
Referenced by setMenuHandle().
Copyright © GarageGames, LLC. All Rights Reserved.