Box3D Class Reference
Main Modules Class List Namespace List Online
Box3D Class Reference
Clone of Box3F, using 3D types.
#include <math/mBox.h>
Public Member Functions
Box3D ()
Box3D (const Point3D &in_rMin, const Point3D &in_rMax, const bool in_overrideCheck=false)
void extend (const Point3D &p)
void getCenter (Point3D *center) const
void intersect (const Box3D &in_rIntersect)
bool isContained (const Point3D &in_rContained) const
bool isOverlapped (const Box3D &in_rOverlap) const
F64 len_x () const
F64 len_y () const
F64 len_z () const
Public Attributes
Point3D maxExtents
Point3D minExtents
Detailed Description
Clone of Box3F, using 3D types.
3D types use F64.
See also
Box3F
Constructor & Destructor Documentation
Box3D::Box3D () inline
References Box3F::extend(), Box3F::getCenter(), Box3F::intersect(), Box3F::isContained(), Box3F::isOverlapped(), Box3F::len_x(), Box3F::len_y(), and Box3F::len_z().
Box3D::Box3D (const Point3D & in_rMin, const Point3D & in_rMax, const bool in_overrideCheck = false) inline
References maxExtents, minExtents, Point3D::setMax(), and Point3D::setMin().
Member Function Documentation
void Box3D::extend (const Point3D & p) inline
Referenced by Box3I::isValidBox().
void Box3D::getCenter (Point3D * center) const inline
References maxExtents, minExtents, Point3D::x, Point3D::y, and Point3D::z.
Referenced by Box3I::Box3I().
void Box3D::intersect (const Box3D & in_rIntersect) inline
References maxExtents, minExtents, Point3D::setMax(), and Point3D::setMin().
Referenced by Box3I::Box3I().
bool Box3D::isContained (const Point3D & in_rContained) const inline
References maxExtents, minExtents, Point3D::x, Point3D::y, and Point3D::z.
Referenced by Box3I::Box3I().
bool Box3D::isOverlapped (const Box3D & in_rOverlap) const inline
References maxExtents, minExtents, Point3D::x, Point3D::y, and Point3D::z.
Referenced by Box3I::Box3I().
F64 Box3D::len_x () const inline
References maxExtents, minExtents, and Point3D::x.
Referenced by Box3I::Box3I().
F64 Box3D::len_y () const inline
References maxExtents, minExtents, and Point3D::y.
Referenced by Box3I::Box3I().
F64 Box3D::len_z () const inline
References maxExtents, minExtents, and Point3D::z.
Referenced by Box3I::Box3I().
Member Data Documentation
Point3D Box3D::maxExtents
Referenced by Box3D(), getCenter(), intersect(), isContained(), isOverlapped(), len_x(), len_y(), and len_z().
Point3D Box3D::minExtents
Referenced by Box3D(), getCenter(), intersect(), isContained(), isOverlapped(), len_x(), len_y(), and len_z().
Copyright © GarageGames, LLC. All Rights Reserved.