TamlCustomField Class Reference
Main Modules Class List Namespace List Online
TamlCustomField Class Reference
#include <persistence/taml/tamlCustom.h>
Public Member Functions
TamlCustomField ()
virtual ~TamlCustomField ()
bool fieldNameBeginsWith (const char *pComparison) const
StringTableEntry getFieldName (void) const
void getFieldValue (ColorF &fieldValue) const
void getFieldValue (ColorI &fieldValue) const
void getFieldValue (Point2I &fieldValue) const
void getFieldValue (Point2F &fieldValue) const
void getFieldValue (Point3I &fieldValue) const
void getFieldValue (Point3F &fieldValue) const
void getFieldValue (RectF &fieldValue) const
void getFieldValue (QuatF &fieldValue) const
void getFieldValue (AngAxisF &fieldValue) const
void getFieldValue (bool &fieldValue) const
void getFieldValue (S32 &fieldValue) const
void getFieldValue (U32 &fieldValue) const
void getFieldValue (F32 &fieldValue) const
const char * getFieldValue (void) const
bool isValueEmpty (void) const
virtual void resetState (void)
void set (const char *pFieldName, const char *pFieldValue)
void setFieldValue (const char *pFieldName, const ColorI &fieldValue)
void setFieldValue (const char *pFieldName, const ColorF &fieldValue)
void setFieldValue (const char *pFieldName, const Point2I &fieldValue)
void setFieldValue (const char *pFieldName, const Point2F &fieldValue)
void setFieldValue (const char *pFieldName, const Point3I &fieldValue)
void setFieldValue (const char *pFieldName, const Point3F &fieldValue)
void setFieldValue (const char *pFieldName, const RectF &fieldValue)
void setFieldValue (const char *pFieldName, const QuatF &fieldValue)
void setFieldValue (const char *pFieldName, const AngAxisF &fieldValue)
void setFieldValue (const char *pFieldName, const U32 fieldValue)
void setFieldValue (const char *pFieldName, const bool fieldValue)
void setFieldValue (const char *pFieldName, const S32 fieldValue)
void setFieldValue (const char *pFieldName, const float fieldValue)
void setFieldValue (const char *pFieldName, const char *fieldValue)
Constructor & Destructor Documentation
TamlCustomField::TamlCustomField () inline
References resetState().
virtual TamlCustomField::~TamlCustomField () inline virtual
Member Function Documentation
bool TamlCustomField::fieldNameBeginsWith (const char * pComparison) const inline
StringTableEntry TamlCustomField::getFieldName (void) const inline
Referenced by TamlCustomNode::getIgnoreEmpty().
void TamlCustomField::getFieldValue (ColorF & fieldValue) const inline
References ColorF::set(), and Con::setData().
Referenced by TamlCustomNode::getIgnoreEmpty().
void TamlCustomField::getFieldValue (ColorI & fieldValue) const inline
References ColorI::set(), and Con::setData().
void TamlCustomField::getFieldValue (Point2I & fieldValue) const inline
References Con::warnf(), Point2I::x, and Point2I::y.
void TamlCustomField::getFieldValue (Point2F & fieldValue) const inline
References Con::warnf(), Point2F::x, and Point2F::y.
void TamlCustomField::getFieldValue (Point3I & fieldValue) const inline
References Con::warnf(), Point3I::x, Point3I::y, and Point3I::z.
void TamlCustomField::getFieldValue (Point3F & fieldValue) const inline
References Con::warnf(), Point3F::x, Point3F::y, and Point3F::z.
void TamlCustomField::getFieldValue (RectF & fieldValue) const inline
References RectF::extent, RectF::point, Con::warnf(), Point2F::x, and Point2F::y.
void TamlCustomField::getFieldValue (QuatF & fieldValue) const inline
References QuatF::w, Con::warnf(), QuatF::x, QuatF::y, and QuatF::z.
void TamlCustomField::getFieldValue (AngAxisF & fieldValue) const inline
References AngAxisF::angle, AngAxisF::axis, Con::warnf(), Point3F::x, Point3F::y, and Point3F::z.
void TamlCustomField::getFieldValue (bool & fieldValue) const inline
References dAtob().
void TamlCustomField::getFieldValue (S32 & fieldValue) const inline
References dAtoi().
void TamlCustomField::getFieldValue (U32 & fieldValue) const inline
References dAtoi().
void TamlCustomField::getFieldValue (F32 & fieldValue) const inline
References dAtof().
const char* TamlCustomField::getFieldValue (void) const inline
bool TamlCustomField::isValueEmpty (void) const inline
virtual void TamlCustomField::resetState (void) inline virtual
Implements IFactoryObjectReset.
Referenced by TamlCustomField(), TamlCustomNode::TamlCustomNode(), and TamlCustomNodes::~TamlCustomNodes().
void TamlCustomField::set (const char * pFieldName, const char * pFieldValue)
void TamlCustomField::setFieldValue (const char * pFieldName, const ColorI & fieldValue) inline
References Con::getData(), and Con::warnf().
Referenced by TamlCustomNode::addField().
void TamlCustomField::setFieldValue (const char * pFieldName, const ColorF & fieldValue) inline
References Con::getData(), and Con::warnf().
void TamlCustomField::setFieldValue (const char * pFieldName, const Point2I & fieldValue) inline
References Point2I::x, and Point2I::y.
void TamlCustomField::setFieldValue (const char * pFieldName, const Point2F & fieldValue) inline
References Point2F::x, and Point2F::y.
void TamlCustomField::setFieldValue (const char * pFieldName, const Point3I & fieldValue) inline
References Point3I::x, Point3I::y, and Point3I::z.
void TamlCustomField::setFieldValue (const char * pFieldName, const Point3F & fieldValue) inline
References Point3F::x, Point3F::y, and Point3F::z.
void TamlCustomField::setFieldValue (const char * pFieldName, const RectF & fieldValue) inline
References RectF::extent, RectF::point, Point2F::x, and Point2F::y.
void TamlCustomField::setFieldValue (const char * pFieldName, const QuatF & fieldValue) inline
References QuatF::w, QuatF::x, QuatF::y, and QuatF::z.
void TamlCustomField::setFieldValue (const char * pFieldName, const AngAxisF & fieldValue) inline
References AngAxisF::angle, AngAxisF::axis, Point3F::x, Point3F::y, and Point3F::z.
void TamlCustomField::setFieldValue (const char * pFieldName, const U32 fieldValue) inline
void TamlCustomField::setFieldValue (const char * pFieldName, const bool fieldValue) inline
void TamlCustomField::setFieldValue (const char * pFieldName, const S32 fieldValue) inline
void TamlCustomField::setFieldValue (const char * pFieldName, const float fieldValue) inline
void TamlCustomField::setFieldValue (const char * pFieldName, const char * fieldValue) inline
Copyright © GarageGames, LLC. All Rights Reserved.