AssetPtr< T > Class Template Reference
Main Modules Class List Namespace List Online
AssetPtr< T > Class Template Reference
#include <assets/assetPtr.h>
Public Member Functions
AssetPtr ()
AssetPtr (const char *pAssetId)
AssetPtr (const AssetPtr< T > &assetPtr)
virtual ~AssetPtr ()
virtual void clear (void)
Referencing.
virtual StringTableEntry getAssetId (void) const
virtual StringTableEntry getAssetType (void) const
virtual bool isAssetId (const char *pAssetId) const
virtual bool isNull (void) const
Validity.
virtual bool notNull (void) const
operator T * (void) const
T & operator* (void) const
T * operator-> (void) const
AssetPtr< T > & operator= (const char *pAssetId)
Assignment.
AssetPtr< T > & operator= (const AssetPtr< T > &assetPtr)
virtual void setAssetId (const char *pAssetId)
Public Member Functions inherited from AssetPtrBase
AssetPtrBase ()
virtual ~AssetPtrBase ()
void registerRefreshNotify (AssetPtrCallback *pCallback)
Notification.
void unregisterRefreshNotify (void)
Constructor & Destructor Documentation
template<typename T> AssetPtr< T >::AssetPtr () inline
template<typename T> AssetPtr< T >::AssetPtr (const char * pAssetId) inline
template<typename T> AssetPtr< T >::AssetPtr (const AssetPtr< T > & assetPtr) inline
template<typename T> virtual AssetPtr< T >::~AssetPtr () inline virtual
Member Function Documentation
template<typename T> virtual void AssetPtr< T >::clear (void) inline virtual
Referencing.
Implements AssetPtrBase.
template<typename T> virtual StringTableEntry AssetPtr< T >::getAssetId (void) const inline virtual
Implements AssetPtrBase.
Referenced by AssetPtr< ShapeAsset >::AssetPtr(), and AssetPtr< ShapeAsset >::operator=().
template<typename T> virtual StringTableEntry AssetPtr< T >::getAssetType (void) const inline virtual
Implements AssetPtrBase.
template<typename T> virtual bool AssetPtr< T >::isAssetId (const char * pAssetId) const inline virtual
Implements AssetPtrBase.
template<typename T> virtual bool AssetPtr< T >::isNull (void) const inline virtual
Validity.
Implements AssetPtrBase.
template<typename T> virtual bool AssetPtr< T >::notNull (void) const inline virtual
Implements AssetPtrBase.
Referenced by AssetPtr< ShapeAsset >::AssetPtr().
template<typename T> AssetPtr< T >::operator T * (void) const inline
template<typename T> T& AssetPtr< T >::operator* (void) const inline
template<typename T> T* AssetPtr< T >::operator-> (void) const inline
template<typename T> AssetPtr<T>& AssetPtr< T >::operator= (const char * pAssetId) inline
Assignment.
template<typename T> AssetPtr<T>& AssetPtr< T >::operator= (const AssetPtr< T > & assetPtr) inline
template<typename T> virtual void AssetPtr< T >::setAssetId (const char * pAssetId) inline virtual
Implements AssetPtrBase.
Copyright © GarageGames, LLC. All Rights Reserved.