Transform3D Class Reference
Main Modules Class List Namespace List Online
Transform3D Class Reference abstract
#include <T3D/sceneComponent/T3DTransform.h>
Classes
class IDirtyListener
Public Member Functions
IDirtyListener * getDirtyListener () const
virtual void getLocalMatrix (MatrixF &localMatrix, bool includeLocalScale) const =0
MatrixF getLocalMatrix () const
virtual void getObjectMatrix (MatrixF &objectMatrix, bool includeLocalScale) const =0
MatrixF getObjectMatrix () const
Transform3D * getParentTransform () const
virtual Point3F getPosition () const =0
virtual QuatF getRotation () const =0
virtual Point3F getScale () const =0
virtual void getWorldMatrix (MatrixF &worldMatrix, bool includeLocalScale) const =0
MatrixF getWorldMatrix () const
bool hasLocalScale () const
bool hasObjectScale () const
bool hasWorldScale () const
bool isChildOf (Transform3D *parent, bool recursive) const
void setDirtyListener (IDirtyListener *dirtyListener)
virtual void setLocalMatrix (const MatrixF &localMatrix)=0
void setObjectMatrix (const MatrixF &objMatrix)
void setParentTransform (Transform3D *parent)
virtual void setPosition (const Point3F &position)=0
virtual void setRotation (const QuatF &rotation)=0
virtual void setScale (const Point3F &scale)=0
void setWorldMatrix (const MatrixF &world)
Protected Types
enum TransformFlags {
None = 0,
LocalHasScale = 1 << 0,
LocalPositionDirty = 1 << 1,
LocalRotationDirty = 1 << 2,
LocalScaleDirty = 1 << 3,
LocalDirty = LocalPositionDirty | LocalRotationDirty | LocalScaleDirty,
ParentDirty = 1 << 4,
LastFlag = 1 << 4
}
Protected Attributes
IDirtyListener * _dirtyListener
U32 _flags
Transform3D * _parentTransform
Member Enumeration Documentation
enum Transform3D::TransformFlags protected
Enumerator
None
LocalHasScale
LocalPositionDirty
LocalRotationDirty
LocalScaleDirty
LocalDirty
ParentDirty
LastFlag
Member Function Documentation
IDirtyListener* Transform3D::getDirtyListener () const inline
References _dirtyListener.
virtual void Transform3D::getLocalMatrix (MatrixF & localMatrix, bool includeLocalScale) const pure virtual
Implemented in TSTransform3D, and Transform3DInPlace.
MatrixF Transform3D::getLocalMatrix () const inline
References getPosition(), getRotation(), getScale(), setPosition(), setRotation(), and setScale().
Referenced by Transform3DInPlace::Transform3DInPlace().
virtual void Transform3D::getObjectMatrix (MatrixF & objectMatrix, bool includeLocalScale) const pure virtual
Implemented in TSTransform3D, and Transform3DInPlace.
MatrixF Transform3D::getObjectMatrix () const inline
Referenced by Transform3DInPlace::Transform3DInPlace().
Transform3D* Transform3D::getParentTransform () const inline
References _parentTransform, and setParentTransform().
virtual Point3F Transform3D::getPosition () const pure virtual
Implemented in TSTransform3D, and Transform3DInPlace.
Referenced by getLocalMatrix(), and Transform3DInPlace::Transform3DInPlace().
virtual QuatF Transform3D::getRotation () const pure virtual
Implemented in TSTransform3D, and Transform3DInPlace.
Referenced by getLocalMatrix(), and Transform3DInPlace::Transform3DInPlace().
virtual Point3F Transform3D::getScale () const pure virtual
Implemented in TSTransform3D, and Transform3DInPlace.
Referenced by getLocalMatrix(), and Transform3DInPlace::Transform3DInPlace().
virtual void Transform3D::getWorldMatrix (MatrixF & worldMatrix, bool includeLocalScale) const pure virtual
Implemented in TSTransform3D, and Transform3DInPlace.
MatrixF Transform3D::getWorldMatrix () const inline
Referenced by Transform3DInPlace::Transform3DInPlace().
bool Transform3D::hasLocalScale () const inline
References _flags, hasObjectScale(), hasWorldScale(), LocalHasScale, and None.
bool Transform3D::hasObjectScale () const
Referenced by hasLocalScale().
bool Transform3D::hasWorldScale () const
Referenced by hasLocalScale().
bool Transform3D::isChildOf (Transform3D * parent, bool recursive) const
Referenced by setDirtyListener().
void Transform3D::setDirtyListener (IDirtyListener * dirtyListener) inline
References _dirtyListener, and isChildOf().
virtual void Transform3D::setLocalMatrix (const MatrixF & localMatrix) pure virtual
Implemented in TSTransform3D, and Transform3DInPlace.
Referenced by Transform3DInPlace::Transform3DInPlace().
void Transform3D::setObjectMatrix (const MatrixF & objMatrix)
void Transform3D::setParentTransform (Transform3D * parent)
Referenced by getParentTransform().
virtual void Transform3D::setPosition (const Point3F & position) pure virtual
Implemented in TSTransform3D, and Transform3DInPlace.
Referenced by getLocalMatrix(), and Transform3DInPlace::Transform3DInPlace().
virtual void Transform3D::setRotation (const QuatF & rotation) pure virtual
Implemented in TSTransform3D, and Transform3DInPlace.
Referenced by getLocalMatrix(), and Transform3DInPlace::Transform3DInPlace().
virtual void Transform3D::setScale (const Point3F & scale) pure virtual
Implemented in TSTransform3D, and Transform3DInPlace.
Referenced by getLocalMatrix(), and Transform3DInPlace::Transform3DInPlace().
void Transform3D::setWorldMatrix (const MatrixF & world)
Member Data Documentation
IDirtyListener* Transform3D::_dirtyListener protected
Referenced by getDirtyListener(), and setDirtyListener().
U32 Transform3D::_flags protected
Referenced by TSTransform3D::doHandleLocal(), and hasLocalScale().
Transform3D* Transform3D::_parentTransform protected
Referenced by getParentTransform().
Copyright © GarageGames, LLC. All Rights Reserved.