StringBuilder Class Reference
Main Modules Class List Namespace List Online
StringBuilder Class Reference
#include <core/util/str.h>
Public Member Functions
StringBuilder ()
S32 append (char ch)
S32 append (const char *str)
S32 append (const String &str)
S32 append (const char *str, U32 length)
void copy (char *buffer) const
const char * data () const
String end ()
S32 format (const char *fmt,...)
U32 length () const
Protected Attributes
String::StrFormat mFormat
Constructor & Destructor Documentation
StringBuilder::StringBuilder () inline
Member Function Documentation
S32 StringBuilder::append (char ch) inline
References String::StrFormat::append().
S32 StringBuilder::append (const char * str) inline
References String::StrFormat::append().
S32 StringBuilder::append (const String & str) inline
References String::StrFormat::append(), String::c_str(), and String::length().
S32 StringBuilder::append (const char * str, U32 length) inline
References String::StrFormat::append().
void StringBuilder::copy (char * buffer) const inline
References String::StrFormat::copy().
const char* StringBuilder::data () const inline
References String::StrFormat::c_str().
String StringBuilder::end () inline
References String::StrFormat::getString().
S32 StringBuilder::format (const char * fmt, ...) inline
References String::StrFormat::formatAppend().
U32 StringBuilder::length () const inline
References String::StrFormat::length().
Member Data Documentation
String::StrFormat StringBuilder::mFormat protected
Copyright © GarageGames, LLC. All Rights Reserved.