TamlAssetReferencedUpdateVisitor Class Reference
Main Modules Class List Namespace List Online
TamlAssetReferencedUpdateVisitor Class Reference
#include <assets/tamlAssetReferencedUpdateVisitor.h>
Public Member Functions
TamlAssetReferencedUpdateVisitor ()
virtual ~TamlAssetReferencedUpdateVisitor ()
StringTableEntry getAssetIdFrom (void) const
const char * getAssetIdTo (void) const
void setAssetIdFrom (const char *pAssetIdFrom)
void setAssetIdTo (const char *pAssetIdTo)
virtual bool visit (const TamlParser &parser, TamlVisitor::PropertyState &propertyState)
The state of the visited property.
virtual bool wantsPropertyChanges (void)
Whether the visitor wants to perform property changes.
virtual bool wantsRootOnly (void)
Whether the visitor wants to visit the root node only.
Public Member Functions inherited from TamlVisitor
TamlVisitor ()
virtual ~TamlVisitor ()
Constructor & Destructor Documentation
TamlAssetReferencedUpdateVisitor::TamlAssetReferencedUpdateVisitor () inline
virtual TamlAssetReferencedUpdateVisitor::~TamlAssetReferencedUpdateVisitor () inline virtual
Member Function Documentation
StringTableEntry TamlAssetReferencedUpdateVisitor::getAssetIdFrom (void) const inline
const char* TamlAssetReferencedUpdateVisitor::getAssetIdTo (void) const inline
void TamlAssetReferencedUpdateVisitor::setAssetIdFrom (const char * pAssetIdFrom) inline
void TamlAssetReferencedUpdateVisitor::setAssetIdTo (const char * pAssetIdTo) inline
virtual bool TamlAssetReferencedUpdateVisitor::visit (const TamlParser & parser, TamlVisitor::PropertyState & propertyState) inline virtual
The state of the visited property.
Implements TamlVisitor.
References TamlVisitor::PropertyState::getPropertyValue(), StringUnit::getUnit(), StringUnit::getUnitCount(), and TamlVisitor::PropertyState::updatePropertyValue().
virtual bool TamlAssetReferencedUpdateVisitor::wantsPropertyChanges (void) inline virtual
Whether the visitor wants to perform property changes.
This allows a check against the parser which may not allow changes.
Implements TamlVisitor.
virtual bool TamlAssetReferencedUpdateVisitor::wantsRootOnly (void) inline virtual
Whether the visitor wants to visit the root node only.
Implements TamlVisitor.
Copyright © GarageGames, LLC. All Rights Reserved.