Px3Player Class Reference
Main Modules Class List Namespace List Online
Px3Player Class Reference
#include <T3D/physics/physx3/px3Player.h>
Public Member Functions
Px3Player ()
virtual ~Px3Player ()
virtual void disableCollision ()
virtual void enableCollision ()
virtual void findContact (SceneObject **contactObject, VectorF *contactNormal, Vector< SceneObject * > *outOverlapObjects) const
virtual MatrixF & getTransform (MatrixF *outMatrix)
Returns the transform of the physics body at the last processed simulation tick.
virtual PhysicsWorld * getWorld ()
Returns the physics world this object is a member of.
virtual Box3F getWorldBounds ()
Returns the world aligned bounding box containing the PhysicsObject.
virtual void init (const char *type, const Point3F &size, F32 runSurfaceCos, F32 stepHeight, SceneObject *obj, PhysicsWorld *world)
virtual bool isSimulationEnabled ()
virtual Point3F move (const VectorF &displacement, CollisionList &outCol)
virtual void setScale (const Point3F &scale)
virtual void setSimulationEnabled (bool enabled)
Set false to skip simulation of this object or temporarily remove it from the physics simulation.
virtual void setSpacials (const Point3F &nPos, const Point3F &nSize)
virtual void setTransform (const MatrixF &transform)
Sets the transform on the physics object.
virtual bool testSpacials (const Point3F &nPos, const Point3F &nSize) const
Public Member Functions inherited from PhysicsPlayer
PhysicsPlayer ()
virtual ~PhysicsPlayer ()
Public Member Functions inherited from PhysicsObject
virtual ~PhysicsObject ()
const PhysicsUserData & getUserData () const
PhysicsUserData & getUserData ()
void queueCallback (U32 ms, Delegate< void()> callback)
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Protected Member Functions
void _findContact (SceneObject **contactObject, VectorF *contactNormal) const
void _onPhysicsReset (PhysicsResetEvent reset)
void _onStaticChanged ()
void _releaseController ()
virtual void onControllerHit (const physx::PxControllersHit &hit)
virtual void onObstacleHit (const physx::PxControllerObstacleHit &)
virtual void onShapeHit (const physx::PxControllerShapeHit &hit)
Protected Member Functions inherited from PhysicsObject
PhysicsObject ()
You shouldn't be creating this object directly.
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Protected Attributes
CollisionList * mCollisionList
Used to get collision info out of the PxUserControllerHitReport callbacks.
physx::PxController * mController
U32 mElapsed
physx::PxCapsuleGeometry mGeometry
SceneObject * mObject
F32 mOriginOffset
F32 mSkinWidth
F32 mStepHeight
Px3World * mWorld
Protected Attributes inherited from PhysicsObject
U32 mQueuedEvent
The last queued callback event.
PhysicsUserData mUserData
The user data object assigned to this object.
Constructor & Destructor Documentation
Px3Player::Px3Player ()
Referenced by onObstacleHit().
virtual Px3Player::~Px3Player () virtual
Referenced by onObstacleHit().
Member Function Documentation
void Px3Player::_findContact (SceneObject ** contactObject, VectorF * contactNormal) const protected
Referenced by onObstacleHit().
void Px3Player::_onPhysicsReset (PhysicsResetEvent reset) protected
Referenced by onObstacleHit().
void Px3Player::_onStaticChanged () protected
Referenced by onObstacleHit().
void Px3Player::_releaseController () protected
virtual void Px3Player::disableCollision () virtual
Implements PhysicsPlayer.
Referenced by isSimulationEnabled().
virtual void Px3Player::enableCollision () virtual
Implements PhysicsPlayer.
Referenced by isSimulationEnabled().
virtual void Px3Player::findContact (SceneObject ** contactObject, VectorF * contactNormal, Vector< SceneObject * > * outOverlapObjects) const virtual
Implements PhysicsPlayer.
Referenced by isSimulationEnabled().
virtual MatrixF& Px3Player::getTransform (MatrixF * outMatrix) virtual
Returns the transform of the physics body at the last processed simulation tick.
Implements PhysicsObject.
Referenced by onObstacleHit().
virtual PhysicsWorld* Px3Player::getWorld () virtual
Returns the physics world this object is a member of.
Implements PhysicsObject.
Referenced by onObstacleHit().
virtual Box3F Px3Player::getWorldBounds () virtual
Returns the world aligned bounding box containing the PhysicsObject.
Implements PhysicsObject.
Referenced by onObstacleHit().
virtual void Px3Player::init (const char * type, const Point3F & size, F32 runSurfaceCos, F32 stepHeight, SceneObject * obj, PhysicsWorld * world) virtual
Implements PhysicsPlayer.
Referenced by isSimulationEnabled().
virtual bool Px3Player::isSimulationEnabled () inline virtual
Implements PhysicsObject.
References disableCollision(), enableCollision(), findContact(), init(), move(), setSpacials(), and testSpacials().
virtual Point3F Px3Player::move (const VectorF & displacement, CollisionList & outCol) virtual
Implements PhysicsPlayer.
Referenced by isSimulationEnabled().
virtual void Px3Player::onControllerHit (const physx::PxControllersHit & hit) protected virtual
virtual void Px3Player::onObstacleHit (const physx::PxControllerObstacleHit &) inline protected virtual
References _findContact(), _onPhysicsReset(), _onStaticChanged(), getTransform(), getWorld(), getWorldBounds(), Px3Player(), setScale(), setTransform(), and ~Px3Player().
virtual void Px3Player::onShapeHit (const physx::PxControllerShapeHit & hit) protected virtual
virtual void Px3Player::setScale (const Point3F & scale) virtual
Referenced by onObstacleHit().
virtual void Px3Player::setSimulationEnabled (bool enabled) inline virtual
Set false to skip simulation of this object or temporarily remove it from the physics simulation.
Implementation is PhysicsPlugin specific.
Implements PhysicsObject.
virtual void Px3Player::setSpacials (const Point3F & nPos, const Point3F & nSize) virtual
Implements PhysicsPlayer.
Referenced by isSimulationEnabled().
virtual void Px3Player::setTransform (const MatrixF & transform) virtual
Sets the transform on the physics object.
For static objects this is only intended to be used for for infrequent changes when editing the mission.
Implements PhysicsObject.
Referenced by onObstacleHit().
virtual bool Px3Player::testSpacials (const Point3F & nPos, const Point3F & nSize) const virtual
Implements PhysicsPlayer.
Referenced by isSimulationEnabled().
Member Data Documentation
CollisionList* Px3Player::mCollisionList protected
Used to get collision info out of the PxUserControllerHitReport callbacks.
physx::PxController* Px3Player::mController protected
U32 Px3Player::mElapsed protected
physx::PxCapsuleGeometry Px3Player::mGeometry protected
SceneObject* Px3Player::mObject protected
F32 Px3Player::mOriginOffset protected
F32 Px3Player::mSkinWidth protected
F32 Px3Player::mStepHeight protected
Px3World* Px3Player::mWorld protected
Copyright © GarageGames, LLC. All Rights Reserved.