PhysicsUserData Class Reference
Main Modules Class List Namespace List Online
PhysicsUserData Class Reference
The base class for physics user data.
#include <T3D/physics/physicsUserData.h>
Public Member Functions
PhysicsUserData ()
The constructor.
virtual ~PhysicsUserData ()
The destructor.
PhysicsBody * getBody () const
PhysicsContactSignal & getContactSignal ()
SceneObject * getObject () const
void setBody (PhysicsBody *body)
void setObject (SceneObject *object)
Static Public Member Functions
static PhysicsUserData * cast (void *data)
Helper method for casting a void pointer to a userdata pointer.
static SceneObject * getObject (void *data)
Helper method for casting a void pointer to a userdata pointer.
Protected Attributes
PhysicsBody * mBody
PhysicsContactSignal mContactSignal
SceneObject * mObject
const char * mTypeId
The type string assigned at construction used to validate the void* cast.
Static Protected Attributes
static const char * smTypeName
The type string used to validate the void* cast.
Detailed Description
The base class for physics user data.
Constructor & Destructor Documentation
PhysicsUserData::PhysicsUserData () inline
The constructor.
virtual PhysicsUserData::~PhysicsUserData () inline virtual
The destructor.
Member Function Documentation
static PhysicsUserData* PhysicsUserData::cast (void * data) inline static
Helper method for casting a void pointer to a userdata pointer.
References mTypeId, and smTypeName.
Referenced by getObject().
PhysicsBody* PhysicsUserData::getBody () const inline
References mBody.
PhysicsContactSignal& PhysicsUserData::getContactSignal () inline
References mContactSignal.
SceneObject* PhysicsUserData::getObject () const inline
References mObject.
Referenced by getObject().
static SceneObject* PhysicsUserData::getObject (void * data) inline static
Helper method for casting a void pointer to a userdata pointer.
References cast(), and getObject().
void PhysicsUserData::setBody (PhysicsBody * body) inline
References mBody.
void PhysicsUserData::setObject (SceneObject * object) inline
References mObject.
Member Data Documentation
PhysicsBody* PhysicsUserData::mBody protected
Referenced by getBody(), and setBody().
PhysicsContactSignal PhysicsUserData::mContactSignal protected
Referenced by getContactSignal().
SceneObject* PhysicsUserData::mObject protected
Referenced by getObject(), and setObject().
const char* PhysicsUserData::mTypeId protected
The type string assigned at construction used to validate the void* cast.
See also
cast
Referenced by cast().
const char* PhysicsUserData::smTypeName static protected
The type string used to validate the void* cast.
See also
cast
Referenced by cast().
Copyright © GarageGames, LLC. All Rights Reserved.