GFXGeneralFence Class Reference
Main Modules Class List Namespace List Online
GFXGeneralFence Class Reference
#include <gfx/gfxFence.h>
Public Member Functions
GFXGeneralFence (GFXDevice *device)
virtual ~GFXGeneralFence ()
virtual void block ()
This method will not return until the fence has been processed by the GPU.
virtual const String describeSelf () const
The resource should put a description of itself (number of vertices, size/width of texture, etc.) in buffer.
virtual FenceStatus getStatus () const
This is a non-blocking call to get the status of the fence.
virtual void issue ()
This method inserts the fence into the command buffer.
virtual void resurrect ()
When called the resource should restore all device sensitive information destroyed by zombify()
virtual void zombify ()
When called the resource should destroy all device sensitive information (e.g. D3D resources in D3DPOOL_DEFAULT.
Public Member Functions inherited from GFXFence
GFXFence (GFXDevice *device)
virtual ~GFXFence ()
Public Member Functions inherited from GFXResource
GFXResource ()
virtual ~GFXResource ()
void clearFlag ()
GFXResource * getNextResource () const
GFXDevice * getOwningDevice () const
GFXResource * getPrevResource () const
bool isFlagged ()
void registerResourceWithDevice (GFXDevice *device)
Registers this resource with the given device.
void setFlag ()
Protected Member Functions
void _init ()
void _onTextureEvent (GFXTexCallbackCode code)
The callback used to get texture events.
Protected Attributes
bool mInitialized
GFXStateBlockRef mRenderSB
GFXTextureTargetRef mRenderTarget
GFXTexHandle mRTTexHandle
Protected Attributes inherited from GFXFence
GFXDevice * mDevice
Additional Inherited Members
Public Types inherited from GFXFence
enum FenceStatus {
Unset,
Pending,
Processed,
Unsupported
}
The states returned by getStatus()
Constructor & Destructor Documentation
GFXGeneralFence::GFXGeneralFence (GFXDevice * device) inline
References GFXFence::issue().
virtual GFXGeneralFence::~GFXGeneralFence () virtual
Member Function Documentation
void GFXGeneralFence::_init () protected
void GFXGeneralFence::_onTextureEvent (GFXTexCallbackCode code) protected
The callback used to get texture events.
See also
GFXTextureManager::addEventDelegate
virtual void GFXGeneralFence::block () virtual
This method will not return until the fence has been processed by the GPU.
Implements GFXFence.
virtual const String GFXGeneralFence::describeSelf () const virtual
The resource should put a description of itself (number of vertices, size/width of texture, etc.) in buffer.
Implements GFXResource.
virtual FenceStatus GFXGeneralFence::getStatus () const inline virtual
This is a non-blocking call to get the status of the fence.
See also
GFXFence::FenceStatus
Implements GFXFence.
References GFXFence::block(), GFXResource::describeSelf(), GFXResource::resurrect(), GFXFence::Unsupported, and GFXResource::zombify().
virtual void GFXGeneralFence::issue () virtual
This method inserts the fence into the command buffer.
Implements GFXFence.
virtual void GFXGeneralFence::resurrect () virtual
When called the resource should restore all device sensitive information destroyed by zombify()
Implements GFXResource.
virtual void GFXGeneralFence::zombify () virtual
When called the resource should destroy all device sensitive information (e.g. D3D resources in D3DPOOL_DEFAULT.
Implements GFXResource.
Member Data Documentation
bool GFXGeneralFence::mInitialized protected
GFXStateBlockRef GFXGeneralFence::mRenderSB protected
GFXTextureTargetRef GFXGeneralFence::mRenderTarget protected
GFXTexHandle GFXGeneralFence::mRTTexHandle protected
Copyright © GarageGames, LLC. All Rights Reserved.