ScopeTrackerObject< NUM_DIMENSIONS > Class Template Reference
Main Modules Class List Namespace List Online
ScopeTrackerObject< NUM_DIMENSIONS > Class Template Reference
Base class for objects registered with a ScopeTracker.
#include <util/scopeTracker.h>
Classes
class TrackingNode
TrackingNodes are used to track object bounds along individual world axes.
Public Types
enum { AllInScope = (0x01010101 >> ((4 - NUM_DIMENSIONS) * 8)) }
typedef void Parent
Public Member Functions
ScopeTrackerObject (U32 flags=0)
void clearScopeMask ()
TrackingNode * getMaxTrackingNode (U32 dimension)
const TrackingNode * getMaxTrackingNode (U32 dimension) const
TrackingNode * getMinTrackingNode (U32 dimension)
const TrackingNode * getMinTrackingNode (U32 dimension) const
bool isInScope () const
Return true if the reference center lies within the object bound's on all axes.
bool isInScope (U32 dimension) const
bool isRegistered () const
Return true if the object is currently being tracked.
void setInScope (U32 dimension, bool state)
Implementor Interface
The following methods must be implemented by the client.
They are defined here just for reference. If you don't override them, you'll get link errors.
void getPosition (F32 pos[NUM_DIMENSIONS]) const
Return the position of the object in world-space.
void getReferenceCenter (F32 pos[NUM_DIMENSIONS]) const
If this object is the reference object, this method should return the world-space pivot point in the object that will be the world reference center.
void getBounds (F32 minBounds[NUM_DIMENSIONS], F32 maxBounds[NUM_DIMENSIONS]) const
Return the object's bounding box in world-space.
String describeSelf () const
Protected Attributes
union {
U8 mBytes [4]
U32 mDWord
} mScopeMask
TrackingNode mTrackingNodes [NUM_DIMENSIONS][2]
Detailed Description
template<S32 NUM_DIMENSIONS>
class ScopeTrackerObject< NUM_DIMENSIONS >
Base class for objects registered with a ScopeTracker.
Member Typedef Documentation
template<S32 NUM_DIMENSIONS> typedef void ScopeTrackerObject< NUM_DIMENSIONS >::Parent
Member Enumeration Documentation
template<S32 NUM_DIMENSIONS> anonymous enum
Enumerator
AllInScope
Constructor & Destructor Documentation
template<S32 NUM_DIMENSIONS> ScopeTrackerObject< NUM_DIMENSIONS >::ScopeTrackerObject (U32 flags = 0) inline
References ScopeTrackerObject< NUM_DIMENSIONS >::clearScopeMask(), ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::FLAG_Max, ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::FLAG_Min, ScopeTrackerObject< NUM_DIMENSIONS >::getMaxTrackingNode(), ScopeTrackerObject< NUM_DIMENSIONS >::getMinTrackingNode(), ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::mFlags, ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::mObject, ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::mOpposite, and BitSet32::set().
Member Function Documentation
template<S32 NUM_DIMENSIONS> void ScopeTrackerObject< NUM_DIMENSIONS >::clearScopeMask () inline
References ScopeTrackerObject< NUM_DIMENSIONS >::mScopeMask.
Referenced by ScopeTrackerObject< NUM_DIMENSIONS >::ScopeTrackerObject().
template<S32 NUM_DIMENSIONS> String ScopeTrackerObject< NUM_DIMENSIONS >::describeSelf () const
Referenced by ScopeTrackerObject< NUM_DIMENSIONS >::getMaxTrackingNode().
template<S32 NUM_DIMENSIONS> void ScopeTrackerObject< NUM_DIMENSIONS >::getBounds (F32 minBounds[NUM_DIMENSIONS], F32 maxBounds[NUM_DIMENSIONS]) const
Return the object's bounding box in world-space.
Referenced by ScopeTrackerObject< NUM_DIMENSIONS >::getMaxTrackingNode().
template<S32 NUM_DIMENSIONS> TrackingNode* ScopeTrackerObject< NUM_DIMENSIONS >::getMaxTrackingNode (U32 dimension) inline
Referenced by ScopeTrackerObject< NUM_DIMENSIONS >::ScopeTrackerObject().
template<S32 NUM_DIMENSIONS> const TrackingNode* ScopeTrackerObject< NUM_DIMENSIONS >::getMaxTrackingNode (U32 dimension) const inline
References ScopeTrackerObject< NUM_DIMENSIONS >::describeSelf(), ScopeTrackerObject< NUM_DIMENSIONS >::getBounds(), ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::getPosition(), and ScopeTrackerObject< NUM_DIMENSIONS >::getReferenceCenter().
template<S32 NUM_DIMENSIONS> TrackingNode* ScopeTrackerObject< NUM_DIMENSIONS >::getMinTrackingNode (U32 dimension) inline
Referenced by ScopeTrackerObject< NUM_DIMENSIONS >::isRegistered(), and ScopeTrackerObject< NUM_DIMENSIONS >::ScopeTrackerObject().
template<S32 NUM_DIMENSIONS> const TrackingNode* ScopeTrackerObject< NUM_DIMENSIONS >::getMinTrackingNode (U32 dimension) const inline
template<S32 NUM_DIMENSIONS> void ScopeTrackerObject< NUM_DIMENSIONS >::getPosition (F32 pos[NUM_DIMENSIONS]) const
Return the position of the object in world-space.
template<S32 NUM_DIMENSIONS> void ScopeTrackerObject< NUM_DIMENSIONS >::getReferenceCenter (F32 pos[NUM_DIMENSIONS]) const
If this object is the reference object, this method should return the world-space pivot point in the object that will be the world reference center.
Referenced by ScopeTrackerObject< NUM_DIMENSIONS >::getMaxTrackingNode().
template<S32 NUM_DIMENSIONS> bool ScopeTrackerObject< NUM_DIMENSIONS >::isInScope () const inline
Return true if the reference center lies within the object bound's on all axes.
References ScopeTrackerObject< NUM_DIMENSIONS >::AllInScope, and ScopeTrackerObject< NUM_DIMENSIONS >::mScopeMask.
template<S32 NUM_DIMENSIONS> bool ScopeTrackerObject< NUM_DIMENSIONS >::isInScope (U32 dimension) const inline
References ScopeTrackerObject< NUM_DIMENSIONS >::mScopeMask.
template<S32 NUM_DIMENSIONS> bool ScopeTrackerObject< NUM_DIMENSIONS >::isRegistered () const inline
Return true if the object is currently being tracked.
References ScopeTrackerObject< NUM_DIMENSIONS >::getMinTrackingNode(), and ScopeTrackerObject< NUM_DIMENSIONS >::TrackingNode::getNext().
template<S32 NUM_DIMENSIONS> void ScopeTrackerObject< NUM_DIMENSIONS >::setInScope (U32 dimension, bool state) inline
References ScopeTrackerObject< NUM_DIMENSIONS >::mScopeMask.
Member Data Documentation
template<S32 NUM_DIMENSIONS> U8 ScopeTrackerObject< NUM_DIMENSIONS >::mBytes[4]
template<S32 NUM_DIMENSIONS> U32 ScopeTrackerObject< NUM_DIMENSIONS >::mDWord
union { ... } ScopeTrackerObject< NUM_DIMENSIONS >::mScopeMask
Referenced by ScopeTrackerObject< NUM_DIMENSIONS >::clearScopeMask(), ScopeTrackerObject< NUM_DIMENSIONS >::isInScope(), and ScopeTrackerObject< NUM_DIMENSIONS >::setInScope().
template<S32 NUM_DIMENSIONS> TrackingNode ScopeTrackerObject< NUM_DIMENSIONS >::mTrackingNodes[NUM_DIMENSIONS][2] protected
Copyright © GarageGames, LLC. All Rights Reserved.