HifiMoveList Class Reference
Main Modules Class List Namespace List Online
HifiMoveList Class Reference
#include <T3D/gameBase/hifi/hifiMoveList.h>
Public Member Functions
HifiMoveList ()
void advanceMove ()
void clientReadMovePacket (BitStream *)
void clientWriteMovePacket (BitStream *bstream)
U32 getMoves (Move **, U32 *numMoves)
void ghostPreRead (NetObject *, bool newGhost)
void ghostReadExtra (NetObject *, BitStream *, bool newGhost)
void init ()
void markControlDirty ()
void onAdvanceObjects ()
void serverReadMovePacket (BitStream *bstream)
void serverWriteMovePacket (BitStream *)
Public Member Functions inherited from MoveList
MoveList ()
virtual ~MoveList ()
virtual void ackMoves (U32 count)
virtual bool areMovesPending ()
void clearMismatch ()
virtual void clearMoves (U32 count)
virtual void collectMove ()
virtual bool isBacklogged ()
If there are no pending moves and the input queue is full, then the connection to the server must be clogged.
bool isMismatch ()
virtual void pushMove (const Move &mv)
virtual void reset ()
Clear out all moves in the list and reset to initial state.
void resetCatchup ()
Reset move list back to last acknowledged move.
void resetClientMoves ()
Reset to beginning of client move list.
void setConnection (GameConnection *connection)
virtual void ghostWriteExtra (NetObject *, BitStream *)
virtual void writeDemoStartBlock (ResizeBitStream *stream)
virtual void readDemoStartBlock (BitStream *stream)
Protected Types
enum {
TotalTicksBits =10,
TotalTicksMask = (1<<TotalTicksBits)-1,
ServerTicksUninitialized =0xFFFFFFFF
}
Protected Types inherited from MoveList
enum {
MoveCountBits = 5,
MaxMoveCount = 30
}
Protected Member Functions
S32 getServerTicks (U32 serverTickNum)
void resetMoveList ()
bool serverTicksInitialized ()
void updateClientServerTickDiff (S32 &tickDiff)
Protected Member Functions inherited from MoveList
bool getNextMove (Move &curMove)
Protected Attributes
F32 mAvgMoveQueueSize
U32 mLastSentMove
U32 mMaxMoveListSize
F32 mMoveListSizeSlack
F32 mSmoothMoveAvg
bool mSuppressMove
U32 mTargetMoveListSize
U32 mTotalServerTicks
Protected Attributes inherited from MoveList
GameConnection * mConnection
bool mControlMismatch
U32 mFirstMoveIndex
U32 mLastClientMove
U32 mLastMoveAck
Vector< Move > mMoveVec
Member Enumeration Documentation
anonymous enum protected
Enumerator
TotalTicksBits
TotalTicksMask
ServerTicksUninitialized
Constructor & Destructor Documentation
HifiMoveList::HifiMoveList ()
Member Function Documentation
void HifiMoveList::advanceMove () virtual
Implements MoveList.
Referenced by onAdvanceObjects().
void HifiMoveList::clientReadMovePacket (BitStream *) virtual
Implements MoveList.
Referenced by init().
void HifiMoveList::clientWriteMovePacket (BitStream * bstream) virtual
Implements MoveList.
Referenced by init().
U32 HifiMoveList::getMoves (Move ** , U32 * numMoves) virtual
Reimplemented from MoveList.
Referenced by init().
S32 HifiMoveList::getServerTicks (U32 serverTickNum) protected
Referenced by onAdvanceObjects().
void HifiMoveList::ghostPreRead (NetObject * , bool newGhost) virtual
Reimplemented from MoveList.
Referenced by init().
void HifiMoveList::ghostReadExtra (NetObject * , BitStream * , bool newGhost) virtual
Reimplemented from MoveList.
Referenced by init().
void HifiMoveList::init () inline virtual
Reimplemented from MoveList.
References clientReadMovePacket(), clientWriteMovePacket(), getMoves(), ghostPreRead(), ghostReadExtra(), markControlDirty(), mTotalServerTicks, serverReadMovePacket(), ServerTicksUninitialized, and serverWriteMovePacket().
void HifiMoveList::markControlDirty () virtual
Reimplemented from MoveList.
Referenced by init().
void HifiMoveList::onAdvanceObjects () inline virtual
Implements MoveList.
References advanceMove(), getServerTicks(), MoveList::mFirstMoveIndex, mLastSentMove, MoveList::mMoveVec, resetMoveList(), Vector< T >::size(), and updateClientServerTickDiff().
void HifiMoveList::resetMoveList () protected
Referenced by onAdvanceObjects().
void HifiMoveList::serverReadMovePacket (BitStream * bstream) virtual
Implements MoveList.
Referenced by init().
bool HifiMoveList::serverTicksInitialized () inline protected
References mTotalServerTicks, and ServerTicksUninitialized.
void HifiMoveList::serverWriteMovePacket (BitStream *) virtual
Implements MoveList.
Referenced by init().
void HifiMoveList::updateClientServerTickDiff (S32 & tickDiff) protected
Referenced by onAdvanceObjects().
Member Data Documentation
F32 HifiMoveList::mAvgMoveQueueSize protected
U32 HifiMoveList::mLastSentMove protected
Referenced by onAdvanceObjects().
U32 HifiMoveList::mMaxMoveListSize protected
F32 HifiMoveList::mMoveListSizeSlack protected
F32 HifiMoveList::mSmoothMoveAvg protected
bool HifiMoveList::mSuppressMove protected
U32 HifiMoveList::mTargetMoveListSize protected
U32 HifiMoveList::mTotalServerTicks protected
Referenced by init(), and serverTicksInitialized().
Copyright © GarageGames, LLC. All Rights Reserved.