PostEffect Class Reference
Main Modules Class List Namespace List Online
PostEffect Class Reference
#include <postFx/postEffect.h>
Classes
class EffectConst
Public Types
enum { NumTextures = 8 }
enum PostEffectRequirements {
RequiresDepth = BIT(0),
RequiresNormals = BIT(1),
RequiresLightInfo = BIT(2)
}
Public Types inherited from SimGroup
typedef SimSet Parent
Public Types inherited from SimSet
typedef SimObject Parent
enum SetModification {
SetCleared,
SetObjectAdded,
SetObjectRemoved
}
typedef Signal< void(SetModification modification, SimSet *set, SimObject *object) > SetModificationSignal
Signal for letting observers know when objects are added to or removed from the set.
typedef SimObjectList::iterator iterator
typedef SimObjectList::value_type value
Public Types inherited from SimObject
typedef ConsoleObject Parent
enum WriteFlags {
SelectedOnly = BIT(0),
NoName = BIT(1),
IgnoreCanSave = BIT(2)
}
Flags passed to SimObject::write.
Public Types inherited from EngineObject
typedef void(* DebugEnumInstancesCallback) (EngineObject *)
Type of callback function for iterating over EngineObject instances.
Public Member Functions
PostEffect ()
Constructor.
virtual ~PostEffect ()
Destructor.
void clearShaderMacros ()
DECLARE_CONOBJECT (PostEffect)
void disable ()
bool dumpShaderDisassembly (String &outFilename) const
Dump the shader disassembly to a temporary text file.
void enable ()
F32 getAspectRatio () const
F32 getPriority () const
const String & getRenderBin () const
PFXRenderTime getRenderTime () const
SimSet * getSet () const
Returns the SimSet which contains all PostEffects.
bool isEnabled () const
bool isOneFrameOnly ()
bool isOnThisFrame ()
bool isSkipped () const
Is set to skip rendering.
virtual bool onAdd ()
Called when the object is added to the sim.
virtual void onRemove ()
Called when the object is removed from the sim.
virtual void process (const SceneRenderState *state, GFXTexHandle &inOutTex, const RectI *inTexViewport=NULL)
void reload ()
bool removeShaderMacro (const String &name)
void setOneFrameOnly (bool enabled)
void setOnThisFrame (bool enabled)
void setShaderConst (const String &name, const String &val)
void setShaderMacro (const String &name, const String &value=String::EmptyString)
void setSkip (bool skip)
Set the effect to skip rendering.
void setTexture (U32 index, const String &filePath)
Callbacks
DECLARE_CALLBACK (void, onAdd,())
DECLARE_CALLBACK (void, preProcess,())
DECLARE_CALLBACK (void, setShaderConsts,())
DECLARE_CALLBACK (bool, onEnabled,())
DECLARE_CALLBACK (void, onDisabled,())
Public Member Functions inherited from SimGroup
~SimGroup ()
void addObject (SimObject *object, SimObjectId id)
void addObject (SimObject *object, const char *name)
virtual void addObject (SimObject *object)
Add the given object to the set.
virtual void clear ()
Remove all objects from this set.
virtual SimGroup * clone ()
Return a shallow copy of this object.
DECLARE_CONOBJECT (SimGroup)
virtual SimGroup * deepClone ()
Return a deep copy of this object.
virtual SimObject * findObject (const char *name)
Find a named sub-object of this object.
virtual void popObject ()
Remove an object from the end of the list.
virtual bool processArguments (S32 argc, ConsoleValueRef *argv)
Process constructor options. (ie, new SimObject(1,2,3))
virtual void pushObject (SimObject *object)
Add the given object to the end of the object list of this set.
virtual void removeObject (SimObject *object)
Remove the given object from the set.
Public Member Functions inherited from SimSet
SimSet ()
~SimSet ()
virtual void addTamlChild (SimObject *pSimObject)
Called when Taml attempts to populate an objects children during a read.
void callOnChildren (const String &method, S32 argc, ConsoleValueRef argv[], bool executeOnChildGroups=true)
DECLARE_CONOBJECT (SimSet)
SimObject * findObject (SimObject *object)
Find the given object in this set.
template<class T >
void findObjectByCallback (bool(*fn)(T *), Vector< T * > &foundObjects)
Add all child objects (including children of children) to the foundObjects Vector which are of type T and for which DecideAddObjectCallback return true;.
virtual SimObject * findObjectByInternalName (StringTableEntry internalName, bool searchChildren=false)
SimObject * findObjectByLineNumber (const char *fileName, S32 declarationLine, bool searchChildren=false)
template<class T >
void findObjectByType (Vector< T * > &foundObjects)
Add all child objects (including children of children) to the foundObjects Vector which are of type T.
SimObject * getRandom ()
const SetModificationSignal & getSetModificationSignal () const
Return the signal that is triggered when an object is added to or removed from the set.
SetModificationSignal & getSetModificationSignal ()
virtual SimObject * getTamlChild (const U32 childIndex) const
Called when Taml attempts to compile a list of children.
virtual U32 getTamlChildCount (void) const
Called when Taml attempts to compile a list of children.
void lock ()
virtual void onDeleteNotify (SimObject *object)
Called when a SimObject is deleted.
virtual bool readObject (Stream *stream)
U32 sizeRecursive ()
Return the number of objects in this set as well as all sets that are contained in this set and its children.
void unlock ()
virtual void write (Stream &stream, U32 tabStop, U32 flags=0)
Output the TorqueScript to recreate this object.
virtual bool writeObject (Stream *stream)
virtual bool acceptsAsChild (SimObject *object) const
Return true if this set accepts the given object as a child.
void deleteAllObjects ()
Deletes all the objects in the set.
void bringObjectToFront (SimObject *obj)
void pushObjectToBack (SimObject *obj)
void scriptSort (const String &scriptCallbackFn)
Performs a sort of the objects in the set using a script callback function to do the comparison.
SimObject * front ()
SimObject * first ()
SimObject * last ()
bool empty () const
S32 size () const
iterator begin ()
iterator end ()
value operator[] (S32 index)
iterator find (iterator first, iterator last, SimObject *obj)
iterator find (SimObject *obj)
virtual bool reOrder (SimObject *obj, SimObject *target=0)
Reorder the position of "obj" to either be the last object in the list or, if "target" is given, to come before "target" in the list of children.
SimObject * at (S32 index) const
Return the object at the given index.
Public Member Functions inherited from SimObject
virtual void copyTo (SimObject *object)
Copy SimObject to another SimObject (Originally designed for T2D).
DECLARE_CONOBJECT (SimObject)
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
virtual void getConsoleMethodData (const char *fname, S32 routingId, S32 *type, S32 *minArgs, S32 *maxArgs, void **callback, const char **usage)
Namespace * getNamespace ()
Return the object's namespace.
StringTableEntry getProgenitorFile (void) const
virtual bool handlesConsoleMethod (const char *fname, S32 *routingId)
void setProgenitorFile (const char *pFile)
const char * tabComplete (const char *prevText, S32 baseLen, bool)
Get next matching item in namespace.
virtual bool writeField (StringTableEntry fieldname, const char *value)
Determine whether or not a field should be written.
virtual void writeFields (Stream &stream, U32 tabStop)
Write the fields of this object in TorqueScript.
void setCanSaveDynamicFields (bool bCanSave)
Set whether fields created at runtime should be saved. Default is true.
bool getCanSaveDynamicFields ()
Get whether fields created at runtime should be saved. Default is true.
SimObject * getCopySource () const
Return the object that this object is copying fields from.
void setCopySource (SimObject *object)
Set the object that this object should be copying fields from.
void assignFieldsFrom (SimObject *obj)
Copy fields from another object onto this one.
void assignDynamicFieldsFrom (SimObject *obj)
Copy dynamic fields from another object onto this one.
Notify * removeNotify (void *ptr, Notify::Type)
Remove a notification from the list.
void deleteNotify (SimObject *obj)
Notify an object when we are deleted.
void clearNotify (SimObject *obj)
Notify an object when we are cleared.
void clearAllNotifications ()
Remove all notifications for this object.
void processDeleteNotifies ()
Send out deletion notifications.
void registerReference (SimObject **obj)
Register a reference to this object.
void unregisterReference (SimObject **obj)
Unregister a reference to this object.
SimPersistID * getPersistentId () const
Return the persistent ID assigned to this object or NULL.
SimPersistID * getOrCreatePersistentId ()
Return the persistent ID assigned to this object or assign one to it if it has none.
StringTableEntry getClassNamespace () const
Return name of class namespace set on this object.
StringTableEntry getSuperClassNamespace () const
Return name of superclass namespace set on this object.
void setClassNamespace (const char *classNamespace)
void setSuperClassNamespace (const char *superClassNamespace)
const char * getDataField (StringTableEntry slotName, const char *array)
Get the value of a field on the object.
void setDataField (StringTableEntry slotName, const char *array, const char *value)
Set the value of a field on the object.
const char * getPrefixedDataField (StringTableEntry fieldName, const char *array)
void setPrefixedDataField (StringTableEntry fieldName, const char *array, const char *value)
const char * getPrefixedDynamicDataField (StringTableEntry fieldName, const char *array, const S32 fieldType=-1)
void setPrefixedDynamicDataField (StringTableEntry fieldName, const char *array, const char *value, const S32 fieldType=-1)
StringTableEntry getDataFieldPrefix (StringTableEntry fieldName)
U32 getDataFieldType (StringTableEntry slotName, const char *array)
Get the type of a field on the object.
void setDataFieldType (const U32 fieldTypeId, StringTableEntry slotName, const char *array)
Set the type of a dynamic field on the object.
void setDataFieldType (const char *typeName, StringTableEntry slotName, const char *array)
SimFieldDictionary * getFieldDictionary ()
Get reference to the dictionary containing dynamic fields.
virtual StringTableEntry getComponentName ()
void setInternalName (const char *newname)
These functions support internal naming that is not namespace bound for locating child controls in a generic way.
StringTableEntry getInternalName () const
Get the internal name of this control.
void setOriginalName (const char *originalName)
Set the original name of this control.
StringTableEntry getOriginalName () const
Get the original name of this control.
void setFilename (const char *file)
These functions allow you to set and access the filename where this object was created.
StringTableEntry getFilename () const
Get the filename.
void setDeclarationLine (U32 lineNumber)
These functions are used to track the line number (1-based) on which the object was created if it was loaded from script.
S32 getDeclarationLine () const
Get the declaration line number.
virtual bool save (const char *pcFilePath, bool bOnlySelected=false, const char *preappend=NULL)
Save object as a TorqueScript File.
virtual bool isMethod (const char *methodName)
Check if a method exists in the objects current namespace.
virtual bool isField (const char *fieldName, bool includeStatic=true, bool includeDynamic=true)
Return true if the field is defined on the object.
SimObjectId getId () const
Return the unique numeric object ID.
const char * getIdString () const
Return the object ID as a string.
StringTableEntry getName () const
Return the name of this object.
SimGroup * getGroup () const
Return the SimGroup that this object is contained in.
void assignName (const char *name)
Assign the given name to this object.
void setId (SimObjectId id)
bool isChildOfGroup (SimGroup *pGroup)
bool isProperlyAdded () const
bool isDeleted () const
bool isRemoved () const
virtual bool isLocked () const
virtual void setLocked (bool b)
virtual bool isHidden () const
virtual void setHidden (bool b)
bool isSelected () const
bool isExpanded () const
bool isEditorOnly () const
bool isNameChangeAllowed () const
bool isAutoDeleted () const
void setSelected (bool sel)
void setExpanded (bool exp)
void setModDynamicFields (bool dyn)
void setModStaticFields (bool sta)
bool canModDynamicFields ()
bool canModStaticFields ()
void setAutoDelete (bool val)
void setEditorOnly (bool val)
void setNameChangeAllowed (bool val)
bool getCanSave () const
Returns boolean specifying if the object can be serialized.
virtual void setCanSave (bool val)
Set serialization flag.
bool isSelectedRecursive () const
Returns true if this object is selected or any group it is a member of is.
SimObject ()
virtual ~SimObject ()
virtual void onGroupAdd ()
Called when the object is added to a SimGroup.
virtual void onGroupRemove ()
Called when the object is removed from a SimGroup.
virtual void onNameChange (const char *name)
Called when the object's name is changed.
virtual void onPostAdd ()
Called when the adding of the object to the sim is complete, all sub-objects have been processed as well.
virtual void onStaticModified (const char *slotName, const char *newValue=NULL)
Specifically, these are called by setDataField when a static or dynamic field is modified, see the console details.
virtual void onDynamicModified (const char *slotName, const char *newValue=NULL)
Called when a dynamic field is modified.
virtual void inspectPreApply ()
Called before any property of the object is changed in the world editor.
virtual void inspectPostApply ()
Called after any property of the object is changed in the world editor.
virtual void onEditorEnable ()
Called when the editor is activated.
virtual void onEditorDisable ()
Called when the editor is deactivated.
bool registerObject ()
Register an object with the object system.
bool registerObject (U32 id)
Register the object, forcing the id.
bool registerObject (const char *name)
Register the object, assigning the name.
bool registerObject (const char *name, U32 id)
Register the object, assigning a name and ID.
void unregisterObject ()
Unregister the object from Sim.
void deleteObject ()
Unregister, mark as deleted, and free the object.
void safeDeleteObject ()
Performs a safe delayed delete of the object using a sim event.
bool addToSet (SimObjectId)
bool addToSet (const char *)
bool removeFromSet (SimObjectId)
bool removeFromSet (const char *)
virtual String describeSelf () const
Return a textual description of the object.
void dumpToConsole (bool includeFunctions=true)
Dump the contents of this object to the console.
virtual void dumpClassHierarchy ()
added this so that you can print the entire class hierarchy, including script objects,
virtual void dumpGroupHierarchy ()
Print the SimGroup hierarchy of this object to the console.
Public Member Functions inherited from ConsoleObject
ConsoleObject ()
virtual AbstractClassRep * getClassRep () const
Gets the ClassRep.
const AbstractClassRep::Field * findField (StringTableEntry fieldName) const
Get a reference to a field by name.
bool setField (const char *fieldName, const char *value)
Set the value of a field.
void logMessage (const char *fmt,...) const
Logs with Con::printf.
void logWarning (const char *fmt,...) const
Logs with Con::warnf.
void logError (const char *fmt,...) const
Logs with Con::errorf.
const AbstractClassRep::FieldList & getFieldList () const
Get a list of all the fields. This information cannot be modified.
AbstractClassRep::FieldList & getModifiableFieldList ()
Get a list of all the fields, set up so we can modify them.
bool & getDynamicGroupExpand ()
Get a handle to a boolean telling us if we expanded the dynamic group.
S32 getClassId (U32 netClassGroup) const
Get our network-layer class id.
StringTableEntry getClassName () const
Get our compiler and platform independent class name.
Public Member Functions inherited from EngineObject
EngineObject ()
virtual ~EngineObject ()
DECLARE_ABSTRACT_CLASS (EngineObject, void)
DECLARE_INSCOPE (_GLOBALSCOPE)
IEngineObjectPool * getEngineObjectPool () const
Return the pool of EngineObjects to which this object belongs.
void operator delete (void *ptr)
Release the given object's memory in the pool it has been allocated from.
void * operator new (size_t size)
void * operator new (size_t size, IEngineObjectPool *pool)
void * operator new (size_t size TORQUE_TMM_ARGS_DECL)
Allocate a new object in the default object pool.
void * operator new (size_t size, IEngineObjectPool *pool TORQUE_TMM_ARGS_DECL)
Allocate a new object in the given object pool.
void * operator new (size_t size, void *ptr)
Placement new.
Public Member Functions inherited from StrongRefBase
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Static Public Member Functions
static void initPersistFields ()
Static Public Member Functions inherited from SimObject
static SimObject * __findObject (const char *id)
static const char * __getObjectId (ConsoleObject *object)
static void initPersistFields ()
static void setForcedId (SimObjectId id)
Force an Id on the next registered object.
Static Public Member Functions inherited from ConsoleObject
static const char * __category ()
static const char * __description ()
static void consoleInit ()
Register global constant variables and do other one-time initialization tasks in a subclass of ConsoleObject.
static void initPersistFields ()
Register dynamic fields in a subclass of ConsoleObject.
static const char * lookupClassName (const U32 in_classTag)
Get the classname from a class tag.
static ConsoleObject * create (const char *in_pClassName)
static ConsoleObject * create (const U32 groupId, const U32 typeId, const U32 in_classId)
static void addGroup (const char *in_pGroupname, const char *in_pGroupDocs=NULL)
Mark the beginning of a group of fields.
static void endGroup (const char *in_pGroupname)
Mark the end of a group of fields.
static void addArray (const char *arrayName, S32 count)
Marks the start of a fixed size array of fields.
static void endArray (const char *arrayName)
Marks the end of an array of fields.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a complex field.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::WriteDataNotify in_writeDataFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, const char *in_pFieldDocs, U32 flags=0)
Register a simple field.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::WriteDataNotify in_writeDataFn, const char *in_pFieldDocs, U32 flags=0)
static void addFieldV (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, TypeValidator *v, const char *in_pFieldDocs=NULL)
Register a validated field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, AbstractClassRep::WriteDataNotify in_writeDataFn=&defaultProtectedWriteFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a complex protected field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, AbstractClassRep::WriteDataNotify in_writeDataFn=&defaultProtectedWriteFn, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a simple protected field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addDeprecatedField (const char *fieldName)
Add a deprecated field.
static bool removeField (const char *in_pFieldname)
Remove a field.
static AbstractClassRep * getStaticClassRep ()
Get the abstract class information for this class.
static AbstractClassRep * getParentStaticClassRep ()
Get the abstract class information for this class's superclass.
static ConsoleObject * __findObject (const char *)
static const char * __getObjectId (ConsoleObject *)
Static Public Member Functions inherited from EngineObject
static void debugDumpInstances ()
Dump describeSelf()s of all live ConsoleObjects to the console.
static void debugEnumInstances (const std::type_info &type, DebugEnumInstancesCallback callback)
Call the given callback for all instances of the given type.
static void debugEnumInstances (const char *className, DebugEnumInstancesCallback callback)
Same as above but uses an export class name and also includes inheritance (i.e.
Protected Types
typedef HashTable< StringCase, EffectConst * > EffectConstTable
Protected Types inherited from EngineObject
typedef ::FalseType __IsDisposableType
typedef ::FalseType __IsSingletonType
Protected Member Functions
void _checkRequirements ()
void _cleanTargets (bool recurse=false)
GFXTextureObject * _getTargetTexture (U32 index)
void _onLMActivate (const char *, bool activate)
Called from the light manager activate signal.
void _onTextureEvent (GFXTexCallbackCode code)
We handle texture events to release named rendered targets.
virtual void _setupConstants (const SceneRenderState *state)
virtual void _setupStateBlock (const SceneRenderState *state)
virtual void _setupTarget (const SceneRenderState *state, bool *outClearTarget)
virtual void _setupTexture (U32 slot, GFXTexHandle &inputTex, const RectI *inTexViewport)
virtual void _setupTransforms ()
void _updateConditioners ()
virtual void _updateScreenGeometry (const Frustum &frustum, GFXVertexBufferHandle< PFXVertex > *outVB)
Protected Member Functions inherited from SimSet
DECLARE_CALLBACK (void, onObjectAdded,(SimObject *object))
DECLARE_CALLBACK (void, onObjectRemoved,(SimObject *object))
Protected Member Functions inherited from SimObject
virtual void _destroySelf ()
Subclasses should overload this method instead of the public destroySelf().
virtual String _getLogMessage (const char *fmt, va_list args) const
We can provide more detail, like object name and id.
virtual void _onSelected ()
Called when the object is selected in the editor.
virtual void _onUnselected ()
Called when the object is unselected in the editor.
object incRefCount ()
virtual void onTamlAddParent (SimObject *pParentObject)
Called after Taml has finished reading the object and has added the object to any parent.
virtual void onTamlCustomRead (const TamlCustomNodes &customNodes)
Called during the reading of the object to allow custom properties to be read.
virtual void onTamlCustomWrite (TamlCustomNodes &customNodes)
Called during the writing of the object to allow custom properties to be written.
virtual void onTamlPostRead (const TamlCustomNodes &customNodes)
Called after Taml has finished reading the object.
virtual void onTamlPostWrite (void)
Called after Taml has finished writing the object.
virtual void onTamlPreRead (void)
Called prior to Taml reading the object.
virtual void onTamlPreWrite (void)
Taml callbacks.
object registerObject ()
void linkNamespaces ()
Perform namespace linking on this object.
void unlinkNamespaces ()
Undo namespace linking on this object.
Protected Member Functions inherited from ConsoleObject
ConsoleObject (const ConsoleObject &)
Protected Member Functions inherited from EngineObject
object incRefCount ()
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Static Protected Member Functions
static bool _setIsEnabled (void *object, const char *index, const char *data)
Protected set method for toggling the enabled state.
Static Protected Member Functions inherited from SimObject
static bool _setPersistentID (void *object, const char *index, const char *data)
Static Protected Member Functions inherited from EngineObject
static void * _allocateObject (size_t size, IEngineObjectPool *pool TORQUE_TMM_ARGS_DECL)
Protected Attributes
GFXShaderConstHandle * mAccumTimeSC
NamedTexTarget * mActiveNamedTarget [NumTextures]
GFXTextureObject * mActiveTextures [NumTextures]
RectI mActiveTextureViewport [NumTextures]
bool mAllowReflectPass
GFXShaderConstHandle * mAmbientColorSC
GFXShaderConstHandle * mCameraForwardSC
GFXShaderConstHandle * mDeltaTimeSC
EffectConstTable mEffectConsts
bool mEnabled
True if the effect has been enabled by the manager.
GFXShaderConstHandle * mEyePosSC
GFXShaderConstHandle * mFogColorSC
GFXShaderConstHandle * mFogDataSC
GFXShaderConstHandle * mInvCameraMatSC
GFXShaderConstHandle * mInvNearFarSC
bool mIsValid
This is true if the effect has been succesfully initialized and all requirements are met for use.
GFXShaderConstHandle * mLightDirectionSC
GFXShaderConstHandle * mMatPrevScreenToWorldSC
GFXShaderConstHandle * mMatScreenToWorldSC
GFXShaderConstHandle * mMatWorldToScreenSC
NamedTexTarget mNamedTarget
NamedTexTarget mNamedTargetDepthStencil
GFXShaderConstHandle * mNearFarSC
bool mOneFrameOnly
GFXShaderConstHandle * mOneOverRTSizeSC
bool mOnThisFrame
GFXShaderConstHandle * mProjectionOffsetSC
String mRenderBin
F32 mRenderPriority
GFXShaderConstHandle * mRenderTargetParamsSC [NumTextures]
PFXRenderTime mRenderTime
GFXShaderConstHandle * mRTSizeSC
GFXShaderConstHandle * mScreenSunPosSC
GFXShaderRef mShader
GFXShaderConstBufferRef mShaderConsts
Vector< GFXShaderMacro > mShaderMacros
String mShaderName
U32 mShaderReloadKey
bool mSkip
Skip processing of this PostEffect and its children even if its parent is enabled.
GFXStateBlockRef mStateBlock
GFXStateBlockData * mStateBlockData
GFXTextureTargetRef mTarget
PFXTargetClear mTargetClear
ColorF mTargetClearColor
The color to prefill the named target when first created by the effect.
GFXTexHandle mTargetDepthStencil
String mTargetDepthStencilName
GFXFormat mTargetFormat
String mTargetName
Point2F mTargetScale
If mTargetSize is zero then this scale is used to make a relative texture size to the active render target.
Point2I mTargetSize
If non-zero this is used as the absolute texture target size.
GFXTexHandle mTargetTex
PFXTargetViewport mTargetViewport
GFXShaderConstHandle * mTargetViewportSC
FileName mTexFilename [NumTextures]
GFXShaderConstHandle * mTexSizeSC [NumTextures]
GFXTexHandle mTextures [NumTextures]
bool mUpdateShader
If true update the shader.
GFXShaderConstHandle * mViewportOffsetSC
GFXShaderConstHandle * mWaterColorSC
GFXShaderConstHandle * mWaterDepthGradMaxSC
GFXShaderConstHandle * mWaterFogDataSC
GFXShaderConstHandle * mWaterFogPlaneSC
GFXShaderConstHandle * mWorldToScreenScaleSC
Protected Attributes inherited from SimSet
void * mMutex
SetModificationSignal mSetModificationSignal
Signal that is triggered when objects are added or removed from the set.
SimObjectList objectList
Protected Attributes inherited from SimObject
DEFINE_CREATE_METHOD
SimObjectId mId
Id number for this object.
StringTableEntry mInternalName
Internal name assigned to the object. Not set by default.
return object
bool mCanSaveFieldDictionary
Whether dynamic fields should be saved out in serialization. Defaults to true.
SimPersistID * mPersistentId
Persistent ID assigned to this object.
Namespace * mNameSpace
The namespace in which method lookup for this object begins.
StringTableEntry mClassName
Name of namespace to use as class namespace.
StringTableEntry mSuperClassName
Name of namespace to use as class super namespace.
Protected Attributes inherited from EngineObject
DEFINE_CREATE_METHOD
return object
Protected Attributes inherited from StrongRefBase
U32 mRefCount
reference counter for StrongRefPtr objects
Additional Inherited Members
Public Attributes inherited from EngineObject
DECLARE_INSTANTIABLE
Static Public Attributes inherited from ConsoleObject
static const bool __smIsDatablock = false
Subclasses of ConsoleObjects that are datablocks should redefine this static member variable and set it to true.
Static Protected Attributes inherited from SimObject
static SimObjectId smForcedId
The Id to force upon the object. Poor object.
static bool smForceId
Force a registered object to use the given Id. Cleared upon use.
Member Typedef Documentation
typedef HashTable<StringCase,EffectConst*> PostEffect::EffectConstTable protected
Member Enumeration Documentation
anonymous enum
Enumerator
NumTextures
enum PostEffect::PostEffectRequirements
Enumerator
RequiresDepth
RequiresNormals
RequiresLightInfo
Constructor & Destructor Documentation
PostEffect::PostEffect ()
Constructor.
Referenced by _onTextureEvent().
virtual PostEffect::~PostEffect () virtual
Destructor.
Referenced by _onTextureEvent().
Member Function Documentation
void PostEffect::_checkRequirements () protected
Referenced by _onTextureEvent().
void PostEffect::_cleanTargets (bool recurse = false) protected
Referenced by _onTextureEvent().
GFXTextureObject* PostEffect::_getTargetTexture (U32 index) protected
Referenced by _onTextureEvent().
void PostEffect::_onLMActivate (const char * , bool activate) inline protected
Called from the light manager activate signal.
See also
LightManager::addActivateCallback
void PostEffect::_onTextureEvent (GFXTexCallbackCode code) inline protected
We handle texture events to release named rendered targets.
See also
GFXTextureManager::addEventDelegate
References _checkRequirements(), _cleanTargets(), _getTargetTexture(), _updateConditioners(), DECLARE_CALLBACK(), DECLARE_CONOBJECT(), disable(), dumpShaderDisassembly(), enable(), getSet(), initPersistFields(), NamedTexTarget::isRegistered(), onAdd(), onRemove(), PostEffect(), process(), reload(), and ~PostEffect().
static bool PostEffect::_setIsEnabled (void * object, const char * index, const char * data) static protected
Protected set method for toggling the enabled state.
virtual void PostEffect::_setupConstants (const SceneRenderState * state) protected virtual
virtual void PostEffect::_setupStateBlock (const SceneRenderState * state) protected virtual
virtual void PostEffect::_setupTarget (const SceneRenderState * state, bool * outClearTarget) protected virtual
virtual void PostEffect::_setupTexture (U32 slot, GFXTexHandle & inputTex, const RectI * inTexViewport) protected virtual
virtual void PostEffect::_setupTransforms () protected virtual
void PostEffect::_updateConditioners () protected
Referenced by _onTextureEvent().
virtual void PostEffect::_updateScreenGeometry (const Frustum & frustum, GFXVertexBufferHandle< PFXVertex > * outVB) protected virtual
void PostEffect::clearShaderMacros ()
Referenced by getPriority().
PostEffect::DECLARE_CALLBACK (void , onAdd , ())
Referenced by _onTextureEvent().
PostEffect::DECLARE_CALLBACK (void , preProcess , ())
PostEffect::DECLARE_CALLBACK (void , setShaderConsts , ())
PostEffect::DECLARE_CALLBACK (bool , onEnabled , ())
PostEffect::DECLARE_CALLBACK (void , onDisabled , ())
PostEffect::DECLARE_CONOBJECT (PostEffect)
Referenced by _onTextureEvent().
void PostEffect::disable ()
Referenced by _onTextureEvent().
bool PostEffect::dumpShaderDisassembly (String & outFilename) const
Dump the shader disassembly to a temporary text file.
Returns true and sets outFilename to the file if successful.
Referenced by _onTextureEvent().
void PostEffect::enable ()
Referenced by _onTextureEvent().
F32 PostEffect::getAspectRatio () const
Referenced by isOneFrameOnly().
F32 PostEffect::getPriority () const inline
References clearShaderMacros(), String::EmptyString, mRenderPriority, removeShaderMacro(), setShaderConst(), setShaderMacro(), and setTexture().
const String& PostEffect::getRenderBin () const inline
References mRenderBin.
PFXRenderTime PostEffect::getRenderTime () const inline
References mRenderTime.
SimSet* PostEffect::getSet () const
Returns the SimSet which contains all PostEffects.
Referenced by _onTextureEvent().
static void PostEffect::initPersistFields () static
Referenced by _onTextureEvent().
bool PostEffect::isEnabled () const inline
References mEnabled.
bool PostEffect::isOneFrameOnly () inline
References getAspectRatio(), and mOneFrameOnly.
bool PostEffect::isOnThisFrame () inline
References mOnThisFrame.
bool PostEffect::isSkipped () const inline
Is set to skip rendering.
References mSkip.
virtual bool PostEffect::onAdd () virtual
Called when the object is added to the sim.
Reimplemented from SimObject.
Referenced by _onTextureEvent().
virtual void PostEffect::onRemove () virtual
Called when the object is removed from the sim.
Reimplemented from SimGroup.
Referenced by _onTextureEvent().
virtual void PostEffect::process (const SceneRenderState * state, GFXTexHandle & inOutTex, const RectI * inTexViewport = NULL) virtual
Referenced by _onTextureEvent().
void PostEffect::reload ()
Referenced by _onTextureEvent().
bool PostEffect::removeShaderMacro (const String & name)
Referenced by getPriority().
void PostEffect::setOneFrameOnly (bool enabled) inline
void PostEffect::setOnThisFrame (bool enabled) inline
void PostEffect::setShaderConst (const String & name, const String & val)
Referenced by getPriority().
void PostEffect::setShaderMacro (const String & name, const String & value = String::EmptyString)
Referenced by getPriority().
void PostEffect::setSkip (bool skip) inline
Set the effect to skip rendering.
void PostEffect::setTexture (U32 index, const String & filePath)
Referenced by getPriority().
Member Data Documentation
GFXShaderConstHandle* PostEffect::mAccumTimeSC protected
NamedTexTarget* PostEffect::mActiveNamedTarget[NumTextures] protected
GFXTextureObject* PostEffect::mActiveTextures[NumTextures] protected
RectI PostEffect::mActiveTextureViewport[NumTextures] protected
bool PostEffect::mAllowReflectPass protected
GFXShaderConstHandle* PostEffect::mAmbientColorSC protected
GFXShaderConstHandle* PostEffect::mCameraForwardSC protected
GFXShaderConstHandle* PostEffect::mDeltaTimeSC protected
EffectConstTable PostEffect::mEffectConsts protected
bool PostEffect::mEnabled protected
True if the effect has been enabled by the manager.
Referenced by isEnabled().
GFXShaderConstHandle* PostEffect::mEyePosSC protected
GFXShaderConstHandle* PostEffect::mFogColorSC protected
GFXShaderConstHandle* PostEffect::mFogDataSC protected
GFXShaderConstHandle* PostEffect::mInvCameraMatSC protected
GFXShaderConstHandle* PostEffect::mInvNearFarSC protected
bool PostEffect::mIsValid protected
This is true if the effect has been succesfully initialized and all requirements are met for use.
GFXShaderConstHandle* PostEffect::mLightDirectionSC protected
GFXShaderConstHandle* PostEffect::mMatPrevScreenToWorldSC protected
GFXShaderConstHandle* PostEffect::mMatScreenToWorldSC protected
GFXShaderConstHandle* PostEffect::mMatWorldToScreenSC protected
NamedTexTarget PostEffect::mNamedTarget protected
NamedTexTarget PostEffect::mNamedTargetDepthStencil protected
GFXShaderConstHandle* PostEffect::mNearFarSC protected
bool PostEffect::mOneFrameOnly protected
Referenced by isOneFrameOnly().
GFXShaderConstHandle* PostEffect::mOneOverRTSizeSC protected
bool PostEffect::mOnThisFrame protected
Referenced by isOnThisFrame().
GFXShaderConstHandle* PostEffect::mProjectionOffsetSC protected
String PostEffect::mRenderBin protected
Referenced by getRenderBin().
F32 PostEffect::mRenderPriority protected
Referenced by getPriority().
GFXShaderConstHandle* PostEffect::mRenderTargetParamsSC[NumTextures] protected
PFXRenderTime PostEffect::mRenderTime protected
Referenced by getRenderTime().
GFXShaderConstHandle* PostEffect::mRTSizeSC protected
GFXShaderConstHandle* PostEffect::mScreenSunPosSC protected
GFXShaderRef PostEffect::mShader protected
GFXShaderConstBufferRef PostEffect::mShaderConsts protected
Vector<GFXShaderMacro> PostEffect::mShaderMacros protected
String PostEffect::mShaderName protected
U32 PostEffect::mShaderReloadKey protected
bool PostEffect::mSkip protected
Skip processing of this PostEffect and its children even if its parent is enabled.
Parent and sibling PostEffects in the chain are still processed. This is intended for debugging purposes.
Referenced by isSkipped().
GFXStateBlockRef PostEffect::mStateBlock protected
GFXStateBlockData* PostEffect::mStateBlockData protected
GFXTextureTargetRef PostEffect::mTarget protected
PFXTargetClear PostEffect::mTargetClear protected
ColorF PostEffect::mTargetClearColor protected
The color to prefill the named target when first created by the effect.
GFXTexHandle PostEffect::mTargetDepthStencil protected
String PostEffect::mTargetDepthStencilName protected
GFXFormat PostEffect::mTargetFormat protected
String PostEffect::mTargetName protected
Point2F PostEffect::mTargetScale protected
If mTargetSize is zero then this scale is used to make a relative texture size to the active render target.
Point2I PostEffect::mTargetSize protected
If non-zero this is used as the absolute texture target size.
See also
mTargetScale
GFXTexHandle PostEffect::mTargetTex protected
PFXTargetViewport PostEffect::mTargetViewport protected
GFXShaderConstHandle* PostEffect::mTargetViewportSC protected
FileName PostEffect::mTexFilename[NumTextures] protected
GFXShaderConstHandle* PostEffect::mTexSizeSC[NumTextures] protected
GFXTexHandle PostEffect::mTextures[NumTextures] protected
bool PostEffect::mUpdateShader protected
If true update the shader.
GFXShaderConstHandle* PostEffect::mViewportOffsetSC protected
GFXShaderConstHandle* PostEffect::mWaterColorSC protected
GFXShaderConstHandle* PostEffect::mWaterDepthGradMaxSC protected
GFXShaderConstHandle* PostEffect::mWaterFogDataSC protected
GFXShaderConstHandle* PostEffect::mWaterFogPlaneSC protected
GFXShaderConstHandle* PostEffect::mWorldToScreenScaleSC protected
Copyright © GarageGames, LLC. All Rights Reserved.