WindowInputGenerator Class Reference
Main Modules Class List Namespace List Online
WindowInputGenerator Class Reference
#include <windowManager/windowInputGenerator.h>
Classes
struct AccKeyMap
Accelerator key map.
Public Member Functions
WindowInputGenerator (PlatformWindow *window)
virtual ~WindowInputGenerator ()
void addAcceleratorKey (void *hnd, const String &cmd, U32 keycode, U32 modifier)
bool lastKeyWasGlobalActionMap () const
Tells us if the last key was used within the global action map.
void removeAcceleratorKey (void *hnd, U32 keycode, U32 modifier)
void removeAcceleratorKeys (void *hnd)
void setInputController (IProcessInput *inputController)
bool wantAsKeyboardEvent (U32 modifiers, U32 key)
Returns true if the given keypress event should be send as a raw keyboard event even if it maps to a character input event.
Protected Member Functions
void generateInputEvent (InputEventInfo &inputEvent)
void handleAppEvent (WindowId did, S32 event)
void handleCharInput (WindowId did, U32 modifier, U16 key)
void handleInputEvent (U32 deviceInst, F32 fValue, F32 fValue2, F32 fValue3, F32 fValue4, S32 iValue, U16 deviceType, U16 objType, U16 ascii, U16 objInst, U8 action, U8 modifier)
void handleKeyboard (WindowId did, U32 modifier, U32 action, U16 key)
void handleMouseButton (WindowId did, U32 modifier, U32 action, U16 button)
void handleMouseMove (WindowId did, U32 modifier, S32 x, S32 y, bool isRelative)
void handleMouseWheel (WindowId did, U32 modifier, S32 wheelDeltaX, S32 wheelDeltaY)
Protected Attributes
Vector< AccKeyMap > mAcceleratorMap
bool mClampToWindow
bool mFocused
We store this off to avoid polling the OS constantly.
IProcessInput * mInputController
Point2I mLastCursorPos
bool mLastPressWasGlobalActionMap
This tells us if the last key we pressed was used from the global action map.
F32 mPixelsPerMickey
This is the scale factor which relates mouse movement in pixels (one unit of mouse movement is a mickey) to units in the GUI.
PlatformWindow * mWindow
Constructor & Destructor Documentation
WindowInputGenerator::WindowInputGenerator (PlatformWindow * window)
virtual WindowInputGenerator::~WindowInputGenerator () virtual
Member Function Documentation
void WindowInputGenerator::addAcceleratorKey (void * hnd, const String & cmd, U32 keycode, U32 modifier) inline
References WindowInputGenerator::AccKeyMap::cmd, WindowInputGenerator::AccKeyMap::hnd, WindowInputGenerator::AccKeyMap::keyCode, WindowInputGenerator::AccKeyMap::modifier, and Vector< T >::push_back().
void WindowInputGenerator::generateInputEvent (InputEventInfo & inputEvent) protected
void WindowInputGenerator::handleAppEvent (WindowId did, S32 event) protected
void WindowInputGenerator::handleCharInput (WindowId did, U32 modifier, U16 key) protected
void WindowInputGenerator::handleInputEvent (U32 deviceInst, F32 fValue, F32 fValue2, F32 fValue3, F32 fValue4, S32 iValue, U16 deviceType, U16 objType, U16 ascii, U16 objInst, U8 action, U8 modifier) protected
void WindowInputGenerator::handleKeyboard (WindowId did, U32 modifier, U32 action, U16 key) protected
void WindowInputGenerator::handleMouseButton (WindowId did, U32 modifier, U32 action, U16 button) protected
void WindowInputGenerator::handleMouseMove (WindowId did, U32 modifier, S32 x, S32 y, bool isRelative) protected
void WindowInputGenerator::handleMouseWheel (WindowId did, U32 modifier, S32 wheelDeltaX, S32 wheelDeltaY) protected
bool WindowInputGenerator::lastKeyWasGlobalActionMap () const inline
Tells us if the last key was used within the global action map.
Returns
true if the key was a global action map key, false otherwise.
Note
Useful and currently used to tell if we just opened the console by using the console key. Currently this is used to fix a bug in SDL but it is not limited to that use.
References mLastPressWasGlobalActionMap.
void WindowInputGenerator::removeAcceleratorKey (void * hnd, U32 keycode, U32 modifier) inline
References Vector< T >::erase(), WindowInputGenerator::AccKeyMap::keyCode, and Vector< T >::size().
void WindowInputGenerator::removeAcceleratorKeys (void * hnd) inline
References Vector< T >::erase(), and Vector< T >::size().
void WindowInputGenerator::setInputController (IProcessInput * inputController) inline
References wantAsKeyboardEvent().
Referenced by PlatformWindow::setInputController().
bool WindowInputGenerator::wantAsKeyboardEvent (U32 modifiers, U32 key)
Returns true if the given keypress event should be send as a raw keyboard event even if it maps to a character input event.
Referenced by setInputController().
Member Data Documentation
Vector<AccKeyMap> WindowInputGenerator::mAcceleratorMap protected
bool WindowInputGenerator::mClampToWindow protected
bool WindowInputGenerator::mFocused protected
We store this off to avoid polling the OS constantly.
IProcessInput* WindowInputGenerator::mInputController protected
Point2I WindowInputGenerator::mLastCursorPos protected
bool WindowInputGenerator::mLastPressWasGlobalActionMap protected
This tells us if the last key we pressed was used from the global action map.
Referenced by lastKeyWasGlobalActionMap().
F32 WindowInputGenerator::mPixelsPerMickey protected
This is the scale factor which relates mouse movement in pixels (one unit of mouse movement is a mickey) to units in the GUI.
PlatformWindow* WindowInputGenerator::mWindow protected
Copyright © GarageGames, LLC. All Rights Reserved.