TSShape Class Reference
Main Modules Class List Namespace List Online
TSShape Class Reference
TSShape stores generic data for a 3space model.
#include <ts/tsShape.h>
Classes
struct ConvexHullAccelerator
struct Detail
Details are used for render detail selection.
struct LodPair
struct Node
Nodes hold the transforms in the shape's tree. They are the bones of the skeleton.
struct Object
Objects hold renderable items (in particular meshes).
struct ObjectState
Describes state of an individual object.
struct Sequence
A Sequence holds all the information necessary to perform a particular animation (sequence).
struct Trigger
When time on a sequence advances past a certain point, a trigger takes effect and changes one of the state variables to on or off.
Public Types
enum {
UniformScale = BIT(0),
AlignedScale = BIT(1),
ArbitraryScale = BIT(2),
Blend = BIT(3),
Cyclic = BIT(4),
MakePath = BIT(5),
HasTranslucency = BIT(6),
AnyScale = UniformScale | AlignedScale | ArbitraryScale
}
Public Member Functions
TSShape ()
~TSShape ()
PhysicsCollision * _buildColShapes (bool useVisibleMesh, const Point3F &scale, Vector< CollisionShapeInfo > *list, bool perMesh)
For internal use.
PhysicsCollision * buildColShape (bool useVisibleMesh, const Point3F &scale)
Builds a physics collision shape at the requested scale.
void buildColShapes (bool useVisibleMesh, const Point3F &scale, Vector< CollisionShapeInfo > *list)
Like buildColShape except we build one PhysicsCollision object per collision node.
bool buildConvexHull (S32 dl) const
bool checkSkip (S32 meshNum, S32 &curObject, S32 skipDL)
mem buffer transfer helper (indicate when we don't want to include a particular mesh/decal)
void computeAccelerator (S32 dl)
build LOS collision detail
void computeBounds (S32 dl, Box3F &bounds) const
void finalizeEditable ()
void findColDetails (bool useVisibleMesh, Vector< S32 > *outDetails, Vector< S32 > *outLOSDetails) const
Used to find collision detail meshes in the DTS.
void fixupOldSkins (S32 numMeshes, S32 numSkins, S32 numDetails, S32 *detFirstSkin, S32 *detailNumSkins)
bool getSequencesConstructed () const
void getVertexBuffer (TSVertexBufferHandle &vb, GFXBufferType bufferType)
Loads shape vertex data into specified buffer.
void init ()
void initMaterialList ()
you can swap in a new material list, but call this if you do
void initObjects ()
Inits object list (no geometry buffers)
void initVertexBufferPointers ()
Inits basic buffer pointers on load.
void initVertexBuffers ()
Initializes the main vertex buffer.
void initVertexFeatures ()
Called from init() to calcuate the GFX vertex features for all detail meshes in the shape.
bool preloadMaterialList (const Torque::Path &path)
called to preload and validate the materials in the mat list
void setSequencesConstructed (const bool c)
void setupBillboardDetails (const String &cachePath)
Collision Accelerators
For speeding up buildpolylist and support calls.
ConvexHullAccelerator * getAccelerator (S32 dl)
Lookup Animation Info
indexed by keyframe number and offset (which object/node/decal of the animated objects/nodes/decals you want information for).
QuatF & getRotation (const Sequence &seq, S32 keyframeNum, S32 rotNum, QuatF *) const
const Point3F & getTranslation (const Sequence &seq, S32 keyframeNum, S32 tranNum) const
F32 getUniformScale (const Sequence &seq, S32 keyframeNum, S32 scaleNum) const
const Point3F & getAlignedScale (const Sequence &seq, S32 keyframeNum, S32 scaleNum) const
TSScale & getArbitraryScale (const Sequence &seq, S32 keyframeNum, S32 scaleNum, TSScale *) const
const ObjectState & getObjectState (const Sequence &seq, S32 keyframeNum, S32 objectNum) const
Lookup Methods
S32 findName (const String &name) const
Returns index into the name vector that equals the passed name.
const String & getName (S32 nameIndex) const
Returns name string at the passed name vector index.
const String & getMeshName (S32 meshIndex) const
Returns name string for mesh at the passed index.
const String & getNodeName (S32 nodeIndex) const
Returns name string for node at the passed index.
const String & getSequenceName (S32 seqIndex) const
Returns name string for sequence at the passed index.
S32 getTargetCount () const
const String & getTargetName (S32 mapToNameIndex) const
S32 findNode (S32 nameIndex) const
S32 findNode (const String &name) const
S32 findObject (S32 nameIndex) const
S32 findObject (const String &name) const
S32 findDetail (S32 nameIndex) const
S32 findDetail (const String &name) const
S32 findDetailBySize (S32 size) const
S32 findSequence (S32 nameIndex) const
S32 findSequence (const String &name) const
S32 getSubShapeForNode (S32 nodeIndex)
S32 getSubShapeForObject (S32 objIndex)
void getSubShapeDetails (S32 subShapeIndex, Vector< S32 > &validDetails)
void getNodeWorldTransform (S32 nodeIndex, MatrixF *mat) const
void getNodeKeyframe (S32 nodeIndex, const TSShape::Sequence &seq, S32 keyframe, MatrixF *mat) const
void getNodeObjects (S32 nodeIndex, Vector< S32 > &nodeObjects)
void getNodeChildren (S32 nodeIndex, Vector< S32 > &nodeChildren)
void getObjectDetails (S32 objIndex, Vector< S32 > &objDetails)
bool findMeshIndex (const String &meshName, S32 &objIndex, S32 &meshIndex)
TSMesh * findMesh (const String &meshName)
bool hasTranslucency () const
const GFXVertexFormat * getVertexFormat () const
Persist Methods
Methods for saving/loading shapes to/from streams
bool canWriteOldFormat () const
void write (Stream *, bool saveOldFormat=false)
bool read (Stream *)
void readOldShape (Stream *s, S32 *&, S16 *&, S8 *&, S32 &, S32 &, S32 &)
void writeName (Stream *, S32 nameIndex)
S32 readName (Stream *, bool addName)
void createEmptyShape ()
Initializes our TSShape to be ready to receive put mesh data.
void exportSequences (Stream *)
void exportSequence (Stream *s, const TSShape::Sequence &seq, bool saveOldFormat)
bool importSequences (Stream *, const String &sequencePath)
Memory Buffer Transfer Methods
uses TSShape::Alloc structure
void assembleShape ()
void disassembleShape ()
Shape Editing
S32 addName (const String &name)
bool removeName (const String &name)
void updateSmallestVisibleDL ()
S32 addDetail (const String &dname, S32 size, S32 subShapeNum)
S32 addImposter (const String &cachePath, S32 size, S32 numEquatorSteps, S32 numPolarSteps, S32 dl, S32 dim, bool includePoles, F32 polarAngle)
bool removeImposter ()
bool renameNode (const String &oldName, const String &newName)
bool renameObject (const String &oldName, const String &newName)
bool renameDetail (const String &oldName, const String &newName)
bool renameSequence (const String &oldName, const String &newName)
bool setNodeTransform (const String &name, const Point3F &pos, const QuatF &rot)
bool addNode (const String &name, const String &parentName, const Point3F &pos, const QuatF &rot)
bool removeNode (const String &name)
S32 addObject (const String &objName, S32 subShapeIndex)
void addMeshToObject (S32 objIndex, S32 meshIndex, TSMesh *mesh)
void removeMeshFromObject (S32 objIndex, S32 meshIndex)
bool setObjectNode (const String &objName, const String &nodeName)
bool removeObject (const String &objName)
TSMesh * copyMesh (const TSMesh *srcMesh) const
bool addMesh (TSShape *srcShape, const String &srcMeshName, const String &meshName)
bool addMesh (TSMesh *mesh, const String &meshName)
bool setMeshSize (const String &meshName, S32 size)
bool removeMesh (const String &meshName)
S32 setDetailSize (S32 oldSize, S32 newSize)
bool removeDetail (S32 size)
bool addSequence (const Torque::Path &path, const String &fromSeq, const String &name, S32 startFrame, S32 endFrame, bool padRotKeys, bool padTransKeys)
bool removeSequence (const String &name)
bool addTrigger (const String &seqName, S32 keyframe, S32 state)
bool removeTrigger (const String &seqName, S32 keyframe, S32 state)
bool setSequenceBlend (const String &seqName, bool blend, const String &blendRefSeqName, S32 blendRefFrame)
bool setSequenceGroundSpeed (const String &seqName, const Point3F &trans, const Point3F &rot)
void makeEditable ()
bool needsReinit ()
bool needsBufferUpdate ()
Public Attributes
U32 data
User-defined data storage.
TSMaterialList * materialList
TSBasicVertexFormat mBasicVertexFormat
Vector< LodPair > mDetailLevelLookup
The lod lookup table where we mark down the detail level and intra-detail level for each pixel size.
U32 mExporterVersion
U32 mFlags
hasTranslucancy
bool mNeedReinit
S32 mReadVersion
File version that this shape was read from.
bool mSequencesConstructed
S8 * mShapeData
U32 mShapeDataSize
TSVertexBufferHandle mShapeVertexBuffer
TSShapeVertexArray mShapeVertexData
GFXPrimitiveBufferHandle mShapeVertexIndices
S32 mSmallestVisibleDL
F32 mSmallestVisibleSize
Computed at load time from details vector.
bool mUseDetailFromScreenError
If enabled detail selection will use the legacy screen error method for lod.
GFXVertexFormat mVertexFormat
The GFX vertex format for all detail meshes in the shape.
U32 mVertexSize
Shape Vector Data
Vector< Node > nodes
Vector< Object > objects
Vector< ObjectState > objectStates
Vector< S32 > subShapeFirstNode
Vector< S32 > subShapeFirstObject
Vector< S32 > detailFirstSkin
Vector< S32 > subShapeNumNodes
Vector< S32 > subShapeNumObjects
Vector< Detail > details
Vector< Quat16 > defaultRotations
Vector< Point3F > defaultTranslations
Vector< S32 > subShapeFirstTranslucentObject
These are set up at load time, but memory is allocated along with loaded data.
Vector< TSMesh * > meshes
Alpha Vectors
these vectors describe how to transition between detail levels using alpha.
"alpha-in" next detail as intraDL goes from alphaIn+alphaOut to alphaOut. "alpha-out" current detail level as intraDL goes from alphaOut to 0.
Note
intraDL is at 1 when if shape were any closer to us we'd be at dl-1
intraDL is at 0 when if shape were any farther away we'd be at dl+1
Vector< F32 > alphaIn
Vector< F32 > alphaOut
Resizeable vectors
Vector< Sequence > sequences
Vector< Quat16 > nodeRotations
Vector< Point3F > nodeTranslations
Vector< F32 > nodeUniformScales
Vector< Point3F > nodeAlignedScales
Vector< Quat16 > nodeArbitraryScaleRots
Vector< Point3F > nodeArbitraryScaleFactors
Vector< Quat16 > groundRotations
Vector< Point3F > groundTranslations
Vector< Trigger > triggers
Vector< TSLastDetail * > billboardDetails
Vector< ConvexHullAccelerator * > detailCollisionAccelerators
Vector< String > names
Bounding
F32 radius
F32 tubeRadius
Point3F center
Box3F bounds
Static Public Attributes
static bool smInitOnRead
by default we initialize shape when we read...
static U32 smMaxSkinBones
Determines maximum number of bones to use in hardware skinning shaders.
static S32 smNumSkipLoadDetails
don't load this many of the highest detail levels (although we always load one renderable detail if there is one)
static bool smUseHardwareSkinning
Enables hardware skinning features.
Alpha Transitions
These control default values for alpha transitions between detail levels
static F32 smAlphaOutLastDetail
static F32 smAlphaInBillboard
static F32 smAlphaOutBillboard
static F32 smAlphaInDefault
static F32 smAlphaOutDefault
Version Info
static S32 smVersion
Most recent version...the one we write.
static S32 smReadVersion
Version currently being read, only valid during read.
static const U32 smMostRecentExporterVersion
Persist Helper Functions
static TSShapeAlloc smTSAlloc
void fixEndian (S32 *, S16 *, S8 *, S32, S32, S32)
Detailed Description
TSShape stores generic data for a 3space model.
TSShape and TSShapeInstance act in conjunction to allow the rendering and manipulation of a three dimensional model.
Note
The material lists are the only thing that is not loaded in TSShape. instead, they are loaded in TSShapeInstance because of a former restriction on the resource manager where only one file could be opened at a time. The resource manager restriction has been resolved, but the material lists are still loaded in TSShapeInstance.
See also
TSShapeInstance for a further discussion of the 3space system.
Member Enumeration Documentation
anonymous enum
Enumerator
UniformScale
AlignedScale
ArbitraryScale
Blend
Cyclic
MakePath
HasTranslucency
AnyScale
Constructor & Destructor Documentation
TSShape::TSShape ()
TSShape::~TSShape ()
Member Function Documentation
PhysicsCollision* TSShape::_buildColShapes (bool useVisibleMesh, const Point3F & scale, Vector< CollisionShapeInfo > * list, bool perMesh)
For internal use.
S32 TSShape::addDetail (const String & dname, S32 size, S32 subShapeNum)
S32 TSShape::addImposter (const String & cachePath, S32 size, S32 numEquatorSteps, S32 numPolarSteps, S32 dl, S32 dim, bool includePoles, F32 polarAngle)
bool TSShape::addMesh (TSShape * srcShape, const String & srcMeshName, const String & meshName)
bool TSShape::addMesh (TSMesh * mesh, const String & meshName)
void TSShape::addMeshToObject (S32 objIndex, S32 meshIndex, TSMesh * mesh)
S32 TSShape::addName (const String & name)
bool TSShape::addNode (const String & name, const String & parentName, const Point3F & pos, const QuatF & rot)
S32 TSShape::addObject (const String & objName, S32 subShapeIndex)
bool TSShape::addSequence (const Torque::Path & path, const String & fromSeq, const String & name, S32 startFrame, S32 endFrame, bool padRotKeys, bool padTransKeys)
bool TSShape::addTrigger (const String & seqName, S32 keyframe, S32 state)
void TSShape::assembleShape ()
PhysicsCollision* TSShape::buildColShape (bool useVisibleMesh, const Point3F & scale)
Builds a physics collision shape at the requested scale.
If using the visible mesh one or more triangle meshes are created from the first visible detail level.
If using collision meshes we look for mesh names prefixed with the following hints: "colbox" "colsphere" "colcapsule" "colmesh"
In the case of the primitives the mesh bounding box is used to generate a box, sphere, or capsule collision shape. The "colmesh" will create a concave triangle mesh for collision.
Any other named collision shape is interpreted as a regular convex hull.
Returns
The collision object or NULL if no collision data could be generated.
void TSShape::buildColShapes (bool useVisibleMesh, const Point3F & scale, Vector< CollisionShapeInfo > * list)
Like buildColShape except we build one PhysicsCollision object per collision node.
Results are returned by filling in the CollisionShapeInfo Vector, which also specifies the collision node index for each PhysicsCollision built.
bool TSShape::buildConvexHull (S32 dl) const
bool TSShape::canWriteOldFormat () const
bool TSShape::checkSkip (S32 meshNum, S32 & curObject, S32 skipDL)
mem buffer transfer helper (indicate when we don't want to include a particular mesh/decal)
void TSShape::computeAccelerator (S32 dl)
build LOS collision detail
void TSShape::computeBounds (S32 dl, Box3F & bounds) const
TSMesh* TSShape::copyMesh (const TSMesh * srcMesh) const
void TSShape::createEmptyShape ()
Initializes our TSShape to be ready to receive put mesh data.
void TSShape::disassembleShape ()
void TSShape::exportSequence (Stream * s, const TSShape::Sequence & seq, bool saveOldFormat)
void TSShape::exportSequences (Stream *)
void TSShape::finalizeEditable ()
void TSShape::findColDetails (bool useVisibleMesh, Vector< S32 > * outDetails, Vector< S32 > * outLOSDetails) const
Used to find collision detail meshes in the DTS.
Parameters
useVisibleMesh If true return the highest visible detail level.
outDetails The output detail index vector.
outLOSDetails The optional output LOS detail vector.
S32 TSShape::findDetail (S32 nameIndex) const
S32 TSShape::findDetail (const String & name) const inline
References findDetail().
Referenced by findDetail().
S32 TSShape::findDetailBySize (S32 size) const
TSMesh* TSShape::findMesh (const String & meshName)
bool TSShape::findMeshIndex (const String & meshName, S32 & objIndex, S32 & meshIndex)
S32 TSShape::findName (const String & name) const
Returns index into the name vector that equals the passed name.
S32 TSShape::findNode (S32 nameIndex) const
S32 TSShape::findNode (const String & name) const inline
References findNode().
Referenced by findNode().
S32 TSShape::findObject (S32 nameIndex) const
S32 TSShape::findObject (const String & name) const inline
References findObject().
Referenced by findObject().
S32 TSShape::findSequence (S32 nameIndex) const
S32 TSShape::findSequence (const String & name) const inline
References findSequence().
Referenced by findSequence().
void TSShape::fixEndian (S32 * , S16 * , S8 * , S32 , S32 , S32)
void TSShape::fixupOldSkins (S32 numMeshes, S32 numSkins, S32 numDetails, S32 * detFirstSkin, S32 * detailNumSkins)
ConvexHullAccelerator* TSShape::getAccelerator (S32 dl)
const Point3F & TSShape::getAlignedScale (const Sequence & seq, S32 keyframeNum, S32 scaleNum) const inline
References TSShape::Sequence::baseScale, and TSShape::Sequence::numKeyframes.
TSScale & TSShape::getArbitraryScale (const Sequence & seq, S32 keyframeNum, S32 scaleNum, TSScale * scale) const inline
References TSShape::Sequence::baseScale, TSScale::mRotate, TSScale::mScale, and TSShape::Sequence::numKeyframes.
const String& TSShape::getMeshName (S32 meshIndex) const
Returns name string for mesh at the passed index.
const String& TSShape::getName (S32 nameIndex) const
Returns name string at the passed name vector index.
void TSShape::getNodeChildren (S32 nodeIndex, Vector< S32 > & nodeChildren)
void TSShape::getNodeKeyframe (S32 nodeIndex, const TSShape::Sequence & seq, S32 keyframe, MatrixF * mat) const
const String& TSShape::getNodeName (S32 nodeIndex) const
Returns name string for node at the passed index.
void TSShape::getNodeObjects (S32 nodeIndex, Vector< S32 > & nodeObjects)
void TSShape::getNodeWorldTransform (S32 nodeIndex, MatrixF * mat) const
void TSShape::getObjectDetails (S32 objIndex, Vector< S32 > & objDetails)
const TSShape::ObjectState & TSShape::getObjectState (const Sequence & seq, S32 keyframeNum, S32 objectNum) const inline
References TSShape::Sequence::baseObjectState, and TSShape::Sequence::numKeyframes.
QuatF & TSShape::getRotation (const Sequence & seq, S32 keyframeNum, S32 rotNum, QuatF * quat) const inline
References TSShape::Sequence::baseRotation, and TSShape::Sequence::numKeyframes.
const String& TSShape::getSequenceName (S32 seqIndex) const
Returns name string for sequence at the passed index.
Referenced by TSThread::getSequenceName().
bool TSShape::getSequencesConstructed () const inline
void TSShape::getSubShapeDetails (S32 subShapeIndex, Vector< S32 > & validDetails)
S32 TSShape::getSubShapeForNode (S32 nodeIndex)
S32 TSShape::getSubShapeForObject (S32 objIndex)
S32 TSShape::getTargetCount () const
const String& TSShape::getTargetName (S32 mapToNameIndex) const
const Point3F & TSShape::getTranslation (const Sequence & seq, S32 keyframeNum, S32 tranNum) const inline
References TSShape::Sequence::baseTranslation, and TSShape::Sequence::numKeyframes.
F32 TSShape::getUniformScale (const Sequence & seq, S32 keyframeNum, S32 scaleNum) const inline
References TSShape::Sequence::baseScale, and TSShape::Sequence::numKeyframes.
void TSShape::getVertexBuffer (TSVertexBufferHandle & vb, GFXBufferType bufferType)
Loads shape vertex data into specified buffer.
const GFXVertexFormat* TSShape::getVertexFormat () const inline
bool TSShape::hasTranslucency () const inline
bool TSShape::importSequences (Stream * , const String & sequencePath)
void TSShape::init ()
void TSShape::initMaterialList ()
you can swap in a new material list, but call this if you do
void TSShape::initObjects ()
Inits object list (no geometry buffers)
void TSShape::initVertexBufferPointers ()
Inits basic buffer pointers on load.
void TSShape::initVertexBuffers ()
Initializes the main vertex buffer.
void TSShape::initVertexFeatures ()
Called from init() to calcuate the GFX vertex features for all detail meshes in the shape.
void TSShape::makeEditable ()
bool TSShape::needsBufferUpdate ()
bool TSShape::needsReinit ()
bool TSShape::preloadMaterialList (const Torque::Path & path)
called to preload and validate the materials in the mat list
bool TSShape::read (Stream *)
S32 TSShape::readName (Stream * , bool addName)
void TSShape::readOldShape (Stream * s, S32 *& , S16 *& , S8 *& , S32 & , S32 & , S32 &)
bool TSShape::removeDetail (S32 size)
bool TSShape::removeImposter ()
bool TSShape::removeMesh (const String & meshName)
void TSShape::removeMeshFromObject (S32 objIndex, S32 meshIndex)
bool TSShape::removeName (const String & name)
bool TSShape::removeNode (const String & name)
bool TSShape::removeObject (const String & objName)
bool TSShape::removeSequence (const String & name)
bool TSShape::removeTrigger (const String & seqName, S32 keyframe, S32 state)
bool TSShape::renameDetail (const String & oldName, const String & newName)
bool TSShape::renameNode (const String & oldName, const String & newName)
bool TSShape::renameObject (const String & oldName, const String & newName)
bool TSShape::renameSequence (const String & oldName, const String & newName)
S32 TSShape::setDetailSize (S32 oldSize, S32 newSize)
bool TSShape::setMeshSize (const String & meshName, S32 size)
bool TSShape::setNodeTransform (const String & name, const Point3F & pos, const QuatF & rot)
bool TSShape::setObjectNode (const String & objName, const String & nodeName)
bool TSShape::setSequenceBlend (const String & seqName, bool blend, const String & blendRefSeqName, S32 blendRefFrame)
bool TSShape::setSequenceGroundSpeed (const String & seqName, const Point3F & trans, const Point3F & rot)
void TSShape::setSequencesConstructed (const bool c) inline
void TSShape::setupBillboardDetails (const String & cachePath)
void TSShape::updateSmallestVisibleDL ()
void TSShape::write (Stream * , bool saveOldFormat = false)
void TSShape::writeName (Stream * , S32 nameIndex)
Member Data Documentation
Vector<F32> TSShape::alphaIn
Vector<F32> TSShape::alphaOut
Vector<TSLastDetail*> TSShape::billboardDetails
Box3F TSShape::bounds
Referenced by TSForestItemData::getObjBox().
Point3F TSShape::center
U32 TSShape::data
User-defined data storage.
Vector<Quat16> TSShape::defaultRotations
Vector<Point3F> TSShape::defaultTranslations
Vector<ConvexHullAccelerator*> TSShape::detailCollisionAccelerators
Vector<S32> TSShape::detailFirstSkin
Vector<Detail> TSShape::details
Referenced by TSShapeInstance::getNumDetails().
Vector<Quat16> TSShape::groundRotations
Vector<Point3F> TSShape::groundTranslations
TSMaterialList* TSShape::materialList
TSBasicVertexFormat TSShape::mBasicVertexFormat
Vector<LodPair> TSShape::mDetailLevelLookup
The lod lookup table where we mark down the detail level and intra-detail level for each pixel size.
Vector<TSMesh*> TSShape::meshes
U32 TSShape::mExporterVersion
U32 TSShape::mFlags
hasTranslucancy
Referenced by TSShapeInstance::animatesAlignedScale(), TSShapeInstance::animatesArbitraryScale(), TSShapeInstance::animatesScale(), and TSShapeInstance::animatesUniformScale().
bool TSShape::mNeedReinit
S32 TSShape::mReadVersion
File version that this shape was read from.
bool TSShape::mSequencesConstructed
S8* TSShape::mShapeData
U32 TSShape::mShapeDataSize
TSVertexBufferHandle TSShape::mShapeVertexBuffer
TSShapeVertexArray TSShape::mShapeVertexData
GFXPrimitiveBufferHandle TSShape::mShapeVertexIndices
S32 TSShape::mSmallestVisibleDL
See also
mSmallestVisibleSize
Referenced by TSPartInstance::getNumDetails().
F32 TSShape::mSmallestVisibleSize
Computed at load time from details vector.
bool TSShape::mUseDetailFromScreenError
If enabled detail selection will use the legacy screen error method for lod.
See also
setDetailFromScreenError
GFXVertexFormat TSShape::mVertexFormat
The GFX vertex format for all detail meshes in the shape.
See also
initVertexFeatures()
U32 TSShape::mVertexSize
Vector<String> TSShape::names
Vector<Point3F> TSShape::nodeAlignedScales
Vector<Point3F> TSShape::nodeArbitraryScaleFactors
Vector<Quat16> TSShape::nodeArbitraryScaleRots
Vector<Quat16> TSShape::nodeRotations
Vector<Node> TSShape::nodes
Vector<Point3F> TSShape::nodeTranslations
Vector<F32> TSShape::nodeUniformScales
Vector<Object> TSShape::objects
Vector<ObjectState> TSShape::objectStates
F32 TSShape::radius
Vector<Sequence> TSShape::sequences
Referenced by TSThread::getSequence().
F32 TSShape::smAlphaInBillboard static
F32 TSShape::smAlphaInDefault static
F32 TSShape::smAlphaOutBillboard static
F32 TSShape::smAlphaOutDefault static
F32 TSShape::smAlphaOutLastDetail static
bool TSShape::smInitOnRead static
by default we initialize shape when we read...
U32 TSShape::smMaxSkinBones static
Determines maximum number of bones to use in hardware skinning shaders.
const U32 TSShape::smMostRecentExporterVersion static
S32 TSShape::smNumSkipLoadDetails static
don't load this many of the highest detail levels (although we always load one renderable detail if there is one)
S32 TSShape::smReadVersion static
Version currently being read, only valid during read.
TSShapeAlloc TSShape::smTSAlloc static
bool TSShape::smUseHardwareSkinning static
Enables hardware skinning features.
S32 TSShape::smVersion static
Most recent version...the one we write.
Vector<S32> TSShape::subShapeFirstNode
Vector<S32> TSShape::subShapeFirstObject
Vector<S32> TSShape::subShapeFirstTranslucentObject
These are set up at load time, but memory is allocated along with loaded data.
Vector<S32> TSShape::subShapeNumNodes
Vector<S32> TSShape::subShapeNumObjects
Vector<Trigger> TSShape::triggers
F32 TSShape::tubeRadius
Copyright © GarageGames, LLC. All Rights Reserved.