MutexHandle Class Reference
Main Modules Class List Namespace List Online
MutexHandle Class Reference
Helper for simplifying mutex locking code.
#include <platform/threads/mutex.h>
Public Member Functions
MutexHandle ()
~MutexHandle ()
bool lock (void *mutex, bool blocking=false)
void unlock ()
Detailed Description
Helper for simplifying mutex locking code.
This class will automatically unlock a mutex that you've locked through it, saving you from managing a lot of complex exit cases. For instance:
MutexHandle handle;
handle.lock(myMutex);
if(error1)
  return; // Auto-unlocked by handle if we leave here - normally would
          // leave the mutex locked, causing much pain later.
handle.unlock();
Constructor & Destructor Documentation
MutexHandle::MutexHandle () inline
MutexHandle::~MutexHandle () inline
References Mutex::unlock().
Member Function Documentation
bool MutexHandle::lock (void * mutex, bool blocking = false) inline
References Mutex::lockMutex().
void MutexHandle::unlock () inline
References Mutex::unlockMutex().
Copyright © GarageGames, LLC. All Rights Reserved.