SimObjectMemento Class Reference
Main Modules Class List Namespace List Online
SimObjectMemento Class Reference
This simple class is used to store an SimObject and its state so it can be recreated at a later time.
#include <console/simObjectMemento.h>
Public Member Functions
SimObjectMemento ()
virtual ~SimObjectMemento ()
bool hasState () const
Returns true if we have recorded state.
SimObject * restore () const
void save (SimObject *object)
Protected Attributes
bool mIsDatablock
String mObjectName
The captured object's name.
UTF8 * mState
The captured object state.
Detailed Description
This simple class is used to store an SimObject and its state so it can be recreated at a later time.
The success of restoring the object completely depends on the results from SimObject::write().
Constructor & Destructor Documentation
SimObjectMemento::SimObjectMemento ()
virtual SimObjectMemento::~SimObjectMemento () virtual
Member Function Documentation
bool SimObjectMemento::hasState () const inline
Returns true if we have recorded state.
References mState, restore(), and save().
SimObject* SimObjectMemento::restore () const
Referenced by hasState().
void SimObjectMemento::save (SimObject * object)
Referenced by hasState().
Member Data Documentation
bool SimObjectMemento::mIsDatablock protected
String SimObjectMemento::mObjectName protected
The captured object's name.
UTF8* SimObjectMemento::mState protected
The captured object state.
Referenced by hasState().
Copyright © GarageGames, LLC. All Rights Reserved.