VertPixelConnectorGLSL Class Reference
Main Modules Class List Namespace List Online
VertPixelConnectorGLSL Class Reference
#include <shaderGen/GLSL/shaderCompGLSL.h>
Public Member Functions
virtual Var * getElement (RegisterType type, U32 numElements=1, U32 numRegisters=-1)
virtual void print (Stream &stream)
virtual void print (Stream &stream, bool isVerterShader)
virtual void printOnMain (Stream &stream, bool isVerterShader)
void printStructDefines (Stream &stream, bool in)
virtual void reset ()
virtual void setName (char *newName)
virtual void sortVars ()
Public Member Functions inherited from ShaderConnector
ShaderConnector ()
virtual ~ShaderConnector ()
U32 getCurTexElem ()
Public Member Functions inherited from ShaderComponent
virtual ~ShaderComponent ()
Additional Inherited Members
Protected Types inherited from ShaderConnector
enum Consts { NUM_TEX_REGS = 8 }
enum Elements {
POSITION = 0,
NORMAL,
COLOR,
NUM_BASIC_ELEMS
}
Protected Attributes inherited from ShaderConnector
U32 mCurBlendIndicesElem
U32 mCurBlendWeightsElem
U32 mCurTexElem
Vector< Var * > mElementList
U8 mName [32]
Member Function Documentation
virtual Var* VertPixelConnectorGLSL::getElement (RegisterType type, U32 numElements = 1, U32 numRegisters = -1) virtual
Implements ShaderConnector.
virtual void VertPixelConnectorGLSL::print (Stream & stream) inline virtual
References printOnMain(), and printStructDefines().
Referenced by AppVertConnectorGLSL::print().
virtual void VertPixelConnectorGLSL::print (Stream & stream, bool isVerterShader) virtual
Implements ShaderConnector.
virtual void VertPixelConnectorGLSL::printOnMain (Stream & stream, bool isVerterShader) virtual
Reimplemented from ShaderComponent.
Referenced by print(), and AppVertConnectorGLSL::print().
void VertPixelConnectorGLSL::printStructDefines (Stream & stream, bool in)
Referenced by print().
virtual void VertPixelConnectorGLSL::reset () virtual
Implements ShaderConnector.
virtual void VertPixelConnectorGLSL::setName (char * newName) virtual
Implements ShaderConnector.
virtual void VertPixelConnectorGLSL::sortVars () virtual
Implements ShaderConnector.
Copyright © GarageGames, LLC. All Rights Reserved.