ThreadSafeRef< T > Class Template Reference
Main Modules Class List Namespace List Online
ThreadSafeRef< T > Class Template Reference
Reference to a concurrently reference-counted object.
#include <platform/threads/threadSafeRefCount.h>
Public Types
enum ETag {
TAG_PreserveOld,
TAG_PreserveNew,
TAG_Set,
TAG_Unset,
TAG_SetOrFail,
TAG_UnsetOrFail,
TAG_FailIfSet,
TAG_FailIfUnset
}
typedef ThreadSafeRef< T > ThisType
Public Member Functions
ThreadSafeRef ()
ThreadSafeRef (T *ptr)
ThreadSafeRef (const ThisType &ref)
~ThreadSafeRef ()
bool isTagged () const
operator T * () const
bool operator! () const
bool operator!= (T *ptr) const
bool operator!= (const ThisType &ref) const
T & operator* () const
T * operator-> () const
ThisType & operator= (T *ptr)
ThisType & operator= (const ThisType &ref)
bool operator== (T *ptr) const
bool operator== (const ThisType &ref) const
T * ptr () const
void setTag ()
bool trySetFromTo (T *oldVal, T *const volatile &newVal, ETag tag=TAG_PreserveOld)
Update the reference from pointing to oldVal to point to newVal.
bool trySetFromTo (T *oldVal, const ThisType &newVal, ETag tag=TAG_PreserveOld)
bool trySetFromTo (const ThisType &oldVal, const ThisType &newVal, ETag tag=TAG_PreserveOld)
Static Public Member Functions
static T * safeRead (T *const volatile &refPtr)
static void unsafeWrite (ThisType &ref, T *ptr)
Update ref to point to ptr but do not release an existing reference held by ref nor do the operation in a thread-safe way.
Static Protected Member Functions
static T * getTaggedPtr (T *ptr)
static T * getUntaggedPtr (T *ptr)
static bool isTaggedPtr (T *ptr)
Protected Attributes
T *volatile mPtr
Detailed Description
template<class T>
class ThreadSafeRef< T >
Reference to a concurrently reference-counted object.
This class takes care of the reference-counting as well as protecting the reference itself from concurrent operations.
Tagging allows the pointer contained in the reference to be flagged. Tag state is preserved through updates to the reference.
Note
If you directly assign a freshly created object with a reference count of zero to a ThreadSafeRef, make absolutely sure the ThreadSafeRef is accessed only by a single thread. Otherwise there's a risk of the object being released and freed in midst of trying to set the reference.
Member Typedef Documentation
template<class T> typedef ThreadSafeRef< T > ThreadSafeRef< T >::ThisType
Member Enumeration Documentation
template<class T> enum ThreadSafeRef::ETag
Enumerator
TAG_PreserveOld
Preserve existing tagging state when changing pointer.
TAG_PreserveNew
Preserve tagging state of new pointer when changing pointer.
TAG_Set
Set tag when changing pointer; okay if already set.
TAG_Unset
Unset tag when changing pointer; okay if already unset.
TAG_SetOrFail
Set tag when changing pointer; fail if already set.
TAG_UnsetOrFail
Unset tag when changing pointer; fail if already unset.
TAG_FailIfSet
Fail changing pointer when currently tagged.
TAG_FailIfUnset
Fail changing pointer when currently untagged.
Constructor & Destructor Documentation
template<class T> ThreadSafeRef< T >::ThreadSafeRef () inline
template<class T> ThreadSafeRef< T >::ThreadSafeRef (T * ptr) inline
template<class T> ThreadSafeRef< T >::ThreadSafeRef (const ThisType & ref) inline
template<class T> ThreadSafeRef< T >::~ThreadSafeRef () inline
Member Function Documentation
template<class T> static T* ThreadSafeRef< T >::getTaggedPtr (T * ptr) inline static protected
template<class T> static T* ThreadSafeRef< T >::getUntaggedPtr (T * ptr) inline static protected
template<class T> bool ThreadSafeRef< T >::isTagged () const inline
Referenced by ThreadSafeDeque< T >::getHead(), and ThreadSafeDeque< T >::getTail().
template<class T> static bool ThreadSafeRef< T >::isTaggedPtr (T * ptr) inline static protected
template<class T> ThreadSafeRef< T >::operator T * () const inline
template<class T> bool ThreadSafeRef< T >::operator! () const inline
template<class T> bool ThreadSafeRef< T >::operator!= (T * ptr) const inline
template<class T> bool ThreadSafeRef< T >::operator!= (const ThisType & ref) const inline
template<class T> T& ThreadSafeRef< T >::operator* (void) const inline
template<class T> T* ThreadSafeRef< T >::operator-> (void) const inline
template<class T> ThreadSafeRef< T > & ThreadSafeRef< T >::operator= (T * ptr) inline
template<class T> ThreadSafeRef< T > & ThreadSafeRef< T >::operator= (const ThisType & ref) inline
template<class T> bool ThreadSafeRef< T >::operator== (T * ptr) const inline
template<class T> bool ThreadSafeRef< T >::operator== (const ThisType & ref) const inline
References ThreadSafeRef< T >::ptr().
template<class T> T* ThreadSafeRef< T >::ptr () const inline
Referenced by ThreadSafeRef< T >::operator==().
template<class T> static T* ThreadSafeRef< T >::safeRead (T *const volatile & refPtr) inline static
Referenced by ThreadSafeFreeList< ThreadSafeDeque::Node >::alloc().
template<class T> void ThreadSafeRef< T >::setTag () inline
Referenced by ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::helpDelete().
template<class T> bool ThreadSafeRef< T >::trySetFromTo (T * oldVal, T *const volatile & newVal, ETag tag = TAG_PreserveOld)
Update the reference from pointing to oldVal to point to newVal.
Do so in a thread-safe way.
This operation will only succeed, if, when doing the pointer-swapping, the reference still points to oldVal. If, however, the reference has been changed in the meantime by another thread, the operation will fail.
Parameters
oldVal The pointer assumed to currently be contained in this ThreadSafeRef.
newVal The pointer to store in this ThreadSafeRef.
tag Operation to perform on the reference's tag field.
Returns
true, if the reference now points to newVal.
References T.
Referenced by ThreadSafeDeque< T >::getHead(), ThreadSafeDeque< T >::getTail(), ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::helpDelete(), ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::insert(), ThreadSafeDeque< T >::pushBack(), ThreadSafeDeque< T >::pushFront(), ThreadSafeDeque< T >::tryPopBack(), and ThreadSafeDeque< T >::tryPopFront().
template<class T> bool ThreadSafeRef< T >::trySetFromTo (T * oldVal, const ThisType & newVal, ETag tag = TAG_PreserveOld) inline
References ThreadSafeRef< T >::mPtr.
template<class T> bool ThreadSafeRef< T >::trySetFromTo (const ThisType & oldVal, const ThisType & newVal, ETag tag = TAG_PreserveOld) inline
References ThreadSafeRef< T >::mPtr.
template<class T> void ThreadSafeRef< T >::unsafeWrite (ThisType & ref, T * ptr) inline static
Update ref to point to ptr but do not release an existing reference held by ref nor do the operation in a thread-safe way.
This method is only for when you absolutely know that your thread is the only thread operating on a reference and you are keeping track of reference counts yourself.
Parameters
ref The reference to update.
ptr The new pointer to store in ref.
References ThreadSafeRef< T >::mPtr.
Member Data Documentation
template<class T> T* volatile ThreadSafeRef< T >::mPtr protected
Referenced by ThreadSafeRef< T >::trySetFromTo(), and ThreadSafeRef< T >::unsafeWrite().
Copyright © GarageGames, LLC. All Rights Reserved.