SignalBaseT< Signature > Class Template Reference
Main Modules Class List Namespace List Online
SignalBaseT< Signature > Class Template Reference
#include <core/util/tSignal.h>
Classes
struct DelegateLinkImpl
struct SlotLinkImpl
Public Types
typedef Delegate< Signature > DelegateSig
The delegate signature for this signal.
Public Member Functions
SignalBaseT ()
SignalBaseT (const SignalBaseT &base)
bool contains (const DelegateSig &dlg) const
Returns true if the signal already contains this delegate.
void merge (const SignalBaseT &base)
void notify (const DelegateSig &dlg, F32 order=0.5f)
template<class T , class U >
void notify (T obj, U func, F32 order=0.5f)
template<class T >
void notify (T func, F32 order=0.5f)
void notify (SignalSlot< Signature > &slot, F32 order=0.5f)
void operator= (const SignalBaseT &base)
void remove (DelegateSig dlg)
template<class T , class U >
void remove (T obj, U func)
template<class T >
void remove (T func)
Public Member Functions inherited from SignalBase
SignalBase ()
~SignalBase ()
bool isEmpty () const
Returns true if the delegate list is empty.
void removeAll ()
Removes all the delegates from the signal.
Protected Member Functions
DelegateSig & getDelegate (SignalBase::DelegateLink *link)
Additional Inherited Members
Protected Attributes inherited from SignalBase
DelegateLink mList
Vector< DelegateLink * > mTriggerNext
We need to protect the delegate list against removal of the currently triggering node as well removal of the next node in the list.
Member Typedef Documentation
template<typename Signature> typedef Delegate<Signature> SignalBaseT< Signature >::DelegateSig
The delegate signature for this signal.
Constructor & Destructor Documentation
template<typename Signature> SignalBaseT< Signature >::SignalBaseT () inline
template<typename Signature> SignalBaseT< Signature >::SignalBaseT (const SignalBaseT< Signature > & base) inline
Member Function Documentation
template<typename Signature> bool SignalBaseT< Signature >::contains (const DelegateSig & dlg) const inline
Returns true if the signal already contains this delegate.
template<typename Signature> DelegateSig& SignalBaseT< Signature >::getDelegate (SignalBase::DelegateLink * link) inline protected
template<typename Signature> void SignalBaseT< Signature >::merge (const SignalBaseT< Signature > & base) inline
template<typename Signature> void SignalBaseT< Signature >::notify (const DelegateSig & dlg, F32 order = 0.5f) inline
Referenced by Process::notify(), and SignalSlot< void()>::setDelegate().
template<typename Signature> template<class T , class U > void SignalBaseT< Signature >::notify (T obj, U func, F32 order = 0.5f) inline
template<typename Signature> template<class T > void SignalBaseT< Signature >::notify (T func, F32 order = 0.5f) inline
template<typename Signature> void SignalBaseT< Signature >::notify (SignalSlot< Signature > & slot, F32 order = 0.5f) inline
template<typename Signature> void SignalBaseT< Signature >::operator= (const SignalBaseT< Signature > & base) inline
template<typename Signature> void SignalBaseT< Signature >::remove (DelegateSig dlg) inline
Referenced by SignalSlot< void()>::disconnect(), and Process::remove().
template<typename Signature> template<class T , class U > void SignalBaseT< Signature >::remove (T obj, U func) inline
template<typename Signature> template<class T > void SignalBaseT< Signature >::remove (T func) inline
Copyright © GarageGames, LLC. All Rights Reserved.