PlatformWindow Class Reference
Main Modules Class List Namespace List Online
PlatformWindow Class Reference abstract
Abstract representation of a native OS window.
#include <windowManager/platformWindow.h>
Public Types
enum WindowSystem {
WindowSystem_Unknown = 0,
WindowSystem_Windows,
WindowSystem_X11
}
Public Member Functions
virtual ~PlatformWindow ()
To get rid of a window, just delete it.
virtual bool getAcceleratorsEnabled () const
Returns true if native OS keyboard accelerators are enabled.
WindowInputGenerator * getInputGenerator () const
virtual Point2I getLockedSize ()
Returns the locked window size.
virtual Point2I getMinimumWindowSize ()
Returns the current minimum window size for this window.
virtual PlatformWindow * getNextWindow () const =0
virtual void * getPlatformDrawable () const =0
Get the platform specific object needed to create or attach an accelerated graohics drawing context on or to the window Win32 D3D and OpenGL typically needs an HWND Mac Cocoa OpenGL typically needs an NSOpenGLView Mac Carbon OpenGL typically needs a WindowRef.
virtual void * getSystemWindow (const WindowSystem system)
virtual WindowId getWindowId ()
Get the ID that uniquely identifies this window in the context of its window manager.
virtual bool isSizeLocked ()
Returns true if the window size is locked.
virtual void lockSize (bool locked)
Locks/unlocks window resizing.
virtual void setAcceleratorsEnabled (const bool enabled)
Used to disable native OS keyboard accelerators.
virtual void setInputController (IProcessInput *controller)
Get the WindowController associated with this window.
virtual void setMinimumWindowSize (Point2I minSize)
Sets a minimum window size.
void setSuppressReset (bool suppress)
Set the flag that determines whether to suppress a GFXDevice reset.
GFX State Management
virtual GFXDevice * getGFXDevice ()=0
Return a pointer to the GFX device this window is bound to.
virtual GFXWindowTarget * getGFXTarget ()=0
Return a pointer to this window's render target.
virtual void setVideoMode (const GFXVideoMode &mode)
Set the video mode for this window.
virtual const GFXVideoMode & getVideoMode ()=0
Get our current video mode - if the window has been resized, it will reflect this.
virtual bool clearFullscreen ()=0
If we're fullscreen, this function returns us to desktop mode.
virtual bool isFullscreen ()=0
void setFullscreen (const bool fullscreen)
Acquire the entire screen.
virtual void setBackground (bool val)
Set Idle State (Background)
virtual bool getBackground ()
Get Idle State (Background)
virtual void setOffscreenRender (bool val)
Set whether this window is intended for offscreen rendering An offscreen window will never be shown or lose focus.
virtual bool getOffscreenRender ()
Set whether this window is intended for offscreen rendering.
virtual void setDisplayWindow (bool val)
Set whether this window is should display as normal.
virtual void setFocus ()
Set Focused State (Foreground)
Caption
virtual bool setCaption (const char *cap)=0
Set the window's caption.
virtual const char * getCaption ()=0
Get the window's caption.
Visibility
Control how the window is displayed
virtual void minimize ()=0
Minimize the window on screen.
virtual void maximize ()=0
Maximize the window on screen.
virtual void hide ()=0
Hide the window on screen.
virtual void show ()=0
Show the window on screen.
virtual void close ()=0
Destroy the window on screen.
virtual void restore ()=0
Restore the window from a Maximized or Minimized state.
Window Bounds
virtual void setClientExtent (const Point2I newExtent)=0
The Client Rectangle or "Render Area" of a window is the area that is occupied by a given client that is rendering to that window.
virtual const Point2I getClientExtent ()=0
Get the Client Area Extent (Resolution) of this window.
virtual void setBounds (const RectI &newBounds)=0
The bounds of a Window are defined as the entire area occupied by that Window.
virtual const RectI getBounds () const =0
Get the position and size (fullscreen windows are always at (0,0)).
virtual void setPosition (const Point2I newPosition)=0
The Position of a window is always in relation to the very upper left of the window.
virtual const Point2I getPosition ()=0
Get the position of this window.
virtual void centerWindow ()
virtual bool setSize (const Point2I &newSize)=0
Resize the window to have a new size (but be in the same position).
Coordinate Space Conversion
virtual Point2I clientToScreen (const Point2I &point)=0
Convert the coordinate given in this window space to screen coordinates.
virtual Point2I screenToClient (const Point2I &point)=0
Convert the given screen coordinates to coordinates in this window space.
Windowed state
This is only really meaningful if the window is not fullscreen.
virtual bool isOpen ()=0
Returns true if the window is instantiated in the OS.
virtual bool isVisible ()=0
Returns true if the window is visible.
virtual bool isFocused ()=0
Returns true if the window has input focus.
virtual bool isMinimized ()=0
Returns true if the window is minimized.
virtual bool isMaximized ()=0
Returns true if the window is maximized.
Keyboard Translation
When keyboard translation is on, keypress events that correspond to character input should be send as character input events rather than as raw key events except if shouldNotTranslate() returns true for a specific keypress event.
This enables the platform layer to perform platform-specific character input mapping.
virtual void setKeyboardTranslation (const bool enabled)
Set if relevant keypress events should be translated into character input events.
virtual bool getKeyboardTranslation () const
Returns true if keyboard translation is enabled.
virtual bool shouldNotTranslate (U32 modifiers, U32 keyCode) const
Returns true if the given keypress event should not be translated.
Window Cursor
Accessors to control a windows cursor shape and visibility
Get the CursorController that this window owns.
virtual PlatformCursorController * getCursorController ()
virtual void setCursorPosition (S32 x, S32 y)
Set the cursor position based on logical coordinates from the upper-right corner.
virtual void getCursorPosition (Point2I &point)
Get the cursor position based on logical coordinates from the upper-right corner.
virtual void setCursorVisible (bool visible)
Set the cursor visibility on this window.
virtual bool isCursorVisible ()
Get the cursor visibility on this window.
virtual void setMouseLocked (bool enable)=0
Lock the mouse to this window.
virtual bool isMouseLocked () const =0
Is the mouse locked ?
virtual bool shouldLockMouse () const =0
Should the mouse be locked at the next opportunity ?
Static Public Member Functions
static ScreenResChangeSignal & getScreenResChangeSignal ()
Public Attributes
Event Handlers
Various events that this window receives.
These are all subclasses of JournaledSignal, so you can subscribe to them and receive notifications per the documentation for that class.
AppEvent appEvent
MouseEvent mouseEvent
MouseWheelEvent wheelEvent
ButtonEvent buttonEvent
LinearEvent linearEvent
KeyEvent keyEvent
CharEvent charEvent
DisplayEvent displayEvent
ResizeEvent resizeEvent
IdleEvent idleEvent
Protected Member Functions
PlatformWindow ()
Protected constructor so that the win.
virtual void _setFullscreen (const bool fullScreen)
virtual void _setVideoMode (const GFXVideoMode &mode)
Protected Attributes
PlatformCursorController * mCursorController
Cursor Controller for this Window.
bool mDisplayWindow
This is set as part of the canvas being shown, and flags that the windows should render as normal from now on.
bool mEnableAccelerators
When Torque GuiText input controls have focus they need to disable native OS keyboard accelerator translation.
bool mEnableKeyboardTranslation
Are we enabling IME or other keyboard input translation services, or concerned about raw input?
bool mIsBackground
Is Idle?
Point2I mLockedSize
When the resize is locked, this will be used as both minimum and maximum window size.
Point2I mMinimumSize
Minimum allowed size for this window.
bool mOffscreenRender
Offscreen Render.
bool mResizeLocked
When this is true, resizing is locked.
bool mSuppressReset
Suppress device resets.
WindowId mWindowId
An opaque ID used to resolve references to this Window.
WindowInputGenerator * mWindowInputGenerator
Window Mouse/Key input Controller for this Window.
Static Protected Attributes
static ScreenResChangeSignal smScreenResChangeSignal
Detailed Description
Abstract representation of a native OS window.
Every windowing system has its own representations and conventions as regards the windows on-screen. In order to provide Torque with means for interfacing with multiple windows, tracking their state, etc. we provide this interface.
This interface also allows the app to access the render target for the window it represents, as well as control mode switches, get mode info, and so on.
See also
PlatformWindowManager
Member Enumeration Documentation
enum PlatformWindow::WindowSystem
Enumerator
WindowSystem_Unknown
WindowSystem_Windows
WindowSystem_X11
Constructor & Destructor Documentation
PlatformWindow::PlatformWindow () inline protected
Protected constructor so that the win.
References Point2I::set().
virtual PlatformWindow::~PlatformWindow () inline virtual
To get rid of a window, just delete it.
Make sure the GFXDevice is done with it first!
References SAFE_DELETE.
Member Function Documentation
virtual void PlatformWindow::_setFullscreen (const bool fullScreen) inline protected virtual
Reimplemented in Win32Window, MacWindow, and PlatformWindowSDL.
virtual void PlatformWindow::_setVideoMode (const GFXVideoMode & mode) inline protected virtual
virtual void PlatformWindow::centerWindow () inline virtual
Reimplemented in Win32Window, PlatformWindowSDL, and MacWindow.
References clientToScreen(), isFocused(), isMaximized(), isMinimized(), isOpen(), isVisible(), screenToClient(), and setSize().
virtual bool PlatformWindow::clearFullscreen () pure virtual
If we're fullscreen, this function returns us to desktop mode.
This will be either the last mode that we had that was not fullscreen, or the equivalent mode, windowed.
Implemented in Win32Window, PlatformWindowSDL, and MacWindow.
Referenced by setSuppressReset().
virtual Point2I PlatformWindow::clientToScreen (const Point2I & point) pure virtual
Convert the coordinate given in this window space to screen coordinates.
Implemented in Win32Window, PlatformWindowSDL, and MacWindow.
Referenced by centerWindow().
virtual void PlatformWindow::close () pure virtual
Destroy the window on screen.
Implemented in Win32Window, PlatformWindowSDL, and MacWindow.
Referenced by setFocus().
virtual bool PlatformWindow::getAcceleratorsEnabled () const inline virtual
Returns true if native OS keyboard accelerators are enabled.
References mEnableAccelerators.
virtual bool PlatformWindow::getBackground () inline virtual
Get Idle State (Background)
This is called to poll the window as to it's idle state.
References mIsBackground.
virtual const RectI PlatformWindow::getBounds () const pure virtual
Get the position and size (fullscreen windows are always at (0,0)).
Implemented in Win32Window, PlatformWindowSDL, and MacWindow.
Referenced by lockSize(), and setFocus().
virtual const char* PlatformWindow::getCaption () pure virtual
Get the window's caption.
Implemented in Win32Window, PlatformWindowSDL, and MacWindow.
Referenced by setFocus().
virtual const Point2I PlatformWindow::getClientExtent () pure virtual
Get the Client Area Extent (Resolution) of this window.
Implemented in Win32Window, PlatformWindowSDL, and MacWindow.
Referenced by GFXGLWindowTarget::getSize(), and setFocus().
virtual PlatformCursorController* PlatformWindow::getCursorController () inline virtual
References mCursorController.
virtual void PlatformWindow::getCursorPosition (Point2I & point) inline virtual
Get the cursor position based on logical coordinates from the upper-right corner.
Parameters
point A reference to a Point2I to store the coordinates
References PlatformCursorController::getCursorPosition().
virtual GFXDevice* PlatformWindow::getGFXDevice () pure virtual
Return a pointer to the GFX device this window is bound to.
A GFX device may use many windows, but a window can only be used by a single GFX device.
Implemented in Win32Window, PlatformWindowSDL, and MacWindow.
Referenced by setSuppressReset().
virtual GFXWindowTarget* PlatformWindow::getGFXTarget () pure virtual
Return a pointer to this window's render target.
By setting window targets from different windows, we can effect rendering to multiple windows from a single device.
Implemented in Win32Window, PlatformWindowSDL, and MacWindow.
Referenced by setSuppressReset().
WindowInputGenerator* PlatformWindow::getInputGenerator () const inline
References mWindowInputGenerator.
virtual bool PlatformWindow::getKeyboardTranslation () const inline virtual
Returns true if keyboard translation is enabled.
References mEnableKeyboardTranslation, and shouldNotTranslate().
virtual Point2I PlatformWindow::getLockedSize () inline virtual
Returns the locked window size.
References mLockedSize.
virtual Point2I PlatformWindow::getMinimumWindowSize () inline virtual
Returns the current minimum window size for this window.
References mMinimumSize.
virtual PlatformWindow* PlatformWindow::getNextWindow () const pure virtual
Implemented in Win32Window, PlatformWindowSDL, and MacWindow.
Referenced by isCursorVisible().
virtual bool PlatformWindow::getOffscreenRender () inline virtual
Set whether this window is intended for offscreen rendering.
This is called to poll the window as to it's idle state.
References mOffscreenRender.
virtual void* PlatformWindow::getPlatformDrawable () const pure virtual
Get the platform specific object needed to create or attach an accelerated graohics drawing context on or to the window Win32 D3D and OpenGL typically needs an HWND Mac Cocoa OpenGL typically needs an NSOpenGLView Mac Carbon OpenGL typically needs a WindowRef.
Implemented in Win32Window, PlatformWindowSDL, and MacWindow.
Referenced by getScreenResChangeSignal().
virtual const Point2I PlatformWindow::getPosition () pure virtual
Get the position of this window.
Implemented in Win32Window, PlatformWindowSDL, and MacWindow.
Referenced by setFocus().
static ScreenResChangeSignal& PlatformWindow::getScreenResChangeSignal () inline static
References getPlatformDrawable(), and smScreenResChangeSignal.
virtual void* PlatformWindow::getSystemWindow (const WindowSystem system) inline virtual
Reimplemented in Win32Window, and PlatformWindowSDL.
virtual const GFXVideoMode& PlatformWindow::getVideoMode () pure virtual
Get our current video mode - if the window has been resized, it will reflect this.
Implemented in Win32Window, PlatformWindowSDL, and MacWindow.
Referenced by setSuppressReset().
virtual WindowId PlatformWindow::getWindowId () inline virtual
Get the ID that uniquely identifies this window in the context of its window manager.
Reimplemented in Win32Window, PlatformWindowSDL, and MacWindow.
virtual void PlatformWindow::hide () pure virtual
Hide the window on screen.
Implemented in Win32Window, PlatformWindowSDL, and MacWindow.
Referenced by setFocus().
virtual bool PlatformWindow::isCursorVisible () inline virtual
Get the cursor visibility on this window.
Returns
true if the cursor is visible or false if it's hidden
References getNextWindow(), PlatformCursorController::isCursorVisible(), isMouseLocked(), setMouseLocked(), and shouldLockMouse().
virtual bool PlatformWindow::isFocused () pure virtual
Returns true if the window has input focus.
Implemented in Win32Window, PlatformWindowSDL, and MacWindow.
Referenced by centerWindow().
virtual bool PlatformWindow::isFullscreen () pure virtual
Returns
true if this window is fullscreen, false otherwise.
Implemented in Win32Window, PlatformWindowSDL, and MacWindow.
Referenced by setSuppressReset().
virtual bool PlatformWindow::isMaximized () pure virtual
Returns true if the window is maximized.
Implemented in Win32Window, PlatformWindowSDL, and MacWindow.
Referenced by centerWindow().
virtual bool PlatformWindow::isMinimized () pure virtual
Returns true if the window is minimized.
Implemented in Win32Window, PlatformWindowSDL, and MacWindow.
Referenced by centerWindow().
virtual bool PlatformWindow::isMouseLocked () const pure virtual
Is the mouse locked ?
Implemented in Win32Window, PlatformWindowSDL, and MacWindow.
Referenced by isCursorVisible().
virtual bool PlatformWindow::isOpen () pure virtual
Returns true if the window is instantiated in the OS.
Implemented in Win32Window, PlatformWindowSDL, and MacWindow.
Referenced by centerWindow().
virtual bool PlatformWindow::isSizeLocked () inline virtual
Returns true if the window size is locked.
References mResizeLocked.
virtual bool PlatformWindow::isVisible () pure virtual
Returns true if the window is visible.
Implemented in Win32Window, PlatformWindowSDL, and MacWindow.
Referenced by centerWindow().
virtual void PlatformWindow::lockSize (bool locked) inline virtual
Locks/unlocks window resizing.
References RectI::extent, and getBounds().
virtual void PlatformWindow::maximize () pure virtual
Maximize the window on screen.
Implemented in Win32Window, PlatformWindowSDL, and MacWindow.
Referenced by setFocus().
virtual void PlatformWindow::minimize () pure virtual
Minimize the window on screen.
Implemented in Win32Window, PlatformWindowSDL, and MacWindow.
Referenced by setFocus().
virtual void PlatformWindow::restore () pure virtual
Restore the window from a Maximized or Minimized state.
Implemented in Win32Window, PlatformWindowSDL, and MacWindow.
Referenced by setFocus().
virtual Point2I PlatformWindow::screenToClient (const Point2I & point) pure virtual
Convert the given screen coordinates to coordinates in this window space.
Implemented in Win32Window, PlatformWindowSDL, and MacWindow.
Referenced by centerWindow().
virtual void PlatformWindow::setAcceleratorsEnabled (const bool enabled) inline virtual
Used to disable native OS keyboard accelerators.
virtual void PlatformWindow::setBackground (bool val) inline virtual
Set Idle State (Background)
This is called to put a window into idle state, which causes it's rendering priority to be toned down to prefer performance
virtual void PlatformWindow::setBounds (const RectI & newBounds) pure virtual
The bounds of a Window are defined as the entire area occupied by that Window.
This includes the area needed for a title-bar, menu, borders, and other non-client elements.Resize the window to have some new bounds.
Implemented in Win32Window, PlatformWindowSDL, and MacWindow.
Referenced by setFocus().
virtual bool PlatformWindow::setCaption (const char * cap) pure virtual
Set the window's caption.
Implemented in Win32Window, PlatformWindowSDL, and MacWindow.
Referenced by setFocus().
virtual void PlatformWindow::setClientExtent (const Point2I newExtent) pure virtual
The Client Rectangle or "Render Area" of a window is the area that is occupied by a given client that is rendering to that window.
This does not include the area occupied by a title-bar, menu, borders or other non-client elements.Set the Client Area Extent (Resolution) of this window
Implemented in Win32Window, PlatformWindowSDL, and MacWindow.
Referenced by setFocus().
virtual void PlatformWindow::setCursorPosition (S32 x, S32 y) inline virtual
Set the cursor position based on logical coordinates from the upper-right corner.
Parameters
x The X position of the cursor
y The Y position of the cursor
References PlatformCursorController::setCursorPosition().
virtual void PlatformWindow::setCursorVisible (bool visible) inline virtual
Set the cursor visibility on this window.
Parameters
visible Whether the cursor should be visible or not
References PlatformCursorController::setCursorVisible().
virtual void PlatformWindow::setDisplayWindow (bool val) inline virtual
Set whether this window is should display as normal.
virtual void PlatformWindow::setFocus () inline virtual
Set Focused State (Foreground)
Claim OS input focus for this window
Reimplemented in Win32Window, PlatformWindowSDL, and MacWindow.
References close(), getBounds(), getCaption(), getClientExtent(), getPosition(), hide(), maximize(), minimize(), restore(), setBounds(), setCaption(), setClientExtent(), setPosition(), and show().
void PlatformWindow::setFullscreen (const bool fullscreen)
Acquire the entire screen.
Referenced by setSuppressReset().
virtual void PlatformWindow::setInputController (IProcessInput * controller) inline virtual
Get the WindowController associated with this window.
References WindowInputGenerator::setInputController().
virtual void PlatformWindow::setKeyboardTranslation (const bool enabled) inline virtual
Set if relevant keypress events should be translated into character input events.
Reimplemented in PlatformWindowSDL.
virtual void PlatformWindow::setMinimumWindowSize (Point2I minSize) inline virtual
Sets a minimum window size.
We'll work with the OS to prevent user from sizing the window to less than this. Setting to (0,0) means user has complete freedom of resize.
virtual void PlatformWindow::setMouseLocked (bool enable) pure virtual
Lock the mouse to this window.
When this is set, the mouse will always be returned to the center of the client area after every mouse event. The mouse will also be hidden while it is locked.
The mouse cannot be moved out of the bounds of the window, but the window may lose focus (for instance by an alt-tab or other event). While the window lacks focus, no mouse events will be reported.
Implemented in Win32Window, PlatformWindowSDL, and MacWindow.
Referenced by isCursorVisible().
virtual void PlatformWindow::setOffscreenRender (bool val) inline virtual
Set whether this window is intended for offscreen rendering An offscreen window will never be shown or lose focus.
virtual void PlatformWindow::setPosition (const Point2I newPosition) pure virtual
The Position of a window is always in relation to the very upper left of the window.
This means that saying setPosition at 0,0 will put the position of the window title-bar (if one exists) at 0,0 and the Client area will be offset from that point by the space needed for the Non-Client area.Set the position of this window
Implemented in Win32Window, PlatformWindowSDL, and MacWindow.
Referenced by setFocus().
virtual bool PlatformWindow::setSize (const Point2I & newSize) pure virtual
Resize the window to have a new size (but be in the same position).
Implemented in Win32Window, PlatformWindowSDL, and MacWindow.
Referenced by centerWindow().
void PlatformWindow::setSuppressReset (bool suppress) inline
Set the flag that determines whether to suppress a GFXDevice reset.
References clearFullscreen(), getGFXDevice(), getGFXTarget(), getVideoMode(), isFullscreen(), setFullscreen(), and setVideoMode().
virtual void PlatformWindow::setVideoMode (const GFXVideoMode & mode) virtual
Set the video mode for this window.
Reimplemented in Win32Window, PlatformWindowSDL, and MacWindow.
Referenced by setSuppressReset().
virtual bool PlatformWindow::shouldLockMouse () const pure virtual
Should the mouse be locked at the next opportunity ?
This flag is set to the current state of the mouse lock on a window, to specify the preferred lock status of the mouse in a platform window.
This is important for situations where a call is made to setMouseLocked, and the window is not in a state that it can be cleanly locked. Take for example if it was called while the window is in the background, then it is not appropriate to lock the window, but rather the window should query this state at it's next opportunity and lock the mouse if requested.
Implemented in Win32Window, PlatformWindowSDL, and MacWindow.
Referenced by isCursorVisible().
virtual bool PlatformWindow::shouldNotTranslate (U32 modifiers, U32 keyCode) const virtual
Returns true if the given keypress event should not be translated.
Referenced by getKeyboardTranslation().
virtual void PlatformWindow::show () pure virtual
Show the window on screen.
Implemented in Win32Window, PlatformWindowSDL, and MacWindow.
Referenced by setFocus().
Member Data Documentation
AppEvent PlatformWindow::appEvent
ButtonEvent PlatformWindow::buttonEvent
CharEvent PlatformWindow::charEvent
DisplayEvent PlatformWindow::displayEvent
IdleEvent PlatformWindow::idleEvent
KeyEvent PlatformWindow::keyEvent
LinearEvent PlatformWindow::linearEvent
PlatformCursorController* PlatformWindow::mCursorController protected
Cursor Controller for this Window.
Referenced by getCursorController().
bool PlatformWindow::mDisplayWindow protected
This is set as part of the canvas being shown, and flags that the windows should render as normal from now on.
bool PlatformWindow::mEnableAccelerators protected
When Torque GuiText input controls have focus they need to disable native OS keyboard accelerator translation.
Referenced by getAcceleratorsEnabled().
bool PlatformWindow::mEnableKeyboardTranslation protected
Are we enabling IME or other keyboard input translation services, or concerned about raw input?
Referenced by getKeyboardTranslation().
bool PlatformWindow::mIsBackground protected
Is Idle?
Referenced by getBackground().
Point2I PlatformWindow::mLockedSize protected
When the resize is locked, this will be used as both minimum and maximum window size.
Referenced by getLockedSize().
Point2I PlatformWindow::mMinimumSize protected
Minimum allowed size for this window.
When possible, we will communicate this to the OS.
Referenced by getMinimumWindowSize().
bool PlatformWindow::mOffscreenRender protected
Offscreen Render.
Referenced by getOffscreenRender().
MouseEvent PlatformWindow::mouseEvent
bool PlatformWindow::mResizeLocked protected
When this is true, resizing is locked.
Referenced by isSizeLocked().
bool PlatformWindow::mSuppressReset protected
Suppress device resets.
WindowId PlatformWindow::mWindowId protected
An opaque ID used to resolve references to this Window.
Referenced by MacWindow::getWindowId().
WindowInputGenerator* PlatformWindow::mWindowInputGenerator protected
Window Mouse/Key input Controller for this Window.
Referenced by getInputGenerator().
ResizeEvent PlatformWindow::resizeEvent
ScreenResChangeSignal PlatformWindow::smScreenResChangeSignal static protected
Referenced by getScreenResChangeSignal().
MouseWheelEvent PlatformWindow::wheelEvent
Copyright © GarageGames, LLC. All Rights Reserved.