AdvancedLightManager Class Reference
Main Modules Class List Namespace List Online
AdvancedLightManager Class Reference
#include <lighting/advanced/advancedLightManager.h>
Public Types
typedef GFXVertexPC LightVertex
Public Types inherited from LightManager
enum SpecialLightTypesEnum {
slSunLightType,
slSpecialLightTypesCount
}
Public Member Functions
virtual void activate (SceneManager *sceneManager)
virtual void deactivate ()
LightShadowMap * findShadowMapForObject (SimObject *object)
GFXVertexBufferHandle< LightVertex > getConeMesh (U32 &outNumPrimitives, GFXPrimitiveBuffer *&outPrimitives)
AdvancedLightBinManager * getLightBinManager ()
Return the lightBinManager for this light manager.
GFXVertexBufferHandle< LightVertex > getSphereMesh (U32 &outNumPrimitives, GFXPrimitiveBuffer *&outPrimitives)
virtual bool isCompatible () const
virtual void registerGlobalLight (LightInfo *light, SimObject *obj)
virtual void setLightInfo (ProcessedMaterial *pmat, const Material *mat, const SceneData &sgData, const SceneRenderState *state, U32 pass, GFXShaderConstBuffer *shaderConsts)
Sets shader constants / textures for light infos.
virtual bool setTextureStage (const SceneData &sgData, const U32 currTexFlag, const U32 textureSlot, GFXShaderConstBuffer *shaderConsts, ShaderConstHandles *handles)
Allows us to set textures during the Material::setTextureStage call, return true if we've done work.
virtual void unregisterAllLights ()
Public Member Functions inherited from LightManager
LightManager (const char *name, const char *id)
virtual ~LightManager ()
void getAllUnsortedLights (Vector< LightInfo * > *list) const
Returns all unsorted and un-scored lights (both global and local).
virtual LightInfo * getDefaultLight ()
const char * getId () const
Return an id string used to load different versions of light manager specific assets.
const char * getName () const
Return an id string used to load different versions of light manager specific assets.
virtual AvailableSLInterfaces * getSceneLightingInterface ()
SceneManager * getSceneManager ()
virtual LightInfo * getSpecialLight (SpecialLightTypesEnum type, bool useDefault=true)
Returns the special light or the default light if useDefault is true.
virtual bool isActive () const
Returns true if this light manager is active.
virtual bool lightScene (const char *callback, const char *param)
Called when the static scene lighting (aka lightmaps) should be computed.
virtual void registerGlobalLights (const Frustum *frustum, bool staticlighting)
virtual void registerLocalLight (LightInfo *light)
virtual void setSpecialLight (SpecialLightTypesEnum type, LightInfo *light)
Set a special light type.
virtual void unregisterGlobalLight (LightInfo *light)
virtual void unregisterLocalLight (LightInfo *light)
Protected Member Functions
AdvancedLightManager ()
virtual ~AdvancedLightManager ()
virtual void _addLightInfoEx (LightInfo *lightInfo)
Attaches any LightInfoEx data for this manager to the light info object.
virtual void _initLightFields ()
LightingShaderConstants * getLightingShaderConstants (GFXShaderConstBuffer *shader)
Protected Member Functions inherited from LightManager
RenderPrePassMgr * _findPrePassRenderBin ()
Find the pre-pass render bin on the scene's default render pass.
Protected Attributes
GFXVertexBufferHandle< LightVertex > mConeGeometry
GFXPrimitiveBufferHandle mConeIndices
U32 mConePrimitiveCount
LightConstantMap mConstantLookup
LightingShaderConstants * mLastConstants
GFXShaderRef mLastShader
SimObjectPtr< AdvancedLightBinManager > mLightBinManager
SimObjectPtr< RenderPrePassMgr > mPrePassRenderBin
GFXVertexBufferHandle< LightVertex > mSphereGeometry
GFXPrimitiveBufferHandle mSphereIndices
U32 mSpherePrimitiveCount
Protected Attributes inherited from LightManager
AvailableSLInterfaces * mAvailableSLInterfaces
The scene lighting interfaces for lightmap generation.
Point3F mCullPos
The root culling position used for special sun light placement.
LightInfo * mDefaultLight
A dummy default light used when no lights happen to be registered with the manager.
const String mId
The constant light manager identifier initialized in the constructor.
bool mIsActive
Is true if this light manager has been activated.
const String mName
The constant light manager name initialized in the constructor.
LightInfoList mRegisteredLights
The list of global registered lights which is initialized before the scene is rendered.
SceneManager * mSceneManager
The scene graph the light manager is associated with.
LightInfo * mSpecialLights [slSpecialLightTypesCount]
The registered special light list.
Static Protected Attributes
static AdvancedLightManager smSingleton
A simple protected singleton.
Static Protected Attributes inherited from LightManager
static LightManager * smActiveLM
The current active light manager.
Additional Inherited Members
Static Public Member Functions inherited from LightManager
static LightInfo * createLightInfo (LightInfo *light=NULL)
static LightManager * findByName (const char *name)
static LightManager * getActiveLM ()
Returns the active LM.
static void getLightManagerNames (String *outString)
Returns a tab seperated list of available light managers.
static void initLightFields ()
Static Public Attributes inherited from LightManager
static Signal< void(const char *, bool)> smActivateSignal
The light manager activation signal.
Static Protected Member Functions inherited from LightManager
static LightManagerMap & _getLightManagers ()
Returns the static light manager map.
static void _update4LightConsts (const SceneData &sgData, GFXShaderConstHandle *lightPositionSC, GFXShaderConstHandle *lightDiffuseSC, GFXShaderConstHandle *lightAmbientSC, GFXShaderConstHandle *lightInvRadiusSqSC, GFXShaderConstHandle *lightSpotDirSC, GFXShaderConstHandle *lightSpotAngleSC, GFXShaderConstHandle *lightSpotFalloffSC, GFXShaderConstBuffer *shaderConsts)
This helper function sets the shader constansts for the stock 4 light forward lighting code.
Member Typedef Documentation
typedef GFXVertexPC AdvancedLightManager::LightVertex
Constructor & Destructor Documentation
AdvancedLightManager::AdvancedLightManager () protected
virtual AdvancedLightManager::~AdvancedLightManager () protected virtual
Member Function Documentation
virtual void AdvancedLightManager::_addLightInfoEx (LightInfo * lightInfo) protected virtual
Attaches any LightInfoEx data for this manager to the light info object.
Implements LightManager.
virtual void AdvancedLightManager::_initLightFields () protected virtual
Implements LightManager.
virtual void AdvancedLightManager::activate (SceneManager * sceneManager) virtual
Reimplemented from LightManager.
Referenced by getLightBinManager().
virtual void AdvancedLightManager::deactivate () virtual
Reimplemented from LightManager.
Referenced by getLightBinManager().
LightShadowMap* AdvancedLightManager::findShadowMapForObject (SimObject * object)
GFXVertexBufferHandle<LightVertex> AdvancedLightManager::getConeMesh (U32 & outNumPrimitives, GFXPrimitiveBuffer *& outPrimitives)
AdvancedLightBinManager* AdvancedLightManager::getLightBinManager () inline
Return the lightBinManager for this light manager.
References activate(), deactivate(), isCompatible(), mLightBinManager, registerGlobalLight(), setLightInfo(), setTextureStage(), and unregisterAllLights().
LightingShaderConstants* AdvancedLightManager::getLightingShaderConstants (GFXShaderConstBuffer * shader) protected
GFXVertexBufferHandle<LightVertex> AdvancedLightManager::getSphereMesh (U32 & outNumPrimitives, GFXPrimitiveBuffer *& outPrimitives)
virtual bool AdvancedLightManager::isCompatible () const virtual
Implements LightManager.
Referenced by getLightBinManager().
virtual void AdvancedLightManager::registerGlobalLight (LightInfo * light, SimObject * obj) virtual
Reimplemented from LightManager.
Referenced by getLightBinManager().
virtual void AdvancedLightManager::setLightInfo (ProcessedMaterial * pmat, const Material * mat, const SceneData & sgData, const SceneRenderState * state, U32 pass, GFXShaderConstBuffer * shaderConsts) virtual
Sets shader constants / textures for light infos.
Implements LightManager.
Referenced by getLightBinManager().
virtual bool AdvancedLightManager::setTextureStage (const SceneData & sgData, const U32 currTexFlag, const U32 textureSlot, GFXShaderConstBuffer * shaderConsts, ShaderConstHandles * handles) virtual
Allows us to set textures during the Material::setTextureStage call, return true if we've done work.
Implements LightManager.
Referenced by getLightBinManager().
virtual void AdvancedLightManager::unregisterAllLights () virtual
Reimplemented from LightManager.
Referenced by getLightBinManager().
Member Data Documentation
GFXVertexBufferHandle<LightVertex> AdvancedLightManager::mConeGeometry protected
GFXPrimitiveBufferHandle AdvancedLightManager::mConeIndices protected
U32 AdvancedLightManager::mConePrimitiveCount protected
LightConstantMap AdvancedLightManager::mConstantLookup protected
LightingShaderConstants* AdvancedLightManager::mLastConstants protected
GFXShaderRef AdvancedLightManager::mLastShader protected
SimObjectPtr<AdvancedLightBinManager> AdvancedLightManager::mLightBinManager protected
Referenced by getLightBinManager().
SimObjectPtr<RenderPrePassMgr> AdvancedLightManager::mPrePassRenderBin protected
GFXVertexBufferHandle<LightVertex> AdvancedLightManager::mSphereGeometry protected
GFXPrimitiveBufferHandle AdvancedLightManager::mSphereIndices protected
U32 AdvancedLightManager::mSpherePrimitiveCount protected
AdvancedLightManager AdvancedLightManager::smSingleton static protected
A simple protected singleton.
Use LightManager::findByName() to access this light manager.
See also
LightManager::findByName()
Copyright © GarageGames, LLC. All Rights Reserved.