ShaderFeatureConstHandles Class Reference
Main Modules Class List Namespace List Online
ShaderFeatureConstHandles Class Reference abstract
#include <shaderGen/shaderFeature.h>
Public Member Functions
virtual ~ShaderFeatureConstHandles ()
virtual void init (GFXShader *shader)=0
virtual void setConsts (SceneRenderState *state, const SceneData &sgData, GFXShaderConstBuffer *buffer)=0
Constructor & Destructor Documentation
virtual ShaderFeatureConstHandles::~ShaderFeatureConstHandles () inline virtual
References init(), and setConsts().
Member Function Documentation
virtual void ShaderFeatureConstHandles::init (GFXShader * shader) pure virtual
Implemented in GroundCoverShaderConstHandles, and WindDeformationConstHandles.
Referenced by ~ShaderFeatureConstHandles().
virtual void ShaderFeatureConstHandles::setConsts (SceneRenderState * state, const SceneData & sgData, GFXShaderConstBuffer * buffer) pure virtual
Implemented in GroundCoverShaderConstHandles, and WindDeformationConstHandles.
Referenced by ~ShaderFeatureConstHandles().
Copyright © GarageGames, LLC. All Rights Reserved.