ShaderGenPrinter Class Reference
Main Modules Class List Namespace List Online
ShaderGenPrinter Class Reference abstract
Base class used by shaderGen to be API agnostic.
#include <shaderGen/shaderGen.h>
Public Member Functions
virtual ~ShaderGenPrinter ()
virtual void printLine (Stream &stream, const String &line)=0
virtual void printMainComment (Stream &stream)=0
Prints a comment block specifying the beginning of the main() function (or equivalent)
virtual void printPixelShaderCloser (Stream &stream)=0
Prints the final line of the pixel shader.
virtual void printPixelShaderOutputStruct (Stream &stream, const MaterialFeatureData &featureData)=0
Prints the output struct for the pixel shader. Probably only used in HLSL/Cg.
virtual void printShaderHeader (Stream &stream)=0
Prints a simple header, including the engine name, language type, and the fact that the shader was procedurally generated.
virtual void printVertexShaderCloser (Stream &stream)=0
Prints the final line of the vertex shader, e.g. return OUT; }, }, END.
Detailed Description
Base class used by shaderGen to be API agnostic.
Subclasses implement the various methods in an API specific way.
Constructor & Destructor Documentation
virtual ShaderGenPrinter::~ShaderGenPrinter () inline virtual
References printLine(), printMainComment(), printPixelShaderCloser(), printPixelShaderOutputStruct(), printShaderHeader(), and printVertexShaderCloser().
Member Function Documentation
virtual void ShaderGenPrinter::printLine (Stream & stream, const String & line) pure virtual
Implemented in ShaderGenPrinterGLSL, and ShaderGenPrinterHLSL.
Referenced by ~ShaderGenPrinter().
virtual void ShaderGenPrinter::printMainComment (Stream & stream) pure virtual
Prints a comment block specifying the beginning of the main() function (or equivalent)
Implemented in ShaderGenPrinterGLSL, and ShaderGenPrinterHLSL.
Referenced by ~ShaderGenPrinter().
virtual void ShaderGenPrinter::printPixelShaderCloser (Stream & stream) pure virtual
Prints the final line of the pixel shader.
Implemented in ShaderGenPrinterGLSL, and ShaderGenPrinterHLSL.
Referenced by ~ShaderGenPrinter().
virtual void ShaderGenPrinter::printPixelShaderOutputStruct (Stream & stream, const MaterialFeatureData & featureData) pure virtual
Prints the output struct for the pixel shader. Probably only used in HLSL/Cg.
Implemented in ShaderGenPrinterGLSL, and ShaderGenPrinterHLSL.
Referenced by ~ShaderGenPrinter().
virtual void ShaderGenPrinter::printShaderHeader (Stream & stream) pure virtual
Prints a simple header, including the engine name, language type, and the fact that the shader was procedurally generated.
Implemented in ShaderGenPrinterGLSL, and ShaderGenPrinterHLSL.
Referenced by ~ShaderGenPrinter().
virtual void ShaderGenPrinter::printVertexShaderCloser (Stream & stream) pure virtual
Prints the final line of the vertex shader, e.g. return OUT; }, }, END.
Implemented in ShaderGenPrinterGLSL, and ShaderGenPrinterHLSL.
Referenced by ~ShaderGenPrinter().
Copyright © GarageGames, LLC. All Rights Reserved.