GFXVertexColor Class Reference
Main Modules Class List Namespace List Online
GFXVertexColor Class Reference
#include <gfx/gfxVertexColor.h>
Public Member Functions
GFXVertexColor ()
GFXVertexColor (const ColorI &color)
void getColor (ColorI *color) const
const U32 & getPackedColorData () const
operator const U32 * () const
GFXVertexColor & operator= (const ColorI &color)
void set (U8 red, U8 green, U8 blue, U8 alpha=255)
void set (const ColorI &color)
Static Public Member Functions
static void setSwizzle (Swizzle< U8, 4 > *val)
Constructor & Destructor Documentation
GFXVertexColor::GFXVertexColor () inline
GFXVertexColor::GFXVertexColor (const ColorI & color) inline
Member Function Documentation
void GFXVertexColor::getColor (ColorI * color) const inline
References Swizzle< T, mapLength >::ToBuffer().
const U32& GFXVertexColor::getPackedColorData () const inline
GFXVertexColor::operator const U32 * () const inline
GFXVertexColor& GFXVertexColor::operator= (const ColorI & color) inline
void GFXVertexColor::set (U8 red, U8 green, U8 blue, U8 alpha = 255) inline
References Swizzle< T, mapLength >::InPlace().
void GFXVertexColor::set (const ColorI & color) inline
References Swizzle< T, mapLength >::ToBuffer().
static void GFXVertexColor::setSwizzle (Swizzle< U8, 4 > * val) inline static
Copyright © GarageGames, LLC. All Rights Reserved.