SceneZoneSpaceManager::ZoneContentIterator Class Reference
Main Modules Class List Namespace List Online
SceneZoneSpaceManager::ZoneContentIterator Class Reference
Iterator for the contents of a given zone.
#include <scene/zones/sceneZoneSpaceManager.h>
Public Member Functions
ZoneContentIterator (SceneZoneSpaceManager *manager, S32 zoneId, bool upToDate=true)
bool isValid () const
bool operator! () const
SceneObject * operator* () const
ZoneContentIterator & operator++ ()
ZoneContentIterator & operator-- ()
SceneObject * operator-> () const
Detailed Description
Iterator for the contents of a given zone.
Constructor & Destructor Documentation
SceneZoneSpaceManager::ZoneContentIterator::ZoneContentIterator (SceneZoneSpaceManager * manager, S32 zoneId, bool upToDate = true) inline
References SceneZoneSpaceManager::_rezoneObjects(), SceneZoneSpaceManager::getNumZones(), SceneZoneSpaceManager::getZoneOwner(), and SceneZoneSpaceManager::mZoneLists.
Member Function Documentation
bool SceneZoneSpaceManager::ZoneContentIterator::isValid () const inline
bool SceneZoneSpaceManager::ZoneContentIterator::operator! () const inline
SceneObject* SceneZoneSpaceManager::ZoneContentIterator::operator* (void) const inline
References SceneObjectRefBase< T >::object.
ZoneContentIterator& SceneZoneSpaceManager::ZoneContentIterator::operator++ () inline
References SceneObjectRefBase< T >::nextInBin.
ZoneContentIterator& SceneZoneSpaceManager::ZoneContentIterator::operator-- () inline
References SceneObjectRefBase< T >::prevInBin.
SceneObject* SceneZoneSpaceManager::ZoneContentIterator::operator-> (void) const inline
References SceneObjectRefBase< T >::object.
Copyright © GarageGames, LLC. All Rights Reserved.