GFXVertexFormat Class Reference
Main Modules Class List Namespace List Online
GFXVertexFormat Class Reference
The vertex format structure usually created via the declare and implement macros.
#include <gfx/gfxVertexFormat.h>
Public Member Functions
GFXVertexFormat ()
Default constructor for an empty format.
GFXVertexFormat (const GFXVertexFormat &format)
The copy constructor.
void addElement (const String &semantic, GFXDeclType type, U32 index=0, U32 stream=0)
Adds a vertex element to the format.
void append (const GFXVertexFormat &format, U32 streamIndex=-1)
Used to append a vertex format to the end of this one.
void clear ()
Clears all the vertex elements.
void copy (const GFXVertexFormat &format)
Copy the other vertex format.
void enableInstancing ()
Tell this format it has instancing.
GFXVertexDecl * getDecl () const
Returns the hardware specific vertex declaration for this format.
const String & getDescription () const
Returns a unique description string for this vertex format.
const GFXVertexElement & getElement (U32 index) const
Returns the vertex element by index.
U32 getElementCount () const
Returns the total elements in this format.
U32 getNumBlendIndices () const
Returns number of blend indices.
U32 getSizeInBytes () const
Returns the size in bytes of the format as described.
U32 getTexCoordCount () const
Returns the texture coordinate count by counting the number of TEXCOORD semantics.
bool hasBlendIndices () const
Returns true if there is a BLENDWEIGHT or BLENDINDICES semantic in this vertex format.
bool hasColor () const
Returns true if there is a COLOR semantic in this vertex format.
bool hasInstancing () const
Return true if instancing is used with this vertex format.
bool hasNormal () const
Returns true if there is a NORMAL semantic in this vertex format.
bool hasTangent () const
Returns true if there is a TANGENT semantic in this vertex format.
bool isEqual (const GFXVertexFormat &format) const
Returns true if these two formats are equal.
Protected Member Functions
void _updateDecl ()
Requests the vertex declaration from the GFX device.
void _updateDirty ()
Recreates the description and state when the format has been modified.
GFXVertexFormat & operator= (const GFXVertexFormat &)
We disable the copy operator.
Protected Attributes
GFXVertexDecl * mDecl
The hardware specific vertex declaration.
String mDescription
An interned string which uniquely identifies the format.
bool mDirty
Set when the element list is changed.
Vector< GFXVertexElement > mElements
The elements of the vertex format.
bool mHasBlendIndices
Is true if there is a BLENDWEIGHT or BLENDINDICES semantic in this vertex format.
bool mHasColor
Is true if there is a COLOR semantic in this vertex format.
bool mHasInstancing
Is instaning used with this vertex format.
bool mHasNormal
Is set if there is a NORMAL semantic in this vertex format.
bool mHasTangent
Is true if there is a TANGENT semantic in this vertex format.
U32 mSizeInBytes
The size in bytes of the vertex format as described.
U32 mTexCoordCount
The texture coordinate count by counting the number of "TEXCOORD" semantics.
Detailed Description
The vertex format structure usually created via the declare and implement macros.
You can use this class directly to create a vertex format, but note that it is expected to live as long as the VB that uses it exists.
See also
GFXDeclareVertexFormat
GFXImplementVertexFormat
GFXVertexElement
Constructor & Destructor Documentation
GFXVertexFormat::GFXVertexFormat ()
Default constructor for an empty format.
GFXVertexFormat::GFXVertexFormat (const GFXVertexFormat & format) inline
The copy constructor.
Member Function Documentation
void GFXVertexFormat::_updateDecl () protected
Requests the vertex declaration from the GFX device.
void GFXVertexFormat::_updateDirty () protected
Recreates the description and state when the format has been modified.
void GFXVertexFormat::addElement (const String & semantic, GFXDeclType type, U32 index = 0, U32 stream = 0)
Adds a vertex element to the format.
Parameters
semantic A valid Torque semantic string.
type The element type.
index The semantic index which is typically only used for texcoords.
void GFXVertexFormat::append (const GFXVertexFormat & format, U32 streamIndex = -1)
Used to append a vertex format to the end of this one.
void GFXVertexFormat::clear ()
Clears all the vertex elements.
void GFXVertexFormat::copy (const GFXVertexFormat & format)
Copy the other vertex format.
Referenced by GFXVertexBuffer::GFXVertexBuffer(), and ProcessedShaderMaterial::InstancingState::setFormat().
void GFXVertexFormat::enableInstancing ()
Tell this format it has instancing.
GFXVertexDecl* GFXVertexFormat::getDecl () const
Returns the hardware specific vertex declaration for this format.
Referenced by GFXVertexBuffer::GFXVertexBuffer(), and GFXDevice::setVertexFormat().
const String& GFXVertexFormat::getDescription () const
Returns a unique description string for this vertex format.
Referenced by isEqual().
const GFXVertexElement& GFXVertexFormat::getElement (U32 index) const inline
Returns the vertex element by index.
U32 GFXVertexFormat::getElementCount () const inline
Returns the total elements in this format.
U32 GFXVertexFormat::getNumBlendIndices () const
Returns number of blend indices.
U32 GFXVertexFormat::getSizeInBytes () const
Returns the size in bytes of the format as described.
Referenced by GFXVertexElement::isSemantic().
U32 GFXVertexFormat::getTexCoordCount () const
Returns the texture coordinate count by counting the number of TEXCOORD semantics.
bool GFXVertexFormat::hasBlendIndices () const
Returns true if there is a BLENDWEIGHT or BLENDINDICES semantic in this vertex format.
bool GFXVertexFormat::hasColor () const
Returns true if there is a COLOR semantic in this vertex format.
bool GFXVertexFormat::hasInstancing () const
Return true if instancing is used with this vertex format.
bool GFXVertexFormat::hasNormal () const
Returns true if there is a NORMAL semantic in this vertex format.
bool GFXVertexFormat::hasTangent () const
Returns true if there is a TANGENT semantic in this vertex format.
bool GFXVertexFormat::isEqual (const GFXVertexFormat & format) const inline
Returns true if these two formats are equal.
References String::c_str(), and getDescription().
GFXVertexFormat& GFXVertexFormat::operator= (const GFXVertexFormat &) inline protected
We disable the copy operator.
Member Data Documentation
GFXVertexDecl* GFXVertexFormat::mDecl protected
The hardware specific vertex declaration.
String GFXVertexFormat::mDescription protected
An interned string which uniquely identifies the format.
bool GFXVertexFormat::mDirty protected
Set when the element list is changed.
Vector<GFXVertexElement> GFXVertexFormat::mElements protected
The elements of the vertex format.
bool GFXVertexFormat::mHasBlendIndices protected
Is true if there is a BLENDWEIGHT or BLENDINDICES semantic in this vertex format.
bool GFXVertexFormat::mHasColor protected
Is true if there is a COLOR semantic in this vertex format.
bool GFXVertexFormat::mHasInstancing protected
Is instaning used with this vertex format.
bool GFXVertexFormat::mHasNormal protected
Is set if there is a NORMAL semantic in this vertex format.
bool GFXVertexFormat::mHasTangent protected
Is true if there is a TANGENT semantic in this vertex format.
U32 GFXVertexFormat::mSizeInBytes protected
The size in bytes of the vertex format as described.
U32 GFXVertexFormat::mTexCoordCount protected
The texture coordinate count by counting the number of "TEXCOORD" semantics.
Copyright © GarageGames, LLC. All Rights Reserved.