IOHelper Namespace Reference
Main Modules Class List Namespace List Online
IOHelper Namespace Reference
Helper templates to aggregate IO operations - generally used in template expansion.
Functions
template<class A , class B , class C , class D , class E , class F , class G , class H , class I , class J , class K , class L , class M >
bool reads (Stream *s, A &a, B &b, C &c, D &d, E &e, F &f, G &g, H &h, I &i, J &j, K &k, L &l, M &m)
template<class A , class B , class C , class D , class E , class F , class G , class H , class I , class J , class K , class L >
bool reads (Stream *s, A &a, B &b, C &c, D &d, E &e, F &f, G &g, H &h, I &i, J &j, K &k, L &l)
template<class A , class B , class C , class D , class E , class F , class G , class H , class I , class J , class K >
bool reads (Stream *s, A &a, B &b, C &c, D &d, E &e, F &f, G &g, H &h, I &i, J &j, K &k)
template<class A , class B , class C , class D , class E , class F , class G , class H , class I , class J >
bool reads (Stream *s, A &a, B &b, C &c, D &d, E &e, F &f, G &g, H &h, I &i, J &j)
template<class A , class B , class C , class D , class E , class F , class G , class H , class I >
bool reads (Stream *s, A &a, B &b, C &c, D &d, E &e, F &f, G &g, H &h, I &i)
template<class A , class B , class C , class D , class E , class F , class G , class H >
bool reads (Stream *s, A &a, B &b, C &c, D &d, E &e, F &f, G &g, H &h)
template<class A , class B , class C , class D , class E , class F , class G >
bool reads (Stream *s, A &a, B &b, C &c, D &d, E &e, F &f, G &g)
template<class A , class B , class C , class D , class E , class F >
bool reads (Stream *s, A &a, B &b, C &c, D &d, E &e, F &f)
template<class A , class B , class C , class D , class E >
bool reads (Stream *s, A &a, B &b, C &c, D &d, E &e)
template<class A , class B , class C , class D >
bool reads (Stream *s, A &a, B &b, C &c, D &d)
template<class A , class B , class C >
bool reads (Stream *s, A &a, B &b, C &c)
template<class A , class B >
bool reads (Stream *s, A &a, B &b)
template<class A >
bool reads (Stream *s, A &a)
template<class A , class B , class C , class D , class E , class F , class G , class H , class I , class J , class K , class L , class M >
bool writes (Stream *s, A &a, B &b, C &c, D &d, E &e, F &f, G &g, H &h, I &i, J &j, K &k, L &l, M &m)
template<class A , class B , class C , class D , class E , class F , class G , class H , class I , class J , class K , class L >
bool writes (Stream *s, A &a, B &b, C &c, D &d, E &e, F &f, G &g, H &h, I &i, J &j, K &k, L &l)
template<class A , class B , class C , class D , class E , class F , class G , class H , class I , class J , class K >
bool writes (Stream *s, A &a, B &b, C &c, D &d, E &e, F &f, G &g, H &h, I &i, J &j, K &k)
template<class A , class B , class C , class D , class E , class F , class G , class H , class I , class J >
bool writes (Stream *s, A &a, B &b, C &c, D &d, E &e, F &f, G &g, H &h, I &i, J &j)
template<class A , class B , class C , class D , class E , class F , class G , class H , class I >
bool writes (Stream *s, A &a, B &b, C &c, D &d, E &e, F &f, G &g, H &h, I &i)
template<class A , class B , class C , class D , class E , class F , class G , class H >
bool writes (Stream *s, A &a, B &b, C &c, D &d, E &e, F &f, G &g, H &h)
template<class A , class B , class C , class D , class E , class F , class G >
bool writes (Stream *s, A &a, B &b, C &c, D &d, E &e, F &f, G &g)
template<class A , class B , class C , class D , class E , class F >
bool writes (Stream *s, A &a, B &b, C &c, D &d, E &e, F &f)
template<class A , class B , class C , class D , class E >
bool writes (Stream *s, A &a, B &b, C &c, D &d, E &e)
template<class A , class B , class C , class D >
bool writes (Stream *s, A &a, B &b, C &c, D &d)
template<class A , class B , class C >
bool writes (Stream *s, A &a, B &b, C &c)
template<class A , class B >
bool writes (Stream *s, A &a, B &b)
template<class A >
bool writes (Stream *s, A &a)
Detailed Description
Helper templates to aggregate IO operations - generally used in template expansion.
Function Documentation
template<class A , class B , class C , class D , class E , class F , class G , class H , class I , class J , class K , class L , class M > bool IOHelper::reads (Stream * s, A & a, B & b, C & c, D & d, E & e, F & f, G & g, H & h, I & i, J & j, K & k, L & l, M & m) inline
References Stream::read().
template<class A , class B , class C , class D , class E , class F , class G , class H , class I , class J , class K , class L > bool IOHelper::reads (Stream * s, A & a, B & b, C & c, D & d, E & e, F & f, G & g, H & h, I & i, J & j, K & k, L & l) inline
References Stream::read().
template<class A , class B , class C , class D , class E , class F , class G , class H , class I , class J , class K > bool IOHelper::reads (Stream * s, A & a, B & b, C & c, D & d, E & e, F & f, G & g, H & h, I & i, J & j, K & k) inline
References Stream::read().
template<class A , class B , class C , class D , class E , class F , class G , class H , class I , class J > bool IOHelper::reads (Stream * s, A & a, B & b, C & c, D & d, E & e, F & f, G & g, H & h, I & i, J & j) inline
References Stream::read().
template<class A , class B , class C , class D , class E , class F , class G , class H , class I > bool IOHelper::reads (Stream * s, A & a, B & b, C & c, D & d, E & e, F & f, G & g, H & h, I & i) inline
References Stream::read().
template<class A , class B , class C , class D , class E , class F , class G , class H > bool IOHelper::reads (Stream * s, A & a, B & b, C & c, D & d, E & e, F & f, G & g, H & h) inline
References Stream::read().
template<class A , class B , class C , class D , class E , class F , class G > bool IOHelper::reads (Stream * s, A & a, B & b, C & c, D & d, E & e, F & f, G & g) inline
References Stream::read().
template<class A , class B , class C , class D , class E , class F > bool IOHelper::reads (Stream * s, A & a, B & b, C & c, D & d, E & e, F & f) inline
References Stream::read().
template<class A , class B , class C , class D , class E > bool IOHelper::reads (Stream * s, A & a, B & b, C & c, D & d, E & e) inline
References Stream::read().
template<class A , class B , class C , class D > bool IOHelper::reads (Stream * s, A & a, B & b, C & c, D & d) inline
References Stream::read().
template<class A , class B , class C > bool IOHelper::reads (Stream * s, A & a, B & b, C & c) inline
References Stream::read().
template<class A , class B > bool IOHelper::reads (Stream * s, A & a, B & b) inline
References Stream::read().
template<class A > bool IOHelper::reads (Stream * s, A & a) inline
References Stream::read().
template<class A , class B , class C , class D , class E , class F , class G , class H , class I , class J , class K , class L , class M > bool IOHelper::writes (Stream * s, A & a, B & b, C & c, D & d, E & e, F & f, G & g, H & h, I & i, J & j, K & k, L & l, M & m) inline
References Stream::write().
template<class A , class B , class C , class D , class E , class F , class G , class H , class I , class J , class K , class L > bool IOHelper::writes (Stream * s, A & a, B & b, C & c, D & d, E & e, F & f, G & g, H & h, I & i, J & j, K & k, L & l) inline
References Stream::write().
template<class A , class B , class C , class D , class E , class F , class G , class H , class I , class J , class K > bool IOHelper::writes (Stream * s, A & a, B & b, C & c, D & d, E & e, F & f, G & g, H & h, I & i, J & j, K & k) inline
References Stream::write().
template<class A , class B , class C , class D , class E , class F , class G , class H , class I , class J > bool IOHelper::writes (Stream * s, A & a, B & b, C & c, D & d, E & e, F & f, G & g, H & h, I & i, J & j) inline
References Stream::write().
template<class A , class B , class C , class D , class E , class F , class G , class H , class I > bool IOHelper::writes (Stream * s, A & a, B & b, C & c, D & d, E & e, F & f, G & g, H & h, I & i) inline
References Stream::write().
template<class A , class B , class C , class D , class E , class F , class G , class H > bool IOHelper::writes (Stream * s, A & a, B & b, C & c, D & d, E & e, F & f, G & g, H & h) inline
References Stream::write().
template<class A , class B , class C , class D , class E , class F , class G > bool IOHelper::writes (Stream * s, A & a, B & b, C & c, D & d, E & e, F & f, G & g) inline
References Stream::write().
template<class A , class B , class C , class D , class E , class F > bool IOHelper::writes (Stream * s, A & a, B & b, C & c, D & d, E & e, F & f) inline
References Stream::write().
template<class A , class B , class C , class D , class E > bool IOHelper::writes (Stream * s, A & a, B & b, C & c, D & d, E & e) inline
References Stream::write().
template<class A , class B , class C , class D > bool IOHelper::writes (Stream * s, A & a, B & b, C & c, D & d) inline
References Stream::write().
template<class A , class B , class C > bool IOHelper::writes (Stream * s, A & a, B & b, C & c) inline
References Stream::write().
template<class A , class B > bool IOHelper::writes (Stream * s, A & a, B & b) inline
References Stream::write().
template<class A > bool IOHelper::writes (Stream * s, A & a) inline
References Stream::write().
Copyright © GarageGames, LLC. All Rights Reserved.