SFXInternal Namespace Reference
Main Modules Class List Namespace List Online
SFXInternal Namespace Reference
Classes
class SFXAsyncQueue
An async stream queue that writes sound packets to SFXBuffers in sync to the playback of an SFXVoice.
class SFXAsyncStream
Asynchronous sound data stream that delivers sound data in discrete packets.
class SFXStreamPacket
Sound stream packets are raw byte buffers containing PCM sample data.
class SFXThreadPool
Thread pool for sound I/O.
class SFXVoiceTimeSource
Wrapper around SFXVoice that yields the raw underlying sample position rather than the virtualized position returned by SFXVoice::getPosition().
class SFXWrapAroundBuffer
Buffer that uses wrap-around packet buffering.
Typedefs
typedef AsyncUpdateList SFXBufferProcessList
typedef AsyncUpdateThread SFXUpdateThread
Enumerations
enum {
MAIN_THREAD_PROCESS_TIMEOUT = 512,
DEFAULT_UPDATE_INTERVAL = 512
}
Functions
bool isSFXThread ()
Return true if the current thread is the one responsible for doing SFX updates.
void PurgeDeadBuffers ()
Delete all buffers currently on the dead buffer list.
ThreadPool & THREAD_POOL ()
Return the thread pool used for SFX work.
bool TriggerUpdate ()
Trigger an SFX update.
SFXBufferProcessList & UPDATE_LIST ()
Return the processing list for SFXBuffers that need updating.
ThreadSafeRef< SFXUpdateThread > UPDATE_THREAD ()
Return the dedicated SFX update thread; NULL if updating on the main thread.
Variables
ThreadSafeRef< SFXBufferProcessList > gBufferUpdateList
List of buffers that need updating.
ThreadSafeDeque< SFXBuffer * > gDeadBufferList
List of buffers that are pending deletion.
ThreadSafeRef< AsyncUpdateThread > gUpdateThread
Dedicated thread that does sound buffer updates.
Typedef Documentation
typedef AsyncUpdateList SFXInternal::SFXBufferProcessList
typedef AsyncUpdateThread SFXInternal::SFXUpdateThread
Enumeration Type Documentation
anonymous enum
Enumerator
MAIN_THREAD_PROCESS_TIMEOUT
Soft limit on milliseconds to spend on updating sound buffers when doing buffer updates on the main thread.
DEFAULT_UPDATE_INTERVAL
Default time interval between periodic sound updates in milliseconds.
Only relevant for devices that perform periodic updates.
Function Documentation
bool SFXInternal::isSFXThread () inline
Return true if the current thread is the one responsible for doing SFX updates.
References ThreadManager::compare(), ThreadManager::getCurrentThreadId(), ThreadManager::getMainThreadId(), and UPDATE_THREAD().
void SFXInternal::PurgeDeadBuffers () inline
Delete all buffers currently on the dead buffer list.
References ThreadSafeDeque< T >::tryPopFront().
ThreadPool& SFXInternal::THREAD_POOL () inline
Return the thread pool used for SFX work.
References ManagedSingleton< SFXThreadPool >::instance().
bool SFXInternal::TriggerUpdate () inline
Trigger an SFX update.
References UPDATE_THREAD().
SFXBufferProcessList& SFXInternal::UPDATE_LIST () inline
Return the processing list for SFXBuffers that need updating.
References gBufferUpdateList.
ThreadSafeRef< SFXUpdateThread > SFXInternal::UPDATE_THREAD () inline
Return the dedicated SFX update thread; NULL if updating on the main thread.
References gUpdateThread.
Referenced by isSFXThread(), and TriggerUpdate().
Variable Documentation
ThreadSafeRef< SFXBufferProcessList > SFXInternal::gBufferUpdateList
List of buffers that need updating.
It depends on the actual device whether this list is processed on a stream update thread or on the main thread.
Referenced by SFXInternal::SFXThreadPool::getSingletonName(), and UPDATE_LIST().
ThreadSafeDeque< SFXBuffer* > SFXInternal::gDeadBufferList
List of buffers that are pending deletion.
This is a messy issue. Buffers with live async states cannot be instantly deleted since they may still be running concurrent updates. However, they also cannot be deleted on the update thread since the StrongRefBase stuff isn't thread-safe (i.e weak references kept by client code would cause trouble).
So, what we do is mark buffers for deletion, wait till they surface on the process list and then ping them back to this list to have them deleted by the SFXDevice itself on the main thread. A bit of overhead but only a fraction of the buffers will ever undergo this procedure.
Referenced by SFXInternal::SFXThreadPool::getSingletonName().
ThreadSafeRef< AsyncUpdateThread > SFXInternal::gUpdateThread
Dedicated thread that does sound buffer updates.
May be NULL if sound API used does not do asynchronous buffer updates but rather uses per-frame polling.
Note
SFXDevice automatically polls if this is NULL.
Referenced by SFXInternal::SFXThreadPool::getSingletonName(), and UPDATE_THREAD().
Copyright © GarageGames, LLC. All Rights Reserved.