Platform Namespace Reference
Main Modules Class List Namespace List Online
Platform Namespace Reference
Namespaces
FS
Classes
struct FileInfo
struct KeyboardInputExclusion
Description of a keyboard input we want to ignore.
struct LocalTime
struct SystemInfo_struct
struct VolumeInformation
Enumerations
enum ALERT_ASSERT_RESULT {
ALERT_ASSERT_DEBUG,
ALERT_ASSERT_IGNORE,
ALERT_ASSERT_IGNORE_ALL,
ALERT_ASSERT_EXIT
}
Functions
void addExcludedDirectory (const char *pDir)
void addKeyboardInputExclusion (const KeyboardInputExclusion &kie)
Add a new keyboard exclusion.
void advanceTime (U32 delta)
ALERT_ASSERT_RESULT AlertAssert (const char *windowTitle, const char *message)
void AlertOK (const char *windowTitle, const char *message)
bool AlertOKCancel (const char *windowTitle, const char *message)
bool AlertRetry (const char *windowTitle, const char *message)
bool cdFileExists (const char *filePath, const char *volumeName, S32 serialNum)
const bool checkKeyboardInputExclusion (const InputEventInfo *info)
Check if a given input event should be excluded.
bool checkOtherInstances (const char *string)
void clearExcludedDirectories ()
void clearKeyboardInputExclusion ()
Reset the keyboard input exclusion list.
bool closeSplashWindow ()
void closeWindow ()
S32 compareFileTimes (const FileTime &a, const FileTime &b)
compare file times returns < 0 if a is earlier than b, >0 if b is earlier than a
S32 compareModifiedTimes (const char *firstPath, const char *secondPath)
Compares the last modified time between two file paths.
bool createPath (const char *path)
Given a directory path, create all necessary directories for that path to exist.
StringTableEntry createPlatformFriendlyFilename (const char *filename)
void debugBreak ()
bool deleteDirectory (const char *pPath)
bool displaySplashWindow (String path)
bool doCDCheck ()
bool dumpDirectories (const char *path, Vector< StringTableEntry > &directoryVector, S32 depth=0, bool noBasePath=false)
bool dumpPath (const char *in_pBasePath, Vector< FileInfo > &out_rFileVector, S32 recurseDepth=-1)
bool excludeOtherInstances (const char *string)
bool fileDelete (const char *name)
bool fileTimeToString (FileTime *time, char *string, U32 strLen)
void fileToLocalTime (const FileTime &ft, LocalTime *lt)
void forceShutdown (S32 returnValue)
S32 getBackgroundSleepTime ()
const char * getClipboard ()
StringTableEntry getCurrentDirectory ()
StringTableEntry getExecutableName ()
Returns the filename of the torque executable.
StringTableEntry getExecutablePath ()
Returns full pathname of the torque executable without filename.
S32 getFileSize (const char *pFilePath)
bool getFileTimes (const char *filePath, FileTime *createTime, FileTime *modifyTime)
void getLocalTime (LocalTime &)
const char * getLoginPassword ()
StringTableEntry getMainDotCsDir ()
Returns the full path to the directory that contains main.cs.
U32 getMathControlState ()
StringTableEntry getPrefsPath (const char *file=NULL)
F32 getRandom ()
U32 getRealMilliseconds ()
Returns the milliseconds since the system was started.
StringTableEntry getTemporaryDirectory ()
StringTableEntry getTemporaryFileName ()
U32 getTime ()
StringTableEntry getUserDataDirectory ()
StringTableEntry getUserHomeDirectory ()
bool getUserIsAdministrator ()
U32 getVirtualMilliseconds ()
void getVolumeInformationList (Vector< VolumeInformation > &out_rVolumeInfoVector, bool bOnlyFixedDrives=false)
void getVolumeNamesList (Vector< const char * > &out_rNameVector, bool bOnlyFixedDrives=false)
bool getWebDeployment ()
Set/Get whether this is a web deployment.
bool hasSubDirectory (const char *pPath)
void init ()
void initConsole ()
bool isDirectory (const char *pDirPath)
bool isExcludedDirectory (const char *pDir)
bool isFile (const char *pFilePath)
bool isFullPath (const char *path)
bool isSubDirectory (const char *pParent, const char *pDir)
String localTimeToString (const LocalTime &lt)
Converts the local time to a formatted string appropriate for the current platform.
char * makeFullPathName (const char *path, char *buffer, U32 size, const char *cwd=NULL)
StringTableEntry makeRelativePathName (const char *path, const char *to)
S32 messageBox (const UTF8 *title, const UTF8 *message, MBButtons buttons=MBOkCancel, MBIcons icon=MIInformation)
void minimizeWindow ()
void openFile (const char *path)
void openFolder (const char *path)
bool openWebBrowser (const char *webAddress)
void outputDebugString (const char *string,...)
void postQuitMessage (const S32 in_quitVal)
void process ()
void restartInstance ()
bool setClipboard (const char *text)
bool setCurrentDirectory (StringTableEntry newDir)
bool setLoginPassword (const char *password)
void setMainDotCsDir (const char *dir)
Set main.cs directory. Used in runEntryScript()
void setMathControlState (U32 state)
void setMathControlStateKnown ()
void setWebDeployment (bool v)
void setWindowLocked (bool locked)
void setWindowSize (U32 newWidth, U32 newHeight, bool fullScreen)
void shutdown ()
void sleep (U32 ms)
bool stringToFileTime (const char *string, FileTime *time)
StringTableEntry stripBasePath (const char *path)
String stripExtension (String fileName, Vector< String > &validExtensions)
Variables
struct VolumeInformation * PVolumeInformation
SystemInfo_struct SystemInfo
Signal< void(void)> SystemInfoReady
Enumeration Type Documentation
enum Platform::ALERT_ASSERT_RESULT
Enumerator
ALERT_ASSERT_DEBUG
ALERT_ASSERT_IGNORE
ALERT_ASSERT_IGNORE_ALL
ALERT_ASSERT_EXIT
Function Documentation
void Platform::addExcludedDirectory (const char * pDir)
void Platform::addKeyboardInputExclusion (const KeyboardInputExclusion & kie)
Add a new keyboard exclusion.
void Platform::advanceTime (U32 delta)
ALERT_ASSERT_RESULT Platform::AlertAssert (const char * windowTitle, const char * message)
void Platform::AlertOK (const char * windowTitle, const char * message)
bool Platform::AlertOKCancel (const char * windowTitle, const char * message)
bool Platform::AlertRetry (const char * windowTitle, const char * message)
bool Platform::cdFileExists (const char * filePath, const char * volumeName, S32 serialNum)
const bool Platform::checkKeyboardInputExclusion (const InputEventInfo * info)
Check if a given input event should be excluded.
bool Platform::checkOtherInstances (const char * string)
void Platform::clearExcludedDirectories ()
void Platform::clearKeyboardInputExclusion ()
Reset the keyboard input exclusion list.
bool Platform::closeSplashWindow ()
void Platform::closeWindow ()
S32 Platform::compareFileTimes (const FileTime & a, const FileTime & b)
compare file times returns < 0 if a is earlier than b, >0 if b is earlier than a
S32 Platform::compareModifiedTimes (const char * firstPath, const char * secondPath)
Compares the last modified time between two file paths.
Returns < 0 if the first file is earlier than the second, > 0 if the second file is earlier than the first, and 0 if the files are equal.
If either of the files doesn't exist it returns -1.
bool Platform::createPath (const char * path)
Given a directory path, create all necessary directories for that path to exist.
StringTableEntry Platform::createPlatformFriendlyFilename (const char * filename)
void Platform::debugBreak ()
bool Platform::deleteDirectory (const char * pPath)
bool Platform::displaySplashWindow (String path)
bool Platform::doCDCheck ()
bool Platform::dumpDirectories (const char * path, Vector< StringTableEntry > & directoryVector, S32 depth = 0, bool noBasePath = false)
bool Platform::dumpPath (const char * in_pBasePath, Vector< FileInfo > & out_rFileVector, S32 recurseDepth = -1)
bool Platform::excludeOtherInstances (const char * string)
bool Platform::fileDelete (const char * name)
bool Platform::fileTimeToString (FileTime * time, char * string, U32 strLen)
void Platform::fileToLocalTime (const FileTime & ft, LocalTime * lt)
void Platform::forceShutdown (S32 returnValue)
S32 Platform::getBackgroundSleepTime ()
const char* Platform::getClipboard ()
StringTableEntry Platform::getCurrentDirectory ()
StringTableEntry Platform::getExecutableName ()
Returns the filename of the torque executable.
On Win32, this is the .exe file. On Mac, this is the .app/ directory bundle.
StringTableEntry Platform::getExecutablePath ()
Returns full pathname of the torque executable without filename.
S32 Platform::getFileSize (const char * pFilePath)
bool Platform::getFileTimes (const char * filePath, FileTime * createTime, FileTime * modifyTime)
void Platform::getLocalTime (LocalTime &)
const char* Platform::getLoginPassword ()
StringTableEntry Platform::getMainDotCsDir ()
Returns the full path to the directory that contains main.cs.
Tools scripts are validated as such if they are in this directory or a subdirectory of this directory.
Referenced by Zip::makeTestPath().
U32 Platform::getMathControlState ()
StringTableEntry Platform::getPrefsPath (const char * file = NULL)
F32 Platform::getRandom ()
Referenced by ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::randomLevel().
U32 Platform::getRealMilliseconds ()
Returns the milliseconds since the system was started.
You should not depend on this for high precision timing.
See also
PlatformTimer
Referenced by DefaultPlatformTimer::DefaultPlatformTimer(), DefaultPlatformTimer::getElapsedMs(), RealMSTimer::getTick(), and ThreadSafePriorityQueueWithUpdate< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::getTick().
StringTableEntry Platform::getTemporaryDirectory ()
StringTableEntry Platform::getTemporaryFileName ()
U32 Platform::getTime ()
StringTableEntry Platform::getUserDataDirectory ()
StringTableEntry Platform::getUserHomeDirectory ()
bool Platform::getUserIsAdministrator ()
U32 Platform::getVirtualMilliseconds ()
Referenced by VirtualMSTimer::getTick().
void Platform::getVolumeInformationList (Vector< VolumeInformation > & out_rVolumeInfoVector, bool bOnlyFixedDrives = false)
void Platform::getVolumeNamesList (Vector< const char * > & out_rNameVector, bool bOnlyFixedDrives = false)
bool Platform::getWebDeployment ()
Set/Get whether this is a web deployment.
bool Platform::hasSubDirectory (const char * pPath)
void Platform::init ()
void Platform::initConsole ()
bool Platform::isDirectory (const char * pDirPath)
bool Platform::isExcludedDirectory (const char * pDir)
bool Platform::isFile (const char * pFilePath)
Referenced by ModuleManager::isModuleMergeAvailable().
bool Platform::isFullPath (const char * path)
bool Platform::isSubDirectory (const char * pParent, const char * pDir)
String Platform::localTimeToString (const LocalTime & lt)
Converts the local time to a formatted string appropriate for the current platform.
char* Platform::makeFullPathName (const char * path, char * buffer, U32 size, const char * cwd = NULL)
Referenced by Zip::makeTestPath().
StringTableEntry Platform::makeRelativePathName (const char * path, const char * to)
S32 Platform::messageBox (const UTF8 * title, const UTF8 * message, MBButtons buttons = MBOkCancel, MBIcons icon = MIInformation)
void Platform::minimizeWindow ()
void Platform::openFile (const char * path)
void Platform::openFolder (const char * path)
bool Platform::openWebBrowser (const char * webAddress)
void Platform::outputDebugString (const char * string, ...)
Referenced by SFXWorld< NUM_DIMENSIONS, Object >::_onScopeIn(), SFXWorld< NUM_DIMENSIONS, Object >::_onScopeOut(), AsyncPacketBufferedInputStream< Stream, Packet >::_requestNext(), AsyncPacketBufferedInputStream< Stream, Packet >::AsyncPacketBufferedInputStream(), ThreadSafeFreeList< ThreadSafeDeque::Node >::dumpDebug(), ThreadSafeDeque< GBitmap * >::dumpDebug(), AsyncPacketBufferedInputStream< Stream, Packet >::PacketReadItem::execute(), AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::needPacket(), ScopeTracker< NUM_DIMENSIONS, Object >::setReferenceObject(), AsyncPacketQueue< Packet, TimeSource, Consumer, Tick >::submitPacket(), and ThreadSafePriorityQueueWithUpdate< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::updatePriorities().
void Platform::postQuitMessage (const S32 in_quitVal)
void Platform::process ()
void Platform::restartInstance ()
bool Platform::setClipboard (const char * text)
bool Platform::setCurrentDirectory (StringTableEntry newDir)
bool Platform::setLoginPassword (const char * password)
void Platform::setMainDotCsDir (const char * dir)
Set main.cs directory. Used in runEntryScript()
void Platform::setMathControlState (U32 state)
void Platform::setMathControlStateKnown ()
void Platform::setWebDeployment (bool v)
void Platform::setWindowLocked (bool locked)
void Platform::setWindowSize (U32 newWidth, U32 newHeight, bool fullScreen)
void Platform::shutdown ()
void Platform::sleep (U32 ms)
bool Platform::stringToFileTime (const char * string, FileTime * time)
StringTableEntry Platform::stripBasePath (const char * path)
String Platform::stripExtension (String fileName, Vector< String > & validExtensions)
Variable Documentation
struct VolumeInformation* Platform::PVolumeInformation
SystemInfo_struct Platform::SystemInfo
Signal<void(void)> Platform::SystemInfoReady
Copyright © GarageGames, LLC. All Rights Reserved.