PersistInfo::PersistChunk Struct Reference
Main Modules Class List Namespace List Online
PersistInfo::PersistChunk Struct Reference
#include <lighting/common/scenePersist.h>
Public Types
enum {
MissionChunkType = 0,
InteriorChunkType,
TerrainChunkType,
AtlasLightMapChunkType
}
Public Member Functions
virtual ~PersistChunk ()
virtual bool read (Stream &)
virtual bool write (Stream &)
Public Attributes
U32 mChunkCRC
U32 mChunkType
Member Enumeration Documentation
anonymous enum
Enumerator
MissionChunkType
InteriorChunkType
TerrainChunkType
AtlasLightMapChunkType
Constructor & Destructor Documentation
virtual PersistInfo::PersistChunk::~PersistChunk () inline virtual
References read(), and write().
Member Function Documentation
virtual bool PersistInfo::PersistChunk::read (Stream &) virtual
Referenced by ~PersistChunk().
virtual bool PersistInfo::PersistChunk::write (Stream &) virtual
Referenced by ~PersistChunk().
Member Data Documentation
U32 PersistInfo::PersistChunk::mChunkCRC
U32 PersistInfo::PersistChunk::mChunkType
Copyright © GarageGames, LLC. All Rights Reserved.