DDSFile Struct Reference
Main Modules Class List Namespace List Online
DDSFile Struct Reference
#include <gfx/bitmap/ddsFile.h>
Classes
struct SurfaceData
Public Types
enum {
Cubemap_Surface_PosX,
Cubemap_Surface_NegX,
Cubemap_Surface_PosY,
Cubemap_Surface_NegY,
Cubemap_Surface_PosZ,
Cubemap_Surface_NegZ,
Cubemap_Surface_Count
}
The index into mSurfaces for each cubemap face.
enum DDSFlags {
ComplexFlag = BIT(0),
MipMapsFlag = BIT(1),
CubeMapFlag = BIT(2),
VolumeFlag = BIT(3),
PitchSizeFlag = BIT(4),
LinearSizeFlag = BIT(5),
RGBData = BIT(6),
CompressedData = BIT(7),
CubeMap_PosX_Flag = BIT(8),
CubeMap_NegX_Flag = BIT(9),
CubeMap_PosY_Flag = BIT(10),
CubeMap_NegY_Flag = BIT(11),
CubeMap_PosZ_Flag = BIT(12),
CubeMap_NegZ_Flag = BIT(13)
}
Public Member Functions
DDSFile ()
DDSFile (const DDSFile &dds)
~DDSFile ()
void clear ()
Clear all our information; used before reading.
U32 getDepth (U32 mipLevel=0) const
GFXFormat getFormat () const
bool getHasTransparency () const
U32 getHeight (U32 mipLevel=0) const
U32 getMipLevels () const
U32 getSizeInBytes () const
Returns the total video memory size of the texture including all mipmaps and compression settings.
const Torque::Path & getSourcePath () const
U32 getSurfacePitch (U32 mipLevel=0) const
U32 getSurfaceSize (U32 mipLevel=0) const
For our current format etc., what is the size of a surface with the given dimensions?
U32 getSurfaceSize (U32 height, U32 width, U32 mipLevel=0) const
const String & getTextureCacheString () const
U32 getWidth (U32 mipLevel=0) const
bool isCubemap () const
bool read (Stream &s, U32 dropMipCount)
Reads a DDS file from the stream.
bool readHeader (Stream &s)
Called from read() to read in the DDS header.
bool write (Stream &s)
Writes this DDS file to the stream.
bool writeHeader (Stream &s)
Called from write() to write the DDS header.
Static Public Member Functions
static DDSFile * createDDSFileFromGBitmap (const GBitmap *gbmp)
static U32 getSizeInBytes (GFXFormat format, U32 height, U32 width, U32 mipLevels)
static Resource< DDSFile > load (const Torque::Path &path, U32 dropMipCount)
Public Attributes
U32 mBytesPerPixel
Ignored if we're a compressed texture.
String mCacheString
U32 mDepth
BitSet32 mFlags
GFXFormat mFormat
U32 mFourCC
bool mHasTransparency
U32 mHeight
U32 mMipMapCount
U32 mPitchOrLinearSize
Torque::Path mSourcePath
Vector< SurfaceData * > mSurfaces
U32 mWidth
Static Public Attributes
static S32 smActiveCopies
static U32 smDropMipCount
Member Enumeration Documentation
anonymous enum
The index into mSurfaces for each cubemap face.
Enumerator
Cubemap_Surface_PosX
Cubemap_Surface_NegX
Cubemap_Surface_PosY
Cubemap_Surface_NegY
Cubemap_Surface_PosZ
Cubemap_Surface_NegZ
Cubemap_Surface_Count
enum DDSFile::DDSFlags
Enumerator
ComplexFlag
Indicates this includes a mipchain, cubemap, or volume texture, ie, isn't a plain old bitmap.
MipMapsFlag
Indicates we have a mipmap chain in the file.
CubeMapFlag
Indicates we are a cubemap. Requires all six faces.
VolumeFlag
Indicates we are a volume texture.
PitchSizeFlag
Cue as to how to interpret our pitchlinear value.
LinearSizeFlag
Cue as to how to interpret our pitchlinear value.
RGBData
Indicates that this is straight out RGBA data.
CompressedData
Indicates that this is compressed or otherwise exotic data.
CubeMap_PosX_Flag
These are the flags for which cubemap surfaces are included in the file.
CubeMap_NegX_Flag
CubeMap_PosY_Flag
CubeMap_NegY_Flag
CubeMap_PosZ_Flag
CubeMap_NegZ_Flag
Constructor & Destructor Documentation
DDSFile::DDSFile () inline
DDSFile::DDSFile (const DDSFile & dds)
DDSFile::~DDSFile () inline
References Vector< T >::clear(), createDDSFileFromGBitmap(), and Vector< T >::size().
Member Function Documentation
void DDSFile::clear ()
Clear all our information; used before reading.
static DDSFile* DDSFile::createDDSFileFromGBitmap (const GBitmap * gbmp) static
Referenced by ~DDSFile().
U32 DDSFile::getDepth (U32 mipLevel = 0) const inline
GFXFormat DDSFile::getFormat () const inline
References getSurfacePitch(), and mFormat.
bool DDSFile::getHasTransparency () const inline
References mHasTransparency.
U32 DDSFile::getHeight (U32 mipLevel = 0) const inline
U32 DDSFile::getMipLevels () const inline
References mMipMapCount.
static U32 DDSFile::getSizeInBytes (GFXFormat format, U32 height, U32 width, U32 mipLevels) static
U32 DDSFile::getSizeInBytes () const
Returns the total video memory size of the texture including all mipmaps and compression settings.
Referenced by getSurfaceSize().
const Torque::Path& DDSFile::getSourcePath () const inline
References mSourcePath.
U32 DDSFile::getSurfacePitch (U32 mipLevel = 0) const
Referenced by getFormat().
U32 DDSFile::getSurfaceSize (U32 mipLevel = 0) const inline
For our current format etc., what is the size of a surface with the given dimensions?
References getSizeInBytes(), and getSurfaceSize().
Referenced by getSurfaceSize().
U32 DDSFile::getSurfaceSize (U32 height, U32 width, U32 mipLevel = 0) const
const String& DDSFile::getTextureCacheString () const inline
References load(), and mCacheString.
U32 DDSFile::getWidth (U32 mipLevel = 0) const inline
bool DDSFile::isCubemap () const inline
References CubeMapFlag, and BitSet32::test().
static Resource<DDSFile> DDSFile::load (const Torque::Path & path, U32 dropMipCount) static
Referenced by getTextureCacheString().
bool DDSFile::read (Stream & s, U32 dropMipCount)
Reads a DDS file from the stream.
bool DDSFile::readHeader (Stream & s)
Called from read() to read in the DDS header.
bool DDSFile::write (Stream & s)
Writes this DDS file to the stream.
bool DDSFile::writeHeader (Stream & s)
Called from write() to write the DDS header.
Member Data Documentation
U32 DDSFile::mBytesPerPixel
Ignored if we're a compressed texture.
String DDSFile::mCacheString
Referenced by getTextureCacheString().
U32 DDSFile::mDepth
BitSet32 DDSFile::mFlags
GFXFormat DDSFile::mFormat
Referenced by getFormat().
U32 DDSFile::mFourCC
bool DDSFile::mHasTransparency
Referenced by getHasTransparency().
U32 DDSFile::mHeight
U32 DDSFile::mMipMapCount
Referenced by getMipLevels().
U32 DDSFile::mPitchOrLinearSize
Torque::Path DDSFile::mSourcePath
Referenced by getSourcePath().
Vector<SurfaceData*> DDSFile::mSurfaces
U32 DDSFile::mWidth
S32 DDSFile::smActiveCopies static
U32 DDSFile::smDropMipCount static
Copyright © GarageGames, LLC. All Rights Reserved.