_EngineConsoleExecCallbackHelper< P1 > Struct Template Reference
Main Modules Class List Namespace List Online
_EngineConsoleExecCallbackHelper< P1 > Struct Template Reference
Console System
#include <console/engineAPI.h>
Public Member Functions
_EngineConsoleExecCallbackHelper (SimObject *pThis)
template<typename R , typename SCB , typename... ArgTs>
R call (SCB simCB, ArgTs...args)
Public Member Functions inherited from _BaseEngineConsoleCallbackHelper
_BaseEngineConsoleCallbackHelper ()
ConsoleValueRef _exec ()
ConsoleValueRef _execLater (SimConsoleThreadExecEvent *evt)
Additional Inherited Members
Public Attributes inherited from _BaseEngineConsoleCallbackHelper
S32 mArgc
ConsoleValueRef mArgv [MAX_ARGUMENTS+2]
StringTableEntry mCallbackName
S32 mInitialArgc
SimObject * mThis
Static Public Attributes inherited from _BaseEngineConsoleCallbackHelper
static const U32 MAX_ARGUMENTS = 11
Matches up to storeArgs.
Constructor & Destructor Documentation
template<typename P1> _EngineConsoleExecCallbackHelper< P1 >::_EngineConsoleExecCallbackHelper (SimObject * pThis) inline
Member Function Documentation
template<typename P1> template<typename R , typename SCB , typename... ArgTs> R _EngineConsoleExecCallbackHelper< P1 >::call (SCB simCB, ArgTs... args) inline
References Sim::getCurrentTime(), Con::isMainThread(), SimConsoleEvent::populateArgs(), Sim::postEvent(), ConsoleValueStack::reserveValues(), ConsoleStackFrameSaver::save(), ConsoleValue::setStackStringValue(), and SimConsoleThreadExecCallback::waitForResult().
Copyright © GarageGames, LLC. All Rights Reserved.