ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node Struct Reference
Main Modules Class List Namespace List Online
ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node Struct Reference
A queue node.
#include <platform/threads/threadSafePriorityQueue.h>
Public Types
typedef ThreadSafeRefCount< Node > Parent
Public Types inherited from ThreadSafeRefCount< Node >
typedef void Parent
Public Member Functions
Node (KeyType priority, const ValueType &value)
~Node ()
void clearValue ()
U32 getLevel ()
Return the skip list level the node is at.
NodePtr & getNext (U32 level)
Return the successor node at the given level.
KeyType getPriority ()
ValueType & getValue ()
bool isMarkedForDeletion ()
Return true if the node is marked to be deleted.
void operator delete (void *ptr)
Reclaim a node.
void * operator new (size_t size, S32 level=-1)
Allocate a new node.
bool tryMarkForDeletion ()
Attempt to mark the node for deletion.
Public Member Functions inherited from ThreadSafeRefCount< Node >
ThreadSafeRefCount ()
ThreadSafeRefCount (bool noSet)
void addRef ()
Increase the reference count on the object.
void clearLowestBit ()
U32 getRefCount () const
Get the current reference count.
bool isShared () const
void release ()
Decrease the object's reference count and delete the object, if the count drops to zero and claiming the object by the current thread succeeds.
Static Public Member Functions
static U32 randomLevel ()
Choose a random level.
Static Public Member Functions inherited from ThreadSafeRefCount< Node >
static Node * safeRead (Node *const volatile &refPtr)
Dereference a reference-counted pointer in a multi-thread safe way.
Additional Inherited Members
Static Protected Member Functions inherited from ThreadSafeRefCount< Node >
static U32 decrementAndTestAndSet (U32 &refCount)
Decrement the given reference count.
Protected Attributes inherited from ThreadSafeRefCount< Node >
U32 mRefCount
Reference count and claim bit. Note that this increments in steps of two.
Detailed Description
template<typename T, typename K = F32, bool SORT_MIN_TO_MAX = false, U32 MAX_LEVEL = 4, U32 PROBABILISTIC_BIAS = 50>
struct ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node
A queue node.
Nodes are reference-counted to coordinate memory management between the different threads. Reclamation happens on the thread that releases the last reference.
Reference-counting and deletion requests are kept separate. A given node is marked for deletion and will then have its references progressively disappear and eventually be reclaimed once the reference count drops to zero.
Note that 'Next' references are released by the destructor which is only called when the reference count to the node itself drops to zero. This is to avoid threads getting trapped in a node with no link out.
Member Typedef Documentation
template<typename T, typename K = F32, bool SORT_MIN_TO_MAX = false, U32 MAX_LEVEL = 4, U32 PROBABILISTIC_BIAS = 50> typedef ThreadSafeRefCount< Node > ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::Parent
Constructor & Destructor Documentation
template<typename T , typename K , bool SORT_MIN_TO_MAX, U32 MAX_LEVEL, U32 PROBABILISTIC_BIAS> ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::Node (KeyType priority, const ValueType & value) inline
References dMemset(), and ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::getLevel().
Referenced by ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::insert(), and ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::ThreadSafePriorityQueue().
template<typename T , typename K , bool SORT_MIN_TO_MAX, U32 MAX_LEVEL, U32 PROBABILISTIC_BIAS> ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::~Node ()
References ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::getLevel(), and ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::getNext().
Member Function Documentation
template<typename T, typename K = F32, bool SORT_MIN_TO_MAX = false, U32 MAX_LEVEL = 4, U32 PROBABILISTIC_BIAS = 50> void ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::clearValue () inline
References ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::randomLevel().
template<typename T , typename K , bool SORT_MIN_TO_MAX, U32 MAX_LEVEL, U32 PROBABILISTIC_BIAS> U32 ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::getLevel () inline
Return the skip list level the node is at.
Referenced by ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::getValue(), ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::Node(), ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::operator delete(), and ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::~Node().
template<typename T , typename K , bool SORT_MIN_TO_MAX, U32 MAX_LEVEL, U32 PROBABILISTIC_BIAS> ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::NodePtr & ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::getNext (U32 level) inline
Return the successor node at the given level.
Parameters
level The level of the desired successor node; must be within the node's level bounds.
Referenced by ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::getValue(), and ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::~Node().
template<typename T, typename K = F32, bool SORT_MIN_TO_MAX = false, U32 MAX_LEVEL = 4, U32 PROBABILISTIC_BIAS = 50> KeyType ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::getPriority () inline
Referenced by ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::takeNext(), and ThreadSafePriorityQueueWithUpdate< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::updatePriorities().
template<typename T, typename K = F32, bool SORT_MIN_TO_MAX = false, U32 MAX_LEVEL = 4, U32 PROBABILISTIC_BIAS = 50> ValueType& ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::getValue () inline
References ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::getLevel(), ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::getNext(), ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::isMarkedForDeletion(), and ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::tryMarkForDeletion().
Referenced by ThreadSafePriorityQueueWithUpdate< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::updatePriorities().
template<typename T , typename K , bool SORT_MIN_TO_MAX, U32 MAX_LEVEL, U32 PROBABILISTIC_BIAS> bool ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::isMarkedForDeletion () inline
Return true if the node is marked to be deleted.
Referenced by ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::getValue(), and ThreadSafePriorityQueueWithUpdate< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::updatePriorities().
template<typename T , typename K , bool SORT_MIN_TO_MAX, U32 MAX_LEVEL, U32 PROBABILISTIC_BIAS> void ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::operator delete (void * ptr)
Reclaim a node.
Parameters
node The node to reclaim. Must refer to a Node instance.
References dFree(), and ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::getLevel().
template<typename T , typename K , bool SORT_MIN_TO_MAX, U32 MAX_LEVEL, U32 PROBABILISTIC_BIAS> void * ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::operator new (size_t size, S32 level = -1)
Allocate a new node.
The node comes with a reference count of one and its level already set.
Parameters
level The level to allocate the node at. If this is -1, a random level is chosen.
Returns
a new node.
References ThreadSafeRefCount< T, DeletePolicy >::addRef(), ThreadSafeRefCount< T, DeletePolicy >::clearLowestBit(), dMalloc, dMemset(), ThreadSafeRefCount< T, DeletePolicy >::getRefCount(), ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::randomLevel(), ThreadSafeRefCount< T, DeletePolicy >::release(), and ThreadSafeRefCount< Node >::safeRead().
template<typename T , typename K , bool SORT_MIN_TO_MAX, U32 MAX_LEVEL, U32 PROBABILISTIC_BIAS> U32 ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::randomLevel () static
Choose a random level.
The chosen level depends on the given PROBABILISTIC_BIAS and MAX_LEVEL, but is not affected by the actual number of nodes in a queue.
References Platform::getRandom().
Referenced by ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::clearValue(), and ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::operator new().
template<typename T , typename K , bool SORT_MIN_TO_MAX, U32 MAX_LEVEL, U32 PROBABILISTIC_BIAS> bool ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::tryMarkForDeletion () inline
Attempt to mark the node for deletion.
If the mark bit has not yet been set and setting it on the current thread succeeds, returns true.
Returns
true, if the marking succeeded.
Referenced by ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::getValue(), and ThreadSafePriorityQueueWithUpdate< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::updatePriorities().
Copyright © GarageGames, LLC. All Rights Reserved.