_EngineConsoleExecCallbackHelper< const char * > Struct Template Reference
Main Modules Class List Namespace List Online
_EngineConsoleExecCallbackHelper< const char * > Struct Template Reference
#include <console/engineAPI.h>
Public Member Functions
_EngineConsoleExecCallbackHelper (const char *callbackName)
template<typename R , typename... ArgTs>
R call (ArgTs...args)
Public Member Functions inherited from _BaseEngineConsoleCallbackHelper
_BaseEngineConsoleCallbackHelper ()
ConsoleValueRef _exec ()
ConsoleValueRef _execLater (SimConsoleThreadExecEvent *evt)
Additional Inherited Members
Public Attributes inherited from _BaseEngineConsoleCallbackHelper
S32 mArgc
ConsoleValueRef mArgv [MAX_ARGUMENTS+2]
StringTableEntry mCallbackName
S32 mInitialArgc
SimObject * mThis
Static Public Attributes inherited from _BaseEngineConsoleCallbackHelper
static const U32 MAX_ARGUMENTS = 11
Matches up to storeArgs.
Constructor & Destructor Documentation
_EngineConsoleExecCallbackHelper< const char * >::_EngineConsoleExecCallbackHelper (const char * callbackName) inline
References _BaseEngineConsoleCallbackHelper::mArgc, _BaseEngineConsoleCallbackHelper::mCallbackName, _BaseEngineConsoleCallbackHelper::mInitialArgc, and _BaseEngineConsoleCallbackHelper::mThis.
Member Function Documentation
template<typename R , typename... ArgTs> R _EngineConsoleExecCallbackHelper< const char * >::call (ArgTs... args) inline
References _BaseEngineConsoleCallbackHelper::_exec(), Sim::getCurrentTime(), Sim::getRootGroup(), Con::isMainThread(), _BaseEngineConsoleCallbackHelper::mArgc, _BaseEngineConsoleCallbackHelper::mArgv, engineAPI::detail::MarshallHelpers< ConsoleValueRef >::marshallEach(), _BaseEngineConsoleCallbackHelper::mCallbackName, SimConsoleEvent::populateArgs(), Sim::postEvent(), ConsoleValueStack::reserveValues(), ConsoleStackFrameSaver::save(), ConsoleValue::setStackStringValue(), ConsoleValueRef::value, and SimConsoleThreadExecCallback::waitForResult().
Copyright © GarageGames, LLC. All Rights Reserved.