FModFNTable::Thunk< FN > Struct Template Reference
Main Modules Class List Namespace List Online
FModFNTable::Thunk< FN > Struct Template Reference
#include <sfx/fmod/sfxFMODDevice.h>
Public Member Functions
template<typename A >
FMOD_RESULT operator() (A a)
template<typename A , typename B >
FMOD_RESULT operator() (A a, B b)
template<typename A , typename B , typename C >
FMOD_RESULT operator() (A a, B b, C c)
template<typename A , typename B , typename C , typename D >
FMOD_RESULT operator() (A a, B b, C c, D d)
template<typename A , typename B , typename C , typename D , typename E >
FMOD_RESULT operator() (A a, B b, C c, D d, E e)
template<typename A , typename B , typename C , typename D , typename E , typename F >
FMOD_RESULT operator() (A a, B b, C c, D d, E e, F f)
template<typename A , typename B , typename C , typename D , typename E , typename F , typename G >
FMOD_RESULT operator() (A a, B b, C c, D d, E e, F f, G g)
template<typename A , typename B , typename C , typename D , typename E , typename F , typename G , typename H >
FMOD_RESULT operator() (A a, B b, C c, D d, E e, F f, G g, H h)
Public Attributes
FN fn
Member Function Documentation
template<typename FN > template<typename A > FMOD_RESULT FModFNTable::Thunk< FN >::operator() (A a) inline
References FModFNTable::Thunk< FN >::fn, Mutex::lock(), and Mutex::unlock().
template<typename FN > template<typename A , typename B > FMOD_RESULT FModFNTable::Thunk< FN >::operator() (A a, B b) inline
References FModFNTable::Thunk< FN >::fn, Mutex::lock(), and Mutex::unlock().
template<typename FN > template<typename A , typename B , typename C > FMOD_RESULT FModFNTable::Thunk< FN >::operator() (A a, B b, C c) inline
References FModFNTable::Thunk< FN >::fn, Mutex::lock(), and Mutex::unlock().
template<typename FN > template<typename A , typename B , typename C , typename D > FMOD_RESULT FModFNTable::Thunk< FN >::operator() (A a, B b, C c, D d) inline
References FModFNTable::Thunk< FN >::fn, Mutex::lock(), and Mutex::unlock().
template<typename FN > template<typename A , typename B , typename C , typename D , typename E > FMOD_RESULT FModFNTable::Thunk< FN >::operator() (A a, B b, C c, D d, E e) inline
References FModFNTable::Thunk< FN >::fn, Mutex::lock(), and Mutex::unlock().
template<typename FN > template<typename A , typename B , typename C , typename D , typename E , typename F > FMOD_RESULT FModFNTable::Thunk< FN >::operator() (A a, B b, C c, D d, E e, F f) inline
References FModFNTable::Thunk< FN >::fn, Mutex::lock(), and Mutex::unlock().
template<typename FN > template<typename A , typename B , typename C , typename D , typename E , typename F , typename G > FMOD_RESULT FModFNTable::Thunk< FN >::operator() (A a, B b, C c, D d, E e, F f, G g) inline
References FModFNTable::Thunk< FN >::fn, Mutex::lock(), and Mutex::unlock().
template<typename FN > template<typename A , typename B , typename C , typename D , typename E , typename F , typename G , typename H > FMOD_RESULT FModFNTable::Thunk< FN >::operator() (A a, B b, C c, D d, E e, F f, G g, H h) inline
References String::c_str(), FModFNTable::Thunk< FN >::fn, MatrixF::getColumn(), Mutex::lock(), String::replace(), String::ToString(), Mutex::unlock(), Point3F::x, Point3F::y, and Point3F::z.
Member Data Documentation
template<typename FN > FN FModFNTable::Thunk< FN >::fn
Referenced by FModFNTable::Thunk< FN >::operator()().
Copyright © GarageGames, LLC. All Rights Reserved.