SFXNullVoice Class Reference
Main Modules Class List Namespace List Online
SFXNullVoice Class Reference
#include <sfx/null/sfxNullVoice.h>
Public Types
typedef SFXVoice Parent
Public Types inherited from SFXVoice
typedef void Parent
Public Types inherited from IPositionable< U32 >
typedef void Parent
typedef U32 PositionType
The type used to indicate positions.
Public Member Functions
virtual ~SFXNullVoice ()
SFXStatus getStatus () const
SFXVoice.
void play (bool looping)
Starts playback from the current position.
void setCone (F32 innerAngle, F32 outerAngle, F32 outerVolume)
Set sound cone of a 3D sound.
void setMinMaxDistance (F32 min, F32 max)
Sets the minimum and maximum distances for 3d falloff.
void setPitch (F32 pitch)
Sets the pitch scale.
void setPosition (U32 sample)
Sets the playback position to the given sample count.
void setTransform (const MatrixF &transform)
Sets the position and orientation for a 3d voice.
void setVelocity (const VectorF &velocity)
Sets the velocity for a 3d voice.
void setVolume (F32 volume)
Sets the volume.
Public Member Functions inherited from SFXVoice
virtual ~SFXVoice ()
The destructor.
const SFXFormat & getFormat () const
virtual U32 getPosition () const
Return the current playback position (in number of samples).
virtual bool isVirtual () const
Returns true if the voice is virtualized on the device.
virtual void pause ()
Pauses playback.
virtual void setPriority (F32 priority)
Set the priority of this voice.
virtual void setReverb (const SFXSoundReverbProperties &reverb)
Set the reverb properties for playback of this sound.
virtual void setRolloffFactor (F32 factor)
Set the distance attenuation rolloff factor. Support by device optional.
virtual void stop ()
Stops playback and moves the position to the start.
Public Member Functions inherited from StrongRefBase
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Protected Types
typedef GenericTimeSource< VirtualMSTimer > TimeSource
Protected Member Functions
SFXNullVoice (SFXNullBuffer *buffer)
U32 _getPlayTime () const
virtual void _pause ()
Pause playback on the device.
virtual void _play ()
Start playback on the device.
virtual void _seek (U32 sample)
Set the playback cursor on the device.
virtual SFXStatus _status () const
Return the current playback status (playing, paused, or stopped).
virtual void _stop ()
Stop playback on the device.
virtual U32 _tell () const
Get the playback cursor on the device.
Protected Member Functions inherited from SFXVoice
SFXVoice (SFXBuffer *buffer)
void _attachToBuffer ()
virtual void _onBufferStatusChange (SFXBuffer *buffer, SFXBuffer::Status newStatus)
Hooked up to SFXBuffer::mOnStatusChange of mBuffer.
void _resetStream (U32 sampleStartPos, bool triggerUpdate=true)
Reset streaming of the voice by cloning the current streaming source and letting the resulting stream start from sampleStartPos.
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Protected Attributes
bool mIsLooping
TimeSource mPlayTimer
The virtual play timer.
Protected Attributes inherited from SFXVoice
WeakRefPtr< SFXBuffer > mBuffer
Sound data played back by the voice.
U32 mOffset
For streaming voices, this keeps track of play start offset after seeking.
volatile SFXStatus mStatus
Current playback status.
Protected Attributes inherited from StrongRefBase
U32 mRefCount
reference counter for StrongRefPtr objects
Additional Inherited Members
Static Public Attributes inherited from SFXVoice
static Signal< void(SFXVoice *) > smVoiceCreatedSignal
static Signal< void(SFXVoice *) > smVoiceDestroyedSignal
Member Typedef Documentation
typedef SFXVoice SFXNullVoice::Parent
typedef GenericTimeSource< VirtualMSTimer > SFXNullVoice::TimeSource protected
Constructor & Destructor Documentation
SFXNullVoice::SFXNullVoice (SFXNullBuffer * buffer) protected
virtual SFXNullVoice::~SFXNullVoice () virtual
Referenced by _getPlayTime().
Member Function Documentation
U32 SFXNullVoice::_getPlayTime () const inline protected
References GenericTimeSource< Timer, Tick >::getPosition(), getStatus(), play(), setCone(), setMinMaxDistance(), setPitch(), setPosition(), setTransform(), setVelocity(), setVolume(), and ~SFXNullVoice().
virtual void SFXNullVoice::_pause () protected virtual
Pause playback on the device.
Note
Called from both the SFX update thread and the main thread.
Implements SFXVoice.
virtual void SFXNullVoice::_play () protected virtual
Start playback on the device.
Note
Called from both the SFX update thread and the main thread.
Implements SFXVoice.
virtual void SFXNullVoice::_seek (U32 sample) protected virtual
Set the playback cursor on the device.
Note
Only used for non-streaming voices.
Implements SFXVoice.
virtual SFXStatus SFXNullVoice::_status () const protected virtual
Return the current playback status (playing, paused, or stopped).
Default status is stopped.
Implements SFXVoice.
virtual void SFXNullVoice::_stop () protected virtual
Stop playback on the device.
Note
Called from both the SFX update thread and the main thread.
Implements SFXVoice.
virtual U32 SFXNullVoice::_tell () const protected virtual
Get the playback cursor on the device.
When the voice is playing or paused, this method must return a valid sample position. When the voice is stopped, the result of this method is undefined.
For streaming voices that are looping, the sample position must be a total count of the number of samples played so far which thus includes the count of all cycles before the current one. For non-looping voices, this behavior is optional.
Note
This is called for both streaming and non-streaming voices.
Implements SFXVoice.
SFXStatus SFXNullVoice::getStatus () const virtual
SFXVoice.
Reimplemented from SFXVoice.
Referenced by _getPlayTime().
void SFXNullVoice::play (bool looping) virtual
Starts playback from the current position.
Reimplemented from SFXVoice.
Referenced by _getPlayTime().
void SFXNullVoice::setCone (F32 innerAngle, F32 outerAngle, F32 outerVolume) virtual
Set sound cone of a 3D sound.
Parameters
innerAngle Inner cone angle in degrees.
outerAngle Outer cone angle in degrees.
outerVolume Outer volume factor.
Implements SFXVoice.
Referenced by _getPlayTime().
void SFXNullVoice::setMinMaxDistance (F32 min, F32 max) virtual
Sets the minimum and maximum distances for 3d falloff.
Implements SFXVoice.
Referenced by _getPlayTime().
void SFXNullVoice::setPitch (F32 pitch) virtual
Sets the pitch scale.
Implements SFXVoice.
Referenced by _getPlayTime().
void SFXNullVoice::setPosition (U32 sample) virtual
Sets the playback position to the given sample count.
Parameters
sample Offset in number of samples. This is allowed to use an offset accumulated from multiple cycles. Each cycle will wrap around back to the beginning of the buffer.
Reimplemented from SFXVoice.
Referenced by _getPlayTime().
void SFXNullVoice::setTransform (const MatrixF & transform) virtual
Sets the position and orientation for a 3d voice.
Implements SFXVoice.
Referenced by _getPlayTime().
void SFXNullVoice::setVelocity (const VectorF & velocity) virtual
Sets the velocity for a 3d voice.
Implements SFXVoice.
Referenced by _getPlayTime().
void SFXNullVoice::setVolume (F32 volume) virtual
Sets the volume.
Implements SFXVoice.
Referenced by _getPlayTime().
Member Data Documentation
bool SFXNullVoice::mIsLooping protected
TimeSource SFXNullVoice::mPlayTimer mutable protected
The virtual play timer.
Copyright © GarageGames, LLC. All Rights Reserved.