FrameAllocatorLockableHelper Class Reference
Main Modules Class List Namespace List Online
FrameAllocatorLockableHelper Class Reference
Helper class for simulate lock/unlock on gfx buffers using FrameAllocator.
#include <gfx/gl/util/glFrameAllocatorLockableHelper.h>
Public Member Functions
FrameAllocatorLockableHelper ()
U8 * getlockedPtr () const
U8 * lock (const U32 size)
void unlock ()
Protected Attributes
U32 mFrameAllocatorMark
U32 mFrameAllocatorMarkGuard
U8 * mFrameAllocatorPtr
Detailed Description
Helper class for simulate lock/unlock on gfx buffers using FrameAllocator.
Constructor & Destructor Documentation
FrameAllocatorLockableHelper::FrameAllocatorLockableHelper () inline
Member Function Documentation
U8* FrameAllocatorLockableHelper::getlockedPtr () const inline
References mFrameAllocatorPtr.
U8* FrameAllocatorLockableHelper::lock (const U32 size) inline
References FrameAllocator::alloc(), FrameAllocator::getWaterMark(), mFrameAllocatorMark, mFrameAllocatorMarkGuard, and mFrameAllocatorPtr.
void FrameAllocatorLockableHelper::unlock () inline
References FrameAllocator::getWaterMark(), mFrameAllocatorMark, mFrameAllocatorMarkGuard, mFrameAllocatorPtr, and FrameAllocator::setWaterMark().
Member Data Documentation
U32 FrameAllocatorLockableHelper::mFrameAllocatorMark protected
Referenced by lock(), and unlock().
U32 FrameAllocatorLockableHelper::mFrameAllocatorMarkGuard protected
Referenced by lock(), and unlock().
U8* FrameAllocatorLockableHelper::mFrameAllocatorPtr protected
Referenced by getlockedPtr(), lock(), and unlock().
Copyright © GarageGames, LLC. All Rights Reserved.