TamlAssetDeclaredVisitor Class Reference
Main Modules Class List Namespace List Online
TamlAssetDeclaredVisitor Class Reference
#include <assets/tamlAssetDeclaredVisitor.h>
Public Types
typedef StringTableEntry typeAssetId
typedef Vector< typeAssetId > typeAssetIdVector
typedef Vector< StringTableEntry > typeLooseFileVector
Public Member Functions
TamlAssetDeclaredVisitor ()
virtual ~TamlAssetDeclaredVisitor ()
void clear (void)
AssetDefinition & getAssetDefinition (void)
typeAssetIdVector & getAssetDependencies (void)
typeLooseFileVector & getAssetLooseFiles (void)
virtual bool visit (const TamlParser &parser, TamlVisitor::PropertyState &propertyState)
The state of the visited property.
virtual bool wantsPropertyChanges (void)
Whether the visitor wants to perform property changes.
virtual bool wantsRootOnly (void)
Whether the visitor wants to visit the root node only.
Public Member Functions inherited from TamlVisitor
TamlVisitor ()
virtual ~TamlVisitor ()
Member Typedef Documentation
typedef StringTableEntry TamlAssetDeclaredVisitor::typeAssetId
typedef Vector<typeAssetId> TamlAssetDeclaredVisitor::typeAssetIdVector
typedef Vector<StringTableEntry> TamlAssetDeclaredVisitor::typeLooseFileVector
Constructor & Destructor Documentation
TamlAssetDeclaredVisitor::TamlAssetDeclaredVisitor () inline
References AssetDefinition::reset().
virtual TamlAssetDeclaredVisitor::~TamlAssetDeclaredVisitor () inline virtual
Member Function Documentation
void TamlAssetDeclaredVisitor::clear (void) inline
References Vector< T >::clear(), and AssetDefinition::reset().
AssetDefinition& TamlAssetDeclaredVisitor::getAssetDefinition (void) inline
typeAssetIdVector& TamlAssetDeclaredVisitor::getAssetDependencies (void) inline
typeLooseFileVector& TamlAssetDeclaredVisitor::getAssetLooseFiles (void) inline
virtual bool TamlAssetDeclaredVisitor::visit (const TamlParser & parser, TamlVisitor::PropertyState & propertyState) inline virtual
The state of the visited property.
Implements TamlVisitor.
References Vector< T >::begin(), dAtob(), Vector< T >::end(), Con::expandPath(), TamlVisitor::PropertyState::getObjectName(), TamlParser::getParsingFilename(), TamlVisitor::PropertyState::getPropertyName(), TamlVisitor::PropertyState::getPropertyValue(), StringUnit::getUnit(), StringUnit::getUnitCount(), TamlVisitor::PropertyState::isRootObject(), AssetDefinition::mAssetAutoUnload, AssetDefinition::mAssetBaseFilePath, AssetDefinition::mAssetCategory, AssetDefinition::mAssetDescription, AssetDefinition::mAssetId, AssetDefinition::mAssetInternal, AssetDefinition::mAssetName, AssetDefinition::mAssetType, and Vector< T >::push_back().
virtual bool TamlAssetDeclaredVisitor::wantsPropertyChanges (void) inline virtual
Whether the visitor wants to perform property changes.
This allows a check against the parser which may not allow changes.
Implements TamlVisitor.
virtual bool TamlAssetDeclaredVisitor::wantsRootOnly (void) inline virtual
Whether the visitor wants to visit the root node only.
Implements TamlVisitor.
Copyright © GarageGames, LLC. All Rights Reserved.