ShadowManager Class Reference
Main Modules Class List Namespace List Online
ShadowManager Class Reference
#include <lighting/shadowManager.h>
Public Member Functions
ShadowManager ()
virtual ~ShadowManager ()
virtual void activate ()
virtual bool canActivate ()
virtual void deactivate ()
const String & getManagerTypeName () const
virtual SceneManager * getSceneManager ()
Static Public Attributes
static const String ManagerTypeName
Constructor & Destructor Documentation
ShadowManager::ShadowManager () inline
virtual ShadowManager::~ShadowManager () inline virtual
References activate().
Member Function Documentation
virtual void ShadowManager::activate () virtual
Reimplemented in ShadowMapManager.
Referenced by ~ShadowManager().
virtual bool ShadowManager::canActivate () virtual
Referenced by deactivate().
virtual void ShadowManager::deactivate () inline virtual
Reimplemented in ShadowMapManager.
References canActivate(), and getSceneManager().
const String& ShadowManager::getManagerTypeName () const inline
References ManagerTypeName.
virtual SceneManager* ShadowManager::getSceneManager () virtual
Referenced by deactivate().
Member Data Documentation
const String ShadowManager::ManagerTypeName static
Referenced by getManagerTypeName().
Copyright © GarageGames, LLC. All Rights Reserved.