SFXDevice Class Reference
Main Modules Class List Namespace List Online
SFXDevice Class Reference abstract
Abstract base class for back-end sound API implementations.
#include <sfx/sfxDevice.h>
Public Types
enum ECaps {
CAPS_Reverb = BIT(0),
CAPS_VoiceManagement = BIT(1),
CAPS_Occlusion = BIT(2),
CAPS_DSPEffects = BIT(3),
CAPS_MultiListener = BIT(4),
CAPS_FMODDesigner = BIT(5)
}
Device capability flags.
typedef void Parent
Public Member Functions
virtual ~SFXDevice ()
virtual SFXBuffer * createBuffer (const ThreadSafeRef< SFXStream > &stream, SFXDescription *description)=0
Tries to create a new sound buffer.
virtual SFXBuffer * createBuffer (const String &fileName, SFXDescription *description)
Create a sound buffer directly for a file.
virtual SFXVoice * createVoice (bool is3D, SFXBuffer *buffer)=0
Tries to create a new voice.
U32 getBufferCount () const
Return the current total number of sound buffers.
U32 getCaps () const
Return the device capability flags.
S32 getMaxBuffers () const
The maximum number of playback buffers this device will use.
const String & getName () const
Returns the name of this device.
SFXProvider * getProvider () const
Returns the provider which created this device.
bool getUseHardware () const
Is the device set to use hardware processing.
U32 getVoiceCount () const
Return the current total number of voices.
virtual void resetReverb ()
Reset the global reverb environment to its default.
virtual void setDistanceModel (SFXDistanceModel model)
Set the rolloff curve to be used by distance attenuation of 3D sounds.
virtual void setDopplerFactor (F32 factor)
Set the scale factor to use for doppler effects on 3D sounds.
virtual void setListener (U32 index, const SFXListenerProperties &listener)
Set the properties of the given listener.
virtual void setNumListeners (U32 num)
Set the number of concurrent listeners on the device.
virtual void setReverb (const SFXReverbProperties &reverb)
Set the global reverb environment.
virtual void setRolloffFactor (F32 factor)
Set the rolloff scale factor for distance attenuation of 3D sounds.
virtual void update ()
Called from SFXSystem to do any updates the device may need to make.
Protected Types
typedef BufferVector::iterator BufferIterator
typedef Vector< SFXBuffer * > BufferVector
typedef VoiceVector::iterator VoiceIterator
typedef Vector< SFXVoice * > VoiceVector
Protected Member Functions
SFXDevice (const String &name, SFXProvider *provider, bool useHardware, S32 maxBuffers)
void _addBuffer (SFXBuffer *buffer)
Register a buffer with the device.
void _addVoice (SFXVoice *voice)
Register a voice with the device.
void _releaseAllResources ()
Release all resources tied to the device.
void _removeBuffer (SFXBuffer *buffer)
Unregister the given buffer.
virtual void _removeVoice (SFXVoice *buffer)
Unregister the given voice.
Protected Attributes
BufferVector mBuffers
Current set of sound buffers.
U32 mCaps
Device capabilities.
S32 mMaxBuffers
The maximum playback buffers this device will use.
String mName
The name of this device.
SFXProvider * mProvider
The provider which created this device.
U32 mStatNumBufferBytes
Current total memory size of sound buffers. Reflected in $SFX::Device::numBufferBytes.
U32 mStatNumBuffers
Current number of buffers. Reflected in $SFX::Device::numBuffers.
U32 mStatNumVoices
Current number of voices. Reflected in $SFX::Device::numVoices.
bool mUseHardware
Should the device try to use hardware processing.
VoiceVector mVoices
Current set of voices.
Detailed Description
Abstract base class for back-end sound API implementations.
Member Typedef Documentation
typedef BufferVector::iterator SFXDevice::BufferIterator protected
typedef Vector< SFXBuffer* > SFXDevice::BufferVector protected
typedef void SFXDevice::Parent
typedef VoiceVector::iterator SFXDevice::VoiceIterator protected
typedef Vector< SFXVoice* > SFXDevice::VoiceVector protected
Member Enumeration Documentation
enum SFXDevice::ECaps
Device capability flags.
Enumerator
CAPS_Reverb
Device supports reverb environments.
CAPS_VoiceManagement
Device manages voices on its own; deactivates virtualization code in SFX system.
CAPS_Occlusion
Device has its own sound occlusion handling (SFXOcclusionManager).
CAPS_DSPEffects
Device implements DSP effects (SFXDSPManager).
CAPS_MultiListener
Device supports multiple listeners.
CAPS_FMODDesigner
FMOD Designer support.
Constructor & Destructor Documentation
SFXDevice::SFXDevice (const String & name, SFXProvider * provider, bool useHardware, S32 maxBuffers) protected
virtual SFXDevice::~SFXDevice () virtual
Member Function Documentation
void SFXDevice::_addBuffer (SFXBuffer * buffer) protected
Register a buffer with the device.
This also triggers the buffer's stream packet request chain.
void SFXDevice::_addVoice (SFXVoice * voice) protected
Register a voice with the device.
void SFXDevice::_releaseAllResources () protected
Release all resources tied to the device.
Can be called repeatedly without harm. It is meant for device destructors that will severe the connection to the sound API and thus need all resources freed before the base destructor is called.
void SFXDevice::_removeBuffer (SFXBuffer * buffer) protected
Unregister the given buffer.
virtual void SFXDevice::_removeVoice (SFXVoice * buffer) protected virtual
Unregister the given voice.
virtual SFXBuffer* SFXDevice::createBuffer (const ThreadSafeRef< SFXStream > & stream, SFXDescription * description) pure virtual
Tries to create a new sound buffer.
If creation fails freeing another buffer will usually allow a new one to be created.
Parameters
stream The sound data stream.
description The playback configuration.
Returns
Returns a new buffer or NULL if one cannot be created.
Implemented in SFXFMODDevice, SFXDSDevice, SFXXAudioDevice, SFXALDevice, and SFXNullDevice.
Referenced by getCaps().
virtual SFXBuffer* SFXDevice::createBuffer (const String & fileName, SFXDescription * description) inline virtual
Create a sound buffer directly for a file.
This is for devices that implemented their own custom file loading.
Note
Only implemented on specific SFXDevices.
Returns
Return a new buffer or NULL.
Reimplemented in SFXFMODDevice.
References createVoice().
virtual SFXVoice* SFXDevice::createVoice (bool is3D, SFXBuffer * buffer) pure virtual
Tries to create a new voice.
Parameters
is3d True if the voice should have 3D sound enabled.
buffer The sound data to play by the voice.
Returns
Returns a new voice or NULL if one cannot be created.
Implemented in SFXFMODDevice, SFXDSDevice, SFXXAudioDevice, SFXALDevice, and SFXNullDevice.
Referenced by createBuffer().
U32 SFXDevice::getBufferCount () const inline
Return the current total number of sound buffers.
References Vector< T >::size().
U32 SFXDevice::getCaps () const inline
Return the device capability flags.
References createBuffer(), and mCaps.
S32 SFXDevice::getMaxBuffers () const inline
The maximum number of playback buffers this device will use.
References mMaxBuffers.
const String& SFXDevice::getName () const inline
Returns the name of this device.
References mName.
SFXProvider* SFXDevice::getProvider () const inline
Returns the provider which created this device.
References mProvider.
bool SFXDevice::getUseHardware () const inline
Is the device set to use hardware processing.
References mUseHardware.
U32 SFXDevice::getVoiceCount () const inline
Return the current total number of voices.
References Vector< T >::size(), and update().
virtual void SFXDevice::resetReverb () inline virtual
Reset the global reverb environment to its default.
Reimplemented in SFXFMODDevice.
virtual void SFXDevice::setDistanceModel (SFXDistanceModel model) inline virtual
Set the rolloff curve to be used by distance attenuation of 3D sounds.
Reimplemented in SFXFMODDevice, SFXDSDevice, SFXXAudioDevice, and SFXALDevice.
virtual void SFXDevice::setDopplerFactor (F32 factor) inline virtual
Set the scale factor to use for doppler effects on 3D sounds.
Reimplemented in SFXFMODDevice, SFXDSDevice, SFXXAudioDevice, and SFXALDevice.
virtual void SFXDevice::setListener (U32 index, const SFXListenerProperties & listener) inline virtual
Set the properties of the given listener.
Note
On devices that do not support multiple listeners, only setting the properties on index=0 will have a effect.
Reimplemented in SFXFMODDevice, SFXDSDevice, SFXXAudioDevice, and SFXALDevice.
virtual void SFXDevice::setNumListeners (U32 num) inline virtual
Set the number of concurrent listeners on the device.
Note
On devices that do not support multiple listeners, any value other than 1 will be ignored.
Reimplemented in SFXFMODDevice.
virtual void SFXDevice::setReverb (const SFXReverbProperties & reverb) inline virtual
Set the global reverb environment.
Reimplemented in SFXFMODDevice.
virtual void SFXDevice::setRolloffFactor (F32 factor) inline virtual
Set the rolloff scale factor for distance attenuation of 3D sounds.
Reimplemented in SFXFMODDevice, SFXDSDevice, SFXXAudioDevice, and SFXALDevice.
virtual void SFXDevice::update () virtual
Called from SFXSystem to do any updates the device may need to make.
Reimplemented in SFXFMODDevice, SFXDSDevice, SFXXAudioDevice, and SFXNullDevice.
Referenced by getVoiceCount().
Member Data Documentation
BufferVector SFXDevice::mBuffers protected
Current set of sound buffers.
U32 SFXDevice::mCaps protected
Device capabilities.
Referenced by getCaps().
S32 SFXDevice::mMaxBuffers protected
The maximum playback buffers this device will use.
Referenced by getMaxBuffers().
String SFXDevice::mName protected
The name of this device.
Referenced by getName().
SFXProvider* SFXDevice::mProvider protected
The provider which created this device.
Referenced by getProvider().
U32 SFXDevice::mStatNumBufferBytes protected
Current total memory size of sound buffers. Reflected in $SFX::Device::numBufferBytes.
U32 SFXDevice::mStatNumBuffers protected
Current number of buffers. Reflected in $SFX::Device::numBuffers.
U32 SFXDevice::mStatNumVoices protected
Current number of voices. Reflected in $SFX::Device::numVoices.
bool SFXDevice::mUseHardware protected
Should the device try to use hardware processing.
Referenced by getUseHardware().
VoiceVector SFXDevice::mVoices protected
Current set of voices.
Copyright © GarageGames, LLC. All Rights Reserved.