Swizzle< T, mapLength > Class Template Reference
Main Modules Class List Namespace List Online
Swizzle< T, mapLength > Class Template Reference
This class will swizzle 'sizeof(T)' length chunks of memory into different patterns which are user described.
#include <core/util/swizzle.h>
Public Member Functions
Swizzle (const dsize_t *map)
Construct a swizzle.
virtual ~Swizzle ()
virtual void InPlace (void *memory, const dsize_t size) const
This method will, in the general case, use the ToBuffer method to swizzle the memory specified into a temporary buffer, allocated by FrameTemp, and then copy the temporary memory into the source memory.
virtual void ToBuffer (void *destination, const void *source, const dsize_t size) const
This method copies the data from source to destination while applying the re-ordering.
Detailed Description
template<class T, dsize_t mapLength>
class Swizzle< T, mapLength >
This class will swizzle 'sizeof(T)' length chunks of memory into different patterns which are user described.
The pattern is described by an instance of Swizzle and this swizzle can then be executed on buffers. The following must be true of the buffer size: size % (sizeof(T) * mapLength) == 0
Constructor & Destructor Documentation
template<class T , dsize_t mapLength> Swizzle< T, mapLength >::Swizzle (const dsize_t * map)
Construct a swizzle.
See also
Swizzle::mMap
References dMemcpy().
template<class T, dsize_t mapLength> virtual Swizzle< T, mapLength >::~Swizzle () inline virtual
Member Function Documentation
template<class T , dsize_t mapLength> void Swizzle< T, mapLength >::InPlace (void * memory, const dsize_t size) const inline virtual
This method will, in the general case, use the ToBuffer method to swizzle the memory specified into a temporary buffer, allocated by FrameTemp, and then copy the temporary memory into the source memory.
Parameters
memory Pointer to the start of the buffer to swizzle
size Size of the buffer
Reimplemented in NullSwizzle< T, mapLength >, DXT5nmSwizzleUp24t32, and DXT5nmSwizzle.
References dMemcpy(), and Swizzle< T, mapLength >::ToBuffer().
Referenced by GFXVertexColor::set(), and Swizzle< U8, 3 >::~Swizzle().
template<class T , dsize_t mapLength> void Swizzle< T, mapLength >::ToBuffer (void * destination, const void * source, const dsize_t size) const inline virtual
This method copies the data from source to destination while applying the re-ordering.
This method is, in the non-specalized case, O(N^2) where N is sizeof(T) / size; the number of instances of type 'T' in the buffer
Parameters
destination The destination of the swizzled data
source The source data to be swizzled
size Size of the source and destination buffers.
Reimplemented in NullSwizzle< T, mapLength >, DXT5nmSwizzleUp24t32, and DXT5nmSwizzle.
References T.
Referenced by GFXVertexColor::getColor(), Swizzle< T, mapLength >::InPlace(), GFXVertexColor::set(), GBitmap::swizzle(), and Swizzle< U8, 3 >::~Swizzle().
Copyright © GarageGames, LLC. All Rights Reserved.