SphereF Class Reference
Main Modules Class List Namespace List Online
SphereF Class Reference
#include <math/mSphere.h>
Public Member Functions
SphereF ()
SphereF (const Point3F &in_rPosition, const F32 in_rRadius)
F32 distanceTo (const Point3F &pt) const
bool intersectsRay (const Point3F &start, const Point3F &end) const
bool isContained (const Point3F &in_rContain) const
bool isContained (const SphereF &in_rContain) const
bool isIntersecting (const SphereF &in_rIntersect) const
F32 squareDistanceTo (const Point3F &pt) const
Public Attributes
Point3F center
F32 radius
Constructor & Destructor Documentation
SphereF::SphereF () inline
SphereF::SphereF (const Point3F & in_rPosition, const F32 in_rRadius) inline
References distanceTo(), intersectsRay(), isContained(), isIntersecting(), and squareDistanceTo().
Member Function Documentation
F32 SphereF::distanceTo (const Point3F & pt) const inline
References center, and radius.
Referenced by SphereF().
bool SphereF::intersectsRay (const Point3F & start, const Point3F & end) const
Referenced by SphereF().
bool SphereF::isContained (const Point3F & in_rContain) const inline
References center, and radius.
Referenced by SphereF().
bool SphereF::isContained (const SphereF & in_rContain) const inline
References center, and radius.
bool SphereF::isIntersecting (const SphereF & in_rIntersect) const inline
References center, and radius.
Referenced by SphereF().
F32 SphereF::squareDistanceTo (const Point3F & pt) const
Referenced by SphereF().
Member Data Documentation
Point3F SphereF::center
Referenced by DecalSphere::DecalSphere(), distanceTo(), WindEmitter::getCenter(), isContained(), isIntersecting(), and PlaneF::whichSide().
F32 SphereF::radius
Referenced by DecalSphere::DecalSphere(), distanceTo(), WindEmitter::getRadius(), isContained(), isIntersecting(), and PlaneF::whichSide().
Copyright © GarageGames, LLC. All Rights Reserved.