BadWordFilter Class Reference
Main Modules Class List Namespace List Online
BadWordFilter Class Reference
#include <app/badWordFilter.h>
Public Member Functions
bool addBadWord (const char *word)
bool containsBadWords (const char *string)
void filterString (char *string, const char *replaceStr=NULL)
const char * getDefaultReplaceStr ()
bool setDefaultReplaceStr (const char *str)
Static Public Member Functions
static void create ()
static void destroy ()
static bool isEnabled ()
static void setEnabled (bool enable)
Member Function Documentation
bool BadWordFilter::addBadWord (const char * word)
bool BadWordFilter::containsBadWords (const char * string)
Referenced by getDefaultReplaceStr().
static void BadWordFilter::create () static
Referenced by setEnabled().
static void BadWordFilter::destroy () static
Referenced by setEnabled().
void BadWordFilter::filterString (char * string, const char * replaceStr = NULL)
Referenced by getDefaultReplaceStr().
const char* BadWordFilter::getDefaultReplaceStr () inline
References containsBadWords(), and filterString().
static bool BadWordFilter::isEnabled () inline static
bool BadWordFilter::setDefaultReplaceStr (const char * str)
static void BadWordFilter::setEnabled (bool enable) inline static
References create(), and destroy().
Copyright © GarageGames, LLC. All Rights Reserved.