SimpleHashTable< T > Class Template Reference
Main Modules Class List Namespace List Online
SimpleHashTable< T > Class Template Reference
#include <core/tSimpleHashTable.h>
Public Member Functions
SimpleHashTable (const U32 modulusSize=64, bool caseSensitive=true)
void insert (T *pObject, U8 *key, U32 keyLen)
void insert (T *pObject, const char *key)
T * remove (U8 *key, U32 keyLen)
T * remove (const char *key)
T * retreive (U8 *key, U32 keyLen)
T * retreive (const char *key)
Public Member Functions inherited from SparseArray< T >
SparseArray (const U32 modulusSize=64)
~SparseArray ()
void clearTables ()
void insert (T *pObject, U32 key)
T * remove (U32 key)
T * retreive (U32 key)
Additional Inherited Members
Protected Attributes inherited from SparseArray< T >
U32 mModulus
Node * mSentryTables
Constructor & Destructor Documentation
template<class T> SimpleHashTable< T >::SimpleHashTable (const U32 modulusSize = 64, bool caseSensitive = true) inline
Member Function Documentation
template<class T> void SimpleHashTable< T >::insert (T * pObject, U8 * key, U32 keyLen) inline
References Torque::hash(), and SparseArray< T >::insert().
Referenced by SimpleHashTable< T >::insert(), and SimpleHashTable< InputEventManager::VirtualMapData >::SimpleHashTable().
template<class T> void SimpleHashTable< T >::insert (T * pObject, const char * key) inline
References SimpleHashTable< T >::insert().
template<class T > T * SimpleHashTable< T >::remove (U8 * key, U32 keyLen) inline
References Torque::hash(), and SparseArray< T >::remove().
template<class T > T * SimpleHashTable< T >::remove (const char * key)
template<class T > T * SimpleHashTable< T >::retreive (U8 * key, U32 keyLen) inline
References Torque::hash(), and SparseArray< T >::retreive().
Referenced by SimpleHashTable< T >::retreive(), and SimpleHashTable< InputEventManager::VirtualMapData >::SimpleHashTable().
template<class T > T * SimpleHashTable< T >::retreive (const char * key)
References SimpleHashTable< T >::retreive().
Copyright © GarageGames, LLC. All Rights Reserved.