AccuStrengthFeature Class Reference
Main Modules Class List Namespace List Online
AccuStrengthFeature Class Reference
#include <shaderGen/HLSL/accuFeatureHLSL.h>
Public Member Functions
virtual String getName ()
Returns the name of this feature.
virtual String getName ()
Returns the name of this feature.
virtual void processPix (Vector< ShaderComponent * > &componentList, const MaterialFeatureData &fd)
virtual void processPix (Vector< ShaderComponent * > &componentList, const MaterialFeatureData &fd)
Public Member Functions inherited from ShaderFeatureHLSL
ShaderFeatureHLSL ()
Var * addOutDetailTexCoord (Vector< ShaderComponent * > &componentList, MultiLine *meta, bool useTexAnim)
Var * addOutWsPosition (Vector< ShaderComponent * > &componentList, bool useInstancing, MultiLine *meta)
Adds the "wsPosition" to the input connector if it doesn't exist.
LangElement * assignColor (LangElement *elem, Material::BlendOp blend, LangElement *lerpElem=NULL, ShaderFeature::OutputTarget outputTarget=ShaderFeature::DefaultTarget)
Helper function for applying the color to shader output.
LangElement * expandNormalMap (LangElement *sampleNormalOp, LangElement *normalDecl, LangElement *normalVar, const MaterialFeatureData &fd)
Expand and assign a normal map. This takes care of compressed normal maps as well.
Var * getInvWorldView (Vector< ShaderComponent * > &componentList, bool useInstancing, MultiLine *meta)
Var * getModelView (Vector< ShaderComponent * > &componentList, bool useInstancing, MultiLine *meta)
Var * getObjTrans (Vector< ShaderComponent * > &componentList, bool useInstancing, MultiLine *meta)
Var * getOutObjToTangentSpace (Vector< ShaderComponent * > &componentList, MultiLine *meta, const MaterialFeatureData &fd)
Returns the "objToTangentSpace" transform or creates one if this is the first feature to need it.
Var * getOutTexCoord (const char *name, const char *type, bool mapsToSampler, bool useTexAnim, MultiLine *meta, Vector< ShaderComponent * > &componentList)
Var * getOutViewToTangent (Vector< ShaderComponent * > &componentList, MultiLine *meta, const MaterialFeatureData &fd)
Returns the existing output "outViewToTangent" transform or creates one if this is the first feature to need it.
Var * getOutWorldToTangent (Vector< ShaderComponent * > &componentList, MultiLine *meta, const MaterialFeatureData &fd)
Returns the existing output "outWorldToTangent" transform or creates one if this is the first feature to need it.
Var * getVertTexCoord (const String &name)
Get the incoming base texture coords - useful for bumpmap and detail maps.
Var * getWorldView (Vector< ShaderComponent * > &componentList, bool useInstancing, MultiLine *meta)
void getWsPosition (Vector< ShaderComponent * > &componentList, bool useInstancing, MultiLine *meta, LangElement *wsPosition)
Calculates the world space position in the vertex shader and assigns it to the passed language element.
LangElement * setupTexSpaceMat (Vector< ShaderComponent * > &componentList, Var **texSpaceMat)
Set up a texture space matrix - to pass into pixel shader.
Public Member Functions inherited from ShaderFeature
ShaderFeature ()
virtual ~ShaderFeature ()
virtual void addDependency (const ShaderDependency *depends)
Adds a dependency to this shader feature.
virtual ShaderFeatureConstHandles * createConstHandles (GFXShader *shader, SimObject *userObject)
virtual void determineFeature (Material *material, const GFXVertexFormat *vertexFormat, U32 stageNum, const FeatureType &type, const FeatureSet &features, MaterialFeatureData *outFeatureData)
virtual Material::BlendOp getBlendOp ()
Identifies what type of blending a feature uses.
virtual const Vector< const ShaderDependency * > & getDependencies () const
Gets the dependency list for this shader feature.
LangElement * getOutput () const
returns output from a processed vertex or pixel shader
virtual U32 getOutputTargets (const MaterialFeatureData &fd) const
Gets the render target this shader feature is assigning data to.
const char * getOutputTargetVarName (OutputTarget target=DefaultTarget) const
Returns the name of output targer var.
virtual const char * getOutputVarName () const
Returns the output variable name for this feature if it applies.
S32 getProcessIndex () const
virtual Resources getResources (const MaterialFeatureData &fd)
Returns the resource requirements of this feature based on what other features are present.
virtual void processPixMacros (Vector< GFXShaderMacro > &macros, const MaterialFeatureData &fd)
Allows the feature to add macros to pixel shader compiles.
virtual void processVert (Vector< ShaderComponent * > &componentList, const MaterialFeatureData &fd)
virtual void processVertMacros (Vector< GFXShaderMacro > &macros, const MaterialFeatureData &fd)
Allows the feature to add macros to vertex shader compiles.
virtual void reset ()
Called after processing the vertex and processing the pixel to cleanup any temporary structures stored in the feature.
void setInstancingFormat (GFXVertexFormat *format)
void setProcessIndex (S32 index)
virtual void setTexData (Material::StageData &stageDat, const MaterialFeatureData &fd, RenderPassData &passData, U32 &texIndex)
Fills texture related info in RenderPassData for this feature.
Public Member Functions inherited from ShaderFeatureGLSL
ShaderFeatureGLSL ()
Var * addOutDetailTexCoord (Vector< ShaderComponent * > &componentList, MultiLine *meta, bool useTexAnim)
Var * addOutWsPosition (Vector< ShaderComponent * > &componentList, bool useInstancing, MultiLine *meta)
Adds the "wsPosition" to the input connector if it doesn't exist.
LangElement * assignColor (LangElement *elem, Material::BlendOp blend, LangElement *lerpElem=NULL, ShaderFeature::OutputTarget outputTarget=ShaderFeature::DefaultTarget)
Helper function for applying the color to shader output.
LangElement * expandNormalMap (LangElement *sampleNormalOp, LangElement *normalDecl, LangElement *normalVar, const MaterialFeatureData &fd)
Expand and assign a normal map. This takes care of compressed normal maps as well.
Var * getInvWorldView (Vector< ShaderComponent * > &componentList, bool useInstancing, MultiLine *meta)
Var * getModelView (Vector< ShaderComponent * > &componentList, bool useInstancing, MultiLine *meta)
Var * getObjTrans (Vector< ShaderComponent * > &componentList, bool useInstancing, MultiLine *meta)
Var * getOutObjToTangentSpace (Vector< ShaderComponent * > &componentList, MultiLine *meta, const MaterialFeatureData &fd)
Returns the "objToTangentSpace" transform or creates one if this is the first feature to need it.
Var * getOutTexCoord (const char *name, const char *type, bool mapsToSampler, bool useTexAnim, MultiLine *meta, Vector< ShaderComponent * > &componentList)
Var * getOutViewToTangent (Vector< ShaderComponent * > &componentList, MultiLine *meta, const MaterialFeatureData &fd)
Returns the existing output "outViewToTangent" transform or creates one if this is the first feature to need it.
Var * getOutWorldToTangent (Vector< ShaderComponent * > &componentList, MultiLine *meta, const MaterialFeatureData &fd)
Returns the existing output "outWorldToTangent" transform or creates one if this is the first feature to need it.
Var * getVertTexCoord (const String &name)
Get the incoming base texture coords - useful for bumpmap and detail maps.
Var * getWorldView (Vector< ShaderComponent * > &componentList, bool useInstancing, MultiLine *meta)
void getWsPosition (Vector< ShaderComponent * > &componentList, bool useInstancing, MultiLine *meta, LangElement *wsPosition)
Calculates the world space position in the vertex shader and assigns it to the passed language element.
LangElement * setupTexSpaceMat (Vector< ShaderComponent * > &componentList, Var **texSpaceMat)
Set up a texture space matrix - to pass into pixel shader.
Additional Inherited Members
Public Types inherited from ShaderFeature
enum OutputTarget {
DefaultTarget = 1 << 0,
RenderTarget1 = 1 << 1,
RenderTarget2 = 1 << 2,
RenderTarget3 = 1 << 3
}
Static Public Member Functions inherited from ShaderFeatureHLSL
static Var * addOutVpos (MultiLine *meta, Vector< ShaderComponent * > &componentList)
static Var * getInColor (const char *name, const char *type, Vector< ShaderComponent * > &componentList)
static Var * getInTexCoord (const char *name, const char *type, bool mapsToSampler, Vector< ShaderComponent * > &componentList)
Returns an input texture coord by name adding it to the input connector if it doesn't exist.
static Var * getInViewToTangent (Vector< ShaderComponent * > &componentList)
Returns the input "viewToTangent" space transform adding it to the input connector if it doesn't exist.
static Var * getInVpos (MultiLine *meta, Vector< ShaderComponent * > &componentList)
Returns the VPOS input register for the pixel shader.
static Var * getInWorldToTangent (Vector< ShaderComponent * > &componentList)
Returns the input "worldToTanget" space transform adding it to the input connector if it doesn't exist.
static Var * getInWsPosition (Vector< ShaderComponent * > &componentList)
Returns the input world space position from the connector.
static Var * getNormalMapTex ()
Returns the input normal map texture.
static Var * getWsView (Var *wsPosition, MultiLine *meta)
Returns the world space view vector from the wsPosition.
Static Public Member Functions inherited from ShaderFeature
static Var * findOrCreateLocal (const char *name, const char *type, MultiLine *multi)
A simpler helper function which either finds the existing local var or creates one.
Static Public Member Functions inherited from ShaderFeatureGLSL
static Var * addOutVpos (MultiLine *meta, Vector< ShaderComponent * > &componentList)
static Var * getInColor (const char *name, const char *type, Vector< ShaderComponent * > &componentList)
static Var * getInTexCoord (const char *name, const char *type, bool mapsToSampler, Vector< ShaderComponent * > &componentList)
Returns an input texture coord by name adding it to the input connector if it doesn't exist.
static Var * getInViewToTangent (Vector< ShaderComponent * > &componentList)
Returns the input "viewToTangent" space transform adding it to the input connector if it doesn't exist.
static Var * getInVpos (MultiLine *meta, Vector< ShaderComponent * > &componentList)
Returns the VPOS input register for the pixel shader.
static Var * getInWorldToTangent (Vector< ShaderComponent * > &componentList)
Returns the input "worldToTanget" space transform adding it to the input connector if it doesn't exist.
static Var * getInWsPosition (Vector< ShaderComponent * > &componentList)
Returns the input world space position from the connector.
static Var * getNormalMapTex ()
Returns the input normal map texture.
static Var * getWsView (Var *wsPosition, MultiLine *meta)
Returns the world space view vector from the wsPosition.
Public Attributes inherited from ShaderFeature
GFXVertexFormat * mInstancingFormat
const GFXVertexFormat * mVertexFormat
Protected Attributes inherited from ShaderFeatureHLSL
bool mIsDirect3D11
Protected Attributes inherited from ShaderFeature
Vector< const ShaderDependency * > mDependencies
The list of unique shader dependencies.
S32 mProcessIndex
LangElement * output
Member Function Documentation
virtual String AccuStrengthFeature::getName () inline virtual
Returns the name of this feature.
Implements ShaderFeature.
virtual String AccuStrengthFeature::getName () inline virtual
Returns the name of this feature.
Implements ShaderFeature.
virtual void AccuStrengthFeature::processPix (Vector< ShaderComponent * > & componentList, const MaterialFeatureData & fd) inline virtual
Process pixel shader - This function is used by each feature to generate a list of LangElements that can be traversed and "printed" to generate the actual shader code. The 'output' member is the head of that list.
The componentList is used mostly for access to the "Connector" structure which is used to pass data from the vertex to the pixel shader.
The MaterialFeatureData parameter is used to determine what other features are present for the shader being generated.
Reimplemented from ShaderFeature.
References Var::constSortPos, LangElement::find(), LangElement::setName(), Var::setType(), and Var::uniform.
virtual void AccuStrengthFeature::processPix (Vector< ShaderComponent * > & componentList, const MaterialFeatureData & fd) inline virtual
Process pixel shader - This function is used by each feature to generate a list of LangElements that can be traversed and "printed" to generate the actual shader code. The 'output' member is the head of that list.
The componentList is used mostly for access to the "Connector" structure which is used to pass data from the vertex to the pixel shader.
The MaterialFeatureData parameter is used to determine what other features are present for the shader being generated.
Reimplemented from ShaderFeature.
References Var::constSortPos, LangElement::find(), LangElement::setName(), Var::setType(), and Var::uniform.
Copyright © GarageGames, LLC. All Rights Reserved.