TamlAssetReferencedVisitor Class Reference
Main Modules Class List Namespace List Online
TamlAssetReferencedVisitor Class Reference
#include <assets/tamlAssetReferencedVisitor.h>
Public Types
typedef StringTableEntry typeAssetId
typedef HashMap< typeAssetId, StringTableEntry > typeAssetReferencedHash
Public Member Functions
TamlAssetReferencedVisitor ()
virtual ~TamlAssetReferencedVisitor ()
void clear (void)
const typeAssetReferencedHash & getAssetReferencedMap (void) const
virtual bool visit (const TamlParser &parser, TamlVisitor::PropertyState &propertyState)
The state of the visited property.
virtual bool wantsPropertyChanges (void)
Whether the visitor wants to perform property changes.
virtual bool wantsRootOnly (void)
Whether the visitor wants to visit the root node only.
Public Member Functions inherited from TamlVisitor
TamlVisitor ()
virtual ~TamlVisitor ()
Member Typedef Documentation
typedef StringTableEntry TamlAssetReferencedVisitor::typeAssetId
typedef HashMap<typeAssetId, StringTableEntry> TamlAssetReferencedVisitor::typeAssetReferencedHash
Constructor & Destructor Documentation
TamlAssetReferencedVisitor::TamlAssetReferencedVisitor () inline
virtual TamlAssetReferencedVisitor::~TamlAssetReferencedVisitor () inline virtual
Member Function Documentation
void TamlAssetReferencedVisitor::clear (void) inline
References HashMap< Key, Value, Sequence >::clear().
const typeAssetReferencedHash& TamlAssetReferencedVisitor::getAssetReferencedMap (void) const inline
virtual bool TamlAssetReferencedVisitor::visit (const TamlParser & parser, TamlVisitor::PropertyState & propertyState) inline virtual
The state of the visited property.
Implements TamlVisitor.
References HashMap< Key, Value, Sequence >::contains(), TamlVisitor::PropertyState::getPropertyValue(), StringUnit::getUnit(), StringUnit::getUnitCount(), and HashMap< Key, Value, Sequence >::insert().
virtual bool TamlAssetReferencedVisitor::wantsPropertyChanges (void) inline virtual
Whether the visitor wants to perform property changes.
This allows a check against the parser which may not allow changes.
Implements TamlVisitor.
virtual bool TamlAssetReferencedVisitor::wantsRootOnly (void) inline virtual
Whether the visitor wants to visit the root node only.
Implements TamlVisitor.
Copyright © GarageGames, LLC. All Rights Reserved.