Point2I Class Reference
Main Modules Class List Namespace List Online
Point2I Class Reference
2D integer point
#include <math/mPoint2.h>
Public Member Functions
Point2I ()
Create an uninitialized point.
Point2I (const Point2I &)
Copy constructor.
Point2I (S32 in_x, S32 in_y)
Create point from two co-ordinates.
void convolve (const Point2I &)
Convolve this point by parameter.
bool isZero () const
Is this point at the origin? (No epsilon used)
F32 len () const
Get the length of the point.
S32 lenSquared () const
Get the length-squared of the point.
void neg ()
Invert sign of point's co-ordinates.
operator const S32 * () const
operator S32 * ()
bool operator!= (const Point2I &) const
Point2I operator* (S32) const
Point2I operator* (const Point2I &) const
Point2I & operator*= (S32)
Point2I & operator*= (const Point2I &)
Point2I operator+ (const Point2I &) const
Point2I & operator+= (const Point2I &)
Point2I operator- (const Point2I &) const
Point2I operator- () const
Point2I & operator-= (const Point2I &)
Point2I operator/ (S32) const
Point2I operator/ (const Point2I &) const
Point2I & operator/= (S32)
Point2I & operator/= (const Point2I &)
bool operator== (const Point2I &) const
void set (S32 in_x, S32 in_y)
Set (x,y) position.
void setMax (const Point2I &)
Store greater co-ordinates from parameter in this point.
void setMin (const Point2I &)
Store lesser co-ordinates from parameter in this point.
void zero ()
Zero all values.
Public Attributes
S32 x
X position.
S32 y
Y position.
Static Public Attributes
static const Point2I Max
static const Point2I Min
static const Point2I One
static const Point2I Zero
Detailed Description
2D integer point
Uses S32 internally.
Constructor & Destructor Documentation
Point2I::Point2I () inline
Create an uninitialized point.
Referenced by operator*(), operator+(), operator-(), and operator/().
Point2I::Point2I (const Point2I & _copy) inline
Copy constructor.
Point2I::Point2I (S32 in_x, S32 in_y) inline
Create point from two co-ordinates.
Member Function Documentation
void Point2I::convolve (const Point2I & c) inline
Convolve this point by parameter.
References x, and y.
Referenced by Point2D::operator const F64 *().
bool Point2I::isZero () const inline
Is this point at the origin? (No epsilon used)
References x, and y.
Referenced by Point2D::operator const F64 *().
F32 Point2I::len () const inline
Get the length of the point.
References x, and y.
Referenced by Point2D::operator const F64 *().
S32 Point2I::lenSquared () const inline
Get the length-squared of the point.
References x, and y.
Referenced by Point2D::operator const F64 *().
void Point2I::neg () inline
Invert sign of point's co-ordinates.
References x, and y.
Referenced by Point2D::operator const F64 *().
Point2I::operator const S32 * () const inline
References operator!=(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator==(), and x.
Point2I::operator S32 * () inline
References x.
bool Point2I::operator!= (const Point2I & _test) const inline
Referenced by Point2F::getPerpendicular(), Point2D::operator const F64 *(), and operator const S32 *().
Point2I Point2I::operator* (S32 mul) const inline
References Point2I(), x, and y.
Referenced by Point2F::getPerpendicular(), Point2D::operator const F64 *(), and operator const S32 *().
Point2I Point2I::operator* (const Point2I & _vec) const inline
References Point2I(), x, and y.
Point2I & Point2I::operator*= (S32 mul) inline
References x, and y.
Referenced by Point2F::getPerpendicular(), Point2D::operator const F64 *(), and operator const S32 *().
Point2I & Point2I::operator*= (const Point2I & _vec) inline
References x, and y.
Point2I Point2I::operator+ (const Point2I & _add) const inline
References Point2I(), x, and y.
Referenced by Point2F::getPerpendicular(), Point2D::operator const F64 *(), and operator const S32 *().
Point2I & Point2I::operator+= (const Point2I & _add) inline
References x, and y.
Referenced by Point2F::getPerpendicular(), Point2D::operator const F64 *(), and operator const S32 *().
Point2I Point2I::operator- (const Point2I & _rSub) const inline
References Point2I(), x, and y.
Point2I Point2I::operator- () const inline
References Point2I(), x, and y.
Referenced by Point2F::getPerpendicular(), Point2D::operator const F64 *(), and operator const S32 *().
Point2I & Point2I::operator-= (const Point2I & _rSub) inline
References x, and y.
Referenced by Point2F::getPerpendicular(), Point2D::operator const F64 *(), and operator const S32 *().
Point2I Point2I::operator/ (S32 div) const inline
References Point2I(), x, and y.
Referenced by Point2F::getPerpendicular(), Point2D::operator const F64 *(), and operator const S32 *().
Point2I Point2I::operator/ (const Point2I & _vec) const inline
References Point2I(), x, and y.
Point2I & Point2I::operator/= (S32 div) inline
References x, and y.
Referenced by Point2F::getPerpendicular(), Point2D::operator const F64 *(), and operator const S32 *().
Point2I & Point2I::operator/= (const Point2I & _vec) inline
References x, and y.
bool Point2I::operator== (const Point2I & _test) const inline
References x, and y.
Referenced by Point2F::getPerpendicular(), Point2D::operator const F64 *(), and operator const S32 *().
void Point2I::set (S32 in_x, S32 in_y) inline
Set (x,y) position.
References x, and y.
Referenced by GuiArrayCtrl::deselectCells(), GuiFrameSetCtrl::FrameDetail::FrameDetail(), GridPoint::GridPoint(), PlatformWindow::PlatformWindow(), RectI::set(), x86UNIXPlatformState::setDesktopSize(), x86UNIXPlatformState::setWindowSize(), and x86UNIXPlatformState::x86UNIXPlatformState().
void Point2I::setMax (const Point2I & _test) inline
Store greater co-ordinates from parameter in this point.
References x, and y.
void Point2I::setMin (const Point2I & _test) inline
Store lesser co-ordinates from parameter in this point.
References x, and y.
void Point2I::zero () inline
Zero all values.
References x, and y.
Member Data Documentation
const Point2I Point2I::Max static
const Point2I Point2I::Min static
const Point2I Point2I::One static
S32 Point2I::x
X position.
Referenced by RectI::area(), RectClipper::clipPoint(), RectI::contains(), convolve(), GuiEditCtrl::drawCrossSection(), Edge::Edge(), EdgeRectI::EdgeRectI(), RectSpacingI::expandRect(), TamlCustomField::getFieldValue(), GuiControl::getLeft(), QuadTreeTracer::getNodeIndex(), GuiControl::getWidth(), DictHash::hash(), GuiFrameSetCtrl::hitHorizontalDivider(), GuiFrameSetCtrl::hitVerticalDivider(), GuiEditCtrl::inNut(), RectI::inset(), RectF::inset(), RectD::inset(), RectSpacingI::insetRect(), RectI::intersect(), RectI::isValidRect(), isZero(), len(), RectI::len_x(), lenSquared(), neg(), Point2D::operator const F64 *(), Edge::operator const RectI(), operator const S32 *(), Point2D::operator F64 *(), operator S32 *(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator==(), RectI::pointInRect(), set(), TamlCustomField::setFieldValue(), setMax(), setMin(), GuiEditCtrl::snapDelta(), RectI::unionRects(), and zero().
S32 Point2I::y
Y position.
Referenced by RectI::area(), RectClipper::clipPoint(), GuiRolloutCtrl::collapse(), RectI::contains(), convolve(), GuiEditCtrl::drawCrossSection(), Edge::Edge(), EdgeRectI::EdgeRectI(), GuiRolloutCtrl::expand(), RectSpacingI::expandRect(), TamlCustomField::getFieldValue(), GuiControl::getHeight(), QuadTreeTracer::getNodeIndex(), GuiControl::getTop(), DictHash::hash(), GuiFrameSetCtrl::hitHorizontalDivider(), GuiFrameSetCtrl::hitVerticalDivider(), GuiEditCtrl::inNut(), RectI::inset(), RectF::inset(), RectD::inset(), RectSpacingI::insetRect(), RectI::intersect(), GuiScrollCtrl::isScrolledToBottom(), RectI::isValidRect(), isZero(), len(), RectI::len_y(), lenSquared(), neg(), Edge::operator const RectI(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator==(), RectI::pointInRect(), set(), TamlCustomField::setFieldValue(), setMax(), setMin(), GuiEditCtrl::snapDelta(), RectI::unionRects(), and zero().
const Point2I Point2I::Zero static
Referenced by GFXTexHandle::getWidthHeight().
Copyright © GarageGames, LLC. All Rights Reserved.