GuiTreeViewCtrl::Item Class Reference
Main Modules Class List Namespace List Online
GuiTreeViewCtrl::Item Class Reference
#include <gui/controls/guiTreeViewCtrl.h>
Classes
struct InspectorTag
struct ScriptTag
Public Types
enum ItemState {
Selected = BIT(0),
Expanded = BIT(1),
Marked = BIT(2),
Filtered = BIT(3),
MouseOverBmp = BIT(4),
MouseOverText = BIT(5),
MouseOverIcon = BIT(6),
InspectorData = BIT(7),
VirtualParent = BIT(8),
RebuildVisited = BIT(9),
ShowObjectId = BIT(10),
ShowClassName = BIT(11),
ShowObjectName = BIT(12),
ShowInternalName = BIT(13),
ShowClassNameForUnnamed = BIT(14),
ForceItemName = BIT(15),
ForceDragTarget = BIT(16),
DenyDrag = BIT(17)
}
Public Member Functions
Item (GuiTreeViewCtrl *parent, GuiControlProfile *pProfile)
this stores the pixel width needed to render the item's data in the onRenderCell function to optimize for speed.
~Item ()
void sort (bool caseSensitive=true, bool traverseHierarchy=false, bool parentsFirst=false)
Sort the childs of the item by their text.
Public Attributes
Item * mChild
S32 mDataRenderWidth
S32 mIcon
S16 mId
struct GuiTreeViewCtrl::Item::InspectorTag mInspectorInfo
Item * mNext
Item * mParent
GuiTreeViewCtrl * mParentControl
Item * mPrevious
SimObjectPtr< GuiControlProfile > mProfile
struct GuiTreeViewCtrl::Item::ScriptTag mScriptInfo
BitSet32 mState
U16 mTabLevel
String mTooltip
Get Methods
S8 getNormalImage () const
S8 getExpandedImage () const
StringTableEntry getText ()
StringTableEntry getValue ()
const S16 getID () const
SimObject * getObject ()
U32 getDisplayTextLength ()
S32 getDisplayTextWidth (GFont *font)
void getDisplayText (U32 bufLen, char *buf)
bool hasObjectBasedTooltip ()
void getTooltipText (U32 bufLen, char *buf)
Set Methods
void setExpanded (const bool f=true)
Set whether an item is expanded or not (showing children or having them hidden)
void setExpandedImage (const S8 id)
Set the image to display when an item IS expanded.
void setNormalImage (const S8 id)
Set the image to display when an item is NOT expanded.
void setObject (SimObject *obj)
Assign a SimObject pointer to an inspector data item.
void setText (StringTableEntry txt)
Set the items displayable text (caption)
void setValue (StringTableEntry val)
Set the items script value (data)
void setVirtualParent (bool value)
Set the items virtual parent flag.
void setFiltered (bool value)
Set whether the item is filtered out or not.
State Retrieval
bool isExpanded () const
Returns true if this item is expanded.
bool isFiltered () const
Return whether the item is current filtered out or not.
bool isInspectorData () const
Returns true if an item is inspector data or false if it's just an item.
bool isDragTargetAllowed () const
Returns true if we've been manually set to allow dragging overrides.
bool isDragAllowed () const
Returns true if we've been manually set to allow dragging overrides.
bool isParent () const
Returns true if we should show the expand art and make the item interact with the mouse as if it were a parent.
bool showInternalNameOnly () const
Return true if text label for inspector item should include internal name only.
bool showObjectNameOnly () const
Return true if text label for inspector item should include object name only.
Searching Methods
Item * findChildByName (const char *name)
Find a regular data item by it's script name.
Item * findChildByValue (const SimObject *obj)
Find an inspector data item by it's SimObject pointer.
Item * findChildByValue (StringTableEntry Value)
Find a regular data item by it's script value.
Detailed Description
Introduction
Member Enumeration Documentation
enum GuiTreeViewCtrl::Item::ItemState
Enumerator
Selected
Expanded
Marked
Marked items are drawn with a border around them.
This is
Filtered
different than "Selected" because it can only be set by script.
Whether the item is currently filtered out.
MouseOverBmp
MouseOverText
MouseOverIcon
InspectorData
Set if we're representing some inspector.
VirtualParent
info (ie, use mInspectorInfo, not mScriptInfo)
This indicates that we should be rendered as
RebuildVisited
a parent even though we don't have any children.
This is useful for preventing scenarios where we might want to create thousands of Items that might never be shown (for instance if we're browsing the object hierarchy in Torque, which might have thousands of objects). Rebuild traversal for virtual parents has visited and validated this item.
ShowObjectId
ShowClassName
ShowObjectName
ShowInternalName
ShowClassNameForUnnamed
ForceItemName
ForceDragTarget
DenyDrag
Constructor & Destructor Documentation
GuiTreeViewCtrl::Item::Item (GuiTreeViewCtrl * parent, GuiControlProfile * pProfile)
this stores the pixel width needed to render the item's data in the onRenderCell function to optimize for speed.
GuiTreeViewCtrl::Item::~Item ()
Member Function Documentation
Item* GuiTreeViewCtrl::Item::findChildByName (const char * name)
Find a regular data item by it's script name.
Referenced by showObjectNameOnly().
Item* GuiTreeViewCtrl::Item::findChildByValue (const SimObject * obj)
Find an inspector data item by it's SimObject pointer.
Referenced by showObjectNameOnly().
Item* GuiTreeViewCtrl::Item::findChildByValue (StringTableEntry Value)
Find a regular data item by it's script value.
void GuiTreeViewCtrl::Item::getDisplayText (U32 bufLen, char * buf)
Referenced by getID().
U32 GuiTreeViewCtrl::Item::getDisplayTextLength ()
Referenced by getID().
S32 GuiTreeViewCtrl::Item::getDisplayTextWidth (GFont * font)
Referenced by getID().
S8 GuiTreeViewCtrl::Item::getExpandedImage () const
const S16 GuiTreeViewCtrl::Item::getID () const inline
References getDisplayText(), getDisplayTextLength(), getDisplayTextWidth(), getObject(), getTooltipText(), hasObjectBasedTooltip(), mId, setExpanded(), setExpandedImage(), setNormalImage(), setObject(), setText(), setValue(), and setVirtualParent().
S8 GuiTreeViewCtrl::Item::getNormalImage () const
SimObject* GuiTreeViewCtrl::Item::getObject ()
Referenced by getID().
StringTableEntry GuiTreeViewCtrl::Item::getText ()
void GuiTreeViewCtrl::Item::getTooltipText (U32 bufLen, char * buf)
Referenced by getID().
StringTableEntry GuiTreeViewCtrl::Item::getValue ()
bool GuiTreeViewCtrl::Item::hasObjectBasedTooltip ()
Referenced by getID().
bool GuiTreeViewCtrl::Item::isDragAllowed () const inline
Returns true if we've been manually set to allow dragging overrides.
As it's a manually set flag, by default it is false.
References DenyDrag, isParent(), and BitSet32::test().
bool GuiTreeViewCtrl::Item::isDragTargetAllowed () const inline
Returns true if we've been manually set to allow dragging overrides.
As it's a manually set flag, by default it is false.
References ForceDragTarget, and BitSet32::test().
bool GuiTreeViewCtrl::Item::isExpanded () const
Returns true if this item is expanded.
For inspector objects, the expansion is stored on the SimObject, for other things we use our bit vector.
Referenced by setFiltered().
bool GuiTreeViewCtrl::Item::isFiltered () const inline
Return whether the item is current filtered out or not.
Note
Parent items may be filtered and yet still be visible if they have children that are not filtered.
References Filtered, and BitSet32::test().
bool GuiTreeViewCtrl::Item::isInspectorData () const inline
Returns true if an item is inspector data or false if it's just an item.
References InspectorData, and BitSet32::test().
bool GuiTreeViewCtrl::Item::isParent () const
Returns true if we should show the expand art and make the item interact with the mouse as if it were a parent.
Referenced by isDragAllowed().
void GuiTreeViewCtrl::Item::setExpanded (const bool f = true)
Set whether an item is expanded or not (showing children or having them hidden)
Referenced by getID().
void GuiTreeViewCtrl::Item::setExpandedImage (const S8 id)
Set the image to display when an item IS expanded.
Referenced by getID().
void GuiTreeViewCtrl::Item::setFiltered (bool value) inline
Set whether the item is filtered out or not.
References Filtered, isExpanded(), and BitSet32::set().
void GuiTreeViewCtrl::Item::setNormalImage (const S8 id)
Set the image to display when an item is NOT expanded.
Referenced by getID().
void GuiTreeViewCtrl::Item::setObject (SimObject * obj)
Assign a SimObject pointer to an inspector data item.
Referenced by getID().
void GuiTreeViewCtrl::Item::setText (StringTableEntry txt)
Set the items displayable text (caption)
Referenced by getID().
void GuiTreeViewCtrl::Item::setValue (StringTableEntry val)
Set the items script value (data)
Referenced by getID().
void GuiTreeViewCtrl::Item::setVirtualParent (bool value)
Set the items virtual parent flag.
Referenced by getID().
bool GuiTreeViewCtrl::Item::showInternalNameOnly () const inline
Return true if text label for inspector item should include internal name only.
References ShowClassName, ShowInternalName, ShowObjectId, ShowObjectName, and BitSet32::test().
bool GuiTreeViewCtrl::Item::showObjectNameOnly () const inline
Return true if text label for inspector item should include object name only.
References findChildByName(), findChildByValue(), ShowClassName, ShowInternalName, ShowObjectId, ShowObjectName, sort(), and BitSet32::test().
void GuiTreeViewCtrl::Item::sort (bool caseSensitive = true, bool traverseHierarchy = false, bool parentsFirst = false)
Sort the childs of the item by their text.
Parameters
caseSensitive If true, sorting is case-sensitive.
traverseHierarchy If true, also triggers a sort() on all child items.
parentsFirst If true, parents are grouped before children in the resulting sort.
Referenced by showObjectNameOnly().
Member Data Documentation
Item* GuiTreeViewCtrl::Item::mChild
S32 GuiTreeViewCtrl::Item::mDataRenderWidth
S32 GuiTreeViewCtrl::Item::mIcon
S16 GuiTreeViewCtrl::Item::mId
Referenced by getID().
struct GuiTreeViewCtrl::Item::InspectorTag GuiTreeViewCtrl::Item::mInspectorInfo
Item* GuiTreeViewCtrl::Item::mNext
Item* GuiTreeViewCtrl::Item::mParent
Referenced by GuiTreeViewCtrl::_isRootLevelItem().
GuiTreeViewCtrl* GuiTreeViewCtrl::Item::mParentControl
Item* GuiTreeViewCtrl::Item::mPrevious
SimObjectPtr< GuiControlProfile > GuiTreeViewCtrl::Item::mProfile
struct GuiTreeViewCtrl::Item::ScriptTag GuiTreeViewCtrl::Item::mScriptInfo
BitSet32 GuiTreeViewCtrl::Item::mState
U16 GuiTreeViewCtrl::Item::mTabLevel
String GuiTreeViewCtrl::Item::mTooltip
Copyright © GarageGames, LLC. All Rights Reserved.