AppMesh Class Reference
Main Modules Class List Namespace List Online
AppMesh Class Reference abstract
#include <ts/loader/appMesh.h>
Public Member Functions
AppMesh ()
virtual ~AppMesh ()
virtual bool animatesFrame (const AppSequence *appSeq)
virtual bool animatesMatFrame (const AppSequence *appSeq)
virtual bool animatesVis (const AppSequence *appSeq)
void computeBounds (Box3F &bounds)
void computeNormals ()
TSMesh * constructTSMesh ()
virtual bool getBool (const char *propName, bool &defaultVal)=0
virtual bool getFloat (const char *propName, F32 &defaultVal)=0
virtual bool getInt (const char *propName, S32 &defaultVal)=0
virtual MatrixF getMeshTransform (F32 time)=0
virtual const char * getName (bool allowFixed=true)=0
virtual F32 getVisValue (F32 time)=0
virtual bool isBillboard ()
virtual bool isBillboardZAxis ()
virtual bool isSkin ()
virtual void lockMesh (F32 t, const MatrixF &objOffset)
virtual void lookupSkinData ()=0
Public Attributes
Vector< S32 > boneIndex
Vector< AppNode * > bones
Vector< ColorI > colors
S32 detailSize
U32 flags
Vector< U32 > indices
Vector< Point3F > initialNorms
Vector< MatrixF > initialTransforms
Vector< Point3F > initialVerts
Vector< S32 > nodeIndex
Vector< Point3F > normals
S32 numFrames
S32 numMatFrames
MatrixF objectOffset
Vector< Point3F > points
Vector< TSDrawPrimitive > primitives
Vector< Point2F > uv2s
Vector< Point2F > uvs
Vector< S32 > vertexIndex
U32 vertsPerFrame
Vector< F32 > weight
Static Public Attributes
static Vector< AppMaterial * > appMaterials
Constructor & Destructor Documentation
AppMesh::AppMesh ()
virtual AppMesh::~AppMesh () virtual
Member Function Documentation
virtual bool AppMesh::animatesFrame (const AppSequence * appSeq) inline virtual
Reimplemented in ColladaAppMesh.
References isBillboard(), and isBillboardZAxis().
virtual bool AppMesh::animatesMatFrame (const AppSequence * appSeq) inline virtual
Reimplemented in ColladaAppMesh.
virtual bool AppMesh::animatesVis (const AppSequence * appSeq) inline virtual
Reimplemented in ColladaAppMesh.
void AppMesh::computeBounds (Box3F & bounds)
void AppMesh::computeNormals ()
TSMesh* AppMesh::constructTSMesh ()
virtual bool AppMesh::getBool (const char * propName, bool & defaultVal) pure virtual
Implemented in ColladaAppMesh.
virtual bool AppMesh::getFloat (const char * propName, F32 & defaultVal) pure virtual
Implemented in ColladaAppMesh.
virtual bool AppMesh::getInt (const char * propName, S32 & defaultVal) pure virtual
Implemented in ColladaAppMesh.
virtual MatrixF AppMesh::getMeshTransform (F32 time) pure virtual
Implemented in ColladaAppMesh.
virtual const char* AppMesh::getName (bool allowFixed = true) pure virtual
Implemented in ColladaAppMesh.
virtual F32 AppMesh::getVisValue (F32 time) pure virtual
Implemented in ColladaAppMesh.
virtual bool AppMesh::isBillboard () virtual
Referenced by animatesFrame().
virtual bool AppMesh::isBillboardZAxis () virtual
Referenced by animatesFrame().
virtual bool AppMesh::isSkin () inline virtual
Reimplemented in ColladaAppMesh.
References lookupSkinData().
virtual void AppMesh::lockMesh (F32 t, const MatrixF & objOffset) inline virtual
Reimplemented in ColladaAppMesh.
virtual void AppMesh::lookupSkinData () pure virtual
Implemented in ColladaAppMesh.
Referenced by isSkin().
Member Data Documentation
Vector<AppMaterial*> AppMesh::appMaterials static
Vector<S32> AppMesh::boneIndex
Vector<AppNode*> AppMesh::bones
Vector<ColorI> AppMesh::colors
S32 AppMesh::detailSize
U32 AppMesh::flags
Vector<U32> AppMesh::indices
Vector<Point3F> AppMesh::initialNorms
Vector<MatrixF> AppMesh::initialTransforms
Vector<Point3F> AppMesh::initialVerts
Vector<S32> AppMesh::nodeIndex
Vector<Point3F> AppMesh::normals
S32 AppMesh::numFrames
S32 AppMesh::numMatFrames
MatrixF AppMesh::objectOffset
Vector<Point3F> AppMesh::points
Vector<TSDrawPrimitive> AppMesh::primitives
Vector<Point2F> AppMesh::uv2s
Vector<Point2F> AppMesh::uvs
Vector<S32> AppMesh::vertexIndex
U32 AppMesh::vertsPerFrame
Vector<F32> AppMesh::weight
Copyright © GarageGames, LLC. All Rights Reserved.