CatmullRomBase Class Reference
Main Modules Class List Namespace List Online
CatmullRomBase Class Reference abstract
The shared base class used by the catmull rom interpolation template class.
#include <util/catmullRom.h>
Public Member Functions
F32 arcLength (F32 t1, F32 t2)
Find length of curve between parameters t1 and t2.
virtual void clear ()
Clean out all the data.
F32 getLength ()
Get the total length of the curve.
U32 getPrevNode (F32 t)
Get the closest previous control point to time t.
F32 getTime (U32 idx)
Returns the time at idx (rather than at a F32 time)
virtual F32 segmentArcLength (U32 i, F32 u1, F32 u2)=0
Find length of curve segment between parameters u1 and u2.
Protected Member Functions
CatmullRomBase ()
virtual ~CatmullRomBase ()
void _initialize (U32 count, const F32 *times=NULL)
Protected Attributes
U32 mCount
The number of points and times.
F32 * mLengths
the length of each curve segment.
F32 * mTimes
The time to arrive at each point.
F32 mTotalLength
The total length of curve.
Static Protected Attributes
static const F32 smC []
static const F32 smX []
Detailed Description
The shared base class used by the catmull rom interpolation template class.
See also
CatmullRom
Constructor & Destructor Documentation
CatmullRomBase::CatmullRomBase () protected
virtual CatmullRomBase::~CatmullRomBase () inline protected virtual
References arcLength(), and clear().
Member Function Documentation
void CatmullRomBase::_initialize (U32 count, const F32 * times = NULL) protected
Referenced by CatmullRom< TYPE >::initialize().
F32 CatmullRomBase::arcLength (F32 t1, F32 t2)
Find length of curve between parameters t1 and t2.
Referenced by ~CatmullRomBase().
virtual void CatmullRomBase::clear () virtual
Clean out all the data.
Reimplemented in CatmullRom< TYPE >.
Referenced by CatmullRom< TYPE >::clear(), and ~CatmullRomBase().
F32 CatmullRomBase::getLength () inline
Get the total length of the curve.
References getPrevNode(), getTime(), mTotalLength, and segmentArcLength().
U32 CatmullRomBase::getPrevNode (F32 t)
Get the closest previous control point to time t.
Referenced by getLength().
F32 CatmullRomBase::getTime (U32 idx)
Returns the time at idx (rather than at a F32 time)
Referenced by getLength().
virtual F32 CatmullRomBase::segmentArcLength (U32 i, F32 u1, F32 u2) pure virtual
Find length of curve segment between parameters u1 and u2.
Implemented in CatmullRom< TYPE >.
Referenced by getLength().
Member Data Documentation
U32 CatmullRomBase::mCount protected
The number of points and times.
Referenced by CatmullRom< TYPE >::acceleration(), CatmullRom< TYPE >::evaluate(), CatmullRom< TYPE >::getPosition(), CatmullRom< TYPE >::segmentArcLength(), and CatmullRom< TYPE >::velocity().
F32* CatmullRomBase::mLengths protected
the length of each curve segment.
F32* CatmullRomBase::mTimes protected
The time to arrive at each point.
Referenced by CatmullRom< TYPE >::acceleration(), CatmullRom< TYPE >::evaluate(), and CatmullRom< TYPE >::velocity().
F32 CatmullRomBase::mTotalLength protected
The total length of curve.
Referenced by getLength().
const F32 CatmullRomBase::smC[] static protected
Referenced by CatmullRom< TYPE >::segmentArcLength().
const F32 CatmullRomBase::smX[] static protected
Referenced by CatmullRom< TYPE >::segmentArcLength().
Copyright © GarageGames, LLC. All Rights Reserved.