Resource< T > Class Template Reference
Main Modules Class List Namespace List Online
Resource< T > Class Template Reference
#include <core/resource.h>
Public Member Functions
Resource ()
Resource (const ResourceBase &base)
operator const T * () const
operator T * ()
T & operator* ()
const T & operator* () const
T * operator-> ()
const T * operator-> () const
void operator= (const ResourceBase &base)
void setResource (const ResourceBase &base, void *resource)
Public Member Functions inherited from ResourceBase
ResourceBase (Header *header)
virtual ~ResourceBase ()
U32 getChecksum () const
const Torque::Path & getPath () const
Static Public Member Functions
static Signal< bool(const Torque::Path &, void **)> & getLoadSignal ()
Registering with this signal will give an opportunity to handle resource creation before calling the create() function.
static Signal< void(Resource< T > &) > & getPostLoadSignal ()
Register with this signal to get notified when resources of this type have been loaded.
static Signal< void(const Torque::Path &, T *) > & getUnloadSignal ()
Register with this signal to get notified when resources of this type are about to get unloaded.
static Signature signature ()
Additional Inherited Members
Public Types inherited from ResourceBase
typedef U32 Signature
Protected Types inherited from ResourceBase
typedef void(* NotifyUnloadFn) (const Torque::Path &path, void *resource)
Protected Member Functions inherited from ResourceBase
ResourceBase ()
void assign (const ResourceBase &inResource, void *resource=NULL)
Protected Attributes inherited from ResourceBase
StrongRefPtr< Header > mResourceHeader
Static Protected Attributes inherited from ResourceBase
static Header smBlank
Constructor & Destructor Documentation
template<class T> Resource< T >::Resource () inline
template<class T> Resource< T >::Resource (const ResourceBase & base) inline
Member Function Documentation
template<class T> static Signal<bool(const Torque::Path &, void**)>& Resource< T >::getLoadSignal () inline static
Registering with this signal will give an opportunity to handle resource creation before calling the create() function.
This may be used to handle file extensions differently and allow a more plugin-like approach to adding resources. Using this mechanism, one could, for example, override the default methods for loading DTS without touching the main source.
Referenced by ResourceRegisterLoadSignal< T >::ResourceRegisterLoadSignal().
template<class T> static Signal< void(Resource< T >&) >& Resource< T >::getPostLoadSignal () inline static
Register with this signal to get notified when resources of this type have been loaded.
Referenced by ResourceRegisterPostLoadSignal< TSShape >::ResourceRegisterPostLoadSignal().
template<class T> static Signal< void(const Torque::Path&, T*) >& Resource< T >::getUnloadSignal () inline static
Register with this signal to get notified when resources of this type are about to get unloaded.
Referenced by ResourceRegisterUnloadSignal< TSShape >::ResourceRegisterUnloadSignal().
template<class T> Resource< T >::operator const T * () const inline
template<class T> Resource< T >::operator T * () inline
template<class T> T& Resource< T >::operator* (void) inline
template<class T> const T& Resource< T >::operator* (void) const inline
template<class T> T* Resource< T >::operator-> (void) inline
template<class T> const T* Resource< T >::operator-> (void) const inline
template<class T> void Resource< T >::operator= (const ResourceBase & base) inline
template<class T> void Resource< T >::setResource (const ResourceBase & base, void * resource) inline
template<class T> static Signature Resource< T >::signature () static
Referenced by Resource< TSShape >::getUnloadSignal().
Copyright © GarageGames, LLC. All Rights Reserved.