FrameAllocatorMarker Class Reference
Main Modules Class List Namespace List Online
FrameAllocatorMarker Class Reference
Helper class to deal with FrameAllocator usage.
#include <core/frameAllocator.h>
Public Member Functions
FrameAllocatorMarker ()
~FrameAllocatorMarker ()
void * alloc (const U32 allocSize) const
template<typename T >
T * alloc (const U32 numElements) const
Detailed Description
Helper class to deal with FrameAllocator usage.
The purpose of this class is to make it simpler and more reliable to use the FrameAllocator. Simply use it like this:
FrameAllocatorMarker mem;
char *buff = (char*)mem.alloc(100);
When you leave the scope you defined the FrameAllocatorMarker in, it will automatically restore the watermark on the FrameAllocator. In situations with complex branches, this can be a significant headache remover, as you don't have to remember to reset the FrameAllocator on every posssible branch.
Constructor & Destructor Documentation
FrameAllocatorMarker::FrameAllocatorMarker () inline
References FrameAllocator::getWaterMark().
FrameAllocatorMarker::~FrameAllocatorMarker () inline
References FrameAllocator::setWaterMark().
Member Function Documentation
void* FrameAllocatorMarker::alloc (const U32 allocSize) const inline
References FrameAllocator::alloc().
template<typename T > T* FrameAllocatorMarker::alloc (const U32 numElements) const inline
References FrameAllocator::alloc(), and T.
Copyright © GarageGames, LLC. All Rights Reserved.