TransformF Class Reference
Main Modules Class List Namespace List Online
TransformF Class Reference
A transform expressed as a combination of a position vector and an angular orientation.
#include <math/mTransform.h>
Public Member Functions
TransformF ()
TransformF (const Point3F &position, const AngAxisF &orientation)
TransformF (const MatrixF &mat)
MatrixF getMatrix () const
const AngAxisF & getOrientation () const
REturn the orientation of the transform.
const Point3F & getPosition () const
Return the position vector of the transform.
bool hasRotation () const
void set (const Point3F &position, const AngAxisF &orientation)
void set (const MatrixF &mat)
Public Attributes
bool mHasRotation
AngAxisF mOrientation
Point3F mPosition
Static Public Attributes
static const TransformF Identity
Detailed Description
A transform expressed as a combination of a position vector and an angular orientation.
Constructor & Destructor Documentation
TransformF::TransformF () inline
TransformF::TransformF (const Point3F & position, const AngAxisF & orientation) inline
TransformF::TransformF (const MatrixF & mat) inline
Member Function Documentation
MatrixF TransformF::getMatrix () const inline
References AngAxisF::setMatrix(), and MatrixF::setPosition().
const AngAxisF& TransformF::getOrientation () const inline
REturn the orientation of the transform.
References mOrientation.
const Point3F& TransformF::getPosition () const inline
Return the position vector of the transform.
References mPosition.
bool TransformF::hasRotation () const inline
References mHasRotation.
void TransformF::set (const Point3F & position, const AngAxisF & orientation) inline
void TransformF::set (const MatrixF & mat) inline
References AngAxisF::set().
Member Data Documentation
const TransformF TransformF::Identity static
Referenced by TSShapeConstructor::getShapePath().
bool TransformF::mHasRotation
Referenced by hasRotation().
AngAxisF TransformF::mOrientation
Referenced by getOrientation().
Point3F TransformF::mPosition
Referenced by getPosition().
Copyright © GarageGames, LLC. All Rights Reserved.