SceneManager Class Reference
Main Modules Class List Namespace List Online
SceneManager Class Reference
An object that manages the SceneObjects belonging to a scene.
#include <scene/sceneManager.h>
Public Types
typedef Signal< void(SceneManager *, const SceneRenderState *) > RenderSignal
A signal used to notify of render passes.
Public Member Functions
SceneManager (bool isClient)
~SceneManager ()
SceneContainer * getContainer () const
Return the SceneContainer for this scene.
const MatrixF & getNonClipProjection () const
const SceneZoneSpaceManager * getZoneManager () const
Return the manager for the zones in this scene.
SceneZoneSpaceManager * getZoneManager ()
void setNonClipProjection (const MatrixF &proj)
SceneObject Management
bool addObjectToScene (SceneObject *object)
Add the given object to the scene.
void removeObjectFromScene (SceneObject *object)
Remove the given object from the scene.
void notifyObjectDirty (SceneObject *object)
Let the scene manager know that the given object has changed its transform or sizing state.
Networking
void scopeScene (CameraScopeQuery *query, NetConnection *netConnection)
Set the scoping states of the objects in the scene.
Fog/Visibility Management
void setPostEffectFog (bool enable)
bool usePostEffectFog () const
const FogData & getFogData ()
Accessor for the FogData structure.
void setFogData (const FogData &data)
Sets the FogData structure.
const WaterFogData & getWaterFogData ()
Accessor for the WaterFogData structure.
void setWaterFogData (const WaterFogData &data)
Sets the WaterFogData structure.
void setVisibleDistance (F32 dist)
Used by LevelInfo to set the default visible distance for rendering the scene.
F32 getVisibleDistance ()
Returns the default visible distance for the scene.
void setVisibleGhostDistance (F32 dist)
F32 getVisibleGhostDistance ()
void setNearClip (F32 nearClip)
Used by LevelInfo to set the default near clip plane for rendering the scene.
F32 getNearClip ()
Returns the default near clip distance for the scene.
dtr Display Target Resolution
Some rendering must be targeted at a specific display resolution.
This display resolution is distinct from the current RT's size (such as when rendering a reflection to a texture, for instance) so we store the size at which we're going to display the results of the current render.
void setDisplayTargetResolution (const Point2I &size)
const Point2I & getDisplayTargetResolution () const
Public Attributes
Vector< SceneObject * > mRenderedObjectsList
Static Public Attributes
static bool smLockDiffuseFrustum
If true use the last stored locked frustum for culling the diffuse render pass.
static bool smRenderBoundingBoxes
If true, render the AABBs of objects for debugging.
Protected Attributes
SceneRenderState * mCurrentRenderState
The currently active render state or NULL if we're not in the process of rendering.
Point2I mDisplayTargetResolution
FogData mFogData
bool mIsClient
Whether this is the client-side scene.
F32 mNearClip
MatrixF mNonClipProj
bool mUsePostEffectFog
F32 mVisibleDistance
F32 mVisibleGhostDistance
WaterFogData mWaterFogData
SceneZoneSpaceManager * mZoneManager
Manager for the zones in this scene.
Static Protected Attributes
static SceneCameraState smLockedDiffuseCamera
The stored last diffuse pass frustum for locking the cull.
Lighting
typedef InterpolatedChangeProperty< ColorF > AmbientLightInterpolator
LightManager * mLightManager
Light manager that is active for the scene.
AmbientLightInterpolator mAmbientLightColor
Global ambient light level in the scene.
bool _setLightManager (LightManager *lm)
Deactivates the previous light manager and activates the new one.
bool setLightManager (const char *lmName)
Finds the light manager by name and activates it.
const ColorF & getAmbientLightColor () const
Return the current global ambient light color.
void setAmbientLightTransitionTime (SimTime time)
Set the time it takes for a new ambient light color to take full effect.
void setAmbientLightTransitionCurve (const EaseF &ease)
Set the interpolation curve to use for blending from one global ambient light color to a different one.
Rendering
RenderPassManager * mDefaultRenderPass
RenderPassManager for the default render pass.
Vector< SceneObject * > mBatchQueryList
void _renderScene (SceneRenderState *state, U32 objectMask=(U32)-1, SceneZoneSpace *baseObject=NULL, U32 baseZone=0)
Render scene using the given state.
static void _batchObjectCallback (SceneObject *object, void *key)
Callback for the container query.
RenderPassManager * getDefaultRenderPass () const
Return the default RenderPassManager for the scene.
void setDefaultRenderPass (RenderPassManager *rpm)
Set the default render pass for the scene.
void renderScene (ScenePassType passType, U32 objectMask=DEFAULT_RENDER_TYPEMASK)
Render the scene with the default render pass.
void renderScene (SceneRenderState *state, U32 objectMask=DEFAULT_RENDER_TYPEMASK, SceneZoneSpace *baseObject=NULL, U32 baseZone=0)
Render the scene with a custom rendering pass.
void renderSceneNoLights (SceneRenderState *state, U32 objectMask=DEFAULT_RENDER_TYPEMASK, SceneZoneSpace *baseObject=NULL, U32 baseZone=0)
Render the scene with a custom rendering pass and no lighting set up.
SceneRenderState * getCurrentRenderState () const
Returns the currently active scene state or NULL if no state is currently active.
static RenderSignal & getPreRenderSignal ()
static RenderSignal & getPostRenderSignal ()
Detailed Description
An object that manages the SceneObjects belonging to a scene.
Member Typedef Documentation
typedef InterpolatedChangeProperty< ColorF > SceneManager::AmbientLightInterpolator protected
typedef Signal< void(SceneManager*, const SceneRenderState*) > SceneManager::RenderSignal
A signal used to notify of render passes.
Constructor & Destructor Documentation
SceneManager::SceneManager (bool isClient)
SceneManager::~SceneManager ()
Member Function Documentation
static void SceneManager::_batchObjectCallback (SceneObject * object, void * key) static protected
Callback for the container query.
void SceneManager::_renderScene (SceneRenderState * state, U32 objectMask = (U32)-1, SceneZoneSpace * baseObject = NULL, U32 baseZone = 0) protected
Render scene using the given state.
Parameters
state SceneManager render state.
objectMask Object type mask with which to filter scene objects.
baseObject Zone manager to start traversal in. If null, the zone manager that contains state's camera position will be used.
baseZone Zone in zone manager in which to start traversal. Ignored if baseObject is NULL.
bool SceneManager::_setLightManager (LightManager * lm) protected
Deactivates the previous light manager and activates the new one.
bool SceneManager::addObjectToScene (SceneObject * object)
Add the given object to the scene.
Referenced by getZoneManager().
const ColorF& SceneManager::getAmbientLightColor () const inline
Return the current global ambient light color.
References InterpolatedChangeProperty< T, TimeSource >::getCurrentValue().
SceneContainer* SceneManager::getContainer () const inline
Return the SceneContainer for this scene.
SceneRenderState* SceneManager::getCurrentRenderState () const inline
Returns the currently active scene state or NULL if no state is currently active.
References mCurrentRenderState.
RenderPassManager* SceneManager::getDefaultRenderPass () const
Return the default RenderPassManager for the scene.
Referenced by getZoneManager().
const Point2I& SceneManager::getDisplayTargetResolution () const
Referenced by getNearClip().
const FogData& SceneManager::getFogData () inline
Accessor for the FogData structure.
References mFogData.
Referenced by SceneData::init().
F32 SceneManager::getNearClip () inline
Returns the default near clip distance for the scene.
References getDisplayTargetResolution(), mNearClip, and setDisplayTargetResolution().
const MatrixF& SceneManager::getNonClipProjection () const inline
References mNonClipProj.
static RenderSignal& SceneManager::getPostRenderSignal () inline static
References setLightManager().
static RenderSignal& SceneManager::getPreRenderSignal () inline static
F32 SceneManager::getVisibleDistance () inline
Returns the default visible distance for the scene.
References mVisibleDistance.
F32 SceneManager::getVisibleGhostDistance () inline
References mVisibleGhostDistance.
const WaterFogData& SceneManager::getWaterFogData () inline
Accessor for the WaterFogData structure.
References mWaterFogData.
const SceneZoneSpaceManager* SceneManager::getZoneManager () const inline
Return the manager for the zones in this scene.
Note
Only client scenes have a zone manager as for the server, no zoning data is kept.
References mZoneManager.
SceneZoneSpaceManager* SceneManager::getZoneManager () inline
References addObjectToScene(), getDefaultRenderPass(), mZoneManager, notifyObjectDirty(), and removeObjectFromScene().
void SceneManager::notifyObjectDirty (SceneObject * object)
Let the scene manager know that the given object has changed its transform or sizing state.
Referenced by getZoneManager().
void SceneManager::removeObjectFromScene (SceneObject * object)
Remove the given object from the scene.
Referenced by getZoneManager().
void SceneManager::renderScene (ScenePassType passType, U32 objectMask = DEFAULT_RENDER_TYPEMASK)
Render the scene with the default render pass.
Note
This uses the current GFX state (transforms, viewport, frustum) to initialize the render state.
Referenced by setDefaultRenderPass().
void SceneManager::renderScene (SceneRenderState * state, U32 objectMask = DEFAULT_RENDER_TYPEMASK, SceneZoneSpace * baseObject = NULL, U32 baseZone = 0)
Render the scene with a custom rendering pass.
void SceneManager::renderSceneNoLights (SceneRenderState * state, U32 objectMask = DEFAULT_RENDER_TYPEMASK, SceneZoneSpace * baseObject = NULL, U32 baseZone = 0)
Render the scene with a custom rendering pass and no lighting set up.
Referenced by setDefaultRenderPass().
void SceneManager::scopeScene (CameraScopeQuery * query, NetConnection * netConnection)
Set the scoping states of the objects in the scene.
Referenced by setAmbientLightTransitionCurve().
void SceneManager::setAmbientLightTransitionCurve (const EaseF & ease) inline
Set the interpolation curve to use for blending from one global ambient light color to a different one.
References scopeScene(), and InterpolatedChangeProperty< T, TimeSource >::setTransitionCurve().
void SceneManager::setAmbientLightTransitionTime (SimTime time) inline
Set the time it takes for a new ambient light color to take full effect.
References InterpolatedChangeProperty< T, TimeSource >::setTransitionTime().
void SceneManager::setDefaultRenderPass (RenderPassManager * rpm) inline
Set the default render pass for the scene.
References renderScene(), and renderSceneNoLights().
void SceneManager::setDisplayTargetResolution (const Point2I & size)
Referenced by getNearClip().
void SceneManager::setFogData (const FogData & data) inline
Sets the FogData structure.
bool SceneManager::setLightManager (const char * lmName)
Finds the light manager by name and activates it.
Referenced by getPostRenderSignal().
void SceneManager::setNearClip (F32 nearClip) inline
Used by LevelInfo to set the default near clip plane for rendering the scene.
See also
GameProcessCameraQuery
LevelInfo
void SceneManager::setNonClipProjection (const MatrixF & proj) inline
void SceneManager::setPostEffectFog (bool enable) inline
void SceneManager::setVisibleDistance (F32 dist) inline
Used by LevelInfo to set the default visible distance for rendering the scene.
Note this should not be used to alter culling which is controlled by the active frustum when a SceneRenderState is created.
See also
SceneRenderState
GameProcessCameraQuery
LevelInfo
void SceneManager::setVisibleGhostDistance (F32 dist) inline
void SceneManager::setWaterFogData (const WaterFogData & data) inline
Sets the WaterFogData structure.
bool SceneManager::usePostEffectFog () const inline
References mUsePostEffectFog.
Member Data Documentation
AmbientLightInterpolator SceneManager::mAmbientLightColor protected
Global ambient light level in the scene.
Vector< SceneObject* > SceneManager::mBatchQueryList protected
SceneRenderState* SceneManager::mCurrentRenderState protected
The currently active render state or NULL if we're not in the process of rendering.
Referenced by getCurrentRenderState().
RenderPassManager* SceneManager::mDefaultRenderPass mutable protected
RenderPassManager for the default render pass.
This is set up in script and looked up by getDefaultRenderPass().
Point2I SceneManager::mDisplayTargetResolution protected
See also
setDisplayTargetResolution
FogData SceneManager::mFogData protected
Referenced by getFogData().
bool SceneManager::mIsClient protected
Whether this is the client-side scene.
LightManager* SceneManager::mLightManager protected
Light manager that is active for the scene.
F32 SceneManager::mNearClip protected
Referenced by getNearClip().
MatrixF SceneManager::mNonClipProj protected
Referenced by getNonClipProjection().
Vector< SceneObject* > SceneManager::mRenderedObjectsList
bool SceneManager::mUsePostEffectFog protected
Referenced by usePostEffectFog().
F32 SceneManager::mVisibleDistance protected
Referenced by getVisibleDistance().
F32 SceneManager::mVisibleGhostDistance protected
Referenced by getVisibleGhostDistance().
WaterFogData SceneManager::mWaterFogData protected
Referenced by getWaterFogData().
SceneZoneSpaceManager* SceneManager::mZoneManager protected
Manager for the zones in this scene.
Referenced by getZoneManager().
bool SceneManager::smLockDiffuseFrustum static
If true use the last stored locked frustum for culling the diffuse render pass.
See also
smLockedDiffuseFrustum
SceneCameraState SceneManager::smLockedDiffuseCamera static protected
The stored last diffuse pass frustum for locking the cull.
bool SceneManager::smRenderBoundingBoxes static
If true, render the AABBs of objects for debugging.
Copyright © GarageGames, LLC. All Rights Reserved.