MaterialParameterHandle Class Reference
Main Modules Class List Namespace List Online
MaterialParameterHandle Class Reference abstract
Similar class to GFXShaderConsts, but this is to describe generic material parameters.
#include <materials/materialParameters.h>
Public Member Functions
virtual ~MaterialParameterHandle ()
virtual const String & getName () const =0
virtual S32 getSamplerRegister (U32 pass) const =0
Returns -1 if this handle does not point to a Sampler.
virtual bool isValid () const =0
Detailed Description
Similar class to GFXShaderConsts, but this is to describe generic material parameters.
Constructor & Destructor Documentation
virtual MaterialParameterHandle::~MaterialParameterHandle () inline virtual
References getName(), getSamplerRegister(), and isValid().
Member Function Documentation
virtual const String& MaterialParameterHandle::getName () const pure virtual
Implemented in ShaderMaterialParameterHandle.
Referenced by ~MaterialParameterHandle().
virtual S32 MaterialParameterHandle::getSamplerRegister (U32 pass) const pure virtual
Returns -1 if this handle does not point to a Sampler.
Implemented in ShaderMaterialParameterHandle.
Referenced by ~MaterialParameterHandle().
virtual bool MaterialParameterHandle::isValid () const pure virtual
Implemented in ShaderMaterialParameterHandle.
Referenced by MaterialParameters::setSafe(), and ~MaterialParameterHandle().
Copyright © GarageGames, LLC. All Rights Reserved.