AbstractClassRep Class Reference
Main Modules Class List Namespace List Online
AbstractClassRep Class Reference abstract
Core functionality for class manipulation.
#include <console/consoleObject.h>
Classes
struct Field
Public Types
typedef ConsoleBaseType Parent
typedef void(* WriteCustomTamlSchema) (const AbstractClassRep *pClassRep, TiXmlElement *pParentElement)
Allows the writing of a custom TAML schema.
Public Member Functions
bool isRenderEnabled () const
bool isSelectionEnabled () const
Public Member Functions inherited from ConsoleBaseType
const char * getDocString () const
Return the documentation string for this type.
const EngineEnumTable * getEnumTable () const
Return the EnumTable for this type (only for enumeration types).
const char * getInspectorFieldType ()
Return the name of the GuiInspectorField subclass that fields of this type should use for editing.
S32 getTypeID () const
Return the unique numeric ID of this type.
const EngineTypeInfo * getTypeInfo () const
Return the type info for the engine type corresponding to this console type or NULL if there is no mapping for the console type.
StringTableEntry getTypeName () const
Return the console type name (TypeXXX).
S32 getTypeSize () const
Return the size of a single value in bytes.
void setInspectorFieldType (const char *type)
Set the name of the GuiInspectorField subclass that fields of this type should use for editing.
virtual void setData (void *dptr, S32 argc, const char **argv, const EnumTable *tbl, BitSet32 flag)=0
virtual const char * getData (void *dptr, const EnumTable *tbl, BitSet32 flag)=0
virtual const char * getTypeClassName ()=0
virtual const bool isDatablock ()
Return true if this is datablock object type.
virtual const char * prepData (const char *data, char *buffer, U32 bufferLen)
virtual StringTableEntry getTypePrefix (void) const
ConsoleBaseType * getListNext () const
Get the item that follows this item in the list.
Public Attributes
bool mIsRenderEnabled
bool mIsSelectionEnabled
'Tructors
AbstractClassRep (S32 *conIdPtr, const char *typeName)
Representation Interface
S32 mClassGroupMask
Mask indicating in which NetGroups this object belongs.
S32 mClassType
Stores the NetClass of this class.
S32 mNetEventDir
Stores the NetDirection of this class.
S32 mClassId [NetClassGroupsCount]
Stores the IDs assigned to this class for each group.
S32 mClassSizeof
Size of instances in bytes.
const char * mClassName
AbstractClassRep * nextClass
AbstractClassRep * parentClass
Namespace * mNamespace
S32 getClassId (U32 netClassGroup) const
AbstractClassRep * getCommonParent (const AbstractClassRep *otherClass) const
StringTableEntry getClassName () const
Return the name of this class.
Namespace * getNameSpace () const
Return the namespace that contains the methods of this class.
AbstractClassRep * getParentClass () const
Return the AbstractClassRep of the class that this class is derived from.
virtual AbstractClassRep * getContainerChildClass (const bool recurse)=0
virtual WriteCustomTamlSchema getCustomTamlSchema (void)=0
S32 getSizeof () const
Return the size of instances of this class in bytes.
AbstractClassRep * getNextClass () const
Return the next class in the global class list link chain.
bool isSubclassOf (const AbstractClassRep *klass) const
Helper class to see if we are a given class, or a subclass thereof by comparing AbstractClassRep pointers.
bool isSubclassOf (const char *klass) const
Helper class to see if we are a given class, or a subclass thereof by comparing the class name strings.
bool isClass (const AbstractClassRep *acr) const
virtual ConsoleObject * create () const =0
AbstractClassRep * findFieldRoot (StringTableEntry fieldName)
static U32 getClassCRC (U32 netClassGroup)
static AbstractClassRep * getClassList ()
Return the head of the global class list.
virtual void init ()
Categories
const char * mCategory
const char * mDescription
const char * getCategory () const
Return the space separated category path for the class.
const char * getDescription () const
Return a short description string suitable for displaying in tooltips.
Fields
enum ACRFieldTypes : U32 {
ARCFirstCustomField = 0xFFFFFFFB,
StartArrayFieldType = 0xFFFFFFFB,
EndArrayFieldType = 0xFFFFFFFC,
StartGroupFieldType = 0xFFFFFFFD,
EndGroupFieldType = 0xFFFFFFFE,
DeprecatedFieldType = 0xFFFFFFFF
}
These are special field type values used to mark groups and arrays in the field list.
enum FieldFlags {
FIELD_HideInInspectors = BIT(0),
FIELD_ComponentInspectors = BIT(1)
}
typedef bool(* SetDataNotify) (void *obj, const char *array, const char *data)
This is a function pointer typedef to support get/set callbacks for fields.
typedef const char *(* GetDataNotify) (void *obj, const char *data)
typedef bool(* WriteDataNotify) (void *obj, StringTableEntry pFieldName)
This is a function pointer typedef to support optional writing for fields.
typedef Vector< Field > FieldList
FieldList mFieldList
bool mDynamicGroupExpand
const Field * findField (StringTableEntry fieldName) const
Console Type Interface
virtual void * getNativeVariable ()
Allocate a single value.
virtual void deleteNativeVariable (void *var)
Delete a single value allocated with getNativeVariable().
Abstract Class Database
static AbstractClassRep ** classTable [NetClassGroupsCount][NetClassTypesCount]
static AbstractClassRep * classLinkList
static U32 classCRC [NetClassGroupsCount]
static bool initialized
static U32 NetClassCount [NetClassGroupsCount][NetClassTypesCount]
static U32 NetClassBitSize [NetClassGroupsCount][NetClassTypesCount]
static void registerClassRep (AbstractClassRep *)
static AbstractClassRep * findClassRep (const char *in_pClassName)
static AbstractClassRep * findClassRep (U32 groupId, U32 typeId, U32 classId)
static void removeClassRep (AbstractClassRep *)
static void initialize ()
static void shutdown ()
static ConsoleObject * create (const char *in_pClassName)
static ConsoleObject * create (const U32 groupId, const U32 typeId, const U32 in_classId)
Additional Inherited Members
Static Public Member Functions inherited from ConsoleBaseType
static ConsoleBaseType * getType (const S32 typeID)
Call me to get a pointer to a type's info.
static ConsoleBaseType * getTypeByClassName (const char *typeName)
static ConsoleBaseType * getTypeByName (const char *typeName)
Call to get a pointer to a type's info.
static void initialize ()
Called once to initialize the console type system.
static ConsoleBaseType * getListHead ()
Get the head of the list.
Protected Member Functions inherited from ConsoleBaseType
ConsoleBaseType (const S32 size, S32 *idPtr, const char *aTypeName)
The constructor is responsible for linking an element into the master list, registering the type ID, etc.
~ConsoleBaseType ()
Destructor is private to avoid people mucking up the list.
Protected Attributes inherited from ConsoleBaseType
const char * mInspectorFieldType
Name of GuiInspectorField subclass to instantiate for field edit controls in inspectors.
ConsoleBaseType * mListNext
Next item in the list of all console types.
S32 mTypeID
Unique numeric type ID.
const EngineTypeInfo * mTypeInfo
Type info object for the engine type corresponding to this console type.
StringTableEntry mTypeName
Name of this console type (TypeXXX).
dsize_t mTypeSize
Size of a single data value point.
Static Protected Attributes inherited from ConsoleBaseType
static S32 smConsoleTypeCount
Total number of defined console types. This is used to generate unique IDs for each type.
static ConsoleBaseType * smListHead
We maintain a linked list of all console types; this is its head.
Detailed Description
Core functionality for class manipulation.
Introduction (or, Why AbstractClassRep?)
Many of Torque's subsystems, especially network, console, and sim, require the ability to programatically instantiate classes. For instance, when objects are ghosted, the networking layer needs to be able to create an instance of the object on the client. When the console scripting language runtime encounters the "new" keyword, it has to be able to fill that request.
Since standard C++ doesn't provide a function to create a new instance of an arbitrary class at runtime, one must be created. This is what AbstractClassRep and ConcreteClassRep are all about. They allow the registration and instantiation of arbitrary classes at runtime.
In addition, ACR keeps track of the fields (registered via addField() and co.) of a class, allowing programmatic access of class fields.
See also
ConsoleObject
Note
In general, you will only access the functionality implemented in this class via ConsoleObject::create(). Most of the time, you will only ever need to use this part part of the engine indirectly - ie, you will use the networking system or the console, or ConsoleObject, and they will indirectly use this code. The following discussion is really only relevant for advanced engine users.
NetClasses and Class IDs
Torque supports a notion of group, type, and direction for objects passed over the network. Class IDs are assigned sequentially per-group, per-type, so that, for instance, the IDs assigned to Datablocks are seperate from the IDs assigned to NetObjects or NetEvents. This can translate into significant bandwidth savings (especially since the size of the fields for transmitting these bits are determined at run-time based on the number of IDs given out.
AbstractClassRep Internals
Much like ConsoleConstructor, ACR does some preparatory work at runtime before execution is passed to main(). In actual fact, this preparatory work is done by the ConcreteClassRep template. Let's examine this more closely.
If we examine ConsoleObject, we see that two macros must be used in the definition of a properly integrated objects. From the ConsoleObject example:
     // This is from inside the class definition...
     DECLARE_CONOBJECT(TorqueObject);
// And this is from outside the class definition...
IMPLEMENT_CONOBJECT(TorqueObject);
What do these things actually do?
Not all that much, in fact. They expand to code something like this:
// This is from inside the class definition...
static ConcreteClassRep<TorqueObject> dynClassRep;
static AbstractClassRep* getParentStaticClassRep();
static AbstractClassRep* getStaticClassRep();
virtual AbstractClassRep* getClassRep() const;
// And this is from outside the class definition...
AbstractClassRep* TorqueObject::getClassRep() const { return &TorqueObject::dynClassRep; }
AbstractClassRep* TorqueObject::getStaticClassRep() { return &dynClassRep; }
AbstractClassRep* TorqueObject::getParentStaticClassRep() { return Parent::getStaticClassRep(); }
ConcreteClassRep<TorqueObject> TorqueObject::dynClassRep("TorqueObject", 0, -1, 0);
As you can see, getClassRep(), getStaticClassRep(), and getParentStaticClassRep() are just accessors to allow access to various ConcreteClassRep instances. This is where the Parent typedef comes into play as well - it lets getParentStaticClassRep() get the right class rep.
In addition, dynClassRep is declared as a member of TorqueObject, and defined later on. Much like ConsoleConstructor, ConcreteClassReps add themselves to a global linked list in their constructor.
Then, when AbstractClassRep::initialize() is called, from Con::init(), we iterate through the list and perform the following tasks:
Sets up a Namespace for each class.
Call the init() method on each ConcreteClassRep. This method:
Links namespaces between parent and child classes, using Con::classLinkNamespaces.
Calls initPersistFields() and consoleInit().
As a result of calling initPersistFields, the field list for the class is populated.
Assigns network IDs for classes based on their NetGroup membership. Determines bit allocations for network ID fields.
Member Typedef Documentation
typedef Vector<Field> AbstractClassRep::FieldList
typedef const char*(* AbstractClassRep::GetDataNotify) (void *obj, const char *data)
typedef ConsoleBaseType AbstractClassRep::Parent
typedef bool(* AbstractClassRep::SetDataNotify) (void *obj, const char *array, const char *data)
This is a function pointer typedef to support get/set callbacks for fields.
typedef void(* AbstractClassRep::WriteCustomTamlSchema) (const AbstractClassRep *pClassRep, TiXmlElement *pParentElement)
Allows the writing of a custom TAML schema.
typedef bool(* AbstractClassRep::WriteDataNotify) (void *obj, StringTableEntry pFieldName)
This is a function pointer typedef to support optional writing for fields.
Member Enumeration Documentation
enum AbstractClassRep::ACRFieldTypes : U32
These are special field type values used to mark groups and arrays in the field list.
See also
Field::type
addArray, endArray
addGroup, endGroup
addGroup, endGroup
addDeprecatedField
Enumerator
ARCFirstCustomField
The first custom field type...
all fields types greater or equal to this one are not console data types.
StartArrayFieldType
Marks the start of a fixed size array of fields.
See also
addArray
EndArrayFieldType
Marks the end of a fixed size array of fields.
See also
endArray
StartGroupFieldType
Marks the beginning of a group of fields.
See also
addGroup
EndGroupFieldType
Marks the beginning of a group of fields.
See also
endGroup
DeprecatedFieldType
Marks a field that is depreciated and no longer stores a value.
See also
addDeprecatedField
enum AbstractClassRep::FieldFlags
Enumerator
FIELD_HideInInspectors
Do not show the field in inspectors.
FIELD_ComponentInspectors
Custom fields used by components.
They are likely to be non-standard size/configuration, so They are handled specially
Constructor & Destructor Documentation
AbstractClassRep::AbstractClassRep (S32 * conIdPtr, const char * typeName) inline
Parameters
conIdPtr Pointer to the static S32 console ID.
conTypeName Console type name.
References mFieldList, mIsRenderEnabled, mIsSelectionEnabled, and parentClass.
Member Function Documentation
virtual ConsoleObject* AbstractClassRep::create () const pure virtual
Implemented in ConcreteClassRep< T >, ConcreteAbstractClassRep< T >, and RuntimeClassRep< T >.
Referenced by ConsoleObject::ConsoleObject(), ConsoleObject::create(), and isClass().
static ConsoleObject* AbstractClassRep::create (const char * in_pClassName) static protected
static ConsoleObject* AbstractClassRep::create (const U32 groupId, const U32 typeId, const U32 in_classId) static protected
virtual void AbstractClassRep::deleteNativeVariable (void * var) inline virtual
Delete a single value allocated with getNativeVariable().
Implements ConsoleBaseType.
static AbstractClassRep* AbstractClassRep::findClassRep (const char * in_pClassName) static
static AbstractClassRep* AbstractClassRep::findClassRep (U32 groupId, U32 typeId, U32 classId) static
const Field* AbstractClassRep::findField (StringTableEntry fieldName) const
Referenced by ConsoleObject::ConsoleObject().
AbstractClassRep* AbstractClassRep::findFieldRoot (StringTableEntry fieldName)
Referenced by isClass().
const char* AbstractClassRep::getCategory () const inline
Return the space separated category path for the class.
References mCategory.
static U32 AbstractClassRep::getClassCRC (U32 netClassGroup) inline static
References classCRC, and getCommonParent().
S32 AbstractClassRep::getClassId (U32 netClassGroup) const inline
Referenced by ConsoleObject::getParentStaticClassRep().
static AbstractClassRep* AbstractClassRep::getClassList () inline static
Return the head of the global class list.
References classLinkList.
StringTableEntry AbstractClassRep::getClassName () const inline
Return the name of this class.
References mClassName.
Referenced by RuntimeClassRep< T >::consoleRegister(), and ConsoleObject::getParentStaticClassRep().
AbstractClassRep* AbstractClassRep::getCommonParent (const AbstractClassRep * otherClass) const
Referenced by getClassCRC().
virtual AbstractClassRep* AbstractClassRep::getContainerChildClass (const bool recurse) pure virtual
Implemented in ConcreteAbstractClassRep< T >, and RuntimeClassRep< T >.
Referenced by RuntimeClassRep< T >::getContainerChildClass(), ConcreteAbstractClassRep< T >::getContainerChildClass(), and getParentClass().
virtual WriteCustomTamlSchema AbstractClassRep::getCustomTamlSchema (void) pure virtual
Implemented in ConcreteAbstractClassRep< T >, and RuntimeClassRep< T >.
Referenced by getParentClass().
const char* AbstractClassRep::getDescription () const inline
Return a short description string suitable for displaying in tooltips.
References mDescription.
Namespace* AbstractClassRep::getNameSpace () const inline
Return the namespace that contains the methods of this class.
References mNamespace.
Referenced by RuntimeClassRep< T >::init(), ConcreteAbstractClassRep< T >::init(), and Namespace::isClass().
virtual void* AbstractClassRep::getNativeVariable () inline virtual
Allocate a single value.
Implements ConsoleBaseType.
AbstractClassRep* AbstractClassRep::getNextClass () const inline
Return the next class in the global class list link chain.
References nextClass.
AbstractClassRep* AbstractClassRep::getParentClass () const inline
Return the AbstractClassRep of the class that this class is derived from.
References getContainerChildClass(), getCustomTamlSchema(), and parentClass.
S32 AbstractClassRep::getSizeof () const inline
Return the size of instances of this class in bytes.
References mClassSizeof.
virtual void AbstractClassRep::init () protected virtual
Reimplemented in ConcreteAbstractClassRep< T >.
Referenced by ConcreteAbstractClassRep< T >::init(), and isClass().
static void AbstractClassRep::initialize () static
bool AbstractClassRep::isClass (const AbstractClassRep * acr) const inline
References create(), findFieldRoot(), init(), and isSubclassOf().
bool AbstractClassRep::isRenderEnabled () const inline
References mIsRenderEnabled.
bool AbstractClassRep::isSelectionEnabled () const inline
References mIsSelectionEnabled.
bool AbstractClassRep::isSubclassOf (const AbstractClassRep * klass) const inline
Helper class to see if we are a given class, or a subclass thereof by comparing AbstractClassRep pointers.
References parentClass.
Referenced by isClass().
bool AbstractClassRep::isSubclassOf (const char * klass) const inline
Helper class to see if we are a given class, or a subclass thereof by comparing the class name strings.
References mClassName, and parentClass.
static void AbstractClassRep::registerClassRep (AbstractClassRep *) static
Referenced by ConcreteAbstractClassRep< T >::ConcreteAbstractClassRep(), and RuntimeClassRep< T >::consoleRegister().
static void AbstractClassRep::removeClassRep (AbstractClassRep *) static
Referenced by RuntimeClassRep< T >::consoleUnRegister().
static void AbstractClassRep::shutdown () static
Member Data Documentation
U32 AbstractClassRep::classCRC[NetClassGroupsCount] static protected
Referenced by getClassCRC().
AbstractClassRep* AbstractClassRep::classLinkList static protected
Referenced by getClassList().
AbstractClassRep** AbstractClassRep::classTable[NetClassGroupsCount][NetClassTypesCount] static protected
bool AbstractClassRep::initialized static protected
const char* AbstractClassRep::mCategory protected
Referenced by ConcreteAbstractClassRep< T >::ConcreteAbstractClassRep(), and getCategory().
S32 AbstractClassRep::mClassGroupMask
Mask indicating in which NetGroups this object belongs.
Referenced by ConcreteAbstractClassRep< T >::ConcreteAbstractClassRep(), and RuntimeClassRep< T >::RuntimeClassRep().
S32 AbstractClassRep::mClassId[NetClassGroupsCount]
Stores the IDs assigned to this class for each group.
Referenced by ConcreteAbstractClassRep< T >::ConcreteAbstractClassRep(), and RuntimeClassRep< T >::RuntimeClassRep().
const char* AbstractClassRep::mClassName protected
Referenced by ConcreteAbstractClassRep< T >::ConcreteAbstractClassRep(), getClassName(), RuntimeClassRep< T >::getTypeClassName(), ConcreteAbstractClassRep< T >::getTypeClassName(), isSubclassOf(), and RuntimeClassRep< T >::RuntimeClassRep().
S32 AbstractClassRep::mClassSizeof
Size of instances in bytes.
Referenced by ConcreteAbstractClassRep< T >::ConcreteAbstractClassRep(), and getSizeof().
S32 AbstractClassRep::mClassType
Stores the NetClass of this class.
Referenced by ConcreteAbstractClassRep< T >::ConcreteAbstractClassRep(), and RuntimeClassRep< T >::RuntimeClassRep().
const char* AbstractClassRep::mDescription protected
Referenced by ConcreteAbstractClassRep< T >::ConcreteAbstractClassRep(), and getDescription().
bool AbstractClassRep::mDynamicGroupExpand
FieldList AbstractClassRep::mFieldList
Referenced by AbstractClassRep(), and RuntimeClassRep< T >::consoleRegister().
bool AbstractClassRep::mIsRenderEnabled
Referenced by AbstractClassRep(), and isRenderEnabled().
bool AbstractClassRep::mIsSelectionEnabled
Referenced by AbstractClassRep(), and isSelectionEnabled().
Namespace* AbstractClassRep::mNamespace protected
Referenced by RuntimeClassRep< T >::consoleRegister(), and getNameSpace().
S32 AbstractClassRep::mNetEventDir
Stores the NetDirection of this class.
Referenced by ConcreteAbstractClassRep< T >::ConcreteAbstractClassRep(), and RuntimeClassRep< T >::RuntimeClassRep().
U32 AbstractClassRep::NetClassBitSize[NetClassGroupsCount][NetClassTypesCount] static
U32 AbstractClassRep::NetClassCount[NetClassGroupsCount][NetClassTypesCount] static
AbstractClassRep* AbstractClassRep::nextClass protected
Referenced by getNextClass().
AbstractClassRep* AbstractClassRep::parentClass protected
Referenced by AbstractClassRep(), ConcreteAbstractClassRep< T >::ConcreteAbstractClassRep(), getParentClass(), isSubclassOf(), and RuntimeClassRep< T >::RuntimeClassRep().
Copyright © GarageGames, LLC. All Rights Reserved.