rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator > Class Template Reference
Main Modules Class List Namespace List Online
rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator > Class Template Reference
Writer with indentation and spacing.
#include <persistence/rapidjson/prettywriter.h>
Public Types
typedef Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator > Base
typedef Base::Ch Ch
Public Types inherited from rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >
typedef SourceEncoding::Ch Ch
Public Member Functions
PrettyWriter (OutputStream &os, Allocator *allocator=0, size_t levelDepth=Base::kDefaultLevelDepth)
Constructor.
PrettyWriter & SetIndent (Ch indentChar, unsigned indentCharCount)
Set custom indentation.
PrettyWriter & String (const Ch *str)
Simpler but slower overload.
PrettyWriter & Null ()
PrettyWriter & Bool (bool b)
PrettyWriter & Int (int i)
PrettyWriter & Uint (unsigned u)
PrettyWriter & Int64 (int64_t i64)
PrettyWriter & Uint64 (uint64_t u64)
PrettyWriter & Double (double d)
PrettyWriter & String (const Ch *str, SizeType length, bool copy=false)
PrettyWriter & StartObject ()
PrettyWriter & EndObject (SizeType memberCount=0)
PrettyWriter & StartArray ()
PrettyWriter & EndArray (SizeType memberCount=0)
Public Member Functions inherited from rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >
Writer (OutputStream &os, Allocator *allocator=0, size_t levelDepth=kDefaultLevelDepth)
Writer & String (const Ch *str)
Simpler but slower overload.
Writer & Null ()
Writer & Bool (bool b)
Writer & Int (int i)
Writer & Uint (unsigned u)
Writer & Int64 (int64_t i64)
Writer & Uint64 (uint64_t u64)
Writer & Double (double d)
Writer & String (const Ch *str, SizeType length, bool copy=false)
Writer & StartObject ()
Writer & EndObject (SizeType memberCount=0)
Writer & StartArray ()
Writer & EndArray (SizeType elementCount=0)
Protected Member Functions
void PrettyPrefix (Type type)
void WriteIndent ()
Protected Member Functions inherited from rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >
void Prefix (Type type)
void WriteBool (bool b)
void WriteDouble (double d)
void WriteEndArray ()
void WriteEndObject ()
void WriteInt (int i)
void WriteInt64 (int64_t i64)
void WriteNull ()
void WriteStartArray ()
void WriteStartObject ()
void WriteString (const Ch *str, SizeType length)
void WriteUint (unsigned u)
void WriteUint64 (uint64_t u64)
Protected Attributes
Ch indentChar_
unsigned indentCharCount_
Protected Attributes inherited from rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >
internal::Stack< Allocator > level_stack_
OutputStream & os_
Additional Inherited Members
Static Protected Attributes inherited from rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >
static const size_t kDefaultLevelDepth = 32
Detailed Description
template<typename OutputStream, typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>>
class rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >
Writer with indentation and spacing.
Template Parameters
OutputStream Type of ouptut os.
Encoding Encoding of both source strings and output.
Allocator Type of allocator for allocating memory of stack.
Member Typedef Documentation
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> typedef Writer<OutputStream, SourceEncoding, TargetEncoding, Allocator> rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Base
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> typedef Base::Ch rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Ch
Constructor & Destructor Documentation
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::PrettyWriter (OutputStream & os, Allocator * allocator = 0, size_t levelDepth = Base::kDefaultLevelDepth) inline
Constructor.
Parameters
os Output os.
allocator User supplied allocator. If it is null, it will create a private one.
levelDepth Initial capacity of
Member Function Documentation
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> PrettyWriter& rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Bool (bool b) inline
References rapidjson::kFalseType, rapidjson::kTrueType, rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::PrettyPrefix(), and rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteBool().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> PrettyWriter& rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Double (double d) inline
References rapidjson::kNumberType, rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::PrettyPrefix(), and rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteDouble().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> PrettyWriter& rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::EndArray (SizeType memberCount = 0) inline
References rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::level_stack_, rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::os_, rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteEndArray(), and rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteIndent().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> PrettyWriter& rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::EndObject (SizeType memberCount = 0) inline
References rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::level_stack_, rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::os_, rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteEndObject(), and rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteIndent().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> PrettyWriter& rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Int (int i) inline
References rapidjson::kNumberType, rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::PrettyPrefix(), and rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteInt().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> PrettyWriter& rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Int64 (int64_t i64) inline
References rapidjson::kNumberType, rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::PrettyPrefix(), and rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteInt64().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> PrettyWriter& rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Null () inline
References rapidjson::kNullType, rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::PrettyPrefix(), and rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteNull().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> void rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::PrettyPrefix (Type type) inline protected
References rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Level::inArray, rapidjson::kArrayType, rapidjson::kObjectType, rapidjson::kStringType, rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::level_stack_, rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::os_, rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Level::valueCount, and rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteIndent().
Referenced by rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Bool(), rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Double(), rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Int(), rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Int64(), rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Null(), rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::StartArray(), rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::StartObject(), rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::String(), rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Uint(), and rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Uint64().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> PrettyWriter& rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::SetIndent (Ch indentChar, unsigned indentCharCount) inline
Set custom indentation.
Parameters
indentChar Character for indentation. Must be whitespace character (' ', '', '
', '').
indentCharCount Number of indent characters for each indentation level.
Note
The default indentation is 4 spaces.
References rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::indentChar_, and rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::indentCharCount_.
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> PrettyWriter& rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::StartArray () inline
References rapidjson::kArrayType, rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::level_stack_, rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::PrettyPrefix(), and rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteStartArray().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> PrettyWriter& rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::StartObject () inline
References rapidjson::kObjectType, rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::level_stack_, rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::PrettyPrefix(), and rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteStartObject().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> PrettyWriter& rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::String (const Ch * str, SizeType length, bool copy = false) inline
References rapidjson::kStringType, rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::PrettyPrefix(), and rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteString().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> PrettyWriter& rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::String (const Ch * str) inline
Simpler but slower overload.
References rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::String(), and rapidjson::internal::StrLen().
Referenced by rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::String().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> PrettyWriter& rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Uint (unsigned u) inline
References rapidjson::kNumberType, rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::PrettyPrefix(), and rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteUint().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> PrettyWriter& rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::Uint64 (uint64_t u64) inline
References rapidjson::kNumberType, rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::PrettyPrefix(), and rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteUint64().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> void rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteIndent () inline protected
References rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::indentChar_, rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::indentCharCount_, rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::level_stack_, rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, Allocator >::os_, and rapidjson::PutN().
Referenced by rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::EndArray(), rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::EndObject(), and rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::PrettyPrefix().
Member Data Documentation
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> Ch rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::indentChar_ protected
Referenced by rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::SetIndent(), and rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteIndent().
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> unsigned rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::indentCharCount_ protected
Referenced by rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::SetIndent(), and rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, Allocator >::WriteIndent().
Copyright © GarageGames, LLC. All Rights Reserved.