TamlCustomNode Class Reference
Main Modules Class List Namespace List Online
TamlCustomNode Class Reference
#include <persistence/taml/tamlCustom.h>
Public Member Functions
TamlCustomNode ()
virtual ~TamlCustomNode ()
TamlCustomField * addField (const char *pFieldName, const ColorI &fieldValue)
TamlCustomField * addField (const char *pFieldName, const ColorF &fieldValue)
TamlCustomField * addField (const char *pFieldName, const Point2I &fieldValue)
TamlCustomField * addField (const char *pFieldName, const Point2F &fieldValue)
TamlCustomField * addField (const char *pFieldName, const Point3I &fieldValue)
TamlCustomField * addField (const char *pFieldName, const Point3F &fieldValue)
TamlCustomField * addField (const char *pFieldName, const RectF &fieldValue)
TamlCustomField * addField (const char *pFieldName, const QuatF &fieldValue)
TamlCustomField * addField (const char *pFieldName, const AngAxisF &fieldValue)
TamlCustomField * addField (const char *pFieldName, const U32 fieldValue)
TamlCustomField * addField (const char *pFieldName, const bool fieldValue)
TamlCustomField * addField (const char *pFieldName, const S32 fieldValue)
TamlCustomField * addField (const char *pFieldName, const float fieldValue)
TamlCustomField * addField (const char *pFieldName, const char *fieldValue)
TamlCustomNode * addNode (SimObject *pProxyObject)
TamlCustomNode * addNode (const char *pNodeName, const bool ignoreEmpty=true)
const TamlCustomField * findField (const char *pFieldName) const
const TamlCustomNode * findNode (const char *pNodeName) const
const Vector< TamlCustomNode * > & getChildren (void) const
const TamlCustomFieldVector & getFields (void) const
bool getIgnoreEmpty (void) const
StringTableEntry getNodeName (void) const
const TamlCustomField & getNodeTextField (void) const
TamlCustomField & getNodeTextField (void)
template<typename T >
T * getProxyObject (const bool deleteIfNotType) const
const TamlWriteNode * getProxyWriteNode (void) const
bool isEmpty (void) const
bool isProxyObject (void) const
void removeNode (const U32 index)
virtual void resetState (void)
void setIgnoreEmpty (const bool ignoreEmpty)
void setNodeName (const char *pNodeName)
void setNodeText (const char *pNodeText)
void setWriteNode (TamlWriteNode *pWriteNode)
Constructor & Destructor Documentation
TamlCustomNode::TamlCustomNode () inline
References TamlCustomField::resetState().
virtual TamlCustomNode::~TamlCustomNode () inline virtual
Member Function Documentation
TamlCustomField* TamlCustomNode::addField (const char * pFieldName, const ColorI & fieldValue) inline
References FactoryCache< T >::createObject(), and TamlCustomField::setFieldValue().
TamlCustomField* TamlCustomNode::addField (const char * pFieldName, const ColorF & fieldValue) inline
References FactoryCache< T >::createObject(), and TamlCustomField::setFieldValue().
TamlCustomField* TamlCustomNode::addField (const char * pFieldName, const Point2I & fieldValue) inline
References FactoryCache< T >::createObject(), and TamlCustomField::setFieldValue().
TamlCustomField* TamlCustomNode::addField (const char * pFieldName, const Point2F & fieldValue) inline
References FactoryCache< T >::createObject(), and TamlCustomField::setFieldValue().
TamlCustomField* TamlCustomNode::addField (const char * pFieldName, const Point3I & fieldValue) inline
References FactoryCache< T >::createObject(), and TamlCustomField::setFieldValue().
TamlCustomField* TamlCustomNode::addField (const char * pFieldName, const Point3F & fieldValue) inline
References FactoryCache< T >::createObject(), and TamlCustomField::setFieldValue().
TamlCustomField* TamlCustomNode::addField (const char * pFieldName, const RectF & fieldValue) inline
References FactoryCache< T >::createObject(), and TamlCustomField::setFieldValue().
TamlCustomField* TamlCustomNode::addField (const char * pFieldName, const QuatF & fieldValue) inline
References FactoryCache< T >::createObject(), and TamlCustomField::setFieldValue().
TamlCustomField* TamlCustomNode::addField (const char * pFieldName, const AngAxisF & fieldValue) inline
References FactoryCache< T >::createObject(), and TamlCustomField::setFieldValue().
TamlCustomField* TamlCustomNode::addField (const char * pFieldName, const U32 fieldValue) inline
References FactoryCache< T >::createObject(), and TamlCustomField::setFieldValue().
TamlCustomField* TamlCustomNode::addField (const char * pFieldName, const bool fieldValue) inline
References FactoryCache< T >::createObject(), and TamlCustomField::setFieldValue().
TamlCustomField* TamlCustomNode::addField (const char * pFieldName, const S32 fieldValue) inline
References FactoryCache< T >::createObject(), and TamlCustomField::setFieldValue().
TamlCustomField* TamlCustomNode::addField (const char * pFieldName, const float fieldValue) inline
References FactoryCache< T >::createObject(), and TamlCustomField::setFieldValue().
TamlCustomField* TamlCustomNode::addField (const char * pFieldName, const char * fieldValue) inline
References FactoryCache< T >::createObject(), and TamlCustomField::setFieldValue().
TamlCustomNode* TamlCustomNode::addNode (SimObject * pProxyObject) inline
References FactoryCache< T >::createObject(), ConsoleObject::getClassName(), and setNodeName().
TamlCustomNode* TamlCustomNode::addNode (const char * pNodeName, const bool ignoreEmpty = true) inline
References FactoryCache< T >::createObject(), setIgnoreEmpty(), and setNodeName().
const TamlCustomField* TamlCustomNode::findField (const char * pFieldName) const inline
const TamlCustomNode* TamlCustomNode::findNode (const char * pNodeName) const inline
References Vector< T >::begin().
const Vector<TamlCustomNode*>& TamlCustomNode::getChildren (void) const inline
const TamlCustomFieldVector& TamlCustomNode::getFields (void) const inline
bool TamlCustomNode::getIgnoreEmpty (void) const inline
References Vector< T >::begin(), FactoryCache< T >::cacheObject(), FactoryCache< T >::createObject(), TamlCustomField::getFieldName(), TamlCustomField::getFieldValue(), and Con::warnf().
StringTableEntry TamlCustomNode::getNodeName (void) const inline
Referenced by TamlCustomNodes::addNode().
const TamlCustomField& TamlCustomNode::getNodeTextField (void) const inline
TamlCustomField& TamlCustomNode::getNodeTextField (void) inline
template<typename T > T* TamlCustomNode::getProxyObject (const bool deleteIfNotType) const inline
References T.
const TamlWriteNode* TamlCustomNode::getProxyWriteNode (void) const inline
bool TamlCustomNode::isEmpty (void) const inline
bool TamlCustomNode::isProxyObject (void) const inline
void TamlCustomNode::removeNode (const U32 index) inline
References FactoryCache< T >::cacheObject().
virtual void TamlCustomNode::resetState (void) inline virtual
Implements IFactoryObjectReset.
References FactoryCache< T >::cacheObject().
void TamlCustomNode::setIgnoreEmpty (const bool ignoreEmpty) inline
Referenced by addNode(), and TamlCustomNodes::addNode().
void TamlCustomNode::setNodeName (const char * pNodeName) inline
Referenced by addNode(), and TamlCustomNodes::addNode().
void TamlCustomNode::setNodeText (const char * pNodeText) inline
void TamlCustomNode::setWriteNode (TamlWriteNode * pWriteNode)
Copyright © GarageGames, LLC. All Rights Reserved.