SceneObject Class Reference
Main Modules Class List Namespace List Online
SceneObject Class Reference
A 3D object.
#include <scene/sceneObject.h>
Classes
struct MountInfo
Mounted object.
struct ObjectZonesIterator
Iterator over the zones that the object is assigned to.
struct ZoneRef
Bidirectional link between a zone manager and its objects.
Public Types
enum {
MaxObjectZones = 128,
NumMountPoints = 32,
NumMountPointBits = 5
}
typedef NetObject Parent
enum SceneObjectFlags {
RenderEnabledFlag = BIT(0),
SelectionEnabledFlag = BIT(1),
DisableCullingInEditorFlag = BIT(2),
VisualOccluderFlag = BIT(3),
SoundOccluderFlag = BIT(4),
NextFreeFlag = BIT(5)
}
Bit-flags stored in mObjectFlags.
enum SceneObjectMasks {
InitialUpdateMask = BIT(0),
ScaleMask = BIT(1),
FlagMask = BIT(2),
MountedMask = BIT(3),
NextFreeMask = BIT(4)
}
Networking dirty mask.
Public Types inherited from SimGroup
typedef SimSet Parent
Public Types inherited from SimSet
typedef SimObject Parent
enum SetModification {
SetCleared,
SetObjectAdded,
SetObjectRemoved
}
typedef Signal< void(SetModification modification, SimSet *set, SimObject *object) > SetModificationSignal
Signal for letting observers know when objects are added to or removed from the set.
typedef SimObjectList::iterator iterator
typedef SimObjectList::value_type value
Public Types inherited from SimObject
typedef ConsoleObject Parent
enum WriteFlags {
SelectedOnly = BIT(0),
NoName = BIT(1),
IgnoreCanSave = BIT(2)
}
Flags passed to SimObject::write.
Public Types inherited from EngineObject
typedef void(* DebugEnumInstancesCallback) (EngineObject *)
Type of callback function for iterating over EngineObject instances.
Public Member Functions
SceneObject ()
virtual ~SceneObject ()
virtual void clearProcessAfter ()
Clears the effects of a call to processAfter()
DECLARE_CONOBJECT (SceneObject)
virtual ProcessObject * getAfterObject () const
Returns the object that this processes after.
ProcessList * getProcessList () const
Return the ProcessList for this object to use.
U32 getTypeMask () const
Return the type mask that indicates to which broad object categories this object belongs.
virtual void inspectPostApply ()
Called after any property of the object is changed in the world editor.
virtual bool onAdd ()
Called when the object is added to the sim.
virtual void onCameraScopeQuery (NetConnection *connection, CameraScopeQuery *query)
Queries the object about information used to determine scope.
virtual void onDeleteNotify (SimObject *object)
Called when a SimObject is deleted.
virtual void onRemove ()
Called when the object is removed from the sim.
virtual U32 packUpdate (NetConnection *conn, U32 mask, BitStream *stream)
Instructs this object to pack its state for transfer over the network.
virtual void processAfter (ProcessObject *obj)
Force this object to process after some other object.
virtual void setProcessTick (bool t)
Set the status of tick processing.
virtual void unpackUpdate (NetConnection *conn, BitStream *stream)
Instructs this object to read state data previously packed with packUpdate.
virtual bool writeField (StringTableEntry fieldName, const char *value)
Determine whether or not a field should be written.
SceneManager Functionality
SceneManager * getSceneManager () const
Return the SceneManager that this SceneObject belongs to.
void addToScene ()
Adds object to the client or server container depending on the object.
void removeFromScene ()
Removes the object from the client/server container.
SceneContainer * getContainer ()
Returns a pointer to the container that contains this object.
Flags
bool isRenderEnabled () const
Return true if this object is rendered.
void setRenderEnabled (bool value)
Set whether the object gets rendered.
bool isSelectionEnabled () const
Return true if this object can be selected in the editor.
void setSelectionEnabled (bool value)
Set whether the object can be selected in the editor.
bool isCullingDisabledInEditor () const
Return true if the object doesn't want to be subjected to culling when in the editor.
bool isVisualOccluder () const
Return true if the object should be taken into account for visual occlusion.
Collision and transform related interface
The Render Transform is the interpolated transform with respect to the frame rate.
The Render Transform will differ from the object transform because the simulation is updated in fixed intervals, which controls the object transform. The framerate is, most likely, higher than this rate, so that is why the render transform is interpolated and will differ slightly from the object transform.
virtual void disableCollision ()
Disables collisions for this object including raycasts.
virtual void enableCollision ()
Enables collisions for this object.
bool isCollisionEnabled () const
Returns true if collisions are enabled.
virtual void onCollision (SceneObject *object, const VectorF &vec)
This gets called when an object collides with this object.
virtual bool isDisplacable () const
Returns true if this object allows itself to be displaced.
virtual Point3F getMomentum () const
Returns the momentum of this object.
virtual void setMomentum (const Point3F &momentum)
Sets the momentum of this object.
virtual F32 getMass () const
Returns the mass of this object.
virtual bool displaceObject (const Point3F &displaceVector)
Displaces this object by a vector.
virtual const MatrixF & getTransform () const
Returns the transform which can be used to convert object space to world space.
const MatrixF & getWorldTransform () const
Returns the transform which can be used to convert world space into object space.
const VectorF & getScale () const
Returns the scale of the object.
const Box3F & getObjBox () const
Returns the bounding box for this object in local coordinates.
const Box3F & getWorldBox () const
Returns the bounding box for this object in world coordinates.
const SphereF & getWorldSphere () const
Returns the bounding sphere for this object in world coordinates.
Point3F getBoxCenter () const
Returns the center of the bounding box in world coordinates.
virtual void setTransform (const MatrixF &mat)
Sets the Object -> World transform.
virtual void setScale (const VectorF &scale)
Sets the scale for the object.
virtual void setRenderTransform (const MatrixF &mat)
This sets the render transform for this object.
const MatrixF & getRenderTransform () const
Returns the render transform.
const MatrixF & getRenderWorldTransform () const
Returns the render transform to convert world to local coordinates.
const Box3F & getRenderWorldBox () const
Returns the render world box.
virtual void setHidden (bool hidden)
Sets the state of this object as hidden or not.
virtual void buildConvex (const Box3F &box, Convex *convex)
Builds a convex hull for this object.
virtual bool buildPolyList (PolyListContext context, AbstractPolyList *polyList, const Box3F &box, const SphereF &sphere)
Builds a list of polygons which intersect a bounding volume.
virtual bool castRay (const Point3F &start, const Point3F &end, RayInfo *info)
Casts a ray and obtain collision information, returns true if RayInfo is modified.
virtual bool castRayRendered (const Point3F &start, const Point3F &end, RayInfo *info)
Casts a ray against rendered geometry, returns true if RayInfo is modified.
virtual void buildSilhouette (const SceneCameraState &cameraState, Vector< Point3F > &outPoints)
Build a world-space silhouette polygon for the object for the given camera settings.
virtual bool containsPoint (const Point3F &point)
Return true if the given point is contained by the object's (collision) shape.
virtual bool collideBox (const Point3F &start, const Point3F &end, RayInfo *info)
virtual Point3F getPosition () const
Returns the position of the object.
Point3F getRenderPosition () const
Returns the render-position of the object.
void setPosition (const Point3F &pos)
Sets the position of the object.
virtual Point3F getVelocity () const
Gets the velocity of the object.
virtual void setVelocity (const Point3F &v)
Sets the velocity of the object.
virtual void applyImpulse (const Point3F &pos, const VectorF &vec)
Applies an impulse force to this object.
virtual void applyRadialImpulse (const Point3F &origin, F32 radius, F32 magnitude)
Applies a radial impulse to the object using the impulse origin and force.
virtual F32 distanceTo (const Point3F &pnt) const
Returns the distance from this object to a point.
Sound
bool isOccludingSound () const
Return whether the object's collision shape is blocking sound.
virtual SFXAmbience * getSoundAmbience () const
Return the ambient sound space active inside the volume of this object or NULL if the object does not have its own ambient space.
Rendering
virtual void prepRenderImage (SceneRenderState *state)
Called when the SceneManager is ready for the registration of render instances.
Lighting
void setLightingPlugin (SceneObjectLightingPlugin *plugin)
SceneObjectLightingPlugin * getLightingPlugin ()
Global Bounds
const bool isGlobalBounds () const
void setGlobalBounds ()
If global bounds are set to be true, then the object is assumed to have an infinitely large bounding box for collision and rendering purposes.
Public Member Functions inherited from NetObject
NetObject ()
~NetObject ()
virtual void clearMaskBits (U32 orMask)
Clear the specified bits from the dirty mask.
void clearScopeAlways ()
Stop scoping the object to all connections.
virtual String describeSelf () const
Return a textual description of the object.
virtual U32 filterMaskBits (U32 mask, NetConnection *connection)
U32 getNetIndex ()
Get the ghost index of this object.
virtual F32 getUpdatePriority (CameraScopeQuery *focusObject, U32 updateMask, S32 updateSkips)
This returns a value which is used to prioritize which objects need to be updated.
bool isClientObject () const
Is this a client object?
bool isGhost () const
Is this is a ghost?
bool isGhostable () const
Is this object ghostable?
bool isGhostAlways () const
Should this object always be ghosted?
bool isScopeable () const
Is this object subject to scoping?
bool isScopeLocal () const
Should this object only be visible to the client which created it?
bool isServerObject () const
Is this a server object?
virtual void setMaskBits (U32 orMask)
Used to mark a bit as dirty; ie, that its corresponding set of fields need to be transmitted next update.
void setScopeAlways ()
Scope the object to all connections.
DECLARE_CONOBJECT (NetObject)
bool onAdd ()
Called when the object is added to the sim.
void onRemove ()
Called when the object is removed from the sim.
NetObject * getServerObject () const
Returns a pointer to the server object when on a local connection.
NetObject * getClientObject () const
Returns a pointer to the client object when on a local connection.
Public Member Functions inherited from SimGroup
~SimGroup ()
void addObject (SimObject *object, SimObjectId id)
void addObject (SimObject *object, const char *name)
virtual void addObject (SimObject *object)
Add the given object to the set.
virtual void clear ()
Remove all objects from this set.
virtual SimGroup * clone ()
Return a shallow copy of this object.
DECLARE_CONOBJECT (SimGroup)
virtual SimGroup * deepClone ()
Return a deep copy of this object.
virtual SimObject * findObject (const char *name)
Find a named sub-object of this object.
virtual void popObject ()
Remove an object from the end of the list.
virtual bool processArguments (S32 argc, ConsoleValueRef *argv)
Process constructor options. (ie, new SimObject(1,2,3))
virtual void pushObject (SimObject *object)
Add the given object to the end of the object list of this set.
virtual void removeObject (SimObject *object)
Remove the given object from the set.
Public Member Functions inherited from SimSet
SimSet ()
~SimSet ()
virtual void addTamlChild (SimObject *pSimObject)
Called when Taml attempts to populate an objects children during a read.
void callOnChildren (const String &method, S32 argc, ConsoleValueRef argv[], bool executeOnChildGroups=true)
DECLARE_CONOBJECT (SimSet)
SimObject * findObject (SimObject *object)
Find the given object in this set.
template<class T >
void findObjectByCallback (bool(*fn)(T *), Vector< T * > &foundObjects)
Add all child objects (including children of children) to the foundObjects Vector which are of type T and for which DecideAddObjectCallback return true;.
virtual SimObject * findObjectByInternalName (StringTableEntry internalName, bool searchChildren=false)
SimObject * findObjectByLineNumber (const char *fileName, S32 declarationLine, bool searchChildren=false)
template<class T >
void findObjectByType (Vector< T * > &foundObjects)
Add all child objects (including children of children) to the foundObjects Vector which are of type T.
SimObject * getRandom ()
const SetModificationSignal & getSetModificationSignal () const
Return the signal that is triggered when an object is added to or removed from the set.
SetModificationSignal & getSetModificationSignal ()
virtual SimObject * getTamlChild (const U32 childIndex) const
Called when Taml attempts to compile a list of children.
virtual U32 getTamlChildCount (void) const
Called when Taml attempts to compile a list of children.
void lock ()
virtual bool readObject (Stream *stream)
U32 sizeRecursive ()
Return the number of objects in this set as well as all sets that are contained in this set and its children.
void unlock ()
virtual void write (Stream &stream, U32 tabStop, U32 flags=0)
Output the TorqueScript to recreate this object.
virtual bool writeObject (Stream *stream)
virtual bool acceptsAsChild (SimObject *object) const
Return true if this set accepts the given object as a child.
void deleteAllObjects ()
Deletes all the objects in the set.
void bringObjectToFront (SimObject *obj)
void pushObjectToBack (SimObject *obj)
void scriptSort (const String &scriptCallbackFn)
Performs a sort of the objects in the set using a script callback function to do the comparison.
SimObject * front ()
SimObject * first ()
SimObject * last ()
bool empty () const
S32 size () const
iterator begin ()
iterator end ()
value operator[] (S32 index)
iterator find (iterator first, iterator last, SimObject *obj)
iterator find (SimObject *obj)
virtual bool reOrder (SimObject *obj, SimObject *target=0)
Reorder the position of "obj" to either be the last object in the list or, if "target" is given, to come before "target" in the list of children.
SimObject * at (S32 index) const
Return the object at the given index.
Public Member Functions inherited from SimObject
virtual void copyTo (SimObject *object)
Copy SimObject to another SimObject (Originally designed for T2D).
DECLARE_CONOBJECT (SimObject)
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
virtual void getConsoleMethodData (const char *fname, S32 routingId, S32 *type, S32 *minArgs, S32 *maxArgs, void **callback, const char **usage)
Namespace * getNamespace ()
Return the object's namespace.
StringTableEntry getProgenitorFile (void) const
virtual bool handlesConsoleMethod (const char *fname, S32 *routingId)
void setProgenitorFile (const char *pFile)
const char * tabComplete (const char *prevText, S32 baseLen, bool)
Get next matching item in namespace.
virtual void writeFields (Stream &stream, U32 tabStop)
Write the fields of this object in TorqueScript.
void setCanSaveDynamicFields (bool bCanSave)
Set whether fields created at runtime should be saved. Default is true.
bool getCanSaveDynamicFields ()
Get whether fields created at runtime should be saved. Default is true.
SimObject * getCopySource () const
Return the object that this object is copying fields from.
void setCopySource (SimObject *object)
Set the object that this object should be copying fields from.
void assignFieldsFrom (SimObject *obj)
Copy fields from another object onto this one.
void assignDynamicFieldsFrom (SimObject *obj)
Copy dynamic fields from another object onto this one.
Notify * removeNotify (void *ptr, Notify::Type)
Remove a notification from the list.
void deleteNotify (SimObject *obj)
Notify an object when we are deleted.
void clearNotify (SimObject *obj)
Notify an object when we are cleared.
void clearAllNotifications ()
Remove all notifications for this object.
void processDeleteNotifies ()
Send out deletion notifications.
void registerReference (SimObject **obj)
Register a reference to this object.
void unregisterReference (SimObject **obj)
Unregister a reference to this object.
SimPersistID * getPersistentId () const
Return the persistent ID assigned to this object or NULL.
SimPersistID * getOrCreatePersistentId ()
Return the persistent ID assigned to this object or assign one to it if it has none.
StringTableEntry getClassNamespace () const
Return name of class namespace set on this object.
StringTableEntry getSuperClassNamespace () const
Return name of superclass namespace set on this object.
void setClassNamespace (const char *classNamespace)
void setSuperClassNamespace (const char *superClassNamespace)
const char * getDataField (StringTableEntry slotName, const char *array)
Get the value of a field on the object.
void setDataField (StringTableEntry slotName, const char *array, const char *value)
Set the value of a field on the object.
const char * getPrefixedDataField (StringTableEntry fieldName, const char *array)
void setPrefixedDataField (StringTableEntry fieldName, const char *array, const char *value)
const char * getPrefixedDynamicDataField (StringTableEntry fieldName, const char *array, const S32 fieldType=-1)
void setPrefixedDynamicDataField (StringTableEntry fieldName, const char *array, const char *value, const S32 fieldType=-1)
StringTableEntry getDataFieldPrefix (StringTableEntry fieldName)
U32 getDataFieldType (StringTableEntry slotName, const char *array)
Get the type of a field on the object.
void setDataFieldType (const U32 fieldTypeId, StringTableEntry slotName, const char *array)
Set the type of a dynamic field on the object.
void setDataFieldType (const char *typeName, StringTableEntry slotName, const char *array)
SimFieldDictionary * getFieldDictionary ()
Get reference to the dictionary containing dynamic fields.
virtual StringTableEntry getComponentName ()
void setInternalName (const char *newname)
These functions support internal naming that is not namespace bound for locating child controls in a generic way.
StringTableEntry getInternalName () const
Get the internal name of this control.
void setOriginalName (const char *originalName)
Set the original name of this control.
StringTableEntry getOriginalName () const
Get the original name of this control.
void setFilename (const char *file)
These functions allow you to set and access the filename where this object was created.
StringTableEntry getFilename () const
Get the filename.
void setDeclarationLine (U32 lineNumber)
These functions are used to track the line number (1-based) on which the object was created if it was loaded from script.
S32 getDeclarationLine () const
Get the declaration line number.
virtual bool save (const char *pcFilePath, bool bOnlySelected=false, const char *preappend=NULL)
Save object as a TorqueScript File.
virtual bool isMethod (const char *methodName)
Check if a method exists in the objects current namespace.
virtual bool isField (const char *fieldName, bool includeStatic=true, bool includeDynamic=true)
Return true if the field is defined on the object.
SimObjectId getId () const
Return the unique numeric object ID.
const char * getIdString () const
Return the object ID as a string.
StringTableEntry getName () const
Return the name of this object.
SimGroup * getGroup () const
Return the SimGroup that this object is contained in.
void assignName (const char *name)
Assign the given name to this object.
void setId (SimObjectId id)
bool isChildOfGroup (SimGroup *pGroup)
bool isProperlyAdded () const
bool isDeleted () const
bool isRemoved () const
virtual bool isLocked () const
virtual void setLocked (bool b)
virtual bool isHidden () const
bool isSelected () const
bool isExpanded () const
bool isEditorOnly () const
bool isNameChangeAllowed () const
bool isAutoDeleted () const
void setSelected (bool sel)
void setExpanded (bool exp)
void setModDynamicFields (bool dyn)
void setModStaticFields (bool sta)
bool canModDynamicFields ()
bool canModStaticFields ()
void setAutoDelete (bool val)
void setEditorOnly (bool val)
void setNameChangeAllowed (bool val)
bool getCanSave () const
Returns boolean specifying if the object can be serialized.
virtual void setCanSave (bool val)
Set serialization flag.
bool isSelectedRecursive () const
Returns true if this object is selected or any group it is a member of is.
SimObject ()
virtual ~SimObject ()
virtual void onGroupAdd ()
Called when the object is added to a SimGroup.
virtual void onGroupRemove ()
Called when the object is removed from a SimGroup.
virtual void onNameChange (const char *name)
Called when the object's name is changed.
virtual void onPostAdd ()
Called when the adding of the object to the sim is complete, all sub-objects have been processed as well.
virtual void onStaticModified (const char *slotName, const char *newValue=NULL)
Specifically, these are called by setDataField when a static or dynamic field is modified, see the console details.
virtual void onDynamicModified (const char *slotName, const char *newValue=NULL)
Called when a dynamic field is modified.
virtual void inspectPreApply ()
Called before any property of the object is changed in the world editor.
virtual void onEditorEnable ()
Called when the editor is activated.
virtual void onEditorDisable ()
Called when the editor is deactivated.
bool registerObject ()
Register an object with the object system.
bool registerObject (U32 id)
Register the object, forcing the id.
bool registerObject (const char *name)
Register the object, assigning the name.
bool registerObject (const char *name, U32 id)
Register the object, assigning a name and ID.
void unregisterObject ()
Unregister the object from Sim.
void deleteObject ()
Unregister, mark as deleted, and free the object.
void safeDeleteObject ()
Performs a safe delayed delete of the object using a sim event.
bool addToSet (SimObjectId)
bool addToSet (const char *)
bool removeFromSet (SimObjectId)
bool removeFromSet (const char *)
void dumpToConsole (bool includeFunctions=true)
Dump the contents of this object to the console.
virtual void dumpClassHierarchy ()
added this so that you can print the entire class hierarchy, including script objects,
virtual void dumpGroupHierarchy ()
Print the SimGroup hierarchy of this object to the console.
Public Member Functions inherited from ConsoleObject
ConsoleObject ()
virtual AbstractClassRep * getClassRep () const
Gets the ClassRep.
const AbstractClassRep::Field * findField (StringTableEntry fieldName) const
Get a reference to a field by name.
bool setField (const char *fieldName, const char *value)
Set the value of a field.
void logMessage (const char *fmt,...) const
Logs with Con::printf.
void logWarning (const char *fmt,...) const
Logs with Con::warnf.
void logError (const char *fmt,...) const
Logs with Con::errorf.
const AbstractClassRep::FieldList & getFieldList () const
Get a list of all the fields. This information cannot be modified.
AbstractClassRep::FieldList & getModifiableFieldList ()
Get a list of all the fields, set up so we can modify them.
bool & getDynamicGroupExpand ()
Get a handle to a boolean telling us if we expanded the dynamic group.
S32 getClassId (U32 netClassGroup) const
Get our network-layer class id.
StringTableEntry getClassName () const
Get our compiler and platform independent class name.
Public Member Functions inherited from EngineObject
EngineObject ()
virtual ~EngineObject ()
DECLARE_ABSTRACT_CLASS (EngineObject, void)
DECLARE_INSCOPE (_GLOBALSCOPE)
IEngineObjectPool * getEngineObjectPool () const
Return the pool of EngineObjects to which this object belongs.
void operator delete (void *ptr)
Release the given object's memory in the pool it has been allocated from.
void * operator new (size_t size)
void * operator new (size_t size, IEngineObjectPool *pool)
void * operator new (size_t size TORQUE_TMM_ARGS_DECL)
Allocate a new object in the default object pool.
void * operator new (size_t size, IEngineObjectPool *pool TORQUE_TMM_ARGS_DECL)
Allocate a new object in the given object pool.
void * operator new (size_t size, void *ptr)
Placement new.
Public Member Functions inherited from StrongRefBase
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Public Member Functions inherited from ProcessObject
ProcessObject ()
virtual ~ProcessObject ()
virtual void advanceTime (F32 dt)
Advances simulation time for animations.
virtual GameConnection * getControllingClient ()
This is really implemented in GameBase and is only here to avoid casts within ProcessList.
virtual U32 getPacketDataChecksum (GameConnection *conn)
This is really implemented in GameBase and is only here to avoid casts within ProcessList.
virtual void interpolateTick (F32 delta)
Interpolates between tick events.
bool isTicking () const
Returns true if this object processes ticks.
void plJoin (ProcessObject *)
void plLinkAfter (ProcessObject *)
void plLinkBefore (ProcessObject *)
void plUnlink ()
virtual void preprocessMove (Move *move)
Allow object to modify the Move before it is ticked or sent to the server.
virtual void processTick (const Move *move)
Processes a move event and updates object state once every 32 milliseconds.
void removeFromProcessList ()
Removes this object from the tick-processing list.
Static Public Member Functions
static void initPersistFields ()
Static Public Member Functions inherited from NetObject
static void collapseDirtyList ()
static void initPersistFields ()
template<class T >
static T * getServerObject (T *netObj)
Template form for the callers convenience.
template<class T >
static T * getClientObject (T *netObj)
Template form for the callers convenience.
Static Public Member Functions inherited from SimObject
static SimObject * __findObject (const char *id)
static const char * __getObjectId (ConsoleObject *object)
static void initPersistFields ()
static void setForcedId (SimObjectId id)
Force an Id on the next registered object.
Static Public Member Functions inherited from ConsoleObject
static const char * __category ()
static const char * __description ()
static void consoleInit ()
Register global constant variables and do other one-time initialization tasks in a subclass of ConsoleObject.
static void initPersistFields ()
Register dynamic fields in a subclass of ConsoleObject.
static const char * lookupClassName (const U32 in_classTag)
Get the classname from a class tag.
static ConsoleObject * create (const char *in_pClassName)
static ConsoleObject * create (const U32 groupId, const U32 typeId, const U32 in_classId)
static void addGroup (const char *in_pGroupname, const char *in_pGroupDocs=NULL)
Mark the beginning of a group of fields.
static void endGroup (const char *in_pGroupname)
Mark the end of a group of fields.
static void addArray (const char *arrayName, S32 count)
Marks the start of a fixed size array of fields.
static void endArray (const char *arrayName)
Marks the end of an array of fields.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a complex field.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::WriteDataNotify in_writeDataFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, const char *in_pFieldDocs, U32 flags=0)
Register a simple field.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::WriteDataNotify in_writeDataFn, const char *in_pFieldDocs, U32 flags=0)
static void addFieldV (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, TypeValidator *v, const char *in_pFieldDocs=NULL)
Register a validated field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, AbstractClassRep::WriteDataNotify in_writeDataFn=&defaultProtectedWriteFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a complex protected field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, AbstractClassRep::WriteDataNotify in_writeDataFn=&defaultProtectedWriteFn, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a simple protected field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addDeprecatedField (const char *fieldName)
Add a deprecated field.
static bool removeField (const char *in_pFieldname)
Remove a field.
static AbstractClassRep * getStaticClassRep ()
Get the abstract class information for this class.
static AbstractClassRep * getParentStaticClassRep ()
Get the abstract class information for this class's superclass.
static ConsoleObject * __findObject (const char *)
static const char * __getObjectId (ConsoleObject *)
Static Public Member Functions inherited from EngineObject
static void debugDumpInstances ()
Dump describeSelf()s of all live ConsoleObjects to the console.
static void debugEnumInstances (const std::type_info &type, DebugEnumInstancesCallback callback)
Call the given callback for all instances of the given type.
static void debugEnumInstances (const char *className, DebugEnumInstancesCallback callback)
Same as above but uses an export class name and also includes inheritance (i.e.
Public Attributes
GFXTextureObject * mAccuTex
bool mPathfindingIgnore
Public Attributes inherited from EngineObject
DECLARE_INSTANTIABLE
Public Attributes inherited from ProcessObject
bool mIsGameBase
U32 mOrderGUID
Link mProcessLink
U32 mProcessTag
bool mProcessTick
Static Public Attributes
static Signal< void(SceneObject *) > smSceneObjectAdd
Triggered when a SceneObject onAdd is called.
static Signal< void(SceneObject *) > smSceneObjectRemove
Triggered when a SceneObject onRemove is called.
Static Public Attributes inherited from ConsoleObject
static const bool __smIsDatablock = false
Subclasses of ConsoleObjects that are datablocks should redefine this static member variable and set it to true.
Protected Member Functions
virtual U32 getObjectFlagMax () const
Returns the greatest object flag bit defined.
virtual bool onSceneAdd ()
Called when this is added to a SceneManager.
virtual void onSceneRemove ()
Called when this is removed from its current SceneManager.
Protected Member Functions inherited from SimSet
DECLARE_CALLBACK (void, onObjectAdded,(SimObject *object))
DECLARE_CALLBACK (void, onObjectRemoved,(SimObject *object))
Protected Member Functions inherited from SimObject
virtual void _destroySelf ()
Subclasses should overload this method instead of the public destroySelf().
virtual String _getLogMessage (const char *fmt, va_list args) const
We can provide more detail, like object name and id.
virtual void _onSelected ()
Called when the object is selected in the editor.
virtual void _onUnselected ()
Called when the object is unselected in the editor.
object incRefCount ()
virtual void onTamlAddParent (SimObject *pParentObject)
Called after Taml has finished reading the object and has added the object to any parent.
virtual void onTamlCustomRead (const TamlCustomNodes &customNodes)
Called during the reading of the object to allow custom properties to be read.
virtual void onTamlCustomWrite (TamlCustomNodes &customNodes)
Called during the writing of the object to allow custom properties to be written.
virtual void onTamlPostRead (const TamlCustomNodes &customNodes)
Called after Taml has finished reading the object.
virtual void onTamlPostWrite (void)
Called after Taml has finished writing the object.
virtual void onTamlPreRead (void)
Called prior to Taml reading the object.
virtual void onTamlPreWrite (void)
Taml callbacks.
object registerObject ()
void linkNamespaces ()
Perform namespace linking on this object.
void unlinkNamespaces ()
Undo namespace linking on this object.
Protected Member Functions inherited from ConsoleObject
ConsoleObject (const ConsoleObject &)
Protected Member Functions inherited from EngineObject
object incRefCount ()
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Protected Attributes
SimObjectPtr< SceneObject > mAfterObject
Object which must be ticked before this object.
SceneObjectLightingPlugin * mLightPlugin
SceneObjectLightingPlugin attached to this object.
BitSet32 mObjectFlags
Combination of SceneObjectFlags.
SceneManager * mSceneManager
SceneManager to which this SceneObject belongs.
SceneObjectLink * mSceneObjectLinks
Links installed by SceneTrackers attached to this object.
U32 mTypeMask
Object type mask.
Protected Attributes inherited from NetObject
SimObjectPtr< NetObject > mClientObject
Pointer to the client object on a local connection.
GhostInfo * mFirstObjectRef
Head of a linked list storing GhostInfos referencing this NetObject.
BitSet32 mNetFlags
Flag values from NetFlags.
U32 mNetIndex
The index of this ghost in the GhostManager on the server.
SimObjectPtr< NetObject > mServerObject
Pointer to the server object on a local connection.
Protected Attributes inherited from SimSet
void * mMutex
SetModificationSignal mSetModificationSignal
Signal that is triggered when objects are added or removed from the set.
SimObjectList objectList
Protected Attributes inherited from SimObject
DEFINE_CREATE_METHOD
SimObjectId mId
Id number for this object.
StringTableEntry mInternalName
Internal name assigned to the object. Not set by default.
return object
bool mCanSaveFieldDictionary
Whether dynamic fields should be saved out in serialization. Defaults to true.
SimPersistID * mPersistentId
Persistent ID assigned to this object.
Namespace * mNameSpace
The namespace in which method lookup for this object begins.
StringTableEntry mClassName
Name of namespace to use as class namespace.
StringTableEntry mSuperClassName
Name of namespace to use as class super namespace.
Protected Attributes inherited from EngineObject
DEFINE_CREATE_METHOD
return object
Protected Attributes inherited from StrongRefBase
U32 mRefCount
reference counter for StrongRefPtr objects
Mounting
MountInfo mMount
SimPersistID * mMountPID
virtual void mountObject (SceneObject *obj, S32 node, const MatrixF &xfm=MatrixF::Identity)
ex: Mount B to A at A's node N A.mountObject(B, N)
virtual void unmountObject (SceneObject *obj)
Remove an object mounting.
virtual void unmount ()
Unmount this object from it's mount.
virtual void onMount (SceneObject *obj, S32 node)
Callback when this object is mounted.
virtual void onUnmount (SceneObject *obj, S32 node)
Callback when this object is unmounted.
virtual void getMountTransform (S32 index, const MatrixF &xfm, MatrixF *outMat)
virtual void getRenderMountTransform (F32 delta, S32 index, const MatrixF &xfm, MatrixF *outMat)
virtual SceneObject * getObjectMount ()
Return the object that this object is mounted to.
virtual SceneObject * getMountLink ()
Return object link of next object mounted to this object's mount.
virtual SceneObject * getMountList ()
Returns object list of objects mounted to this object.
virtual U32 getMountNode ()
Returns the mount id that this is mounted to.
virtual bool isMounted ()
Returns true if this object is mounted to anything at all Also try to resolve the PID to objectId here if it is pending.
virtual S32 getMountedObjectCount ()
Returns the number of object mounted along with this.
virtual SceneObject * getMountedObject (S32 idx)
Returns the object mounted at a position in the mount list.
virtual S32 getMountedObjectNode (S32 idx)
Returns the node the object at idx is mounted to.
virtual SceneObject * getMountNodeObject (S32 node)
Returns the object a object on the mount list is mounted to.
void resolveMountPID ()
Zoning
bool mZoneRefDirty
If an object moves, its zoning state needs to be updated.
U32 mNumCurrZones
Number of zones this object is assigned to.
ZoneRef * mZoneRefHead
List of zones that this object is part of.
void _updateZoningState () const
Refresh the zoning state of this object, if it isn't up-to-date anymore.
ZoneRef * _getZoneRefHead () const
Return the first link in the zone list of this object.
U32 _getNumCurrZones () const
Gets the number of zones containing this object.
U32 _getCurrZone (const U32 index) const
Returns the nth zone containing this object.
Transform and Collision Members
MatrixF mObjToWorld
Transform from object space to world space.
MatrixF mWorldToObj
Transform from world space to object space (inverse).
Point3F mObjScale
Object scale.
Box3F mObjBox
Bounding box in object space.
Box3F mWorldBox
Bounding box (AABB) in world space.
SphereF mWorldSphere
Bounding sphere in world space.
MatrixF mRenderObjToWorld
Render matrix to transform object space to world space.
MatrixF mRenderWorldToObj
Render matrix to transform world space to object space.
Box3F mRenderWorldBox
Render bounding box in world space.
SphereF mRenderWorldSphere
Render bounding sphere in world space.
bool mGlobalBounds
Whether this object is considered to have an infinite bounding box.
S32 mCollisionCount
void resetWorldBox ()
Regenerates the world-space bounding box and bounding sphere.
void resetRenderWorldBox ()
Regenerates the render-world-space bounding box and sphere.
void resetObjectBox ()
Regenerates the object-space bounding box from the world-space bounding box, the world space to object space transform, and the object scale.
virtual void onScaleChanged ()
Called when the size of the object changes.
SceneContainer Interface
When objects are searched, we go through all the zones and ask them for all of their objects.
Because an object can exist in multiple zones, the container sequence key is set to the id of the current search. Then, while searching, we check to see if an object's sequence key is the same as the current search key. If it is, it will NOT be added to the list of returns since it has already been processed.
SceneContainer * mContainer
Container database that the object is assigned to.
U32 mContainerSeqKey
SceneContainer sequence key.
SceneObjectRef * mBinRefHead
U32 mBinMinX
U32 mBinMaxX
U32 mBinMinY
U32 mBinMaxY
U32 getContainerSeqKey () const
Returns the container sequence key.
void setContainerSeqKey (const U32 key)
Sets the container sequence key.
Additional Inherited Members
Protected Types inherited from NetObject
enum NetFlags {
IsGhost = BIT(1),
ScopeAlways = BIT(6),
ScopeLocal = BIT(7),
Ghostable = BIT(8),
MaxNetFlagBit = 15
}
Protected Types inherited from EngineObject
typedef ::FalseType __IsDisposableType
typedef ::FalseType __IsSingletonType
Static Protected Member Functions inherited from SimObject
static bool _setPersistentID (void *object, const char *index, const char *data)
Static Protected Member Functions inherited from EngineObject
static void * _allocateObject (size_t size, IEngineObjectPool *pool TORQUE_TMM_ARGS_DECL)
Static Protected Attributes inherited from SimObject
static SimObjectId smForcedId
The Id to force upon the object. Poor object.
static bool smForceId
Force a registered object to use the given Id. Cleared upon use.
Detailed Description
A 3D object.
Introduction
SceneObject exists as a foundation for 3D objects in Torque. It provides the basic functionality for:
A scene graph (in the Zones and Portals sections), allowing efficient and robust rendering of the game scene.
Various helper functions, including functions to get bounding information and momentum/velocity.
Collision detection, as well as ray casting.
Lighting. SceneObjects can register lights both at lightmap generation time, and dynamic lights at runtime (for special effects, such as from flame or a projectile, or from an explosion).
Manipulating scene objects, for instance varying scale.
An Example
Melv May has written a most marvelous example object deriving from SceneObject. Unfortunately this page is too small to contain it.
See also
http://www.garagegames.com/index.php?sec=mg&mod=resource&page=view&qid=3217 for a copy of Melv's example.
Member Typedef Documentation
typedef NetObject SceneObject::Parent
Member Enumeration Documentation
anonymous enum
Enumerator
MaxObjectZones
Maximum number of zones that an object can concurrently be assigned to.
NumMountPoints
NumMountPointBits
enum SceneObject::SceneObjectFlags
Bit-flags stored in mObjectFlags.
If a derived class adds more flags they must overload getObjectFlagMax to ensure those flags will be transmitted over the network.
See also
getObjectFlagMax
Enumerator
RenderEnabledFlag
If set, the object can be rendered.
Note
The per-class render disable flag can override the per-object flag.
SelectionEnabledFlag
If set, the object can be selected in the editor.
Note
The per-class selection disable flag can override the per-object flag.
DisableCullingInEditorFlag
If set, object will not be subjected to culling when in the editor.
This is useful to bypass zone culling and always render certain editor-only visual elements (like the zones themselves).
VisualOccluderFlag
If set, object will be used as a visual occluder.
In this case, the object should implement buildSilhouette() and return a convex silhouette polygon.
SoundOccluderFlag
If set, object will be used as a sound occluder.
NextFreeFlag
enum SceneObject::SceneObjectMasks
Networking dirty mask.
Enumerator
InitialUpdateMask
ScaleMask
FlagMask
MountedMask
NextFreeMask
Constructor & Destructor Documentation
SceneObject::SceneObject ()
Referenced by getAfterObject(), and getObjectFlagMax().
virtual SceneObject::~SceneObject () virtual
Referenced by getObjectFlagMax().
Member Function Documentation
U32 SceneObject::_getCurrZone (const U32 index) const protected
Returns the nth zone containing this object.
Referenced by _getNumCurrZones().
U32 SceneObject::_getNumCurrZones () const inline protected
Gets the number of zones containing this object.
References _getCurrZone(), and mNumCurrZones.
ZoneRef* SceneObject::_getZoneRefHead () const inline protected
Return the first link in the zone list of this object.
Each link represents a single zone that the object is assigned to.
Note
This method will return the zoning list as is. In case the zoning state of the object is dirty, the list contents may be outdated.
References mZoneRefHead.
void SceneObject::_updateZoningState () const protected
Refresh the zoning state of this object, if it isn't up-to-date anymore.
void SceneObject::addToScene ()
Adds object to the client or server container depending on the object.
Referenced by getSceneManager().
virtual void SceneObject::applyImpulse (const Point3F & pos, const VectorF & vec) inline virtual
Applies an impulse force to this object.
Parameters
pos Position where impulse came from in world space
vec Velocity vector (Impulse force F = m * v)
Reimplemented in ShapeBase, Player, Vehicle, RigidShape, PhysicsShape, Item, and PhysicsDebris.
virtual void SceneObject::applyRadialImpulse (const Point3F & origin, F32 radius, F32 magnitude) inline virtual
Applies a radial impulse to the object using the impulse origin and force.
Parameters
origin Point of origin of the radial impulse.
radius The radius of the impulse area.
magnitude The strength of the impulse.
Reimplemented in PhysicsShape, Forest, and PhysicsDebris.
References distanceTo(), getMountTransform(), getRenderMountTransform(), MatrixF::Identity, mountObject(), SceneObject::MountInfo::node, onMount(), onUnmount(), unmount(), unmountObject(), and SceneObject::MountInfo::xfm.
virtual void SceneObject::buildConvex (const Box3F & box, Convex * convex) inline virtual
Builds a convex hull for this object.
Think of a convex hull as a low-res mesh which covers, as tightly as possible, the object mesh, and is used as a collision mesh.
Parameters
box
convex Convex mesh generated (out)
Reimplemented in ShapeBase, Player, MeshRoad, TerrainBlock, Entity, Forest, ConvexShape, OpenVRTrackedObject, TSStatic, Trigger, CollisionTrigger, GroundPlane, PhysicalZone, and VehicleBlocker.
virtual bool SceneObject::buildPolyList (PolyListContext context, AbstractPolyList * polyList, const Box3F & box, const SphereF & sphere) inline virtual
Builds a list of polygons which intersect a bounding volume.
This will use either the sphere or the box, not both, the SceneObject implementation ignores sphere.
See also
AbstractPolyList
Parameters
context A contentual hint as to the type of polylist to build.
polyList Poly list build (out)
box Box bounding volume
sphere Sphere bounding volume
Reimplemented in ShapeBase, Player, MeshRoad, TerrainBlock, River, WheeledVehicle, Entity, Forest, ConvexShape, TSStatic, WaterBlock, WaterPlane, Prefab, and GroundPlane.
virtual void SceneObject::buildSilhouette (const SceneCameraState & cameraState, Vector< Point3F > & outPoints) inline virtual
Build a world-space silhouette polygon for the object for the given camera settings.
This is used for occlusion.
Parameters
cameraState Camera view parameters.
outPoints Vector to store the resulting polygon points in. Leave untouched if method is not implemented.
Reimplemented in AccumulationVolume, and OcclusionVolume.
References collideBox(), containsPoint(), getPosition(), getRenderPosition(), and setPosition().
virtual bool SceneObject::castRay (const Point3F & start, const Point3F & end, RayInfo * info) inline virtual
Casts a ray and obtain collision information, returns true if RayInfo is modified.
Parameters
start Start point of ray
end End point of ray
info Collision information obtained (out)
Reimplemented in ShapeBase, Player, MeshRoad, TerrainBlock, River, Entity, Forest, ConvexShape, Trigger, OpenVRTrackedObject, TSStatic, CollisionTrigger, WaterBlock, WaterPlane, and GroundPlane.
References castRayRendered(), and SimSet::end().
virtual bool SceneObject::castRayRendered (const Point3F & start, const Point3F & end, RayInfo * info) virtual
Casts a ray against rendered geometry, returns true if RayInfo is modified.
Parameters
start Start point of ray
end End point of ray
info Collision information obtained (out)
Reimplemented in ShapeBase, Entity, Forest, and TSStatic.
Referenced by castRay().
virtual void SceneObject::clearProcessAfter () virtual
Clears the effects of a call to processAfter()
Reimplemented from ProcessObject.
Referenced by isGlobalBounds().
virtual bool SceneObject::collideBox (const Point3F & start, const Point3F & end, RayInfo * info) virtual
Reimplemented in MeshRoad, River, TerrainBlock, Forest, and ConvexShape.
Referenced by buildSilhouette().
virtual bool SceneObject::containsPoint (const Point3F & point) virtual
Return true if the given point is contained by the object's (collision) shape.
The default implementation will return true if the point is within the object's bounding box. Subclasses should implement more precise tests.
Reimplemented in SFXEmitter, WaterObject, ScenePolyhedralObject< SceneSimpleZone >, and ScenePolyhedralObject< SceneSpace >.
Referenced by buildSilhouette().
SceneObject::DECLARE_CONOBJECT (SceneObject)
Referenced by getAfterObject().
virtual void SceneObject::disableCollision () virtual
Disables collisions for this object including raycasts.
Reimplemented in Vehicle, and RigidShape.
Referenced by isVisualOccluder().
virtual bool SceneObject::displaceObject (const Point3F & displaceVector) inline virtual
Displaces this object by a vector.
Parameters
displaceVector Displacement vector
Reimplemented in Player.
virtual F32 SceneObject::distanceTo (const Point3F & pnt) const virtual
Returns the distance from this object to a point.
Parameters
pnt World space point to measure to
Reimplemented in WaterBlock, and WaterPlane.
Referenced by applyRadialImpulse().
virtual void SceneObject::enableCollision () virtual
Enables collisions for this object.
Reimplemented in Vehicle, and RigidShape.
Referenced by isVisualOccluder().
virtual ProcessObject* SceneObject::getAfterObject () const inline virtual
Returns the object that this processes after.
See also
processAfter
Reimplemented from ProcessObject.
References DECLARE_CONOBJECT(), initPersistFields(), inspectPostApply(), mAfterObject, onAdd(), onCameraScopeQuery(), onDeleteNotify(), onRemove(), packUpdate(), SceneObject(), setProcessTick(), unpackUpdate(), and writeField().
Point3F SceneObject::getBoxCenter () const inline
Returns the center of the bounding box in world coordinates.
References Box3F::maxExtents, Box3F::minExtents, setRenderTransform(), setScale(), and setTransform().
SceneContainer* SceneObject::getContainer () inline
Returns a pointer to the container that contains this object.
References isRenderEnabled(), isSelectionEnabled(), mContainer, setRenderEnabled(), and setSelectionEnabled().
U32 SceneObject::getContainerSeqKey () const inline protected
Returns the container sequence key.
References mContainerSeqKey.
SceneObjectLightingPlugin* SceneObject::getLightingPlugin () inline
References mLightPlugin.
virtual F32 SceneObject::getMass () const inline virtual
Returns the mass of this object.
Reimplemented in ShapeBase, and PhysicsShape.
virtual Point3F SceneObject::getMomentum () const inline virtual
Returns the momentum of this object.
Reimplemented in Player.
virtual SceneObject* SceneObject::getMountedObject (S32 idx) virtual
Returns the object mounted at a position in the mount list.
Parameters
idx Position on the mount list
Referenced by getMountNode().
virtual S32 SceneObject::getMountedObjectCount () virtual
Returns the number of object mounted along with this.
Referenced by getMountNode().
virtual S32 SceneObject::getMountedObjectNode (S32 idx) virtual
Returns the node the object at idx is mounted to.
Parameters
idx Index
Referenced by getMountNode().
virtual SceneObject* SceneObject::getMountLink () inline virtual
Return object link of next object mounted to this object's mount.
References SceneObject::MountInfo::link.
virtual SceneObject* SceneObject::getMountList () inline virtual
Returns object list of objects mounted to this object.
References SceneObject::MountInfo::list.
virtual U32 SceneObject::getMountNode () inline virtual
Returns the mount id that this is mounted to.
References getMountedObject(), getMountedObjectCount(), getMountedObjectNode(), getMountNodeObject(), isMounted(), SceneObject::MountInfo::node, and resolveMountPID().
virtual SceneObject* SceneObject::getMountNodeObject (S32 node) virtual
Returns the object a object on the mount list is mounted to.
Parameters
node
Referenced by getMountNode().
virtual void SceneObject::getMountTransform (S32 index, const MatrixF & xfm, MatrixF * outMat) virtual
Reimplemented in ShapeBase, and Entity.
Referenced by applyRadialImpulse().
const Box3F& SceneObject::getObjBox () const inline
Returns the bounding box for this object in local coordinates.
References mObjBox.
virtual U32 SceneObject::getObjectFlagMax () const inline protected virtual
Returns the greatest object flag bit defined.
Only bits within this range will be transmitted over the network.
References NextFreeFlag, SceneObject(), and ~SceneObject().
virtual SceneObject* SceneObject::getObjectMount () inline virtual
Return the object that this object is mounted to.
References SceneObject::MountInfo::object.
virtual Point3F SceneObject::getPosition () const virtual
Returns the position of the object.
Reimplemented in Entity, and T3DSceneComponent.
Referenced by buildSilhouette().
ProcessList* SceneObject::getProcessList () const
Return the ProcessList for this object to use.
Referenced by isGlobalBounds().
virtual void SceneObject::getRenderMountTransform (F32 delta, S32 index, const MatrixF & xfm, MatrixF * outMat) virtual
Reimplemented in ShapeBase, and Entity.
Referenced by applyRadialImpulse().
Point3F SceneObject::getRenderPosition () const
Returns the render-position of the object.
See also
getRenderTransform
Referenced by buildSilhouette().
const MatrixF& SceneObject::getRenderTransform () const inline
Returns the render transform.
References mRenderObjToWorld.
const Box3F& SceneObject::getRenderWorldBox () const inline
Returns the render world box.
References mRenderWorldBox, and setHidden().
const MatrixF& SceneObject::getRenderWorldTransform () const inline
Returns the render transform to convert world to local coordinates.
References mRenderWorldToObj.
const VectorF& SceneObject::getScale () const inline
Returns the scale of the object.
References mObjScale.
Referenced by ScenePolyhedralZone::_updateIntersector(), and SceneSimpleZone::_updateOrientedWorldBox().
SceneManager* SceneObject::getSceneManager () const inline
Return the SceneManager that this SceneObject belongs to.
References addToScene(), mSceneManager, and removeFromScene().
virtual SFXAmbience* SceneObject::getSoundAmbience () const inline virtual
Return the ambient sound space active inside the volume of this object or NULL if the object does not have its own ambient space.
Reimplemented in WaterObject, SceneAmbientSoundObject< ScenePolyhedralObject< SceneSpace > >, and SceneAmbientSoundObject< ScenePolyhedralZone >.
virtual const MatrixF& SceneObject::getTransform () const inline virtual
Returns the transform which can be used to convert object space to world space.
References mObjToWorld.
Referenced by ScenePolyhedralZone::_updateIntersector(), SceneSimpleZone::_updateOrientedWorldBox(), and MeshRoadConvex::MeshRoadConvex().
U32 SceneObject::getTypeMask () const inline
Return the type mask that indicates to which broad object categories this object belongs.
References mTypeMask.
virtual Point3F SceneObject::getVelocity () const inline virtual
Gets the velocity of the object.
Reimplemented in Player, Vehicle, RigidShape, PhysicsShape, Camera, Projectile, and Item.
References Point3F::Zero.
const Box3F& SceneObject::getWorldBox () const inline
Returns the bounding box for this object in world coordinates.
References mWorldBox.
Referenced by ScenePolyhedralZone::_updateIntersector().
const SphereF& SceneObject::getWorldSphere () const inline
Returns the bounding sphere for this object in world coordinates.
References mWorldSphere.
const MatrixF& SceneObject::getWorldTransform () const inline
Returns the transform which can be used to convert world space into object space.
References mWorldToObj.
static void SceneObject::initPersistFields () static
Referenced by getAfterObject().
virtual void SceneObject::inspectPostApply () virtual
Called after any property of the object is changed in the world editor.
See also
inspectPreApply
Reimplemented from SimObject.
Reimplemented in TerrainBlock, MeshRoad, River, Precipitation, GameBase, NavMesh, fxFoliageReplicator, PhysicsShape, SFXEmitter, TSStatic, VolumetricFog, CameraBookmark, ForestWindEmitter, DecalRoad, Forest, ConvexShape, WaterObject, Marker, SpawnSphere, GroundCover, Trigger, WaterBlock, WaterPlane, Sun, WayPoint, OpenVRTrackedObject, fxShapeReplicator, NavPath, CollisionTrigger, LightBase, RenderMeshExample, CoverPoint, RenderShapeExample, ScatterSky, SkyBox, ParticleEmitterNode, AccumulationVolume, MissionMarker, TimeOfDay, CloudLayer, PhysicalZone, GroundPlane, RibbonNode, BasicClouds, and Prefab.
Referenced by getAfterObject().
bool SceneObject::isCollisionEnabled () const inline
Returns true if collisions are enabled.
bool SceneObject::isCullingDisabledInEditor () const inline
Return true if the object doesn't want to be subjected to culling when in the editor.
References DisableCullingInEditorFlag, and BitSet32::test().
virtual bool SceneObject::isDisplacable () const inline virtual
Returns true if this object allows itself to be displaced.
See also
displaceObject
Reimplemented in Player.
const bool SceneObject::isGlobalBounds () const inline
References clearProcessAfter(), getProcessList(), mGlobalBounds, processAfter(), and setGlobalBounds().
virtual bool SceneObject::isMounted () virtual
Returns true if this object is mounted to anything at all Also try to resolve the PID to objectId here if it is pending.
Referenced by getMountNode().
bool SceneObject::isOccludingSound () const inline
Return whether the object's collision shape is blocking sound.
References SoundOccluderFlag, and BitSet32::test().
bool SceneObject::isRenderEnabled () const
Return true if this object is rendered.
Referenced by getContainer().
bool SceneObject::isSelectionEnabled () const
Return true if this object can be selected in the editor.
Referenced by getContainer().
bool SceneObject::isVisualOccluder () const inline
Return true if the object should be taken into account for visual occlusion.
References disableCollision(), enableCollision(), BitSet32::test(), and VisualOccluderFlag.
virtual void SceneObject::mountObject (SceneObject * obj, S32 node, const MatrixF & xfm = MatrixF::Identity) virtual
ex: Mount B to A at A's node N A.mountObject(B, N)
Parameters
obj Object to mount
node Mount node ID
Reimplemented in Vehicle, TurretShape, and Entity.
Referenced by applyRadialImpulse().
virtual bool SceneObject::onAdd () virtual
Called when the object is added to the sim.
Reimplemented from SimObject.
Reimplemented in ShapeBase, Player, MeshRoad, River, TerrainBlock, Vehicle, AITurretShape, GameBase, RigidShape, fxFoliageReplicator, Precipitation, PhysicsShape, Camera, WheeledVehicle, ParticleEmitter, SFXEmitter, ForestWindEmitter, NavMesh, CameraBookmark, VolumetricFog, FlyingVehicle, Projectile, TurretShape, Item, Splash, DecalRoad, ConvexShape, Explosion, Lightning, Forest, WaterObject, AIPlayer, Debris, SpawnSphere, HoverVehicle, PhysicsDebris, GroundCover, TSStatic, Marker, Trigger, OpenVRTrackedObject, WayPoint, WaterBlock, Sun, ProximityMine, fxShapeReplicator, Ribbon, WaterPlane, PathCamera, CollisionTrigger, RenderMeshExample, NavPath, LightBase, RenderObjectExample, ScenePolyhedralObject< SceneSimpleZone >, ScenePolyhedralObject< SceneSpace >, CoverPoint, RenderShapeExample, TimeOfDay, SkyBox, ParticleEmitterNode, AccumulationVolume, ScatterSky, Entity, MissionMarker, StaticShape, ScenePolyhedralZone, PhysicalZone, CloudLayer, RibbonNode, OcclusionVolume, BasicClouds, SceneSpace, GroundPlane, Prefab, SceneRootZone, PhysicsForce, and VehicleBlocker.
Referenced by getAfterObject().
virtual void SceneObject::onCameraScopeQuery (NetConnection * cr, CameraScopeQuery * camInfo) virtual
Queries the object about information used to determine scope.
Something that is 'in scope' is somehow interesting to the client.
If we are a NetConnection's scope object, it calls this method to determine how things should be scoped; basically, we tell it our field of view with camInfo, and have the opportunity to manually mark items as "in scope" as we see fit.
By default, we just mark all ghostable objects as in scope.
Parameters
cr Net connection requesting scope information.
camInfo Information about what this object can see.
Reimplemented from NetObject.
Reimplemented in ShapeBase, Player, and Entity.
Referenced by getAfterObject().
virtual void SceneObject::onCollision (SceneObject * object, const VectorF & vec) inline virtual
This gets called when an object collides with this object.
Parameters
object Object colliding with this object
vec Vector along which collision occurred
Reimplemented in ShapeBase.
virtual void SceneObject::onDeleteNotify (SimObject * object) virtual
Called when a SimObject is deleted.
When you are on the notification list for another object and it is deleted, this method is called.
Reimplemented from SimSet.
Reimplemented in ShapeBase, ForestWindEmitter, Camera, Trigger, NavPath, and CollisionTrigger.
Referenced by getAfterObject().
virtual void SceneObject::onMount (SceneObject * obj, S32 node) virtual
Callback when this object is mounted.
Parameters
obj Object we are mounting to.
node Node we are unmounting from.
Reimplemented in ShapeBase, GameBase, TSStatic, Entity, and PhysicsForce.
Referenced by applyRadialImpulse().
virtual void SceneObject::onRemove () virtual
Called when the object is removed from the sim.
Reimplemented from SimGroup.
Reimplemented in ShapeBase, Player, MeshRoad, River, TerrainBlock, Vehicle, AITurretShape, GameBase, RigidShape, fxFoliageReplicator, Precipitation, PhysicsShape, Camera, WheeledVehicle, ParticleEmitter, SFXEmitter, ForestWindEmitter, NavMesh, CameraBookmark, VolumetricFog, FlyingVehicle, Projectile, TurretShape, Item, Splash, DecalRoad, ConvexShape, Explosion, Lightning, Forest, WaterObject, AIPlayer, Debris, HoverVehicle, PhysicsDebris, GroundCover, Ribbon, TSStatic, Marker, Trigger, OpenVRTrackedObject, WaterBlock, Sun, ProximityMine, fxShapeReplicator, WaterPlane, PathCamera, CollisionTrigger, RenderMeshExample, NavPath, LightBase, RenderObjectExample, CoverPoint, RenderShapeExample, TimeOfDay, SkyBox, ParticleEmitterNode, AccumulationVolume, ScatterSky, Entity, MissionMarker, StaticShape, PhysicalZone, CloudLayer, RibbonNode, BasicClouds, SceneSpace, VolumetricFogRTManager, GroundPlane, Prefab, SceneRootZone, PhysicsForce, and VehicleBlocker.
Referenced by getAfterObject().
virtual void SceneObject::onScaleChanged () inline protected virtual
Called when the size of the object changes.
Reimplemented in Player, TSStatic, and ConvexShape.
virtual bool SceneObject::onSceneAdd () inline protected virtual
Called when this is added to a SceneManager.
Reimplemented in DecalManager, SceneSimpleZone, and SceneRootZone.
virtual void SceneObject::onSceneRemove () inline protected virtual
Called when this is removed from its current SceneManager.
Reimplemented in ShapeBase, DecalManager, SceneZoneSpace, Portal, VolumetricFogRTManager, and SceneRootZone.
virtual void SceneObject::onUnmount (SceneObject * obj, S32 node) virtual
Callback when this object is unmounted.
This should be overridden to set maskbits or do other object type specific work.
Parameters
obj Object we are unmounting from.
node Node we are unmounting from.
Reimplemented in ShapeBase, Player, GameBase, TSStatic, Entity, TurretShape, and PhysicsForce.
Referenced by applyRadialImpulse().
virtual U32 SceneObject::packUpdate (NetConnection * conn, U32 mask, BitStream * stream) virtual
Instructs this object to pack its state for transfer over the network.
Parameters
conn Net connection being used
mask Mask indicating fields to transmit.
stream Bitstream to pack data to
Returns
Any bits which were not dealt with. The value is stored by the networking system. Don't set bits you weren't passed.
Reimplemented from NetObject.
Reimplemented in ShapeBase, Player, TerrainBlock, MeshRoad, River, GameBase, AITurretShape, RigidShape, SceneZoneSpace, Precipitation, PhysicsShape, fxFoliageReplicator, WheeledVehicle, Camera, Lightning, Vehicle, SFXEmitter, VolumetricFog, TSStatic, NavMesh, ForestWindEmitter, CameraBookmark, TurretShape, HoverVehicle, Portal, FlyingVehicle, Splash, Item, Projectile, Forest, DecalRoad, ConvexShape, WaterObject, Entity, SpawnSphere, Marker, GroundCover, Trigger, OpenVRTrackedObject, SceneSimpleZone, ProximityMine, Sun, WayPoint, PathCamera, WaterBlock, fxShapeReplicator, NavPath, RenderMeshExample, LightBase, CollisionTrigger, WaterPlane, RenderObjectExample, ParticleEmitterNode, CoverPoint, ScenePolyhedralObject< SceneSimpleZone >, ScenePolyhedralObject< SceneSpace >, RenderShapeExample, AccumulationVolume, RibbonNode, ScatterSky, SkyBox, TimeOfDay, MissionMarker, StaticShape, CloudLayer, PhysicalZone, SceneSpace, BasicClouds, Prefab, GroundPlane, SceneAmbientSoundObject< ScenePolyhedralObject< SceneSpace > >, SceneAmbientSoundObject< ScenePolyhedralZone >, SpotLight, VehicleBlocker, and PointLight.
Referenced by getAfterObject().
virtual void SceneObject::prepRenderImage (SceneRenderState * state) inline virtual
Called when the SceneManager is ready for the registration of render instances.
Parameters
state Rendering state.
Reimplemented in ShapeBase, Player, MeshRoad, TerrainBlock, Precipitation, fxFoliageReplicator, PhysicsShape, ParticleEmitter, SFXEmitter, NavMesh, VolumetricFog, TurretShape, TSStatic, Lightning, ForestWindEmitter, Projectile, DecalRoad, Explosion, ConvexShape, Forest, WaterObject, DecalManager, Item, PhysicsDebris, Debris, GroundCover, Trigger, OpenVRTrackedObject, RenderMeshExample, Sun, SceneSimpleZone, RenderObjectExample, Marker, LightBase, RenderShapeExample, NavPath, CollisionTrigger, Ribbon, fxShapeReplicator, CoverPoint, ProximityMine, ScatterSky, SkyBox, PhysicalZone, CloudLayer, BasicClouds, Entity, SceneSpace, and GroundPlane.
virtual void SceneObject::processAfter (ProcessObject * obj) virtual
Force this object to process after some other object.
For example, a player mounted to a vehicle would want to process after the vehicle to prevent a visible 'lagging' from occurring when the vehicle moves. So the player would be set to processAfter(theVehicle).
Parameters
obj Object to process after
Reimplemented from ProcessObject.
Referenced by isGlobalBounds().
void SceneObject::removeFromScene ()
Removes the object from the client/server container.
Referenced by getSceneManager().
void SceneObject::resetObjectBox () protected
Regenerates the object-space bounding box from the world-space bounding box, the world space to object space transform, and the object scale.
Referenced by Entity::resetObjectBox().
void SceneObject::resetRenderWorldBox () protected
Regenerates the render-world-space bounding box and sphere.
Referenced by Entity::resetRenderWorldBox().
void SceneObject::resetWorldBox () protected
Regenerates the world-space bounding box and bounding sphere.
Referenced by Entity::resetWorldBox().
void SceneObject::resolveMountPID ()
Referenced by getMountNode().
void SceneObject::setContainerSeqKey (const U32 key) inline protected
Sets the container sequence key.
void SceneObject::setGlobalBounds ()
If global bounds are set to be true, then the object is assumed to have an infinitely large bounding box for collision and rendering purposes.
They can't be toggled currently.
Referenced by isGlobalBounds().
virtual void SceneObject::setHidden (bool hidden) virtual
Sets the state of this object as hidden or not.
If an object is hidden it is removed entirely from collisions, it is not ghosted and is essentially "non existant" as far as simulation is concerned.
Parameters
hidden True if object is to be hidden
Reimplemented from SimObject.
Reimplemented in ShapeBase, and WayPoint.
Referenced by getRenderWorldBox().
void SceneObject::setLightingPlugin (SceneObjectLightingPlugin * plugin) inline
virtual void SceneObject::setMomentum (const Point3F & momentum) inline virtual
Sets the momentum of this object.
Parameters
momentum Momentum
Reimplemented in Player.
void SceneObject::setPosition (const Point3F & pos)
Sets the position of the object.
Referenced by buildSilhouette().
virtual void SceneObject::setProcessTick (bool t) virtual
Set the status of tick processing.
Set true to receive processTick, advanceTime, and interpolateTick calls.
See also
processTick
Parameters
t If true, tick processing is enabled.
Reimplemented from ProcessObject.
Referenced by getAfterObject().
void SceneObject::setRenderEnabled (bool value)
Set whether the object gets rendered.
Referenced by getContainer().
virtual void SceneObject::setRenderTransform (const MatrixF & mat) virtual
This sets the render transform for this object.
Parameters
mat New render transform
Reimplemented in Camera, and Entity.
Referenced by getBoxCenter(), and fxShapeReplicatedStatic::setTransform().
virtual void SceneObject::setScale (const VectorF & scale) virtual
Sets the scale for the object.
Parameters
scale Scaling values
Reimplemented in MeshRoad, TerrainBlock, River, PhysicsShape, SFXEmitter, NavMesh, DecalRoad, WaterBlock, T3DSceneComponent, Prefab, GroundPlane, SpotLight, and PointLight.
Referenced by getBoxCenter().
void SceneObject::setSelectionEnabled (bool value)
Set whether the object can be selected in the editor.
Referenced by getContainer().
virtual void SceneObject::setTransform (const MatrixF & mat) virtual
Sets the Object -> World transform.
Parameters
mat New transform matrix
Reimplemented in Player, MeshRoad, TerrainBlock, River, AITurretShape, Precipitation, PhysicsShape, SFXEmitter, Vehicle, RigidShape, TSStatic, NavMesh, Portal, ForestWindEmitter, Item, TurretShape, DecalRoad, ConvexShape, Forest, Camera, Trigger, WaterBlock, SceneSimpleZone, OpenVRTrackedObject, WaterPlane, LightBase, Entity, ProximityMine, T3DSceneComponent, CollisionTrigger, RenderMeshExample, RenderObjectExample, AccumulationVolume, CoverPoint, RenderShapeExample, PhysicalZone, StaticShape, ScenePolyhedralZone, OcclusionVolume, Prefab, GroundPlane, MissionMarker, SceneSpace, and fxShapeReplicatedStatic.
Referenced by getBoxCenter(), and fxShapeReplicatedStatic::setTransform().
virtual void SceneObject::setVelocity (const Point3F & v) inline virtual
Sets the velocity of the object.
Parameters
v Velocity
Reimplemented in ShapeBase, Player, Camera, Item, and Debris.
virtual void SceneObject::unmount () virtual
Unmount this object from it's mount.
Reimplemented in Player.
Referenced by applyRadialImpulse().
virtual void SceneObject::unmountObject (SceneObject * obj) virtual
Remove an object mounting.
Parameters
obj Object to unmount
Reimplemented in TurretShape.
Referenced by applyRadialImpulse().
virtual void SceneObject::unpackUpdate (NetConnection * conn, BitStream * stream) virtual
Instructs this object to read state data previously packed with packUpdate.
Parameters
conn Net connection being used
stream stream to read from
Reimplemented from NetObject.
Reimplemented in ShapeBase, Player, TerrainBlock, MeshRoad, River, GameBase, AITurretShape, RigidShape, SceneZoneSpace, Precipitation, PhysicsShape, fxFoliageReplicator, WheeledVehicle, Camera, Lightning, Vehicle, SFXEmitter, VolumetricFog, TSStatic, NavMesh, ForestWindEmitter, CameraBookmark, TurretShape, HoverVehicle, Portal, FlyingVehicle, Splash, Item, Projectile, Forest, DecalRoad, ConvexShape, WaterObject, Entity, SpawnSphere, Marker, GroundCover, Trigger, OpenVRTrackedObject, SceneSimpleZone, ProximityMine, Sun, WayPoint, PathCamera, WaterBlock, RenderMeshExample, fxShapeReplicator, NavPath, LightBase, RenderObjectExample, CollisionTrigger, WaterPlane, ParticleEmitterNode, CoverPoint, RenderShapeExample, ScenePolyhedralObject< SceneSimpleZone >, ScenePolyhedralObject< SceneSpace >, AccumulationVolume, RibbonNode, ScatterSky, SkyBox, TimeOfDay, MissionMarker, StaticShape, CloudLayer, PhysicalZone, SceneSpace, BasicClouds, Prefab, GroundPlane, SceneAmbientSoundObject< ScenePolyhedralObject< SceneSpace > >, SceneAmbientSoundObject< ScenePolyhedralZone >, SpotLight, VehicleBlocker, and PointLight.
Referenced by getAfterObject().
virtual bool SceneObject::writeField (StringTableEntry fieldname, const char * value) virtual
Determine whether or not a field should be written.
Parameters
fiedname The name of the field being written.
value The value of the field.
Reimplemented from SimObject.
Reimplemented in MeshRoad, River, SceneZoneSpace, Portal, DecalRoad, ConvexShape, ScenePolyhedralObject< SceneSimpleZone >, and ScenePolyhedralObject< SceneSpace >.
Referenced by getAfterObject().
Member Data Documentation
GFXTextureObject* SceneObject::mAccuTex
SimObjectPtr< SceneObject > SceneObject::mAfterObject protected
Object which must be ticked before this object.
Referenced by getAfterObject().
U32 SceneObject::mBinMaxX protected
U32 SceneObject::mBinMaxY protected
U32 SceneObject::mBinMinX protected
U32 SceneObject::mBinMinY protected
SceneObjectRef* SceneObject::mBinRefHead protected
S32 SceneObject::mCollisionCount protected
SceneContainer* SceneObject::mContainer protected
Container database that the object is assigned to.
Referenced by getContainer().
U32 SceneObject::mContainerSeqKey protected
SceneContainer sequence key.
Referenced by getContainerSeqKey().
bool SceneObject::mGlobalBounds protected
Whether this object is considered to have an infinite bounding box.
Referenced by isGlobalBounds().
SceneObjectLightingPlugin* SceneObject::mLightPlugin protected
SceneObjectLightingPlugin attached to this object.
Referenced by getLightingPlugin().
MountInfo SceneObject::mMount protected
SimPersistID* SceneObject::mMountPID protected
U32 SceneObject::mNumCurrZones mutable protected
Number of zones this object is assigned to.
Note
If mZoneRefDirty is set, this might be outdated.
Referenced by _getNumCurrZones().
Box3F SceneObject::mObjBox protected
Bounding box in object space.
Referenced by getObjBox(), and Entity::getObjectBox().
BitSet32 SceneObject::mObjectFlags protected
Combination of SceneObjectFlags.
Point3F SceneObject::mObjScale protected
Object scale.
Referenced by getScale().
MatrixF SceneObject::mObjToWorld protected
Transform from object space to world space.
Referenced by Entity::getObjToWorld(), and getTransform().
bool SceneObject::mPathfindingIgnore
MatrixF SceneObject::mRenderObjToWorld protected
Render matrix to transform object space to world space.
Referenced by getRenderTransform().
Box3F SceneObject::mRenderWorldBox protected
Render bounding box in world space.
Referenced by getRenderWorldBox().
SphereF SceneObject::mRenderWorldSphere protected
Render bounding sphere in world space.
MatrixF SceneObject::mRenderWorldToObj protected
Render matrix to transform world space to object space.
Referenced by getRenderWorldTransform().
SceneManager* SceneObject::mSceneManager protected
SceneManager to which this SceneObject belongs.
Referenced by getSceneManager().
SceneObjectLink* SceneObject::mSceneObjectLinks protected
Links installed by SceneTrackers attached to this object.
U32 SceneObject::mTypeMask protected
Object type mask.
See also
SimObjectTypes
Referenced by getTypeMask().
Box3F SceneObject::mWorldBox protected
Bounding box (AABB) in world space.
Referenced by getWorldBox().
SphereF SceneObject::mWorldSphere protected
Bounding sphere in world space.
Referenced by getWorldSphere().
MatrixF SceneObject::mWorldToObj protected
Transform from world space to object space (inverse).
Referenced by Entity::getWorldToObj(), and getWorldTransform().
bool SceneObject::mZoneRefDirty mutable protected
If an object moves, its zoning state needs to be updated.
This is deferred to when the state is actually needed and this flag indicates a refresh is necessary.
ZoneRef* SceneObject::mZoneRefHead mutable protected
List of zones that this object is part of.
Note
If mZoneRefDirty is set, this might be outdated.
Referenced by _getZoneRefHead().
Signal< void(SceneObject*) > SceneObject::smSceneObjectAdd static
Triggered when a SceneObject onAdd is called.
Signal< void(SceneObject*) > SceneObject::smSceneObjectRemove static
Triggered when a SceneObject onRemove is called.
Copyright © GarageGames, LLC. All Rights Reserved.