SFXStream Class Reference
Main Modules Class List Namespace List Online
SFXStream Class Reference abstract
The base sound data streaming interface.
#include <sfx/sfxStream.h>
Public Types
typedef void Parent
Public Types inherited from ThreadSafeRefCount< SFXStream >
typedef void Parent
Public Types inherited from IResettable
typedef void Parent
Public Member Functions
virtual ~SFXStream ()
Destructor.
virtual SFXStream * clone () const
Make a copy of this stream with its own private state, so new independent read() operations can be issued on the same data stream.
virtual U32 getDataLength () const =0
The data size in bytes of the decompressed PCM data.
virtual U32 getDuration () const =0
The length of the sound in milliseconds.
virtual const SFXFormat & getFormat () const =0
The format of the data in the stream.
virtual U32 getSampleCount () const =0
The number of samples in the data stream.
virtual bool isEOS () const =0
Returns true if we've reached the end of the stream.
virtual U32 read (U8 *buffer, U32 length)=0
Reads data from the stream and decompresses it into PCM samples.
virtual void reset ()=0
Resets the stream to restart reading data from the begining.
Public Member Functions inherited from ThreadSafeRefCount< SFXStream >
ThreadSafeRefCount ()
ThreadSafeRefCount (bool noSet)
void addRef ()
Increase the reference count on the object.
void clearLowestBit ()
U32 getRefCount () const
Get the current reference count.
bool isShared () const
void release ()
Decrease the object's reference count and delete the object, if the count drops to zero and claiming the object by the current thread succeeds.
Additional Inherited Members
Static Public Member Functions inherited from ThreadSafeRefCount< SFXStream >
static SFXStream * safeRead (SFXStream *const volatile &refPtr)
Dereference a reference-counted pointer in a multi-thread safe way.
Static Protected Member Functions inherited from ThreadSafeRefCount< SFXStream >
static U32 decrementAndTestAndSet (U32 &refCount)
Decrement the given reference count.
Protected Attributes inherited from ThreadSafeRefCount< SFXStream >
U32 mRefCount
Reference count and claim bit. Note that this increments in steps of two.
Detailed Description
The base sound data streaming interface.
Note
Streams that support seeking should implement the IPositionable<U32> interface.
Since SFXStreams are byte streams, all offset/size information is in bytes and not in number of samples.
Member Typedef Documentation
typedef void SFXStream::Parent
Constructor & Destructor Documentation
virtual SFXStream::~SFXStream () inline virtual
Destructor.
Member Function Documentation
virtual SFXStream* SFXStream::clone () const inline virtual
Make a copy of this stream with its own private state, so new independent read() operations can be issued on the same data stream.
Returns
Returns a copy of the stream or NULL.
Reimplemented in SFXWavStream.
References getDataLength(), getDuration(), getFormat(), getSampleCount(), isEOS(), read(), and reset().
virtual U32 SFXStream::getDataLength () const pure virtual
The data size in bytes of the decompressed PCM data.
Implemented in SFXFileStream, and SFXMemoryStream.
Referenced by clone().
virtual U32 SFXStream::getDuration () const pure virtual
The length of the sound in milliseconds.
Implemented in SFXFileStream, and SFXMemoryStream.
Referenced by clone().
virtual const SFXFormat& SFXStream::getFormat () const pure virtual
The format of the data in the stream.
Implemented in SFXFileStream, and SFXMemoryStream.
Referenced by clone().
virtual U32 SFXStream::getSampleCount () const pure virtual
The number of samples in the data stream.
Implemented in SFXFileStream, and SFXMemoryStream.
Referenced by clone().
virtual bool SFXStream::isEOS () const pure virtual
Returns true if we've reached the end of the stream.
Implemented in SFXFileStream, and SFXMemoryStream.
Referenced by clone().
virtual U32 SFXStream::read (U8 * buffer, U32 length) pure virtual
Reads data from the stream and decompresses it into PCM samples.
Parameters
length Number of bytes to read.
Implements IInputStream< U8 >.
Implemented in SFXMemoryStream, and SFXWavStream.
Referenced by clone().
virtual void SFXStream::reset () pure virtual
Resets the stream to restart reading data from the begining.
Implements IResettable.
Implemented in SFXMemoryStream, and SFXWavStream.
Referenced by clone().
Copyright © GarageGames, LLC. All Rights Reserved.