Map< Key, Value, Sequence > Class Template Reference
Main Modules Class List Namespace List Online
Map< Key, Value, Sequence > Class Template Reference
A Map template class.
#include <core/util/tDictionary.h>
Public Types
typedef Sequence::ConstIterator ConstIterator
typedef const Pair & ConstReference
typedef S32 DifferenceType
typedef Sequence::Iterator Iterator
typedef Sequence::Pair Pair
typedef Pair & Reference
typedef U32 SizeType
typedef Pair ValueType
Public Member Functions
Map ()
Map (const Map &p)
~Map ()
Iterator begin ()
Iterator to first element.
ConstIterator begin () const
Iterator to first element.
void clear ()
Empty the Map.
bool contains (const Key &a) const
Iterator end ()
IIterator to last element + 1.
ConstIterator end () const
Iterator to last element + 1.
void erase (Iterator)
Erase the given entry.
void erase (const Key &key)
Erase the key from the map.
Iterator find (const Key &)
Find entry for the given key.
ConstIterator find (const Key &) const
Find entry for the given key.
Iterator insert (const Key &key, const Value &)
Insert the key value pair but don't allow duplicates.
bool isEmpty () const
Returns true if the map is empty.
Value & operator[] (const Key &)
Index using the given key.
void resize (U32 size)
U32 size () const
Return the number of elements.
bool tryGetValue (const Key &key, Value &val) const
Try to get the value of the specified key.
Detailed Description
template<typename Key, typename Value, class Sequence = HashTable<Key,Value>>
class Map< Key, Value, Sequence >
A Map template class.
The map class maps between a key and an associated value. Keys are unique. The hash table class is used as the default implementation so the the key must be hashable, see util/hash.h for details.
Member Typedef Documentation
template<typename Key, typename Value, class Sequence = HashTable<Key,Value>> typedef Sequence::ConstIterator Map< Key, Value, Sequence >::ConstIterator
template<typename Key, typename Value, class Sequence = HashTable<Key,Value>> typedef const Pair& Map< Key, Value, Sequence >::ConstReference
template<typename Key, typename Value, class Sequence = HashTable<Key,Value>> typedef S32 Map< Key, Value, Sequence >::DifferenceType
template<typename Key, typename Value, class Sequence = HashTable<Key,Value>> typedef Sequence::Iterator Map< Key, Value, Sequence >::Iterator
template<typename Key, typename Value, class Sequence = HashTable<Key,Value>> typedef Sequence::Pair Map< Key, Value, Sequence >::Pair
template<typename Key, typename Value, class Sequence = HashTable<Key,Value>> typedef Pair& Map< Key, Value, Sequence >::Reference
template<typename Key, typename Value, class Sequence = HashTable<Key,Value>> typedef U32 Map< Key, Value, Sequence >::SizeType
template<typename Key, typename Value, class Sequence = HashTable<Key,Value>> typedef Pair Map< Key, Value, Sequence >::ValueType
Constructor & Destructor Documentation
template<typename Key, typename Value, class Sequence = HashTable<Key,Value>> Map< Key, Value, Sequence >::Map () inline
template<typename Key, typename Value, class Sequence = HashTable<Key,Value>> Map< Key, Value, Sequence >::~Map () inline
template<typename Key , typename Value , class Sequence > Map< Key, Value, Sequence >::Map (const Map< Key, Value, Sequence > & p)
Member Function Documentation
template<typename Key , typename Value , class Sequence > Map< Key, Value, Sequence >::Iterator Map< Key, Value, Sequence >::begin () inline
Iterator to first element.
Referenced by NamedFactory< Type >::create().
template<typename Key , typename Value , class Sequence > Map< Key, Value, Sequence >::ConstIterator Map< Key, Value, Sequence >::begin () const inline
Iterator to first element.
template<typename Key , typename Value , class Sequence > void Map< Key, Value, Sequence >::clear (void) inline
Empty the Map.
template<typename Key, typename Value, class Sequence = HashTable<Key,Value>> bool Map< Key, Value, Sequence >::contains (const Key & a) const inline
template<typename Key , typename Value , class Sequence > Map< Key, Value, Sequence >::Iterator Map< Key, Value, Sequence >::end () inline
IIterator to last element + 1.
template<typename Key , typename Value , class Sequence > Map< Key, Value, Sequence >::ConstIterator Map< Key, Value, Sequence >::end () const inline
Iterator to last element + 1.
template<typename Key , typename Value , class Sequence > void Map< Key, Value, Sequence >::erase (Iterator node)
Erase the given entry.
template<typename Key, typename Value , class Sequence > void Map< Key, Value, Sequence >::erase (const Key & key)
Erase the key from the map.
template<typename Key, typename Value , class Sequence > Map< Key, Value, Sequence >::Iterator Map< Key, Value, Sequence >::find (const Key & key)
Find entry for the given key.
Referenced by NamedFactory< Type >::create().
template<typename Key, typename Value , class Sequence > Map< Key, Value, Sequence >::ConstIterator Map< Key, Value, Sequence >::find (const Key & key) const
Find entry for the given key.
template<typename Key, typename Value, class Sequence > Map< Key, Value, Sequence >::Iterator Map< Key, Value, Sequence >::insert (const Key & key, const Value & x)
Insert the key value pair but don't allow duplicates.
The map class does not allow duplicates keys. If the key already exists in the map the function will fail and return end().
Referenced by NamedFactory< Type >::add().
template<typename Key , typename Value , class Sequence > bool Map< Key, Value, Sequence >::isEmpty () const inline
Returns true if the map is empty.
template<typename Key, typename Value , class Sequence > Value & Map< Key, Value, Sequence >::operator[] (const Key & key) inline
Index using the given key.
If the key is not currently in the map it is added. If you just want to try to get the value without the side effect of creating the key, use tryGetValue() instead.
template<typename Key , typename Value , class Sequence > void Map< Key, Value, Sequence >::resize (U32 size) inline
template<typename Key , typename Value , class Sequence > U32 Map< Key, Value, Sequence >::size () const inline
Return the number of elements.
template<typename Key, typename Value, class Sequence = HashTable<Key,Value>> bool Map< Key, Value, Sequence >::tryGetValue (const Key & key, Value & val) const inline
Try to get the value of the specified key.
Returns true and fills in the value if the key exists. Returns false otherwise. Unlike operator [], this function does not create the key/value if the key is not found.
Copyright © GarageGames, LLC. All Rights Reserved.