TSShapeAlloc Class Reference
Main Modules Class List Namespace List Online
TSShapeAlloc Class Reference
Alloc structure used in the reading/writing of shapes.
#include <ts/tsShapeAlloc.h>
Public Types
enum {
ReadMode = 0,
WriteMode = 1,
PageSize = 1024
}
Public Member Functions
void align32 ()
align on dword boundary
void checkGuard ()
void doAlloc ()
S8 * getBuffer ()
S32 getSize ()
void setGuard ()
void setRead (S32 *buff32, S16 *buff16, S8 *buff8, bool clear)
void setSkipMode (bool skip)
void setWrite ()
Detailed Description
Alloc structure used in the reading/writing of shapes.
In read mode we assemble contents of 32-bit, 16-bit, and 8-bit buffers into a single destination buffer.
In write mode we dissemble a stream of memory (which may be scattered in physical memory) into 32-bit, 16-bit, 8-bit, Point3F, and Point2F buffers using function calls similar to the read calls.
Read usage:
call "setRead" with each incoming memory buffers and clear=true.
run through set of operations for allocating and transfering memory to target buffer these are the operations under "DECLARE_ALLOC" that call readOnly in the .cc file.
call "doAlloc" to create buffer exactly as large as needed.
repeat step 1 & 2 to do the actual transfer of memory, except with clear=false (note: first time through nothing was copied to the shape, we only kept track of the size of the transfer).
call getBuffer to get the target (destination buffer)
write usage:
call "setWrite" (no parameters).
run through set of operations for allocating and transfering memory to internal buffers these are the operations under "DECLARE_ALLOC" that call writeOnly in the .cc file.
call getBuffer32 and getBufferSize32 to get 32-bit buffer and size. Similarly for 16-bit, 8-bit (getBuffer16, getBuffer8).
TSShape::assesmbleShape and TSShape::dissembleShape can be used as examples
Member Enumeration Documentation
anonymous enum
Enumerator
ReadMode
WriteMode
PageSize
Member Function Documentation
void TSShapeAlloc::align32 ()
align on dword boundary
void TSShapeAlloc::checkGuard ()
Referenced by setSkipMode().
void TSShapeAlloc::doAlloc ()
S8* TSShapeAlloc::getBuffer () inline
S32 TSShapeAlloc::getSize () inline
void TSShapeAlloc::setGuard ()
Referenced by setSkipMode().
void TSShapeAlloc::setRead (S32 * buff32, S16 * buff16, S8 * buff8, bool clear)
void TSShapeAlloc::setSkipMode (bool skip) inline
References checkGuard(), and setGuard().
void TSShapeAlloc::setWrite ()
Copyright © GarageGames, LLC. All Rights Reserved.