ColladaAppNode Class Reference
Main Modules Class List Namespace List Online
ColladaAppNode Class Reference
#include <ts/collada/colladaAppNode.h>
Public Member Functions
ColladaAppNode (const domNode *node, ColladaAppNode *parent=0)
virtual ~ColladaAppNode ()
bool animatesTransform (const AppSequence *appSeq)
bool getBool (const char *propName, bool &defaultVal)
const domNode * getDomNode () const
bool getFloat (const char *propName, F32 &defaultVal)
bool getInt (const char *propName, S32 &defaultVal)
const char * getName ()
MatrixF getNodeTransform (F32 time)
const char * getParentName ()
bool isEqual (AppNode *node)
bool isParentRoot ()
Public Member Functions inherited from AppNode
AppNode ()
virtual ~AppNode ()
AppNode * getChildNode (S32 idx)
AppMesh * getMesh (S32 idx)
S32 getNumChildNodes ()
S32 getNumMesh ()
virtual bool isBillboard ()
virtual bool isBillboardZAxis ()
virtual bool isBounds ()
virtual bool isDummy ()
virtual bool isRoot ()
virtual bool isSequence ()
Protected Attributes
ColladaAppNode * appParent
Parent node in Collada-space.
MatrixF defaultNodeTransform
Transform at DefaultTime.
bool defaultTransformValid
Flag indicating whether the defaultNodeTransform is valid.
bool invertMeshes
True if this node's coordinate space is inverted (left handed)
MatrixF lastTransform
Last transform lookup (getTransform)
F32 lastTransformTime
Time of the last transform lookup (getTransform)
Map< StringTableEntry, F32 > mProps
Hash of float properties (converted to int or bool as needed)
ColladaExtension_node * nodeExt
node extension
Vector< AnimatedFloatList > nodeTransforms
Ordered vector of node transform elements (scale, translate etc)
const domNode * p_domNode
Pointer to the node in the Collada DOM.
Protected Attributes inherited from AppNode
Vector< AppNode * > mChildNodes
Vector< AppMesh * > mMeshes
char * mName
S32 mParentIndex
char * mParentName
Constructor & Destructor Documentation
ColladaAppNode::ColladaAppNode (const domNode * node, ColladaAppNode * parent = 0)
virtual ColladaAppNode::~ColladaAppNode () inline virtual
References nodeExt.
Member Function Documentation
bool ColladaAppNode::animatesTransform (const AppSequence * appSeq) virtual
Implements AppNode.
Referenced by getBool().
bool ColladaAppNode::getBool (const char * propName, bool & defaultVal) inline virtual
Implements AppNode.
References animatesTransform(), getFloat(), and getNodeTransform().
Referenced by ColladaAppMesh::getBool().
const domNode* ColladaAppNode::getDomNode () const inline
References p_domNode.
bool ColladaAppNode::getFloat (const char * propName, F32 & defaultVal) inline virtual
Implements AppNode.
Referenced by getBool(), ColladaAppMesh::getFloat(), and getInt().
bool ColladaAppNode::getInt (const char * propName, S32 & defaultVal) inline virtual
Implements AppNode.
References getFloat().
Referenced by ColladaAppMesh::getInt().
const char* ColladaAppNode::getName () inline virtual
Implements AppNode.
References AppNode::mName.
Referenced by ColladaAppMesh::fixDetailSize().
MatrixF ColladaAppNode::getNodeTransform (F32 time) virtual
Implements AppNode.
Referenced by getBool().
const char* ColladaAppNode::getParentName () inline virtual
Implements AppNode.
References AppNode::mParentName.
bool ColladaAppNode::isEqual (AppNode * node) inline virtual
Implements AppNode.
References ColladaAppMesh::appNode, and p_domNode.
bool ColladaAppNode::isParentRoot () inline virtual
Implements AppNode.
Member Data Documentation
ColladaAppNode* ColladaAppNode::appParent protected
Parent node in Collada-space.
MatrixF ColladaAppNode::defaultNodeTransform protected
Transform at DefaultTime.
bool ColladaAppNode::defaultTransformValid protected
Flag indicating whether the defaultNodeTransform is valid.
bool ColladaAppNode::invertMeshes protected
True if this node's coordinate space is inverted (left handed)
MatrixF ColladaAppNode::lastTransform protected
Last transform lookup (getTransform)
F32 ColladaAppNode::lastTransformTime protected
Time of the last transform lookup (getTransform)
Map<StringTableEntry, F32> ColladaAppNode::mProps protected
Hash of float properties (converted to int or bool as needed)
ColladaExtension_node* ColladaAppNode::nodeExt protected
node extension
Referenced by ~ColladaAppNode().
Vector<AnimatedFloatList> ColladaAppNode::nodeTransforms protected
Ordered vector of node transform elements (scale, translate etc)
const domNode* ColladaAppNode::p_domNode protected
Pointer to the node in the Collada DOM.
Referenced by getDomNode(), and isEqual().
Copyright © GarageGames, LLC. All Rights Reserved.