Torque Namespace Reference
Main Modules Class List Namespace List Online
Torque Namespace Reference
Namespaces
FS
Mem
Posix
TimeConstant
Win32
Classes
class ByteBuffer
class List
A list template class.
class Path
FileSystem filename representation.
class Time
64 bit time representation with ten microsecond resolution.
class UUID
A universally unique identifier.
class ZipFileSystem
Enumerations
enum GL_AttributeLocation {
GL_VertexAttrib_Position = 0,
GL_VertexAttrib_Normal,
GL_VertexAttrib_Color,
GL_VertexAttrib_Tangent,
GL_VertexAttrib_TangentW,
GL_VertexAttrib_Binormal,
GL_VertexAttrib_TexCoord0,
GL_VertexAttrib_TexCoord1,
GL_VertexAttrib_TexCoord2,
GL_VertexAttrib_TexCoord3,
GL_VertexAttrib_TexCoord4,
GL_VertexAttrib_TexCoord5,
GL_VertexAttrib_TexCoord6,
GL_VertexAttrib_TexCoord7,
GL_VertexAttrib_TexCoord8,
GL_VertexAttrib_TexCoord9,
GL_VertexAttrib_COUNT,
GL_VertexAttrib_LAST = GL_VertexAttrib_TexCoord9,
GL_VertexAttrib_BlendWeight0 = GL_VertexAttrib_TexCoord6,
GL_VertexAttrib_BlendIndex0 = GL_VertexAttrib_TexCoord2
}
Functions
U32 hash (register const U8 *k, register U32 length, register U32 initval)
U64 hash64 (register const U8 *k, register U32 length, register U64 initval)
String PathToOS (String file)
Convert file/path name to use OS standard path separator.
String PathToPlatform (String file)
Convert file/path name to use platform standard path separator.
template<class S >
bool read (S &stream, Time *theTime)
Time UnixTimeToTime (U32 t)
Time Win32FileTimeToTime (U32 low, U32 high)
template<class S >
bool write (S &stream, const Time &theTime)
Enumeration Type Documentation
enum Torque::GL_AttributeLocation
Enumerator
GL_VertexAttrib_Position
GL_VertexAttrib_Normal
GL_VertexAttrib_Color
GL_VertexAttrib_Tangent
GL_VertexAttrib_TangentW
GL_VertexAttrib_Binormal
GL_VertexAttrib_TexCoord0
GL_VertexAttrib_TexCoord1
GL_VertexAttrib_TexCoord2
GL_VertexAttrib_TexCoord3
GL_VertexAttrib_TexCoord4
GL_VertexAttrib_TexCoord5
GL_VertexAttrib_TexCoord6
GL_VertexAttrib_TexCoord7
GL_VertexAttrib_TexCoord8
GL_VertexAttrib_TexCoord9
GL_VertexAttrib_COUNT
GL_VertexAttrib_LAST
GL_VertexAttrib_BlendWeight0
GL_VertexAttrib_BlendIndex0
Function Documentation
U32 Torque::hash (register const U8 * k, register U32 length, register U32 initval)
Referenced by DictHash::hash(), SimpleHashTable< T >::insert(), SimpleHashTable< T >::remove(), and SimpleHashTable< T >::retreive().
U64 Torque::hash64 (register const U8 * k, register U32 length, register U64 initval)
template<class S > bool Torque::read (S & stream, Time * theTime) inline
References Torque::Time::Time().
Referenced by Stream::read().
Time Torque::UnixTimeToTime (U32 t) inline
References Torque::Time::Time().
Time Torque::Win32FileTimeToTime (U32 low, U32 high) inline
References Torque::Time::Time().
template<class S > bool Torque::write (S & stream, const Time & theTime) inline
References Torque::Time::getInternalRepresentation().
Referenced by Stream::Put(), Stream::read(), Stream::write(), Stream::writeStringBuffer(), and Stream::writeTabs().
Copyright © GarageGames, LLC. All Rights Reserved.