GuiFrameSetCtrl::FrameDetail Struct Reference
Main Modules Class List Namespace List Online
GuiFrameSetCtrl::FrameDetail Struct Reference
#include <gui/containers/guiFrameCtrl.h>
Public Member Functions
FrameDetail ()
Public Attributes
ColorI mBorderColor
S32 mBorderEnable
S32 mBorderMovable
U32 mBorderWidth
Point2I mMinExtent
RectSpacingI mPadding
Constructor & Destructor Documentation
GuiFrameSetCtrl::FrameDetail::FrameDetail () inline
References GuiFrameSetCtrl::addObject(), GuiFrameSetCtrl::columnOffsets(), GuiFrameSetCtrl::columns(), GuiFrameSetCtrl::DECLARE_CONOBJECT(), GuiFrameSetCtrl::DECLARE_DESCRIPTION(), GuiFrameSetCtrl::DEFAULT_BORDER_WIDTH, GuiFrameSetCtrl::DEFAULT_MIN_FRAME_EXTENT, GuiFrameSetCtrl::FRAME_STATE_AUTO, GuiFrameSetCtrl::GuiFrameSetCtrl(), GuiFrameSetCtrl::initPersistFields(), GuiFrameSetCtrl::onAdd(), GuiFrameSetCtrl::onMouseDown(), GuiFrameSetCtrl::onMouseDragged(), GuiFrameSetCtrl::onMouseUp(), GuiFrameSetCtrl::onRender(), GuiFrameSetCtrl::removeObject(), GuiFrameSetCtrl::resize(), GuiFrameSetCtrl::rowOffsets(), GuiFrameSetCtrl::rows(), Point2I::set(), RectSpacingI::setAll(), and GuiFrameSetCtrl::~GuiFrameSetCtrl().
Member Data Documentation
ColorI GuiFrameSetCtrl::FrameDetail::mBorderColor
S32 GuiFrameSetCtrl::FrameDetail::mBorderEnable
S32 GuiFrameSetCtrl::FrameDetail::mBorderMovable
U32 GuiFrameSetCtrl::FrameDetail::mBorderWidth
Referenced by GuiFrameSetCtrl::borderWidth(), GuiFrameSetCtrl::hitHorizontalDivider(), and GuiFrameSetCtrl::hitVerticalDivider().
Point2I GuiFrameSetCtrl::FrameDetail::mMinExtent
RectSpacingI GuiFrameSetCtrl::FrameDetail::mPadding
Copyright © GarageGames, LLC. All Rights Reserved.