TSTransform Struct Reference
Main Modules Class List Namespace List Online
TSTransform Struct Reference
struct for encapsulating ts transform related static functions
#include <ts/tsTransform.h>
Static Public Member Functions
static void applyScale (F32 scale, MatrixF *)
static void applyScale (const Point3F &scale, MatrixF *)
static void applyScale (const TSScale &scale, MatrixF *)
static Point3F & interpolate (const Point3F &p1, const Point3F &p2, F32 t, Point3F *)
static F32 interpolate (F32 p1, F32 p2, F32 t)
static QuatF & interpolate (const QuatF &q1, const QuatF &q2, F32 t, QuatF *)
static TSScale & interpolate (const TSScale &s1, const TSScale &s2, F32 t, TSScale *)
static void setMatrix (const QuatF &q, MatrixF *)
static void setMatrix (const QuatF &q, const Point3F &p, MatrixF *)
Detailed Description
struct for encapsulating ts transform related static functions
Member Function Documentation
static void TSTransform::applyScale (F32 scale, MatrixF *) static
static void TSTransform::applyScale (const Point3F & scale, MatrixF *) static
static void TSTransform::applyScale (const TSScale & scale, MatrixF *) static
Point3F & TSTransform::interpolate (const Point3F & p1, const Point3F & p2, F32 t, Point3F * p) inline static
References Point3F::x, Point3F::y, and Point3F::z.
Referenced by interpolate().
F32 TSTransform::interpolate (F32 p1, F32 p2, F32 t) inline static
static QuatF& TSTransform::interpolate (const QuatF & q1, const QuatF & q2, F32 t, QuatF *) static
TSScale & TSTransform::interpolate (const TSScale & s1, const TSScale & s2, F32 t, TSScale * s) inline static
References interpolate(), TSScale::mRotate, and TSScale::mScale.
void TSTransform::setMatrix (const QuatF & q, MatrixF * pDest) inline static
References QuatF::setMatrix().
void TSTransform::setMatrix (const QuatF & q, const Point3F & p, MatrixF * pDest) inline static
References MatrixF::setColumn(), and QuatF::setMatrix().
Copyright © GarageGames, LLC. All Rights Reserved.