Dispatcher::MessageQueue Struct Reference
Main Modules Class List Namespace List Online
Dispatcher::MessageQueue Struct Reference
Message System
Internal class for tracking message queues.
#include <util/messaging/dispatcher.h>
Public Member Functions
MessageQueue ()
bool dispatchMessage (const char *event, const char *data)
bool dispatchMessageObject (Message *msg)
bool isEmpty ()
Public Attributes
VectorPtr< IMessageListener * > mListeners
StringTableEntry mQueueName
Detailed Description
Internal class for tracking message queues.
Constructor & Destructor Documentation
Dispatcher::MessageQueue::MessageQueue () inline
Member Function Documentation
bool Dispatcher::MessageQueue::dispatchMessage (const char * event, const char * data) inline
References VectorPtr< T >::begin(), and VectorPtr< T >::end().
bool Dispatcher::MessageQueue::dispatchMessageObject (Message * msg) inline
References VectorPtr< T >::begin(), Dispatcher::dispatchMessage(), Dispatcher::dispatchMessageObject(), VectorPtr< T >::end(), Dispatcher::getMessageQueue(), Dispatcher::isQueueRegistered(), Dispatcher::lockDispatcherMutex(), Dispatcher::registerAnonMessageQueue(), Dispatcher::registerMessageListener(), Dispatcher::registerMessageQueue(), Dispatcher::unlockDispatcherMutex(), Dispatcher::unregisterMessageListener(), and Dispatcher::unregisterMessageQueue().
bool Dispatcher::MessageQueue::isEmpty (void) inline
Member Data Documentation
VectorPtr<IMessageListener *> Dispatcher::MessageQueue::mListeners
StringTableEntry Dispatcher::MessageQueue::mQueueName
Copyright © GarageGames, LLC. All Rights Reserved.