StaticNamedSingleton< T > Struct Template Reference
Main Modules Class List Namespace List Online
StaticNamedSingleton< T > Struct Template Reference
Collection of statically registered named singletons.
#include <core/util/namedSingleton.h>
Public Types
typedef StaticNamedSingleton This
Public Member Functions
StaticNamedSingleton (const char *name)
virtual ~StaticNamedSingleton ()
const char * getName ()
T * getNext ()
Static Public Member Functions
static EnumTable * staticCreateEnumTable ()
Create a TorqueScript EnumTable that contains all registered instance names.
static T * staticFindSingleton (const char *name)
Find the instance with the given name.
static T * staticGetFirst ()
static U32 staticGetNumSingletons ()
Return the number of registered named singletons.
Detailed Description
template<class T>
struct StaticNamedSingleton< T >
Collection of statically registered named singletons.
This class is useful as a mix-in for classes that are supposed to represent a range of named singleton instances from which a specific instance is then selected at run-time.
Parameters
T Arbitrary type parameter; identical types will share static data.
Member Typedef Documentation
template<class T> typedef StaticNamedSingleton StaticNamedSingleton< T >::This
Constructor & Destructor Documentation
template<class T > StaticNamedSingleton< T >::StaticNamedSingleton (const char * name)
template<class T> virtual StaticNamedSingleton< T >::~StaticNamedSingleton () inline virtual
References StaticNamedSingleton< T >::getName(), StaticNamedSingleton< T >::getNext(), StaticNamedSingleton< T >::staticCreateEnumTable(), StaticNamedSingleton< T >::staticFindSingleton(), StaticNamedSingleton< T >::staticGetFirst(), StaticNamedSingleton< T >::staticGetNumSingletons(), and T.
Member Function Documentation
template<class T > const char * StaticNamedSingleton< T >::getName () inline
Referenced by StaticNamedSingleton< T >::staticCreateEnumTable(), and StaticNamedSingleton< T >::~StaticNamedSingleton().
template<class T > T * StaticNamedSingleton< T >::getNext () inline
References T.
Referenced by StaticNamedSingleton< T >::~StaticNamedSingleton().
template<class T > EnumTable * StaticNamedSingleton< T >::staticCreateEnumTable () static
Create a TorqueScript EnumTable that contains all registered instance names.
References StaticNamedSingleton< T >::getName(), and StaticNamedSingleton< T >::staticGetNumSingletons().
Referenced by StaticNamedSingleton< T >::~StaticNamedSingleton().
template<class T > T * StaticNamedSingleton< T >::staticFindSingleton (const char * name) static
Find the instance with the given name.
Returns NULL if no such instance exists.
References T.
Referenced by StaticNamedSingleton< T >::~StaticNamedSingleton().
template<class T > T * StaticNamedSingleton< T >::staticGetFirst () static
References T.
Referenced by StaticNamedSingleton< T >::~StaticNamedSingleton().
template<class T > U32 StaticNamedSingleton< T >::staticGetNumSingletons () static
Return the number of registered named singletons.
Referenced by StaticNamedSingleton< T >::staticCreateEnumTable(), and StaticNamedSingleton< T >::~StaticNamedSingleton().
Copyright © GarageGames, LLC. All Rights Reserved.