LangElement Struct Reference
Main Modules Class List Namespace List Online
LangElement Struct Reference
#include <shaderGen/langElement.h>
Public Member Functions
LangElement ()
virtual ~LangElement ()
virtual void print (Stream &stream)
void setName (const char *newName)
Static Public Member Functions
static void deleteElements ()
static LangElement * find (const char *name)
Public Attributes
U8 name [32]
Static Public Attributes
static Vector< LangElement * > elementList
Detailed Description
The LangElement class is the base building block for procedurally generated shader code. LangElement and its subclasses are strung together using the static Vector 'elementList'. When a shader needs to be written to disk, the elementList is traversed and print() is called on each LangElement and the shader is output. elementList is cleared after each shader is printed out.
Constructor & Destructor Documentation
LangElement::LangElement ()
virtual LangElement::~LangElement () inline virtual
Member Function Documentation
static void LangElement::deleteElements () static
static LangElement* LangElement::find (const char * name) static
Referenced by AccuScaleFeature::processPix(), AccuDirectionFeature::processPix(), AccuStrengthFeature::processPix(), AccuCoverageFeature::processPix(), and AccuSpecularFeature::processPix().
virtual void LangElement::print (Stream & stream) inline virtual
Reimplemented in MultiLine, GenOp, Var, EchoOp, and DecOp.
References setName().
Referenced by MultiLine::MultiLine().
void LangElement::setName (const char * newName)
Referenced by print(), AccuScaleFeature::processPix(), AccuDirectionFeature::processPix(), AccuStrengthFeature::processPix(), AccuCoverageFeature::processPix(), and AccuSpecularFeature::processPix().
Member Data Documentation
Vector<LangElement*> LangElement::elementList static
U8 LangElement::name[32]
Copyright © GarageGames, LLC. All Rights Reserved.