rapidjson::GenericValue< Encoding, Allocator > Class Template Reference
Main Modules Class List Namespace List Online
rapidjson::GenericValue< Encoding, Allocator > Class Template Reference
Represents a JSON value. Use Value for UTF8 encoding and default allocator.
#include <persistence/rapidjson/document.h>
Classes
struct Member
Name-value pair in an object.
Public Types
typedef Allocator AllocatorType
Allocator type from template parameter.
typedef Encoding::Ch Ch
Character type derived from Encoding.
typedef const Member * ConstMemberIterator
Constant member iterator for iterating in object.
typedef const GenericValue * ConstValueIterator
Constant value iterator for iterating in array.
typedef Encoding EncodingType
Encoding type from template parameter.
typedef Member * MemberIterator
Member iterator for iterating in object.
typedef GenericValue * ValueIterator
Value iterator for iterating in array.
Public Member Functions
template<typename Handler >
const GenericValue & Accept (Handler &handler) const
Generate events of this value to a Handler.
Assignment operators
GenericValue & operator= (GenericValue &rhs)
Assignment with move semantics.
template<typename T >
GenericValue & operator= (T value)
Assignment with primitive types.
Type
Type GetType () const
bool IsNull () const
bool IsFalse () const
bool IsTrue () const
bool IsBool () const
bool IsObject () const
bool IsArray () const
bool IsNumber () const
bool IsInt () const
bool IsUint () const
bool IsInt64 () const
bool IsUint64 () const
bool IsDouble () const
bool IsString () const
Null
GenericValue & SetNull ()
Bool
bool GetBool () const
GenericValue & SetBool (bool b)
Object
GenericValue & SetObject ()
Set this value as an empty object.
GenericValue & operator[] (const Ch *name)
Get the value associated with the name.
const GenericValue & operator[] (const Ch *name) const
ConstMemberIterator MemberBegin () const
Member iterators.
ConstMemberIterator MemberEnd () const
MemberIterator MemberBegin ()
MemberIterator MemberEnd ()
bool HasMember (const Ch *name) const
Check whether a member exists in the object.
Member * FindMember (const Ch *name)
Find member by name.
const Member * FindMember (const Ch *name) const
GenericValue & AddMember (GenericValue &name, GenericValue &value, Allocator &allocator)
Add a member (name-value pair) to the object.
GenericValue & AddMember (const Ch *name, Allocator &nameAllocator, GenericValue &value, Allocator &allocator)
GenericValue & AddMember (const Ch *name, GenericValue &value, Allocator &allocator)
template<typename T >
GenericValue & AddMember (const Ch *name, T value, Allocator &allocator)
bool RemoveMember (const Ch *name)
Remove a member in object by its name.
Array
GenericValue & SetArray ()
Set this value as an empty array.
SizeType Size () const
Get the number of elements in array.
SizeType Capacity () const
Get the capacity of array.
bool Empty () const
Check whether the array is empty.
void Clear ()
Remove all elements in the array.
GenericValue & operator[] (SizeType index)
Get an element from array by index.
const GenericValue & operator[] (SizeType index) const
ValueIterator Begin ()
Element iterator.
ValueIterator End ()
ConstValueIterator Begin () const
ConstValueIterator End () const
GenericValue & Reserve (SizeType newCapacity, Allocator &allocator)
Request the array to have enough capacity to store elements.
GenericValue & PushBack (GenericValue &value, Allocator &allocator)
Append a value at the end of the array.
template<typename T >
GenericValue & PushBack (T value, Allocator &allocator)
GenericValue & PopBack ()
Remove the last element in the array.
Number
int GetInt () const
unsigned GetUint () const
int64_t GetInt64 () const
uint64_t GetUint64 () const
double GetDouble () const
GenericValue & SetInt (int i)
GenericValue & SetUint (unsigned u)
GenericValue & SetInt64 (int64_t i64)
GenericValue & SetUint64 (uint64_t u64)
GenericValue & SetDouble (double d)
String
const Ch * GetString () const
SizeType GetStringLength () const
Get the length of string.
GenericValue & SetString (const Ch *s, SizeType length)
Set this value as a string without copying source string.
GenericValue & SetString (const Ch *s)
Set this value as a string without copying source string.
GenericValue & SetString (const Ch *s, SizeType length, Allocator &allocator)
Set this value as a string by copying from source string.
GenericValue & SetString (const Ch *s, Allocator &allocator)
Set this value as a string by copying from source string.
Constructors and destructor.
GenericValue ()
Default constructor creates a null value.
GenericValue (Type type)
Constructor with JSON value type.
GenericValue (bool b)
Constructor for boolean value.
GenericValue (int i)
Constructor for int value.
GenericValue (unsigned u)
Constructor for unsigned value.
GenericValue (int64_t i64)
Constructor for int64_t value.
GenericValue (uint64_t u64)
Constructor for uint64_t value.
GenericValue (double d)
Constructor for double value.
GenericValue (const Ch *s, SizeType length)
Constructor for constant string (i.e. do not make a copy of string)
GenericValue (const Ch *s)
Constructor for constant string (i.e. do not make a copy of string)
GenericValue (const Ch *s, SizeType length, Allocator &allocator)
Constructor for copy-string (i.e. do make a copy of string)
GenericValue (const Ch *s, Allocator &allocator)
Constructor for copy-string (i.e. do make a copy of string)
~GenericValue ()
Destructor.
Detailed Description
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>>
class rapidjson::GenericValue< Encoding, Allocator >
Represents a JSON value. Use Value for UTF8 encoding and default allocator.
A JSON value can be one of 7 types. This class is a variant type supporting these types.
Use the Value if UTF8 and default allocator
Template Parameters
Encoding Encoding of the value. (Even non-string values need to have the same encoding in a document)
Allocator Allocator type for allocating memory of object, array and string.
Member Typedef Documentation
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> typedef Allocator rapidjson::GenericValue< Encoding, Allocator >::AllocatorType
Allocator type from template parameter.
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> typedef Encoding::Ch rapidjson::GenericValue< Encoding, Allocator >::Ch
Character type derived from Encoding.
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> typedef const Member* rapidjson::GenericValue< Encoding, Allocator >::ConstMemberIterator
Constant member iterator for iterating in object.
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> typedef const GenericValue* rapidjson::GenericValue< Encoding, Allocator >::ConstValueIterator
Constant value iterator for iterating in array.
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> typedef Encoding rapidjson::GenericValue< Encoding, Allocator >::EncodingType
Encoding type from template parameter.
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> typedef Member* rapidjson::GenericValue< Encoding, Allocator >::MemberIterator
Member iterator for iterating in object.
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> typedef GenericValue* rapidjson::GenericValue< Encoding, Allocator >::ValueIterator
Value iterator for iterating in array.
Constructor & Destructor Documentation
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue () inline
Default constructor creates a null value.
Referenced by rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::GenericValue(), rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::operator=(), rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::SetArray(), rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::SetBool(), rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::SetDouble(), rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::SetInt(), rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::SetInt64(), rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::SetNull(), rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::SetObject(), rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::SetUint(), and rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::SetUint64().
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue (Type type) inline
Constructor with JSON value type.
This creates a Value of specified type with default content.
Parameters
type Type of the value.
Note
Default content for number is zero.
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue (bool b) inline
Constructor for boolean value.
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue (int i) inline
Constructor for int value.
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue (unsigned u) inline
Constructor for unsigned value.
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue (int64_t i64) inline
Constructor for int64_t value.
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue (uint64_t u64) inline
Constructor for uint64_t value.
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue (double d) inline
Constructor for double value.
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue (const Ch * s, SizeType length) inline
Constructor for constant string (i.e. do not make a copy of string)
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue (const Ch * s) inline
Constructor for constant string (i.e. do not make a copy of string)
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue (const Ch * s, SizeType length, Allocator & allocator) inline
Constructor for copy-string (i.e. do make a copy of string)
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue (const Ch * s, Allocator & allocator) inline
Constructor for copy-string (i.e. do make a copy of string)
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> rapidjson::GenericValue< Encoding, Allocator >::~GenericValue () inline
Destructor.
Need to destruct elements of array, members of object, or copy-string.
Referenced by rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::operator=(), rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::SetArray(), rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::SetBool(), rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::SetDouble(), rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::SetInt(), rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::SetInt64(), rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::SetNull(), rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::SetObject(), rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::SetString(), rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::SetUint(), and rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::SetUint64().
Member Function Documentation
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> template<typename Handler > const GenericValue& rapidjson::GenericValue< Encoding, Allocator >::Accept (Handler & handler) const inline
Generate events of this value to a Handler.
This function adopts the GoF visitor pattern. Typical usage is to output this JSON value as JSON text via Writer, which is a Handler. It can also be used to deep clone this value via GenericDocument, which is also a Handler.
Template Parameters
Handler type of handler.
Parameters
handler An object implementing concept Handler.
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::AddMember (GenericValue< Encoding, Allocator > & name, GenericValue< Encoding, Allocator > & value, Allocator & allocator) inline
Add a member (name-value pair) to the object.
Parameters
name A string value as name of member.
value Value of any type.
allocator Allocator for reallocating memory.
Returns
The value itself for fluent API.
Note
The ownership of name and value will be transfered to this object if success.
Referenced by rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::AddMember().
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::AddMember (const Ch * name, Allocator & nameAllocator, GenericValue< Encoding, Allocator > & value, Allocator & allocator) inline
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::AddMember (const Ch * name, GenericValue< Encoding, Allocator > & value, Allocator & allocator) inline
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> template<typename T > GenericValue& rapidjson::GenericValue< Encoding, Allocator >::AddMember (const Ch * name, T value, Allocator & allocator) inline
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> ValueIterator rapidjson::GenericValue< Encoding, Allocator >::Begin () inline
Element iterator.
Referenced by rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::Begin().
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> ConstValueIterator rapidjson::GenericValue< Encoding, Allocator >::Begin () const inline
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> SizeType rapidjson::GenericValue< Encoding, Allocator >::Capacity () const inline
Get the capacity of array.
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> void rapidjson::GenericValue< Encoding, Allocator >::Clear () inline
Remove all elements in the array.
This function do not deallocate memory in the array, i.e. the capacity is unchanged.
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> bool rapidjson::GenericValue< Encoding, Allocator >::Empty () const inline
Check whether the array is empty.
Referenced by rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::PopBack().
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> ValueIterator rapidjson::GenericValue< Encoding, Allocator >::End () inline
Referenced by rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::End().
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> ConstValueIterator rapidjson::GenericValue< Encoding, Allocator >::End () const inline
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> Member* rapidjson::GenericValue< Encoding, Allocator >::FindMember (const Ch * name) inline
Find member by name.
Returns
Return the member if exists. Otherwise returns null pointer.
Referenced by rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::FindMember(), rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::HasMember(), rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::operator[](), and rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::RemoveMember().
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> const Member* rapidjson::GenericValue< Encoding, Allocator >::FindMember (const Ch * name) const inline
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> bool rapidjson::GenericValue< Encoding, Allocator >::GetBool () const inline
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> double rapidjson::GenericValue< Encoding, Allocator >::GetDouble () const inline
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> int rapidjson::GenericValue< Encoding, Allocator >::GetInt () const inline
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> int64_t rapidjson::GenericValue< Encoding, Allocator >::GetInt64 () const inline
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> const Ch* rapidjson::GenericValue< Encoding, Allocator >::GetString () const inline
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> SizeType rapidjson::GenericValue< Encoding, Allocator >::GetStringLength () const inline
Get the length of string.
Since rapidjson permits "\u0000" in the json string, strlen(v.GetString()) may not equal to v.GetStringLength().
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> Type rapidjson::GenericValue< Encoding, Allocator >::GetType () const inline
Referenced by rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::Accept().
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> unsigned rapidjson::GenericValue< Encoding, Allocator >::GetUint () const inline
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> uint64_t rapidjson::GenericValue< Encoding, Allocator >::GetUint64 () const inline
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> bool rapidjson::GenericValue< Encoding, Allocator >::HasMember (const Ch * name) const inline
Check whether a member exists in the object.
Note
It is better to use FindMember() directly if you need the obtain the value as well.
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> bool rapidjson::GenericValue< Encoding, Allocator >::IsArray () const inline
Referenced by rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::Begin(), rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::Capacity(), rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::Clear(), rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::Empty(), rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::End(), rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::operator[](), rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::PopBack(), rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::PushBack(), rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::Reserve(), and rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::Size().
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> bool rapidjson::GenericValue< Encoding, Allocator >::IsBool () const inline
Referenced by rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::GetBool().
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> bool rapidjson::GenericValue< Encoding, Allocator >::IsDouble () const inline
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> bool rapidjson::GenericValue< Encoding, Allocator >::IsFalse () const inline
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> bool rapidjson::GenericValue< Encoding, Allocator >::IsInt () const inline
Referenced by rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::Accept().
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> bool rapidjson::GenericValue< Encoding, Allocator >::IsInt64 () const inline
Referenced by rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::Accept().
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> bool rapidjson::GenericValue< Encoding, Allocator >::IsNull () const inline
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> bool rapidjson::GenericValue< Encoding, Allocator >::IsNumber () const inline
Referenced by rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::GetDouble().
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> bool rapidjson::GenericValue< Encoding, Allocator >::IsObject () const inline
Referenced by rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::AddMember(), rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::FindMember(), rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::MemberBegin(), rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::MemberEnd(), and rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::RemoveMember().
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> bool rapidjson::GenericValue< Encoding, Allocator >::IsString () const inline
Referenced by rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::AddMember(), rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::GetString(), and rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::GetStringLength().
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> bool rapidjson::GenericValue< Encoding, Allocator >::IsTrue () const inline
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> bool rapidjson::GenericValue< Encoding, Allocator >::IsUint () const inline
Referenced by rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::Accept().
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> bool rapidjson::GenericValue< Encoding, Allocator >::IsUint64 () const inline
Referenced by rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::Accept().
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> ConstMemberIterator rapidjson::GenericValue< Encoding, Allocator >::MemberBegin () const inline
Member iterators.
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> MemberIterator rapidjson::GenericValue< Encoding, Allocator >::MemberBegin () inline
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> ConstMemberIterator rapidjson::GenericValue< Encoding, Allocator >::MemberEnd () const inline
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> MemberIterator rapidjson::GenericValue< Encoding, Allocator >::MemberEnd () inline
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::operator= (GenericValue< Encoding, Allocator > & rhs) inline
Assignment with move semantics.
Parameters
rhs Source of the assignment. It will become a null value after assignment.
Referenced by rapidjson::GenericDocument< Encoding, Allocator >::EndArray().
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> template<typename T > GenericValue& rapidjson::GenericValue< Encoding, Allocator >::operator= (T value) inline
Assignment with primitive types.
Template Parameters
T Either Type, int, unsigned, int64_t, uint64_t, const Ch*
Parameters
value The value to be assigned.
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::operator[] (const Ch * name) inline
Get the value associated with the name.
Note
In version 0.1x, if the member is not found, this function returns a null value. This makes issue 7. Since 0.2, if the name is not correct, it will assert. If user is unsure whether a member exists, user should use HasMember() first. A better approach is to use the now public FindMember().
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> const GenericValue& rapidjson::GenericValue< Encoding, Allocator >::operator[] (const Ch * name) const inline
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::operator[] (SizeType index) inline
Get an element from array by index.
Parameters
index Zero-based index of element.
Note
Value a(kArrayType);
a.PushBack(123);
int x = a[0].GetInt();           // Error: operator[ is ambiguous, as 0 also mean a null pointer of const char* type.
int y = a[SizeType(0)].GetInt(); // Cast to SizeType will work.
int z = a[0u].GetInt();          // This works too.
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> const GenericValue& rapidjson::GenericValue< Encoding, Allocator >::operator[] (SizeType index) const inline
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::PopBack () inline
Remove the last element in the array.
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::PushBack (GenericValue< Encoding, Allocator > & value, Allocator & allocator) inline
Append a value at the end of the array.
Parameters
value The value to be appended.
allocator The allocator for allocating memory. It must be the same one use previously.
Returns
The value itself for fluent API.
Note
The ownership of the value will be transfered to this object if success.
If the number of elements to be appended is known, calls Reserve() once first may be more efficient.
Referenced by rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::PushBack().
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> template<typename T > GenericValue& rapidjson::GenericValue< Encoding, Allocator >::PushBack (T value, Allocator & allocator) inline
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> bool rapidjson::GenericValue< Encoding, Allocator >::RemoveMember (const Ch * name) inline
Remove a member in object by its name.
Parameters
name Name of member to be removed.
Returns
Whether the member existed.
Note
Removing member is implemented by moving the last member. So the ordering of members is changed.
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::Reserve (SizeType newCapacity, Allocator & allocator) inline
Request the array to have enough capacity to store elements.
Parameters
newCapacity The capacity that the array at least need to have.
allocator The allocator for allocating memory. It must be the same one use previously.
Returns
The value itself for fluent API.
Referenced by rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::PushBack().
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::SetArray () inline
Set this value as an empty array.
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::SetBool (bool b) inline
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::SetDouble (double d) inline
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::SetInt (int i) inline
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::SetInt64 (int64_t i64) inline
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::SetNull () inline
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::SetObject () inline
Set this value as an empty object.
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::SetString (const Ch * s, SizeType length) inline
Set this value as a string without copying source string.
This version has better performance with supplied length, and also support string containing null character.
Parameters
s source string pointer.
length The length of source string, excluding the trailing null terminator.
Returns
The value itself for fluent API.
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::SetString (const Ch * s) inline
Set this value as a string without copying source string.
Parameters
s source string pointer.
Returns
The value itself for fluent API.
Referenced by rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::SetString().
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::SetString (const Ch * s, SizeType length, Allocator & allocator) inline
Set this value as a string by copying from source string.
This version has better performance with supplied length, and also support string containing null character.
Parameters
s source string.
length The length of source string, excluding the trailing null terminator.
allocator Allocator for allocating copied buffer. Commonly use document.GetAllocator().
Returns
The value itself for fluent API.
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::SetString (const Ch * s, Allocator & allocator) inline
Set this value as a string by copying from source string.
Parameters
s source string.
allocator Allocator for allocating copied buffer. Commonly use document.GetAllocator().
Returns
The value itself for fluent API.
Referenced by rapidjson::GenericValue< rapidjson::Encoding, rapidjson::Allocator >::SetString().
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::SetUint (unsigned u) inline
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::SetUint64 (uint64_t u64) inline
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>> SizeType rapidjson::GenericValue< Encoding, Allocator >::Size () const inline
Get the number of elements in array.
Copyright © GarageGames, LLC. All Rights Reserved.