String::StrFormat Class Reference
Main Modules Class List Namespace List Online
String::StrFormat Class Reference
An internal support class for ToString().
#include <core/util/str.h>
Public Member Functions
StrFormat ()
StrFormat (const char *formatStr, va_list args)
~StrFormat ()
S32 append (const char *str, S32 len)
S32 append (const char *str)
const char * c_str () const
char * copy (char *buffer) const
Copy the formatted string into the output buffer which must be at least size() characters.
S32 format (const char *format, va_list args)
S32 formatAppend (const char *format, va_list args)
String getString ()
U32 length () const
Return the length of the formated string (does not include the terminating 0)
void reset ()
Public Attributes
char * _dynamicBuffer
U32 _dynamicSize
char _fixedBuffer [2048]
U32 _len
Detailed Description
An internal support class for ToString().
StrFormat manages the formatting of arbitrary length strings. The class starts with a default internal fixed size buffer and moves to dynamic allocation from the heap when that is exceeded. Constructing the class on the stack will result in its most efficient use. This class is meant to be used as a helper class, and not for the permanent storage of string data.
char* indexString(U32 index)
{
   StrFormat format("Index: %d",index);
   char* str = new char[format.size()];
   format.copy(str);
   return str;
}
Constructor & Destructor Documentation
String::StrFormat::StrFormat () inline
References _fixedBuffer.
String::StrFormat::StrFormat (const char * formatStr, va_list args) inline
References append(), format(), formatAppend(), and ~StrFormat().
String::StrFormat::~StrFormat ()
Referenced by StrFormat().
Member Function Documentation
S32 String::StrFormat::append (const char * str, S32 len)
Referenced by StringBuilder::append(), and StrFormat().
S32 String::StrFormat::append (const char * str)
const char* String::StrFormat::c_str () const inline
References _dynamicBuffer, and _fixedBuffer.
Referenced by StringBuilder::data(), and getString().
char* String::StrFormat::copy (char * buffer) const
Copy the formatted string into the output buffer which must be at least size() characters.
Referenced by StringBuilder::copy(), and reset().
S32 String::StrFormat::format (const char * format, va_list args)
Referenced by StrFormat().
S32 String::StrFormat::formatAppend (const char * format, va_list args)
Referenced by StringBuilder::format(), and StrFormat().
String String::StrFormat::getString () inline
References _len, c_str(), and String::String().
Referenced by StringBuilder::end().
U32 String::StrFormat::length () const inline
Return the length of the formated string (does not include the terminating 0)
References _fixedBuffer, and _len.
Referenced by StringBuilder::length().
void String::StrFormat::reset (void) inline
References _fixedBuffer, _len, and copy().
Member Data Documentation
char* String::StrFormat::_dynamicBuffer
Referenced by c_str().
U32 String::StrFormat::_dynamicSize
char String::StrFormat::_fixedBuffer[2048]
Referenced by c_str(), length(), reset(), and StrFormat().
U32 String::StrFormat::_len
Referenced by getString(), length(), and reset().
Copyright © GarageGames, LLC. All Rights Reserved.