ManagedSingleton< T > Class Template Reference
Main Modules Class List Namespace List Online
ManagedSingleton< T > Class Template Reference
This is a managed singleton class with explict creation and destruction functions which must be called at startup and shutdown of the engine.
#include <core/util/tSingleton.h>
Static Public Member Functions
static void createSingleton ()
Create the singleton instance.
static void deleteSingleton ()
Destroy the singleton instance.
static T * instance ()
Return the singleton instance.
static T * instanceOrNull ()
Return the singleton instance or NULL if it has been deleted or not yet constructed.
Detailed Description
template<typename T>
class ManagedSingleton< T >
This is a managed singleton class with explict creation and destruction functions which must be called at startup and shutdown of the engine.
Your class to be managed must implement the following function:
static const char* getSingletonName() { return "YourClassName"; }
This allow us to provide better asserts.
Member Function Documentation
template<typename T> static void ManagedSingleton< T >::createSingleton () inline static
Create the singleton instance.
Note
Asserts when the singleton instance has already been constructed.
template<typename T> static void ManagedSingleton< T >::deleteSingleton () inline static
Destroy the singleton instance.
Note
Asserts when no singleton has been constructed.
template<typename T> static T* ManagedSingleton< T >::instance () inline static
Return the singleton instance.
Note
Asserts when called before createSingleton().
Referenced by ThreadManager::addThread(), ThreadManager::getThreadById(), and ThreadManager::removeThread().
template<typename T> static T* ManagedSingleton< T >::instanceOrNull () inline static
Return the singleton instance or NULL if it has been deleted or not yet constructed.
Copyright © GarageGames, LLC. All Rights Reserved.