MemStream Class Reference
Main Modules Class List Namespace List Online
MemStream Class Reference
The MemStream class is used to read and write to a memory buffer.
#include <core/stream/memStream.h>
Public Member Functions
MemStream (U32 growSize, bool allowRead=true, bool allowWrite=true)
This constructs an empty memory stream that will grow in increments as needed.
MemStream (U32 bufferSize, void *buffer, bool allowRead=true, bool allowWrite=true)
This constructs the stream with a fixed size memory buffer.
virtual ~MemStream ()
The destructor.
void * getBuffer ()
Returns the memory buffer.
const void * getBuffer () const
U32 getPosition () const
Gets the position in the stream.
U32 getStreamSize ()
Gets the size of the stream.
bool hasCapability (const Capability caps) const
Checks to see if this stream has the capability of a given function.
bool setPosition (const U32 in_newPosition)
Sets the position of the stream. Returns if the new position is valid or not.
void * takeBuffer ()
Takes the memory buffer reseting the stream.
Public Member Functions inherited from Stream
Stream ()
virtual ~Stream ()
virtual Stream * clone () const
Create an exact replica of this stream.
bool copyFrom (Stream *other)
Copy the contents of another stream into this one.
Stream::StreamStatus getStatus () const
Gets the status of the stream.
bool Put (char character)
void read (String *str)
bool read (ColorI *)
Read an integral color from the stream.
bool read (ColorF *)
Read a floating point color from the stream.
bool read (NetAddress *)
Read a network address from the stream.
bool read (NetSocket *)
Read a network socket from the stream.
bool read (RawData *)
Read some raw data from the stream.
bool read (Torque::ByteBuffer *)
Read some raw data from the stream.
bool read (const U32 in_numBytes, void *out_pBuffer)
bool read (bool *out_pRead)
void readLine (U8 *buffer, U32 bufferSize)
Reads a line from the stream.
void readLongString (U32 maxStringLen, char *stringBuf)
Reads a string that could potentially be more than 255 characters long.
virtual void readString (char stringBuf[256])
Reads a string of maximum 255 characters long.
const char * readSTString (bool casesens=false)
Reads a string and inserts it into the StringTable.
void write (const String &str)
bool write (const ColorI &)
Write an integral color to the stream.
bool write (const ColorF &)
Write a floating point color to the stream.
bool write (const NetAddress &)
Write a network address to the stream.
bool write (const NetSocket &)
Write a network socket to the stream.
bool write (const RawData &)
Write some raw data onto the stream.
bool write (const Torque::ByteBuffer &)
Write some raw data onto the stream.
bool write (const U32 in_numBytes, const void *in_pBuffer)
bool write (const bool &in_rWrite)
bool writeFormattedBuffer (const char *format,...)
Writes a formatted buffer to the stream.
void writeLine (const U8 *buffer)
writes a line to the stream
void writeLongString (U32 maxStringLen, const char *string)
Writes a string to the stream.
virtual void writeString (const char *stringBuf, S32 maxLen=255)
Writes a string to the stream.
bool writeStringBuffer (const char *buffer)
Writes a NULL terminated string buffer.
void writeTabs (U32 count)
Write a number of tabs to this stream.
void writeText (const char *text)
Write raw text to the stream.
Protected Member Functions
bool _read (const U32 in_numBytes, void *out_pBuffer)
bool _write (const U32 in_numBytes, const void *in_pBuffer)
Protected Member Functions inherited from Stream
virtual void _read (String *str)
virtual void _write (const String &str)
void setStatus (const StreamStatus in_newStatus)
Protected Attributes
void * mBufferBase
The memory buffer.
U32 mBufferSize
The actual size of the memory buffer.
U32 mCurrentPosition
Our current read/write position within the buffer.
U32 mGrowSize
The amount to grow the buffer when we run out of space writing to the stream.
U32 mInstCaps
bool mOwnsMemory
If true the memory is owned by the steam and it will be deleted in the destructor.
U32 mStreamSize
The size of the data in the stream.
Additional Inherited Members
Public Types inherited from Stream
enum Capability {
StreamWrite = BIT(0),
StreamRead = BIT(1),
StreamPosition = BIT(2)
}
enum StreamStatus {
Ok = 0,
IOError,
EOS,
IllegalCall,
Closed,
UnknownError
}
Status constants for the stream.
Static Public Member Functions inherited from Stream
static const char * getStatusString (const StreamStatus in_status)
Gets a printable string form of the status.
Detailed Description
The MemStream class is used to read and write to a memory buffer.
Constructor & Destructor Documentation
MemStream::MemStream (U32 growSize, bool allowRead = true, bool allowWrite = true)
This constructs an empty memory stream that will grow in increments as needed.
MemStream::MemStream (U32 bufferSize, void * buffer, bool allowRead = true, bool allowWrite = true)
This constructs the stream with a fixed size memory buffer.
If buffer is null then it will be allocated for you.
virtual MemStream::~MemStream () virtual
The destructor.
Member Function Documentation
bool MemStream::_read (const U32 in_numBytes, void * out_pBuffer) protected virtual
Implements Stream.
bool MemStream::_write (const U32 in_numBytes, const void * in_pBuffer) protected virtual
Implements Stream.
void* MemStream::getBuffer () inline
Returns the memory buffer.
References mBufferBase.
Referenced by Px3MemOutStream::getData().
const void* MemStream::getBuffer () const inline
References mBufferBase, and takeBuffer().
U32 MemStream::getPosition () const virtual
Gets the position in the stream.
Implements Stream.
U32 MemStream::getStreamSize () virtual
Gets the size of the stream.
Implements Stream.
Referenced by Px3MemOutStream::getSize().
bool MemStream::hasCapability (const Capability caps) const virtual
Checks to see if this stream has the capability of a given function.
Implements Stream.
bool MemStream::setPosition (const U32 in_newPosition) virtual
Sets the position of the stream. Returns if the new position is valid or not.
Implements Stream.
void* MemStream::takeBuffer ()
Takes the memory buffer reseting the stream.
Referenced by getBuffer().
Member Data Documentation
void* MemStream::mBufferBase protected
The memory buffer.
Referenced by getBuffer().
U32 MemStream::mBufferSize protected
The actual size of the memory buffer.
It is always greater than or equal to the mStreamSize.
U32 MemStream::mCurrentPosition protected
Our current read/write position within the buffer.
U32 MemStream::mGrowSize protected
The amount to grow the buffer when we run out of space writing to the stream.
U32 MemStream::mInstCaps protected
bool MemStream::mOwnsMemory protected
If true the memory is owned by the steam and it will be deleted in the destructor.
U32 MemStream::mStreamSize protected
The size of the data in the stream.
It is always less than or equal to the mBufferSize.
Copyright © GarageGames, LLC. All Rights Reserved.