_TorqueThreadStaticReg Class Reference
Main Modules Class List Namespace List Online
_TorqueThreadStaticReg Class Reference
#include <core/threadStatic.h>
Public Member Functions
_TorqueThreadStaticReg (_TorqueThreadStatic *ttsInitial)
Constructor.
virtual ~_TorqueThreadStaticReg ()
const _TorqueThreadStaticReg * getNext () const
Static Public Member Functions
static void destroyInstance (TorqueThreadStaticList *instanceList)
static void destroyInstances ()
static const _TorqueThreadStaticReg * getFirst ()
static const TorqueThreadStaticList & getStaticList (const U32 idx=0)
static TorqueThreadStaticListHandle spawnThreadStaticsInstance ()
Spawn another copy of the ThreadStatics and pass back the id.
Constructor & Destructor Documentation
_TorqueThreadStaticReg::_TorqueThreadStaticReg (_TorqueThreadStatic * ttsInitial) inline
Constructor.
References Vector< T >::increment(), _TorqueThreadStatic::mListIndex, Vector< T >::push_back(), and Vector< T >::size().
virtual _TorqueThreadStaticReg::~_TorqueThreadStaticReg () virtual
Member Function Documentation
static void _TorqueThreadStaticReg::destroyInstance (TorqueThreadStaticList * instanceList) static
static void _TorqueThreadStaticReg::destroyInstances () static
static const _TorqueThreadStaticReg* _TorqueThreadStaticReg::getFirst () inline static
const _TorqueThreadStaticReg* _TorqueThreadStaticReg::getNext () const inline
static const TorqueThreadStaticList& _TorqueThreadStaticReg::getStaticList (const U32 idx = 0) inline static
static TorqueThreadStaticListHandle _TorqueThreadStaticReg::spawnThreadStaticsInstance () static
Spawn another copy of the ThreadStatics and pass back the id.
Copyright © GarageGames, LLC. All Rights Reserved.