TSShapeLoader Class Reference
Main Modules Class List Namespace List Online
TSShapeLoader Class Reference abstract
#include <ts/loader/tsShapeLoader.h>
Classes
struct ShapeFormat
struct Subshape
Public Types
enum eLoadPhases {
Load_ReadFile = 0,
Load_ParseFile,
Load_ExternalRefs,
Load_EnumerateScene,
Load_GenerateSubshapes,
Load_GenerateObjects,
Load_GenerateDefaultStates,
Load_GenerateSkins,
Load_GenerateMaterials,
Load_GenerateSequences,
Load_InitShape,
NumLoadPhases,
Load_Complete = NumLoadPhases
}
Public Member Functions
TSShapeLoader ()
virtual ~TSShapeLoader ()
TSShape * generateShape (const Torque::Path &path)
Static Public Member Functions
static void addFormat (String name, String extension)
static String getFormatExtensions ()
static String getFormatFilters ()
static const Torque::Path & getShapePath ()
static void updateProgress (S32 major, const char *msg, S32 numMinor=0, S32 minor=0)
static void zapScale (MatrixF &mat)
Static Public Attributes
static const F64 AppGroundFrameRate
static const F32 DefaultTime
static const F64 MaxFrameRate
static const F64 MinFrameRate
Protected Member Functions
void addDetailMesh (AppMesh *mesh)
void addNodeAlignedScale (Point3F &scale)
void addNodeArbitraryScale (QuatF &qrot, Point3F &scale)
void addNodeRotation (QuatF &rot, bool defaultVal)
void addNodeTranslation (Point3F &trans, bool defaultVal)
void addNodeUniformScale (F32 scale)
void addObject (AppMesh *mesh, S32 nodeIndex, S32 subShapeNum)
void addSkin (AppMesh *mesh)
void addSubshape (AppNode *node)
void clearNodeTransformCache ()
virtual void computeBounds (Box3F &bounds)
virtual void enumerateScene ()=0
void fillNodeTransformCache (TSShape::Sequence &seq, const AppSequence *appSeq)
void generateDefaultStates ()
void generateFrame (TSShape::Object &obj, F32 t, bool addFrame, bool addMatFrame)
void generateFrameTriggers (TSShape::Sequence &seq, const AppSequence *appSeq)
void generateGroundAnimation (TSShape::Sequence &seq, const AppSequence *appSeq)
void generateMaterialList ()
void generateNodeAnimation (TSShape::Sequence &seq)
void generateNodeTransform (AppNode *node, F32 t, bool blend, F32 referenceTime, QuatF &rot, Point3F &trans, QuatF &srot, Point3F &scale)
void generateObjectAnimation (TSShape::Sequence &seq, const AppSequence *appSeq)
void generateObjects ()
void generateObjectState (TSShape::Object &obj, F32 t, bool addFrame, bool addMatFrame)
void generateSequences ()
void generateSkins ()
void generateSubshapes ()
MatrixF getLocalNodeMatrix (AppNode *node, F32 t)
virtual bool ignoreMesh (const String &name)
virtual bool ignoreNode (const String &name)
void install ()
bool processNode (AppNode *node)
void recurseSubshape (AppNode *appNode, S32 parentIndex, bool recurseChildren)
void setNodeMembership (TSShape::Sequence &seq, const AppSequence *appSeq)
void setObjectMembership (TSShape::Sequence &seq, const AppSequence *appSeq)
void setRotationMembership (TSShape::Sequence &seq)
void setScaleMembership (TSShape::Sequence &seq)
void setTranslationMembership (TSShape::Sequence &seq)
void sortDetails ()
Protected Attributes
Vector< AppMesh * > appMeshes
Vector< AppNode * > appNodes
Nodes in the loaded shape.
Vector< AppSequence * > appSequences
AppNode * boundsNode
Vector< QuatF * > nodeRotCache
Vector< Point3F * > nodeScaleCache
Vector< QuatF * > nodeScaleRotCache
Vector< Point3F * > nodeTransCache
TSShape * shape
Point3F shapeOffset
Offset used to translate the shape origin.
Vector< Subshape * > subshapes
Static Protected Attributes
static Torque::Path shapePath
static Vector< ShapeFormat > smFormats
Member Enumeration Documentation
enum TSShapeLoader::eLoadPhases
Enumerator
Load_ReadFile
Load_ParseFile
Load_ExternalRefs
Load_EnumerateScene
Load_GenerateSubshapes
Load_GenerateObjects
Load_GenerateDefaultStates
Load_GenerateSkins
Load_GenerateMaterials
Load_GenerateSequences
Load_InitShape
NumLoadPhases
Load_Complete
Constructor & Destructor Documentation
TSShapeLoader::TSShapeLoader () inline
References ~TSShapeLoader().
virtual TSShapeLoader::~TSShapeLoader () virtual
Referenced by TSShapeLoader().
Member Function Documentation
void TSShapeLoader::addDetailMesh (AppMesh * mesh) protected
Referenced by ignoreMesh().
static void TSShapeLoader::addFormat (String name, String extension) static
void TSShapeLoader::addNodeAlignedScale (Point3F & scale) protected
Referenced by ignoreMesh().
void TSShapeLoader::addNodeArbitraryScale (QuatF & qrot, Point3F & scale) protected
Referenced by ignoreMesh().
void TSShapeLoader::addNodeRotation (QuatF & rot, bool defaultVal) protected
Referenced by ignoreMesh().
void TSShapeLoader::addNodeTranslation (Point3F & trans, bool defaultVal) protected
Referenced by ignoreMesh().
void TSShapeLoader::addNodeUniformScale (F32 scale) protected
Referenced by ignoreMesh().
void TSShapeLoader::addObject (AppMesh * mesh, S32 nodeIndex, S32 subShapeNum) protected
Referenced by ignoreMesh().
void TSShapeLoader::addSkin (AppMesh * mesh) protected
Referenced by ignoreMesh().
void TSShapeLoader::addSubshape (AppNode * node) protected
Referenced by ignoreMesh().
void TSShapeLoader::clearNodeTransformCache () protected
Referenced by ignoreMesh().
virtual void TSShapeLoader::computeBounds (Box3F & bounds) protected virtual
Reimplemented in ColladaShapeLoader.
Referenced by ignoreMesh().
virtual void TSShapeLoader::enumerateScene () protected pure virtual
Implemented in ColladaShapeLoader.
void TSShapeLoader::fillNodeTransformCache (TSShape::Sequence & seq, const AppSequence * appSeq) protected
Referenced by ignoreMesh().
void TSShapeLoader::generateDefaultStates () protected
Referenced by ignoreMesh().
void TSShapeLoader::generateFrame (TSShape::Object & obj, F32 t, bool addFrame, bool addMatFrame) protected
Referenced by ignoreMesh().
void TSShapeLoader::generateFrameTriggers (TSShape::Sequence & seq, const AppSequence * appSeq) protected
Referenced by ignoreMesh().
void TSShapeLoader::generateGroundAnimation (TSShape::Sequence & seq, const AppSequence * appSeq) protected
Referenced by ignoreMesh().
void TSShapeLoader::generateMaterialList () protected
Referenced by ignoreMesh().
void TSShapeLoader::generateNodeAnimation (TSShape::Sequence & seq) protected
Referenced by ignoreMesh().
void TSShapeLoader::generateNodeTransform (AppNode * node, F32 t, bool blend, F32 referenceTime, QuatF & rot, Point3F & trans, QuatF & srot, Point3F & scale) protected
Referenced by ignoreMesh().
void TSShapeLoader::generateObjectAnimation (TSShape::Sequence & seq, const AppSequence * appSeq) protected
Referenced by ignoreMesh().
void TSShapeLoader::generateObjects () protected
Referenced by ignoreMesh().
void TSShapeLoader::generateObjectState (TSShape::Object & obj, F32 t, bool addFrame, bool addMatFrame) protected
Referenced by ignoreMesh().
void TSShapeLoader::generateSequences () protected
Referenced by ignoreMesh().
TSShape* TSShapeLoader::generateShape (const Torque::Path & path)
Referenced by getShapePath().
void TSShapeLoader::generateSkins () protected
Referenced by ignoreMesh().
void TSShapeLoader::generateSubshapes () protected
Referenced by ignoreMesh().
static String TSShapeLoader::getFormatExtensions () static
static String TSShapeLoader::getFormatFilters () static
MatrixF TSShapeLoader::getLocalNodeMatrix (AppNode * node, F32 t) protected
Referenced by ignoreMesh().
static const Torque::Path& TSShapeLoader::getShapePath () inline static
References generateShape(), shapePath, and zapScale().
virtual bool TSShapeLoader::ignoreMesh (const String & name) inline protected virtual
Reimplemented in ColladaShapeLoader.
References addDetailMesh(), addNodeAlignedScale(), addNodeArbitraryScale(), addNodeRotation(), addNodeTranslation(), addNodeUniformScale(), addObject(), addSkin(), addSubshape(), clearNodeTransformCache(), computeBounds(), fillNodeTransformCache(), generateDefaultStates(), generateFrame(), generateFrameTriggers(), generateGroundAnimation(), generateMaterialList(), generateNodeAnimation(), generateNodeTransform(), generateObjectAnimation(), generateObjects(), generateObjectState(), generateSequences(), generateSkins(), generateSubshapes(), getLocalNodeMatrix(), install(), recurseSubshape(), setNodeMembership(), setObjectMembership(), setRotationMembership(), setScaleMembership(), setTranslationMembership(), and sortDetails().
virtual bool TSShapeLoader::ignoreNode (const String & name) inline protected virtual
Reimplemented in ColladaShapeLoader.
void TSShapeLoader::install () protected
Referenced by ignoreMesh().
bool TSShapeLoader::processNode (AppNode * node) protected
void TSShapeLoader::recurseSubshape (AppNode * appNode, S32 parentIndex, bool recurseChildren) protected
Referenced by ignoreMesh().
void TSShapeLoader::setNodeMembership (TSShape::Sequence & seq, const AppSequence * appSeq) protected
Referenced by ignoreMesh().
void TSShapeLoader::setObjectMembership (TSShape::Sequence & seq, const AppSequence * appSeq) protected
Referenced by ignoreMesh().
void TSShapeLoader::setRotationMembership (TSShape::Sequence & seq) protected
Referenced by ignoreMesh().
void TSShapeLoader::setScaleMembership (TSShape::Sequence & seq) protected
Referenced by ignoreMesh().
void TSShapeLoader::setTranslationMembership (TSShape::Sequence & seq) protected
Referenced by ignoreMesh().
void TSShapeLoader::sortDetails () protected
Referenced by ignoreMesh().
static void TSShapeLoader::updateProgress (S32 major, const char * msg, S32 numMinor = 0, S32 minor = 0) static
static void TSShapeLoader::zapScale (MatrixF & mat) static
Referenced by getShapePath().
Member Data Documentation
const F64 TSShapeLoader::AppGroundFrameRate static
Vector<AppMesh*> TSShapeLoader::appMeshes protected
Vector<AppNode*> TSShapeLoader::appNodes protected
Nodes in the loaded shape.
Vector<AppSequence*> TSShapeLoader::appSequences protected
AppNode* TSShapeLoader::boundsNode protected
const F32 TSShapeLoader::DefaultTime static
const F64 TSShapeLoader::MaxFrameRate static
const F64 TSShapeLoader::MinFrameRate static
Vector<QuatF*> TSShapeLoader::nodeRotCache protected
Vector<Point3F*> TSShapeLoader::nodeScaleCache protected
Vector<QuatF*> TSShapeLoader::nodeScaleRotCache protected
Vector<Point3F*> TSShapeLoader::nodeTransCache protected
TSShape* TSShapeLoader::shape protected
Point3F TSShapeLoader::shapeOffset protected
Offset used to translate the shape origin.
Torque::Path TSShapeLoader::shapePath static protected
Referenced by getShapePath().
Vector<ShapeFormat> TSShapeLoader::smFormats static protected
Vector<Subshape*> TSShapeLoader::subshapes protected
Copyright © GarageGames, LLC. All Rights Reserved.