GFXGLCubemap Class Reference
Main Modules Class List Namespace List Online
GFXGLCubemap Class Reference
#include <gfx/gl/gfxGLCubemap.h>
Public Member Functions
GFXGLCubemap ()
virtual ~GFXGLCubemap ()
virtual GFXFormat getFormat () const
Returns the face texture format.
U32 getHandle ()
U32 getHeight ()
U32 getNumMipLevels ()
virtual U32 getSize () const
Returns the size of the faces.
U32 getWidth ()
virtual void initDynamic (U32 texSize, GFXFormat faceFormat=GFXFormatR8G8B8A8)
virtual void initStatic (GFXTexHandle *faces)
Create a static cubemap from a list of 6 face textures.
virtual void initStatic (DDSFile *dds)
Create a static cubemap from a DDS cubemap file.
virtual void resurrect ()
When called the resource should restore all device sensitive information destroyed by zombify()
void tmResurrect ()
Called by texCB; this is to ensure that all textures have been resurrected before we attempt to res the cubemap.
virtual void zombify ()
When called the resource should destroy all device sensitive information (e.g. D3D resources in D3DPOOL_DEFAULT.
Public Member Functions inherited from GFXCubemap
virtual ~GFXCubemap ()
virtual const String describeSelf () const
The resource should put a description of itself (number of vertices, size/width of texture, etc.) in buffer.
const String & getPath () const
Returns the cubemap file path set at creation.
void initNormalize (U32 size)
Public Member Functions inherited from StrongRefBase
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Public Member Functions inherited from GFXResource
GFXResource ()
virtual ~GFXResource ()
void clearFlag ()
GFXResource * getNextResource () const
GFXDevice * getOwningDevice () const
GFXResource * getPrevResource () const
bool isFlagged ()
void registerResourceWithDevice (GFXDevice *device)
Registers this resource with the given device.
void setFlag ()
Static Public Member Functions
static GLenum getEnumForFaceNumber (U32 face)
Performs lookup to get a GLenum for the given face number.
Protected Member Functions
void _onTextureEvent (GFXTexCallbackCode code)
The callback used to get texture events.
virtual void bind (U32 textureUnit) const
Notifies our owning device that we want to be set to the given texture unit (used for GL internal state tracking)
void fillCubeTextures (GFXTexHandle *faces)
Copies the textures in faces into the cubemap.
virtual void setToTexUnit (U32 tuNum)
Binds the cubemap to the given texture unit.
Protected Member Functions inherited from GFXCubemap
void _setPath (const String &path)
Sets the cubemap file path.
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Protected Attributes
GLuint mCubemap
Internal GL handle.
Resource< DDSFile > mDDSFile
The backing DDSFile uses to restore the faces when the surface is lost.
U32 mDynamicTexSize
Size of faces for a dynamic texture (used in resurrect)
GFXFormat mFaceFormat
U32 mHeight
U32 mMipLevels
GFXTexHandle mTextures [6]
Keep refs to our textures for resurrection of static cubemaps.
U32 mWidth
Protected Attributes inherited from GFXCubemap
String mPath
The path to the cubemap file.
Protected Attributes inherited from StrongRefBase
U32 mRefCount
reference counter for StrongRefPtr objects
Static Protected Attributes
static GLenum faceList [6]
Lookup table.
Constructor & Destructor Documentation
GFXGLCubemap::GFXGLCubemap ()
virtual GFXGLCubemap::~GFXGLCubemap () virtual
Member Function Documentation
void GFXGLCubemap::_onTextureEvent (GFXTexCallbackCode code) protected
The callback used to get texture events.
See also
GFXTextureManager::addEventDelegate
virtual void GFXGLCubemap::bind (U32 textureUnit) const protected virtual
Notifies our owning device that we want to be set to the given texture unit (used for GL internal state tracking)
void GFXGLCubemap::fillCubeTextures (GFXTexHandle * faces) protected
Copies the textures in faces into the cubemap.
static GLenum GFXGLCubemap::getEnumForFaceNumber (U32 face) inline static
Performs lookup to get a GLenum for the given face number.
References faceList.
virtual GFXFormat GFXGLCubemap::getFormat () const inline virtual
Returns the face texture format.
Implements GFXCubemap.
References mFaceFormat.
U32 GFXGLCubemap::getHandle () inline
References mCubemap, resurrect(), tmResurrect(), and zombify().
U32 GFXGLCubemap::getHeight () inline
References mHeight.
U32 GFXGLCubemap::getNumMipLevels () inline
References mMipLevels.
virtual U32 GFXGLCubemap::getSize () const inline virtual
Returns the size of the faces.
Implements GFXCubemap.
References mWidth.
U32 GFXGLCubemap::getWidth () inline
References mWidth.
virtual void GFXGLCubemap::initDynamic (U32 texSize, GFXFormat faceFormat = GFXFormatR8G8B8A8) virtual
Implements GFXCubemap.
virtual void GFXGLCubemap::initStatic (GFXTexHandle * faces) virtual
Create a static cubemap from a list of 6 face textures.
Implements GFXCubemap.
virtual void GFXGLCubemap::initStatic (DDSFile * dds) virtual
Create a static cubemap from a DDS cubemap file.
Implements GFXCubemap.
virtual void GFXGLCubemap::resurrect () virtual
When called the resource should restore all device sensitive information destroyed by zombify()
Implements GFXResource.
Referenced by getHandle().
virtual void GFXGLCubemap::setToTexUnit (U32 tuNum) protected virtual
Binds the cubemap to the given texture unit.
Implements GFXCubemap.
void GFXGLCubemap::tmResurrect ()
Called by texCB; this is to ensure that all textures have been resurrected before we attempt to res the cubemap.
Referenced by getHandle().
virtual void GFXGLCubemap::zombify () virtual
When called the resource should destroy all device sensitive information (e.g. D3D resources in D3DPOOL_DEFAULT.
Implements GFXResource.
Referenced by getHandle().
Member Data Documentation
GLenum GFXGLCubemap::faceList[6] static protected
Lookup table.
Referenced by getEnumForFaceNumber().
GLuint GFXGLCubemap::mCubemap protected
Internal GL handle.
Referenced by getHandle().
Resource<DDSFile> GFXGLCubemap::mDDSFile protected
The backing DDSFile uses to restore the faces when the surface is lost.
U32 GFXGLCubemap::mDynamicTexSize protected
Size of faces for a dynamic texture (used in resurrect)
GFXFormat GFXGLCubemap::mFaceFormat protected
Referenced by getFormat().
U32 GFXGLCubemap::mHeight protected
Referenced by getHeight().
U32 GFXGLCubemap::mMipLevels protected
Referenced by getNumMipLevels().
GFXTexHandle GFXGLCubemap::mTextures[6] protected
Keep refs to our textures for resurrection of static cubemaps.
U32 GFXGLCubemap::mWidth protected
Referenced by getSize(), and getWidth().
Copyright © GarageGames, LLC. All Rights Reserved.