OculusVRDevice Class Reference
Main Modules Class List Namespace List Online
OculusVRDevice Class Reference
#include <platform/input/oculusVR/oculusVRDevice.h>
Public Member Functions
OculusVRDevice ()
~OculusVRDevice ()
bool _handleDeviceEvent (GFXDevice::GFXDeviceEventType evt)
void disable ()
void dismissWarning ()
String dumpMetrics (U32 idx)
bool enable ()
bool getActive ()
virtual GameConnection * getCurrentConnection ()
virtual void getEyeOffsets (Point3F *dest) const
Returns eye offset not taking into account any position tracking info.
virtual void getFovPorts (FovPort *out) const
virtual void getFrameEyePose (DisplayPose *outPose, U32 eyeId) const
U32 getHMDCount () const
F32 getHMDCurrentIPD (U32 index)
OculusVRHMDDevice * getHMDDevice (U32 index) const
GFXTexHandle getPreviewTexture ()
Returns a texture handle representing a preview of the composited VR view.
virtual const Point2F & getProjectionOffset () const
VectorF getSensorAcceleration (U32 index)
EulerF getSensorAngularVelocity (U32 index)
U32 getSensorCount () const
const OculusVRSensorDevice * getSensorDevice (U32 index) const
EulerF getSensorEulerRotation (U32 index)
bool getSensorMagnetometerCalibrated (U32 index)
bool getSensorYawCorrection (U32 index)
virtual void getStereoTargets (GFXTextureTarget **out) const
virtual void getStereoViewports (RectI *out) const
bool isDiplayingWarning ()
virtual void onStartFrame ()
bool process ()
virtual bool providesEyeOffsets () const
virtual bool providesFovPorts () const
virtual bool providesFrameEyePose () const
virtual bool providesProjectionOffset () const
void resetAllSensors ()
void setActive (bool state)
virtual void setCurrentConnection (GameConnection *connection)
void setDrawCanvas (GuiCanvas *canvas)
void setHMDCurrentIPD (U32 index, F32 ipd)
void setOptimalDisplaySize (U32 idx, GuiCanvas *canvas)
void setSensorYawCorrection (U32 index, bool state)
Public Member Functions inherited from IInputDevice
const char * getDeviceName () const
U32 getDeviceType () const
bool isEnabled ()
Public Member Functions inherited from IDisplayDevice
virtual void getFrameEyePose (IDevicePose *pose, S32 eyeId) const =0
Get a display pose for the specified eye, or the HMD if eyeId is -1.
virtual void setDrawMode (GFXDevice::GFXDeviceRenderStyles style)=0
Static Public Member Functions
static const char * getSingletonName ()
static void staticInit ()
Static Public Attributes
static F32 smDesiredPixelDensity
Determines desired pixel density for render target.
static bool smEnableDevice
static bool smGenerateAngleAxisRotationEvents
static bool smGenerateEulerRotationEvents
static bool smGeneratePositionEvents
static bool smGenerateRotationAsAxisEvents
static bool smGenerateSensorRawEvents
static bool smGenerateWholeFrameEvents
static F32 smMaximumAxisAngle
static F32 smPositionTrackingScale
static bool smSimulateHMD
static bool smWindowDebug
Determined if the window is moved to the oculus display.
Protected Member Functions
void addHMDDevice (ovrHmd hmd, ovrGraphicsLuid luid)
void buildCodeTable ()
Build out the codes used for controller actions with the Input Event Manager.
void cleanUp ()
void createSimulatedHMD ()
Protected Attributes
bool mActive
Is the device active.
U32 mActiveDeviceId
Which HMD is the active one.
Vector< OculusVRHMDDevice * > mHMDDevices
ovrGraphicsLuid mLuid
Device id we need to use to hook up with oculus.
Protected Attributes inherited from IInputDevice
U32 mDeviceType
Device type.
bool mEnabled
Is the device enabled.
char mName [30]
Device name.
Constructor & Destructor Documentation
OculusVRDevice::OculusVRDevice ()
OculusVRDevice::~OculusVRDevice ()
Member Function Documentation
bool OculusVRDevice::_handleDeviceEvent (GFXDevice::GFXDeviceEventType evt)
Referenced by getSensorCount().
void OculusVRDevice::addHMDDevice (ovrHmd hmd, ovrGraphicsLuid luid) protected
void OculusVRDevice::buildCodeTable () protected
Build out the codes used for controller actions with the Input Event Manager.
void OculusVRDevice::cleanUp () protected
void OculusVRDevice::createSimulatedHMD () protected
void OculusVRDevice::disable ()
void OculusVRDevice::dismissWarning ()
Referenced by getSensorCount().
String OculusVRDevice::dumpMetrics (U32 idx)
Referenced by getSensorCount().
bool OculusVRDevice::enable ()
bool OculusVRDevice::getActive () inline
References mActive.
virtual GameConnection* OculusVRDevice::getCurrentConnection () virtual
Implements IDisplayDevice.
Referenced by getSensorCount().
virtual void OculusVRDevice::getEyeOffsets (Point3F * dest) const virtual
Returns eye offset not taking into account any position tracking info.
Implements IDisplayDevice.
Referenced by providesFovPorts().
virtual void OculusVRDevice::getFovPorts (FovPort * out) const virtual
Implements IDisplayDevice.
Referenced by providesFovPorts().
virtual void OculusVRDevice::getFrameEyePose (DisplayPose * outPose, U32 eyeId) const virtual
Referenced by setActive().
U32 OculusVRDevice::getHMDCount () const inline
References getHMDCurrentIPD(), getHMDDevice(), setHMDCurrentIPD(), and Vector< T >::size().
F32 OculusVRDevice::getHMDCurrentIPD (U32 index)
Referenced by getHMDCount().
OculusVRHMDDevice* OculusVRDevice::getHMDDevice (U32 index) const
Referenced by getHMDCount().
GFXTexHandle OculusVRDevice::getPreviewTexture () virtual
Returns a texture handle representing a preview of the composited VR view.
Implements IDisplayDevice.
Referenced by getSensorCount().
virtual const Point2F& OculusVRDevice::getProjectionOffset () const virtual
Referenced by providesFovPorts().
VectorF OculusVRDevice::getSensorAcceleration (U32 index)
Referenced by getSensorCount().
EulerF OculusVRDevice::getSensorAngularVelocity (U32 index)
Referenced by getSensorCount().
U32 OculusVRDevice::getSensorCount () const inline
References _handleDeviceEvent(), dismissWarning(), dumpMetrics(), getCurrentConnection(), getPreviewTexture(), getSensorAcceleration(), getSensorAngularVelocity(), getSensorDevice(), getSensorEulerRotation(), getSensorMagnetometerCalibrated(), getSensorYawCorrection(), isDiplayingWarning(), resetAllSensors(), setCurrentConnection(), setDrawCanvas(), setOptimalDisplaySize(), setSensorYawCorrection(), and Vector< T >::size().
const OculusVRSensorDevice* OculusVRDevice::getSensorDevice (U32 index) const
Referenced by getSensorCount().
EulerF OculusVRDevice::getSensorEulerRotation (U32 index)
Referenced by getSensorCount().
bool OculusVRDevice::getSensorMagnetometerCalibrated (U32 index)
Referenced by getSensorCount().
bool OculusVRDevice::getSensorYawCorrection (U32 index)
Referenced by getSensorCount().
static const char* OculusVRDevice::getSingletonName () inline static
virtual void OculusVRDevice::getStereoTargets (GFXTextureTarget ** out) const virtual
Implements IDisplayDevice.
Referenced by providesFovPorts().
virtual void OculusVRDevice::getStereoViewports (RectI * out) const virtual
Implements IDisplayDevice.
Referenced by providesFovPorts().
bool OculusVRDevice::isDiplayingWarning ()
Referenced by getSensorCount().
virtual void OculusVRDevice::onStartFrame () virtual
Implements IDisplayDevice.
Referenced by providesFovPorts().
bool OculusVRDevice::process () virtual
Implements IInputDevice.
Referenced by setActive().
virtual bool OculusVRDevice::providesEyeOffsets () const virtual
Implements IDisplayDevice.
Referenced by setActive().
virtual bool OculusVRDevice::providesFovPorts () const inline virtual
Implements IDisplayDevice.
References getEyeOffsets(), getFovPorts(), getProjectionOffset(), getStereoTargets(), getStereoViewports(), onStartFrame(), and providesProjectionOffset().
virtual bool OculusVRDevice::providesFrameEyePose () const virtual
Implements IDisplayDevice.
Referenced by setActive().
virtual bool OculusVRDevice::providesProjectionOffset () const virtual
Referenced by providesFovPorts().
void OculusVRDevice::resetAllSensors ()
Referenced by getSensorCount().
void OculusVRDevice::setActive (bool state) inline
References getFrameEyePose(), process(), providesEyeOffsets(), and providesFrameEyePose().
virtual void OculusVRDevice::setCurrentConnection (GameConnection * connection) virtual
Implements IDisplayDevice.
Referenced by getSensorCount().
void OculusVRDevice::setDrawCanvas (GuiCanvas * canvas) virtual
Implements IDisplayDevice.
Referenced by getSensorCount().
void OculusVRDevice::setHMDCurrentIPD (U32 index, F32 ipd)
Referenced by getHMDCount().
void OculusVRDevice::setOptimalDisplaySize (U32 idx, GuiCanvas * canvas)
Referenced by getSensorCount().
void OculusVRDevice::setSensorYawCorrection (U32 index, bool state)
Referenced by getSensorCount().
static void OculusVRDevice::staticInit () static
Member Data Documentation
bool OculusVRDevice::mActive protected
Is the device active.
Referenced by getActive().
U32 OculusVRDevice::mActiveDeviceId protected
Which HMD is the active one.
Vector<OculusVRHMDDevice*> OculusVRDevice::mHMDDevices protected
ovrGraphicsLuid OculusVRDevice::mLuid protected
Device id we need to use to hook up with oculus.
F32 OculusVRDevice::smDesiredPixelDensity static
Determines desired pixel density for render target.
bool OculusVRDevice::smEnableDevice static
bool OculusVRDevice::smGenerateAngleAxisRotationEvents static
bool OculusVRDevice::smGenerateEulerRotationEvents static
bool OculusVRDevice::smGeneratePositionEvents static
bool OculusVRDevice::smGenerateRotationAsAxisEvents static
bool OculusVRDevice::smGenerateSensorRawEvents static
bool OculusVRDevice::smGenerateWholeFrameEvents static
F32 OculusVRDevice::smMaximumAxisAngle static
F32 OculusVRDevice::smPositionTrackingScale static
bool OculusVRDevice::smSimulateHMD static
bool OculusVRDevice::smWindowDebug static
Determined if the window is moved to the oculus display.
Copyright © GarageGames, LLC. All Rights Reserved.