OculusVRSensorDevice Class Reference
Main Modules Class List Namespace List Online
OculusVRSensorDevice Class Reference
#include <platform/input/oculusVR/oculusVRSensorDevice.h>
Public Member Functions
OculusVRSensorDevice ()
virtual ~OculusVRSensorDevice ()
void cleanUp ()
VectorF getAcceleration ()
EulerF getAngularVelocity ()
EulerF getEulerRotation ()
bool getHasValidPosition () const
U32 getLastTrackingStatus () const
bool getMagnetometerCalibrationAvailable () const
const char * getManufacturer ()
bool getOrientationTrackingAvailable () const
Point3F getPosition ()
bool getPositionTrackingAvailable () const
U16 getProductId ()
const char * getProductName ()
EulerF getRawEulerRotation ()
const char * getSerialNumber ()
U16 getVendorId ()
U32 getVersion ()
bool getYawCorrection () const
bool getYawCorrectionUserDisabled () const
bool isValid () const
bool process (U32 deviceType, bool generateRotAsAngAxis, bool generateRotAsEuler, bool generateRotationAsAxisEvents, bool generatePositionEvents, F32 maxAxisRadius, bool generateRawSensor)
void reset ()
void set (ovrHmd sensor, S32 actionCodeIndex)
void setPositionTracking (bool state)
void setYawCorrection (bool state)
void updateTrackingCaps ()
Static Public Member Functions
static void buildCodeTable ()
Static Public Attributes
static U32 OVR_SENSORACCELERATION [OculusVRConstants::MaxSensors]
static U32 OVR_SENSORANGVEL [OculusVRConstants::MaxSensors]
static U32 OVR_SENSORMAGNETOMETER [OculusVRConstants::MaxSensors]
static U32 OVR_SENSORPOSITION [OculusVRConstants::MaxSensors]
static U32 OVR_SENSORROT [OculusVRConstants::MaxSensors]
static U32 OVR_SENSORROTANG [OculusVRConstants::MaxSensors]
static U32 OVR_SENSORROTAXISX [OculusVRConstants::MaxSensors]
static U32 OVR_SENSORROTAXISY [OculusVRConstants::MaxSensors]
Protected Attributes
S32 mActionCodeIndex
U32 mCurrentTrackingCaps
OculusVRSensorData * mDataBuffer [2]
ovrHmd mDevice
bool mIsValid
U32 mLastStatus
String mManufacturer
bool mPositionTrackingDisabled
OculusVRSensorData * mPrevData
U16 mProductId
String mProductName
String mSerialNumber
U32 mSupportedTrackingCaps
U16 mVendorId
U32 mVersion
bool mYawCorrectionDisabled
Constructor & Destructor Documentation
OculusVRSensorDevice::OculusVRSensorDevice ()
virtual OculusVRSensorDevice::~OculusVRSensorDevice () virtual
Member Function Documentation
static void OculusVRSensorDevice::buildCodeTable () static
void OculusVRSensorDevice::cleanUp ()
VectorF OculusVRSensorDevice::getAcceleration ()
Referenced by getSerialNumber().
EulerF OculusVRSensorDevice::getAngularVelocity ()
Referenced by getSerialNumber().
EulerF OculusVRSensorDevice::getEulerRotation ()
Referenced by getSerialNumber().
bool OculusVRSensorDevice::getHasValidPosition () const inline
References getMagnetometerCalibrationAvailable(), getOrientationTrackingAvailable(), getPositionTrackingAvailable(), setPositionTracking(), and setYawCorrection().
U32 OculusVRSensorDevice::getLastTrackingStatus () const inline
References mLastStatus.
bool OculusVRSensorDevice::getMagnetometerCalibrationAvailable () const
Referenced by getHasValidPosition().
const char* OculusVRSensorDevice::getManufacturer () inline
References String::c_str().
bool OculusVRSensorDevice::getOrientationTrackingAvailable () const
Referenced by getHasValidPosition().
Point3F OculusVRSensorDevice::getPosition ()
Referenced by getSerialNumber().
bool OculusVRSensorDevice::getPositionTrackingAvailable () const
Referenced by getHasValidPosition().
U16 OculusVRSensorDevice::getProductId () inline
References mProductId.
const char* OculusVRSensorDevice::getProductName () inline
References String::c_str().
EulerF OculusVRSensorDevice::getRawEulerRotation ()
Referenced by getSerialNumber().
const char* OculusVRSensorDevice::getSerialNumber () inline
References getAcceleration(), getAngularVelocity(), getEulerRotation(), getPosition(), getRawEulerRotation(), mSerialNumber, and updateTrackingCaps().
U16 OculusVRSensorDevice::getVendorId () inline
References mVendorId.
U32 OculusVRSensorDevice::getVersion () inline
References mVersion.
bool OculusVRSensorDevice::getYawCorrection () const
Referenced by getYawCorrectionUserDisabled().
bool OculusVRSensorDevice::getYawCorrectionUserDisabled () const inline
References getYawCorrection(), and mYawCorrectionDisabled.
bool OculusVRSensorDevice::isValid () const inline
References mIsValid, process(), and reset().
bool OculusVRSensorDevice::process (U32 deviceType, bool generateRotAsAngAxis, bool generateRotAsEuler, bool generateRotationAsAxisEvents, bool generatePositionEvents, F32 maxAxisRadius, bool generateRawSensor)
Referenced by isValid().
void OculusVRSensorDevice::reset ()
Referenced by isValid().
void OculusVRSensorDevice::set (ovrHmd sensor, S32 actionCodeIndex)
void OculusVRSensorDevice::setPositionTracking (bool state)
Referenced by getHasValidPosition().
void OculusVRSensorDevice::setYawCorrection (bool state)
Referenced by getHasValidPosition().
void OculusVRSensorDevice::updateTrackingCaps ()
Referenced by getSerialNumber().
Member Data Documentation
S32 OculusVRSensorDevice::mActionCodeIndex protected
U32 OculusVRSensorDevice::mCurrentTrackingCaps protected
OculusVRSensorData* OculusVRSensorDevice::mDataBuffer[2] protected
ovrHmd OculusVRSensorDevice::mDevice protected
bool OculusVRSensorDevice::mIsValid protected
Referenced by isValid().
U32 OculusVRSensorDevice::mLastStatus protected
Referenced by getLastTrackingStatus().
String OculusVRSensorDevice::mManufacturer protected
bool OculusVRSensorDevice::mPositionTrackingDisabled protected
OculusVRSensorData* OculusVRSensorDevice::mPrevData protected
U16 OculusVRSensorDevice::mProductId protected
Referenced by getProductId().
String OculusVRSensorDevice::mProductName protected
String OculusVRSensorDevice::mSerialNumber protected
Referenced by getSerialNumber().
U32 OculusVRSensorDevice::mSupportedTrackingCaps protected
U16 OculusVRSensorDevice::mVendorId protected
Referenced by getVendorId().
U32 OculusVRSensorDevice::mVersion protected
Referenced by getVersion().
bool OculusVRSensorDevice::mYawCorrectionDisabled protected
Referenced by getYawCorrectionUserDisabled().
U32 OculusVRSensorDevice::OVR_SENSORACCELERATION[OculusVRConstants::MaxSensors] static
U32 OculusVRSensorDevice::OVR_SENSORANGVEL[OculusVRConstants::MaxSensors] static
U32 OculusVRSensorDevice::OVR_SENSORMAGNETOMETER[OculusVRConstants::MaxSensors] static
U32 OculusVRSensorDevice::OVR_SENSORPOSITION[OculusVRConstants::MaxSensors] static
U32 OculusVRSensorDevice::OVR_SENSORROT[OculusVRConstants::MaxSensors] static
U32 OculusVRSensorDevice::OVR_SENSORROTANG[OculusVRConstants::MaxSensors] static
U32 OculusVRSensorDevice::OVR_SENSORROTAXISX[OculusVRConstants::MaxSensors] static
U32 OculusVRSensorDevice::OVR_SENSORROTAXISY[OculusVRConstants::MaxSensors] static
Copyright © GarageGames, LLC. All Rights Reserved.