GFXResource Class Reference
Main Modules Class List Namespace List Online
GFXResource Class Reference abstract
Mixin for the purpose of tracking GFX resources owned by a GFXDevice.
#include <gfx/gfxResource.h>
Public Member Functions
GFXResource ()
virtual ~GFXResource ()
void clearFlag ()
virtual const String describeSelf () const =0
The resource should put a description of itself (number of vertices, size/width of texture, etc.) in buffer.
GFXResource * getNextResource () const
GFXDevice * getOwningDevice () const
GFXResource * getPrevResource () const
bool isFlagged ()
void registerResourceWithDevice (GFXDevice *device)
Registers this resource with the given device.
virtual void resurrect ()=0
When called the resource should restore all device sensitive information destroyed by zombify()
void setFlag ()
virtual void zombify ()=0
When called the resource should destroy all device sensitive information (e.g. D3D resources in D3DPOOL_DEFAULT.
Detailed Description
Mixin for the purpose of tracking GFX resources owned by a GFXDevice.
There are many types of resource that are allocated from a GFXDevice that must be participatory in device resets. For instance, all default pool DirectX resources have to be involved when the device resets. Render targets in all APIs need to unbind themselves when resets happen.
This system is also handy for accounting purposes. For instance, we may want to traverse all registered VBs, IBs, Textures, or RTs in order to determine what, if any, items are still allocated. This can be used in leak reports, memory usage reports, etc.
Constructor & Destructor Documentation
GFXResource::GFXResource ()
virtual GFXResource::~GFXResource () virtual
Member Function Documentation
void GFXResource::clearFlag () inline
virtual const String GFXResource::describeSelf () const pure virtual
The resource should put a description of itself (number of vertices, size/width of texture, etc.) in buffer.
Implemented in GFXShader, GFXD3D11ShaderConstBuffer, GFXStateBlock, GFXTextureObject, GFXD3D9ShaderConstBuffer, GFXGLShaderConstBuffer, GFXPrimitiveBuffer, GFXGeneralFence, GFXTarget, GFXVertexBuffer, GFXOcclusionQuery, GFXGLTextureObject, GFXCubemap, GFXGLTextureTarget, GFXGLShader, GFXD3D9OcclusionQuery, GFXD3D11OcclusionQuery, GFXD3D9QueryFence, GFXD3D11QueryFence, GFXGLAppleFence, and GFXGLOcclusionQuery.
Referenced by GFXGeneralFence::getStatus().
GFXResource* GFXResource::getNextResource () const inline
GFXDevice* GFXResource::getOwningDevice () const inline
GFXResource* GFXResource::getPrevResource () const inline
bool GFXResource::isFlagged () inline
void GFXResource::registerResourceWithDevice (GFXDevice * device)
Registers this resource with the given device.
virtual void GFXResource::resurrect () pure virtual
When called the resource should restore all device sensitive information destroyed by zombify()
Implemented in GFXD3D11Shader, GFXD3D11ShaderConstBuffer, GFXD3D9Shader, GFXD3D9ShaderConstBuffer, GFXGLShaderConstBuffer, GFXPCD3D9WindowTarget, GFXD3D11WindowTarget, GFXGeneralFence, GFXD3D11TextureObject, GFXOcclusionQuery, GFXPCD3D9TextureTarget, GFXGLTextureObject, GFXD3D9VertexBuffer, GFXD3D9TextureObject, GFXD3D11TextureTarget, GFXD3D9PrimitiveBuffer, GFXGLTextureTarget, GFXGLStateBlock, GFXD3D11PrimitiveBuffer, GFXGLShader, GFXD3D11StateBlock, GFXD3D9OcclusionQuery, GFXD3D9StateBlock, GFXD3D11VertexBuffer, GFXGLVertexBuffer, GFXNullWindowTarget, GFXD3D11OcclusionQuery, GFXGLCubemap, GFXD3D9Cubemap, GFXD3D11Cubemap, GFXD3D9QueryFence, GFXGLWindowTarget, GFXD3D11QueryFence, GFXGLPrimitiveBuffer, GFXGLAppleFence, and GFXGLOcclusionQuery.
Referenced by GFXGeneralFence::getStatus().
void GFXResource::setFlag () inline
virtual void GFXResource::zombify () pure virtual
When called the resource should destroy all device sensitive information (e.g. D3D resources in D3DPOOL_DEFAULT.
Implemented in GFXD3D11Shader, GFXD3D11ShaderConstBuffer, GFXD3D9Shader, GFXD3D9ShaderConstBuffer, GFXGLShaderConstBuffer, GFXPCD3D9WindowTarget, GFXD3D11WindowTarget, GFXGeneralFence, GFXD3D11TextureObject, GFXOcclusionQuery, GFXPCD3D9TextureTarget, GFXGLTextureObject, GFXD3D9VertexBuffer, GFXD3D9TextureObject, GFXD3D11TextureTarget, GFXD3D9PrimitiveBuffer, GFXGLTextureTarget, GFXD3D11PrimitiveBuffer, GFXGLShader, GFXGLStateBlock, GFXD3D9OcclusionQuery, GFXD3D11StateBlock, GFXD3D9StateBlock, GFXD3D11VertexBuffer, GFXGLVertexBuffer, GFXNullWindowTarget, GFXD3D11OcclusionQuery, GFXGLCubemap, GFXD3D9Cubemap, GFXD3D11Cubemap, GFXD3D9QueryFence, GFXGLWindowTarget, GFXD3D11QueryFence, GFXGLPrimitiveBuffer, GFXGLAppleFence, and GFXGLOcclusionQuery.
Referenced by GFXGeneralFence::getStatus().
Copyright © GarageGames, LLC. All Rights Reserved.