SceneTraversalState Class Reference
Main Modules Class List Namespace List Online
SceneTraversalState Class Reference
Temporary state for zone traversals.
#include <scene/zones/sceneTraversalState.h>
Public Member Functions
SceneTraversalState (SceneCullingState *cullingState)
Construct an empty scene traversal state.
void addToTraversedArea (const Box3F &area)
Add an area to what has been visited so far in the traversal.
SceneCullingState * getCullingState () const
Return the scene culling state for this traversal.
const Box3F & getTraversedArea () const
Get the scene area that has been visited so far in the traversal.
Zone Stack
U32 getTraversalDepth () const
Return the number of zones that are currently on the traversal stack.
void pushZone (U32 zoneId)
Push a zone onto the traversal stack.
void popZone ()
Pop the topmost zone from the traversal stack.
bool haveVisitedZone (U32 zoneId) const
Return true if the given zone has already been visited in the current traversal chain, i.e.
U32 getZoneIdFromStack (U32 depth=0)
Return the zone ID of the topmost zone on the traversal stack.
SceneZoneSpace * getZoneFromStack (U32 depth=0)
Return the zone space that owns the topmost zone on the traversal stack.
Culling Volume Stack
void pushCullingVolume (const SceneCullingVolume &volume)
Push a culling volume onto the stack so that it becomes the current culling volume.
void popCullingVolume ()
Pop the current culling volume from the stack.
const SceneCullingVolume & getCurrentCullingVolume () const
Protected Attributes
SceneCullingState * mCullingState
Scene culling state.
Vector< SceneCullingVolume > mCullingVolumeStack
Stack of culling volumes. Topmost is current volume.
Box3F mTraversedArea
Area of scene visited in traversal.
Vector< U32 > mZoneStack
Stack of zones visited in current traversal chain.
Detailed Description
Temporary state for zone traversals.
Keeps track of the zones that were visited in the current traversal chain as well as of the total area that so far has been visited in the traversal.
Constructor & Destructor Documentation
SceneTraversalState::SceneTraversalState (SceneCullingState * cullingState)
Construct an empty scene traversal state.
Parameters
cullingState Scene culling state.
Member Function Documentation
void SceneTraversalState::addToTraversedArea (const Box3F & area) inline
Add an area to what has been visited so far in the traversal.
References Box3F::intersect().
SceneCullingState* SceneTraversalState::getCullingState () const inline
Return the scene culling state for this traversal.
References mCullingState.
const SceneCullingVolume& SceneTraversalState::getCurrentCullingVolume () const inline
References Vector< T >::last().
U32 SceneTraversalState::getTraversalDepth () const inline
Return the number of zones that are currently on the traversal stack.
References Vector< T >::size().
const Box3F& SceneTraversalState::getTraversedArea () const inline
Get the scene area that has been visited so far in the traversal.
References mTraversedArea.
SceneZoneSpace* SceneTraversalState::getZoneFromStack (U32 depth = 0)
Return the zone space that owns the topmost zone on the traversal stack.
Referenced by getZoneIdFromStack().
U32 SceneTraversalState::getZoneIdFromStack (U32 depth = 0) inline
Return the zone ID of the topmost zone on the traversal stack.
References getZoneFromStack(), popCullingVolume(), pushCullingVolume(), and Vector< T >::size().
bool SceneTraversalState::haveVisitedZone (U32 zoneId) const inline
Return true if the given zone has already been visited in the current traversal chain, i.e.
if it is currently on the traversal stack.
References Vector< T >::contains().
void SceneTraversalState::popCullingVolume ()
Pop the current culling volume from the stack.
Referenced by getZoneIdFromStack().
void SceneTraversalState::popZone () inline
Pop the topmost zone from the traversal stack.
References Vector< T >::pop_back().
void SceneTraversalState::pushCullingVolume (const SceneCullingVolume & volume)
Push a culling volume onto the stack so that it becomes the current culling volume.
Referenced by getZoneIdFromStack().
void SceneTraversalState::pushZone (U32 zoneId) inline
Push a zone onto the traversal stack.
References Vector< T >::push_back().
Member Data Documentation
SceneCullingState* SceneTraversalState::mCullingState protected
Scene culling state.
Referenced by getCullingState().
Vector< SceneCullingVolume > SceneTraversalState::mCullingVolumeStack protected
Stack of culling volumes. Topmost is current volume.
Box3F SceneTraversalState::mTraversedArea protected
Area of scene visited in traversal.
Referenced by getTraversedArea().
Vector< U32 > SceneTraversalState::mZoneStack protected
Stack of zones visited in current traversal chain.
Copyright © GarageGames, LLC. All Rights Reserved.