CreatorTree::Node Class Reference
Main Modules Class List Namespace List Online
CreatorTree::Node Class Reference
#include <gui/worldEditor/creator.h>
Public Types
enum {
Group = BIT(0),
Expanded = BIT(1),
Selected = BIT(2),
Root = BIT(3)
}
Public Member Functions
Node ()
~Node ()
void expand (bool exp)
Node * find (S32 id)
S32 getId ()
S32 getSelected ()
bool hasChildItem ()
bool isExpanded ()
bool isFirst ()
bool isGroup ()
bool isLast ()
bool isRoot ()
bool isSelected ()
void select (bool sel)
Public Attributes
Vector< Node * > mChildren
BitSet32 mFlags
S32 mId
StringTableEntry mName
Node * mParent
U32 mTab
StringTableEntry mValue
Member Enumeration Documentation
anonymous enum
Enumerator
Group
Expanded
Selected
Root
Constructor & Destructor Documentation
CreatorTree::Node::Node ()
CreatorTree::Node::~Node ()
Member Function Documentation
void CreatorTree::Node::expand (bool exp)
Referenced by CreatorTree::getSelected().
Node* CreatorTree::Node::find (S32 id)
Referenced by select().
S32 CreatorTree::Node::getId () inline
References CreatorTree::CreatorTree(), getSelected(), hasChildItem(), isFirst(), isLast(), and CreatorTree::~CreatorTree().
S32 CreatorTree::Node::getSelected ()
Referenced by getId(), and CreatorTree::getSelected().
bool CreatorTree::Node::hasChildItem ()
Referenced by getId().
bool CreatorTree::Node::isExpanded () inline
References Expanded, and BitSet32::test().
bool CreatorTree::Node::isFirst ()
Referenced by getId().
bool CreatorTree::Node::isGroup () inline
References Group, and BitSet32::test().
bool CreatorTree::Node::isLast ()
Referenced by getId().
bool CreatorTree::Node::isRoot () inline
References Root, and BitSet32::test().
bool CreatorTree::Node::isSelected () inline
References Selected, and BitSet32::test().
void CreatorTree::Node::select (bool sel) inline
References find(), Selected, and BitSet32::set().
Referenced by CreatorTree::getSelected().
Member Data Documentation
Vector<Node*> CreatorTree::Node::mChildren
BitSet32 CreatorTree::Node::mFlags
S32 CreatorTree::Node::mId
StringTableEntry CreatorTree::Node::mName
Node* CreatorTree::Node::mParent
U32 CreatorTree::Node::mTab
StringTableEntry CreatorTree::Node::mValue
Copyright © GarageGames, LLC. All Rights Reserved.