Gizmo Class Reference
Main Modules Class List Namespace List Online
Gizmo Class Reference
#include <gui/worldEditor/gizmo.h>
Public Types
enum Selection {
None = -1,
Axis_X = 0,
Axis_Y = 1,
Axis_Z = 2,
Plane_XY = 3,
Plane_XZ = 4,
Plane_YZ = 5,
Centroid = 6,
Custom1 = 7,
Custom2 = 8
}
Public Types inherited from SimObject
typedef ConsoleObject Parent
enum WriteFlags {
SelectedOnly = BIT(0),
NoName = BIT(1),
IgnoreCanSave = BIT(2)
}
Flags passed to SimObject::write.
Public Types inherited from EngineObject
typedef void(* DebugEnumInstancesCallback) (EngineObject *)
Type of callback function for iterating over EngineObject instances.
Public Member Functions
Gizmo ()
~Gizmo ()
bool collideAxisGizmo (const Gui3DMouseEvent &event)
DECLARE_CONOBJECT (Gizmo)
GizmoAlignment getAlignment () const
const Point3F & getDeltaRot () const
const Point3F & getDeltaScale () const
const Point3F & getDeltaTotalRot () const
const Point3F & getDeltaTotalScale () const
GizmoMode getMode () const
const Point3F & getOffset () const
Point3F getPosition () const
GizmoProfile * getProfile ()
const Point3F & getScale () const
Selection getSelection ()
const Point3F & getTotalOffset () const
const MatrixF & getTransform () const
Returns current object to world transform of the object being manipulated.
bool isDirty ()
void markClean ()
void on3DMouseDown (const Gui3DMouseEvent &event)
void on3DMouseDragged (const Gui3DMouseEvent &event)
void on3DMouseMove (const Gui3DMouseEvent &event)
void on3DMouseUp (const Gui3DMouseEvent &event)
bool onAdd ()
Called when the object is added to the sim.
void onRemove ()
Called when the object is removed from the sim.
void renderGizmo (const MatrixF &cameraTransform, F32 camerFOV=1.5f)
void renderText (const RectI &viewPort, const MatrixF &modelView, const MatrixF &projection)
Point3F selectionToAxisVector (Selection axis)
void set (const MatrixF &objMat, const Point3F &worldPos, const Point3F &objScale)
void setCentroidHandleHighlight (bool state)
void setGridPlaneEnabled (bool value)
Set whether to render the grid plane.
void setMoveGridEnabled (bool value)
Set whether to a transparent grid overlay when using the move gizmo.
void setMoveGridSize (F32 value)
Set the size of the move grid along one dimension.
void setMoveGridSpacing (F32 value)
Set the spacing between grid lines on the move grid.
void setProfile (GizmoProfile *profile)
void setSelection (Selection sel)
Public Member Functions inherited from SimObject
virtual void copyTo (SimObject *object)
Copy SimObject to another SimObject (Originally designed for T2D).
DECLARE_CONOBJECT (SimObject)
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
virtual SimObject * findObject (const char *name)
Find a named sub-object of this object.
virtual void getConsoleMethodData (const char *fname, S32 routingId, S32 *type, S32 *minArgs, S32 *maxArgs, void **callback, const char **usage)
Namespace * getNamespace ()
Return the object's namespace.
StringTableEntry getProgenitorFile (void) const
virtual bool handlesConsoleMethod (const char *fname, S32 *routingId)
void setProgenitorFile (const char *pFile)
const char * tabComplete (const char *prevText, S32 baseLen, bool)
Get next matching item in namespace.
virtual bool writeField (StringTableEntry fieldname, const char *value)
Determine whether or not a field should be written.
virtual void write (Stream &stream, U32 tabStop, U32 flags=0)
Output the TorqueScript to recreate this object.
virtual void writeFields (Stream &stream, U32 tabStop)
Write the fields of this object in TorqueScript.
virtual bool writeObject (Stream *stream)
virtual bool readObject (Stream *stream)
void setCanSaveDynamicFields (bool bCanSave)
Set whether fields created at runtime should be saved. Default is true.
bool getCanSaveDynamicFields ()
Get whether fields created at runtime should be saved. Default is true.
SimObject * getCopySource () const
Return the object that this object is copying fields from.
void setCopySource (SimObject *object)
Set the object that this object should be copying fields from.
void assignFieldsFrom (SimObject *obj)
Copy fields from another object onto this one.
void assignDynamicFieldsFrom (SimObject *obj)
Copy dynamic fields from another object onto this one.
Notify * removeNotify (void *ptr, Notify::Type)
Remove a notification from the list.
void deleteNotify (SimObject *obj)
Notify an object when we are deleted.
void clearNotify (SimObject *obj)
Notify an object when we are cleared.
void clearAllNotifications ()
Remove all notifications for this object.
void processDeleteNotifies ()
Send out deletion notifications.
void registerReference (SimObject **obj)
Register a reference to this object.
void unregisterReference (SimObject **obj)
Unregister a reference to this object.
SimPersistID * getPersistentId () const
Return the persistent ID assigned to this object or NULL.
SimPersistID * getOrCreatePersistentId ()
Return the persistent ID assigned to this object or assign one to it if it has none.
StringTableEntry getClassNamespace () const
Return name of class namespace set on this object.
StringTableEntry getSuperClassNamespace () const
Return name of superclass namespace set on this object.
void setClassNamespace (const char *classNamespace)
void setSuperClassNamespace (const char *superClassNamespace)
virtual SimObject * clone ()
Return a shallow copy of this object.
virtual SimObject * deepClone ()
Return a deep copy of this object.
const char * getDataField (StringTableEntry slotName, const char *array)
Get the value of a field on the object.
void setDataField (StringTableEntry slotName, const char *array, const char *value)
Set the value of a field on the object.
const char * getPrefixedDataField (StringTableEntry fieldName, const char *array)
void setPrefixedDataField (StringTableEntry fieldName, const char *array, const char *value)
const char * getPrefixedDynamicDataField (StringTableEntry fieldName, const char *array, const S32 fieldType=-1)
void setPrefixedDynamicDataField (StringTableEntry fieldName, const char *array, const char *value, const S32 fieldType=-1)
StringTableEntry getDataFieldPrefix (StringTableEntry fieldName)
U32 getDataFieldType (StringTableEntry slotName, const char *array)
Get the type of a field on the object.
void setDataFieldType (const U32 fieldTypeId, StringTableEntry slotName, const char *array)
Set the type of a dynamic field on the object.
void setDataFieldType (const char *typeName, StringTableEntry slotName, const char *array)
SimFieldDictionary * getFieldDictionary ()
Get reference to the dictionary containing dynamic fields.
virtual StringTableEntry getComponentName ()
void setInternalName (const char *newname)
These functions support internal naming that is not namespace bound for locating child controls in a generic way.
StringTableEntry getInternalName () const
Get the internal name of this control.
void setOriginalName (const char *originalName)
Set the original name of this control.
StringTableEntry getOriginalName () const
Get the original name of this control.
void setFilename (const char *file)
These functions allow you to set and access the filename where this object was created.
StringTableEntry getFilename () const
Get the filename.
void setDeclarationLine (U32 lineNumber)
These functions are used to track the line number (1-based) on which the object was created if it was loaded from script.
S32 getDeclarationLine () const
Get the declaration line number.
virtual bool save (const char *pcFilePath, bool bOnlySelected=false, const char *preappend=NULL)
Save object as a TorqueScript File.
virtual bool isMethod (const char *methodName)
Check if a method exists in the objects current namespace.
virtual bool isField (const char *fieldName, bool includeStatic=true, bool includeDynamic=true)
Return true if the field is defined on the object.
SimObjectId getId () const
Return the unique numeric object ID.
const char * getIdString () const
Return the object ID as a string.
StringTableEntry getName () const
Return the name of this object.
SimGroup * getGroup () const
Return the SimGroup that this object is contained in.
void assignName (const char *name)
Assign the given name to this object.
void setId (SimObjectId id)
bool isChildOfGroup (SimGroup *pGroup)
bool isProperlyAdded () const
bool isDeleted () const
bool isRemoved () const
virtual bool isLocked () const
virtual void setLocked (bool b)
virtual bool isHidden () const
virtual void setHidden (bool b)
bool isSelected () const
bool isExpanded () const
bool isEditorOnly () const
bool isNameChangeAllowed () const
bool isAutoDeleted () const
void setSelected (bool sel)
void setExpanded (bool exp)
void setModDynamicFields (bool dyn)
void setModStaticFields (bool sta)
bool canModDynamicFields ()
bool canModStaticFields ()
void setAutoDelete (bool val)
void setEditorOnly (bool val)
void setNameChangeAllowed (bool val)
bool getCanSave () const
Returns boolean specifying if the object can be serialized.
virtual void setCanSave (bool val)
Set serialization flag.
bool isSelectedRecursive () const
Returns true if this object is selected or any group it is a member of is.
SimObject ()
virtual ~SimObject ()
virtual bool processArguments (S32 argc, ConsoleValueRef *argv)
Process constructor options. (ie, new SimObject(1,2,3))
virtual void onGroupAdd ()
Called when the object is added to a SimGroup.
virtual void onGroupRemove ()
Called when the object is removed from a SimGroup.
virtual void onNameChange (const char *name)
Called when the object's name is changed.
virtual void onPostAdd ()
Called when the adding of the object to the sim is complete, all sub-objects have been processed as well.
virtual void onStaticModified (const char *slotName, const char *newValue=NULL)
Specifically, these are called by setDataField when a static or dynamic field is modified, see the console details.
virtual void onDynamicModified (const char *slotName, const char *newValue=NULL)
Called when a dynamic field is modified.
virtual void inspectPreApply ()
Called before any property of the object is changed in the world editor.
virtual void inspectPostApply ()
Called after any property of the object is changed in the world editor.
virtual void onDeleteNotify (SimObject *object)
Called when a SimObject is deleted.
virtual void onEditorEnable ()
Called when the editor is activated.
virtual void onEditorDisable ()
Called when the editor is deactivated.
bool registerObject ()
Register an object with the object system.
bool registerObject (U32 id)
Register the object, forcing the id.
bool registerObject (const char *name)
Register the object, assigning the name.
bool registerObject (const char *name, U32 id)
Register the object, assigning a name and ID.
void unregisterObject ()
Unregister the object from Sim.
void deleteObject ()
Unregister, mark as deleted, and free the object.
void safeDeleteObject ()
Performs a safe delayed delete of the object using a sim event.
bool addToSet (SimObjectId)
bool addToSet (const char *)
bool removeFromSet (SimObjectId)
bool removeFromSet (const char *)
virtual String describeSelf () const
Return a textual description of the object.
void dumpToConsole (bool includeFunctions=true)
Dump the contents of this object to the console.
virtual void dumpClassHierarchy ()
added this so that you can print the entire class hierarchy, including script objects,
virtual void dumpGroupHierarchy ()
Print the SimGroup hierarchy of this object to the console.
Public Member Functions inherited from ConsoleObject
ConsoleObject ()
virtual AbstractClassRep * getClassRep () const
Gets the ClassRep.
const AbstractClassRep::Field * findField (StringTableEntry fieldName) const
Get a reference to a field by name.
bool setField (const char *fieldName, const char *value)
Set the value of a field.
void logMessage (const char *fmt,...) const
Logs with Con::printf.
void logWarning (const char *fmt,...) const
Logs with Con::warnf.
void logError (const char *fmt,...) const
Logs with Con::errorf.
const AbstractClassRep::FieldList & getFieldList () const
Get a list of all the fields. This information cannot be modified.
AbstractClassRep::FieldList & getModifiableFieldList ()
Get a list of all the fields, set up so we can modify them.
bool & getDynamicGroupExpand ()
Get a handle to a boolean telling us if we expanded the dynamic group.
S32 getClassId (U32 netClassGroup) const
Get our network-layer class id.
StringTableEntry getClassName () const
Get our compiler and platform independent class name.
Public Member Functions inherited from EngineObject
EngineObject ()
virtual ~EngineObject ()
DECLARE_ABSTRACT_CLASS (EngineObject, void)
DECLARE_INSCOPE (_GLOBALSCOPE)
IEngineObjectPool * getEngineObjectPool () const
Return the pool of EngineObjects to which this object belongs.
void operator delete (void *ptr)
Release the given object's memory in the pool it has been allocated from.
void * operator new (size_t size)
void * operator new (size_t size, IEngineObjectPool *pool)
void * operator new (size_t size TORQUE_TMM_ARGS_DECL)
Allocate a new object in the default object pool.
void * operator new (size_t size, IEngineObjectPool *pool TORQUE_TMM_ARGS_DECL)
Allocate a new object in the given object pool.
void * operator new (size_t size, void *ptr)
Placement new.
Public Member Functions inherited from StrongRefBase
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Static Public Member Functions
static void initPersistFields ()
Static Public Member Functions inherited from SimObject
static SimObject * __findObject (const char *id)
static const char * __getObjectId (ConsoleObject *object)
static void initPersistFields ()
static void setForcedId (SimObjectId id)
Force an Id on the next registered object.
Static Public Member Functions inherited from ConsoleObject
static const char * __category ()
static const char * __description ()
static void consoleInit ()
Register global constant variables and do other one-time initialization tasks in a subclass of ConsoleObject.
static void initPersistFields ()
Register dynamic fields in a subclass of ConsoleObject.
static const char * lookupClassName (const U32 in_classTag)
Get the classname from a class tag.
static ConsoleObject * create (const char *in_pClassName)
static ConsoleObject * create (const U32 groupId, const U32 typeId, const U32 in_classId)
static void addGroup (const char *in_pGroupname, const char *in_pGroupDocs=NULL)
Mark the beginning of a group of fields.
static void endGroup (const char *in_pGroupname)
Mark the end of a group of fields.
static void addArray (const char *arrayName, S32 count)
Marks the start of a fixed size array of fields.
static void endArray (const char *arrayName)
Marks the end of an array of fields.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a complex field.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::WriteDataNotify in_writeDataFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, const char *in_pFieldDocs, U32 flags=0)
Register a simple field.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::WriteDataNotify in_writeDataFn, const char *in_pFieldDocs, U32 flags=0)
static void addFieldV (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, TypeValidator *v, const char *in_pFieldDocs=NULL)
Register a validated field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, AbstractClassRep::WriteDataNotify in_writeDataFn=&defaultProtectedWriteFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a complex protected field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, AbstractClassRep::WriteDataNotify in_writeDataFn=&defaultProtectedWriteFn, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a simple protected field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addDeprecatedField (const char *fieldName)
Add a deprecated field.
static bool removeField (const char *in_pFieldname)
Remove a field.
static AbstractClassRep * getStaticClassRep ()
Get the abstract class information for this class.
static AbstractClassRep * getParentStaticClassRep ()
Get the abstract class information for this class's superclass.
static ConsoleObject * __findObject (const char *)
static const char * __getObjectId (ConsoleObject *)
Static Public Member Functions inherited from EngineObject
static void debugDumpInstances ()
Dump describeSelf()s of all live ConsoleObjects to the console.
static void debugEnumInstances (const std::type_info &type, DebugEnumInstancesCallback callback)
Call the given callback for all instances of the given type.
static void debugEnumInstances (const char *className, DebugEnumInstancesCallback callback)
Same as above but uses an export class name and also includes inheritance (i.e.
Protected Member Functions
void _calcAxisInfo ()
GizmoAlignment _filteredAlignment ()
F32 _getProjectionLength (F32 dist) const
void _renderAxisArrows ()
void _renderAxisBoxes ()
void _renderAxisCircles ()
void _renderAxisText ()
void _renderPlane ()
void _renderPrimaryAxis ()
void _setStateBlock ()
F32 _snapFloat (const F32 &val, const F32 &snap) const
Point3F _snapPoint (const Point3F &pnt) const
void _updateEnabledAxices ()
void _updateState (bool collideGizmo=true)
Protected Member Functions inherited from SimObject
virtual void _destroySelf ()
Subclasses should overload this method instead of the public destroySelf().
virtual String _getLogMessage (const char *fmt, va_list args) const
We can provide more detail, like object name and id.
virtual void _onSelected ()
Called when the object is selected in the editor.
virtual void _onUnselected ()
Called when the object is unselected in the editor.
object incRefCount ()
virtual void onTamlAddParent (SimObject *pParentObject)
Called after Taml has finished reading the object and has added the object to any parent.
virtual void onTamlCustomRead (const TamlCustomNodes &customNodes)
Called during the reading of the object to allow custom properties to be read.
virtual void onTamlCustomWrite (TamlCustomNodes &customNodes)
Called during the writing of the object to allow custom properties to be written.
virtual void onTamlPostRead (const TamlCustomNodes &customNodes)
Called after Taml has finished reading the object.
virtual void onTamlPostWrite (void)
Called after Taml has finished writing the object.
virtual void onTamlPreRead (void)
Called prior to Taml reading the object.
virtual void onTamlPreWrite (void)
Taml callbacks.
object registerObject ()
void linkNamespaces ()
Perform namespace linking on this object.
void unlinkNamespaces ()
Undo namespace linking on this object.
Protected Member Functions inherited from ConsoleObject
ConsoleObject (const ConsoleObject &)
Protected Member Functions inherited from EngineObject
object incRefCount ()
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Protected Attributes
bool mAxisEnabled [3]
MatrixF mCameraMat
Point3F mCameraPos
GizmoAlignment mCurrentAlignment
GizmoMode mCurrentMode
MatrixF mCurrentTransform
F32 mDeltaAngle
Point3F mDeltaPos
EulerF mDeltaRot
Point3F mDeltaScale
Point3F mDeltaTotalPos
EulerF mDeltaTotalRot
Point3F mDeltaTotalScale
bool mDirty
Point3F mElipseCursorCollidePntSS
Point3F mElipseCursorCollideVecSS
bool mGridPlaneEnabled
If false, don't render the grid plane even if it is enabled in the profile.
bool mHighlightAll
bool mHighlightCentroidHandle
F32 mLastAngle
F32 mLastCameraFOV
Gui3DMouseEvent mLastMouseEvent
MatrixF mLastProjMat
Point3F mLastScale
RectI mLastViewport
MatrixF mLastWorldMat
Point2F mLastWorldToScreenScale
MathUtils::Line mMouseCollideLine
PlaneF mMouseCollidePlane
bool mMouseDown
Point2I mMouseDownPos
Point3F mMouseDownProjPnt
bool mMoveGridEnabled
If false, don't render a transparent grid overlay when using the move gizmo.
F32 mMoveGridSize
Size of the move grid along one dimension.
U32 mMoveGridSpacing
Spacing between grid lines on the move grid.
MatrixF mObjectMat
MatrixF mObjectMatInv
Point3F mOrigin
GizmoProfile * mProfile
Point3F mProjAxisVector [3]
F32 mProjLen
Point3F mProjPnt
EulerF mRot
EulerF mSavedRot
Point3F mSavedScale
MatrixF mSavedTransform
Point3F mScale
Point3F mScaleInfluence
bool mScreenRotateHandleEnabled
S32 mSelectionIdx
F32 mSign
GFXStateBlockRef mSolidStateBlock
GFXStateBlockRef mStateBlock
MatrixF mTransform
bool mUniformHandleEnabled
Protected Attributes inherited from SimObject
DEFINE_CREATE_METHOD
SimObjectId mId
Id number for this object.
StringTableEntry mInternalName
Internal name assigned to the object. Not set by default.
return object
bool mCanSaveFieldDictionary
Whether dynamic fields should be saved out in serialization. Defaults to true.
SimPersistID * mPersistentId
Persistent ID assigned to this object.
Namespace * mNameSpace
The namespace in which method lookup for this object begins.
StringTableEntry mClassName
Name of namespace to use as class namespace.
StringTableEntry mSuperClassName
Name of namespace to use as class super namespace.
Protected Attributes inherited from EngineObject
DEFINE_CREATE_METHOD
return object
Protected Attributes inherited from StrongRefBase
U32 mRefCount
reference counter for StrongRefPtr objects
Static Protected Attributes
static F32 smProjectDistance
A large hard coded distance used to test gizmo axis selection.
Static Protected Attributes inherited from SimObject
static SimObjectId smForcedId
The Id to force upon the object. Poor object.
static bool smForceId
Force a registered object to use the given Id. Cleared upon use.
Additional Inherited Members
Public Attributes inherited from EngineObject
DECLARE_INSTANTIABLE
Static Public Attributes inherited from ConsoleObject
static const bool __smIsDatablock = false
Subclasses of ConsoleObjects that are datablocks should redefine this static member variable and set it to true.
Protected Types inherited from EngineObject
typedef ::FalseType __IsDisposableType
typedef ::FalseType __IsSingletonType
Static Protected Member Functions inherited from SimObject
static bool _setPersistentID (void *object, const char *index, const char *data)
Static Protected Member Functions inherited from EngineObject
static void * _allocateObject (size_t size, IEngineObjectPool *pool TORQUE_TMM_ARGS_DECL)
Member Enumeration Documentation
enum Gizmo::Selection
Enumerator
None
Axis_X
Axis_Y
Axis_Z
Plane_XY
Plane_XZ
Plane_YZ
Centroid
Custom1
Custom2
Constructor & Destructor Documentation
Gizmo::Gizmo ()
Gizmo::~Gizmo ()
Member Function Documentation
void Gizmo::_calcAxisInfo () protected
GizmoAlignment Gizmo::_filteredAlignment () protected
F32 Gizmo::_getProjectionLength (F32 dist) const inline protected
References Point3F::len(), and Point3F::y.
void Gizmo::_renderAxisArrows () protected
void Gizmo::_renderAxisBoxes () protected
void Gizmo::_renderAxisCircles () protected
void Gizmo::_renderAxisText () protected
void Gizmo::_renderPlane () protected
void Gizmo::_renderPrimaryAxis () protected
void Gizmo::_setStateBlock () protected
F32 Gizmo::_snapFloat (const F32 & val, const F32 & snap) const protected
Point3F Gizmo::_snapPoint (const Point3F & pnt) const protected
void Gizmo::_updateEnabledAxices () protected
void Gizmo::_updateState (bool collideGizmo = true) protected
bool Gizmo::collideAxisGizmo (const Gui3DMouseEvent & event)
Gizmo::DECLARE_CONOBJECT (Gizmo)
GizmoAlignment Gizmo::getAlignment () const inline
const Point3F& Gizmo::getDeltaRot () const inline
const Point3F& Gizmo::getDeltaScale () const inline
const Point3F& Gizmo::getDeltaTotalRot () const inline
const Point3F& Gizmo::getDeltaTotalScale () const inline
GizmoMode Gizmo::getMode () const inline
const Point3F& Gizmo::getOffset () const inline
Point3F Gizmo::getPosition () const inline
GizmoProfile* Gizmo::getProfile () inline
References GuiControl::mProfile.
const Point3F& Gizmo::getScale () const inline
Selection Gizmo::getSelection ()
const Point3F& Gizmo::getTotalOffset () const inline
const MatrixF& Gizmo::getTransform () const inline
Returns current object to world transform of the object being manipulated.
static void Gizmo::initPersistFields () static
bool Gizmo::isDirty () inline
void Gizmo::markClean () inline
void Gizmo::on3DMouseDown (const Gui3DMouseEvent & event)
void Gizmo::on3DMouseDragged (const Gui3DMouseEvent & event)
void Gizmo::on3DMouseMove (const Gui3DMouseEvent & event)
void Gizmo::on3DMouseUp (const Gui3DMouseEvent & event)
bool Gizmo::onAdd () virtual
Called when the object is added to the sim.
Reimplemented from SimObject.
void Gizmo::onRemove () virtual
Called when the object is removed from the sim.
Reimplemented from SimObject.
void Gizmo::renderGizmo (const MatrixF & cameraTransform, F32 camerFOV = 1.5f)
void Gizmo::renderText (const RectI & viewPort, const MatrixF & modelView, const MatrixF & projection)
Point3F Gizmo::selectionToAxisVector (Selection axis)
void Gizmo::set (const MatrixF & objMat, const Point3F & worldPos, const Point3F & objScale)
void Gizmo::setCentroidHandleHighlight (bool state) inline
References WorldEditor::on3DMouseDown(), WorldEditor::on3DMouseDragged(), WorldEditor::on3DMouseMove(), and WorldEditor::on3DMouseUp().
void Gizmo::setGridPlaneEnabled (bool value) inline
Set whether to render the grid plane.
void Gizmo::setMoveGridEnabled (bool value) inline
Set whether to a transparent grid overlay when using the move gizmo.
void Gizmo::setMoveGridSize (F32 value) inline
Set the size of the move grid along one dimension.
The total size of the move grid is value * value.
void Gizmo::setMoveGridSpacing (F32 value) inline
Set the spacing between grid lines on the move grid.
void Gizmo::setProfile (GizmoProfile * profile) inline
References GuiControl::mProfile.
void Gizmo::setSelection (Selection sel) inline
Member Data Documentation
bool Gizmo::mAxisEnabled[3] protected
MatrixF Gizmo::mCameraMat protected
Point3F Gizmo::mCameraPos protected
GizmoAlignment Gizmo::mCurrentAlignment protected
GizmoMode Gizmo::mCurrentMode protected
MatrixF Gizmo::mCurrentTransform protected
F32 Gizmo::mDeltaAngle protected
Point3F Gizmo::mDeltaPos protected
EulerF Gizmo::mDeltaRot protected
Point3F Gizmo::mDeltaScale protected
Point3F Gizmo::mDeltaTotalPos protected
EulerF Gizmo::mDeltaTotalRot protected
Point3F Gizmo::mDeltaTotalScale protected
bool Gizmo::mDirty protected
Point3F Gizmo::mElipseCursorCollidePntSS protected
Point3F Gizmo::mElipseCursorCollideVecSS protected
bool Gizmo::mGridPlaneEnabled protected
If false, don't render the grid plane even if it is enabled in the profile.
bool Gizmo::mHighlightAll protected
bool Gizmo::mHighlightCentroidHandle protected
F32 Gizmo::mLastAngle protected
F32 Gizmo::mLastCameraFOV protected
Gui3DMouseEvent Gizmo::mLastMouseEvent protected
MatrixF Gizmo::mLastProjMat protected
Point3F Gizmo::mLastScale protected
RectI Gizmo::mLastViewport protected
MatrixF Gizmo::mLastWorldMat protected
Point2F Gizmo::mLastWorldToScreenScale protected
MathUtils::Line Gizmo::mMouseCollideLine protected
PlaneF Gizmo::mMouseCollidePlane protected
bool Gizmo::mMouseDown protected
Point2I Gizmo::mMouseDownPos protected
Point3F Gizmo::mMouseDownProjPnt protected
bool Gizmo::mMoveGridEnabled protected
If false, don't render a transparent grid overlay when using the move gizmo.
F32 Gizmo::mMoveGridSize protected
Size of the move grid along one dimension.
U32 Gizmo::mMoveGridSpacing protected
Spacing between grid lines on the move grid.
MatrixF Gizmo::mObjectMat protected
MatrixF Gizmo::mObjectMatInv protected
Point3F Gizmo::mOrigin protected
GizmoProfile* Gizmo::mProfile protected
Point3F Gizmo::mProjAxisVector[3] protected
F32 Gizmo::mProjLen protected
Point3F Gizmo::mProjPnt protected
EulerF Gizmo::mRot protected
EulerF Gizmo::mSavedRot protected
Point3F Gizmo::mSavedScale protected
MatrixF Gizmo::mSavedTransform protected
Point3F Gizmo::mScale protected
Point3F Gizmo::mScaleInfluence protected
bool Gizmo::mScreenRotateHandleEnabled protected
S32 Gizmo::mSelectionIdx protected
F32 Gizmo::mSign protected
GFXStateBlockRef Gizmo::mSolidStateBlock protected
GFXStateBlockRef Gizmo::mStateBlock protected
MatrixF Gizmo::mTransform protected
bool Gizmo::mUniformHandleEnabled protected
F32 Gizmo::smProjectDistance static protected
A large hard coded distance used to test gizmo axis selection.
Copyright © GarageGames, LLC. All Rights Reserved.