SFXSound Class Reference
Main Modules Class List Namespace List Online
SFXSound Class Reference
A scriptable controller playing a specific single sound file.
#include <sfx/sfxSound.h>
Public Member Functions
SFXSound ()
The default constructor is only here to satisfy the construction needs of IMPLEMENT_CONOBJECT.
DECLARE_CONOBJECT (SFXSound)
U32 getDuration () const
Returns the source's total playback time in milliseconds.
virtual F32 getElapsedPlayTimeCurrentCycle () const
Return the elapsed play time of the current loop cycle so far in seconds.
U32 getPosition () const
Return the current playback position in milliseconds.
SFXProfile * getProfile () const
Return the SFXProfile datablock attached to this sound.
virtual F32 getTotalPlayTime () const
Return the total play time of the source in seconds.
bool hasVoice () const
This is normally called from the system to detect if this source has been assigned a voice for playback.
bool isBlocked () const
Return true if the sound stream tied to the source is currently in a buffer underrun situation.
bool isReady () const
Returns true if the source's associated data is ready for playback.
bool isStreaming () const
Returns true if this is a continuously streaming source.
virtual bool isVirtualized () const
Returns true if the source is currently being virtualized.
virtual void onDeleteNotify (SimObject *object)
Called when a SimObject is deleted.
virtual void onRemove ()
Called when the object is removed from the sim.
void setPosition (U32 ms)
Set the current playback position in milliseconds.
virtual void setTransform (const MatrixF &transform)
Sets the position and orientation for a 3d buffer.
virtual void setVelocity (const VectorF &velocity)
Sets the velocity for a 3d buffer.
Public Member Functions inherited from SFXSource
SFXSource ()
~SFXSource ()
virtual bool acceptsAsChild (SimObject *object)
DECLARE_CATEGORY ("SFX")
DECLARE_CONOBJECT (SFXSource)
DECLARE_DESCRIPTION ("SFX sound playback controller.")
SFXDescription * getDescription () const
Return the SFX description associated with this source. Never NULL.
SFXSource * getSourceGroup () const
Return the source group that this source has been assigned to.
SFXTrack * getTrack () const
Returns the track played by this source; NULL for sources playing directly from streams.
virtual bool onAdd ()
Called when the object is added to the sim.
virtual void onGroupAdd ()
Called when the object is added to a SimGroup.
void update ()
SFXStatus getLastStatus () const
Returns the last known status without doing an update.
SFXStatus getSavedStatus () const
Return the status that the source wants to be in.
SFXStatus getStatus () const
Returns the sound status.
bool isPlaying () const
Returns true if the source is playing.
bool isStopped () const
Returns true if the source is stopped.
bool isPaused () const
Returns true if the source has been paused.
bool isLooping () const
Returns true if this is a looping source.
virtual void play (F32 fadeInTime=-1.f)
Starts the sound from the current playback position.
virtual void stop (F32 fadeOutTime=-1.f)
Stops playback and resets the playback position.
virtual void pause (F32 fadeOutTime=-1.f)
Pauses the sound playback.
virtual F32 getElapsedPlayTime () const
Return the total elapsed play time so far in seconds.
U32 getNumParameters () const
SFXParameter * getParameter (U32 index)
virtual void addParameter (SFXParameter *parameter)
virtual void removeParameter (SFXParameter *parameter)
virtual void notifyDescriptionChanged ()
Notify the source that its attached SFXDescription has changed.
virtual void notifyTrackChanged ()
Notify the source that its attached SFXTrack has changed.
F32 getVolume () const
Returns the source volume at its unaltered initial setting, i.e.
void setVolume (F32 volume)
Sets the source volume which will still be scaled by the master and group volumes.
F32 getModulativeVolume () const
void setModulativeVolume (F32 value)
Set the per-source volume scale factor.
F32 getPreAttenuatedVolume () const
F32 getAttenuatedVolume () const
Returns the volume with respect to the master and group volumes and the listener.
F32 getFadeInTime () const
F32 getFadeOutTime () const
void setFadeTimes (F32 fadeInTime, F32 fadeOutTime)
F32 getPriority () const
Returns the source priority.
void setPriority (F32 priority)
F32 getModulativePriority () const
void setModulativePriority (F32 value)
F32 getEffectivePriority () const
F32 getPitch () const
Returns the source pitch scale.
void setPitch (F32 pitch)
Sets the source pitch scale.
F32 getModulativePitch () const
void setModulativePitch (F32 value)
F32 getEffectivePitch () const
bool is3d () const
Returns true if this is a 3D source.
const VectorF & getVelocity () const
Returns the last set velocity.
const MatrixF & getTransform () const
Returns the last set transform.
void setMinMaxDistance (F32 min, F32 max)
Sets the minimum and maximum distances for 3d falloff.
void setCone (F32 innerAngle, F32 outerAngle, F32 outerVolume)
Set sound cone of a 3D sound.
F32 getDistToListener () const
Returns the last distance to the listener.
void addModifier (SFXModifier *modifier)
void addMarker (const String &name, F32 pos)
Public Member Functions inherited from SimGroup
~SimGroup ()
void addObject (SimObject *object, SimObjectId id)
void addObject (SimObject *object, const char *name)
virtual void addObject (SimObject *object)
Add the given object to the set.
virtual void clear ()
Remove all objects from this set.
virtual SimGroup * clone ()
Return a shallow copy of this object.
DECLARE_CONOBJECT (SimGroup)
virtual SimGroup * deepClone ()
Return a deep copy of this object.
virtual SimObject * findObject (const char *name)
Find a named sub-object of this object.
virtual void popObject ()
Remove an object from the end of the list.
virtual void pushObject (SimObject *object)
Add the given object to the end of the object list of this set.
virtual void removeObject (SimObject *object)
Remove the given object from the set.
Public Member Functions inherited from SimSet
SimSet ()
~SimSet ()
virtual void addTamlChild (SimObject *pSimObject)
Called when Taml attempts to populate an objects children during a read.
void callOnChildren (const String &method, S32 argc, ConsoleValueRef argv[], bool executeOnChildGroups=true)
DECLARE_CONOBJECT (SimSet)
SimObject * findObject (SimObject *object)
Find the given object in this set.
template<class T >
void findObjectByCallback (bool(*fn)(T *), Vector< T * > &foundObjects)
Add all child objects (including children of children) to the foundObjects Vector which are of type T and for which DecideAddObjectCallback return true;.
virtual SimObject * findObjectByInternalName (StringTableEntry internalName, bool searchChildren=false)
SimObject * findObjectByLineNumber (const char *fileName, S32 declarationLine, bool searchChildren=false)
template<class T >
void findObjectByType (Vector< T * > &foundObjects)
Add all child objects (including children of children) to the foundObjects Vector which are of type T.
SimObject * getRandom ()
const SetModificationSignal & getSetModificationSignal () const
Return the signal that is triggered when an object is added to or removed from the set.
SetModificationSignal & getSetModificationSignal ()
virtual SimObject * getTamlChild (const U32 childIndex) const
Called when Taml attempts to compile a list of children.
virtual U32 getTamlChildCount (void) const
Called when Taml attempts to compile a list of children.
void lock ()
virtual bool readObject (Stream *stream)
U32 sizeRecursive ()
Return the number of objects in this set as well as all sets that are contained in this set and its children.
void unlock ()
virtual void write (Stream &stream, U32 tabStop, U32 flags=0)
Output the TorqueScript to recreate this object.
virtual bool writeObject (Stream *stream)
virtual bool acceptsAsChild (SimObject *object) const
Return true if this set accepts the given object as a child.
void deleteAllObjects ()
Deletes all the objects in the set.
void bringObjectToFront (SimObject *obj)
void pushObjectToBack (SimObject *obj)
void scriptSort (const String &scriptCallbackFn)
Performs a sort of the objects in the set using a script callback function to do the comparison.
SimObject * front ()
SimObject * first ()
SimObject * last ()
bool empty () const
S32 size () const
iterator begin ()
iterator end ()
value operator[] (S32 index)
iterator find (iterator first, iterator last, SimObject *obj)
iterator find (SimObject *obj)
virtual bool reOrder (SimObject *obj, SimObject *target=0)
Reorder the position of "obj" to either be the last object in the list or, if "target" is given, to come before "target" in the list of children.
SimObject * at (S32 index) const
Return the object at the given index.
Public Member Functions inherited from SimObject
virtual void copyTo (SimObject *object)
Copy SimObject to another SimObject (Originally designed for T2D).
DECLARE_CONOBJECT (SimObject)
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
virtual void getConsoleMethodData (const char *fname, S32 routingId, S32 *type, S32 *minArgs, S32 *maxArgs, void **callback, const char **usage)
Namespace * getNamespace ()
Return the object's namespace.
StringTableEntry getProgenitorFile (void) const
virtual bool handlesConsoleMethod (const char *fname, S32 *routingId)
void setProgenitorFile (const char *pFile)
const char * tabComplete (const char *prevText, S32 baseLen, bool)
Get next matching item in namespace.
virtual bool writeField (StringTableEntry fieldname, const char *value)
Determine whether or not a field should be written.
virtual void writeFields (Stream &stream, U32 tabStop)
Write the fields of this object in TorqueScript.
void setCanSaveDynamicFields (bool bCanSave)
Set whether fields created at runtime should be saved. Default is true.
bool getCanSaveDynamicFields ()
Get whether fields created at runtime should be saved. Default is true.
SimObject * getCopySource () const
Return the object that this object is copying fields from.
void setCopySource (SimObject *object)
Set the object that this object should be copying fields from.
void assignFieldsFrom (SimObject *obj)
Copy fields from another object onto this one.
void assignDynamicFieldsFrom (SimObject *obj)
Copy dynamic fields from another object onto this one.
Notify * removeNotify (void *ptr, Notify::Type)
Remove a notification from the list.
void deleteNotify (SimObject *obj)
Notify an object when we are deleted.
void clearNotify (SimObject *obj)
Notify an object when we are cleared.
void clearAllNotifications ()
Remove all notifications for this object.
void processDeleteNotifies ()
Send out deletion notifications.
void registerReference (SimObject **obj)
Register a reference to this object.
void unregisterReference (SimObject **obj)
Unregister a reference to this object.
SimPersistID * getPersistentId () const
Return the persistent ID assigned to this object or NULL.
SimPersistID * getOrCreatePersistentId ()
Return the persistent ID assigned to this object or assign one to it if it has none.
StringTableEntry getClassNamespace () const
Return name of class namespace set on this object.
StringTableEntry getSuperClassNamespace () const
Return name of superclass namespace set on this object.
void setClassNamespace (const char *classNamespace)
void setSuperClassNamespace (const char *superClassNamespace)
const char * getDataField (StringTableEntry slotName, const char *array)
Get the value of a field on the object.
void setDataField (StringTableEntry slotName, const char *array, const char *value)
Set the value of a field on the object.
const char * getPrefixedDataField (StringTableEntry fieldName, const char *array)
void setPrefixedDataField (StringTableEntry fieldName, const char *array, const char *value)
const char * getPrefixedDynamicDataField (StringTableEntry fieldName, const char *array, const S32 fieldType=-1)
void setPrefixedDynamicDataField (StringTableEntry fieldName, const char *array, const char *value, const S32 fieldType=-1)
StringTableEntry getDataFieldPrefix (StringTableEntry fieldName)
U32 getDataFieldType (StringTableEntry slotName, const char *array)
Get the type of a field on the object.
void setDataFieldType (const U32 fieldTypeId, StringTableEntry slotName, const char *array)
Set the type of a dynamic field on the object.
void setDataFieldType (const char *typeName, StringTableEntry slotName, const char *array)
SimFieldDictionary * getFieldDictionary ()
Get reference to the dictionary containing dynamic fields.
virtual StringTableEntry getComponentName ()
void setInternalName (const char *newname)
These functions support internal naming that is not namespace bound for locating child controls in a generic way.
StringTableEntry getInternalName () const
Get the internal name of this control.
void setOriginalName (const char *originalName)
Set the original name of this control.
StringTableEntry getOriginalName () const
Get the original name of this control.
void setFilename (const char *file)
These functions allow you to set and access the filename where this object was created.
StringTableEntry getFilename () const
Get the filename.
void setDeclarationLine (U32 lineNumber)
These functions are used to track the line number (1-based) on which the object was created if it was loaded from script.
S32 getDeclarationLine () const
Get the declaration line number.
virtual bool save (const char *pcFilePath, bool bOnlySelected=false, const char *preappend=NULL)
Save object as a TorqueScript File.
virtual bool isMethod (const char *methodName)
Check if a method exists in the objects current namespace.
virtual bool isField (const char *fieldName, bool includeStatic=true, bool includeDynamic=true)
Return true if the field is defined on the object.
SimObjectId getId () const
Return the unique numeric object ID.
const char * getIdString () const
Return the object ID as a string.
StringTableEntry getName () const
Return the name of this object.
SimGroup * getGroup () const
Return the SimGroup that this object is contained in.
void assignName (const char *name)
Assign the given name to this object.
void setId (SimObjectId id)
bool isChildOfGroup (SimGroup *pGroup)
bool isProperlyAdded () const
bool isDeleted () const
bool isRemoved () const
virtual bool isLocked () const
virtual void setLocked (bool b)
virtual bool isHidden () const
virtual void setHidden (bool b)
bool isSelected () const
bool isExpanded () const
bool isEditorOnly () const
bool isNameChangeAllowed () const
bool isAutoDeleted () const
void setSelected (bool sel)
void setExpanded (bool exp)
void setModDynamicFields (bool dyn)
void setModStaticFields (bool sta)
bool canModDynamicFields ()
bool canModStaticFields ()
void setAutoDelete (bool val)
void setEditorOnly (bool val)
void setNameChangeAllowed (bool val)
bool getCanSave () const
Returns boolean specifying if the object can be serialized.
virtual void setCanSave (bool val)
Set serialization flag.
bool isSelectedRecursive () const
Returns true if this object is selected or any group it is a member of is.
SimObject ()
virtual ~SimObject ()
virtual void onGroupRemove ()
Called when the object is removed from a SimGroup.
virtual void onNameChange (const char *name)
Called when the object's name is changed.
virtual void onPostAdd ()
Called when the adding of the object to the sim is complete, all sub-objects have been processed as well.
virtual void onStaticModified (const char *slotName, const char *newValue=NULL)
Specifically, these are called by setDataField when a static or dynamic field is modified, see the console details.
virtual void onDynamicModified (const char *slotName, const char *newValue=NULL)
Called when a dynamic field is modified.
virtual void inspectPreApply ()
Called before any property of the object is changed in the world editor.
virtual void inspectPostApply ()
Called after any property of the object is changed in the world editor.
virtual void onEditorEnable ()
Called when the editor is activated.
virtual void onEditorDisable ()
Called when the editor is deactivated.
bool registerObject ()
Register an object with the object system.
bool registerObject (U32 id)
Register the object, forcing the id.
bool registerObject (const char *name)
Register the object, assigning the name.
bool registerObject (const char *name, U32 id)
Register the object, assigning a name and ID.
void unregisterObject ()
Unregister the object from Sim.
void deleteObject ()
Unregister, mark as deleted, and free the object.
void safeDeleteObject ()
Performs a safe delayed delete of the object using a sim event.
bool addToSet (SimObjectId)
bool addToSet (const char *)
bool removeFromSet (SimObjectId)
bool removeFromSet (const char *)
virtual String describeSelf () const
Return a textual description of the object.
void dumpToConsole (bool includeFunctions=true)
Dump the contents of this object to the console.
virtual void dumpClassHierarchy ()
added this so that you can print the entire class hierarchy, including script objects,
virtual void dumpGroupHierarchy ()
Print the SimGroup hierarchy of this object to the console.
Public Member Functions inherited from ConsoleObject
ConsoleObject ()
virtual AbstractClassRep * getClassRep () const
Gets the ClassRep.
const AbstractClassRep::Field * findField (StringTableEntry fieldName) const
Get a reference to a field by name.
bool setField (const char *fieldName, const char *value)
Set the value of a field.
void logMessage (const char *fmt,...) const
Logs with Con::printf.
void logWarning (const char *fmt,...) const
Logs with Con::warnf.
void logError (const char *fmt,...) const
Logs with Con::errorf.
const AbstractClassRep::FieldList & getFieldList () const
Get a list of all the fields. This information cannot be modified.
AbstractClassRep::FieldList & getModifiableFieldList ()
Get a list of all the fields, set up so we can modify them.
bool & getDynamicGroupExpand ()
Get a handle to a boolean telling us if we expanded the dynamic group.
S32 getClassId (U32 netClassGroup) const
Get our network-layer class id.
StringTableEntry getClassName () const
Get our compiler and platform independent class name.
Public Member Functions inherited from EngineObject
EngineObject ()
virtual ~EngineObject ()
DECLARE_ABSTRACT_CLASS (EngineObject, void)
DECLARE_INSCOPE (_GLOBALSCOPE)
IEngineObjectPool * getEngineObjectPool () const
Return the pool of EngineObjects to which this object belongs.
void operator delete (void *ptr)
Release the given object's memory in the pool it has been allocated from.
void * operator new (size_t size)
void * operator new (size_t size, IEngineObjectPool *pool)
void * operator new (size_t size TORQUE_TMM_ARGS_DECL)
Allocate a new object in the default object pool.
void * operator new (size_t size, IEngineObjectPool *pool TORQUE_TMM_ARGS_DECL)
Allocate a new object in the given object pool.
void * operator new (size_t size, void *ptr)
Placement new.
Public Member Functions inherited from StrongRefBase
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Static Public Member Functions
static S32 QSORT_CALLBACK qsortCompare (const void *item1, const void *item2)
Used to sort sources by attenuated volume and channel priority.
Static Public Member Functions inherited from SFXSource
static void initPersistFields ()
Static Public Member Functions inherited from SimObject
static SimObject * __findObject (const char *id)
static const char * __getObjectId (ConsoleObject *object)
static void initPersistFields ()
static void setForcedId (SimObjectId id)
Force an Id on the next registered object.
Static Public Member Functions inherited from ConsoleObject
static const char * __category ()
static const char * __description ()
static void consoleInit ()
Register global constant variables and do other one-time initialization tasks in a subclass of ConsoleObject.
static void initPersistFields ()
Register dynamic fields in a subclass of ConsoleObject.
static const char * lookupClassName (const U32 in_classTag)
Get the classname from a class tag.
static ConsoleObject * create (const char *in_pClassName)
static ConsoleObject * create (const U32 groupId, const U32 typeId, const U32 in_classId)
static void addGroup (const char *in_pGroupname, const char *in_pGroupDocs=NULL)
Mark the beginning of a group of fields.
static void endGroup (const char *in_pGroupname)
Mark the end of a group of fields.
static void addArray (const char *arrayName, S32 count)
Marks the start of a fixed size array of fields.
static void endArray (const char *arrayName)
Marks the end of an array of fields.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a complex field.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::WriteDataNotify in_writeDataFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, const char *in_pFieldDocs, U32 flags=0)
Register a simple field.
static void addField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::WriteDataNotify in_writeDataFn, const char *in_pFieldDocs, U32 flags=0)
static void addFieldV (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, TypeValidator *v, const char *in_pFieldDocs=NULL)
Register a validated field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, AbstractClassRep::WriteDataNotify in_writeDataFn=&defaultProtectedWriteFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a complex protected field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, const U32 in_elementCount=1, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, AbstractClassRep::WriteDataNotify in_writeDataFn=&defaultProtectedWriteFn, const char *in_pFieldDocs=NULL, U32 flags=0)
Register a simple protected field.
static void addProtectedField (const char *in_pFieldname, const U32 in_fieldType, const dsize_t in_fieldOffset, AbstractClassRep::SetDataNotify in_setDataFn, AbstractClassRep::GetDataNotify in_getDataFn=&defaultProtectedGetFn, const char *in_pFieldDocs=NULL, U32 flags=0)
static void addDeprecatedField (const char *fieldName)
Add a deprecated field.
static bool removeField (const char *in_pFieldname)
Remove a field.
static AbstractClassRep * getStaticClassRep ()
Get the abstract class information for this class.
static AbstractClassRep * getParentStaticClassRep ()
Get the abstract class information for this class's superclass.
static ConsoleObject * __findObject (const char *)
static const char * __getObjectId (ConsoleObject *)
Static Public Member Functions inherited from EngineObject
static void debugDumpInstances ()
Dump describeSelf()s of all live ConsoleObjects to the console.
static void debugEnumInstances (const std::type_info &type, DebugEnumInstancesCallback callback)
Call the given callback for all instances of the given type.
static void debugEnumInstances (const char *className, DebugEnumInstancesCallback callback)
Same as above but uses an export class name and also includes inheritance (i.e.
Protected Member Functions
SFXSound (SFXProfile *profile, SFXDescription *description)
Internal constructor used for sources.
bool _allocVoice (SFXDevice *device)
Create a new voice for this source.
virtual void _onParameterEvent (SFXParameter *parameter, SFXParameterEvent event)
void _onProfileChanged (SFXProfile *profile)
virtual void _pause ()
Pause playback.
virtual void _play ()
Start playback.
bool _releaseVoice ()
Release the voice if the source has one.
void _reloadBuffer ()
Reload the sound buffer. Temporarily goes to virtualized playback when necessary.
void _setBuffer (SFXBuffer *buffer)
virtual void _setCone (F32 innerAngle, F32 outerAngle, F32 outerVolume)
Set 3D cone without affecting CustomConeFlag.
virtual void _setMinMaxDistance (F32 min, F32 max)
Set 3D min/max distance without affecting CustomRadiusFlag.
virtual void _stop ()
Stop playback.
virtual void _updatePitch ()
Update the effective pitch of the source.
virtual void _updatePriority ()
Update the effective priority of the source.
virtual void _updateStatus ()
Update the playback status of the source.
virtual void _updateVolume (const MatrixF &listener)
Update the effective volume of the source.
Protected Member Functions inherited from SFXSource
SFXSource (SFXTrack *track, SFXDescription *description=NULL)
virtual void _update ()
virtual bool processArguments (S32 argc, ConsoleValueRef *argv)
We overload this to disable creation of a source via script 'new'.
DECLARE_CALLBACK (void, onStatusChange,(SFXStatus newStatus))
DECLARE_CALLBACK (void, onParameterValueChange,(SFXParameter *parameter))
virtual void _setFadeTimes (F32 fadeInTime, F32 fadeOutTime)
void _setupFadeOutSegment (FadeSegmentType type, F32 fadeOutTime)
Set up a temporary fade-out segment.
virtual void _setStatus (SFXStatus newStatus)
Used internally for setting the sound status.
void _setVolume (F32 volume)
Set volume without affecting CustomVolumeFlag.
void _setPriority (F32 priority)
Set priority without affecting CustomPriorityFlag.
void _setPitch (F32 pitch)
Set pitch without affecting CustomPitchFlag.
void _scatterTransform ()
Randomize transform based on scatter settings.
void _addParameter (StringTableEntry name)
template<class T >
void _clearModifiers ()
Delete all modifiers of the given type.
Protected Member Functions inherited from SimSet
DECLARE_CALLBACK (void, onObjectAdded,(SimObject *object))
DECLARE_CALLBACK (void, onObjectRemoved,(SimObject *object))
Protected Member Functions inherited from SimObject
virtual void _destroySelf ()
Subclasses should overload this method instead of the public destroySelf().
virtual String _getLogMessage (const char *fmt, va_list args) const
We can provide more detail, like object name and id.
virtual void _onSelected ()
Called when the object is selected in the editor.
virtual void _onUnselected ()
Called when the object is unselected in the editor.
object incRefCount ()
virtual void onTamlAddParent (SimObject *pParentObject)
Called after Taml has finished reading the object and has added the object to any parent.
virtual void onTamlCustomRead (const TamlCustomNodes &customNodes)
Called during the reading of the object to allow custom properties to be read.
virtual void onTamlCustomWrite (TamlCustomNodes &customNodes)
Called during the writing of the object to allow custom properties to be written.
virtual void onTamlPostRead (const TamlCustomNodes &customNodes)
Called after Taml has finished reading the object.
virtual void onTamlPostWrite (void)
Called after Taml has finished writing the object.
virtual void onTamlPreRead (void)
Called prior to Taml reading the object.
virtual void onTamlPreWrite (void)
Taml callbacks.
object registerObject ()
void linkNamespaces ()
Perform namespace linking on this object.
void unlinkNamespaces ()
Undo namespace linking on this object.
Protected Member Functions inherited from ConsoleObject
ConsoleObject (const ConsoleObject &)
Protected Member Functions inherited from EngineObject
object incRefCount ()
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Static Protected Member Functions
static SFXSound * _create (SFXDevice *device, SFXProfile *profile)
Used by SFXSystem to create sources.
static SFXSound * _create (SFXDevice *device, const ThreadSafeRef< SFXStream > &stream, SFXDescription *description)
Static Protected Member Functions inherited from SFXSource
static const char * _getDescription (void *obj, const char *data)
static bool _setDescription (void *obj, const char *index, const char *data)
Static Protected Member Functions inherited from SimObject
static bool _setPersistentID (void *object, const char *index, const char *data)
Static Protected Member Functions inherited from EngineObject
static void * _allocateObject (size_t size, IEngineObjectPool *pool TORQUE_TMM_ARGS_DECL)
Protected Attributes
StrongWeakRefPtr< SFXBuffer > mBuffer
The reference counted device specific buffer used by the voice for playback.
U32 mDuration
The duration of the sound cached from the buffer in _initBuffer() used for managing virtual sources.
StrongWeakRefPtr< SFXVoice > mVoice
The device specific voice which is used during playback.
Protected Attributes inherited from SFXSource
BitSet32 mFlags
SimObjectPtr< SFXTrack > mTrack
The track being played by this source.
SimObjectPtr< SFXDescription > mDescription
The description holding the SFX sound configuration.
F32 mFadeInTime
The current "persistent" fade-in time in seconds.
F32 mFadeOutTime
The current "persistent" fade-out time in seconds.
F32 mFadeInPoint
Playtime at which persistent fade-in ends. -1 if no fade-in.
F32 mFadeOutPoint
Playtime at which persistent fade-out starts. -1 if no fade-out.
FadeSegmentType mFadeSegmentType
Type of the current temporary fade segment.
EaseF * mFadeSegmentEase
Easing curve for the current fade segment.
F32 mFadeSegmentStartPoint
Playback position where the current temporary fade segment starts.
F32 mFadeSegmentEndPoint
Playback position where the current temporary fade segment ends.
F32 mSavedFadeTime
Fade time to apply when transitioning to mSavedStatus.
SFXStatus mStatus
Current playback status.
SFXStatus mSavedStatus
The playback status that the source actually wants to be in.
StringTableEntry mStatusCallback
Console functions to call when the source status changes.
F32 mVolume
The desired sound volume.
F32 mPreFadeVolume
Volume before fade stage.
F32 mFadedVolume
"mVolume" after fade stage.
F32 mModulativeVolume
Volume scale factor imposed on this source by controller.
F32 mPreAttenuatedVolume
Effective volume after fade and modulation but before distance attenuation.
F32 mAttenuatedVolume
Effective volume after distance attenuation.
F32 mPriority
The desired sound priority.
F32 mModulativePriority
The priority scale factor imposed by controllers.
F32 mEffectivePriority
The final priority level.
F32 mPitch
The desired sound pitch.
F32 mModulativePitch
The pitch scale factor imposed by controllers.
F32 mEffectivePitch
The final effective pitch.
MatrixF mTransform
The transform if this is a 3d source.
VectorF mVelocity
The last set velocity.
F32 mMinDistance
Distance at which to begin distanced-based volume attenuation.
F32 mMaxDistance
Distance at which to stop distance-based volume attenuation.
F32 mConeInsideAngle
Inside cone angle in degrees.
F32 mConeOutsideAngle
Outside cone angle in degrees.
F32 mConeOutsideVolume
Outside cone volume.
F32 mDistToListener
The distance of this source to the last listener position.
bool mTransformScattered
If true, the transform position has been randomized.
Vector< SFXParameter * > mParameters
U32 mPlayStartTick
The simulation tick count that playback was started at for this source.
TimeSource mPlayTimer
Time object used to keep track of playback.
ModifierList mModifiers
List of modifiers that are active on this source.
Protected Attributes inherited from SimSet
void * mMutex
SetModificationSignal mSetModificationSignal
Signal that is triggered when objects are added or removed from the set.
SimObjectList objectList
Protected Attributes inherited from SimObject
DEFINE_CREATE_METHOD
SimObjectId mId
Id number for this object.
StringTableEntry mInternalName
Internal name assigned to the object. Not set by default.
return object
bool mCanSaveFieldDictionary
Whether dynamic fields should be saved out in serialization. Defaults to true.
SimPersistID * mPersistentId
Persistent ID assigned to this object.
Namespace * mNameSpace
The namespace in which method lookup for this object begins.
StringTableEntry mClassName
Name of namespace to use as class namespace.
StringTableEntry mSuperClassName
Name of namespace to use as class super namespace.
Protected Attributes inherited from EngineObject
DEFINE_CREATE_METHOD
return object
Protected Attributes inherited from StrongRefBase
U32 mRefCount
reference counter for StrongRefPtr objects
Additional Inherited Members
Public Types inherited from SFXSource
typedef SimGroup Parent
Public Types inherited from SimGroup
typedef SimSet Parent
Public Types inherited from SimSet
typedef SimObject Parent
enum SetModification {
SetCleared,
SetObjectAdded,
SetObjectRemoved
}
typedef Signal< void(SetModification modification, SimSet *set, SimObject *object) > SetModificationSignal
Signal for letting observers know when objects are added to or removed from the set.
typedef SimObjectList::iterator iterator
typedef SimObjectList::value_type value
Public Types inherited from SimObject
typedef ConsoleObject Parent
enum WriteFlags {
SelectedOnly = BIT(0),
NoName = BIT(1),
IgnoreCanSave = BIT(2)
}
Flags passed to SimObject::write.
Public Types inherited from EngineObject
typedef void(* DebugEnumInstancesCallback) (EngineObject *)
Type of callback function for iterating over EngineObject instances.
Public Types inherited from IPositionable< U32 >
typedef void Parent
typedef U32 PositionType
The type used to indicate positions.
Public Attributes inherited from EngineObject
DECLARE_INSTANTIABLE
Static Public Attributes inherited from ConsoleObject
static const bool __smIsDatablock = false
Subclasses of ConsoleObjects that are datablocks should redefine this static member variable and set it to true.
Protected Types inherited from SFXSource
enum Flags {
CustomVolumeFlag = BIT(0),
CustomPitchFlag = BIT(1),
CustomPriorityFlag = BIT(2),
CustomRadiusFlag = BIT(3),
CustomConeFlag = BIT(4),
CustomFadeFlag = BIT(5),
CustomGroupFlag = BIT(6)
}
typedef Torque::List< SFXModifier * > ModifierList
typedef GenericTimeSource< RealMSTimer > TimeSource
enum FadeSegmentType {
FadeSegmentNone,
FadeSegmentPlay,
FadeSegmentStop,
FadeSegmentPause
}
Type for temporary fade segments.
Protected Types inherited from EngineObject
typedef ::FalseType __IsDisposableType
typedef ::FalseType __IsSingletonType
Static Protected Attributes inherited from SimObject
static SimObjectId smForcedId
The Id to force upon the object. Poor object.
static bool smForceId
Force a registered object to use the given Id. Cleared upon use.
Detailed Description
A scriptable controller playing a specific single sound file.
Constructor & Destructor Documentation
SFXSound::SFXSound (SFXProfile * profile, SFXDescription * description) protected
Internal constructor used for sources.
SFXSound::SFXSound () explicit
The default constructor is only here to satisfy the construction needs of IMPLEMENT_CONOBJECT.
It does not create a valid source!
Referenced by _onProfileChanged().
Member Function Documentation
bool SFXSound::_allocVoice (SFXDevice * device) protected
Create a new voice for this source.
static SFXSound* SFXSound::_create (SFXDevice * device, SFXProfile * profile) static protected
Used by SFXSystem to create sources.
static SFXSound* SFXSound::_create (SFXDevice * device, const ThreadSafeRef< SFXStream > & stream, SFXDescription * description) static protected
virtual void SFXSound::_onParameterEvent (SFXParameter * parameter, SFXParameterEvent event) protected virtual
Reimplemented from SFXSource.
Referenced by _onProfileChanged().
void SFXSound::_onProfileChanged (SFXProfile * profile) inline protected
References _onParameterEvent(), _pause(), _play(), _reloadBuffer(), _setCone(), _setMinMaxDistance(), _stop(), _updatePitch(), _updatePriority(), _updateStatus(), _updateVolume(), DECLARE_CONOBJECT(), SFXSource::mTrack, and SFXSound().
virtual void SFXSound::_pause () protected virtual
Pause playback.
For implementation by concrete subclasses.
Note
This method should not take fading into account.
Reimplemented from SFXSource.
Referenced by _onProfileChanged().
virtual void SFXSound::_play () protected virtual
Start playback.
For implementation by concrete subclasses.
Note
This method should not take fading into account.
Reimplemented from SFXSource.
Referenced by _onProfileChanged().
bool SFXSound::_releaseVoice () protected
Release the voice if the source has one.
void SFXSound::_reloadBuffer () protected
Reload the sound buffer. Temporarily goes to virtualized playback when necessary.
Referenced by _onProfileChanged().
void SFXSound::_setBuffer (SFXBuffer * buffer) protected
virtual void SFXSound::_setCone (F32 innerAngle, F32 outerAngle, F32 outerVolume) protected virtual
Set 3D cone without affecting CustomConeFlag.
Reimplemented from SFXSource.
Referenced by _onProfileChanged().
virtual void SFXSound::_setMinMaxDistance (F32 min, F32 max) protected virtual
Set 3D min/max distance without affecting CustomRadiusFlag.
Reimplemented from SFXSource.
Referenced by _onProfileChanged().
virtual void SFXSound::_stop () protected virtual
Stop playback.
For implementation by concrete subclasses.
Note
This method should not take fading into account.
Reimplemented from SFXSource.
Referenced by _onProfileChanged().
virtual void SFXSound::_updatePitch () protected virtual
Update the effective pitch of the source.
Reimplemented from SFXSource.
Referenced by _onProfileChanged().
virtual void SFXSound::_updatePriority () protected virtual
Update the effective priority of the source.
Reimplemented from SFXSource.
Referenced by _onProfileChanged().
virtual void SFXSound::_updateStatus () protected virtual
Update the playback status of the source.
Meant for subclasses that need to poll a connected resource.
Reimplemented from SFXSource.
Referenced by _onProfileChanged().
virtual void SFXSound::_updateVolume (const MatrixF & listener) protected virtual
Update the effective volume of the source.
Reimplemented from SFXSource.
Referenced by _onProfileChanged().
SFXSound::DECLARE_CONOBJECT (SFXSound)
Referenced by _onProfileChanged().
U32 SFXSound::getDuration () const inline
Returns the source's total playback time in milliseconds.
References mDuration.
virtual F32 SFXSound::getElapsedPlayTimeCurrentCycle () const virtual
Return the elapsed play time of the current loop cycle so far in seconds.
Reimplemented from SFXSource.
Referenced by isStreaming().
U32 SFXSound::getPosition () const virtual
Return the current playback position in milliseconds.
Note
For looping sources, this returns the position in the current cycle.
Implements IPositionable< U32 >.
Referenced by hasVoice().
SFXProfile* SFXSound::getProfile () const
Return the SFXProfile datablock attached to this sound.
Referenced by isStreaming().
virtual F32 SFXSound::getTotalPlayTime () const virtual
Return the total play time of the source in seconds.
Positive infinity by default.
Note
For looping sounds, this must include only the playtime of a single cycle.
Reimplemented from SFXSource.
Referenced by isStreaming().
bool SFXSound::hasVoice () const inline
This is normally called from the system to detect if this source has been assigned a voice for playback.
References getPosition(), and setPosition().
bool SFXSound::isBlocked () const inline
Return true if the sound stream tied to the source is currently in a buffer underrun situation.
References SFXVoice::getStatus().
bool SFXSound::isReady () const
Returns true if the source's associated data is ready for playback.
Referenced by isStreaming().
bool SFXSound::isStreaming () const inline
Returns true if this is a continuously streaming source.
References getElapsedPlayTimeCurrentCycle(), getProfile(), getTotalPlayTime(), isReady(), isVirtualized(), SFXSource::mDescription, onDeleteNotify(), onRemove(), qsortCompare(), setTransform(), and setVelocity().
virtual bool SFXSound::isVirtualized () const virtual
Returns true if the source is currently being virtualized.
Reimplemented from SFXSource.
Referenced by isStreaming().
virtual void SFXSound::onDeleteNotify (SimObject * object) virtual
Called when a SimObject is deleted.
When you are on the notification list for another object and it is deleted, this method is called.
Reimplemented from SFXSource.
Referenced by isStreaming().
virtual void SFXSound::onRemove () virtual
Called when the object is removed from the sim.
Reimplemented from SFXSource.
Referenced by isStreaming().
static S32 QSORT_CALLBACK SFXSound::qsortCompare (const void * item1, const void * item2) static
Used to sort sources by attenuated volume and channel priority.
Referenced by isStreaming().
void SFXSound::setPosition (U32 ms) virtual
Set the current playback position in milliseconds.
Implements IPositionable< U32 >.
Referenced by hasVoice().
virtual void SFXSound::setTransform (const MatrixF & transform) virtual
Sets the position and orientation for a 3d buffer.
Reimplemented from SFXSource.
Referenced by isStreaming().
virtual void SFXSound::setVelocity (const VectorF & velocity) virtual
Sets the velocity for a 3d buffer.
Reimplemented from SFXSource.
Referenced by isStreaming().
Member Data Documentation
StrongWeakRefPtr< SFXBuffer > SFXSound::mBuffer protected
The reference counted device specific buffer used by the voice for playback.
U32 SFXSound::mDuration protected
The duration of the sound cached from the buffer in _initBuffer() used for managing virtual sources.
Referenced by getDuration().
StrongWeakRefPtr< SFXVoice > SFXSound::mVoice protected
The device specific voice which is used during playback.
By making it a SafePtr it will NULL automatically when the device is deleted.
Copyright © GarageGames, LLC. All Rights Reserved.