rapidjson::FileWriteStream Class Reference
Main Modules Class List Namespace List Online
rapidjson::FileWriteStream Class Reference
Wrapper of C file stream for input using fread().
#include <persistence/rapidjson/filewritestream.h>
Public Types
typedef char Ch
Character type. Only support char.
Public Member Functions
FileWriteStream (FILE *fp, char *buffer, size_t bufferSize)
void Flush ()
char Peek () const
void Put (char c)
char * PutBegin ()
size_t PutEnd (char *)
void PutN (char c, size_t n)
char Take ()
size_t Tell () const
Detailed Description
Wrapper of C file stream for input using fread().
Member Typedef Documentation
typedef char rapidjson::FileWriteStream::Ch
Character type. Only support char.
Constructor & Destructor Documentation
rapidjson::FileWriteStream::FileWriteStream (FILE * fp, char * buffer, size_t bufferSize) inline
Member Function Documentation
void rapidjson::FileWriteStream::Flush () inline
Referenced by Put(), and PutN().
char rapidjson::FileWriteStream::Peek () const inline
void rapidjson::FileWriteStream::Put (char c) inline
References Flush().
char* rapidjson::FileWriteStream::PutBegin () inline
size_t rapidjson::FileWriteStream::PutEnd (char *) inline
void rapidjson::FileWriteStream::PutN (char c, size_t n) inline
References Flush().
Referenced by rapidjson::PutN().
char rapidjson::FileWriteStream::Take () inline
size_t rapidjson::FileWriteStream::Tell () const inline
Copyright © GarageGames, LLC. All Rights Reserved.