MacWindowManager Class Reference
Main Modules Class List Namespace List Online
MacWindowManager Class Reference
#include <windowManager/mac/macWindowManager.h>
Public Member Functions
MacWindowManager ()
~MacWindowManager ()
void _addWindow (MacWindow *window)
void _onAppSignal (WindowId wnd, S32 event)
void _removeWindow (MacWindow *window)
bool canWindowGainFocus (MacWindow *window)
virtual PlatformWindow * createWindow (GFXDevice *device, const GFXVideoMode &mode)
Create a new window, appropriate for the specified device and mode.
virtual void * getParentWindow ()
Get the parent window.
bool onShutdown ()
virtual void setParentWindow (void *newParent)
Set the parent window.
Desktop Queries
virtual RectI getPrimaryDesktopArea ()
Return the extents in window coordinates of the primary desktop area.
virtual void getMonitorRegions (Vector< RectI > &regions)
Populate a vector with all monitors and their extents in window space.
virtual S32 getDesktopBitDepth ()
Retrieve the currently set desktop bit depth.
virtual Point2I getDesktopResolution ()
Retrieve the currently set desktop resolution.
Window Lookup
virtual S32 getWindowCount ()
Get the number of Window's in this system.
virtual void getWindows (VectorPtr< PlatformWindow * > &windows)
Populate a list with references to all the windows created from this manager.
virtual PlatformWindow * getWindowById (WindowId id)
Get a window from a device ID.
virtual PlatformWindow * getFirstWindow ()
Get the first window in the window list.
virtual PlatformWindow * getFocusedWindow ()
Get the window that currently has the input focus or NULL.
virtual void lowerCurtain ()
During full-screen toggles we want to suppress ugly transition states, which we do (on Win32) by showing and hiding a full-monitor black window.
virtual void raiseCurtain ()
Command Line Usage
virtual void _processCmdLineArgs (const S32 argc, const char **argv)
Process command line arguments sent to this window manager to manipulate it's windows.
Public Member Functions inherited from PlatformWindowManager
PlatformWindowManager ()
virtual ~PlatformWindowManager ()
virtual void buildMonitorsList ()
virtual S32 findFirstMatchingMonitor (const char *name)
virtual U32 getMonitorCount ()
virtual const char * getMonitorName (U32 index)
virtual RectI getMonitorRect (U32 index)
virtual void setDisplayWindow (bool set)
This method indicates to created windows to show as normal.
Additional Inherited Members
Static Public Member Functions inherited from PlatformWindowManager
static PlatformWindowManager * get ()
Get Global Singleton.
static void processCmdLineArgs (const S32 argc, const char **argv)
Protected Member Functions inherited from PlatformWindowManager
S32 getNextId ()
Get the next available window Id.
Constructor & Destructor Documentation
MacWindowManager::MacWindowManager ()
MacWindowManager::~MacWindowManager ()
Member Function Documentation
void MacWindowManager::_addWindow (MacWindow * window)
Referenced by getParentWindow().
void MacWindowManager::_onAppSignal (WindowId wnd, S32 event)
Referenced by getParentWindow().
virtual void MacWindowManager::_processCmdLineArgs (const S32 argc, const char ** argv) virtual
Process command line arguments sent to this window manager to manipulate it's windows.
Implements PlatformWindowManager.
Referenced by getParentWindow().
void MacWindowManager::_removeWindow (MacWindow * window)
Referenced by getParentWindow().
bool MacWindowManager::canWindowGainFocus (MacWindow * window)
Referenced by getParentWindow().
virtual PlatformWindow* MacWindowManager::createWindow (GFXDevice * device, const GFXVideoMode & mode) virtual
Create a new window, appropriate for the specified device and mode.
Returns
Pointer to the new window.
Implements PlatformWindowManager.
Referenced by getParentWindow().
virtual S32 MacWindowManager::getDesktopBitDepth () virtual
Retrieve the currently set desktop bit depth.
Returns
The current desktop bit depth, or -1 if an error occurred
Implements PlatformWindowManager.
Referenced by getParentWindow().
virtual Point2I MacWindowManager::getDesktopResolution () virtual
Retrieve the currently set desktop resolution.
Returns
The current desktop bit depth, or Point2I(-1,-1) if an error occurred
Implements PlatformWindowManager.
Referenced by getParentWindow().
virtual PlatformWindow* MacWindowManager::getFirstWindow () virtual
Get the first window in the window list.
Returns
The first window in the list, or NULL if no windows found
Implements PlatformWindowManager.
Referenced by getParentWindow().
virtual PlatformWindow* MacWindowManager::getFocusedWindow () virtual
Get the window that currently has the input focus or NULL.
Implements PlatformWindowManager.
Referenced by getParentWindow().
virtual void MacWindowManager::getMonitorRegions (Vector< RectI > & regions) virtual
Populate a vector with all monitors and their extents in window space.
Implements PlatformWindowManager.
Referenced by getParentWindow().
virtual void* MacWindowManager::getParentWindow () inline virtual
Get the parent window.
Implements PlatformWindowManager.
References _addWindow(), _onAppSignal(), _processCmdLineArgs(), _removeWindow(), canWindowGainFocus(), createWindow(), getDesktopBitDepth(), getDesktopResolution(), getFirstWindow(), getFocusedWindow(), getMonitorRegions(), getPrimaryDesktopArea(), getWindowById(), getWindowCount(), getWindows(), lowerCurtain(), onShutdown(), and raiseCurtain().
virtual RectI MacWindowManager::getPrimaryDesktopArea () virtual
Return the extents in window coordinates of the primary desktop area.
On a single monitor system this is just the display extents. On a multi-monitor system this is the primary monitor (which Torque should launch on).
Implements PlatformWindowManager.
Referenced by getParentWindow().
virtual PlatformWindow* MacWindowManager::getWindowById (WindowId id) virtual
Get a window from a device ID.
Returns
The window associated with the specified ID, or NULL if no match was found.
Implements PlatformWindowManager.
Referenced by getParentWindow().
virtual S32 MacWindowManager::getWindowCount () virtual
Get the number of Window's in this system.
Referenced by getParentWindow().
virtual void MacWindowManager::getWindows (VectorPtr< PlatformWindow * > & windows) virtual
Populate a list with references to all the windows created from this manager.
Implements PlatformWindowManager.
Referenced by getParentWindow().
virtual void MacWindowManager::lowerCurtain () virtual
During full-screen toggles we want to suppress ugly transition states, which we do (on Win32) by showing and hiding a full-monitor black window.
This method cues the appearance of that window ("lowering the curtain").
Implements PlatformWindowManager.
Referenced by getParentWindow().
bool MacWindowManager::onShutdown ()
Referenced by getParentWindow().
virtual void MacWindowManager::raiseCurtain () virtual
See also
lowerCurtain
This method removes the curtain window.
Implements PlatformWindowManager.
Referenced by getParentWindow().
virtual void MacWindowManager::setParentWindow (void * newParent) inline virtual
Set the parent window.
This can be used to render in a child window.
Implements PlatformWindowManager.
Copyright © GarageGames, LLC. All Rights Reserved.