WeakRefUnion< ExposedType > Class Template Reference
Main Modules Class List Namespace List Online
WeakRefUnion< ExposedType > Class Template Reference
Union of an arbitrary type with a WeakRefBase.
#include <core/util/refBase.h>
Public Member Functions
WeakRefUnion ()
WeakRefUnion (const WeakRefPtr< WeakRefBase > &ref, ExposedType *ptr)
WeakRefUnion (const Union &lock)
WeakRefUnion (WeakRefBase *ref)
~WeakRefUnion ()
ExposedType * getPointer () const
WeakRefPtr< WeakRefBase > getRef () const
bool isNull () const
operator ExposedType * () const
bool operator!= (const ExposedType *t) const
bool operator!= (const Union &t) const
ExposedType & operator* () const
ExposedType * operator-> () const
Union & operator= (const Union &ptr)
bool operator== (const ExposedType *t) const
bool operator== (const Union &t) const
void set (const WeakRefPtr< WeakRefBase > &ref, ExposedType *ptr)
Detailed Description
template<class ExposedType>
class WeakRefUnion< ExposedType >
Union of an arbitrary type with a WeakRefBase.
The exposed type will remain accessible so long as the WeakRefBase is not cleared. Once it is cleared, accessing the exposed type will result in a NULL pointer.
Constructor & Destructor Documentation
template<class ExposedType > WeakRefUnion< ExposedType >::WeakRefUnion () inline
template<class ExposedType > WeakRefUnion< ExposedType >::WeakRefUnion (const WeakRefPtr< WeakRefBase > & ref, ExposedType * ptr) inline
template<class ExposedType > WeakRefUnion< ExposedType >::WeakRefUnion (const Union & lock) inline
template<class ExposedType > WeakRefUnion< ExposedType >::WeakRefUnion (WeakRefBase * ref) inline
template<class ExposedType > WeakRefUnion< ExposedType >::~WeakRefUnion () inline
Member Function Documentation
template<class ExposedType > ExposedType* WeakRefUnion< ExposedType >::getPointer () const inline
Referenced by WeakRefUnion< ExposedType >::operator!=(), WeakRefUnion< ExposedType >::operator=(), and WeakRefUnion< ExposedType >::operator==().
template<class ExposedType > WeakRefPtr<WeakRefBase> WeakRefUnion< ExposedType >::getRef () const inline
template<class ExposedType > bool WeakRefUnion< ExposedType >::isNull (void) const inline
template<class ExposedType > WeakRefUnion< ExposedType >::operator ExposedType * () const inline
template<class ExposedType > bool WeakRefUnion< ExposedType >::operator!= (const ExposedType * t) const inline
template<class ExposedType > bool WeakRefUnion< ExposedType >::operator!= (const Union & t) const inline
References WeakRefUnion< ExposedType >::getPointer().
template<class ExposedType > ExposedType& WeakRefUnion< ExposedType >::operator* (void) const inline
template<class ExposedType > ExposedType* WeakRefUnion< ExposedType >::operator-> (void) const inline
template<class ExposedType > Union& WeakRefUnion< ExposedType >::operator= (const Union & ptr) inline
References WeakRefUnion< ExposedType >::getPointer().
template<class ExposedType > bool WeakRefUnion< ExposedType >::operator== (const ExposedType * t) const inline
template<class ExposedType > bool WeakRefUnion< ExposedType >::operator== (const Union & t) const inline
References WeakRefUnion< ExposedType >::getPointer().
template<class ExposedType > void WeakRefUnion< ExposedType >::set (const WeakRefPtr< WeakRefBase > & ref, ExposedType * ptr) inline
Copyright © GarageGames, LLC. All Rights Reserved.