VectorPtr< T > Class Template Reference
Main Modules Class List Namespace List Online
VectorPtr< T > Class Template Reference
Template for vectors of pointers.
#include <core/util/tVector.h>
Public Member Functions
VectorPtr ()
VectorPtr (const char *fileName, const U32 lineNum)
STL interface
typedef T value_type
typedef T & reference
typedef const T & const_reference
typedef T * iterator
typedef const T * const_iterator
typedef U32 difference_type
typedef U32 size_type
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
void insert (iterator, const T &)
void insert (S32 idx)
void erase (iterator)
T & front ()
const T & front () const
T & back ()
const T & back () const
void push_front (const T &)
void push_back (const T &)
T & operator[] (U32)
const T & operator[] (U32) const
Extended interface
typedef Vector< void * > Parent
T & first ()
T & last ()
const T & first () const
const T & last () const
void erase_fast (U32)
void erase_fast (iterator)
Detailed Description
template<class T>
class VectorPtr< T >
Template for vectors of pointers.
Member Typedef Documentation
template<class T> typedef const T* VectorPtr< T >::const_iterator
template<class T> typedef const T& VectorPtr< T >::const_reference
template<class T> typedef U32 VectorPtr< T >::difference_type
template<class T> typedef T* VectorPtr< T >::iterator
template<class T> typedef Vector<void*> VectorPtr< T >::Parent
template<class T> typedef T& VectorPtr< T >::reference
template<class T> typedef U32 VectorPtr< T >::size_type
template<class T> typedef T VectorPtr< T >::value_type
Constructor & Destructor Documentation
template<class T > VectorPtr< T >::VectorPtr () inline
template<class T > VectorPtr< T >::VectorPtr (const char * fileName, const U32 lineNum) inline
Member Function Documentation
template<class T > T & VectorPtr< T >::back () inline
References VectorPtr< T >::end(), and Vector< void * >::mElementCount.
template<class T > const T & VectorPtr< T >::back () const inline
References VectorPtr< T >::end(), and Vector< void * >::mElementCount.
template<class T > VectorPtr< T >::iterator VectorPtr< T >::begin () inline
References Vector< void * >::begin().
Referenced by SimSet::begin(), Dispatcher::MessageQueue::dispatchMessage(), Dispatcher::MessageQueue::dispatchMessageObject(), SimSet::findObjectByCallback(), SimSet::findObjectByType(), VectorPtr< T >::front(), and VectorSet< T >::insert().
template<class T > VectorPtr< T >::const_iterator VectorPtr< T >::begin () const inline
References Vector< void * >::begin().
template<class T > VectorPtr< T >::iterator VectorPtr< T >::end () inline
References Vector< void * >::end().
Referenced by VectorPtr< T >::back(), Dispatcher::MessageQueue::dispatchMessage(), Dispatcher::MessageQueue::dispatchMessageObject(), SimSet::end(), SimSet::findObjectByCallback(), SimSet::findObjectByType(), and VectorSet< T >::insert().
template<class T > VectorPtr< T >::const_iterator VectorPtr< T >::end () const inline
References Vector< void * >::end().
template<class T > void VectorPtr< T >::erase (iterator i) inline
References Vector< void * >::erase().
template<class T > void VectorPtr< T >::erase_fast (U32 index) inline
References Vector< void * >::decrement(), Vector< void * >::mArray, and Vector< void * >::mElementCount.
Referenced by VectorPtr< T >::erase_fast().
template<class T > void VectorPtr< T >::erase_fast (iterator i) inline
References VectorPtr< T >::erase_fast(), and Vector< void * >::mArray.
template<class T > T & VectorPtr< T >::first () inline
References Vector< void * >::first(), and T.
Referenced by SimSet::first().
template<class T > const T & VectorPtr< T >::first () const inline
References Vector< void * >::first(), and T.
template<class T > T & VectorPtr< T >::front () inline
References VectorPtr< T >::begin().
Referenced by SimSet::front().
template<class T > const T & VectorPtr< T >::front () const inline
References VectorPtr< T >::begin().
template<class T> void VectorPtr< T >::insert (iterator i, const T & x) inline
References Vector< void * >::insert().
template<class T> void VectorPtr< T >::insert (S32 idx) inline
template<class T > T & VectorPtr< T >::last () inline
References Vector< void * >::last(), and T.
Referenced by SimSet::last().
template<class T > const T & VectorPtr< T >::last () const inline
References Vector< void * >::last(), and T.
template<class T > T & VectorPtr< T >::operator[] (U32 index) inline
References Vector< void * >::operator[](), and T.
template<class T > const T & VectorPtr< T >::operator[] (U32 index) const inline
References Vector< void * >::operator[](), and T.
template<class T> void VectorPtr< T >::push_back (const T & x) inline
References Vector< void * >::push_back().
Referenced by VectorSet< T >::insert().
template<class T> void VectorPtr< T >::push_front (const T & x) inline
References Vector< void * >::push_front().
Copyright © GarageGames, LLC. All Rights Reserved.