PlaneSet< T > Class Template Reference
Main Modules Class List Namespace List Online
PlaneSet< T > Class Template Reference
Set of planes which can be tested against bounding volumes.
#include <math/mPlaneSet.h>
Public Member Functions
Constructors
PlaneSet ()
Create an uninitialized set.
PlaneSet (const T *planes, U32 numPlanes)
Use the given set of planes to initialize the set.
Accessors
U32 getNumPlanes () const
Return the number of planes that this set consists of.
const T * getPlanes () const
Return the array of planes for this set.
Intersection
All of these intersection methods are approximate in that they can produce false positives on GeometryIntersecting.
For precise results, use Intersector.
OverlapTestResult testPotentialIntersection (const Box3F &aabb) const
Test intersection of the given AABB with the volume defined by the plane set.
OverlapTestResult testPotentialIntersection (const SphereF &sphere) const
Test intersection of the given sphere with the volume defined by the plane set.
OverlapTestResult testPotentialIntersection (const OrientedBox3F &obb) const
Test intersection of the given OBB with the volume defined by the plane set.
U32 testPlanes (const Box3F &bounds, U32 planeMask=0xFFFFFFFF, F32 expand=0.0f) const
Returns a bitmask of which planes are hit by the given box.
Containment
Testing for containment of geometric shapes within the volume enclosed by the planes.
bool isContained (const Point3F &point, F32 epsilon=__EQUAL_CONST_F) const
Return true if the given point lies on the positive side of all the planes in the set.
bool isContained (const Point3F *points, U32 numPoints) const
Return true if all of the given points lie on the positive side of all the planes in the set.
bool isContained (const Box3F &aabb) const
Return true if the given AABB lies on the positive side of all the planes in the set.
bool isContained (const SphereF &sphere) const
Return true if the given sphere lies on the positive side of all the planes in the set.
bool isContained (const OrientedBox3F &obb) const
Return true if the given OBB lies on the positive side of all the planes in the set.
Clipping
bool clipSegment (Point3F &pnt0, Point3F &pnt1) const
Clip the given line segment against the plane set.
U32 clipPolygon (const Point3F *inVertices, U32 inNumVertices, Point3F *outVertices, U32 maxOutVertices) const
Clip a convex polygon by all planes in the set.
Protected Member Functions
template<typename P >
bool _isContained (const P &bounds) const
template<typename P >
OverlapTestResult _testOverlap (const P &bounds) const
Protected Attributes
U32 mNumPlanes
Number of planes in mPlanes.
const T * mPlanes
Set of planes.
Detailed Description
template<typename T>
class PlaneSet< T >
Set of planes which can be tested against bounding volumes.
This class is meant as a helper to collect functionality for working with sets of planes. As a helper, it does not define means to manage the data it uses.
This class does not manage the memory needed for the set.
Constructor & Destructor Documentation
template<typename T> PlaneSet< T >::PlaneSet () inline
Create an uninitialized set.
None of the members will be initialized.
template<typename T> PlaneSet< T >::PlaneSet (const T * planes, U32 numPlanes) inline
Use the given set of planes to initialize the set.
Parameters
planes The planes. Memory must be valid for the entire lifetime of the plane set.
numPlanes Number of planes.
Member Function Documentation
template<typename T > template<typename P > bool PlaneSet< T >::_isContained (const P & bounds) const inline protected
References PlaneF::Front, PlaneSet< T >::mNumPlanes, and PlaneSet< T >::mPlanes.
Referenced by PlaneSet< PlaneF >::isContained().
template<typename T > template<typename P > OverlapTestResult PlaneSet< T >::_testOverlap (const P & bounds) const inline protected
References PlaneF::Back, PlaneF::Front, PlaneSet< T >::getNumPlanes(), PlaneSet< T >::getPlanes(), and PlaneF::whichSide().
Referenced by PlaneSet< PlaneF >::testPotentialIntersection().
template<typename T > U32 PlaneSet< T >::clipPolygon (const Point3F * inVertices, U32 inNumVertices, Point3F * outVertices, U32 maxOutVertices) const
Clip a convex polygon by all planes in the set.
Parameters
inVertices Array holding the vertices of the input polygon.
inNumVertices Number of vertices in inVertices.
outVertices Array to hold the vertices of the clipped polygon. Must have spaces for inNumVertices + numberOfPlanesInSet. Must not be the same as inVertices.
maxOutVertices Maximum number of vertices that can be stored in outVertices. If insufficient to store the clipped polygon, the return value will be 0.
Returns
Number of vertices in the clipped polygon, i.e. number of vertices stored in outVertices.
Note
Be aware that if the polygon fully lies on the negative side of all planes, the resulting outNumVertices will be zero, i.e. no polygon will result from the clip.
References PlaneF::clipPolygon(), dMemcpy(), PlaneSet< T >::mNumPlanes, and PlaneSet< T >::mPlanes.
Referenced by PolyhedronImpl< FrustumData >::clipPolygon(), and PlaneSet< PlaneF >::isContained().
template<typename T > bool PlaneSet< T >::clipSegment (Point3F & pnt0, Point3F & pnt1) const
Clip the given line segment against the plane set.
If the segment intersects with any of the planes, the points will be clipped at the intersection.
Returns
True if any part of the segment is inside the volume defined by the plane set.
References Point3F::interpolate(), PlaneF::intersect(), PlaneSet< T >::isContained(), PlaneSet< T >::mNumPlanes, and PlaneSet< T >::mPlanes.
Referenced by PolyhedronImpl< FrustumData >::clipSegment(), and PlaneSet< PlaneF >::isContained().
template<typename T> U32 PlaneSet< T >::getNumPlanes () const inline
Return the number of planes that this set consists of.
Referenced by PlaneSet< T >::_testOverlap(), and SceneCullingState::isOccludedWithExtraPlanesCull().
template<typename T> const T* PlaneSet< T >::getPlanes () const inline
Return the array of planes for this set.
Referenced by PlaneSet< T >::_testOverlap().
template<typename T > bool PlaneSet< T >::isContained (const Point3F & point, F32 epsilon = __EQUAL_CONST_F) const inline
Return true if the given point lies on the positive side of all the planes in the set.
References PlaneSet< T >::mNumPlanes, and PlaneSet< T >::mPlanes.
Referenced by SceneCullingVolume::_testBounds(), PlaneSet< T >::clipSegment(), PlaneSet< T >::isContained(), PolyhedronImpl< FrustumData >::isContained(), and PlaneSet< PlaneF >::testPotentialIntersection().
template<typename T > bool PlaneSet< T >::isContained (const Point3F * points, U32 numPoints) const inline
Return true if all of the given points lie on the positive side of all the planes in the set.
References PlaneSet< T >::isContained().
template<typename T> bool PlaneSet< T >::isContained (const Box3F & aabb) const inline
Return true if the given AABB lies on the positive side of all the planes in the set.
template<typename T> bool PlaneSet< T >::isContained (const SphereF & sphere) const inline
Return true if the given sphere lies on the positive side of all the planes in the set.
template<typename T> bool PlaneSet< T >::isContained (const OrientedBox3F & obb) const inline
Return true if the given OBB lies on the positive side of all the planes in the set.
template<typename T > U32 PlaneSet< T >::testPlanes (const Box3F & bounds, U32 planeMask = 0xFFFFFFFF, F32 expand = 0.0f) const
Returns a bitmask of which planes are hit by the given box.
References PlaneF::d, Box3F::maxExtents, Box3F::minExtents, PlaneSet< T >::mNumPlanes, PlaneSet< T >::mPlanes, Point3F::x, Point3F::y, and Point3F::z.
Referenced by PolyhedronImpl< FrustumData >::testPlanes(), and PlaneSet< PlaneF >::testPotentialIntersection().
template<typename T> OverlapTestResult PlaneSet< T >::testPotentialIntersection (const Box3F & aabb) const inline
Test intersection of the given AABB with the volume defined by the plane set.
Parameters
aabb Axis-aligned bounding box.
Returns
The type of overlap that the given AABB has with the plane set.
Note
The method will not test for those edge cases where none of the planes rejects the given AABB yet the AABB is actually outside the volume defined by the planes. This speeds up the test at the cost of losing precision which is acceptable for cases where doing the additional tests for all intersecting objects will generally waste more time than accepting a few additional non-intersecting objects as intersecting.
Referenced by SceneCullingState::isOccludedWithExtraPlanesCull(), and PolyhedronImpl< FrustumData >::testPotentialIntersection().
template<typename T> OverlapTestResult PlaneSet< T >::testPotentialIntersection (const SphereF & sphere) const inline
Test intersection of the given sphere with the volume defined by the plane set.
Parameters
sphere Sphere.
Returns
The type of overlap that the given sphere has with the plane set.
Note
The method will not test for those edge cases where none of the planes rejects the given sphere yet the sphere is actually outside the volume defined by the planes. This speeds up the test at the cost of losing precision which is acceptable for cases where doing the additional tests for all intersecting objects will generally waste more time than accepting a few additional non-intersecting objects as intersecting.
template<typename T> OverlapTestResult PlaneSet< T >::testPotentialIntersection (const OrientedBox3F & obb) const inline
Test intersection of the given OBB with the volume defined by the plane set.
Parameters
obb Oriented bounding box.
Returns
The type of overlap that the given OBB has with the plane set.
Note
The method will not test for those edge cases where none of the planes rejects the given OBB yet the OBB is actually outside the volume defined by the planes. This speeds up the test at the cost of losing precision which is acceptable for cases where doing the additional tests for all intersecting objects will generally waste more time than accepting a few additional non-intersecting objects as intersecting.
Member Data Documentation
template<typename T> U32 PlaneSet< T >::mNumPlanes protected
Number of planes in mPlanes.
Referenced by PlaneSet< T >::_isContained(), PlaneSet< T >::clipPolygon(), PlaneSet< T >::clipSegment(), PlaneSet< PlaneF >::getNumPlanes(), PlaneSet< T >::isContained(), and PlaneSet< T >::testPlanes().
template<typename T> const T* PlaneSet< T >::mPlanes protected
Set of planes.
The memory for this array is managed outside this class.
Referenced by PlaneSet< T >::_isContained(), PlaneSet< T >::clipPolygon(), PlaneSet< T >::clipSegment(), PlaneSet< PlaneF >::getPlanes(), PlaneSet< T >::isContained(), and PlaneSet< T >::testPlanes().
Copyright © GarageGames, LLC. All Rights Reserved.