Torque::FS::VirtualMountSystem Class Reference
Main Modules Class List Namespace List Online
Torque::FS::VirtualMountSystem Class Reference
The VirtualMountSystem extend the mount system by allowing you to mount and access multiple filesystems on a single root.
#include <core/virtualMountSystem.h>
Public Member Functions
VirtualMountSystem ()
virtual ~VirtualMountSystem ()
virtual bool createPath (const Path &path)
virtual S32 findByPattern (const Path &inBasePath, const String &inFilePattern, bool inRecursive, Vector< String > &outList, bool includeDirs=false, bool multiMatch=true)
virtual bool mount (String root, FileSystemRef fs)
virtual bool mount (String root, const Path &path)
virtual FileSystemRef unmount (String root)
virtual bool unmount (FileSystemRef fs)
Public Member Functions inherited from Torque::FS::MountSystem
virtual ~MountSystem ()
DirectoryRef createDirectory (const Path &path, FileSystemRef fs=NULL)
FileRef createFile (const Path &path)
const Path & getCwd () const
bool getFileAttributes (const Path &path, FileNode::Attributes *attr)
FileNodeRef getFileNode (const Path &path)
FileSystemRef getFileSystem (const Path &path)
String getMountPath (S32 index) const
String getMountRoot (S32 index) const
String getMountType (S32 index) const
S32 getNumMounts () const
bool isDirectory (const Path &path, FileSystemRef fsRef=NULL)
bool isFile (const Path &path)
bool isReadOnly (const Path &path)
bool mapFSPath (const String &inRoot, const Path &inPath, Path &outPath)
DirectoryRef openDirectory (const Path &path)
FileRef openFile (const Path &path, File::AccessMode mode)
bool remove (const Path &path)
bool rename (const Path &from, const Path &to)
bool setCwd (const Path &file)
void startFileChangeNotifications ()
void stopFileChangeNotifications ()
Protected Types
typedef Map< String, Vector< FileSystemRef > > PathFSMap
typedef Vector< FileSystemRef > RootToFSVec
Protected Member Functions
virtual FileSystemRef _getFileSystemFromList (const Path &path) const
virtual void _log (const String &msg)
virtual FileSystemRef _removeMountFromList (String root)
Protected Member Functions inherited from Torque::FS::MountSystem
Path _normalize (const Path &path)
void _setFindByPatternOverrideFS (FileSystemRef fs)
Protected Attributes
PathFSMap mRootMap
bool mUseParentFind
Protected Attributes inherited from Torque::FS::MountSystem
Path mCWD
FileSystemRef mFindByPatternOverrideFS
Vector< MountFS > mMountList
Detailed Description
The VirtualMountSystem extend the mount system by allowing you to mount and access multiple filesystems on a single root.
This allows you to mount multiple volume files on a single root without needing to change source paths that reference those volumes to use new roots. For instance, you could mount "missions1.zip" and "missions2.zip", on the same root "", and you could access files from either one.
If you need to mount a writeable filesystem on a VMS, you should mount it as the first filesystem on a root. File writes are handled as follows: 1) If you try to open a file for write, and it exists on one of the virtual mounts, that is the mount that will be used for writing. But if the filesystem is read-only then the writes will fail (and you will get appropriate error codes from your FileStream or whatever). 2) If you try to open a file for write that doesn't exist, the VMS falls back to the default MountSystem behavior, which is to use the first filesystem mounted on the root. If this filesystem happens to be writable, then you will be able to write to the file. 3) Nothing special is done for the WriteAppend case; that is, it follows the same logic as if you were just trying to Write the file.
Because of rule 1) above, you should take care that any files you need to write (such as prefs.cs), are not included in read-only zip archive files.
Member Typedef Documentation
typedef Map<String, Vector<FileSystemRef> > Torque::FS::VirtualMountSystem::PathFSMap protected
typedef Vector<FileSystemRef> Torque::FS::VirtualMountSystem::RootToFSVec protected
Constructor & Destructor Documentation
Torque::FS::VirtualMountSystem::VirtualMountSystem () inline
virtual Torque::FS::VirtualMountSystem::~VirtualMountSystem () inline virtual
References _getFileSystemFromList(), _log(), _removeMountFromList(), createPath(), findByPattern(), mount(), and unmount().
Member Function Documentation
virtual FileSystemRef Torque::FS::VirtualMountSystem::_getFileSystemFromList (const Path & path) const protected virtual
Reimplemented from Torque::FS::MountSystem.
Referenced by ~VirtualMountSystem().
virtual void Torque::FS::VirtualMountSystem::_log (const String & msg) protected virtual
Reimplemented from Torque::FS::MountSystem.
Referenced by ~VirtualMountSystem().
virtual FileSystemRef Torque::FS::VirtualMountSystem::_removeMountFromList (String root) protected virtual
Reimplemented from Torque::FS::MountSystem.
Referenced by ~VirtualMountSystem().
virtual bool Torque::FS::VirtualMountSystem::createPath (const Path & path) virtual
Reimplemented from Torque::FS::MountSystem.
Referenced by ~VirtualMountSystem().
virtual S32 Torque::FS::VirtualMountSystem::findByPattern (const Path & inBasePath, const String & inFilePattern, bool inRecursive, Vector< String > & outList, bool includeDirs = false, bool multiMatch = true) virtual
Reimplemented from Torque::FS::MountSystem.
Referenced by ~VirtualMountSystem().
virtual bool Torque::FS::VirtualMountSystem::mount (String root, FileSystemRef fs) virtual
Reimplemented from Torque::FS::MountSystem.
Referenced by ~VirtualMountSystem().
virtual bool Torque::FS::VirtualMountSystem::mount (String root, const Path & path) virtual
Reimplemented from Torque::FS::MountSystem.
virtual FileSystemRef Torque::FS::VirtualMountSystem::unmount (String root) virtual
Reimplemented from Torque::FS::MountSystem.
Referenced by ~VirtualMountSystem().
virtual bool Torque::FS::VirtualMountSystem::unmount (FileSystemRef fs) virtual
Reimplemented from Torque::FS::MountSystem.
Member Data Documentation
PathFSMap Torque::FS::VirtualMountSystem::mRootMap protected
bool Torque::FS::VirtualMountSystem::mUseParentFind protected
Copyright © GarageGames, LLC. All Rights Reserved.