ConvexEditorCreateTool Class Reference
Main Modules Class List Namespace List Online
ConvexEditorCreateTool Class Reference
#include <gui/worldEditor/guiConvexShapeEditorCtrl.h>
Public Member Functions
ConvexEditorCreateTool (GuiConvexEditorCtrl *editor)
virtual ~ConvexEditorCreateTool ()
ConvexShape * extrudeShapeFromFace (ConvexShape *shape, S32 face)
virtual EventResult on3DMouseDown (const Gui3DMouseEvent &event)
virtual EventResult on3DMouseDragged (const Gui3DMouseEvent &event)
virtual EventResult on3DMouseMove (const Gui3DMouseEvent &event)
virtual EventResult on3DMouseUp (const Gui3DMouseEvent &event)
virtual void onActivated (ConvexEditorTool *prevTool)
virtual void onDeactivated (ConvexEditorTool *newTool)
virtual void renderScene (const RectI &updateRect)
Public Member Functions inherited from ConvexEditorTool
ConvexEditorTool (GuiConvexEditorCtrl *editor)
virtual ~ConvexEditorTool ()
bool isDone ()
virtual EventResult on3DMouseEnter (const Gui3DMouseEvent &event)
virtual EventResult on3DMouseLeave (const Gui3DMouseEvent &event)
virtual EventResult on3DRightMouseDown (const Gui3DMouseEvent &event)
virtual EventResult on3DRightMouseUp (const Gui3DMouseEvent &event)
virtual EventResult onKeyDown (const GuiEvent &event)
virtual void render2D ()
Protected Attributes
PlaneF mCreatePlane
Point3F mEnd
ConvexShape * mNewConvex
Point3F mPlaneSizes
S32 mStage
Point3F mStart
MatrixF mTransform
Protected Attributes inherited from ConvexEditorTool
bool mDone
Additional Inherited Members
Public Types inherited from ConvexEditorTool
enum EventResult {
NotHandled = 0,
Handled = 1,
Done = 2,
Failed = 3
}
Public Attributes inherited from ConvexEditorTool
GuiConvexEditorCtrl * mEditor
Constructor & Destructor Documentation
ConvexEditorCreateTool::ConvexEditorCreateTool (GuiConvexEditorCtrl * editor)
virtual ConvexEditorCreateTool::~ConvexEditorCreateTool () inline virtual
References GuiConvexEditorCtrl::on3DMouseDown(), GuiConvexEditorCtrl::on3DMouseDragged(), GuiConvexEditorCtrl::on3DMouseMove(), GuiConvexEditorCtrl::on3DMouseUp(), and GuiConvexEditorCtrl::renderScene().
Member Function Documentation
ConvexShape* ConvexEditorCreateTool::extrudeShapeFromFace (ConvexShape * shape, S32 face)
virtual EventResult ConvexEditorCreateTool::on3DMouseDown (const Gui3DMouseEvent & event) virtual
Reimplemented from ConvexEditorTool.
virtual EventResult ConvexEditorCreateTool::on3DMouseDragged (const Gui3DMouseEvent & event) virtual
Reimplemented from ConvexEditorTool.
virtual EventResult ConvexEditorCreateTool::on3DMouseMove (const Gui3DMouseEvent & event) virtual
Reimplemented from ConvexEditorTool.
virtual EventResult ConvexEditorCreateTool::on3DMouseUp (const Gui3DMouseEvent & event) virtual
Reimplemented from ConvexEditorTool.
virtual void ConvexEditorCreateTool::onActivated (ConvexEditorTool * prevTool) virtual
Reimplemented from ConvexEditorTool.
virtual void ConvexEditorCreateTool::onDeactivated (ConvexEditorTool * newTool) virtual
Reimplemented from ConvexEditorTool.
virtual void ConvexEditorCreateTool::renderScene (const RectI & updateRect) virtual
Reimplemented from ConvexEditorTool.
Member Data Documentation
PlaneF ConvexEditorCreateTool::mCreatePlane protected
Point3F ConvexEditorCreateTool::mEnd protected
ConvexShape* ConvexEditorCreateTool::mNewConvex protected
Point3F ConvexEditorCreateTool::mPlaneSizes protected
S32 ConvexEditorCreateTool::mStage protected
Point3F ConvexEditorCreateTool::mStart protected
MatrixF ConvexEditorCreateTool::mTransform protected
Copyright © GarageGames, LLC. All Rights Reserved.