ShaderFeature Class Reference
Main Modules Class List Namespace List Online
ShaderFeature Class Reference abstract
#include <shaderGen/shaderFeature.h>
Classes
struct Resources
Public Types
enum OutputTarget {
DefaultTarget = 1 << 0,
RenderTarget1 = 1 << 1,
RenderTarget2 = 1 << 2,
RenderTarget3 = 1 << 3
}
Public Member Functions
ShaderFeature ()
virtual ~ShaderFeature ()
virtual void addDependency (const ShaderDependency *depends)
Adds a dependency to this shader feature.
virtual LangElement * assignColor (LangElement *elem, Material::BlendOp blend, LangElement *lerpElem=NULL, ShaderFeature::OutputTarget outputTarget=ShaderFeature::DefaultTarget)=0
Helper function for applying the color to shader output.
virtual ShaderFeatureConstHandles * createConstHandles (GFXShader *shader, SimObject *userObject)
virtual void determineFeature (Material *material, const GFXVertexFormat *vertexFormat, U32 stageNum, const FeatureType &type, const FeatureSet &features, MaterialFeatureData *outFeatureData)
virtual LangElement * expandNormalMap (LangElement *sampleNormalOp, LangElement *normalDecl, LangElement *normalVar, const MaterialFeatureData &fd)=0
Expand and assign a normal map. This takes care of compressed normal maps as well.
virtual Material::BlendOp getBlendOp ()
Identifies what type of blending a feature uses.
virtual const Vector< const ShaderDependency * > & getDependencies () const
Gets the dependency list for this shader feature.
virtual String getName ()=0
Returns the name of this feature.
LangElement * getOutput () const
returns output from a processed vertex or pixel shader
virtual U32 getOutputTargets (const MaterialFeatureData &fd) const
Gets the render target this shader feature is assigning data to.
const char * getOutputTargetVarName (OutputTarget target=DefaultTarget) const
Returns the name of output targer var.
virtual const char * getOutputVarName () const
Returns the output variable name for this feature if it applies.
S32 getProcessIndex () const
virtual Resources getResources (const MaterialFeatureData &fd)
Returns the resource requirements of this feature based on what other features are present.
virtual Var * getVertTexCoord (const String &name)=0
Get the incoming base texture coords - useful for bumpmap and detail maps.
virtual void processPix (Vector< ShaderComponent * > &componentList, const MaterialFeatureData &fd)
virtual void processPixMacros (Vector< GFXShaderMacro > &macros, const MaterialFeatureData &fd)
Allows the feature to add macros to pixel shader compiles.
virtual void processVert (Vector< ShaderComponent * > &componentList, const MaterialFeatureData &fd)
virtual void processVertMacros (Vector< GFXShaderMacro > &macros, const MaterialFeatureData &fd)
Allows the feature to add macros to vertex shader compiles.
virtual void reset ()
Called after processing the vertex and processing the pixel to cleanup any temporary structures stored in the feature.
void setInstancingFormat (GFXVertexFormat *format)
void setProcessIndex (S32 index)
virtual void setTexData (Material::StageData &stageDat, const MaterialFeatureData &fd, RenderPassData &passData, U32 &texIndex)
Fills texture related info in RenderPassData for this feature.
virtual LangElement * setupTexSpaceMat (Vector< ShaderComponent * > &componentList, Var **texSpaceMat)=0
Set up a texture space matrix - to pass into pixel shader.
Static Public Member Functions
static Var * findOrCreateLocal (const char *name, const char *type, MultiLine *multi)
A simpler helper function which either finds the existing local var or creates one.
Public Attributes
GFXVertexFormat * mInstancingFormat
const GFXVertexFormat * mVertexFormat
Protected Attributes
Vector< const ShaderDependency * > mDependencies
The list of unique shader dependencies.
S32 mProcessIndex
LangElement * output
Detailed Description
The ShaderFeature class is the base class for every procedurally generated feature. Each feature the engine recognizes is part of the MaterialFeatureType enum. That structure is used to indicate which features are present in a shader to be generated. This is useful as many ShaderFeatures will output different code depending on what other features are going to be in the shader.
Shaders are generated using the ShaderFeature interface, so all of the descendants interact pretty much the same way.
Member Enumeration Documentation
enum ShaderFeature::OutputTarget
Enumerator
DefaultTarget
RenderTarget1
RenderTarget2
RenderTarget3
Constructor & Destructor Documentation
ShaderFeature::ShaderFeature () inline
virtual ShaderFeature::~ShaderFeature () inline virtual
Member Function Documentation
virtual void ShaderFeature::addDependency (const ShaderDependency * depends) virtual
Adds a dependency to this shader feature.
virtual LangElement* ShaderFeature::assignColor (LangElement * elem, Material::BlendOp blend, LangElement * lerpElem = NULL, ShaderFeature::OutputTarget outputTarget = ShaderFeature::DefaultTarget) pure virtual
Helper function for applying the color to shader output.
Parameters
elem The rbg or rgba color to assign.
blend The type of blending to perform.
lerpElem The optional lerp parameter when doing a LerpAlpha blend, if not set then the elem is used.
Implemented in ShaderFeatureHLSL, ShaderFeatureGLSL, and ConditionerFeature.
virtual ShaderFeatureConstHandles* ShaderFeature::createConstHandles (GFXShader * shader, SimObject * userObject) inline virtual
Reimplemented in FoliageFeatureHLSL, FoliageFeatureGLSL, WindDeformationGLSL, and WindDeformationHLSL.
Referenced by FoliageFeatureGLSL::getName(), and FoliageFeatureHLSL::getName().
virtual void ShaderFeature::determineFeature (Material * material, const GFXVertexFormat * vertexFormat, U32 stageNum, const FeatureType & type, const FeatureSet & features, MaterialFeatureData * outFeatureData) inline virtual
Reimplemented in ImposterVertFeatureHLSL, ImposterVertFeatureGLSL, FoliageFeatureHLSL, FoliageFeatureGLSL, VertPositionHLSL, VertPositionGLSL, WindDeformationGLSL, and WindDeformationHLSL.
Referenced by VertPositionGLSL::getName(), VertPositionHLSL::getName(), FoliageFeatureGLSL::getName(), FoliageFeatureHLSL::getName(), ImposterVertFeatureGLSL::getName(), and ImposterVertFeatureHLSL::getName().
virtual LangElement* ShaderFeature::expandNormalMap (LangElement * sampleNormalOp, LangElement * normalDecl, LangElement * normalVar, const MaterialFeatureData & fd) pure virtual
Expand and assign a normal map. This takes care of compressed normal maps as well.
Implemented in ShaderFeatureHLSL, ShaderFeatureGLSL, and ConditionerFeature.
static Var* ShaderFeature::findOrCreateLocal (const char * name, const char * type, MultiLine * multi) static
A simpler helper function which either finds the existing local var or creates one.
virtual Material::BlendOp ShaderFeature::getBlendOp () inline virtual
Identifies what type of blending a feature uses.
This is used to group features with the same blend operation together in a multipass situation.
Reimplemented in HDROutHLSL, HDROutGLSL, GlowMaskHLSL, GlowMaskGLSL, AlphaTestHLSL, AlphaTestGLSL, VisibilityFeatHLSL, VisibilityFeatGLSL, TexAnimHLSL, TexAnimGLSL, FogFeatHLSL, FogFeatGLSL, DetailFeatHLSL, DetailFeatGLSL, VertLitHLSL, VertLitGLSL, TonemapFeatHLSL, TonemapFeatGLSL, LightmapFeatHLSL, LightmapFeatGLSL, DiffuseVertColorFeatureHLSL, DiffuseVertColorFeatureGLSL, DiffuseFeatureHLSL, DiffuseFeatureGLSL, OverlayTexFeatHLSL, OverlayTexFeatGLSL, DiffuseMapFeatHLSL, DiffuseMapFeatGLSL, RTLightingFeatHLSL, RTLightingFeatGLSL, NormalsOutFeatGLSL, NormalsOutFeatHLSL, DeferredBumpFeatGLSL, DeferredBumpFeatHLSL, AccuTexFeatGLSL, AccuTexFeatHLSL, DeferredRTLightingFeatGLSL, DeferredRTLightingFeatHLSL, DepthOutGLSL, DepthOutHLSL, ConditionerFeature, BumpFeatGLSL, BumpFeatHLSL, ParaboloidVertTransformGLSL, ParaboloidVertTransformHLSL, EyeSpaceDepthOutGLSL, and EyeSpaceDepthOutHLSL.
References Material::Add.
virtual const Vector<const ShaderDependency *>& ShaderFeature::getDependencies (void) const inline virtual
Gets the dependency list for this shader feature.
virtual String ShaderFeature::getName () pure virtual
Returns the name of this feature.
Implemented in HardwareSkinningFeatureHLSL, HardwareSkinningFeatureGLSL, ImposterVertFeatureHLSL, ImposterVertFeatureGLSL, ParticleNormalFeatureHLSL, ParticleNormalFeatureGLSL, FoliageFeatureHLSL, FoliageFeatureGLSL, HDROutHLSL, HDROutGLSL, GlowMaskHLSL, GlowMaskGLSL, AlphaTestHLSL, AlphaTestGLSL, VisibilityFeatHLSL, VisibilityFeatGLSL, TexAnimHLSL, TexAnimGLSL, FogFeatHLSL, FogFeatGLSL, ReflectCubeFeatHLSL, ReflectCubeFeatGLSL, DetailFeatHLSL, DetailFeatGLSL, VertLitHLSL, VertLitGLSL, TonemapFeatHLSL, TonemapFeatGLSL, LightmapFeatHLSL, LightmapFeatGLSL, DiffuseVertColorFeatureHLSL, DiffuseVertColorFeatureGLSL, DiffuseFeatureHLSL, DiffuseFeatureGLSL, OverlayTexFeatHLSL, OverlayTexFeatGLSL, DiffuseMapFeatHLSL, DiffuseMapFeatGLSL, RTLightingFeatHLSL, RTLightingFeatGLSL, LinearEyeDepthConditioner, VertPositionHLSL, VertPositionGLSL, AccuSpecularFeature, AccuSpecularFeature, RenderTargetZeroHLSL, RenderTargetZeroGLSL, TerrainBlankInfoMapFeatHLSL, TerrainBlankInfoMapFeatGLSL, DeferredSubSurfaceGLSL, DeferredSubSurfaceHLSL, AccuCoverageFeature, AccuCoverageFeature, TerrainAdditiveFeatHLSL, NamedFeatureHLSL, TerrainAdditiveFeatGLSL, NamedFeatureGLSL, TerrainLightMapFeatHLSL, TerrainLightMapFeatGLSL, DeferredMinnaertGLSL, DeferredMinnaertHLSL, AccuStrengthFeature, AccuStrengthFeature, TerrainNormalMapFeatHLSL, TerrainNormalMapFeatGLSL, AccuDirectionFeature, AccuDirectionFeature, DeferredPixelSpecularGLSL, DeferredPixelSpecularHLSL, TerrainMacroMapFeatHLSL, TerrainMacroMapFeatGLSL, NormalsOutFeatGLSL, NormalsOutFeatHLSL, AccuScaleFeature, AccuScaleFeature, DeferredBumpFeatGLSL, DeferredBumpFeatHLSL, TerrainDetailMapFeatHLSL, TerrainDetailMapFeatGLSL, ParallaxFeatGLSL, ParallaxFeatHLSL, AccuTexFeatGLSL, AccuTexFeatHLSL, DeferredEmptySpecGLSL, DeferredEmptySpecHLSL, SpecularMapGLSL, SpecularMapHLSL, DeferredRTLightingFeatGLSL, DeferredRTLightingFeatHLSL, TerrainBaseMapFeatHLSL, GBufferConditionerGLSL, GBufferConditionerHLSL, TerrainBaseMapFeatGLSL, DeferredSpecVarsGLSL, DeferredSpecVarsHLSL, BumpFeatGLSL, BumpFeatHLSL, DepthOutGLSL, DepthOutHLSL, DeferredMatInfoFlagsGLSL, DeferredMatInfoFlagsHLSL, AdvancedLightBufferConditioner, PixelSpecularGLSL, PixelSpecularHLSL, WindDeformationGLSL, WindDeformationHLSL, ParaboloidVertTransformGLSL, ParaboloidVertTransformHLSL, EyeSpaceDepthOutGLSL, EyeSpaceDepthOutHLSL, DeferredSpecMapGLSL, and DeferredSpecMapHLSL.
LangElement* ShaderFeature::getOutput () const inline
returns output from a processed vertex or pixel shader
virtual U32 ShaderFeature::getOutputTargets (const MaterialFeatureData & fd) const inline virtual
Gets the render target this shader feature is assigning data to.
Reimplemented in VertLitHLSL, VertLitGLSL, TonemapFeatHLSL, TonemapFeatGLSL, LightmapFeatHLSL, LightmapFeatGLSL, DiffuseFeatureHLSL, DiffuseFeatureGLSL, DiffuseMapFeatHLSL, DiffuseMapFeatGLSL, RenderTargetZeroHLSL, RenderTargetZeroGLSL, TerrainBlankInfoMapFeatHLSL, TerrainBlankInfoMapFeatGLSL, TerrainMacroMapFeatHLSL, TerrainMacroMapFeatGLSL, TerrainDetailMapFeatHLSL, TerrainDetailMapFeatGLSL, DeferredEmptySpecGLSL, DeferredEmptySpecHLSL, TerrainBaseMapFeatHLSL, TerrainBaseMapFeatGLSL, DeferredSpecVarsGLSL, DeferredSpecVarsHLSL, DeferredMatInfoFlagsGLSL, and DeferredMatInfoFlagsHLSL.
Referenced by DiffuseFeatureGLSL::getBlendOp(), DiffuseFeatureHLSL::getBlendOp(), TerrainBaseMapFeatGLSL::getName(), TerrainBaseMapFeatHLSL::getName(), TerrainDetailMapFeatGLSL::getName(), TerrainDetailMapFeatHLSL::getName(), TerrainMacroMapFeatGLSL::getName(), TerrainMacroMapFeatHLSL::getName(), LightmapFeatGLSL::getName(), LightmapFeatHLSL::getName(), TonemapFeatGLSL::getName(), TonemapFeatHLSL::getName(), VertLitGLSL::getName(), and VertLitHLSL::getName().
const char* ShaderFeature::getOutputTargetVarName (OutputTarget target = DefaultTarget) const
Returns the name of output targer var.
virtual const char* ShaderFeature::getOutputVarName () const inline virtual
Returns the output variable name for this feature if it applies.
Reimplemented in DepthOutGLSL, DepthOutHLSL, EyeSpaceDepthOutGLSL, and EyeSpaceDepthOutHLSL.
S32 ShaderFeature::getProcessIndex () const inline
References DefaultTarget.
virtual Resources ShaderFeature::getResources (const MaterialFeatureData & fd) virtual
Returns the resource requirements of this feature based on what other features are present.
The "resources" are things such as texture units, and texture registers of which there can be very limited numbers. The resources can vary depending on hardware and what other features are present.
Reimplemented in VisibilityFeatHLSL, VisibilityFeatGLSL, FogFeatHLSL, FogFeatGLSL, ReflectCubeFeatHLSL, ReflectCubeFeatGLSL, DetailFeatHLSL, DetailFeatGLSL, TonemapFeatHLSL, TonemapFeatGLSL, LightmapFeatHLSL, LightmapFeatGLSL, OverlayTexFeatHLSL, OverlayTexFeatGLSL, DiffuseMapFeatHLSL, DiffuseMapFeatGLSL, RTLightingFeatHLSL, RTLightingFeatGLSL, TerrainLightMapFeatHLSL, TerrainLightMapFeatGLSL, DeferredMinnaertGLSL, DeferredMinnaertHLSL, TerrainNormalMapFeatHLSL, TerrainNormalMapFeatGLSL, DeferredPixelSpecularGLSL, DeferredPixelSpecularHLSL, TerrainMacroMapFeatHLSL, TerrainMacroMapFeatGLSL, TerrainDetailMapFeatHLSL, TerrainDetailMapFeatGLSL, DeferredBumpFeatGLSL, DeferredBumpFeatHLSL, ParallaxFeatGLSL, ParallaxFeatHLSL, GBufferConditionerGLSL, GBufferConditionerHLSL, TerrainBaseMapFeatHLSL, SpecularMapGLSL, SpecularMapHLSL, TerrainBaseMapFeatGLSL, AccuTexFeatGLSL, AccuTexFeatHLSL, DeferredRTLightingFeatGLSL, DeferredRTLightingFeatHLSL, DepthOutGLSL, DepthOutHLSL, BumpFeatGLSL, BumpFeatHLSL, PixelSpecularGLSL, PixelSpecularHLSL, ParaboloidVertTransformGLSL, ParaboloidVertTransformHLSL, EyeSpaceDepthOutGLSL, EyeSpaceDepthOutHLSL, DeferredSpecMapGLSL, and DeferredSpecMapHLSL.
Referenced by RTLightingFeatGLSL::getBlendOp(), RTLightingFeatHLSL::getBlendOp(), DiffuseMapFeatGLSL::getBlendOp(), DiffuseMapFeatHLSL::getBlendOp(), OverlayTexFeatGLSL::getBlendOp(), OverlayTexFeatHLSL::getBlendOp(), LightmapFeatGLSL::getBlendOp(), LightmapFeatHLSL::getBlendOp(), TonemapFeatGLSL::getBlendOp(), and TonemapFeatHLSL::getBlendOp().
virtual Var* ShaderFeature::getVertTexCoord (const String & name) pure virtual
Get the incoming base texture coords - useful for bumpmap and detail maps.
Implemented in ShaderFeatureHLSL, ShaderFeatureGLSL, and ConditionerFeature.
virtual void ShaderFeature::processPix (Vector< ShaderComponent * > & componentList, const MaterialFeatureData & fd) inline virtual
Process pixel shader - This function is used by each feature to generate a list of LangElements that can be traversed and "printed" to generate the actual shader code. The 'output' member is the head of that list.
The componentList is used mostly for access to the "Connector" structure which is used to pass data from the vertex to the pixel shader.
The MaterialFeatureData parameter is used to determine what other features are present for the shader being generated.
Reimplemented in ImposterVertFeatureHLSL, ImposterVertFeatureGLSL, FoliageFeatureHLSL, FoliageFeatureGLSL, HDROutHLSL, HDROutGLSL, GlowMaskHLSL, GlowMaskGLSL, AlphaTestHLSL, AlphaTestGLSL, VisibilityFeatHLSL, VisibilityFeatGLSL, FogFeatHLSL, FogFeatGLSL, ReflectCubeFeatHLSL, ReflectCubeFeatGLSL, DetailFeatHLSL, DetailFeatGLSL, VertLitHLSL, VertLitGLSL, TonemapFeatHLSL, TonemapFeatGLSL, LightmapFeatHLSL, LightmapFeatGLSL, DiffuseVertColorFeatureHLSL, DiffuseVertColorFeatureGLSL, DiffuseFeatureHLSL, DiffuseFeatureGLSL, OverlayTexFeatHLSL, OverlayTexFeatGLSL, DiffuseMapFeatHLSL, DiffuseMapFeatGLSL, RTLightingFeatHLSL, RTLightingFeatGLSL, LinearEyeDepthConditioner, VertPositionHLSL, RenderTargetZeroHLSL, RenderTargetZeroGLSL, AccuSpecularFeature, AccuSpecularFeature, TerrainBlankInfoMapFeatHLSL, TerrainBlankInfoMapFeatGLSL, DeferredSubSurfaceGLSL, DeferredSubSurfaceHLSL, TerrainAdditiveFeatHLSL, TerrainAdditiveFeatGLSL, AccuCoverageFeature, AccuCoverageFeature, TerrainLightMapFeatHLSL, TerrainLightMapFeatGLSL, DeferredMinnaertGLSL, DeferredMinnaertHLSL, TerrainNormalMapFeatHLSL, TerrainNormalMapFeatGLSL, AccuStrengthFeature, AccuStrengthFeature, DeferredPixelSpecularGLSL, DeferredPixelSpecularHLSL, TerrainMacroMapFeatHLSL, TerrainMacroMapFeatGLSL, AccuDirectionFeature, AccuDirectionFeature, NormalsOutFeatGLSL, NormalsOutFeatHLSL, TerrainDetailMapFeatHLSL, TerrainDetailMapFeatGLSL, AccuScaleFeature, AccuScaleFeature, DeferredBumpFeatGLSL, DeferredBumpFeatHLSL, ParallaxFeatGLSL, ParallaxFeatHLSL, DeferredEmptySpecGLSL, DeferredEmptySpecHLSL, DeferredSpecVarsGLSL, GBufferConditionerGLSL, DeferredSpecVarsHLSL, GBufferConditionerHLSL, TerrainBaseMapFeatHLSL, SpecularMapGLSL, SpecularMapHLSL, TerrainBaseMapFeatGLSL, DeferredMatInfoFlagsGLSL, DeferredMatInfoFlagsHLSL, AccuTexFeatGLSL, AccuTexFeatHLSL, DeferredRTLightingFeatGLSL, DeferredRTLightingFeatHLSL, DepthOutGLSL, DepthOutHLSL, BumpFeatGLSL, BumpFeatHLSL, PixelSpecularGLSL, PixelSpecularHLSL, ParaboloidVertTransformGLSL, ParaboloidVertTransformHLSL, EyeSpaceDepthOutGLSL, EyeSpaceDepthOutHLSL, DeferredSpecMapGLSL, and DeferredSpecMapHLSL.
Referenced by RenderTargetZeroGLSL::getName(), and RenderTargetZeroHLSL::getName().
virtual void ShaderFeature::processPixMacros (Vector< GFXShaderMacro > & macros, const MaterialFeatureData & fd) inline virtual
Allows the feature to add macros to pixel shader compiles.
Reimplemented in DeferredMinnaertGLSL, DeferredMinnaertHLSL, DeferredRTLightingFeatGLSL, and DeferredRTLightingFeatHLSL.
virtual void ShaderFeature::processVert (Vector< ShaderComponent * > & componentList, const MaterialFeatureData & fd) inline virtual
Process vertex shader - This function is used by each feature to generate a list of LangElements that can be traversed and "printed" to generate the actual shader code. The 'output' member is the head of that list.
The componentList is used mostly for access to the "Connector" structure which is used to pass data from the vertex to the pixel shader.
The MaterialFeatureData parameter is used to determine what other features are present for the shader being generated.
Reimplemented in HardwareSkinningFeatureHLSL, HardwareSkinningFeatureGLSL, ImposterVertFeatureHLSL, ImposterVertFeatureGLSL, ParticleNormalFeatureHLSL, ParticleNormalFeatureGLSL, FoliageFeatureHLSL, FoliageFeatureGLSL, VisibilityFeatHLSL, VisibilityFeatGLSL, FogFeatHLSL, FogFeatGLSL, ReflectCubeFeatHLSL, ReflectCubeFeatGLSL, DetailFeatHLSL, DetailFeatGLSL, VertLitHLSL, VertLitGLSL, TonemapFeatHLSL, TonemapFeatGLSL, LightmapFeatHLSL, LightmapFeatGLSL, DiffuseVertColorFeatureHLSL, DiffuseVertColorFeatureGLSL, OverlayTexFeatHLSL, OverlayTexFeatGLSL, DiffuseMapFeatHLSL, DiffuseMapFeatGLSL, RTLightingFeatHLSL, RTLightingFeatGLSL, VertPositionHLSL, VertPositionGLSL, DeferredMinnaertGLSL, DeferredMinnaertHLSL, TerrainNormalMapFeatHLSL, TerrainNormalMapFeatGLSL, DeferredPixelSpecularGLSL, DeferredPixelSpecularHLSL, TerrainMacroMapFeatHLSL, TerrainMacroMapFeatGLSL, NormalsOutFeatGLSL, NormalsOutFeatHLSL, TerrainDetailMapFeatHLSL, TerrainDetailMapFeatGLSL, DeferredBumpFeatGLSL, DeferredBumpFeatHLSL, ParallaxFeatGLSL, ParallaxFeatHLSL, GBufferConditionerGLSL, GBufferConditionerHLSL, TerrainBaseMapFeatHLSL, SpecularMapGLSL, SpecularMapHLSL, TerrainBaseMapFeatGLSL, AccuTexFeatGLSL, AccuTexFeatHLSL, DeferredRTLightingFeatGLSL, DeferredRTLightingFeatHLSL, DepthOutGLSL, DepthOutHLSL, DeferredSpecMapGLSL, DeferredSpecMapHLSL, WindDeformationGLSL, WindDeformationHLSL, BumpFeatGLSL, BumpFeatHLSL, PixelSpecularGLSL, PixelSpecularHLSL, ParaboloidVertTransformGLSL, ParaboloidVertTransformHLSL, EyeSpaceDepthOutGLSL, and EyeSpaceDepthOutHLSL.
virtual void ShaderFeature::processVertMacros (Vector< GFXShaderMacro > & macros, const MaterialFeatureData & fd) inline virtual
Allows the feature to add macros to vertex shader compiles.
virtual void ShaderFeature::reset (void) inline virtual
Called after processing the vertex and processing the pixel to cleanup any temporary structures stored in the feature.
void ShaderFeature::setInstancingFormat (GFXVertexFormat * format)
void ShaderFeature::setProcessIndex (S32 index) inline
virtual void ShaderFeature::setTexData (Material::StageData & stageDat, const MaterialFeatureData & fd, RenderPassData & passData, U32 & texIndex) inline virtual
Fills texture related info in RenderPassData for this feature.
It takes into account the current pass (passData) as well as what other data is available to the material stage (stageDat).
For instance, ReflectCubeFeatHLSL would like to modulate its output by the alpha channel of another texture. If the current pass does not contain a diffuse or bump texture, but the Material does, then this function allows it to use one of those textures in the current pass.
Reimplemented in ReflectCubeFeatHLSL, ReflectCubeFeatGLSL, DetailFeatHLSL, DetailFeatGLSL, TonemapFeatHLSL, TonemapFeatGLSL, LightmapFeatHLSL, LightmapFeatGLSL, OverlayTexFeatHLSL, OverlayTexFeatGLSL, DiffuseMapFeatHLSL, DiffuseMapFeatGLSL, DeferredMinnaertGLSL, DeferredMinnaertHLSL, DeferredBumpFeatGLSL, DeferredBumpFeatHLSL, ParallaxFeatGLSL, ParallaxFeatHLSL, AccuTexFeatGLSL, AccuTexFeatHLSL, SpecularMapGLSL, SpecularMapHLSL, DeferredRTLightingFeatGLSL, DeferredRTLightingFeatHLSL, BumpFeatGLSL, BumpFeatHLSL, DeferredSpecMapGLSL, and DeferredSpecMapHLSL.
Referenced by DiffuseMapFeatGLSL::getBlendOp(), DiffuseMapFeatHLSL::getBlendOp(), OverlayTexFeatGLSL::getBlendOp(), OverlayTexFeatHLSL::getBlendOp(), LightmapFeatGLSL::getBlendOp(), LightmapFeatHLSL::getBlendOp(), TonemapFeatGLSL::getBlendOp(), TonemapFeatHLSL::getBlendOp(), DetailFeatGLSL::getBlendOp(), and DetailFeatHLSL::getBlendOp().
virtual LangElement* ShaderFeature::setupTexSpaceMat (Vector< ShaderComponent * > & componentList, Var ** texSpaceMat) pure virtual
Set up a texture space matrix - to pass into pixel shader.
Implemented in ShaderFeatureHLSL, ShaderFeatureGLSL, and ConditionerFeature.
Member Data Documentation
Vector<const ShaderDependency *> ShaderFeature::mDependencies protected
The list of unique shader dependencies.
GFXVertexFormat* ShaderFeature::mInstancingFormat
S32 ShaderFeature::mProcessIndex protected
const GFXVertexFormat* ShaderFeature::mVertexFormat
LangElement* ShaderFeature::output protected
Copyright © GarageGames, LLC. All Rights Reserved.