AsyncIOItem< T, Stream > Class Template Reference
Main Modules Class List Namespace List Online
AsyncIOItem< T, Stream > Class Template Reference
Abstract superclass of async I/O work items.
#include <platform/threads/threadPoolAsyncIO.h>
Public Types
typedef RawDataT< ValueType > BufferType
typedef U32 OffsetType
typedef WorkItem Parent
typedef Stream StreamType
typedef T ValueType
Public Types inherited from ThreadPool::WorkItem
typedef ThreadSafeRefCount< WorkItem > Parent
Public Types inherited from ThreadSafeRefCount< WorkItem >
typedef void Parent
Public Member Functions
AsyncIOItem (StreamType *stream, U32 numElements, OffsetType offsetInStream, ThreadContext *context=0)
If the stream uses implicit positioning, then the supplied "offsetInStream" is meaningless and ignored.
AsyncIOItem (StreamType *stream, BufferType &buffer, U32 offsetInBuffer, U32 numElements, OffsetType offsetInStream, bool takeOwnershipOfBuffer=true, ThreadContext *context=0)
Construct a read item on "stream" that stores data into the given "buffer".
BufferType & getBuffer ()
Return the data buffer being written to/read from.
U32 getNumElements ()
Return the number of elements involved in the transfer.
U32 getOffsetInBuffer ()
Return the position in the data buffer at which to start the transfer.
OffsetType getOffsetInStream ()
Return the position in the stream at which to start the transfer.
StreamType * getStream ()
Return the stream being written to/read from.
Public Member Functions inherited from ThreadPool::WorkItem
WorkItem (Context *context=0)
Construct a new work item.
virtual ~WorkItem ()
Context * getContext () const
Return the work context associated with the work item.
virtual F32 getPriority ()
Return the item's base priority value.
bool hasExecuted () const
Has this work item been executed already?
virtual bool isCancellationRequested ()
Return true if the work item should be cancelled.
void process ()
Process the work item.
Public Member Functions inherited from ThreadSafeRefCount< WorkItem >
ThreadSafeRefCount ()
ThreadSafeRefCount (bool noSet)
void addRef ()
Increase the reference count on the object.
void clearLowestBit ()
U32 getRefCount () const
Get the current reference count.
bool isShared () const
void release ()
Decrease the object's reference count and delete the object, if the count drops to zero and claiming the object by the current thread succeeds.
Protected Member Functions
ValueType * getBufferPtr ()
Protected Member Functions inherited from ThreadPool::WorkItem
bool cancellationPoint ()
Mark a point in a work item's execution where the item can be safely cancelled.
virtual void execute ()=0
Execute the actions associated with this work item.
virtual void onCancelled ()
Called when the item has been cancelled.
Protected Attributes
BufferType mBuffer
Buffer keeping/receiving the data elements.
U32 mNumElements
Number of elements to read from/write to the stream.
U32 mOffsetInBuffer
Offset in "mBuffer" from where to read/where to start writing to.
OffsetType mOffsetInStream
Offset in stream from where to read/where to write to.
StreamType * mStream
The stream to read from/write to.
Protected Attributes inherited from ThreadPool::WorkItem
Context * mContext
The work context of this item.
bool mExecuted
This flag is set after the execute() method has completed.
Protected Attributes inherited from ThreadSafeRefCount< WorkItem >
U32 mRefCount
Reference count and claim bit. Note that this increments in steps of two.
Additional Inherited Members
Static Public Member Functions inherited from ThreadSafeRefCount< WorkItem >
static WorkItem * safeRead (WorkItem *const volatile &refPtr)
Dereference a reference-counted pointer in a multi-thread safe way.
Static Protected Member Functions inherited from ThreadSafeRefCount< WorkItem >
static U32 decrementAndTestAndSet (U32 &refCount)
Decrement the given reference count.
Detailed Description
template<typename T, class Stream>
class AsyncIOItem< T, Stream >
Abstract superclass of async I/O work items.
Supports both offset-based stream I/O as well as I/O on streams with implicit positions. Note that if you use the latter type, make sure that no other thread is messing with the stream at the same time or chaos will ensue.
Parameters
T Type of elements being streamed.
Member Typedef Documentation
template<typename T, class Stream> typedef RawDataT< ValueType > AsyncIOItem< T, Stream >::BufferType
template<typename T, class Stream> typedef U32 AsyncIOItem< T, Stream >::OffsetType
template<typename T, class Stream> typedef WorkItem AsyncIOItem< T, Stream >::Parent
template<typename T, class Stream> typedef Stream AsyncIOItem< T, Stream >::StreamType
template<typename T, class Stream> typedef T AsyncIOItem< T, Stream >::ValueType
Constructor & Destructor Documentation
template<typename T, class Stream> AsyncIOItem< T, Stream >::AsyncIOItem (StreamType * stream, U32 numElements, OffsetType offsetInStream, ThreadContext * context = 0) inline
If the stream uses implicit positioning, then the supplied "offsetInStream" is meaningless and ignored.
template<typename T, class Stream> AsyncIOItem< T, Stream >::AsyncIOItem (StreamType * stream, BufferType & buffer, U32 offsetInBuffer, U32 numElements, OffsetType offsetInStream, bool takeOwnershipOfBuffer = true, ThreadContext * context = 0) inline
Construct a read item on "stream" that stores data into the given "buffer".
Member Function Documentation
template<typename T, class Stream> BufferType& AsyncIOItem< T, Stream >::getBuffer () inline
Return the data buffer being written to/read from.
Note
This may not yet have been allocated.
Referenced by AsyncReadItem< Parent::SourceElementType, StreamType >::_allocBuffer(), and AsyncIOItem< Parent::SourceElementType, StreamType >::getBufferPtr().
template<typename T, class Stream> ValueType* AsyncIOItem< T, Stream >::getBufferPtr () inline protected
Referenced by AsyncReadItem< Parent::SourceElementType, StreamType >::_prep(), AsyncWriteItem< T, Stream >::_prep(), AsyncReadItem< Parent::SourceElementType, StreamType >::_read(), and AsyncWriteItem< T, Stream >::_write().
template<typename T, class Stream> U32 AsyncIOItem< T, Stream >::getNumElements () inline
Return the number of elements involved in the transfer.
Referenced by AsyncReadItem< Parent::SourceElementType, StreamType >::_allocBuffer(), AsyncReadItem< Parent::SourceElementType, StreamType >::_prep(), AsyncWriteItem< T, Stream >::_prep(), AsyncReadItem< Parent::SourceElementType, StreamType >::_read(), and AsyncWriteItem< T, Stream >::_write().
template<typename T, class Stream> U32 AsyncIOItem< T, Stream >::getOffsetInBuffer () inline
Return the position in the data buffer at which to start the transfer.
Referenced by AsyncIOItem< Parent::SourceElementType, StreamType >::getBufferPtr().
template<typename T, class Stream> OffsetType AsyncIOItem< T, Stream >::getOffsetInStream () inline
Return the position in the stream at which to start the transfer.
Note
Only meaningful for streams that support offset I/O.
Referenced by AsyncReadItem< Parent::SourceElementType, StreamType >::_prep(), AsyncReadItem< Parent::SourceElementType, StreamType >::_read(), and AsyncWriteItem< T, Stream >::_write().
template<typename T, class Stream> StreamType* AsyncIOItem< T, Stream >::getStream () inline
Return the stream being written to/read from.
Referenced by AsyncReadItem< Parent::SourceElementType, StreamType >::_prep(), AsyncReadItem< T, Stream >::execute(), and AsyncWriteItem< T, Stream >::execute().
Member Data Documentation
template<typename T, class Stream> BufferType AsyncIOItem< T, Stream >::mBuffer protected
Buffer keeping/receiving the data elements.
Referenced by AsyncIOItem< Parent::SourceElementType, StreamType >::getBuffer().
template<typename T, class Stream> U32 AsyncIOItem< T, Stream >::mNumElements protected
Number of elements to read from/write to the stream.
Referenced by AsyncIOItem< Parent::SourceElementType, StreamType >::getNumElements().
template<typename T, class Stream> U32 AsyncIOItem< T, Stream >::mOffsetInBuffer protected
Offset in "mBuffer" from where to read/where to start writing to.
Referenced by AsyncIOItem< Parent::SourceElementType, StreamType >::getOffsetInBuffer().
template<typename T, class Stream> OffsetType AsyncIOItem< T, Stream >::mOffsetInStream protected
Offset in stream from where to read/where to write to.
Note
This is only meaningful if the stream is an offset I/O stream. For a stream that is can do both types of I/O, explicit offsets are preferred and this value is used.
Referenced by AsyncIOItem< Parent::SourceElementType, StreamType >::getOffsetInStream().
template<typename T, class Stream> StreamType* AsyncIOItem< T, Stream >::mStream protected
The stream to read from/write to.
Referenced by AsyncIOItem< Parent::SourceElementType, StreamType >::getStream().
Copyright © GarageGames, LLC. All Rights Reserved.