CodeStream Class Reference
Main Modules Class List Namespace List Online
CodeStream Class Reference
Utility class to emit and patch bytecode.
#include <console/compiler.h>
Public Types
enum Constants { BlockSize = 16384 }
enum FixType {
FIXTYPE_LOOPBLOCKSTART,
FIXTYPE_BREAK,
FIXTYPE_CONTINUE
}
Protected Attributes
Emitted code
{
CodeData * mCode
CodeData * mCodeHead
U32 mCodePos
Code fixing stacks
}
{
Vector< U32 > mFixList
Vector< U32 > mFixStack
Vector< bool > mFixLoopStack
Vector< PatchEntry > mPatchList
Vector< U32 > mBreakLines
}
CodeStream ()
~CodeStream ()
U8 * allocCode (U32 sz)
U32 emit (U32 code)
void patch (U32 addr, U32 code)
U32 emitSTE (const char *code)
U32 tell ()
bool inLoop ()
U32 emitFix (FixType type)
void pushFixScope (bool isLoop)
void popFixScope ()
void fixLoop (U32 loopBlockStart, U32 breakPoint, U32 continuePoint)
void addBreakLine (U32 lineNumber, U32 ip)
U32 getNumLineBreaks ()
void emitCodeStream (U32 *size, U32 **stream, U32 **lineBreaks)
void reset ()
Detailed Description
Utility class to emit and patch bytecode.
Member Enumeration Documentation
enum CodeStream::Constants
Enumerator
BlockSize
enum CodeStream::FixType
Enumerator
FIXTYPE_LOOPBLOCKSTART
FIXTYPE_BREAK
FIXTYPE_CONTINUE
Constructor & Destructor Documentation
CodeStream::CodeStream () inline
CodeStream::~CodeStream () inline
References CodeData::data, dFree(), and Compiler::CompilerIdentTable::reset().
Member Function Documentation
void CodeStream::addBreakLine (U32 lineNumber, U32 ip) inline
References Vector< T >::push_back().
U8* CodeStream::allocCode (U32 sz)
U32 CodeStream::emit (U32 code) inline
void CodeStream::emitCodeStream (U32 * size, U32 ** stream, U32 ** lineBreaks)
U32 CodeStream::emitFix (FixType type) inline
References Vector< T >::push_back().
U32 CodeStream::emitSTE (const char * code) inline
References Compiler::STEtoCode.
void CodeStream::fixLoop (U32 loopBlockStart, U32 breakPoint, U32 continuePoint)
U32 CodeStream::getNumLineBreaks () inline
References Compiler::CompilerIdentTable::reset(), and Vector< T >::size().
bool CodeStream::inLoop () inline
void CodeStream::patch (U32 addr, U32 code) inline
References Vector< T >::push_back().
void CodeStream::popFixScope () inline
References Vector< T >::pop_back(), and Vector< T >::size().
void CodeStream::pushFixScope (bool isLoop) inline
References Vector< T >::push_back(), and Vector< T >::size().
void CodeStream::reset ()
U32 CodeStream::tell () inline
Member Data Documentation
Vector<U32> CodeStream::mBreakLines protected
}
Line numbers
CodeData* CodeStream::mCode protected
CodeData* CodeStream::mCodeHead protected
U32 CodeStream::mCodePos protected
Vector<U32> CodeStream::mFixList protected
Vector<bool> CodeStream::mFixLoopStack protected
Vector<U32> CodeStream::mFixStack protected
Vector<PatchEntry> CodeStream::mPatchList protected
Copyright © GarageGames, LLC. All Rights Reserved.