GFXD3D9Cubemap Class Reference
Main Modules Class List Namespace List Online
GFXD3D9Cubemap Class Reference
#include <gfx/D3D9/gfxD3D9Cubemap.h>
Public Member Functions
GFXD3D9Cubemap ()
virtual ~GFXD3D9Cubemap ()
virtual GFXFormat getFormat () const
Returns the face texture format.
virtual U32 getSize () const
Returns the size of the faces.
virtual void initDynamic (U32 texSize, GFXFormat faceFormat=GFXFormatR8G8B8A8)
virtual void initStatic (GFXTexHandle *faces)
Create a static cubemap from a list of 6 face textures.
virtual void initStatic (DDSFile *dds)
Create a static cubemap from a DDS cubemap file.
virtual void resurrect ()
When called the resource should restore all device sensitive information destroyed by zombify()
virtual void setToTexUnit (U32 tuNum)
virtual void zombify ()
When called the resource should destroy all device sensitive information (e.g. D3D resources in D3DPOOL_DEFAULT.
Public Member Functions inherited from GFXCubemap
virtual ~GFXCubemap ()
virtual const String describeSelf () const
The resource should put a description of itself (number of vertices, size/width of texture, etc.) in buffer.
const String & getPath () const
Returns the cubemap file path set at creation.
void initNormalize (U32 size)
Public Member Functions inherited from StrongRefBase
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Public Member Functions inherited from GFXResource
GFXResource ()
virtual ~GFXResource ()
void clearFlag ()
GFXResource * getNextResource () const
GFXDevice * getOwningDevice () const
GFXResource * getPrevResource () const
bool isFlagged ()
void registerResourceWithDevice (GFXDevice *device)
Registers this resource with the given device.
void setFlag ()
Protected Member Functions
void _onTextureEvent (GFXTexCallbackCode code)
The callback used to get texture events.
void fillCubeTextures (GFXTexHandle *faces, LPDIRECT3DDEVICE9 D3DDevice)
void releaseSurfaces ()
Protected Member Functions inherited from GFXCubemap
void _setPath (const String &path)
Sets the cubemap file path.
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Protected Attributes
LPDIRECT3DCUBETEXTURE9 mCubeTex
bool mDynamic
GFXFormat mFaceFormat
U32 mTexSize
Protected Attributes inherited from GFXCubemap
String mPath
The path to the cubemap file.
Protected Attributes inherited from StrongRefBase
U32 mRefCount
reference counter for StrongRefPtr objects
Static Protected Attributes
static _D3DCUBEMAP_FACES faceList [6]
Constructor & Destructor Documentation
GFXD3D9Cubemap::GFXD3D9Cubemap ()
Referenced by getFormat().
virtual GFXD3D9Cubemap::~GFXD3D9Cubemap () virtual
Referenced by getFormat().
Member Function Documentation
void GFXD3D9Cubemap::_onTextureEvent (GFXTexCallbackCode code) protected
The callback used to get texture events.
See also
GFXTextureManager::addEventDelegate
void GFXD3D9Cubemap::fillCubeTextures (GFXTexHandle * faces, LPDIRECT3DDEVICE9 D3DDevice) protected
virtual GFXFormat GFXD3D9Cubemap::getFormat () const inline virtual
Returns the face texture format.
Implements GFXCubemap.
References GFXD3D9Cubemap(), mFaceFormat, resurrect(), zombify(), and ~GFXD3D9Cubemap().
virtual U32 GFXD3D9Cubemap::getSize () const inline virtual
Returns the size of the faces.
Implements GFXCubemap.
References mTexSize.
virtual void GFXD3D9Cubemap::initDynamic (U32 texSize, GFXFormat faceFormat = GFXFormatR8G8B8A8) virtual
Implements GFXCubemap.
virtual void GFXD3D9Cubemap::initStatic (GFXTexHandle * faces) virtual
Create a static cubemap from a list of 6 face textures.
Implements GFXCubemap.
virtual void GFXD3D9Cubemap::initStatic (DDSFile * dds) virtual
Create a static cubemap from a DDS cubemap file.
Implements GFXCubemap.
void GFXD3D9Cubemap::releaseSurfaces () protected
virtual void GFXD3D9Cubemap::resurrect () virtual
When called the resource should restore all device sensitive information destroyed by zombify()
Implements GFXResource.
Referenced by getFormat().
virtual void GFXD3D9Cubemap::setToTexUnit (U32 tuNum) virtual
Implements GFXCubemap.
virtual void GFXD3D9Cubemap::zombify () virtual
When called the resource should destroy all device sensitive information (e.g. D3D resources in D3DPOOL_DEFAULT.
Implements GFXResource.
Referenced by getFormat().
Member Data Documentation
_D3DCUBEMAP_FACES GFXD3D9Cubemap::faceList[6] static protected
LPDIRECT3DCUBETEXTURE9 GFXD3D9Cubemap::mCubeTex protected
bool GFXD3D9Cubemap::mDynamic protected
GFXFormat GFXD3D9Cubemap::mFaceFormat protected
Referenced by getFormat().
U32 GFXD3D9Cubemap::mTexSize protected
Referenced by getSize().
Copyright © GarageGames, LLC. All Rights Reserved.