PhysicsPlugin Class Reference
Main Modules Class List Namespace List Online
PhysicsPlugin Class Reference abstract
#include <T3D/physics/physicsPlugin.h>
Public Member Functions
PhysicsPlugin ()
virtual ~PhysicsPlugin ()
virtual PhysicsBody * createBody ()=0
virtual PhysicsCollision * createCollision ()=0
virtual PhysicsPlayer * createPlayer ()=0
virtual bool createWorld (const String &worldName)=0
virtual void destroyPlugin ()=0
Cleans up, deactivates, and deletes the plugin.
virtual void destroyWorld (const String &worldName)=0
void enableDebugDraw (bool enabled)
virtual void enableSimulation (const String &worldName, bool enable)=0
SimSet * getPhysicsCleanup () const
Returns the physics cleanup set.
virtual const F32 getTimeScale () const =0
virtual PhysicsWorld * getWorld (const String &worldName) const =0
virtual bool isSimulationEnabled () const =0
virtual void reset ()=0
virtual void setTimeScale (const F32 timeScale)=0
Static Public Member Functions
static bool activate (const char *library)
static PhysicsResetSignal & getPhysicsResetSignal ()
static PhysicsPlugin * getSingleton ()
Returns the active physics plugin.
static U32 getThreadCount ()
static bool isSinglePlayer ()
Static Public Attributes
static bool smSinglePlayer
Note this should go away when we have "real" singleplayer.
static U32 smThreadCount
Number of threads to use if supported by the plugin.
Protected Member Functions
virtual void _onDebugDrawEnabled (bool enabled)
Overload this to toggle any physics engine specific stuff when debug rendering is enabled or disabled.
Static Protected Member Functions
static void _debugDraw (SceneManager *graph, const SceneRenderState *state)
Delegate method for debug drawing.
Protected Attributes
SimObjectPtr< SimSet > mPhysicsCleanup
A SimSet of objects to delete before the physics reset/restore event occurs.
Map< StringNoCase, PhysicsWorld * > mPhysicsWorldLookup
Static Protected Attributes
static String smClientWorldName
static PhysicsResetSignal smPhysicsResetSignal
static String smServerWorldName
static PhysicsPlugin * smSingleton
The current active physics plugin.
Constructor & Destructor Documentation
PhysicsPlugin::PhysicsPlugin ()
Referenced by getSingleton().
virtual PhysicsPlugin::~PhysicsPlugin () virtual
Referenced by getSingleton().
Member Function Documentation
static void PhysicsPlugin::_debugDraw (SceneManager * graph, const SceneRenderState * state) static protected
Delegate method for debug drawing.
virtual void PhysicsPlugin::_onDebugDrawEnabled (bool enabled) inline protected virtual
Overload this to toggle any physics engine specific stuff when debug rendering is enabled or disabled.
static bool PhysicsPlugin::activate (const char * library) static
Referenced by getSingleton().
virtual PhysicsBody* PhysicsPlugin::createBody () pure virtual
Implemented in Px3Plugin, and BtPlugin.
Referenced by getPhysicsCleanup().
virtual PhysicsCollision* PhysicsPlugin::createCollision () pure virtual
Implemented in Px3Plugin, and BtPlugin.
Referenced by getPhysicsCleanup().
virtual PhysicsPlayer* PhysicsPlugin::createPlayer () pure virtual
Implemented in Px3Plugin, and BtPlugin.
Referenced by getPhysicsCleanup().
virtual bool PhysicsPlugin::createWorld (const String & worldName) pure virtual
Implemented in Px3Plugin, and BtPlugin.
Referenced by getPhysicsResetSignal().
virtual void PhysicsPlugin::destroyPlugin () pure virtual
Cleans up, deactivates, and deletes the plugin.
Implemented in Px3Plugin, and BtPlugin.
Referenced by getSingleton().
virtual void PhysicsPlugin::destroyWorld (const String & worldName) pure virtual
Implemented in Px3Plugin, and BtPlugin.
Referenced by getPhysicsResetSignal().
void PhysicsPlugin::enableDebugDraw (bool enabled)
Referenced by getPhysicsCleanup().
virtual void PhysicsPlugin::enableSimulation (const String & worldName, bool enable) pure virtual
Implemented in Px3Plugin, and BtPlugin.
Referenced by getPhysicsCleanup().
SimSet* PhysicsPlugin::getPhysicsCleanup () const inline
Returns the physics cleanup set.
References createBody(), createCollision(), createPlayer(), enableDebugDraw(), enableSimulation(), getTimeScale(), isSimulationEnabled(), mPhysicsCleanup, and setTimeScale().
static PhysicsResetSignal& PhysicsPlugin::getPhysicsResetSignal () inline static
References createWorld(), destroyWorld(), getWorld(), and smPhysicsResetSignal.
static PhysicsPlugin* PhysicsPlugin::getSingleton () inline static
Returns the active physics plugin.
See also
PHYSICSPLUGIN
References activate(), destroyPlugin(), PhysicsPlugin(), reset(), smSingleton, and ~PhysicsPlugin().
static U32 PhysicsPlugin::getThreadCount () inline static
References smThreadCount.
virtual const F32 PhysicsPlugin::getTimeScale () const pure virtual
Implemented in Px3Plugin, and BtPlugin.
Referenced by getPhysicsCleanup().
virtual PhysicsWorld* PhysicsPlugin::getWorld (const String & worldName) const pure virtual
Implemented in Px3Plugin, and BtPlugin.
Referenced by getPhysicsResetSignal().
virtual bool PhysicsPlugin::isSimulationEnabled () const pure virtual
Implemented in Px3Plugin, and BtPlugin.
Referenced by getPhysicsCleanup().
static bool PhysicsPlugin::isSinglePlayer () inline static
References smSinglePlayer.
virtual void PhysicsPlugin::reset () pure virtual
Implemented in Px3Plugin, and BtPlugin.
Referenced by getSingleton().
virtual void PhysicsPlugin::setTimeScale (const F32 timeScale) pure virtual
Implemented in Px3Plugin, and BtPlugin.
Referenced by getPhysicsCleanup().
Member Data Documentation
SimObjectPtr<SimSet> PhysicsPlugin::mPhysicsCleanup protected
A SimSet of objects to delete before the physics reset/restore event occurs.
Referenced by getPhysicsCleanup().
Map<StringNoCase, PhysicsWorld*> PhysicsPlugin::mPhysicsWorldLookup protected
String PhysicsPlugin::smClientWorldName static protected
PhysicsResetSignal PhysicsPlugin::smPhysicsResetSignal static protected
Referenced by getPhysicsResetSignal().
String PhysicsPlugin::smServerWorldName static protected
bool PhysicsPlugin::smSinglePlayer static
Note this should go away when we have "real" singleplayer.
Referenced by isSinglePlayer().
PhysicsPlugin* PhysicsPlugin::smSingleton static protected
The current active physics plugin.
Referenced by getSingleton().
U32 PhysicsPlugin::smThreadCount static
Number of threads to use if supported by the plugin.
Referenced by getThreadCount().
Copyright © GarageGames, LLC. All Rights Reserved.