GFXTextureProfileStats Class Reference
Main Modules Class List Namespace List Online
GFXTextureProfileStats Class Reference
Helper struct for gathering profile stats.
#include <gfx/gfxTextureProfile.h>
Public Member Functions
GFXTextureProfileStats ()
Constructs and clears the stats.
void clear ()
Zeros all the stats.
GFXTextureProfileStats & operator+= (const GFXTextureProfileStats &stats)
Adds stats together.
Public Attributes
U32 activeBytes
Amount of storage currently allocated under this profile.
U32 activeCount
Count of textures of this profile type allocated.
U32 activeTexels
Amount of texelspace currently allocated under this profile.
U32 allocatedBytes
Total number of bytes allocated under this profile.
U32 allocatedTexels
Total number of texels allocated under this profile.
U32 allocatedTextures
Total number of textures allocated under this profile.
Detailed Description
Helper struct for gathering profile stats.
Constructor & Destructor Documentation
GFXTextureProfileStats::GFXTextureProfileStats () inline
Constructs and clears the stats.
References clear().
Member Function Documentation
void GFXTextureProfileStats::clear (void) inline
Zeros all the stats.
References dMemset().
Referenced by GFXTextureProfileStats().
GFXTextureProfileStats& GFXTextureProfileStats::operator+= (const GFXTextureProfileStats & stats) inline
Adds stats together.
References activeBytes, activeCount, activeTexels, allocatedBytes, allocatedTexels, and allocatedTextures.
Member Data Documentation
U32 GFXTextureProfileStats::activeBytes
Amount of storage currently allocated under this profile.
Referenced by operator+=().
U32 GFXTextureProfileStats::activeCount
Count of textures of this profile type allocated.
Referenced by operator+=().
U32 GFXTextureProfileStats::activeTexels
Amount of texelspace currently allocated under this profile.
Referenced by operator+=().
U32 GFXTextureProfileStats::allocatedBytes
Total number of bytes allocated under this profile.
Referenced by operator+=().
U32 GFXTextureProfileStats::allocatedTexels
Total number of texels allocated under this profile.
Referenced by operator+=().
U32 GFXTextureProfileStats::allocatedTextures
Total number of textures allocated under this profile.
Referenced by operator+=().
Copyright © GarageGames, LLC. All Rights Reserved.