BitVectorW Class Reference
Main Modules Class List Namespace List Online
BitVectorW Class Reference
#include <core/bitVectorW.h>
Public Member Functions
BitVectorW ()
~BitVectorW ()
U32 bitWidth () const
U8 * dataPtr () const
U32 getU17 (U32 idx) const
U32 numBytes () const
U32 numEntries () const
void setDims (U32 sz, U32 w)
void setU17 (U32 idx, U32 val)
Detailed Description
See also
BitVector
Constructor & Destructor Documentation
BitVectorW::BitVectorW () inline
References setDims().
BitVectorW::~BitVectorW () inline
Member Function Documentation
U32 BitVectorW::bitWidth () const inline
U8* BitVectorW::dataPtr () const inline
References getU17(), numBytes(), setDims(), and setU17().
U32 BitVectorW::getU17 (U32 idx) const inline
Referenced by dataPtr().
U32 BitVectorW::numBytes () const inline
Referenced by dataPtr(), and setDims().
U32 BitVectorW::numEntries () const inline
void BitVectorW::setDims (U32 sz, U32 w) inline
References dMemset(), and numBytes().
Referenced by BitVectorW(), and dataPtr().
void BitVectorW::setU17 (U32 idx, U32 val) inline
Referenced by dataPtr().
Copyright © GarageGames, LLC. All Rights Reserved.