GFXD3D11Cubemap Class Reference
Main Modules Class List Namespace List Online
GFXD3D11Cubemap Class Reference
#include <gfx/D3D11/gfxD3D11Cubemap.h>
Public Member Functions
GFXD3D11Cubemap ()
virtual ~GFXD3D11Cubemap ()
ID3D11Texture2D * get2DTex ()
ID3D11DepthStencilView * getDSView ()
virtual GFXFormat getFormat () const
Returns the face texture format.
ID3D11RenderTargetView * getRTView (U32 faceIdx)
ID3D11RenderTargetView ** getRTViewArray ()
virtual U32 getSize () const
Returns the size of the faces.
ID3D11ShaderResourceView * getSRView ()
virtual void initDynamic (U32 texSize, GFXFormat faceFormat=GFXFormatR8G8B8A8)
virtual void initStatic (GFXTexHandle *faces)
Create a static cubemap from a list of 6 face textures.
virtual void initStatic (DDSFile *dds)
Create a static cubemap from a DDS cubemap file.
virtual void resurrect ()
When called the resource should restore all device sensitive information destroyed by zombify()
virtual void setToTexUnit (U32 tuNum)
virtual void zombify ()
When called the resource should destroy all device sensitive information (e.g. D3D resources in D3DPOOL_DEFAULT.
Public Member Functions inherited from GFXCubemap
virtual ~GFXCubemap ()
virtual const String describeSelf () const
The resource should put a description of itself (number of vertices, size/width of texture, etc.) in buffer.
const String & getPath () const
Returns the cubemap file path set at creation.
void initNormalize (U32 size)
Public Member Functions inherited from StrongRefBase
StrongRefBase ()
void decRefCount ()
Decrements the reference count.
virtual void destroySelf ()
object destroy self call (from StrongRefPtr). Override if this class has specially allocated memory.
U32 getRefCount () const
void incRefCount ()
Increments the reference count.
Public Member Functions inherited from WeakRefBase
WeakRefBase ()
virtual ~WeakRefBase ()
WeakReference * getWeakReference ()
Public Member Functions inherited from GFXResource
GFXResource ()
virtual ~GFXResource ()
void clearFlag ()
GFXResource * getNextResource () const
GFXDevice * getOwningDevice () const
GFXResource * getPrevResource () const
bool isFlagged ()
void registerResourceWithDevice (GFXDevice *device)
Registers this resource with the given device.
void setFlag ()
Additional Inherited Members
Protected Member Functions inherited from GFXCubemap
void _setPath (const String &path)
Sets the cubemap file path.
Protected Member Functions inherited from WeakRefBase
void clearWeakReferences ()
Protected Attributes inherited from GFXCubemap
String mPath
The path to the cubemap file.
Protected Attributes inherited from StrongRefBase
U32 mRefCount
reference counter for StrongRefPtr objects
Constructor & Destructor Documentation
GFXD3D11Cubemap::GFXD3D11Cubemap ()
Referenced by getFormat().
virtual GFXD3D11Cubemap::~GFXD3D11Cubemap () virtual
Referenced by getFormat().
Member Function Documentation
ID3D11Texture2D* GFXD3D11Cubemap::get2DTex ()
Referenced by getFormat().
ID3D11DepthStencilView* GFXD3D11Cubemap::getDSView ()
Referenced by getFormat().
virtual GFXFormat GFXD3D11Cubemap::getFormat () const inline virtual
Returns the face texture format.
Implements GFXCubemap.
References get2DTex(), getDSView(), getRTView(), getRTViewArray(), getSRView(), GFXD3D11Cubemap(), resurrect(), zombify(), and ~GFXD3D11Cubemap().
ID3D11RenderTargetView* GFXD3D11Cubemap::getRTView (U32 faceIdx)
Referenced by getFormat().
ID3D11RenderTargetView** GFXD3D11Cubemap::getRTViewArray ()
Referenced by getFormat().
virtual U32 GFXD3D11Cubemap::getSize () const inline virtual
Returns the size of the faces.
Implements GFXCubemap.
ID3D11ShaderResourceView* GFXD3D11Cubemap::getSRView ()
Referenced by getFormat().
virtual void GFXD3D11Cubemap::initDynamic (U32 texSize, GFXFormat faceFormat = GFXFormatR8G8B8A8) virtual
Implements GFXCubemap.
virtual void GFXD3D11Cubemap::initStatic (GFXTexHandle * faces) virtual
Create a static cubemap from a list of 6 face textures.
Implements GFXCubemap.
virtual void GFXD3D11Cubemap::initStatic (DDSFile * dds) virtual
Create a static cubemap from a DDS cubemap file.
Implements GFXCubemap.
virtual void GFXD3D11Cubemap::resurrect () virtual
When called the resource should restore all device sensitive information destroyed by zombify()
Implements GFXResource.
Referenced by getFormat().
virtual void GFXD3D11Cubemap::setToTexUnit (U32 tuNum) virtual
Implements GFXCubemap.
virtual void GFXD3D11Cubemap::zombify () virtual
When called the resource should destroy all device sensitive information (e.g. D3D resources in D3DPOOL_DEFAULT.
Implements GFXResource.
Referenced by getFormat().
Copyright © GarageGames, LLC. All Rights Reserved.