rapidjson::GenericReader< SourceEncoding, TargetEncoding, Allocator > Class Template Reference
Main Modules Class List Namespace List Online
rapidjson::GenericReader< SourceEncoding, TargetEncoding, Allocator > Class Template Reference
SAX-style JSON parser. Use Reader for UTF8 encoding and default allocator.
#include <persistence/rapidjson/reader.h>
Public Types
typedef SourceEncoding::Ch Ch
Public Member Functions
GenericReader (Allocator *allocator=0, size_t stackCapacity=kDefaultStackCapacity)
Constructor.
size_t GetErrorOffset () const
const char * GetParseError () const
bool HasParseError () const
template<unsigned parseFlags, typename InputStream , typename Handler >
bool Parse (InputStream &is, Handler &handler)
Parse JSON text.
Detailed Description
template<typename SourceEncoding, typename TargetEncoding, typename Allocator = MemoryPoolAllocator<>>
class rapidjson::GenericReader< SourceEncoding, TargetEncoding, Allocator >
SAX-style JSON parser. Use Reader for UTF8 encoding and default allocator.
GenericReader parses JSON text from a stream, and send events synchronously to an object implementing Handler concept.
It needs to allocate a stack for storing a single decoded string during non-destructive parsing.
For in-situ parsing, the decoded string is directly written to the source text string, no temporary buffer is required.
A GenericReader object can be reused for parsing multiple JSON text.
Template Parameters
SourceEncoding Encoding of the input stream.
TargetEncoding Encoding of the parse output.
Allocator Allocator type for stack.
Member Typedef Documentation
template<typename SourceEncoding, typename TargetEncoding, typename Allocator = MemoryPoolAllocator<>> typedef SourceEncoding::Ch rapidjson::GenericReader< SourceEncoding, TargetEncoding, Allocator >::Ch
Constructor & Destructor Documentation
template<typename SourceEncoding, typename TargetEncoding, typename Allocator = MemoryPoolAllocator<>> rapidjson::GenericReader< SourceEncoding, TargetEncoding, Allocator >::GenericReader (Allocator * allocator = 0, size_t stackCapacity = kDefaultStackCapacity) inline
Constructor.
Parameters
allocator Optional allocator for allocating stack memory. (Only use for non-destructive parsing)
stackCapacity stack capacity in bytes for storing a single decoded string. (Only use for non-destructive parsing)
Member Function Documentation
template<typename SourceEncoding, typename TargetEncoding, typename Allocator = MemoryPoolAllocator<>> size_t rapidjson::GenericReader< SourceEncoding, TargetEncoding, Allocator >::GetErrorOffset () const inline
References rapidjson::kParseInsituFlag, rapidjson::kParseValidateEncodingFlag, rapidjson::internal::Pow10(), rapidjson::SkipWhitespace(), and rapidjson::Transcoder< SourceEncoding, TargetEncoding >::Transcode().
Referenced by rapidjson::GenericDocument< Encoding, Allocator >::ParseStream().
template<typename SourceEncoding, typename TargetEncoding, typename Allocator = MemoryPoolAllocator<>> const char* rapidjson::GenericReader< SourceEncoding, TargetEncoding, Allocator >::GetParseError () const inline
Referenced by rapidjson::GenericDocument< Encoding, Allocator >::ParseStream().
template<typename SourceEncoding, typename TargetEncoding, typename Allocator = MemoryPoolAllocator<>> bool rapidjson::GenericReader< SourceEncoding, TargetEncoding, Allocator >::HasParseError () const inline
template<typename SourceEncoding, typename TargetEncoding, typename Allocator = MemoryPoolAllocator<>> template<unsigned parseFlags, typename InputStream , typename Handler > bool rapidjson::GenericReader< SourceEncoding, TargetEncoding, Allocator >::Parse (InputStream & is, Handler & handler) inline
Parse JSON text.
Template Parameters
parseFlags Combination of ParseFlag.
InputStream Type of input stream.
Handler Type of handler which must implement Handler concept.
Parameters
stream Input stream to be parsed.
handler The handler to receive events.
Returns
Whether the parsing is successful.
References rapidjson::SkipWhitespace().
Copyright © GarageGames, LLC. All Rights Reserved.