MoveList Class Reference
Main Modules Class List Namespace List Online
MoveList Class Reference abstract
#include <T3D/gameBase/moveList.h>
Public Member Functions
MoveList ()
virtual ~MoveList ()
virtual void ackMoves (U32 count)
virtual void advanceMove ()=0
virtual bool areMovesPending ()
void clearMismatch ()
virtual void clearMoves (U32 count)
virtual void collectMove ()
virtual U32 getMoves (Move **, U32 *numMoves)
virtual void init ()
virtual bool isBacklogged ()
If there are no pending moves and the input queue is full, then the connection to the server must be clogged.
bool isMismatch ()
virtual void markControlDirty ()
virtual void onAdvanceObjects ()=0
virtual void pushMove (const Move &mv)
virtual void reset ()
Clear out all moves in the list and reset to initial state.
void resetCatchup ()
Reset move list back to last acknowledged move.
void resetClientMoves ()
Reset to beginning of client move list.
void setConnection (GameConnection *connection)
Move Packets
Write/read move data to the packet.
virtual void ghostReadExtra (NetObject *, BitStream *, bool newGhost)
virtual void ghostWriteExtra (NetObject *, BitStream *)
virtual void ghostPreRead (NetObject *, bool newGhost)
virtual void clientWriteMovePacket (BitStream *bstream)=0
virtual void clientReadMovePacket (BitStream *)=0
virtual void serverWriteMovePacket (BitStream *)=0
virtual void serverReadMovePacket (BitStream *bstream)=0
virtual void writeDemoStartBlock (ResizeBitStream *stream)
virtual void readDemoStartBlock (BitStream *stream)
Protected Types
enum {
MoveCountBits = 5,
MaxMoveCount = 30
}
Protected Member Functions
bool getNextMove (Move &curMove)
Protected Attributes
GameConnection * mConnection
bool mControlMismatch
U32 mFirstMoveIndex
U32 mLastClientMove
U32 mLastMoveAck
Vector< Move > mMoveVec
Member Enumeration Documentation
anonymous enum protected
Enumerator
MoveCountBits
MaxMoveCount
MaxMoveCount should not exceed the MoveManager's own maximum (MaxMoveQueueSize)
Constructor & Destructor Documentation
MoveList::MoveList ()
virtual MoveList::~MoveList () inline virtual
Member Function Documentation
virtual void MoveList::ackMoves (U32 count) virtual
Reimplemented in ExtendedMoveList.
Referenced by clearMismatch().
virtual void MoveList::advanceMove () pure virtual
Implemented in HifiMoveList, StdMoveList, and ExtendedMoveList.
Referenced by ghostPreRead().
virtual bool MoveList::areMovesPending () virtual
Reimplemented in ExtendedMoveList.
Referenced by clearMismatch().
void MoveList::clearMismatch () inline
References ackMoves(), areMovesPending(), getNextMove(), isBacklogged(), mControlMismatch, and reset().
virtual void MoveList::clearMoves (U32 count) virtual
Reimplemented in StdMoveList, and ExtendedMoveList.
Referenced by resetCatchup().
virtual void MoveList::clientReadMovePacket (BitStream *) pure virtual
Implemented in HifiMoveList, StdMoveList, and ExtendedMoveList.
Referenced by ghostPreRead().
virtual void MoveList::clientWriteMovePacket (BitStream * bstream) pure virtual
Implemented in HifiMoveList, StdMoveList, and ExtendedMoveList.
Referenced by ghostPreRead().
virtual void MoveList::collectMove () virtual
Reimplemented in ExtendedMoveList.
Referenced by resetCatchup().
virtual U32 MoveList::getMoves (Move ** , U32 * numMoves) virtual
Reimplemented in HifiMoveList, StdMoveList, and ExtendedMoveList.
Referenced by ghostPreRead().
bool MoveList::getNextMove (Move & curMove) protected
Referenced by clearMismatch().
virtual void MoveList::ghostPreRead (NetObject * , bool newGhost) inline virtual
Reimplemented in HifiMoveList.
References advanceMove(), clientReadMovePacket(), clientWriteMovePacket(), getMoves(), onAdvanceObjects(), readDemoStartBlock(), serverReadMovePacket(), serverWriteMovePacket(), and writeDemoStartBlock().
virtual void MoveList::ghostReadExtra (NetObject * , BitStream * , bool newGhost) inline virtual
Reimplemented in HifiMoveList.
virtual void MoveList::ghostWriteExtra (NetObject * , BitStream *) inline virtual
virtual void MoveList::init () inline virtual
Reimplemented in HifiMoveList.
virtual bool MoveList::isBacklogged () virtual
If there are no pending moves and the input queue is full, then the connection to the server must be clogged.
Reimplemented in ExtendedMoveList.
Referenced by clearMismatch().
bool MoveList::isMismatch () inline
References mControlMismatch.
virtual void MoveList::markControlDirty () inline virtual
Reimplemented in HifiMoveList.
References mLastClientMove, and mLastMoveAck.
virtual void MoveList::onAdvanceObjects () pure virtual
Implemented in HifiMoveList, StdMoveList, and ExtendedMoveList.
Referenced by ghostPreRead().
virtual void MoveList::pushMove (const Move & mv) virtual
Reimplemented in ExtendedMoveList.
Referenced by resetCatchup().
virtual void MoveList::readDemoStartBlock (BitStream * stream) virtual
Referenced by ghostPreRead().
virtual void MoveList::reset () virtual
Clear out all moves in the list and reset to initial state.
Reimplemented in ExtendedMoveList.
Referenced by clearMismatch(), and HifiClientProcessList::forceHifiReset().
void MoveList::resetCatchup () inline
Reset move list back to last acknowledged move.
References clearMoves(), collectMove(), mLastClientMove, mLastMoveAck, and pushMove().
void MoveList::resetClientMoves () inline
Reset to beginning of client move list.
References mFirstMoveIndex, and mLastClientMove.
virtual void MoveList::serverReadMovePacket (BitStream * bstream) pure virtual
Implemented in HifiMoveList, StdMoveList, and ExtendedMoveList.
Referenced by ghostPreRead().
virtual void MoveList::serverWriteMovePacket (BitStream *) pure virtual
Implemented in HifiMoveList, StdMoveList, and ExtendedMoveList.
Referenced by ghostPreRead().
void MoveList::setConnection (GameConnection * connection) inline
References mConnection.
virtual void MoveList::writeDemoStartBlock (ResizeBitStream * stream) virtual
Referenced by ghostPreRead().
Member Data Documentation
GameConnection* MoveList::mConnection protected
Referenced by setConnection().
bool MoveList::mControlMismatch protected
Referenced by clearMismatch(), and isMismatch().
U32 MoveList::mFirstMoveIndex protected
Referenced by HifiMoveList::onAdvanceObjects(), and resetClientMoves().
U32 MoveList::mLastClientMove protected
Referenced by markControlDirty(), resetCatchup(), and resetClientMoves().
U32 MoveList::mLastMoveAck protected
Referenced by markControlDirty(), and resetCatchup().
Vector<Move> MoveList::mMoveVec protected
Referenced by HifiMoveList::onAdvanceObjects().
Copyright © GarageGames, LLC. All Rights Reserved.