SFXFormat Class Reference
Main Modules Class List Namespace List Online
SFXFormat Class Reference
This class defines the various types of sound data that may be used in the sound system.
#include <sfx/sfxCommon.h>
Public Member Functions
SFXFormat (U8 channels=0, U8 bitsPerSample=0, U32 samplesPerSecond=0)
SFXFormat (const SFXFormat &format)
Copy constructor.
U8 getBitsPerChannel () const
The bits of data per channel.
U8 getBitsPerSample () const
The number of bits per sound sample.
U8 getBytesPerChannel () const
The number of bytes of data per channel.
U8 getBytesPerSample () const
The number of bytes of data per sample.
U8 getChannels () const
Returns the number of sound channels.
U32 getDataLength (U32 ms) const
Returns the data length in bytes.
U32 getDuration (U32 samples) const
Returns the duration from the sample count.
U32 getSampleCount (U32 ms) const
U32 getSamplesPerSecond () const
bool isMono () const
Returns true if there is a single sound channel.
bool isMultiChannel () const
Is true if there are more than two sound channels.
bool isStereo () const
Is true if there are two sound channels.
bool operator== (const SFXFormat &format) const
Comparision between formats.
void set (U8 channels, U8 bitsPerSample, U32 samplesPerSecond)
Sets the format.
Protected Attributes
U8 mBitsPerSample
The number of bits per sound sample.
U8 mChannels
The number of sound channels in the data.
U32 mSamplesPerSecond
The frequency in samples per second.
Detailed Description
This class defines the various types of sound data that may be used in the sound system.
Unlike with most sound APIs, we consider each sample point to comprise all channels in a sound stream rather than only one value for a single channel.
Constructor & Destructor Documentation
SFXFormat::SFXFormat (U8 channels = 0, U8 bitsPerSample = 0, U32 samplesPerSecond = 0) inline
SFXFormat::SFXFormat (const SFXFormat & format) inline
Copy constructor.
Member Function Documentation
U8 SFXFormat::getBitsPerChannel () const inline
The bits of data per channel.
References mChannels.
Referenced by getBytesPerChannel().
U8 SFXFormat::getBitsPerSample () const inline
The number of bits per sound sample.
References mBitsPerSample.
Referenced by SFXALBuffer::_sfxFormatToALFormat().
U8 SFXFormat::getBytesPerChannel () const inline
The number of bytes of data per channel.
References getBitsPerChannel().
U8 SFXFormat::getBytesPerSample () const inline
The number of bytes of data per sample.
Note
Be aware that this comprises all channels.
Referenced by SFXFileStream::getDataLength(), getDataLength(), SFXInternal::SFXAsyncStream::getPacketDuration(), and SFXInternal::SFXStreamPacket::getSampleCount().
U8 SFXFormat::getChannels () const inline
Returns the number of sound channels.
References mChannels.
Referenced by SFXALBuffer::_sfxFormatToALFormat().
U32 SFXFormat::getDataLength (U32 ms) const inline
Returns the data length in bytes.
References getBytesPerSample(), and mSamplesPerSecond.
Referenced by SFXMemoryStream::getDataLength().
U32 SFXFormat::getDuration (U32 samples) const inline
Returns the duration from the sample count.
Referenced by SFXMemoryStream::getDuration(), SFXFileStream::getDuration(), and SFXInternal::SFXAsyncStream::getPacketDuration().
U32 SFXFormat::getSampleCount (U32 ms) const inline
U32 SFXFormat::getSamplesPerSecond () const inline
References mSamplesPerSecond.
bool SFXFormat::isMono () const inline
Returns true if there is a single sound channel.
bool SFXFormat::isMultiChannel () const inline
Is true if there are more than two sound channels.
bool SFXFormat::isStereo () const inline
Is true if there are two sound channels.
bool SFXFormat::operator== (const SFXFormat & format) const inline
Comparision between formats.
References mBitsPerSample, mChannels, and mSamplesPerSecond.
void SFXFormat::set (U8 channels, U8 bitsPerSample, U32 samplesPerSecond) inline
Sets the format.
Member Data Documentation
U8 SFXFormat::mBitsPerSample protected
The number of bits per sound sample.
Referenced by getBitsPerSample(), and operator==().
U8 SFXFormat::mChannels protected
The number of sound channels in the data.
Referenced by getBitsPerChannel(), getChannels(), and operator==().
U32 SFXFormat::mSamplesPerSecond protected
The frequency in samples per second.
Referenced by getDataLength(), getSamplesPerSecond(), and operator==().
Copyright © GarageGames, LLC. All Rights Reserved.