ClassChunker< T > Class Template Reference
Main Modules Class List Namespace List Online
ClassChunker< T > Class Template Reference
Templatized data chunker class with proper construction and destruction of its elements.
#include <core/dataChunker.h>
Public Member Functions
ClassChunker (S32 size=DataChunker::ChunkSize)
T * alloc ()
Allocates and properly constructs in place a new element.
void free (T *elem)
Properly destructs and frees an element allocated with the alloc method.
void freeBlocks (bool keepOne=false)
Detailed Description
template<class T>
class ClassChunker< T >
Templatized data chunker class with proper construction and destruction of its elements.
DataChunker just allocates space. This subclass actually constructs/destructs the elements. This class is appropriate for more complex classes.
Constructor & Destructor Documentation
template<class T> ClassChunker< T >::ClassChunker (S32 size = DataChunker::ChunkSize) inline
Member Function Documentation
template<class T> T* ClassChunker< T >::alloc () inline
Allocates and properly constructs in place a new element.
Referenced by HashTable< Key, Value >::findOrInsert(), HashTable< Key, Value >::insertEqual(), and HashTable< Key, Value >::insertUnique().
template<class T> void ClassChunker< T >::free (T * elem) inline
Properly destructs and frees an element allocated with the alloc method.
Referenced by HashTable< Key, Value >::erase().
template<class T> void ClassChunker< T >::freeBlocks (bool keepOne = false) inline
Referenced by HashTable< Key, Value >::~HashTable().
Copyright © GarageGames, LLC. All Rights Reserved.