SplCtrlPts Class Reference
Main Modules Class List Namespace List Online
SplCtrlPts Class Reference
Class for spline control points.
#include <math/mSplinePatch.h>
Public Member Functions
SplCtrlPts ()
virtual ~SplCtrlPts ()
void addPoint (Point3F &point)
Adds a point to the end of the spline.
U32 getNumPoints ()
Gets the number of points in the spline.
const Point3F * getPoint (U32 pointNum)
Gets the point at the given index.
void setPoint (Point3F &point, U32 pointNum)
Sets a point at the given index to the point given.
void submitPoints (Point3F *pts, U32 num)
Clears existing points and enters new points.
Detailed Description
Class for spline control points.
See also
SplinePatch
Constructor & Destructor Documentation
SplCtrlPts::SplCtrlPts ()
virtual SplCtrlPts::~SplCtrlPts () virtual
Member Function Documentation
void SplCtrlPts::addPoint (Point3F & point)
Adds a point to the end of the spline.
Parameters
point New point to be added
Referenced by getNumPoints().
U32 SplCtrlPts::getNumPoints () inline
Gets the number of points in the spline.
References addPoint(), getPoint(), setPoint(), Vector< T >::size(), and submitPoints().
const Point3F* SplCtrlPts::getPoint (U32 pointNum)
Gets the point at the given index.
Parameters
pointNum index of the point in question
Referenced by SplinePatch::getControlPoint(), and getNumPoints().
void SplCtrlPts::setPoint (Point3F & point, U32 pointNum)
Sets a point at the given index to the point given.
Parameters
point New value for the given point
pointNum index of the given point
Referenced by getNumPoints().
void SplCtrlPts::submitPoints (Point3F * pts, U32 num)
Clears existing points and enters new points.
Parameters
pts List of points to be added
num Number of points to be added
Referenced by getNumPoints().
Copyright © GarageGames, LLC. All Rights Reserved.