SignalSlot< Signature > Class Template Reference
Main Modules Class List Namespace List Online
SignalSlot< Signature > Class Template Reference
Class for handle automatic diconnect form Signal when destroyed.
#include <core/util/tSignal.h>
Public Types
typedef Delegate< Signature > DelegateSig
typedef SignalBaseT< Signature > SignalSig
Public Member Functions
SignalSlot ()
~SignalSlot ()
void disconnect ()
disconnect from Signal
const DelegateSig & getDelegate ()
bool isConnected () const
is connected to Signal
template<typename X >
void setDelegate (const X &fn)
setDelegate disconect form Signal old delegate and connect new delegate
template<typename X , typename Y >
void setDelegate (const X &ptr, const Y &fn)
void setDelegate (const DelegateSig &dlg)
Protected Member Functions
SignalSig * _getSignal () const
void _setSignal (SignalSig *sig)
Protected Attributes
DelegateSig mDlg
SignalSig * mSignal
Detailed Description
template<typename Signature>
class SignalSlot< Signature >
Class for handle automatic diconnect form Signal when destroyed.
Member Typedef Documentation
template<typename Signature> typedef Delegate< Signature > SignalSlot< Signature >::DelegateSig
template<typename Signature> typedef SignalBaseT< Signature > SignalSlot< Signature >::SignalSig
Constructor & Destructor Documentation
template<typename Signature> SignalSlot< Signature >::SignalSlot () inline
template<typename Signature> SignalSlot< Signature >::~SignalSlot () inline
Member Function Documentation
template<typename Signature> SignalSig* SignalSlot< Signature >::_getSignal () const inline protected
template<typename Signature> void SignalSlot< Signature >::_setSignal (SignalSig * sig) inline protected
Referenced by SignalBaseT< void(A, B, C, D)>::notify().
template<typename Signature> void SignalSlot< Signature >::disconnect () inline
disconnect from Signal
Referenced by SignalBaseT< void(A, B, C, D)>::notify().
template<typename Signature> const DelegateSig& SignalSlot< Signature >::getDelegate () inline
Referenced by SignalBaseT< void(A, B, C, D)>::notify().
template<typename Signature> bool SignalSlot< Signature >::isConnected () const inline
is connected to Signal
Referenced by SignalBaseT< void(A, B, C, D)>::notify().
template<typename Signature> template<typename X > void SignalSlot< Signature >::setDelegate (const X & fn) inline
setDelegate disconect form Signal old delegate and connect new delegate
Referenced by SignalSlot< void()>::setDelegate().
template<typename Signature> template<typename X , typename Y > void SignalSlot< Signature >::setDelegate (const X & ptr, const Y & fn) inline
Referenced by SignalSlot< void()>::setDelegate().
template<typename Signature> void SignalSlot< Signature >::setDelegate (const DelegateSig & dlg) inline
Member Data Documentation
template<typename Signature> DelegateSig SignalSlot< Signature >::mDlg protected
template<typename Signature> SignalSig* SignalSlot< Signature >::mSignal protected
Copyright © GarageGames, LLC. All Rights Reserved.