PSSMLightShadowMap Class Reference
Main Modules Class List Namespace List Online
PSSMLightShadowMap Class Reference
#include <lighting/shadowMap/pssmLightShadowMap.h>
Public Member Functions
PSSMLightShadowMap (LightInfo *light)
virtual void _render (RenderPassManager *renderPass, const SceneRenderState *diffuseState)
virtual ShadowType getShadowType () const
virtual void setShaderParameters (GFXShaderConstBuffer *params, LightingShaderConstants *lsc)
Public Member Functions inherited from LightShadowMap
LightShadowMap (LightInfo *light)
virtual ~LightShadowMap ()
U32 getBestTexSize (U32 scale=1) const
Returns the best texture size based on the user texture size, the last light screen size, and global shadow tweak parameters.
F32 getLastPriority () const
F32 getLastScreenSize () const
U32 getLastUpdate () const
LightInfo * getLightInfo ()
BaseMatInstance * getShadowMaterial (BaseMatInstance *inMat) const
Returns the correct shadow material this type of light or NULL if no shadow material is possible.
U32 getTexSize () const
GFXTextureObject * getTexture () const
const MatrixF & getWorldToLightProj () const
virtual bool hasShadowTex () const
bool isDynamic ()
bool isViewDependent () const
virtual void releaseTextures ()
void render (RenderPassManager *renderPass, const SceneRenderState *diffuseState, bool _dynamic, bool _forceUpdate)
void setDebugTarget (const String &name)
void setDynamic (bool value)
virtual bool setTextureStage (U32 currTexFlag, LightingShaderConstants *lsc)
void updatePriority (const SceneRenderState *state, U32 currTimeMs)
Static Public Attributes
static F32 smDetailAdjustScale
Used to scale TSShapeInstance::smDetailAdjust to have objects lod quicker when in the PSSM shadow.
static F32 smSmallestVisiblePixelSize
Like TSShapeInstance::smSmallestVisiblePixelSize this is used to define the smallest LOD to render.
Static Public Attributes inherited from LightShadowMap
static const GFXFormat ShadowMapFormat
static bool smDebugRenderFrustums
Whether to render shadow frustums for lights that have debug rendering enabled.
static F32 smShadowTexScalar
Used to scale the shadow texture size for performance tweaking.
Protected Member Functions
Box3F _calcClipSpaceAABB (const Frustum &f, const MatrixF &transform, F32 farDist)
void _calcPlanesCullForShadowCasters (Vector< Vector< PlaneF > > &out, const Frustum &viewFrustum, const Point3F &_ligthDir)
void _calcSplitPos (const Frustum &currFrustum)
void _roundProjection (const MatrixF &lightMat, const MatrixF &cropMatrix, Point3F &offset, U32 splitNum)
void _setNumSplits (U32 numSplits, U32 texSize)
Protected Member Functions inherited from LightShadowMap
void _debugRender (SceneRenderState *shadowRenderState)
If there is a LightDebugInfo attached to the light that owns this map, then update its information from the given render state.
void _onTextureEvent (GFXTexCallbackCode code)
The callback used to get texture events.
void calcLightMatrices (MatrixF &outLightMatrix, const Frustum &viewFrustum)
Protected Attributes
Point4F mFarPlaneScalePSSM
F32 mLogWeight
U32 mNumSplits
Point3F mOffsetProj [MAX_SPLITS]
Point3F mScaleProj [MAX_SPLITS]
F32 mSplitDist [MAX_SPLITS+1]
RectI mViewports [MAX_SPLITS]
Protected Attributes inherited from LightShadowMap
GFXShaderConstHandle * mBlurBoundaries
NamedTexTarget mDebugTarget
Helper for rendering shadow map for debugging.
PlatformTimer * mDynamicRefreshTimer
bool mIsDynamic
bool mIsViewDependent
If true the shadow is view dependent and cannot be skipped if visible and within active range.
U32 mLastCull
The time this shadow was last culled and prioritized.
F32 mLastPriority
F32 mLastScreenSize
GFXShader * mLastShader
U32 mLastUpdate
The time this shadow was last updated.
LightInfo * mLight
GFXTexHandle mShadowMapDepth
GFXTexHandle mShadowMapTex
PlatformTimer * mStaticRefreshTimer
GFXTextureTargetRef mTarget
U32 mTexSize
MatrixF mWorldToLightProj
Static Protected Attributes
static const S32 MAX_SPLITS = 4
Static Protected Attributes inherited from LightShadowMap
static Vector< LightShadowMap * > smShadowMaps
All the shadow maps in the system.
static Vector< LightShadowMap * > smUsedShadowMaps
All the shadow maps that have been recently rendered to.
Additional Inherited Members
Static Public Member Functions inherited from LightShadowMap
static GFXTextureObject * _getDepthTarget (U32 width, U32 height)
static S32 QSORT_CALLBACK cmpPriority (LightShadowMap *const *lsm1, LightShadowMap *const *lsm2)
static void releaseAllTextures ()
static U32 releaseUnusedTextures ()
Releases any shadow maps that have not been culled in a while and returns the count of the remaing shadow maps in use.
Constructor & Destructor Documentation
PSSMLightShadowMap::PSSMLightShadowMap (LightInfo * light)
Member Function Documentation
Box3F PSSMLightShadowMap::_calcClipSpaceAABB (const Frustum & f, const MatrixF & transform, F32 farDist) protected
void PSSMLightShadowMap::_calcPlanesCullForShadowCasters (Vector< Vector< PlaneF > > & out, const Frustum & viewFrustum, const Point3F & _ligthDir) protected
void PSSMLightShadowMap::_calcSplitPos (const Frustum & currFrustum) protected
virtual void PSSMLightShadowMap::_render (RenderPassManager * renderPass, const SceneRenderState * diffuseState) virtual
Implements LightShadowMap.
Referenced by getShadowType().
void PSSMLightShadowMap::_roundProjection (const MatrixF & lightMat, const MatrixF & cropMatrix, Point3F & offset, U32 splitNum) protected
void PSSMLightShadowMap::_setNumSplits (U32 numSplits, U32 texSize) protected
virtual ShadowType PSSMLightShadowMap::getShadowType () const inline virtual
Implements LightShadowMap.
References _render(), and setShaderParameters().
virtual void PSSMLightShadowMap::setShaderParameters (GFXShaderConstBuffer * params, LightingShaderConstants * lsc) virtual
Implements LightShadowMap.
Referenced by getShadowType().
Member Data Documentation
const S32 PSSMLightShadowMap::MAX_SPLITS = 4 static protected
Point4F PSSMLightShadowMap::mFarPlaneScalePSSM protected
F32 PSSMLightShadowMap::mLogWeight protected
U32 PSSMLightShadowMap::mNumSplits protected
Point3F PSSMLightShadowMap::mOffsetProj[MAX_SPLITS] protected
Point3F PSSMLightShadowMap::mScaleProj[MAX_SPLITS] protected
F32 PSSMLightShadowMap::mSplitDist[MAX_SPLITS+1] protected
RectI PSSMLightShadowMap::mViewports[MAX_SPLITS] protected
F32 PSSMLightShadowMap::smDetailAdjustScale static
Used to scale TSShapeInstance::smDetailAdjust to have objects lod quicker when in the PSSM shadow.
See also
TSShapeInstance::smDetailAdjust
F32 PSSMLightShadowMap::smSmallestVisiblePixelSize static
Like TSShapeInstance::smSmallestVisiblePixelSize this is used to define the smallest LOD to render.
See also
TSShapeInstance::smSmallestVisiblePixelSize
Copyright © GarageGames, LLC. All Rights Reserved.