_TorqueThreadStatic Class Reference
Main Modules Class List Namespace List Online
_TorqueThreadStatic Class Reference abstract
#include <core/threadStatic.h>
Public Member Functions
_TorqueThreadStatic ()
virtual ~_TorqueThreadStatic ()
virtual const void * getConstMemInstPtr () const =0
virtual void * getMemInstPtr ()=0
virtual const dsize_t getMemInstSize () const =0
Static Public Member Functions
static const U32 getListIndex ()
Protected Member Functions
virtual _TorqueThreadStatic * _createInstance () const =0
Static Protected Attributes
static U32 mListIndex
Constructor & Destructor Documentation
_TorqueThreadStatic::_TorqueThreadStatic () inline
virtual _TorqueThreadStatic::~_TorqueThreadStatic () inline virtual
Member Function Documentation
virtual _TorqueThreadStatic* _TorqueThreadStatic::_createInstance () const protected pure virtual
virtual const void* _TorqueThreadStatic::getConstMemInstPtr () const pure virtual
Implemented in TorqueThreadStatic< T >.
Referenced by getListIndex().
static const U32 _TorqueThreadStatic::getListIndex () inline static
References getConstMemInstPtr(), getMemInstPtr(), getMemInstSize(), and mListIndex.
virtual void* _TorqueThreadStatic::getMemInstPtr () pure virtual
Implemented in TorqueThreadStatic< T >.
Referenced by getListIndex().
virtual const dsize_t _TorqueThreadStatic::getMemInstSize () const pure virtual
Referenced by getListIndex().
Member Data Documentation
U32 _TorqueThreadStatic::mListIndex static protected
Referenced by _TorqueThreadStaticReg::_TorqueThreadStaticReg(), and getListIndex().
Copyright © GarageGames, LLC. All Rights Reserved.