EnumConsoleBaseType Class Reference
Main Modules Class List Namespace List Online
EnumConsoleBaseType Class Reference
#include <console/dynamicTypes.h>
Public Types
typedef ConsoleBaseType Parent
Public Member Functions
virtual const char * getData (void *dptr, const EnumTable *tbl, BitSet32 flag)
virtual void setData (void *dptr, S32 argc, const char **argv, const EnumTable *tbl, BitSet32 flag)
Public Member Functions inherited from ConsoleBaseType
const char * getDocString () const
Return the documentation string for this type.
const EngineEnumTable * getEnumTable () const
Return the EnumTable for this type (only for enumeration types).
const char * getInspectorFieldType ()
Return the name of the GuiInspectorField subclass that fields of this type should use for editing.
S32 getTypeID () const
Return the unique numeric ID of this type.
const EngineTypeInfo * getTypeInfo () const
Return the type info for the engine type corresponding to this console type or NULL if there is no mapping for the console type.
StringTableEntry getTypeName () const
Return the console type name (TypeXXX).
S32 getTypeSize () const
Return the size of a single value in bytes.
void setInspectorFieldType (const char *type)
Set the name of the GuiInspectorField subclass that fields of this type should use for editing.
virtual const char * getTypeClassName ()=0
virtual void * getNativeVariable ()=0
Allocate a single value.
virtual void deleteNativeVariable (void *var)=0
Delete a single value allocated with getNativeVariable().
virtual const bool isDatablock ()
Return true if this is datablock object type.
virtual const char * prepData (const char *data, char *buffer, U32 bufferLen)
virtual StringTableEntry getTypePrefix (void) const
ConsoleBaseType * getListNext () const
Get the item that follows this item in the list.
Protected Member Functions
EnumConsoleBaseType (S32 size, S32 *idPtr, const char *typeName)
Protected Member Functions inherited from ConsoleBaseType
ConsoleBaseType (const S32 size, S32 *idPtr, const char *aTypeName)
The constructor is responsible for linking an element into the master list, registering the type ID, etc.
~ConsoleBaseType ()
Destructor is private to avoid people mucking up the list.
Additional Inherited Members
Static Public Member Functions inherited from ConsoleBaseType
static ConsoleBaseType * getType (const S32 typeID)
Call me to get a pointer to a type's info.
static ConsoleBaseType * getTypeByClassName (const char *typeName)
static ConsoleBaseType * getTypeByName (const char *typeName)
Call to get a pointer to a type's info.
static void initialize ()
Called once to initialize the console type system.
static ConsoleBaseType * getListHead ()
Get the head of the list.
Protected Attributes inherited from ConsoleBaseType
const char * mInspectorFieldType
Name of GuiInspectorField subclass to instantiate for field edit controls in inspectors.
ConsoleBaseType * mListNext
Next item in the list of all console types.
S32 mTypeID
Unique numeric type ID.
const EngineTypeInfo * mTypeInfo
Type info object for the engine type corresponding to this console type.
StringTableEntry mTypeName
Name of this console type (TypeXXX).
dsize_t mTypeSize
Size of a single data value point.
Static Protected Attributes inherited from ConsoleBaseType
static S32 smConsoleTypeCount
Total number of defined console types. This is used to generate unique IDs for each type.
static ConsoleBaseType * smListHead
We maintain a linked list of all console types; this is its head.
Member Typedef Documentation
typedef ConsoleBaseType EnumConsoleBaseType::Parent
Constructor & Destructor Documentation
EnumConsoleBaseType::EnumConsoleBaseType (S32 size, S32 * idPtr, const char * typeName) inline protected
Member Function Documentation
virtual const char* EnumConsoleBaseType::getData (void * dptr, const EnumTable * tbl, BitSet32 flag) inline virtual
Implements ConsoleBaseType.
References ConsoleBaseType::getEnumTable(), and EngineEnumTable::getNumValues().
virtual void EnumConsoleBaseType::setData (void * dptr, S32 argc, const char ** argv, const EnumTable * tbl, BitSet32 flag) inline virtual
Implements ConsoleBaseType.
References ConsoleBaseType::getEnumTable(), and EngineEnumTable::getNumValues().
Copyright © GarageGames, LLC. All Rights Reserved.