fsTiXmlNode Class Reference
Main Modules Class List Namespace List Online
fsTiXmlNode Class Reference abstract
#include <persistence/taml/fsTinyXml.h>
Public Member Functions
virtual void Print (FileStream &stream, int depth) const =0
Member Function Documentation
virtual void fsTiXmlNode::Print (FileStream & stream, int depth) const pure virtual
Implemented in fsTiXmlUnknown, fsTiXmlText, fsTiXmlComment, fsTiXmlElement, fsTiXmlDeclaration, fsTiXmlAttribute, and fsTiXmlDocument.
Referenced by fsTiXmlDeclaration::fsTiXmlDeclaration(), fsTiXmlElement::fsTiXmlElement(), fsTiXmlText::fsTiXmlText(), fsTiXmlAttribute::Print(), and fsTiXmlDeclaration::Print().
Copyright © GarageGames, LLC. All Rights Reserved.