FixedSizeVector< T, SIZE > Class Template Reference
Main Modules Class List Namespace List Online
FixedSizeVector< T, SIZE > Class Template Reference
A vector with a compile-time constant size.
#include <core/util/tFixedSizeVector.h>
Public Types
typedef const T * const_iterator
typedef T * iterator
Public Member Functions
FixedSizeVector ()
FixedSizeVector (const T &a)
FixedSizeVector (const T &a, const T &b)
FixedSizeVector (const T &a, const T &b, const T &c)
FixedSizeVector (const T &a, const T &b, const T &c, const T &d)
FixedSizeVector (const T &a, const T &b, const T &c, const T &d, const T &e)
FixedSizeVector (const T &a, const T &b, const T &c, const T &d, const T &e, const T &f)
FixedSizeVector (const T &a, const T &b, const T &c, const T &d, const T &e, const T &f, const T &g)
FixedSizeVector (const T &a, const T &b, const T &c, const T &d, const T &e, const T &f, const T &g, const T &h)
FixedSizeVector (const T &a, const T &b, const T &c, const T &d, const T &e, const T &f, const T &g, const T &h, const T &i)
FixedSizeVector (const T &a, const T &b, const T &c, const T &d, const T &e, const T &f, const T &g, const T &h, const T &i, const T &j)
FixedSizeVector (const T &a, const T &b, const T &c, const T &d, const T &e, const T &f, const T &g, const T &h, const T &i, const T &j, const T &k)
FixedSizeVector (const T &a, const T &b, const T &c, const T &d, const T &e, const T &f, const T &g, const T &h, const T &i, const T &j, const T &k, const T &l)
FixedSizeVector (const T &a, const T &b, const T &c, const T &d, const T &e, const T &f, const T &g, const T &h, const T &i, const T &j, const T &k, const T &l, const T &m)
const T * address () const
T * address ()
iterator begin ()
const_iterator begin () const
bool empty () const
iterator end ()
const_iterator end () const
const T & first () const
T & first ()
const T & last () const
T & last ()
const T & operator[] (U32 index) const
T & operator[] (U32 index)
U32 size () const
Protected Attributes
T mArray [SIZE]
Detailed Description
template<typename T, S32 SIZE>
class FixedSizeVector< T, SIZE >
A vector with a compile-time constant size.
Member Typedef Documentation
template<typename T, S32 SIZE> typedef const T* FixedSizeVector< T, SIZE >::const_iterator
template<typename T, S32 SIZE> typedef T* FixedSizeVector< T, SIZE >::iterator
Constructor & Destructor Documentation
template<typename T, S32 SIZE> FixedSizeVector< T, SIZE >::FixedSizeVector () inline
template<typename T, S32 SIZE> FixedSizeVector< T, SIZE >::FixedSizeVector (const T & a) inline
template<typename T, S32 SIZE> FixedSizeVector< T, SIZE >::FixedSizeVector (const T & a, const T & b) inline
template<typename T, S32 SIZE> FixedSizeVector< T, SIZE >::FixedSizeVector (const T & a, const T & b, const T & c) inline
template<typename T, S32 SIZE> FixedSizeVector< T, SIZE >::FixedSizeVector (const T & a, const T & b, const T & c, const T & d) inline
template<typename T, S32 SIZE> FixedSizeVector< T, SIZE >::FixedSizeVector (const T & a, const T & b, const T & c, const T & d, const T & e) inline
template<typename T, S32 SIZE> FixedSizeVector< T, SIZE >::FixedSizeVector (const T & a, const T & b, const T & c, const T & d, const T & e, const T & f) inline
template<typename T, S32 SIZE> FixedSizeVector< T, SIZE >::FixedSizeVector (const T & a, const T & b, const T & c, const T & d, const T & e, const T & f, const T & g) inline
template<typename T, S32 SIZE> FixedSizeVector< T, SIZE >::FixedSizeVector (const T & a, const T & b, const T & c, const T & d, const T & e, const T & f, const T & g, const T & h) inline
template<typename T, S32 SIZE> FixedSizeVector< T, SIZE >::FixedSizeVector (const T & a, const T & b, const T & c, const T & d, const T & e, const T & f, const T & g, const T & h, const T & i) inline
template<typename T, S32 SIZE> FixedSizeVector< T, SIZE >::FixedSizeVector (const T & a, const T & b, const T & c, const T & d, const T & e, const T & f, const T & g, const T & h, const T & i, const T & j) inline
template<typename T, S32 SIZE> FixedSizeVector< T, SIZE >::FixedSizeVector (const T & a, const T & b, const T & c, const T & d, const T & e, const T & f, const T & g, const T & h, const T & i, const T & j, const T & k) inline
template<typename T, S32 SIZE> FixedSizeVector< T, SIZE >::FixedSizeVector (const T & a, const T & b, const T & c, const T & d, const T & e, const T & f, const T & g, const T & h, const T & i, const T & j, const T & k, const T & l) inline
template<typename T, S32 SIZE> FixedSizeVector< T, SIZE >::FixedSizeVector (const T & a, const T & b, const T & c, const T & d, const T & e, const T & f, const T & g, const T & h, const T & i, const T & j, const T & k, const T & l, const T & m) inline
Member Function Documentation
template<typename T, S32 SIZE> const T* FixedSizeVector< T, SIZE >::address () const inline
Referenced by FrustumData::getEdges(), PolyhedronFixedVectorData< NUM_PLANES, NUM_POINTS, NUM_EDGES >::getEdges(), FrustumData::getPlanes(), PolyhedronFixedVectorData< NUM_PLANES, NUM_POINTS, NUM_EDGES >::getPlanes(), FrustumData::getPoints(), and PolyhedronFixedVectorData< NUM_PLANES, NUM_POINTS, NUM_EDGES >::getPoints().
template<typename T, S32 SIZE> T* FixedSizeVector< T, SIZE >::address () inline
template<typename T, S32 SIZE> iterator FixedSizeVector< T, SIZE >::begin () inline
template<typename T, S32 SIZE> const_iterator FixedSizeVector< T, SIZE >::begin () const inline
template<typename T, S32 SIZE> bool FixedSizeVector< T, SIZE >::empty () const inline
Referenced by FixedSizeVector< PlaneF, PlaneCount >::first(), and FixedSizeVector< PlaneF, PlaneCount >::last().
template<typename T, S32 SIZE> iterator FixedSizeVector< T, SIZE >::end () inline
template<typename T, S32 SIZE> const_iterator FixedSizeVector< T, SIZE >::end () const inline
template<typename T, S32 SIZE> const T& FixedSizeVector< T, SIZE >::first () const inline
template<typename T, S32 SIZE> T& FixedSizeVector< T, SIZE >::first () inline
template<typename T, S32 SIZE> const T& FixedSizeVector< T, SIZE >::last () const inline
template<typename T, S32 SIZE> T& FixedSizeVector< T, SIZE >::last () inline
template<typename T, S32 SIZE> const T& FixedSizeVector< T, SIZE >::operator[] (U32 index) const inline
template<typename T, S32 SIZE> T& FixedSizeVector< T, SIZE >::operator[] (U32 index) inline
template<typename T, S32 SIZE> U32 FixedSizeVector< T, SIZE >::size () const inline
Referenced by PolyhedronFixedVectorData< NUM_PLANES, NUM_POINTS, NUM_EDGES >::getNumEdges(), PolyhedronFixedVectorData< NUM_PLANES, NUM_POINTS, NUM_EDGES >::getNumPlanes(), PolyhedronFixedVectorData< NUM_PLANES, NUM_POINTS, NUM_EDGES >::getNumPoints(), FixedSizeVector< PlaneF, PlaneCount >::last(), and FixedSizeVector< PlaneF, PlaneCount >::operator[]().
Member Data Documentation
template<typename T, S32 SIZE> T FixedSizeVector< T, SIZE >::mArray[SIZE] protected
Referenced by FixedSizeVector< PlaneF, PlaneCount >::address().
Copyright © GarageGames, LLC. All Rights Reserved.