SettingSaveNode Class Reference
Main Modules Class List Namespace List Online
SettingSaveNode Class Reference
#include <util/settings.h>
Public Member Functions
SettingSaveNode ()
SettingSaveNode (const String &name, bool isGroup=false)
SettingSaveNode (const String &name, const String &value)
~SettingSaveNode ()
void addValue (const UTF8 *name, const UTF8 *value)
void buildDocument (SimXMLDocument *document, bool skipWrite=false)
void clear ()
String getGroup (const String &name, S32 num)
S32 getGroupCount (const String &name)
String getSettingName (const String &name)
Public Attributes
Vector< SettingSaveNode * > mGroupNodes
bool mIsGroup
String mName
Vector< SettingSaveNode * > mSettingNodes
String mValue
Constructor & Destructor Documentation
SettingSaveNode::SettingSaveNode () inline
SettingSaveNode::SettingSaveNode (const String & name, bool isGroup = false) inline
SettingSaveNode::SettingSaveNode (const String & name, const String & value) inline
References Settings::value().
SettingSaveNode::~SettingSaveNode () inline
References SimObject::getGroup(), and Settings::value().
Member Function Documentation
void SettingSaveNode::addValue (const UTF8 * name, const UTF8 * value)
void SettingSaveNode::buildDocument (SimXMLDocument * document, bool skipWrite = false)
void SettingSaveNode::clear ()
String SettingSaveNode::getGroup (const String & name, S32 num)
S32 SettingSaveNode::getGroupCount (const String & name)
String SettingSaveNode::getSettingName (const String & name)
Member Data Documentation
Vector<SettingSaveNode*> SettingSaveNode::mGroupNodes
bool SettingSaveNode::mIsGroup
String SettingSaveNode::mName
Vector<SettingSaveNode*> SettingSaveNode::mSettingNodes
String SettingSaveNode::mValue
Copyright © GarageGames, LLC. All Rights Reserved.