ThreadSafeRefCount< T, DeletePolicy > Class Template Reference
Main Modules Class List Namespace List Online
ThreadSafeRefCount< T, DeletePolicy > Class Template Reference
Baseclass for concurrently reference-counted objects.
#include <platform/threads/threadSafeRefCount.h>
Public Types
typedef void Parent
Public Member Functions
ThreadSafeRefCount ()
ThreadSafeRefCount (bool noSet)
void addRef ()
Increase the reference count on the object.
void clearLowestBit ()
U32 getRefCount () const
Get the current reference count.
bool isShared () const
void release ()
Decrease the object's reference count and delete the object, if the count drops to zero and claiming the object by the current thread succeeds.
Static Public Member Functions
static T * safeRead (T *const volatile &refPtr)
Dereference a reference-counted pointer in a multi-thread safe way.
Static Protected Member Functions
static U32 decrementAndTestAndSet (U32 &refCount)
Decrement the given reference count.
Protected Attributes
U32 mRefCount
Reference count and claim bit. Note that this increments in steps of two.
Detailed Description
template<class T, class DeletePolicy = DeleteSingle>
class ThreadSafeRefCount< T, DeletePolicy >
Baseclass for concurrently reference-counted objects.
Note
NOTE that freshly instantiated objects start out with a reference count of ZERO! Depending on how this class is used, this may not be desirable, so override this behavior in constructors if necessary.
Parameters
T the class being reference counted; this is passed to this class, so it can call the correct destructor without having to force users to have virtual methods
Member Typedef Documentation
template<class T, class DeletePolicy = DeleteSingle> typedef void ThreadSafeRefCount< T, DeletePolicy >::Parent
Constructor & Destructor Documentation
template<class T, class DeletePolicy = DeleteSingle> ThreadSafeRefCount< T, DeletePolicy >::ThreadSafeRefCount () inline
template<class T, class DeletePolicy = DeleteSingle> ThreadSafeRefCount< T, DeletePolicy >::ThreadSafeRefCount (bool noSet) inline
Member Function Documentation
template<class T , class DeletePolicy > void ThreadSafeRefCount< T, DeletePolicy >::addRef () inline
Increase the reference count on the object.
References ThreadSafeRefCount< T, DeletePolicy >::mRefCount.
Referenced by ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::operator new(), and ThreadSafeRefCount< SFXStream >::ThreadSafeRefCount().
template<class T , class DeletePolicy > void ThreadSafeRefCount< T, DeletePolicy >::clearLowestBit () inline
References ThreadSafeRefCount< T, DeletePolicy >::mRefCount.
Referenced by ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::operator new(), and ThreadSafeRefCount< SFXStream >::ThreadSafeRefCount().
template<class T , class DeletePolicy > U32 ThreadSafeRefCount< T, DeletePolicy >::decrementAndTestAndSet (U32 & refCount) static protected
Decrement the given reference count.
Return 1 if the count dropped to zero and the claim bit has been successfully set; return 0 otherwise.
Referenced by ThreadSafeRefCount< T, DeletePolicy >::release().
template<class T , class DeletePolicy > U32 ThreadSafeRefCount< T, DeletePolicy >::getRefCount () const inline
Get the current reference count.
This method is mostly meant for debugging and should not normally be used.
References ThreadSafeRefCount< T, DeletePolicy >::mRefCount.
Referenced by ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::operator new(), and ThreadSafeRefCount< SFXStream >::ThreadSafeRefCount().
template<class T , class DeletePolicy > bool ThreadSafeRefCount< T, DeletePolicy >::isShared () const inline
Returns
true if the object is referenced by more than a single reference.
References ThreadSafeRefCount< T, DeletePolicy >::mRefCount.
Referenced by ThreadSafeRefCount< SFXStream >::ThreadSafeRefCount().
template<class T , class DeletePolicy > void ThreadSafeRefCount< T, DeletePolicy >::release () inline
Decrease the object's reference count and delete the object, if the count drops to zero and claiming the object by the current thread succeeds.
References ThreadSafeRefCount< T, DeletePolicy >::decrementAndTestAndSet(), ThreadSafeRefCount< T, DeletePolicy >::mRefCount, and T.
Referenced by ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::operator new(), and ThreadSafeRefCount< SFXStream >::ThreadSafeRefCount().
template<class T, class DeletePolicy > T * ThreadSafeRefCount< T, DeletePolicy >::safeRead (T *const volatile & refPtr) static
Dereference a reference-counted pointer in a multi-thread safe way.
References T.
Referenced by ThreadSafeRef< AsyncBufferedInputStream< T, Stream > >::safeRead(), and ThreadSafeRefCount< SFXStream >::ThreadSafeRefCount().
Member Data Documentation
template<class T, class DeletePolicy = DeleteSingle> U32 ThreadSafeRefCount< T, DeletePolicy >::mRefCount protected
Reference count and claim bit. Note that this increments in steps of two.
Referenced by ThreadSafeRefCount< T, DeletePolicy >::addRef(), ThreadSafeRefCount< T, DeletePolicy >::clearLowestBit(), ThreadSafeRefCount< T, DeletePolicy >::getRefCount(), ThreadSafeRefCount< T, DeletePolicy >::isShared(), and ThreadSafeRefCount< T, DeletePolicy >::release().
Copyright © GarageGames, LLC. All Rights Reserved.