AvailableSLInterfaces Class Reference
Main Modules Class List Namespace List Online
AvailableSLInterfaces Class Reference
#include <lighting/lightingInterfaces.h>
Public Member Functions
AvailableSLInterfaces ()
void initInterfaces ()
void registerSystem (SceneLightingInterface *si)
Public Attributes
U32 mAvailableObjectTypes
SceneLightingInterfaces mAvailableSystemInterfaces
U32 mClippingMask
U32 mZoneLightSkipMask
Protected Attributes
bool mDirty
Constructor & Destructor Documentation
AvailableSLInterfaces::AvailableSLInterfaces () inline
References initInterfaces(), mAvailableSystemInterfaces, and registerSystem().
Member Function Documentation
void AvailableSLInterfaces::initInterfaces ()
Referenced by AvailableSLInterfaces().
void AvailableSLInterfaces::registerSystem (SceneLightingInterface * si)
Referenced by AvailableSLInterfaces().
Member Data Documentation
U32 AvailableSLInterfaces::mAvailableObjectTypes
SceneLightingInterfaces AvailableSLInterfaces::mAvailableSystemInterfaces
Referenced by AvailableSLInterfaces().
U32 AvailableSLInterfaces::mClippingMask
bool AvailableSLInterfaces::mDirty protected
U32 AvailableSLInterfaces::mZoneLightSkipMask
Copyright © GarageGames, LLC. All Rights Reserved.