ConnectionStringTable Class Reference
Main Modules Class List Namespace List Online
ConnectionStringTable Class Reference
Maintain a table of strings which are shared across the network.
#include <sim/connectionStringTable.h>
Public Types
enum Constants {
EntryCount = 32,
EntryBitSize = 5,
InvalidEntryId = 32
}
Public Member Functions
ConnectionStringTable (NetConnection *parent)
Initialize the connection string table.
U32 checkString (NetStringHandle &stringTableId, bool *stringOnOtherSide=NULL)
Checks if the global string ID is.
void confirmStringReceived (NetStringHandle &string, U32 index)
Has the specified string been received on the other side?
U32 getNetSendId (NetStringHandle &stringTableId)
currently valid for this connection and returns the table ID.
NetStringHandle lookupString (U32 netId)
was just sent over the net to the corresponding net ID.
void mapString (U32 netId, NetStringHandle &string)
but will assert if the string is not valid.
Demo functionality
void readDemoStartBlock (BitStream *stream)
void writeDemoStartBlock (ResizeBitStream *stream)
Detailed Description
Maintain a table of strings which are shared across the network.
This allows us to reference strings in our network streams more efficiently.
Member Enumeration Documentation
enum ConnectionStringTable::Constants
Enumerator
EntryCount
EntryBitSize
InvalidEntryId
Constructor & Destructor Documentation
ConnectionStringTable::ConnectionStringTable (NetConnection * parent)
Initialize the connection string table.
Parameters
parent Connection over which we are maintaining this string table.
Member Function Documentation
U32 ConnectionStringTable::checkString (NetStringHandle & stringTableId, bool * stringOnOtherSide = NULL)
Checks if the global string ID is.
Referenced by NetConnection::checkString(), and confirmStringReceived().
void ConnectionStringTable::confirmStringReceived (NetStringHandle & string, U32 index) inline
Has the specified string been received on the other side?
References checkString(), getNetSendId(), and mapString().
Referenced by NetConnection::confirmStringReceived().
U32 ConnectionStringTable::getNetSendId (NetStringHandle & stringTableId)
currently valid for this connection and returns the table ID.
Sends a string event to the other side if it is not active. It will fill in stringOnOtherSide. Same return value as checkString
Referenced by confirmStringReceived(), and NetConnection::getNetSendId().
NetStringHandle ConnectionStringTable::lookupString (U32 netId) inline
was just sent over the net to the corresponding net ID.
Parameters
netId looks up the string ID and returns
References readDemoStartBlock(), and writeDemoStartBlock().
Referenced by NetConnection::translateRemoteStringId().
void ConnectionStringTable::mapString (U32 netId, NetStringHandle & string)
but will assert if the string is not valid.
Maps a string that
Referenced by confirmStringReceived(), and NetConnection::mapString().
void ConnectionStringTable::readDemoStartBlock (BitStream * stream)
Referenced by lookupString().
void ConnectionStringTable::writeDemoStartBlock (ResizeBitStream * stream)
Referenced by lookupString().
Copyright © GarageGames, LLC. All Rights Reserved.