Box3F Class Reference
Main Modules Class List Namespace List Online
Box3F Class Reference
Axis-aligned bounding box (AABB).
#include <math/mBox.h>
Public Member Functions
Box3F ()
Box3F (const Point3F &in_rMin, const Point3F &in_rMax, const bool in_overrideCheck=false)
Create a box from two points.
Box3F (const F32 &xMin, const F32 &yMin, const F32 &zMin, const F32 &xMax, const F32 &yMax, const F32 &zMax)
Create a box from six extent values.
Box3F (F32 cubeSize)
bool collideLine (const Point3F &start, const Point3F &end, F32 *t, Point3F *n) const
Collide a line against the box.
bool collideLine (const Point3F &start, const Point3F &end) const
Collide a line against the box.
bool collideOrientedBox (const Point3F &radii, const MatrixF &toUs) const
Collide an oriented box against the box.
Point3F computeVertex (U32 corner) const
Return one of the corner vertices of the box.
void extend (const Point3F &p)
Extend the box to include point.
SphereF getBoundingSphere () const
Return the bounding sphere that contains this AABB.
void getCenter (Point3F *center) const
Get the center of this box.
Point3F getCenter () const
Point3F getClosestPoint (const Point3F &refPt) const
Return the closest point of the box, relative to the passed point.
F32 getDistanceToPoint (const Point3F &refPt) const
Return distance of closest point on box to refPt.
Point3F getExtents () const
Returns the max minus the min extents.
F32 getGreatestDiagonalLength () const
Get the length of the longest diagonal in the box.
Box3F getOverlap (const Box3F &otherBox) const
Return the overlap between this box and otherBox.
F32 getSqDistanceToPoint (const Point3F &refPt) const
Return the squared distance to closest point on box to refPt.
F32 getVolume () const
Return the volume of the box.
void intersect (const Box3F &in_rIntersect)
Perform an intersection operation with another box and store the results in this box.
void intersect (const Point3F &in_rIntersect)
bool isContained (const Point3F &in_rContained) const
Check to see if a point is contained in this box.
bool isContained (const Point2F &pt) const
Check if the Point2F is within the box xy extents.
bool isContained (const Box3F &in_rContained) const
Check to see if another box is contained in this box.
bool isEmpty () const
Returns true if any of the extent axes are less than or equal to zero.
bool isOverlapped (const Box3F &in_rOverlap) const
Check to see if another box overlaps this box.
bool isOverlapped (const SphereF &sphere) const
Check if the given sphere overlaps with the box.
bool isValidBox () const
Check that the min extents of the box is less than or equal to the max extents.
F32 len () const
Returns the diagonal box length.
F32 len (S32 axis) const
Returns the length of extent by axis index.
F32 len_max () const
Returns the maximum box extent.
F32 len_min () const
Returns the minimum box extent.
F32 len_x () const
Returns the length of the x extent.
F32 len_y () const
Returns the length of the y extent.
F32 len_z () const
Returns the length of the z extent.
bool operator!= (const Box3F &b) const
Inequality operator.
bool operator== (const Box3F &b) const
Equality operator.
void scale (const Point3F &amt)
Scale the box by a Point3F or F32.
void scale (F32 amt)
void set (const Point3F &in_rMin, const Point3F &in_rMax)
void set (const F32 &xMin, const F32 &yMin, const F32 &zMin, const F32 &xMax, const F32 &yMax, const F32 &zMax)
void set (const Point3F &in_Length)
Create box around origin given lengths.
void setCenter (const Point3F &center)
Recenter the box.
Static Public Member Functions
static Box3F aroundPoints (const Point3F *points, U32 numPoints)
Create an AABB that fits around the given point cloud, i.e.
Static Public Member Functions inherited from BoxBase
static void getEdgePointIndices (Edges edge, Points &outP1, Points &outP2)
Get the start and end point of the given edge.
static Points getOppositePoint (Points p)
Return the point index for the opposite corner of p.
static Points getPlanePointIndex (Planes plane, U32 i)
static Points getPointIndexFromOctant (const Point3F &p)
Return the point index for the corner point that corresponds to the octant that p points to.
Public Attributes
Point3F maxExtents
Maximum extents of box.
Point3F minExtents
Minimum extents of box.
Static Public Attributes
static const Box3F Invalid
An inverted bounds where the minimum point is positive and the maximum point is negative.
static const Box3F Max
A box that covers the entire floating point range.
static const Box3F Zero
A null box of zero size.
Additional Inherited Members
Public Types inherited from BoxBase
enum Edges {
NearLeftEdge,
NearBottomEdge,
NearRightEdge,
NearTopEdge,
FarLeftEdge,
FarTopEdge,
FarRightEdge,
FarBottomEdge,
LeftTopEdge,
LeftBottomEdge,
RightTopEdge,
RightBottomEdge,
NUM_EDGES,
InvalidEdge
}
Indices for the edges of the box.
enum PlaneMasks : U32 {
PlaneMaskLeft = (1 << LeftPlane),
PlaneMaskRight = (1 << RightPlane),
PlaneMaskTop = (1 << TopPlane),
PlaneMaskBottom = (1 << BottomPlane),
PlaneMaskNear = (1 << NearPlane),
PlaneMaskFar = (1 << FarPlane),
PlaneMaskAll = 0xFFFFFFFF
}
enum Planes {
LeftPlane,
RightPlane,
NearPlane,
FarPlane,
TopPlane,
BottomPlane,
NUM_PLANES
}
Indices for the side planes of the box.
enum Points {
NearBottomRight,
NearTopRight,
NearTopLeft,
NearBottomLeft,
FarBottomRight,
FarTopRight,
FarTopLeft,
FarBottomLeft,
NUM_POINTS,
InvalidPoint = NUM_POINTS
}
Indices of the corner points.
Detailed Description
Axis-aligned bounding box (AABB).
A helper class for working with boxes. It runs at F32 precision.
See also
Box3D
Constructor & Destructor Documentation
Box3F::Box3F () inline
References isContained(), isOverlapped(), and setCenter().
Box3F::Box3F (const Point3F & in_rMin, const Point3F & in_rMax, const bool in_overrideCheck = false) inline
Create a box from two points.
Normally, this function will compensate for mismatched min/max values. If you know your values are valid, you can set in_overrideCheck to true and skip this.
Parameters
in_rMin Minimum extents of box.
in_rMax Maximum extents of box.
in_overrideCheck Pass true to skip check of extents.
References maxExtents, minExtents, Point3F::setMax(), and Point3F::setMin().
Box3F::Box3F (const F32 & xMin, const F32 & yMin, const F32 & zMin, const F32 & xMax, const F32 & yMax, const F32 & zMax) inline
Create a box from six extent values.
No checking is performed as to the validity of these extents, unlike the other constructor.
Box3F::Box3F (F32 cubeSize) inline
Member Function Documentation
static Box3F Box3F::aroundPoints (const Point3F * points, U32 numPoints) static
Create an AABB that fits around the given point cloud, i.e.
find the minimum and maximum extents of the given point set.
Referenced by PolyhedronImpl< FrustumData >::getBounds(), and isValidBox().
bool Box3F::collideLine (const Point3F & start, const Point3F & end, F32 * t, Point3F * n) const
Collide a line against the box.
Parameters
start Start of line.
end End of line.
t Value from 0.0-1.0, indicating position along line of collision.
n Normal of collision.
Referenced by getExtents().
bool Box3F::collideLine (const Point3F & start, const Point3F & end) const
Collide a line against the box.
Returns true on collision.
bool Box3F::collideOrientedBox (const Point3F & radii, const MatrixF & toUs) const
Collide an oriented box against the box.
Returns true if "oriented" box collides with us. Assumes incoming box is centered at origin of source space.
Parameters
radii The dimension of incoming box (half x,y,z length).
toUs A transform that takes incoming box into our space.
Referenced by getExtents().
Point3F Box3F::computeVertex (U32 corner) const
Return one of the corner vertices of the box.
Referenced by isValidBox().
void Box3F::extend (const Point3F & p) inline
Extend the box to include point.
See also
Invalid
Referenced by Box3D::Box3D(), and isValidBox().
SphereF Box3F::getBoundingSphere () const
Return the bounding sphere that contains this AABB.
Referenced by isValidBox().
void Box3F::getCenter (Point3F * center) const inline
Get the center of this box.
This is the average of min and max.
References maxExtents, minExtents, Point3F::x, Point3F::y, and Point3F::z.
Referenced by ForestItem::getCenterPoint(), TerrCell::getDistanceTo(), and TerrCell::getSphereBounds().
Point3F Box3F::getCenter () const inline
References maxExtents, minExtents, Point3F::x, Point3F::y, and Point3F::z.
Referenced by Box3D::Box3D(), and isEmpty().
Point3F Box3F::getClosestPoint (const Point3F & refPt) const inline
Return the closest point of the box, relative to the passed point.
References maxExtents, minExtents, Point3F::x, Point3F::y, and Point3F::z.
Referenced by isValidBox().
F32 Box3F::getDistanceToPoint (const Point3F & refPt) const inline
Return distance of closest point on box to refPt.
References getSqDistanceToPoint().
Referenced by isValidBox().
Point3F Box3F::getExtents () const inline
Returns the max minus the min extents.
References collideLine(), collideOrientedBox(), and minExtents.
Referenced by ForestItem::getSize().
F32 Box3F::getGreatestDiagonalLength () const
Get the length of the longest diagonal in the box.
Referenced by isValidBox().
Box3F Box3F::getOverlap (const Box3F & otherBox) const inline
Return the overlap between this box and otherBox.
References maxExtents, and minExtents.
Referenced by isEmpty().
F32 Box3F::getSqDistanceToPoint (const Point3F & refPt) const inline
Return the squared distance to closest point on box to refPt.
References maxExtents, and minExtents.
Referenced by getDistanceToPoint(), and isValidBox().
F32 Box3F::getVolume () const inline
Return the volume of the box.
References maxExtents, minExtents, Point3F::x, Point3F::y, and Point3F::z.
Referenced by isEmpty().
void Box3F::intersect (const Box3F & in_rIntersect) inline
Perform an intersection operation with another box and store the results in this box.
References maxExtents, minExtents, Point3F::setMax(), and Point3F::setMin().
Referenced by SceneTraversalState::addToTraversedArea(), Box3D::Box3D(), and isEmpty().
void Box3F::intersect (const Point3F & in_rIntersect) inline
References maxExtents, minExtents, Point3F::setMax(), and Point3F::setMin().
bool Box3F::isContained (const Point3F & in_rContained) const inline
Check to see if a point is contained in this box.
References maxExtents, minExtents, Point3F::x, Point3F::y, and Point3F::z.
Referenced by Box3D::Box3D(), Box3F(), and PolyhedronBoxIntersector< Polyhedron >::test().
bool Box3F::isContained (const Point2F & pt) const inline
Check if the Point2F is within the box xy extents.
References maxExtents, minExtents, Point3F::x, Point2F::x, Point3F::y, and Point2F::y.
bool Box3F::isContained (const Box3F & in_rContained) const inline
Check to see if another box is contained in this box.
References maxExtents, minExtents, Point3F::x, Point3F::y, and Point3F::z.
bool Box3F::isEmpty () const inline
Returns true if any of the extent axes are less than or equal to zero.
References getCenter(), getOverlap(), getVolume(), intersect(), len_x(), len_y(), and len_z().
bool Box3F::isOverlapped (const Box3F & in_rOverlap) const inline
Check to see if another box overlaps this box.
References maxExtents, minExtents, Point3F::x, Point3F::y, and Point3F::z.
Referenced by Box3D::Box3D(), and Box3F().
bool Box3F::isOverlapped (const SphereF & sphere) const
Check if the given sphere overlaps with the box.
bool Box3F::isValidBox () const inline
Check that the min extents of the box is less than or equal to the max extents.
References aroundPoints(), computeVertex(), extend(), getBoundingSphere(), getClosestPoint(), getDistanceToPoint(), getGreatestDiagonalLength(), getSqDistanceToPoint(), operator!=(), operator==(), scale(), Point3F::x, Point3F::y, and Point3F::z.
F32 Box3F::len () const inline
Returns the diagonal box length.
F32 Box3F::len (S32 axis) const inline
Returns the length of extent by axis index.
Parameters
axis The axis index of 0, 1, or 2.
F32 Box3F::len_max () const inline
Returns the maximum box extent.
References len_x(), len_y(), and len_z().
F32 Box3F::len_min () const inline
Returns the minimum box extent.
References len_x(), len_y(), and len_z().
F32 Box3F::len_x () const inline
Returns the length of the x extent.
References Point3F::x.
Referenced by Box3D::Box3D(), PolyhedronData::buildBoxData(), isEmpty(), len_max(), len_min(), and setCenter().
F32 Box3F::len_y () const inline
Returns the length of the y extent.
References Point3F::y.
Referenced by Box3D::Box3D(), PolyhedronData::buildBoxData(), isEmpty(), len_max(), len_min(), and setCenter().
F32 Box3F::len_z () const inline
Returns the length of the z extent.
References Point3F::z.
Referenced by Box3D::Box3D(), PolyhedronData::buildBoxData(), isEmpty(), len_max(), len_min(), and setCenter().
bool Box3F::operator!= (const Box3F & b) const inline
Inequality operator.
References Point3F::equal(), maxExtents, and minExtents.
Referenced by isValidBox().
bool Box3F::operator== (const Box3F & b) const inline
Equality operator.
References Point3F::equal(), maxExtents, and minExtents.
Referenced by isValidBox().
void Box3F::scale (const Point3F & amt) inline
Scale the box by a Point3F or F32.
References maxExtents, and minExtents.
Referenced by ForestItem::getSize(), and isValidBox().
void Box3F::scale (F32 amt) inline
References maxExtents, and minExtents.
void Box3F::set (const Point3F & in_rMin, const Point3F & in_rMax) inline
References maxExtents, minExtents, and Point3F::set().
void Box3F::set (const F32 & xMin, const F32 & yMin, const F32 & zMin, const F32 & xMax, const F32 & yMax, const F32 & zMax) inline
References maxExtents, minExtents, and Point3F::set().
void Box3F::set (const Point3F & in_Length) inline
Create box around origin given lengths.
References maxExtents, minExtents, Point3F::set(), Point3F::x, Point3F::y, and Point3F::z.
void Box3F::setCenter (const Point3F & center) inline
Recenter the box.
References len_x(), len_y(), len_z(), maxExtents, minExtents, Point3F::set(), Point3F::x, Point3F::y, and Point3F::z.
Referenced by Box3F().
Member Data Documentation
const Box3F Box3F::Invalid static
An inverted bounds where the minimum point is positive and the maximum point is negative.
Should be used with extend() to construct a minimum volume box.
See also
extend
Referenced by NavMesh::getNavMesh(), ForestItemData::getObjBox(), and BtPlayer::getWorldBounds().
const Box3F Box3F::Max static
A box that covers the entire floating point range.
Point3F Box3F::maxExtents
Maximum extents of box.
Referenced by Box3F(), SceneObject::getBoxCenter(), getCenter(), getClosestPoint(), getOverlap(), GroundPlane::getPlaneBox(), getSqDistanceToPoint(), getVolume(), intersect(), isContained(), isOverlapped(), MatrixF::mul(), operator!=(), operator==(), scale(), set(), setCenter(), PolyhedronBoxIntersector< Polyhedron >::test(), PlaneSet< T >::testPlanes(), and PlaneF::whichSide().
Point3F Box3F::minExtents
Minimum extents of box.
Referenced by Box3F(), PolyhedronData::buildBoxData(), SceneObject::getBoxCenter(), getCenter(), getClosestPoint(), getExtents(), getOverlap(), GroundPlane::getPlaneBox(), getSqDistanceToPoint(), getVolume(), intersect(), isContained(), isOverlapped(), MatrixF::mul(), operator!=(), operator==(), scale(), set(), setCenter(), PolyhedronBoxIntersector< Polyhedron >::test(), PlaneSet< T >::testPlanes(), and PlaneF::whichSide().
const Box3F Box3F::Zero static
A null box of zero size.
Referenced by TSForestItemData::getObjBox().
Copyright © GarageGames, LLC. All Rights Reserved.