RuntimeClassRep< T > Class Template Reference
Main Modules Class List Namespace List Online
RuntimeClassRep< T > Class Template Reference
This class is to allow new types to be added, at run-time, to Torque.
#include <console/runtimeClassRep.h>
Public Member Functions
RuntimeClassRep (const char *name, const char *conTypeName, S32 *conTypeIdPtr, S32 netClassGroupMask, S32 netClassType, S32 netEventDir, AbstractClassRep *parent)
void consoleRegister ()
Register this class with the Torque console.
void consoleUnRegister ()
Unregister this class with the Torque console.
ConsoleObject * create () const
Wrap constructor.
virtual AbstractClassRep * getContainerChildClass (const bool recurse)
virtual WriteCustomTamlSchema getCustomTamlSchema (void)
void init () const
Perform class specific initialization tasks.
Console Type Interface
virtual void setData (void *dptr, S32 argc, const char **argv, const EnumTable *tbl, BitSet32 flag)
virtual const char * getData (void *dptr, const EnumTable *tbl, BitSet32 flag)
virtual const char * getTypeClassName ()
virtual const bool isDatablock ()
Return true if this is datablock object type.
Public Member Functions inherited from AbstractClassRep
bool isRenderEnabled () const
bool isSelectionEnabled () const
AbstractClassRep (S32 *conIdPtr, const char *typeName)
S32 getClassId (U32 netClassGroup) const
AbstractClassRep * getCommonParent (const AbstractClassRep *otherClass) const
StringTableEntry getClassName () const
Return the name of this class.
Namespace * getNameSpace () const
Return the namespace that contains the methods of this class.
AbstractClassRep * getParentClass () const
Return the AbstractClassRep of the class that this class is derived from.
S32 getSizeof () const
Return the size of instances of this class in bytes.
AbstractClassRep * getNextClass () const
Return the next class in the global class list link chain.
bool isSubclassOf (const AbstractClassRep *klass) const
Helper class to see if we are a given class, or a subclass thereof by comparing AbstractClassRep pointers.
bool isSubclassOf (const char *klass) const
Helper class to see if we are a given class, or a subclass thereof by comparing the class name strings.
bool isClass (const AbstractClassRep *acr) const
AbstractClassRep * findFieldRoot (StringTableEntry fieldName)
const char * getCategory () const
Return the space separated category path for the class.
const char * getDescription () const
Return a short description string suitable for displaying in tooltips.
const Field * findField (StringTableEntry fieldName) const
virtual void * getNativeVariable ()
Allocate a single value.
virtual void deleteNativeVariable (void *var)
Delete a single value allocated with getNativeVariable().
Public Member Functions inherited from ConsoleBaseType
const char * getDocString () const
Return the documentation string for this type.
const EngineEnumTable * getEnumTable () const
Return the EnumTable for this type (only for enumeration types).
const char * getInspectorFieldType ()
Return the name of the GuiInspectorField subclass that fields of this type should use for editing.
S32 getTypeID () const
Return the unique numeric ID of this type.
const EngineTypeInfo * getTypeInfo () const
Return the type info for the engine type corresponding to this console type or NULL if there is no mapping for the console type.
StringTableEntry getTypeName () const
Return the console type name (TypeXXX).
S32 getTypeSize () const
Return the size of a single value in bytes.
void setInspectorFieldType (const char *type)
Set the name of the GuiInspectorField subclass that fields of this type should use for editing.
virtual const char * prepData (const char *data, char *buffer, U32 bufferLen)
virtual StringTableEntry getTypePrefix (void) const
ConsoleBaseType * getListNext () const
Get the item that follows this item in the list.
Static Public Member Functions
static const bool isRegistered ()
Returns true if this class type is registered with the console system.
Static Public Member Functions inherited from AbstractClassRep
static U32 getClassCRC (U32 netClassGroup)
static AbstractClassRep * getClassList ()
Return the head of the global class list.
static void registerClassRep (AbstractClassRep *)
static AbstractClassRep * findClassRep (const char *in_pClassName)
static AbstractClassRep * findClassRep (U32 groupId, U32 typeId, U32 classId)
static void removeClassRep (AbstractClassRep *)
static void initialize ()
static void shutdown ()
Static Public Member Functions inherited from ConsoleBaseType
static ConsoleBaseType * getType (const S32 typeID)
Call me to get a pointer to a type's info.
static ConsoleBaseType * getTypeByClassName (const char *typeName)
static ConsoleBaseType * getTypeByName (const char *typeName)
Call to get a pointer to a type's info.
static void initialize ()
Called once to initialize the console type system.
static ConsoleBaseType * getListHead ()
Get the head of the list.
Static Protected Attributes
static bool smConRegistered = false
This variable will be set to true if this class-rep is currently registered.
Static Protected Attributes inherited from AbstractClassRep
static AbstractClassRep ** classTable [NetClassGroupsCount][NetClassTypesCount]
static AbstractClassRep * classLinkList
static U32 classCRC [NetClassGroupsCount]
static bool initialized
Static Protected Attributes inherited from ConsoleBaseType
static S32 smConsoleTypeCount
Total number of defined console types. This is used to generate unique IDs for each type.
static ConsoleBaseType * smListHead
We maintain a linked list of all console types; this is its head.
Additional Inherited Members
Public Types inherited from AbstractClassRep
typedef ConsoleBaseType Parent
typedef void(* WriteCustomTamlSchema) (const AbstractClassRep *pClassRep, TiXmlElement *pParentElement)
Allows the writing of a custom TAML schema.
enum ACRFieldTypes : U32 {
ARCFirstCustomField = 0xFFFFFFFB,
StartArrayFieldType = 0xFFFFFFFB,
EndArrayFieldType = 0xFFFFFFFC,
StartGroupFieldType = 0xFFFFFFFD,
EndGroupFieldType = 0xFFFFFFFE,
DeprecatedFieldType = 0xFFFFFFFF
}
These are special field type values used to mark groups and arrays in the field list.
enum FieldFlags {
FIELD_HideInInspectors = BIT(0),
FIELD_ComponentInspectors = BIT(1)
}
typedef bool(* SetDataNotify) (void *obj, const char *array, const char *data)
This is a function pointer typedef to support get/set callbacks for fields.
typedef const char *(* GetDataNotify) (void *obj, const char *data)
typedef bool(* WriteDataNotify) (void *obj, StringTableEntry pFieldName)
This is a function pointer typedef to support optional writing for fields.
typedef Vector< Field > FieldList
Public Attributes inherited from AbstractClassRep
bool mIsRenderEnabled
bool mIsSelectionEnabled
S32 mClassGroupMask
Mask indicating in which NetGroups this object belongs.
S32 mClassType
Stores the NetClass of this class.
S32 mNetEventDir
Stores the NetDirection of this class.
S32 mClassId [NetClassGroupsCount]
Stores the IDs assigned to this class for each group.
S32 mClassSizeof
Size of instances in bytes.
FieldList mFieldList
bool mDynamicGroupExpand
Static Public Attributes inherited from AbstractClassRep
static U32 NetClassCount [NetClassGroupsCount][NetClassTypesCount]
static U32 NetClassBitSize [NetClassGroupsCount][NetClassTypesCount]
Protected Member Functions inherited from AbstractClassRep
virtual void init ()
Protected Member Functions inherited from ConsoleBaseType
ConsoleBaseType (const S32 size, S32 *idPtr, const char *aTypeName)
The constructor is responsible for linking an element into the master list, registering the type ID, etc.
~ConsoleBaseType ()
Destructor is private to avoid people mucking up the list.
Static Protected Member Functions inherited from AbstractClassRep
static ConsoleObject * create (const char *in_pClassName)
static ConsoleObject * create (const U32 groupId, const U32 typeId, const U32 in_classId)
Protected Attributes inherited from AbstractClassRep
const char * mClassName
AbstractClassRep * nextClass
AbstractClassRep * parentClass
Namespace * mNamespace
const char * mCategory
const char * mDescription
Protected Attributes inherited from ConsoleBaseType
const char * mInspectorFieldType
Name of GuiInspectorField subclass to instantiate for field edit controls in inspectors.
ConsoleBaseType * mListNext
Next item in the list of all console types.
S32 mTypeID
Unique numeric type ID.
const EngineTypeInfo * mTypeInfo
Type info object for the engine type corresponding to this console type.
StringTableEntry mTypeName
Name of this console type (TypeXXX).
dsize_t mTypeSize
Size of a single data value point.
Detailed Description
template<class T>
class RuntimeClassRep< T >
This class is to allow new types to be added, at run-time, to Torque.
This is primarily for dynamic libraries, plugins etc.
The idea is the same, one instance per type which is getting registered however it doesn't get added to the dictionary until it is told to add itself. It can be removed, as well, though no safe-execution assurances are made by this class. If an object type is removed behavior of existing console objects of that type is undefined. (aka bad stuff will probably happen but I don't know exactly what)
Constructor & Destructor Documentation
template<class T > RuntimeClassRep< T >::RuntimeClassRep (const char * name, const char * conTypeName, S32 * conTypeIdPtr, S32 netClassGroupMask, S32 netClassType, S32 netEventDir, AbstractClassRep * parent) inline
References AbstractClassRep::mClassGroupMask, AbstractClassRep::mClassId, AbstractClassRep::mClassName, AbstractClassRep::mClassType, AbstractClassRep::mNetEventDir, ConsoleBaseType::mTypeInfo, and AbstractClassRep::parentClass.
Member Function Documentation
template<class T > void RuntimeClassRep< T >::consoleRegister () inline
Register this class with the Torque console.
References Vector< T >::clear(), AbstractClassRep::getClassName(), RuntimeClassRep< T >::init(), Con::lookupNamespace(), Namespace::mClassRep, AbstractClassRep::mFieldList, AbstractClassRep::mNamespace, AbstractClassRep::registerClassRep(), Vector< T >::setSize(), and Vector< T >::size().
template<class T > void RuntimeClassRep< T >::consoleUnRegister () inline
Unregister this class with the Torque console.
References AbstractClassRep::removeClassRep().
template<class T > ConsoleObject* RuntimeClassRep< T >::create () const inline virtual
Wrap constructor.
Implements AbstractClassRep.
References T.
template<class T > virtual AbstractClassRep* RuntimeClassRep< T >::getContainerChildClass (const bool recurse) inline virtual
Implements AbstractClassRep.
References AbstractClassRep::getContainerChildClass().
template<class T > virtual WriteCustomTamlSchema RuntimeClassRep< T >::getCustomTamlSchema (void) inline virtual
Implements AbstractClassRep.
template<class T > virtual const char* RuntimeClassRep< T >::getData (void * dptr, const EnumTable * tbl, BitSet32 flag) inline virtual
Implements ConsoleBaseType.
References Con::getReturnBuffer(), and T.
template<class T > virtual const char* RuntimeClassRep< T >::getTypeClassName () inline virtual
Implements ConsoleBaseType.
References AbstractClassRep::mClassName.
template<class T > void RuntimeClassRep< T >::init () const inline
Perform class specific initialization tasks.
Link namespaces, call initPersistFields() and consoleInit().
References Con::classLinkNamespaces(), and AbstractClassRep::getNameSpace().
Referenced by RuntimeClassRep< T >::consoleRegister().
template<class T > virtual const bool RuntimeClassRep< T >::isDatablock () inline virtual
Return true if this is datablock object type.
Reimplemented from ConsoleBaseType.
template<class T > static const bool RuntimeClassRep< T >::isRegistered () inline static
Returns true if this class type is registered with the console system.
References RuntimeClassRep< T >::smConRegistered.
template<class T > virtual void RuntimeClassRep< T >::setData (void * dptr, S32 argc, const char ** argv, const EnumTable * tbl, BitSet32 flag) inline virtual
Implements ConsoleBaseType.
References Con::errorf(), and T.
Member Data Documentation
template<class T > bool RuntimeClassRep< T >::smConRegistered = false static protected
This variable will be set to true if this class-rep is currently registered.
Referenced by RuntimeClassRep< T >::isRegistered().
Copyright © GarageGames, LLC. All Rights Reserved.