ColladaAppMesh Class Reference
Main Modules Class List Namespace List Online
ColladaAppMesh Class Reference
#include <ts/collada/colladaAppMesh.h>
Public Member Functions
ColladaAppMesh (const domInstance_geometry *instance, ColladaAppNode *node)
ColladaAppMesh (const domInstance_controller *instance, ColladaAppNode *node)
~ColladaAppMesh ()
bool animatesFrame (const AppSequence *appSeq)
Check if the mesh is animated.
bool animatesMatFrame (const AppSequence *appSeq)
Check if the material used by this mesh is animated.
bool animatesVis (const AppSequence *appSeq)
Check if the mesh visibility is animated.
bool getBool (const char *propName, bool &defaultVal)
Get a boolean property value.
bool getFloat (const char *propName, F32 &defaultVal)
Get a floating point property value.
bool getInt (const char *propName, S32 &defaultVal)
Get an integer property value.
MatrixF getMeshTransform (F32 time)
Get the transform of this mesh at a certain time.
const char * getName (bool allowFixed=true)
Get the name of this mesh.
F32 getVisValue (F32 time)
Get the visibility of this mesh at a certain time.
bool isSkin ()
Return true if this mesh is a skin.
void lockMesh (F32 time, const MatrixF &objOffset)
Generate the vertex, normal and triangle data for the mesh.
void lookupSkinData ()
Get the skin data: bones, vertex weights etc.
Public Member Functions inherited from AppMesh
AppMesh ()
virtual ~AppMesh ()
void computeBounds (Box3F &bounds)
void computeNormals ()
TSMesh * constructTSMesh ()
virtual bool isBillboard ()
virtual bool isBillboardZAxis ()
Static Public Member Functions
static void fixDetailSize (bool fixed, S32 size=2)
Protected Member Functions
S32 addMaterial (const char *symbol)
bool checkGeometryType (const daeElement *element)
const domMorph * getMorph ()
Get the morph controller for this mesh (if any)
void getMorphVertexData (const domMorph *morph, F32 time, const MatrixF &objOffset, Vector< Point3F > &points, Vector< Point3F > &norms, Vector< ColorI > &colors, Vector< Point2F > &uvs, Vector< Point2F > &uv2s)
void getPrimitives (const domGeometry *geometry)
void getVertexData (const domGeometry *geometry, F32 time, const MatrixF &objOffset, Vector< Point3F > &points, Vector< Point3F > &norms, Vector< ColorI > &colors, Vector< Point2F > &uvs, Vector< Point2F > &uv2s, bool appendValues)
Protected Attributes
class ColladaAppNode * appNode
Pointer to the node that owns this mesh.
Map< StringTableEntry, U32 > boundMaterials
Local map of symbols to materials.
ColladaExtension_geometry * geomExt
geometry extension
const domInstance_controller * instanceCtrl
const domInstance_geometry * instanceGeom
Vector< VertTuple > vertTuples
Static Protected Attributes
static S32 fixedSize
The fixed detail size value for all geometry.
static bool fixedSizeEnabled
Set to true to fix the detail size to a particular value for all geometry.
Additional Inherited Members
Public Attributes inherited from AppMesh
Vector< S32 > boneIndex
Vector< AppNode * > bones
Vector< ColorI > colors
S32 detailSize
U32 flags
Vector< U32 > indices
Vector< Point3F > initialNorms
Vector< MatrixF > initialTransforms
Vector< Point3F > initialVerts
Vector< S32 > nodeIndex
Vector< Point3F > normals
S32 numFrames
S32 numMatFrames
MatrixF objectOffset
Vector< Point3F > points
Vector< TSDrawPrimitive > primitives
Vector< Point2F > uv2s
Vector< Point2F > uvs
Vector< S32 > vertexIndex
U32 vertsPerFrame
Vector< F32 > weight
Static Public Attributes inherited from AppMesh
static Vector< AppMaterial * > appMaterials
Constructor & Destructor Documentation
ColladaAppMesh::ColladaAppMesh (const domInstance_geometry * instance, ColladaAppNode * node)
ColladaAppMesh::ColladaAppMesh (const domInstance_controller * instance, ColladaAppNode * node)
ColladaAppMesh::~ColladaAppMesh () inline
Member Function Documentation
S32 ColladaAppMesh::addMaterial (const char * symbol) protected
bool ColladaAppMesh::animatesFrame (const AppSequence * appSeq) virtual
Check if the mesh is animated.
Parameters
appSeq Start/end time to check
Returns
True if the mesh is animated, false if not
Reimplemented from AppMesh.
bool ColladaAppMesh::animatesMatFrame (const AppSequence * appSeq) virtual
Check if the material used by this mesh is animated.
Parameters
appSeq Start/end time to check
Returns
True if the material is animated, false if not
Reimplemented from AppMesh.
bool ColladaAppMesh::animatesVis (const AppSequence * appSeq) virtual
Check if the mesh visibility is animated.
Parameters
appSeq Start/end time to check
Returns
True if the mesh visibility is animated, false if not
Reimplemented from AppMesh.
bool ColladaAppMesh::checkGeometryType (const daeElement * element) protected
static void ColladaAppMesh::fixDetailSize (bool fixed, S32 size = 2) inline static
References ColladaAppNode::getName().
bool ColladaAppMesh::getBool (const char * propName, bool & defaultVal) inline virtual
Get a boolean property value.
Parameters
propName Name of the property to get
defaultVal Reference to variable to hold return value
Returns
True if a value was set, false if not
Implements AppMesh.
References ColladaAppNode::getBool().
bool ColladaAppMesh::getFloat (const char * propName, F32 & defaultVal) inline virtual
Get a floating point property value.
Parameters
propName Name of the property to get
defaultVal Reference to variable to hold return value
Returns
True if a value was set, false if not
Implements AppMesh.
References ColladaAppNode::getFloat().
bool ColladaAppMesh::getInt (const char * propName, S32 & defaultVal) inline virtual
Get an integer property value.
Parameters
propName Name of the property to get
defaultVal Reference to variable to hold return value
Returns
True if a value was set, false if not
Implements AppMesh.
References ColladaAppNode::getInt().
MatrixF ColladaAppMesh::getMeshTransform (F32 time) virtual
Get the transform of this mesh at a certain time.
Parameters
time Time at which to get the transform
Returns
The mesh transform at the specified time
Implements AppMesh.
const domMorph* ColladaAppMesh::getMorph () inline protected
Get the morph controller for this mesh (if any)
References ColladaAppNode::ColladaAppMesh.
void ColladaAppMesh::getMorphVertexData (const domMorph * morph, F32 time, const MatrixF & objOffset, Vector< Point3F > & points, Vector< Point3F > & norms, Vector< ColorI > & colors, Vector< Point2F > & uvs, Vector< Point2F > & uv2s) protected
const char* ColladaAppMesh::getName (bool allowFixed = true) virtual
Get the name of this mesh.
Returns
A string containing the name of this mesh
Implements AppMesh.
void ColladaAppMesh::getPrimitives (const domGeometry * geometry) protected
void ColladaAppMesh::getVertexData (const domGeometry * geometry, F32 time, const MatrixF & objOffset, Vector< Point3F > & points, Vector< Point3F > & norms, Vector< ColorI > & colors, Vector< Point2F > & uvs, Vector< Point2F > & uv2s, bool appendValues) protected
F32 ColladaAppMesh::getVisValue (F32 time) virtual
Get the visibility of this mesh at a certain time.
Parameters
time Time at which to get visibility info
Returns
Visibility from 0 (invisible) to 1 (opaque)
Implements AppMesh.
bool ColladaAppMesh::isSkin () inline virtual
Return true if this mesh is a skin.
Reimplemented from AppMesh.
void ColladaAppMesh::lockMesh (F32 time, const MatrixF & objOffset) virtual
Generate the vertex, normal and triangle data for the mesh.
Parameters
time Time at which to generate the mesh data
objOffset Transform to apply to the generated data (bounds transform)
Reimplemented from AppMesh.
void ColladaAppMesh::lookupSkinData () virtual
Get the skin data: bones, vertex weights etc.
Implements AppMesh.
Member Data Documentation
class ColladaAppNode* ColladaAppMesh::appNode protected
Pointer to the node that owns this mesh.
Referenced by ColladaAppNode::isEqual().
Map<StringTableEntry,U32> ColladaAppMesh::boundMaterials protected
Local map of symbols to materials.
S32 ColladaAppMesh::fixedSize static protected
The fixed detail size value for all geometry.
bool ColladaAppMesh::fixedSizeEnabled static protected
Set to true to fix the detail size to a particular value for all geometry.
ColladaExtension_geometry* ColladaAppMesh::geomExt protected
geometry extension
const domInstance_controller* ColladaAppMesh::instanceCtrl protected
const domInstance_geometry* ColladaAppMesh::instanceGeom protected
Vector<VertTuple> ColladaAppMesh::vertTuples protected
Copyright © GarageGames, LLC. All Rights Reserved.