Zip::ZipTempStream Class Reference
Main Modules Class List Namespace List Online
Zip::ZipTempStream Class Reference
Zip Code » Zip Code Internals
#include <core/util/zip/zipTempStream.h>
Public Member Functions
ZipTempStream ()
ZipTempStream (CentralDir *cd)
virtual ~ZipTempStream ()
virtual void close ()
CentralDir * getCentralDir ()
virtual bool open (String filename, Torque::FS::File::AccessMode mode)
virtual bool open ()
Open a temporary file in ReadWrite mode. The file will be deleted when the stream is closed.
bool rewind ()
Seek back to the start of the file.
void setCentralDir (CentralDir *cd)
void setDeleteOnClose (bool del)
virtual bool setPosition (const U32 i_newPosition)
Disallow setPosition()
Public Member Functions inherited from FileStream
FileStream ()
virtual ~FileStream ()
FileStream * clone () const
Create an exact replica of this stream.
bool flush ()
virtual U32 getPosition () const
Gets the position in the stream.
virtual U32 getStreamSize ()
Gets the size of the stream.
virtual bool hasCapability (const Capability i_cap) const
Checks to see if this stream has the capability of a given function.
virtual bool open (const String &inFileName, Torque::FS::File::AccessMode inMode)
Public Member Functions inherited from Stream
Stream ()
virtual ~Stream ()
bool copyFrom (Stream *other)
Copy the contents of another stream into this one.
Stream::StreamStatus getStatus () const
Gets the status of the stream.
bool Put (char character)
void read (String *str)
bool read (ColorI *)
Read an integral color from the stream.
bool read (ColorF *)
Read a floating point color from the stream.
bool read (NetAddress *)
Read a network address from the stream.
bool read (NetSocket *)
Read a network socket from the stream.
bool read (RawData *)
Read some raw data from the stream.
bool read (Torque::ByteBuffer *)
Read some raw data from the stream.
bool read (const U32 in_numBytes, void *out_pBuffer)
bool read (bool *out_pRead)
void readLine (U8 *buffer, U32 bufferSize)
Reads a line from the stream.
void readLongString (U32 maxStringLen, char *stringBuf)
Reads a string that could potentially be more than 255 characters long.
virtual void readString (char stringBuf[256])
Reads a string of maximum 255 characters long.
const char * readSTString (bool casesens=false)
Reads a string and inserts it into the StringTable.
void write (const String &str)
bool write (const ColorI &)
Write an integral color to the stream.
bool write (const ColorF &)
Write a floating point color to the stream.
bool write (const NetAddress &)
Write a network address to the stream.
bool write (const NetSocket &)
Write a network socket to the stream.
bool write (const RawData &)
Write some raw data onto the stream.
bool write (const Torque::ByteBuffer &)
Write some raw data onto the stream.
bool write (const U32 in_numBytes, const void *in_pBuffer)
bool write (const bool &in_rWrite)
bool writeFormattedBuffer (const char *format,...)
Writes a formatted buffer to the stream.
void writeLine (const U8 *buffer)
writes a line to the stream
void writeLongString (U32 maxStringLen, const char *string)
Writes a string to the stream.
virtual void writeString (const char *stringBuf, S32 maxLen=255)
Writes a string to the stream.
bool writeStringBuffer (const char *buffer)
Writes a NULL terminated string buffer.
void writeTabs (U32 count)
Write a number of tabs to this stream.
void writeText (const char *text)
Write raw text to the stream.
Protected Attributes
CentralDir * mCD
bool mDeleteOnClose
String mFilename
Protected Attributes inherited from FileStream
U32 mStreamCaps
Additional Inherited Members
Public Types inherited from FileStream
enum : U32 {
BUFFER_SIZE = 8 * 1024,
BUFFER_INVALID = 0xffffffff
}
Public Types inherited from Stream
enum Capability {
StreamWrite = BIT(0),
StreamRead = BIT(1),
StreamPosition = BIT(2)
}
enum StreamStatus {
Ok = 0,
IOError,
EOS,
IllegalCall,
Closed,
UnknownError
}
Status constants for the stream.
Static Public Member Functions inherited from FileStream
static FileStream * createAndOpen (const String &inFileName, Torque::FS::File::AccessMode inMode)
Static Public Member Functions inherited from Stream
static const char * getStatusString (const StreamStatus in_status)
Gets a printable string form of the status.
Protected Member Functions inherited from FileStream
virtual bool _read (const U32 i_numBytes, void *o_pBuffer)
virtual bool _write (const U32 i_numBytes, const void *i_pBuffer)
void clearBuffer ()
bool fillBuffer (const U32 i_startPosition)
void init ()
void setStatus ()
Protected Member Functions inherited from Stream
virtual void _read (String *str)
virtual void _write (const String &str)
void setStatus (const StreamStatus in_newStatus)
Static Protected Member Functions inherited from FileStream
static void calcBlockBounds (const U32 i_position, U32 *o_blockHead, U32 *o_blockTail)
static void calcBlockHead (const U32 i_position, U32 *o_blockHead)
Constructor & Destructor Documentation
Zip::ZipTempStream::ZipTempStream () inline
Zip::ZipTempStream::ZipTempStream (CentralDir * cd) inline
virtual Zip::ZipTempStream::~ZipTempStream () inline virtual
References close().
Member Function Documentation
virtual void Zip::ZipTempStream::close () inline virtual
Reimplemented from FileStream.
References FileStream::close(), and Torque::FS::Remove().
Referenced by ~ZipTempStream().
CentralDir* Zip::ZipTempStream::getCentralDir () inline
References mCD.
virtual bool Zip::ZipTempStream::open (String filename, Torque::FS::File::AccessMode mode) virtual
virtual bool Zip::ZipTempStream::open () inline virtual
Open a temporary file in ReadWrite mode. The file will be deleted when the stream is closed.
References Torque::FS::File::ReadWrite.
Referenced by setDeleteOnClose().
bool Zip::ZipTempStream::rewind () inline
Seek back to the start of the file.
This is used internally by the zip code and should never be called whilst filters are attached (e.g. when reading or writing in a zip file)
References FileStream::mStreamCaps, FileStream::setPosition(), and Stream::StreamPosition.
void Zip::ZipTempStream::setCentralDir (CentralDir * cd) inline
void Zip::ZipTempStream::setDeleteOnClose (bool del) inline
References open().
virtual bool Zip::ZipTempStream::setPosition (const U32 i_newPosition) inline virtual
Disallow setPosition()
Reimplemented from FileStream.
Member Data Documentation
CentralDir* Zip::ZipTempStream::mCD protected
Referenced by getCentralDir().
bool Zip::ZipTempStream::mDeleteOnClose protected
String Zip::ZipTempStream::mFilename protected
Copyright © GarageGames, LLC. All Rights Reserved.