ForestWindAccumulator Class Reference
Main Modules Class List Namespace List Online
ForestWindAccumulator Class Reference
This simple class holds the state of the accumulated wind effect for a single tree.
#include <forest/forestWindAccumulator.h>
Classes
struct VerletParticle
Public Member Functions
ForestWindAccumulator (const TreePlacementInfo &info)
~ForestWindAccumulator ()
void applyImpulse (const VectorF &impulse)
VectorF getDirection () const
Point3F getPosition () const
F32 getStrength () const
void presimulate (const VectorF &windVector, U32 ticks)
void setDirection (const VectorF &dir)
void setPosition (const Point3F &pos)
void setStrength (F32 strength)
void updateWind (const VectorF &windVector, F32 timeDelta)
Protected Member Functions
void _updateParticle (VerletParticle *particle, const Point2F &force, F32 timeDelta)
Protected Attributes
Point2F mCurrentDir
F32 mCurrentStrength
ForestItemData * mDataBlock
VerletParticle mParticles [2]
Point3F mPosition
F32 mScale
Detailed Description
This simple class holds the state of the accumulated wind effect for a single tree.
Constructor & Destructor Documentation
ForestWindAccumulator::ForestWindAccumulator (const TreePlacementInfo & info)
ForestWindAccumulator::~ForestWindAccumulator ()
Member Function Documentation
void ForestWindAccumulator::_updateParticle (VerletParticle * particle, const Point2F & force, F32 timeDelta) protected
void ForestWindAccumulator::applyImpulse (const VectorF & impulse)
Referenced by getPosition().
VectorF ForestWindAccumulator::getDirection () const inline
References Point2F::x, and Point2F::y.
Point3F ForestWindAccumulator::getPosition () const inline
References applyImpulse(), and mPosition.
F32 ForestWindAccumulator::getStrength () const inline
References mCurrentStrength.
void ForestWindAccumulator::presimulate (const VectorF & windVector, U32 ticks)
void ForestWindAccumulator::setDirection (const VectorF & dir) inline
References Point2F::set(), Point3F::x, and Point3F::y.
void ForestWindAccumulator::setPosition (const Point3F & pos) inline
void ForestWindAccumulator::setStrength (F32 strength) inline
void ForestWindAccumulator::updateWind (const VectorF & windVector, F32 timeDelta)
Member Data Documentation
Point2F ForestWindAccumulator::mCurrentDir protected
F32 ForestWindAccumulator::mCurrentStrength protected
Referenced by getStrength().
ForestItemData* ForestWindAccumulator::mDataBlock protected
VerletParticle ForestWindAccumulator::mParticles[2] protected
Point3F ForestWindAccumulator::mPosition protected
Referenced by getPosition().
F32 ForestWindAccumulator::mScale protected
Copyright © GarageGames, LLC. All Rights Reserved.