MacCursorController Class Reference
Main Modules Class List Namespace List Online
MacCursorController Class Reference
#include <windowManager/mac/macCursorController.h>
Public Member Functions
MacCursorController (MacWindow *owner)
virtual void getCursorPosition (Point2I &point)
virtual S32 getDoubleClickHeight ()
virtual U32 getDoubleClickTime ()
virtual S32 getDoubleClickWidth ()
virtual bool isCursorVisible ()
virtual void setCursorPosition (S32 x, S32 y)
virtual void setCursorShape (U32 cursorID)
virtual void setCursorShape (const UTF8 *fileName, bool reload)
virtual void setCursorVisible (bool visible)
Public Member Functions inherited from PlatformCursorController
PlatformCursorController (PlatformWindow *owner)
virtual ~PlatformCursorController ()
virtual void popCursor ()
virtual void pushCursor (S32 cursorID)
virtual void pushCursor (const UTF8 *fileName)
virtual void refreshCursor ()
virtual void setCursorShape (const Cursor_Shape &shape, bool reload)
Additional Inherited Members
Public Types inherited from PlatformCursorController
enum {
curArrow = 0,
curWait,
curPlus,
curResizeVert,
curResizeHorz,
curResizeAll,
curIBeam,
curResizeNESW,
curResizeNWSE,
curHand
}
Protected Attributes inherited from PlatformCursorController
Vector< Cursor_Shape > mCursors
PlatformWindow * mOwner
The PlatformWindow that owns this Cursor Controller.
Constructor & Destructor Documentation
MacCursorController::MacCursorController (MacWindow * owner) inline
References PlatformCursorController::curArrow, getCursorPosition(), getDoubleClickHeight(), getDoubleClickTime(), getDoubleClickWidth(), isCursorVisible(), PlatformCursorController::pushCursor(), setCursorPosition(), setCursorShape(), and setCursorVisible().
Member Function Documentation
virtual void MacCursorController::getCursorPosition (Point2I & point) virtual
Implements PlatformCursorController.
Referenced by MacCursorController().
virtual S32 MacCursorController::getDoubleClickHeight () virtual
Implements PlatformCursorController.
Referenced by MacCursorController().
virtual U32 MacCursorController::getDoubleClickTime () virtual
Implements PlatformCursorController.
Referenced by MacCursorController().
virtual S32 MacCursorController::getDoubleClickWidth () virtual
Implements PlatformCursorController.
Referenced by MacCursorController().
virtual bool MacCursorController::isCursorVisible () virtual
Implements PlatformCursorController.
Referenced by MacCursorController().
virtual void MacCursorController::setCursorPosition (S32 x, S32 y) virtual
Implements PlatformCursorController.
Referenced by MacCursorController().
virtual void MacCursorController::setCursorShape (U32 cursorID) virtual
Implements PlatformCursorController.
Referenced by MacCursorController().
virtual void MacCursorController::setCursorShape (const UTF8 * fileName, bool reload) virtual
Implements PlatformCursorController.
virtual void MacCursorController::setCursorVisible (bool visible) virtual
Implements PlatformCursorController.
Referenced by MacCursorController().
Copyright © GarageGames, LLC. All Rights Reserved.