CameraSpline Class Reference
Main Modules Class List Namespace List Online
CameraSpline Class Reference
#include <T3D/cameraSpline.h>
Classes
struct Knot
Public Member Functions
CameraSpline ()
~CameraSpline ()
F32 advanceDist (F32 t, F32 meters)
F32 advanceTime (F32 t, S32 delta_ms)
Knot * back ()
Knot * front ()
F32 getDistance (F32 t)
Knot * getKnot (S32 i)
F32 getTime (F32 d)
bool isEmpty ()
Knot * next (Knot *k)
Knot * prev (Knot *k)
void push_back (Knot *w)
void push_front (Knot *w)
Knot * remove (Knot *w)
void removeAll ()
void renderTimeMap ()
S32 size ()
void value (F32 t, Knot *result, bool skip_rotation=false)
Constructor & Destructor Documentation
CameraSpline::CameraSpline ()
CameraSpline::~CameraSpline ()
Member Function Documentation
F32 CameraSpline::advanceDist (F32 t, F32 meters)
Referenced by prev().
F32 CameraSpline::advanceTime (F32 t, S32 delta_ms)
Referenced by prev().
Knot* CameraSpline::back () inline
References push_back().
Knot* CameraSpline::front () inline
F32 CameraSpline::getDistance (F32 t)
Referenced by prev().
Knot* CameraSpline::getKnot (S32 i)
Referenced by push_front().
F32 CameraSpline::getTime (F32 d)
Referenced by prev().
bool CameraSpline::isEmpty (void) inline
Knot* CameraSpline::next (Knot * k) inline
References CameraSpline::Knot::next.
Knot* CameraSpline::prev (Knot * k) inline
References advanceDist(), advanceTime(), getDistance(), getTime(), CameraSpline::Knot::mDistance, CameraSpline::Knot::prev, renderTimeMap(), and value().
void CameraSpline::push_back (Knot * w)
Referenced by back(), and push_front().
void CameraSpline::push_front (Knot * w) inline
References getKnot(), and push_back().
Knot* CameraSpline::remove (Knot * w)
void CameraSpline::removeAll ()
Referenced by size().
void CameraSpline::renderTimeMap ()
Referenced by prev().
S32 CameraSpline::size () inline
References removeAll().
void CameraSpline::value (F32 t, Knot * result, bool skip_rotation = false)
Referenced by prev().
Copyright © GarageGames, LLC. All Rights Reserved.