ShadowMapPass Class Reference
Main Modules Class List Namespace List Online
ShadowMapPass Class Reference
ShadowMapPass, this is plugged into the SceneManager to generate ShadowMaps for the scene.
#include <lighting/shadowMap/shadowMapPass.h>
Public Member Functions
ShadowMapPass ()
ShadowMapPass (LightManager *LightManager, ShadowMapManager *ShadowManager)
virtual ~ShadowMapPass ()
virtual bool geometryOnly () const
virtual const String & getPassType () const
Return the type of pass this is.
virtual F32 getSortValue () const
Return our sort value. (Go first in order to have shadow maps available for RIT_Objects)
void render (SceneManager *sceneGraph, const SceneRenderState *diffuseState, U32 objectMask)
Called to render a scene.
Static Public Attributes
static const String PassTypeName
static bool smDisableShadows
Used to for debugging performance by disabling shadow updates and rendering.
static bool smDisableShadowsEditor
static bool smDisableShadowsPref
static F32 smShadowsTeleportDist
distance moved per frame before forcing a shadow update
static F32 smShadowsTurnRate
angle turned per frame before forcing a shadow update
Detailed Description
ShadowMapPass, this is plugged into the SceneManager to generate ShadowMaps for the scene.
Constructor & Destructor Documentation
ShadowMapPass::ShadowMapPass () inline
References render(), and ~ShadowMapPass().
ShadowMapPass::ShadowMapPass (LightManager * LightManager, ShadowMapManager * ShadowManager)
virtual ShadowMapPass::~ShadowMapPass () virtual
Referenced by ShadowMapPass().
Member Function Documentation
virtual bool ShadowMapPass::geometryOnly () const inline virtual
virtual const String& ShadowMapPass::getPassType () const inline virtual
Return the type of pass this is.
References PassTypeName.
virtual F32 ShadowMapPass::getSortValue () const inline virtual
Return our sort value. (Go first in order to have shadow maps available for RIT_Objects)
void ShadowMapPass::render (SceneManager * sceneGraph, const SceneRenderState * diffuseState, U32 objectMask)
Called to render a scene.
Referenced by ShadowMapPass().
Member Data Documentation
const String ShadowMapPass::PassTypeName static
Referenced by getPassType().
bool ShadowMapPass::smDisableShadows static
Used to for debugging performance by disabling shadow updates and rendering.
bool ShadowMapPass::smDisableShadowsEditor static
bool ShadowMapPass::smDisableShadowsPref static
F32 ShadowMapPass::smShadowsTeleportDist static
distance moved per frame before forcing a shadow update
F32 ShadowMapPass::smShadowsTurnRate static
angle turned per frame before forcing a shadow update
Copyright © GarageGames, LLC. All Rights Reserved.