PlaneTransformer Class Reference
Main Modules Class List Namespace List Online
PlaneTransformer Class Reference
#include <math/mPlaneTransformer.h>
Public Member Functions
void set (const MatrixF &xform, const Point3F &scale)
void setIdentity ()
void transform (const PlaneF &plane, PlaneF &result)
Member Function Documentation
void PlaneTransformer::set (const MatrixF & xform, const Point3F & scale)
Referenced by PolyhedronBoxIntersector< Polyhedron >::_preprocess(), AbstractPolyList::setTransform(), and PolyhedronImpl< Base >::transform().
void PlaneTransformer::setIdentity ()
Referenced by AbstractPolyList::doConstruct().
void PlaneTransformer::transform (const PlaneF & plane, PlaneF & result)
Referenced by PolyhedronBoxIntersector< Polyhedron >::_preprocess(), and PolyhedronImpl< Base >::transform().
Copyright © GarageGames, LLC. All Rights Reserved.