Volume System
Main Modules Class List Namespace List Online
Volume System
Volume access.
Classes
class Torque::FS::Directory
Directory in a FileSystem.
class Torque::FS::File
File object in a FileSystem.
class Torque::FS::FileBase
Base class for all FileIO objects.
class Torque::FS::FileNode
Base class for objects in a FileSystem.
class Torque::FS::FileSystem
Collection of FileNode objects.
Functions
String Torque::PathToOS (String file)
Convert file/path name to use OS standard path separator.
String Torque::PathToPlatform (String file)
Convert file/path name to use platform standard path separator.
File System Access
Functions for mounting file systems and dealing with files and directories.
The kernel provides FileSystem mounting, the concept of a current working directory as well as relative paths.
bool Torque::FS::Mount (String root, FileSystemRef fs)
Mount file system.
bool Torque::FS::Mount (String root, const Path &path)
Mount file system redirect.
FileSystemRef Torque::FS::Unmount (String root)
Remove mounted file system.
FileSystemRef Torque::FS::GetFileSystem (const Path &file)
Find the the file system which owns the given file.
FileNodeRef Torque::FS::GetFileNode (const Path &path)
Find the file system node for the given file.
template<class T , class U >
bool Torque::FS::AddChangeNotification (const Path &path, T obj, U func)
Adds a file change notification callback.
template<class T , class U >
bool Torque::FS::RemoveChangeNotification (const Path &path, T obj, U func)
Removes an existing file change notification callback.
S32 Torque::FS::FindByPattern (const Path &inBasePath, const String &inFilePattern, bool inRecursive, Vector< String > &outList, bool multiMatch=false)
Find files matching a pattern starting in a given dir.
bool Torque::FS::SetCwd (const Path &file)
Set current working directory.
const Path & Torque::FS::GetCwd ()
Get the current working directory.
bool Torque::FS::Remove (const Path &file)
Remove (or delete) a file from the file system.
bool Torque::FS::Rename (const Path &from, const Path &to)
Rename a file or directory.
bool Torque::FS::GetFileAttributes (const Path &path, FileNode::Attributes *attr)
Get the file attributes.
FileRef Torque::FS::OpenFile (const Path &file, File::AccessMode mode)
Open a file.
DirectoryRef Torque::FS::OpenDirectory (const Path &file)
Open a directory.
FileRef Torque::FS::CreateFile (const Path &file)
Create a file.
DirectoryRef Torque::FS::CreateDirectory (const Path &file)
Create a directory.
bool Torque::FS::CreatePath (const Path &path)
Create all the directories in the path if they don't already exist.
bool Torque::FS::Unmount (FileSystemRef fs)
Remove mounted file system.
bool Torque::FS::MapFSPath (const String &inRoot, const Path &inPath, Path &outPath)
Map a real file system path to a virtual one based on a root.
bool Torque::FS::GetFSPath (const Path &inPath, Path &outPath)
Returns a true file system path without virtual mounts.
S32 Torque::FS::CompareModifiedTimes (const Path &p1, const Path &p2)
Compare modified times of p1 & p2.
bool Torque::FS::ReadFile (const Path &inPath, void *&outData, U32 &outSize, bool inNullTerminate=false)
Read in an entire file.
bool Torque::FS::IsReadOnly (const Path &path)
bool Torque::FS::IsDirectory (const Path &path)
bool Torque::FS::IsFile (const Path &path)
bool Torque::FS::VerifyWriteAccess (const Path &path)
String Torque::FS::MakeUniquePath (const char *path, const char *fileName, const char *ext)
This returns a unique file path from the components by appending numbers to the end of the file name if a file with the same name already exists.
void Torque::FS::StartFileChangeNotifications ()
void Torque::FS::StopFileChangeNotifications ()
S32 Torque::FS::GetNumMounts ()
String Torque::FS::GetMountRoot (S32 index)
String Torque::FS::GetMountPath (S32 index)
String Torque::FS::GetMountType (S32 index)
Detailed Description
Volume access.
Function Documentation
template<class T , class U > bool Torque::FS::AddChangeNotification (const Path & path, T obj, U func) inline
Adds a file change notification callback.
References Torque::FS::GetFileSystem().
S32 Torque::FS::CompareModifiedTimes (const Path & p1, const Path & p2)
Compare modified times of p1 & p2.
Returns
-1 if p1 < p2, 0 if p1 == p2, 1 if p1 > p2
Referenced by Torque::FS::RemoveChangeNotification().
DirectoryRef Torque::FS::CreateDirectory (const Path & file)
Create a directory.
The directory object is returned in a closed state.
Referenced by Torque::FS::RemoveChangeNotification().
FileRef Torque::FS::CreateFile (const Path & file)
Create a file.
The file object is returned in a closed state.
Referenced by Torque::FS::RemoveChangeNotification().
bool Torque::FS::CreatePath (const Path & path)
Create all the directories in the path if they don't already exist.
Referenced by Torque::FS::RemoveChangeNotification().
S32 Torque::FS::FindByPattern (const Path & inBasePath, const String & inFilePattern, bool inRecursive, Vector< String > & outList, bool multiMatch = false)
Find files matching a pattern starting in a given dir.
Parameters
inBasePath path to start in
inFilePattern the file pattern [it uses the FindMatch class]
inRecursive do we search recursively?
outList the list of files as Strings [Paths are more expensive to compute, so these may be converted on demand]
multiMatch match against multiple file patterns given in inFilePattern?
Returns
number of files which matched
Referenced by Torque::FS::RemoveChangeNotification().
const Path& Torque::FS::GetCwd ()
Get the current working directory.
Referenced by Torque::FS::RemoveChangeNotification().
bool Torque::FS::GetFileAttributes (const Path & path, FileNode::Attributes * attr)
Get the file attributes.
Returns
success
Referenced by Torque::FS::RemoveChangeNotification().
FileNodeRef Torque::FS::GetFileNode (const Path & path)
Find the file system node for the given file.
Returns
Null if the file doesn't exist
FileSystemRef Torque::FS::GetFileSystem (const Path & file)
Find the the file system which owns the given file.
Referenced by Torque::FS::AddChangeNotification(), and Torque::FS::RemoveChangeNotification().
bool Torque::FS::GetFSPath (const Path & inPath, Path & outPath)
Returns a true file system path without virtual mounts.
Parameters
inPath The path to convert.
outPath The resulting real file system path.
Referenced by Torque::FS::RemoveChangeNotification().
String Torque::FS::GetMountPath (S32 index)
Referenced by Torque::FS::RemoveChangeNotification().
String Torque::FS::GetMountRoot (S32 index)
Referenced by Torque::FS::RemoveChangeNotification().
String Torque::FS::GetMountType (S32 index)
Referenced by Torque::FS::RemoveChangeNotification().
S32 Torque::FS::GetNumMounts ()
Referenced by Torque::FS::RemoveChangeNotification().
bool Torque::FS::IsDirectory (const Path & path)
Referenced by Torque::FS::RemoveChangeNotification().
bool Torque::FS::IsFile (const Path & path)
Referenced by Torque::FS::RemoveChangeNotification().
bool Torque::FS::IsReadOnly (const Path & path)
Referenced by Torque::FS::RemoveChangeNotification().
String Torque::FS::MakeUniquePath (const char * path, const char * fileName, const char * ext)
This returns a unique file path from the components by appending numbers to the end of the file name if a file with the same name already exists.
Parameters
path The root and directory for the file.
fileName The file name without extension.
ext The dot-less extension.
Referenced by Torque::FS::RemoveChangeNotification().
bool Torque::FS::MapFSPath (const String & inRoot, const Path & inPath, Path & outPath)
Map a real file system path to a virtual one based on a root.
This is useful when we get a real path back from an OS file dialog for example. e.g. If we have a root "gumby" which points at "C:/foo/bar", MapFSPath("gumby", "C:/foo/bar/blat/picture.png", path); will map "C:/foo/bar/blat/picture.png" to "gumby:/blat/picture.png"
Parameters
inRoot The root to check
inPath The real file system path
outPath The resulting volume system path
Returns
Success or failure
Referenced by Torque::FS::RemoveChangeNotification().
bool Torque::FS::Mount (String root, FileSystemRef fs)
Mount file system.
bool Torque::FS::Mount (String root, const Path & path)
Mount file system redirect.
DirectoryRef Torque::FS::OpenDirectory (const Path & file)
Open a directory.
If the directory exists a directory object will be returned even if the open operation fails.
Returns
Null if the file does not exist
Referenced by Torque::FS::RemoveChangeNotification().
FileRef Torque::FS::OpenFile (const Path & file, File::AccessMode mode)
Open a file.
If the file exists a file object will be returned even if the open operation fails.
Returns
Null if the file does not exist
Referenced by Torque::FS::RemoveChangeNotification().
String Torque::PathToOS (String file)
Convert file/path name to use OS standard path separator.
Referenced by Torque::Path::getExtension().
String Torque::PathToPlatform (String file)
Convert file/path name to use platform standard path separator.
Referenced by Torque::Path::getExtension().
bool Torque::FS::ReadFile (const Path & inPath, void *& outData, U32 & outSize, bool inNullTerminate = false)
Read in an entire file.
Note
Caller is responsible for freeing memory
Parameters
inPath the file
outData the pointer to return the data
outSize the size of the data returned
inNullTerminate add an extra '\0' byte to the return buffer
Returns
successful read? If not, outData will be NULL and outSize will be 0
Referenced by Torque::FS::RemoveChangeNotification().
bool Torque::FS::Remove (const Path & file)
Remove (or delete) a file from the file system.
Referenced by Zip::ZipTempStream::close(), and Torque::FS::RemoveChangeNotification().
template<class T , class U > bool Torque::FS::RemoveChangeNotification (const Path & path, T obj, U func) inline
Removes an existing file change notification callback.
References Torque::FS::CompareModifiedTimes(), Torque::FS::CreateDirectory(), Torque::FS::CreateFile(), Torque::FS::CreatePath(), Torque::FS::FindByPattern(), Torque::FS::GetCwd(), Torque::FS::GetFileAttributes(), Torque::FS::GetFileSystem(), Torque::FS::GetFSPath(), Torque::FS::GetMountPath(), Torque::FS::GetMountRoot(), Torque::FS::GetMountType(), Torque::FS::GetNumMounts(), Torque::FS::IsDirectory(), Torque::FS::IsFile(), Torque::FS::IsReadOnly(), Torque::FS::MakeUniquePath(), Torque::FS::MapFSPath(), Torque::FS::OpenDirectory(), Torque::FS::OpenFile(), Torque::FS::ReadFile(), Torque::FS::Remove(), Torque::FS::Rename(), Torque::FS::SetCwd(), Torque::FS::StartFileChangeNotifications(), Torque::FS::StopFileChangeNotifications(), and Torque::FS::VerifyWriteAccess().
bool Torque::FS::Rename (const Path & from, const Path & to)
Rename a file or directory.
Referenced by Torque::FS::RemoveChangeNotification().
bool Torque::FS::SetCwd (const Path & file)
Set current working directory.
Referenced by Torque::FS::RemoveChangeNotification().
void Torque::FS::StartFileChangeNotifications ()
Referenced by Torque::FS::RemoveChangeNotification().
void Torque::FS::StopFileChangeNotifications ()
Referenced by Torque::FS::RemoveChangeNotification().
FileSystemRef Torque::FS::Unmount (String root)
Remove mounted file system.
The file system object associated with the given root is unmounted. Open files associated with this file system are unaffected.
Returns
The unmounted file system.
bool Torque::FS::Unmount (FileSystemRef fs)
Remove mounted file system.
Open files associated with this file system are unaffected.
Returns
true if the filesystem was successfully unmounted, false otherwise (most likely, the FS was not mounted)
bool Torque::FS::VerifyWriteAccess (const Path & path)
Referenced by Torque::FS::RemoveChangeNotification().
Copyright © GarageGames, LLC. All Rights Reserved.