TempAlloc< T > Struct Template Reference
Main Modules Class List Namespace List Online
TempAlloc< T > Struct Template Reference
#include <util/tempAlloc.h>
Public Member Functions
TempAlloc ()
TempAlloc (U32 size)
~TempAlloc ()
operator T * ()
Public Attributes
T * ptr
U32 size
Constructor & Destructor Documentation
template<typename T> TempAlloc< T >::TempAlloc () inline
Referenced by TempAlloc< T >::operator T *().
template<typename T> TempAlloc< T >::TempAlloc (U32 size) inline
References dMalloc, and T.
template<typename T> TempAlloc< T >::~TempAlloc () inline
References dFree().
Member Function Documentation
template<typename T> TempAlloc< T >::operator T * () inline
References TempAlloc< T >::ptr, and TempAlloc< T >::TempAlloc().
Member Data Documentation
template<typename T> T* TempAlloc< T >::ptr
Referenced by TempAlloc< T >::operator T *().
template<typename T> U32 TempAlloc< T >::size
Copyright © GarageGames, LLC. All Rights Reserved.