ServerInfo Struct Reference
Main Modules Class List Namespace List Online
ServerInfo Struct Reference
#include <app/net/serverQuery.h>
Public Types
enum StatusFlags {
Status_Dedicated = BIT(0),
Status_Passworded = BIT(1),
Status_Linux = BIT(2),
Status_Xenon = BIT(6),
Status_New = 0,
Status_Querying = BIT(28),
Status_Updating = BIT(29),
Status_Responded = BIT(30),
Status_TimedOut = BIT(31)
}
Public Member Functions
ServerInfo ()
~ServerInfo ()
bool hasResponded ()
bool isDedicated ()
bool isLinux ()
bool isNew ()
bool isPassworded ()
bool isQuerying ()
bool isTimedOut ()
bool isUpdating ()
bool isXenon ()
Public Attributes
NetAddress address
U32 cpuSpeed
char * gameType
char * infoString
bool isFavorite
U8 maxPlayers
char * missionName
char * missionType
char * name
U8 numBots
U8 numPlayers
U32 ping
BitSet32 status
char * statusString
U32 version
Member Enumeration Documentation
enum ServerInfo::StatusFlags
Enumerator
Status_Dedicated
Status_Passworded
Status_Linux
Status_Xenon
Status_New
Status_Querying
Status_Updating
Status_Responded
Status_TimedOut
Constructor & Destructor Documentation
ServerInfo::ServerInfo () inline
References Status_New, and ~ServerInfo().
ServerInfo::~ServerInfo ()
Referenced by ServerInfo().
Member Function Documentation
bool ServerInfo::hasResponded () inline
References Status_Responded, and BitSet32::test().
bool ServerInfo::isDedicated () inline
References Status_Dedicated, and BitSet32::test().
bool ServerInfo::isLinux () inline
References Status_Linux, and BitSet32::test().
bool ServerInfo::isNew () inline
References Status_New.
bool ServerInfo::isPassworded () inline
References Status_Passworded, and BitSet32::test().
bool ServerInfo::isQuerying () inline
References Status_Querying, and BitSet32::test().
bool ServerInfo::isTimedOut () inline
References Status_TimedOut, and BitSet32::test().
bool ServerInfo::isUpdating () inline
References Status_Updating, and BitSet32::test().
bool ServerInfo::isXenon () inline
References gameType, maxPlayers, missionType, Status_Xenon, and BitSet32::test().
Member Data Documentation
NetAddress ServerInfo::address
U32 ServerInfo::cpuSpeed
char* ServerInfo::gameType
Referenced by isXenon().
char* ServerInfo::infoString
bool ServerInfo::isFavorite
U8 ServerInfo::maxPlayers
Referenced by isXenon().
char* ServerInfo::missionName
char* ServerInfo::missionType
Referenced by isXenon().
char* ServerInfo::name
U8 ServerInfo::numBots
U8 ServerInfo::numPlayers
U32 ServerInfo::ping
BitSet32 ServerInfo::status
char* ServerInfo::statusString
U32 ServerInfo::version
Copyright © GarageGames, LLC. All Rights Reserved.