PhysicsState Struct Reference
Main Modules Class List Namespace List Online
PhysicsState Struct Reference
Helper structure which defines the state of a single physics body.
#include <T3D/physics/physicsCommon.h>
Public Member Functions
PhysicsState ()
Constructor.
MatrixF getTransform () const
Helper builds the transform from the state.
PhysicsState & interpolate (const PhysicsState &a, const PhysicsState &b, F32 t)
Interpolates between two physics states leaving the result in this physics state.
Public Attributes
Point3F position
The primary physics state.
Point3F momentum
The momentum in kilogram meters per second.
QuatF orientation
The orientation of the body.
Point3F angularMomentum
The angular momentum.
bool sleeping
Is true if the shape is asleep.
Point3F linVelocity
The secondary physics state derived from the primary state.
Point3F angVelocity
Detailed Description
Helper structure which defines the state of a single physics body.
Constructor & Destructor Documentation
PhysicsState::PhysicsState () inline
Constructor.
Member Function Documentation
MatrixF PhysicsState::getTransform () const inline
Helper builds the transform from the state.
References QuatF::setMatrix(), and MatrixF::setPosition().
PhysicsState& PhysicsState::interpolate (const PhysicsState & a, const PhysicsState & b, F32 t) inline
Interpolates between two physics states leaving the result in this physics state.
References angularMomentum, QuatF::interpolate(), momentum, orientation, and position.
Member Data Documentation
Point3F PhysicsState::angularMomentum
The angular momentum.
Referenced by interpolate().
Point3F PhysicsState::angVelocity
Point3F PhysicsState::linVelocity
The secondary physics state derived from the primary state.
The linear velocity derived from the momentum.
Referenced by RigidBodyComponent::getVelocity(), and PhysicsShape::getVelocity().
Point3F PhysicsState::momentum
The momentum in kilogram meters per second.
Referenced by interpolate().
QuatF PhysicsState::orientation
The orientation of the body.
Referenced by interpolate().
Point3F PhysicsState::position
The primary physics state.
The position of the body.
Referenced by interpolate().
bool PhysicsState::sleeping
Is true if the shape is asleep.
Copyright © GarageGames, LLC. All Rights Reserved.