ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS > Struct Template Reference
Main Modules Class List Namespace List Online
ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS > Struct Template Reference
Fast, lock-free priority queue implementation for concurrent access.
#include <platform/threads/threadSafePriorityQueue.h>
Classes
struct Node
A queue node.
Public Types
enum { MAX_LEVEL_CONST = MAX_LEVEL }
typedef K KeyType
typedef T ValueType
Public Member Functions
ThreadSafePriorityQueue ()
Construct an empty queue.
void insert (KeyType priority, const T &value)
Insert the given value into the queue at the place determined by the given priority.
bool isEmpty ()
Return true if the queue does not currently contain an item.
bool takeNext (T &outValue, KeyType upToPriority=(SORT_MIN_TO_MAX?TypeTraits< KeyType >::MAX:TypeTraits< KeyType >::MIN))
Take the item with the highest priority from the queue.
Protected Types
typedef ThreadSafeRef< Node > NodePtr
Protected Member Functions
void helpDelete ()
void insert (KeyType priority, const T &value, NodePtr &outResult)
void readNext (NodePtr &refPrev, NodePtr &refNext, U32 level)
Update the given references to the next non-deleted node at the given level.
void scan (NodePtr &refPrev, NodePtr &refNext, U32 level, KeyType priority)
Scan for the position at which to insert a node of the given priority.
void scanFromHead (NodePtr &refPrev, NodePtr &refNext, U32 level, KeyType priority)
Protected Attributes
NodePtr mHead
Artificial head node.
NodePtr mTail
Artificial tail node.
Detailed Description
template<typename T, typename K = F32, bool SORT_MIN_TO_MAX = false, U32 MAX_LEVEL = 4, U32 PROBABILISTIC_BIAS = 50>
struct ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >
Fast, lock-free priority queue implementation for concurrent access.
Equal priorities are allowed and are placed before existing items of identical priority in the queue.
Based on (but with significant deviations from) "Fast and Lock-Free Concurrent Priority Queues for Multi-Thread Systems" by Hakan Sundell and Philippas Tsigas. Parts of the skiplist code is based on work by William Pugh.
Parameters
T The item value type. Must have a default constructor.
K The priority key type. Must be comparable, have a default constructor, and be a valid template parameter to TypeTraits.
SORT_MIN_TO_MAX If true, the queue sorts from minimum to maximum priority or the reverse if false.
MAX_LEVEL The number of levels a node can have at most.
PROBABILISTIC_BIAS The probabilistic level distribution factor for the skiplist. Multiplied by 100 and turned into int to conform to restrictions on non-type template parameters.
See also
TypeTraits
Member Typedef Documentation
template<typename T, typename K = F32, bool SORT_MIN_TO_MAX = false, U32 MAX_LEVEL = 4, U32 PROBABILISTIC_BIAS = 50> typedef K ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::KeyType
template<typename T, typename K = F32, bool SORT_MIN_TO_MAX = false, U32 MAX_LEVEL = 4, U32 PROBABILISTIC_BIAS = 50> typedef ThreadSafeRef< Node > ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::NodePtr protected
template<typename T, typename K = F32, bool SORT_MIN_TO_MAX = false, U32 MAX_LEVEL = 4, U32 PROBABILISTIC_BIAS = 50> typedef T ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::ValueType
Member Enumeration Documentation
template<typename T, typename K = F32, bool SORT_MIN_TO_MAX = false, U32 MAX_LEVEL = 4, U32 PROBABILISTIC_BIAS = 50> anonymous enum
Enumerator
MAX_LEVEL_CONST
Constructor & Destructor Documentation
template<typename T , typename K , bool SORT_MIN_TO_MAX, U32 MAX_LEVEL, U32 PROBABILISTIC_BIAS> ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::ThreadSafePriorityQueue ()
Construct an empty queue.
Internally, this creates a head node with maximal priority and a tail node with minimal priority, both at maximum level.
References ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::mHead, ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::mTail, ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::Node(), and ThreadSafeRef< Node >::unsafeWrite().
Member Function Documentation
template<typename T , typename K , bool SORT_MIN_TO_MAX, U32 MAX_LEVEL, U32 PROBABILISTIC_BIAS> void ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::helpDelete () protected
References ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::mHead, ThreadSafeRef< T >::setTag(), ThreadSafeRef< Node >::TAG_Unset, and ThreadSafeRef< T >::trySetFromTo().
Referenced by ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::scanFromHead(), and ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::takeNext().
template<typename T, typename K , bool SORT_MIN_TO_MAX, U32 MAX_LEVEL, U32 PROBABILISTIC_BIAS> void ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::insert (KeyType priority, const T & value) inline
Insert the given value into the queue at the place determined by the given priority.
Referenced by ThreadSafePriorityQueueWithUpdate< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::insert().
template<typename T, typename K , bool SORT_MIN_TO_MAX, U32 MAX_LEVEL, U32 PROBABILISTIC_BIAS> void ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::insert (KeyType priority, const T & value, NodePtr & outResult) protected
References ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::Node(), ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::scanFromHead(), ThreadSafeRef< Node >::TAG_FailIfSet, ThreadSafeRef< T >::trySetFromTo(), and ThreadSafeRef< Node >::unsafeWrite().
template<typename T , typename K , bool SORT_MIN_TO_MAX, U32 MAX_LEVEL, U32 PROBABILISTIC_BIAS> bool ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::isEmpty (void)
Return true if the queue does not currently contain an item.
References ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::mHead, and ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::mTail.
template<typename T , typename K , bool SORT_MIN_TO_MAX, U32 MAX_LEVEL, U32 PROBABILISTIC_BIAS> void ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::readNext (NodePtr & refPrev, NodePtr & refNext, U32 level) inline protected
Update the given references to the next non-deleted node at the given level.
refPrev will be updated to reference the immediate predecessor of the next node returned. Note that this can be a node in deleted state.
Parameters
refPrev Reference to a node of which the successor node should be returned. Updated to immediate predecessor of refNext on return.
refNext Reference to update to refer to next non-deleted node on the given level.
level Skiplist level to operate on.
References ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::mTail.
Referenced by ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::scan(), and ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::takeNext().
template<typename T , typename K , bool SORT_MIN_TO_MAX, U32 MAX_LEVEL, U32 PROBABILISTIC_BIAS> void ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::scan (NodePtr & refPrev, NodePtr & refNext, U32 level, KeyType priority) protected
Scan for the position at which to insert a node of the given priority.
Upon return, the position between refPrev and refNext is the one to insert at.
Parameters
refPrev position at which to start scanning; updated to match insert position.
refNext
References ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::mTail, and ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::readNext().
Referenced by ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::scanFromHead().
template<typename T , typename K , bool SORT_MIN_TO_MAX, U32 MAX_LEVEL, U32 PROBABILISTIC_BIAS> void ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::scanFromHead (NodePtr & refPrev, NodePtr & refNext, U32 level, KeyType priority) protected
References ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::helpDelete(), ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::mHead, and ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::scan().
Referenced by ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::insert().
template<typename T, typename K , bool SORT_MIN_TO_MAX, U32 MAX_LEVEL, U32 PROBABILISTIC_BIAS> bool ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::takeNext (T & outValue, KeyType upToPriority = (SORT_MIN_TO_MAX ? TypeTraits< KeyType >::MAX : TypeTraits< KeyType >::MIN))
Take the item with the highest priority from the queue.
Parameters
outValue Reference to where the resulting value should be stored.
upToPriority Priority limit (inclusive) up to which items are taken from the queue.
Returns
true if there was a matching item in the queue.
References ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::Node::getPriority(), ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::helpDelete(), ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::mHead, ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::mTail, and ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::readNext().
Referenced by ThreadSafePriorityQueueWithUpdate< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::takeNext().
Member Data Documentation
template<typename T, typename K = F32, bool SORT_MIN_TO_MAX = false, U32 MAX_LEVEL = 4, U32 PROBABILISTIC_BIAS = 50> NodePtr ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::mHead protected
Artificial head node.
Referenced by ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::helpDelete(), ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::isEmpty(), ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::scanFromHead(), ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::takeNext(), and ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::ThreadSafePriorityQueue().
template<typename T, typename K = F32, bool SORT_MIN_TO_MAX = false, U32 MAX_LEVEL = 4, U32 PROBABILISTIC_BIAS = 50> NodePtr ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::mTail protected
Artificial tail node.
Referenced by ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::isEmpty(), ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::readNext(), ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::scan(), ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::takeNext(), and ThreadSafePriorityQueue< T, K, SORT_MIN_TO_MAX, MAX_LEVEL, PROBABILISTIC_BIAS >::ThreadSafePriorityQueue().
Copyright © GarageGames, LLC. All Rights Reserved.