StringStack Struct Reference
Main Modules Class List Namespace List Online
StringStack Struct Reference
Core stack for interpreter operations.
#include <console/stringStack.h>
Public Types
enum {
MaxStackDepth = 1024,
MaxArgs = 20,
ReturnBufferSpace = 512
}
Public Member Functions
StringStack ()
~StringStack ()
void advance ()
Advance the start stack, placing a zero length string on the top.
void advanceChar (char c)
Advance the start stack, placing a single character, null-terminated strong on the top.
void clearFrames ()
void clearFunctionOffset ()
Clear the function offset.
U32 compare ()
Compare 1st and 2nd items on stack, consuming them in the process, and returning true if they matched, false if they didn't.
char * getArgBuffer (U32 size)
Return a buffer we can use for arguments.
void getArgcArgv (StringTableEntry name, U32 *argc, const char ***in_argv, bool popStackFrame=false)
Get the arguments for a function call from the stack.
F64 getFloatValue ()
Get a float representation of the top of the stack.
U32 getIntValue ()
Get an integer representation of the top of the stack.
const char * getPreviousStringValue ()
StringStackPtr getPreviousStringValuePtr ()
char * getReturnBuffer (U32 size)
Return a temporary buffer we can use to return data.
const char * getStringValue ()
Get a string representation of the top of the stack.
StringStackPtr getStringValuePtr ()
StringTableEntry getSTValue ()
Get the top of the stack, as a StringTableEntry.
void popFrame ()
void push ()
Push the stack, placing a zero-length string on the top.
void pushFrame ()
void rewind ()
Pop the start stack.
void rewindTerminate ()
void setFloatValue (F64 v)
Set the top of the stack to be a float value.
void setIntValue (U32 i)
Set the top of the stack to be an integer value.
void setLen (U32 newlen)
void setStringValue (const char *s)
Set a string value on the top of the stack.
void validateArgBufferSize (U32 size)
void validateBufferSize (U32 size)
Public Attributes
char * mArgBuffer
U32 mArgBufferSize
U32 mArgc
const char * mArgV [MaxArgs]
char * mBuffer
U32 mBufferSize
U32 mFrameOffsets [MaxStackDepth]
U32 mFunctionOffset
U32 mLen
U32 mNumFrames
U32 mStart
U32 mStartOffsets [MaxStackDepth]
U32 mStartStackSize
Detailed Description
Core stack for interpreter operations.
This class provides some powerful semantics for working with strings, and is used heavily by the console interpreter.
Member Enumeration Documentation
anonymous enum
Enumerator
MaxStackDepth
MaxArgs
ReturnBufferSpace
Constructor & Destructor Documentation
StringStack::StringStack () inline
References dMemset().
StringStack::~StringStack () inline
References dFree().
Member Function Documentation
void StringStack::advance () inline
Advance the start stack, placing a zero length string on the top.
Note
You should use StringStack::push, not this, if you want to properly push the stack.
void StringStack::advanceChar (char c) inline
Advance the start stack, placing a single character, null-terminated strong on the top.
Note
You should use StringStack::push, not this, if you want to properly push the stack.
void StringStack::clearFrames () inline
void StringStack::clearFunctionOffset () inline
Clear the function offset.
U32 StringStack::compare () inline
Compare 1st and 2nd items on stack, consuming them in the process, and returning true if they matched, false if they didn't.
char* StringStack::getArgBuffer (U32 size) inline
Return a buffer we can use for arguments.
This updates the function offset.
References Con::isMainThread().
void StringStack::getArgcArgv (StringTableEntry name, U32 * argc, const char *** in_argv, bool popStackFrame = false)
Get the arguments for a function call from the stack.
F64 StringStack::getFloatValue () inline
Get a float representation of the top of the stack.
References dAtof().
U32 StringStack::getIntValue () inline
Get an integer representation of the top of the stack.
References dAtoi().
const char* StringStack::getPreviousStringValue () inline
StringStackPtr StringStack::getPreviousStringValuePtr () inline
char* StringStack::getReturnBuffer (U32 size) inline
Return a temporary buffer we can use to return data.
References Con::isMainThread().
const char* StringStack::getStringValue () inline
Get a string representation of the top of the stack.
Note
This returns a pointer to the actual top of the stack, be careful!
StringStackPtr StringStack::getStringValuePtr () inline
StringTableEntry StringStack::getSTValue () inline
Get the top of the stack, as a StringTableEntry.
Note
Don't free this memory!
void StringStack::popFrame () inline
void StringStack::push () inline
Push the stack, placing a zero-length string on the top.
void StringStack::pushFrame () inline
void StringStack::rewind () inline
Pop the start stack.
void StringStack::rewindTerminate () inline
void StringStack::setFloatValue (F64 v) inline
Set the top of the stack to be a float value.
void StringStack::setIntValue (U32 i) inline
Set the top of the stack to be an integer value.
void StringStack::setLen (U32 newlen) inline
void StringStack::setStringValue (const char * s) inline
Set a string value on the top of the stack.
void StringStack::validateArgBufferSize (U32 size) inline
References dRealloc.
void StringStack::validateBufferSize (U32 size) inline
References dRealloc.
Member Data Documentation
char* StringStack::mArgBuffer
U32 StringStack::mArgBufferSize
U32 StringStack::mArgc
const char* StringStack::mArgV[MaxArgs]
char* StringStack::mBuffer
Referenced by StringStackPtrRef::getPtr().
U32 StringStack::mBufferSize
U32 StringStack::mFrameOffsets[MaxStackDepth]
U32 StringStack::mFunctionOffset
U32 StringStack::mLen
U32 StringStack::mNumFrames
U32 StringStack::mStart
U32 StringStack::mStartOffsets[MaxStackDepth]
U32 StringStack::mStartStackSize
Copyright © GarageGames, LLC. All Rights Reserved.